### ISSUE TITLE
피벗/바차트 출력 문제

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1056]
## 버그 설명 ##
바차트 출력시 레전드 수가 많아지면 출력이 정상적으로 안됨, 현재는 스택차트로 나타남
레전드 수를 줄이도록 범례기준을 변경하면 정상 출력됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
SSM계정에서 화면에 보는 형태로 피벗을 실행하면됨

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/47124611-cb83df00-d2b9-11e8-8466-36abb9a7f9d1.png)

**Comment by veldise** [comment]
오래된 이슈 닫습니다.
