### ISSUE TITLE
[데이터추가] SYSLOG 데이터를 IRIS 로컬테이블로 로딩하는데 unicode decode  관련 에러납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1074]
## 버그 설명 ##
데이터추가 메뉴에서 SYSLOG 데이터를 IRIS 로컬테이블로 로딩하는데 unicode decode  관련 에러납니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. DB브라우저에서 SYSLOG데이터를 로컬PC로 저장합니다.  select SQL은 아래와 같습니다. 
 /*+ LOCATION ( PARTITION >= '20180701000000' AND PARTITION < '20180702000000' ) */ 
SELECT 
	DATETIME as CDATE, HOST, FACILITY, PRIORITY, LEVEL, LEVEL_INT,  PROGRAM, 'no msg' as MSG, 'pk' as PAR_KEY_DUMMY
FROM 
	EVA.SYSLOG

2. 데이터추가 메뉴에서   열구분자로 쉼표, 기존 테이블 myiris 계정의 테이블 SYSLOG_1000_MOD 테이블 선택
3. 제출

## 스크린샷 ##
MYIRIS.SYSLOG_1000_MOD 테이블과 컬럼
<img width="222" alt="2018-10-24 2 25 56" src="https://user-images.githubusercontent.com/5126497/47408256-8bc96580-d799-11e8-9381-9aad8df50c7d.png">

<img width="677" alt="2018-10-24 2 33 24" src="https://user-images.githubusercontent.com/5126497/47408313-cc28e380-d799-11e8-8837-9fb847a642a9.png">

데이터 샘플
<img width="1008" alt="2018-10-24 2 47 46" src="https://user-images.githubusercontent.com/5126497/47408987-4f4b3900-d79c-11e8-9c92-96e85d7260a1.png">

데이터 추가 설정
<img width="1130" alt="2018-10-24 2 48 10" src="https://user-images.githubusercontent.com/5126497/47408937-2165f480-d79c-11e8-97bf-886df633f941.png">

데이터 추가 메뉴에서 로딩 에러내용
<img width="1011" alt="2018-10-24 2 48 46" src="https://user-images.githubusercontent.com/5126497/47408930-19a65000-d79c-11e8-903b-a2fc77c6d210.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sonchanseung** [comment]
네 알겠습니다. 최종적으로 확인한 이슈이고, 정혜정 선임님께 확인 후 이슈 닫도록 하겠습니다.
