### ISSUE TITLE
[이상탐지] 결측치(빠진 시간대)를 0 으로 채운 경우, 그래프에 적용이 되지 않고, UCL,LCL계산도 틀립니다

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1107]
## 버그 설명 ##
syslog 데이터모델이고, 결측치를 0 으로 채운 경우, 즉 빠진 시간대의 값을 0 으로 채워서 AD 를 진행하는 경우 
0으로 채운 값으로 챠트에 그려지지 않고, UCL, LCL값도 맞지 않습니다.

참고로 0 으로 채우지 않고 계산해도 결과에서 나온 UCL/LCL이 나오지 않아서 어떻게 계산되는 지 모르겠습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. myiris 계정의 시각화 모델 search_for_new_ad 를 실행
2. 검색 결과가 나오면 이상탐지로 이동
3. 설정(스크린샷 참조)

## 예상한 행동 ##
platform2 서버는 08:20, 09:30 값이 0 으로  그려지고,  참조기간동안의 데이터도 결측치를 0 으로 채운 값으로 평균과 표준편차가 구해져야 합니다.
platform2 의 10분 데이터 벡터 
11/02   (2, 1, 0, 1, 1, 1,      2, 1, 1, 0)

4주 참조데이터 벡터
10/26    3, 0, 1, 1, 0, 1,      3, 0, 1, 1
10/19    2, 1, 1, 0, 1, 1,      2, 1, 1, 0
10/12    3, 0, 1, 1, 0, 1,      3, 0, 1, 1
10/05    2, 1, 1, 0, 1, 1,      2, 2, 1, 0

입니다.

8시 UCL/LCL 은 3.502173 , -1.502173  로 나옵니다.
` 
> a <- c(3, 0, 1, 1, 0, 1,     2, 1, 1, 0, 1, 1,    3, 0, 1, 1, 0, 1,     2, 1, 1, 0, 1, 1)
> mean(a) + 3*sd(a)
[1] 3.502173
> mean(a) - 3*sd(a)
[1] -1.502173
`

## 스크린샷 ##
* 검색 데이터 조건
<img width="1081" alt="2018-11-07 3 06 03" src="https://user-images.githubusercontent.com/5126497/48113555-b12c9800-e29e-11e8-9e1a-19173f6e0300.png">

* 이상탐지 설정
<img width="484" alt="2018-11-07 3 07 44" src="https://user-images.githubusercontent.com/5126497/48114035-c7d3ee80-e2a0-11e8-81e9-8c1152609608.png">

* platform2 서버의 결과
<img width="1057" alt="2018-11-07 3 08 59" src="https://user-images.githubusercontent.com/5126497/48114192-69f3d680-e2a1-11e8-97cc-443ed01874a1.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

**Comment by namjals** [comment]
@veldise 
최영철 선임님, 이슈를 재현하면 아래 그림과 같이 그래프가 그려집니다.
3개의 색깔별로 꺽은선 그래프가 나와야 할거 같은데, 우측의 response의 데이터대로 그려지는게 좌측의 그래프가 맞는지 확인 요청드립니다.
![image](https://user-images.githubusercontent.com/22319132/62117772-7f110980-b2f7-11e9-8d63-87d78a60d945.png)

**Comment by veldise** [comment]
@namjals 
꺾은선 그래프는 "키 컬럼"을 지정하지 않고 수행하거나,
히트맵 차트에서 마우스우클릭 > 메뉴 > 카드 분리를 수행해야 그려집니다.

**Comment by pjh0347** [comment]
현재 시점에 본 이슈와 직접 또는 간접적으로 아래와 같은 문제점이 있어 이번달 중으로 개선 완료할 예정입니다.

- `결측치` 처리 로직 보완
  - 처리 대상 데이터
    - 기존 : 비교 기간의 데이터만 결측치 처리
    - 변경 : 참조/비교 기간의 양쪽 데이터에 결측치 처리
  - `NULL` 을 선택한 경우
    - 기존 : 집계 결과에 아무 처리를 하지 않음.
    - 변경 : 집계 결과에 누락된 시간대 및 키를 추가하고 값을 null 로 채움
- `요일 분류` 처리 로직 보완
  - 기존 : 참조/비교 데이터를 `키` 와 `시간대` 기준으로 비교
  - 변경 : 참조/비교 데이터를 `키`, `요일` 그리고 `시간대` 기준으로 비교
- IQR 모델 수식 개선 (본 이슈는 SPC 모델 관련 이슈 이지만 IQR 에 UCL 계산식 오류도 함께 개선)
  - 기존 : `ucl = Q1 + 1.5 * IQR`
  - 변경 : `ucl = Q3 + 1.5 * IQR`

**Comment by pjh0347** [comment]
운영 서버에 개선 적용 완료하였습니다.

![image](https://user-images.githubusercontent.com/5305236/63913818-72094680-ca6c-11e9-8f42-61befa4daae0.png)
