### ISSUE TITLE
[R-studio] 데이터 탐색시, 명령어 혹은 함수의 도움말이 나오지 않습니다.

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1131]
## 버그 설명 ##
R에서는 일반적으로, 
패키지의 명령어, 혹은 함수의 사용법이 생각나지 않을경우, 
도움말을 부르는 경우가 흔히 존재하는데
iris 의 Rstudio 에서 사용하려고 하니 오류라고 나옵니다

## 재현하는 방법 ##
동작을 재현하는 방법 :

<img width="854" alt="2018-11-15 1 27 03" src="https://user-images.githubusercontent.com/36151180/48530317-8a8fe200-e8da-11e8-8ed6-087d52751bec.png">

## 예상한 행동 ##
일반적인 R에서, 같은내용을 실행했을시, 도움말이 떠야합니다.

## 스크린샷 ##
아래와 같이 도움말이 뜨기를 원합니다. 
<img width="1675" alt="2018-11-15 1 25 31" src="https://user-images.githubusercontent.com/36151180/48530351-b14e1880-e8da-11e8-8796-5b6ebd3e7dec.png">

**Comment by anhm** [comment]
KEYWORDS.db 파일을 docker 내에 포함하여 해결 완료
