### ISSUE TITLE
anomalies 검색 실행시 'DataFrame' object has no attribute 'value' 에러

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1147]
## 버그 설명 ##
anomalies 검색 실행시 'DataFrame' object has no attribute 'value' 에러가 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 180 서버에서 root로 접속
2. 검색페이지에서 아래와 같은 조건으로 검색
```
데이터 모델: syslog
시간: 최근 1분
검색어: * | anomalies DATETIME LEVEL_INT alg=agile
```

## 예상한 행동 ##
search 와 figures 에서 동일한 에러가 발생합니다.

## 스크린샷 ##
검색후 에러 표시
![image](https://user-images.githubusercontent.com/5515493/48926600-f5f93580-ef12-11e8-97ef-5108bde7fa48.png)
search 에러
![image](https://user-images.githubusercontent.com/5515493/48926679-6c963300-ef13-11e8-8973-f6accec50aa0.png)
figures 에러
![image](https://user-images.githubusercontent.com/5515493/48926686-73bd4100-ef13-11e8-9f56-b95a0c7dacf3.png)

**Comment by seoryjj** [comment]
수정 완료하여 116 서버에 적용했습니다
