### ISSUE TITLE
[이상탐지] UCL/LCL 이 변하는 시간단위가 원래 1시간이 최소인데, 현재는 데이터의 집계 단위로 그려집니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1150]
## 버그 설명 ##
이상탐지 메뉴에서 UCL/LCL 이 변하는 시간기준은 1시간이 최소로 설정하고 계산되기로 설정되어 있었는데,  
갑자기 데이터의 집계 단위 시간으로 UCL/LCL 이 생성되고 있습니다.
그래서 챠트를 보기가 힘들고,  적은 데이터 갯수로 인해 판정에 오류가 커보입니다.
 
## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to '이상탐지'
2. 데이터모델 AD_TEST_NEW  , 검색 시간 2018/11/02 22:00:00 ~ 11/03 07:00:00
3. 스크린샷 설정 확인

## 예상한 행동 ##
UCL/LCL 은 1시간 마다 변하고, value 의 집계는 설정에 따라 10분 집계

## 스크린샷 ##
* 설정
<img width="403" alt="2018-11-26 6 01 03" src="https://user-images.githubusercontent.com/5126497/49003501-60c19f80-f1a5-11e8-8ac4-4bfeff358b89.png">

* 결과
<img width="874" alt="2018-11-26 6 01 14" src="https://user-images.githubusercontent.com/5126497/49003512-64552680-f1a5-11e8-8f83-b21ee1e8010d.png">

* UCL/LCL 이 1시간마다 변하고, value 는 설정에 따라 10분 집계 데이터입니다.
<img width="883" alt="2018-11-26 6 01 30" src="https://user-images.githubusercontent.com/5126497/49003520-6919da80-f1a5-11e8-8fd4-6f2a0a7853a5.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by pjh0347** [comment]
개선하여 운영 서버 반영 하였습니다.

![image](https://user-images.githubusercontent.com/5305236/63914114-328f2a00-ca6d-11e9-8000-27b14af98076.png)

![image](https://user-images.githubusercontent.com/5305236/63914139-42a70980-ca6d-11e9-9f96-f272ccc00828.png)
