### ISSUE TITLE
보고서 / Safari 브라우저에서 텍스트 객체 추가 후 텍스트 입력 안됨

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1158]
## 버그 설명 ##
Safari 브라우저 기준, 보고서 편집 화면에서 텍스트 객체 추가 후 텍스트 입력 안되는 문제가 있습니다.
Google Chrome 브라우저에서는 잘 됩니다.

**Comment by swish1995** [comment]
https://stackoverflow.com/questions/20435166/contenteditable-not-working-in-safari-but-works-in-chrome
해당 내용 수정하여 pr 했습니다.

**Comment by veldise** [comment]
해결되어 닫습니다.
