### ISSUE TITLE
[HDFS브라우저] 다른 사용자 계정 조회/새폴더생성/삭제가 가능한 이슈

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1162]
## 버그 설명 ##
어제 최영철 선임님께 보여드린 내용을 토대로 이슈 올립니다.

스크린샷에서 자세히 설명 드리겠습니다.

## 재현하는 방법 ##
권한이 '사용자'인 계정으로 접속하여 [HDFS브라우저]의 'USERS' 아래에 있는 아무 계정에서나 새폴더 생성을 하고 삭제를 한다

## 스크린샷 ##
1. 모든 사용자 계정이 다 보임
![image](https://user-images.githubusercontent.com/35832986/49263164-b12e4b00-f48c-11e8-8821-b21ecd01241c.png)

'USERS'의 권한이 스크린샷과 같이 설정되어 있는데, '사용자' 권한을 가진 계정의 [HDFS브라우저] 화면에서 모든 사용자의 디렉토리가 전부 조회가능하고 접근도 가능함

2. 다른 사용자 디렉토리에서 새폴더 생성 / 삭제 가능
![image](https://user-images.githubusercontent.com/35832986/49263437-e5563b80-f48d-11e8-85c0-2d98af3f0e27.png)

권한이 위와 같이 설정되어 있을 때, 새폴더 생성과 삭제가 가능합니다 
(반면 업로드는 권한이 없다고 안됩니다.)

## 예상한 행동 ##
1. 권한에 해당하는 만큼의 사용자 계정 디렉토리가 조회되어야 합니다
2. 새폴더 생성과 삭제는 불가해야한다고 판단합니다 (root 및 그룹장 제외)

**Comment by veldise** [comment]
배포 및 해결되었습니다.
