### ISSUE TITLE
[개발서버(116) forecasts 명령어] 에서 "single positional indexer is out-of-bounds" 라는 에러가 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1165]
## 버그 설명 ##
root 계정의 시각화 "forecasts샘플" 을 실행하니(결과가 나온 것을 시각화로 저장한 것) 이런 에러가 뜹니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1.  시각화 목록에서 "forecasts 샘플" 을 실행  
2. See error

## 예상한 행동 ##
현재 데이터와 예측데이터가 통계탭에 출력

## 스크린샷 ##
<img width="792" alt="2018-12-03 2 10 06" src="https://user-images.githubusercontent.com/5126497/49354249-2d32c800-f705-11e8-9753-fc7d0ee40f5d.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
"No data at that time"을 출력하도록 수정하였습니다. 차주 목요일에 180번에 반영 예정입니다.
재현 쿼리 
`model name = 'WEATHER' model_owner = choi start_date = 20190725151400 end_date = 20190725151559 | forecasts DATE AVG_TEMP alg=linear`

**Comment by namjals** [comment]
반영되었습니다.
![image](https://user-images.githubusercontent.com/22319132/62179116-613eb580-b386-11e9-88d1-3449f1e6d2b6.png)
