### ISSUE TITLE
[개발서버(116) forecasts명령어] 에서 "dict has no attribute 'lower' " 에러가  여전히 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1166]
## 버그 설명 ##
forecast 의 알고리즘 linear 에서 dict has no attribute 'lower'  에러( python 에러 ) 가 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 시각화 myiris 계정 /   forecasts_예제_tsdn-svr1_linear_샘플  
2. 에러 확인

## 예상한 행동 ##
통계 탭에서 현재 데이터와 prediction 컬럼으로 예측값이 나오기를 기대

## 스크린샷 ##
<img width="871" alt="2018-12-03 2 48 26" src="https://user-images.githubusercontent.com/5126497/49355485-29a23f80-f70b-11e8-8ec1-dd673bfbf7d6.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
180번기준 현재 에러없이 동작하고 있습니다.
통계
![image](https://user-images.githubusercontent.com/22319132/62755163-d8262d80-baad-11e9-8afa-858495bdb75d.png)
시각화
![image](https://user-images.githubusercontent.com/22319132/62755175-e83e0d00-baad-11e9-92be-6c3644c610ff.png)

**Comment by namjals** [comment]
현재 로컬버전에서 테스트할때는, 예측 데이터가 시간순으로 출력이 되는데 180번은 예측 데이터의 시간이 뒤죽박죽으로 출력이 되는 문제가 있습니다.
현재 로컬버전을 180에 반영하여 재현 여부를 확인해야 합니다.

재현 쿼리 
`* HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME_10M, * from angora" | stats COUNT(*) as CNT by DATETIME_10M, HOST | sort +DATETIME_10M | forecasts DATETIME_10M CNT alg=linear`

**Comment by namjals** [comment]
시간이 뒤죽박죽으로는 출력되지 않는데, 시간의 간격이 제각각인 부분이 있습니다. 확인 후 처리하겠습니다.

**Comment by namjals** [comment]
spark 클러스터에 rdd가 시간에 상관없이 뒤섞여있는 상태에서 limit를 호출하여 임의의 시간을 가져왔습니다. 
시간 순으로 sorting 후, limit를 호출하도록 수정했습니다.
![image](https://user-images.githubusercontent.com/22319132/64159439-378d1880-ce75-11e9-81e3-88dfd5b906e0.png)

결과 화면
![image](https://user-images.githubusercontent.com/22319132/64159700-98b4ec00-ce75-11e9-8479-1588850982c1.png)
