### ISSUE TITLE
고급시각화 / Safari에서 컬럼 드래그시 레이어가 다중으로 잡혀 보이는 문제

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1173]
## 버그 설명 ##
[데이터 브라우저]-[고급시각화]에서 축및 범례에 해당하는 변수를 드래그 할때 
레이어가 2개로 잡혀보입니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :

<img width="1397" alt="2018-12-05 11 39 31" src="https://user-images.githubusercontent.com/36151180/49490016-2afd7480-f891-11e8-9e5d-aa05059778d8.png">

<img width="1106" alt="2018-12-05 1 34 41" src="https://user-images.githubusercontent.com/36151180/49490282-972ca800-f892-11e8-8998-18ff50d68698.png">

위 스크린샷은 변수를 드래그 하는 과정에서 
계속적으로 레이어가 두개 잡히는 모습을 찍은 화면입니다.
다른 고급시각화 차트에서도 동일한 이슈가 있습니다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

드래그를 했을 시에 레이어가 하나인 상태로 드래그되어 보이는 것이 깔끔하고 명확해 보입니다. 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
현재 사파리에서 재현되지 않아 닫습니다.
