### ISSUE TITLE
보고서, 테이블 셀 너비가 유동적으로 변경

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1176]
## 기능 요청 ##
보고서 기능중 테이블 셀 너비가 고정이 아닌 데이터 너비에 맞춰 변경이 되도록 필요

## 원하는 솔루션 설명 ##
현재 보고서 기능에서는 테이블의 셀의 너비가 전부 똑같은 크기로 되고 있음
필요로 하는 기능은 해당 셀의 너비가 데이테에 맞춰 유동적으로 변경이 되었으면 좋겠음

## 고려한 다른 대안 ##
가능하다면, 사용자가 컬럼마다 크기를 지정할수 있으면 더 좋을것 같음

**Comment by veldise** [comment]
테이블 크기 - 객체와 가로 길이 맞춤 옵션을 추가하였습니다.
![image](https://user-images.githubusercontent.com/3411842/62262002-2bff9980-b452-11e9-9bc7-7a841a59aafa.png)
