### ISSUE TITLE
시각화 / 피벗, 고급시각화, 보고서 범례 중복 오류

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1177]
## 버그 설명 ##

<img width="1341" alt="2018-12-05 4 08 41" src="https://user-images.githubusercontent.com/36151180/49496136-82f3a580-f8a8-11e8-9c30-d7f0f3003d85.png">
위의 스크린샷은 보고서, 

<img width="1404" alt="2018-12-05 4 24 48" src="https://user-images.githubusercontent.com/36151180/49496882-58a2e780-f8aa-11e8-9245-e15cd56de5ce.png">
위 스크린샷은  피벗의 차트입니다.

시각화 차트(피벗, 고급시각화, 보고서) 모두 에서 그래프의 범례부분이 10개씩 반복(중복)이 이루어집니다. 

또한, 고급시각화와 보고서의 범례의 경우 색상 뿐 아니라 모양도 함께 변경되어 나타나는데 
범례의 모양을 동일하게 하거나 
혹은 모양을 변경하는 것을 선택할 수 있었으면 좋겠습니다.  

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [데이터브라우저 ]-[관리]-[보고서]에서 새 보고서 작성(다른 시각화에서도 비슷)
2. 
<img width="278" alt="2018-12-05 4 09 43" src="https://user-images.githubusercontent.com/36151180/49496228-b8988e80-f8a8-11e8-8127-2f8c48f59a75.png">

3. 
<img width="279" alt="2018-12-05 4 09 51" src="https://user-images.githubusercontent.com/36151180/49496289-e4b40f80-f8a8-11e8-8df3-c08c1efc8bb8.png">

4. 
<img width="505" alt="2018-12-05 4 09 33" src="https://user-images.githubusercontent.com/36151180/49496247-be8e6f80-f8a8-11e8-935f-d8c4ca64301f.png">

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

색 혹은 모양 중복이 일어나지 않은상태로 범례생성이 되길 바랍니다. 
또한, 고급시각화와 보고서의 범례의 경우 색상 뿐 아니라 모양도 함께 나타나는데 
다른 시각화 차트처럼 범례의 모양을 동일하게 하거나 
혹은 모양을 변경하는 것을 선택할 수 있었으면 좋겠습니다.  

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

참고로 R에서는 범례를 생성할 경우 팔레트를 기준으로 
갯수에 상관없이 계속적으로 새로운 색이 만들어도록 합니다. 
레인보우 팔레트가 default인것 같고, 특정 팔레트를 지정하는것도 가능합니다. 
특정 그룹인자의 색변경도 가능합니다. 

그룹개수 5개, 10개, 20개 R에서  ggplot에서 생성시 아래 참고 
<img width="245" alt="2018-12-05 4 56 39" src="https://user-images.githubusercontent.com/36151180/49498556-c8b36c80-f8ae-11e8-9a13-7882f28082ec.png">

**Comment by veldise** [comment]
Highcharts 기본 범례 컬러 설정이 10개라서 발생하는 문제입니다.
d3를 참조하여 30개 정도로 늘일 수 없는지 방법을 찾아보겠습니다.

**Comment by veldise** [comment]
Highcharts 기본 색상에 D3.js 에서 제공하는 category 색깔을 추가하도록 하겠습니다. 
이 색깔들의 RGB 코드는 다음과 같습니다.
```js
// d3.scale.category20().range()
var D3_COLORS = ['#1f77b4', '#aec7e8', '#ff7f0e', '#ffbb78', '#2ca02c', '#98df8a', '#d62728', '#ff9896', '#9467bd', '#c5b0d5', '#8c564b', '#c49c94', '#e377c2', '#f7b6d2', '#7f7f7f', '#c7c7c7', '#bcbd22', '#dbdb8d', '#17becf', '#9edae5'];
// highcharts defaults
var HC_COLORS = ['#7cb5ec', '#434348', '#90ed7d', '#f7a35c', '#8085e9', '#f15c80', '#e4d354', '#2b908f', '#f45b5b', '#91e8e1'];
```

**Comment by veldise** [comment]
본사 180번 서버에 적용 완료했습니다.
