### ISSUE TITLE
Jupyter / 404 Not Found 페이지 출력

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1178]
## 버그 설명 ##
B-IRIS 신규 설치 - root 계정으로 Jupyter 접속 시 404 Not Found 페이지가 출력됩니다.

## 원인 추측
1. `/save/jupyter/packages` 폴더가 생성되지 않음
  - python 공용 패키지 폴더
2. `/notebook` 폴더의 permission 등이 맞지 않음
  - `chmod -R 775 /notebook`
  - `chown -R $NB_USER:root /notebook`

## 참고사항
`50dfcea` 버전 `-c` 옵션으로 설치후
`dcef32f` 버전 `-c` 옵션 없이 재설치하면 정상 동작

**Comment by anhm** [comment]
첫 설치시에 rstudio_common 파일이 압축해제 되지 않는 것이 확인 되었으며,
처음 설치시 자동으로 설치 되도록 수정했습니다.
