### ISSUE TITLE
DB브라우저/ SELECT결과 테이블 다운로드시 실행 결과 내용 없음

### ISSUE THREAD

**Issue by yubin90** [mobigen/IRIS-BigData-Platform#1180]
## 버그 설명 ##
DB브라우저에서 SELECT 한 결과 테이블을 다운로드 하였을 때, 아무 내용도 없는 파일만이 다운로드 됩니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. DB브라우저 실행 - 쿼리 실행 - 하단 실행결과 확인 
2. 실행 결과 창에서 오른쪽 상단 [다운로드] 버튼 클릭
3. 다운로드 된 CSV파일 열기 
4. 내용 확인

## 예상한 행동 ##
실행 결과의 테이블이 CSV파일로 로컬에 다운로드 되어야 함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/40253529/49620187-2ce74500-fa03-11e8-953b-71a5cb597326.png)

![image](https://user-images.githubusercontent.com/40253529/49620200-3b356100-fa03-11e8-86b2-a9590040ec3c.png)

![image](https://user-images.githubusercontent.com/40253529/49620220-47b9b980-fa03-11e8-8fae-b40dc7dd52cf.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
배포 및 해결되었습니다.
