### ISSUE TITLE
데이터 추가 / 로컬테이블로 데이터 추가 시 null 포함 행의 자동 삭제 관련

### ISSUE THREAD

**Issue by yubin90** [mobigen/IRIS-BigData-Platform#1181]
## 기능 요청 ##

- 현재 아이리스에서 로컬 테이블로 데이터를 추가 할 때 일부 행이 전부 NULL값일 경우 그 행 자체를 누락한 형태로 업로드 됩니다.
- NULL값 포함 행을 그대로 업로드 하는 방식이 필요합니다.
- 상황에 대한 예는 다음과 같습니다.

로컬 테이블로 업로드 시 한 행이 전부 NULL값일 때 행 자체가 누락됨(5번째 행)
![image](https://user-images.githubusercontent.com/40253529/49621961-f57c9680-fa0a-11e8-9028-30e0835ffcf8.png)

![image](https://user-images.githubusercontent.com/40253529/49622048-4e4c2f00-fa0b-11e8-9597-9916a576c21c.png)
  
## 원하는 솔루션 설명 ##
- 분석 프로세스에서 분석가는 대상 테이블 내 값들의 NULL여부 및 분포를 파악할 필요가 있으며, 해당 NULL값을 채우기 위한 값 보정 및 예측 작업이 빈번히 일어납니다.
- 테이블 스케일이 큰 로컬 테이블을 사용할 경우 사람이 눈으로 일일히 누락을 확인할 수 없습니다.
- 따라서 일부 행 전체가 NULL값인 테이블이더라도 그대로 업로드 하는 기능이 필요합니다.

## 고려한 다른 대안 ##
- 최소한 누락이 발생하였을 때 몇 행이 누락되었는지 등의 알림을 제공하였으면 좋겠습니다.

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sonchanseung** [comment]
@yubin90 
IRIS 는 기본적으로 `파티션 키` 와 `파티션 구분일` 을 선택하는데 이 이슈의 경우 `DATE` 컬럼을 `파티션 구분일` 로 선택했습니다. 이 때, `DATE` 컬럼의 값의 `NULL` 인 경우 내부적으로 시간을 `2018-01-01` 로 설정합니다. 따라서 현재 시각을 기준으로 `DATE` 의 값이 `디스크 저장시간` 을 초과하면 자동으로 데이터가 삭제됩니다.
해결 방법은 데이터를 `import` 할 때, `디스크 저장시간` 항목을 적절하게 조절하시면 됩니다.

**Comment by sonchanseung** [comment]
이슈 닫도록 하겠습니다.
