### ISSUE TITLE
DB브라우저 / SQL쿼리문 저장 기능 추가

### ISSUE THREAD

**Issue by yubin90** [mobigen/IRIS-BigData-Platform#1182]
## 기능 요청 ##
- DB브라우저에서 작성된 SQL쿼리 스크립트를 따로 저장, 로드할 수 있는 기능이 필요합니다.

## 원하는 솔루션 설명 ##
- 현재 DB브라우저에서 SQL 쿼리문을 입력한 후 다른 페이지로 이동하거나 계정 로그아웃 후 다시 로그인을 하면 쿼리문이 지워집니다. (리셋되거나 오래전 작성된 일부 구문만 남음)
- 작성한 쿼리 스크립트를 저장, 로드하여 재사용, 로컬에 텍스트 파일 등으로 다운로드 할 수 있는 기능을 추가해주시길 바랍니다.
 
## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
배포 및 해결되었습니다.
