### ISSUE TITLE
[개발서버(116) forecasts명령어] 의 alg=seasonal 에서는 결과가 없다고 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1183]
## 버그 설명 ##
forecasts 명령어에서 alg=seasonal 로 하면 결과가 없다고 나옵니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 시각화 myiris 계정의  forecasts_예제_tsdn-svr1_seasonal_샘플   

## 예상한 행동 ##
아직 매뉴얼을 받지 못해  alg=linear 대신 alg=seasonal  로만 바꿔서 실행했는데, 
1.  예측 결과가 통계탭에 나오거나 
2. 명령어 오류 라는 메세지가 나온다.

## 스크린샷 ##
<img width="1039" alt="2018-12-07 3 29 41" src="https://user-images.githubusercontent.com/5126497/49631486-94b68380-fa35-11e8-8de9-f72bf9148e27.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
현재 결과는 잘 나오고 있습니다.
통계
![image](https://user-images.githubusercontent.com/22319132/62756310-37863c80-bab2-11e9-9294-e67eb034acf3.png)

시각화
![image](https://user-images.githubusercontent.com/22319132/62756319-41a83b00-bab2-11e9-8d53-46b3c8b0ec62.png)

**Comment by namjals** [comment]
현재 로컬버전에서 테스트할때는, 예측 데이터가 시간순으로 출력이 되는데 180번은 예측 데이터의 시간이 뒤죽박죽으로 출력이 되는 문제가 있습니다.
현재 로컬버전을 180에 반영 후 다시 확인해보겠습니다.

재현 쿼리
* HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME_10M, * from angora" | stats COUNT(*) as CNT by DATETIME_10M, HOST | sort +DATETIME_10M | forecasts DATETIME_10M CNT alg=linear

**Comment by namjals** [comment]
수정하였습니다.
![image](https://user-images.githubusercontent.com/22319132/64159903-e598c280-ce75-11e9-91c1-7f4724beb15b.png)


관련 이슈
https://github.com/mobigen/IRIS-BigData-Platform/issues/1166
