### ISSUE TITLE
데이터 추가 / datetime 필드의 년도/월/일/시/분/초 구분 기능

### ISSUE THREAD

**Issue by yubin90** [mobigen/IRIS-BigData-Platform#1186]
## 기능 요청 ##
데이터 추가 화면에서 데이터 업로드 시, datetime 문자열 컬럼이 포함되는 경우 자동으로 년도/월/일/시/분/초 로 나눌 수 있는 기능.
 
## 원하는 솔루션 설명 ##
현재 데이터 추가 기능에서 새 로컬 데이터를 업로드 할 때, 데이터 row 생성의 기준이 되는 datetime 필드가 포함되는 경우가 매우 많습니다. 
현재는 필요에 따라 [열 분할] 기능을 이용하고 있습니다. 
하지만 생성 이후에도 다시 년도/월/일/시/분 또는 시/분/초 등 다양한 시간 조합이 필요할 때가 있습니다. 
또한 각 일자가 컬럼으로 구분되어 있을 경우 데이터브라우저에서 검색 쿼리를 사용하기에 매우 편리합니다. 
![image](https://user-images.githubusercontent.com/40253529/49730438-b32db080-fcbb-11e8-87c8-fd965c446fe1.png)

이렇듯 로컬 데이터를 데이터 추가 기능을 통해 업로드 시 이용자가 선택한 datetime 필드를 시간 기준에 따라 나누는 기능이 있으면 좋겠습니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise @anhm 특정 필드를 구분하여 새 필드를 만들 수 있는 방법 또는 명령어를 설명해 주시면 좋을것 같습니다.
