### ISSUE TITLE
[R studio] 세션 종료 및 로그아웃시 과거작성 및 실행했던 working history 사라짐

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1187]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

iris 로그아웃을 하거나 
시간이 많이 지나 세션이 종료되었을 경우, 로그아웃되고 다시 로그인을 하는 작업을 하는데, 
과거에 작성했던 workspace의 history 기록이 모두 삭제되어서 
다시 처음부터 실행해야 하는 경우가 생깁니다. 

user가 사용했던 기록이 사라지기에 일일이 workspace의 image를 저장해 놓지않으면
안되는 어려움이 있습니다. 

예를들어 1-2시간이 걸려 r-studio에서 모델을 실행시켜놓고, 다음날이 되어 저장 되었을 줄 알고 있었는데, 
세션이 종료되어 있었고, 다시 로그인을 해보니 
콘솔 및 workspace 등 실행기록이 모두 사라져 있어, 
다시 1-2시간동안 모델 실행 및 전처리 작업을 반복해야만 합니다. (불필요한 반복이 발생)

심지어 스크립트에 코드를 작성하고 있었다면(저장하지 않았다면), 
로그아웃과 동시에 작성하던 코드가 사라집니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. r-studio에서 r 스크립트를 실행시킨다.
2. 로그아웃한뒤 다시 로그인을 한다.
3. 과거의 r 스크립트의 '실행'기록이 사라진다. 
(실행했던 workspace, 콘솔창, 저장하지 않았던 스크립트 기록이 모두 사라짐)

## 예상한 행동 ##

로그아웃을 하거나 세션이 종료되어도 
마지막에 r에서 실행했던 정보가 workspace에 남아있기를 바랍니다. 

그리고 로그인 했을 시에 사용자가 사용하던 그대로(실행기록 그대로) 남아있어야 합니다.
작성하고 있던 코드가 있으면(저장하지 않았지만), 코드도 그대로 남아있어야 합니다.

## 스크린샷 ##
<img width="1403" alt="2018-12-11 9 29 07" src="https://user-images.githubusercontent.com/36151180/49770543-4997bb80-fd28-11e8-968a-1dd51f85b644.png">
세션이 종료된후 다시 로그인을 했을 시에, 과거의 기록이모두 사라지고, 
아주 예전에 과거의 이미지만 생기는 경우입니다.

**Comment by veldise** [comment]
1. `session-save-action-default=yes` 옵션으로는 해결되지 않았습니다.
2. rstudio 내에서 로그아웃 시, 즉 docker container가 유지된 상태에서는 정상적으로 history가 초기화되지 않고 남아있습니다.
3. 사용자 홈 폴더의 `.rstudio/history_database` 파일에는 남아있지만, rstudio 접속시 아예 불러오고 있지 않습니다.

현재 docker container를 삭제하면 client_state 값부터 유지가 안되어, history를 포함한 모든 동작(탭 선택 등)의 기록이 사라지는 것으로 생각됩니다.

**Comment by veldise** [comment]
1. docker container 내부에서 `.Rdata`, `.Rhistory`파일을 찾지 못했습니다.
2. `savehistory()` 함수를 사용하면 지정한 경로에 `.Rhistory` 파일이 생성되고 `loadhistory()`로 다시 불러올 수 있습니다.

**Comment by veldise** [comment]
#1211
