### ISSUE TITLE
데이터 검색/ 값이 비었을 경우 NULL의 추가/제외 조건으로 필터링되지 않음

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1188]
## 버그 설명 ##

![2018-12-11 2 46 37](https://user-images.githubusercontent.com/36151180/49780854-bd02f280-fd53-11e8-8d6c-5f4d4c0dced6.png)

![2018-12-11 2 46 50](https://user-images.githubusercontent.com/36151180/49780856-bf654c80-fd53-11e8-9b25-db5f52f1aab1.png)

RAINFALL_CONT_TIME 변수처럼 데이터 값에 빈값을 가지고 있는경우, 
왼쪽의 summary 에서는 빈 데이터 값이 NULL로 카운트 되어서 집계가 되는데, 
정작 컬럼을 선택하여 오른쪽버튼을 눌러 [검색에 추가]를 선택 할 경우, 
값이 NULL로 잡히지 않아서 filtering이 되지 않습니다.  

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. weather 테이블 선택, 전체시간 선택

![2018-12-11 2 46 15](https://user-images.githubusercontent.com/36151180/49780849-ba080200-fd53-11e8-9bb1-3499c245e215.png)
2. RAINFALL_CONT_TIME 의 빈행을 검색어 추가/제외를 누른다
3. NULL 값으로 잡히지 않아서 필터링 할 수 없음

## 예상한 행동 ##
빈 데이터 값이 NULL 값으로 잡혔으면 좋겠습니다.

**Comment by veldise** [comment]
@pjh0347

**Comment by namjals** [comment]
대소문자 구분없이 `컬럼명 is null` 이라고 검색하면 됩니다.
![image](https://user-images.githubusercontent.com/22319132/61766500-ff2d0000-ae1b-11e9-9d3c-a3b84c51e124.png)
