### ISSUE TITLE
고급시각화 / 차트의 y축의 값 에러 

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1189]
## 버그 설명 ##
![2018-12-11 3 22 03](https://user-images.githubusercontent.com/36151180/49782348-4f59c500-fd59-11e8-9497-d7211117cd4d.png)

y축 변수는 실수정보인데 날짜값으로 변환되어 보입니다. 

실제 값은 그대로 들어가 있는데, y축 스케일상에서 오류가 난 것 같습니다.
다른 실수값의 변수를 선택하여 y축에 넣어봐도 동일한 현상이 나타납니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. weather 테이블, 전체시간을 선택한다. 
2. 고급시각화로 넘어간다. 
3. 시계열분포 선택
4. x축에 날짜를, y축에 다른 변수를 넣어본다. 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
y축의 스케일이 실수면 실수 값에 맞게, text면 text에 맞게 나타나야 합니다. 

## 스크린샷 ##

y축에 real, integer 말고, text값을 넣었을 시에도 날짜로 인지하는것 같습니다. 
![2018-12-11 3 25 33](https://user-images.githubusercontent.com/36151180/49782332-42d56c80-fd59-11e8-9393-e00194d2586d.png)
![2018-12-11 3 26 09](https://user-images.githubusercontent.com/36151180/49782334-449f3000-fd59-11e8-93d6-6a32032fad55.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
배포 및 해결되었습니다.
