### ISSUE TITLE
geoip 오류

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#1191]
## 버그 설명 ##
명령어가 정상 동작 하지 않습니다.

## 스크린샷 ##
<img width="1004" alt="2018-12-13 4 13 48" src="https://user-images.githubusercontent.com/512653/49921804-1739ba00-fef2-11e8-9f82-1ada608171f5.png">

**Comment by pjh0347** [comment]
**문제 현상과 원인 : **
ip 정보 기준으로 위/경도 정보를 찾아 추가하는 과정에서, 모든 입력 데이터에 대해 위/경도 정보를 한 건도 찾지 못한 경우 위와 같은 에러가 출력되도록 되어 있습니다. 그리고 기본적으로 맵핑 데이터(ip->위/경도)는 memcached 에 저장되어 있는 것을 사용하도록 되어 있는데, 현재 memcached 데몬이 꺼져 있어 위/경도 정보를 한건도 찾지 못하고 있습니다.

**문제 해결 : **
1) memcached 데몬을 실행하고, 맵핑 데이터를 memcached 에 적재.
2) geoip 명령어 실행될때 memcached 접속이 불가한 경우 오류 메시지 처리.
3) memcached 접속은 가능하지만 맵핑 데이터를 한 건도 찾지 못한 경우(데이터 품질 문제), 정상적으로 결과를 내려주되 위/경도 컬럼에는 null 값으로 내려주기.

**Comment by pjh0347** [comment]
운영 서버에서 memcached 데몬을 실행하고, 맵핑 데이터를 memcached 에 적재하였으며, 추가적으로 예외처리부분을 추가 개발하였습니다. 해당 내용은 다음번 패치때 적용될 예정입니다.
