### ISSUE TITLE
[시각화/데이터모델] root계정의 syslog 데이터모델에 읽기접근권한이 갑자기 없어졌습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1194]
## 버그 설명 ##
지난 주까지 root계정의 syslog 데이터모델에 읽기 권한이 있어서 이 데이터모델로 여러개의 시각화 모델을 생성했습니다.
그런데 오늘 보니 갑자기 권한이 없다고 나오고,  데이터모델 리스트에도 보이지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. myiris 로그인
2. 시각화 tmp1 선택

## 예상한 행동 ##
읽기 접근 권한 유지

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
현재 root 계정은 syslog 데이터 모델을 소유하고 있지 않습니다.
대신 eva 계정의 syslog 데이터 모델을 '모든 사용자'로 설정하였으니 확인부탁드립니다.

**Comment by seoryjj** [comment]
네. 이제 syslog 데이터모델 기반으로 만든 시각화가 정상적으로 나옵니다. 감사합니다
