### ISSUE TITLE
Text to Num 필드 타입 변경 기능

### ISSUE THREAD

**Issue by yubin90** [mobigen/IRIS-BigData-Platform#1195]
## 기능 요청 ##
현재 테이블 업로드 혹은 업로드 된 테이블의 데이터 모델 내 필드 타입 변경 과정에서 TEXT타입의 필드로 지정 후, 다시 값을 INT, REAL의 numeric값으로 치환 시 공백으로 처리합니다. 
(버그 이슈인지 확인할 수 없어 일단 기능 제안으로 작성하였습니다.)

예를 들어, 테이블 필드 전체를 텍스트 타입으로 업로드 후
![image](https://user-images.githubusercontent.com/40253529/50125367-dbb13e00-02ab-11e9-8795-90e975b67611.png)

[데이터 모델]로 추가 시 타입을 변경합니다.
![image](https://user-images.githubusercontent.com/40253529/50125362-d5bb5d00-02ab-11e9-9ee2-401c937a3d57.png)

이후 테이블 값을 검색해보면 필드마다 값들이 distinct count는 되지만 테이블 내용에 보이지 않습니다.
![image](https://user-images.githubusercontent.com/40253529/50125399-01d6de00-02ac-11e9-89cb-7d8562706599.png)

numeric한 값으로 인식하는지 확인하기 위해 테스트하였지만 결과가 없습니다.
![image](https://user-images.githubusercontent.com/40253529/50125418-28951480-02ac-11e9-8ba4-6d1ee8c7c534.png)

## 원하는 솔루션 설명 ##
데이터 타입 변환이 가능하도록 convert기능이 추가되었으면 합니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@yubin90 
업로드한 데이터의 해당 컬럼에 문자열(`"`) 값이 섞여있어 numeric으로 인식되지 않아서 발생하는 문제로 보입니다.
[데이터 추가] 화면에서 데이터 업로드시, **열 구분 > 텍스트 한정자** 옵션을 사용해보시고,
그래도 잘 되지 않는다면 샘플 데이터를 압축하여 본문에 첨부해주시기 바랍니다.
샘플 데이터를 토대로 문제 원인을 파악해보겠습니다.

**Comment by yubin90** [comment]
특수문자를 제외하고 테스트 한 결과 정상작동하였습니다. 그런데 예를 들어 한 필드 값이 TEXT타입인 경우 일부러 INT타입으로 변환해보면 그냥 공백으로 처리하게 되는데 이 부분은 에러 혹은 안내 메시지가 생성되는 방식이 좋지 않을까 합니다. 사용자가 잘못 변환하여(클릭 실수 등) 필드가 공백이 된 경우를 모델 생성 후 발견하면 추후 번거로운 작업이 발생할 것 같습니다.

**Comment by veldise** [comment]
@yubin90 
좋은 말씀 감사합니다.
말씀하신대로 문자열 값이 들어있는 컬럼을 INTEGER 등으로 지정한 경우 검색 결과가 공백인 문제를 확인했습니다.
별도 이슈로 해결이 필요해보입니다.

**Comment by veldise** [comment]
#1197
