### ISSUE TITLE
SMS 알람창 인지등록시 창이 닫히는 순서 오류

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1196]
## 버그 설명 ##
SMS 알람창 인지 등록시 아람창이 닫히는데 누른 알람 창이 닫히지 않고, 가장 먼저 생성된 알람이 닫히는 걸로 판단됨

닫힘 버튼을 누를 경우 눌린 알람창이 닫힘,
하지만, 알람 인지 버튼을 누를 경우 가장 뒷쪽에 있는 알람창이 닫힘

## 재현하는 방법 ##
동작을 재현하는 방법 :
SMS 알람이 2개 이상 쌓이도록 기다린다.
발생한 알람창에서 알람인지 버튼을 누름

## 예상한 행동 ##
알람 인지 버튼을 누른 알람창이 닫혀야함

**Comment by veldise** [comment]
해결 및 180번에 배포 완료했습니다.
