### ISSUE TITLE
Angora v2 / fields 명령어 사용시 timeline 결과 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1198]
## 버그 설명 ##
검색 화면에서, `fields` 명령어를 사용시 다음과 같은 에러가 반환됩니다.

* POST request body:
```json
{
    "q":"model-timeline name = 'syslog' start_date = 20181220133500 end_date = 20181220133610 unit = 1S | fields DATETIME,HOST"
}
```

* GET Response:
```json
{
  "message": "None of [date, event_count] was selected in [fields].", 
  "type": "<class 'angora.exceptions.AngoraException'>"
}
```

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 116번 서버에서 root 계정으로 접속
2. `syslog` 데이터 모델 선택
3. 검색어를 `* | fields DATETIME,HOST`로 입력
4. 실행

**Comment by sonchanseung** [comment]
model-timeline 명령어는 date 와 event_count 를 가지고 dataframe 을 구성하기 때문에 fields 로 입력한 컬럼에 대해서 찾을 수 없다는 에러가 발생하는 이슈입니다.
전에 말씀드린대로 model-timeline 명령어에 대해서는 `| fields ~` 로 입력되는 부분을 제거하여 요청 보내주시면 되겠습니다.

**Comment by veldise** [comment]
@sonchanseung @pjh0347 
`fields` 명령어 이외에 제거해야하는 명령어들을 정리해주세요. 박진호 선임님과 이야기된 부분입니다.
결과 열에 영향을 주는 명령어 / 결과 행에 영향을 주는 명령어 / 통계성 결과를 내는 명령어
이렇게 정리해주시면 됩니다.

**Comment by sonchanseung** [comment]
@veldise 
명령어를 정리하여 git 에 업로드 해놓았습니다. 확인 부탁드립니다.
https://github.com/mobigen/B-IRIS-Data-Discovery-Service/blob/master/src/main/python/angora/cmds/WebUI_cmds.csv

**Comment by veldise** [comment]
@pjh0347  @sonchanseung 
`model-timeline` 요청시 결과 열에 영향을 주는 명령어 `count, fields, rename` 등을 제거하였습니다만,
결과 행에 영향을 주는 `where`, `head` 등의 명령어도 문제가 있는 것이 확인되었습니다.

`where`의 경우, 아래와 같이 `model-timeline`의 결과 컬럼
`date`, `event_count`에 없는 컬럼을 지정하면 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/3411842/50813918-3d207600-135b-11e9-82f6-41090e23163a.png)

`head`의 경우, 수행은 되지만 `head` 명령어가 반영되지 않습니다.

![image](https://user-images.githubusercontent.com/3411842/50813964-5a554480-135b-11e9-999a-49da85b0c2d2.png)

**Comment by veldise** [comment]
@pjh0347 @sonchanseung 
`where` 명령어 부분을 임의로 model-timeline 명령어 부분으로 옮기는 일은 UI에서는 매우 어려운 일이며 UI에서 수행하는 것은 적절하지 않다고 생각합니다.
어려운 이유는 사용자가 복잡하게 검색어를 작성했을 경우에 Syntax(구문) 분석이 필요하기 때문입니다.
사실 `fields`의 경우에도 동일한데, 현재 UI에서는 model-timeline 요청시 단순히 `fields` 키워드 이후 내용을 모두 삭제하고 있습니다. (`fields` 부분만 제거하게 되면 이후 수행하는 명령어에 따라 에러가 발생할 것이므로)

저는 사용자가 model-timeline 수행시 pipe(`|`)에 따라 단계적으로 수행하는 것이 아니라
전체 검색어의 구문을 분석하여 내용에 따라 효율적으로(최적화) 작업을 수행해야 할 수 있어야 한다고 생각합니다.

그게 아니라면 `count` 사례와 동일하게 `timeline` 명령어를 만드는 방법이 있을 것 같습니다.
ex) `* | where HOST=="gcs1" | timeline`

**Comment by sonchanseung** [comment]
@veldise 
여러가지 상황을 고려한 결과 model-timeline 명령어에 대해 앙고라에서 처리해야 할 것 같습니다. model-timeline 명령어를 수행할 때 예전과 같이 전체 쿼리를 넘겨주시면 앙고라에서 처리하도록 하겠습니다.

**Comment by veldise** [comment]
@sonchanseung 
model-timeline 요청시 일부 명령어를 제거하는 동작을 revert 하여 개발 서버(116)에 임시 배포하였습니다.

**Comment by EricLeeMbg** [comment]
180번 서버에서 정상동작 됨을 확인, close합니다.
