### ISSUE TITLE
Angora v2 / 시간 컬럼이 없는 모델로 검색 실행시 결과 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1199]
## 버그 설명 ##
시간 컬럼이 없는 데이터 모델을 선택하여 검색 수행시 작업 결과가 없습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 116번 서버에 root 계정으로 접속
2. `TEST_NAN` 데이터 모델을 선택
3. 검색 실행

## 스크린샷 ##
`TEST_NAN` 모델 정보:
![image](https://user-images.githubusercontent.com/3411842/50264325-6b4a1e80-045d-11e9-9cdd-7679625492ba.png)

180번(Angora v1)에서 수행시:
![image](https://user-images.githubusercontent.com/3411842/50264352-84eb6600-045d-11e9-84ae-10890e74f511.png)

116번(Angora v2)에서 수행시:
![image](https://user-images.githubusercontent.com/3411842/50264376-af3d2380-045d-11e9-84d3-3f0f457d4b2e.png)

**Comment by veldise** [comment]
API 결과 response에 total count 값이 사라져서 발생한 문제였습니다.
`count` 명령어 수행을 추가하겠습니다.

**Comment by veldise** [comment]
검색어(query) 마지막에 `| count`를 추가로 요청하도록 임시 처리하였습니다.

검색 화면에서 검색 수행시, API 호출은 다음과 같이 됩니다.
- count
- search
- timeline (시간 컬럼이 존재할 경우에만 호출)
- stats ('데이터 개수' switch button을 ON으로 설정하였을 때만 호출)
- figure (검색어 내용에 `stats`, `pivot`이 포함되어있을 때만 호출)

@pjh0347 
count 요청이 추가되어도 괜찮은지 검토 부탁드립니다.

**Comment by veldise** [comment]
116번에 수정한 내용 적용하였습니다.

**Comment by sonchanseung** [comment]
QUERY TEST
query : [model name=TEST_NAN] 
parameters : {'q': 'model name=TEST_NAN'}
URL : /angora/query/jobs
URL : /angora/query/jobs/1545354024.9836
{u'status': {u'current': 1, u'total': 1}, u'fields': [{u'grouped': False, u'type': u'TEXT', u'name': u'PRODUCTID'}, {u'grouped': False, u'type': u'INTEGER', u'name': u'PRODUCT_NAME'}, {u'grouped': False, u'type': u'INTEGER', u'name': u'PRICE'}, {u'grouped': False, u'type': u'INTEGER', u'name': u'SALE_PRICE'}, {u'grouped': False, u'type': u'TEXT', u'name': u'CODE'}], u'isEnd': True, u'results': [[u'DB-SG-G01', None, 24, 19, u'A'], [u'DC-SG-G02', None, 39, 24, u'B'], [u'FS-SG-G03', None, 24, 16, u'C'], [u'WC-SH-G04', None, 24, 19, u'D'], [u'WC-SH-T0', None, 9, 6, u'E'], [u'PZ-SG-G05', None, 4, 1, u'F'], [u'CU-PG-G06', None, 19, 16, u'G'], [u'MB-AG-G07', None, 39, 24, u'H'], [u'MB-AG-T0', None, 9, 6, u'I'], [u'FI-AG-G08', None, 39, 24, u'J'], [u'BS-AG-G09', None, 24, 19, u'K'], [u'SC-MG-G10', None, 19, 16, u'L'], [u'WC-SH-A01', None, 5, 2, u'M'], [u'WC-SH-A02', None, 3, 1, u'N']]}
{u'grouped': False, u'type': u'TEXT', u'name': u'PRODUCTID'}
{u'grouped': False, u'type': u'INTEGER', u'name': u'PRODUCT_NAME'}
{u'grouped': False, u'type': u'INTEGER', u'name': u'PRICE'}
{u'grouped': False, u'type': u'INTEGER', u'name': u'SALE_PRICE'}
{u'grouped': False, u'type': u'TEXT', u'name': u'CODE'}
[u'DB-SG-G01', None, 24, 19, u'A']
[u'DC-SG-G02', None, 39, 24, u'B']
[u'FS-SG-G03', None, 24, 16, u'C']
[u'WC-SH-G04', None, 24, 19, u'D']
[u'WC-SH-T0', None, 9, 6, u'E']
[u'PZ-SG-G05', None, 4, 1, u'F']
[u'CU-PG-G06', None, 19, 16, u'G']
[u'MB-AG-G07', None, 39, 24, u'H']
[u'MB-AG-T0', None, 9, 6, u'I']
[u'FI-AG-G08', None, 39, 24, u'J']
[u'BS-AG-G09', None, 24, 19, u'K']
[u'SC-MG-G10', None, 19, 16, u'L']
[u'WC-SH-A01', None, 5, 2, u'M']
[u'WC-SH-A02', None, 3, 1, u'N']

**Comment by sonchanseung** [comment]
말씀하신대로 count 요청을 추가해서 사용하는 것이 좋을 것 같습니다.
