### ISSUE TITLE
Angora v2 / WEATHER 모델 검색시 modeltimelineCommand 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1200]
## 버그 설명 ##
검색 화면에서, `WEATHER` 모델을 선택하여 검색 수행시 다음과 같은 에러가 반환됩니다.
(`WEATHER` 모델은 HDFS 데이터입니다.)

* POST request body:
```json
{
    "q":"model-timeline name = 'WEATHER' start_date = 20151220144200 "
}
```

* GET Response:
```json
{
  "message": "'modeltimelineCommand' object has no attribute 'each_count'", 
  "type": "<type 'exceptions.AttributeError'>"
}
```

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 116번 서버에서 root 계정으로 접속
2. `WEATHER` 데이터 모델 선택
3. 검색 실행

**Comment by sonchanseung** [comment]
hdfs 데이터 모델에 시간 범위 조건이 추가되었을 때, start_date 와 end_date 를 입력된 시간 포맷에 맞게 변경하지 않았기 때문입니다. 시간 데이터를 시간 포맷에 맞도록 변경하는 로직을 추가하였습니다.
https://github.com/mobigen/B-IRIS-Data-Discovery-Service/commit/15ad876c9ff52e30d80b897908bc62a218c78897
