### ISSUE TITLE
[개발서버 116] syslog 검색에서 DATETIME 필드  SPARK 에러 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1201]
## 버그 설명 ##
180  서버에서는 정상적으로 나오는 결과인데, 116 서버에서는  syslog 에 DATETIME 필드 관련 SPARK 에러 납니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 180 서버에서 myiris 계정 시각화  outlier_by_host_예제_MAD_filter1102_2200_1103_0700  실행
2. 결과 확인
3. 116 서버에서 myiris 계정 시각화  outlier_by_host_예제_MAD_filter1102_2200_1103_0700  실행

## 스크린샷 ##
180 서버 결과
<img width="1013" alt="2018-12-24 10 32 39" src="https://user-images.githubusercontent.com/5126497/50389053-f4b46600-0767-11e9-9ad7-45a3f453d208.png">

116 개발 서버
<img width="872" alt="2018-12-24 10 33 17" src="https://user-images.githubusercontent.com/5126497/50389058-fe3dce00-0767-11e9-90c9-4ac2fa2a2956.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#1198 과 동일한 이슈로 보입니다.

**Comment by pjh0347** [comment]
#1198 과 동일한 이슈로 해당 이슈가 close 되어 본 이슈도 close 처리.
