### ISSUE TITLE
[집계 기능] outlier, anomalies, forecasts, adex 명령어를 사용하기 위해서 필요한 기능입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1202]
## 기능 요청 ##
단위 시간별 집계가 가능한 명령어 또는  API 가 필요합니다.
- anomalies, outliers, forecasts, adex  명령어의  input 데이터를 만들기 위한 집계 데이터 생성 기능
- 피벗에서 제공되지 않는 집계 데이터가 필요한 경우에 사용함
  - 단위시간이 1분으로 된 시계열데이터로부터 시간별 평균을 구할 때, 빠진 1분의 value 값을 0 으로 채워서 평균을 구해야 하는 경우가 있음
  - 현재의 pivot 은 값을 채우는 기능이 없는데, 집계 기능에서는 이 기능이 필요함.
- 사용자가 검색 명령어 창에서 원하는 집계 데이터를 sql, stats 로만 생성하기에는 어렵고, 불가능한 부분도 있기 때문.

## 원하는 솔루션 설명 ##
입력 파라미터 기준으로 집계 데이터를 생성

1. 입력 parameter : 모델이름, 단위시간, 시간필드(yyyymmddhhmmss)이름, event_object 수에 대한 flag(Y/N), 빠진 시간대 채우기(null/채우는값),  그룹필드이름,  [ value필드이름, value 처리 함수]
- 예 :  my_data, 10min, C_DATETIME, Y,0, C_DATETIME
  *  의미 :  
     - 데이터모델 my_data
     - 10min, C_DATETIME  : 필드 C_DATETIME(=> 14자리 시간필드) 기준으로 10분 집계
     - Y : 이벤트건수를  집계함
     - 0, C_DATETIME :  10분동안 데이터가 없는 경우 해당 시간대필드의  count 를 0 으로 채워서 집계 데이터 생성함
     - C_DATETIME : 그룹필드의 이름과 시간필드가 같으므로 10분 단위로 count 를 집계하는 것

- 예 : my_data, 1hour, C_DATETIME, Y, 0, HOST
  *  의미 : 
     - 데이터모델 my_data
     - 1hour, C_DATETIME  : 필드 C_DATETIME(=> 14자리 시간필드) 기준으로 hourly 집계
     - Y : 이벤트건수를  집계함
     - 0 :  1hour동안 데이터가 없는 경우 해당 시간대필드의  count 를 0 으로 채워서 집계 데이터 생성함
     - HOST : 그룹필드의 이름과 시간필드가 다르므로, 시간필드가 생락되었다고 보고, HOST 별 이벤트 건수를 시간(hour) 단위로 집계 
     
- 예 : my_data, 1hour, C_DATETIME, N, 0, HOST, UP_SIZE, AVG
  *  의미 : 
     - 데이터모델 my_data
     - 1hour, C_DATETIME  : 필드 C_DATETIME(=> 14자리 시간필드) 기준으로 hourly 집계
     - N : 이벤트 건수 집계가 아님
     - 0 :  1hour동안 데이터가 없는 경우 해당 시간대필드의  value 값을 0 으로 채워서 집계 데이터 생성함
     - HOST : 그룹필드의 이름과 시간필드가 다르므로, 시간필드가 생락되었다고 보고, HOST 별 houly 집계
     - UP_SIZE, AVG :  value 필드와 value필드를 집계하는 함수가 평균을 의미
     - 전체 의미 :   yyyymmddhh0000, HOST, AVG(UP_SIZE) from my_data group by yyyymmddhh0000, HOST  +   { 빠진 시간대의  yyyymmddhh0000, HOST 별로 0  으로 채우기 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
다른 이슈에서 진행하도록 하고 본 이슈는 닫도록 하겠습니다.
