### ISSUE TITLE
[DB브라우저] SQL order by 동작 오류

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1204]
## 버그 설명 ##
SQL 문에서 order by 를 사용하면 파티션 단위로밖에 작동 안하는 것으로 보입니다.

스크린샷을 보면 USER_ID가 부분적으로 order by가 적용된 것처럼 보입니다.

## 재현하는 방법 ##
여러 파티션의 데이터를 한번에 묶어 order by 사용
(스크린샷 SQL 참조)

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/50671160-87c88800-1013-11e9-99da-20ff7ff48658.png)

## 기타 ##
본 데이터는 1일 단위의 파티션 데이터입니다.

**Comment by anhm** [comment]
@veldise 
확인해본 결과
iplus에서 해당 쿼리를 실행할 경우 정상적인 결과가 출력되는것을 확인하였습니다.

여러가지 테스트를 진행해본 결과 예상으로는 같은 레코드 100개를 반복적으로 출력하는것 같습니다.
웹쪽 내용 확인이 필요한 상태이니다.

**Comment by veldise** [comment]
@anhm 
웹 UI에서는 쿼리 결과에 별도의 변경을 가하지 않는 것으로 알고 있습니다.

@ssm0219 
"부분적으로 order by가 적용된 것"이 어떤 말인지 조금 더 자세히 설명을 부탁드립니다.

**Comment by veldise** [comment]
@anhm
확인 감사합니다. UI에서 스크롤 이벤트 시에 같은 레코드(100개)를 반환하는 버그를 확인했습니다.
금주내로 수정하겠습니다.

**Comment by veldise** [comment]
180번 서버에는 배포 및 해결되었습니다.

**Comment by ssm0219** [comment]
@veldise 
공항철도 배포 일정은 어떻게 되나요?
배포 시 상암에서 진행하시면 되나요?

**Comment by veldise** [comment]
@ssm0219 
배포 일정은 아직 정해지지 않았습니다. 선임님 일정에 맞추려고 하는데 나중에 따로 전화드리겠습니다.
배포는 상암에서 진행해도 됩니다.

**Comment by veldise** [comment]
금일(3/11) 배포로 해결되었습니다.
