### ISSUE TITLE
[보고서] pdf로 저장시 그래프는 저장이 안됨

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1205]
## 버그 설명 ##
보고서 결과화면을 pdf로 저장하는 경우 차트 계열(원형, 막대형 등)은 pdf로 출력되지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서에서 막대 그래프 생성후
2. 보기 버튼 클릭
3. pdf 내보내기 클릭

**Comment by veldise** [comment]
기능 제거되었으므로 닫습니다.
