### ISSUE TITLE
Angora v1 / timeline 명령어 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1206]
## 버그 설명 ##
WEATHER 모델에 대하여 `* | timeline DATE 1d` 명령어 수행시 에러가 반환됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. `WEATHER` 모델 선택
2. 시간 범위를 `2007/01/03 00:00:00 ~ 2008/03/15 00:00:00`로 설정
3. 검색 명령어를 `* | timeline DATE 1d`로 작성
4. 실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/50815057-19f7c580-135f-11e9-91af-2e4a85c62957.png)

## 기타
* 에러 발생한 API: `/iris-timeline`
* 에러 response:
```json
{
  "message": "[SPARK] \ud574\ub2f9 \ud544\ub4dc '`DATE`'\ub294 \uc8fc\uc5b4\uc9c4 \uc785\ub825 \ud544\ub4dc[angora.key, angora.value] \uc5d0 \uc18d\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. ", 
  "type": "<class 'pyspark.sql.utils.AnalysisException'>"
}
```

**Comment by namjals** [comment]
현재 재현되지 않습니다.
![재현되지 않음](https://user-images.githubusercontent.com/22319132/54111449-311e6680-4427-11e9-809a-d91a20aa8b54.png)

**Comment by namjals** [comment]
@veldise 
현재 재현 방법대로 재현 시, 모델 결과에 key, value 필드가 표시되지 않습니다. 
앙고라에서는 key와 value의 필드 정보, 결과값을 반환하는 것으로 확인됩니다.
확인요청 드립니다.
![image](https://user-images.githubusercontent.com/22319132/61849533-8cd82080-aeec-11e9-83ca-88098db3bd10.png)

**Comment by veldise** [comment]
@namjals 
왼쪽 패널의 컬럼 목록에서 해당 컬럼이 선택(체크)되어 있어야 오른쪽 그리드 뷰에 해당 컬럼 및 데이터가 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/61857612-74bdcc80-aeff-11e9-9298-02b5ec8162fb.png)

**Comment by namjals** [comment]
현재 정상동작하므로 닫겠습니다.
