### ISSUE TITLE
Angora v2 / 검색시 한글 깨짐

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1207]
## 버그 설명 ##
한글 데이터가 저장된 IRIS-DB 테이블 데이터를 검색시 한글이 ???로 출력됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.100.116 IRIS-WEB 접속 > 데이터 브라우저 화면 진입
2. `school_data` 데이터 모델 선택 (글로벌 테이블, 시간 필드 없음)
3. 검색

## 스크린샷 ##
* 검색 결과 (192.168.100.116)
![image](https://user-images.githubusercontent.com/3411842/50866653-21b27b00-13ee-11e9-8228-a5798d36c98a.png)

* DB 조회 화면에서 SQL SELECT 결과
![image](https://user-images.githubusercontent.com/3411842/50866737-88d02f80-13ee-11e9-976c-fd36724e1fc7.png)

## 기타
* 수신받은 데이터(response) 일부:
```json
{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [
    { "grouped": false, "type": "TEXT", "name": "ID" }, 
    { "grouped": false, "type": "TEXT", "name": "NAME" }, 
    { "grouped": false, "type": "TEXT", "name": "CLASSIFICATION" }, 
    { "grouped": false, "type": "REAL", "name": "LATITUDE" }, 
    { "grouped": false, "type": "REAL", "name": "LONGITUDE" }
  ], 
  "isEnd": true, 
  "results": [
    [ "B000025726", "????????", "???", 36.92648648, 127.0517466 ], 
    [ "B000002533", "??????", "????", 35.11429749, 129.0825604 ], 
    [ "B000026689", "???????", 
```

**Comment by sonchanseung** [comment]
@veldise 
116번 서버에 model 명령어로 직접 테스트 해 본 결과, results 에 unicode 로 데이터가 정상적으로 들어가는 것을 확인했습니다. 다른 가능성은 Sherman 에서 데이터를 전달할 때 문제가 있을 수 있을 것 같습니다. 확인 부탁드립니다.

**Comment by veldise** [comment]
@sonchanseung 
sherman WAS 에서 UTF8 처리가 누락된 것을 확인하였습니다. 금일중으로 수정하겠습니다.

**Comment by veldise** [comment]
116번 서버에서 해결되었습니다. 이슈 닫습니다.
