### ISSUE TITLE
Angora v1 / stats 명령어를 iris-figure 요청시 에러 반환

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1208]
## 버그 설명 ##
 stats 명령어를 iris-figure 요청시 에러를 반환합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.100.180 IRIS-WEB 접속 > 데이터 브라우저 화면 진입
2. `school_data` 모델 선택 (글로벌 테이블, 시간 필드 없음)
3. `* | stats avg(LATITUDE) by CLASSIFICATION`를 검색어로 입력
4. 검색 실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/50866769-b61cdd80-13ee-11e9-9eed-e6468aa9d015.png)

**Comment by leehaejoon** [comment]
@EricLeeMbg @pjh0347 @namjals 

stats 명령어에서 내부적으로 SQL을 생성해낼때,

Group by 절에 오는 컬럼에 대해 "AS" 라는 문자열 기준으로 split하고있었습니다.

따라서 CLASSIFICATION 이 CL, SIFICATION으로 쪼개져서 발생한 이슈입니다.

해당 부분 조치해 PR 생성하였습니다.

https://github.com/mobigen/B-IRIS-Data-Discovery-Service/pull/55

**Comment by leehaejoon** [comment]
@EricLeeMbg @pjh0347 @namjals 

stats 명령어에서 내부적으로 SQL을 생성해낼때,

Group by 절에 오는 컬럼에 대해 "AS" 라는 문자열 기준으로 split하고있었습니다.

따라서 CLASSIFICATION 이 CL, SIFICATION으로 쪼개져서 발생한 이슈입니다.

해당 부분 조치해 PR 생성하였습니다.

https://github.com/mobigen/B-IRIS-Data-Discovery-Service/pull/55

**Comment by pjh0347** [comment]
iris-figure REST API 가 삭제되었고, 해당 기능을 model 명령어로 대체하여 정상적으로 동작하므로 이슈를 닫습니다.
