### ISSUE TITLE
[고급시각화] line plot 차트날짜구간 오류

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1209]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
[고급시각화] -[꺽은 선형그래프] 에서 

분석 시간이 아닌 구간을 조회해서 실제 조회 구간이 보이지 않습니다. 
<img width="1325" alt="2019-01-15 3 33 25" src="https://user-images.githubusercontent.com/36151180/51162857-060e0f80-18db-11e9-8bf4-1cbd552606a0.png">

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
<img width="1668" alt="2019-01-15 3 21 33" src="https://user-images.githubusercontent.com/36151180/51162659-589afc00-18da-11e9-8ac4-cbe0c8c4b052.png">

동일한 데이터, 구간에 대하여 시계열 분포에서 확인한 내용입니다.
같은구간으로 나와야 합니다.

**Comment by veldise** [comment]
데이터 중에 `collect_date` 값이 `null`인 레코드가 있어 발생하는 문제로 확인되었습니다.
null 값을 0으로 처리해서 발생하는 문제입니다.

**Comment by veldise** [comment]
문제 해결하여 180번에 패치 완료했습니다.
