### ISSUE TITLE
[참고 : R-studio 사용 가이드] B-IRIS에서 R-studio quit 가이드

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1211]
####  **(1) R-studio console에서  작업이 끝난 후에 q() , quit()  로 세션을 빠져나오면**, 
* 이 때까지 작업한 workspace 의 image 를 저장할 건지 묻는다 .
* Y (yes) 엔터 -> ::getwd() 디랙토리에 .RData 파일이 저장::된다.
* 그리고 "R Session Ended"  팝업창이 뜨면  "start new session"  을 **클릭하지 말고**  바로 **B-IRIS 의 메뉴창**에서 원하는 메뉴 클릭
	* 만약 new R session  을 시작한다는 버튼을 누르면  R-studio 로그인 창이 뜬다.  =>   다시 R-studio 창으로 로그인되므로 session 을 종료하려면 B-IRIS  메뉴 선택
<img width="804" alt="2019-01-17 8 24 15" src="https://user-images.githubusercontent.com/5126497/51286969-ba717800-1a38-11e9-8459-2c6cafde654a.png">

#### **(2) R-studio 의 session quit 버튼을 누르면**
<img width="787" alt="2019-01-17 9 18 02" src="https://user-images.githubusercontent.com/5126497/51286991-d5dc8300-1a38-11e9-9cc1-cad8350d76d9.png">

<img width="796" alt="2019-01-17 9 18 14" src="https://user-images.githubusercontent.com/5126497/51286997-db39cd80-1a38-11e9-9c77-b5b32f27a0c4.png">

	  
## 시간이 오래 걸리는 R 작업(예: 딥러닝 모델 학습 등) 을 해야 할 때는
* R script 코드 안에  시간이 오래 걸리는 작업 후 실행 코드 후반에 그 때까지의 모든 이미지를 save.image(..)  로 별도의 파일 이름으로 저장하는 코드를 넣는다. 
* 스크립트의 실행은 R-studio 의 terminal 에서 백그라운드 실행 시킨 후, PC 에서  **B-IRIS 를 로그아웃하지 않고**둔다. 
  * 현재의 버전(2019.01.17) 은 B-IRIS를 로그아웃 하면 R session 이 종료된다.
  * R session 은 빠져 나온 후, 다시 R-studio 메뉴로 들어가도 **B-IRIS 세션이 유지 중이면 백그라운드 실행은 계속**  정상 동작한다.
<img width="748" alt="2019-01-17 9 18 48" src="https://user-images.githubusercontent.com/5126497/51287011-eab91680-1a38-11e9-94e2-fcb586868c11.png">

**Comment by sunghoon** [comment]
개선 사항에 참고 하겠습니다. 이슈 닫습니다.
