### ISSUE TITLE
Angora v2 / HDFS 대상의 모델 search 결과 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1214]
## 버그 설명 ##
`WEATHER`, `BATTING` 모델에 대하여 검색시 타임라인 결과는 나오는데, 검색 결과 raw data는 나오지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 116번 서버에서 root 계정으로 접속
2. `WEATHER` 모델 선택
3. 시간 범위를 `2008/01/09 00:00:00 ~ 2008/05/06 00:00:00`로 설정
    * (`전체 시간`으로 검색 후, 타임라인 차트에서 마우스 드래그로 아무 시간 범위든 설정 후 검색해도 동일)
4. 실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/51462905-20e1f780-1da5-11e9-9c29-617e92af788f.png)

**Comment by namjals** [comment]
시간데이터 포맷이 잘못되었을 가능성을 보고 진행 예정

**Comment by namjals** [comment]
검색하는 시간 데이터 포맷(20080109000000)과 실제 시간 데이터 포맷(2008-01-09)이 달라 생기는 오류로, 포맷이 다를 경우, 실제 시간 데이터 포맷으로 변환하여 처리했습니다.

**Comment by veldise** [comment]
재현됩니다.

![image](https://user-images.githubusercontent.com/3411842/54173821-d1779800-44c6-11e9-9bd6-d30ed2bbbf33.png)

**Comment by namjals** [comment]
@veldise 
180번 서버 확인하였습니다.
![해결됨](https://user-images.githubusercontent.com/22319132/54342365-99678500-467f-11e9-991c-ba4b10bd3abe.png)
