### ISSUE TITLE
Angora v2 / 시간 범위 지정시 검색 결과 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1215]
## 버그 설명 ##
'전체 시간'으로 검색하면 결과가 나오는데, 시간 범위를 지정하면 검색 결과가 없습니다.
최근 생성한 MDT 관련 모델만 해당하는 이슈로 보입니다. syslog는 정상 동작합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 개발 서버(192.168.100.116)에 설치된 IRIS-WEB 접속
2. `PM_RTT_SCORE` 모델 선택
3. 시간 범위를 `2018/11/01 16:00:00 ~ 2018/11/01 18:00:00`로 지정
4. 검색 수행

## 스크린샷 ##
'전체 시간' 범위로 검색 시:
![image](https://user-images.githubusercontent.com/3411842/51649759-19029d00-1fc9-11e9-89b2-ba3d4b34efa0.png)

특정 시간 범위로 검색 시:
![image](https://user-images.githubusercontent.com/3411842/51650356-1bfe8d00-1fcb-11e9-9e61-aa8f41df4bac.png)

## 참고 ##
q: `model name = 'PM_RTT_SCORE' start_date = 20181101160000 end_date = 20181101180000`
```json
{"fields":
   [ { "grouped": false, "type": "TEXT", "name": "PARTITION_DATE" },
     { "grouped": false, "type": "TEXT", "name": "PARTITION_KEY" },
     { "grouped": false, "type": "TEXT", "name": "EVENT_TIME" },
     { "grouped": false, "type": "TEXT", "name": "IMSI" },
     { "grouped": false, "type": "INTEGER", "name": "MCC" },
     { "grouped": false, "type": "INTEGER", "name": "MNC" },
     { "grouped": false, "type": "INTEGER", "name": "ENB_ID" },
     { "grouped": false, "type": "INTEGER", "name": "CELL_ID" },
     { "grouped": false, "type": "REAL", "name": "SYN_ACK_FIRST_TIME" },
     { "grouped": false, "type": "REAL", "name": "ACK_TIME" },
     { "grouped": false, "type": "REAL", "name": "LATITUDE" },
     { "grouped": false, "type": "REAL", "name": "LONGITUDE" },
     { "grouped": false, "type": "INTEGER", "name": "ARTT" },
     { "grouped": false, "type": "REAL", "name": "ARTT_SCORE" },
     { "grouped": false, "type": "INTEGER", "name": "GEOM_LEVEL" },
     { "grouped": false, "type": "TEXT", "name": "GEOM_JSON" } ],
  "results": [] }
```

**Comment by pjh0347** [comment]
@anhm DB 브라우저에서 IRIS 쿼리로 직접 조회해 보니 데이터가 조회되지 않습니다. 확인 부탁드립니다.
```
/*+ LOCATION(PARTITION >= '20181101163000' AND PARTITION < '20181101173000') */ 
SELECT * FROM MDT.PM_RTT_SCORE MLIMIT 10;
```

**Comment by anhm** [comment]
@leehaejoon 

MDT.PM_RTT_SCORE  데이터를 다시 로딩 부탁 드립니다.

**Comment by leehaejoon** [comment]
PM_RTT_SCORE, PM_NPR, PM_CELL_KPI, PM_CELL_CAUSE_DETAIL
상기 4개 테이블에 대하여,

/*+ LOCATION(PARTITION >= ‘20181028000000’ AND PARTITION < ‘20181101170000’)* /
SELECT * FROM MDT.PM_CELL_CAUSE_DETAIL MLIMIT 10;

위 쿼리 제대로 동작하는 것을 확인하였습니다.

**Comment by namjals** [comment]
쿼리 잘못 전달했습니다. 아래가 맞습니다.
```
/*+ LOCATION(PARTITION >= '20181101163000' AND PARTITION < '20181101173000') */ 
SELECT * FROM MDT.PM_RTT_SCORE MLIMIT 10;
```
