### ISSUE TITLE
Angora v2 / metadata API 결과가 무조건 0(zero)입니다.

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1216]
## 버그 설명 ##
지정한 모델, 시간 범위의 파티션 개수를 구하는 metadata API 결과가 무조건 0(zero)입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. `syslog` 등 model을 지정해서 metadata http API 수행
2. response의 `partition_num` 값 확인

## 결과
request url:
```
http://192.168.100.116:6036/angora/metadata?start_date=20181101160000&end_date=20181101180000&datamodel_id=e45aeae4-ef48-4b66-9a58-89ae4cc26060
```
response:
```json
{ "data": { "partition_num": 0 } }
```

**Comment by namjals** [comment]
iris 명령어의 파싱 결과 데이터 포맷이 string에서 dict로 바뀌었는데, 이로인한 예외문제입니다. 수정하였고, 개발 서버 배포 시, 닫겠습니다.
