### ISSUE TITLE
Angora v2 / 모델명에 공백이나 특수문자가 포함되어 있으면 no model 에러 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1217]
## 버그 설명 ##
`1_school_data (2)` 와 같은 모델에 대하여 검색을 수행하면 no model 에러가 반환됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 개발 서버(192.168.100.116)에 설치된 IRIS-WEB 접속
2. `1_school_data (2)` 모델 선택
3. 검색

## 로그 ##
q:
`model name = '1_school_data (2)' start_date = 20190123000000 end_date = 20190123000010 `

response:
```json
{ "message":
   "There is no model name like [ 1 _school_data (2) ], please check model name with [model list] option.",
  "type": "<class 'angora.exceptions.AngoraException'>" }
```

**Comment by pjh0347** [comment]
현재는 모델 명령어에 공백이나 특수 문자는 지원하지 않고 있습니다. 추후 지원하도록 개선후 이슈 닫도록 하겠습니다.

**Comment by seungfwani** [comment]
본 이슈에 대한 내용은 KDN 개발과정에서 개선되어 운영서버(192.168.100.180)에 개선된 상태로 이슈 닫도록 하겠습니다.
