### ISSUE TITLE
[R-studio] 필요한 package를 install 하기 위해  libxml-2.0  가 설치되어 있어야 합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1218]
## 버그 설명 ##
R package "xml2", "tidyverse" 를 install 하기 위해서는 
**libxms-2.0** 이 설치되어 있고
**PKG_CONFIG_PATH** 에 해당 파일이 존재해야 합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'R-studio'
2. console 에서 
install.packages("tidyverse")

## 스크린샷 ##
* R console 에서 package 를 install 하면 발생하는 에러 
<img width="547" alt="2019-01-30 9 28 47" src="https://user-images.githubusercontent.com/5126497/51950149-a3884800-2472-11e9-85bc-8dbf534d1d38.png">

* PKG_CONFIG_PATH 에 설정된 디렉토리에  libxml-2.0 파일이 없는 것 확인함
<img width="936" alt="2019-01-30 9 30 59" src="https://user-images.githubusercontent.com/5126497/51950207-dd594e80-2472-11e9-8df0-63019dcb50f1.png">

## 로그 ##
**Configuration failed because libxml-2.0 was not found**. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file.

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
터미널에서 `yum install -y libxml2-devel` 수행 후 
RStudio에서 `install.packages("tidyverse")`가 잘 수행되는 것을 확인했습니다.

![image](https://user-images.githubusercontent.com/3411842/51953719-c588c700-2480-11e9-8a12-b0764b31830e.png)

RStudio 도커 이미지를 업데이트 한 뒤 패치하도록 하겠습니다.

**Comment by veldise** [comment]
180번에 적용 패치 완료했습니다.

@seoryjj
