### ISSUE TITLE
Angora v2 / timeline 요청시 fields 명령어 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1219]
## 버그 설명 ##
`model-timeline`을 수행할 때 `fields` 명령어를 사용하면 에러가 반환됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 116번 IRIS-WEB 접속
2. syslog 데이터 모델 선택
3. `* | fields DATETIME,HOST` 입력 후 실행

## 기타 ##
`model-timeline name = 'syslog' start_date = 20190130125800 end_date = 20190130125934 unit = 1S | fields DATETIME,HOST`

```js
{ message: 'None of [date, event_count] was selected in [fields].',
  type: '<class \'angora.exceptions.AngoraException\'>' }
```

**Comment by leehaejoon** [comment]
@namjals @EricLeeMbg 

` * | model-timeline name = 'syslog' start_date = 20190130125800 end_date = 20190130125934 unit = 1S | fields date, event_count`

위 명령어는 제대로 동작하는것 확인,
필드명 파싱 과정에서 사용자가 입력하는 필드명을 사용하지 않고 내부에서 관리하는 필드명(date, event_count)을 사용해서 발생하는 이슈로 보입니다.

관련해서
`src/main/python/angora/cmds/impl/fields.py`
92~93번 라인 확인중입니다.

**Comment by namjals** [comment]
@pjh0347 @leehaejoon model-timeline의 결과 dataframe의 컬럼은 항상 date, event_count 입니다. 여기서 DATETIME, HOST를 선택했기때문에, 일치하는 컬럼이 없어 발생한 에러입니다. 
제 생각에 논리적으로 `* | model-timeline name = 'syslog' start_date = 20190130125800 end_date = 20190130125934 unit = 1S | fields DATETIME,HOST` 는 없는 컬럼에 대해 쿼리를 했으므로 에러가 맞습니다. 
그러나  `* | fields DATETIME,HOST`를 실행하면 자동으로 위의 잘못된 model-timeline을 수행하기 때문에 문제가 됩니다. ('*' 수행 시, model, model | count, model-timeline을 수행)
특정 명령어(fields 등)에 대해 model-timeline을 수행하는 경우 예외처리는 `https://github.com/mobigen/B-IRIS-Data-Discovery-Service/blob/master/src/main/python/angora/interface/restful/handlers/query.py`의 `def transform_query`에서 하고 있습니다. 이 부분은 저도 디버깅을 해봐야해서 진행 하시다가 어려운 부분있으면 말씀주세요.

**Comment by pjh0347** [comment]
#1198 과 동일한 이슈로 해당 이슈가 close 되어 본 이슈도 close 처리.
