### ISSUE TITLE
데이터 브라우저 / 보고서 / UI의 간격이 세로 높이에 따라 달라지는 문제

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1220]
## 버그 설명 ##
* 데이터 브라우저 - 보고서 - 시각화 옵션 - 데이터탭
* UI의 간격이 세로 높이에 따라 달라지는 문제

## 재현하는 방법 ##
* 데이터 브라우저 - 보고서 메뉴
* 영역 객체 생성 후 속성 탭에서 시각화 유형을 꺾은선형으로 변경
* 시각화 옵션 클릭 후 데이터 탭 선택

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/52398333-feb5dc80-2afb-11e9-9239-f75fd6bed21d.png)

## 기타 ##
* 항목간의 세로 간격이 서로 붙어 있는 형태로 조절 되어야 할 것 같습니다.
* 해당 이슈는 모든 시각화 유형에서 발생합니다.
* 구두로 상황 및 재현 방법 전달 했으며 업무화를 위해 이슈 작성 합니다.

**Comment by veldise** [comment]
`<table>` 태그를 사용한 구조에 한계가 있어 js로 해결할 수 있는지 확인해보기로 결정되었습니다.

**Comment by veldise** [comment]
table row(`<tr>`)을 show/hide 하는 방식(`ng-show`)이 아니라 추가/삭제하는 방식(`ng-if`)으로 변경해야 합니다.

**Comment by tylor-kr** [comment]
https://github.com/mobigen/B-IRIS-Data-Discovery-Web-Service/pull/1273/commits/b134b20fdd846aa6583f2bcf881e3b8cef14bfab
