### ISSUE TITLE
검색 기능에서 datetime function사용시 오류 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1221]
## 버그 설명 ##
검색기능에서 일부 sql function 은 사용 가능함.
datetime function 사용시 오류 발생

현재 sql을 사용한 조회시에 정상적으로 동작하는 function과 동작하지 않는 function은 어떤 것들이 있는지 확인 요청드립니다.

## 재현하는 방법 ##
아래 스크린샷 참조

## 스크린샷 ##

[round function 사용 가능]
![image](https://user-images.githubusercontent.com/4444717/52460801-7b55c300-2baf-11e9-8381-1e5aad7ab774.png)

[datetime function 사용시 에러발생]
![image](https://user-images.githubusercontent.com/4444717/52460823-8e689300-2baf-11e9-9487-1e31b19c429c.png)

[query실행시 정상적인 조회 가능]
![image](https://user-images.githubusercontent.com/4444717/52460866-c40d7c00-2baf-11e9-8122-beb27af2abc7.png)

**Comment by namjals** [comment]
앙고라는 내부적으로 spark sql을 사용하고 있습니다.
round는 지원하고 있고, datetime은 지원하지 않습니다.
아래 사이트는 spark sql에서 지원하는 함수목록입니다.
https://docs.databricks.com/spark/latest/spark-sql/language-manual/functions.html#round

datetime처럼 사용할 거라면 아래 쿼리를 참조해주세요. syslog 모델을 사용했습니다.
`* | sql "select round(unix_timestamp(DATETIME, 'yyyyMMddHHmmss')/10000000 - 11644473600, 0) as newdate FROM angora"`
`* | sql "select date_format(cast(unix_timestamp(DATETIME, 'yyyyMMddHHmmss')/10000000 - 11644473600 as timestamp), 'yyyy-MM-dd HH:mm:ss') as newdate FROM angora"`

spark sql 지원여부와 상관없이 angora의 sql 명령에서는 아래 명령어를 지원하지 않습니다.
`group by, order by, having, union, intersection, except`
