### ISSUE TITLE
[보고서] 공유받은 보고서를 복제 했을 때 '데이터 모델' 설정이 누락되어 복제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1226]
## 버그 설명 ##
공유받은 보고서를 복제하고 '수정'에 들어가면, 접근 권한이 있는 데이터모델인데도 불구하고 데이터모델 란이 공란으로 표시됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
테스트 계정: ssm0219
1. 보고서 'SYSLOG 수집현황:latest'와 데이터모델 'tylor-syslog'를 공유받은 상태
2. [보고서]에서 'SYSLOG 수집현황:latest'를 복제
3. 복제된 보고서 'SYSLOG 수집현황:latest (2)'의 '수정'을 눌러 수정 화면으로 이동
4. '이벤트 개수의 평균' 이란 텍스트 바로 아래에 있는 영역을 클릭하면 우측 바 '데이터 모델' 드롭다운 메뉴에 '--데이터 모델--'이라고 표시되어 있고, '실행'버튼을 누르면 '데이터 모델이 없습니다.' 라는 오류 메시지가 표시됨

## 예상한 행동 ##
'데이터 모델' 드롭다운 메뉴에 'tylor-syslog'가 표시되어서 '실행' 버튼을 누르면 바로 실행되어야 한다고 생각함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/52546682-cd435680-2e04-11e9-9cb4-33f48cfb4cc8.png)

**Comment by tylor-kr** [comment]
복제한 보고서 `SYSLOG 수집현황:latest` 에서 `이벤트 개수의 평균` 바로 아래에 있는 영역에서 사용하는 데이터 모델은 `syslog` 입니다.

테스트 계정 `ssm0219` 에 경우 `sysglog`를 공유 받지 않았기 때문에 위처럼 나오는 것이 정상 입니다.
`tylor-syslog`는 해당 보고서에서 사용되지 않습니다.

![image](https://user-images.githubusercontent.com/13827425/52604334-ce7c8e00-2ead-11e9-83cf-af3234df7632.png)

**Comment by ssm0219** [comment]
@tylor-kr 

보이는 결과가 같길래 같은 데이터인줄 알았습니다. 
답변 감사합니다.
