### ISSUE TITLE
[검색] '날짜 및 시간 범위'로 시작시간과 종료시간 특정하면 조회가 안됨

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1228]
## 버그 설명 ##
보고서에서 '테이블'을 생성하고 해당 테이블에 표시할 데이터 모델의 시간을 '시간 설정' 에서 기간을 특정하여 '사이 시간 범위'로 설정하였는데, 조회 되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

재현 대상 테이블: BATTING_DB.BATTING
재현 대상 데이터모델: BATTING_SSM
재현 당시 계정: ssm0219

1. [검색]에서 데이터 모델 BATTING_SSM 선택
2. [시간]에서 시작 시간과 종료 시간을 2016/05/01 ~ 2016/05/31 로 설정
5. [실행] 버튼을 누르면 스크린샷처럼 표시됨

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/52553186-1526a580-2e26-11e9-955d-921b4d5a8ec1.png)

**Comment by veldise** [comment]
#1214 와 동일한 이슈로 생각됩니다.

**Comment by pjh0347** [comment]
본 이슈 등록 시점과 현재 시점 사이에 angora 코드에 상당히 많은 변화가 있었습니다.
(REST API 변경 및 KDN 개발 적용 등)

그래서 현 시점에서, 본 이슈에 대해 증상 부터 다시 확인해 볼 필요가 있다고 생각합니다.

========================== 증상 ===========================
1. 최초 언급된 위 조건으로 재현을 해보면 타임라인과 raw 테이블 모두 빈 값으로 출력됩니다.
2. 또한 시간 조건을 아래와 같이 주었을 때 비정상적인 결과가 출력됩니다.
`2015/08/01 00:00:00 ~ 2018/08/01 13:29:22` 조건으로 검색하면 결과가 나오고,
`2015/08/01 00:00:00 ~ 2017/08/01 13:29:22` 조건으로 검색하면 결과가 안나옴.

**Comment by seungfwani** [comment]
19/08/09 11시 35분에 UI의 `DB조회>DB 브라우저` 를 통해서 `EVA.SYSLOG` 데이터를 조회해 보았습니다.

검색 쿼리는 다음과 같습니다.
```/*+ LOCATION ( PARTITION >= '20160808150000' AND PARTITION <= '20180809115959' ) */
SELECT
*
FROM
EVA.SYSLOG
limit 10
;
```
![image](https://user-images.githubusercontent.com/46172579/62750060-b28f2900-ba99-11e9-8cdd-b7f4a1c37248.png)

![image](https://user-images.githubusercontent.com/46172579/62750038-a5723a00-ba99-11e9-885b-64c45fc16739.png)

**Comment by seungfwani** [comment]
@pjh0347 
19/08/09 11시 35분에 UI의 `DB조회>DB 브라우저` 를 통해서 `EVA.SYSLOG` 데이터를 조회해 보았습니다.

각 그림에 대한 검색 쿼리는 다음과 같습니다.

```/*+ LOCATION ( PARTITION >= '20160808150000' AND PARTITION <= '20180809115959' ) */
SELECT
*
FROM
EVA.SYSLOG
limit 10
;
```
![image](https://user-images.githubusercontent.com/46172579/62750060-b28f2900-ba99-11e9-8cdd-b7f4a1c37248.png)

```/*+ LOCATION ( PARTITION >= '20160808150000' AND PARTITION <= '20180809125959' ) */
SELECT
*
FROM
EVA.SYSLOG
limit 10
;
```
![image](https://user-images.githubusercontent.com/46172579/62750038-a5723a00-ba99-11e9-885b-64c45fc16739.png)

데이터가 존재하는 `2018/08/09 12시경` 데이터를 포함(2016/05/01 ~ 2018/08/09 12:59:59)하여 검색해 보았을 때는 다음과 같이 검색이 됩니다.
![image](https://user-images.githubusercontent.com/46172579/62750238-6a243b00-ba9a-11e9-834f-86a17bcf228b.png)

최초 이슈 내용인 `model-timeline` 은 결과가 있는데 `model`은 결과가 없는 현상은 발생하지 않는 것으로 확인되며,

박진호 선임님의 증상확인에 대해서는 
코멘트를 작성하신 시점에 `EVA.SYSLOG`의 데이터가 `2018/08/01` 부터 존재하던 데이터가
현재는 `2018/08/09 12:00:00` 이후 데이터만 존재하는 것으로 확인됩니다.

**Comment by seungfwani** [comment]
최초 이슈 내용은 #1214 이슈와 함께 해결이 되었습니다.

코맨트에 박진호 선임님의 증상에 대해서는

IRIS DB에 저장되어있는 `BATTING_DB.BATTING` 테이블의 파티션이 `20171201000000` 에 저장이 되어있어서,

조건1(`2015/08/01 00:00:00 ~ 2018/08/01 13:29:22`) 에서는 파티션이 포함되어 있어 데이터 조회가 가능하였고,

조건2(`2015/08/01 00:00:00 ~ 2017/08/01 13:29:22`) 에서는 파티션이 포함되지 않았기 때문에 데이터 조회가 되지 않습니다.

`BATTING_DB.BATTING` 정보 조회 결과 사진입니다.
![image](https://user-images.githubusercontent.com/46172579/62763303-26dfc180-bac6-11e9-9c0f-23e040c54487.png)

**Comment by seungfwani** [comment]
최초 이슈는 재현되지 않기 때문에 이슈 닫겠습니다.
