### ISSUE TITLE
검색기능에서 sql 사용시 instr 실행결과가 맞지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1229]
## 버그 설명 ##
아래 두개 실행 결과가 동일하게 나옴

 1. instr(IMAGE_PATH,'\')
 2. instr(substr(IMAGE_PATH,-15),'\') 

## 재현하는 방법 ##
[검색 실행]
* | sql "select IMAGE_PATH, instr(IMAGE_PATH,'\') as instr_1, instr(substr(IMAGE_PATH,-15),'\') as instr2, substr(IMAGE_PATH,-15) as val_a, substr(substr(IMAGE_PATH,-15) , instr(substr(IMAGE_PATH,-15),'\')+1,15) as VAL from angora " 

## 예상한 행동 ##
1번 실행시의 결과값과 2번 실행시의 결과값이 다르게 나와야함, 실제 '\' 문자의 위치 반환

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/52552407-713bfa80-2e23-11e9-9d98-c0de61059e34.png)

**Comment by leehaejoon** [comment]
@EricLeeMbg @namjals @pjh0347 

본 이슈에서 언급된 `instr(IMAGE_PATH,'\')` 함수를 포함한 모든 함수에서,
역슬래시 (\\) 를 제대로 파싱하지 못하는 이슈가 있는 것으로 보입니다. 

`angora/cmds/impl/sql.py` 파일의 81번 라인 부근을 보면,
`clauses = self.new_parser.parse(raw_args, lexer=self.lexer)` 부분이 있는데요,

이 때, 파서가 문법을 체크하는 과정에서 역슬래시를 문자열로 인식하지 못하고 걸러내는 것으로 보입니다.

**Comment by EricLeeMbg** [comment]
mobigen/B-IRIS-Data-Discovery-Service/#41
테스트 결과화면
![hdfs처리결과1](https://user-images.githubusercontent.com/44352311/56177613-354b2e80-603a-11e9-9217-f31a5de179d1.jpg)
![hdfs처리결과2](https://user-images.githubusercontent.com/44352311/56177616-37ad8880-603a-11e9-8dc9-5efc55ad8454.jpg)

**Comment by leehaejoon** [comment]
@EricLeeMbg @namjals @pjh0347


결론부터 말씀드리면, 현재는 다음과 같이 백슬래시를 네 번 입력해야 쿼리가 제대로 동작하는 것을 확인했습니다.

`| sql "select substr(IMAGE_PATH, -15) as substr_1, instr(substr(IMAGE_PATH, -15), '\\\\') as instr_1 from angora "`

<img width="972" alt="스크린샷 2019-05-16 오후 1 54 22" src="https://user-images.githubusercontent.com/23020977/57827392-221ab280-77e2-11e9-9290-0f1801368c36.png">

<br/>

원인을 설명드리겠습니다.

1. 우선, spark에서 백슬래시를 문자열로 인식시키기 위해서는 다음과 같이 백슬래시를 한 번 더 입력해 escape 해주어야 합니다. 그렇지 않으면 에러가 발생합니다.

- 에러

![스크린샷 2019-05-16 오후 1 50 23](https://user-images.githubusercontent.com/23020977/57827228-91dc6d80-77e1-11e9-95ef-167d97e52907.png)

- 정상

![스크린샷 2019-05-16 오후 1 49 59](https://user-images.githubusercontent.com/23020977/57827212-825d2480-77e1-11e9-99c7-a88930a11991.png)

즉, B-IRIS 웹에서도 다음과 같이 백슬래시를 두 번 사용하는 형태로 쿼리가 전달되어야 한다는 결론에 도달하는데요.

`| sql "select substr(IMAGE_PATH, -15) as substr_1, instr(substr(IMAGE_PATH, -15), '\\') as instr_1 from angora "`

<br/>

하지만, 현재 위 쿼리를 날리면 다음과 같은 에러가 발생 합니다.

<img width="800" alt="스크린샷 2019-05-16 오후 1 47 54" src="https://user-images.githubusercontent.com/23020977/57827160-3b6f2f00-77e1-11e9-9f09-2bd78df607be.png">


중요한 부분만 좀 더 자세히 보겠습니다. 

<img width="412" alt="스크린샷 2019-05-16 오후 1 49 25" src="https://user-images.githubusercontent.com/23020977/57827198-707b8180-77e1-11e9-9f24-a40d5b91ec61.png">

보시다시피 angora에서 spark으로 문자열을 넘겨줄때 중간에서 다시 백슬래시 하나를 제거하고 보내기 때문입니다.

즉, 두 개의 백슬래시를 spark으로 온전히 전달하기 위해,

사용자 입장에서는 맨 처음 보여드렸던 바와 같이 총 네 개의 백슬래시를 사용해야 한다는 결론에 도달합니다.

`| sql "select substr(IMAGE_PATH, -15) as substr_1, instr(substr(IMAGE_PATH, -15), '\\\\') as instr_1 from angora "`

이러한 이유로 네 개의 백슬래시를 사용해 동작시키면 원하는 결과를 받아 볼 수 있으나,

과연 사용자 입장에서 수용될 수 있는 부분인가에 대해서는 담당자간 협의가 필요할 것으로 보입니다.

**Comment by seungfwani** [comment]
이해준 선임님께서 말씀해주신 바와 같이 백슬래시에 대한 문제입니다.
하지만 제시하신 문제처럼 백슬래시 4개를 써야하는 불편함은 사용자 입장에서 수용하기 힘든 것으로 보입니다.

따라서 백슬래시 문제는 다음과 같이 수정 하였습니다.
사용자는 백슬래시 문자를 sql 쿼리로 쓸 때 두개를 쓰도록 합니다.
  - 백슬래시는 python에서 escape 문자로 `'\'` = `''`  와 같습니다.
  - 따라서 백슬래시 문자 자체를 원할 때는 `'\\'` 와 같은 형태로 써야합니다.

해당 부분은 운영서버 배포 예정입니다.

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하였습니다.
위에 설명처럼 `\` 문자를 처리하기 위해 사용자는 `\\`를 사용하여야합니다.

![image](https://user-images.githubusercontent.com/46172579/63915122-222c7e80-ca70-11e9-9f91-e39f84c801ec.png)
