### ISSUE TITLE
[보고서] 리스트의 unique 값 출력 필요

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1230]
## 기능 요청 ##
보고서의 '리스트'에서 표시되는 값들은 distinct 한게 좋을 것 같습니다.

## 원하는 솔루션 설명 ##
(ssm0219 계정으로 만든 보고서 'BATTING_github' 참고하시면 이해하기 더 편하실 겁니다.)

팀ID 리스트를 통해, 조회하고자 하는 팀을 선택해서, 해당 팀의 전체 출전 횟수를 보여주는 보고서를 생성하고자 함

이 때, 스크린샷에서와 같이 리스트에 표시되는 팀ID가 중복되어 표시됨
적어도 리스트에서 표시될 땐 distinct 가 적용된 unique한 값들만 표시되어야 활용이 편할 것으로 판단됨

## 기타 ##
- 스크린샷
![image](https://user-images.githubusercontent.com/35832986/52602951-e94c0400-2ea7-11e9-9dce-556ce9b89567.png)

**Comment by veldise** [comment]
해결되어 닫습니다.

다만, 이벤트 값 전달 설정에서 "값 필드" 설정에 따라 중복된 값이 나타날 수 있습니다.
이유는 목록에 표현되는 텍스트는 같으나 "값 필드"의 컬럼값이 다를 경우,
사용자가 의도하지 않은 동작이 발생할 수 있기 때문입니다.
