### ISSUE TITLE
[보고서] 시각화로 저장된 원형 차트가 표시되지 않음

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1232]
## 버그 설명 ##
시각화로 저장한 원형 차트를 보고서에서 읽어 실행하면 실행되지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [보고서]에서 '새 보고서' 클릭
2. 임의의 영역을 생성한 후 '불러오기'로 시각화 "BATTING_선수별_득점비율" 적용
3. [실행] 버튼 클릭하면 스크린샷처럼 오류메시지 없이 하얗게만 표시됨

## 예상한 행동 ##
[고급시각화]에서 실행한 것과 같은 원형 차트가 표시됨

## 스크린샷 ##
- [고급시각화]에서 보이는 화면
![image](https://user-images.githubusercontent.com/35832986/52613974-7062a180-2ed3-11e9-96e1-d8b302e196a9.png)

- [보고서]에서 보이는 화면
![image](https://user-images.githubusercontent.com/35832986/52614085-d818ec80-2ed3-11e9-8bdc-0fb4e116a423.png)

**Comment by veldise** [comment]
확인 결과, 불러오기를 수행하면 그룹과 크기가 서로 반대로 설정되는 것으로 보입니다.

**Comment by veldise** [comment]
#1234 와 유사한 이슈입니다.
현재 시각화를 불러올 때에는 시각화 정보를 시각화 옵션 - 데이터 탭의 설정에 적용하지 않습니다.

**Comment by veldise** [comment]
설명이 된 것으로 보고 닫습니다. (오래된 이슈)
