### ISSUE TITLE
[보고서] 게이지 차트 비정상적으로 작동

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1233]
## 버그 설명 ##
2019.02.12 17:13 에 진행한 보고서 작성 시 발생한 게이지 차트의 수치가 이상하여 확인 부탁드립니다.

## 재현하는 방법 ##
스크린샷을 통해 재현 옵션을 확인하실 수 있습니다.

테스트 계정: ssm0219

## 스크린샷 ##
1) 게이지 차트의 그림과 수치의 불일치
![image](https://user-images.githubusercontent.com/35832986/52621076-bc204580-2ee9-11e9-9004-ddad2657c1f1.png)

2.54%인데 게이지는 거의 80%로 보임

2) 비정상적으로 큰 수치
![image](https://user-images.githubusercontent.com/35832986/52621171-fc7fc380-2ee9-11e9-9514-29274dd612b5.png)

특정 Agent의 최근 1분 메모리 소요량을 확인하고 싶어서 그려보았는데, 퍼센테이지가 아닌 실제값이 표시되는 것으로 보임

**Comment by veldise** [comment]
@ssm0219 
현재 게이지 차트는 0~100 사이의 단일 수치 결과로만 설정해야 합니다.
아래와 같이 검색 결과가 1개여야 합니다.

![image](https://user-images.githubusercontent.com/3411842/52621920-de1ac780-2eeb-11e9-89a2-dcde48114f16.png)

**Comment by ssm0219** [comment]
@veldise 

설명하신대로면 0 ~ 1 사이의 단일 값만 표시되도록 전처리가 필요하고,
SMS 데이터들은 게이지 차트로 표시하기에 적절치 않다는 말씀으로 이해하면 될까요?

**Comment by veldise** [comment]
@ssm0219 
0 ~ 1이 아니고 0 ~ 100입니다.
네 전처리라고 하셨는데 검색어나 SQL을 작성해서 결과를 조정해야 합니다.

데이터 결과의 특정 셀값을 게이지 차트로 표현하는 것은 추가 개발이 필요합니다.

**Comment by ssm0219** [comment]
@veldise

답변 감사합니다 👍
