### ISSUE TITLE
[보고서] 주기 설정에 의해 갱신 시 <%= %>로 선택된 항목값 미반영

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1234]
## 버그 설명 ##
스크린샷을 통해 설명

## 재현하는 법 ##
테스트 계정: ssm0219
테스트 보고서: BATTING_github(2)

## 스크린샷 ##
1) 보고서를 실행했을 때 초기 화면
![image](https://user-images.githubusercontent.com/35832986/52622048-30f47f00-2eec-11e9-9c8a-535a019fc515.png)

2) 좌측 팀ID 리스트를 클릭했을 때의 화면
![image](https://user-images.githubusercontent.com/35832986/52622073-45d11280-2eec-11e9-9dc2-8db6bca714da.png)

3) 설정한 갱신 주기가 지나거나 '즉시 실행'을 누르면 다시 1)의 화면으로 돌아간다.

## 예상되는 행동 ##

갱신하더라도 리스트에 선택된 팀ID 값은 유지된 체로 갱신되어야 한다고 생각함

**Comment by sunghoon** [comment]
연결된 이슈로 해결 되었다고 보고 본 이슈는 닫습니다.
