### ISSUE TITLE
[보고서] 꺾은선 그래프의 y축 데이터 컬럼 정보가 해지됨

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1236]
## 버그 설명 ##
맵(지도) 의 이벤트값 전달을 설정한후
전달받은 데이터를 이용하여 그래프를 그린후 (y축 데이터 컬럼 지정)

편집모드에서 지도의 point를 클릭할 경우 그래프 영역에 설정해 두었던 y축 컬럼 정보가 해지되는 현상이 존재함

## 재현하는 방법 ##
동작을 재현하는 방법 :
저장되어 있는 보고서: MDT_JP  에서
왼쪽 맵(지도)에서 mesh를 선택시 중앙의 맵(지도) 에 point가 나오는데,
이때 point를 클릭하면 오른쪽에 있는 꺾은선 그래프의 y축 항목이 사라짐.

**Comment by veldise** [comment]
현재는 "시각화 옵션 > 데이터 탭" 설정을 유지하도록 다소 개선한 상태입니다.
재현되면 이슈 reopen 바랍니다.
