### ISSUE TITLE
[보고서] 초기 이벤트를 이용한 설정에서 초기 설정값 적용

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1238]
## 기능 요청 ##
이벤트 값 전달 기능을 이용시 초기 값 지정

## 원하는 솔루션 설명 ##
이벤트값 전달 설정을 이용하여 화면을 구성시
처음 실행할 경우 이벤트가 없기 때문에 화면의 대부분이 회색으로 표시되고 있습니다.

처음에 회색으로 나오지 않고, 임의의 값을 표시해 주는 방법이 존재하면 좋을것 같습니다.

## 기타 ##
중요도 낮음.

**Comment by sunghoon** [comment]
개선 사항에 참고 하겠습니다. 이슈 닫습니다.
