### ISSUE TITLE
샘플링 기능 추가에 따른 데이터모델 검색시 기간별 조회 불가 이슈

### ISSUE THREAD

**Issue by beobest2** [mobigen/IRIS-BigData-Platform#1240]
## 버그 설명 ##

__sampling 테이블을 웹상에서 기간 조회할 경우 데이터가 0건
전체 조회시에만 데이터가 조회됨

* {원본_테이블명}__SAMPLING 인 테이블의 특이사항 
    - 블록 파일의 PARTITION에 입력되는 값이 데이터 노드마다 모두 동일
    - 샘플링 테이블은 공통적으로 _PARTITION_KEY, _PARTITION_DATE 컬럼을 가지고 있음

따라서 __SAMPLING이 붙은 테이블의경우 앙고라에서 기간별 조회 명령시 입력되는 기간 HINT option 대신에
WHERE문에서 _PARTITION_DATE를 통해 필터링할 수 있도록 로직 추가 필요

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 데이터모델 검색에서 "jp_mesh_sampling_test" 모델 선택(JP_MESH_SUMMARY_STREAM__SAMPLING 테이블로 생성한 모델)
2. 시간을 최근 24시간으로 선택 후 조회시 데이터가 없다고 출력
3. 전체로 시간을 설정한 경우 최근 시간의 데이터를 포함하여 정상 출력 

## 예상한 행동 ##
실시간 로딩중인 데이터이므로 최근 N시간 기간 설정후 조회시 데이터가 출력되어야함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7010554/52763660-07f4fb00-3060-11e9-8c65-8db551526f85.png)

**Comment by namjals** [comment]
@anhm 
8월에 개발된 `샘플 테이블 조회` 인터페이스는 아래와 같습니다.

종류 | 인터페이스 | 예제
-- | -- | --
angora - spark_on_iris | .option('hint', {파티션 값}) .option('samplingTable',{True or False}) | .option('hint', None). option('samplingTable', True)
angora - irisdb | /\*+ USE_SAMPLING_TABLE,LOCATION({파티션 값})\*/ {SQL 쿼리} | /\*+ USE_SAMPLING_TABLE,LOCATION((PARTITION = '20190808100000' AND KEY = '0'))\*/ SELECT SUBSTR(DATETIME, 0, 15), COUNT(*) AS value FROM EVA.SYSLOG WHEREDATETIME>= '20190808100900' ANDDATETIME< '20190808101126' GROUP BY SUBSTR(DATETIME, 0, 15)

WHERE문에서 _PARTITION_DATE를 통해 필터링할 수 있도록 로직 추가를 해야하는지 문의드립니다.

현재 해당 이슈의 모델(jp_mesh_sampling_test)의 경우 재현이 되며, 8월 개발 시 생성된 샘플 데이터에 대해서는다시 테스트해보니 위의 인터페이스로 동작하고 있습니다.

쿼리 속도가 너무 느린 부분이 있어, 이 부분은 확인후 재문의드리겠습니다.

**Comment by anhm** [comment]
@namjals 
해당 이슈는 IRIS-DB에서 sampling을 만들기 위한 구조상 발생한 이슈입니다.

sampling을 위하여 하나의 파일로 데이터를 처리하기 위해 만들어진 블럭 파일의 크기가 너무 커져 발생한 이슈입니다.
