### ISSUE TITLE
MDT 데이터를 불러올 경우 데이터 쏠림 현상

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1241]
## 이슈 설명 ##
MDT 데이터를 불러올 경우 데이터가 많아 일부 데이터만 불러와 지는데,
이 경우 상위 몇개만 불러오는 것으로 보임

이 경우 화면 전체적으로 데이터가 나오지 않고, 일정 부분에 쏠리는 현상이 존재함

이를 해결하기 위한 방안이 필요

MDT 데이터를 조회할때 IRIS에 where절을 사용자가 입력할 수 있는 방안을 제공해줄 필요가 있음
이 경우  where 절을 통해 사용자가 임의의 값을 가져올수 있음

**Comment by veldise** [comment]
@anhm 
금주 초 기준으로는 화면에서 상위 200개 데이터만 제한하여 불러오고 있던 것을
현재는 상위 10,000개 데이터를 불러오도록 하고 있습니다.

그리고 where절은 Angora의 `search` 명령어 등의 필터 기능으로 처리가능할 것으로 보입니다.

위 내용에 대해 의견 바랍니다.

**Comment by anhm** [comment]
일반 쿼리를 사용할 경우 rowid라는 숨겨진 컬럼을 이용합니다.
그래서 아래와 같이 쿼리를 작성합니다.
```
```
angora 명령어를 이용해본 결과

* | where rowid

**Comment by veldise** [comment]
@anhm 
숨겨진 컬럼이라면 현재 버전으로는 불가능하고 별도의 angora 명령어가 필요할 것 같습니다.

@pjh0347

**Comment by sunghoon** [comment]
데이터 불러오는 count 조정 기능이 최근 반영된것으로 알고 있습니다. 해당 이슈는 닫겠습니다.
