### ISSUE TITLE
[보고서] 꺾은선형 데이터 Y축 모두 선택 이슈

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1242]
## 버그 설명 ##
보고서에서 꺾은선형 데이터 Y축의  '모두 선택' 을 이용할 경우 
데이터가 없습니다. 에러가 발생함

## 재현하는 방법 ##

보고서 MDT_JP_2 의 아래쪽 영역에 있는 그래프

```
/*+ BYPASS,
 LOCATION (
PARTITION >= '20190129000000'
AND
PARTITION < '20190131000000' )
*/
SELECT
sum(ok_count) as ok_count,
sum(fail_count) as fail_count,
sum(drop_count) as drop_count,
substr(partition_date, 5, 2) || '-' ||
substr(partition_date, 7, 2) || ' ' ||
substr(partition_date, 9, 2) || ':00'
as partition_date
FROM
JP_MESH_SUMMARY
WHERE
CODE = '53393691'
group by
partition_date
;
```
와 같이 4개의 컬럼 생성하는 쿼리를 작성

이후 꺾은선형 그래프를 그릴 경우
시각화 옵션 - 데이터 - X축: partition_date
시각화 옵션 - 데이터 - Y축: 모두 선택

을 할경우 값이 나오지 않음

Y축을 특정 컬럼을 선택할 경우 결과가 나옴

## 예상한 행동 ##
나머지 3개의 컬럼의 데이터들이 하나의 화면에 꺾은선형으로 나올것으로 예상함

**Comment by veldise** [comment]
@anhm
보고서에서 IRIS-DB를 대상으로 데이터를 요청하여 받을 경우,
컬럼 유형(TEXT, NUMBER, ...)에 대한 정보가 없기 때문에 강제 형변환을 하고 있습니다.
이 때 "모두 선택"으로 설정할 경우 텍스트값은 NaN값으로 변환되어 차트가 제대로 그려지지 않는 것입니다.

**Comment by anhm** [comment]
해당 내용 확인 되었으며, 추후 IRIS에서 데이터 타입을 전달할수 있는 방안 확인 필요.
