### ISSUE TITLE
[보고서] 지도 데이터의 잘못 표현된 영어 단어 수정 필요

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1244]
## 버그 설명 ##
보고서의 지도 부분의 잘못 표현된 영어 단어 수정 필요

한글로 했을때 색상으로 나오는 부분이 영ㅇ

## 재현하는 방법 ##
홈페이지를 영어로 변경

지도생성후 레이어 등록

property - visual options - Data 부분에서

Longitude 부분이 한글로는 '색상'에 해당하는 부분임

전체적으로 색상 부분이 Longitude로 나오는 것으로 봐서는 단어 등록이 잘못 되어 있는것으로 판단됨

![2019-02-19 6 27 25](https://user-images.githubusercontent.com/3415270/53004540-bcce5400-3474-11e9-91c2-a63fc6ac0e39.png)

**Comment by veldise** [comment]
수정하여 금일 패치 예정입니다.

**Comment by veldise** [comment]
패치 완료되어 닫습니다.
