### ISSUE TITLE
[검색] 응답속도 이슈

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1245]
모델: MDT_DEMO_DATA2 를 전체 시간으로 검색할 경우 느리게 응답하는 원인

```
{"daemon":"DSD","protocol":"EXECUTE","query_option":{},"max_cont_record_count":2000,"backend_info_list":[{"info":"BACKEND_INFO","attach_name":"DEMO","d_u_name":"DEMO","p_date":"20190127010000","t_u_name":"MDT_DEMO_DATA2","path":"","p_block_num":"1","p_key":"7.7"}],"query":"SELECT * FROM MDT_DEMO_DATA2   ","serialize_type":2}
```

angora에서 위와 같이 데이터를 요청하는 것으로 확인됨

전체 데이터를 요청하기 떄문에 전체 데이터를 가져가다 보니 느리게 반응 하는것으로 판단됨
과거 limit 을 사용했는지 확인할 필요가 있음

**Comment by pjh0347** [comment]
@anhm angora 조회 입력(쿼리, 파라미터) 을 어떻게 했는지 조건 정보를 확인 바랍니다.

**Comment by anhm** [comment]
위에 상황은,
MDT_DEMO_DATA2 데이터 모델을
전체 시간 범위로 검색한 상태입니다.

**Comment by pjh0347** [comment]
@anhm Angora 는 v1/v2 상관 없이 engine 부분에서 개별 명령에 대해 df 관련 연산 함수들을 호출 후, 맨 마지막에 df.take(size) 함수를 호출하여 결과를 받아와 리턴 합니다. 즉, 기존 로직과 변경 사항이 없습니다.

**Comment by anhm** [comment]
속도가 느린것은 다른 원인으로 판단이 되며 해당 원인이 아니기 때문에 이슈는 닫습니다.
