### ISSUE TITLE
[검색] angora 검색시 속도 느린 현상

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1246]
iris web의 사용시 느리게 반응하던 이유는 spark-on-iris 와 DSD와의 통신 부하로 확인이 되었습니다.

이에 spark-on-iris에서 파일로 직접 접근할때 사용하는 옵션을 생성하였으며,
해당 옵션을 angora에서 사용하도록 요청 드립니다.

아래와 같이 옵션을 사용하시면 됩니다.

`.option("directBlock", "true")`

아래는 예제 코드 입니다.

```
irisDF = sqlContext.read.format("iris")\
    .option("table", "demo.MDT_DEMO_DATA2")\
    .option("host", "192.168.100.180")\
    .option("user", "root")\
    .option("passwd", "<root password>")\
    .option("port", "5050")\
    .option("dsdPort", "5110")\
    .option("version", "v2")\
    .option("directBlock", "true")\
    .load()
print irisDF.count()
```

**Comment by namjals** [comment]
수정 버전이 개발, 운영 서버에 배포되었습니다. 
MDT 공간 관련 where절 조건이 있는 경우 directBlock 옵션을 false, 아닌경우 true 입니다. 
MDT 공간 관련 검색의 경우 속도가 늦더라도 쿼리 변환을 위해, directBlock 옵션을 false로하여 IRIS(DSD)를 1회 거쳐야함.
그 외 일반 검색의 경우 directBlock를 true로 주어 다이렉트로 sqlite 질의를 함.
