### ISSUE TITLE
[보고서] 저장 기능 - 복제된 보고서에서 저장시 이슈 발생

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1247]
## 버그 설명 ##
복제된 보고서에서 저장시 원본 보고서에 영향을 줌

## 재현하는 방법 ##
확인된 사항은

지도 - 포인터를 이용하여 보고서를 만든 이후
복제를 진행하고
복제된 보고서에서 포인트의 크기를 변경할 경우

원본 보고서의 포인트 크기도 같이 변경이 되는 것으로 확인됨

이때, 복제/원본은 root로 진행하였음.

**Comment by tylor-kr** [comment]
이슈 처리 후 180 서버에 배포 되었습니다.
