### ISSUE TITLE
[보고서] 지도, threshold 설정이슈

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1248]
## 버그 설명 ##
보고서의 색상 지정 방법중 threshold를 이용하여 지정할 경우

보고서를 새로 불러올 경우 이슈가 발생함

## 재현하는 방법 ##
1. 보고서의 색상 지정 방법중에 threshold 방법을 이용하여 색상 지정

2. 저장

3. 불러오기

4. threshold 내용이 변경되어 있음

## 스크린샷 ##
<img width="320" alt="2019-02-24 9 29 43" src="https://user-images.githubusercontent.com/3415270/53304978-e7a51780-387b-11e9-9987-e89ec1fb4d01.png">

위의 이미지 처럼 항목이 하나 자동으로 추가되는 이슈가 존재함

**Comment by anhm** [comment]
데이터를 불러오는 시점이 아닌 저장하는 시점에 이슈가 있는것으로 보임
저장된 데이터를 보는 시점에서도 정상적으로 출력되지 않음
데이터 모델: JP MESH new

**Comment by tylor-kr** [comment]
이슈 처리 후 180 서버에 배포 되었습니다.
