### ISSUE TITLE
[보고서] 그래프 항목의 설정값이 자동으로 변경됨

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1249]
## 버그 설명 ##
그래프에 설정한 축 컬럼 정보가 자동으로 변경됨

- 그래프에 이용되는 데이터는 IRIS 데이터를 이용하여 쿼리로 데이터를 가져옴

## 재현하는 방법 ##
1. 지도 데이터 설정
2. 그래프 데이터 설정
    - 그래프 데이터 설정시 지도를 클릭하면 반응하도록 만듬
    - 그래프 데이터는 IRIS-DB에 있는 데이터 이용
    - 데이터를 가져올 경우 쿼리를 이용
3. 그래프의 x, y축을 임의로 지정
4. 지도를 클릭하여 그래프가 반응하도록 테스트
    - 이때 그래프의 축에 설정한 컬럼 정보가 변경됨

**Comment by veldise** [comment]
컬럼 정보 설정은 작업 "실행"의 결과 데이터(`fields`) 정보로만 설정하게 되어있는데,
이벤트에 반응하여 실행이 다시 이루어지면 해당 정보가 리셋되어 발생하는 문제입니다.
현재 UI/UX 구조로는 해결이 다소 어렵습니다.

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/1236#issuecomment-517098198
