### ISSUE TITLE
고급시각화 / 꺾은선형 X축 포맷 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1250]
## 버그 설명 ##
고급시각화 / 꺾은선형 X축 포맷 에러

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/53308961-3d170e00-38e8-11e9-840d-40c3fc373a9c.png)

**Comment by JoonseokRyu** [comment]
https://github.com/mobigen/B-IRIS-Data-Discovery-Web-Service/pull/1282
처리했습니다. 180번 서버에 배포후 클로즈 하겠습니다.

**Comment by veldise** [comment]
금주(3/7) 패치 예정

**Comment by veldise** [comment]
3/6 17시 패치 완료되어 닫습니다.
