### ISSUE TITLE
고급시각화 / adv outlier, summary 명령어 NoneType 에러 반환 

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1251]
## 버그 설명 ##
`adv outlier`, `adv summary` 명령 실행시 에러가 반환됩니다.
Angora v2로 전환하면서 미처 확인하지 못한 부분으로 생각됩니다.

**아래 명령어가 문법 등에 맞게 작성되었는지 확인이 필요합니다.**

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 180번 운영 서버 접속 (root)
2. 고급시각화 화면 이동, Outlier 유형 선택
3. syslog 모델 선택, 컬럼을 LEVEL_INT로 설정
4. 실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/53309049-e78f3100-38e8-11e9-9545-f8fabe8f1086.png)

## 로그 ##
request:
```json
{
  "q": "model name = 'syslog' start_date = 20190225102300 end_date = 20190225103310 | adv summary  TARGETS LEVEL_INT COLSIZE 500",
  "size": 500
}
```
response:
```
{
  "message": "'NoneType' object has no attribute 'strip'", 
  "type": "<type 'exceptions.AttributeError'>"
}
```

request:
```json
{
    "q":"model name = 'syslog' start_date = 20190225102300 end_date = 20190225103310 | adv outlier  TARGETS LEVEL_INT COLSIZE 500",
    "size":500
}
```
response:
```json
{
  "message": "'NoneType' object has no attribute 'strip'", 
  "type": "<type 'exceptions.AttributeError'>"
}
```

**Comment by seungfwani** [comment]
이슈번호 #1303 과 같은 내용으로 
현 운영서버(192.168.100.180)에서는 정상동작 합니다.

![image](https://user-images.githubusercontent.com/46172579/62514536-77eb7d80-b85a-11e9-83c0-42d32980e6a2.png)
