### ISSUE TITLE
[보고서] 지도의 mesh4 이상의 레벨 추가 필요

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1254]
## 기능 요청 ##
현재 보고서의 mesh를 이용하여 데이터를 표현할 경우 level이 1~3까지만 지원하고 있습니다.

일본 데이터를 이용하여 MDT 시연시 실제 보고 싶어 하는 범위는 가로 세로 약 100m 범위 까지 보고 싶어 하는 상황이 발생하고 있습니다. 
확인해본 결과 이는 level 6에 해당하는 범위에 가까운 것으로 확인이 되었습니다.

당장은 아니더라도, 추후 일본에 MDT 데이터를 시연하기 위해서는 level 4 이상의 mesh 를 준비하는 것이 좋을것 같습니다.

**Comment by veldise** [comment]
4레벨 이상의 mesh 정보에 대하여 JavaScript는 이미 개발된 모듈이나 코드가 없습니다.
서버에서 정보를 받아오는 방식으로 변경하거나, 새로 개발해야 합니다.
