### ISSUE TITLE
[보고서] SMS 서비스가 없을 경우 에러창 처리 필요

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1255]
## 버그 설명 ##
SMS 서비스가 등록되지 않은 사이트에서 보고서 화면으로 들어갈 경우, 매번 에러 메시지가 발생함

## 예상한 행동 ##
SMS가 등록되지 않았을 경우에는 에러 메시지가 발생하지 않으면 좋겠음

## 스크린샷 ##
![2019-03-05 9 29 45](https://user-images.githubusercontent.com/3415270/53772376-8e974c80-3f29-11e9-83bb-754b85289cb8.png)

**Comment by swish1995** [comment]
검색결과 studio 에서 해당 메세지를 출력하는게 아닌것으로 확인됩니다.
관련 메세지는 brick 에서 처리되어 있는것으로 판단됩니다.

**Comment by swish1995** [comment]
### TODO : 데이타 모듈 통합후 sms 서비스가 없을때 sidepanel 에서 getAgentList 처리

**Comment by veldise** [comment]
데모 운영서버에 패치 및 해결되어 닫습니다.
