### ISSUE TITLE
[보고서] 버튼 클릭시 에러 발생

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1256]
## 버그 설명 ##
다음과 같은 에러 메시지 창이 발생합니다.

## 재현하는 방법 ##
에러 상황이 간혹적을 발생하고 있는 상황이라 정확한 재현이 불가능한 상태입니다.

## 스크린샷 ##
![kakaotalk_photo_2019-03-05-09-32-44](https://user-images.githubusercontent.com/3415270/53772472-d28a5180-3f29-11e9-972f-7e2bee926c60.png)

**Comment by anhm** [comment]
추가적으로 다음과 같은 에러도 발생 중입니다.
![kakaotalk_image_2019-03-05-09-41-10](https://user-images.githubusercontent.com/3415270/53772722-cfdc2c00-3f2a-11e9-9a04-166d9e6d8421.png)

**Comment by veldise** [comment]
@anhm
본문 스크린샷은 IRIS-DB와의 jdbc connection 생성이 실패한 상황으로 생각됩니다.
두번째 스크린샷은 Angora가 정상 설치되지 않았거나 정상 동작하지 않는 것으로 보입니다.

**Comment by veldise** [comment]
해결된 것으로 보고 닫겠습니다.
재현되면 열어주세요.
