### ISSUE TITLE
[고급시각화] 원형 차트 수치형 변수 필터 기능 문제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1258]
## 버그 설명 ##
스크린샷을 보시면 수치형 변수인 FILESIZE에 필터를 추가할 때 드롭다운 메뉴에 아무것도 뜨지 않습니다.

## 스크린샷 ##
1) 수치형(INTEGER) 변수일 때
![_ _ _ 1](https://user-images.githubusercontent.com/35832986/53780503-2c017900-3f48-11e9-9aa6-9ff59add5b48.jpg)

2) 명목형(TEXT) 변수일 때
![_ _ _ 2](https://user-images.githubusercontent.com/35832986/53780518-3459b400-3f48-11e9-9a58-ff04608873c4.jpg)

## 기타 ##
다이렉트 클라우드 서버에서 진행한 작업입니다.

**Comment by veldise** [comment]
고급시각화 화면에서 필터 입력시
`NUMBER`, `REAL`의 경우에는 정상동작, `INTEGER`의 경우에는 본문과 같은 비정상 동작을 확인하였습니다.
빠른 시일내 수정하겠습니다.

**Comment by veldise** [comment]
금주(3/7) 패치 예정

**Comment by veldise** [comment]
3/6 17시 패치 완료되어 닫습니다.
