### ISSUE TITLE
[보고서] '시간' 설정 시 종료시간 선택 에러

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1260]
## 버그 설명 ##
시간 설정 시 종료시간을 '현재 시간'이 아닌 다른 특정 시간으로 선택하면 시간이 설정되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [보고서]에서 [새 보고서] 클릭
2. '시간' 컴퍼넌트 생성
3. '날짜 및 시간 범위'에서 시작과 종료시간을 특정하여 선택 후 [선택]버튼 클릭
4. 적용되지 않음

## 스크린샷 ##
![_ _](https://user-images.githubusercontent.com/35832986/53784981-480e1600-3f5a-11e9-9c15-88d06058f931.jpg)

## 기타 ##
'미리 설정'에서 선택하거나 종료 시간에 있는 '현재 시간'을 체크하면 잘 적용됨

**Comment by ssm0219** [comment]
@veldise 선임님, 위 이슈에 혹시 문제가 있나요?
4월 초에 예정된 일본 전시회 관련 내용이어서, 일정 확인 요청 드립니다

**Comment by veldise** [comment]
@ssm0219 
최근에 해결되어 아직 배포하지 않은 상태입니다. 운영서버에는 차주(3월 2주)에 배포 예정입니다.

**Comment by ssm0219** [comment]
@veldise 감사합니다. 해결될 것으로 감안하고 작업하겠습니다.

**Comment by veldise** [comment]
지난주 배포로 해결되어 닫습니다.
