### ISSUE TITLE
[피벗][고급시각화] '수정'버튼 이상

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1261]
## 버그 설명 ##
연필 모양의 '수정' 버튼이 피벗과 고급시각화에서 이상하게 표시됨

약간 오른쪽으로 벗어나게 표시됨

## 스크린샷 ##
1) 피벗
![image](https://user-images.githubusercontent.com/35832986/53786790-1ef08400-3f60-11e9-903a-b0447d529f64.png)

2) 고급시각화의 '필터'
![image](https://user-images.githubusercontent.com/35832986/53786806-2879ec00-3f60-11e9-8942-f3cd075bb17f.png)

## 기타 ##
다이렉트 클라우드 작업 진행 중 발견하였습니다.

**Comment by veldise** [comment]
영문 버전에서만 나타나는 현상으로 확인되었습니다.
수정 요청하겠습니다.

**Comment by veldise** [comment]
지난주 배포로 해결되어 닫습니다.
