### ISSUE TITLE
[IRIS-WEB] docker 컨테이너 일반계정으로 실행시 에러 발생

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1262]
## 버그 설명 ##
[iris-web] docker 컨테이너를 일반계정으로 실행시 에러가 발생됩니다.
일반계정으로 사용이 필요한 경우 스크립트 확인을 요청드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 압축된 최신 이미지 파일을 일반계정에서 압축 해제 및 권한 수정 후 컨테이너 전체  start
 
![image](https://user-images.githubusercontent.com/25650544/53851572-721b1300-4002-11e9-9316-8c1a3f2fb218.png)

2. 컨테이너 시작 시 에러 발생

![image](https://user-images.githubusercontent.com/25650544/53851686-cb834200-4002-11e9-9a76-f8e6cc022ba0.png)
 
3. iris-web 컨테이너 status 확인 시 unknown , offline 상태 확인됨.

![image](https://user-images.githubusercontent.com/25650544/53851735-f4a3d280-4002-11e9-9fe7-815f8cdbb8dd.png)

테스트는 192.168.101.181 서버에서 진행되었습니다.

## 예상한 행동 ##

service/bin/각컨테이너별 쉘스크립트 파일 에서 docker 실행 시 host 실행계정을 가져와서 컨테이너를 실행하는듯함.

## 기타 ##

문제발생된 hdfs-browser.sh(컨테이너 실행은 되나 권한관련 로그생김) , ext-manager.sh(컨테이너 실행되지않고 컨테이너 안에 iris 계정이 없는듯함) 스크립트 파일에서 docker 실행시 user 정의된 옵션 수정하여 임시 해결. 

hdfs-browser -- >>  $userOpts 옵션을 --user root 변경
ext-manager -- >> --user $currUser 옵션을 --user root 변경

**Comment by veldise** [comment]
ext-manager :
```
docker: Error response from daemon: linux spec user: unable to find user iris: no matching entries in passwd file.

docker: Error response from daemon: Conflict. The container name “/ext-manager” is already in user by container “….”. You have to remove (or rename) that container to be able to reuse that name.
```

hdfs-browser:
```
[INFO] hdfs-browser still running
```

**Comment by sunghoon** [comment]
IRIS-Cloud 적용하면서 처리된 것으로 보고 닫습니다.
