### ISSUE TITLE
[검색] 영문 페이지에서 도움말이 제대로 작동하지 않음

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1263]
## 버그 설명 ##
도움말의 일부 하이퍼링크들이 제대로 작동하지 않음

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/53923243-f4ffa480-40ba-11e9-8dd5-74d35c724180.png)

예를 들면,
metatron, iris, hdfs, sql 등은 링크를 클릭해도 반응이 없음

## 기타 ##
timeline의 경우 도움말 내용에서 제목의 서식이 제대로 적용되지 않은 것 같습니다.
![image](https://user-images.githubusercontent.com/35832986/53923326-4445d500-40bb-11e9-97b9-e3a3f1804d87.png)

**Comment by tylor-kr** [comment]
180 서버 배포 후 확인 되어 닫습니다.
