### ISSUE TITLE
[공항철도] 검색 / 결과 pending

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1264]
## 버그 설명 ##
검색 수행시 결과 중에 차트는 잘 나오는데, 결과 데이터는 나오지 않는 문제가 발생하고 있습니다.
report by: 윤정훈 선임

## 스크린샷 ##
상황:
![image](https://user-images.githubusercontent.com/3411842/53942741-dfac6980-40fe-11e9-992c-f74d9a0a322c.png)

모델 정보(IRIS-DB):
![image](https://user-images.githubusercontent.com/3411842/53942744-e2a75a00-40fe-11e9-9fae-fe86f75eb7a8.png)

**Comment by veldise** [comment]
@pjh0347

**Comment by pjh0347** [comment]
방화벽 설정으로 인해 Spark 포트가 막혀 동작 안했던 이슈로, 방화벽 설정을 변경하여 처리되었습니다.
