### ISSUE TITLE
[보고서] 작은 영역에서 테이블 출력 시 문제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1267]
## 버그 설명 ##
스크린샷 참조

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/54007724-90217880-41a6-11e9-9ba4-dd3e62dbf15a.png)

스크린샷을 보면, 작은 영역에서 테이블을 출력하면 페이지 색인 링크 (1,2,3,4,5)가 영역 밖에 표시된 것을 확인할 수 있습니다.

밖으로 나오지 않고 영역 내에서 횡스크롤같은 걸로 볼 수 있어야하지 않나 생각합니다.

**Comment by tylor-kr** [comment]
## 확인 결과
* 영역 객체의 가로. 세로 최소 길이는 30px
* 사용자가 영역 객체의 크기를 너무 작게 줄일 경우 클릭 및 크기 조절이 불가능하게 되는 현상을 방지 하기 위함
* 페이지 네이션 가로 최소 길이는 440px 이므로 위와 같은 현상이 발생함

## 의견
영역 개체의 가로 최소 길이를 아래와 같이 조절
* 페이지 네이션이 있을 경우 440px
* 페이지 네이션이 없을 경우 30px

@veldise @onlyeon 
별 다른 의견 없으시면 위처럼 처리 하겠습니다.

**Comment by tylor-kr** [comment]
처리 후 배포 되어 닫습니다.
