### ISSUE TITLE
[보고서] '시간' 컴퍼넌트로 '리스트'도 설정할 수 있게 기능 추가 요청

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1268]
## 기능 요청 ##
스크린샷과 함께 설명하겠습니다.

![image](https://user-images.githubusercontent.com/35832986/54010564-974e8380-41b2-11e9-8f70-90fe9f14a5cc.png)

제가 만들려는 보고서는 다이렉트 클라우드 로그를 회사별로 분석한 결과를 조회할 수 있는 보고서입니다.
그래서 우측 상단의 '시간' 컴퍼넌트로 분석 대상 로그의 기간을 설정하고,
좌측 하단의 'Company List' 밑의 '리스트' 컴퍼넌트에서 분석 대상 회사를 선정하게 하려고 합니다.

이를 위해서는 '리스트' 컴퍼넌트에 보여지는 회사들은 우측 상단 '시간' 컴퍼넌트 에서 설정한 기간 내에 발생한 로그가 있는 회사들이어야 합니다.

그러기 위해서는 '시간' 컴퍼넌트로 '리스트' 컴퍼넌트도 설정할 수 있어야하는데, 현재는 되지 않고 있습니다.

'리스트' 컴퍼넌트도 '시간' 컴퍼넌트의 적용 대상이 되도록 기능 추가를 요청드립니다.

**Comment by veldise** [comment]
본문의 '시간 컴포넌트는 '데이터모델 일괄설정' 객체로, 2020/02/27 패치에서
'기간 설정' 객체가 추가됨에 따라 폐기되었습니다.
'기간 설정' 객체와 아래 '객체연결' 방식의 설정을 이용하면 본문에서 하고자하는 동작을 할 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/82864725-2da9c900-9f60-11ea-8b2d-5edb6b614651.png)
