### ISSUE TITLE
[검색] 영문 화면으로 볼때 틀이 깨져보이는 현상

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1269]
## 버그 설명 ##

검색 화면에서 아래와 같이 영문으로 할 경우 틀이 깨져보이는 현상이 발생함

![2019-03-08 3 55 57](https://user-images.githubusercontent.com/3415270/54012870-b8b36d80-41ba-11e9-9dca-9b27e3e68a99.png)
![2019-03-08 3 55 59](https://user-images.githubusercontent.com/3415270/54012871-b8b36d80-41ba-11e9-9388-96a01581b47c.png)

**Comment by veldise** [comment]
지난주 배포로 해결되어 닫습니다.
