### ISSUE TITLE
[보고서][시각화] 접근권한 설정 에러

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1270]
ㅁ## 버그 설명 ##
[보고서]와 [시각화] 화면에서 접근권한 설정 버튼을 누르면 스크린샷처럼 오류 메시지가 나타남

## 스크린샷 ##
1) [보고서] 화면
![image](https://user-images.githubusercontent.com/35832986/54096182-17146200-43ee-11e9-99e5-6b6f942a1b60.png)

2) [시각화] 화면
![image](https://user-images.githubusercontent.com/35832986/54096189-20053380-43ee-11e9-80f1-6e5747b74dd2.png)

## 기타 ##
다이렉트 클라우스 서버에서 발생한 이슈입니다.

**Comment by tylor-kr** [comment]
@ssm0219 
현상 파악을 위해서는 서버에 있는 로그 확인이 필요 합니다.
위 iris-web이 설치 되어 있는 서버에 접속 가능한 서버 주소, 계정 정보(아이디, 패스워드) 요청 드립니다.

**Comment by ssm0219** [comment]
@tylor-kr 

--ssh 접속 정보---

서버1 (mobigen-master)

ip : 52.197.255.62
id : centos
pw : ahqlGen#031
su-pw : WpsahqlVotm#034


서버2 (mobigen-slave)

ip : 54.95.93.74
id : centos
pw : ahqlGen#031
su-pw : WpsahqlVotm#034

**Comment by tylor-kr** [comment]
@ssm0219 
iris db에 접근권한을 사용하기 위한 테이블이 생성되어 있지 않아서 발생한 오류 입니다.
테이블 생성 후 정상 동작 확인 하였습니다.

![image](https://user-images.githubusercontent.com/13827425/54102028-ff4ad700-4409-11e9-8305-270216ca76b8.png)
