### ISSUE TITLE
[검색] 창에서 ADE 명령어를 직접 입력하면 'can not find job' 에러가 항상 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1271]
## 버그 설명 ##
이상 탐지 명령어인 ADE 를 검색창에 직접 입력하면 
cannot find job id
에러가 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 시각화 에서 myiris 계정의 'ADE_검색창_에러'  실행

명령어 구문
`*   | ade SPC KEYS HOST SIZE 500 VALUES count(HOST) TEST DATETIME START '20181102150000' END '20181102212000' REFERENCE DATETIME START '20181002150000' END '20181102212000' BY 10M  PERMISSIVE TRUE  TIMEMATCH TRUE NULLVALUE NULL DAYS SAMEDAY`

## 예상한 행동 ##
이상탐지 메뉴로 자동 이동 & 결과

## 스크린샷 ##
<img width="1033" alt="스크린샷 2019-03-11 오후 2 55 30" src="https://user-images.githubusercontent.com/5126497/54102973-da586300-440d-11e9-9597-090524bacdc7.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by EricLeeMbg** [comment]
Web UI - '이상탐지' 메뉴를 선택한 경우 ADE REST API 호출 후 정상작동
위 처럼 명령어로 수행한 경우 - query REST API 호출 후 에러 발생 
에러는 Angora log 확인 결과 상기 에러가 아니라 KeyError: 'test_period' 가 발생함 

해당 키워드는 '이상탐지'로 수행할 경우 웹에서 구성하여 json format으로 전달되는 인자이며, 
query API에서는 해당 기능이 구현되어 있지 않음 

Angora 팀원과 협력하여 추가구현 논의 예정임

**Comment by pjh0347** [comment]
### 배경
현재 검색/피벗/고급시각화 메뉴에 사용하는 angora 명령어의 경우 query rest api 를 공통으로 이용합니다. 이는 rest api 하고 명령어 사이에 관계를 느슨하게 만들자는 취지에서 구조 개선 적용된 내용입니다.

### 에러 원인
하지만 이상탐지 메뉴의 경우 전용의 ade rest api 를 이용합니다. 인터페이스의 차이로 인하여 ade 명령어를 ade rest api 를 통하지 않고 검색 메뉴에서 query rest api 를 이용하면 현재 동작하지 않습니다. (지원하고 있지 않습니다.)

### 지원하지 않고 있는 이유
현 시점에서 ade 기능은 UI 로 제공되고 있기 때문에 불편하게 검색창에 복잡한 명령어를 직접 실행할 일은 없기 때문에 내부 명령어로 구분하고 있습니다. 여기서 내부 명령어는 사용자가 사용하는 명령어가 아닌 개발자 혹은 시스템 연동 시 사용되는 명령어를 의미합니다. 도움말에도 해당 명령어 설명은 제외됩니다.

위와 같은 이유로 현재 지원하고 있지 않아 에러가 발생하는 부분이며, 기능 구현이 필요한 경우 별도의 일정을 가지고 개발해야 합니다.
