### ISSUE TITLE
[검색] 커맨드창에서 hdfs명령어를 써서 데이터를 HDFS 에 write하면 root 소유자로 되어 access 가 안됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1272]
## 버그 설명 ##
검색창에서 명령어창에 hdfs 명령어로 write 를 하면 HDFS브라우저에서 root 소유자로 write 되어 파일에 access 가 안됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 검색 창에서  select 구문을 사용한 후   *  | hdfs csv write /B-IRIS/USERS/myiris/tmp_aaaa
2. HDFS 브라우저에서 확인

## 스크린샷 ##
<img width="995" alt="스크린샷 2019-03-11 오후 5 52 51" src="https://user-images.githubusercontent.com/5126497/54111199-a5a4d580-4426-11e9-9123-1a78fd115563.png">

HDFS 브라우저 : 소유자 root  로 되어 있음
<img width="993" alt="스크린샷 2019-03-11 오후 5 53 10" src="https://user-images.githubusercontent.com/5126497/54111205-accbe380-4426-11e9-892f-718c474d0502.png">

에러 팝업창
<img width="486" alt="스크린샷 2019-03-11 오후 5 24 41" src="https://user-images.githubusercontent.com/5126497/54111208-af2e3d80-4426-11e9-8910-fa01d40f2f95.png">

**Comment by EricLeeMbg** [comment]
https://github.com/mobigen/B-IRIS-Data-Discovery-Service/pull/41
테스트 결과화면

![hdfs처리결과1](https://user-images.githubusercontent.com/44352311/56177707-8f4bf400-603a-11e9-9d3a-3e69cfa18fbc.jpg)
![hdfs처리결과2](https://user-images.githubusercontent.com/44352311/56177709-92df7b00-603a-11e9-80ee-e3dad274d2bc.jpg)

**Comment by pjh0347** [comment]
조회 결과를 HDFS 로 저장하거나 로컬 컴퓨터로 다운로드 하려면 UI 기능을 이용하시면 됩니다. hdfs 명령어는 내부 명령어로서 명령어 도움말 문서에서도 제외되었습니다.

`검색 화면` 에서 `다운로드` 아이콘을 클릭한 후, `결과 내보내기` 팝업에서 `HDFS` 선택.
![image](https://user-images.githubusercontent.com/5305236/62258674-4e8bb580-b446-11e9-8731-cc5c7fea9b59.png)
