### ISSUE TITLE
[보고서] 실행 시 리스트 컴포넌트 표시 에러

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1273]
## 버그 설명 ##
생성한 보고서를 실행하면 안의 리스트가 표시되는 화면과 불일치합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/54187110-2d0a4b80-44f0-11e9-80e3-cc98aebd828a.png)

위 스크린샷은 [보고서] 메뉴 화면에서 제가 작업한 보고서 이름을 클릭하면 나오는 화면입니다.

스크린샷에서 빨간색 동그라미로 표시된 부분은 좌측 리스트에서 'USER'를 클릭했을 때 나타나는 화면입니다.
반면 리스트에 선택된걸로 표시되는 건 'FILE & DIRECTORY' 입니다.

리스트가 'FILE & DIRECTORY'로 표시되는 이유는, 제가 추정하건데,
제가 마지막으로 작업하고 저장할 때 선택되어 있던 게 'FILE & DIRECTORY'여서 그런것으로 보입니다.

## 예상되는 행동 ##
보고서가 실행되면 리스트는 무조건 첫번째 걸 선택하여 보여주도록 수정하는게 어떨까 싶습니다.
리스트의 통제를 받는 컴퍼넌트들은 그렇게 되어잇는 것 같은데,
리스트 자체는 그렇게 표시되지 않는 것으로 보입니다.

## 기타 ##
다이렉트 클라우드 서버에서 작업하여 발견한 문제입니다.

**Comment by veldise** [comment]
리스트라고 하셔서 헷갈렸네요, 탭 동작에 대한 버그로 확인했습니다.
