### ISSUE TITLE
[데이터추가] 500 에러 발생

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1275]
## 버그 설명 ##
스크린샷 및 재현방법 참고

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 다이렉트 클라우드 IRIS 서버에서 언어를 영문으로 설정
2. [Import Data]로 이동
3. "Select File" 버튼을 클릭하여 csv 파일을 선택 
(버그 당시 csv 파일이 보안사항이라 필요하시다면 별도로 보내드리겠습니다.)
4. 우측의 'Next >' 버튼 클릭

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/54575446-75b58d80-4a37-11e9-8409-f1a8dd905aff.png)

**Comment by veldise** [comment]
@ssm0219 
운영서버(180)에는 최근 수정된 내용중 하나입니다.
버전 확인 및 재배포가 필요합니다.

**Comment by veldise** [comment]
Direct Cloud 서버에도 배포되었습니다. 이슈 닫습니다.
