### ISSUE TITLE
[클러스터관리]사용자 추가시 USERAPI 에러

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1276]
## 버그 설명 ##
IRIS-DB 1.6.4.4 버전이며  IRIS-WEB 페이지 접속 후 클러스터관리 -> 사용자 메뉴에서 사용자추가시 에러메세지가 발생됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS-WEB 접속 후 클러스터관리 -> 사용자 -> 사용자추가시 로딩되는 화면이 3분가량 나타남
![image](https://user-images.githubusercontent.com/25650544/54888051-ef88c380-4edc-11e9-95ce-1abc70716726.png)
2. 에러메세지가 나타남.
![image](https://user-images.githubusercontent.com/25650544/54888072-28289d00-4edd-11e9-8849-11677463947e.png)
재시도 시 다른 에러메세지 출력됨.
![image](https://user-images.githubusercontent.com/25650544/54888082-38407c80-4edd-11e9-98cb-1301aa3355d3.png)

## 기타 ##
한국도로공사 적용된 IRIS-WEB 에서 발생되는 화면입니다.

**Comment by veldise** [comment]
```
Unexpected charater ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null) at [Source: java.io.StringReader@32597d79; line:1, column: 2]
```

**Comment by veldise** [comment]
@big-mobigen 
도로공사에 설치된 버전을 정확히 확인하진 못했습니다. (0.1.2 위치 소실)
하지만 0.1.3 버전의 코드로 확인한 결과, 메타트론 미설치 혹은 비정상 동작을 할 때 발생하는 문제로 추측됩니다.

계정 생성을 할 때 다음과 같은 과정을 거칩니다.
1. 계정 존재 여부 확인
2. IRIS-DB 계정 추가 (IRIS-DB 프로토콜 사용)
3. **메타트론 계정 추가** (메타트론 http API 사용)
4. 2개 테이블에 계정 정보 저장

여기서 3번 메타트론이 미설치/shutdown/비정상동작 등의 상황으로
메타트론 계정 추가시에 정상적인 결과(성공/실패)를 반환하지 않으면
위와 같은 에러가 발생합니다.

메타트론의 상태 확인이 필요하고, 메타트론 계정 추가 동작을 제거해야 한다면
코드 수정 및 재배포가 필요합니다.

**Comment by veldise** [comment]
처리되어 닫습니다.
