### ISSUE TITLE
[전력연구원] 데이터 모델 접근 권한 설정

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1279]
## 버그 설명 ##
데이터 모델 접근 권한 설정 클릭 시 오류 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 데이터브라우저 > 관리
2. "접근권한" 클릭 시 오류 발생함

![image](https://user-images.githubusercontent.com/29471177/54965363-8b84fe80-4fb3-11e9-83fd-54e00f9c4ffd.png)

**Comment by tylor-kr** [comment]
@veldise 
직접 접속 하여 확인 할 수 없어서 정확한 원인은 파악하기 힘드나,  접근 권한 서비스에 사용되는 테이블이 없는 것으로 예상됩니다.

**Comment by veldise** [comment]
@chohi22 
배포된 버전 정보가 필요합니다.

**Comment by chohi22** [comment]
@veldise 
배포 버전입니다.
![image](https://user-images.githubusercontent.com/29471177/54987211-821d8580-4ff7-11e9-9723-7a9f1dd8d16f.png)

**Comment by veldise** [comment]
@chohi22 
권한 설정을 위한 DB테이블이 생성되어있지 않아서 발생하는 문제로 보입니다.
IRIS-DB에서 아래 쿼리를 실행하여 테이블 생성을 하시고 다시 확인 부탁드립니다.

```sql
CREATE TABLE WAS.WAS_ACCESS_RIGHTS (
    ID TEXT,
    CATEGORY TEXT,
    TYPE TEXT,
    VALUE TEXT
)
datascope GLOBAL
ramexpire 0
diskexpire 0
partitionkey None
partitiondate None
partitionrange 0
;
```

**Comment by chohi22** [comment]
ㅁ 테이블 확인 후 생성
![image](https://user-images.githubusercontent.com/29471177/55853524-75bf2e00-5b9c-11e9-9c0f-5571f03ab26c.png)


ㅁ 테이블 생성이후 확인 결과
![image](https://user-images.githubusercontent.com/29471177/55853480-545e4200-5b9c-11e9-834e-a30ff7176eeb.png)

오류 없이 잘나옵니다.
