### ISSUE TITLE
보고서 / 영문 버전에서 차트 그려지지 않음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1280]
## 버그 설명 ##
보고서에서 영역 객체를 다수 구성하였을때, 영문 버전에서 일부 차트가 그려지지 않는 문제가 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://52.197.255.62
2. eva 계정으로 접속 (비밀번호는 별도 문의 바람)
3. `Direct Cloud Analysis Report v1 (2)` 보고서 실행
4. System Code 차트가 그려지는 것을 확인
5. 국가/언어 설정을 English로 변경
6. System Code 차트가 그려지지 않음

**Comment by veldise** [comment]
컬럼 선택 정보를 저장할 때 국가/언어설정에 따라 다른 값을 저장하고 있어 발생하는 문제로 확인했습니다.

**Comment by tylor-kr** [comment]
@veldise 
현재 `http://52.197.255.62` 서버에 접속이 안되고 있습니다.
조금 더 상세한 방법을 알려주시면 확인 해보겠습니다.

**Comment by veldise** [comment]
@tylor-kr 
보고서를 저장할 때 차트(영역) 객체의 시각화 옵션 - 데이터 탭의 내용을 저장할 때 발생하는 문제가 있습니다.
b-iris.mobigen.com 사이트에 "ISSUE #1280"으로 보고서 생성해보았습니다.

#### 시각화 옵션 설정
![image](https://user-images.githubusercontent.com/3411842/58302810-fcb42700-7e27-11e9-87ce-f89ecc597346.png)

#### 언어 설정 - 대한민국
![image](https://user-images.githubusercontent.com/3411842/58302838-1ce3e600-7e28-11e9-85fb-262f102a4e59.png)

#### 언어 설정 - English
![image](https://user-images.githubusercontent.com/3411842/58302842-240af400-7e28-11e9-8a9f-23a883c75258.png)
