### ISSUE TITLE
브라우저 언어가 일본어 일경우일 경우 접속할 수 없는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1281]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by JoonseokRyu** [comment]
다이렉트 클라우드 서버에 이슈처리 반영되어 클로즈합니다.
