### ISSUE TITLE
IE에서 화면 깨짐 현상 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1287]
## 버그 설명 ##
IE에서 화면 깨짐 현상 발생

## 재현하는 방법 ##
프로세스 관리, 페이블 스페이스 사용율 조회, DB브라우저 실행시 검색 입력박스 깨짐 

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/55209328-51229800-5225-11e9-98fc-f107330a97cf.png)

![image](https://user-images.githubusercontent.com/4444717/55209409-b70f1f80-5225-11e9-90c8-141f958be9e0.png)

![image](https://user-images.githubusercontent.com/4444717/55209424-c4c4a500-5225-11e9-985f-aa6b3cc22668.png)

**Comment by JeongHeeDong** [comment]
수정 및 반영 일정 공유 요청 드립니다.

**Comment by veldise** [comment]
@JeongHeeDong 
KDN 일정을 고려하여 4월 4~5주 진행 예정입니다.
반영 일정은 미정입니다.

**Comment by onlyeon** [comment]
![Cap 2019-09-19 14-26-11-879](https://user-images.githubusercontent.com/11944592/65215741-8a0f3b80-dae9-11e9-87fa-b128cca4ab60.png)
![Cap 2019-09-19 14-25-59-352](https://user-images.githubusercontent.com/11944592/65215742-8bd8ff00-dae9-11e9-82e3-ef1d481855a0.png)
![Cap 2019-09-19 14-25-45-902](https://user-images.githubusercontent.com/11944592/65215745-8d0a2c00-dae9-11e9-9f38-dffaba92429a.png)

http://b-iris.mobigen.com/ 기준 수정 내역이 적용 되어있습니다.
확인 부탁 드립니다.

**Comment by veldise** [comment]
@onlyeon 
확인했습니다. 이슈 닫습니다.
