### ISSUE TITLE
[Direct Cloud]보고서/쿼리 조회 오류 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1288]
## 버그 설명 ##
쿼리 브라우저에서 실행되는 sql이 보고서에서는 오류가 발생함
- 컬럼명 alias에 'zzzz' 형태로 넣으면 에러 발생하는 것으로 보임

## 재현하는 방법 ##
동작을 재현하는 방법 :

정상동작
```sql
*| sql "select PART_DATE AS a, substr(user_id,1,1) || '****' AS b,  substr(user_name,1,1) || '****' as c, ACCOUNT_TYPE AS d, DOWNLOAD_CNT AS e, UPLOAD_CNT AS f, LINK_CNT AS g, ATTACH_CNT AS h, SCORE  from angora where COMPANY_CODE = '<%= cpn_cd %>'" | sort -SCORE
```

오류발생
```sql
*| sql "select PART_DATE AS 'a', substr(user_id,1,1) || '****' AS 'b',  substr(user_name,1,1) || '****' as 'c', ACCOUNT_TYPE AS 'd', DOWNLOAD_CNT AS 'e', UPLOAD_CNT AS 'f', LINK_CNT AS 'g', ATTACH_CNT AS 'h', SCORE  from angora where COMPANY_CODE = '<%= cpn_cd %>'" | sort -SCORE
```

캡춰화면 쿼리
```sql
/*+ LOCATION ( PARTITION >= '20181001000000' AND PARTITION < '20181101000000' ) */ 
select PART_DATE AS '日時', substr(user_id,1,1) || '****' AS 'ユーザーID',  substr(user_name,1,1) || '****' as 'ユーザー名', ACCOUNT_TYPE AS 'アカウント種類', DOWNLOAD_CNT AS 'ダウンロード数', UPLOAD_CNT AS 'アップロード数', LINK_CNT AS 'リンク数', ATTACH_CNT AS '添付ファイル送信', SCORE  
from  TB_USER_SCORE
;
```

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/55222189-9e672f80-524e-11e9-9201-22c4ad96385c.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by pjh0347** [comment]
@JeongHeeDong @veldise 재현해 보려면 해당 서버에 접속 정보가 필요합니다. 이메일로 공유 부탁드립니다.

**Comment by JeongHeeDong** [comment]
현재 개발 서버에서 해 보셔도 됩니다.(http://b-iris.mobigen.com)
![image](https://user-images.githubusercontent.com/4444717/55302152-cf2bac80-547a-11e9-8991-41ef527a071f.png)

**Comment by leehaejoon** [comment]
@pjh0347 @EricLeeMbg @namjals 

현재 내부적으로 해당 명령을 spark sql의 DataFrame을 통하여 처리하고있는것으로 보입니다.

하지만 spark sql에서 다음과 같이 한글, 일본어같은 멀티바이트 언어에 대한 aliasing을 지원하고있지 않는 근본적인 문제가 있어 현재로써는 지원이 어려운 기능으로 판단됩니다.

![스크린샷 2019-04-05 오후 1 52 24](https://user-images.githubusercontent.com/23020977/55604316-1206c080-57aa-11e9-964a-80afa013b4d5.png)

만약 반드시 해당 쿼리를 사용해야 한다면,

멀티바이트 언어로 aliasing을 시도했을 때 컬럼명을 내부적으로 임의로 할당하여 출력하는 방식은 가능할 것 같습니다.

예를들어 `* | sql "select host as '日時' from angora"` 와 같은 명령을 실행했을 때,

에러를 발생하는 대신 결과로 출력되는 테이블의 컬럼명을 `'日時'`이 아닌 임의의 컬럼명으로 대체하는 것입니다.

영문에 따옴표를 주어 aliasing하는 부분(`select host as 'a' from angora`)에 대해서는 수정 후 적용이 가능합니다.

**Comment by leehaejoon** [comment]
@pjh0347 @EricLeeMbg @namjals 

현재 내부적으로 해당 명령을 spark sql의 DataFrame을 통하여 처리하고있는것으로 보입니다.

하지만 spark sql에서 다음과 같이 한글, 일본어같은 멀티바이트 언어에 대한 aliasing을 지원하고있지 않는 근본적인 문제가 있어 현재로써는 지원이 어려운 기능으로 판단됩니다.

![스크린샷 2019-04-05 오후 1 52 24](https://user-images.githubusercontent.com/23020977/55604316-1206c080-57aa-11e9-964a-80afa013b4d5.png)


만약 반드시 해당 쿼리를 사용해야 한다면,

멀티바이트 언어로 aliasing을 시도했을 때 컬럼명을 내부적으로 임의로 할당하여 출력하는 방식은 가능할 것 같습니다.

예를들어 `* | sql "select host as '日時' from angora"` 와 같은 명령을 실행했을 때,

에러를 발생하는 대신 결과로 출력되는 테이블의 컬럼명을 `'日時'`이 아닌 임의의 컬럼명으로 대체하는 것입니다.

**Comment by seungfwani** [comment]
이해준 선임님의 코멘트 처럼 spark sql 에서 영어가 아닌 문자가 들어갔을때 발생하는 문제입니다.

현재 사용자가 as 뒤에 어떤 문자를 써도 그대로 처리 할 수 있도록 수정 하였습니다.

수정 사항은 목요일(8/29) 배포 예정입니다.

예) `*| sql "select HOST as 日時 from angora"` 명령어 수행시 컬럼명 = `日時`
      `*| sql "select HOST as '日時' from angora"` 명령어 수행시 컬럼명 = `'日時'`

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하여 처리된 것을 확인하였습니다.

- 스크린샷 1번
![image](https://user-images.githubusercontent.com/46172579/63913726-2b1b5100-ca6c-11e9-8c9c-a41f758b6c00.png)

- 스크린샷 2번
![image](https://user-images.githubusercontent.com/46172579/63913702-150d9080-ca6c-11e9-9eb9-a054def765f8.png)
