### ISSUE TITLE
[directCloud] 보고서 리스트 출력 오류

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1289]
## 버그 설명 ##
일본어가 들어간 단어 조회 리스트가 출력 되지 않음

## 재현하는 방법 ##

검색에서는 정상 조회 : `* | sql " select C_CODE from angora where  COMPANY_CODE in ('tel8035','coprofilesv', 'kovecinc') " | stats count(C_CODE) as CNT  by C_CODE | sort -CNT`

보고서에서 조회 하면 리스트가 빈컬럼으로 출력됨

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/55304781-1a988780-5488-11e9-8948-f83f1cf55952.png)

정상조회회
![image](https://user-images.githubusercontent.com/4444717/55304865-94c90c00-5488-11e9-9f12-682e3b8bfa98.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@JeongHeeDong 
혹시 재현되는지 다시 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/3411842/55305403-394c4d80-548b-11e9-842b-0e376e6d9005.png)

**Comment by JeongHeeDong** [comment]
출력되는것 확인 완료 되었습니다.
