### ISSUE TITLE
[Direct Cloud] "exportPDF" 기능 확인 및 버튼 삭제 가능 여부 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1291]
## 버그 설명 ##
1. "exportPDF" 버튼 삭제 요청
2. "exportPDF" 실행시 출력결과가 깨짐 수정 필요

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/55312299-242de980-54a0-11e9-9cb9-ba2f79a48eb4.png)

출력결과 깨짐

![image](https://user-images.githubusercontent.com/4444717/55312359-4cb5e380-54a0-11e9-8b8f-6453d77af66e.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@JeongHeeDong 
#1205 에서 해결 시도했으나 실패하였습니다. highcharts가 있을 때 PDF로 내보내기가 정상동작하지 않습니다.
기능 제거는 가능합니다.

**Comment by veldise** [comment]
금일~내일 오전 중 DC서버 배포 예정

**Comment by veldise** [comment]
배포되어 닫습니다.
