### ISSUE TITLE
[전력연구원] 메뉴 삭제후 오류 발생내역

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1294]
## 버그 설명 ##
전력연 b-iris 대메뉴 삭제 이후 오류 발생내역
클러스터관리 : "cluster": "cluster",
데이터 추가 : "data-import": "data-import",
DB조회 : "db-browser": "db-browser",
대화형 분석 : "ext-manager": "ext-manager"

![image](https://user-images.githubusercontent.com/29471177/55852457-12330180-5b98-11e9-8922-2b58afb34030.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
ㅁ 데이터모델 기능 선택시
![image](https://user-images.githubusercontent.com/29471177/55852490-37277480-5b98-11e9-88cb-1cfebd43b9ad.png)

ㅁ 보고서
 보고서 목록에서 "새보고서"버튼 클릭 시 
![image](https://user-images.githubusercontent.com/29471177/55852527-53c3ac80-5b98-11e9-99ed-37139b8acadc.png)

5월 초에 전력연구원 b-iris시연 일정이 잡혀 있는데요.
오류 메시지가 출력안되게 보완부탁드립니다.

**Comment by veldise** [comment]
@chohi22 
전력연구원이 MDA가 맞습니까? 보고서 편집 기능도 시연 대상인지 궁금합니다.

**Comment by chohi22** [comment]
MDA 맞습니다. 보고서 편집기능은 제외시킬겁니다.

**Comment by veldise** [comment]
@chohi22 
1. 보고서 관련은 제외이므로 처리하지 않아도 될 것으로 생각됩니다.
2. brick 서비스에서 `db-browser` 설정을 제거하신 것 같은데, 현재 버전에서는 `db-browser` 서비스가 필요합니다.
IRIS 의존성을 제거하여 `db-browser` 서비스가 불필요해지는 것은 Angora middleware 개발 일정상 5월 말에나 가능하므로, 설정은 다시 추가하고 다른 이슈로 요청하신 것처럼 메뉴를 제거하는 방향으로 가는게 좋겠습니다.

**Comment by veldise** [comment]
@chohi22 
`db-browser`를 재설정하시고 데이터모델 기능 동작 확인 부탁드립니다.

**Comment by veldise** [comment]
해결된 것으로 보고 닫습니다.

**Comment by veldise** [comment]
@chohi22 이슈 재오픈 이유를 적어주시기 바랍니다.

**Comment by chohi22** [comment]
확인후 close하겠습니다.

**Comment by veldise** [comment]
@chohi22 알겠습니다. 확인하시고 이슈 닫아주세요.

**Comment by chohi22** [comment]
패치 확인후 close합니다.
