### ISSUE TITLE
[전력연구원] 메뉴 삭제 요청 드립니다.

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1295]
5월 초에 전력연 시연계획이 잡혀있습니다.
아래의 그림 처럼 메뉴가 삭제 될 수 있도록 조치 부탁드립니다.

ㅁ 메뉴 변경 방법 공유 부탁드립니다.
1. 장기적으로는 관리자가 메뉴를 관리할 수 있었으면 좋겠습니다.
2. 삭제할 수 있는 방법을 공유
3. 삭제된 기능을 전력연에 배포

ㅁ 변경안
ㅇ 대메뉴 삭제
![image](https://user-images.githubusercontent.com/29471177/55852760-30e5c800-5b99-11e9-8679-9556842b1071.png)

ㅇ 고급시각화 항목 및 메뉴이동
![image](https://user-images.githubusercontent.com/29471177/55852790-54107780-5b99-11e9-966c-ce69f57bdca7.png)

**Comment by veldise** [comment]
@chohi22 
고급시각화 / 분석 유형 중에 Outlier 기능도 삭제 대상인가요?

**Comment by chohi22** [comment]
1. 삭제 요청하신 대상이 전력연구원에 설치된 IRIS-WEB인가요?
>  네, 맞습니다.

2. 좌상단 이름 변경이라고 적어주신 부분은 텍스트가 아니고 이미지라서 변경이 불가합니다. 이미지를 제공해주시면 교체하겠습니다.
> 디자인 시안 작업중이고요. 금주 금요일 작업 이후 차주 주간보고에 보고드리고 관련된 이미지 공유 드리도록 하겠습니다.

3. 고급시각화 / 분석 유형 중에 Outlier도 삭제 대상인가요?
> 이미지에 있는 것 처럼 시계열 3종, 분포 3종, 관계형 2종만 사용합니다.

**Comment by veldise** [comment]
IRIS-WEB 내부 구조 변경에 대한 작업이 진행중이라, 4월 4주에 진행하겠습니다.

@chohi22 
차후 정확한 데모시연 일정이 잡히면 알려주세요.

**Comment by veldise** [comment]
현재 버전에서 아래 내용을 적용하여 차주(4/17~18) 배포 예정입니다.

- 대메뉴 제거 (대시보드, 클러스터 관리, DB조회, 대화형 분석, 데이터 추가)
- 데이터 브라우저 일부 메뉴 제거 (이상탐지, 보고서)
- 데이터 브라우저 내 "이상탐지로 이동" UI 제거
- 고급시각화 분석 유형 일부 제거 (Outlier, 지도 2종)
- 좌상단 타이틀 로고 변경

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/56114767-bfdd5080-5f9c-11e9-9786-d74fa588eef1.png)
![image](https://user-images.githubusercontent.com/3411842/56114896-21052400-5f9d-11e9-9689-bcccddac6e92.png)
![image](https://user-images.githubusercontent.com/3411842/56114877-13e83500-5f9d-11e9-8e56-271e0180f18d.png)

로고는 디자인팀에서 작업중입니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/56183114-f922c880-604f-11e9-90e8-9ee8db1e0492.png)
![image](https://user-images.githubusercontent.com/3411842/56183117-fd4ee600-604f-11e9-8428-28d7cf7c66aa.png)

**Comment by veldise** [comment]
배포 완료되어 닫습니다.

**Comment by veldise** [comment]
@chohi22 이슈 재오픈 이유를 적어주시기 바랍니다.

**Comment by chohi22** [comment]
확인후 close하겠습니다.

**Comment by veldise** [comment]
@chohi22 알겠습니다. 확인하시고 이슈 닫아주세요.

**Comment by chohi22** [comment]
전력연구원 패치내역 확인후 close 합니다.
