### ISSUE TITLE
[중국어 적용] brick / 알람 리스트 깨짐

### ISSUE THREAD

**Issue by JoonseokRyu** [mobigen/IRIS-BigData-Platform#1296]
## 버그 설명 ##
중국어 선택시 알람 리스트 목록이 깨짐
![스크린샷 2019-04-16 오후 3 46 46](https://user-images.githubusercontent.com/6845938/56187983-40fd1c00-605f-11e9-9ce2-3fd6e01b0b3e.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 중국어 선택
2. 알람 더보기 이동
3. 좌측 리스트

## 예상한 행동 ##
![스크린샷 2019-04-16 오후 3 50 34](https://user-images.githubusercontent.com/6845938/56188047-6558f880-605f-11e9-9061-e96a12400d6a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
IRIS-Cloud 로 변환되면서 SMS 기능이 disable되어 닫습니다.
