### ISSUE TITLE
[중국어 적용] 알람 리소스(sms)가 한글로 표시됨

### ISSUE THREAD

**Issue by JoonseokRyu** [mobigen/IRIS-BigData-Platform#1297]
## 버그 설명 ##
중국어로 언어를 선택하여도 관련 아이템이 한글로 표시
![스크린샷 2019-04-16 오후 3 55 39](https://user-images.githubusercontent.com/6845938/56188409-676f8700-6060-11e9-849e-1a6fbd7413a1.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 중국어 선택
2. 알람 항목 설정으로 이동
3. agent 선택

## 예상한 행동 ##
중국어로 해당 아이템이 표시

**Comment by veldise** [comment]
영어도 동일합니다.

**Comment by sunghoon** [comment]
IRIS-Cloud 적용되면서 SMS disable 되어 닫습니다.
