### ISSUE TITLE
[공항철도] 일부 계정의 Jupyter notebook 메뉴 접근 오류

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1298]
## 버그 설명 ##
일부 계정에서 Jupyter notebook 메뉴로 들어가면 404 에러가 발생합니다.

## 재현하는 방법 ##
1. 오류가 발생하는 계정으로 B-IRIS 로그인
2. 대화형분석 - Jupyter 클릭
3. 404 에러가 표시된 화면이 나타남

## 기타 ##
원인 파악을 위해 필요한 내용을 말씀해주시면 현장에서 대응하겠습니다.

**Comment by veldise** [comment]
404 에러는 두가지 중 하나로 추측됩니다.
1. jupyter docker image 삭제됨
2. jupyter 웹 서버가 늦게 실행됨.
3. jupyter 메뉴 접근 권한이 없음

1번의 경우, jupyter docker image를 재설치해야합니다.
2번의 경우, 브라우저 새로고침을 하면 정상적으로 나올 것입니다.
3번의 경우, 메뉴 접근 권한이 해당 계정에 없는 것입니다.

1~2번의 경우는 발생하기 힘든 상황이므로 서비스 로그를 확인할 필요가 있습니다.

**Comment by veldise** [comment]
## 조윤경 선임 전달 사항

1. 어떤 계정(C**)은 404, 어떤 계정(B**)은 정상 동작
![image](https://user-images.githubusercontent.com/3411842/56491861-dc413600-6524-11e9-8297-5278ef5da5c6.png)

2. 404 계정은 docker container는 정상 실행, checkalive 실패함(404)
![image](https://user-images.githubusercontent.com/3411842/56491934-20ccd180-6525-11e9-88e4-83a1922976b1.png)
![image](https://user-images.githubusercontent.com/3411842/56491946-29250c80-6525-11e9-8409-6a0c66e74efe.png)
![image](https://user-images.githubusercontent.com/3411842/56491961-380bbf00-6525-11e9-9fef-8e79cb20324e.png)

3. 이외의 로그 정상

**Comment by veldise** [comment]
29일 공항철도 상암 방문 예정입니다.

**Comment by veldise** [comment]
`/attach/prepare.sh`에서 `chgrp` 명령어로 notebook 폴더의 group 권한을 변경하고 있습니다.
그런데 notebook 폴더의 경로가 되는 save 폴더가 없어서 `chgrp`가 수행되지 않아 발생하는 문제였습니다.

**Comment by veldise** [comment]
https://github.com/mobigen/iris-web-apps/commit/27414dd69b88bb9dd3669115d6c3365abc096e55
