### ISSUE TITLE
검색 / 특정 날짜의 데이터가 검색되지 않습니다(HDFS)

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1301]
## 버그 설명 ##
`WEATHER` 모델에 대한 검색 결과가 아래와 같습니다.
- 2007/10/26 00:00:00 ~ 2007/10/27 00:00:00 (결과 있음, 정상)
- 2007/10/26 00:00:00 ~ 2007/10/26 00:10:00 (결과 없음, 비정상)
- 전체시간, `* DATE='2007-10-26'` (결과 없음, 비정상)

## 예상한 행동 ##
2007/10/26 데이터가 존재하므로,
`2007/10/26 00:00:00 ~ 2007/10/26 00:10:00` 혹은
`2007/10/26 00:00:00 ~ 2007/10/26 00:00:00` 으로 검색 했을 때 결과가 있어야 합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/56554605-31d11d80-65cd-11e9-9bb2-303151b4720f.png)

![image](https://user-images.githubusercontent.com/3411842/56554618-3d244900-65cd-11e9-8460-3f5cb64dec52.png)

### 원시 데이터
![image](https://user-images.githubusercontent.com/3411842/56554767-c89dda00-65cd-11e9-98b9-b1874879703d.png)

**Comment by EricLeeMbg** [comment]
WEATHER data format 확인결과, 아래 그림처럼 YYYY-MM-DD형태로 되어 있음
- 이런 Timestamp에서도 시/분/초로 검색을 가능하게 할 경우 자동 형변환 기능이 필요
![20190430_163240](https://user-images.githubusercontent.com/44352311/56946820-3a45cd00-6b66-11e9-994e-b171976cf9ca.png)

시분초가 있는 데이터의 경우 
![20190430_163828](https://user-images.githubusercontent.com/44352311/56946881-6f521f80-6b66-11e9-85be-bb9e805c904e.png)

- 아래처럼 시작과 종료시간을 동일하게 적용할 경우 데이터 검색 안됨
- Spark에서 처리하는 query 내용으로 시스템 활용 전략적 측면으로 보임
![20190430_164154](https://user-images.githubusercontent.com/44352311/56947031-e5568680-6b66-11e9-9bea-b41322429925.png)

- Timestamp 형태는 'YYYYMMDDHHmmss' 일 경우 가장 정확하게 검색되는 것으로 보임, 다양한 테스트가 필요
- 시작시간은 '이상', 종료시간은 '미만'으로 처리됨
![20190430_165942](https://user-images.githubusercontent.com/44352311/56947868-61ea6480-6b69-11e9-82b8-3caa5d84ae7c.png)

**Comment by pjh0347** [comment]
#1352
