### ISSUE TITLE
고급시각화 / 이상치 관련 데이터 요청시 에러 발생

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1303]
## 버그 설명 ##
* 이상치 관련 데이터 요청시 에러 발생

## 재현하는 방법 ##
* 192.168.100.180 접속 후 로그인
* 데이터 브라우저 > 고급시각화
* 이상치 선택 후 아래 조건으로 실행
  * 데이터 모델: syslog
  * 시간 설정: 최근 1분

## 예상한 행동 ##
* 화면에 표현 가능한 데이터가 응답으로 전달

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/56567303-8e453480-65ef-11e9-917b-bd27da011f5f.png)

## 로그 ##
```json
{"q":"model name = 'syslog' start_date = 20190423174400 end_date = 20190423174532 | adv summary  TARGETS LEVEL_INT"}

{
  "message": "'NoneType' object has no attribute 'strip'", 
  "type": "<type 'exceptions.AttributeError'>"
}
```

```json
{"q":"model name = 'syslog' start_date = 20190423174400 end_date = 20190423174532 | adv outlier  TARGETS LEVEL_INT"}

{
  "message": "'NoneType' object has no attribute 'strip'", 
  "type": "<type 'exceptions.AttributeError'>"
}
```

**Comment by veldise** [comment]
#1251

**Comment by EricLeeMbg** [comment]
- 고급시각화 자료의 불일치로 보임
- 코드 추적결과, 해당 오류는 angora.cmds.impl.adv package에서 발생
- 회피 코드를 작성하여 PR 생성

**Comment by seungfwani** [comment]
현 운영서버(192.168.100.180)에서는 정상동작 합니다.

![image](https://user-images.githubusercontent.com/46172579/62514390-014e8000-b85a-11e9-8f5b-703c89f81d5a.png)
