### ISSUE TITLE
검색 / 피벗에서 '이동'할 경우 별칭 중복 표시 에러

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1304]
## 버그 설명 ##
스크린샷으로 설명 드리겠습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 계정 ssm0219로 만든 시각화 '버그테스트용_피벗'을 클릭
2. [피벗] 화면에서 실행하면 1번 스크린샷처럼 별칭이 정상적으로 적용된 결과가 조회됨
3. [피벗] 화면 우측 상단의 '이동' 버튼을 클릭하여 '검색으로 이동'을 선택
4. 이동하면 2번 스크린샷처럼 별칭이 중복 적용된 화면이 조회됨

## 스크린샷 ##
1) 피벗 화면
![별칭중복버그(1)](https://user-images.githubusercontent.com/35832986/56568475-0e6c9980-65f2-11e9-81f8-abdcbbd47175.JPG)

2) 검색 화면
![별칭중복버그(2)](https://user-images.githubusercontent.com/35832986/56568483-1298b700-65f2-11e9-8562-beca59f6510d.JPG)

**Comment by tylor-kr** [comment]
180 서버 배포 후 확인 되어 닫습니다.
