### ISSUE TITLE
[데이터 추가] 테이블 이름 중복 확인 invalid user error

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#1305]
## 버그 설명 ##
데이터 추가 탭을 이용해 데이터 추가 시 '입력'단계에서 테이블 이름에 대한 중복확인을 하면
아래 스크린샷과 같이 에러가 납니다. 
"예"를 누르면 해당 박스는 사라지고 우측 상단에 "다음"을 누르면 다음 단계로 넘어가 집니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. jack 아이디로 로그인
2. 데이터 추가 탭으로 csv파일 업로드 
3. "입력"단계에서 테이블 이름 중복확인

## 스크린샷 ##
![아이리스 버그](https://user-images.githubusercontent.com/32768535/56714894-20c11180-6771-11e9-9444-feea3b94308d.PNG)

## 로그 ##
HikariPool.PoolInitializationException: Failed to initialize pool: -ERR ISUSER [PGD-E002] Invalid user (User, Password, Host IP)

**Comment by GyuminJack** [comment]
해당 상황에서 에러를 무시하고 마지막단계에서 생성을 하게 되면 동일한 에러로그 발생으로 테이블 생성을 중지합니다.

[작업현황]
에러 발생으로 중지 합니다.
HikariPool.PoolInitializationException: Failed to initialize pool: -ERR ISUSER [PGD-E002] Invalid user (User, Password, Host IP)

**Comment by veldise** [comment]
@GyuminJack 
이전에 올려주셨던 이슈와 유사한 문제로 보입니다.
혹시 위 작업 전에 비밀번호를 변경하신 적이 있으신가요?

**Comment by tylor-kr** [comment]
@veldise @GyuminJack 

위 현상은 특정 계정 (이경우에는 `jack`) 에서만 발생하는 현상입니다.

사용이 가능하도록 임시 조치 해드렸으며, 해당 이슈는 내부적으로 관리 하는 이슈로 등록 되어 있기 때문에 닫겠습니다.
