### ISSUE TITLE
[한국도로공사] 특정 사용자 추가시 에러발생

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1309]
## 버그 설명 ##
특정사용자(user036) 추가시 에러 발생되며 다른사용자들은 정상으로 생성됨.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 클러스터관리 -> [관리] ->  사용자 메뉴에서 user036 사용자를 추가시 에러메세지 발생
![image](https://user-images.githubusercontent.com/25650544/56936048-1cf60c00-6b30-11e9-8056-0171884e3a56.png)

2. user036 계정은 생성되어 있지 않으며 다른 계정은 정상 생성됨.

![image](https://user-images.githubusercontent.com/25650544/56936058-2b442800-6b30-11e9-9345-80d4decca677.png)
![image](https://user-images.githubusercontent.com/25650544/56936061-3008dc00-6b30-11e9-8130-5a89f4c59f5c.png)
![image](https://user-images.githubusercontent.com/25650544/56936065-31d29f80-6b30-11e9-9018-832de91c1266.png)

3. iris db 상에서의 user036 계정은 확인되지 않습니다. 
확인을 요청드립니다. 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }
docker 버전정보입니다.
![image](https://user-images.githubusercontent.com/25650544/56936099-634b6b00-6b30-11e9-871a-c482ef359fd9.png)

**Comment by big-mobigen** [comment]
iris db 상에서의 유저정보
![image](https://user-images.githubusercontent.com/25650544/56936143-bc1b0380-6b30-11e9-8155-415c5b83446f.png)

**Comment by big-mobigen** [comment]
Docker에 올라간 R-studio에 접속하여 생성된 계정을 확인시 user036 계정이 있으며
/home/user036 권한 확인 시 다른 계정들과 권한이 달라 수정 하여 해결되었습니다.

**Comment by tylor-kr** [comment]
해결된 이슈이므로 닫습니다.
