### ISSUE TITLE
고급시각화에서 저장된 차트가 보고서에서 불러오기 될 경우 x축의 정렬순서 변경

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#1313]
## 버그 설명 ##
고급시각화에서 저장된 차트가 보고서에서 불러오기 될 경우 x축의 정렬순서가 마음대로 변경됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 고급시각화에서 batting 데이터로 스크린샷 1과 같이 구현후 저장.
2. 저장된 시각화 그래프를 보고서탭에서 불러오기
3, x축의 정렬순서가 뒤바뀜.

## 스크린샷 ##
<고급시각화에서 저장된 그래프>
![캡처1_Correct](https://user-images.githubusercontent.com/32768535/57120151-3f935980-6daa-11e9-8abe-bbddf6bb3c14.PNG)
<보고서에서 불러온 그래프>
![uncorrect](https://user-images.githubusercontent.com/32768535/57120152-402bf000-6daa-11e9-9cfe-3548814a5ca6.PNG)

**Comment by veldise** [comment]
@GyuminJack 
고급시각화의 경우, 각각의 축 설정에 따라 일부 데이터만 조회하여 시각화 합니다.
IRIS-DB를 대상으로 할 경우 이 일부 데이터는 랜덤하게 조회되므로 위와같이 다른 결과가 나올 수 있습니다.

x축 버튼을 클릭시 아래와 같이 설정 팝업이 나오는데, 이 설정에서
"정렬" 설정 여부를 확인 부탁드립니다.

**Comment by veldise** [comment]
옵션에 따른 결과이고, 오래된 이슈라 닫습니다.
