### ISSUE TITLE
대화형 분석 / 분석툴 container 실행중에 서비스 재시작시 오류

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1315]
## 버그 설명 ##
- 대화형 분석 서비스(ext-manager)를 재시작할 때, 오픈소스 분석도구 docker container가 실행중이면 페이지와 해당 container가 정상 연결되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 대화형 분석 > Jupyter에 접근한다.
2. ext-manager 서비스를 재시작한다.
3. 다른 유저로 로그인하여 대화형 분석 > RStudio에 접근한다. 
4. 에러 발생

## 원인 ##
ext-manager 서비스 내부에서 iframe - docker container 간 PORT NUMBER 매핑 정보를 관리하고 있는데 서비스를 내릴 경우 이 정보가 사라집니다. 서비스를 시작할 때 실행중인 docker container가 있다면 해당 docker container의 PORT NUMBER는 관리되지 않아 에러가 발생합니다.

## 해결 방안 1 ##
서비스를 내릴 때, 분석도구 docker container를 강제로 모두 내립니다.(`docker rm -f <container_id>`)

## 해결 방안 2 ##
서비스를 시작할 때 현재 실행중인 docker container 정보를 읽어서 PORT NUMBER 관리 정보를 갱신합니다.

**Comment by sunghoon** [comment]
@anhm @ollehQ 해당 이슈 확인하여 공유 바랍니다.

**Comment by anhm** [comment]
ext-manager 는 현재 앞으로 배포되지 않는 버전이기 때문에 해당 이슈는 닫도록 하겠습니다.
