### ISSUE TITLE
HDFS 조회 / 특정 파일 업로드시 Parse Error 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1316]
## 버그 설명 ##
첨부 파일(.csv)을 업로드시, 업로드 결과로 error가 출력됩니다.

## 첨부 파일
[한글파일.csv.zip](https://github.com/mobigen/IRIS-BigData-Platform/files/3162015/csv.zip)

## 내용
위 파일을 업로드시, 아래와 같은 에러가 반환됩니다.
파일에 문제가 있다고 추측되지만 정확한 원인 파악이 필요합니다.

```json
{
	"status": "error",
	"message": "Parse Error",
	"progress": 100,
	"filePath": "/B-IRIS/USERS/choi/%ED%95%9C%EA%B8%80%ED%8C%8C%EC%9D%BC.csv"
}
```

**Comment by hiy2259** [comment]
파일에는 문제는 없습니다. webHdfs 모듈 정리 하면서 코등 정리 및 에러 처리등을 하여 현제 로컬에서 테스트시 에러는 발생하지 안습니다.
이 문제는 webHdfs 모듈이 추가된 버전으로 올리면 문제가 없을것 같습니다.

**Comment by veldise** [comment]
Node.js 버전 미스매치 문제로 확인되어 닫습니다.
