### ISSUE TITLE
알람 방식 설정 / 문자(SMS) 전송 옵션의 변경이 안됨

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1317]
## 버그 설명 ##
재현하는 방법 참조

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [클러스터관리] , [데이터브라우저], [대화형 분석] 내 메뉴들에 대한 권한만 가지고 있는 계정
2. 우측 종모양 아이콘을 클릭하여 나오는 메뉴에서 [알람 방식 설정]을 클릭
3. 문자(SMS) 전송 을 ON으로 변경하고 '적용' 버튼을 누름
4. 다시 우측 종모양 아이콘을 누르고 [더보기]를 눌러 페이지 이동
5. 나타나는 페이지 우측의 [알람 방식 설정]을 클릭하면 문자(SMS)전송이 OFF로 설정되어 있음
6. 거기서 다시 ON으로 바꾼 후 '적용'을 누른 뒤 좌측 메뉴를 눌러 다른 페이지로 이동 (예를 들면 데이터브라우저의 [피벗] 등)
7. 그리고 다시 우측 종모양을 눌러 [더보기]를 눌러 페이지 이동 후 [알람 방식 설정]을 눌러보면 문자(SMS)전송이 OFF로 설정되어 있음을 확인할 수 있음
8. 결정적으로 SMS를 발송하는 시스템으로 전달하는 파일(.DAT)에 phones_use 가 false로 나타남
(즉, UI에서 설정한 내용이 반영되지 않는 것으로 보임)

## 예상한 행동 ##
1) 알람 방식 설정을 어디서 보든 동일하게 표시되어야 함
2) ON이 되었으면 문자가 발송되어야 함

## 기타 ##
공항철도 이슈입니다.

월요일에 인수인계가 예정되어 있어 다소 긴급한 사안입니다.

**Comment by veldise** [comment]
UI 버그로 확인되었습니다. 가능한 금일 배포 예정

**Comment by veldise** [comment]
해결 및 배포 완료했습니다. https://github.com/mobigen/B-IRIS-API-Gateway-Service/commit/5a8527eb6f6b59cd5f86736281eb1f80f544b712
