### ISSUE TITLE
데이터 import 에러

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#1318]
## 버그 설명 ##
메일로 보낸 데이터파일을 아이리스 웹 상에서 import 하는데 에러가 납니다.
![스크린샷 2019-05-14 오후 2 22 37](https://user-images.githubusercontent.com/3468426/57672704-1e592580-7654-11e9-8b13-5bc067c8763a.png)
![스크린샷 2019-05-14 오후 2 23 30](https://user-images.githubusercontent.com/3468426/57672710-25803380-7654-11e9-8ba8-786bc8cbd1b5.png)
![스크린샷 2019-05-14 오후 2 24 08](https://user-images.githubusercontent.com/3468426/57672719-2c0eab00-7654-11e9-821a-e359cabed3f7.png)
![스크린샷 2019-05-14 오후 2 24 47](https://user-images.githubusercontent.com/3468426/57672733-316bf580-7654-11e9-8456-37f750c5b510.png)

**Comment by sunghoon** [comment]
@pjh0347  아래를 참고하여 진행해 주세요.

Data-Conversion-Service 서비스의 addon/iris-load/loader.py 모듈에서 key가 한글로 구성되어 있을때 발생하는 것으로 확인하였습니다.

- key encoding 오류가 발생하더라도 데이터가 문제 없이 실행될수 있도록 예외처리를 추가해 주세요.

**Comment by pjh0347** [comment]
@sunghoon 급한 업무인가요?
@namjals 위 내용 follow up 바랍니다.

**Comment by namjals** [comment]
5월 24일 이후 진행 예정

**Comment by sunghoon** [comment]
비슷한 상황이 발생하면 새 이슈로 처리하겠습니다.
