### ISSUE TITLE
[전력연구원] hdfs 서비스 오류

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1319]
## 버그 설명 ##
나주본사 요청으로 전력연구원 해외용 개발서버 CDH5.4.8 -> CDH 6.2.0으로 업그레이드 이후 HDFS서비스 오류발생

## 스크린샷 ##
메인화면
![image](https://user-images.githubusercontent.com/29471177/57679955-7f3e2900-7667-11e9-8078-698d51464e7d.png)

HDFS 브라우저
![image](https://user-images.githubusercontent.com/29471177/57680021-9ed55180-7667-11e9-8afa-2e7cd58b54db.png)

B-IRIS 상태
![image](https://user-images.githubusercontent.com/29471177/57680070-bc0a2000-7667-11e9-8008-50ec0e33c70e.png)

CHD 6.2.0 버전정보
참고로 hadoop 3.0.0버전임.
![image](https://user-images.githubusercontent.com/29471177/57680220-15724f00-7668-11e9-89e7-53c112c3a70f.png)

**Comment by veldise** [comment]
@chohi22 
첨부하신 스크린샷을 기준으로 보았을때, HDFS 브라우저(hdfs-browser) 서비스는 정상동작하는 것으로 보이고
HDFS 의 상태를 체크하는 부분에 문제가 있는 것 같습니다.

본문 현상이 발생하는 서버의 HDFS 접속 정보가 필요합니다.
- (master node) host address (ex) `192.168.101.50`)
- (master node) port number (ex) `8020`)
- webhdfs API port number (ex) `50070`)

**Comment by chohi22** [comment]
@veldise 
정상적인 경우는 /B-IRIS/USERS/mobigen/ 폴더가 보여야 하는데 디렉토리가 조회가 안되고 있고요.
hdfs 접속 정보는 서비스 상태에 화면 덤프방아서 올렸는데, test로 다시 올립니다.


{   "super.user": "****",   "user.path": "/B-IRIS/USERS/",   "master.ip": "10.1.1.11",   "master.port": "8020",   "webhdfs.port": "50070" }
--

**Comment by veldise** [comment]
@chohi22 
저희 B-IRIS 설정 정보말고, 실제 hadoop file system 정보가 필요합니다.
두 개가 불일치하기 때문에 발생하는 현상일 가능성이 크기 때문입니다.

HDFS 조회 화면 접근시 `/B-IRIS/USERS/<user_id>` 폴더를 생성하게 되어 있는데,
super user인 root는 폴더를 생성하지 않습니다. 다른 사용자로 접속 테스트 바랍니다.

**Comment by chohi22** [comment]
ㅁ HDFS 파일 조회
![image](https://user-images.githubusercontent.com/29471177/57743417-f0c9b600-76ff-11e9-8f32-7c767ac2e62f.png)

ㅁ b-iris hdfs 파일 브라우저
![image](https://user-images.githubusercontent.com/29471177/57743460-1787ec80-7700-11e9-904a-fd9a198bf47c.png)

hdfs파일조회 하는 화면과 b-iris파일 브라우저 조회 내용이 틀리고요.
cdh 5.4.8일때는 데이터 모델링까지 되서 검색, 피벗, 고급시각화까지 전력연구원에 시연했습니다.
cdh 6.2.0버전 업그레이드 이후 발생하는 문제입니다.

메일로도 문의를 드렸었는데요.
b-iris가 HDFS 3.0.0을 지원하는지요?

**Comment by chohi22** [comment]
ㅁ hdfs-browser 로그 첨부합니다.
[app.log](https://github.com/mobigen/IRIS-BigData-Platform/files/3180680/app.log)
[error.log](https://github.com/mobigen/IRIS-BigData-Platform/files/3180681/error.log)

**Comment by veldise** [comment]
@chohi22 
b-iris HDFS 브라우저가 대상으로 하는 HDFS가 말씀하신 hdfs와 다른 것으로 보입니다.
서버 관리자에게 문의하시기 바랍니다.

HDFS 3.0 지원 여부는 조사해서 메일로 드리겠습니다.

**Comment by suk555** [comment]
권영길팀장 의견은 b-iris에서 hdfs 2.7.x의 환경을 가지고 접속하게되는데
대상 hdfs가 3.0이면 b-iris가 접속하는 환경 설정을 모두 3.0으로 맞춰야할거 같다는 의견입니다.
즉, conf디렉토리 파일을 3.0 파일로 교체해야한다는 말이죠.
그런데, 2.7.x와 3.x와 차이가 많으면 hdfs클라이언트를 3.0으로 올려야할 수 도 있습니다.
본사 개발서버에서 테스트를 위한 CDH업그레이드는 빠르면 오늘 아니면 늦으면 금요일 업그레이드 가능한 상태입니다.

**Comment by veldise** [comment]
@suk555
HDFS 3.0 지원은 제가 사전에 전달받지 못한 내용이라서, 일정상 불가능할 수 있습니다.

**Comment by veldise** [comment]
@chohi22 @suk555 
배성훈 그룹장님 통해서 일단 HDFS 3.0 지원 여부 테스트 진행하는 걸로 되었습니다.
3.0 지원을 위한 업무량이 많거나, 3.0 지원하면 2.7.3에 맞출 수 없을 경우 3.0 지원이 불가할 수 있습니다.

**Comment by chohi22** [comment]
CDH6.2로 업그레이드 되면서, webhdfs 포트가 50070->9870으로 변경되었네요.
확인후 이슈 close합니다.
오장석 팀장님 감사합니다.

ㅁ config 수정(50070 -> 9870)
./b-iris-data-discovery-service/angora.conf:  spark.hdfs.rest.host: 10.1.1.11:50070
./b-iris-data-discovery-service/angora.conf.templete:  spark.hdfs.rest.host: HDFS_CLUSTER_MASTER_IP:50070
./network.conf:hdfs.webhdfs.port=50070

![image](https://user-images.githubusercontent.com/29471177/57751870-0e0f7c00-7722-11e9-8d9b-dd6431d1b8fe.png)
