### ISSUE TITLE
데이터 추가 / 데이터 추가 기능으로 입력한 데이터에 대하여 검색 시 결과가 없는 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1320]
## 버그 설명 ##
데이터 브라우저 검색에서 시간 범위를 설정 후 데이터를 검색하면 데이터가 나오지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
* 아래 조건으로 검색시 검색 결과가 옴
    * 데이터 모델 선택 -> japanmdt
    * 시간 설정 -> 전체시간
    * 쿼리 -> *
* 아래 조건으로 검색시 검색 결과가 안옴
    * 데이터 모델 선택 -> japanmdt
    * 시간 설정 -> 2019/04/01 00:00:00 ~ 2019/04/01 00:00:00
    * 쿼리 -> *

**Comment by anhm** [comment]
@hiy2259 
해당 원인의 경우 데이터가 로딩된 파티션에 문제 가 있습니다.
현재 시간(partitiondate) 컬럼은 DT로 되어 있으며, 해당 시간의 범위는 2019-04-01 정의가 되어 있으나,
실제 IRIS에 생성된 파티션 정보는 20180101000000 로 되어 있는 상태입니다.

2018년도 파티션 범위에 2019년도 데이터가 들어가 있는 상태입니다.
해당 문제로 인해 전체 시간을 주면 결과가 나오지만 2019년도로 범위를 주면 2019년도 파티션 정보는 존재하지 않아서 데이터가 나오지 않고 있습니다.

**Comment by anhm** [comment]
참고로 해당 이슈를 해결하기 위해서는 데이터를 알맞게 가공하여 다시 로딩 해야 합니다.

**Comment by veldise** [comment]
@pjh0347 
대표이사님께 확인 결과 본문의 데이터 로딩은 "데이터 추가" UI를 통하여 수행하였다고 합니다.
data-trans-service에 문제가 없는지 확인 부탁드립니다. UI 쪽도 확인하겠습니다.

**Comment by anhm** [comment]
해당 기능으로
데이터를 가져올 경우 다음과 같이 DT 컬럼이 소수점이 나옵니다.
![스크린샷 2019-05-16 오후 5 45 21](https://user-images.githubusercontent.com/3415270/57839930-98c7a800-7802-11e9-9302-df825f0d87f6.png)

이를 아래와 같이 변경하시면
![스크린샷 2019-05-16 오후 5 45 33](https://user-images.githubusercontent.com/3415270/57839970-a9781e00-7802-11e9-8ce5-831531492e70.png)

정수값으로 변경이 됩니다.
![스크린샷 2019-05-16 오후 5 45 53](https://user-images.githubusercontent.com/3415270/57839985-b09f2c00-7802-11e9-95b7-dee5f26f2d47.png)

이후 컬럼 설정 부분에서
![스크린샷 2019-05-16 오후 5 44 28](https://user-images.githubusercontent.com/3415270/57840000-b7c63a00-7802-11e9-8c9a-83846abe4290.png)

파티션키/파티션 구분일을 선택해 주시면 원하시는 형태로 로딩이 가능 합니다.

**Comment by veldise** [comment]
@anhm 
추가 설명 감사합니다 👍

**Comment by veldise** [comment]
데이터가 적절히 가공되지 않아서 발생한 이슈였습니다. 닫습니다.
