### ISSUE TITLE
위경도 있는 데이터 시각화 오류

### ISSUE THREAD

**Issue by epkim2015** [mobigen/IRIS-BigData-Platform#1321]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
위경도 있는 Data 를 시각화 하려 했으나 결과 값이 나오지 않아, 직접 검색 해보았으나
아래와 같이 오류 발생

## 스크린샷 ##
![b-iris_errror_!](https://user-images.githubusercontent.com/45088022/57897565-551b7f80-7890-11e9-8679-be21f85b316c.png)

**Comment by namjals** [comment]
내부에서 생성하는 데이터 프레임의 위도 경도 컬럼명을 "latitude", "longitude"로 하드코딩하여 "LON"이라는 컬럼을 데이터 프레임의 컬럼에서 찾지못해 발생한 에러입니다.
위도 경도 컬럼명을 geostats에 입력받은 컬럼명을 쓰도록 수정하였습니다.

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/63917794-5c008380-ca76-11e9-8b11-813bdb14c556.png)
