### ISSUE TITLE
[DC][HDFS Browser] 메인메뉴에서 HDFS Browser 선택 시 에러

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1323]
## 버그 설명 ##
IRIS-WEB 메인메뉴에서 왼쪽 상단에 HDFS 조회 선택 시 에러발생 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/25650544/57904843-69bb4000-78af-11e9-9416-9605c660098f.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by big-mobigen** [comment]
[DC] 사용자관리 메뉴중에 사용자권한 , 그룹권한 메뉴 선택시 에러도 나타납니다. 

![image](https://user-images.githubusercontent.com/25650544/57907272-e7834980-78b7-11e9-87bf-c2b0fef7e594.png)

아래 화면은 account서비스 재기동 후 나타나는 docker logs 내용을 캡쳐한 화면입니다. 

![image](https://user-images.githubusercontent.com/25650544/57907314-07b30880-78b8-11e9-85c5-99dc432786cd.png)

**Comment by veldise** [comment]
1년 이상 지난 이슈라 닫습니다.
혹시 현상이 재현되면 Reopen 해주시기 바랍니다.
