### ISSUE TITLE
adv summary 에러

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#1324]
## 버그 설명 ##
summary 함수가 동작하지 않습니다.

## 재현하는 방법 ##
1. 데이터 브라우저 -> 검색
2. syslog데이터 선택, 전체 시간
3. * |  adv summary TARGETS LEVEL_INT 쿼리 실행
4. ['NoneType' object has no attribute 'strip'] 에러 발생

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
현 운영서버(192.168.100.180)에서는 이슈내용이 재현되지 않고, **정상동작** 합니다.

![image](https://user-images.githubusercontent.com/46172579/62514170-5342d600-b859-11e9-8b9b-3a705e8aa626.png)

**Comment by seungfwani** [comment]
이슈로 등록된 문제의 원인인 `NoneType Error` 는 해결이 되었으나,
adv의 summary/outlier 결과로 리턴되는 값이 제대로 나오지 않아 이슈를 다시 열었습니다.

현재 summary/outlier 의 결과가 정상적으로 나오도록 수정하였고,
수정 내용은 운영서버에 배포 예정입니다.

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하여 `adv` 명령어의 `summary`/`outlier`의 계산 결과가 정상적으로 나오는 것을 확인했습니다.

![image](https://user-images.githubusercontent.com/46172579/63913605-ae887280-ca6b-11e9-9cfc-0cdfea760f06.png)
