### ISSUE TITLE
Angora / ade 명령어 에러 

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1329]
## 버그 설명 ##
* ade 명령어 실행시 에러가 반환됨

## 재현하는 방법 ##
1. http://192.168.100.180/#!/ 접속 후 계정 로그인
2. 데이터 브라우저 > 이상탐지 메뉴로 이동 후 아래 조건으로 실행
3. 실행 조건
![image](https://user-images.githubusercontent.com/13827425/58083223-8dee8800-7bf3-11e9-8da2-623166060b5d.png)
4. 에러 발생

### http reqeust
* 아래 내용으로 sid 발급 후 실행 요청하면 에러 발생
* url: http://192.168.100.180:6036/angora/ade/jobs
* reqeust body
```json
{
    "q": "*",
    "datamodel_id": "61aa1a9e-b6f5-4196-9bef-9b3b62fcff43",
    "ade": {
        "values": [{
            "name": "LEVEL_INT",
            "func": "sum"
        }],
        "model": "SPC",
        "permisive": true,
        "null_value": null,
        "test_period": {
            "start_date": "20190521170000",
            "end_date": "20190521181000"
        },
        "reference_period": {
            "start_date": "20190421000000",
            "end_date": "20190521170000"
        },
        "unit": {
            "value": "10M",
            "match": true
        },
        "date_classification": "sameday",
        "key": [{
            "name": "HOST",
            "size": 100
        }, {
            "name": "PRIORITY",
            "size": 100
        }]
    },
    "start_date": "20190521170400",
    "end_date": "20190521180417",
    "job_time": "1558429457463"
}
```

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/58083313-b6768200-7bf3-11e9-8ef4-f947fb6fee66.png)

**Comment by pjh0347** [comment]
이상탐지 명령어 파서 부분에 키 두 개 이상에 대한 처리가 제대로 동작하지 않아 발생하는 이슈 입니다. 이번달 중으로 개선하겠습니다.

**Comment by pjh0347** [comment]
로컬 개선 완료.

**Comment by pjh0347** [comment]
문법 파싱 문제는 개선하여 운영 서버에 적용하였습니다.
하지만 키를 두 개 이상 설정한 경우 실행 시간이 상당히 길어 집니다.
향후 최적화를 통해 성능을 개선할 예정입니다.

**Comment by pjh0347** [comment]
이상 탐지 모델을 최적화 하여 로컬 개선하였고, 차주 목요일 운영 서버 반영될 예정입니다.

**Comment by pjh0347** [comment]
현재는 이슈 본문의 조건으로 실행 시킬 경우 상당한 시간이 걸려서 결과가 출력되지는 않고 있는 상황 입니다. 
![image](https://user-images.githubusercontent.com/5305236/64665639-3cae2100-d48e-11e9-86fc-16588cbf41f3.png)

**Comment by pjh0347** [comment]
운영 서버에 적용 시키 후 결과입니다.
![image](https://user-images.githubusercontent.com/5305236/65570387-e7990180-df9b-11e9-89a8-8eabd077d006.png)
![image](https://user-images.githubusercontent.com/5305236/65570412-f5e71d80-df9b-11e9-91d6-be2cf3a6324b.png)
