### ISSUE TITLE
Angora / pivot 명령어 에러

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1330]
## 버그 설명 ##
* pivot 명령어 실행시 에러가 반환됨

## 재현하는 방법 ##
1. http://192.168.100.180/#!/ 접속 후 계정 로그인
2. 데이터 브라우저 > 피벗 메뉴로 이동 후 아래 조건으로 실행
3. 실행 조건
  ![image](https://user-images.githubusercontent.com/13827425/58216541-f6478180-7d39-11e9-94bb-05dc24b7c997.png)

### http reqeust
* 아래 내용으로 sid 발급 후 실행 요청하면 에러 발생
* url: http://192.168.100.180:6036/angora/query/jobs
* reqeust body
```json
{
    "q": "model name = 'syslog' start_date = 20190516000000 end_date = 20190523084932 | pivot count(*),sum(LEVEL_INT) SPLITROW HOST,PRIORITY,TAG SPLITCOL PROGRAM COLSIZE 500",
    "size": 500
}
```

**Comment by seungfwani** [comment]
해당 이슈는 위의 조건으로 pivot 결과를 도출하는 과정에서  syslog의 `PROGRAM` 필드의 데이터 중, `XRDP` 과 `xrdp`, `XRDP-sesman` 과 `xrdp-sesman`,

**Comment by seungfwani** [comment]
해당 이슈는 위의 조건으로 처리가 되는 도중에
dataframe의 필드 중 중복되는 이름을 가진 필드가 있어 발생한 문제입니다. 

syslog의 PROGRAM 필드의 데이터에는 아래와 같은 데이터가 저장이 되어 있는 것으로 파악됩니다.
    - `XRDP` 과 `xrdp`, `XRDP-sesman` 과 `xrdp-sesman`

열 선택 조건에서 `PROGRAM` 이 아닌 다른 필드를 선택하면 현재 버전에서 같은 이슈는 발생하지 않습니다.
![image](https://user-images.githubusercontent.com/46172579/62445913-680d6400-b79c-11e9-8a09-3b6396ca8806.png)

현재 앙고라에서는 dataframe 만들때는 대/소문자를 구별하여 처리하고, 
이후 select를 할때는 대/소문자를 구분없이 처리하는 부분이 있습니다.
이 부분에서 논리적 차이가 있었습니다.

해당 이슈 처리를 위해서 대/소문자 구분없이 `XRDP`-`xrdp` 를 같은 값으로 처리를 하도록 수정하였습니다.
운영서버(192.168.100.180)에는 배포 예정입니다.

**Comment by seungfwani** [comment]
위의 <이슈 처리 내용> 이 변경된 점이 있습니다.

위에서는 `XRDP`/`xrdp` 와 같은 대/소문자 구분을 하지 않고, 같은 값으로 처리하도록 하였으나,
데이터에 저장된 값을 앙고라에서 임의로 변환 하는 것이라는 문제가 있었습니다.

따라서, 대/소문자를 구분하여 처리, 
즉, 저장된 데이터를 그대로 pivot 할 수 있도록 수정하였습니다.

**Comment by seungfwani** [comment]
현 이슈를 수정함에 따라 다른 버그가 발생하여 
현 이슈 수정내용을 변경하고 있습니다.

**Comment by tylor-kr** [comment]
@seungfwani 
제가 작성한 이슈를 임의로 변경 하시면 안됩니다.
다른 이슈가 발생 했을 때에는 새로 이슈를 생성 해야 합니다.

**Comment by seungfwani** [comment]
이슈 처리를 위해서 
pivot 결과로 생성되는 dataframe 필드의 이름을
대/소문자 구분없이 하도록 수정하였습니다. (XRDP-xrdp 를 같은 값으로 처리)

운영서버에는 반영 예정입니다.

**Comment by seungfwani** [comment]
운영서버에 배포완료 하였습니다.

![image](https://user-images.githubusercontent.com/46172579/64929807-b7e44e00-d865-11e9-98d5-ca19fd617341.png)
