### ISSUE TITLE
데이터 모델 편집시 유형 변경 select box z-index 이슈

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1334]
## 버그 설명 ##
select box 는 펼쳐진 상태이지만 아래 목록이 나오지 않습니다.  
![image](https://user-images.githubusercontent.com/5515493/58295475-6f160e80-7e0a-11e9-819a-f23b7e607068.png)  
스크롤바를 내리면 그때서야 select box 아이템들이 보입니다.  
![image](https://user-images.githubusercontent.com/5515493/58295535-a389ca80-7e0a-11e9-921b-86eb09938856.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by tylor-kr** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/693 와 동일한 이슈 입니다.

**Comment by veldise** [comment]
table - select-box 연계시 이슈는 당장 해결하기 어렵고,
"컬럼 설정"에 해당하는 영역의 height가 잘못 설정된 것 같은데 이부분만 일단 해결이 필요합니다.

**Comment by tylor-kr** [comment]
`height` 동작 처리 후 배포 되어 닫습니다.
