### ISSUE TITLE
Angora / model-stats 명령어 에러

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1335]
## 버그 설명 ##
* model-stats 명령어 실행시 에러가 반환됨

## 재현하는 방법 ##
1. http://192.168.100.180/#!/ 접속 후 계정 로그인
2. 데이터 브라우저 > 검색 메뉴로 이동 후 아래 조건으로 실행
3. 실행 조건 (조회 결과가 없을 경우 시간 설정을 넓게 조정)
  ![image](https://user-images.githubusercontent.com/13827425/58294058-168f4300-7e03-11e9-8572-b31fce1a2d06.png)
4. 실행 후 좌측 하단 특정 컬럼을 클릭하여 컬럼 상세 정보 요청(해당 이슈 에서는 HOST 클릭)
  ![image](https://user-images.githubusercontent.com/13827425/58294082-2eff5d80-7e03-11e9-890a-6d53a8a575c5.png)

### http reqeust
* 아래 내용으로 sid 발급 후 실행 요청하면 에러 발생
* url: http://192.168.100.180:6036/angora/query/jobs
* reqeust body
```json
{"q":"model-stats name = 'syslog' start_date = 20190523160000 end_date = 20190524165154 field = HOST | where HOST = 'gcs6' or HOST = 'gcs1'"}
```

### http response
* resonse body
```json
{
  "message": "[SPARK] \ud574\ub2f9 \ud544\ub4dc '`HOST`'\ub294 \uc8fc\uc5b4\uc9c4 \uc785\ub825 \ud544\ub4dc[distinct_count, type, name] \uc5d0 \uc18d\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. ", 
  "type": "<class 'pyspark.sql.utils.AnalysisException'>"
}
```

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/58294124-59511b00-7e03-11e9-9e49-206d625bc13f.png)

**Comment by namjals** [comment]
아래 2가지 방법으로 현재 모두 재현되지 않습니다.
1. 재현하는 방법, 2 http reqeust
![image](https://user-images.githubusercontent.com/22319132/63740217-118ed380-c8cb-11e9-9be3-b04833e68a16.png)
