### ISSUE TITLE
고급시각화 모듈중에 "워드클라우드" 모듈이 필요합니다. 물론 대시보드에서도...

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#1336]
## 기능 요청 ##
검색한 특정 필드의 데이터를 "한글/영어" 형태소 분석을 해서 단어별로 워드클라우드 GUI 생성

**Comment by veldise** [comment]
워드클라우드 데이터 생성을 위한 명령어도 필요하므로 Angora 도 같이 라벨링 하였습니다.

**Comment by JeongHeeDong** [comment]
특정 컬럼에 저장되어 있는 한글/영문 문장에 대한 형태소 분석을 통한 워드클라우드 기능이 생성 되었는지 , 현재 진행 상황이 어떻게 되는지요?

**Comment by veldise** [comment]
@JeongHeeDong 
Analyzer 쪽에는 현재 다른 업무로 진행되고 있지 않습니다.

@anhm 
일정 공유 부탁드립니다.

**Comment by seungfwani** [comment]
@veldise 
앙고라에 필요한 기능은 개발 하였으며, 메일로 관련 내용을 공유하였습니다.
확인 부탁드립니다.

**Comment by sunghoon** [comment]
dicscovery에서 adv에 wordcloud 옵션을 추가해두었습니다. 관련 정보는 아래 주소를 참고하세요. 
http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/adv.html?highlight=adv

그리고 해당 기능은 studio에서 워드 클라우드 시각화 유형으로 동작하고 있습니다. 

@eumminsun 해당 기능 점검하여 진행 해 주시기 바랍니다.
