### ISSUE TITLE
보고서 / 리스트 컴포넌트에서 시간 컬럼 출력 시 이슈

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1337]
## 버그 설명 ##
[보고서]의 '리스트' 컴포넌트로 데이터모델의 '시간' 컬럼을 출력했을 때 표시되는 값이 이상함

## 재현하는 방법 ##
동작을 재현하는 방법 :
(이슈 발견 시 사용한 모델: ssm0219 계정이 만든 LAPD_CRIME)
1. [보고서] 에서 [새 보고서] 클릭하여 보고서 생성 화면으로 이동
2. '리스트' 컴포넌트를 생성
3. 세부 설정은 하단 스크린샷과 같이 설정
4. '실행' 버튼을 누르면, 스크린샷에서와 같이 시간이 UNIX Time으로 보이는 값이 나타남

## 예상한 행동 ##
![image](https://user-images.githubusercontent.com/35832986/58401155-1065c480-8098-11e9-9f25-c6ec717aed61.png)

예상되는 결과는 실제 STIME이 입력되어 있는 값을 보여주는 것 
(상단 스크린샷은 동일한 쿼리를 DB 브라우저에서 실행한 결과)

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/58401238-3be8af00-8098-11e9-92d7-49e98d16fed8.png)

**Comment by veldise** [comment]
유사 이슈: https://github.com/mobigen/IRIS-BigData-Platform/issues/1332#issuecomment-495466268
`sql` 명령어를 사용하여서 발생하는 문제로 생각됩니다.

참고로, 현재 목록에 항목 출력시 uniq를 적용하는 옵션을 개발중에 있습니다.

**Comment by veldise** [comment]
현재 최신 버전에는 해결된 이슈입니다.

![image](https://user-images.githubusercontent.com/3411842/82865013-cb9d9380-9f60-11ea-85f9-90bcf51efb72.png)
