### ISSUE TITLE
Angora / 검색, 피벗 csv, json 다운로드 안되는 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1338]
## 버그 설명 ##
HTTP GET Request URL = http://192.168.101.50:6036/angora/query/jobs/1559020878.6464/download?type=csv&sep=%2C  
위와 같이 요청시 아래와 같이 에러가 발생합니다.
angora error status code: 500 INTERNAL_SERVER_ERROR
angora error response data: angora error: DownloadHandler can only have PollingResultHandler as a delegate.
Status 코드는 500이고 메시지는 DownloadHandler can only have PollingResultHandler as a delegate.로 나옵니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
#1344 번 이슈와 같은 내용으로 해결되었습니다.
