### ISSUE TITLE
보고서 편집과 보기 화면의 출력 화면 다름.

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#1339]
## 버그 설명 ##
보고서 편집 화면에서 히스토그램을 그릴 경우 그룹 값이 세개로 그래프로 제대로 출력이 되지만
보기 화면에서는 개별 컬럼의 카운트가 같이 등장.

## 재현하는 방법 ##
동작을 재현하는 방법 :
보고서 내 tmp_saved (jack 계정으로 생성) 클릭후 하단부 컴포넌트에서 클릭

## 스크린샷 ##
제대로 작동 되는 화면(편집화면)
![주석 2019-05-28 163930](https://user-images.githubusercontent.com/32768535/58460093-dc59d480-8167-11e9-8c7e-5343158a1217.png)
갑자기 column이 나온 화면
![주석 2019-05-28 164012](https://user-images.githubusercontent.com/32768535/58460131-f09dd180-8167-11e9-8622-f32bb4f5f797.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@GyuminJack 
시각화 옵션 > 데이터 탭에 x축이 특정 값으로 고정되어 있어 발생하는 문제입니다.
아래와 같이 PETAL_LEN 으로 지정되어 있어 PETAL_LEN 을 선택시에는 정상 출력되고,
PETAL_WID 일 때는 비정상 출력되는 것입니다.

`rename` 등의 명령어를 통해 컬럼명을 하나로 통일하는 것을 권장 드립니다.

![image](https://user-images.githubusercontent.com/3411842/58464972-a883ac80-8171-11e9-8342-49949973a714.png)

**Comment by GyuminJack** [comment]
![image](https://user-images.githubusercontent.com/32768535/58521409-a2381380-81f7-11e9-8b32-e16f7b7ac095.png)
해당 그래프는 쿼리를 통해 x축을 정하고 있습니다. 편집화면에서 테스팅 해본 결과 <%= column_name %>이 변경될 경우 정상적으로 시각화 옵션 내 x축 값도 변하고 있습니다.
그럼에도 불구하고 문제상황이 똑같이 나타나고 있는것으로 확인됩니다.

**Comment by veldise** [comment]
@GyuminJack 
편집 화면에서는 쿼리 결과에 따라 시각화 옵션 내 x축 값이 변하지만, 보기 화면에서는 변하지 않습니다.

**Comment by GyuminJack** [comment]
그러면 그래프에 마우스를 가져다댈때 나오는 툴팁정보에 표출되는 컬럼명이 바뀐 컬럼명으로 적용되어 보여질 것으로 여겨지는데 제 생각이 맞을까요?

**Comment by veldise** [comment]
@GyuminJack 
따로 구두로 설명을 드려야할 것 같은데, 동작이 다음과 같습니다.

### 편집 화면
1. 쿼리 실행 
2. 쿼리 결과 중 필드 정보를 시각화 옵션 > 데이터 탭에 반영
3. 데이터 탭 x축 값 변경됨
4. 변경된 x축 값으로 차트 Draw

### 보기 화면
1. 쿼리 실행
2. 데이터 탭에 설정된 x축 값 기준으로 차트 Draw

편집 화면에서는 쿼리 결과 기준으로 시각화 설정을 위해서 위와 같이 동작하는 것이고
보기 화면에서는 저장된 값 기준으로 차트를 그릴 뿐이므로 변경이 되지 않는 것입니다.

**Comment by GyuminJack** [comment]
답변감사합니다.

**Comment by veldise** [comment]
답변된 이슈이므로 닫습니다.
