### ISSUE TITLE
Angora / sort 명령어 에러

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1343]
## 버그 설명 ##
* sort 명령어를 여러개 사용할 경우 마지막 sort 명령어만 적용됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://192.168.100.180/#!/ 접속 후 계정 로그인
2. 데이터 브라우저 > 검색 메뉴로 이동 후 아래 조건으로 실행
  ![image](https://user-images.githubusercontent.com/13827425/58530650-711d0a80-821a-11e9-8b6d-2c75a92288a7.png)
  검색어:  * | fields LEVEL_INT, HOST  | sort +LEVEL_INT | sort -HOST

## 예상한 행동 ##
* LEVEL_INT 오름차순, HOST 내림차순이 순서대로 적용된 검색 결과

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/58530689-9ad63180-821a-11e9-89c3-a9dcd6fc9f87.png)

* 엑셀에서 동일하게 정렬을 해보면 LEVEL_INT 오름차순, HOST 내림차순이 순서대로 적용되어 정렬 됨
![image](https://user-images.githubusercontent.com/13827425/58530720-b7726980-821a-11e9-92ee-8a558980a544.png)

**Comment by pjh0347** [comment]
@tylor-kr 여러 컬럼을 정렬하는 기능은 현재 미구현 상태 입니다. 해당 기능 지원이 필요할 경우 기능 개발이 필요합니다.

**Comment by seungfwani** [comment]
이슈 내용은 `여러 컬럼을 정렬하지 못함` 입니다.

현재 sort 명령어를 수정/개발하여 해당 이슈를 해결하였습니다.

===== 해결내용 =====
-> 기존 sort 명령어 문법 : 
    - `* | sort N? [+/-]?field` 
    - 예) `* | sort +LEVEL_INT`

-> 수정된 sort 명령어 문법 :
    - `* | sort N? [+/-]?field (, [+/-]?field)*`
    - 예) `* | sort +LEVEL_INT, -HOST`

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하여 처리된 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/46172579/63912690-b692e300-ca68-11e9-9e34-bd894c60a11a.png)
