### ISSUE TITLE
Angora / hbase 결과 내보내기가 정상 수행되지 않습니다.

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1344]
## 버그 설명 ##
* 테스트 위치: 192.168.102.104
* hbase 모델을 대상으로 검색 수행 후, "결과 내보내기"를 수행시 에러 내용으로 다운로드 됩니다.

## 로그 ##
download.csv 파일 내용:
```
{
  "message": "DownloadHandler can only have PollingResultHandler as a delegate."
}
```

**Comment by namjals** [comment]
수정되었습니다.
Personal:Phone | Personal:Name | Office:Address | Office:Phone
-- | -- | -- | --
1-425-000-0001 | John Dole | 1111 San Gabriel Dr. | 1-425-000-0002
230-555-0191 | Calvin Raji | 5415 San Gabriel Dr. | 230-555-0191
