### ISSUE TITLE
Angora / geoip  오류

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#1345]
## 버그 설명 ##
geoip 검색시 오류가 발생합니다.

## 재현하는 방법 ##
* | geoip SENDER_IP

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/5077625/58844836-e2920880-86b3-11e9-8873-ae7d658193e6.png)

**Comment by tylor-kr** [comment]
* 192.168.100.180

## 원인
* 앙고라 에러
```json
{"q":"model name = 'jiranmail' start_date = 20190604105500 end_date = 20190604105629 | geoip SENDER_IP","size":200}
```

```json
{
  "message": "Can't connect to memcached", 
  "type": "<class 'angora.exceptions.AngoraException'>"
}
```

**Comment by namjals** [comment]
memcache를 특정 포트를 가리키도록(127.0.0.1:11212) 하드코딩되어 있어서 angora.conf에서 memcache의 호스트를 지정할 수 있도록 수정했고 금주 반영 예정입니다. 
(memcache가 특정 port를 사용하도록 확인 필요)

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/63915702-a6cbcc80-ca71-11e9-9f67-4723e6f70a9e.png)
