### ISSUE TITLE
Angora / model-statsdetails 명령어 에러

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1348]
## 버그 설명 ##
* 아래와 같은 방법으로 실행시 에러 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://192.168.100.180/#!/ 접속 후 계정 로그인
2. 데이터 브라우저 > 검색 메뉴로 이동 후 아래 조건으로 실행
  ![image](https://user-images.githubusercontent.com/13827425/58922699-f94d6380-8776-11e9-921d-4f100c8f81eb.png)
  검색어:  * | sql "select * from angora" | rename HOST 호스트

### http reqeust
* 아래 내용으로 sid 발급 후 실행 요청하면 에러 발생
* url: http://192.168.100.180:6036/angora/query/jobs
* reqeust body
```json
{"q":"model-statsdetails name = 'syslog' start_date = 20190605094400 end_date = 20190605094559 field = 호스트 | sql \"select * from angora\" | rename HOST 호스트"}
```

### http response
* resonse body
```json
{
  "message": "-ERR UnicodeEncodeError('ascii', u\"Illegal character '\\ud638'\", 19, 20, 'ordinal not in range(128)') [/*+ LOCATION(PARTITION = '20190605090000') */ SELECT count(DISTINCT `\ud638\uc2a4\ud2b8`) FROM EVA.SYSLOG WHERE DATETIME >= '20190605094400' AND DATETIME < '20190605094559' LIMIT 100;]\r\n", 
  "type": "<type 'exceptions.Exception'>"
}
```

## 예상한 행동 ##
* 호스트의 필드 상세 정보가 화면에 표시

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/58922718-11bd7e00-8777-11e9-9b4f-4e36945dccd6.png)

**Comment by seungfwani** [comment]
model-statsdetails 명령어의 한글문제는 현재 수정되었습니다.

**Comment by seungfwani** [comment]
model-statsdetails 명령어의 한글문제는 수정되었습니다.
하지만 Angora 에서는 주어진 쿼리를 파싱하여 동작하기 때문에
 `model-statsdetails name = 'syslog' start_date = 20190605094400 end_date = 20190605094559 field = 호스트` 와 같은 명령어는 실행이 되지 않습니다. (이유: `field = 호스트` 부분에서 원본 데이터의 컬럼명에는 '호스트' 라는 컬럼명이 존재하지 않기 때문입니다.)

`model-statsdetails name = 'syslog' start_date = 20190605094400 end_date = 20190605094559 field = HOST` 로 변경하여 전송해야 할 듯 합니다.

**Comment by tylor-kr** [comment]
@seungfwani 

위에서 예시로 말씀하신 

`model-statsdetails name = 'syslog' start_date = 20190605094400 end_date = 20190605094559 field = 호스트`

에 경우에는 `호스트` 라는 컬럼이 없기 때문에 오류가 발생하는 것이 맞지만

이번 이슈에서 발생하는 쿼리는 쿼리내에 `rename` 이라는 명령어가 같이 전달 되므로 정상 동작 되어야 합니다.

`model-statsdetails name = 'syslog' start_date = 20190605094400 end_date = 20190605094559 field = 호스트 | sql \"select * from angora\" | rename HOST 호스트`

왜냐하면 

1. `rename`으로 컬럼명을 재정의 하였는데, `호스트` 라는 컬럼이 없다 라고 하면 사용자가 `rename` 한 컬럼명을 모두 기억해서 사용해야 합니다.

2. 사용자가 원하는 동작은 `rename`으로 필드 이름을 바꾼 상태에서 `field` 명령어를 사용한 결과 이기 때문 입니다.

3. 위 이슈가 해결 불가능 하다면, 도움말에 위 내용과 관련된 내용이 반영 되어야 합니다.

**Comment by veldise** [comment]
@seungfwani 
좌측 컬럼 목록은 검색명령어 결과 정보(`fields`)에 따라 구성되는 것이고
UI쪽에서는 `rename HOST 호스트`와 같은 Angora DSL 구문을 분석할 수 없습니다. (유지보수 문제)
다른 방안을 찾아야 합니다.

**Comment by namjals** [comment]
한글 문제는 irisDB는 한글 컬럼에 대한 쿼리를 지원하지 않고
아래와 같이 HOST -> HOST2로 rename이 있는 경우, rename 구문을 확인하여 이를 다시 HOST로 원복하는 형식으로 수정하였고, 금주내에 배포 예정입니다.
```
{"q":"model-statsdetails name = 'syslog' start_date = 20190605094400 end_date = 20190605094559 field = 호스트 | sql \"select * from angora\" | rename HOST HOST2"}
```

**Comment by namjals** [comment]
아래와 같이 `호스트`를 클릭하면 `HOST`로 변환하여 결과를 출력합니다.
![image](https://user-images.githubusercontent.com/22319132/63914150-4aff4480-ca6d-11e9-877f-6a7ec8a35f03.png)
