### ISSUE TITLE
Angora / hbase 유형 모델 검색 시 timeline 결과 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1349]
## 버그 설명 ##
hbase 유형 모델 검색 시 `model-timeline` 명령어의 결과가 없습니다.
이에 따라 아래 스크린샷과 같이 타임라인 차트가 그려지지 않고 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.102.104 접속
2. `WEB hbase test 02` 모델 선택
3. 검색

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/58940270-05a3e180-87b4-11e9-9dc2-a5ef55f7474a.png)

## 로그 ##
request body:
```js
{"q":"model-timeline name = 'WEB hbase test 02'","save":false}
```
response:
```js
{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [], 
  "isEnd": true, 
  "results": []
}
```

**Comment by namjals** [comment]
수정되었습니다.
앞서 아래의 이슈에서 작은따옴표가 아닌 ` 문자로 문제의 컬럼을 감쌌습니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/1347
![image](https://user-images.githubusercontent.com/22319132/58952508-e23a6000-87ce-11e9-8755-71a783fa8113.png)
