### ISSUE TITLE
Angora / hbase 유형 모델로 피벗 수행시 에러 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1350]
## 버그 설명 ##
hbase 유형 대상으로 피벗 수행시 에러가 반환됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.102.104 접속
2. 피벗 분석 화면으로 이동
3. `WEB hbase test 02` 모델 선택
4. 필터 추가
    - `cf:LEVEL` 컬럼 선택
    - info 입력, 추가

## 로그 ##
```js
{"q":"model name = 'WEB hbase test 02' start_date = 20190607095400 end_date = 20190607095520 | pivot count(*) FILTER cf:LEVEL = 'info'","save":true,"size":500}
```
```js
{"message":"angora error: <class 'pyspark.sql.utils.ParseException'>\n\nmismatched input ':' expecting <EOF>(line 1, pos 2)\n\n== SQL ==\ncf:LEVEL = 'info'\n--^^^\n"}
```

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/59092754-44b96a80-894d-11e9-8ac9-f2adb46b2fee.png)
