### ISSUE TITLE
Angora / HDFS 유형 특정 날짜 데이터 조회 불가

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1352]
## 버그 설명 ##
- 위치: 192.168.102.104
- 현상: 특정 날짜의 데이터가 조회되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.102.104 접속
2. 피벗 분석 화면으로 이동
3. `WEATHER (101.51 HDFS)` 모델 선택
4. 3가지 종류로 시간 설정
    - `2008/05/13 00:00:00 ~ 2008/05/14 00:00:00`
    - `2008/05/13 00:00:00 ~ 2008/05/13 00:00:00`
    - `2008/05/13 00:00:00 ~ 2008/05/13 00:00:05`
5. 검색

## 예상한 행동 ##
- 만약 현재 시간 범위가 적용되는 것이 `start_date` <= time < `end_date` 와 같은 조건이라면, 
`start_date = 20080513000000 end_date = 20080513000000` 조건에는 검색 결과가 없는 것이 맞지만
`start_date = 20080513000000 end_date = 20080513000005` 조건에는 검색 결과가 있어야 합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/59083669-35c5be80-8933-11e9-84dc-d7dd1da13150.png)

### request body case 1
```js
{"q":"model name = 'WEATHER (101.51 HDFS)' start_date = 20080513000000 end_date = 20080514000000  | count","save":false}
```

### request body case 2, 3
```js
{"q":"model name = 'WEATHER (101.51 HDFS)' start_date = 20080513000000 end_date = 20080513000000  | count","save":false}
```
```js
{"q":"model name = 'WEATHER (101.51 HDFS)' start_date = 20080513000000 end_date = 20080513000005  | count","save":false}
```

### response case 1
```
{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [
    {
      "grouped": false, 
      "type": "LONG", 
      "name": "count"
    }
  ], 
  "isEnd": true, 
  "results": [
    [
      80
    ]
  ]
}
```

### response case 2, 3
```js
{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [
    {
      "grouped": false, 
      "type": "LONG", 
      "name": "count"
    }
  ], 
  "isEnd": true, 
  "results": [
    [
      0
    ]
  ], 
  "ui": null, 
  "save": false
}
```

**Comment by namjals** [comment]
model 명령은 고쳤는데, model-timeline이 나오지 않네요, 좀더 확인해보겠습니다.
![image](https://user-images.githubusercontent.com/22319132/60422198-73fa8900-9c26-11e9-889d-cc39c8bf6088.png)

**Comment by namjals** [comment]
현재 모델(`WEATHER (101.51 HDFS)`)의 원본 데이터의 DATE 컬럼 포맷이 YYYY/MM/DD 입니다. 
이를 20080513000000 ~ 20080513000005 사이를 검색하게 되면 20080513 ~ 20080513을 검색하는 것처럼 일단위 이하는 삭제 됩니다.
앙고라 내부에서 일단위 이하를 삭제 않도록 처리하는 것은 date 처리 복잡도가 높아, 모든 경우를 만족하는 답을 찾기가 어렵습니다.

@veldise
차라리 UI에서 DATE 컬럼의 포맷을 확인하고, 위와 같이 시분초가 없는 경우, 시, 분, 초는 범위지정을 못하도록  막는게 가능한지 문의드립니다.

**Comment by veldise** [comment]
@namjals 
시간 범위 설정 기능은 전체 코드에 영향을 주기 때문에 기간 내에는 불가능합니다.

**Comment by veldise** [comment]
@namjals 
해결되어서 닫으신 건가요?

**Comment by veldise** [comment]
@namjals 
192.168.102.129 기준 재현됩니다. 해결되면 배포하고 닫아주세요.

![image](https://user-images.githubusercontent.com/3411842/60485664-ad8bcc80-9cd8-11e9-9a88-c23505d26f68.png)

**Comment by pjh0347** [comment]
@veldise 본 내용은 결함이 아니라 사용법 관련하여 오해가 있어 등록된 것으로 파악됩니다.

Angora 가 시간 조건을 처리하는 규칙에 대해 정리하면 아래와 같습니다.
- start_date 는 `이상` 으로 처리하고, end_date 는 `미만` 으로 처리합니다.
- 모델 생성 시 입력한 시간 포멧 기준으로 하위 레벨의 시간은 `버림` 으로 처리합니다.

그래서 위 3가지 종류 시간 설정에 대한 예상 동작 결과는 아래와 같습니다.
2008/05/13 00:00:00 ~ 2008/05/14 00:00:00 : 13일 이상 14일 미만 이니까 13일 데이터가 출력.
2008/05/13 00:00:00 ~ 2008/05/13 00:00:00 : 13일 이상 13일 미만 이니까 출력 x.
2008/05/13 00:00:00 ~ 2008/05/13 00:00:05 : 13일 이상 13일 미만(시간 단위 이하 버림) 이니까 출력 x.

위와 같은 이유로 본 이슈를 닫습니다. 혹시 기타 사유로 인해 angora 기능 동작 변경이 필요하다면 알려주세요. 감사합니다.

**Comment by veldise** [comment]
@sunghoon 
사용자 입장에서는 박진호 선임 답변이 잘 이해가 가지 않는데 한 번 보시면 좋을 것 같습니다.

**Comment by veldise** [comment]
채병석 선임 의견으로는 특정 1일 혹은 특정 시간의 데이터를 조회하는데
시작/끝 시간 범위를 다르게 지정하는 것은 납득하기 어렵지만,
일정상 **관련된 모든 기능에 대하여 사용자 메뉴얼 및 운용 메뉴얼에 상세하게 기술하는 것**으로 결정했습니다.
