### ISSUE TITLE
Angora / HDFS 유형 model-statsdetails 명령어 결과 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1353]
## 버그 설명 ##
- 위치: 192.168.102.104
- 현상: 시간 범위를 설정하면 `model-statsdetails` 명령어 결과가 없습니다. 
  - `전체시간`으로 설정하면 결과가 있습니다.

## 재현하는 방법 ##
1. 192.168.102.104 접속
3. `WEATHER (101.51 HDFS)` 모델 선택
4. `2008/05/13 00:00:00 ~ 2008/05/14 00:00:00` 시간 설정
5. 실행
6. 좌측 하단 컬럼 목록에서 `LOCATION` 클릭
8. 팝업 레이어 안에 통계 결과 없음

## 스크린샷 ##
검색 결과에는 LOCATION 값 존재:
![image](https://user-images.githubusercontent.com/3411842/59083669-35c5be80-8933-11e9-84dc-d7dd1da13150.png)

## 로그 ##
request body:
```js
{"q":"model-statsdetails name = 'WEATHER (101.51 HDFS)' start_date = 20080513000000 end_date = 20080514000000 field = LOCATION","save":false}
```
response:
```js
{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [], 
  "isEnd": true, 
  "results": []
}
```

**Comment by namjals** [comment]
현재 재현되지 않습니다, model-stats.py 관련 자체 검증 과정에 수정이 된것으로 보입니다.
![image](https://user-images.githubusercontent.com/22319132/60243181-97ee5f80-98f2-11e9-9ba8-7fceb98141ad.png)
