### ISSUE TITLE
검색 / 검색 결과가 없습니다

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#1354]
## 버그 설명 ##
검색 실행시 '검색 결과가 없습니다' 라고 나옵니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/5077625/59253549-73935180-8c69-11e9-8a90-075e36ed6f87.png)

![image](https://user-images.githubusercontent.com/5077625/59253495-52cafc00-8c69-11e9-9ac6-41c2dc89f5fb.png)

**Comment by tylor-kr** [comment]
/angora/query/jobs

```json
{"q":"model-timeline name = 'jiranmail' SENDER_IP='103.225.145.14'"}

{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [], 
  "isEnd": true, 
  "results": []
}
```

**Comment by namjals** [comment]
현재 재현되지 않습니다.
![image](https://user-images.githubusercontent.com/22319132/61342819-8ad7e700-a886-11e9-8172-bf240e6579ad.png)
