### ISSUE TITLE
[전력연구원] 검색필터링 조회 결과 내보기기 오류

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1356]
## 버그 설명 ##
fileds 키워드 검색 데이터 조회된것을 내보기기 버튼 클릭 시 `"message":   "DownloadHandler can only have PollingResultHandler as a delegate."` 오류가 엑셀파일에 export됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 검색 조건 : * | fields METER_NO, MR_YMD
2. 내보내기 버튼 클릭 -> 로컬,  csv, 무제한  -> 내보내기

![image](https://user-images.githubusercontent.com/29471177/59326898-f0cecd00-8d22-11e9-824e-9cfa66150fcf.png)

![image](https://user-images.githubusercontent.com/29471177/59326908-fc21f880-8d22-11e9-9261-c876b61f286e.png)

**Comment by veldise** [comment]
@namjals 
`/angora/query/jobs/.../download` 요청의 결과가 에러인 경우 에러를 파일 내용으로 기록하도록 되어있습니다.
본문 에러 확인 바랍니다.

**Comment by namjals** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/1344 와 같은 이슈로 mda에 아직 배포가 되지 않아 발생한 문제 입니다.

**Comment by chohi22** [comment]
전력연 배포된것 확인후  close하겠습니다.

**Comment by chohi22** [comment]
![image](https://user-images.githubusercontent.com/29471177/60644741-f88d1780-9e71-11e9-9ebf-87637f27d194.png)

07.04 패치 후 확인 했습니다.
