### ISSUE TITLE
table에 delete 쿼리 실행 후 select 쿼리 실행시 조회 data가 있는 것으로 나오는 현상

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1359]
## 버그 설명 ##
table에 delete 쿼리 실행 후 select 쿼리 실행시 조회 data가 있는 것으로 나오는 현상

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. delete from CCFI_DATA; 쿼리 실행
2. SELECT  SDATE, STYPE, CCFI_VALUE FROM VALUELINKU.CCFI_DATA;  쿼리 실행

## 예상한 행동 ##
조회 결과 없음

## 스크린샷 ##
[쿼리 실행 이력]
![image](https://user-images.githubusercontent.com/4444717/59405739-7bc4cb80-8de6-11e9-810a-4634b55987f3.png)

[조회 결과]
![image](https://user-images.githubusercontent.com/4444717/59405708-63ed4780-8de6-11e9-9cf5-a212c54ddcb7.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by anhm** [comment]
해당 이슈는 사이트 환경에서 확인을 해야 하는 이슈입니다.
혹시라도 같은 현상이 확인되면 다시한번 연락을 부탁 드리겠습니다.

해당 이슈는 일단 닫도록 하겠습니다.
