### ISSUE TITLE
쿼리 브라우져에서 조회 되는 data가 검색에서 조회 안됨(날짜조건)

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1360]
## 버그 설명 ##
쿼리 브라우져에서 조회 되는 data가 검색에서 조회 안됨(날짜조건)

## 재현하는 방법 ##
동작을 재현하는 방법 :
0. valuelinku로 로그인(비번 ID와 동일)
1. sql 브라우저에서 아래 쿼리 실행
/*+ LOCATION ( PARTITION >= '20190401000000' AND PARTITION <= '20190613180000' ) */ 
SELECT 
	SDATE, STYPE, SCFI_VALUE 
FROM 
	VALUELINKU.SCFI_DATA
order by SDATE      
; 

2. 검색에서 아래 조건으로 실행
모델 : SCFI_DATA
날짜 : 2019/04/01 00:00:00 ~ 2019/06/13 18:23:40

## 예상한 행동 ##
검색에서도 동일하게 조회 결과가 나옴

## 스크린샷 ##
[sql 조회 결과]
![image](https://user-images.githubusercontent.com/4444717/59421131-10402580-8e09-11e9-85c7-2340cfb34b1b.png)

[검색 조회 결과]
![image](https://user-images.githubusercontent.com/4444717/59421174-251cb900-8e09-11e9-8a8b-292e452932f8.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
앙고라의 iris 데이터 조회시 파티션 범위 지정을 수정하여 해결완료 하였습니다.

해당 내용은 운영서버에 배포 예정입니다.

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하여 처리된 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/46172579/63912815-0f627b80-ca69-11e9-8d26-e01fd29e0bd1.png)
