### ISSUE TITLE
[보고서] studio 직접 접근시 리포트 미리보기, 작성시 보기 기능 동작하지 않음

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#1361]
## 버그 설명 ##
* report 목록 화면에서 보고서 이름을 클릭시 미리보기가 동작하지 않음
* 보고서 작성 화면에서 보기 기능이 동작하지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 목록에서 이름 클릭시 아무 동작이 없음
2. 보고서 작성 화면에서 보기 클릭시 아무 반응이 없음

## 예상한 행동 ##
보고서 미리보기 

## 기타 ##
* 소스 확인내용
    ```
    services
        └── brick.js : 82
    ```
    * iframe 내부인지 확인하는 부분에서 동작하지 않음
        * iframe 내부가 아니어도 $window.parent 가 존재
        * 아래의 방식이 아닌 다름 방식으로 iframe 내부인지 아닌지 획인하는 소스가 필요함
        ```
            if ($window.parent) {
        ```
        * studio 직접 접근시 iframe 내부가 아님에도 내부로 판단하여 다음의 코드가 실행됨
        ```
            $window.parent.postMessage({
        ```
       * 받아줄 상위 객체가 없어서 동작하지 않음

**Comment by veldise** [comment]
기존에는 iframe 기준으로 동작하여 상위 객체가 반드시 존재하는 것이 기본이었기 때문에 버그는 아닙니다.

**Comment by veldise** [comment]
코드 병합 완료, 테스트 대기중

**Comment by veldise** [comment]
테스트 및 처리 완료되어 닫습니다.
