### ISSUE TITLE
[전력연구원] 시각화 지역맵형 삭제 요청

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1365]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
분석및 시각화 > 검색 > 시각화탭
클러스터맵형, 지역맵형 삭제요청 드립니다.

![image](https://user-images.githubusercontent.com/29471177/59572134-04dd4a80-90e6-11e9-9768-9a892bb9a707.png)

**Comment by veldise** [comment]
@chohi22 
내일(6/18) 운용기술연구팀과 배포 일정을 협의하겠습니다.

**Comment by chohi22** [comment]
07.04 전력연구원 패치 이후 수정이 안되어 있습니다.
![image](https://user-images.githubusercontent.com/29471177/60644878-443fc100-9e72-11e9-8e1b-d087bbd885cc.png)

**Comment by veldise** [comment]
@choihi
확인 후 바로 조치하겠습니다.

**Comment by chohi22** [comment]
07.08 전력연 배포후 확인 했습니다.
![image](https://user-images.githubusercontent.com/29471177/60788566-fbe91180-a197-11e9-9ee3-4bdf0941a072.png)
