### ISSUE TITLE
[전력연구원] 오라클 Date컬럼 시간유형(TIMESTAME)컬럼 지정안됨

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1366]
## 버그 설명 ##
오라클DB 테이블 DATE컬럼을 시간유형(TIMESTAMP)컬럼으로 지정하려고 하는데, 컬럼을 선택할 수 없습니다.

CREATE TABLE KMDMS.BCT1430 
(
	REGION_CD     VARCHAR2 (4) NOT NULL,
	DCU_ID        VARCHAR2 (10) NOT NULL,
	MR_YMD        VARCHAR2 (8) NOT NULL,
	MESH_NO       VARCHAR2 (8),
	DCU_STAT_CD   VARCHAR2 (1),
	INST_DT       VARCHAR2 (30),
	LAST_GET_DT   VARCHAR2 (30),
	AGG_DATE      DATE,
	AREA_CD       VARCHAR2 (4),
	BLOCK_CD      VARCHAR2 (4)
)

## 재현하는 방법 ##
동작을 재현하는 방법 :
관리 > 데이터 모델 > 새모델 (Oracle)

AGG_DATE 컬럼을 시간유형으로 지정하려고 하는데, 지정할 수 없습니다.

![image](https://user-images.githubusercontent.com/29471177/59572229-b0869a80-90e6-11e9-87ca-7e2de784e631.png)

**Comment by veldise** [comment]
@pjh0347 @namjals 
oracle 의 `DATE` 타입의 컬럼을 시간 컬럼으로 지정하면 `model`, `model-timeline` 등의 명령어가 정상 수행되나요?

**Comment by veldise** [comment]
현재 UI에서 `TEXT`, `NUMBER` 유형 외에는 선택이 불가능 하도록 막아놓은 상태입니다.
이유는 기존에는 IRIS-DB / HDFS 에서 시간 컬럼을 `TEXT` 타입으로 지정하였기 때문입니다.

**Comment by chohi22** [comment]
07.04 전력연구원 패키 이후 확인 완료했습니다.

![image](https://user-images.githubusercontent.com/29471177/60644966-718c6f00-9e72-11e9-92f1-7a0a6a955fe3.png)

**Comment by veldise** [comment]
@chohi22
Oracle 한정으로 시간 컬럼 선택 가능하도록 수정하였습니다. 확인 부탁드립니다.

**Comment by seungfwani** [comment]
앙고라 서비스
  - DATE, TIMESTAMP 타입에 대해 명령어가 정상 수행되도록 기능개발 완료하였습니다.

**Comment by chohi22** [comment]
ㅁ date컬럼 TIMESTAMP로 지정해서 모델을 만드는것은 확인 되었습니다.
![image](https://user-images.githubusercontent.com/29471177/62507051-ec63f380-b83d-11e9-9679-d1bd8961baa7.png)

ㅁ 위에서 생성한 모델로 데이터 조회시 "Invalid Date" 라고 잘못 나오는 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/29471177/62507088-0dc4df80-b83e-11e9-8b11-16db3f4c3bc6.png)

**Comment by veldise** [comment]
@chohi22 
현재 동일한 내용이 패치된 본사 개발 서버(KDN기준)에서는 재현되지 않는 것으로 볼 때,
원본 데이터, Oracle 테이블 설정, 주고받은 네트워크상 데이터 등 확인이 필요합니다.

구글 크롬 기준으로 아래와 같이 수행하신 후 캡처 화면을 보내주시면 감사하겠습니다.
1. 검색 페이지로 이동
2. 설정 > "도구 더 보기" > "개발자도구" 메뉴로 개발자 메뉴를 활성화
3. 개발자도구에서 Network 탭 선택, Clear 버튼으로 현재 목록 초기화
4. 현상이 재현되도록 검색 수행
5. 검색 결과에 해당하는 http 호출 내용을 찾아서, Response 확인
    - Response 에 `UPDT_DT`가 포함된 것을 찾으시면 됩니다.
6. 캡처 or Response 텍스트 복사

ex) 
![image](https://user-images.githubusercontent.com/3411842/62510977-5d120c80-b84c-11e9-9259-05254cdccced.png)

**Comment by veldise** [comment]
@pjh0347 @namjals 
129번에서 재현되지 않는 것으로 볼 때, Oracle DB 혹은 테이블 설정에 따라
시간 컬럼 결과가 API와는 다르게 반환되는게 아닌가 합니다.
관련하여 내용을 확인하는 방법을 정현일 선임님께 전달 바랍니다.

**Comment by chohi22** [comment]
ㅁ Response부분이 2개로 캡처해서 첨부합니다.
![image](https://user-images.githubusercontent.com/29471177/62517242-eed84480-b861-11e9-9e85-7f235069d476.png)
![image](https://user-images.githubusercontent.com/29471177/62517248-f4ce2580-b861-11e9-8bfd-67d8fff67978.png)

**Comment by veldise** [comment]
영문버전에서 발생하는 문제로 확인되었습니다.

**Comment by veldise** [comment]
@chohi22 
이슈를 해결한 수정 버전을 운영팀에 전달하였으니, 시간 여유가 되시면 문제가 해결되었는지 확인 부탁드립니다.

**Comment by chohi22** [comment]
오라클 date컬럼 시간 문자열로 정상적으로 출력되는것 확인했습니다.
![image](https://user-images.githubusercontent.com/29471177/63487219-5a1e4980-c4e5-11e9-859f-8a1a9ff95422.png)
