### ISSUE TITLE
검색 / 조건 검색시 에러 반환

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1368]
## 버그 설명 ##
- 제보: 한전KDN
- 대상: 192.168.102.104

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.102.104 접속
2. `WEATHER (101.51 HDFS)` 모델 선택
3. 시간 범위: `2007/08/18 00:00:00 ~ 2007/10/06 00:00:00` 설정
4. 검색어: `* LOCATION='90'` 입력
5. 에러

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/59754825-d87e2580-92c1-11e9-96f9-8d5862ed3058.png)

## 로그 ##
```js
{"q":"model name = 'WEATHER (101.51 HDFS)' model_owner = root start_date = 20070818000000 end_date = 20071006000000 LOCATION='90'","save":true,"size":200,"ui":"{\"q\":\"* LOCATION='90'\",\"datamodel_id\":\"996742b4-1af3-4a0f-8ce9-e0f017eaef51\",\"datamodel_name\":\"WEATHER (101.51 HDFS)\",\"datamodel_owner\":\"root\",\"isStatsQuery\":false,\"start_date\":\"20070818000000\",\"end_date\":\"20071006000000\",\"job_time\":\"1560937278555\",\"type\":\"grid\",\"route\":\"search\",\"modelId\":\"996742b4-1af3-4a0f-8ce9-e0f017eaef51\"}"}
```

```js
{"message":"angora error: <type 'exceptions.SyntaxError'>\nYACC Syntax error near ''90'' [model name = 'WEATHER (101.51 HDFS)' model_owner = root start_date = 20070818000000 end_date = 20071006000000 LOCATION= '90']"}
```

## 기타
다른 데이터 모델은 유사한 검색으로 결과가 정상적으로 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/59755128-5c381200-92c2-11e9-9d5d-cc2c71076ed8.png)

**Comment by namjals** [comment]
로컬에서 확인 되었고 배포, 테스트 후 닫을 예정입니다.

**Comment by namjals** [comment]
개선되었습니다.
![image](https://user-images.githubusercontent.com/22319132/60483573-f770b480-9cd0-11e9-9b57-2dafdae5500c.png)
