### ISSUE TITLE
데이터 모델 / Comment 명이 별칭으로 자동 입력되게 보완 요청

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1369]
## 기능 요청 ##
- 요청자: 정현일S
- 오라클 서버의 Comment 명이 별칭으로 자동 입력되게 보완 요청

## 원하는 솔루션 설명 ##
![image](https://user-images.githubusercontent.com/3411842/60155917-41b3ea80-9826-11e9-8631-960d0462c337.png)

## 방안
1. Angora 에서 특정 테이블의 `fields` 정보(실제로는 `sample`)를 UI쪽에 반환할때 컬럼별 comment 정보도 반환
2. UI는 받은 컬럼별 comment 정보를 별칭(alias) 입력란에 자동 입력

**Comment by seungfwani** [comment]
1. Angora 에서 특정 테이블의 fields 정보(실제로는 sample)를 UI쪽에 반환할때 컬럼별 comment 정보도 반환
  -> oracle 명령어로 데이터를 조회시 컬럼별 comment 정보를 반환하도록 수정하였습니다.

**Comment by chohi22** [comment]
전력연 패치이후 테스트 완료

![image](https://user-images.githubusercontent.com/29471177/60645515-d399a400-9e73-11e9-8708-ac910c43878e.png)
