### ISSUE TITLE
작업 조회 / 쿼리에서 iris 문구 제거

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1372]
## 버그 설명 ##
출처: 6/29 KDN 설치 및 테스트 결과

작업 조회 - 상세정보에서 쿼리에 `iris_date_group`이 있습니다. `iris_`를 제거해야 합니다.

## 상세 내용 ##
피벗 분석, (고급)시각화 화면에서 수행하는 쿼리는 
Angora의 `/query-analysis` API를 사용하여 각 분석 조건 json를 문자열로 변환한 것입니다.
모든 `/query-analysis` API 결과에서 `iris` 문구를 제거해야 합니다.

## 스크린샷 ##
![분석시각화-작업상세_iris문구제거](https://user-images.githubusercontent.com/3411842/60393559-4cd28780-9b52-11e9-9c1f-87882ff015d7.png)

**Comment by namjals** [comment]
adv에 대한 쿼리 명령어에 iris_date_group -> date_group로 동작하게끔 수정하여 적용했습니다.
# 배포 전
q = "model name = 'angora hbase 1 man' model_owner = root | adv line avg(cf:base_point) SPLITROW 'iris_date_group(\"cf:event_time\", \"10M\")' SPLITCOL cf:eg_name COLSIZE 500"
# 배포 후
q = "model name = 'angora hbase 1 man' model_owner = root | adv line avg(cf:base_point) SPLITROW 'date_group(\"cf:event_time\", \"10M\")' SPLITCOL cf:eg_name COLSIZE 500"

ui에서 아마 `iris_`를 제거해서 쿼리해야할 것으로 보입니다.

**Comment by veldise** [comment]
@namjals 
오해하고 계신거 같은데 UI에서는 `iris_`를 추가하는 부분이 없습니다.

**Comment by veldise** [comment]
7/3 09:04 기준 192.168.102.129 에서 재현됩니다.

**Comment by namjals** [comment]
아래와 같이 쿼리를 날렸을때, 
![image](https://user-images.githubusercontent.com/22319132/60554793-0f4d4480-9d74-11e9-9347-df20cb97ce1b.png)
쿼리 내역이 다음과 같이 iris_date_group으로 쿼리를 합니다. 이 쿼리문은 ui에서 만드는거 아닌지 문의드립니다.
"q":"model name = 'angora hbase 1 man' model_owner = root | adv line avg(cf:base_point) SPLITROW 'iris_date_group(\"cf:event_time\", \"10M\")' SPLITCOL cf:eg_name COLSIZE 500"

**Comment by veldise** [comment]
@namjals
본문 내용을 다시 읽어보시기 바랍니다. `iris_`가 들어가는 쿼리는 Angora의 `/query-analysis` API의 결과입니다.

**Comment by namjals** [comment]
네 query-analysis API로 확인을 해보겠습니다, 그럼 제가 수정한 내역은 원복을 하면 될까요?

**Comment by veldise** [comment]
@namjals 
UI이슈가 아닌데 webUI 라벨 달지 말기 바랍니다.

**Comment by veldise** [comment]
@namjals 
어떤 모델이든지 다음과 같이 수행하면 재현됩니다.
- 피벗: 행 선택에 시간 컬럼 설정
- 고급시각화: 꺾은선형 or 막대형 차트에서 x축에 시간 컬럼 지정

**Comment by namjals** [comment]
처리 되었습니다.
![image](https://user-images.githubusercontent.com/22319132/60560908-aaeaaf00-9d8c-11e9-996e-b903e2fdb40d.png)
