### ISSUE TITLE
[전력연구원] 영문버전 한글 나오는 문제

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1373]
## 버그 설명 ##
MDA > Administrator > Connection Infos 화면에 2가지 문제가 있습니다.

1. Delete 글씨가 짤립니다.
2. New Conn Info 선택 시 한글이 나옵니다.

전력연구원 패치 버전에 함께 배포해주세요.

![image](https://user-images.githubusercontent.com/29471177/60405519-b0f55a00-9beb-11e9-8f1c-e3ad65dff5ba.png)

**Comment by veldise** [comment]
@chohi22 
2번 한글 이슈는 KDN 단위테스트를 거치면서 해결되었습니다.
1번은 조치하여 가능하면 금주 배포에 포함시키겠습니다.

**Comment by chohi22** [comment]
07.04 전력연 패치 이후 확인함

![image](https://user-images.githubusercontent.com/29471177/60645717-6f2b1480-9e74-11e9-81de-e00e17394edc.png)
