### ISSUE TITLE
[전력연구원] 데이터 모델의 컬럼 선택후 검색시 일부 모델 검색결과에 반영이 안됩니다.

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1374]
## 버그 설명 ##
아래의 그림처럼 일부모델은 기본으로 uncheck되어 있고, "Select All" 버튼 체크한뒤 검색을하면 결색결과에 uncheck되어 보입니다.
전력연 패치 버전에 포함시켜 주시고요.
급하게 조치를 하려면 어떻게 처리할 수 있는지 방법을 가르쳐 주세요.

![image](https://user-images.githubusercontent.com/29471177/60475166-ef088180-9cb0-11e9-9cd2-ffe7372c4a6a.png)

**Comment by veldise** [comment]
KDN 일정으로 인해 차주 월요일(7/8) 처리하기로 협의되었습니다.

**Comment by veldise** [comment]
@chohi22 
현재 본사 개발 서버에서 재현이 되지 않아, 다음과 같은 작업 후 재시도를 부탁드립니다.
- 브라우저 쿠키 삭제

현상이 다시 재현된다면, 현상이 나타나는 동작을 수행하신 후, 구글 크롬 브라우저의 개발자 도구 콘솔 내용 캡처를 부탁드립니다.
구글 크롬 브라우저의 개발자 도구는 아래와 같이 설정 창에서 띄울 수 있으며,

![image](https://user-images.githubusercontent.com/3411842/60702690-93e9bf80-9f3a-11e9-851d-2d8a69e0185f.png)

아래와 같이 Console 탭의 내용을 캡쳐해서 보내주시면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/60702744-b8459c00-9f3a-11e9-98e5-6dafae17536f.png)

**Comment by chohi22** [comment]
쿠키 제거후에 처음에는 정상적으로 작동을 하는데요..
여러번 다른 모델을 검색하다보면 동일한 증상이 보입니다.

http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/

**Comment by veldise** [comment]
@chohi22 
검색 작업이 완료되기 전에 데이터 모델을 변경할 수 있어서 발생하는 문제로 확인되었습니다.

**Comment by veldise** [comment]
@chohi22
검색 작업 중에는 모델을 변경할 수 없게 처리하였습니다. 확인 부탁드립니다.

**Comment by chohi22** [comment]
컬럼없어지는 문제 확인후 close합니다.
