### ISSUE TITLE
[전력연구원] 작업이력 조회 No Data로 나옵니다.

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1375]
## 버그 설명 ##
07.04 전력연구원 패치 이후 이부 작업이력 데이터에 No Data라고 나옵니다.
좀더 테스트를 해봐야 어떤 조건인지 나올것 같은데요. 
우선 스샷부터 올립니다.

![image](https://user-images.githubusercontent.com/29471177/60647167-09d92280-9e78-11e9-816f-3f9a09897679.png)

**Comment by veldise** [comment]
UI 버그로 파악되었습니다. 1374 이슈와 함께 배포하겠습니다.

**Comment by chohi22** [comment]
07.08 전력연 배포 후 확인했습니다.
![image](https://user-images.githubusercontent.com/29471177/60788774-6e59f180-a198-11e9-9fbf-d81fa8730754.png)
