### ISSUE TITLE
[사내데모서버] status 메뉴 클릭시 잘못된 페이지 접속

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1376]
## 버그 설명 ##
192.168.100.180 사내데모서버에서 상단에 status 메뉴를 클릭하면 
테이블 스페이스(사용률 현황)페이지로 이동됩니다. 
두번클릭하면 status화면으로 이동됩니다. 

## 재현하는 방법 ##
![image](https://user-images.githubusercontent.com/25650544/60875877-c1ee3d00-a275-11e9-82ba-5523b56b5fc6.png)

![image](https://user-images.githubusercontent.com/25650544/60875888-c9154b00-a275-11e9-882a-5256e905ef94.png)

배포후 발생하는 문제로 확인 부탁드립니다.

**Comment by veldise** [comment]
사내 데모서버(운영서버) 기준 해결 완료되어 닫습니다.
