### ISSUE TITLE
SMS / API 호출시 'NoneType' object has no attribute 'empty' 에러 반환

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1377]
## 버그 설명 ##
아래 API 호출시 'NoneType' object has no attribute 'empty' 에러를 반환합니다.

## 내용
`http://192.168.100.180:5555/sms/v1/root/alarm/method`

```json
{
    "message": "'NoneType' object has no attribute 'empty'",
    "code": 99999
}
```

**Comment by anhm** [comment]
해당 원인 해결해 두었습니다.
