### ISSUE TITLE
데이터모델 생성 시 에러

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#1378]
## 버그 설명 ##
IRIS DB table로부터 데이터모델 생성을 시도할 때 에러 발생

## 재현하는 방법 ##
1. 192.168.100.180 B-IRIS web에서 '데이터모델' - '새 모델' 클릭
2. 연결정보 - 'IRIS' - '180 iris connector'
3. 대상데이터 - INLEE.JENKINS_BUILD_RESULT

## 예상한 행동 ##
대상 데이터가 화면에 출력되고 데이터모델이 생성되어야 함 

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/60929047-ad985780-a2ea-11e9-9ef9-38c9cee3e881.png)

**Comment by namjals** [comment]
설정 문제입니다. 수정되었습니다.
