### ISSUE TITLE
[데이터추가] CSV 로 데이터 로딩 하는데 에러 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1379]
## 버그 설명 ##
1. 데이터추가 메뉴에서 csv 로 데이터 파일 선택 / 열이름 분할 및 이름 변경 / 제출  하는데
   테이블은 create  되었는데,
   로딩 시 에러 발생한 것 같습니다.
2. 기존 테이블로 선택 후 다시 로딩해도 로더에서 에러 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to '데이터추가'

## 예상한 행동 ##
데이터 로딩

## 스크린샷 ##

create 된 테이블과 조건    : MYIRIS.TEST_SUM_10_HOST
<img width="1430" alt="스크린샷 2019-07-10 오전 10 50 28" src="https://user-images.githubusercontent.com/5126497/60934922-fb20be80-a302-11e9-8615-ff758c2a80dd.png">

데이터 형태
<img width="401" alt="스크린샷 2019-07-10 오전 11 01 44" src="https://user-images.githubusercontent.com/5126497/60934934-05db5380-a303-11e9-8186-c4ee15f1892e.png">

데이터 가공 결과
<img width="1414" alt="스크린샷 2019-07-10 오전 11 04 16" src="https://user-images.githubusercontent.com/5126497/60934901-ed6b3900-a302-11e9-92f7-1956fe4211a5.png">

제출 단계에서 발생한 에러
<img width="499" alt="스크린샷 2019-07-10 오전 10 49 00" src="https://user-images.githubusercontent.com/5126497/60935045-7aae8d80-a303-11e9-8417-b430a290f999.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
문제가 발생한 원본 데이터를 링크나 메일로 받아볼 수 있을까요?
메일은 namjals@mobigen.com 입니다.

**Comment by sunghoon** [comment]
비슷한 상황이 발생하면 새 이슈로 처리하겠습니다.
