### ISSUE TITLE
[보고서] 보고서를 가져오는데 실패하였습니다 오류 발생

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1382]
## 버그 설명 ##
보고서를 생성하던 중에 갑자기 영역 컴포넌트 하나가 실행 결과가 안되길래, '저장' 버튼을 누르고 새로고침으로 다시 [보고서] 페이지에 들어와서 해당 보고서를 클릭했더니 스크린샷과 같은 오류가 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. '영역' 에 아래 작업을 하고 '실행' 버튼을 눌렀는데 '실행중' 표시만 뜨고 결과가 안보이길래 '중지' 누르고 여러차례 시도했음. 그럼에도 제대로 결과가 안뜨길래 '저장' 누르고 새로고침함

계정: ssm0219
데이터모델: 사내웹메일_자체
기간: 2019-05-02 ~ 2019-05-04 ('기간' 컴포넌트로 연결되어 설정됨)
실행 명령어:  * | sql "select count(*) from angora where S_R_TYPE = 'S'"

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/35832986/61259041-60692980-a7b3-11e9-85cd-b0eb742d9ec1.png)

## 기타 ##
보고서 수정, 복제도 다 안됨

**Comment by swish1995** [comment]
*180 db 기준으로 ETC 가 다음과 같이 ETC 가 base64 encoding 되지않고 정상적으로 저장되지 않은 상태를 확인하였습니다.

    {"size":{"key":"1980X1080","width":1980,"height":1080},"color":"#ffffff","visual":...

* 특히 문의된 Webmail 보고서의 경우 아래와 같이 입력되어 있습니다.
    241.44 kB (204.8 kB loaded) {"size":{"key":"1980X1080","width":1980,...

* 어떤 경로로 위와 같이 입력되었는 확인중이며 금일 10시 이후에 작업된 5건에 대해서 비정상적인 ETC 내용을 확인하였습니다.

**Comment by swish1995** [comment]
* 해당하는 보고서가 정상적으로 저장되지 않은 부분은 확인하였습니다.
   * 저장될때 정상적이지 않은 형태로 저장이 되어 데이터를 복구 할수도 없는 상태입니다. - 데이터 잘림
   * 비슷한 시간대에 작업된 다른 보고서에도 비슷한 현상이 발견된것으로 보이나 재현이 불가능한 상태입니다.
   * 서버쪽 오류로 인해 그 시간대에 다른 보고서에도 같은 문제가 발견되었으나 정확한 원인은 확인이 안되고 있습니다. 
   * 다른 보고서는 복구 하였으며 이후에는 증상이 발견되고 있지 않습니다. 
* 현재 재현 방법으로 했을때 똑같은 현상이 발견되지 않고 있어서 원인 파악을 할수 없는 상태입니다.
* 추후 발생시 보고서 전체 작업 내용과 보다 자세한 내용을 알려주시면 원인 파악에 도움이 될것으로 판단됩니다.

**Comment by ssm0219** [comment]
@swish1995 말씀하신 바와 같이 제가 작업한 내용으로 문제가 생긴 게 아니라 저장 기능 자체의 문제였던 것으로 여겨집니다.

위 이슈를 올리고서도 몇 차례나 저장할 때 '이름이 중복된다' 며 저장이 되지 않아 [새로 저장] 하는 방식으로 저장하면서 진행했었습니다.

저장 이슈 외에도 다르게 재현되는 방법이 있다면 말씀드리겠습니다.

**Comment by tylor-kr** [comment]
처리 후 배포 되어 닫습니다.
