### ISSUE TITLE
[RStudio] 특정 계정 RStudio 화면 접속 불가

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1383]
## 버그 설명 ##
![image](https://user-images.githubusercontent.com/35832986/61339297-29108080-a878-11e9-8216-590c75759099.png)

어제까지 잘 되던 RStudio가 다시 접속했더니 위와 같은 오류 창과 함께 나타나지 않고 있습니다.

그래서 제 PC에서 다른 계정 (yubin90) 으로 켜보니 정상 접속되었습니다.

확인 부탁 드립니다.

**Comment by anhm** [comment]
어재 6시 이후부터 rstudio 패치 작업이 있었습니다.
확인 결과 해당 시점에 r이 실행되어 발생한 문제였습니다.

지금 다시 접속하시면 정상적으로 사용이 가능 하십니다.


패치 내용은
r의 버전이 3.5.8에서 3.6.0 으로 변경 되었으며...
추가적인 라이브러리를 설치해 둔 상태입니다.

Rstudio와 관련하여 추가적인 요구사항이 있으시면, issues로 등록 혹은 메일 부탁 드립니다.
