### ISSUE TITLE
ValueLinkU / 메뉴추가 후 특정화면(Studio)으로만 연결됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1384]
## 버그 설명 ##
메뉴추가 기능을 이용하여 두개의 메뉴를 추가한 후 각각 서로다른 보고서(Studio)를 선택하여 저장함
--> 첫번째 메뉴인 "주택" 메뉴는 정상적으로 화면이 실행됨
--> 두번째 메뉴인 "금리/증시/원유/원자재"는 실행시 "주택" 메뉴가 실행됨

## 재현하는 방법 ##
http://irisdev.valuelinku.com

## 예상한 행동 ##
각 메뉴 설정에 맞는 보고서(Studio) 화면이 나타나야함

## 스크린샷 ##
[메뉴]
![image](https://user-images.githubusercontent.com/4444717/61775836-ac137700-ae34-11e9-9f74-7fb301a54f22.png)

[메뉴추가]
![image](https://user-images.githubusercontent.com/4444717/61775866-bd5c8380-ae34-11e9-82be-a775d180f9ee.png)

[메뉴링크#1]
![image](https://user-images.githubusercontent.com/4444717/61775888-cfd6bd00-ae34-11e9-8f74-7da8a6ff6fbd.png)

[메뉴링크#2]
![image](https://user-images.githubusercontent.com/4444717/61775908-db29e880-ae34-11e9-9a75-c32a09358791.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
* https://github.com/mobigen/B-IRIS-API-Gateway-Service/issues/536 와 동일한 내용으로 확인됩니다.
* 로그아웃 동작후 처음 선택한 메뉴가 "주택관련" 이면 두메뉴 동일하게 "주택관련" 으로 나오고 "금리" 메뉴이면 두메뉴 동일하게 "금리" 보고서가 동작합니다.
* 해당 내용을 어떤식으로 처리할지 의견 주시면 처리하도록 하겠습니다.

**Comment by veldise** [comment]
현재 최신 버전에서는 재현되지 않아, 본사 운영서버 기준으로는 해결된 이슈로 생각됩니다.
패치 작업 요청하여 진행한 후 재현 여부를 확인하도록 하겠습니다.

**Comment by veldise** [comment]
irisdev.valuelinku.com 기준 해결된 것이 확인되어 닫습니다.
혹시 현상이 재현되면 이슈 reopen 부탁드립니다.
