### ISSUE TITLE
ValueLinkU / 보고서(Studio)화면이 두번 refresh됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1385]
## 버그 설명 ##
보고서(Studio) 생성 후 화면을 실행하면, 내용이 한번 출력 후 다시 refresh되면서 두번 출력됨
두번 출력되면서 전체적으로 화면 실행 시간이 느려짐

## 재현하는 방법 ##
http://irisdev.valuelinku.com 접속
--> 로그인
--> 보고서 실행

## 예상한 행동 ##
화면이 깜빡임 없이 한번에 출력되어야 함

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/4444717/61928130-61b80480-afb2-11e9-83bf-8de00967f52b.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
현재 최신 버전에서는 재현되지 않아, 본사 운영서버 기준으로는 해결된 이슈로 생각됩니다.
패치 작업 요청하여 진행한 후 재현 여부를 확인하도록 하겠습니다.

**Comment by veldise** [comment]
http://irisdev.valuelinku.com/ 에서 현상 재현을 확인했습니다.
시간 설정 객체를 연결할 경우 발생합니다.

**Comment by veldise** [comment]
irisdev.valuelinku.com 기준 해결된 것이 확인되어 닫습니다.
혹시 현상이 재현되면 이슈 reopen 부탁드립니다.
