### ISSUE TITLE
[검색] Command Syntax에 대한 도움말에서 지원되는 command의 리스트 누락

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1386]
## 버그 설명 ##
데이터 브라우저 > 검색 화면의 검색어 입력란에서 도움말 버튼을 클릭하면 Command References가 오픈(아래 스크린샷 참조)되나, command 항목이 현저하게 줄어들었습니다.
IRIS에서 지원하는 모든 command가 리스트되어야 하지 않을까요?

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to '검색' 메뉴
2. 검색어 입력란 하단의 화살표 버튼 클릭
3. Command Syntax의 도움말 버튼 클릭

## 예상한 행동 ##
구 버전에서의 도움말에는 ade 등 20여개 command가 리스트에 출력되어, 각 command의 기능을 설명하였으나, 현재 버전은 9개 command만 리스트에 출력됩니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/61934514-7781f580-afc3-11e9-96ed-6bd9ae12cd62.png)

## 기타 ##
각 command의 사용방법이 도움말에 작성되는 것으로 알고 있습니다만, example이 좀 더 많으면 이해하기가 더 쉬울 것 같습니다.

**Comment by sunghoon** [comment]
신규 예제는 계속 추가 중입니다.
