### ISSUE TITLE
[고급시각화]검색어가 잘려서 출력됩니다.

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1387]
## 버그 설명 ##
검색 화면에서 검색어를 입력하여 검색한 후 고급 시각화로 이동한 경우, 검색어가 일정 길이 이상 길어지면 잘려서 표시되어 어떤 검색 조건을 사용했는지 확인할 수 없습니다.

## 재현하는 방법 ##
1. 데이터브라우저 > 검색
2. 데이터 모델을 선택한 후 검색어 입력란에 검색어 입력
    - 데이터 모델: jiranmail
    - 시간: 전체시간
    - 입력한 검색어: * | where ATTACH_SIZE > 0 and SENDER_COUNTRY = 'US' 
3. '이동' 버튼을 클릭한 후, '고급시각화로 이동' 선택
4. 고급시각화 화면에서 상기 문제 확인

## 예상한 행동 ##
입력한 검색어 전체가 표시되어야 함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/61936984-d302b200-afc8-11e9-87a4-560cfb3504b3.png)

**Comment by veldise** [comment]
@jins00 
IRIS 데이터 브라우저 화면은 기준 해상도를 1280 x 800으로 하고 있으며, 이에 따라 검색어 텍스트가 매우 길 경우 오른쪽에 버튼과 같은 다른 UI 컨트롤과 겹칠 수 있어 위와 같이 축약표기하도록 되어있습니다.

그렇게되면 사용자는 검색어 전체 내용을 확인할 수 없으므로, 피벗 분석에서는 아래와 같이
검색어에 마우스를 올리면 검색어 내용이 나오도록 하는 popover 기능이 있습니다.

문제는 시각화에 이러한 기능이 없는 것으로 확인되었습니다. 추가하도록 하겠습니다.


![image](https://user-images.githubusercontent.com/3411842/61937731-77d1bf00-afca-11e9-90e5-b0daafa18716.png)

**Comment by veldise** [comment]
피벗 / 시각화 / 이상탐지 모두 popover 추가하였습니다.
