### ISSUE TITLE
[시각화/피벗]범위만들기의 기준이 모호합니다.

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1388]
## 버그 설명 ##
피벗 혹은 시각화 화면에서 범위 만들기의 기준이 명확하지 않습니다.
예를 들어, 컬럼값이 10,000 이상부터 10,000의 간격으로 볼 경우,
범위 시작 = 10,000, 범위 크기 = 10,000으로 지정하고 실행하면 첫번째 축의 값이 10,000으로 표시됩니다. 이는 정상으로 판단됩니다.
그런데, 범위 크기를 범위 시작보다 크게(예, 50,000) 하면 첫번째 축의 값이 10,000이 아닌 0으로 표시됩니다.
또한, 범위 크기를 범위 시작보다 작게(예, 8,000) 하면 첫번째 축의 값이 10,000이 아닌 8,000으로 표시됩니다.
범위 시작과 범위 크기의 변화에 따른 차트 값의 출력의 기준이 무엇인지 명확히 정의할 필요가 있습니다.

## 재현하는 방법 ##
1. 데이터 브라우저 > 검색으로 이동
2. 데이터 모델 = jiranmail, 시간 = 전체시간을 선택
3. 검색어 입력란에 검색조건(* | where SENDER_COUNTRY = 'US') 입력한 후, 검색
4. 이동 버튼을 클릭하여 고급 시각화로 이동
5. 시각화 화면에서 히스토그램을 선택
6. 좌측의 컬럼 중, MAIL_SIZE를 X축으로 드래그
7. X축의 MAIL_SIZE를 클릭한 후 범위 만들기를 "예"로 변경
8. 범위 시작과 범위 크기 입력란 각각에 10000을 입력한 후 실행버튼 클릭하고 차트 확인(스크린샷 1번 참조)
9. X축의 MAIL_SIZE를 클릭한 후 범위 크기 입력란에 범위 시작의 값보다 큰 50000을 입력한 후 실행버튼 클릭하고 차트 확인(스크린샷 2번 참조)
10. X축의 MAIL_SIZE를 클릭한 후 범위 크기 입력란에 범위 시작의 값보다 작은 8000을 입력한 후 실행버튼 클릭하고 차트 확인(스크린샷 3번 참조)

## 예상한 행동 ##
범위 크기가 범위 시작과 같든, 크든, 작든 범위 시작으로 지정된 값이 차트의 첫번째 값이 되어야 하지 않을까요?

## 스크린샷 ##
* 스크린샷 1번
![image](https://user-images.githubusercontent.com/23075670/61939654-b49fb500-afce-11e9-937f-350628645a79.png)

* 스크린샷 2번
![image](https://user-images.githubusercontent.com/23075670/61939674-bcf7f000-afce-11e9-8897-c453eb309ce9.png)

* 스크린샷 3번
![image](https://user-images.githubusercontent.com/23075670/61939726-dc8f1880-afce-11e9-9d94-45ecc0db9e65.png)

**Comment by veldise** [comment]
@pjh0347 
data-discovery 서비스의 `/query-analysis` API 가, `start`값이 `unit`보다 작을 경우 `start`를 0으로 처리하는 것 같습니다.

### 참고
#### POST `/query-analysis`
request body:
```json
{
  "q": "*",
  "parameters": {
    "size": 500,
    "col_size": 500,
    "rows": [
      {
        "field": "LEVEL_INT",
        "unit": 10,
        "start": 2
      }
    ],
    "cells": [
      {
        "field": "*",
        "func": "count"
      }
    ]
  },
  "operation": "bar"
}
```
response: 
```
{
  "data": {
    "q": "* | adv bar count(*) SPLITROW 'iris_number_group(\"LEVEL_INT\", 10)' FILTER LEVEL_INT >= 0 COLSIZE 500", 
    "operation": "bar"
  }
}
```

**Comment by seungfwani** [comment]
이슈를 등록해주신 내용처럼 start = 10000, unit = 8000 이라면 `10000~17999, 18000~25999, ...` 의 범위로 결과가 나와야 한다고 생각됩니다.

현재 앙고라의 `/query-analaysis` API 에서 `start`, `unit` 을 처리하는 부분을 수정하였으며,
해당 내용은 운영서버에 배포 예정입니다.

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하여 처리된 것을 확인하였습니다.

- 스크린샷 1번 (시작: 10000, 범위: 10000)
![image](https://user-images.githubusercontent.com/46172579/63912959-7a13b700-ca69-11e9-9bee-25001a1638e5.png)

- 스크린샷 1번 (시작: 10000, 범위: 50000)
![image](https://user-images.githubusercontent.com/46172579/63912984-90ba0e00-ca69-11e9-9302-f299e9a67895.png)

- 스크린샷 1번 (시작: 10000, 범위: 8000)
![image](https://user-images.githubusercontent.com/46172579/63912934-68321400-ca69-11e9-95a4-016629390357.png)
