### ISSUE TITLE
[보고서] 테이블에서 필터를 제거해도 필터 공간이 여백으로 남아있습니다

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1389]
## 버그 설명 ##
그림으로 설명드리겠습니다.

![image](https://user-images.githubusercontent.com/35832986/62017699-9e723e80-b1f2-11e9-927c-c2db965074fc.png)

![image](https://user-images.githubusercontent.com/35832986/62017824-16406900-b1f3-11e9-80e8-2829a1a7b6f5.png)

첫 번째 사진은 [보고서] 의 '테이블'에서 '필터' 가 '표시' 되고 있을 때의 사진입니다.
두 번째 사진은 해당 '테이블' 영역의 '필터'의 '표시' 체크박스를 해제한 상태입니다.

예상대로라면 필터가 사라지면서 붉게 표시된 영역만큼 테이블의 위로 올라가야 하는데
그러지 않고 있습니다.

이 경우, 시각적으로 보기 안좋은 것도 있지만, 스크롤을 없애기 위해 영역을 생각보다 더 길게 만들어야 하는 어려움이 있습니다.

확인 부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [새 보고서]를 눌러 보고서 생성 화면으로 넘어간다
2. "영역"을 생성해서 아무 데이터나 '테이블' 형식으로 표시한다
3. '시각화 옵션'에서 '필터'의 '표시' 체크박스를 선택했다 해제하면서 오류가 발생하는지 확인한다

**Comment by tylor-kr** [comment]
![image](https://user-images.githubusercontent.com/13827425/62749263-b9686c80-ba96-11e9-86c8-72781ea191dc.png)

![image](https://user-images.githubusercontent.com/13827425/62749269-bec5b700-ba96-11e9-88a3-3cab5dd2906d.png)

처리 후 배포 되어 닫습니다.
