### ISSUE TITLE
Studio / 2중축 꺾은선형, y축에 "모두 선택" 설정시 데이터 중복

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1390]
## 버그 설명 ##
- 위치: http://irisdev.valuelinku.com/
- y축 보조의 데이터가 y축 기본에도 나타나는데 제외되어야 합니다. (중복 표현)

## 재현 방법 ##
1. 사이트 접속
    - `valuelinku` 계정으로 접속 (비번 별도 문의)
2. 보고서 - 새 보고서
3. 차트 객체 추가
4. 불러오기 탭에서 "주요국 증시지표(Close) chart" 선택
5. 실행
7. 시각화 유형을 "2중축"으로 변경
6. 시각화 옵션 > 데이터 탭에서 아래와 같이 설정
    - y축 기본: 모두 선택
    - y축 보조: KS11

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/62028869-523bf400-b21c-11e9-8af2-2c7178612a66.png)

**Comment by tylor-kr** [comment]
배포 후 정상 동작 확인하여 닫습니다.
![image](https://user-images.githubusercontent.com/13827425/64405583-79f36700-d0ba-11e9-93f3-f1cd6019c763.png)
