### ISSUE TITLE
Studio / 2중축 꺾은선형 - 시각화 옵션 Null 값 설정 미적용

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1391]
## 버그 설명 ##
- 시각화 옵션 > 일반 탭 > Null 값 설정이 y축(보조)에는 적용되지 않습니다.

## 재현하는 방법 ##
1. 사이트 접속
    - `valuelinku` 계정으로 접속 (비번 별도 문의)
2. 보고서 - 새 보고서
3. 차트 객체 추가
4. 불러오기 탭에서 "주요국 증시지표(Close) chart" 선택
5. 실행
7. 시각화 유형을 "2중축"으로 변경
6. 시각화 옵션 > 데이터 탭에서 아래와 같이 설정
    - y축 기본: 모두 선택
    - y축 보조: KS11
7. 시각화 옵션 > 일반 탭에서 Null 값을 표시, 간격 등으로 변경

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/62029034-a8a93280-b21c-11e9-8675-02016e679369.png)

**Comment by tylor-kr** [comment]
배포 후 정상 동작 하여 닫습니다.
![image](https://user-images.githubusercontent.com/13827425/64405620-9c858000-d0ba-11e9-838e-64dd77542759.png)
