### ISSUE TITLE
데이터추가 / encoding 문제로 추정되는 이슈

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1392]
## 버그 설명 ##
워드클라우드를 그리기 위해 한글 단어가 포함된 데이터를 추가하는데 오류가 발생했습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [데이터 추가]에서 다음 파일을 읽어와 추가한다
파일: (원래 CSV 파일인데, 안올라가서 압축파일로 올립니다.)
[sender_wc_df.zip](https://github.com/mobigen/IRIS-BigData-Platform/files/3441050/sender_wc_df.zip)
2. 아무런 옵션 변경 없이 다음으로 넘어간다
3. 테이블 설정을 다음과 같이 설정한다
![wc_df_추가가안됨(2)](https://user-images.githubusercontent.com/35832986/62033787-bc0dcb00-b227-11e9-9c5b-6b61910c6ce7.png)
4. 다음으로 넘어가 '실행'하면 아래와 같은 로그가 발생하며 실패
로그파일: 
[wc_df_추가안됨(로그).txt](https://github.com/mobigen/IRIS-BigData-Platform/files/3441057/wc_df_.txt)

**Comment by namjals** [comment]
되는 버전으로 원복하였습니다.
