### ISSUE TITLE
연결 정보 / 수정일이 출력되지 않는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1393]
## 버그 설명 ##
- 연결 정보 화면의 목록에 수정일이 출력되지 않습니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/62095662-0476c880-b2bc-11e9-9a7b-eb96c847ad2c.png)

## 내용 ##
- GET `/dsms/v1/connector` 결과에 `update_time` 혹은 `mdate` 값이 없습니다.
- API 결과에 해당 값이 추가되면, UI는 해당 값의 포맷에 맞추어 수정해야 합니다.

**Comment by donghwasuh** [comment]
@veldise 
GET /dsms/v1/connector API 결과로 update_time 혹은 mdate 항목은 존재하지 않습니다. 
GET /dsms/v1/connector/{connector_id} API 결과에 update_time이 존재합니다.

**Comment by veldise** [comment]
@donghwasuh 
GET /dsms/v1/connector API 결과에는 해당 항목을 추가할 수 없나요?

**Comment by donghwasuh** [comment]
@veldise 
해당 항목에 추가 가능합니다.

**Comment by veldise** [comment]
해결되어 닫습니다.
