### ISSUE TITLE
데이터모델 / "데이터 추가"에서 INTEGER로 넣은 컬럼의 유형이 NUMBER로 표시됨

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1394]
## 버그 설명 ##
[데이터 추가] 기능으로 데이터를 넣을 때 열 유형을 'INTEGER'로 설정한 테이블로 데이터 모델을 만들 때 보니, UI에서 "INTEGER" 가 아닌 "NUMBER"로 표시됨

그리고 원래 "NUMBER"는 선택지에 없음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. ssm0219 계정의 WEBMAIL_WC_SEND 테이블을 활용하여 테스트
2. [데이터모델]에서 [새 모델]을 눌러서 해당 테이블을 불러온다
3. 컬럼 "CNT" 부분을 보면 스크린샷과 같이 "NUMBER"로 표시됨
![image](https://user-images.githubusercontent.com/35832986/62108481-1f116780-b2e5-11e9-8a38-af35d81e59c0.png)

## 예상한 행동 ##
INTERGER로 표시되어야 할 것 같음

**Comment by veldise** [comment]
선택하신 IRIS-DB 테이블의 해당 컬럼이 `NUMBER` 유형이고,
IRIS-DB v2에서는 `NUMBER` 유형을 지원하지 않기 때문에 나타나는 현상으로 보입니다.

선택한 테이블의 해당 컬럼의 유형을 확인 부탁드립니다.

**Comment by ssm0219** [comment]
@veldise 

[데이터 추가]에서 해당 컬럼을 제가 "유형 변경"으로 "INTEGER"로 변경했습니다.
스크린샷을 통해 보시는 바와 같이 "NUMBER"는 선택지에 없습니다.
![image](https://user-images.githubusercontent.com/35832986/62114228-2c345380-b2f1-11e9-85b5-d2418f531262.png)


그리고 [데이터 추가] 단계에서 나타나는 컬럼 유형도 "INTEGER"로 되어있습니다.
![image](https://user-images.githubusercontent.com/35832986/62114303-5d148880-b2f1-11e9-8dd3-32db2bf9cc3e.png)


저는 테이블 생성부터 데이터 추가까지 전부 [데이터 추가] 메뉴를 이용한 것이어서 별도로 해당 컬럼을 NUMBER로 지정하거나 그러지 않았습니다.

**Comment by veldise** [comment]
@ssm0219 
네 해당 내용 다시 확인중이었습니다. UI 이슈입니다.

**Comment by veldise** [comment]
@pjh0347 
`iris read` 명령어 수행 결과가 다소 이상합니다.
해당 테이블 컬럼은 `INTEGER`인데 `iris read` 명령어 결과 컬럼 유형은 `LONG`이고,
데이터는 string 입니다.

```json
{"q":"iris read CHOI.TEMP_09999 connector_id = 3 | search *","save":false,"size":10,"sample":true}
```

```json
{
  "status": {
    "current": 1, 
    "total": 1
  }, 
  "fields": [
    {
      "grouped": false, 
      "type": "TEXT", 
      "name": "PRODUCTID"
    }, 
    {
      "grouped": false, 
      "type": "TEXT", 
      "name": "PRODUCT_NAME"
    }, 
    {
      "grouped": false, 
      "type": "LONG", 
      "name": "PRICE"
    }, 
    {
      "grouped": false, 
      "type": "TEXT", 
      "name": "SALE_PRICE"
    }, 
    {
      "grouped": false, 
      "type": "TEXT", 
      "name": "CODE"
    }
  ], 
  "isEnd": true, 
  "results": [
    [
      "FI-AG-G08", 
      "Orvil the Wolverine", 
      39, 
      "24.99", 
      "J"
    ], 
    [
```

**Comment by seungfwani** [comment]
@veldise

**Comment by seungfwani** [comment]
@veldise 
코멘트 해주신 문제에 대한 상황을 설명드리겠습니다.
IRIS에서는 정수 값에 대한 타입을 `INTEGER` 하나로 사용하고 있기 때문에 python에서 제공하는 int(32bit, -21억~21억 범위의 수), long(int 보다 범위가 큰 수) 타입을 구분할 수 없습니다.

int, long 타입을 구분 할 수 없기 때문에 해당 문제를 최소화 하기 위해서,
spark-on-iris 에서는 IRIS에 `INTEGER` 타입을 `Long` 타입으로 읽어 옵니다.

Angora 에서는 spark-on-iris로 읽어온 타입을 그대로 UI측으로 보내고 있습니다.
이로 인해서 `LONG` 타입으로 response가 된 것으로 확인됩니다.

숫자 표현의 범위가 다르기 때문에 정수형의 데이터 처리에서 문제를 최소화 하기 위해서 Angora에서 임의로 타입변환(long->int)을 할 수 없는 것이로 보이며,

두 타입의 구분이 꼭 필요한 기능이라면 추가 개발이 필요합니다.

추가적으로, UI에서 `LONG`으로 response 되는 값을 `NUMBER` 가 아닌 `INTEGER`로 표시할 수는 없는지 검토 부탁드립니다.

**Comment by veldise** [comment]
@seungfwani 
아주 오래전에 이전 개발자 분과 타입 매핑에 대하여 결정한 사항이 아래와 같습니다.
다음 2가지를 검토하여 답변해주시면 그에 따라 수정하겠습니다.

1. LONG 이외의 다른 숫자 3가지 타입 매핑
2. `NUMBER` 유형은 이제 사용하지 않는 것인지?


|데이터 유형| angora 유형|
|:-:|:-:|
| BYTE | NUMBER |
| SHORT | NUMBER |
| LONG | NUMBER |
| FLOAT | NUMBER |
| BINARY | TEXT |
| BOOLEAN | TEXT |
| TIMESTAMP | TIMESTAMP |
| DATE | DATE |

**Comment by seungfwani** [comment]
@veldise 
답변드리겠습니다.

1. 수정이 필요한 타입 매핑 테이블
|데이터유형|angora 유형|
| ---- | ---- | ---- |
|BYTE | INTEGER|
|SHORT| INTEGER|
|LONG | INTEGER|
|FLOAT | REAL|

2. 현재 IRIS 에서 `NUMBER` 유형은 사용하지 않는다고 합니다.
  - 이유: `NUMBER` 유형에 대한 사용자의 혼란이 있어, `INTEGER` 및 `REAL`로 변화

**Comment by veldise** [comment]
@seungfwani 
확인했습니다. 차주중에 수정하도록 하겠습니다.

**Comment by veldise** [comment]
운영서버까지 배포 완료되어 닫습니다.
