### ISSUE TITLE
피벗 분석 / 2개 이상의 필터 사용 시 오류 발생

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1396]
## 버그 설명 ##
[피벗 분석]에서 각각 1개씩 필터를 걸었을 때는 정상 작동 하던 것이 2개를 동시에 적용하니 오류가 발생했습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 아래 스크린샷과 같이 설정 후 실행 (계정: ssm0219 )
![image](https://user-images.githubusercontent.com/35832986/62179722-7288c180-b388-11e9-8f94-9c10045581e9.png)

## 예상한 행동 ##
필터 두 개 다 적용된 결과가 나와야 함

## 스크린샷 ##
1. 필터 중 '첨부파일유무' 에 대한 것만 적용했을 때의 정상 작동 화면
![image](https://user-images.githubusercontent.com/35832986/62179776-9e0bac00-b388-11e9-9f23-7e14522dda74.png)

2. 필터 중 '메일구분'에 대한 것만 적용했을 때의 정상 작동 화면
![image](https://user-images.githubusercontent.com/35832986/62179801-b2e83f80-b388-11e9-9768-66d44f92b56f.png)

## 로그 ##
 angora error: <class 'pyspark.sql.utils.ParseException'> mismatched input 'S_R_TYPE' expecting <EOF>(line 1, pos 24) == SQL == `FILE_STAT` = 'Y' `AND` S_R_TYPE = `'S'` ------------------------^^^

**Comment by seungfwani** [comment]
해당 이슈는 pivot 명령어의 filter 인자의 파싱에서
한개의 필터는 파싱이 잘되나, 2개 이상 부터 잘못 파싱되는 문제가 있었습니다.

현재 filter 조건의 개수에 상관없이 파싱이 정상적으로 되도록 수정하였고,

**Comment by seungfwani** [comment]
해당 이슈는 pivot 명령어의 filter 인자의 파싱에서
한개의 조건은 파싱이 잘되나, 2개 이상 부터 파싱 잘못되는 문제가 있었습니다.

현재 filter 조건의 개수에 상관없이 파싱이 정상적으로 되도록 수정하였고,
운영서버(192.168.100.180)에 배포가 되어 정상 동작하는 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/46172579/62437607-e5c27700-b77e-11e9-92f4-6e5412d14eef.png)
