### ISSUE TITLE
[워드클라우드]결과 표시에 대한 개선 요청사항

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1397]
## 개선 요청 ##
신규 개발된 워드 클라우드 기능을 실제 데이터(각 단어의 발생 카운트)에 적용한 결과, 
최대값과 대다수 작은값의 차이가 10배 이상인 경우, 대다수의 작은 값을 갖는 단어가 알아볼 수 없을 정도로 작게 표시되므로(아래 화면 캡쳐 참조), 이에 대한 보정 등 대책이 필요합니다.

## 재현 방법 ##
1. 데이터 브라우저 > 보고서로 이동
2. 새보고서 선택
3. 영역 선택
4. 조건 입력
   - 데이터 모델: 사내웹메일_WC_발신
   - 시간: 2019/05/02 00:00:00 ~ 2019/05/03 00:00:00  
   - 검색어: * | stats sum(CNT) as FREQ by WORD | where FREQ > 20
5. 시각화 유형 = 워드클라우드 선택 후 실행

## 화면 캡쳐 ##
![image](https://user-images.githubusercontent.com/23075670/62186734-2f3b4c80-b3a2-11e9-9c9c-7f043a69c27d.png)

**Comment by veldise** [comment]
@jins00 
아래와 같이 "최소 글자 크기", "최대 글자 크기" 옵션을 추가하였습니다.
기본값은 1 / 25, 단위는 px 입니다. 다만 차트 크기에 따라 정확한 크기로 표현되지 않을 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/63004557-a4844280-beb5-11e9-9096-6518f3019240.png)
