### ISSUE TITLE
[검색 - 통계탭] 천 단위 표시기능 미적용

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1398]
## 버그 설명 ##
개인설정에서 천 단위 표시에 체크하면 데이터 브라우저의 모든 화면에 출력되는 데이터는 천 단위로 ','가 표시되는 것으로 알고 있습니다.
그러나, 검색 > 통계/시각화 탭에 출력되는 데이터에는 적용되지 않습니다.

## 재현하는 방법 ##
1. 개인설정 > 표시로 이동하여 "천단위 표시" 체크박스에 체크한 후 변경 버튼 클릭
2. 데이터브라우저 > 검색 화면으로 이동하여 데이터 검색
   - 데이터모델: syslog
   - 시간: 최근 10분
   - 검색어: *| stats count(*) as event BY HOST | sort -event
3. 통계탭에 출력되는 천 자리 이상 데이터에 ','가 미표시됨을 확인(아래 화면 참조)
    (시각화 탭도 동일함)

## 예상한 행동 ##
개인설정에서 "천단위 표시"에 체크하면 검색 > 통계 탭을 포함하여 모든 데이터브라우저 화면에서 동일하게 적용되어야 함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/62199892-4d637580-b3bf-11e9-99c7-7929cb532d0f.png)

**Comment by veldise** [comment]
운영서버에 배포 및 해결되어 닫습니다.

@jins00 
혹시 현상이 재현되는 경우에는, 개인설정에서 한 번 더 "변경"(저장) 버튼을 눌러주시기 바랍니다.
