### ISSUE TITLE
Studio / 보고서에 출력된 그리드/차트의 Data 다운로드 기능 필요

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1399]
## 기능 요청 ##
Studio에서 생성한 결과물(차트/그리드)에 대한 개별 Data 다운로드 기능 필요(엑셀파일 다운로드)

## 원하는 솔루션 설명 ##
Studio에 등록 되는 각 차트 및 그리드에 대해 엑셀 저장버튼을 추가하여, 원하는 데이터를 엑셀파일로 다운로드 하는 기능 필요
(DB브라우저에 있는 조회 결과 다운로드와 같은 기능)

**Comment by seungfwani** [comment]
DSMS 에 `execute/download` API 를 추가하였습니다.
request 로 쿼리가 오면, 
response로 해당 결과 파일을 보내주는 역할을 하는 API 입니다.

사용방법에 대해서는 아래 링크의 `쿼리 결과 다운로드` 탭에서 확인 할 수 있습니다.

https://dsm2.docs.apiary.io/#reference/0/7/0

**Comment by swish1995** [comment]
@seungfwani 
* 링크 걸어주신 `쿼리 결과 다운로드` 는  `GET` 방식으로 되어 있습니다.
* 필요한 변수값을 `BODY` 를 통해 `POST` 방식으로 전달하도록 되어 있어 다음과 같은 에러가 발생합니다.
   ```
   {status: 2, messages: "required value error, user"}
   messages: "required value error, user"
   status: 2
   ```
   확인 부탁드립니다. 

* 참고로 `POST` 방식으로 시도했을때는 `not supported method` 에러가 발생합니다.

**Comment by seungfwani** [comment]
@swish1995 
현재 다운로드시 `GET` 으로 요청함과 동시에 쿼리를 요청하도록 되어있습니다.
python request 모듈로 실행시 `GET`에도 body를 요청할 수 있어 이와 같이 구성하였는데
일반적인 REST API 사용방식이 아닌 것으로 보입니다.

따라서 다음 두가지 순서로 변경해야 할 듯 합니다.
1. `POST /dsms/v1/execute/async` API 로 쿼리 실행
2. `GET /dsms/v1/execute/download` API 로 실행된 쿼리 파일로 다운로드

해당 내용을 수정 한 후 말씀드리도록 하겠습니다.

**Comment by swish1995** [comment]
@seungfwani
그러면 
1. `POST /dsms/v1/execute/async` API 로 쿼리 실행
작업후에 기존 dsms 실행처럼 status 를 확인후 작업이 완료된 job 에 대해 
2. `GET /dsms/v1/execute/download` API 로 실행된 쿼리 파일로 다운로드
작업을 수행하면 되는것인지 확인바랍니다.

**Comment by seungfwani** [comment]
- 질문 사항에 대한 답변입니다.
  - 기존에 `GET /dsms/v1/execute/{task_id}/fetch` API 와 유사한 동작을 합니다.

- 수정완료 공유
  - download api 를 수정하였습니다.
  - `GET /dsms/v1/execute/{task_id}/download?type={type}` 의 형태로 구성되어있습니다.
  - 다음 링크를 참고하시기 바랍니다. https://dsm2.docs.apiary.io/#reference/0/7/0
