### ISSUE TITLE
보고서 / 클릭 시 초기 실행이 안됨

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1400]
## 버그 설명 ##
[보고서] 메뉴에서 보고서명을 클릭하여 새 창에서 보고서를 열었는데, 열렸을 때 처음에 진행되어야 하는 실행이 진행되지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [보고서]에서 ssm0219 계정으로 만든 "메일로그분석_사내" 클릭
2. 아래 스크린샷처럼 아무것도 진행되지 않는 화면이 표시됨
![image](https://user-images.githubusercontent.com/35832986/62272895-2799a780-b477-11e9-9231-939c6e585507.png)
3. 우측 상단의 기간을 조정해서 다시 실행하면 정상 실행됨
![image](https://user-images.githubusercontent.com/35832986/62272958-4bf58400-b477-11e9-85dc-8d84ddd58e66.png)

**Comment by veldise** [comment]
긴급 패치로 해결되어 닫습니다.
