### ISSUE TITLE
연결 정보 / 연결 정보 수정 실패

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1401]
## 버그 설명 ##
해당 서버: http://192.168.100.180/#/

## 재현하는 방법 ##
* 서버 접속
* 데이터브라우저 > 관리 > 연결정보 메뉴로 이동
* 새 연결정보 버튼 클릭 후 다이얼로그에 스크린샷에 있는 내용 입력
* 저장 버튼 클릭
* 생성된 연결정보에 대하여 수정 버튼 클릭
* 비밀번호 입력 후 저장하면 실패

> 이슈에 비밀번호가 노출 되면 안되므로, 실제 테스트시에 참고만 하시기 바랍니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/13827425/62444237-ed424a00-b797-11e9-85e5-37395ff71922.png)

![image](https://user-images.githubusercontent.com/13827425/62444426-69d52880-b798-11e9-8fc2-6eb17d37d56d.png)

## 로그 ##
![image](https://user-images.githubusercontent.com/13827425/62444460-86716080-b798-11e9-840f-68f1e066a384.png)

**Comment by tylor-kr** [comment]
@pjh0347

**Comment by anhm** [comment]
일차적으로 확인인을 해본 결과

에러를 해결하기 위해서는 둘중 하나가 만족 되면 됩니다.

1. 웹에서 해결을 할 경우
```
{
  "connector_name": "mariadb_test",
  "description": null,
  "info": {
    "update_time": null,
    "host": "192.168.100.180",
    "port": 3308,
    "database": "jhm",
    "user": "jhm",
    "password": "hello.jhm"
  }
}
```
여기에서  `"update_time": null,` 항목이 제외되면 에러가 발생하지 않습니다.
update_time항목은 db에 insert될때 자동으로 들어가는 항목입니다.

2. 서버에서 해결을 할 경우
불필요한 key값이 들어오면 그냥 continue 시켜 주시면 됩니다.


--------


해당 이슈 이외에도 웹 항목상에서 수정일이 표시가 되는데,
현재 DSMS에서 리스트를 요청할 경우 updatetime 항목은 제공하고 있지 않습니다.

web과 server에서 해당 프로토콜을 정의해서 전달하도록 수정을 해야 할것 같습니다.

(현재는 update_time 항목은 connetion의 상세 항목에서만 제공하고 있습니다.)

**Comment by veldise** [comment]
일단 이 이슈는 1번으로 해결하겠습니다. (UI에서 해결)

**Comment by veldise** [comment]
운영서버에 해결 및 배포되어 닫습니다.
