### ISSUE TITLE
ValueLinkU / 콤보(or Select) 박스의 부가 기능 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1402]
## 기능 요청 ##
-  콤보(or Select) 박스 추가시 해당 리스트조회는 다른  콤보(or Select) 박스의 인자값으로 가져 올 수 있어야 함
-  콤보(or Select) 박스에 값을 입력받아 자동 필터 조건이 적용될 수 있어야 함(현재 검색 기능의 DSL 입력방식처럼)

## 고려한 다른 대안 ##
 콤보(or Select) 박스로 안될경우 현재 검색화면의 DSL입력 방식처럼 선택 항목을 설정 할 수 있도록 지원

**Comment by veldise** [comment]
정희동 팀장님께 문의한 결과 현재 진행중인 다음 2가지 기능으로 확인되었습니다.
- Combo-box / 사용자 입력으로 드랍다운 목록 필터링
- Combo-box / 다른 Combo-box의 선택 이벤트를 트리거로 지정하여 실행

**Comment by veldise** [comment]
개발 완료된 이슈라 닫습니다.
