### ISSUE TITLE
[보고서] 영역 객체에 대한 탭 타이틀 폰트 크기가 작음

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1403]
## 버그 설명 ##
보고서 화면에서 영역 객체를 선택하여 드래그한 후, 우측의 각 탭을 보면 탭 타이틀의 폰트가 타이틀을 읽지 못할 정도로 작아집니다.
현재 사용중인 브라우저는 크롬 Version 75.0.3770.142 (Official Build) (64-bit) 이며,
IE에서도 동일 현상 발생합니다.

## 재현하는 방법 ##
1.보고서 화면으로 이동하여 "새보고서" 오픈
2. 좌측 상단의 "영역" 아이콘을 클릭한 후, 캔버스에 드래그
3. 우측에 표시되는 4개 탭의 타이틀 폰트 확인 (아래 화면 캡쳐 참조)

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/62512965-2b517380-b855-11e9-9905-7bf2a4eb7619.png)

**Comment by jins00** [comment]
보고서 화면의 다른 객체를 선택한 경우에는 해당 탭의 타이틀 폰트 크기가 정상으로 표시됩니다.

**Comment by veldise** [comment]
특정 OS/브라우저에서 해당 현상을 확인하였습니다. 이번주에 패치 가능한지 검토해보겠습니다.

**Comment by onlyeon** [comment]
탭의 갯수가 늘어나 임시로 작성된 인라인 스타일로 인해 발생한 문제입니다.
CSS에서 탭 사이즈 조절하고 인라인 스타일은 제거할 수 있도록 처리하겠습니다.
