### ISSUE TITLE
[보고서] 텍스트 객체의 글꼴 크기 설정 적용 오류

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1404]
## 버그 설명 ##
보고서 화면에서 텍스트 객채를 선택하고 캔버스에 드래그하여 텍스트를 입력한 후 우측의 글꼴에서 크기를 변경(24 -> 36)하였으나, 변경된 크기가 24로 계속 유지됩니다.

## 재현하는 방법 ##
1. 데이터브라우저 > 보고서 > 새보고서
2. 텍스트 아이콘을 클릭하고 캔버스에 드래그한 후에 텍스트를 입력
3. 우측의 속성 탭에서 글꼴 크기를 기본 24에서 36으로 변경
4. 텍스트의 크기는 커졌으나, 속성 탭에서의 글꼴 크기는 계속 24로 유지됨

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/62516909-35796f00-b861-11e9-88c8-b451ff545376.png)

**Comment by swish1995** [comment]
수정되어 닫습니다.

**Comment by veldise** [comment]
@swish1995 
이슈가 발생한 위치(ex) 운영서버)에 배포되어 해결 확인 후 닫아주세요.

**Comment by veldise** [comment]
운영서버에 해결 및 배포 완료되어 닫습니다.
