### ISSUE TITLE
[전력연구원] 로그인 문제

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1407]
## 버그 설명 ##
로그아웃 버튼 클릭후 로그아웃된 상태에서 사용자계정 입력하는 textbox이나 패스워드 입력하는 textbox를 클릭하면 바로 로그인이 됩니다.
로구아웃 이후에 정상적인 로그인 처리가 될 수 있도록 보완 부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://mda.kepco.co.kr:51080/#/login 로그인 화면에서 로그인
2. MDA메인화면 우측 상단의 로그아웃버튼 클릭
3. http://mda.kepco.co.kr:51080/#/login화면에서 textbox클릭 
  or http://mda.kepco.co.kr:51080/ 주소창에 입력
전에 로그인한 세션이 유지됨.

**Comment by veldise** [comment]
현재 본사에서는 재현되지 않습니다.

**Comment by chohi22** [comment]
IP로 테스트를 하면 재현이 안되는것 같고요.
dns명으로 설정하고 테스트를 해보면 재현이 됩니다.
ex) hosts파일에 추가
 1.  192.168.102.112 mda.kepco.co.kr 
 2.  웹브라우저에 mda.kepco.co.kr로 접속 후 로구인>로그아웃
 3.  textbox클릭 or 주소창에 mda.kepco.co.kr 입력

**Comment by veldise** [comment]
@chohi22 
아, 위 코멘트는 원인파악 차원에서 기록한 내용입니다.
`b-iris.mobigen.com` 사이트에서는 재현되지 않아, 운영/MDA 버전 차이에 따른 문제일 가능성이 높습니다.

현재 원인 파악 중입니다.

**Comment by veldise** [comment]
@chohi22 
이슈를 해결한 수정 버전을 운영팀에 전달하였으니, 시간 여유가 되시면 문제가 해결되었는지 확인 부탁드립니다.

**Comment by chohi22** [comment]
로그인문제 확인 했습니다.
