### ISSUE TITLE
[보고서] 게이지의 값 표시 문제

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1408]
## 버그 설명 ##
보고서에서 시각화 유형을 Guage로 선택하고 검색하는 경우, 게이지 객체의 크기를 줄이면 데이터 값이 안 보이는 현상 발생

## 재현하는 방법 ##
1. 데이터 브라우저 > 보고서 > 새보고서
2. 영역 아이콘을 선택한 후, 시각화 유형을 Guage로 선택
3. 데이터 모델: syslog
4. 시간 설정: 어제
5. 검색어
* LEVEL != 'info' | sql 'select (select count(*) from angora where LEVEL = "crit" or LEVEL = "err") / count(*) * 100 as RAT from angora' | sql 'select round(RAT, 1) from angora'
6. 게이지 객체의 크기를 줄였다 늘렸다 하면 데이터 값이 정상적으로 표시되지 않음
   (게이지 객체에 빈 공간이 너무 크게 할당된 것이 아닌가요?)

## 스크린샷 ##
1. 데이터가 정상적으로 표시되었을때 게이지 객체의 최소 크기:    
![image](https://user-images.githubusercontent.com/23075670/62594679-6667ab80-b916-11e9-9c9c-983e560ed64a.png)

2. 빈 공간이 너무 많고, 보고서 내에서 다른 객체와의 균형을 맞추기 위해서 사이즈를 줄인 경우:
![image](https://user-images.githubusercontent.com/23075670/62594634-3f10de80-b916-11e9-88f9-a8ab15892cb8.png)

**Comment by veldise** [comment]
@jins00 
아래와 같이 게이지 차트의 크기를 140% 정도로 조정하였습니다.

![image](https://user-images.githubusercontent.com/3411842/63004630-d3021d80-beb5-11e9-9fb0-1345305f6cc3.png)
