### ISSUE TITLE
[보고서] 테이블 객체의 시각화 옵션이 변경됩니다.

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1410]
## 버그 설명 ##
보고서에서 이벤트 값 전달 설정이 되어 있는 테이블 객체의 경우, 
수정 화면에서 해당 객체의 시각화 옵션을 기본값에서 변경한 상태에서
해당 테이블 객체에 표시된 데이터를 선택하여 해당 이벤트 값이 전달된 후에는
시각화 옵션의 설정값이 다시 기본값으로 변경됩니다.

## 재현하는 방법 ##
1. 데이터브라우저 > 보고서 
2. > "사용 현황" 보고서의 편집 컬럼 옵션에서 '수정'을 선택하여 해당 보고서의 수정 화면으로 이동
3. "Top 10 호스트" 객체를 선택한 후 '실행' 버튼 클릭
   이때 우측의 시각화 옵션에서 행번호 = 미표시, 필터 = 미표시, 목록 개수 값 = 10, 목록 개수 = 미표시 임을 확인.(스크린 1 참조)
4. 해당 객체에 표시된 데이터 중 하나를 선택하면 해당 이벤트 값이 우측의 차트로 전달되어 표시됨. 그러나,  이때 "Top 10 호스트" 객체의 시각화 옵션이 기본 값으로 변경됨(스크린 2 참조)

## 스크린샷 ##
1. 스크린 1
![image](https://user-images.githubusercontent.com/23075670/62606783-e0f4f300-b937-11e9-8916-d94cf4c821c5.png)

2. 스크린2
![image](https://user-images.githubusercontent.com/23075670/62606860-0aae1a00-b938-11e9-8f36-82a95293836d.png)

**Comment by veldise** [comment]
우측 사이드패널에 값을 표시하는 조건에 버그가 있었습니다.
수정하여 운영 서버에 배포 완료하였습니다.
