### ISSUE TITLE
[보고서]IE에서 검색어 입력창 확대 불가능 오류

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1411]
## 버그 설명 ##
크롬에서는 보고서 화면에서 검색어 입력 시, 입력창을 확대가 가능하지만(스크린샷 1 및 스크린샷 2),
IE에서는 확대가 불가능합니다(스크린샷 3).
현재 사용중인 IE 버전은 11.239.18362.0

## 재현하는 방법 ##
1. IE 오픈한 후, IRIS > 데이터 브라우저 > 보고서 > 새 보고서
2. 영역 객체 선택 및 캔버스에 드래그
3. 우측 데이터 탭에서 검색어 입력창에 검색어 입력(*)
4. 크롬에서와 같이 검색어 입력창 우측 하단을 드래그하여 검색창을 확대하고자 하였으나 확대 불가함

## 스크린샷 ##
1. 스크린샷 1(크롬 화면) -> 정상 화면
![image](https://user-images.githubusercontent.com/23075670/62754616-8c728480-baab-11e9-87d5-cdf246a25a63.png)

2. 스크린샷 2(크롬화면에서 검색창 확대 후) -> 정상 화면
![image](https://user-images.githubusercontent.com/23075670/62754640-a744f900-baab-11e9-97df-539e4293b560.png)

3. 스크린샷 3(IE 화면) -> 확대 안됨
![image](https://user-images.githubusercontent.com/23075670/62754668-ce032f80-baab-11e9-9c98-b19e188809b6.png)

**Comment by sunghoon** [comment]
비슷한 상황이 발생하면 새 이슈로 처리하겠습니다.
