### ISSUE TITLE
MDT / 검색 기능에서 마이너스 값 조건으로  조회시 오류 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1412]
## 버그 설명 ##
검색 기능에서 마이너스 값을 조건으로 조회하면 오류 발생

## 재현하는 방법 ##

1. 검색화면 실행
2. MDT_DATA_JP 모델 선택
3. * | where RSRP<-100  실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/62921993-41c37600-bde5-11e9-9381-29a33bc12303.png)

**Comment by pjh0347** [comment]
where 명령어 문법 파서의 문제 입니다. 개선하여 차주 목요일에 운영 배포 예정입니다.

**Comment by seungfwani** [comment]
명령어 문법 파서에 `-` 값을 처리 할 수 있도록 수정하였습니다.

목요일(8/29) 운영서버 배포 예정입니다.

**Comment by seungfwani** [comment]
앙고라 서비스를 8/29(목) 운영서버에 배포하여 처리된 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/46172579/63913300-a7ad3000-ca6a-11e9-8d79-add94ec63d6c.png)
