### ISSUE TITLE
MDT / 보고서에서 SQL작성시 일본어(한자) 조건으로 할 경우 오류 발생 

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1413]
## 버그 설명 ##
보고서에서 SQL을 작성시 일본어 조건을 넣으면 쿼리 실행 오류가 발생함

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 실행
2. 일본어(한자) 조건이 들어간 SQL실행
 select round(abs(rsrp),2) as rsrp , meshcode3 from mdt_jp.TB_MDT 
where area2 = '東京都' group by meshcode3;

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/62922289-04abb380-bde6-11e9-8ebf-ea475a4fff61.png)

**Comment by anhm** [comment]
1차저으로 확인을 해본 결과 같은 쿼리를 IRIS-DB의 콘솔 및 IRIS-WEB의 DB 브라우저에서 진행할 경우 정상적으로 동작하는 것으로 파단됨

- DSMS에서 쿼리를 전달하는 과정중 문제가 있는 것으로 파악되는 상황임

**Comment by anhm** [comment]
DSMS에 사용된 IRIS용 API를 확인볼 필요가 있어 보임
    - DSMS에서 사용중인 IRIS-DB용 API가 문제 로 보임

WEB-DSMS-DB 를 거치면서 DB에서 받는 최종 쿼리가 아래와 같이 짤려 들어가는 것으로 파악됨

```
select round(abs(rsrp),2) as rsrp , meshcode3 from mdt_jp.TB_MDT where area2 = '東京都' group by mesh
```

**Comment by donghwasuh** [comment]
현재 IRIS API 수정하여 박진호 선임님이 DSMS 재배포 예정입니다. 
배호된 후 테스트하고 이슈 닫도록 하겠습니다.

**Comment by donghwasuh** [comment]
@seungfwani 해당 이슈 해결된 DSMS 재배포 완료된 경우 issue close 부탁드립니다.

**Comment by JeongHeeDong** [comment]
담당자분께서는 현재 진행 상황 업데이트 해 주세요
