### ISSUE TITLE
MDT / 보고서 기능에서 쿼리 실행시 job timeout이 자주 발생함

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1414]
## 버그 설명 ##
보고서 생성 화면에서 job timeout이 발생함

정상실행 쿼리 : SELECT LON,LAT, MESHCODE3,  min(RSRP) AS RSRP FROM OSDEV.MDT_MS_2H where HH='6' group by LON, LAT, MESHCODE3
timeout 발생 쿼리 : SELECT LON,LAT, MESHCODE3,  min(RSRP) AS RSRP FROM OSDEV.MDT_MS_2H group by LON, LAT, MESHCODE3

쿼리 결과수가 많으면 발행 하는 것인지?
job timeout발생 기준이 어떻게 되는지?

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 실행
2. sql실행
 SELECT LON,LAT, MESHCODE3,  min(RSRP) AS RSRP FROM OSDEV.MDT_MS_2H group by LON, LAT, MESHCODE3

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/62923120-ffe7ff00-bde7-11e9-9e40-4f70ae9d670d.png)

## 기타 ##
job timeout이 아닌 다른 원인으로 발생한 오류라면 실제 오류에 대한 노티정보 필요

**Comment by pjh0347** [comment]
위에 IRIS 쿼리를 DB 브라우저 통해서 실행시켜 봤을때 5초가 넘어가는 경우가 있습니다. 

@veldise 
UI 타임아웃 기준을 5초로 잡고 있는 상황에서 쿼리 수행에 걸리는 시간이 이보다 길어 발생하는 이슈로 보입니다.

![image](https://user-images.githubusercontent.com/5305236/63404026-8d48d600-c41c-11e9-87d4-0167d94a00f1.png)

**Comment by veldise** [comment]
@pjh0347 
이전에 말씀하신대로 위 쿼리에 대해 적절한 타임아웃 시간을 알려주시면 먼저 적용하겠습니다.

**Comment by JeongHeeDong** [comment]
우선 타임아웃 시간을 15초로 설정 요청 드립니다.

**Comment by veldise** [comment]
@JeongHeeDong 
알겠습니다.
