### ISSUE TITLE
치안연 쿼리버그1. 점두개 오류

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1415]
## 버그 설명 ##
DB명.테이블명.필드명 식의 점 두개 표현이 WHERE절에서 안됨.

## 재현하는 방법 ##
동작을 재현하는 방법 : 아래 화면에 접속 정보 있음

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3444816/63133828-df938c80-c001-11e9-89de-3310e312bff4.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##

다음 주에(8월19일~23일) 치안연 연구원들이 들어와서 이것을 볼 예정입니다.
이 화면을 이용해서 QUERY로 각종 검색을 할 예정인데 안되어서 대략 난감입니다.

**Comment by anhm** [comment]
현재 IRIS의 쿼리의 경우 WHERE 절에 사용하는 규칙은 다음과 같이 두가지만 제공을 하고 있습니다.

```
SELECT
   FILED1
FROM
   {DB1.}TABLE1
WHERE
   {TABLE1.}FIELD = 1
```

 혹은

```
SELECT
   FILED1
FROM
   {DB1.}TABLE1 as ALIAS1
WHERE
   ALIAS1.FIELD = 1
```

요청하신 방식을 제공하기 위해서는 단기간에는 불가능한 상태입니다.

**Comment by nomota** [comment]
@kim3163 (김준우 주임도 같이)

일단 점을 하나만 쓰는 방식으로 우회해서 쓰면 되겠네요.

혹시 이런 내용이 매뉴얼에도 반영되어 있나요? (궁금해서)

**Comment by anhm** [comment]
현재는 이렇게 자세하게는 매뉴얼에서는 제공을 하고 있지는 않습니다.

요번 기회에 이런 내용을 매뉴얼에 조금씩 반영을 하면 될것 같습니다.
해당 내용을 매뉴얼에 반영한 이후에 이슈를 닫도록 하겠습니다.
