### ISSUE TITLE
치안연 버그2. SQL 한글 검색 오류

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1416]
## 버그 설명 ##
SQL WHERE MATCH 절에 한글이 안되네요. 

## 재현하는 방법 ##
동작을 재현하는 방법 : 스크린샷 참조

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3444816/63133937-46b14100-c002-11e9-983c-6e802d71f4b1.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
다음 주(8월19일~23일)에 이 화면에서 고객이 SQL로 검색을 직접 할 예정입니다.

**Comment by anhm** [comment]
1. 해당 쿼리를 직접 써서 확인을 해본 결과 같은 현상이 나타나고 있지 않습니다. 예상으로는 테스트를 진행한 컴퓨터의 환결 이슈로 파악되고 있습니다.
    - 해당 쿼리를 직접 작성하여 몇대의 컴퓨터에서 진행해본 결과 같은 현상이 나타나지 않고 있습니다.
    - 과거 전례로 봤을 경우 쿼리를 붙여넣기 등의 작업을 할경우 간혹 발생하던 적이 있었습니다.

=> 아래의 쿼리로 다시한번 테스트를 부탁 드립니다. 

```
/*+ LOCATION ( PARTITION >= '20190101000000') */ 
SELECT 
	CDATE, title
FROM 
	NEWS.NV_NEWS
where
  nv_news.title  = '구조'
dlimit 1
; 
```

만약에 같은 현상일 경우에는 사용하신 OS, 브라우저 등의 정보를 알려 주시면 같은 환경에서 발생하는지 다시한번 확인해 볼수 있을것 같습니다.

2. 해당 쿼리의 경우 match 문법을 사용하셨으나, 해당 쿼리의 경우 테이블이 FTS 테이블일 경우에만 사용 가능합니다.
    - CREATE 쿼리를 다시한번 확인 부탁 드립니다.
    - 현재 사용자 기준으로는 FTS4 테이블만 가능합니다. FTS5 테이블은 사용자가 직접 작성이 불가능합니다.
        - 예전 일본어 특허 검색으로 사용된 테이블은 FTS5 테이블로 만들어진 테이블입니다.

**Comment by nomota** [comment]
치안연 건들은 김준우 주임(기트허브 kim3163)에게 연결이 되면 좋겠습니다. 김준우 주임이 트래킹 할 예정입니다.

**Comment by anhm** [comment]
@nomota
트래킹을 연결을 위해서는 이슈 등록시 다음과 같이 해주시면 좋을것 같습니다.

```
이슈 등록시 
@kim3163
와 같은 방식으로 이름을 등록
혹은
오른쪽 메뉴의 assignees 로 등록
```

**Comment by nomota** [comment]
DB 브라우저 화면에서는 한글 오류가 나고, 검색 화면에서는 한글 오류가 안 나오네요.

안형민 선임이 얘기한 copy-paste 해서 생긴 원인 일 수 있을 것 같습니다.
지금 쿼리를 DB브라우저 화면에서 지우고 직접 타이핑해 보니 또 되네요.

뭔가 도움말이 더 잘나오면, 좋긴 하겠지만, 일단 우회해서 쓸 수는 있겠네요.
매뉴얼과 사용자 교육으로 해결할 수 있을 것 같습니다.

**Comment by anhm** [comment]
해당 내용을 트러블 슈팅 같은 매뉴얼에 반영한 이후에 이슈를 닫도록 하겠습니다.
