### ISSUE TITLE
치안연 검색, 본문 키워드 검색 오류

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1417]
## 버그 설명 ##
신문기사 테이블을 데이터로 모델링 한 후에, 검색 화면에서 원하는 검색을 하려고 하는데, 잘 안되네요.

## 재현하는 방법 ##
동작을 재현하는 방법 : 스크린 샷 참조.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3444816/63134819-208da000-c006-11e9-8248-4935b0543a4a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
다음주 (8월 19일~23일) 중에 치안연 사람들이 원격접속해서, 이 시스템으로 서로 다른 키워드로 각종 검색을 할 예정입니다.

**Comment by anhm** [comment]
- 해당 테이블이 FTS 테이블이 아니기 때문에 match 문법 오류가 발생할 수 있는 상태입니다.
    - 해당 테이블을 FTS 테이블로 다시 생성이후에 테스트가 필요한 상태입니다.

**Comment by nomota** [comment]
해당 테이블을 김준우 주임이 다시 FTS로 재구성할 예정입니다.

**Comment by anhm** [comment]
해당 이슈는 닫고,
추후 FTS 테이블로 같은 현상이 발생할 경우 이슈를 등록 부탁 드립니다.
