### ISSUE TITLE
치안연 검색 이슈 - 쿼리 대소문자 이슈

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1418]
## 버그 설명 ##

검색화면에서 대소문자 처리가 안되는 것 같음.

## 재현하는 방법 ##
동작을 재현하는 방법 : 화면 참조

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3444816/63136036-1cb04c80-c00b-11e9-9879-4d6016db830a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##

치안연 지원을 '김준우 주임(기트허브 ID: kim3163)'이 트래킹 할 예정입니다.
혹시 치안연 이슈들이 김준우 주임과 연결될 수 있도록 해 줄 수 있나요?

**Comment by nomota** [comment]
@kim3163

소문자로 하면 되기는 하니까 우회가 가능해서, 급한 일은 아닙니다.

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/64393357-f6228600-d08b-11e9-92ea-b8be57f9c0ee.png)
