### ISSUE TITLE
ValueLinkU / 검색에서 자동 생성된 차트로 필터 실행시 Data조회 결과 없음으로 나타남

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1419]
## 버그 설명 ##
검색에서 자동 생성된 차트로 필터 실행시 Data조회 결과 없음으로 나타남
장기간(??년~10년이상의 Data대상)의 데이터에 대하여 검색 실행시 기본 차트가 1년단위로 출력됨, 차트에서 특정 위치를 선택하고 필터 실행시 결과 없음으로 나타남
>> 자동으로 설정되는 날짜필터가 해당 바그래프의 날짜로만 들어가서 문제가 되는것으로 보임

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 검색실행
2. "통합지표_Data_Global " 모델 선택
3. DSL실행
* | where  LOC_NAME='Comprehensive Index' | where DATA_TYPE = 'SCFI' OR DATA_TYPE='OIL' 
4. 출력된 차트에서 특정 위치 선택 후 "이범위로 실행" 실행

## 예상한 행동 ##
선택한 범위로 조회 결과가 나타나야함

## 스크린샷 ##
[검색]
![image](https://user-images.githubusercontent.com/4444717/63148122-2356b800-c03b-11e9-8b96-0845b4ba8300.png)

[검색결과]
![image](https://user-images.githubusercontent.com/4444717/63148143-2fdb1080-c03b-11e9-9fae-376f9decff80.png)

**Comment by seungfwani** [comment]
Angora에서는 시간 범위 조회를 다음과 같이 처리합니다.

- start_date는 `이상` 으로 처리, end_date는 `미만`으로 처리

캡처된 화면을 확인해 보면, timeline화면의 `이 범위로 검색`을 누르면
`2014/01/01 00:00:00 ~ 2014/01/01 00:00:00` 으로 범위를 검색합니다.

Angora는 1일 이상, 1일 미만 데이터를 필터 하기 때문에 데이터가 출력이 되지 않습니다.

기타 의견이 있다면 남겨주시기 바랍니다.

**Comment by JeongHeeDong** [comment]
해당 Data는 실제 2014/01/01 00:00:00 데이터가 아닙니다.  
상단 그래프 그릴때 월단위로 summary해서 보여주면서 해당 날짜로 보여지는 것으로 보입니다.
따라서 1분/1시간/1일/1달/1년 등으로 차트가 그룹핑 된다면, 실제 조회시에는 해당 기간이 모두 포함된 시간 조건이 들어가야 할 것으로 보입니다.

**Comment by seungfwani** [comment]
@veldise 
위의 이슈에 대해서 UI상의 차이점이 있어 질문드립니다.

아래의 사진 2개는 각각 `운영서버(192.168.100.180)` 와 `irisdev.valuelinku.com` 서버 입니다.

`운영서버`에서는 다음과 같이 검색을 하면 `년/월/일` 단위로 요약된 timeline 결과가 나오고,
timeline 중 하나의 결과에 마우스를 올리면 `년/월/일 ~ 년/월/일` 로 표시가 됩니다.

![스크린샷(4)](https://user-images.githubusercontent.com/46172579/64307078-e7769900-cfcf-11e9-965a-859795af565f.png)

하지만, `irisdev.valuelinku.com` 서버에서는 다음과 같이 검색하면 `년` 단위로 요약된 결과가 나오지만,
timeline 중 하나의 결과에 마우스를 올리면 `년/월/일 시:분 ~ 시:분` 으로 표시가 됩니다.
-> 이상황 이라면, `년 ~ 년` 으로 표시가 되야할 것 같다는 생각입니다.

![스크린샷(5)](https://user-images.githubusercontent.com/46172579/64307150-2dcbf800-cfd0-11e9-9dec-4c1efed5e38f.png)

위의 내용에 대해서 확인 해주시면 감사하겠습니다.

**Comment by veldise** [comment]
@seungfwani 
본 이슈에서 왜 이 질문을 하시는지 잘 모르겠는데, 사이트의 차이가 아니고 검색 조건의 차이입니다.
첫번째는 시간 범위를 직접 지정하였고, 두번째는 전체 시간으로 지정하였습니다.
시간 범위로 지정한 경우에는 정해진 규칙에 따라 단위(`unit`)를 설정하지만,
전체 시간의 경우에는 데이터가 어떻게 반환되는지 알 수 없으므로 단위를 시간(`hour`)로 고정하고 있습니다.

**Comment by seungfwani** [comment]
@veldise 
위의 질문은 제가 UI에서 `unit` 에 대한 처리 방식을 제대로 이해를 하지 못하여, 
정리되지 않은 질문을 하였습니다.
선임님께서 말씀 해주신 `전체시간일 경우 1시간 단위 처리` 에 대해서 이해 하였습니다.

설명해 주신 내용을 이해하였으며, 본 이슈와 연관이 된 부분이 있는 것 같아 다시 정리하여 말씀드리겠습니다.

- 문제
-> 전체 검색 결과의 1개의 막대를 클릭해서 지정검색을 했을 때, `unit` 단위가 1시간이어서, 1개의 막대에 해당하는 범위와 일치하지 않는 검색을 하고 있습니다. -- 이슈내용
-> 이에 대한 해결 방법을 찾고 있습니다. 의견 부탁드립니다.

- 해결방안, 2가지

1. 전체 검색시, 해당 모델의 date 포멧을 확인하여, 가장 작은 단위로 unit을 세팅하는 방법
-> 예) yyyy -> 1y, yyyymm -> 1m, yyyymmdd -> 1d, yyyymmdd ... -> 1H
2. model-timeline 결과에 angora에서는 `unit`을 반환하고, UI에서는 전체시간 검색 시, 이 `unit`을 기준으로 UI상에 표시하는 방법

**Comment by veldise** [comment]
@seungfwani 
Angora v1 에서는 전체 시간이 아닌 경우, 해결방안 2로 처리했었습니다.
date 포맷은 사용자가 데이터 모델의 시간 컬럼을 `DATE` or `TIMESTAMP` 유형의 컬럼으로 설정할 경우 포맷을 입력받지 않으므로 불가능할 것으로 생각됩니다.

**Comment by seungfwani** [comment]
@veldise 
`해결방안 1`은 처리 불가능 한 것을 이해했습니다.

본 이슈 해결을 위해서, 아래 내용이 가능한지 문의드립니다.

현재 UI `검색`에서 모델이름을 클릭할 때, `/angora/metadata` API를 사용하고 있습니다.
이 API는 `{"data": { "partition_num": 0 }}` 형식의 데이터를 응답 하고 있습니다.

추가의견:
`/angora/metadata` API의 결과로 아래와 같이 보낸다면, **전체 검색시** `model-timeline` 쿼리에 `unit` 값 추가가 가능한지 검토 요청드립니다.

```
{
    "data": {
        "partition_num": 0,
        "unit": "1d"
    }
}
```

**Comment by veldise** [comment]
@seungfwani 
네 가능합니다.

**Comment by seungfwani** [comment]
@veldise
그렇다면 위에 말씀드린 의견과 같이 `/angora/metadata` API의 결과로 `unit` 데이터를 응답하도록 적용토록 하겠습니다.
UI에서도 적용 해 주시면 감사하겠습니다.

**Comment by veldise** [comment]
@seungfwani 
갱신된 API 문서를 메일로 보내주세요.

**Comment by seungfwani** [comment]
@veldise 
앙고라 서버는 운영서버(192.168.100.180)에 
해당 내용을 적용하여 배포하였습니다.

**Comment by veldise** [comment]
@seungfwani 
아래와 같이 검색어 수행시 에러 발생합니다.

검색어:
```
model-timeline name = 'BATTING' model_owner = root unit = 1y
```
에러:
```json
{"message":"angora error: <class 'angora.exceptions.AngoraException'>\n[ unit ] must be used number + one of ['Y','m'','d'','H','M','S' ]"}
```

이전에 아래 문서 기준으로 연도(Year)는 `y`로 맞췄었는데 현재 상황은 어떤지 확인바랍니다.
https://github.com/mobigen/B-IRIS-Data-Discovery-Service/blob/master/docs/ko/restful/iris-timeline.md

**Comment by seungfwani** [comment]
@veldise 
현재 `model-timeline` 명령어를 사용하고 있고, 
기준 문서는 아래 링크로 확인됩니다.
https://github.com/mobigen/B-IRIS-Data-Discovery-Service/blob/master/docs/ko/commands/model-timeline.md

문서수정 날짜는 `2018/11/28` 이고, 
model-timeline 코드의 연관 부분의 수정일은 `2018/08/10` 입니다.

해당 기준이 코드에 반영되지 않은 것으로 보이며 수정하여 다음 배포시 적용하도록 하겠습니다.

추가적으로, `y` 외에 `d`, `m`, `H`, `M`, `S` 의 경우에는 정상적입니다.

**Comment by veldise** [comment]
@seungfwani 
그렇다면 metadata API가 잘못된 것 같습니다. 아래와 같이 요청시 `1y`를 반환합니다.
데이터 모델은 `BATTING`입니다.
```
GET /metadata?datamodel_id=e1012d00-365b-4b44-b193-705d5be9b35e&start_date=null&end_date=null
```
```json
{
  "data": {
    "unit": "1y", 
    "partition_num": 0
  }
}
```

**Comment by seungfwani** [comment]
@veldise 
model-timeline 시 `1y` 에 대한 오류는 수정하여 운영서버에 배포하였습니다.

기존에 약속된 기준인 `[y, m, d, H, M, S]` 로 동작하도록 `model-timeline` 명령어를 수정하였습니다.

추가적으로, `/angora/metadata` API 의 결과로 `1y`가 리턴되는 것은 의도한 바 입니다.

**Comment by veldise** [comment]
@seungfwani 
로컬 개발 환경에서 변경된 동작 확인했습니다. 별다른 사항이 없으면 차주 배포 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/65213890-defb8380-dae2-11e9-8757-dabdb01f1ebb.png)

**Comment by seungfwani** [comment]
현재 ValueLinkU 서버에서 `전체검색 후 범위 검색` 시 정상적으로 데이터를 가져오는 것을 확인하였습니다.

[결과]
![image](https://user-images.githubusercontent.com/46172579/65652473-e247bf80-e04c-11e9-9e4b-6f99aac9e582.png)

![image](https://user-images.githubusercontent.com/46172579/65652496-f1c70880-e04c-11e9-9569-a0aa6e89a760.png)
