### ISSUE TITLE
valueLinkU / 검색의 where조건 결과값이 일치 하지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1420]
## 버그 설명 ##
검색에서 where조건을 입력하고 조회시 결과값이 다르게 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 검색메뉴 실행
2. "통합지표_Data_Global" 선택
3. DSL실행
  * |  where DATA_TYPE = 'SCFI' OR DATA_TYPE='OIL' | where  LOC_NAME='Comprehensive Index' 

## 예상한 행동 ##
두번째 where조건에 의해 LOC_NAME이 Comprehensive Index 항목만 조회 될 것으로 예상

## 스크린샷 ##
[실행결과]
![image](https://user-images.githubusercontent.com/4444717/63148431-1dada200-c03c-11e9-80b9-d751477f78ed.png)

**Comment by seungfwani** [comment]
#1503  이슈와 같은 것으로 보입니다.

**Comment by seungfwani** [comment]
Spark-On-IRIS 수정 배포 후 확인결과,
Angora의 `model` 명령어는 정상적으로 동작하는 것을 확인 하였으나,
`model-timeline`, `model-stats`, `model-statsdetails` 명령어는 이상 동작을 하는 것으로 확인되었습니다.

위 내용을 확인 후 Angora 코드를 수정하였으며 배포 후 확인하도록 하겠습니다.

**Comment by seungfwani** [comment]
`model-timeline`, `model-stats`, `model-statsdetails` 명령어의 수정을
운영서버(192.168.100.180) 서버 반영 후 확인 하였습니다.

아래는 where 조건 필드에 대한 결과가 정상적인 것을 확인한 스크린샷입니다.
![image](https://user-images.githubusercontent.com/46172579/65560286-fd48ff80-df78-11e9-823f-6e5110968cac.png)

![image](https://user-images.githubusercontent.com/46172579/65560293-076afe00-df79-11e9-9260-5ad02f8158a1.png)

**Comment by seungfwani** [comment]
ValueLinkU 서버에 배포되어 정상 동작하는 것을 확인 했습니다.

[결과]
![image](https://user-images.githubusercontent.com/46172579/65577235-60a15480-dfae-11e9-8a10-115ef9918793.png)

![image](https://user-images.githubusercontent.com/46172579/65577207-541cfc00-dfae-11e9-885c-664ab4617a7d.png)
