### ISSUE TITLE
ValueLinkU / 피벗, 시각화 기능에서 필터 조건을 OR조건으로 줄수 있는 기능 필요

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1421]
## 기능 요청 ##
피벗 및 시각화 기능에서 필터 조건을 줄 수 있지만, 현재 AND조건으로만 가능 함
필터조건을 추가할때 AND 또는 OR조건을 선택 할 수 있는 기능 필요

## 원하는 솔루션 설명 ##
필터 조건을 OR조건으로도 할 수 있는 기능

[시각화의  필터기능]
![image](https://user-images.githubusercontent.com/4444717/63148956-aed14880-c03d-11e9-9223-4bd078286025.png)

[피벗의 필터기능]
![image](https://user-images.githubusercontent.com/4444717/63148988-c7d9f980-c03d-11e9-88b8-f9738fdabc58.png)

**Comment by veldise** [comment]
1. UI에서 입력한 필터값을 아래와 같은 json(array) 형태로만 angora 쪽에 전송하고 있고, `OR` 혹은 `AND`와 같은 연산자는 전송하고 있지 않은 상태입니다.
    `filters: ["HOST = 'gcs7'", "HOST = 'gcs5'"]`
2. 이 부분이 angora의 query-analaysis API 를 통해 변환이 되는데 `AND` 조건으로 변환됩니다.
    `FILTER HOST = 'gcs7' AND HOST = 'gcs5'`

따라서 다음과 같은 사항이 고려되거나 새로 개발되어야 합니다.

### Angora
1. query-analaysis API 에 연산자 옵션 추가
2. `pivot`, `adv` 명령어가 OR 연산자 지원하는지 검토

### UI
1. `OR` 연산자를 설정하는 UI 추가 (기획 필요)

**Comment by namjals** [comment]
@veldise 
아래 2가지에 대해 지원 가능합니다.
1. query-analaysis API 에 연산자 옵션 추가
    - ui - angora 간 인터페이스를 정하면 됩니다.
2. pivot, adv 명령어가 OR 연산자 지원하는지 검토
    - 지원합니다.
필터 조건이 A and B or C 인경우 순차적으로 연산을 진행하는데, A and (B or C)와 같이 `괄호`에 대한 지원을 해야할지 문의드립니다.

**Comment by veldise** [comment]
@sunghoon @pjh0347 @namjals 
정희동 팀장님께 문의 결과, 당장 필요한 기능은 아니라고 합니다.

**Comment by veldise** [comment]
확인 결과 `type=tree`, `type=string` 두 가지 옵션으로 serialize, parse 기능 둘 다 사용하고 있습니다.
- serialize(`type=string`): JSON -> DSL Commned
- parse(`type=tree`): DSL commend -> JSON

**Comment by sunghoon** [comment]
@veldise @namjals 아래 내용을 참고하여 진행하면 될 것 같습니다. 

- serialize(type=string): JSON -> DSL Commned
  - pivot / adv 전용화면에서 DSL 명령을 전송하기 전에 처리되는 과정에 적용되어 있음.
  - 이 부분을 처리하는 API는 추후 사라지게 할 예정
  - 화면에서 사용하려는 명령어 Command에 맞게 문자열을 생성해서 Angora에 전달하면 됨.

- parse(type=tree): DSL commend -> JSON
  - 검색화면에서 pivot / adv 전용화면으로 이동할때 화면에 파라메터 정보를 설정하기 위해 데이터를 획득하는 과정에 적용.
  - 이 부분을 처리하는 API는 정리하여 pivot / adv 전용 api가 아닌 다른 명령에서도 적용 가능한 common한 api로 재 정의 필요.
  - 각 명령어는 모두 parse 함수를 가지고 있으며, 해당 결과를 json으로 출력할 수 있도록 규격화.
  - 규격화가 되면 아마도 지금 현재 처리되고 있는 json과 내용이 다를 것으로 예상되고, 신규 규격을 참고하여 화면 기능 갱신 필요.

**Comment by namjals** [comment]
아래 2가지에 대해 지원하도록 수정되었고 다음주 중 배포 예정입니다.
1. query-analaysis API 에 연산자 옵션 추가
2. pivot, adv 명령어가 OR 연산자 지원하는지 검토

추가적으로 앙고라에는 연산자 우선 수행을 위한 괄호를 지원합니다.
ex) `FILTER HOST = 'gcs3' OR (HOST = 'gcs4' AND PRIORITY = 'notice')`

**Comment by veldise** [comment]
웹UI 는 다음과 같이 진행 예정입니다.
1. OR/AND 연산자 지원
2. 괄호 연산자 지원 (상세 기획 필요)

**Comment by seungfwani** [comment]
#1845 이슈와 동일하게 진행 중입니다.

**Comment by seungfwani** [comment]
현재 앙고라는 확인 완료되었습니다.
https://github.com/mobigen/IRIS-Discovery-Service/blob/master/docs/ko/restful/query-analysis-v2.md

**Comment by sunghoon** [comment]
@veldise 최종 진행 상황 및 진행하지 않고 있다면 진행 일정정보를 공유해 주세요.
