### ISSUE TITLE
데이터추가 / mariadb등 다양한 종류의 데이터 소스에 데이터가 추가 가능한 기능 필요

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1423]
## 기능 요청 ##
데이터 추가 메뉴를 이용하여 데이터를 추가시 데이터 유형이
IRIS-DB, HDFS 이외에

mariadb등 DSMS에서 제공중인 데이터 소스에도 추가가 가능하도록 하는 기능 필요

**Comment by sunghoon** [comment]
외부 요청 사항이 있으면 상황에 맞춰서 제공하도록 하겠습니다.
