### ISSUE TITLE
IRIS-WEB의 첫 페이지 설정

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1424]
## 기능 요청 ##
IRIS-WEB의 첫페이지에 나오는 보고서가 사용자 혹은 그룹 별로 다른 보고서를 볼수 있도록 지정

## 원하는 솔루션 설명 ##
IRIS-WEB을 처음 들어갈 경우 보여지는 보고서의 경우 사용자 별로 관리자가 지정 한 보고서가 보여 졌으면 좋을것 같음

## 고려한 다른 대안 ##
사용자/그룹별로 보여지는 첫페이지를 설정할 수 있으면 좋을것 같음.
(해당 기능을 이용해서 사용자별로 첫 페이지를 지정할 경우 특정 보고서를 지정할수 있을것 같기 때문에)

관리자가 보고서를 만들고, 사용자가 보기만 하는 요구사항이 발생하고 있음.

**Comment by rhcpn** [comment]
해당 기능은 IWP로 구현 되었기에 close 합니다.
