### ISSUE TITLE
API.M6 in Python3

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1425]
## 기능 요청 ##
Python3로 돌아가는 API.M6 라이브러리.

## 원하는 솔루션 설명 ##
기계학습 라이브러리들이 다들 Python 3대 코드들인데, IRIS 테이블을 읽어서 중간 과정 없이 바로 기계학습 적용 기능을 수행해서 테이블 특정 필드에 바로 업데이트 해서 넣고 싶은데... 그게 잘 안되네요.

## 고려한 다른 대안 ##
2.7로 만들어진 IRIS커넥터로 데이터 읽어내서 CSV저장하고, Python3로 만들어진 코드로 CSV만들고, 다시 2.7커넥터로 로딩하기.

## 기타 ##
영향 범위가 적은 것부터 하나씩 Python3로 넘어가야 하지 않을까요?
Python3.7에서는 성능도 꽤 좋아졌다는 소식도 있던데.

**Comment by anhm** [comment]
- 2019년 하반기부터는 연구소 내에서는 시작되는 프로젝트의 python 버전은 python3.6을 기본으로 하고 있습니다.
- IRIS API는 현재 python3.6을 제공하고 있습니다.(현재 여러 경로를 통해 API를 제공하고 있으며, 홈페이지 개선을 통해 링크를 제공해 드릴 예정입니다.)
    - https://github.com/mobigen/mobigen.github.io/raw/master/dist/IRIS_API_2.1_PYTHON3.6.zip
