### ISSUE TITLE
보고서 파이차트 사용 시 '실행중...' 문구가 계속 출력됩니다

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#1426]
## 버그 설명 ##
DSMS 사용 보고서에서 꺾은선차트는 데이터가 없을 시에도 데이터가 없는 화면이 나오지만 파이차트는 '실행중...'이라는 메시지가 계속 출력됩니다. 

## 재현하는 방법 ##
1. IRIS 접속 후 보고서로 이동
2. 보고서 중 'CI/CD-detail-파이차트이상' 선택
3. 좌측 프로젝트 리스트에서 'B-IRIS-E2E' 선택

## 예상한 행동 ##
꺾은선 차트와 마찬가지로 파이차트 영역에 공백(또는 데이터없음) 표시

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/63237507-4cff2180-c27d-11e9-83a1-e49130a72e3c.png)

**Comment by veldise** [comment]
DSMS 유형으로 구성시, 결과가 없을 경우 발생하는 문제로 확인되었습니다.
금주내로 수정하겠습니다.

**Comment by veldise** [comment]
데모 운영서버에 패치 및 해결되어 닫습니다.
