### ISSUE TITLE
ValueLinkU / 보고서의 URL복사 기능 오류

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1427]
## 버그 설명 ##
보고서리스트에서 URL생성후 별도의 브라우져에서 실행하면 오류가 발생함
(본사 개발 서버/192.168.100.180 에서는 정상 동작함)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://irisdev.valuelinku.com/#/ 접속
2. "보고서" 메뉴 실행
3. URL복사 기능 실행
4. 복사된 URL을 다른 브라우져에서 실행

## 예상한 행동 ##
정상적으로 화면 출력

## 스크린샷 ##
[URL 복사]
![image](https://user-images.githubusercontent.com/4444717/63312190-a6c62100-c33b-11e9-823d-3762dcd9411b.png)

[URL 실행]
![image](https://user-images.githubusercontent.com/4444717/63312166-94e47e00-c33b-11e9-81d8-5e22f0c4b3d0.png)

**Comment by swish1995** [comment]
### 확인내용 - 서버 로그 참조
* export url 의 리포트 호출시 brick 주소 확인 - http://172.17.0.15:8080
* 해당 주소로 보고서 데이타 호출
   ```
   http://172.17.0.15:8080/studio/report/33b9bb60-7287-48de-877f-8f6734ebb896
   ```
* brick 에서 별도의에러 없이 html 페이지 반환 
![brick.html](https://user-images.githubusercontent.com/49141403/63482328-75805900-c4d3-11e9-8daa-e20f0ebec23a.png)

* studio preview 페이지에서 해당 보고서 데이터 에러로 판단하여 에러 메세지 표시 시도 
* 에러에 해당되는 messages 값이 없어 위에 표시된 오류 발생 

### 현재 테스트 내용
* brick 의 주소가 아닌 request 의 protocol, hostname, hostport 를 이용하여 호출하도록 수정
* 개인 서버 기준으로 이상없이 동작하는지 확인함

### 추가 확인 요청 사항
* 위의 요청한 방식 또는 다른 방식으로 해결해야 하는지 확인
* brick 호출까지는 되는데 studio 로 해당 리포트를 요청하지 않는 이유
* 비슷한 방식으로 사용하는 ServiceInfo 유틸은 정상적인것으로 보이는데 차이점

**Comment by veldise** [comment]
위에 정리해준 내용과, b-iris.mobigen.com 에서는 정상 동작하는 것을 볼 때
서버 설치 환경이 기존 환경과 달라서 발생하는 문제로 추측됩니다.

**Comment by veldise** [comment]
brick 서비스의 `auth_except_list` 설정을 아래와 같이 수정하여 정상 동작하는 것을 확인했습니다.

기존:
```json
"auth_except_list": ["studio/exported", "studio/direct", "studio/views", "static", "api", "css", "images", "js", "dist", "lib"],
```
변경:
```json
"auth_except_list": ["studio", "static", "api", "css", "images", "js", "dist", "lib"],
```

**Comment by veldise** [comment]
http://irisdev.valuelinku.com/#/ 에서 동작 확인하여 닫습니다.
