### ISSUE TITLE
ValueLinkU / Studio / 시간 콤포넌트 표시 이슈

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1428]
## 버그 설명 ##
보고서 생성 후 저장한 화면에서 시간 콤포넌트의 배경이 흰색으로 나타남
(매우 자주 발생하는 현상임)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 생성에서 시간콤포넌트 추가
2. 보고서 저장
3. 보기 실행

## 예상한 행동 ##
배경에 흰색이 아닌 투명한 모습으로 출력

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/63322823-4d6fe900-c35f-11e9-9672-340887768cbe.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@JeongHeeDong 
혹시 편집 화면에서만 발생하는 문제인지 확인 부탁드립니다.

**Comment by JeongHeeDong** [comment]
편집 화면 과 실재 실행 화면 모두 발생 합니다.

**Comment by onlyeon** [comment]
윈도우의 IE, chrome, firefox에서 테스트 했을 때 위 현상이 발생하지 않았습니다. 
다만, 실행 화면에서는 해당 스타일이 보이지 않도록 CSS를 수정했습니다.
