### ISSUE TITLE
치안연, 글로벌 테이블 생성 오류

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1429]
## 버그 설명 ##
참조성 글로벌 테이블을 정의하려고 해도 안 되네요.

## 재현하는 방법 ##
동작을 재현하는 방법 : 스크린샷 참조

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
@kim3163

**Comment by sunghoon** [comment]
오래된 이슈로, 해결 된 것으로 보고 닫습니다.
