### ISSUE TITLE
연결정보 오류

### ISSUE THREAD

**Issue by jhnam2513** [mobigen/IRIS-BigData-Platform#1431]
## 버그 설명 ##
새모델 >> 연결정보 >> IRIS >> IRIS connector 연결 실패

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/22606205/63486281-d3b43880-c4e1-11e9-8f2f-aa26d741a117.png)

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }
![image](https://user-images.githubusercontent.com/22606205/63486317-00685000-c4e2-11e9-9689-a3c3e9951f7d.png)

연결정보에서 IRIS를 선택하면 위와 같은 3개의 선택메뉴가 나오는데 각 항목에 대한 차이를 잘 모르겠습니다. 부연 설명이 필요해 보입니다. 

![image](https://user-images.githubusercontent.com/22606205/63486566-0ca0dd00-c4e3-11e9-86e3-37400b34cd91.png)

그 외 연결정보 항목에서 MARIA DB를 제외하고는 선택할 수 있는 데이터가 없네요

**Comment by sunghoon** [comment]
오래된 이슈로 비슷한 상황이 재발하면 새 이슈로 처리하겠습니다.
