### ISSUE TITLE
Angora / HDFS 대상의 데이터 모델 검색시 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1432]
## 버그 설명 ##
- 위치: b-iris.mobigen.com
HDFS 대상의 데이터 모델에 대하여 검색시 에러가 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. b-iris.mobigen.com 접속
2. `WEATHER`, `BATTING` 등의 데이터 모델 선택
3. 시간 범위: `전체 시간`으로 설정
4. 검색 수행
5. 에러

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/63490244-2fd18980-c4ef-11e9-8e0e-69559510897e.png)

**Comment by seungfwani** [comment]
@veldise 
지난주 배포에서 타 이슈(#1330) 처리를 위해 angora 설정 값을 추가한 것이 있는데 그 설정값이 영향을 주어 발생한 에러입니다.

현재 운영서버는 해당 설정값을 삭제 하였고, 위 에러는 발생하지 않습니다.
연관된 이슈에 대한 내용은 다른 방법으로 해결하도록 하겠습니다.
