### ISSUE TITLE
치안연,  검색화면 LIKE 연산자 두개 사용 오류

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1434]
## 버그 설명 ##
검색 화면에서 LIKE 연산자를 두 개 연달아 쓸 수가 없네요.

## 재현하는 방법 ##
동작을 재현하는 방법 : 화면 캡처 참조

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3444816/63562975-6e704e00-c59a-11e9-831f-14912c479697.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by nomota** [comment]
원래 하고 싶은 것은, 2개 이상의 키워드를 이용해서 검색하고 싶은 것입니다.
"* TEXT LIKE '%수사권%' OR TEXT LIKE '%조정%'" 이런 쿼리가 의도하는 바입니다.

* TEXT LIKE '%수사권%' CAT1='POL' 
이런 식으로 LIKE를 하나만 쓰는 것은 됩니다.

그리고 FTS4 로 색인된 테이블이라서, LIKE 연산자 말고 MATCH  연산자를 쓰고 싶은데, MATCH 연산자는 DB 브라우저에서는 되는데, 여기 검색 화면에서는 안 됩니다.

일단 당분간은 이거 안되는 거 알고 고객에게 제한적으로 써 달라고 요청하겠습니다.

**Comment by pjh0347** [comment]
angora 에 버그가 있어서 위 현상이 발생하고 있습니다.

가능하다면, `* | sql  "select * from angora where HOST like '%gcs1%' or HOST like '%gcs2%'"` 와 같이 sql 명령어를 이용하여 우회하여 사용이 가능합니다.

위 버그는 향후 개선 하도록 하겠습니다.

**Comment by sunghoon** [comment]
이야기 하신 방법으로 지금 해 보니 아래 이미지와 같은 현상이 있습니다. 
![스크린샷 2019-08-23 오후 4 25 59](https://user-images.githubusercontent.com/512653/63574451-c3c05580-c5c2-11e9-90f7-387cd669157e.png)

**Comment by namjals** [comment]
검색 화면에서 LIKE 연산자를 두 개 연달아 쓰지 못했던건, model-timeline의 파싱 문제입니다. 
해당문제는 차주 목요일에 배포요청 예정입니다.
아래의 쿼리의 경우, sql 명령어의 where문 컨텍스트가 model-stats나 model-statsdetail 명령어에 반영되지 않아서 입니다. 해당 부분 수정은 시일이 필요해보입니다.
`* | sql "select * from angora where HOST like '%gcs1%' or HOST like '%gcs2%'"`
