### ISSUE TITLE
치안연 검색화면 좌측 필드 통계/분포 보기 오류

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1435]
## 버그 설명 ##
필드별 분포를 보는 기능이 동작하지 않고 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 : 화면 캡처 참고

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3444816/63563474-323ded00-c59c-11e9-9624-47f1fb3d9c2c.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
치안연에 3주전 앙고라가 설치되어있는데, 해당 오류는 8월 19일 이후 버전부터 발생하지 않습니다. 차주 목요일에 운영기술팀에 배포 요청하겠습니다.

**Comment by namjals** [comment]
수정된 버전이 치안연에 배포되었습니다.
![image](https://user-images.githubusercontent.com/22319132/64393210-4ea55380-d08b-11e9-8f61-2fd6974965e2.png)
