### ISSUE TITLE
문의: 검색 화면에서, 건수 추이 그래프 나오게 하는 법

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1436]
## 문의 설명 ##

치안연에서 신문기사 로딩이 되어 있는 상태입니다.
YYYYMMDD 스타일의 날짜로 구분되어 있는 상태인데, 검색 화면의 첫 화면에서 건수 추이 그래프가 나오게 하려면 어떻게 해야 할까요?

## 재현하는 방법 ##
동작을 재현하는 방법 : 치안연 검색 화면

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##

없이도 검색이 가능하기는 합니다만...

**Comment by sunghoon** [comment]
오래된 이슈로 비슷한 상황이 재발하면 새 이슈로 처리하겠습니다. 
치안연 프로젝트를 진행하면서 해결된 것으로 보입니다.
