### ISSUE TITLE
[SmartIDC] IRIS-WEB DB브라우저 결과값 중복 현상

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1437]
## 버그 설명 ##
IRIS-WEB DB브라우저에서 특정 쿼리 조회시 실행 결과값에 중복 데이터 출력 발생합니다.

## 재현하는 방법 ##
1. IRIS-WEB DB브라우저에서 특정 쿼리 실행합니다.
2. 실행 결과값(레코드 수)이 114개가 나오면 이중 하단의 14개는 중복되어 나옵니다.

## 예상한 행동 ##
실행 결과 레코드 수는 100개로 제한되어 있으며 100개가 넘는 값에 대해서는 처음 데이터 값을 읽어들여 총 레코드를 맞추는거 같습니다.

## 스크린샷 ##
1. DB브라우저에서 특정 쿼리 실행
![image](https://user-images.githubusercontent.com/25650544/63671975-da151e00-c81b-11e9-975f-9041e79ee657.png)

2. 실행 결과값 하단에서 중복 데이터 발생합니다.
![image](https://user-images.githubusercontent.com/25650544/63672047-02048180-c81c-11e9-9301-9f291a1e14af.png)

## 로그 ##
IRIS-WEB 버전 정보
![image](https://user-images.githubusercontent.com/25650544/63672479-febdc580-c81c-11e9-9989-da4f2cadbacb.png)

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
버전 확인 결과 아래 이슈와 동일한 문제로 추측됩니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/1204#issuecomment-452132479

**Comment by big-mobigen** [comment]
해당 이슈와 관련해서 배포 파일 준비 및 배포 가능한 일정에 대해 문의드립니다.

**Comment by veldise** [comment]
@big-mobigen 
이전에 해결된 이슈지만 테스트 환경 구축에 시간이 좀 걸립니다. 차주중에는 가능할 것으로 생각됩니다.

**Comment by big-mobigen** [comment]
해당 이슈에 대한 배포 파일이 준비되었는지 문의드립니다.

**Comment by veldise** [comment]
@big-mobigen 
죄송합니다. ValueLinkU 이슈 처리로 인해 진행하지 못했습니다.
금주(~금)에는 배포 파일을 전달해드리겠습니다.

**Comment by veldise** [comment]
@big-mobigen 
권영길 팀장님, 배포 결과 공유 부탁드립니다.

**Comment by big-mobigen** [comment]
db-browser-dist-v0.1.2_9187a6a-20191024.tar.gz 배포로 이슈 해결되었습니다.
