### ISSUE TITLE
통계입력시 지도가 나오는경우

### ISSUE THREAD

**Issue by jhnam2513** [mobigen/IRIS-BigData-Platform#1438]
## 버그 설명 ##

지도와 상관없는 데이터로 통계입력시 시각화메뉴에서 지도가 나오는경우

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/22606205/63733674-3fb4e900-c8b4-11e9-894b-737b56abcb93.png)

![image](https://user-images.githubusercontent.com/22606205/63733693-5b1ff400-c8b4-11e9-845e-6c745fe31e6e.png)

## 기타의견 ##

어떤 데이터를 사용하던 디폴트로 지도를 보여주는 것인가요? 차후 혼란이 생길 수 있을거 같아서 "이슈리포트"를 드립니다.

**Comment by veldise** [comment]
@jhnam2513 
`geomap`, `geostats` 와 같은 명령어를 사용시에만 차트 유형을 지도형으로 설정해줍니다.
`stats` 명령어 사용시에는 꺾은선형이 기본이며, 현재 같은 데이터 같은 쿼리로 현상이 재현되지 않습니다.
