### ISSUE TITLE
데이터 브라우저 > 시각화 > 클러스터 맵 분석 오류

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1439]
## 버그 설명 ##
데이터 브라우저 > 시각화 > 클러스터 맵 분석 오류

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 테이블 생성 및 데이터 모델 생성
2. 1번과정 생량 시 "jphong.CONSTRUCTION_EXAMPLE_20190826_2" 테이블 사용
3. 클러스터 맵 분석 사용 시 반응 없음. 

## 예상한 행동 ##
클러스터 맵 분석 결과 

## 스크린샷 ##
![biris_map_시각화테스트](https://user-images.githubusercontent.com/8993205/63736533-57916a80-c8be-11e9-9ef2-30fb89cbfcc2.JPG)

## 로그 ##
스크린샷으로 대체

## 기타 ##
클러스터 맵 분석을 위해선 컬럼에 수/개수 와 같은 데이터가 반드시 필요한 것 같습니다.
다만, 수/개수와 같은 데이터가 없는 경우에는 임의로 데이터를 '1'로 생성하여 분석을 했는데
이러한 과정없이 분석단에서 row마다 수치를 1로 할 수 있는 기능이 있으면 좋겠습니다.

**Comment by readmehong** [comment]
금일 오전 - 20190827에 해당 분석 실행했습니다.

**Comment by veldise** [comment]
* POST request body:
```json
{
    "q": "model name = '공사데이터_분석_예시' model_owner = jphong | geostats LATITUDE LONGITUDE sum(CON_CNT) by CONSTRUCT_TYPE",
    "save": true
}
```
* GET response:
```json
{"message":"angora error: <class 'pyspark.sql.utils.AnalysisException'>\nCannot resolve column name \"LONGITUDE\" among (latitude, longitude, cluster_id, CONSTRUCT_TYPE, CON_CNT);"}
```

**Comment by namjals** [comment]
geostat 명령어 이슈로 아래 링크와 같이 해결된 상태입니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/1321
![image](https://user-images.githubusercontent.com/22319132/64302151-fe5fc000-cfbc-11e9-8e2a-04688136717b.png)
