### ISSUE TITLE
HDFS브라우저-> 일반계정 파일 업로드시 반응없음

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1440]
## 버그 설명 ##
일반계정을 생성하여 hdfs 브라우저 메뉴에서 파일 업로드시 done 문구를 확인하였으나 
실제로 디렉토리에 저장되지 않습니다. 

root계정에서는 정상 작동하고있습니다. 

## 재현하는 방법 ##

![image](https://user-images.githubusercontent.com/25650544/63740778-62073080-c8cd-11e9-9019-b8f9a47d7cbf.png)

![image](https://user-images.githubusercontent.com/25650544/63740782-64698a80-c8cd-11e9-9c7f-1e1ad999f3ca.png)

**Comment by veldise** [comment]
@big-mobigen 
HDFS 용량을 확인하려면 어떻게 해야 하나요?

**Comment by veldise** [comment]
@big-mobigen 
혹시 최근에 변경된 HDFS 설정이 있나요?

**Comment by big-mobigen** [comment]
@veldise 
최근에 hadoop config 은 변경된게 없어 보입니다. 
hdfs 도커 이미지를 설치및 배포간에 설정/구성을 변경한건 없습니다.

hdfs 용량은 hadoop 실행되는 root계정에서
hdfs dfsadmin -report 명령어로 확인가능합니다.

**Comment by hiy2259** [comment]
root계정에서는 정상 작동하나 사용자 계정으로 업로드 했을 때 동작을 안한다면 Permission 또는 소유자 문제일 수도 있는데 현재 확인한 바로는 이부분에 대해서는 문제가 없습니다.

예측으로는 저의 UI 코드 에러가 아닌 webHdfs 에러 이거나 hadoop 자체의 문제가 발생한거 같습니다.

파일을 업로드 하고 업로드가 성공했을 경우 바로 아래와 같이 set  owner를 이용해 권한을 변경하는 부분이 있습니다.

set owner를 실행 했을때 이미 업로드가 성공한 상태이고 이를 실행시 아래와 같이 set owner가 성공한 부분에서 java.io.FileNotFoundException 에러 코드가 찍힙니다.

파일 업로드 success 되었다고 하는데 파일이 없는 결과가 찍힙니다.
```
// set owner
2019-09-03 11:10:14.654 +0900 - info: PUT: setOwner option =  {"url":"http://192.168.100.180:50070/webhdfs/v1/B-IRIS/USERS/yongs/IRIS_bigdata_platform.pptx","method":"PUT","qs":{"user.name":"root","owner":"yongs","group":"yongs","op":"SETOWNER"}}
// set owner success 
3|hdfs-bro | 2019-09-03 11:10:14.664 +0900 - info: set owner body =  exception=FileNotFoundException, javaClassName=java.io.FileNotFoundException, message=Directory/File does not exist /B-IRIS/USERS/yongs/IRIS_bigdata_platform.pptx
```
현재 내부 webHdfs에서 어떻게 동작하는 확인이 불가능 합니다.

헌데 아래 사이트에 접속해 보니 2가지 문제가 있었습니다.

[http://192.168.100.180:50070/](http://192.168.100.180:50070/) 에 접속하셔서 일단 아래 문제들을 일단 해결하고 실행해 봐야 할 거 같습니다.

* missing blocks
![스크린샷 2019-09-03 오후 12 53 28](https://user-images.githubusercontent.com/5515493/64143314-64780600-ce4a-11e9-8b15-2a7760763bc7.png)

* Permission denied: user=dr.who, access=READ_EXECUTE, inode="/":root:supergroup:drwxr-x---
![스크린샷 2019-09-03 오후 12 53 55](https://user-images.githubusercontent.com/5515493/64143335-85d8f200-ce4a-11e9-835a-baf41eb3806b.png)

원래 나오던 브라우저도 나오지 않습니다.

**Comment by veldise** [comment]
@big-mobigen 
위 코멘트에 대해 의견 부탁드립니다.

**Comment by seoryjj** [comment]
권한 문제 인 것 같습니다. ( 일반계정으로 업로드 성공한 파일을 읽지 못합니다.)

  * myiris 계정으로  HDFS브라우저로 파일 업로드 하면 성공됩니다.
<img width="1054" alt="스크린샷 2019-09-04 오전 9 02 27" src="https://user-images.githubusercontent.com/5126497/64216310-503c1380-cef3-11e9-9717-8595e8fc581a.png">

  * 같은 계정으로 R-studio에서 파일을 읽으려고 하면 이런 permission 에러가 발생합니다.
<img width="804" alt="스크린샷 2019-09-04 오전 9 05 18" src="https://user-images.githubusercontent.com/5126497/64216340-7bbefe00-cef3-11e9-9199-ca0d64230c62.png">

  * 상위의 B-IRIS/USERS 디렉토리 권한을 확인해보니 이렇습니다.
<img width="824" alt="스크린샷 2019-09-04 오전 9 03 14" src="https://user-images.githubusercontent.com/5126497/64216377-92fdeb80-cef3-11e9-886f-e60d96528053.png">

**Comment by veldise** [comment]
@seoryjj 
이슈 본문 내용에 대해서는,
hdfs-browser 서비스에서 HDFS에 write 관련 동작을 수행할 때, 설정 파일에 따라 hadoop super user로 수행하고 있습니다.
또한 webhdfs API가 반환하는 에러가 FileNotFound 이므로 권한과는 다른 문제로 생각됩니다.
참고로 USERS 폴더는 root:root 권한이 맞고, USERS 폴더 하위의 사용자별 폴더가 <user>:<group> 권한인게 정상입니다.

코멘트에 적어주신, R에서 파일을 읽을 때 Permission denied 에러가 발생하는 것은 아마 user/group 등의 설정이 없어서 그런게 아닐까 합니다.
webhdfs API의 경우 다음과 같이 요청합니다.
```
http://127.0.0.1:50070/webhdfs/v1/?op=CHECKACCESS&fsaction=r-x&user.name=hadoop
```

**Comment by seungfwani** [comment]
본 이슈 해결 방법에 대한 의견을 공유해 드리겠습니다.

이슈 원인:
일반 사용자가 hdfs에 파일을 업로드 할 때, `permission denied` 에러 발생

`permission denied` 관련 로그(192.168.100.180 서버 hdfs namenode log 중 일부):
`2019-08-27 13:17:18,947 INFO org.apache.hadoop.ipc.Server: IPC Server handler 5 on 9090, call org.apache.hadoop.hdfs.protocol.ClientProtocol.create from 192.168.100.173:58516 Call#2196190 Retry#0: org.apache.hadoop.security.AccessControlException: Permission denied: user=hdfs_test, access=EXECUTE, inode="/B-IRIS/USERS/hdfs_test/test2.csv":root:supergroup:drwxr-x---`

`permission denied` 원인:
원인 - `hdfs_test` 사용자가 `/B-IRIS/USERS/hdfs_test/test2.csv` 파일을 `EXECUTE` 하려고 하는데 권한이 없음

`hdfs_test` 사용자가 파일을 write 하려는 경로 상 디렉토리들의 권한:
`/` 디렉토리 권한 : `drwxr-x---`  --> `hdfs_test` 사용자는 접근불가
`/B-IRIS` 디렉토리 권한 : `drwxr-xr-x`  --> `/` 디렉토리 권한이 `755`라면 --> `hdfs_test` 사용자 접근 가능
`/B-IRIS/USERS` 디렉토리 권한 : `drwxr-x---`  --> `hdfs_test` 사용자는 접근불가
`/B-IRIS/USERS/hdfs_test` 디렉토리 권한 : `drwxr-x---`


위의 디렉토리 권한으로 인해서 일반 사용자가 파일을 쓸 수 없는 것으로 보입니다.
`/` 와 `/B-IRIS/USERS` 폴더의 권한을 `755`로 바꾸면 본 이슈내용을 해결 할 수 있을 것으로 보입니다.


참고 문장 및 URL:
문장 : `All operations require traversal access. Traversal access demands the EXECUTE permission on all existing components of the path, except for the final path component. For example, for any operation accessing /foo/bar/baz, the caller must have EXECUTE permission on /, /foo and /foo/bar.`
URL : https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsPermissionsGuide.html

**Comment by seungfwani** [comment]
운영 팀과 협의 하에 `/` 경로의 퍼미션을 `755`로 변경하였습니다.
![image](https://user-images.githubusercontent.com/46172579/65734787-990c7400-e10f-11e9-95db-1b8f2dedbae5.png)

**Comment by big-mobigen** [comment]
일반계정에서도 정상적으로 파일 업로드됨을 확인하였습니다. 

감사합니다.

**Comment by anhm** [comment]
해당 기능 정상 동작 확인 완료 했습니다.
또한 권한이 잘못 생성되어 있던 데이터들에 대해서 권한을 직접 할당하여 정상화 시켜 두었습니다.
