### ISSUE TITLE
DB 브라우저, 디폴트 SELECT문, MLIMIT 및 디폴트 파티션

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1441]
## 기능 요청 ##
DB브라우저에서 로컬 테이블을 더블클릭하면, SELECT 문이 자동으로 하나 들어가게 되어 있습니다.
훌륭한 기능입니다만, 한가지를 더하면 더 좋은 기능이 될 것 같습니다.

## 원하는 솔루션 설명 ##
사용자들의 첫번째 요구는 간단하게 해당 테이블에 무슨 데이터가 들어 있는지 보고 싶을 뿐입니다.
그냥 디폴트 액션으로 데이터 자체를 보여주게 하려면, 두가지 작업을 필요로 합니다.

(1) MLIMIT 가 무조건 붙어 있어야 할 것 같습니다. 그러면, 데이터 양이 항상 일정량으로 정해지기 때문에, 좀더 시스템 부하와 실수를 줄일 수 있을 것 같습니다.

(2) MLIMIT 들어가도 파티션 범위가 맞지 않으면, 데이터 없는 휑뎅그러한 화면 보입니다. 데이터 범위가 실제 데이터가 있는 범위이어야 답이 나올 테니, 파티셔닝의 값의 범위를, 기존 테이블의 마지막 데이터에 상대적으로 정해주면 좋겠습니다.

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
(2) 자동 생성되는 SQL의 파티션 시간을 데이터의 마지막 시간으로 하는 것은 불가능한 것으로 알고 있습니다.

**Comment by sunghoon** [comment]
오래된 이슈로 비슷한 상황이 재발하면 새 이슈로 처리하겠습니다.
