### ISSUE TITLE
[검색] 화면에서 이벤트 막대그래프를 클릭후 "이범위로 검색" 시 시간범위 설정 오류

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1442]
## 버그 설명 ##
[검색] 화면에서 이벤트 막대그래프를 클릭후 "이범위로 검색" 시 시간범위 설정 오류

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
* 검색 화면에서 막대 그래프 지정후 재검색 : 09:00 ~ 10:00 
<img width="727" alt="스크린샷 2019-08-29 오전 11 11 34" src="https://user-images.githubusercontent.com/5126497/63905010-cea93900-ca4d-11e9-834d-56bf9fc6284c.png">

* 시간이 09:00 ~ 09:00으로 지정되어 데이터 안나옴
<img width="632" alt="스크린샷 2019-08-29 오전 11 13 03" src="https://user-images.githubusercontent.com/5126497/63905071-fe584100-ca4d-11e9-9d33-a9772b9019ff.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
이건 web 의 문제가 아닌 것 같습니다.

DB 브라우저에서 sql 로 쿼리를 해보니 partition 구분 컬럼인 RECEIVE_TIME의 날짜는 2019-05-21 인데, IRIS 테이블에는 20180101000000  파티션 1개에 데이터가 전부 들어가 있네요. 

 **데이터추가** 메뉴에서 수동으로  날짜컬럼을 YYYYMMDDhhmmss 로 변환해서 새 테이블로 생성, 로드해도 전부  20180101000000 파티션으로 인서트됩니다.

<img width="547" alt="스크린샷 2019-08-29 오후 2 43 33" src="https://user-images.githubusercontent.com/5126497/63914294-adf0db80-ca6d-11e9-9031-5e7261fdecd4.png">

**Comment by veldise** [comment]
@seoryjj 
괜찮으시면 "데이터 추가" 기능에 문제가 있다고 생각되는 부분은 별도 이슈로 올려주실 수 있으신가요?

일단 본문과 같이 09시~10시 막대를 선택하였는데 시간 범위가 09시~09시로 설정되는 것은
웹에서 해결해야 할 문제가 맞아서 그렇습니다.

**Comment by veldise** [comment]
UI 문제는 unit가 시간(h) 단위일때만 발생하는 것으로 보입니다.
