### ISSUE TITLE
[데이터추가] 날짜 컬럼 값변환 안된채로 로딩

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1443]
## 버그 설명 ##
**데이터추가** 에서 값변환(yyyymmddhhmmss) 한 컬럼이 원래 값(yyyy-mm-dd hh:mm:ss) 형태로 로딩되어 있음.
이 컬럼이 파티션구분일 컬럼인데, 실제 파티션 날짜는 전부 2018010100000 으로 설정되어 입력됨

* 데이터 추가에서 RECEIVE_TIME 컬럼을 yyyy-mm-dd hh:mm:ss  에서 yyyymmddhhmmss 로 값변환함
<img width="1123" alt="스크린샷 2019-08-29 오후 2 46 52" src="https://user-images.githubusercontent.com/5126497/63921744-57d86400-ca7e-11e9-90db-795b322aaf59.png">

* 로딩할 때는 2018010100000  파티션으로 로딩됨
<img width="1078" alt="스크린샷 2019-08-29 오후 2 47 24" src="https://user-images.githubusercontent.com/5126497/63921860-86563f00-ca7e-11e9-9a26-217c45bbc149.png">

<img width="547" alt="스크린샷 2019-08-29 오후 2 43 33" src="https://user-images.githubusercontent.com/5126497/63921868-8a825c80-ca7e-11e9-97ce-697d438da1dc.png">

* DB select 결과
<img width="910" alt="스크린샷 2019-08-29 오후 2 45 46" src="https://user-images.githubusercontent.com/5126497/63921694-3ecfb300-ca7e-11e9-9fcd-d650d5ee2728.png">

**Comment by sunghoon** [comment]
오래된 이슈로 비슷한 상황이 재발하면 새 이슈로 처리하겠습니다.
