### ISSUE TITLE
ValueLinkU / 보고서 / 콤보&Input박스의 값이 없이 조회 하는 경우 오류 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1444]
## 버그 설명 ##
콤보 또는 Input박스의 값이 없는 경우 조회 오류 발생

일반적으로 해당 필터 조건을 사용 할때는 값이 없는 경우 전체 조회가 되는 것이 일반적임
(콤보의 경우 "전체"와같은 키워드를 두고 조회 하는 경우가 많음)

보고서 생성에서 콤보 또는 Input박스를 추가하고 해당 값이 특정값이 아닌 전체에 대해 조회 하고자 하는 경우 어떻게 해야 하는지요?

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 생성 시작
2. 콤보 또는 Input박스 추가
3. 각각에 해당하는 변수 설정
4. 차트 출력물에 대한 변수 적용
5. 조회 실행

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/4444717/63994812-e5748c00-cb30-11e9-8d6f-73ae7b8f8ed6.png)

**Comment by veldise** [comment]
아래와 같은 조건문이 처리 가능하도록 템플릿 엔진을 검색어 입력란에 적용하는 방안을 검토중입니다.
```
* | where 1=1
    if (cqi_1) { OR CQI=${cqi_1} }
    if (cqi_2) { OR CQI=${cqi_2} }
```

**Comment by veldise** [comment]
### if 문 쿼리 예제 
* 데이터 모델
```
    * | where 1=1
    {% if input_1 %}
        and name = '${input_1}'
    {% else %}
        and classification in ('${list_1}', '${list_2}')
    {% endif %}
```
* SQL
```
    select 
    '${list_1}' as list_1,
    '${list_2}' as list_2,
    {% if input_1 %}
        '${input_1}'
    {% else %}
        '검색어 없음'
    {% endif %}
    as INPUT_1
    from jhm.jhm_tbjobinfo
    limit 1;
```
​
