### ISSUE TITLE
ValueLinkU/Studio/탭설정 후 보기 실행시 Text가 모두 표시됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1446]
## 버그 설명 ##
탭 설정 후 보기 실행시 생성한 Text콤포넌트가 모두 표시됨
화면에서 탭을 누르면 설정한 값으로 하나만 출력됨

## 예상한 행동 ##
첫 화면 출력시 탭에서 설정한 항목만 표현

## 스크린샷 ##
[보고서 생성화면]
![image](https://user-images.githubusercontent.com/4444717/64110644-ab6bea00-cdbd-11e9-9bb4-c4c874dfd2b4.png)

[보고서 실행화면]
![image](https://user-images.githubusercontent.com/4444717/64110683-c63e5e80-cdbd-11e9-85da-eba1a28b8666.png)

**Comment by veldise** [comment]
편집 화면 > 미리보기로는 이상이 없으나, 저장 후 실행하면 문제가 발생합니다.
탭 동작에 대한 설정이 저장되지 않거나 실행(preview) 모드일때 Label 객체에 문제가 있는 것 같습니다.
