### ISSUE TITLE
ValueLinkU/Studio/보고서 편집화면에서 기존 생성된 보고서가 빈 페이지로 나타남

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1447]
## 버그 설명 ##
보고서 편집화면에서 기존 생성된 보고서가 빈 페이지로 나타남
최초 로그인 후 첫번째 편집 실행시에는 실행됨, 이후 리스트에서 선택하면 빈페이지로 나타남

## 예상한 행동 ##
편집화면으로 정상 출력

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/4444717/64111036-a2c7e380-cdbe-11e9-9f98-53950ed0d3dc.png)

**Comment by veldise** [comment]
Map(지도) 객체 내부에서 데이터 처리가 잘못되고 있는 것으로 보입니다.

**Comment by swish1995** [comment]
@veldise 
### 원인 파악 
* 마이그레이션 과정에서 tab 에 대한 bindName 을 report 의 varList 에 추가
* report 를 불러오면 해당 varList 를 varManager 에 setAll 동작 수행
* report 목록으로 이동시 varManager 의 tab 관련 변수 삭제가 이루어지지 않음
   * 현재 area, list, button, combo, check-radio 등만 varManger 에서 자기 변수 삭제 코드가 있음
* 이후에는 어떤 보고서를 불러와도 varManager 가 비어 있지 않으므로 throw error 인해 코드 멈출

### 해결방안
1. throw 관련 코드 수정
   * setAll 시 오류 발생하면 지우고 대체?
   * tab 등 다른 코드에도 일단 bindName 이 있으면 destroy 에 해당 코드 추가

**Comment by veldise** [comment]
@swish1995 
말씀하신대로
- `setAll()` 내부에서 already 에러 부분 제거
- tab 등 모든 컴포넌트 `$destroy` 검토하여 수정
처리 부탁드립니다.
