### ISSUE TITLE
studio: 언어 설정에 따라 상단 배경색이 다름

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1448]
## 버그 설명 ##
* 언어 설정에 따라 상단 배경색이 다름

## 재현하는 방법 ##
* 보고서 생성 및 열기
* 언어 변경

## 스크린샷 ##
* 언어 설정 - 대한민국
![image](https://user-images.githubusercontent.com/13827425/64137588-207a0680-ce34-11e9-846a-31eefb1479a0.png)

* 언어 설정 - English
![image](https://user-images.githubusercontent.com/13827425/64137601-34be0380-ce34-11e9-82b5-f950acc6a784.png)

**Comment by onlyeon** [comment]
언어 설정 변경으로 버튼 텍스트가 길어질 경우 버튼 영역이 타이틀 영역 아래로 밀려나는 레이아웃 이슈였습니다.
버튼이 더 추가되는 상황 등을 고려해 타이틀 영역의 가로값을 여유있게 줄였습니다.
