### ISSUE TITLE
angora: 검색어가 정상 동작 하지 않음

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#1450]
## 버그 설명 ##
* 검색어가 정상 동작 하지 않습니다.

## 재현하는 방법 ##
* 데이터 브라우저 - 검색 화면 이동
* 아래 조건 으로 실행
  * 데이터 모델: syslog
  * 검색어: * LEVEL_INT=7

## 스크린샷 ##
* LEVEL_INT에 7이라는 값이 존재 하는데 검색이 안됩니다.
![image](https://user-images.githubusercontent.com/13827425/64138251-2d4c2980-ce37-11e9-87a4-73c3c99c4e7e.png)

![image](https://user-images.githubusercontent.com/13827425/64138241-23c2c180-ce37-11e9-99ad-ee917bcd5cc2.png)

**Comment by seungfwani** [comment]
이슈 원인은 EVA.SYSLOG 테이블의 LEVEL_INT 컬럼의 타입으로 인해 발생한 것으로,
현재는 수정되어 이슈가 해결되었습니다.

![image](https://user-images.githubusercontent.com/46172579/64320111-c5ddd780-cff8-11e9-8a7a-f714cfc4871e.png)
