### ISSUE TITLE
studio: 쿼리중 '${} ' 으로 넣는경우 오류 발생

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#1466]
## 개요
* 2019.09.03
* 쿼리에 변수명 없이 ${} 와 같이 넣을 경우 콘솔창 오류 발생

## 에러 내용
* 위와 같이 쿼리를 작성시 오류가 발생하고 미리보기가 수행되지 않음

**Comment by veldise** [comment]
@swish1995 
검색어 미리보기에만 처리된 것 같습니다. 실행시 아래 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/3411842/64219234-9e571400-ceff-11e9-9540-ef787f799701.png)
