### ISSUE TITLE
베트남 데이터, DB브라우저, SQL결과 다운로드 안됨

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1469]
## 버그 설명 ##
DB 브라우저에서, 데이터를 다운로드 하는 버튼을 누르면, 값이 없는 제로 사이즈 파일만 다운됨

## 재현하는 방법 ##
동작을 재현하는 방법 : 스크린 캡처 참조

![image](https://user-images.githubusercontent.com/3444816/64156916-a320b700-ce70-11e9-81a6-bc9fb5d9b173.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
당장은 아주 급한 일은 아닙니다.

**Comment by hiy2259** [comment]
일단 원인은 확인해 보겠습니다.

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/1680#issuecomment-602450671

동일 증상으로 보고 닫습니다.
