### ISSUE TITLE
기존 보고서 출력 상이합니다

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#1471]
## 버그 설명 ##
CI/CD 대시보드 보고서가 정상적으로 출력되지 않습니다.

## 재현하는 방법 ##
1. Go to '보고서'
2. Click on 'CI/CD-dashboard' , ' CI/CD-detail'

## 스크린샷 ##
CI/CD dashboard
  - 행과 행 사이에 빈 칸이 들어갑니다. 
  - 컬럼 명이 안나옵니다
![image](https://user-images.githubusercontent.com/44352311/64216317-5631f480-cef3-11e9-8125-22241113bbf3.png)

CI/CD detail 
  - 좌측 리스트 프로젝트명 선택 시 우측의 데이터가 변경되어야 합니다
![image](https://user-images.githubusercontent.com/44352311/64216393-a6a95200-cef3-11e9-83a4-769daec0dae5.png)

**Comment by veldise** [comment]
1) 컬럼명이 나오지 않는 문제는 이번에 grid view 관련된 내부 모듈을 교체하면서 css 파일이 크게 변경되어서 그렇습니다. 번거로우시더라도 브라우저 캐시를 지우고 다시 접속하시면 해결됩니다.

2) 이번에 변수 관련 기능을 개편하고 트리거 설정 기능을 추가하면서 객체간 상호작용 기능이 변경되었습니다.
기존에는 변수만 설정해도 돌아가는 방식이었지만, 이제는 이벤트/값을 수신받는 객체쪽에서 "트리거 설정"이란 것을 해주어야 동작합니다.

**Comment by veldise** [comment]
답변이 되었으므로 이슈 닫습니다.
