### ISSUE TITLE
ValueLinkU / Studio / 메뉴의 텍스트 폰트 크기 조정 가능 여부 문의

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1474]
## 버그 설명 ##
현재 메뉴는 3단계로 구성이 가능 함, 이중에 두번째 단계의 메뉴에 대한 텍스트 폰트 크기를 줄일 수 있는지 문의 드립니다.

첨부 스크린샷과 같이 두번째 단계에 메뉴명이 길어지고 많이 생성되는 경우 문제가 되고 있습니다.

메뉴명을 줄이는 방안이 있겠지만, 이것 이외에 폰트 크기만 줄일 수 있는지 확인 요청 드립니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64216902-f2f59180-cef5-11e9-99fb-1124d4377e13.png)

**Comment by onlyeon** [comment]
![스크린샷 2019-09-20 오후 2 07 38](https://user-images.githubusercontent.com/11944592/65301696-8647eb80-dbb3-11e9-98c6-5b8ec6db1fbd.png)

1920 해상도에서 Full스크린일 때 메뉴가 한줄로 표현되도록 수정했습니다.
각 메뉴 그룹의 시각적인 분리를 위해 메뉴간의 간격을 넓혔습니다.
이로 인해 브라우저 사이즈가 줄어들면 두줄로 표현될 수 있습니다.
