### ISSUE TITLE
[R-studio] 에서 일반계정으로 hdfs파일에 read/write 할 수 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1475]
## 버그 설명 ##
R 에서 일반적으로 사용되는 hdfs 파일 access 방법이 있습니다.
예전(2018년 12월경) 에는 이 방법으로 hdfs 파일 엑세스를 했는데,
현재는 안됩니다.
 
read/write 하면 동일한 permission 에러로그가 나옵니다.

아래 코드가 모든 R 사용자들이 사용하는 일반적인 HDFS 엑세스 방법입니다. 
이 방법 외에 IRIS 의 HDFS 에 access하는 특별한 방법이 있어야 한다고 결론이 난다면 
rhdfs 패키지 기준으로 IRIS  의 R 패키지 개발이 되어야 합니다.

## 스크린샷 ##
<img width="804" alt="스크린샷 2019-09-04 오전 9 05 18" src="https://user-images.githubusercontent.com/5126497/64217806-c9d70000-cef9-11e9-8862-fb410b9e4579.png">

<img width="783" alt="스크린샷 2019-09-04 오전 9 53 38" src="https://user-images.githubusercontent.com/5126497/64217835-e3784780-cef9-11e9-860a-0e28a204d306.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@big-mobigen

**Comment by sunghoon** [comment]
@anhm @ollehQ 해당 이슈에 대한 확인 바랍니다.

**Comment by anhm** [comment]
ext-manager이 R을 실행할때 사용하는 계정으로 발생하는 이슈 입니다.
ext-manager는 앞으로 유지보수를 진행하지 않고, paly-ground로 변경될 예정이기 때문에 해당 이슈는 닫도록 하겠습니다.
