### ISSUE TITLE
앙고라 내 fit 관련 함수 동작 에러

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#1476]
## 버그 설명 ##
fit/fit_predict를 통해 생성된 모델의 결과가 보여지지 않습니다. 
모델은 생성되어 적용되지만 화면에 결과가 나타나지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
- 데이터 브라우저>검색
- * |  fit_predict kmeans FEATURES  SEPAL_LEN,SEPAL_WID k=3 INTO no_result

## 예상한 행동 ##
데이터에 kmeans 알고리즘이 적용된 결과가 나와야 하며, 
hdfs://192.168.100.180:9090/B-IRIS/USERS/dani/ML/model/no_result가 추가되어야 합니다.

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/32768535/64219245-ad3dc680-ceff-11e9-8654-89886810bd55.png)

![image](https://user-images.githubusercontent.com/32768535/64219261-c47cb400-ceff-11e9-8943-79359399752d.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
fit / fit_predict로 만들어진 함수들의 동작이 일정하지 않습니다.
어떨때는 동작되다가, 어떨때는 동작되지 않고 있습니다. 각각의 상황을 특정할 수 없을정도로 일관성있게 에러가 나오지 않습니다.

**Comment by GyuminJack** [comment]
모델을 저장하고 앙고라에서 웹으로 불러오는 과정에서 에러가 생기는 것으로 보입니다.
학습모델을 저장하는 동일한 쿼리를 날리면, HDFS에 저장이 되고 있습니다. 그런데 동일한 쿼리를 날리다가도 거의 대부분 상기 오류를 발생시키지만 때때로(?) 정상 작동하기도 합니다.
- 쿼리 : * |  fit LinearRegression FEATURES  SEPAL_LEN,SEPAL_WID LABEL PETAL_WID maxIter=1000 standardization=True INTO AAA
-동일 쿼리로 저장된 모델의 목록
![image](https://user-images.githubusercontent.com/32768535/64498080-b6f36f80-d2ed-11e9-848e-b6e87efc7f20.png)

**Comment by sunghoon** [comment]
@seungfwani 해당 기능에 대한 점검 바랍니다.

**Comment by seungfwani** [comment]
현재 모델 저장소를 hdfs -> minio 로 변경되었고, 해당 이슈시점의 서버 구성이 docker 환경에서 kubernetes 환경으로 변경되었습니다.

현재 해당 데이터 모델이 존재하지 않아, 내용이 같을 것이라 예상되는 iris(붓꽃) 데이터를 이용해서 쿼리를 실행 해보았고 동작을 하고있습니다.

![Screen Shot 2021-03-23 at 2 05 31 PM](https://user-images.githubusercontent.com/46172579/112095992-d8bafb80-8be0-11eb-9ec3-abd49c44b3bf.png)
