### ISSUE TITLE
studio: input 디폴트값 설정 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1480]
## 개요
기본값 과 안내 문구 변경시 input이 공유되는거 같습니다.

## 에러 내용
* 기본값을 변경합니다.
![image](https://user-images.githubusercontent.com/5515493/64226950-66aa9500-cf1c-11e9-9c97-cf3520868815.png)

*  안내 문구를 변경합니다.
![image](https://user-images.githubusercontent.com/5515493/64226960-788c3800-cf1c-11e9-9a98-a074c9f12d73.png)

* 다시 기본값으로 변경하면 안내 문구가 기본값으로 변경 됩니다.
![image](https://user-images.githubusercontent.com/5515493/64226973-880b8100-cf1c-11e9-8910-930ddfe6c78a.png)

* 이는 사용자에게 혼란을 줄수 있습니다.
*  추가로 저렇게 한후 저장하고 다시 불러 왔을 경우 안내문구는 나오지 않습니다.

**Comment by veldise** [comment]
기본값 / 안내문구 입력란(input)을 분리하는 것으로 진행하겠습니다.
