### ISSUE TITLE
studio: Combo-Box 값이 셋팅된 상태에서 Combo-Box를 클릭 했을때 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1481]
## 개요
Combo-Box 에 값이 셋팅된 상황에서 값을 선택하기위해 클릭하면 기존 값이 초기화 됩니다.

## 내용
* 값이 셋팅된 상태입니다.
![image](https://user-images.githubusercontent.com/5515493/64228367-8abca500-cf21-11e9-9c17-196fb4f4141f.png)

* 값을 변경하기 위해서 선택한 상태입니다.
![image](https://user-images.githubusercontent.com/5515493/64228371-8e502c00-cf21-11e9-9298-a2ffd2b2b8e4.png)

* 기획에 의도된 내용이라면 Close 해주시고 아니라면 수정해야 할 거 같습니다.

**Comment by veldise** [comment]
항목 선택(값 변경) 전에는 기존 값이 변경되어서는 안됩니다.
"에디터 사용" UI 관련하여 이슈가 있는 것으로 판단됩니다.
