### ISSUE TITLE
ValueLinkU / Studio / 조회 시간 이외의 Data가 그리드에 출력됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1485]
## 버그 설명 ##
최근 1년 data를 조회 했는데, 2010년 이후 Data가 표기됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 2010년 이후 Data조회
2. 최근 1년 Data조회

## 예상한 행동 ##
최근 1년 data만 출력

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/64235881-3ff85880-cf34-11e9-94d5-5799817c74d4.png)

**Comment by veldise** [comment]
#1463 과 같은 이슈로 판단됩니다.

**Comment by JeongHeeDong** [comment]
저장되어 있는 보고서를 실행한 경우 동일 현상 발생함
보고서 편집모드에서 실행하면 정상적으로 출력됨

[저장된 보고서 실행]
![image](https://user-images.githubusercontent.com/4444717/64496621-15b2ec00-d2e2-11e9-9ac1-1bc195f5104c.png)

[편집모드에서 실행]
![image](https://user-images.githubusercontent.com/4444717/64496629-311df700-d2e2-11e9-903c-fb07c35a6a59.png)

**Comment by veldise** [comment]
열(column) 정보가 동적으로 구성될 경우 발생하는 문제로 확인되었습니다.
(이전에는 열을 동적 데이터로 구성하는 경우가 없었습니다.)

이에 대응하기 위해 일단 1차적으로 시각화 옵션에서 헤더/열 옵션을 모두 disable 하는 옵션을 추가하는 것으로 잠정 결정되었습니다.
이 경우 각 열마다 스타일 지정하는 것은 불가능하게 됩니다.
