### ISSUE TITLE
ValueLinkU / Studio / 데이터 출력이 안되는 현상 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1486]
## 버그 설명 ##
보고서 화면 실행시 특정 데이터는 출력이 안되는 현상 발생
하나의 화면에 여러개의 차트, 그리드 등을 출력 할 경우 안되는 현상이 자주 발생함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64236303-155acf80-cf35-11e9-8a60-8456b97bdbdd.png)

[정상 실행화면]
![image](https://user-images.githubusercontent.com/4444717/64236347-2c99bd00-cf35-11e9-827d-0cd64fe86cf4.png)

**Comment by veldise** [comment]
이슈 본문 내용만으로 판단했을때, Angora API를 동시다발적으로 호출시
간헐적으로 API 결과(response)가 잘못되어 발생하는 것으로 추측됩니다.

다만 추측이 맞을 경우, 스크린샷과 같이 "차트를 그릴 수 없는 포맷입니다." 라고 출력되는 것은 UI 오류입니다.

@pjh0347 @namjals 
이 현상에 대하여 검토/테스트 요청합니다.
