### ISSUE TITLE
ValueLinkU / Studio / 테이블 출력에 대한 목록 개수값이 적용 안됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1487]
## 버그 설명 ##
보고서 생성에서 목록 개수값은 50으로 설정 하였으나, 보기 화면에서는 5로 표기되어 출력됨

## 예상한 행동 ##
보기 화면에서 50개의 목록이 기본으로 설정되어 출력

## 스크린샷 ##
[설정값]
![image](https://user-images.githubusercontent.com/4444717/64248490-2e22af80-cf4c-11e9-89f6-34fc09c13fb9.png)

[실행시 출력값]
![image](https://user-images.githubusercontent.com/4444717/64248519-4692ca00-cf4c-11e9-852b-201c6cf8ae71.png)

**Comment by veldise** [comment]
#1463 과 같은 이슈로 판단됩니다.
