### ISSUE TITLE
ValueLinkU / studio 보고서가 링크된 메뉴실행시 마지막 실행한 보고서가 출력됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1488]
## 버그 설명 ##
studio에서 생성한 보고서를 메뉴에 설정한 경우 실제 설정된 보고서가 아닌 마지막에 실행한 보고서가 실행됨
이 후 studio로 연결된 메뉴는 모두 같은 화면만 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서로 생성된 특정 보고서 실행
2. 메뉴에서 다른 보고서와 연결된 메뉴 실행

## 예상한 행동 ##
설정한 보고서 화면이 출력

## 스크린샷 ##
[Main Dashboard 메뉴 실행]
![image](https://user-images.githubusercontent.com/4444717/64252414-d7ba6e80-cf55-11e9-8053-056809ec03f5.png)

[글로벌 메뉴 실행]
![image](https://user-images.githubusercontent.com/4444717/64252437-eacd3e80-cf55-11e9-8dc4-bc77ac51cbeb.png)

**Comment by veldise** [comment]
현재 현상이 잘 재현이 안되는데 조금 더 확인해보겠습니다.

**Comment by veldise** [comment]
메뉴를 Studio로 구성한 경우,  iframe src는 제대로 변경되는데 content-view가 변경되지 않고 있습니다.

**Comment by veldise** [comment]
여전히 재현이 안되고 있지만 iframe cache 이슈로 추정됩니다.
관련글: https://www.fastly.com/blog/clearing-cache-browser

**Comment by veldise** [comment]
편집 화면에서 "보기" 버튼을 클릭하여 열리는 새 창에서 메뉴를 이동하면 나타나는 현상으로 확인되었습니다.
편집 미리보기에서는 메뉴를 제거하는 방안을 검토해야 할 것 같습니다.
