### ISSUE TITLE
ValueLinkU / Studio / 이미지가 표현 되지 않는 현상 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1489]
## 버그 설명 ##
Studio의 보고서에 적용한 이미지 파일이 간헐적으로 나타나지 않는 현상 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

왼쪽 화면을 보면 이미지가 정상적으로 로딩되지 않은 경우이며, 오른쪽이 정상 로딩 된 경우임

![image](https://user-images.githubusercontent.com/4444717/64302036-78dc1000-cfbc-11e9-99bd-37694ac7013d.png)

**Comment by veldise** [comment]
다음과 같은 순서로 진행하면 이미지가 로딩되지 않는 현상을 발견하였습니다.
1. 보고서 편집 화면 진입
2. 편집 화면이 열려있는 상태에서, 메뉴를 통해 다른 보고서 실행 화면으로 이동
3. 이미지가 로드되지 않고 box 상태로 출력
    - class가 다음과 같이 설정되어 있음 `box tool image`
