### ISSUE TITLE
ValueLinkU / Studio / 글로벌 테이블(날짜없는)로 생성된 모델데이터 조회 불가

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1491]
## 버그 설명 ##
날짜가 없는 글로벌 테이블을 모델로 만들고, 
해당 데이터를 Studio의 보고서에서 조회 할 경우 조회 안됨

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64303492-65807300-cfc3-11e9-935a-c5630bfa25ed.png)

[검색기능에서의 조회 결과]
![image](https://user-images.githubusercontent.com/4444717/64303519-8d6fd680-cfc3-11e9-90ab-88ff0f9680f9.png)

**Comment by veldise** [comment]
@JeongHeeDong 
글로벌 테이블 여부에 따라 검색이 안되는 것이 아니고, Map 객체에서 "데이터 모델" 로 검색어를 실행하는 경우에는
다음과 같이 지도의 영역 정보가 필터 조건으로 추가되어 검색이 수행됩니다.
```js
model name = '국가별 위경도 정보' spatial_coordinates = 'POLYGON((28.762241877092478 77.03407287597658, 28.762241877092478 77.44468688964844, 28.47412369059679 77.44468688964844, 28.47412369059679 77.03407287597658, 28.762241877092478 77.03407287597658))' map_level = 11
```
현재 화면에 보여지는 지도 내에 해당 데이터가 없다면 결과 데이터가 없을 수 있습니다.

위 검색 문법에 대해 자세한 내용은 플랫폼연구팀 박진호 선임에게 문의하시면 됩니다.

**Comment by JeongHeeDong** [comment]
@박진호 선임님 아래 확인 요청 드립니다.

테이블에 출력하면 정상 조회 되는것을 확인 했습니다.
다만 맵에 출력하고자 조회 한 경우에는 조회 결과가 없다고 나타 납니다.
![image](https://user-images.githubusercontent.com/4444717/64311361-ce291900-cfde-11e9-83d4-6b198b9cb410.png)

시각화 옵션에서 컬럼 선택도 나타나지 않습니다.
![image](https://user-images.githubusercontent.com/4444717/64311405-f153c880-cfde-11e9-9fd0-16ac14036c2a.png)

**Comment by veldise** [comment]
@pjh0347

**Comment by sunghoon** [comment]
오래된 이슈로 해당 보고에 대한 동일 내용이 다시 발생하면 새 이슈로 처리하겠습니다.
