### ISSUE TITLE
ValueLinkU / Studio / 보고서 테이블에 대한 컬럼 고정기능 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1492]
## 기능 요청 ##
Studio의 보고서 기능에서 테이블 형태의 data 출력시 특정 컬럼 위치를 고정으로 스크롤시에 항상 보이도록 하는 기능 필요

## 원하는 솔루션 설명 ##
엑셀의 틀 고정과 같은 기능

**Comment by sunghoon** [comment]
오래된 이슈로 해당 보고에 대한 동일 내용이 다시 발생하면 새 이슈로 처리하겠습니다.
