### ISSUE TITLE
[고급시각화] 의 꺾은 선형 챠트 오류 ( [검색] 의 시각화탭에서는 바로 나옵니다 )

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1494]
## 버그 설명 ##
고급시각화의 꺾은 선형 챠트가 잘못 그려집니다.
**검색** 메뉴에서 명령어로 그린 시각화탭에서는 multi-line 으로 챠트가 제대로 그려집니다.

myiris 계정
데이터모델 change_point_test   , 전체시간
검색 명령어
`* |  sort +DATETIME_10M | adv line sum(VALUE_CNT),sum(SMA_3) SPLITROW DATETIME_10M SPLITCOL TMP_GRP_KEY_COL COLSIZE 500`

## 스크린샷 ##
**고급시각화** 결과

<img width="1208" alt="스크린샷 2019-09-06 오전 10 00 15" src="https://user-images.githubusercontent.com/5126497/64394064-61218c00-d08f-11e9-9e56-86bc3b4d35f9.png">

** 검색 명령어 시각화 결과 **  이게 맞는 결과같습니다
<img width="1122" alt="스크린샷 2019-09-06 오전 10 14 26" src="https://user-images.githubusercontent.com/5126497/64394184-e016c480-d08f-11e9-9dda-10b15a274bc7.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
고급시각화의 명령어는
`* | adv line sum(VALUE_CNT),sum(SMA_3) SPLITROW 'date_group("DATETIME_10M", "10M")' SPLITCOL TMP_GRP_KEY_COL COLSIZE 500`

로 시간필드부분에 data_group 을 쓴 게 차이가 납니다.

**Comment by seoryjj** [comment]
date_group 에 버그가 있는 것 같네요. 
date_group 결과가 잘못 나오고 있습니다.( 참고로 데이터모델은 **검색**결과를 **HDFS로 내보내기** 한 후 생성한 모델입니다.) 
<img width="483" alt="스크린샷 2019-09-06 오전 10 41 14" src="https://user-images.githubusercontent.com/5126497/64394815-e195bc00-d092-11e9-94e8-8b6eb9db1f27.png">

**Comment by sunghoon** [comment]
@seungfwani DSL Command 확인바랍니다.

**Comment by seungfwani** [comment]
1. 시각화 탭에서 결과 이상
    - adv 명령어의 `date_group` 함수의 로직을 확인 해 보겠습니다.
2. sql 명령어에서 버그
    - `date_group` 집계함수는 IRIS 에서 생성한 함수로, spark SQL 을 사용하는 sql 명령어로는 사용 할 수 없습니다.

**Comment by sunghoon** [comment]
@seungfwani 
1번 사항은 확인 후 내용 공유바랍니다. 
2번 원하는 결과를 얻기 위한 다른 방안을 제시해 주세요.
2-1. 다른 명령어 사용 (concat)
2-2. 시간정보를 변환하기 위한 새 명령어

**Comment by seungfwani** [comment]
@seoryjj 
이슈를 다시 확인해본 바로 adv 명령어에서 date_group 함수로 그룹핑을 할 때 이미 그룹핑된 데이터에 대한 처리가 이상한 것으로 보이며 해당 내용을 수정 하도록 하겠습니다.

또한 현재 배포된 것은 아니지만 stats 명령어를 개선하여 배포 예정입니다.
테스트 용으로 stats2 명령어를 추가해놓았습니다. adv 의 date_group 함수도 stats 동작과 일치 하도록 수정하겠습니다.
```
syslog - 최근 60분

* | adv line sum(level_int) as AAA SPLITROW  'date_group("DATETIME", "10M")'  |  stats2 sum(`AAA` ) by date_group(`DATETIME`, "10M")

* | stats2 sum(   level_int   ) by date_group(`DATETIME`, "10M")
```

진행 할 내용
1. adv date_group 동작 수정

**Comment by seungfwani** [comment]
다시 확인해보니, 해당 데이터 모델의 시간컬럼 포멧이 잘못 지정되어 있었던 원인도 있습니다.
기존:
![Screen Shot 2020-12-11 at 10 52 46 AM](https://user-images.githubusercontent.com/46172579/101851667-53ff2100-3b9f-11eb-9428-4a4c653a6f7c.png)
변경:
![Screen Shot 2020-12-11 at 10 52 57 AM](https://user-images.githubusercontent.com/46172579/101851684-5eb9b600-3b9f-11eb-9017-1a73288ff0fe.png)

변경 후 시각화
![Screen Shot 2020-12-11 at 10 52 23 AM](https://user-images.githubusercontent.com/46172579/101851719-7002c280-3b9f-11eb-81c7-dbf32e373ecf.png)
![Screen Shot 2020-12-11 at 10 54 38 AM](https://user-images.githubusercontent.com/46172579/101851728-72651c80-3b9f-11eb-9778-5151fc70f327.png)

**Comment by sunghoon** [comment]
@seoryjj 확인 후 특이사항이 없다면 Close 부탁드립니다.
