### ISSUE TITLE
studio: 편집 화면 / 영문 전환시 사이드 패널 깨짐

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1495]
## 버그 설명 ##
- 편집 화면 / 영문 전환시 사이드 패널 깨짐

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/64396963-6c2de980-d09a-11e9-81ed-9b6933834bfb.png)

**Comment by onlyeon** [comment]
`<html>`의 `lang` 속성이 `en`일 경우 간격과 자간이 조절되도록 처리했습니다.
![스크린샷 2019-09-17 오후 4 24 50](https://user-images.githubusercontent.com/11944592/65020338-f9f5b880-d967-11e9-8765-7d0e3f9b12f7.png)
