### ISSUE TITLE
보고서 Chart에서 클릭시 신규 팝업창으로 이벤트 파라미터 전달기능 필요 

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#1499]
## 기능 요청 ##
   * 현재는 보고서 Grid상에서 클릭시 신규 팝업창으로 파라미터를 전달할수 있습니다.

## 원하는 솔루션 설명 ##
   * 보고서의 Chart에서 클릭시에도 신규 팝업창으로 파라미터 전달하는 기능이 필요합니다.
   * 대상 Project : 
        * SKB NMS+, Kotra 빅데이터, 수원시 빅데이터, 밸류링크유, NOKIA JMS, 교통빅데이터 등 모든 과제에서 사용이 필요합니다. 

## 고려한 다른 대안 ##
   * 별도의 웹개발로 Chart 컴포넌트를 사용하면 가능하지만, IRIS Studio의 보고서 Edit기능으로 사용하길 희망합니다.

## 기타 ##
   * 일정 : ASAP 입니닷!

**Comment by veldise** [comment]
#1804

**Comment by veldise** [comment]
Grid 행 클릭과 유사하게, 차트를 클릭시 변수값 설정 및 트리거를 동작시키도록 기능이 추가되었습니다.

패치 일자: 2020-02-21
관련 이슈: #1804

**Comment by veldise** [comment]
해결된 것으로 보고 닫습니다.
