### ISSUE TITLE
ValueLinkU / Studio&검색 / DSL로 조회한 결과가 sql조건과 맞지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1503]
## 버그 설명 ##
Studion와 검색에서 DSL로 조회한 결과가 sql조건과 맞지 않음

[실행DSL]
*| sql "select LOC_NAME, DATA_NAME , STIME, LOC_CODE, DATA_VALUE from angora where 
(DATA_TYPE='OECD_HPI' or DATA_TYPE='OECD_RPI')
and LOC_CODE = 'KOR'"

위 실행 결과는 LOC_CODE가 KOR 인것만 나와야 하지만, 다른 LOC_CODE들도 모두 조회됨

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64471318-fc4b5c00-d18a-11e9-87b3-c51135958f7d.png)

**Comment by seungfwani** [comment]
@sunghoon 
이슈에 대한 확인 내용을 전달드립니다.

이슈는 IRIS 데이터 소스에 관련해서 발생하는 것으로 확인했습니다.

문제가 발생하는 부분은 현재 확인 중입니다.

예상되는 문제 부분으로는 _1. 데이터 소스를 읽을 때_, _2. dataframe에 filter 조건을 추가할 때_, 로 예상됩니다.

참고사진: 운영서버에서 IRIS, HDFS 데이터 소스 별로 sql문을 구성하여 실행해 보았습니다.
- IRIS 데이터소스 : 잘못된 결과
![image](https://user-images.githubusercontent.com/46172579/64516004-a14f6b80-d328-11e9-8cc1-1911fe41d9ee.png)

- HDFS 데이터소스 : 정상 결과
![image](https://user-images.githubusercontent.com/46172579/64516045-b3310e80-d328-11e9-9c9a-9bf4bcf649bd.png)

**Comment by sunghoon** [comment]
WHERE에 들어 있는 조건문에서 괄호 우선순의 고나련 SOI 단에서 확인을 해 보게습니다.

**Comment by donghwasuh** [comment]
현재 이슈 해결되어서 다음 배포일에 적용될 예정입니다. 
배포된 후 테스트까지해서 이슈 close 하도록 하겠습니다.

**Comment by donghwasuh** [comment]
![스크린샷 2019-09-20 오전 9 34 42](https://user-images.githubusercontent.com/24667396/65290379-f3468b80-db89-11e9-9ccc-123acb880809.png)

배포 후 이슈해결 확인되어 close 하겠습니다.
