### ISSUE TITLE
ValueLinkU / Studio / 라디오 버튼 과 콤보박스를 연결한 자동 설정 문제

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1504]
## 버그 설명 ##
콤보박스에 라디오버튼으로 트리거를 설정한 경우 라디오 버튼을 클릭했을때 반영은 잘 됨
그러나 처음 화면 실행시 콤보박스에는 아무런 값이 설정되어 있지 안는 문제가 있음
(무조건 라디오버튼을 한번 선택해 주어야하만 콤보박스에 값이 설정됨)

처음화면 실행시에도 라디오 버튼의 설정값을 이용하여 콤보박스의 값이 나타나야함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64471483-2a31a000-d18d-11e9-9932-39b5b311db6e.png)

**Comment by veldise** [comment]
제가 판단하기로는 "화면 진입시 기본 값으로 자동 트리거"가 필요한 내용으로, 어느정도 기획or논의가 필요합니다.

**Comment by swish1995** [comment]
check-radio 콤포넌트의 기본값이 세팅 되어 있을경우 combo box 의 자동실행 옵션을 체크 하여 해결이 가능하도록 수정되었습니다.
