### ISSUE TITLE
ValueLinkU / Studio / Map에 표현되는 지역(나라) 명칭이 모두 한글로 표현 되어야함

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1505]
## 버그 설명 ##
Studio의 보고서에서 Map사용시 각 나라(지역) 명칭이 해당 국가의 언어로 표기되고 있음
모두 한글로 표기 되어야함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64471733-0facf600-d190-11e9-90ce-cb5a3c1b493e.png)

**Comment by sunghoon** [comment]
이건 오픈스트리트맵 이슈라 해결하려면 지도를 변경해야 하며,
변경한다면 구글 지도로 변경해야 하고. 
API 사용을 위해서는 access token 발생 등 추가적인 상황이 있을 겁니다. 
지금 상황에서는 지도 변경에 따른 일정이 없습니다

**Comment by JeongHeeDong** [comment]
아래 캡쳐 이미지를 보면 한글로 적용이 되어 있는 것으로 보입니다.
아래 사이트와 같이 지도 스킨을 선택 및 맵에 표현된 지역정보가 한글로 나오도록 하는게 되는지 다시한번 검토 요청 드립니다.

![image](https://user-images.githubusercontent.com/4444717/64484066-1f881100-d248-11e9-8b13-821c124305a2.png)

**Comment by sunghoon** [comment]
여기 어떻게 했는지 좀 보기는 해야 겠지만.
지금 잠시 제가 살펴본 바로는 해당 지도는 네이버지도 인것 같습니다. 
자세한건 담당자들에게 확인해 보라고 하겠습니다.

**Comment by JeongHeeDong** [comment]
추가 논의가 필요 없어 close처리함
