### ISSUE TITLE
ValueLinkU / Studio / Map에 Data가 출력되지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1506]
## 버그 설명 ##
243개 국가의 주요 위치 Data가 Map으로 출력이 안됨

특정 국가 하나만 조회하면 출력됨

[조회 SQL]

전체 조회 : SELECT 	SNAME, SCODE, LAT, LON , 100 as vv FROM 	VALUELINKU.TB_G_COUNTRY_INFO ;

한국만 조회 : SELECT 	SNAME, SCODE, LAT, LON , 100 as vv FROM 	VALUELINKU.TB_G_COUNTRY_INFO where SCODE = 'KR' ;

## 스크린샷 ##
[개별 조회시 출력됨]
![image](https://user-images.githubusercontent.com/4444717/64471878-97473480-d191-11e9-9bb9-dac1943efb1e.png)

[전체 조회시 출력안됨]
![image](https://user-images.githubusercontent.com/4444717/64471865-67982c80-d191-11e9-9cf0-6e7609aa312b.png)

**Comment by veldise** [comment]
일부 LAT, LNG 데이터가 잘못된 것으로 추측되는데 자세히 확인해봐야 합니다.

**Comment by hiy2259** [comment]
일단 데이터를 확인해 보니 데이터가 틀립니다.
<img width="918" alt="스크린샷 2019-09-10 오전 10 15 54" src="https://user-images.githubusercontent.com/5515493/64577813-74e33000-d3b8-11e9-887c-c73778722f89.png">

웹에서서 받은 모든 데이터는 results로 받게 되어 있는데 angora에서 주는 데이터는 records로 오고 있어 형식이 안맞아 에러가 발생하고 있습니다.

**Comment by veldise** [comment]
현재까지 확인한 바로는 LAT, LNG 컬럼의 유형이 `TEXT`라서 발생하는 문제로 추측됩니다.
