### ISSUE TITLE
[데이터모델]- 검색창에서 쿼리 결과로 만들어진 최종 Spark DataFrame 으로 chart 그리기

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1509]
## 기능 요청 ##
검색창에서
IRIS 및 HDFS, DB 에 저장된 데이터로부터 생성된 데이터 모델 -> read -> 검색 쿼리 및 사용자정의 명령어 -> **새로운 Spark DataFrame**이 생성됩니다.
이 최종 SparkDataFrame 은 맨처음 read한 데이터모델과는 전혀 다른 데이터필드및 struct 를 가지고 있습니다.
이 결과 dataframe 을 시각화, 재사용하려면 
현재
검색창에서 HDSF 로 내보내기 - HDFS저장 - 데이터모델 생성 - [고급시각화/검색/피벗]
의 과정을 거쳐야 합니다.

검색 창에서 나온 결과를 확인한 후 바로  "고급시각화로 이동" 하여 마지막 생성된  SparkDataFrame 으로 챠트를 그리고 싶습니다.

## 원하는 솔루션 설명 ##
검색 창에서 쿼리 결과 확인후 바로 **고급시각화로 이동**하여 **마지막 생성된  SparkDataFrame** 으로 챠트를 그리고 싶습니다.

## 고려한 다른 대안 ##
최종 output  으로 나오는 SparkDataFrame 을 **temp-데이터모델** 로 생성하는 명령어가 있어도 좋을 듯.

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
데이터모델뷰로 대응할 수 있을 것으로 보고 본 이슈는 닫도록 하겠습니다.
