### ISSUE TITLE
ValueLinkU / Studio / 콤보&체크박스의 세로 위치정렬을 가운데로 

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1510]
## 버그 설명 ##
Studio의 콤보&체크박스의 세로 위치 정렬이 위쪽으로 되어 있음
세로위치를 가운데 정렬로 해야 라벨(Text)및 다른 컴포넌트들과 열이 맞게 정렬됨

라벨(text) 콤포넌트의 텍스트 가운데 정렬과 같이...정렬기능을 넣을 필요는 없으나, 기본적으로 가운데 정렬이면 좋겠음

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64500051-a0054b00-d2f6-11e9-90f4-9fbb2b662c3e.png)

[text의 가운데 정렬]
![image](https://user-images.githubusercontent.com/4444717/64500094-c925db80-d2f6-11e9-9ba8-8ad9b338c5dd.png)

**Comment by onlyeon** [comment]
![스크린샷 2019-09-19 오후 1 23 23](https://user-images.githubusercontent.com/11944592/65231022-e4b88f80-db09-11e9-8e52-69d1dc416aff.png)
check, radio 객체가 기본 가운데 정렬 되도록 처리하였습니다.

**Comment by veldise** [comment]
해결된 내용이라 닫습니다.
