### ISSUE TITLE
[MDT] THP_DL 값이 0인 항목에 색상 적용이 안됨

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1511]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :
MDT_JSON_Shibuya라는 레포트의 100m/THP_DL, 50m/THP_DL에서 볼 수 있습니다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![이미지 1](https://user-images.githubusercontent.com/7123538/64508717-0ef39b80-d319-11e9-8368-abf63a54c298.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
`THP_DL` 컬럼의 유형이 숫자(`INTEGER` or `REAL`)가 아니고 `TEXT`라서 발생하는 문제로 확인되었습니다.
