### ISSUE TITLE
[MDT] 오브젝트 복사/붙여넣기 및 지도 이벤트

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1512]
## 기능 요청 ##
1. 레이어이름을 갖는 체크리스트박스에서 체크하면 지도내의 레이어에서 보이기/숨기기를 제어

2. 한번 만들어진 지도(콘트롤) 등을 복사하여 재사용(Copy/Paste)
    - 속성등 내용도 같이 복사

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
현재 최신 버전에는 아래와 같은 레이어 표시/숨김 기능, 객체 복사&붙여넣기 기능이 구현되었습니다.

![image](https://user-images.githubusercontent.com/3411842/82865305-5f6f5f80-9f61-11ea-8de5-03386afccd05.png)
