### ISSUE TITLE
클러스터 관리: 테이블 권한에서 그룹과 사용자 그룹에서 그룹이 일치하지 않는 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1513]
## 개요
사용자 그룹과 데이블 권한의 내용이 일치하지 않습니다.

## 에러 내용
* 사용자 권한은 WAS.WAS_GROUP 테이블을 요청하고 테이블 권한은 TB.TB_GROUP 테이블에 요청하고 있습니다.
* 이를 WAS.WAS_GROUP 테이블에서 데이터를 요청해야 합니다.

**Comment by hiy2259** [comment]
2019. 09. 10 운영 서버에 배포 했지만 예상치 못한 문제가 있었습니다.

단순히 쿼리만 변경하면 될 줄 알았는데 설정이 더 추가 되어야 합니다.

클러스터 관리는 DB connection이 IRIS만 연결되어 있는데 Meta 정보는 MariaDB에 있어 연결 정보를 추가해야 합니다.

만약 웹을 이용하여 권한을 줄 수 없을 시 일단 쿼리로 권한을 수정하고 내부 일정 협의하여 일정을 정해 처리하겠습니다.

**Comment by veldise** [comment]
당장 급하게 테이블 권한 설정이 필요한 경우 IRIS-Database에 직접 접속하여 권한을 부여하는 것이 좋겠습니다.

**Comment by veldise** [comment]
#1546 이 처리되면 사용자 그룹 관련하여 구조가 변경될 것이니, 해당 이슈 처리 후 진행해야 합니다.

**Comment by veldise** [comment]
일단 현재 버전에는 그룹으로 권한 설정하는 기능을 제거하고 정상화하기로 했습니다.
