### ISSUE TITLE
ValueLinkU / Studio / 조회 DSL과 다른 컬럼명으로 표가 출력됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1515]
## 버그 설명 ##
조회 DSL과 다른 컬럼명으로 표가 출력됨
아래 DSL을 보고서에서 실행시 출력 결과에 컬럼명이 LOFFICE로만 나타남

* | sql "select STIME, WN, BKG_NO, CUST_ID, CONTRACT, RHQ, LOFFICE, COFFICE, LREPCODE, CREPCODE, SLANE_CD, VTPSZ_CD, VOLUME, ACVTPSZ_CD, ACVOLUME from angora 
where 1=1
"| pivot sum(VOLUME) SPLITROW CUST_ID, RHQ,  **LOFFICE**, CONTRACT, SLANE_CD, VTPSZ_CD SPLITCOL WN

* | sql "select STIME, WN, BKG_NO, CUST_ID, CONTRACT, RHQ, LOFFICE, COFFICE, LREPCODE, CREPCODE, SLANE_CD, VTPSZ_CD, VOLUME, ACVTPSZ_CD, ACVOLUME from angora 
where 1=1
"| pivot sum(VOLUME) SPLITROW CUST_ID, RHQ,  **COFFICE**, CONTRACT, SLANE_CD, VTPSZ_CD SPLITCOL WN

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
LOFFICE / COFFICE 컬럼 설정에 따라 컬럼명이 각각 맞게 나타남

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/64529682-5e9c8c00-d346-11e9-88cc-131247cf0935.png)

**Comment by pjh0347** [comment]
`${combo_10}` 이 어떤 항목인지는 정확히 알 수 없으나 "L" 또는 "C" 값을 선택함에 따라 둘 중 해당 컬럼만 출력되도록 쿼리를 작성한 듯 합니다.

**Comment by pjh0347** [comment]
${combo_10} 이 어떤 항목인지는 정확히 알 수 없으나 "L" 또는 "C" 값을 선택함에 따라 둘 중 해당 컬럼만 출력되도록 쿼리를 작성한 듯 합니다.
