### ISSUE TITLE
ValueLinkU / 보고서 실행시 객체 이동

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1519]
## 버그 설명 ##
보고서를 생성하여 메뉴에 링크를 걸어 메뉴로 해당 보고서를 볼때 각 객체들에 마우스를 올리면 움직일 수 있다는 아이콘으로 변경되고 실제 객체들이 움직입니다.
마우스 포인트까지 캡쳐가 안되 스크린샷은 첨부 못했습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
동일한 보고서 페이지를 편집 화면에서 불러온 후, 메뉴를 통해 실행 화면으로 이동하면 발생하는 문제로 확인되었습니다.
