### ISSUE TITLE
[보고서]에서 URL 불러오기 에서 HDFS브라우저의 html 링크파일이 불러오기가 안됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1520]
## 버그 설명 ##
HDFS 에 저장된 html 파일의 링크로 **보고서**  의 **URL불러오기** 하면 에러가 납니다.
<img width="1229" alt="스크린샷 2019-09-16 오후 2 40 37" src="https://user-images.githubusercontent.com/5126497/64936687-158e8f80-d892-11e9-8fe8-098c2a8eba53.png">

## 재현하는 방법 ##
1. root 계정

2. HDFS  의 링크
http://192.168.100.180/hdfs-browser/hdfs/download?path=/B-IRIS/USERS/myiris/sample_plotly_htmlwidgets.html

3. 보고서 의 URL 불러오기 결과
<img width="1229" alt="스크린샷 2019-09-16 오후 2 40 37" src="https://user-images.githubusercontent.com/5126497/64936687-158e8f80-d892-11e9-8fe8-098c2a8eba53.png">

4. HDFS의 링크를 클릭하면
<img width="426" alt="스크린샷 2019-09-16 오후 2 53 10" src="https://user-images.githubusercontent.com/5126497/64936739-54bce080-d892-11e9-9ed9-25d492ecc74a.png">

## 예상한 행동 ##
해당  html 파일의 결과
<img width="1055" alt="스크린샷 2019-09-16 오후 2 42 32" src="https://user-images.githubusercontent.com/5126497/64936779-88980600-d892-11e9-8f31-b96d65a8feab.png">

python 의 plot.ly, htmlwedget 패키지를 이용했으며
웹 퍼블리싱을 위해 python 사용자들이 가장 일반적으로 사용하는 패키지입니다.

**Comment by veldise** [comment]
적어주신 HDFS 브라우저의 링크는 다운로드 전용 링크로, 위와 같은 사용에는 적합하지 않습니다.
만약 위와같은 사용을 원하시면 HDFS 브라우저 쪽에 기능을 추가해야 합니다.
