### ISSUE TITLE
ValueLinkU / 개인 설정에서 소숫점 자리수&천단위 표현 설정 값이 초기화 되는 경우 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1521]
## 버그 설명 ##
개인설정에서 소숫점 2자리, 천단위 표현으로 저장 하였으나, 계속 초기화 되어 소숫점 6자리로 , 천단위 표현 안되는 것으로 나타나는 경우가 자주 발생함

**Comment by SukYoungEun** [comment]
- cache 유효기간 설정이 정상적으로 되지않아서 Infinity로 수정함.
- 개인 설정 값이 cache 에 없을때 기본값을 설정해주는 타이밍 수정.
