### ISSUE TITLE
ValueLinkU / Studio / 등록한 오브젝트의 id값이 변경되는 현상이 발생함

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1522]
## 버그 설명 ##
보고서 생성 후 수정으로 들어가서 보면 오브젝트ID값들이 변경되어 있는 경우가 발생함
combo & check박스, input박스등을 많이 사용하는 경우 발생

**Comment by veldise** [comment]
오래된 이슈, 재현되지 않는 것으로 보고 닫습니다.
