### ISSUE TITLE
ValueLinkU / 개인설정의 소숫점 자리 설정시 포멧 정의 

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1523]
## 기능 요청 ##
개인설정에서 소숫점 자리에 대한 설정에 따라 표현시 뒤에 값이 0이더라도 표현 필요

예시) 0.101010  를 소숫점 2자리로 변경시
   --> 현재적용 : 0.1
  --> 변경요청 : 0.10

소숫점 자리수는 n자리까지 보겠다는 의미도 있지만, 포멧을 맞추겠다는 의미도 있음
따라서 자리수 만큼 보여주었으면 좋겠음

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/1617#issuecomment-542461599

본문 내용은 위 이슈로 해결된 것으로 생각되어 닫습니다.
혹시 다른 내용이라면 Reopen 혹은 신규 이슈 등록을 부탁드립니다.
