### ISSUE TITLE
brick: 해상도가 매우 클 때, 메뉴 깨지는 현상

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1524]
## 버그 설명 ##
- 메뉴가 깨지는 현상이 있어, 가운데 정렬로 수정하는 것이 필요하다고 합니다.

## 요구사항 분석 
- 아래 스크린샷과 같이, 메뉴의 개수가 매우 많을때, 왼쪽은 여백이 있는데 오른쪽은 여백이 없다는 이야기 같습니다.
- 정확한 내용은 문의 중

### 스크린샷
![screenshot-irisdev valuelinku com-2019 09 16-18-15-40](https://user-images.githubusercontent.com/3411842/64946535-159c8880-d8ae-11e9-81c1-ed713afc7eec.png)

**Comment by rhcpn** [comment]
이미 관련자들에게 전달 했지만 위의 

> 메뉴의 개수가 매우 많을때, 왼쪽은 여백이 있는데 오른쪽은 여백이 없다는 이야기 같습니다.
부분의 설명은 잘못 되었고 해상도가 커질때 우측으로 사이즈가 늘어나면서 상단 메뉴 오른쪽 서브 메뉴가 오른쪽 정렬로 계속 늘어나다보니 메인 컨텐츠는 가운데 정렬 되고 메뉴만 주욱 늘어나서 보기 이상하다는 의견 입니다.

아래 이미지 처럼 하고 싶다는건데 .. 일단 수정 없음으로 의견 전달 했습니다.

![image](https://user-images.githubusercontent.com/11566844/65472216-5ea39c80-dead-11e9-9e5a-84811e03d103.png)
