### ISSUE TITLE
studio: check&radio / 옵션/체크박스의 간격 조정 필요

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1525]
## 기능 요청 ##
옵션/체크박스의 간격이 너무 좁다고 합니다. 조정이 필요합니다.

## 스크린샷
현재 개발 적용된 상태:
![image](https://user-images.githubusercontent.com/3411842/64945438-7d050900-d8ab-11e9-8b65-e906ba7c5f74.png)

**Comment by onlyeon** [comment]
디자인/퍼블리싱이 적용되지 않아 브라우저 기본 체크박스로 보여지고 있습니다.
![스크린샷 2019-09-17 오후 4 08 02](https://user-images.githubusercontent.com/11944592/65019074-763acc80-d965-11e9-851d-e92e3d643528.png)
디자인 저장소 `dev`브랜치에 예제로 작성된 `B-IRIS-Design-System/views/studio/edit_checkbox-data_data.html` 파일 참조하여 적용 부탁드립니다.

**Comment by veldise** [comment]
배포된 항목이므로 닫습니다.
