### ISSUE TITLE
사용자관리에서 그룹생성시 테이블권한에서 생성한 그룹이 보이지않음

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1527]
## 버그 설명 ##
 사용자관리 > 그룹에서 신규 그룹을 생성하고
테이블권한에서 그룹에  테이블권한을 생성할려고 하는데 새로 생성한 [신규 그룹]이 보이지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 사용자관리 > 그룹에서 신규 그룹을 생성
2. 클러스터관리> 관리 > 테이블관리
3. 설정> 그룹에서 신규로 생성한 그룹이 안보임
4. 

## 스크린샷 ##
![캡처0](https://user-images.githubusercontent.com/5468183/65292001-939fae80-db90-11e9-8bde-d2cac505d628.PNG)

* 위에서 추가한 "nmsplus" 가 없슴

![캡처1](https://user-images.githubusercontent.com/5468183/65292006-97333580-db90-11e9-8681-6aeefdf8631f.PNG)

**Comment by veldise** [comment]
#1513 과 동일한 이슈로 생각됩니다.

**Comment by veldise** [comment]
#1513 과 중복 이슈로, 해당 이슈에서 처리하도록 하겠습니다.
