### ISSUE TITLE
[NMSPLUS]사용자별 접근화면 이력 저장 기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1528]
## 기능 요청 ##
사용자별로 접근한 메뉴/uri 저장/조회 기능 요청드립니다.

## 원하는 솔루션 설명 ##
1. 1차는 접속계정별 접근한 메뉴/uri  저장/조회 입니다.
2. 2차는 CRUD 기능이 들어가면 접속계정별 접근한 매뉴/url  및 파라미터값 저장,조회 기능입니다.

## 고려한 다른 대안 ##
없슴

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
없슴

**Comment by veldise** [comment]
@jjinylee 
본문 내용을 상세 작성 부탁드립니다.

**Comment by veldise** [comment]
#1566 에서 해결되었습니다.
메뉴 URI를 저장하지는 않지만, 대신 IRIS 시스템의 메뉴 ID를 저장합니다.
