### ISSUE TITLE
userId 가 글자수가 20자 이상일 경우 데이터가 조회되지 않음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1529]
## 버그 설명 ##
- Reported by: ValueLinkU
- userId 글자수가 20자 이상일 경우 데이터가 조회되지 않는다고 합니다.

## 상세
해당 userId는 SSO 관련하여 ValueLinkU 사이트에서 생성한 토큰 내 정보입니다.
따라서 IRIS-WEB 혹은 IRIS-DB에 존재하지 않는 계정일 수 있습니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/65300231-b9877c00-dbad-11e9-9001-0c678972c9f3.png)

**Comment by veldise** [comment]
정확히 확인된 내용은 아니지만, 이메일 형식이어도 20자 이하면 문제가 없다고 합니다.

**Comment by veldise** [comment]
오늘 오픈해야해서 급하다고 합니다.

**Comment by namjals** [comment]
일단 이메일 유형(@가 들어간)이라고 parsing하는데 문제는 없습니다. 글자 수 말고 다른 원인이 있어보입니다.

**Comment by donghwasuh** [comment]
IRIS에서 userid에 "@" 문자가 들어가는것을 허용하고 있지 않습니다. 
IRIS에서 사용자 계정정보를 아래와같은 형식으로 받기때문에 파싱하지 못할 수 있습니다. 
  - [USER_ID]:[USER_PASSWORD]@[HOST]

**Comment by donghwasuh** [comment]
IRIS에서 전반적으로 "user_id:userpassword@host" 형식을 사용하고있고 
이를 ":", "@" 문자기준으로 파싱해서 사용하고있기때문에 이메일형식을 허용하기위해서는 
IRIS를 전반적으로 수정해야합니다.

**Comment by veldise** [comment]
웹 쪽 이슈 정리입니다. (지속 수정중)
- 계정 등 REST API uri에 `userId`를 넣어서 호출하는 경우가 있는데, uri 에서 `@` 문자 허용하지 않음
- 대화형 분석 / docker conatiner 동적 실행시 container naming 을 아래와 같이 수행 (확인중)
    - `imageName + '...' + userId` (ex) `jupyter...root`)
- 아래와 같이 웹 cookie 키를 저장하는 경우가 있음.
    - `userId + '.someKeyName'`

**Comment by namjals** [comment]
angora에서 jhm에 소켓을 연결할 때, user_id 정보를 넘기는데, 이때 에러가 나고 있습니다.

**Comment by JeongHeeDong** [comment]
**[문제점 : 20자리 이상의 ID인경우 오류 발생]**
 - 정상 수행 : peace12@mobigen.com 
 - 오류 발생 : peace1234567@mobigen.com

**Comment by veldise** [comment]
@namjals 
위 예시로 원인 파악 부탁드립니다.

**Comment by namjals** [comment]
jhm에서 table에 업로드하는 user 컬럼의 조건이 아래와 같이 최대 길이 20으로 지정되어 있습니다.
`user = models.CharField(max_length=20)`

**Comment by namjals** [comment]
현재 수정된 파일을 벨류링크유에 업로드 중입니다.

**Comment by namjals** [comment]
배포가 완료되었습니다. 확인요청드립니다.

**Comment by JeongHeeDong** [comment]
동일하게 오류 발생하고 있습니다.
다시한번 확인 요청 드립니다.

**Comment by JeongHeeDong** [comment]
api쪽 실행시에도 같은 현상이 있는것으로 보입니다.

정상 동작 : http://bis.valuelinku.com/meta/api/account/logismarketing
오류 발생 : http://bis.valuelinku.com/meta/api/account/keyjong.kim@gmail.com

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/65310180-ac2bbb00-dbc8-11e9-8cea-018be5dab615.png)
