### ISSUE TITLE
[검색]창에서 fit cmd 로 ML 모델을 생성할 때, 재실행하면 에러가 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1532]
## 버그 설명 ##
검색 명령어 중 fit 으로 ML 모델을 생성할 때,
로그인 후 처음은 모델 생성이 되지만, 그 다음 모델 생성을 실행하면 에러발생합니다.
(->  파라미터 변경이나 데이터의 시간을 변경해서 해당 cmd 를 다시 실행하거나, 동일 명령어를 재실행하는 경우)

참고로 플랫폼연구팀 angora 담당자에게 해당 에러내용을 알린 상태입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 분석탬플릿에서  CMD_cast_syslog_DC_fit_org2  선택
<img width="962" alt="스크린샷 2019-09-23 오전 11 13 35" src="https://user-images.githubusercontent.com/5126497/65398777-268c5300-ddf4-11e9-912d-e3efe434903b.png">

2. 결과가 나온 후 model 이름을 변경하여 재실행하면( 파라미터 수정 후 재실행 또는 수정없이 재실행하는 것 포함. )
<img width="838" alt="스크린샷 2019-09-23 오전 11 13 09" src="https://user-images.githubusercontent.com/5126497/65398849-79660a80-ddf4-11e9-8fb2-e08c705632f1.png">

**Comment by sunghoon** [comment]
관련 데이터 부재로, 재현이 불가하여 닫습니다.
동일 사항이 재발생하면 새 이슈로 처리하겠습니다.
