### ISSUE TITLE
기본 설정 - 소수점 자리수를 6자리 -> 2자리로 변경

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1533]
## 기능 요청 ##
기본 설정 - 소수점 자리수를 6자리 -> 2자리로 변경

## 기타
ValueLinkU에만 적용

**Comment by rhcpn** [comment]
@정희동 팀장님 요청으로 일정을 앞당겨서 ValueLinkU(2019/09/25) milestone 내에 진행 처리 부탁합니다.
