### ISSUE TITLE
studio: 차트 객체 초기 이미지 변경

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1536]
## 기능 요청 ##
- 스크린샷과 같은 차트 객체 초기 이미지를 변경 요망
- 정확한 요구사항 없음 (차후 이야기 듣고 수정)

## 스크린샷
![image](https://user-images.githubusercontent.com/3411842/65412656-a8976e80-de2a-11e9-9dc2-443618364516.png)

## 기타
ValueLinkU에만 변경할 것인지, 전체 변경할 것인지 디자인 검토 필요

**Comment by sunghoon** [comment]
오래된 개선 요구 사항으로 닫습니다.
