### ISSUE TITLE
ValueLinkU / Main Dashboard 띄울 때, 간혹가다 데이터 통신 에러가 나타나는 경우가 있음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1537]
## 버그 설명 ##
- Main Dashboard 띄울때, 간혹가다 데이터 통신 에러가 나타나는 경우가 있음

## 원인 추측
- request가 많은 경우에 일시적인 오류가 발생하는 것으로 추정
- 조치 전, 현상 파악 필요

**Comment by sunghoon** [comment]
오래된 이슈로 동일 사항이 재발생하면 새 이슈로 처리하겠습니다.
