### ISSUE TITLE
studio: 세션 타임아웃이 되지 않는 것 같음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1538]
## 버그 설명 ##
- 세션 타임아웃 기능이 동작 안하는것 같음
- 페이지를 띄워놓고 1시간 이상 지나도, 세션 타임아웃이 되지 않는 것 같다.

## 기타
- 세션 타임아웃은 1시간이지만, 이전에 분석가분들 요구사항에 따라 일부 서비스는 무제한(unlimit) 처리
- 위 항목과 더불어, ping 요청으로 계속 세션을 갱신하고 있음

**Comment by veldise** [comment]
#1916 이슈 긴급 처리로 인해 마일스톤 변경했습니다.

**Comment by sunghoon** [comment]
처리된 것으로 보고 닫습니다.
