### ISSUE TITLE
angora: rename 명령어에 문자열을 넣을 수 있도록 개선 필요

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1541]
## 기능 요청 ##
- report by: 정희동T
- rename : 문자열을 넣을 수 있도록 개선 필요 , 예)"가나다라 / 마바사"

**Comment by seungfwani** [comment]
해당 내용 수정하였으며, valuelinku 배포 요청 하도록 하겠습니다.

**Comment by seungfwani** [comment]
운영서버에서는 해당 내용이 확인 되었습니다.
![image](https://user-images.githubusercontent.com/46172579/73919818-a0d2f500-4907-11ea-9fb3-26ee287ea3c8.png)

**Comment by seungfwani** [comment]
valuelinku 서버에 아래 내용처럼 rename 명령어로 문자열을 사용할 수 있습니다.
![image](https://user-images.githubusercontent.com/46172579/74119141-96fc0b00-4c01-11ea-8639-53075fa18c49.png)
