### ISSUE TITLE
ValueLinkU / 피벗 : SPLITCOL기준 정렬 기능

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1544]
## 기능 요청 ##
 피벗기능에서  SPLITCOL기준 정렬 기능.
예시) 날짜기준으로 피벗을 했을경우 최근 날짜가 먼저 출력되도록 하는 기능

[출력예시]
항목 | 201909 | 201908 | 201907.......
A      |   100     |     200   |    300
B      |   100     |     200   |    300

**Comment by veldise** [comment]
본문 요청하신 기능이 검색질의어(DSL)인지, 웹UI인지 확인이 필요합니다.

**Comment by JeongHeeDong** [comment]
DSL에 정렬할 수 있는 명령어(기능) 이 필요합니다.

**Comment by seungfwani** [comment]
아래 두 결과 중 어떤 기준으로 출력되도록 해야하는지 기준을 요청드립니다.

[원본데이터]
항목 | DATE | 필드1
-- | -- | --
A | 201901 | 2
B | 201902 | 5
B | 201901 | 3
C | 201903 | 14
A | 201902 | 4

[`pivot count(*), sum(필드1) SPLITCOL DATE SORTCOL DESC` 결과 1]
201903_count(*) | 201902_count(*) | 201901_count(*) | 201903_sum(필드1) | 201902_sum(필드1) | 201901_sum(필드1) 
-- | -- | -- | -- | -- | --
1 | 2 | 2 | 14 | 9 | 5

[`pivot count(*), sum(필드1) SPLITCOL DATE SORTCOL DESC` 결과 2]
201903_sum(필드1) | 201903_count(*) | 201902_sum(필드1) | 201902_count(*) | 201901_sum(필드1) | 201901_count(*) 
-- | -- | -- | -- | -- | --
14 | 1 | 9 | 2 | 5 | 2

**Comment by seungfwani** [comment]
본 요구사항을 해결하기 위해서 위의 댓글 [결과1], [결과2] 중
[결과 2] 으로 출력되도록 처리 하였습니다.

배포 후 테스트 진행 하도록 하겠습니다.

**Comment by seungfwani** [comment]
pivot 명령어에 `SORTROW` 및 `SORTCOL` 옵션을 추가하였습니다.
예제) 
`pivot avg(LEVEL_INT) SPLITCOL DATE SORTCOL DESC`
`pivot avg(LEVEL_INT) SPLITROW HOST SPLITCOL DATE SORTROW ASC SORTCOL DESC`

상세 설명은 문서에 기록해 놓았습니다.
문서: https://github.com/mobigen/B-IRIS-Data-Discovery-Service/blob/master/docs/ko/commands/pivot.md

**Comment by seungfwani** [comment]
해당 옵션이 동작하는 것을 확인 하였습니다.

예제 1) SORTROW ASC  SORTCOL DESC
![image](https://user-images.githubusercontent.com/46172579/68173683-181e8300-ffbf-11e9-86c3-effd217aadc4.png)

예제 2) SORTROW ASC  SORTCOL ASC  
![image](https://user-images.githubusercontent.com/46172579/68173720-34222480-ffbf-11e9-9775-6a54eea2d275.png)


예제 3) SORTROW DESC SORTCOL DESC
![image](https://user-images.githubusercontent.com/46172579/68173626-ec030200-ffbe-11e9-8340-0ef13387c25f.png)
