### ISSUE TITLE
ValueLinkU / SSO로그인(ID값, 권한 설정 등)

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1545]
## 버그 설명 ##

 SSO관련 이슈

현재 밸류링크유에서 로그인하면서 쿠키를 생성하게 됩니다.
이때 사용자 ID가 이메일 주소로 되어 있습니다. 그런데 IRIS에서는 이메일 주소의 ID를 허용하고 있지 않습니다. 이런경우 밸류링크유 ID와 IRIS의 ID가 불일치 하게 됩니다.
이렇게 되면 각 계정에 대한 권한 관리를 할 수 없습니다.

이에 대한 해결 방안이 필요합니다.

**Comment by veldise** [comment]
다음과 같이 협의 및 해결되었습니다.
- ValueLinkU 에서 IRIS 웹 토큰 생성시, `userId`, `email` 정보를 같이 입력
- IRIS 웹 상단 UI에 `userId` 출력 부분을 `email` 출력하도록 수정 (사이트 커스터마이징)
