### ISSUE TITLE
[jupyter] 에서 python2.7 로 pip install 작업 시 에러발생하는데, 에러 로그내용이 python3 에 관한 내용이 포함되어 있습니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1548]
## 버그 설명 ##
jupyter 에서 python2.7 로 new 한 후 pip install tensorflow

<img width="923" alt="스크린샷 2019-09-24 오후 2 47 49" src="https://user-images.githubusercontent.com/5126497/65484743-c58b7a80-deda-11e9-8cf4-7230e15df451.png">

<img width="870" alt="스크린샷 2019-09-24 오후 2 54 34" src="https://user-images.githubusercontent.com/5126497/65484918-52cecf00-dedb-11e9-9c05-38269e41f019.png">

=> 로그 중간 중간 path 이름에  python2.7 , python3.7 이 혼재되어 있습니다.

**Comment by anhm** [comment]
내용을 확인하여 사내 서버에 배포 완료 했습니다.
