### ISSUE TITLE
studio: 테이블 상단에 여백 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1549]
## 버그 설명 ##
- Issuer: 정희동T
- 스크린샷과 같이, 테이블 상단에 여백(margin 으로 추정)이 갑자기 생겼다고 합니다.

## 스크린샷
![image](https://user-images.githubusercontent.com/3411842/65508800-00f26d00-df0c-11e9-9061-84bbd1ba918a.png)

**Comment by onlyeon** [comment]
chart 객체의 테두리, 여백 제거로 인해
그리드 차트 상단에 filter기능(페이지네이션)이 올 경우 여백이 없어 추가한 margin으로 인해 발생한 문제입니다.
차트 상단의 여백을 제거하고 filter기능 하단에 여백이 생기도록 수정하였습니다.

@veldise IRIS-Design-System REPO 가장 최근 CSS 참조 부탁드립니다.

**Comment by veldise** [comment]
@onlyeon 
알겠습니다.

**Comment by JeongHeeDong** [comment]
지난번 패치한 버전에도 동일하게 여백이 발생하고 있습니다.
추가로 그리드의 세로 스크롤바가 무조건 나타나고 있습니다. 출력되는 row수에 따라 가변적으로 보여야 합니다.
확인 및 조치 부탁 드립니다.

![image](https://user-images.githubusercontent.com/4444717/69701654-bfab5300-1130-11ea-8066-0c4b1635c152.png)

**Comment by veldise** [comment]
패치로 해결된 내용입니다. 당시 패치 후에 구두로 내용 전달했습니다.
