### ISSUE TITLE
ValueLinkU/Studio/콤보박스의 모델 선택이 안되는 현상 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1554]
## 버그 설명 ##
콤보박스 설정에서 데이터 모델을 선택 할 경우 특정 모델에 대한 선택이 안되는 현상 발생

"통합지표_Data_Global"모델은 선택하면, 계속 선택이 안된것으로 나타남

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/65578653-2b4a3600-dfb1-11e9-8c1c-650e909952c5.png)

**Comment by JeongHeeDong** [comment]
동일한 현상이 다시 발생 하고 있습니다. 
확인 부탁 드립니다.

**Comment by veldise** [comment]
#1572 에 조금 더 상세한 내용이 있어 그쪽에서 처리하겠습니다.
