### ISSUE TITLE
ValueLinkU/Studio/공유받은 보고서 복제 후 수정시 모델 리스트가 없는 현상

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1555]
## 버그 설명 ##
공유받은 보고서를 복제하여 사용 할 경우, 데이터모델에 대한 권한은 어떻게 되는지요?
현재 다른계정에서 복제한 보고서의 경우 모델리스트가 나오지 않는 현상이 있습니다.

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/65581301-2dfb5a00-dfb6-11e9-85b9-fe09bdbb4a43.png)

**Comment by sunghoon** [comment]
최신 버전에서 관련 내용이 재현되지 않아 동일 사항이 재발생하면 새 이슈로 처리하겠습니다.
