### ISSUE TITLE
SMS 클릭시 에러가 발생함

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1556]
## 버그 설명 ##

아래와 같이 알람 버튼을 클릭하며 에러가 표시됨

![스크린샷 2019-09-26 오후 3 16 51](https://user-images.githubusercontent.com/3415270/65663039-b3434500-e070-11e9-91fb-7a9ddaee1f6d.png)

## 재현하는 방법 ##
다음 사이트에서 발생:
http://192.168.102.159/#/

root 계정으로 로그인 하시면 됩니다. (180번과 root pw는 동일함)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm 
해결된 이슈입니다. 최신 버전을 배포하면 해결될 것입니다.

**Comment by sunghoon** [comment]
disable 되어 닫습니다 .
