### ISSUE TITLE
ValueLinkU / Studio / 그리드의 상단에 불필요한 공간 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1558]
## 버그 설명 ##
그리드 설정에서 "필터" 와 "목록개수"를 제거한 경우 출력물의 레코드수에 따라 상단에 공간이 발생함 

기본 5개 이하로 출력시에는 공간이 없지만, 5개 이상인경우 발생하는것으로 보임

## 스크린샷 ##
[출력수가 많지 않는 경우 상단 공간 없음]
![image](https://user-images.githubusercontent.com/4444717/65733283-e9340800-e108-11e9-804a-3af32e72822b.png)

[출력수가 많은경우 상단 공간 발생]
![image](https://user-images.githubusercontent.com/4444717/65733308-fe109b80-e108-11e9-9f02-795487252fca.png)

**Comment by veldise** [comment]
#1549 와 동일한 이슈로 생각됩니다.

**Comment by veldise** [comment]
아래와 같이 pagination UI가 나타나야 합니다.

![image](https://user-images.githubusercontent.com/3411842/65842277-593eca00-e365-11e9-8653-d58e9253beef.png)

**Comment by veldise** [comment]
현재는 해결된 것으로 보고 닫습니다.

![image](https://user-images.githubusercontent.com/3411842/67444723-3b534500-f645-11e9-96ad-967c26de1d6e.png)
