### ISSUE TITLE
[대화형분석] jupyter 에서 python2, 3버전 에서 패키지 설치 시 에러 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1559]
## 버그 설명 ##
python example_code에 있는 hdfs access 패키지인 hdfs 가 설치 되어 있지 않아서
pip install hdfs
시 에러납니다. python2, 3 버전 모두 설치 에러 납니다.
다른 서버(python2.7) 에서는 정상적으로 install 됩니다.

<img width="870" alt="스크린샷 2019-09-27 오후 1 53 43" src="https://user-images.githubusercontent.com/5126497/65743142-4bebca80-e12e-11e9-90c1-3e87f1c0d6b5.png">

<img width="872" alt="스크린샷 2019-09-27 오후 1 53 56" src="https://user-images.githubusercontent.com/5126497/65743149-55753280-e12e-11e9-849c-475f27de2a9d.png">
<img width="862" alt="스크린샷 2019-09-27 오후 1 54 05" src="https://user-images.githubusercontent.com/5126497/65743152-5908b980-e12e-11e9-99a6-211936a7b140.png">

## 예상한 행동 ##
* 다른 서버에서 설치 성공
<img width="995" alt="스크린샷 2019-09-27 오후 1 54 57" src="https://user-images.githubusercontent.com/5126497/65743164-6756d580-e12e-11e9-9efa-0dbd45729fa7.png">

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @ollehQ 이슈 확인바랍니다.

**Comment by anhm** [comment]
ext-manager 는 더이상 배포되지 않을 예정이며, 다음 버전인 play-ground가 배포될 예정입니다.
해당 이슈는 play-ground에서 해결이 되었습니다.
