### ISSUE TITLE
studio: 미리보기 화면에서 데이터 모델이 없습니다.

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1560]
## 버그 설명 ##
편집화면에서 자동 실행이 되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 새 보고서 버튼을 클릭한다.
2. 편집화면에서 영역 객체를 생성 후 데이터에서 데이터 모델 쿼리를 셋팅하고 자동실행을 클릭한다.
3. 보기 버튼을 클릭한다. 

## 예상한 행동 ##
* src/main/javascript/directives/visual-box/area.js
```js
var getModelPromise;
if (params.authority === 'owner') {
    // model list에 존재하지 않음.
    getModelPromise = dataModelAgent.getOneWithSharerAuth({
        modelId: params.modelId,
        reportId: scope.box.reportId
    });
} else {
    getModelPromise = $q(function (resolve, reject) {
        var list = dataModelAgent.cache.modelList();
        var model = _.find(list, { id: params.modelId });
        if (model) {
            resolve(model);
        } else {
            reject('report.edit.message.no_model');
        }
    });
}
```
위 코드에서 ``` var list = dataModelAgent.cache.modelList();```에서 데이터 모델 리스트가 빈 array 입니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/5515493/65746843-d3d7d180-e13a-11e9-98de-c712300c86e2.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
해결되어 닫습니다.
