### ISSUE TITLE
MDT / Map의 여러 레이어에 대하여 특정 레이어만 보여주거나 숨기는 기능

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1563]
## 기능 요청 ##
MDT / Map의 여러 레이어에 대하여 특정 레이어만 보여주거나 숨기는 기능

레이어1, 레이어2, 레이어3 이 있는경우 체크박스 또는 콤보박스로 보곳싶은 레이어를 선택적으로 볼 수 있는 기능

**Comment by veldise** [comment]
@JeongHeeDong 
말씀하신 기능은 "레이어 관리" 기능에서 "표시" 버튼을 토글하시면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/65851754-fa8e4600-e38e-11e9-8120-beb9a4092b61.png)

**Comment by JeongHeeDong** [comment]
네, 실제 화면에서 제어 하고자 하는 내용입니다. 
체크박스를 추가해서, 선택적으로 보여지도록 하는 기능을 추가
(백승욱 선임께서 해당 내용 알고 계십니다.)

**Comment by veldise** [comment]
@JeongHeeDong 
혼선이 있을 수 있으니 가능하면 개발자 개인에게 전달하지 마시고,
저희 팀장님이나 이슈로 이야기해주시면 감사하겠습니다.
