### ISSUE TITLE
ValueLinkU / Studio / if문 사용시 데이터 값 체크 기능 추가

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1564]
## 기능 요청 ##
현재 if문은 값이 있는지 없는지만 체크 가능함, 
값을 체크하여 별도로 처리 할 수 있는 기능 필요

추가적으로 값의 체크 결과에 따라 alert 같은 알림 메세지 표현 기능 추가 필요

**Comment by JeongHeeDong** [comment]
@veldise 책임님
현재 b-iris.mobigen.com에서는 되는 기능으로 알고 있습니다.
완료된 기능이면 close해 주세요

**Comment by veldise** [comment]
@JeongHeeDong 
아래와 같은 nunjucks template 문법으로 조건문을 사용 가능합니다.
```
{% if hungry %}
  I am hungry
{% elif tired %}
  I am tired
{% else %}
  I am good!
{% endif %}
```
그런데 값의 체크 결과에 따라 alert 등의 동작을 하도록 지정하는 기능은 아직 없습니다.
