### ISSUE TITLE
ValueLinkU / IRIS사용에 대한 이력을 저장하여 조회 할 수 있는 방안 필요

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1566]
## 기능 요청 ##

- [ ] IRIS Analyzer의 실행된 메뉴에 대한 이력 저장(사용자가 정의한 메뉴 포함)
필수 저장 항목 :  매뉴 실행일시, 실행 계정(사용자), IP

- [x] DSL 실행 이력에 대한 저장
현재 SQL에 대해서는 실행 이력을 볼 수 있지만, DSL은 없음
필수 저장 항목 :  DSL실행시간, DSL종료시간, 실행 계정(사용자), IP, DSL, 실행결과

- [ ] 로그인/로그아웃에 대한 이력 저장
필수 저장 항목 :  로그인 시간, 로그아웃 시간, 계정(사용자), IP

**Comment by veldise** [comment]
@JeongHeeDong 
"DSL 실행 이력에 대한 저장" 은 데이터 브라우저 > 작업 조회 기능으로 충족되는 항목이 아닌가 싶습니다.
확인 부탁드리며 필요시 시간 내주시면 따로 구두로 설명드리겠습니다.

**Comment by JeongHeeDong** [comment]
"DSL 실행 이력에 대한 저장" 관련해서는 작업 조회로 처리 가능 한것으로 확인 했습니다.

**Comment by veldise** [comment]
@JeongHeeDong 
감사합니다. 나머지 2개는 UI까지는 어렵지만, 서버 로그로 이력을 남기는 것까지는 2월중에 진행 예정입니다.
