### ISSUE TITLE
ValueLinkU / Studio / 그리드의 셀 머지 출력 기능

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1571]
## 기능 요청 ##
그리드에 데이터 출력시 동일한 값에 대해서는 cell이 머지 되도록 기능 구현

[셀 머지 예시]
![image](https://user-images.githubusercontent.com/4444717/65926802-eea79000-e431-11e9-9e82-5a5795d9a821.png)

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by sunghoon** [comment]
@eumminsun 본 이슈 관련 사항에 대한 정보 공유 바랍니다.

**Comment by eumminsun** [comment]
@sunghoon 2020-11-5 해당 이슈 리뷰 후  결과 공유 드리겠습니다.  :)

**Comment by eumminsun** [comment]
@sunghoon 
기획 진행예정입니다
기획부터 진행 후 개발 일정 산정 하기로 하였습니다

**Comment by JeongHeeDong** [comment]
진행일정이 확정되면 공유 요청 드립니다.
