### ISSUE TITLE
[IRIS ML Command] fit 으로 저장한 ML모델을 predict 에서 불러올 때 기능 요청(predict에 옵션 추가)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1573]
## 기능 요청 ##
IRIS ML command 에서 fit 으로 저장한 ML 모델은
동일한 이름으로 HDFS에 저장될 때 실행시간별 하위 디렉토리가 생성되어 저장됩니다.
predict 로 ML모델을 불러올 때
- 디폴트는 가장 최근에 저장된 ML모델을 가지고 오는 것
- 옵션으로 특정 디렉토리를 지정하면 해당 디렉토리의 ML모델을 가지고 온다.

## HDFS 에 동일한 이름으로 ML모델 저장된 경우 ##
<img width="985" alt="스크린샷 2019-10-01 오후 3 16 14" src="https://user-images.githubusercontent.com/5126497/65938786-f3cf0400-e45e-11e9-9001-6ccf8c975578.png">

`predict  model_1_DC_classif_castsyslog_org2`

를 실행하면 자동으로 가장 최신 디렉토리 20191001145628  에서 가지고 오고

`predict model_1_DC_classif_castsyslog_org2 model_dir=/B-IRIS/USER/../20190923095854`

를 실행하면 model_dir 아래에 있는 model_1_DC_classif_castsyslog_org2 모델을 가져온다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
현재 predict 명령어는 *1. 가장 최근에 저장된 ML모델을 가지고 오는 것* 으로 동작하고 있습니다.

2. 특정 디렉토리를 지정하면 해당 디렉토리의 ML모델을 가지고 온다. 
의 경우 옵션 정보를 추가해야합니다.

**Comment by seungfwani** [comment]
ML 구성을 변경하며, 학습 모델명은 유니크 하도록 변경 되었기 때문에 위와 같은 처리는 진행 하지 않습니다.
