### ISSUE TITLE
[ML Command] 검색창에서 mlmodel summary  에러 발생

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1576]
## 버그 설명 ##
fit으로 생성한 model_1_DC_classif_castsyslog_org2  모델에 대한 정보를 보기 위해
mlmodel summary 를 실행하면 에러 발생

<img width="369" alt="스크린샷 2019-10-01 오후 5 44 02" src="https://user-images.githubusercontent.com/5126497/65947482-5fbb6780-e473-11e9-93e5-ad4732c12a2f.png">

<img width="259" alt="스크린샷 2019-10-01 오후 5 43 54" src="https://user-images.githubusercontent.com/5126497/65947491-64801b80-e473-11e9-9b0b-5b23543a7327.png">

**Comment by seungfwani** [comment]
현재 동작 하도록 수정하였습니다.

![image](https://user-images.githubusercontent.com/46172579/66887810-23613d00-f017-11e9-91a4-192d04e391c6.png)
