### ISSUE TITLE
MDT / studio / 특정 Map에 설정한 변수가 다른 Map도 동일하게 나타남

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1590]
## 버그 설명 ##
1번 Map에 변수를 설정 하였으나, 2번 Map도 동일한 값으로 나타남

## 예상한 행동 ##
Map별로 각각 다른 변수를 설정 되어야 함

## 스크린샷 ##
[1번 Map 변수 설정]
![image](https://user-images.githubusercontent.com/4444717/66013860-cb4f1480-e507-11e9-85c4-5abfbeb1a2cf.png)

[2번 Map에 동일하게 나타남]
![image](https://user-images.githubusercontent.com/4444717/66013886-defa7b00-e507-11e9-809e-3da67ec6d654.png)

**Comment by veldise** [comment]
변수명 중복 현상 - 현재는 아래와 같이 해결된 것으로 보입니다.
혹여 재발하면 이슈를 다시 열어주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/67647511-ec275000-f975-11e9-8396-831585dae607.png)
