### ISSUE TITLE
MDT / studio / Map에 출력된 Data 값에 대한 색상적용이 안됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1591]
## 버그 설명 ##
Map에 출력된 Data 값에 대한 색상적용이 안됨

## 예상한 행동 ##
Data 값에 따라 색상이 다르게 적용

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/66014356-9774ee80-e509-11e9-93f3-fb48cd70be2c.png)

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/1511#issuecomment-532993270

위 이슈와 마찬가지로 값 유형이 `TEXT`라서 발생하는 문제입니다.
`TEXT`일 때 강제 형변환하도록 개선해보겠습니다.
