### ISSUE TITLE
관리자 기능의 포트/URL 분리

### ISSUE THREAD

**Issue by nomota** [mobigen/IRIS-BigData-Platform#1592]
## 기능 요청 ##

국정원의 보안 가이드는, 관리자 기능을 엄격히 분리해서 별도 관리하기를 요구하고 있습니다.
만약 일반 사용자 기능과 관리자 기능이 하나의 포트를 공유하면, 전체를 다 관리자 기능으로 보고 전체가 관리자 기능과 같은 수준의 보안을 요청받게 된다는 뜻입니다.

특히 공공기관 납품시 국정원의 가이드라인을 엄격하게 지키는 사이트에서 IRIS를 여러 사람이 쓰게 하기 위해서 IP/Port/URL 을 사내 여러 IP에서 쓸 수 있도록 허용하는 단계에서 문제가 발생한다네요.

관리자 기능이 IP/Port 레벨에서 분리되어 있지 않으면, 방화벽에서는 모두다 관리자 기능으로 간주하고, 접근하는 개인들의 IP/Mac 레벨에서 일일이 지정을 해 줘야 한다는 것입니다. (현실적으로 불가능)

## 원하는 솔루션 설명 ##

관리자 기능에 해당하는 일부 기능을 별도의 Port/URL로 분리해서, 방화벽 설정을 따로 할 수 있도록 해 달라 입니다.

## 기타 ##

매우 급한 것은 아닙니다.

현재까지의 과제에서는 그런 요구가 없지만, 향후 공공기관 납품이 발생할 때, 문제가 될 수 있으니, 미리미리 분리 작업을 해야 하지 않을까 싶습니다.

**Comment by sunghoon** [comment]
해당 사항이 조금 더 구체화 되면 검토해 보겠습니다.
