### ISSUE TITLE
studio: 보고서를 목록에서 열면 정상, url 로 열면 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1596]
## 버그 설명 ##
- Reported by: 채병석 선임

## 내용
보고서 컴포넌트 중에 HTML Viewer에 HTML을 입력후 실행을 하면 해당 HTML이 정상적으로 보이는데 
보기로 실행 해보면 HTML 실행 결과가 보이지 않습니다.
보고서 리스트에 보시면 "(수원시)데이터관리_지표_상세보기_DSMS_테스트"  라는 보고서를 참고 하시면 될꺼 같습니다.
또한 보고서 리스트에서 해당 보고서를 열면 정상적으로 보이지만 url 로 열면 에러가 납니다.

## 스크린샷 ##
1. 보고서 보기로 열었을때 화면 입니다.
![image](https://user-images.githubusercontent.com/3411842/66358081-56b72280-e9ac-11e9-9010-5ee9cb659a06.png)

2. url 로 보기 (url : http://b-iris.mobigen.com/studio/exported/f1bff833c3e34f6dba92a5a0c44ad06a184bfa5d4bf14880a87d4ed49d16a395)
![image](https://user-images.githubusercontent.com/3411842/66358091-633b7b00-e9ac-11e9-80fd-4ca6e90569e3.png)

## 원인 추측 ##
postgreSQL connection 이 너무 많이 한 번에 붙어서 발생

**Comment by seungfwani** [comment]
위 현상으로 보이는 관련 로그가 보이지 않고,
여러번의 재현 시도를 하였으나 정상적으로 화면이 보여 확인이 안됩니다.

재현 시도 방법:
1. 보고서에서 "`(수원시)데이터관리_지표_상세보기_DSMS_테스트`" 보고서 "이름" 클릭 하여 확인
2. 보고서에서 "`(수원시)데이터관리_지표_상세보기_DSMS_테스트`" 보고서 "내보내기 URL -> 관리 -> URL 복사 -> 링크로 접속" 하여 확인
3. 메일로 보내주신 2번의 링크를 이용해 접속 하여 확인
4. 10개의 탭을 띄운 후 모든 탭을 빠르게 "`새로고침`" 하여 확인

**Comment by rhcpn** [comment]
#1594 #1595 
위의 두개와 같은 이슈 입니다.

**Comment by rhcpn** [comment]
HTML Viewer에 관련된 오류는 이미 충분히 보고가 되었고
Too Many Request 관련 이슈로 따로 분류 하는게 좋을것 같아 패스합니다.

**Comment by seungfwani** [comment]
- 확인내용공유

`19-10-11 오후 3시경`에 해당 이슈가 다시 발생하는 것을 확인 하였습니다.
하지만 `새로고침` 후 부터는 몇 번을 새로고침해도 에러는 발생하지 않았습니다.

`DSMS` 로그 중 `오후 2시~3시 10분` 사이의 로그에서 위에서 발생한 `Too many request` 라는 에러는 확인 할 수 없었습니다.
 `POSTGRESQL` 관련 로그 역시 확인 할 수 없었습니다.

- 의심내용

`DSMS` 측에서 발생 할 수 있는 경우를 찾던 중 의심되는 부분을 발견하였습니다.
-> `gunicorn` 실행 시 `worker-class` 의 종류가 default 값인 `sync(동기화)` 로 실행이 되고있었습니다.
-> 해당 문서를 확인하여 이해한 바로, `sync` 로 동작하는 `worker`는 `1번에 1개의 request` 를 조작 하고, 당시 `DSMS`의 `worker` 개수는 3개 였습니다.

- 수정내용

`sync`로 동작하던 `worker`의 옵션을 `async 인 gevent` 로 변경 하였습니다.

- 참고 문서
http://docs.gunicorn.org/en/stable/design.html

**Comment by seungfwani** [comment]
추가적으로, 이미 알고 계신 것일 수도 있지만 검색 결과를 공유드립니다.

`Too many follow-up requests : 21` 관련하여 검색을 해보니
`Retrofit` or `Okhttp` 라이브러리를 사용하여 `Redirect`를 할 때 발생할 수 있는 에러라고 합니다.
확인 해보시면 좋을 것 같습니다.

- 참고url
  - https://stackoverflow.com/questions/35132330/retrofit-too-many-follow-up-requests-21
  - https://github.com/square/okhttp/issues/2770

**Comment by sunghoon** [comment]
같은 이슈가 개별 페이지로 보는경우 많은 비율로 발생하고 있습니다. 

![스크린샷 2019-11-19 오후 12 12 44](https://user-images.githubusercontent.com/512653/69113273-e7157680-0ac5-11ea-87f5-8fb318f4304a.png)

**Comment by sunghoon** [comment]
@veldise @rhcpn @seungfwani 

해당 오류 메시지("Too Many follow-up ...")는 어느 단계에서 출력되는지 알려주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
이전 ValueLinkU 등에서는 로그가 발견되지 않아 웹 문제가 아니라고 생각했는데,
최근 studio 서비스쪽 로그에서 오류를 확인했습니다.

URL복사 기능으로 인해 로그인 없이 통신할때 문제가 있는 것 같습니다.

**Comment by swish1995** [comment]
@sunghoon @veldise @rhcpn @seungfwani
해당 문제는 URL 복사기능 사용시 인증 토큰 갱신 문제로 확인되어 관련 코드 수정하였습니다.
