### ISSUE TITLE
[데이터브라우징>검색] 검색어 입력시 오류 원인 확인 요청

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1599]
## 버그 설명 ##
해당 검색어는 기존에 동작하던 쿼리입니다.

현재 몇가지 동작하지 않는 원인을 파악 및 처리 방안을 확인 부탁 드립니다.

### 1. sum안에 - 연산자를 입력할 경우 에러가 발생함
- 검색 조건
    - SMS_RESOURCE_KERNEL
    - 최근 1분

- 검색 내용
    ```
    * | stats min(INTERRUPTS) as MIN_ITT,max(INTERRUPTS) as MAX_ITT by HOST | stats sum(MAX_ITT-MIN_ITT) as INTERRUPTS by HOST
    ```
- 에러 내용
    - 해당 방식으로 입력시 `angora error: <class 'pyspark.sql.utils.AnalysisException'>` 에러가 발생  
    - `sum(MAX_ITT-MIN_ITT)` 부분을 `sum(MAX_ITT - MIN_ITT)`로 띄어쓰기 할 경우 `angora error: <type 'exceptions.SyntaxError'>`에러발생  
    - `sum(MAX_ITT)`와 같은 방식으로 변경시 정상 동작 하고 있습니다.  

- `sum()` 안에 연산자를 쓰지 못하는 상태인지 확인 부탁 드립니다.

### 2. date_groupby 구문 에러
- 검색조건
    - SMS_SWITCH_INTERFACE
    - 전체 시간 or 최근 1분(데이터 없음)

- 검색 내용
    ```
    * | stats sum(IN_BPS),sum(OUT_BPS) by date_group(PARTITION_DATE, "1M")
    ```

- 에러 내용
    - `angora error: <class 'pyspark.sql.utils.AnalysisException'>` 에러 발생

**Comment by namjals** [comment]
수정 되었고 10월 24일 반영 예정입니다.
1. sum안에 - 연산자를 입력할 경우 에러가 발생함
sum 연산 시 tilt("`")가 아래와 같이 전체를 감싸서 발생한 문제입니다. 개별로 감싸도록 수정했습니다.
```
sum(`MAX_ITT-MIN_ITT`)
```
2. date_groupby 구문 에러
date_group(PARTITION_DATE, "1M")을 내부적으로 object로 만드는데 이를 다시 string으로 풀어주지 않고 쿼리하여 문제가 발생했습니다. string으로 풀도록 수정했습니다.
