### ISSUE TITLE
모델 생성시 동일 data-source 내의 조인 및 쿼리로 모델 생성 기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1600]
## 기능 요청 ##
보고서를 만들때 "데이터 모델| DSMS|SMS" 를 선택하여 만들수 있는데, 
IRIS 의 글로벌 테이블과 로컬테이블과의 조인을 하여 보고서를 만들려면 DSMS 를 통해서 쿼리를 만들어야합니다.
그렇다보니 데이터모델에 비해 시각화 등의 기능을 제대로 사용하기가 어렵습니다.

## 원하는 솔루션 설명 ##

 데이터 모델생성시 현재는 data-source 를 선택하고 1개 테이블을 선택하는데
데이터 모델생성시, 동일 data-source 에서 쿼리를 등록하여(다수 테이블의 조인쿼리) 데이터 모델을 생성할수 있으면 좋겠습니다.
즉, 오라클의 view 테이블을 생성하는 개념을 도입하면 정말 유용할거같습니다.
( 모델과 모델간의 조인까지는 아직 바라지 않습니다. 이것도 차차 적용되겠죠? ^^)

## 고려한 다른 대안 ##
 없슴

## 기타 ##
 없슴

**Comment by sunghoon** [comment]
모델뷰 기능이 배포되었습니다.
