### ISSUE TITLE
model-statsdetails 명령어에 sql where like 미적용

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1601]
## 버그 설명 ##
`model-statsdetails` 명령어에 `sql ... where ... like ...`가 적용되지 않는 것 같습니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/66540453-d4269280-eb66-11e9-9deb-5dfe06fc87bc.png)

### `model ... | count` 결과
query: `model name = 'NV_NEWS' model_owner = root start_date = 20190320000000 end_date = 20190326000000 | sql "select * from angora where TITLE like '%국회%'" | count`
```json
{
  "fields": [
    { "grouped": false, "type": "LONG", "name": "count" }
  ],
  "results": [
    [ 545 ]
  ]
}
```

### `model-statsdetails ...` 결과
query: `model-statsdetails name = 'NV_NEWS' model_owner = root start_date = 20190320000000 end_date = 20190326000000 field = SECTION | sql "select * from angora where TITLE like '%국회%'"`
```json
{
  "fields": [
    { "grouped": false, "type": "LONG", "name": "count" },
    { "grouped": false, "type": "TEXT", "name": "value" }
  ],
  "results": [
    [ 16613, "세계" ],
    [ 14413, "사회" ],
    [ 13766, "정치" ],
    [ 13538, "경제" ],
    [ 5811, "생활/문화" ],
    [ 3299, "IT/과학" ],
    [ 1098, "오피니언" ]
  ]
}
```

**Comment by seungfwani** [comment]
@veldise 
질문해 주신 내용은 버그가 아닙니다.
`model-statsdetails ... | sql` 쿼리에서 sql에 지정한 filtering 조건은 적용이 되지 않습니다.

`sql` 명령어는 앙고라 초기에 사용자에게 편의를 위해 제공한 명령어입니다.
점차적으로 대체 가능한 명령어가 추가되고 있으며,
`sql` 명령어는 추후 앙고라에서 지원하지 않게 될 것 입니다.

위에 설명해 주신 쿼리는 아래의 쿼리를 이용하면 정상적인 filtering의 결과를 볼 수 있습니다.
query: `model-statsdetails name = 'NV_NEWS' model_owner = root start_date = 20190320000000 end_date = 20190326000000 field = SECTION TITLE like '%국회%'`

![image](https://user-images.githubusercontent.com/46172579/69701405-3c89fd00-1130-11ea-827e-5d964b598e33.png)
![image](https://user-images.githubusercontent.com/46172579/69702020-9d660500-1131-11ea-8d68-a420ea607eda.png)
