### ISSUE TITLE
ValueLinkU / 메뉴 / 새창에 실행 옵션 추가

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1602]
## 기능 요청 ##
메뉴의 외부 URL 설정의 경우 새창에 화면을 띄울수 있는 옵션 기능 추가

![image](https://user-images.githubusercontent.com/4444717/66544485-3f766180-eb73-11e9-9300-aea7a7c457d7.png)

**Comment by veldise** [comment]
운영서버까지 배포/적용된 내용이라 닫습니다.
