### ISSUE TITLE
ValueLinkU / IE에서 뒤로가기 버튼 실행시 로그인 화면이 나타남

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1603]
## 버그 설명 ##
IE에서 화면 접근시 뒤로 가기버튼을 실행하면 로그인 화면이 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IE브라우저로  www.valuelinku.com 접속(peace@mobigen.com / !1q2w3e4r5t)
2. 밸류링크유_BIS 링크 실행
3. IRIS Analyzer 실행된 화면에서 뒤로가기 버튼 실행

## 예상한 행동 ##
로그인 화면이 나타나지 않음

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/66544672-c297b780-eb73-11e9-803a-3f6769ff5fa5.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by JeongHeeDong** [comment]
어떻게 진행 되고 있는지 진행 상황 코멘트 요청 드립니다.

**Comment by veldise** [comment]
@JeongHeeDong 
T-CORE, KOTRA, 수원시, MDT 관련 업무 진행으로 인해 지체되어 있었습니다.
IE에서만 발생하는 문제라 원인 파악이 어려워 시간이 조금 더 필요합니다.
