### ISSUE TITLE
[ML 명령어] 에서 predict 결과에 누락된 부분이 많아서 확인/검증이 안됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1604]
## 버그 설명 ##
fit  .. into 모델  로 저장한 후
test 데이터로  'predict 모델' 한  결과가 검증 자체가 안 됩니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. myiris 계정의 분석템플릿  CMD_cast_syslog_DC_predict_org2  실행
2. 시간이 5분 정도 소요됨
3. predict의 번호가 무엇을 의미하는 지 정보가 없음

## 스크린샷 ##
* 분석템플릿 선택
<img width="947" alt="스크린샷 2019-10-10 오후 5 23 19" src="https://user-images.githubusercontent.com/5126497/66552374-2fb34900-eb84-11e9-8a02-b7e44d4d578b.png">

* 분석 결과에서  predict 값이 의미하는 HOST 가 무엇인지 확인할 수 없음
<img width="1006" alt="스크린샷 2019-10-10 오후 5 22 59" src="https://user-images.githubusercontent.com/5126497/66552425-4194ec00-eb84-11e9-8f0b-3ecffc626e79.png">

=> 데이터모델 : cast_syslog_org2  은 syslog 데이터를 전처리한 것임
=> 알려고 하는 Y 값은 HOST 임
=> 따라서 predict 는 HOST 가 나옴. 그런데 학습과정에서 HOST 는 숫자로 1:1 로 인덱싱됨
=> 예를 들어 gcs1 이 1번으로, gcs2 는 2번으로 등의 인덱싱정보를 알 수 있도록 predict 결과가 나와야 함

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
- 위의 쿼리의 순서를 간단히 표현하자면 아래와 같습니다.
`model | sort | scaler | indexer | (fit/predict)`

1. predict의 결과로 숫자만 나오는 것은 현재 설계상 의도한 바가 맞습니다.
2. 하지만, 설계상 고려하지 못한 부분이 있어 이 부분의 설계부터 수정을 해야합니다.
3. indexer 명령어를 수정하여 예측 결과를 원본 데이터로 보여 줄 수 있도록 할 계획입니다.
4. 아래는 설계상 고려하지 못한 부분입니다.

- indexer 
  - indexer는 선택한 inputColumn 의 데이터를 outputColumn으로 인덱싱을 하는 명령어입니다.
  - 이때, inputColumn의 현재 데이터를 기반으로 인덱싱을 하기때문에 fit을 할때와 predict 할때의 데이터가 다르면 결과도 다르게 나타납니다.
  - indexer 명령어로 fit/predict 시 같은 값을 참조할 수 있도록 수정할 계획입니다.
  - indexer 명령어의 규격도 변경될 것이므로 이에 대한 내용은 수정 완료 후 문서공유 드리겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 본 이슈에 대한 대응 부탁드립니다.

**Comment by anhm** [comment]
해당 이슈는 이슈 정리를 위해서 일단 닫도록 하겠습니다.
predict 고도화 작업시 해당 상황을 고려해 방향을 잡도록 하겠습니다.
