### ISSUE TITLE
피벗 / 분석 템플릿 불러오기 안됨

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1609]
## 버그 설명 ##
피벗 화면에서 분석 템플릿 불러오기(더블 클릭)이 안됩니다.

**Comment by veldise** [comment]
@pjh0347 @namjals 

query-analysis API 결과가 이상합니다. 확인바랍니다.
결과 sort값은 문자열이어야 하는데, Array 이고 `[null, null, null]`과 같이 이상한 값이 반환됩니다.

request:
`GET /query-analysis?type=tree&analysis-type=pivot`
request body:
```json
{"q":"* | pivot count(*) SPLITROW 'date_group(\"DATETIME\", \"1M\")'"}
```

response:
```json
{
  "data": {
    "q": "*", 
    "pivot": {
      "sort": [
        null, 
        null, 
        null
      ], 
      "rows": [
        {
          "field": "DATETIME", 
          "unit": "1M"
        }
      ], 
      "cells": [
        {
          "field": "*", 
          "func": "count"
        }
      ], 
      "cols": [], 
      "filters": [], 
      "col_size": null
    }
  }
}
```

**Comment by namjals** [comment]
pivot의 sort [사용법](https://github.com/mobigen/B-IRIS-Data-Discovery-Service/blob/master/docs/ko/commands/pivot.md)이 업데이트 되었습니다.
"sort": [
        null, 
        null, 
        null
      ]
첫번째 null값은 기존에 사용하던 asc, desc 정보
두번째 null값은 SPLITROW로 지정된 컬럼에 대한 asc, desc 정보
세번째 null값은 SPLITCOL로 지정된 컬럼에 대한 asc, desc 정보

모두 null값으로 나온이유는 sort관련 명령어가 없기 때문이며, 의도한 값입니다.
첫번째 null값을 지우지않고 유지한 이유는 기존에 사용되던 명령어에 대한 호환때문입니다.

**Comment by veldise** [comment]
@namjals 
UI는 아직 수정 전이므로 해당 부분 롤백해주시기 바랍니다.

**Comment by veldise** [comment]
@namjals 
pivot 관련 메일 언제 보내셨나요? 메일함에서 찾을 수가 없네요.

**Comment by namjals** [comment]
@veldise
UI는 아직 수정 전이므로 해당 부분 롤백해주시기 바랍니다.
-> 일단 `/query-analysis`에서는 sort의 0번째 값만 반환하도록 하겠습니다. 

pivot 관련 메일 언제 보내셨나요? 메일함에서 찾을 수가 없네요.
-> 아래 제목으로 9월 25일에 보냈습니다.
     ` [Angora] query-analaysis API 통합 가이드 공유`

**Comment by veldise** [comment]
@namjals 
말씀하신 메일 내용에는 문서 공유에 대한 내용만 있고 API 변경점에 대한 설명이 없습니다.
다음에 메일 보내실 때는 변경사항도 같이 보내주세요.

**Comment by namjals** [comment]
@veldise
변경사항에 대해 메일드렸습니다. 
아직은 `sort의 0번째 값만 반환`하는 상태이고 문서의 API대로 UI에서 개발이 완료되면 Angora도 그에 맞춰 수정해놓겠습니다.

**Comment by veldise** [comment]
본문 이슈는 해결된 상태라 닫습니다.
sort 관련하여 UI 개발은 별도 이슈에서 진행하겠습니다.
