### ISSUE TITLE
[수원시] IRIS웹 DB브라우저 에러 알람 확인 요청

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#1611]
## 버그 설명 ##
수원시에 설치된 IRIS 웹에 접속하여 로그인 이후, DB브라우저를 클릭했을 시 "다시 로그인을 해주세요"라는 알람이 떴습니다.

이후, 새로고침을 "테이블 목록" 오른쪽의 새로고침으로 보이는 버튼을 클릭했을 시, 영문 알람이 떴습니다.

## 재현하는 방법 ##
수원시에 설치된 IRIS 웹에 접속하여 로그인 이후, DB브라우저를 클릭했을 시 "다시 로그인을 해주세요"라는 알람이 떴습니다.

이후, 새로고침을 "테이블 목록" 오른쪽의 새로고침으로 보이는 버튼을 클릭했을 시, 영문 알람이 떴습니다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

------------ 원본 메일 내용 ------------
보낸 사람 : "홍준표"<jphong@mobigen.com>
받는 사람 : "최영철" <choiycdev@mobigen.com>
참      조 : "박세종" <rhcpn@mobigen.com>, "수원시-inner" <suwon-inner@mobigen.com>, "김대호" <dhkim@mobigen.com>
메일 제목 : [수원시] IRIS웹 DB브라우저 에러 알람 확인 요청
보낸 날짜 : 2019/10/10 14:43

안녕하세요. DT개발2팀 홍준표 선임입니다.

수원시에 설치된 IRIS 웹에 접속하여 로그인 이후, DB브라우저를 클릭했을 시 "다시 로그인을 해주세요"라는 알람이 떴습니다.

이후, 새로고침을 "테이블 목록" 오른쪽의 새로고침으로 보이는 버튼을 클릭했을 시, 영문 알람이 떴습니다.

해당 현상이 정상적인 현상인지 확인 요청드립니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/66724543-118a6900-ee62-11e9-96c2-f7197106678b.png)

![image](https://user-images.githubusercontent.com/3411842/66724547-25ce6600-ee62-11e9-85f5-b9b56eef790c.png)

**Comment by veldise** [comment]
에러 알람(Alert)이 발생하는 원인은 현재 웹으로 로그인한 유저(ex) suwon_dev)의 계정으로
IRIS-DB에 접속할 수 없어 발생하는 문제로 보입니다.

DB 브라우저 기능이 정상적으로 동작하기 위해서는 IRIS-DB에 웹 유저와 동일한 아이디가 존재해야 합니다.
suwon_dev 아이디가 현재 IRIS-DB에 없는 것으로 추측됩니다.
수원시에 설치된 IRIS-DB의 유저 목록 확인이 필요합니다.

**Comment by veldise** [comment]
@홍준표 선임

1. IRIS-DB의 유저 목록 확인
웹 계정과 동일한 계정이 생성되어 있는지 확인해야 합니다. 유저 목록 확인 방법은 플랫폼연구팀에 문의 바랍니다.

2. root 계정으로 접속해서 정상 동작하는지 확인
root 계정 비밀번호는 network.conf 파일의 meta.datasource.pass 설정을 따릅니다.
파일 위치 등은 수원시에 IRIS 설치를 진행한 분께 문의해주시기 바랍니다.

root 로 정상 동작할 경우, 원인 파악을 위해 로그가 필요합니다. 아래 위치의 로그를 보내주시기 바랍니다.
<IRIS 설치 위치>/service/logs/meta/application-<날짜>.log

root로 비정상 동작할 경우, IRIS-DB의 연결 설정이 정상인지 확인해야 합니다.
이 설정은 마찬가지로 network.conf 파일에 있습니다.

**Comment by veldise** [comment]
db-browser 서비스의 application.properties 파일에 root 계정 비밀번호가 잘못 설정되어 발생한 문제였습니다.
운용기술연구팀 강준희 선임님이 확인 및 처리해주셨습니다.
