### ISSUE TITLE
ValueLinkU / Studio / 이미지 URL생성 기능

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1612]
## 기능 요청 ##
보고서 생성시 많은 이미지를 사용하는 경우가 발생됨
현재 동일한 이미지를 여러 보고서에서 사용 하고자 할 경우 각 보고서에 개별 추가를 해야함
(다른 방법으로 특정 URL에 있는 이미지를 사용 할 수도 있으나, 외부 저장소가됨)

특정 보고서에 사용된 이미지에 대한 URL을 확인 할 수 있는 기능 추가
또는 이미지 리소스 게시판 같이 별도로 이미지 리스트를 관리 하는 기능 추가

**Comment by sunghoon** [comment]
@eumminsun 아래와 같은 방향으로 기획 진행 바랍니다. 

- 이미지 파일은 IRIS 내부 minio에 저장하여 사용 관리 할 수 있도록.
- 지금은 DB 인코딩/디코딩 인데 성능 저하의 원인
