### ISSUE TITLE
ValeuLinkU/검색/ where in 조건시 오류 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1615]
## 버그 설명 ##
DSL실행시 where in 조건으로 실행하는 경우 오류 발생

`* | where LOC_CODE in (7, 14, 11, 1, 18, 12, 9)`

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/66730044-09462400-ee8a-11e9-8e5b-6bb94ce56262.png)

**Comment by namjals** [comment]
수정 버전에 대해 배포파일 빌드중이며 배포까지 15분정도 더 걸릴것으로 보입니다.

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/66732962-d8b9b680-ee98-11e9-8669-173b6e5eb78e.png)
