### ISSUE TITLE
ValueLinkU/검색/round명령어 결과값이 맞지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1617]
## 버그 설명 ##
DSL로 round명령어 실행시 결과가 맞지 않음
round 3자리로 조회 했으나 2자리로 출력됨

## 스크린샷 ##
round 3자리로 조회 했으나 2자리로 출력됨

![image](https://user-images.githubusercontent.com/4444717/66737980-5df89780-eea8-11e9-882b-5168dc907bd7.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
```
model name = 'LPI 지수' model_owner = valuelinku | sql "select COUNTRY, YEAR, LPI_RANK, LPI_SCORE, CUST_RANK, CUST_SCORE, INF_RANK, INF_SCORE, IS_RANK, IS_SCORE, LC_RANK, LC_SCORE, TT_RANK, TT_SCORE, TL_RANK, TL_SCORE from angora " | round 3 col=[LPI_SCORE]
```
```js
{
    "status": {
      "current": 1, 
      "total": 1
    }, 
    "fields": [
      { "grouped": false, "type": "TEXT", "name": "COUNTRY" }, 
      { "grouped": false, "type": "TEXT", "name": "YEAR" }, 
      { "grouped": false, "type": "INTEGER", "name": "LPI_RANK" }, 
      { "grouped": false, "type": "TEXT", "name": "LPI_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "CUST_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "CUST_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "INF_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "INF_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "IS_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "IS_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "LC_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "LC_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "TT_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "TT_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "TL_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "TL_SCORE" }
    ], 
    "isEnd": true, 
    "results": [
      [ "Singapore", "2007", 1, "4.190", 3, 3.9, 2, 4.27, 2, 4.04, 2, 4.21, 1, 4.25, 1, 4.53 ], 
      [ "Netherlands", "2007", 2, "4.180", 1, 3.99, 1, 4.29, 1, 4.05, 1, 4.25, 4, 4.14, 5, 4.38 ], 
      [ "Germany", "2007", 3, "4.100", 4, 3.88, 3, 4.19, 4, 3.91, 3, 4.21, 5, 4.12, 8, 4.33 ], 
    // ... 후략 ...
```

**Comment by seungfwani** [comment]
@veldise 
위의 명령어를 통해서  실행하여 나온 결과를 확인해본 바로,
Angora에서 자릿수 결과리턴은 잘되는 것으로 보입니다.

아래 response 결과에서 `fields` 부분을 보면
round 명령을 적용한 필드인 `LPI_SCORE`는 4번째에 있습니다.

response의 `results`에서 4번째 결과를 보면 `"4.190", "4.180", "4.100"` 이러한 값으로 3자리 수를 표현하고 있습니다.

UI에서 이 데이터를 화면에 표시 할 때 처리 방법을 확인해 봐야 할 것으로 보입니다.

response:
```
{
    "status": {
      "current": 1, 
      "total": 1
    }, 
    "fields": [
      { "grouped": false, "type": "TEXT", "name": "COUNTRY" }, 
      { "grouped": false, "type": "TEXT", "name": "YEAR" }, 
      { "grouped": false, "type": "INTEGER", "name": "LPI_RANK" }, 
      { "grouped": false, "type": "TEXT", "name": "LPI_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "CUST_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "CUST_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "INF_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "INF_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "IS_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "IS_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "LC_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "LC_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "TT_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "TT_SCORE" }, 
      { "grouped": false, "type": "INTEGER", "name": "TL_RANK" }, 
      { "grouped": false, "type": "REAL", "name": "TL_SCORE" }
    ], 
    "isEnd": true, 
    "results": [
      [ "Singapore", "2007", 1, "4.190", 3, 3.9, 2, 4.27, 2, 4.04, 2, 4.21, 1, 4.25, 1, 4.53 ], 
      [ "Netherlands", "2007", 2, "4.180", 1, 3.99, 1, 4.29, 1, 4.05, 1, 4.25, 4, 4.14, 5, 4.38 ], 
      [ "Germany", "2007", 3, "4.100", 4, 3.88, 3, 4.19, 4, 3.91, 3, 4.21, 5, 4.12, 8, 4.33 ], 
    // ... 후략 ...
```

**Comment by veldise** [comment]
@seungfwani 
3자리로 반환되고는 있으나, 소수점 3번째 자리수가 모두 0입니다. 데이터와 비교하여 정확한 결과인지 재확인 바랍니다.

![image](https://user-images.githubusercontent.com/3411842/66809469-5d273a80-ef68-11e9-9b44-cf5f0ff56393.png)

**Comment by seungfwani** [comment]
- 해당 컬럼(`LPI_SCORE`)은 아래 사진과 같이 소수점 2 or 1 자리 숫자입니다.
![image](https://user-images.githubusercontent.com/46172579/66878190-9e186100-eff3-11e9-9b1f-3483672e687a.png)

- round 명령어는 소수점 아래 표현을 할 때 자릿수를 맞추는 명령어로 아래와 같이 표현이 되는 것을 의도한 것입니다.
  - `3.14` 데이터에 `round 3`를 할 경우: `3.140` 
  - `3.14159` 데이터에 `round 3` 를 할 경우: `3.142`

- 추가적으로, UI의 결과가 Angora에서 리스폰스 된 값에 소수점을 붙여서 표현하는 것 같습니다.
  - UI 결과 및 Angora response 중 일부
![image](https://user-images.githubusercontent.com/46172579/66878430-ce143400-eff4-11e9-8874-4cf6775e4ba0.png)
  - 원본 데이터 검색 결과 중 일부
![image](https://user-images.githubusercontent.com/46172579/66878461-f0a64d00-eff4-11e9-80b1-76a1e4a6ab51.png)

**Comment by veldise** [comment]
@seungfwani 
UI의 "개인설정 > 소수점 자리수 설정" 기능에 의해 소수점을 붙이는 것은 맞습니다.
다만 UI의 소수점 자리수 표현 기능 관련해서는 이전에 발생한 다른 이슈에서 해결 및 확인이 완료된 내용입니다.

@JeongHeeDong 
정희동 팀장님, 내용 확인 부탁드립니다.

**Comment by JeongHeeDong** [comment]
@veldise 
최영철 선임님, 개인설정에서 지장한 소숫점 표현은 최대 표현 자리수로 이해하고 있습니다.
설정이 2로 되어 있더라도 1자리까지만 있으면, 1자리만 보여지는것이 맞는지, 무조건 소수점을 2자리로 보여 주고 있는지 확인 부탁 드립니다.

현재 개인설정과 round명령어간에 어느것이 최종적으로 적용되어 나타나느냐의 문제는 위 확인 후 다시 논의가 필요할 것으로 보입니다.

**Comment by veldise** [comment]
@JeongHeeDong 
소수점 자리수 설정은 AA연구팀 요구사항에 따른 것으로, 최대 표현 자리수가 아니라 고정입니다.
이전에 설정이 `2`로 되어있어도 1자리만 나오던 것은 버그입니다.

사용자가 입력한 명령어에 따라 UI 표현이 달라져야 한다면 DSL parsing 이 필요하므로
말씀하신대로 별도 논의가 필요합니다.

**Comment by veldise** [comment]
@JeongHeeDong 
소수점 자리수 설정을 off 하는 UI 기능을 추가하는 방안도 있을 것 같습니다.

**Comment by veldise** [comment]
재확인 결과, 결과 컬럼 유형이 `TEXT`인데 소수점 자리수 설정이 적용되는 문제가 있습니다.
조치하도록 하겠습니다.

**Comment by seungfwani** [comment]
@JeongHeeDong 
추가적인 사항을 말씀드리겠습니다.

그룹장님과 협의 하에 `round` 명령어에 옵션을 추가하였습니다.
옵션은 `fixed` 로, default = False 입니다.

- 옵션의미 
  - `fixed=False` 일때는 자릿수 반올림은 하지만, 결과에 자릿수를 고정하지 않습니다.
    - ex) `3.14` 데이터에 `round 3`을 하면, 결과는 `3.14` 입니다.
    - ex) `3.14159` 데이터에 `round 3`을 하면, 결과는 `3.142` 입니다.
  - `fixed=True` 일때는 자릿수 반올림도 하고, 결과에 자릿수를 고정합니다.
    - ex) `3.14` 데이터에 `round 3`을 하면, 결과는 `3.140` 입니다.
    - ex) `3.14159` 데이터에 `round 3`을 하면, 결과는 `3.142` 입니다.

문서에 이러한 내용을 작성해 놓았고,
배포 후 메일로 공유해드리겠습니다.

**Comment by veldise** [comment]
UI쪽은 운영서버에 패치 완료했습니다.

@seungfwani 
Angora도 수정 완료되었다면 이슈 닫아주세요.

**Comment by seungfwani** [comment]
Angora도 수정 완료되었습니다.
