### ISSUE TITLE
ValueLinkU/사이트 공통으로 Google Analytics 스크립트 등록 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1618]
## 버그 설명 ##

ValueLinkU의 IRIS Analyzer 사이트 공통으로 Google Analytics 스크립트 등록 요청.

[등록 스크립트]
[ValuelinkU  BIS Google Analytics.txt](https://github.com/mobigen/IRIS-BigData-Platform/files/3726825/ValuelinkU.BIS.Google.Analytics.txt)

**Comment by veldise** [comment]
운영서버에는 해당하지 않고, ValueLinkU 에는 처리되어 닫습니다.
