### ISSUE TITLE
IRIS 데이터브라우저  > 시각화 > 클러스터 맵 기능 추가 요청

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1621]
## 기능 요청 ##
위도/경도 데이터가 있는 데이터 모델에 각 row 마다 개수가 있는 column이 없어도 row마다 1의 개수를 임의로 두어 지도 위에 표현이 가능했으면 합니다. 

## 원하는 솔루션 설명 ##

수원시 행사/공사 데이터엔 각 row마다 행사/공사의 설명 + x,y 좌표 데이터가 있습니다. 
다만, 각 row마다 '개수'가 표현된 데이터가 없어서 시각화 > 클러스터 맵에서 x,y 좌표를 대입하고 합계/개수/평균,.. 에 들어갈 마땅한 데이터가 없습니다.

그래서 해당 항목에, 예를들어 시각화 > 막대형 에서 Y축에 임의로 표현되는 '이벤트 개수'와 같이 기본 row당 '1'로 개수를 default로 두었으면 합니다.

## 고려한 다른 대안 ##
None

## 기타 ##

아래와 같이 "막대형"에선 세로 축에 "이벤트 개수"라는 디폴트로 제공되는 cnt가 있는 것 같습니다.
![e1](https://user-images.githubusercontent.com/8993205/66802299-f0f00b00-ef56-11e9-9eef-10c1f8450afd.jpg)

클러스터맵의 경우 아래와 같이 항목을 채워넣어야 하는데, 마땅한 데이터가 없으면 채워넣을 수 없습니다.
![e2](https://user-images.githubusercontent.com/8993205/66802304-f3526500-ef56-11e9-9aee-3cb34828cec3.jpg)

**Comment by veldise** [comment]
현재 아래와 같이 기본은 "이벤트 개수"(`count`)로 설정되도록 수정중입니다.

![image](https://user-images.githubusercontent.com/3411842/67729853-20624580-fa36-11e9-8f6c-dcf6429dc670.png)


@pjh0347
아래와 같이 `geostats` 명령어를 수행하면 에러가 반환됩니다. 확인 부탁드립니다.
```
model name = 'GEO_geostats_hdfs' model_owner = dani start_date = 20191029102100 end_date = 20191029102237 | geostats latitude longitude count
```

```
 { message: 'Reference \'None\' is ambiguous, could be: None, None.; line 1 pos 0',
  type: '<class \'pyspark.sql.utils.AnalysisException\'>',
  trace: 'Traceback (most recent call last):\n  File "/app/src/main/python/angora/interface/restful/handlers/supporthandlers/backgroundresult.py", line 89, in run\n  File "/app/src/main/python/angora/interface/restful/handlers/query.py", line 265, in _response\n  File "/app/src/main/python/angora/core/engine.py", line 256, in query\n  File "/app/thirdparty/spark-2.3.1-bin-hadoop2.7/python/pyspark/sql/dataframe.py", line 1216, in selectExpr\n    jdf = self._jdf.selectExpr(self._jseq(expr))\n  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1257, in __call__\n    answer, self.gateway_client, self.target_id, self.name)\n  File "/app/thirdparty/spark-2.3.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 69, in deco\n    raise AnalysisException(s.split(\': \', 1)[1], stackTrace)\nAnalysisException: u"Reference \'None\' is ambiguous, could be: None, None.; line 1 pos 0"\n' }
```

**Comment by namjals** [comment]
@veldise 
아래 케이스의 경우 데이터가 없어, column이 `cluster_id, latitude, longitude, None, None`이 되어 angora 엔진에서 처리를 못해 에러가 발생했습니다.
```
model name = 'GEO_geostats_hdfs' model_owner = dani start_date = 20191029102100 end_date = 20191029102237 | geostats latitude longitude count
```
위처럼 데이터가 없는 경우, 아래와 같이 field만 채우고 데이터는 빈리스트로 반환하도록 수정했습니다. 금주 목요일 배포 예정입니다.
```
{
  "status": {
    "current": 1,
    "total": 1
  },
  "fields": [
    {
      "grouped": false,
      "type": "TEXT",
      "name": "cluster_id"
    },
    {
      "grouped": false,
      "type": "FLOAT",
      "name": "latitude"
    },
    {
      "grouped": false,
      "type": "FLOAT",
      "name": "longitude"
    },
    {
      "grouped": false,
      "type": "TEXT",
      "name": "count"
    }
  ],
  "isEnd": true,
  "results": [],
  "ui": null,
  "save": true
}
```

**Comment by veldise** [comment]
UI 쪽은 11월4일 이후 배포 예정입니다.
