### ISSUE TITLE
angora: directdb tablelist 명령어 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1622]
## 버그 설명 ##
현재 모든 연결 유형에 대하여 `directdb tablelist` 요청시 에러가 발생하는 것으로 보입니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/66811336-decc9780-ef6b-11e9-95a6-b94ad1c24588.png)

## 로그 ##
```
directdb tablelist connector_id = 2
```
```js
{"message":"angora error: <type 'exceptions.AttributeError'>\n'NoneType' object has no attribute 'schema'"}
```

**Comment by seungfwani** [comment]
패키지 파일에 문제가 있어 재빌드 하였고,
운영서버에 바로 적용하였습니다. 현재는 문제없습니다.
![image](https://user-images.githubusercontent.com/46172579/66886680-307c2d00-f013-11e9-9fcf-d7c7fb88db7c.png)
