### ISSUE TITLE
[전력연구원] 피벗 오류

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1625]
## 버그 설명 ##
피벗 분석에 펄터 조건을 2개이상 설정시 오류 발생합니다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/29471177/66993274-3acb2380-f106-11e9-8a04-af5e6befd107.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

[오류로그.txt](https://github.com/mobigen/IRIS-BigData-Platform/files/3738258/default.txt)

**Comment by veldise** [comment]
@pjh0347 
원인 파악 부탁드립니다.

**Comment by namjals** [comment]
앙고라 배포일자가 9월 20일 이전인가요? 
쿼리 명령어에 대해 틸트가 잘못 입력된거 같습니다.
최근 배포파일로 패치하면 해결될 것으로 보입니다.

**Comment by namjals** [comment]
마지막 배포가 8월이라고 하여 재배포 요청드렸습니다. 배포 후 확인이 필요합니다.

**Comment by chohi22** [comment]
![KakaoTalk_20191024_154125454](https://user-images.githubusercontent.com/29471177/67463316-28a83280-f67c-11e9-8faa-c0608710de96.png)

b-iris-data-discovery-service-dist-v2.5_728d8fc-20191022.tar.gz 버전으로 배포후 확인 완료 했습니다.
