### ISSUE TITLE
MDT / Studio / Map출력된 데이터가 동적인 경우 색상 표현이 안됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1627]
## 버그 설명 ##
Map표현하기 위한 데이터를 동적으로 생성하고자 하는 경우 최초 설정한 데이터 선택 값이, 변경된 값으로 변경되지 않아 생상 표현이 되지 않음

## 예상한 행동 ##
선택한 지표의 값으로 색상 표현

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/67070043-f00ae380-f1b9-11e9-9693-abf2a76e0024.png)

**Comment by minjaekang7** [comment]
위 현상이 사라졌기때문에 클로즈하고 다시 재현되면 오픈하겠습니다.
