### ISSUE TITLE
지금 본사 biris.mobigen.com 이슈있나요?

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1637]
## 버그 설명 ##
데이터 브라우저 검색자체가 안됨

금일 오후 고객시연으로 보고서 점검중에 아래와 같이 응답이 없슴

<img width="874" alt="응답없슴" src="https://user-images.githubusercontent.com/5468183/67254679-598c3a00-f4b9-11e9-9117-9eca6f41fe5d.PNG">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
Angora 관련 배포가 잘못되어 원복했다는 연락 받았습니다. 댓글 남기는 시점에 문제가 발생 하지 않는것을 확인 하였습니다.
