### ISSUE TITLE
[KOTRA 요청]피벗 분석에서 열 선택 추가

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1638]
## 기능 요청 ##
피벗 분석시
행 선택은 추가가 가능한데
열 선택은 추가가 안됩니다. 추가가 가능한가요?

**Comment by seungfwani** [comment]
제가 이해한 질문 의도가 맞는지 확인해 주시면 감사하겠습니다.

아래 사진처럼 행 선택은 1개를 선택 했음에도, 추가가 가능하지만,
열 선택은 2개 이상 선택 할 수 없다고 질문 하시는게 맞나요?

![image](https://user-images.githubusercontent.com/46172579/72321811-2d630c80-36e8-11ea-8cdd-eb89a2a60b46.png)

**Comment by seungfwani** [comment]
혹시 위에 질문한 내용이 맞다면,

현재는 pivot의 열 선택은 1개만 할 수 있고,
2 개 이상 추가하는 것은 검토가 필요합니다.

**Comment by yariyarishow** [comment]
> 제가 이해한 질문 의도가 맞는지 확인해 주시면 감사하겠습니다.
> 
> 아래 사진처럼 행 선택은 1개를 선택 했음에도, 추가가 가능하지만,
> 열 선택은 2개 이상 선택 할 수 없다고 질문 하시는게 맞나요?
> 
> ![image](https://user-images.githubusercontent.com/46172579/72321811-2d630c80-36e8-11ea-8cdd-eb89a2a60b46.png)
> 
> 혹시 파악한 내용이 맞다면,
> 
> 현재는 pivot의 열 선택은 1개만 할 수 있고,
> 2 개 이상 추가하는 것은 검토가 필요합니다.

네 파악하신 내용이 맞습니다. 
본 건은 일정이 시급한게 아니니 추후 검토 의견 주시면 그에 맞게 대응하겠습니다.

**Comment by seungfwani** [comment]
검토 상으로 해당 동작은 가능합니다.

※ 주의점 
여러 컬럼을 선택하였을 때 표현 방법에 대해서는 엑셀과 차이점이 있습니다.

앙고라는 컬럼의 깊이가 1이기 때문에 이중 컬럼의 구조를 가질 수 없습니다.
앙고라는 아래와 같은 결과가 나옵니다.
![image](https://user-images.githubusercontent.com/46172579/72769596-972a6b80-3c3e-11ea-8c5d-e898413a2548.png)

앙고라의 소요기간은 3일정도 예상됩니다.

**Comment by yariyarishow** [comment]
네. 알겠습니다. 
일정은 2월 10~15 사이에 적용하려고 합니다. 
그전에 완료해주시면 됩니다. 
감사합니다.

**Comment by veldise** [comment]
@yariyarishow 
UI 적용 일정은 별도입니다. 현재 2월 15일까지 일정에 고려되어있지 않습니다.

**Comment by yariyarishow** [comment]
네 알겠습니다.

**Comment by seungfwani** [comment]
앙고라는 개발 완료되었습니다.
`SPLITCOL` 부분을 여러개 선택할 수 있으며, 각 피벗 값을 이어주는 문자는 `SEP 예약어`를 통해서 설정가능합니다. (default로는 $ 로 구분됩니다.)

pivot 명령어 문법입니다. `SPLITCOL` 부분이 수정되었습니다.
```
... | pivot FUNCTION (ASLIAS)? (, FUNCTION (ASLIAS)?)* (SPLITROW FIELD_NAME(, FIELD_NAME)*)? (SPLITCOL FIELD_NAME(, FIELD_NAME)* (SEP split_str)?)? (FILTER filter_expr)? (COLSIZE N)? ((SORT order)? | (SORTROW order)? (SORTCOL order)?)
```

기본 분리문자($) 로 동작하는 모습입니다.
```
* | pivot count(*) as cnt, avg(LEVEL_INT) as avg SPLITROW HOST SPLITCOL FACILITY, PRIORITY SORTCOL asc
```
![image](https://user-images.githubusercontent.com/46172579/73409709-6388c900-4343-11ea-8cf6-3d4340d74749.png)

`SEP` 예약어를 통해 `#`으로 분리하는 모습입니다.
```
* | pivot count(*) as cnt, avg(LEVEL_INT) as avg SPLITROW HOST SPLITCOL FACILITY, PRIORITY SEP # SORTCOL asc
```
![image](https://user-images.githubusercontent.com/46172579/73409933-122d0980-4344-11ea-8edc-dd51b7bfb41d.png)

**Comment by veldise** [comment]
@seungfwani 
query-analysis API 도 관련 처리 후 변경된 API 문서를 보내주시기 바랍니다.

**Comment by veldise** [comment]
패치내역에는 누락되었는데 5월 14일자로 웹 UI도 기능 추가되었습니다.
