### ISSUE TITLE
[KOTRA] 데이터브라우저 > 검색 > GUI 기반으로 변경 가능?

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1639]
## 기능 요청 ##
데이터 브라우저 > 검색 화면에서
데이터 조회시 검색어 또는 명령어를 입력해서 검색하게 되어 있습니다. 
이를 GUI 기반으로 변경할 수 있나요?

**Comment by sunghoon** [comment]
참고 하도록 하겠습니다.
