### ISSUE TITLE
[KOTRA]데이터 검색 결과에 대한 재그룹화

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1640]
## 기능 요청 ##
[상황]
1. 상품별 / 국가별로 수출입 금액 데이터가 있음
2. 사용자는 특정 상품에 대한 국가별 수출입 금액을 조회하고 싶음

[전개]
1. 사용자가 국가별 수출입 금액을 조회했음. 
2. 사용자는 본인 담당 상품으로만 검색하고 싶음. (쿼리는 할줄 모름)

[요구]
1. 사용자가 보길 원하는 상품 목록을 등록하면 해당 상품 기준으로 
   국가별 수출입 금액이 집계가 되길 바람. 
2. 보고서 화면을 볼때 상품을 바꿔가면서 조회하고 싶음.

**Comment by sunghoon** [comment]
오래된 이슈로 동일 사항이 재발생하면 새 이슈로 처리하겠습니다.
