### ISSUE TITLE
검색 DSL 명령어 이슈

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1642]
## 버그 설명 ##
```
* | stats count(*)
```

위와 같은 `count(*)` 명령어가 동작하지 않음

`count(*)` 대신에 `count(HOST)` 와 같이 컬럼 이름을 지정할 경우 정상 동작함

## 재현 방법

모델에서 syslog 를 선택후

```
* | stats count(*)
```

명령어 사용

**Comment by namjals** [comment]
`* | stats count(``*``)` 와 같이 변환을 잘못하였습니다.
운영서버에는 11월 1일 반영 예정입니다.

**Comment by namjals** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/22319132/67653943-16393c00-f98f-11e9-9ec1-b93170cc1e14.png)
