### ISSUE TITLE
[NMS+/수원시/교통]CRUD RestAPI 적용 - 콤보 컴포넌트

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1643]
## 기능 요청 ##
 금일 영철선임님이 IRIS 신규기능 교육해주셔서 넘 감사합니다.
다들 조마조마하면서 기대도 많이 했는데 짧은기간안에 고생 많이들 하셨네요. ^^

 현재 RestAPI 로 변수적용되는 컴포넌트가 3개 - 그리드/text/레이블 인데 차후 적용 컴포넌트중에
최우선순위로 "콤보" 를 해주시면
라디오/체크/리스트 등을 콤보로 대체하여 쓰다가 차차 적용되면 사업부에서 적용변경하려고 합니다.

일정 반영시 고려부탁드립니다.

다들 수고하셨습니다. 짝짝짝~

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
11월 5일자 패치로 Combo 컴포넌트도 REST API 컴포넌트를 대상으로 설정할 수 있게 되었습니다.
https://github.com/mobigen/IRIS-BigData-Platform/wiki/2019-11-05---Patch
