### ISSUE TITLE
[검색]특정기간 조회 시, 차트에 "데이터가 없습니다."로 표시됨

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1644]
## 버그 설명 ##
검색 화면에서 특정 기간으로 데이터 조회 시, 그리드에는 데이터가 표시됨에도 불구하고, 차트에는 "데이터가 없습니다."로 표시됨

## 재현하는 방법 ##
1. 검색 화면
2. 데이터 모델: 사내메일로그_자체
    시간: 2019/05/07 00:00:00 ~ 2019/05/08 23:59:59
3. 상기 조건으로 * 검색한 결과, 그리드에는 데이터가 표시되나, 차트는 표시되지 않음
   (아래 스크린샷 참조)

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/67549429-32469e80-f73f-11e9-9a35-316d8cbc014c.png)

**Comment by anhm** [comment]
IRIS-DB 에서 관리하는 파일이 손상되어 발생한 이슈입니다.
파일을 복구하여 정상적으로 동작하도록 수정해 두었습니다.

**Comment by seungfwani** [comment]
확인하였고 close 하겠습니다.
![image](https://user-images.githubusercontent.com/46172579/67728226-cbbbcc00-fa2f-11e9-99af-6857c51d07e6.png)
