### ISSUE TITLE
MDT / 지도상의 보이는 부분의 4꼭지 위경도 정보 추출 기능

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1645]
## 기능 요청 ##
지도상의 보이는 부분의 각각의 모서리의 위경도 정보 추출

## 원하는 솔루션 설명 ##
모서리의 위경도 정보를 추출하여 해당 부분에 필요한 정보만 DB에서 쿼리하기 위하여(DB 쿼리 속도 개선을 위해)

**Comment by veldise** [comment]
원하시는 기능이 아닐 수 있는데, 아래와 같이 지도 이동시 MAP_GEON_TEXT 라는 이름으로
검색어에서 활용할 수 있도록 변수를 제공하고 있습니다.

![image](https://user-images.githubusercontent.com/3411842/67644729-6e5c4800-f967-11e9-82ff-a8950e613395.png)

다만 해당 변수 값은 아래와 같은 형태이며, 
```
POLYGON((28.81700312114226 76.76147460937501, 28.81700312114226 77.47283935546876, 28.27656770648601 77.47283935546876, 28.27656770648601 76.76147460937501, 28.81700312114226 76.76147460937501))
```
지도 zoom-in/out 이나 move 이벤트가 발생했을 때만 값이 채워집니다.

**Comment by veldise** [comment]
사용 예제는 아래와 같습니다. (IRIS-DB SQL)
```sql
/*+ LOCATION ( PARTITION >=20190131000000 and  PARTITION <= 20190131005959) */
SELECT
    lon,
    lat,
    abs(rsrp) as abs_rsrp
FROM
    MDT_JP_POINT
WHERE
    ST_INTERSECTS (GEOMFROMTEXT('${EVENT_GEOM_TEXT}'), GEOM)
and rowid % 10 = 0
;
```

**Comment by leehaejoon** [comment]
IRIS 데이터베이스에서는 아래와 같은 공간 함수를 지원하고있습니다.

![스크린샷 2019-10-31 오후 4 00 10](https://user-images.githubusercontent.com/23020977/67925750-8fd36300-fbf7-11e9-986e-199d19e7690d.png)

**Comment by sunghoon** [comment]
@jsk3238 확인 후 특이사항이 없으면 close 부탁드립니다.

**Comment by veldise** [comment]
@jsk3238 
추가 답변입니다. 지도 줌 레벨의 경우에는 `MAP_GEOM_TEXT`와 마찬가지로
`MAP_ZOOM_LEVEL`을 SQL/검색어 입력시에 필터 조건으로 활용할 수 있으며,

또한 2개 이상의 지도의 줌 레벨을 동적으로 조정하고 싶을 경우 아래와 같이
지도 레이어에서 줌 레벨을 변수 치환 문법으로 입력하면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/67929664-2d7f6000-fc01-11e9-8bcc-e79463ee6a16.png)

그런데 현재 버전에 줌 레벨을 숫자로만 입력 가능한 버그가 있습니다.
이는 별도 이슈로 등록하여 빠르게 처리하도록 하겠습니다.

**Comment by minjaekang7** [comment]
ST_AREA, ST_Centroid는 동작하지만 ST_X, ST_Y등 동작하지않는 함수가 있습니다.
그리고 SpatialIndex작성방법을 알려주기 바랍니다.

**Comment by veldise** [comment]
@leehaejoon

**Comment by leehaejoon** [comment]
> ST_AREA, ST_Centroid는 동작하지만 ST_X, ST_Y등 동작하지않는 함수가 있습니다.
- 메뉴얼상에 기재되어있는 공간 함수를 사용할 수 있도록 IRIS DB 내부적으로 함수 목록에 추가하였습니다.

> 그리고 SpatialIndex작성방법을 알려주기 바랍니다.
- 공간 인덱스는 내부적으로 R-TREE를 사용하며 다음과 문법으로 생성할 수 있습니다.
`CREATE INDEX [인덱스 이름] ON [테이블 이름] ([공간 컬럼명] rtree);`
e.g. 
`CREATE INDEX MY_GEOM_INDEX ON MY_GEOM_TABLE (MY_POLYGON rtree);`

**Comment by minjaekang7** [comment]
다음과 같이 공간인덱스를 만들어보았는 데 에러가 발생합니다.
CREATE INDEX MDTX_GEOM ON MDTX (geom rtree);

정희동팀장님께 문의하니 지금은 공간인덱스를 생성할 수 없다고 들었습니다.

그리고 IRIS에서 공간쿼리를 이용해보니 상당히 느리게 동작했습니다.
(1) 단순 위경도만으로 쿼리하면 0.3초 걸립니다.
SELECT count(*) AS TRAFFIC FROM OSDEV.MDT_GEOM
where LON between 139.74695248784082 and 139.7583679694082
and LAT between 35.682778365845046 and 35.69030741843099
;
count: 444
time: 0.3sec

(2) 공간쿼리를 이용하니 6.6초로 20배 느립니다.
SELECT count(*) AS TRAFFIC FROM OSDEV.MDT_GEOM
where  ST_Within(geom, geomfromtext('POLYGON((35.69030741843099 139.74695248784082, 35.69030741843099 139.7583679694082, 35.682778365845046 139.7583679694082, 35.682778365845046 139.74695248784082, 35.69030741843099 139.74695248784082))'))=1
;
count:444
time: 6.6sec

(3) 제 노트북에 spatialite를 이용하여 공간쿼리를 사용해보니 1.3초 걸립니다. 공간인덱스가 있을 때와 없을 때가 차이가 없었습니다.
time: 1.3sec

IRIS가 노트북보다 훨씬 느린 것이 좀 이상하고 만일 그러하다면 IRIS를 사용해야하는 이유가 없겠지요. 원인을 규명해주시기 바라며 4꼭지점 위경도정보를 제공해주시기 바랍니다.
일본에서 데모할 때는 많은 데이터를 쿼리하게되면 네트워이 느려서 IRIS가 성능상에 상당히 느린 것처럼 보입니다.

**Comment by leehaejoon** [comment]
1. 공간인덱스는 현재 다음과 같이 생성 가능합니다.

- 문법 : ```CREATE INDEX [인덱스 이름] ON [테이블 이름] ([공간 컬럼명] rtree);```
- 예제 : ```CREATE INDEX MDTX_GEOM ON MDT_GEOM (geom rtree); ```
- 실제 생성화면 :

<img width="1470" alt="스크린샷 2019-11-04 오후 5 24 06" src="https://user-images.githubusercontent.com/23020977/68107352-f2926a80-ff27-11e9-9f0e-49efcf610f00.png">

혹시 문법과 테이블 이름, 공간 컬럼명 등을 제대로 기재했을 경우에도 에러가 발생한다면,

에러메시지를 공유해주시면 많은 도움이 될 것 같습니다.

<br/>

2. 쿼리에서 `=1` 검증 부분을 제거해야 제대로된 인덱스 성능을 볼 수 있습니다.

ST_Within 함수는 성공시 1, 실패시 0을 반환하며,

이는 WHERE절에서 자동으로 False 처리되므로 따로 조건비교를 해주지 않아도 됩니다.

```sql
SELECT count(*) AS TRAFFIC
FROM OSDEV.MDT_GEOM
WHERE ST_Within(
    geom,
    geomfromtext(
        'POLYGON((
            35.69030741843099 139.74695248784082, 
            35.69030741843099 139.7583679694082, 
            35.682778365845046 139.7583679694082, 
            35.682778365845046 139.74695248784082, 
            35.69030741843099 139.74695248784082))'))
;
```

<br/>

3. 공간 인덱스 생성 후 예제로 사용하신 쿼리를 실행하면 서버기준 약 0.08초, IRIS-WEB 기준 약 0.2초 정도의 실행시간이 소요됩니다.

<img width="963" alt="스크린샷 2019-11-04 오후 5 27 53" src="https://user-images.githubusercontent.com/23020977/68107511-751b2a00-ff28-11e9-83a3-e11423c5610d.png">

<img width="1147" alt="스크린샷 2019-11-04 오후 5 36 44" src="https://user-images.githubusercontent.com/23020977/68107942-b06a2880-ff29-11e9-865d-94d907e4b406.png">


\** 다만 현재 출력되는 결과 갯수가 444개가 아닌 442개로 출력되고 있습니다.

혹시나 인덱싱을 하는 과정에서 데이터가 유실되는가 했으나, 다행히 그 문제는 아니었고,

IRIS DB에서 인덱싱을 처리하는 내부적인 로직을 확인후 조치하도록 하겠습니다.

**Comment by anhm** [comment]
인덱스 관련된 문제를 해결완료 했습니다.
건수가 잘못나오던 원인은 내부의 부동 소수점 연산으로 인한 문제 였습니다.

create table, index 및 검색 부분을 수정하여 패치 완료 되었습니다.

```
iplus> SELECT count(*) AS TRAFFIC FROM OSDEV.MDT_GEOM
     > where ST_Within(geom, geomfromtext('POLYGON((35.69030741843099 139.74695248784082, 35.69030741843099 139.7583679694082, 35.682778365845046 139.7583679694082, 35.682778365845046 139.74695248784082, 35.69030741843099 139.74695248784082))'));
Ret : +OK Success


 TRAFFIC
===========
 444
===========

1 row in set

0.0810 sec
```

**Comment by minjaekang7** [comment]
공간인덱스가 동작하여 처리속도가 나오는 것이 확인됩니다.

**Comment by veldise** [comment]
"지도상의 보이는 부분의 각각의 모서리의 위경도 정보 추출하여, IRIS-DB 쿼리 수행"
에 대한 방법이 설명이 된 것으로 보고 이슈 닫겠습니다.

혹시 설명이 부족하다고 판단되시면 Reopen 해주시기 바라며,
다른 질문 사항은 새로운 이슈로 등록해주시면 감사하겠습니다.
