### ISSUE TITLE
MDT / 전역번수인 MAP_ZOOM_LEVEL의 가중치 적용 기능

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1646]
## 기능 요청 ##
MAP_ZOOM_LEVEL 변수값에 가중치를 주는 방법

## 원하는 솔루션 설명 ##
예) ${MAP_ZOOM_LEVEL+2}

**Comment by veldise** [comment]
현재 버전에서는 아래와 같은 형태로 값을 변형할 수 있습니다.
다만 약간의 오류로 인해 미리보기는 안되는 상태입니다. (실행은 가능)

`${MAP_ZOOM_LEVEL * 1 + 2}`

**Comment by veldise** [comment]
본문 내용은 답변이 된 것으로 보고 닫겠습니다.
