### ISSUE TITLE
MDT / 지도상에 화살표 그리는 방법

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1647]
## 기능 요청 ##
방향정보(각)와 길이정보를 가지고 화살표를 그리는 방법
선과 화살머리 표시가 가능한지

## 원하는 솔루션 설명 ##
기지국을 마커로 표시한 후 신호 방향과 범위를 화살표로 표시하고자 함

**Comment by veldise** [comment]
데이터가 GeoJSON인 경우 도형을 그릴 수는 있습니다만,
본문 내용처럼 각&길이로 화살표를 그리는 기능은 없습니다.

**Comment by sunghoon** [comment]
해당 기능이 반영되어 있습니다.
