### ISSUE TITLE
MDT / 데이터추가시 기존 테이블이 존재하는 경우 테이블 정보를 자동으로 유형에 설정 가능한지

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1648]
## 기능 요청 ##
데이터 추가시 기존 테이블이 존재하면 2번째 단계인 가공 단계에서 테이블 정보를 선택하여 자동으로 유형 변경이 기능

## 원하는 솔루션 설명 ##
데이터 추가시 유형을 계속 변경해줘야 해서 불편하다고 함

**Comment by veldise** [comment]
"기존 테이블"에 데이터를 추가(append)하는 경우 아래와 같이
가공 단계의 유형이 아닌 테이블 유형을 따라갑니다.

![image](https://user-images.githubusercontent.com/3411842/67644232-f8ee7880-f962-11e9-8d93-7a7cbd608bad.png)

**Comment by sunghoon** [comment]
오래된 이슈로 동일 사항이 재발생하면 새 이슈로 처리하겠습니다.
