### ISSUE TITLE
[KOTRA]Excel 다운로드시 내용 누락

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1650]
/*+ LOCATION (PARTITION >= '20170916110000' AND PARTITION <= '20191016110000') */
SELECT
    MCA
FROM
    KOTRABP.BP_LC_BIGBOT_TRAINING
WHERE
    YEAR = '2017';
다음의 쿼리를 입력하여 얻은 결과를 우측 하단에 다운로드 버튼을 눌러 Excel로 Import 받았을 때
쿼리의 결과가 누락되어 저장되는 이슈가 발생

**Comment by veldise** [comment]
@yariyarishow 
본사 운영서버 사이트에서 수행시 재현이 되고 있지 않습니다.
혹시 작업하고 계신 데이터 일부와 테이블 정보 등을 제공받을 수 있을까요?

**Comment by yariyarishow** [comment]
컬럼에 comma(,)가 들어간 상태에서 다운로드를 받으면 칼럼이 밀립니다.

**Comment by veldise** [comment]
@yariyarishow 
말씀하신 내용은 본문과는 다른 내용으로 생각됩니다. (#1669)
컬럼이 밀리는 문제는 모비젠 본사 운영서버에는 해결된 내용으로,
KOTRA 쪽에 설치된 IRIS에 대하여 패치 요청을 하시면 됩니다.

**Comment by sunghoon** [comment]
해결된 것으로 보고 닫습니다.
