### ISSUE TITLE
[KOTRA]데이터 피벗분석 > 필터 조건 추가 요청

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1651]
## 기능 요청 ##
필터 조건에 IN 또는 BETWEEN이 가능하게 해주세요. 

## 원하는 솔루션 설명 ##
현재 필터 유형으로는 그룹화 할 수 가 없습니다. 
예를 들어, 한국, 일본, 중국의 미국에 대한 수출금액을 출력하고 싶은데, 
한국, 일본, 중국만 구분할 수가 없습니다.

**Comment by veldise** [comment]
@pjh0347 
pivot 명령어에서 필터 기능에 `IN`, `BETWEEN` 연산자를 지원하는지 확인 및 답변 부탁드립니다.

**Comment by seungfwani** [comment]
현재 `X BETWEEN 'value1' AND 'value2'` 와 같은 between 연산자는 가능합니다.
하지만 `IN` 연산자의 경우 comma(`,`) 의 파싱이 되지 않아 수정이 필요합니다.

**Comment by seungfwani** [comment]
pivot의 filter 옵션에 `IN` 연산자 사용가능 하도록 추가하였고, 배포요청하였습니다.

**Comment by seungfwani** [comment]
운영서버(192.168.100.180)에는 해당 내용이 추가되었습니다.
- `where` 명령어로 필터링
![image](https://user-images.githubusercontent.com/46172579/69320025-baa75900-0c83-11ea-9b6b-b84faa5c29cc.png)

- `pivot` 명령어로 필터링
![image](https://user-images.githubusercontent.com/46172579/69320007-ae230080-0c83-11ea-83c9-06177fb1f339.png)

**Comment by namjals** [comment]
앙고라는 코트라에서 동작 확인했습니다.

**Comment by veldise** [comment]
@namjals 
query-analysis API 수정이 필요합니다.

### type=tree
request:
```js
{
    "url": "http://192.168.100.180:6036/angora/query-analysis?type=tree",
    "method": "POST",
    "body": {"q": "* | pivot count(*) FILTER FTRDCTR_NM in ('다카', '홍콩')"}
}
```
response:
```js
{
    "data": {
        "q": "*",
        "pivot": {
            "filters": ["FTRDCTR_NM in", "(", "'다카' , '홍콩'", ")"],
            "rows": [],
            "cols": [],
            "sort": null,
            "col_size": null,
            "cells": [{"func": "count", "field": "*"}]
        }
    }
}
```

### type=string
```js
{
    "url": "http://192.168.100.180:6036/angora/query-analysis?type=string",
    "method": "POST",
    "body": {
        "q": "*",
        "pivot": {
            "filters": ["FTRDCTR_NM in", "(", "'다카' , '홍콩'", ")"],
            "rows": [],
            "cols": [],
            "sort": null,
            "col_size": null,
            "cells": [{"func": "count", "field": "*"}]
        }
    }
}
```
```js
{
    "data": {
        "q": "* | pivot count(*) FILTER FTRDCTR_NM in AND ( AND '다카' , '홍콩' AND )"
    }
}
```

**Comment by veldise** [comment]
@namjals 
BETWEEN의 경우에는 조금 이상하긴 한데 tree -> string -> tree가 되긴 합니다.

### type=tree
request:
```js
{
    "url": "http://192.168.100.180:6036/angora/query-analysis?type=tree",
    "method": "POST",
    "body": {"q": "* | pivot count(*) FILTER X BETWEEN 'value1' AND 'value2'"}
}
```
response:
```js
{
    "data": {
        "q": "*",
        "pivot": {
            "filters": ["X BETWEEN 'value1'", "AND", "'value2'"],
            "rows": [],
            "cols": [],
            "sort": null,
            "col_size": null,
            "cells": [{"func": "count", "field": "*"}]
        }
    }
}
```

### type=string
request:
```js
{
    "url": "http://192.168.100.180:6036/angora/query-analysis?type=string",
    "method": "POST",
    "body": {
        "q": "*",
        "pivot": {
            "filters": ["X BETWEEN 'value1'", "AND", "'value2'"],
            "rows": [],
            "cols": [],
            "sort": null,
            "col_size": null,
            "cells": [{"func": "count", "field": "*"}]
        }
    }
}
```
response:
```js
{"data": {"q": "* | pivot count(*) FILTER X BETWEEN 'value1' AND 'value2'"}}
```

**Comment by seungfwani** [comment]
@veldise 
아래와 같이 `.. in ( )` 문법이 제대로 리턴되도록 수정 하였습니다.
## type=string
request:

{
    "url": "http://192.168.100.180:6036/angora/query-analysis?type=string",
    "method": "POST",
    "body": {
        "q": "*",
        "pivot": {
            "filters": ["FTRDCTR_NM in", "(", "'다카' , '홍콩'", ")"],
            "rows": [],
            "cols": [],
            "sort": null,
            "col_size": null,
            "cells": [{"func": "count", "field": "*"}]
        }
    }
}
response:
![image](https://user-images.githubusercontent.com/46172579/71156344-309ee000-2283-11ea-94da-fa474943cfd4.png)

**Comment by veldise** [comment]
@seungfwani 
type=string 이 아니고 type=tree 결과가 잘못된 겁니다.
다시 검토 바랍니다.

**Comment by seungfwani** [comment]
@veldise 
tree 의 결과가 잘못된 것을 인지 하였습니다.

아래 예제처럼 되도록 수정하였습니다. 운영서버 배포는 요청하도록 하겠습니다.

## type=tree
request:
```
{
    "url": "http://192.168.100.180:6036/angora/query-analysis?type=tree",
    "method": "POST",
    "body": {"q": "* |  pivot count(*) FILTER FTRDCTR_NM in ('다카', '홍콩') and FFF between A and B"}
}
```
response:
![image](https://user-images.githubusercontent.com/46172579/71230695-00f8e200-232e-11ea-8f7d-a9e35f9e6077.png)

**Comment by seungfwani** [comment]
@veldise 
운영서버 배포 완료되었습니다.

**Comment by seungfwani** [comment]
@veldise 
query-analysis API 로 아래 쿼리를 보냈을 때 결과입니다.
```
q: "* | pivot count(*) FILTER HOST in ('gcs1', 'gcs3')"
```
![image](https://user-images.githubusercontent.com/46172579/71795823-5f8ec180-308b-11ea-962b-2a8ce1a29808.png)

**Comment by seungfwani** [comment]
#1845 이슈와 함께 진행중입니다.

**Comment by veldise** [comment]
UI는 #1874 에서 진행 예정입니다.

**Comment by sunghoon** [comment]
@veldise 해당이슈 UI 진행 최종 상태가 어떻게 되어 있는지 공유 바랍니다.  Discovery 까지는 진행된것 같습니다.

**Comment by veldise** [comment]
@sunghoon 
UI 개발은 아래 이슈로 분리하였고 고객 요구사항 등에 의해 일정 연기된 상태입니다.
#1874

**Comment by sunghoon** [comment]
@veldise 해당 기능 개발에 필요한 작업 일정정보를 공유해 주시기 바랍니다.
