### ISSUE TITLE
ValueLinkU / 사용자가 생성한 메뉴에 대한 도움말 기능 추가

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1652]
## 기능 요청 ##
메뉴 등록 기능에서 해당 메뉴에 대한 설명 정보를 넣을 수 있는 기능 필요
메뉴에 대한 설명 정보를 도움말 기능과 같이 볼 수 있는 기능 필요

예시) 구글문서의 도움말 보기와 유사한 기능
![image](https://user-images.githubusercontent.com/4444717/67674131-0d605e80-f9bf-11e9-95ee-1526bece44b1.png)

**Comment by mondbarde** [comment]
요청사항에서 언급하신 도움말은 관리자 열람용인가요 아니면 엔드유저 열람용인가요?
두가지 케이스에 따라서 들어가게 되는 UX가 달라져서 문의드립니다.

**Comment by JeongHeeDong** [comment]
엔드유저 열람용입니다.

**Comment by mondbarde** [comment]
네 감사합니다. 그럼 일단 메뉴 관리 페이지에서 엔드유저쪽에서 호출시 내보낼 수 있는 설명 정보를 입력할 수 있는 UI를 넣어두도록 하겠습니다. 설명 정보 열람용 도움말 UX는 추후 공통 UX 가이드쪽 설계시에 반영하도록 하겠습니다. 감사합니다.
