### ISSUE TITLE
MDT / DB Browser에서 GEOMETRY컬럼을 갖는 테이블 생성에러

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1653]
## 버그 설명 ##
MDT / DB Browser에서 GEOMETRY컬럼을 갖는 테이블 생성에러

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS로그인 osdev계정
2. Click on 'DB Browser'
3. 다음 쿼리를 입력
CREATE TABLE SPATIAL_TABLE (
   k         TEXT,
   p         TEXT,
   geom      GEOMETRY(SRID=4326)
)
datascope       LOCAL
ramexpire       30
diskexpire      34200
partitionkey    k
partitiondate   p
partitionrange  10
extension       geospatial
;

다음과 같은 에러메세지가 나타납니다.
Line 1 ~ 13 : Unknown error. ( UnboundLocalError("local variable 'cursor' referenced before assignment",)

## 예상한 행동 ##
에러없이 테이블이 생성되기를 기대합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/54348795/67749693-03973380-fa71-11e9-9360-1c3489f5cb02.png)

**Comment by veldise** [comment]
@anhm
iplus 에서도 동일 에러가 발생합니다. 

![image](https://user-images.githubusercontent.com/3411842/67750131-ee6ed480-fa71-11e9-98b6-c1c2be701de4.png)

**Comment by minjaekang7** [comment]
버그수정이 이루어질 것으로 들었는 데, 여전히 에러가 발생하고 있습니다.

Line 1 ~ 13 : 알 수 없는 에러. (에러 메시지가 비어있습니다.)

**Comment by anhm** [comment]
버그 수정을 완료 하며 배포 되었습니다.
현 시점부터 정상적으로 사용 가능하십니다.

**Comment by sunghoon** [comment]
@minjaekang7 확인 후 특이사항이 없으면 close 부탁드립니다.
