### ISSUE TITLE
보고서 RestAPI 기능 https 통신 기능 추가 요청

### ISSUE THREAD

**Issue by ilseon** [mobigen/IRIS-BigData-Platform#1654]
## 버그 설명 ##
같은 서버에 brick과 web application을 구성 후 
보고서에서 RestAPI URI를 https 로  요청 시 에러 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 새 보고서 작성 클릭
2. Rest API 생성
3. URI : https://localhost/test
   Method : GET
4. 에러 발생 

## 예상한 행동 ##
URI의 응답 결과 정상 수신

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/20102098/67750449-908ebc80-fa72-11e9-8968-c6abc8e555a2.png)

## 로그 ##
![image](https://user-images.githubusercontent.com/20102098/67750509-ad2af480-fa72-11e9-85ec-b804979322cb.png)

**Comment by veldise** [comment]
일단 본문 내용과 올려주신 스크린샷으로 판단하기로는,
URI를 `localhost`나 IRIS 와 동일한 도메인(`192.168.102.132`)로 설정하면
http request 가 IRIS로 전송되기 때문에 정상 동작하지 않습니다.

실행하신 WAS(web application server)의 IP Address로 URI를 설정해주시고,
CORS 옵션을 해제해주어야 cross-domain 에러가 발생하지 않습니다.

**Comment by ilseon** [comment]
해당 이슈는 CORS 옵션 추가하여 해결하였습니다.
