### ISSUE TITLE
MDT / Report작성에서 지도상의 클릭이벤트가 동작안함

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1656]
## 버그 설명 ##
 Report작성모드에서 하나의 지도(A)위에서 클릭하면 트리거설정된 다른 지도(B)가 조회되어 갱신되는 것은 확인되지만 지도(B)중심이 이동하지않는 문제가 발생한다.  지도(A)클릭후 드래그하면 지도(B)가 갱신된다.  클릭만으로 지도(B)가 갱신 및 중심이동도 같이 될 것으로 기대하고 있다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS WEB의 osdev로그인
2. Report메뉴이동후 MDT_chart2를 편집한다.
3. 'Show'버튼을 클릭하면 좌상단의 지도(A)가 갱신된다.
4. 지도(A)의 한 그리드를 클릭하면 좌하단의 지도(B)가 갱신되는 바(BAR)의 색상이 변하지만 멈춘뒤에도 지도(B)에는 아무런 변화가 보이지 않는다. 하지만 지도를 마우스로 이동하여 도쿄지역으로 이동하면 갱신되어 있는 것이 확인된다. 즉, 지도가 자동으로 이동하지 않는 것이 문제.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/54348795/67751977-77d3d600-fa75-11e9-9249-37300edae4ba.png)

**Comment by veldise** [comment]
본문 내용과 같은 동작을 지원하기 위해 다음과 같은 변수값들을 지원하고 있습니다.

![image](https://user-images.githubusercontent.com/3411842/67752176-dc8f3080-fa75-11e9-8b5b-b3a908c88853.png)

EVENT_* 변수를 지도 레이어에서 아래와 같이 설정해주면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/67752287-12ccb000-fa76-11e9-9029-c62a665dbd1b.png)

**Comment by minjaekang7** [comment]
이미 그렇게 설정되어 있습니다.
클릭이벤트와 드래그이벤트가 다르게 동작하는 것으로 보입니다.

**Comment by veldise** [comment]
@minjaekang7 
이벤트 동작과는 별개로 지도 객체 - 레이어 선택 부분에 버그가 있는 것이 확인되었습니다.
조치하고 다시 알려드리겠습니다.

**Comment by veldise** [comment]
@minjaekang7 
11/5 패치로 레이어 선택 버그가 해결되었습니다.
지도(A)에서 클릭 대상이 될 레이어를 선택해 둔 상태에서, 지도(B)에서 트리거 대상을 지도(A)로 선택하면 지도(A)의 레이어가 트리거 대상이 될 것입니다.

확인 부탁드립니다.
