### ISSUE TITLE
MDT / 지도의 범례설정오류

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1657]
## 버그 설명 ##
설정한 범례와 출력된 색상이 다르게 나옴

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS에서 osdev로 로그인
2. Report로 이동후 MDTX를 편집
3. Show버튼 클릭
4. 좌상단의 Traffic지도에서 "객체이동"을 클릭해서 "지도이동"으로 변경.  지도상의 한점을 클릭한번한 후에 다시 드래그
5. 좌하단의 OVERLAP표기의 지도를 클릭한후에 MESH_OVERLAP레이어선택후 RUN
6. 시각화옵션선택후 색상선택
7. 지도상의 레전드와 설정된 범위가 같지 않고 이로 인해 다른 색상이 표현된다.

## 예상한 행동 ##
위 설명

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/54348795/67753129-963ad100-fa77-11e9-8aa0-8246b29a1ddd.png)

**Comment by veldise** [comment]
일단 설정한 값과 범례가 다르게 출력되는 것은 버그로 생각됩니다.

다른 색상이 표현되는 것은, 현재 운영서버 배포된 버전에는 아래와 같은 문제가 있어서 그렇습니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/1591#issuecomment-546767488
금주내로 패치 예정입니다.

**Comment by swish1995** [comment]
@veldise 
임계치의 값 설정부분의 `input type="number"` 로 되어 있어 소수점을 포함한 값을 넣어도 integer 값으로 저장됩니다.

위에 스크린샷의 `1.4`,` 1.5`, `1.8` 모두 `1`로 계산되는 문제 가 있습니다.
해당 컴포넌트의 type 을 `text` 로 바꾸고 validation 을 추가해서 작업하면 되는지 확인바랍니다.

**Comment by veldise** [comment]
@swish1995 
네, 말씀하신대로 작업 부탁드립니다.

**Comment by swish1995** [comment]
@veldise 
추가 확인결과 입니다.
- chart 옵션을 leaflet layer 옵션으로 넘겨주는 과정에서 임계치 색상으로 parseInt 를 통해 강제 형변환
-parseFloat 으로 수정후 정상적으로 동작하는것으로 확인됨

**Comment by veldise** [comment]
운영서버(b-iris.mobigen.com)에 버그 수정 버전이 패치되었습니다.
혹시 문제가 재발하거나 유사한 문제가 발생하면 이슈를 Reopen 하시거나 새로운 이슈를 등록해주시기 바랍니다.
