### ISSUE TITLE
Map 객체 선택시 선택된 레이어의 목록과 아래 정보가 일치하지 않음

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#1658]
## 버그 설명 ##
map 의 layer 선택, 다른 컴포넌트 선택, map 재 선택시 layer 선택 창과 아래 내용이 일치하지 않음

## 예상한 행동 ##
선택된 레이어의 이름과 정보가 일치함

## 스크린샷 ##
![스크린샷 2019-10-30 오전 11 36 46](https://user-images.githubusercontent.com/49141403/67824928-12322900-fb0b-11e9-9ba9-5afcfeaa24ec.png)
map 객체 선택후 지도 레이어 선택
![스크린샷 2019-10-30 오전 11 37 16](https://user-images.githubusercontent.com/49141403/67824933-15c5b000-fb0b-11e9-9c27-99496dd5c9f6.png)
map 객체의 하위레어이를 선택후 trigger 지정
![스크린샷 2019-10-30 오전 11 37 32](https://user-images.githubusercontent.com/49141403/67824934-16f6dd00-fb0b-11e9-8059-970104a2bcec.png)
다른 객체 선택후 해당 map 객체를 재 선택하면 레이어 선택이름은 mesh 이나 밑의 내용은 map 의 지도객체의 정보가 표시됨
![스크린샷 2019-10-30 오전 11 37 40](https://user-images.githubusercontent.com/49141403/67824944-1cecbe00-fb0b-11e9-8e9d-ae1162e61128.png)
레이어 select box 를 통해 다시 mesh 레이어를 선택하면 정보가 일치함

**Comment by veldise** [comment]
11월 4일 본사 운영서버에 패치 예정입니다.
