### ISSUE TITLE
ValueLinkU / 메뉴 접근 권한 설정 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1661]
## 버그 설명 ##
특정 메뉴의 접근 권한을 그룹에 관리자/정회원/일반회원(개인)을 등록하고 일반화원(개인) 그룹의 사용자로 로그인하여 메뉴를 보면 해당 메뉴 보이지 않음.
사용자 개인 권한으로 등록하면 정상적으로 메뉴 보임.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
현재 권한 설정 상태
- 사용자
![image](https://user-images.githubusercontent.com/7067615/67925433-b5ac3800-fbf6-11e9-8178-3fbde2ba1ee7.png)

- 그룹
![image](https://user-images.githubusercontent.com/7067615/67925417-a6c58580-fbf6-11e9-80db-94ee7e85ad21.png)

- 계정 정보
![image](https://user-images.githubusercontent.com/7067615/67925477-d5dbf700-fbf6-11e9-8853-c70ab1750fe9.png)

- 메뉴(Main Dashboard옆 VoC 메뉴 안보임)
![image](https://user-images.githubusercontent.com/7067615/67925502-eab88a80-fbf6-11e9-9097-bda3cc1f3f5f.png)

- 메뉴에 해당 계정 권한 추가
![image](https://user-images.githubusercontent.com/7067615/67925545-1471b180-fbf7-11e9-9e1d-faf1ff0812a3.png)

- 메뉴(Main Dashboard옆 VoC 메뉴 보임)
![image](https://user-images.githubusercontent.com/7067615/67925574-26535480-fbf7-11e9-97d9-7b7205806362.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
IRIS 인증 토큰에 `groupId` 정보가 없어서 발생하는 문제입니다.
토큰 생성(발급)시 `groupId` 값을 추가해야 합니다.

따로 시간을 잡고 논의가 필요할 것 같습니다.

**Comment by veldise** [comment]
ValueLinkU 쪽에서 토큰 생성시 `groupId` 값을 추가하는 것으로 협의되었습니다.

**Comment by veldise** [comment]
해결된 것으로 보고 닫습니다.
