### ISSUE TITLE
[농협BMT] IRIS JAVA API 접속 에러(v2.1.0.3 및 이전 버전)

### ISSUE THREAD

**Issue by suk555** [mobigen/IRIS-BigData-Platform#1664]
## 버그 설명 ##
디버그 메시지
DEBUG 2019-11-01 17:05:59.716 [TaskWorker_2019-11-01 17:05:59.480]  com.sycros.EWSAgent.realTime.InputDBWorker - pstmt :com.mobigen.iris.jdbc.**IRISPreparedStatement**@21e93747

API설명서에는 PreparedStatement 방식과 Statement방식 두가지를 제공한다고하는데
Statement방식만 정상적으로 동작됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
IRISPrepareStatement를 사용하면 IRIS데이터를 못가져옴(null)

## 로그 ##
DEBUG 2019-11-01 16:40:38.749 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - connection start

DEBUG 2019-11-01 16:40:39.853 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - connection success

DEBUG 2019-11-01 16:40:39.854 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - start get column info

DEBUG 2019-11-01 16:40:39.854 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - query :/*+ LOCATION ( PARTITION >= '20191101120000' AND PARTITION <= '20191101150000' ) */
SELECT
        AGENT_ID, HOST, DEVICE, FSTYPE, MODE, PATH, INODES_FREE, INODES_TOTAL, INODES_USED, INODES_USED_PERCENT, FREE, TOTAL, USED, USED_PERCENT, COTIME, PARTITION_KEY, PARTITION_DATE
FROM
        SMS.RESOURCE_DISK
;
DEBUG 2019-11-01 16:40:39.854 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - connection clientInfo : null
DEBUG 2019-11-01 16:40:39.869 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - pstmt :com.mobigen.iris.jdbc.IRISPreparedStatement@2f486f8b

DEBUG 2019-11-01 16:40:49.888 [TaskWorker_2019-11-01 16:40:38.642]  com.sycros.EWSAgent.realTime.InputDBWorker - inputdbworker finally

DEBUG 2019-11-01 16:40:49.888 [resultBufferWorker]  com.sycros.EWSAgent.TaskWorker - null

DEBUG 2019-11-01 16:40:49.903 [Session2ManagerWorker_2019-11-01 16:40:38]  com.sycros.EWSAgent.TaskWorker - java.io.IOException
        at com.sycros.dna.Session2.advReceiveNio(Session2.java:429)
        at com.sycros.dna.Session2.advReceive(Session2.java:411)
        at com.sycros.dna.ProtocolReadManager.readHead(ProtocolReadManager.java:75)
        at com.sycros.dna.ProtocolReadManager.readContent(ProtocolReadManager.java:193)
        at com.sycros.EWSAgent.TaskWorker.read(TaskWorker.java:231)
        at com.sycros.dna.Session2ManagerWorker.dispatch(Session2ManagerWorker.java:97)
        at com.sycros.dna.Session2ManagerWorker.run(Session2ManagerWorker.java:69)

**Comment by anhm** [comment]
일차적으로 내부에서 사요하는 코드를 이용하여  select prepareStatement 테스트를 진행해 보았습니다.

아래 방식으로는 에러가 없이 동작하는 것을 확인하였습니다.
에러가 발생하는 곳에서 사용 패턴을 알려 주시면, 해당 패턴으로 테스트를 진행할 수 있을것 같습니다.

참고로 아래는 테스트에 사용한 코드 입니다.

``` java
	public static void main(String[] args) {
		
		String url = AccountInfo.url;
		Properties info = AccountInfo.getAccount();
		
		try {
			Class.forName("com.mobigen.iris.jdbc.IRISDriver");
		} catch (java.lang.ClassNotFoundException e) {
			e.printStackTrace();
			return;
		}
		
		Connection conn = null;
		try {
			conn = DriverManager.getConnection(url, info);
			Statement stmt = conn.createStatement();
			PreparedStatement pstmt = conn.prepareStatement("select k, p, a from local_test_table_JDBC where k = ?;");
			pstmt.setString(1,  "k");
			ResultSet rs = pstmt.executeQuery();
					
			// 두번째 방법 (row 수를 얻어와서 for문 돌기)
			for( int i = 1 ; i <= rs.getRow() ; i++ )
			{
				rs.next();
				System.out.println(i + " : " + rs.getString(1) + "," + rs.getString(2) + "," + rs.getString(3));
			}

			rs.close();
			stmt.close();
			conn.close();
		} catch (SQLException e) {
			//System.out.println(e.getErrorCode());
			//System.out.println(e.getMessage());
			e.printStackTrace();
		}
	}
```

**Comment by anhm** [comment]
농협 BMT가 종료되어 해당 이슈는 닫도록 하겠습니다.
