### ISSUE TITLE
영문 미적용 화면에 대한 영문 적용 요청

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1666]
## 버그 설명 ##
사용 언어를 영문으로 선택하였으나, 일부 화면에는 영문이 아닌 국문으로 출력됨.

## 재현하는 방법 ##
- 보고서 화면에서 접근권한 설정 팝업 (스크린샷 #1 참조) 
- HDFS Browser 화면 (스크린샷 #2 참조)
  -> MOUNT Browser도 동일한 현상임
- Jupyter 화면 (스크린샷 #3 참조)

## 스크린샷 ##
- 스크린샷 #1
  
![image](https://user-images.githubusercontent.com/23075670/68099444-f44b3680-ff05-11e9-925d-2cd6dec36897.png)

- 스크린샷 #2 
![image](https://user-images.githubusercontent.com/23075670/68099504-5441dd00-ff06-11e9-9bd5-6fbdc88f378d.png)

- 스크린샷 #3 
![image](https://user-images.githubusercontent.com/23075670/68099603-b00c6600-ff06-11e9-9213-a8a55a334515.png)

**Comment by veldise** [comment]
보고서 및 HDFS 조회 화면은 버그입니다. 확인 및 조치하겠습니다.

@anhm

**Comment by veldise** [comment]
@jins00 
이슈와는 관계없는 사소한 부분입니다만,
Github 에서 # 문자와 숫자를 같이 작성하면 이슈번호에 대한 링크가 됩니다. (ex) #1666)
이슈나 다른 문서를 작성하실대 참고하시면 좋을 것 같습니다.
