### ISSUE TITLE
MDT / Map 조회타임아웃이 너무 짧습니다.

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1667]
## 버그 설명 ##
결과적으로 화면에 표현되지 않기때문에 타임아웃설정변경 바랍니다.
모비젠내에서는 네트워크환경이 좋기때문에 문제가 발생하지 않지만 일본에서 접속하면 타임아웃이 발생할 확율이 매우 높습니다. 현재 지도의 경우 40초정도로 보이지만 3분정도로 늘려주기 바랍니다.

## 재현하는 방법 ##
모비젠에서는 재현이 안될 수도 있겠네요.

## 예상한 행동 ##
지도에 포인트정보가 표현되어야함.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/54348795/68101415-e18a2f00-ff10-11e9-959a-bcda5cae6f68.png)

**Comment by veldise** [comment]
@pjh0347 
현재 timeout은 15초로 설정되어 있습니다. (이전 이슈: #1414)
3분으로 변경해도 괜찮은지 검토 바랍니다.

**Comment by seungfwani** [comment]
@veldise 
DSMS 의 connection-timeout은 현재는 30초로 설정되어 있습니다. (운영서버 기준)
값을 변경하는 것에는 무리가 없습니다.

**Comment by veldise** [comment]
@seungfwani 
문의 드린게 아니고, 웹에서도 http timeout이 15초로 설정되어 있습니다.
3분으로 변경해도 괜찮은지 검토하고 답변 바랍니다.

**Comment by seungfwani** [comment]
웹의 클라이언트가 서버에 연결하는 시간을 변경하는 것은 괜찮을 것으로 보입니다.

또한, DSMS의 worker 의 timeout 을 180초(3분) 로 설정하였습니다.

**Comment by veldise** [comment]
@seungfwani 
네, UI도 3분으로 변경하겠습니다.
