### ISSUE TITLE
MDT / Report / 지도 / 트리거설정 / 대상오프젝트 설정이 안됨

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1668]
## 버그 설명 ##
MDT / Report / 지도 / 트리거설정 / 대상오프젝트 설정이 안됨
대상오프젝트를 클릭해서 지정하게 되어 있지만 대상의 지도가 두개이상의 레이어를 가지고 있음에도 불구하고 하나만 선택되고 원하는 레이어가 등록되지 않는 문제가 발생합니다.
물론, 선택되는 경우도 있습니다. 확률은 반반.  안되는 경우에는 계속 안되는 경향이 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. osdev로 로그인
2. Report로 이동, MDTX_DXDY를 편집모드로 연다.
3. 왼쪽에서 3번째, 위에서 3번째의 지도를 선택한다. 
4. 레이어에서 POINT를 선택한다.  트리거설정 아이콘을 클릭한 후에 첫번째(1,1) 지도를 선택한다.
5. 하지만 선택되는 것은 두개의 레이어중에서 하나만 선택된다. 즉, 지도레이어만 선택되고 그 위의 그리드가 표현되어 있는 레이어는 선택되지 않는다.

## 예상한 행동 ##
두개의 레이어가 모두 등록되어야한다. 그 뒤에 불필요하면 삭제한다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/54348795/68101687-3c705600-ff12-11e9-9218-506ce66b3834.png)

**Comment by veldise** [comment]
현재 특정 레이어를 제대로 선택할 수 없는 버그가 있습니다. (#1658)
금일 패치 예정이며 패치된 이후에는, 트리거 설정시 현재 활성화된(선택된) 레이어가 대상으로 설정됩니다.

아래 예제의 경우, 각 오브젝트ID가 다음과 같습니다.

report-component-box1 : 지도(A)의 지도 레이어
report-component-box3 : 지도(A)의 LAYER_01 레이어
report-component-box4 : 지도(A)의 LAYER_02 레이어

![image](https://user-images.githubusercontent.com/3411842/68102539-8b1fef00-ff16-11e9-9884-a728dfaff308.png)

**Comment by veldise** [comment]
#1658 가 패치로 해결됨에 따라 이 이슈도 해결된 것으로 보고 닫겠습니다.
