### ISSUE TITLE
[KOTRA]데이터모델 다운로드 포맷 추가 요청

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1674]
## 상황 ##
1. 코트라의 데이터들은 데이터 내용에 콤마(,), 버티컬바(|) 등 키보드에 있는 기호들을 포함하고 있음. 
2. 1번의 이유로  CSV 구분자를 사용할때 여러기호를 혼용해서 써야함. 
3. 코트라 사용자들은 일반 사용자여서 이러한 사용방식에 어려움을 느낌.

## 기능 요청 ##
1. 사용자들의 추가적인 행위 없이 탭기반 파일(TSV) 다운로드를 지원해주길 바람.

**Comment by veldise** [comment]
@pjh0347 
Angora download API 에서 tsv 포맷을 지원해야 합니다.

**Comment by pjh0347** [comment]
@yariyarishow 다운로드시에만 TSV 포멧을 지원해주면 되나요?

**Comment by yariyarishow** [comment]
네.

**Comment by seungfwani** [comment]
Angora download API 에 tsv 포멧도 처리 할 수 있도록 추가하였습니다.
`/angora/query/jobs/<sid>/download?type=tsv&sep=%09` 로 사용할 수 있습니다.

**Comment by namjals** [comment]
앙고라는 코트라에서 동작 확인했습니다.

**Comment by veldise** [comment]
UI는 11월 28일 패치 예정입니다.
