### ISSUE TITLE
[KOTRA]데이터모델 조회시 칼럼별 데이터 카운트가 스크롤 되지 않음

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1675]
## 버그 설명 ##
1. 데이터 모델 조회시 칼럼목록을 스크롤 되는데, 칼럼 옆에 표기되는 데이터 개수는 
   스크롤 되지 않음. 
2. 컬럼수가 117개임.

**Comment by veldise** [comment]
@yariyarishow 
아래 현상을 말씀하시는게 맞는지 답변 부탁드립니다.

![image](https://user-images.githubusercontent.com/3411842/68269581-a36e4600-009d-11ea-9ef8-865bba3b7bed.png)
