### ISSUE TITLE
[KOTRA]데이터모델 수치가 지수로 표현됨

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1676]
## 버그 설명 ##
1. 데이터모델 조회시 수치데이터가 지수로 표현됨. 
2. 코트라의 경우 수출금액이 1000,000,000,000,000 (천조) 의 수준에서 표현되는데, 
   이값이 제대로 출력되지 않음.

**Comment by veldise** [comment]
@pjh0347 
현재 HDFS에 유사 데이터를 업로드하고 데이터 모델을 만들어 검색을 수행하면 아래와 같이 `null`이 반환됩니다.

```json
{
  "fields": [
    { "grouped": false, "type": "TEXT", "name": "key" }, 
    { "grouped": false, "type": "INTEGER", "name": "value" }
  ], 
  "isEnd": true, 
  "results": [
    [ "A", null ], 
    [ "B", null ]
  ]
}
```

이에 따라 아래 2가지가 논의되어야 합니다.
1. 이 이슈에 대한 Angora 처리, Angora API 변경
2. Angora API 변경에 따른 UI 처리

**Comment by namjals** [comment]
Angora에서는 bigint나 long 데이터 타입으로 처리가 가능합니다. 
UI에서 fields의 type을 BIGINT 혹은 LONG형을 추가해주셔서, 사용자가 해당 타입으로 모델 생성 후, 검색 시, BIGINT 혹은 LONG형으로 반환하겠습니다.
제 의견으로는 BIGINT가 사용자 입장에서 이해하기 좋을거 같습니다.

**Comment by veldise** [comment]
@namjals 
알겠습니다. 갱신된 데이터 모델 API 문서를 메일로 보내주세요.

**Comment by namjals** [comment]
@veldise 
전달드렸습니다.

**Comment by veldise** [comment]
@namjals
확인했습니다. Angora 패치 일정은 어떻게 되나요?

**Comment by namjals** [comment]
@veldise
내일(11/20) 배포 요청할 예정입니다.

**Comment by namjals** [comment]
180번 운영서버 패치 되었습니다.
![image](https://user-images.githubusercontent.com/22319132/69504539-0b120580-0f67-11ea-98f4-82baabf8d9d9.png)

**Comment by veldise** [comment]
UI는 금주 목요일 패치 예정입니다.
