### ISSUE TITLE
[KOTRA]IRIS Web WAS가 먹통이됨.

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1678]
## 버그 설명 ##
1. 데이터 크기 : 6천만 Rows, 50GB, 117칼럼 
2. 1번의 데이터를 데이터 모델로 만들어서 검색 및 피벗분석 등을 수행하면,
    데이터모델 조회 속도가 점점 느려지면서, 
   종국에는 WAS가 죽어버림.

**Comment by veldise** [comment]
UI 에서는 개수 제한(200~500)이 걸려있으므로, Web WAS보다는
백엔드에서 발생하는 문제로 추정됩니다.

@pjh0347 
이슈 본문에 대하여 확인 바랍니다.

**Comment by pjh0347** [comment]
@yariyarishow 상황을 재현해 볼 수 있는 조건을 명시 부탁드립니다.

**Comment by yariyarishow** [comment]
1. 생성한 테이블 : 연도를 기준으로 파티션 설정(2008 ~ 2019 년까지의 데이터)
2. 데이터 속성 : 국가정보, 기업정보, 수출금액(금액은 100,000,000,000 자릿수의 데이터) 등의 117개 칼럼
3. 데이터 Rows : 6천만 건 => 데이터 모델로 생성 
4. 피벗 기능을 통해 필터링 해서 6천만건 -> 4천만건 -> 9백만건 -> 1백만건 으로 줄여가며
   시각화 및 데이터 추출 
5. 이 과정을 지나는 동안 데이터조회 반응이 점점 느려지다가 먹통됨.

**Comment by namjals** [comment]
@yariyarishow  @pjh0347
위 사항을 여기서 테스트한다고 동일한 현상이 발생하는지 보장할 수 없고
발생하더라도 같은 원인으로 문제가 재현된다고 보장할 수 없습니다.
iris의 문제일 수 있고, spark의 자원환경의 문제일 수 있습니다.

서버에서 직접 디버깅할 수 있도록 접속정보를 공유해주시면 좋지만 어렵다면 여기서 실험은 해보겠습니다.

**Comment by yariyarishow** [comment]
이곳은 폐쇄망이어서 외부 접속이 불가합니다. 
테스트를 하려면 이곳에 방문하셔야 합니다.

**Comment by namjals** [comment]
현재 코트라에 방문했는데 테스트 가능한 모델명이 어떻게 되는지 문의드립니다.

**Comment by namjals** [comment]
약 5천만건정도 되는 "**수출통계" 데이터 모델에 대해, 검색, 피벗, 시각화를 여러번 했을때, 멈추거나 하는 현상이 없었습니다. 실제 재현이 되는 경우 로그를 받아봐야 할거 같습니다. 로그 확인하는 방법은 따로 업로드하겠습니다.

**Comment by namjals** [comment]
미들웨어(angora) 로그 10월 부터 11월 5일까지를 확인해봤는데, 원인이 되는 에러는 발견되지 않았습니다. 현재 spark core가 30, memory 4G으로 설정되어있는데, 속도가 느린경우 이 자원을 늘려야할 것으로 보입니다.

**Comment by namjals** [comment]
@yariyarishow 
자원을 늘리고 재현이 된다면 다시 열어주세요.
