### ISSUE TITLE
MDT / DB브라우저 / 다운로드 결과 파일이 빈파일로 생성됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1680]
## 버그 설명 ##
DB브라우저에서 sql조회 후 다운로드 실행시 결과 파일이 빈파일로 생성됨

실행SQL : SELECT * FROM OSDEV.MDT_GEOM dlimit 1 ; 

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/68362310-2eb50d80-016a-11ea-9638-1b2fd84ca581.png)

[저장 파일]
![image](https://user-images.githubusercontent.com/4444717/68362402-78055d00-016a-11ea-8398-914cf8ef2854.png)

**Comment by hiy2259** [comment]
현재 같은 동작으로 테스트 해보니 다운로드가 잘 실행되고 있습니다.

재현이 안되는 부분에 대해서는 향후 다시 문제가 발생시 파일 내용을 같이 올려 주시면 감사하겠습니다.

일단 파일 다운로드시 문제가 생기는 두가지 경우가 있습니다.

첫번째 파일을 다운 받을 때 데이터를 불러오는 과정에서 에러가 발생한 경우 에러 내용이 파일에 write 되므로 파일 또는 파일 내용을 전달해 주시면 에러 내용 보고 처리가 가능할 것 같습니다.

두번째 파일을 다운 받을때 데이터를 불러오고 데이터가 없을 경우 파일에 헤더만 write 되고 내용이 없을 수도 있습니다.

만약 두번째일 경우 테이블에 데이터는 있는데 IRIS에서 데이터를 가져오지 못해서 생기는 문제이므로 발생 즉시 플랫폼 연구팀에 문의해주시면 될거 같습니다.

**Comment by veldise** [comment]
에디터에서 쿼리 실행과 다운로드 차이는 다음과 같습니다.

#### 에디터:
- SQL에 `limit 5000` 추가하여 실행
- response 형식: `application/json`
- encoding: `UTF-8`

#### 다운로드:
- SQL 그대로 실행 (`limit 5000` 추가하지 않음)
- response 형식: `application/octet-stream` (binary)
- encoding: `EUC-KR`

파일에 헤더만 write 되고 내용(레코드)가 없는 경우, 아래와 같은 원인을 추가로 추측해볼 수 있습니다.
1. SQL 결과 데이터와 encoding이 맞지 않음
2. `.use` 명령어 이슈가 해결되지 않은 버전에서 수행

**Comment by veldise** [comment]
파일 다운로드는 다음과 같이 Java로 SQL 쿼리를 수행하고 이 결과를 csv 포맷으로 구성하는 식입니다.
```
Class.forName(irisDriver);

if (!userId.equals("root")) {
    irisUrl = irisUrl.replace("DEFAULT", userId.toUpperCase());
}

_conn = DriverManager.getConnection(irisUrl, userId, userPass);
_pstmt = _conn.prepareStatement(query);
_resultSet = _pstmt.executeQuery();
```

@anhm @donghwasuh 
잠시동안 운영서버에서 현상이 재현되어 확인해본 결과, 위 코드가 수행되었음에도
IRIS-DB에서 쿼리가 실행되지 않았고(`.session list` 결과 없음) 코드상 Exception도 발생하지 않았습니다.

그런데 동일한 동작을 했을 때 로컬 개발환경에서 현상이 재현되지 않았고,
db-browser 서비스를 재시작하자 운영서버에서도 현상이 재현되지 않았습니다.

이것으로 추측하기로는 `java.sql.*` 패키지 혹은 IRIS-DB jdbc 드라이버에 무언가 문제가 있어
장시간(약 2주) 코드를 수행하면 문제가 발생하는게 아닌가 합니다.

**Comment by ollehQ** [comment]
테스트를 진행해 본 결과 IRIS DB의 Error와 관련이 있는 것이 확인되었습니다.
IRIS DB에 Error가 발생하게 된다면, 다운로드를 하게 된다면 빈 파일이 나오게 됩니다.
Backend location file의 블록 파일의 위치정보의 소실 또는 Process Memory Limit로 인한 것으로 예상하고 있습니다.
만일 파일 위치 정보의 소실일 경우에는, Recover의 명령어를 통해 복구작업을 실행해야 합니다.
Process Memory Limit일 경우에는, 파티션의 범위를 줄이거나, dlimit query 구문을 사용하는 방법이 있을 것 같습니다.
혹시라도 같은 이슈가 발생할 경우에는, 이슈를 한 번만 다시 등록 부탁 드립니다.
해당 이슈는 닫도록 하겠습니다.
