### ISSUE TITLE
연결 정보 / OBJECTSTORAGE 연결 테스트를 하면 에러가 발생합니다.

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1682]
## 개요
OBJECTSTORAGE 선택 후 필요한 정보를 입력해서 연결 테스트를 했을 때 에러가 발생.

## 내용
* 아래와 같이 내용을 입력합니다.
![image](https://user-images.githubusercontent.com/5515493/68373308-f4596980-0185-11ea-907d-e8acf9676eb5.png)
* request body의 내용입니다.
![image](https://user-images.githubusercontent.com/5515493/68373355-181caf80-0186-11ea-90e3-ba57a2356dcc.png)
* 에러 메시지 입니다.
![image](https://user-images.githubusercontent.com/5515493/68373330-04714900-0186-11ea-8c04-c6a74b77aaed.png)
* endPoint 설정 문제가 있는거 같습니다.

**Comment by seungfwani** [comment]
@hiy2259 
현재 수정하여 연결 가능합니다.
![image](https://user-images.githubusercontent.com/46172579/68375460-3ab0c780-018a-11ea-99aa-5b4fbfa9ad5c.png)

`http://` 를 명시하는 방법 또한 가능 합니다.
![image](https://user-images.githubusercontent.com/46172579/68375516-54eaa580-018a-11ea-8409-e915f74f51ed.png)
