### ISSUE TITLE
ValueLinkU / Studio / 그리드 상단에 표현되는 목록개수&페이징&검색&다운로드 표현을 한줄로 처리

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1683]
## 기능 요청 ##
보고서에서 표형태의 그리드 출력시 표현되는 목록개수 / 페이징 번호 / 검색 / 다운로드에 대한 표현이 현재 상단에 목록개수 / 페이징번호 / 다운로드 가 표현되고, 하단에 검색이 표현되고 있음
이를 모두 한줄로 표현하는 방안 고려 요청(가로 크기가 줄어들 경우 2단으로 자동 변경 처리 필요)

출력하는 row수가 적은 경우 다운로드와 검색만을 표현했을경우 상단에 불필요하세 차지하는 공간이 많이 생김

[검색&다운로드만 보이게 하는 경우]
![image](https://user-images.githubusercontent.com/4444717/68439116-ccabe500-0209-11ea-8c32-5005eddc87a4.png)

[모두 표현된 경우]
![image](https://user-images.githubusercontent.com/4444717/68439235-2b715e80-020a-11ea-97ad-072e1e230964.png)

## 원하는 솔루션 설명 ##
그리드의 경우 상단에 목록개수 / 페이징번호 / 다운로드/ 검색이 모두 한줄로 표현(가로 크기가 줄어들 경우 2단으로 자동 변경 처리)

**Comment by JeongHeeDong** [comment]
현재 진행상황 또는 진행 일정 공유 요청 드립니다.

**Comment by onlyeon** [comment]
위 내용은 마크업 구조 변경과 차트 객체 사이즈에 따라 반응형으로 동작하도록 처리가 필요합니다.
#1549 , #1707 이슈와 함께 12월 말 쯤 처리 가능해 보입니다. 혹시 일정 조정이 필요하면 말씀해주세요!

**Comment by veldise** [comment]
현재 구조상 반응형으로 처리하기 어려워, 아래와 같이 '컨트롤 바 (1단/2단)' 옵션을 추가하여 요구사항을 만족할 수 있도록 하였습니다.

![image](https://user-images.githubusercontent.com/3411842/76599435-5ec15280-6548-11ea-9fc5-e8a029764a72.png)
