### ISSUE TITLE
[NMS+] 보고서 / Rest API로 가져온 값을 콤보박스, 체크박스, 라디오박스에 set 해주는 기능 요청

### ISSUE THREAD

**Issue by devjban** [mobigen/IRIS-BigData-Platform#1684]
## 기능 요청 ##
 - Rest API로 가져온 값을 콤보박스, 체크박스, 라디오박스에 set 해주는 기능
 - 현재는 텍스트박스에만 set 해주는데 그 외 콤포넌트에도 필요.
 - 현재 텍스트박스에 다음과 같이 설정
   ex) [ 설정할 변수/값 ] ${rest_api_2.metricValueCd}

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
![report](https://user-images.githubusercontent.com/40290202/68459495-eddff600-0248-11ea-87ef-4d7a946e09d1.png)

**Comment by rhcpn** [comment]
#1635  항목과 동일한 내용입니다.

**Comment by veldise** [comment]
구두로 다시 설명을 들어본 결과, #1635 기존에 구현된 내용은 콤보박스의 목록을 구성하기 위한 것이고
목록의 특정 항목을 선택(set)하기 위한 기능은 구현되지 않았습니다.
이에 대한 구현 방안 및 일정 등은 차주에 팀 내부에서 검토 후에 다시 알려드리겠습니다.

**Comment by veldise** [comment]
checkbox의 경우 combo와 달리 하나의 값이 아닌 여러개의 값을 설정하는 동작이라
별도로 진행중입니다.
