### ISSUE TITLE
MDT / sql error 90%

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1686]
## 버그 설명 ##
다음 SQL을 실행시키면 90%정도 에러가 발생하고 가끔씩 성공한다.
/*+ LOCATION ( PARTITION >= '20190501010000' AND PARTITION <= '20190501015959' ) */
SELECT * FROM  OSDEV.MDT_GEOM
where ST_Within(geomfromtext('POINT(' || LAT || ' ' || LON || ')'), geomfromtext('POLYGON((35.71460112595024 139.68189239501956, 35.71460112595024 139.85115051269534, 35.63846449878156 139.85115051269534, 35.63846449878156 139.68189239501956, 35.71460112595024 139.68189239501956))'))=1;

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. logon to b-iris by osdev
2. go to dbbrowser
3. run the sql above

## 예상한 행동 ##
정상실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/54348795/68537721-29470580-03ac-11ea-855f-4101f5127003.png)

## 로그 ##
없음

## 기타 ##
없음

**Comment by anhm** [comment]
해당 현상이 재현 되었습니다.
원인 파악중에 있습니다.

**Comment by anhm** [comment]
원인 파악 결과 쿼리 파서쪽에 이슈가 확인이 되었습니다.

해당 이슈를 처리하기 위해서는 약간의 시간이 걸릴 것으로 판단 됩니다.
아래와 같이 `geomfromtext` 첫번째 인자로는 컬럼이 들어가야 하는 상황입니다.

```
ST_Within(geomfromtext(geom, geomfromtext('POLYGON((35.71460112595024 139.68189239501956, 35.71460112595024 139.85115051269534, 35.63846449878156 139.85115051269534, 35.63846449878156 139.68189239501956, 35.71460112595024 139.68189239501956))'))
```

해당 내용은 요번주 중에 처리하여 패치를 진행하도록 하겠습니다.

**Comment by minjaekang7** [comment]
geomfromtext함수는 텍스트를 geom바이너리타입으로 바꾸어줍니다.
그러니까 geom컬럼내용이 단순 텍스트형태 'POLYGON((...' 이런식으로 들어가 있으면 문제없이 실행됩니다.

가령, geom이 텍스트인경우에는다음과 같이 실행하면 됩니다.
ST_Within(geomfromtext(geom), geomfromtext('POLYGON((35.71460112595024 139.68189239501956, 35.71460112595024 139.85115051269534, 35.63846449878156 139.85115051269534, 35.63846449878156 139.68189239501956, 35.71460112595024 139.68189239501956))'))

그러나 geom이 이미 바이너리 geom인 경우에는 geomfromtext가 불필요합니다.
ST_Within(geom, geomfromtext('POLYGON((35.71460112595024 139.68189239501956, 35.71460112595024 139.85115051269534, 35.63846449878156 139.85115051269534, 35.63846449878156 139.68189239501956, 35.71460112595024 139.68189239501956))'))

그런데, 에러가 발생하는 경우와 에러가 발생하지 않는 경우가 있습니다.
왜 그런건지 확인바랍니다.

**Comment by anhm** [comment]
해당 문제는 IRIS-DB 내에서 사용되는 쿼리파서에 이슈가 있었습니다.

위에서 말씀하신 형태의 쿼리가 동작하도록 수정해 두었습니다.
