### ISSUE TITLE
Demo System에 작성되어 있는 CI/CD-dashboard 에서 Tab 선택시 참고되는 List의 Index 정보가 정상 동작 하지 않습니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#1689]
## 버그 설명 ##
Demo System에 작성되어 있는 CI/CD-dashboard 에서 Tab 선택시 참고되는 List의 Index 정보가 정상 동작 하지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 데모시스템(180)에 접속
2. 보고서 항목중 "CI/CD-dashboard" Open
3. **하단에 보여주는 트랜드 정보가 무엇에 관련된 트랜드인지 인지를 할 수 없습니다.(버그1)**
4. **상단 왼쪽 리스트에서 Angora를 선택하고 하단 Tab에서 API테스트를 선택하면 원하는 결과가 나오지 않습니다.(버그2)**
5. 상단 리스트에서 E2E-TEST를 선택하였다가 다시 Angora를 선택하면 API 테스트 정상 출력.

**Comment by veldise** [comment]
3.
제가 잘 이해를 못한 걸 수 있는데, 각 차트에 "축 제목"을 설정하거나
Label 컴포넌트를 추가로 배치하는 것으로 개선 가능할 것 같습니다.

4.
탭 선택으로 화면에 표시(show)되어야만 실행이 되기 때문에 발생하는 것으로 생각됩니다.

현재 서버 부하 경감 목적으로 Area 등 실행 가능한 각 컴포넌트들은
화면에 표시된 상태(visible)일 때만 서버로부터 데이터를 받아오게 되어있습니다.

**Comment by sunghoon** [comment]
@veldise 자리에서 직접 구두로 상세 설명을 하였습니다.

**Comment by veldise** [comment]
3번)
현재 우상단 그리드뷰에 할당된 변수에 값이 들어있는데, 해당 행에 선택(selected)된 효과가 없습니다.

4번)
우상단 그리드뷰의 행을 선택하면 차트가 실행되도록 트리거 설정이 걸려있지만,
화면에 처음 진입시 "빌드평균점수" 탭이 선택되어있는 상태에서는
"API테스트" 탭의 show/hide 대상으로 설정된 각 객체들은 실행이 되지 않습니다.

따라서 이 경우 탭의 show/hide 대상으로 설정된 모든 객체들이 탭 선택이 변경됐을 때 실행되도록
트리거 설정을 걸어주면 해결됩니다.

**Comment by sunghoon** [comment]
@veldise 네. 알려주신 방법대로 설정하니 원하는 동작이 이루어 졌습니다. 감사합니다. ^^
