### ISSUE TITLE
[JDBC] R-studio 에서 JDBC 로 IRIS DB 접속 후 일부SQL 및 메소드  실행 시  connection끊어지는 문제

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1691]
## 버그 설명 ##
R 에서 JDBC 로 IRIS DB 접속 후 
1.  dbSendUpdate(conn, 'drop table if exists myTable;')
    실행 할 때, 
    myTable 이 있어서 drop table 이 되면 정상 동작하고
    myTable 이 없으면 connection 이 끊어져서 다시 IRIS DB 접속을 해야 합니다.

2. 그 외에 잘못 된 SQL/ 명령어 구문을  보낸 경우 접속세션은 유지 된 채 에러구문이 리턴되어야 할텐데
    접속이 끊어집니다.
    dbGetQuery('table list')    를 보내야 하는데
    dbGetQuery('tablelist')  로 잘 못 보내면  connection 이 끊어져서
    재접속을 해야 합니다. 

## 재현하는 방법 ##

- R 에서 접속 하는 방법 
   myiris  계정 접속 후 R-studio 의  home 디렉토리에 있는  RJDBC_v0.2.Rmd  파일을 참조하세요
<img width="455" alt="스크린샷 2019-11-14 오전 10 34 43" src="https://user-images.githubusercontent.com/5126497/68819089-66700800-06ca-11ea-8f63-bc48708425f1.png">

<img width="576" alt="스크린샷 2019-11-14 오전 10 26 09" src="https://user-images.githubusercontent.com/5126497/68818730-3a07bc00-06c9-11ea-9e04-537305393dc4.png">

    

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by anhm** [comment]
현재 JDBC 방식이 
쿼리등을 실패할 경우 connection을 종료하도록 개발이 되어 있는 상태입니다.
해당 이슈를 해결하기 위해서는 JDBC를 전체적으로 개선해야 하는 상황입니다.

**Comment by sunghoon** [comment]
@anhm @ollehQ 본 이슈에 대한 최종 진행 상태 정보를 공유 해 주세요.

**Comment by anhm** [comment]
@sunghoon 
JDBC API 개선은 우선수위가 낮아 현재 상황에서 일정이 잡혀있지 않은 상태입니다.

**Comment by sunghoon** [comment]
@seoryjj 우선순위 높여야 하는 경우 라면 추가 의견 바랍니다.

**Comment by seoryjj** [comment]
다른 사이트에서 관련 요청 사항이 없다면 일정대로 하시면 될 듯 합니다.( 제가 받거나 알고 있는 요청은 없습니다 )

만약 문의가 들어온다면 임시로 R 코드로 우회할 수 있는 방법으로 처리하겠습니다

**Comment by sunghoon** [comment]
@anhm 대략의 일정 계획을 세워 진행해 주시기 바랍니다. 정보 공유도 같이.
