### ISSUE TITLE
[HDFS Browser]검색에서 HDFS로 결과 내보내기 후, HDFS Browser에서 사용권한 거부됨.

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1694]
## 버그 설명 ##
검색 화면에서 데이터를 검색하여 HDFS로 결과 내보내기 성공하였으나,
HDFS Browser에서 사용 권한이 거부되어 해당 HDFS 파일을 볼 수 없음.

## 재현하는 방법 ##
1. myiris 계정으로 IRIS에 접속
2. 검색 화면에서 데이터 검색
3. 검색 결과에 대하여 '결과 내보내기' 버튼을 클릭 HDFS의 /temp/SKBB_download.csv/ 폴더에 업로드 성공 (스크린샷 1 참조)
4. HDFS 브라우저로 이동하여 좌측 트리에서 /temp/ 폴더를 더블클릭하였으나, 에러메시지 발생 (스크린샷 2 참조)
   - 이유: "사용 권한이 거부되었습니다."

## 스크린샷 ##
1. 스크린샷 1. 
![image](https://user-images.githubusercontent.com/23075670/68906310-30dd2480-0787-11ea-91be-174637230bb3.png)

2. 스크린샷 2.
![image](https://user-images.githubusercontent.com/23075670/68906433-8dd8da80-0787-11ea-8613-c9c685d03816.png)

**Comment by veldise** [comment]
@jins00 
HDFS 조회 기능에서 일반 유저는 기본적으로 계정과 동일한 이름을 가진 폴더 이하만 권한이 있습니다.
b-iris.mobigen.com 사이트에서 myiris 계정의 경우, `/B-IRIS/USERS/myiris/*` 에만 접근 권한을 가집니다.

따라서 접근 불가능한 것은 정상이고, 권한이 없는 폴더에 결과 내보내기가 가능한 것이 문제인데
"연결 정보"를 기반으로 결과 내보내기를 수행하다보니 모든 폴더에 접근이 가능한 상황입니다.
차후 개선이 필요한데, 현재로서는 어려운 부분입니다.
