### ISSUE TITLE
[NMS+]데이터 브라우저에서 기존에 조회하던 모델에서 에러발생

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1695]
## 버그 설명 ##
아래와 같이 데이터 브라우저에서 기존에 사용하던 모델인데 검색하면 에러가 발생합니다.

b-iris.mobigen.com 의 nmsplus.raw_snmp 입니다

## 재현하는 방법 ##

![에러](https://user-images.githubusercontent.com/5468183/69019919-10ff6800-09f6-11ea-9dbf-ef5d7ad903e0.PNG)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
특정 테이블이 손상된거 같습니다.
일부 샘플데이터에 대해서는 조회가 가능한데, 전체 데이터를 가져오려고 하면 발생하고 있고,
현재는 복구되었는지 바로 에러는 안나고 조회중인데, 결과 확인하고 다시 코멘트 달겠습니다.

**Comment by namjals** [comment]
분산되어있는 RAW_SNMP 테이블 중 192.168.100.135의 sqlite 파일이 손상되거나 없는거 같습니다.
```
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 324 in stage 8956.0 failed 4 times, 
most recent failure: Lost task 324.3 in stage 8956.0 (TID 516149, 192.168.100.135, executor 21): org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: RAW_SNMP)
```
일부 샘플 (10개, 혹은 3000개)를 가져올때는 정상동작합니다.
안**선임님께 문의해보겠습니다.

**Comment by anhm** [comment]
파일을 복구하여 정상적으로 정상적으로 쿼리가 되도록 수정했습니다.

**Comment by namjals** [comment]
![image](https://user-images.githubusercontent.com/22319132/69115364-999c0800-0acb-11ea-83df-b6f82d1d211b.png)
