### ISSUE TITLE
[KOTRA]테이블스페이스 화면조회 지연

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1696]
## 버그 설명 ##
테이블 스페이스 화면조회가 1분이 넘어가도 화면출력이 되지 않음

## 재현하는 방법 ##
1. Database 30개 생성
2. Database 별 평균 Tables 120개 생성 
(총 테이블수 약 3600개)
* 특정 Database의 경우 테이블수 450개 (5개 Databases)

## 예상한 행동 ##
1. 10초이내에 테이블스페이스 사용률 및 사용률현황 화면이 출력되길 기대.

**Comment by veldise** [comment]
@anhm
"테이블 스페이스(사용률 조회)" 화면 최초 진입시 IRIS-DB에 수행하는 명령어는 다음과 같습니다.
```
.statistics table --stime 20191129000000 --etime 20191206235959 -r 60 --summary --get-all
```

약 일주일치 데이터로, 명령어 결과를 얻는데 약 22초가 소요됩니다.
```

```
iplus> .statistics table --stime 20191129000000 --etime 20191206235959 -r 60 --summary --get-all
Ret : +OK Success


 UPDATE_TIME       NODE_ID    DATABASE_NAME    TABLE_NAME    TABLE_SIZE        NUM_OF_FILE    TABLE_SIZE_RAM    NUM_OF_FILE_RAM
==================================================================================================================================
 20191129000000    -1         -                -             11186708017062    329184         31293379611       2116
 20191129010000    -1         -                -             11186265285919    329083         31287800443       2116
 20191129020000    -1         -                -             11185608155458    329079         31277633027       2115

 ... 중략 ...
==================================================================================================================================

163 row in set

21.7975 sec

iplus>
```

다른 이슈(#1728)에서 Database 개수가 많을 수록 성능이 저하된다는 말이 있습니다.
이와 관련해서 검토가 필요합니다.

**Comment by anhm** [comment]
```
iplus> .statistics table --stime 20191129000000 --etime 20191206235959 -r 60 --summary --get-all

Ret : +OK Success


 UPDATE_TIME       NODE_ID    DATABASE_NAME    TABLE_NAME    TABLE_SIZE        NUM_OF_FILE    TABLE_SIZE_RAM    NUM_OF_FILE_RAM
==================================================================================================================================
 20191129000000    -1         -                -             11186708017062    329184         31293379611       2116
 20191129010000    -1         -                -             11186265285919    329083         31287800443       2116
 20191129020000    -1         -                -             11185608155458    329079         31277633027       2115
...
 20191206230000    -1    -    -    11166804774891    332075    31228335744    2274
==================================================================================================================================

175 row in set

7.7344 sec
```

내부 기능을 개선해서 속도를 개선했습니다.
이 이상의 개선은 현 단계에서는 힘들것 같습니다.

**Comment by yariyarishow** [comment]
> ```
> iplus> .statistics table --stime 20191129000000 --etime 20191206235959 -r 60 --summary --get-all
> 
> Ret : +OK Success
> 
> 
>  UPDATE_TIME       NODE_ID    DATABASE_NAME    TABLE_NAME    TABLE_SIZE        NUM_OF_FILE    TABLE_SIZE_RAM    NUM_OF_FILE_RAM
> ==================================================================================================================================
>  20191129000000    -1         -                -             11186708017062    329184         31293379611       2116
>  20191129010000    -1         -                -             11186265285919    329083         31287800443       2116
>  20191129020000    -1         -                -             11185608155458    329079         31277633027       2115
> ...
>  20191206230000    -1    -    -    11166804774891    332075    31228335744    2274
> ==================================================================================================================================
> 
> 175 row in set
> 
> 7.7344 sec
> ```
> 
> 내부 기능을 개선해서 속도를 개선했습니다.
> 이 이상의 개선은 현 단계에서는 힘들것 같습니다.

현 단계에서 힘드니 다음 단계로 넘어갈까요?

**Comment by sunghoon** [comment]
@veldise @anhm 해당 이슈 진행 어떻게 되었는지 최종 상태를 공유해 주세요.

**Comment by anhm** [comment]
@sunghoon 
해당 이슈는 IRIS-DB의 구조적 이슈로 현 단계에서 개선은 힘든 상황이며,
더 개선이 필요할 경우 프로토콜을 변경하는 작업을 진행해야 합니다.

**Comment by sunghoon** [comment]
@yariyarishow 검토의견 바랍니다.

**Comment by sunghoon** [comment]
별다른 검토 의견이 없고, 오래된 이슈라 닫겠습니다. 
비슷한 이슈가 다시 발생하면 새 이슈로 다루겠습니다.
