### ISSUE TITLE
[수원시] 테이블 조회 화면 redirect 인터페이스 및 기능

### ISSUE THREAD

**Issue by outsider8721** [mobigen/IRIS-BigData-Platform#1697]
## 기능 요청 ##
외부 WEB에서 **테이블과 관련된 지표 선택 시** 
IRIS의 **테이블 조회 화면으로 redirect** 시키는 기능 요청이 들어옴(수원시)

## 원하는 솔루션 설명 ##
IRIS의 테이블 별로 접근 가능한 URL 정보

**Comment by rhcpn** [comment]
- 2019/11/19 DT개발2팀 김성준 선임과 회의 결과, 해당 내용은 **_수원시에서 설정한 파라메터로 IRIS의 데터이브라우저 > 검색으로 이동하여 자동 검색 결과 출력 기능_** 으로 처리하기로 합의 하였습니다.
- IRIS 데이터브라우저 기능 중에 LocalStorage 에 특정 모델과 쿼리를 지정하여 자동 실행하는 기능이 요구 기능과 비슷해 보입니다.

**Comment by rhcpn** [comment]
## IRIS 데이터 브라우저 페이지에 파라메터를 전달 하여 새창으로 띄우는 방법
### 개요
해당 기능을 수행 하기 위해 1. 원격에서 IRIS 쪽에 데이터 모델을 생성 하고 2. 데이터 모델 및 수행 하고자 하는 Angora 쿼리를 파라메터로 생성 하여 IRIS 페이지를 호출 하여 처리 하도록 한다.

### 원격에서 IRIS DB 테이블을 이용하여 데이터 모델 생성
#### 처리 방법
- IRIS DB 테이블 리스트 조회
  - Angora "directdb tablelist" 명령어 사용
- IRIS에 데이터 모델 CRUD
  - Angora "Data model API" 사용
  - 해당 기능을 위해서 Angora Token 생성이 필요. 계정은 IRIS Web 사용자 정보 이용
- 파라메터를 이용하여 IRIS 데이터브라우저의 검색을 바로 실행
  - 수원시에서 SSO 인증 후, IRIS Web에서 제공하는 URL에 파라메터를 붙여서 호출
  - 파라메터 예시 (search?q=*&d=61aa1a9e-b6f5-4196-9bef-9b3b62fcff43&t.start=-1m&t.end=now&t.preset=null&distinct_count=false&jt=1574224726174)

#### 고려사항
- Angora 관련 명령어는 이미 존재하고 있으며, 플랫폼 연구팀에게 문의 필요
- 파라메터를 통한 IRIS Web 데이터브라우저 실행 URL은 개발 필요
