### ISSUE TITLE
[수원시] 수원시 권한과 IRIS 권한 연동 처리

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#1699]
## 기능 요청 ##
수원시의 메타관리시스템의 조직정보 및 사용자 Role 권한을 IRIS의 권한 정보와 연동 하여
IRIS 쪽 메뉴, 데이터 모델 접근 제한 기능을 처리 해야 함.

### 권한 처리 방안
- IRIS는 현재 단일 계층 구조의 그룹 권한을 가지고 있음
- 메타관리시스템은 다중 계층 구조의 그룹 권한 및 사용자 Role 권한도 따로 가지고 있음
- 둘의 차이를 해소하기 위해, 다음과 같은 과정으로 양쪽의 권한 처리 차이점을 처리 할 예정
  - 수원시에서는 그룹 관리는 마지막 단계의 그룹만  IRIS와 연동
  - 그룹 정보 동기화는 주기적으로 수원시에서 IRIS API를 호출 하여 처리
  - 사용자 당 그룹아이디가 2개가 존재
    - Role , 조직
    - SSO 로 IRIS 접속 시, 사용자 그룹 리스트 전달 
    - IRIS 쪽에서 그룹 리스트로 메뉴, 모델 필터링

**Comment by rhcpn** [comment]
## 2019/11/19 DT개발팀 김성준 선임과 회의 내용
- 결정사항
	+ RestAPI를 기반으로 전달
	+ 메타관리시스템(수원시)에서 마지막 depth의 조직정보를 전달, IRIS에서는 마지막 depth의 조직정보 관리
	+ 롤 그룹 따로 관리 필요	
		- SSO 연동시 role group, organization group을 전달 예정

 - 메뉴 인가
	+ 개발 가능성 확인 후 RestAPI 개발 (UI솔루션연구팀)
	+ 주기 및 수시 권한 연동(DT개발2팀)

 - 테이블 인가
	+ 개발 가능성 확인 후 RestAPI 개발 (UI솔루션연구팀)
	+ 주기 및 수시 권한 연동(DT개발2팀)

 - 보고서 인가
	+ 개발 가능성 확인 후 RestAPI 개발 (UI솔루션연구팀)
	+ 주기 및 수시 권한 연동(DT개발2팀)

 - 메타시스템과 IRIS 화면 연동
	+ 메타시스템에서 테이블과 관련된 지표 선택시 해당 테이블정보를 분석할 수 있는 하면으로 redirect 할수 있는 기능이 필요
	+ 개발 가능성 확인 후 개발

 - 추가 확인 필요사항 (회의때 누락된 부분입니다.)
	+ 메타시스템에서 관리하는 권한보다 IRIS에서 직접적으로 관리하는 권한을 우선적으로 해야함
	+ 인가정보 연동시 직접적으로 관리한 권한을 배제할 수 있는 방안이 필요해 보임

 - 개발 일정
	+ 수원시 가오픈 12월 초중 예정
	+ 수원시 최종 오픈 1차 통합테스트 (1월 20일 예정)
	+ 수원시 최종 오픈 3차 통합테스트 (2월 17일 예정)
	+ 위 추가 사항은 1월중으로 개발 마무리가 되어야 3차 통합 테스트때 기능 검증할 수 있음

 - 요청사항
	+ 대략적인 설계가 나오면 전달 요청. 해당 설계안을 확인 후 커뮤니케이션 누락이 된 부분에 대하여 확인할 필요가 있어 보임(김성준S)

**Comment by rhcpn** [comment]
## 수원시 메타관리시스템과 IRIS Web 권한 연동 처리 방안
### 개요
수원시의 계층 구조의 그룹과 역할 Role 권한을 IRIS Web의 단일 구조의 그룹에 연동 하기 위해 
1. 수원시 계층 그룹의 마지막 단계의 그룹만 IRIS와 동기화 하고, 
2. 역할 Role 도 그룹으로 간주하여 IRIS에 동기화 하며, 
3. 동기화는 수원시에서 IRIS API를 이용하여 처리하도록 하며, 
4. SSO 연동 시 수원시에서 사용자의 그룹 리스트를 Token으로 구성하여 인증 후
5. IRIS에서 그룹 리스트를 토대로 메뉴, 데이터 모델 접근권한을 처리하는것으로 한다.

### 데이터 동기화 처리 방법
#### 처리 방법
- IRIS에서 제공 가능한 동기화 API 항목
  - 메뉴 CRUD API
  - 메뉴 권한 CRUD API
  - 데이터 모델 권한 CRUD API
  - 그룹 CRUD API
  - 사용자 정보 업데이트 API

- IRIS 관리자가 수정한 정보에 대한 우선권 처리 
  - IRIS 쪽 권한 관련 테이블에 LOCK 컬럼을 추가하여 동기화 시 예외 처리

- SSO 연동
  - 수원시에서 SSO 연동시 사용자당 소속그룹, Role 그룹 아이디 두가지를 IRIS에 전달
  - 통상적으로는 IRIS에서 인증과 동시에 Token을 생성하여 전달 하지만 해당 경우에는 수원시에서 인증 성공 후, 자체적으로 Token 생성을 해야 함. (Token 생성 라이브러리 제공 예정)

#### 고려사항
- IRIS 관리자 수정 정보 우선 처리 부분은 개발 필요
- IRIS Web에서 로그인 시, 복수개의 그룹으로 권한 처리 하는 부분 개발 필요

**Comment by veldise** [comment]
2번째 그룹아이디는 수원시만을 위한 별도 버전으로,
Lock 기능은 정식버전에도 포함되어 패치될 예정입니다.
