### ISSUE TITLE
MDT / update 처리가 끝나지 않는다

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1702]
## 버그 설명 ##
다음 갱신은 3.39초에 끝납니다.
/*+ LOCATION ( PARTITION >= '20190301100000' AND PARTITION <= '20190301105959' ) */
update OSDEV.MDT_TEST set geom=geomfromtext('POINT(' || MESH500_CY || ' ' || MESH500_CX || ')');
실제 데이터도 1시간분만 들어가 있습니다.

그런데 다음의 갱신은 실행후 끝나지 않습니다.
/*+ LOCATION ( PARTITION >= '20190401100000' AND PARTITION <= '20190401105959' ) */
update OSDEV.MDT_GEOM set geom=geomfromtext('POINT(' || MESH500_CY || ' ' || MESH500_CX || ')');
이 테이블은 데이터가 많기는 하지만 1시간분의 데이터만 갱신요구했기에 3-4초정도로 끝날 것으로 기대됩니다. 위에서 설정된 파티션만 실행되지 않고 전 데이터를 갱신하는 것은 아닌지요? 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'DB Browser'
2. 위 명령어를 실행

**Comment by anhm** [comment]
테스트를 진행해본 결과 index 와 관련이 있는것이 확인 되었습니다.
index 를 생성한 이후에 update를 진행할 오랜 시간이 걸리고 있으며,
index를 삭제한 이후에 진행을 하면 3~4초로 끝나는 것이 확인 되었습니다.

해결 방법으 파악중에 있으며, 처리가 완료되면 내용을 공유 드리겠습니다.

**Comment by anhm** [comment]
내부적으로 index 관련 부분을 개선 했습니다.

현재 테이블에 생성되어 있는 index는 수정을 완료해 두었습니다.


현재 하나의 블럭 파일 기준으로
```
update MDT_TEST set geom=geomfromtext('POINT(' || MESH500_CY || ' ' || MESH500_CX || ')');
```
와 같은 쿼리를 통한 업데이트를 진행시 
블럭파일 기준 초당 약 15000 건식 update가 이루어집니다.
(IRIS-DB 를 이용시 약간 더 느림)

```
iplus> /*+ LOCATION ( PARTITION >= '20190401100000' AND PARTITION <= '20190401105959' ) */
     > update OSDEV.MDT_GEOM set geom=geomfromtext('POINT(' || MESH500_CY || ' ' || MESH500_CX || ')');
Ret : +OK

31.2480 sec

iplus> /*+ LOCATION ( PARTITION >= '20190401100000' AND PARTITION <= '20190401105959' ) */
     > select count(*) from OSDEV.MDT_GEOM;
Ret : +OK Success


 COUNT(*)
============
 387761
============

1 row in set

0.1573 sec
```
