### ISSUE TITLE
MDT / how to load geom

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1703]
## 기능 요청 ##
csv, tsv화일로부터 로드할 때 geom데이터의 경우에는 어떻게 설정해야하는 지 알려주시기 바랍니다.

## 원하는 솔루션 설명 ##
단순히 텍스트로 POINT(37.127423 132.483483) 형태로 입력하면 텍스트로 데이터가 들어갑니다.
geom타입으로 들어가야하는 데 텍스트가 되어버립니다.

**Comment by anhm** [comment]
파일에서 로딩을 할때
데이터 파일과 컨트롤 파일이 사용하게 되는데,
이때 사용하는 컨트롤 파일을 다음과 같이 `+`를 적어 주시면 됩니다.

```
table_partition
table_key
+geom
geom_json
```

위에는 `geom` 컬럼이 POINT가 들어가는 컬럼이 됩니다.
