### ISSUE TITLE
MDT / index정보표기 오류

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1705]
## 버그 설명 ##
b-IRIS에서 LON, LAT에 대한 인덱스를 만들었지만 Table Details에서는 인덱스로 표현되고 있지 않다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'DB 브라우저'
2. Click on 'MDT_TEST' and click right and 'Table Details'

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/54348795/69305037-01865600-0c66-11ea-8659-5a10752946aa.png)

**Comment by anhm** [comment]
@veldise 특이 사항으로 공간-db가 아니더라도 IRIS-DB 와 다른 값을 보여주는 것 같습니다.
해당 화면을 위해 사용되는 쿼리를 알려 주시면 좀더 확인을 진행해 보도록 하겠습니다.

현재  공간DB 의 인덱스 정보는 IRIS-DB에서 정상적으로 전달이 안되고 있습니다.
금일 내에 패치가 진행될 예정입니다.

**Comment by veldise** [comment]
본문 스크린샷에 해당하는 "테이블 상세 정보"에서는 아래와 같이 3가지 명령어를 실행하고 있습니다.
```
.table columns ${dbName}.${tableName}
.table info ${dbName}.${tableName}
.table schema ${dbName}.${tableName}
```

**Comment by anhm** [comment]
@mobigen/iris-addon 
test

**Comment by anhm** [comment]
@mobigen/iris 
test

**Comment by sunghoon** [comment]
@anhm 해당 이슈 어떻게 진행 되었는지 최종 상태를 공유해 주세요.
