### ISSUE TITLE
MDT / drop index에러

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1706]
## 버그 설명 ##
b-IRIS에서 다음 명령어를 실행하면 drop할 때 에러(Unknwon Query)가 발생한다.
create index mdt_test_lat on MDT_TEST(LAT);
drop index if_exists  mdt_test_lat;

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'DB Browser'
2. 위 버그설명의 명령어를 차례로 실행
3. 에러가 발생한다

**Comment by anhm** [comment]
에러가 발생한 원인은 쿼리 문법 이슈입니다. `if_exists` 에서 `_` 가 생략 되어야 합니다.

- 인덱스 생성시
```                                                        
create index if not exists mdt_test_lat_test on OSDEV.MDT_TEST(LAT);     
```

- 인덱스 삭제시
```
drop index if exists mdt_test_lat_test on OSDEV.MDT_TEST;
```


이외로 `Unknwon Query` 에러는 다른 이슈가 존재하는 것이기 때문에, 이슈를 따로 생성해 두도록 하겠습니다.

**Comment by anhm** [comment]
추가적으로 
해당 테스트는 iplus (콘솔) 에서 테스트를 진행했습니다.

테스트 결과 DB-WEB으로 진행할 경우 `Line 4 ~ 4 : Unknown Query` 가 발생하며, 해당 이슈를 처리하기 위해 따로 이슈를 등록하도록 하겠습니다.
