### ISSUE TITLE
ValueLinkU / Studio / 그리드 다운로드 버튼 표시 선택 시 가로스크롤 표시 문제

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1707]
## 버그 설명 ##
그리드 다운로드 버튼 표시 선택 시 가로스크롤이 밑으로 내려가 세로스크롤을 해야 보이는 문제
다운로드 버튼 표시 선택 해제하고 아무것도 선택안하면 그리드 상단 알수없는 여백때문에 정상적으로 가로스크롤이 안보임.
필터만 선택할 경우 가로스크롤이 정상적으로 보임.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
다운로드 표시 선택 시
![image](https://user-images.githubusercontent.com/7067615/69513513-59390000-0f8b-11ea-8ac8-15eefff4d628.png)

다운로드 표시 선택 해제 시
![image](https://user-images.githubusercontent.com/7067615/69513551-7968bf00-0f8b-11ea-95e1-278b0d178206.png)

다운로드 표시 선택 해제하고 필터 선택 시
![image](https://user-images.githubusercontent.com/7067615/69513570-8dacbc00-0f8b-11ea-8d4a-f04bdf29e499.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
해결된 내용으로 보고 닫습니다.
