### ISSUE TITLE
MDT / 공간인덱스가 빠르지 않음

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1708]
## 버그 설명 ##
아래와 같이 검색하면 4.5초정도 소요됩니다.
```
/*+ LOCATION ( PARTITION >= '20190301100000' AND PARTITION <= '20190301105959' ) */
SELECT count(*)
FROM OSDEV.MDT_TEST
where ST_Within(geom, geomfromtext('POLYGON((35.71460112595024 139.68189239501956, 35.71460112595024 139.85115051269534, 35.63846449878156 139.85115051269534, 35.63846449878156 139.68189239501956, 35.71460112595024 139.68189239501956))'))
;
```

다음과 같이 공간인덱스를 만들었습니다.
CREATE INDEX MDT_TEST_GEOM ON MDT_TEST (geom rtree);

그런데 여전히 검색속도가 전혀 낳아지지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'DB Browser'
2. 위의 쿼리 실행하여 실행시간 비교

## 예상한 행동 ##
1초이내로 결과가 나올 것으로 예상(어디까지나 개인의견)
가령, 인덱스가 없어도 다음과 같은 쿼리를 실행하면 0.3초정도 걸립니다.
/*+ LOCATION ( PARTITION >= '20190301100000' AND PARTITION <= '20190301105959' ) */
SELECT count(*)
FROM OSDEV.MDT_TEST
where MESH500_CX between 139.68189239501956 and 139.85115051269534 and MESH500_CY between 35.63846449878156 and 35.71460112595024;

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by anhm** [comment]
내용을 확인해본 결과 검색되는 대상이 많아서 발생하는 이슈 입니다.

해당 범위의 전체 개수:  388051, 소요시간 6s
조건에 해당하는 개수: 244828, 소요시간 4s

확인을 위해서 검색 범위를 다음과 같이 테스트를 진행했습니다.
```
iplus> /*+ LOCATION ( PARTITION >= '20190301100000' AND PARTITION <= '20190301105959' ) */
     > SELECT count(*)
     > FROM OSDEV.MDT_TEST
     > where ST_Within(geom, geomfromtext('POLYGON((35.71460 139.68189, 35.71460 139.6933, 35.71033 139.6933, 35.71033 139.68189, 35.71460 139.68189))'))
     > ;
Ret : +OK Success


 COUNT(*)
============
 329
============

1 row in set

0.1286 sec
```
