### ISSUE TITLE
IRIS WEB 메뉴에서 테이블 관리 메뉴가 안보입니다.

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1709]
## 버그 설명 ##
root 권한으로 로그인했는데 테이블 관리 메뉴가 보이지 않습니다.

확인부탁드립니다.

## 스크린샷 ##
![메뉴화면](https://user-images.githubusercontent.com/7123538/69518248-6dd0c480-0f9a-11ea-80c9-a0058c168094.png)

**Comment by veldise** [comment]
현재 클러스터 관리 > 테이블 권한 메뉴는 정상 동작하지 않아 메뉴를 잠시 삭제한 상태입니다.
IRIS-DB의 데이터베이스나 테이블에 권한을 부여하고자 하면 서버에서 아래와 같이 grant/revoke 명령어를 사용하시면 됩니다.

```
iplus> GRANT ${PRIV_LIST} ON ${DB_NAME}.${TABLE_NAME} TO ${USER_ID}@*;
```
ex)
```
GRANT SELECT ON TEST.TEST_LOCAL_TABLE TO user1@*;
```
```
iplus> REVOKE ${PRIV_LIST} ON ${DB_NAME}.${TABLE_NAME} FROM ${USER_ID}@*;
```
ex) 
```
REVOKE SELECT ON TEST.TEST_LOCAL_TABLE FROM user1@*;
```

아래 사이트에 메뉴얼이 있으니 참고하시고, 더 자세한 내용은 플랫폼연구팀 안형민 선임에게 문의하시면 됩니다.
http://iris.mobigen.com/manual/IRIS-DB_Doc/dbmanager_guide/doc/02.privilege.html#id2

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
