### ISSUE TITLE
ValueLinkU / Studio / 콤보박스 DSMS 설정 후 자동실행 적용안됨

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1710]
## 버그 설명 ##
콤보박스에 데이터 모델이 아닌 DSMS 적용하여 보고서 화면 생성 시 자동실행이 적용 안됨.
데이터 모델로 변경하여 적용했습니다. 확입부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
@SONHOJUN @veldise  
DSMS 는 비동기로 실행을 하고 있어 리포트 화면 진입후 시간차가 발생하는데 이부분이 의심됩니다.
자동실행되지 않는 샘플 리포트를 알려주시면 빠른 검토가 가능할것으로 판단됩니다.

**Comment by sunghoon** [comment]
해당 기능은 지원되는 것으로 알고 있습니다.
같은 이슈가 발생하면 다시 등록 바랍니다.
