### ISSUE TITLE
MDT / Import Data 동시접속 에러

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1716]
## 버그 설명 ##
kcme계정으로 4명이 로그인 한 후에 같은 구조의 테이블을 4개 만들고 동시에 4명이 Import Data를 수행하면 1명만 성공하고 나머지는 모두 실패하는 현상이 발생한다.
같은 교육받는 교육생이 동시에 오퍼레이션을 할 때 이런 현상이 자주 발생하였다.
사용된 테이블은 MDT_KCME0, MDT_KCME1, MDT_KCME_2, MDT_KCME3이고 사용된 화일은  MDT_20190301_H10.tsv로 /home/eva/MDT/ZIP/20190301에 gz확장자로 저장되어 있음.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. kcme / kcme!@# 로 로그인 Go to 'Import Data'
2. 각자 위 테이블을 지정하고 submit
3. 에러 발생

## 예상한 행동 ##
에러없이 동시에 처리가 되어야할 것으로 기대되었다.

## 스크린샷 ##
취득 못함

## 로그 ##
없음

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@minjaekang7 
어떤 에러가 발생했는지 화면에 출력된 에러 텍스트를 적어주실 수 있나요?
그리고 `MDT_20190301_H10.tsv` 파일의 크기를 알려주시면 감사하겠습니다.

**Comment by veldise** [comment]
#1724 와 함께 해결된 것으로 보고 닫습니다.
문제가 재발하면 reopen 해주세요.
