### ISSUE TITLE
[NMS+]보고서 컴포넌트의 숨김/보임 속성의 동적 세팅 기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1717]
## 기능 요청 ##
권한에 따라 컴포넌트를 실행할수있게 하기위한 기능으로 
숨김/보임 속성이 동적으로 세팅될수 있도록 요청드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@jjinylee 해당 요청에 대한 기능 요구가 높은가요?

**Comment by jjinylee** [comment]
고려안하셔도 됩니다.
