### ISSUE TITLE
[NMS+]보고서 그리드의 속성추가

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1718]
## 기능 요청 ##
1. 그리드의 컬럼에 이미지/색상을 넣을수 있는 기능
 - NMS 기능상 알람을 표현할때 Critical/Major/Minor 등을 가시적으로 보이게하는 기능이 기본이라 필요

2. 그리드의 다수개의 행을 선택할수 있는 기능
3. 그리드에 컬럼에 컴포넌트(버튼)을 넣을수 있는 기능 (2번이 포함될라나요)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
다른 항목들은 검토해봐야 하지만, 3번 "그리드 컬럼에 컴포넌트(버튼)을 넣는 기능"은
현재 Studio 구조상 불가합니다.
객체 및 객체 ID는 유일하며 다른 객체를 포함하는 형태가 될 수 없습니다.

**Comment by sunghoon** [comment]
일부 기능 처리된 것으로 보며, 미 지원 기능에 대한 추가 검토 요청이 필요시 새 이슈로 등록 바랍니다.
