### ISSUE TITLE
195번 서버에서 데이터모델 생성 및 편집시 angora error 발생

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1719]
## 버그 설명 ##

QA 테스트용 서버(192.168.102.195) 에서 데이터모델 생성시,

임의의 연결 정보를 클릭할 경우 다음과 같은 에러 발생. (MariaDB, IRIS 상관 없이 발생)

![image](https://user-images.githubusercontent.com/37629503/69769080-9b9a5100-11c6-11ea-9ed8-6860a2e64791.png)

검색, 피벗분석, 시각화, 이상탐지에서 데이터모델 조회시 다음과 같은 에러 발생.

![image](https://user-images.githubusercontent.com/37629503/69769168-16fc0280-11c7-11ea-9b18-1043d9275bc1.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. 192.168.102.195 서버 접속 후, 로그인
2. 좌측 상단 카테고리에서 {데이터 브라우저 > 관리 > 데이터 모델} 항목으로 이동
3. 우측 상단 '새 모델' 클릭
4. '연결 정보' 의 왼쪽 드롭다운 박스에서 'IRIS' 선택 (다른 항목을 선택해도 상관 없음)
5. '연결 정보'의 오른쪽 드롭다운 박스에서 '180_temp' 선택 (다른 항목을 선택해도 상관 없음)

## 예상한 행동 ##

다음 화면과 같이 '성공' 이 표시되는것을 기대함. (해당 화면은 180번 서버에서 캡쳐)

![스크린샷 2019-11-28 오전 10 26 42](https://user-images.githubusercontent.com/23020977/69769770-9a1e5800-11c9-11ea-8c55-12803ab70e3d.png)

**Comment by seungfwani** [comment]
@leehaejoon 
spark 2.4.4 버전으로 변경되어 발생한 에러로, 재설치 하여 해결 하였습니다.
![image](https://user-images.githubusercontent.com/46172579/69839270-26984b80-129a-11ea-9f94-6ad68f503793.png)
