### ISSUE TITLE
195번 서버에서 새 보고서 클릭시 알 수 없는 오류 발생

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1721]
## 버그 설명 ##
QA 테스트용 서버(192.168.102.195) 에서 '새 보고서' 클릭시 다음과 같은 오류 발생

![스크린샷 2019-12-02 오전 10 03 30](https://user-images.githubusercontent.com/23020977/69923874-3064bd80-14eb-11ea-8a1c-673d0ab1bae5.png)

- 해당 오류 팝업은 '예' 버튼을 5번가량 클릭해야 사라짐
- 오류 팝업이 사라진 이후에는 문제 없이 동작하는 것으로 보임

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. 192.168.102.195 서버 접속 후, 로그인
2. 좌측 상단 카테고리에서 {데이터 브라우저 > 관리 > 보고서} 항목으로 이동
3. 우측 상단 '새 보고서' 클릭

**Comment by veldise** [comment]
아래와 같은 요청/응답에 의한 에러 출력입니다.

`GET http://192.168.102.195/sms/v1/root/alarm/agent`

```js
{"message": "'NoneType' object has no attribute 'empty'", "code": 99999}
```

**Comment by leehaejoon** [comment]
@anhm 동일 현상이 쿠버네티스 클러스터에서도 발생중입니다. 휴가 복귀 이후 확인 부탁드리겠습니다.

**Comment by big-mobigen** [comment]
안녕하세요 운용기술연구팀 한유종입니다. 

도움이 되실까하여 comment 를 남깁니다.

service/conf/sms/sms.conf 파일에 0.0.0.0 설정된 ip를 분석서버 or iris-db서버에 ip로 변경할 경우 해당에러가 나타나지 않습니다.

해당에러메세지는 sms.conf 파일을 수정하면 나타나지 않는 점 참고 부탁드립니다. 

감사합니다.

**Comment by EricLeeMbg** [comment]
sms 조치되어 닫음
