### ISSUE TITLE
[검색] 창에서 fit 명령어로 기계학습 실행 결과 에러 발생

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1722]
## 버그 설명 ##
저장된 분석템플릿( 예전에는 정상적으로 값이 나와서 저장된 분석템플릿으로 저장된 것)을 불러오기 한 후 
저장할 모델 이름만 변경후 실행 
-> 10여분 넘게 실행 중이더니 다음 2개의 에러 팝업창을 띄워줌

## 재현하는 방법 ##
동작을 재현하는 방법 :
1.  b-iris.mobigen.com 접속 / myiris 계정 / 검색창에서 분석 템플릿 불러오기
2. 분석 템플릿명 :  CMD_cast_syslog_org2_rf_classifir_fit
3. 검색창의 command 창에서 구문에서 가장 마지막 줄의 저장할 model 이름을 변경 한 후 실행(이름이 중복 안되도록 하기 위함)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
<img width="1059" alt="스크린샷 2019-12-02 오후 3 46 02" src="https://user-images.githubusercontent.com/5126497/69936972-aafa0100-151c-11ea-9c9d-56344b0e65c6.png">

<img width="904" alt="스크린샷 2019-12-02 오후 3 46 11" src="https://user-images.githubusercontent.com/5126497/69936979-acc3c480-151c-11ea-8015-2f72c032478d.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
과거 특정 시점의 시스템 운영 관련 사항이라 조치된 것으로 보고 닫습니다.
