### ISSUE TITLE
[오류레포트] 계정이 속한 그룹을 (일반 그룹이 아닌) 특정 그룹으로 바꾸면 "URL을 받아올수 없습니다."  에러가 화면에 발생함.

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#1725]
## 버그 설명 ##
[오류레포트] 계정의 소속그룹을 "기본 그룹" 아닌 그룹으로 수정하면 "URL을 받아올수 없습니다."  라는 에러가 화면에 발생함.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 신규계정 ("heehanyoon")을 "Diamond-E"라는 그룹 소속으로 생성하고, 해당 계정으로 로그인 하면,
2. 화면에 "URL을 받아올수 없습니다." 라는 오류화면이 뜨면서, 메뉴에도 3가지 메뉴만 출력됨.
3. **참고로 크롬과 익스플로러에서 모두 시험했으며, 브라우저 캐시 없이 시험했음.** 

## 예상한 행동 ##
 * [오류레포트] 계정의 소속그룹을 "기본 그룹" 아닌 그룹으로 수정하면 "URL을 받아올수 없습니다."  라는 에러가 화면에 발생함.
 * 버그가 의심되는 기능 : 
     * 사용자 계정의 속성을 추가하면 뭔가 버그가 동작하는것 같습니다.
        * 왜냐하면, 기존에 잘 사용하던 "diamonde" 계정도 "일반 그룹"에서 "Diamond-E" 라는 그룹으로 바꿔서 저장하고, 해당 계정 로그인 해 보면, 동일한 에러가 발생하기 때문임. 
 * 그래서, 다시 "일반 그룹"으로 바꾸면 두개 계정 모두 정상 동작합니다. 

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3426052/70142339-59987000-16dc-11ea-9f67-f060671f4dc0.png)
![image](https://user-images.githubusercontent.com/3426052/70142523-c27fe800-16dc-11ea-9563-9d1a914c6f72.png)

## 로그 ##
(없음)

## 기타 ##
(없음)

**Comment by veldise** [comment]
확인 결과, 계정/그룹/메뉴에 대해서 권한이 아래와 같았습니다.
1. heehanyoon 계정은 "DB 조회 > DB 브라우저" 메뉴에만 권한이 있습니다.
2. Diamond-E 그룹은 어떤 메뉴에도 권한이 없습니다.
3. "데이터 브라우저 > 관리 > 작업 조회" 메뉴는 모든 사용자에게 접근 권한이 부여된 상태입니다.
4. 기본 그룹은 모든 메뉴에 권한이 부여되어 있습니다.

이 중에서 3, 4번은 잘못 설정된 상태입니다.
누군가 "데이터 브라우저 > 관리 > 작업 조회" 메뉴에 대해 모든 사용자에게 접근 권한을 부여한 것 같습니다.
기본 그룹의 경우에는 계정 관리 기능에 접근할 수 없어야 합니다.
현재 위 2가지는 수정한 상태입니다.

1, 2번의 경우 메뉴 접근 권한은 계정 권한 + 그룹 권한의 합연산(union)으로 이루어지므로
그룹을 Diamond-E 로 변경하면  "DB 조회 > DB 브라우저" 메뉴에만 권한이 있는 것은 정상입니다.

**권한이 있는 메뉴가 아예 없는 것이 아니거나, 관련 서비스에 장애가 있는 것이 아닌데
"URL을 받아올수 없습니다." 라는 에러가 화면에 나오는 것은 비정상입니다.**

이 부분은 수정하도록 하겠습니다.
