### ISSUE TITLE
hdfs 에 저장한 파일의 권한이 달라짐

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1727]
## 버그설명
hdfs에 저장한 파일이 권한이 달라져 읽기가 안됨
갑자기 그럽니다

![D2BEAB82-0ED9-444F-940A-FD138BD8F6C7](https://user-images.githubusercontent.com/18297120/70193343-39030100-1742-11ea-93e8-56e083e06388.jpeg)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
MOUNT 기능은 linux 파일시스템을 기반으로 하며, 기본 파일모드(권한)은 750(`rwxr-x---`) 입니다.
따라서 스크린샷 기준으로 DB218098 유저는 해당 파일에 읽기/쓰기/실행이 모두 가능할 것이며
다른 유저는 같은 그룹이 아닌 이상 읽기가 불가능한게 정상입니다.

@yariyarishow 
해당 파일에 읽기를 시도한 사용자 계정을 다시 확인 부탁드립니다.

**Comment by yariyarishow** [comment]
표시된 파일위에 있는 파일과 그아래 있는 파일을 보시면 권한이 다릅니다. 
소유자도 동일하고, 해당 사용자가 작업한 파일이고,
시스템에서 권한을 직접 변경할 수 없는데, 저 파일만 권한이 다르게 설정되는 상황을
설명할수 없습니다.

**Comment by yariyarishow** [comment]
![ADEE1A76-644A-4295-8DFF-4C6F332DFBD2](https://user-images.githubusercontent.com/18297120/70203585-b50c4180-1760-11ea-81b4-f7054b5fe050.jpeg)
화면캡쳐 보시면 오전에 문제가된 파일의 권한이 바껴있습니다. 그리고 그아래 파일을 다시 올렸더니 파일권한이 또 다릅니다

**Comment by veldise** [comment]
RStudio 실행시(메뉴 진입시) 해당 현상이 발생하는 것을 확인하였습니다.

@anhm 
안형민 선임님, 해당 이슈에 대하여 논의가 필요합니다.

**Comment by anhm** [comment]
확인해본 결과 파일의 권한이 다른 이유는 생성 방식에 따라 다르게 됩니다.
hdfs-브라우져를 이용할 경우 기본 권한은 750를 따라 갑니다.
R등 프로그램을 통해 파일을 생성할 경우 644를 따라 갑니다.

HDFS에서는 기본적으로 생성되는 파일은 644 권한을 따라 가게 됩니다.
hdfs-브라우져를 이용할경우 750인 이유는 내부적 로직으로 파일을 업로드 한다음 바로 권한을 수정하기 때문입니다.

예상으로는 사용자가 처음 파일을 만들 경우 644가 되고, 필요에 따라 변경을 했을것으로 예상 됩니다. 

R에서 다음과 같이 실행을 할 경우
```
hdfs.put("./weekday.dat", "/B-IRIS/USERS/anhm/WEEKDAYSS.csv")
hdfs.put("./weekday.dat", "/B-IRIS/USERS/anhm/WEEKDAYSS2.csv")
hdfs.chmod("/B-IRIS/USERS/anhm/WEEKDAYSS2.csv", 775)
```

WEEKDAYSS.csv 파일은 644 권한
WEEKDAYSS2.csv 파일은 775 권한
을 가지게 됩니다.

**Comment by yariyarishow** [comment]
땡. 예상이 틀렸음. 파일권한은 아무도 변경하지 않았음. 
다시 예상 하시요. ^^

**Comment by anhm** [comment]
@yariyarishow 
그럴리가..........

**Comment by yariyarishow** [comment]
땡!땡!땡!
저 사용자는 서버에서 작업을 할줄 모름. 
그냥 주구장창 IRIS 웹만 사용함.

**Comment by anhm** [comment]
@yariyarishow 
HDFS 인줄 알았는데...  mount 디렉토리였네요;;;;

**Comment by sunghoon** [comment]
과거 특정 시점의 시스템 운영 관련 사항이라 조치된 것으로 보고 닫습니다.
