### ISSUE TITLE
195번 서버 'URL을 받아올 수 없습니다', '메뉴를 가져올 수 없습니다' 에러 발생

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1730]
## 버그 설명 ##
QA 테스트 서버(192.168.102.195) 접속시 다음과 같은 화면 출력, "URL을 가져올 수 없습니다."

![스크린샷 2019-12-09 오후 2 29 46](https://user-images.githubusercontent.com/23020977/70409864-95db2000-1a90-11ea-89e5-985b1d568d9f.png)

또한, 좌측 상단 메뉴 클릭시 다음과 같은 화면 출력, "메뉴를 가져올 수 없습니다." 

![스크린샷 2019-12-09 오후 2 29 53](https://user-images.githubusercontent.com/23020977/70409873-a1c6e200-1a90-11ea-8cf0-f1709ffac75c.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 192.168.102.195 서버 접속 후 로그인
2. 좌측 상단 메뉴 클릭

**Comment by veldise** [comment]
요청:
```
GET /meta/api/menu/?locale=ko
```
응답:
```json
{"code":3,"message":"nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2"}
```

DB 상에 첫 화면(`FIRST_PAGE`으로 설정된 레코드가 1건이어야 하는데, 2건입니다.
이로 인해 서버 에러가 발생한 것으로 확인되었습니다.

메뉴 편집 화면에서 특정 메뉴를 첫 화면으로 설정하거나, DB 상에서 데이터를 수정하면 됩니다.

**Comment by veldise** [comment]
@leehaejoon 
#1731 와 같은 버그가 확인되었습니다.

**Comment by EricLeeMbg** [comment]
195번의 '메뉴' 테스트 과정 중 말씀하신 내용이 포함된 것 같습니다. 즉 A>B의 형태로 되어 있는 메뉴 삭제를 B부터 수행하고 A를 수행해야 한다는 의미로 보입니다. 
해당 테스트를 점검하여 수정 후 다시 확인하겠습니다.

**Comment by leehaejoon** [comment]
도커 컨테이너 삭제시 MariaDB 메타정보가 남아있는 버그로인해 발생하는 에러로, 현재 해결되었습니다.
