### ISSUE TITLE
meta: 상위 메뉴 삭제시, 하위 메뉴가 사라지는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1731]
## 버그 설명 ##
- A > B 와 같은 형태로 메뉴가 구성되어 있을 때, 상위 메뉴/카테고리인 A를 삭제하면 이후에는 B 메뉴 데이터에 접근할 수 없는 문제가 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. A 메뉴 추가 (미선택)
2. B 메뉴 추가 (A 하위로 추가)
3. A 메뉴 삭제

## 내용
상위 메뉴(A)를 삭제하면 하위 메뉴(B)가 목록에서 사라지고, 조회가 불가능하게 됩니다.
이로인해 아래와 같은 문제가 발생합니다.
1. DB table에 정크 데이터가 누적되는 문제 
2. 하위 메뉴(B)가 첫 화면으로 설정되어있을 경우, (상위 메뉴(A)를) 삭제 후 다른 메뉴를 첫 화면으로 설정하면 아래와 같은 에러 발생

### 첫 화면 설정 관련 에러
요청:
```
GET /meta/api/menu/?locale=ko
```
응답:
```json
{"code":3,"message":"nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2"}
```

### 해결 방안 2) 상위 메뉴 삭제시, 하위 메뉴 모두 제거 (+confirm 창 추가)

**Comment by EricLeeMbg** [comment]
혹시 195번 서버 'Menu'의 초기화를 수행해주실 수 있을까요? 또는 방법을 알려주시면 초기화를 수행하겠습니다.

**Comment by veldise** [comment]
@EricLeeMbg 
네, 금일 오전중에 진행하고 따로 방법을 알려드리겠습니다.

**Comment by veldise** [comment]
@EricLeeMbg 
195번 서버 메뉴 관련하여 DB상에서 초기화를 완료했습니다.

**Comment by EricLeeMbg** [comment]
@veldise 
확인하였습니다. 감사합니다.
