### ISSUE TITLE
[NMS+]보고서 내보내기를 동시에 하다가 에러가 난듯합니다.

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1736]
## 버그 설명 ##
보고서 내보내기를 우연히 동시에 하다가 보고서 조회하기가 실패하였습니다.
라고 하면서 보고서 목록을 조회하지 못하고 있습니다.

해당부분 어디를 확인해야하는지 빠른 확인이 필요합니다. T_T
우선 동작부터 할수있도록 확인부탁드립니다.

![보고서에러](https://user-images.githubusercontent.com/5468183/70533772-18510600-1b9d-11ea-9608-57a7ec3af33c.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
이슈 본문 내용으로 추측하기로는 ID가 동일한 보고서가 DB 상에 존재하는 것 같습니다.
해결을 위해서는 DB 상에서 처리가 필요합니다.

@jjinylee 
NMS+ 에 별도 설치된 IRIS에서 발생한 것인가요?

**Comment by jjinylee** [comment]
제가 SKBB 서초IDC 에 상주하고 있는데, 이쪽 DB 에서 발생하여 운용기술지원팀 통해 계정확인후 maria-db 에서 직접 삭제하였습니다.
