### ISSUE TITLE
데이터 추가 -> csv 파일선택 후 다음 버튼 눌리지 않음.

### ISSUE THREAD

**Issue by sundoforce** [mobigen/IRIS-BigData-Platform#1737]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

<img width="1892" alt="스크린샷 2019-12-11 오후 2 33 31" src="https://user-images.githubusercontent.com/16316626/70594419-d5864100-1c23-11ea-92a2-6281b9bf4683.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :
데이터 추가 -> 데이터 추가
[파일 선택]
cvs 파일 
다음 버튼 누름 

TypeError: event is undefined index.bundle.js:2:54057
    onloadend http://b-iris.mobigen.com/data-import/dist/index.bundle.js:2

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

파일 선택 후 다음 버튼을 누르면
파일 가공 단계로 이동 예상.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
<img width="1892" alt="스크린샷 2019-12-11 오후 2 33 31" src="https://user-images.githubusercontent.com/16316626/70594262-4a0cb000-1c23-11ea-9271-5cf9029593b9.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

TypeError: event is undefined index.bundle.js:2:54057
    onloadend http://b-iris.mobigen.com/data-import/dist/index.bundle.js:2

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@sundoforce 
사용하고 계신 웹 브라우저 이름과 버전을 알려주시면 감사하겠습니다.

**Comment by sundoforce** [comment]
<img width="621" alt="스크린샷 2019-12-11 오후 2 55 58" src="https://user-images.githubusercontent.com/16316626/70595291-5e9e7780-1c26-11ea-8b0a-cbd595352468.png">

firefox 브라우저 71.0 (64-비트) 입니다.
감사합니다

**Comment by veldise** [comment]
@sundoforce
빠른 답변 감사합니다.
버그 확인하였고 근시일내에 수정하도록 하겠습니다.

**Comment by sundoforce** [comment]
@veldise 선임님 감사합니다

**Comment by veldise** [comment]
금일(12/12) 오전 임시 패치로 동일 버전(firefox 브라우저 71.0 (64-비트))에서 정상 동작하는 것을 확인했습니다.
