### ISSUE TITLE
[K8S] IRIS Web에서 데이터모델 검색 이후 '새 창으로 열기' 동작하지 않음

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1738]
## 버그 설명 ##
쿠버네티스 클러스터에서 데이터모델 검색 이후 '새 창으로 열기' 버튼이 작동하지 않음

![스크린샷 2019-12-11 오후 2 40 15](https://user-images.githubusercontent.com/23020977/70594570-59402d80-1c24-11ea-8810-bf8533d475d4.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 쿠버네티스 클러스터를 통해 IRIS Web 실행
  - method: POST
  - path: 192.168.102.180:8075/api/services
  - body:
```
{
	"Cluster" : "-", 
	"Namespace" : "api-test",
	"ServiceFlavorID" : "1"
}
```
2. 생성된 클러스터의 IRIS Web에 접속후, 로그인
3. GNB `데이터 브라우저 > 관리 > 데이터 모델` 접속
4. 임의의 데이터모델 선택 후 우측 상단 '실행' 클릭
5. 결과 출력 후 우측 상단 '새 창으로 열기' 클릭

## 예상한 행동 ##
현재 화면과 동일한 형태의 새 창이 열리는 것을 기대.

**Comment by veldise** [comment]
brick, sherman 2개 서비스 버전 정보가 필요합니다.

**Comment by donghwasuh** [comment]
brick: v0.1.9_22ff4c9
sherman: v1.7.2_decfe96
현재 쿠버네티스에서 사용중인 이미지 버전입니다.

**Comment by veldise** [comment]
brick: v0.1.9_1ea48a9
sherman: v2.5_5f28c8f

위 버전을 보내드리겠습니다. 다만 테스트가 부족한 점 양해바랍니다.

**Comment by veldise** [comment]
처리 완료된 것으로 보고 닫습니다.
