### ISSUE TITLE
[K8S] 새모델 생성시 연결정보에서 무한대기현상

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1741]
## 버그 설명 ##
쿠버네티스로 생성한 클러스터에서 새모델 생성 -> 연결정보 IRIS -> iris 선택시 무한대기현상 발생

![스크린샷 2019-12-13 오전 10 09 47](https://user-images.githubusercontent.com/23020977/70761666-51ea6280-1d91-11ea-8d13-71070ca6727d.png)

(위 화면에서 넘어가지 않음)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 쿠버네티스 클러스터를 통해 IRIS Web 실행
  - method: POST
  - path: 192.168.102.180:8075/api/services
  - body:
```
{
    "Cluster" : "150-cluster",
    "Namespace" : "test",
    "ServiceFlavorName" : "191212-150-cluster"
}
```
2. 생성된 클러스터의 IRIS Web에 접속후, 로그인
3. GNB `데이터 브라우저 > 관리 > 데이터 모델` 접속
4. 우측 상단 '새 모델' 클릭
5. 연결 정보 IRIS -> iris 선택
6. 무한대기현상 발생

**Comment by leehaejoon** [comment]
현재는 정상 동작합니다.
클러스터 생성 이후 일정 시간(약 10분 이상)이 지난 이후 동작하는 것처럼 보이는데,
추가적인 정보가 있으면 공유하도록 하겠습니다.

**Comment by donghwasuh** [comment]
보통은 해당 현상 발생시,  `192.168.100.180:8082 (spark ui)`에서 확인해보면 
k8s에서 생성한 앙고라가 코어를 할당받지 못하고 무한 대기하는 경우가 존재합니다. 

앞으로 기존 180 앙고라 외에 k8s 개발/QA 에서도 앙고라가 사용될 예정이기때문에 
앙고라팀과 논의하여 자원을 재분배하여 무한 대기 현상이 발생하지 않도록 조치해야할 것 같습니다. 

@namjals @leehaejoon

**Comment by leehaejoon** [comment]
담당자와 협의하여 해결하였습니다.

**Comment by EricLeeMbg** [comment]
동일 현상이지만 새이슈로 등록합니다.
