### ISSUE TITLE
MDT / EVENT_LNG, EVENT_LAT, EVENT_GEOM_TEXT에 값이 할당되지 않는다

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1744]
## 버그 설명 ##
MDTX_USECASE4레포트에서 지도표시후에 지도상에서 클릭해도 EVENT변수들이 반영되지 않는다

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'B-IRIS'
2. Click on 'Report / MDTX_USECASE4'
3. [RSRP500m]버튼을 눌러서 지도를 갱신한 후에 임의의 그리드를 클릭한 후 show variables를 보아도 변수가 공백으로 남아있다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
버그가 확인되었습니다. 수정하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/70871602-12678480-1fe4-11ea-8a5c-c305bf41af86.png)
