### ISSUE TITLE
hdfs-browser: SSL 적용시 unable to verify the first certificate 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1746]
## 기능 요청 ##
SSL 적용시 hdfs-browser 서비스에서 unable to verify the first certificate 에러 발생

**Comment by big-mobigen** [comment]
ssl 적용된 오픈랩 운용계 서버에서 hdfs-browser 최신버전(v2.5_1463510) 설치 후 데이터모델에서 objectstorage 연결정보 선택 후 찾아보기 클릭시 데이터가 없습니다 라는 화면이 나타납니다. 
![image](https://user-images.githubusercontent.com/25650544/71519253-1bb4f300-28fa-11ea-8b36-31945591e328.png)

실제 버킷에는 데이터가 있는 상태입니다. 
관련하여 hdfs-browser 로그 와 config 설정을 공유드립니다. 

**hdfs-browser docker config**
[root@Koti-OpenLab-A01 bin]# cat /DATA/b-iris/service/conf/hdfs-browser/config.json
{
    "security": {
        "secret": "jwt-secrect-b-iris",
        "access": {
            "mode": "brick"
        }
    },
    "server": {
        "port": 18087
    },
    "ssl": {
        "key": "conf/ssl/diamonde_key.pem",
        "cert": "conf/ssl/diamonde_crt.pem",
        "passphrase": "a12345"
    },
    "dev": {
        "appId": "hdfs-browser",
        "brickAddress": "http://localhost:8080/",
        "hdfsBrowserAddress": "http://localhost:18087/",
        "hdfsAddress": "http://172.27.0.244:50070/",
        "hdfsSuperUserId": "iris",
        "userId": "iris",
        "groupId": null,
        "hdfsUserPath": "/",

        "mount": {
            "base_path": {
                "user": "/configure/user/workspace/tmp/user",
                "tool": "/configure/user/workspace/tmp/save"
            },
            "tool_path": {
                "jupyter": "/jupyter/notebook",
                "rstudio": "/rstudio/user",
                "zeppelin": "/zeppelin/notebook"
            }
        },
        "minio": {
            "ip": "172.27.0.66",
            "port": 9000,
            "accessKey": "3bf26409e4854608f0224269ce3b1e7a",
            "secretKey": "737b4c333fe1863fdc2fe2ee6ec8147b",
            "region": "ap-northeast-2"
        }
    }
}

**hdfs-browser docker log**
22:43:37 0|hdfs-browser  | 2019-12-27 22:43:37.629 +0900 - info: request to brick: https://172.17.0.3:10443/api/status
22:43:37 0|hdfs-browser  | 2019-12-27 22:43:37.801 +0900 - info: GET: dsms option =  url=http://172.27.0.66:9001/dsms/v1/connector/6?value=True, method=GET
22:43:37 0|hdfs-browser  | 2019-12-27 22:43:37.817 +0900 - error: /minio list error =  message=unable to verify the first certificate, stack=Error: unable to verify the first certificate
22:43:37 0|hdfs-browser  |     at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
22:43:37 0|hdfs-browser  |     at TLSSocket.emit (events.js:198:13)
22:43:37 0|hdfs-browser  |     at TLSSocket._finishInit (_tls_wrap.js:636:8), code=UNABLE_TO_VERIFY_LEAF_SIGNATURE

오픈랩 운용계 접속정보는 오장석팀장님께서 알고계시며 
바쁘시겠지만 확인을 부탁 드립니다.

**Comment by veldise** [comment]
@big-mobigen 
해당 에러는 인증받지 않은 사설인증서를 사용시 발생하는 에러입니다.
상용 환경에서도 사설인증서를 사용할 예정인지 답변 부탁드립니다.
