### ISSUE TITLE
[K8S] DB 브라우저에서 쿼리 생성 및 수행시 무한 대기현상

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1747]
## 버그 설명 ##
쿠버네티스 클러스터(192.168.102.150:32012)의 DB브라우저에서 쿼리 생성시 무한 대기현상 발생

![스크린샷 2019-12-16 오후 2 45 05](https://user-images.githubusercontent.com/23020977/70882444-2676aa80-2013-11ea-9380-7d1b720b8b28.png)

위와 같이 쿼리 생성시

![스크린샷 2019-12-16 오후 2 45 18](https://user-images.githubusercontent.com/23020977/70882430-1959bb80-2013-11ea-95f3-e12feb42b153.png)

위와 같이 무한 대기 현상 발생

또한, 쿼리 입력창에 직접 입력 후 실행 시에도 다음과 같이 동일 현상 발생.

![스크린샷 2019-12-16 오후 3 25 41](https://user-images.githubusercontent.com/23020977/70884171-8de32900-2018-11ea-9388-824877983cb5.png)

동작을 재현하는 방법 :
1. 쿠버네티스 클러스터를 통해 IRIS Web 실행
  - method: POST
  - path: 192.168.102.180:8075/api/services
  - body:
```json
{

           "Cluster" : "150-cluster",

           "Namespace" : "test",

           "ServiceFlavorName" : "191212-150-cluster"

}
```
2. 생성된 클러스터의 IRIS Web에 접속후, 로그인
3. GNB `DB 조회 > DB 브라우저` 접속
4. 임의의 테이블 우클릭 후, 임의의 쿼리 생성
5. 무한대기현상 발생

**Comment by sunghoon** [comment]
IRIS Clusterr 이슈로 확인되어 클러스터를 조치 하였습니다.
