### ISSUE TITLE
[K8S] DB 브라우저 접속시 'DB 접속에 문제가 발생했습니다.....' 에러 발생

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1749]
## 버그 설명 ##
쿠버네티스 클러스터(192.168.102.150:32011)의 DB브라우저 접속시 다음과 같이 `'DB 접속에 문제가 발생했습니다...'` 에러 발생

![스크린샷 2019-12-17 오전 11 24 02](https://user-images.githubusercontent.com/23020977/70959494-d30e6600-20bf-11ea-91b9-a2437a3643b7.png)

동작을 재현하는 방법 :
1. 쿠버네티스 클러스터를 통해 IRIS Web 실행
  - method: POST
  - path: 192.168.102.180:8075/api/services
  - body:
```json
{

           "Cluster" : "150-cluster",

           "Namespace" : "test",

           "ServiceFlavorName" : "191212-150-cluster"

}
```
2. 생성된 클러스터의 IRIS Web에 접속후, 로그인
3. GNB `DB 조회 > DB 브라우저` 접속
4. 에러 팝업 출력

**Comment by sunghoon** [comment]
IRIS Cluster 이슈로 확인되어 클러스터를 조치 해 두었습니다.
