### ISSUE TITLE
studio: IE 에서 객체 선택이 안되는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1750]
## 버그 설명 ##
IE 11 에서 객체 선택이 안되는 문제가 발생했습니다.

**Comment by swish1995** [comment]
- 확인된 내용은 다음과 같습니다.
- 객체를 선택하는 부분에서 DOM 상의 상위객체를 찾는 과정에서 오류가 발생합니다.
   - IE 에서 SVG Element(highchart 에서 사용되는 `rect`와 같은) 의 parentElement 가 null 을 반환함
   - 해당 코드로 인해 상위 DOM 객체를 찾지 못함
   - 마우스에 의해 반응하는 interact 에서는 jquery 의 parent() 를 사용하여 오류가 없음
      - 마우스 오버된 객체가 반응함
- `canvas.js` 와 `report-preview/main.js` 의 selectVisual 함수 수정
   - parentElement 가 아닌 jquery 의 parent 함수를 사용하도록 수정해야 할것으로 판단됨 
- 해당 내용대로 수정하고 IE, Safari, Chrome 테스트 예정
