### ISSUE TITLE
교통빅데이터 / DB브라우저 /  update 쿼리 실행 오류

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1755]
## 버그 설명 ##

문자에 대한 update 쿼리 실행시 동작 하지 않음
(숫자에 대한 update는 오류메세지는 발생 하시만 update 쿼리는 실행됨)

[update 실행안됨 / 문자 update  sql] 
update TB_HT_COLLECT_HISTORY set ps_section = '진주시' where src_file_name like 'ko_%';

[update실행됨 / 숫자 update sql]
update TB_HT_COLLECT_HISTORY set src_file_row_cnt = 101010 where ps_section like 'KST%' and src_file_row_cnt = 9440094;

[결과 메세지]
Line 38 ~ 38 : Unknown error. ( sequence item 1: expected string, NoneType found )

**Comment by ollehQ** [comment]
사내에서 테스트 진행하였지만 재현이 불가능해서 확인이 힘든 상황 입니다.
혹시 지금도 같은 현상이 발생하는지 알려 주시면 감사하겠습니다.

**Comment by sunghoon** [comment]
과거 특정 시점의 시스템 운영 관련 사항이라 조치된 것으로 보고 닫습니다.
