### ISSUE TITLE
교통빅데이터 / DB브라우저 / sql 조회결과 다운로드 안됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1756]
## 버그 설명 ##
sql조회 결과에 대해 다운로드시 내용이 없는 파일로 저장됨

[조회 sql]
```sql
SELECT 
	INSERT_TIME, PS_NAME, PS_GROUP_NAME, PS_GROUP_PARENT_NAME, PS_IP, PS_SECTION, PS_START_TIME, PS_END_TIME, PS_TIME, PS_SUCCESS_FLAG, FAIL_REASON, SRC_FILE_NAME, SRC_FILE_SIZE, SRC_FILE_ROW_CNT, IN_FILE_NAME, IN_FILE_SIZE, IN_FILE_ROW_CNT, OUT_FILE_NAME, OUT_FILE_SIZE, OUT_FILE_ROW_CNT, IRIS_TABLE_NAME, IRIS_KEY, IRIS_PARTITION, DESCRIPTION 
FROM 
	DIAMONDE.TB_HT_COLLECT_HISTORY
; 
```

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/70978873-eb987380-20f3-11ea-9f3a-2107ddb18b42.png)

**Comment by veldise** [comment]
#1680 동일 이슈로 생각됩니다.

@JeongHeeDong 
혹시 다운로드한 파일이 비어있는게 아니라면 파일 내용도 첨부해주시면 감사하겠습니다.

**Comment by JeongHeeDong** [comment]
특수문자 하나 들어간 경우가 있었는데..파일을 지워버려서 없네요.
몇번 다운로드 받았지만 마지막 테스트는 빈 파일이었습니다.

**Comment by ollehQ** [comment]
테스트를 진행해 본 결과 IRIS DB의 Error와 관련이 있는 것이 확인되었습니다.
IRIS DB에 Error가 발생하게 된다면, 다운로드를 하게 된다면 빈 파일이 나오게 됩니다.
Backend location file의 블록 파일의 위치정보의 소실 또는 Process Memory Limit로 인한 것으로 예상하고 있습니다.
만일 파일 위치 정보의 소실일 경우에는, Recover의 명령어를 통해 복구작업을 실행해야 합니다.
Process Memory Limit일 경우에는, 파티션의 범위를 줄이거나, dlimit query 구문을 사용하는 방법이 있을 것 같습니다.
혹시라도 같은 이슈가 발생할 경우에는, 이슈를 한 번만 다시 등록 부탁 드립니다.
해당 이슈는 닫도록 하겠습니다.
