### ISSUE TITLE
studio: PostgreSQL 일부 컬럼 유형 미지원

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1758]
## 버그 설명 ##
DSMS에 PostgreSQL 연결정보를 통해 쿼리를 실행하면 결과 컬럼 유형(type)이 `int8`로 반환됩니다.
UI에서는 mysql, mariadb, oracle 에서 지원하는 컬럼 유형에 대해서는 IRIS 컬럼 유형으로 매핑변환 처리가 되어 있는데 postgresql 등에 대해서는 처리가 되어있지 않습니다.

이에 sql 유형의 연결정보에서 사용하는 모든 컬럼 유형과, 각 컬럼 유형을 아래 컬럼 유형에 각각 어떻게 매핑하면 정리한 문서를 요청합니다.

#### 처리가 필요한 연결정보 유형:
POSTGRESQL
TIBERO
~~ELASTICSEARCH~~
VECTORWISE

#### IRIS 컬럼 유형 목록:
TEXT
NUMBER
INTEGER
BIGINT
REAL
TIMESTAMP
DATE

#### 매핑변환 예시(ex):
varchar: TEXT
int8: BIGINT

## 기타
앞으로 `category: "SQL"` 유형의 데이터소스를 추가할 때에는 위 작업이 동반되어야 합니다.

**Comment by seungfwani** [comment]
데이터 타입 매핑 테이블 문서를 추가하였습니다.

https://github.com/mobigen/data_source_manager/wiki/Data-Type-Mapping-Tables

**Comment by veldise** [comment]
@seungfwani 
권한이 없어 해당 페이지 접근이 안됩니다.
md 파일을 코멘트에 첨부하거나, 메일로 보내주시기 바랍니다.

**Comment by seungfwani** [comment]
elasticsearch 는 sql 문을 지원하지 않습니다.
DSMS에서 category 를 수정하도록 하겠습니다.
