### ISSUE TITLE
angora: stats count(*) 결과가 count(1)로 반환되는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1761]
## 버그 설명 ##
`stats count(*) by HOST` 명령어를 수행하면, 결과 컬럼명이 `count(*)`이 아니라 `count(1)`로 반환됩니다.
정상인지 / 정상이라면 관련 변경 이력 문서가 필요합니다.

## 내용
```
model name = 'syslog' model_owner = eva start_date = 20191219100600 end_date = 20191219100745 | stats count(*) by HOST
```
```js
{
  "fields": [
    {
      "name": "HOST",
      "type": "TEXT",
      "grouped": true
    },
    {
      "name": "count(1)",
      "type": "LONG",
      "grouped": false
    }
  ],
```

**Comment by seungfwani** [comment]
`count(*)` -> `count(1)` 로 변환이 되는 것은 앙고라에서는 버그입니다.
원인은 #1599 , #1642  이슈에서 stats 명령어가 수정이 되었는데 이 때 수정한 부분이 문제가 된 것으로 보입니다.

해당 내용은 원복하여 커밋하였고, 목요일 배포시 배포될 예정입니다.

**Comment by seungfwani** [comment]
수정되었습니다.
![image](https://user-images.githubusercontent.com/46172579/71795536-01adaa00-308a-11ea-9f0f-0eccdb7503ec.png)
![image](https://user-images.githubusercontent.com/46172579/71795548-0a9e7b80-308a-11ea-8d98-eda4a931d231.png)
