### ISSUE TITLE
[데이터브라우저-검색]에서  샘플링-사용안함  결과와 샘플링적용 결과가 이상합니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1763]
## 요약 
syslog 데이터모델에서 샘플링 사용안함 일 때 데이터가 없다고 나온 기간을
샘플링테이블에서 조회하면 데이터가 나옴

###  샘플링 사용안함 결과
  -  syslog 데이터모델  샘플링 사용안함  최근 4주 결과
<img width="990" alt="스크린샷 2019-12-19 오전 9 40 43" src="https://user-images.githubusercontent.com/5126497/71150549-1a8a2300-2275-11ea-90cc-af89720276b1.png">
   
  - 12월 7일 ~ 11 일 부근 데이터 비어 있음. 12월7일 ~ 11일 조회

<img width="861" alt="스크린샷 2019-12-19 오후 3 36 32" src="https://user-images.githubusercontent.com/5126497/71150646-5a510a80-2275-11ea-894b-4d89352bbba3.png">

###  샘플링테이블 12월7일 ~ 11일 조회
<img width="988" alt="스크린샷 2019-12-19 오전 9 48 22" src="https://user-images.githubusercontent.com/5126497/71150851-d77c7f80-2275-11ea-9b1a-8bfe69908eac.png">

**Comment by sunghoon** [comment]
과거 운영 관련 내용이라 이슈를 닫도록 하겠습니다.
