### ISSUE TITLE
ValueLinkU / Studio / 그리드 데이터 다운로드 기능 오류

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1764]
## 버그 설명 ##
Libor금리 화면에서 그리드 데이터 다운로드 실행히 동작 하지 않음
브라우저 하단에 "응답을 기다리는중...." 에서 넘어가지 않음

다른 보고서 화면에서는 정상적으로 다운로드됨

## 재현하는 방법 ##
1. 메뉴 > 경제 > 금융 > Libor금리 실행
2. 그리드의 다운로드 버튼 실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/71151839-16133980-2278-11ea-96ec-bbdafaae3380.png)

**Comment by veldise** [comment]
다운로드 버튼 눌렀을 때 요청:
```js
{"q":"model name = '통합지표_Data_Global' DATA_TYPE='LIBOR' | pivot avg(DATA_VALUE) SPLITROW LOC_NAME SPLITCOL DATA_DATE SORTCOL ASC | rename LOC_NAME Index","size":-1}
```

@namjals @seungfwani 
아래와 같이 job 요청시 응답이 오지 않습니다.
```
{"q":"model name = '통합지표_Data_Global' model_owner = valuelinku DATA_TYPE='LIBOR' | pivot avg(DATA_VALUE) SPLITROW LOC_NAME SPLITCOL DATA_DATE SORTCOL ASC | rename LOC_NAME Index","save":false,"size":500}
```

**Comment by veldise** [comment]
#1713 버그 수정 내역이 ValueLinkU에는 패치가 되지 않은 것 같습니다.

**Comment by veldise** [comment]
ValueLinkU 에 수정 내역 패치되어 닫습니다.
