### ISSUE TITLE
ValueLinkU / Studio / 그리드 데이터 다운로드시 화면의 내용과 다른 결과가 저장됨

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1765]
## 버그 설명 ##
최근 2주 데이터를 조회 한 결과에 대해 그리드 데이터를 다운로드 하면 8월부터의 데이터가 저장됨
화면에 출력된 데이터와 다운로드 받은 데이터가 다름

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 메뉴 > 경제 > 원유.원자재 > 원자재 시황 실행
2. 파일 다운로드 실행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/71152118-e0bb1b80-2278-11ea-9652-f63c5d244303.png)

**Comment by veldise** [comment]
#1713 버그 수정 내역이 ValueLinkU에는 패치가 되지 않은 것 같습니다.

**Comment by veldise** [comment]
ValueLinkU 에 수정 내역 패치되어 닫습니다.
