### ISSUE TITLE
ValueLinkU / Studio / DateTime picker를 모델에 적용 할 수 있는 기능 

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1766]
## 기능 요청 ##
- "데이터 모델 일괄설정" DataTime 설정 과 같이 Data/Time Picker 컴포넌트를 데이터 모델에 적용 가능하도록 개선 
- Data/Time Picker의 output 형태가 현재는 "2019/12/19" 형태로 고정인 부분을 "20191219" 형태로 변경 할 수 있게  설정 기능 개선(시간도 동일 "10:00" --> "1000" )

![image](https://user-images.githubusercontent.com/4444717/71153323-2c22f900-227c-11ea-8d12-10b7fbb27e6d.png)

**Comment by veldise** [comment]
#1742 와 동일 이슈로 생각됩니다.

**Comment by JeongHeeDong** [comment]
포맷부분은 동일한 내용이 맞습니다.
모델에 적용하는 부분은 다른 내용입니다.
