### ISSUE TITLE
HTTPS 모드일 때, 대화형 분석 메뉴는 새 창으로 띄우도록 처리

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1767]
## 기능 요청 ##
SSL을 적용하여 HTTPS 모드일 때, 대화형 분석 메뉴는 새 창으로 띄우도록 처리

**Comment by big-mobigen** [comment]
ssl 적용된 오픈랩 운용계 서버에 최신 배포파일 v2.6.1_0e874f4 설치하여 설정해보았으나 새창으로 대화형분석툴이 뜨지 않습니다. ( 하얀화면으로 먹통 )

**ext-manager config**
[root@Koti-OpenLab-A01 ext-manager]# cat config.json
{
    "debug": false,
    "security": {
        "secret": "jwt-secrect-b-iris",
        "access": {
            "mode": "brick"
        }
    },
    "protocol": "http",

    "base_path": "/DATA/b-iris/service",
    "user_private_path": "/user",
    "spark_on_iris_path": "/DATA/b-iris/service/lib/Spark-on-IRIS",

    "company": "mobigen.com",
    "host_uid": "0",
    "host_gid": "0",

    "self.ip": "172.27.0.66",

    "container": {
        "name": {
            "prefix": "",
            "sep": "..."
        },
        "port_range_start": 32500,
        "port_range_end": 32600
    },

    "check_alive": {
        "interval": 500,
        "timeout": 15000
    },

**ext-manager docker log** 
22:05:11 0|app  | [2019-12-27 22:05:11] container started: 5c53b779f9c79b60be07059b22fccc5a1865fa3066984c38f08674dcb0e8d5fb
22:05:11 0|app  | [2019-12-27 22:05:11] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:11 0|app  | [2019-12-27 22:05:11] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:12 0|app  | [2019-12-27 22:05:12] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:12 0|app  | [2019-12-27 22:05:12] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:13 0|app  | [2019-12-27 22:05:13] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:13 0|app  | [2019-12-27 22:05:13] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:14 0|app  | [2019-12-27 22:05:14] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:14 0|app  | [2019-12-27 22:05:14] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:15 0|app  | [2019-12-27 22:05:15] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:15 0|app  | [2019-12-27 22:05:15] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:16 0|app  | [2019-12-27 22:05:16] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:16 0|app  | [2019-12-27 22:05:16] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:17 0|app  | [2019-12-27 22:05:17] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:17 0|app  | [2019-12-27 22:05:17] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:18 0|app  | [2019-12-27 22:05:18] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:18 0|app  | [2019-12-27 22:05:18] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:19 0|app  | [2019-12-27 22:05:19] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:19 0|app  | [2019-12-27 22:05:19] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:20 0|app  | [2019-12-27 22:05:20] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:20 0|app  | [2019-12-27 22:05:20] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:21 0|app  | [2019-12-27 22:05:21] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:21 0|app  | [2019-12-27 22:05:21] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:22 0|app  | [2019-12-27 22:05:22] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:22 0|app  | [2019-12-27 22:05:22] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:23 0|app  | [2019-12-27 22:05:23] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:23 0|app  | [2019-12-27 22:05:23] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:24 0|app  | [2019-12-27 22:05:24] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:24 0|app  | [2019-12-27 22:05:24] (checkAlive) retry(count): https://172.27.0.66:32503
22:05:25 0|app  | [2019-12-27 22:05:25] (checkAlive) fail: -1 { Error: connect ECONNREFUSED 172.27.0.66:32503
22:05:25 0|app  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
22:05:25 0|app  |   errno: 'ECONNREFUSED',
22:05:25 0|app  |   code: 'ECONNREFUSED',
22:05:25 0|app  |   syscall: 'connect',
22:05:25 0|app  |   address: '172.27.0.66',
22:05:25 0|app  |   port: 32503 }

서버 접속정보는 오장석 팀장님께서 알고 계시며
바쁘시겠지만 확인을 요청 드립니다.

**Comment by veldise** [comment]
대화형 분석 메뉴가 새 창으로 띄워지지 않는 문제는 버전 문제로 확인되었습니다.

현재 diamond-e brick 버전: `v2.5_4bf5eea`
대화형 분석 새창 처리한 버전: `v2.5_7abaa61`

**Comment by veldise** [comment]
19/12/31 10:20분경 `v2.5_7abaa61` 버전으로 패치했습니다.

**Comment by veldise** [comment]
새 창 팝업으로 처리하지 않고,
각 대화형 분석 메뉴가 https 지원하도록 플랫폼연구팀에서 처리하여 닫습니다.

**Comment by veldise** [comment]
플랫폼연구팀에서 다른 방법으로 해결하여, 이슈 닫습니다.
