### ISSUE TITLE
[NMS+]studio 버튼 색상 설정가능하도록 요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1771]
## 기능 요청 ##
보고서 작성중에, 버튼 콤포넌트에 색상을 변경하고 싶습니다.
특정 버튼을 강조하기위해 색상으로 구별하고 싶습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
3월 13일자 패치로 버튼의 채우기/테두리 색상을 변경할 수 있는 기능이 추가되었습니다.
이에 닫습니다.

https://github.com/mobigen/IRIS-BigData-Platform/wiki/2020-03-13---Patch

![image](https://user-images.githubusercontent.com/3411842/78333467-d40ec900-75c4-11ea-94ad-1abff45e34bf.png)
