### ISSUE TITLE
[NMS+]studio 그리드 다운로드 버튼 문의 등

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1777]
## 기능 요청 ##
1. 다운로드 버튼을 클릭하면 다음과 같은 메시지가 나오고 다운로드가 안됩니다.

어떤경우인가요 ?
혹시, 그리드의 datasource=restapi 로 하면 다운로드가 안되나요?

 << 아래 화면스샷의 파란색 표기 부분 >>

2. studio 로 보고서를 만들고 나서 화면을 띄우면 상단에 "보고서명" 이 나옵니다.
  보고서명을 안나오게 할수없나요 ?
보고서가 많을때 보고서명을 MENU_포트정보, POP_포트등록 등으로 명명규칙을 정해서 등록하고 있는데, 보고서 로딩시 무조건 보고서 명이 나오네요.
보고서명이 안보이게 하는 방법을 알려주세요.
<< 아래 화면스샷의 빨간색 표기 부분 >>

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

- 다운로드 버튼 화면 스샷
![iris2](https://user-images.githubusercontent.com/5468183/71454368-d39bb080-27d3-11ea-81ba-f0a79c20273e.PNG)

**Comment by veldise** [comment]
1. 다운로드 버튼을 클릭하면 다음과 같은 메시지가 나오고 다운로드가 안됩니다. 어떤경우인가요 ?
=> 다운로드 기능은 데이터 유형이 "데이터 모델"일 때만 가능합니다.

2. studio 로 보고서를 만들고 나서 화면을 띄우면 상단에 "보고서명" 이 나옵니다. 보고서명을 안나오게 할수없나요 ?
=> 현재 버전에서는 보고서명이 나오게 할 수 없습니다. 팀장님과 논의하여 별도 기능으로 개발을 검토해보겠습니다.

**Comment by jjinylee** [comment]
2. studio 로 보고서를 만들고 나서 화면을 띄우면 상단에 "보고서명" 이 나옵니다. 보고서명을 안나오게 할수없나요 ?
=> 현재 버전에서는 보고서명이 나오지 않게 할 수 없습니다. 팀장님과 논의하여 별도 기능으로 개발을 검토해보겠습니다.

---> 밸류링크유는 보고서명이 나오지않던데요.  그경우는 무엇일까요? 
예외케이스가 있는건지?

![캡처](https://user-images.githubusercontent.com/5468183/71564690-3baa0980-2ae8-11ea-8845-6dbd5c2736b6.PNG)

**Comment by veldise** [comment]
@jjinylee 
ValueLinkU 는 로고 및 일부 스타일을 포함하여 보고서 명이 나오지 않도록
ValueLinkU 전용 디자인을 적용하여서 그렇습니다. (사이트 커스터마이징)

**Comment by veldise** [comment]
2번 보고서명 표시/숨김 기능은 신규 기능으로 개발 예정입니다. 아래 이슈로 분리하여 진행합니다.
#1803

**Comment by veldise** [comment]
#1803 개발 완료됨에 따라 닫습니다.
