### ISSUE TITLE
[NMS+]studio 보고서 그리드의 속성추가 #2

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1778]
## 기능 요청 ##
- studio 그리드의 시각화 옵션에서 헤더or 열의 숨김기능 추가요청
그리드에서 조회는 해서 가져오지만 보여주고 싶지않은 열이 있습니다.
( id, code값등 CRUD 를 위해 key 값으로 조회를 해야하지만 그리드에서 보여주고 싶지않음)

아래는 #1718 issue 임
- 그리드의 컬럼에 이미지/색상을 넣을수 있는 기능
NMS 기능상 알람을 표현할때 Critical/Major/Minor 등을 가시적으로 보이게하는 기능이 기본이라 필요
- 그리드의 다수개의 행을 선택할수 있는 기능 (체크버튼)
- 그리드에 컬럼에 컴포넌트(버튼)을 넣을수 있는 기능 (2번이 포함될라나요)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
다른 항목들은 검토해봐야 하지만, "그리드 컬럼에 컴포넌트(버튼)을 넣는 기능"은 현재 Studio 구조상 불가합니다.
객체 및 객체 ID는 유일하며 다른 객체를 포함하는 형태가 될 수 없습니다.

**Comment by veldise** [comment]
그리드 다수행 선택, 그리드에 버튼 삽입 등의 기능은 현재 Studio 기능 구조상 or 일정상 어려워
일단 아래 2가지 항목만 진행하기로 하였습니다.

- Chart / 테이블 유형 - 특정 컬럼 show/hide 기능 추가
- Chart / 테이블 유형 - 조건부 서식 행/열 선택 가능하도록 기능 추가/변경

**Comment by veldise** [comment]
3월 4일자로, 위 2가지 항목 개발 및 패치 완료됐습니다.
