### ISSUE TITLE
MDT / ERROR01_MAP_GEOM_TEXT

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1780]
## 버그 설명 ##
3개이상의 지도에서 MAP_GEOM_TEXT가 다른 지도의 범위를 참조하는 현상이 발생한다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'Report'
2. Click on 'ERROR01_MAP_GEOM_TEXT'
3. 첨부 화일을 참조하세요

[ERROR01_MAP_GEOM_TEXT.xlsx](https://github.com/mobigen/IRIS-BigData-Platform/files/4004828/ERROR01_MAP_GEOM_TEXT.xlsx)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
오래된 이슈고, 동작에 특이사항이 없어 보여 닫습니다. 

다른 특이사항이 있다면 새 이슈로 다시 등록해 주시기 바랍니다.
