### ISSUE TITLE
MDT / B-IRIS angora error

### ISSUE THREAD

**Issue by minjaekang7** [mobigen/IRIS-BigData-Platform#1781]
## 버그 설명 ##
angora관련 에러가 발생하고 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to '검색'

![image](https://user-images.githubusercontent.com/54348795/71539139-717daf80-297b-11ea-96de-fff4360e03ea.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
현재 fields 명령어가 대소문자 구분이 되어 동작하고 있습니다.
![image](https://user-images.githubusercontent.com/46172579/71795334-0c1b7400-3089-11ea-9b7e-2d6c19a452f7.png)

이 부분을 대소문자 구분하지 않도록 수정하겠습니다.

**Comment by seungfwani** [comment]
현재 운영서버에 배포를 하여,
아래 두 사진과 같이 대소문자에 상관없이 fields 명령어가 동작합니다.

![image](https://user-images.githubusercontent.com/46172579/72578845-a5b11400-391a-11ea-8680-5ad7ceeb9256.png)

![image](https://user-images.githubusercontent.com/46172579/72578864-b82b4d80-391a-11ea-9415-7004c30e5902.png)
