### ISSUE TITLE
studio: 객체 copy&paste, 설정값 불러오기 기능 필요

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1785]
## 기능 요청 ##
- 유사한 내용(ex) 검색어)의 객체를 여러개 작성하고자 할 때 객체 copy&paste 기능이 없어 불편합니다.
- 이전에 작성한 어떠한 설정값을 불러와 적용하는 기능이 있으면 좋겠습니다.
    - ex) Map 객체의 시각화 옵션 - 범례 설정

**Comment by sunghoon** [comment]
유사 기능이 배포된 것으로 보고 닫습니다.
