### ISSUE TITLE
studio: Map / 레이어가 2개 이상일 때, 범례는 어떻게 출력됩니까?

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1786]
## 기능 요청 ##
- 제보자: @minjaekang7
- Map / 레이어가 2개 이상일 때, 범례는 어떻게 출력됩니까?

**Comment by swish1995** [comment]
범례는 겹치지 않고 스크린샷과 같이 왼쪽 하단에 쌓이면서 출력됩니다.
<img width="321" alt="스크린샷 2019-12-31 오후 12 19 55" src="https://user-images.githubusercontent.com/49141403/71608935-e34a3900-2bc7-11ea-8ca9-a3909a1b61b1.png">

**Comment by veldise** [comment]
@minjaekang7

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
