### ISSUE TITLE
studio: Map / 전역 변수들을 객체 각각의 개별 변수로 변경

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1787]
## 기능 요청 ##
Map 객체는 Map 객체간에 동작 연동을 위해, 다양한 변수를 제공합니다.
이 변수는 사용자가 정의한 변수가 아닌 객체가 고유한 이름으로 제공하는 변수입니다.
이 변수는 특정 이벤트 발생시에만 값이 채워집니다.

그런데 이 변수는 일종의 전역변수처럼 하나만 존재하고, 어떤 객체에서 이벤트가 발생하더라도
상관없이 변수의 값이 변경됩니다.
이 변수들을 각 객체의 개별 변수로 변경해야 합니다.

## Map 고유 변수 목록 (19/12/31 기준)
```
EVENT_LAT
EVENT_LNG
EVENT_GEOM_TEXT
EVENT_NORTH_LAT
EVENT_WEST_LNG
EVENT_SOUTH_LAT
EVENT_EAST_LNG
MAP_ZOOM_LEVEL
MAP_GEOM_TEXT
```

**Comment by minjaekang7** [comment]
이 건은 언제쯤 개선이 될 수 있는지요?

**Comment by veldise** [comment]
@minjaekang7 
3~4월 중에 진행이 가능한지 검토중입니다.
