### ISSUE TITLE
Studio: Map / 지도 기본값을 이벤트 변수와, 이벤트 변수값이 없을 때 설정할 수 있는 방법 필요

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1789]
## 기능 요청 ##
Map 객체의 지도 레이어(layer map)은 기본값을 수치와 변수 두 가지 방식으로 설정할 수 있습니다.
그런데 변수 방식으로 설정하면 수치 방식으로는 설정할 수 없어,
해당하는 지도 이벤트가 발생하여 변수 값이 채워지기 전에는 지도의 기본 위치(현재 인도 델리)로 설정됩니다.
두 가지 방식을 동시에 설정할 수 있거나, 지도의 기본 위치를 따로 설정할 수 있어야 합니다.

## 스크린샷
![image](https://user-images.githubusercontent.com/3411842/71605713-7e361980-2bae-11ea-8ac1-e96e4b6d6ea2.png)

![image](https://user-images.githubusercontent.com/3411842/71605731-9a39bb00-2bae-11ea-96cd-6a215be5f2fc.png)

**Comment by minjaekang7** [comment]
아직 수정이 안되었을 것으로 여겨지는 데, 이전과 다르게 동작합니다.
변수를 ${EVENT_LAT}, ${EVENT_LNG}등으로 설정해도 다시 열어보면 28.618281599983852가 들어가 있습니다. 확인바랍니다.

**Comment by veldise** [comment]
@minjaekang7 
네, 댓글로 말씀하신 문제는 #1795 에서 처리하겠습니다.
