### ISSUE TITLE
[코트라]로그인 문구변경

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1793]
## 기능 요청 ##
로그인 화면 안내문구 수정이 필요합니다. 

![2BBD3159-4B96-43E4-9C0E-5CAA194777F6](https://user-images.githubusercontent.com/18297120/71703588-b771c200-2e18-11ea-887b-d77e1fc709c7.jpeg)

## 고려한 다른 대안 ##
문구가 상황에 따라, 조직이나 역할이 변경되는 경우 
내용이 바뀌어야 하는데, 
화면 안내문구를 수정할 수 있는 별도의 resource 파일로 분리할 수 있을까요?

**Comment by veldise** [comment]
@yariyarishow 

#### 1. 안내문구 변경? 추가?
이슈 본문에 작성해주신대로라면, 안내 문구를 서브타이틀 아래에 추가하는 것으로 보입니다.
변경이 아닌 추가가 맞는지 답변을 부탁드립니다.

현재 서브 타이틀:
A New Experience in Big Data Analytics
IRIS Big Data Platform

어느쪽이든 디자인/퍼블리싱/개발 작업이 필요하며, 진행 예정입니다.


#### 2. 화면 안내문구 부분을 별도의 resource 파일로 설정할 수 있는 기능
현재 저희팀은 수원시/NMSPLUS/교통연 등 다른 프로젝트 지원을 위한 개발 일정이 밀려있어
해당 기능을 개발하기가 어렵습니다. 이 기능이 반드시 필요한지 궁금합니다.


#### 3. 회사 및 제품 로고 변경
전력연이나 교통연 등에서는 회사 로고(Mobigen) 및 제품 로고(IRIS) 변경 요청이 있어,
해당 사이트에서 보내준 이미지나, 디자인팀에서 제작한 이미지로 각 이미지를 교체하였습니다.
KOTRA의 경우에는 로고 변경이 불필요한지 궁금합니다.
자세한 내용은 아래 문서를 확인하시기 바랍니다.

https://github.com/mobigen/IRIS-BigData-Platform/wiki/IRIS-Web-Customize-%EA%B0%80%EC%9D%B4%EB%93%9C


#### 4. 일정 
안내 문구 변경이 언제 완료/적용되어야 하는지 궁금합니다.
다른 업무가 밀려있어 금주중에는 어렵습니다.
일정에 대해 답변 부탁드립니다.

**Comment by yariyarishow** [comment]
1. 일정 :  1월 16일에 사용자 공개가 진행됩니다. 그 전에 적용되어야 합니다. 15일까지 겠네요.

2. 변경항목 : 문구 추가 및 로고 변경(오늘 얘기됨)

               변경에 대해서는 따로 메일 드리겠습니다. 

3. resource 분리 : 담당팀 변경, 계정 생성 정책 등이 바뀌는 경우 매번 연구소에 의뢰하는게 비효율적이라 생각해서 요청햇습니다. 

                     당장 구현되어야 하는 것은 아니고, 본 프로젝트 종료가 3월14일 인데 이 전에 적용하면 될것 같습니다.

**Comment by veldise** [comment]
@yariyarishow 
로고 변경은 시간이 촉박하여 15일까지는 어려울 것 같습니다.
안내문구는 본문 스크린샷 내용대로 추가해보도록 하겠습니다.

**Comment by onlyeon** [comment]
@yariyarishow 
본문 스크린샷의 안내 문구 추가 적용안 2개 첨부 드립니다.

1. IRIS의 Notification 콤포넌트를 활용한 시안
![스크린샷 2020-01-13 오후 2 08 14](https://user-images.githubusercontent.com/11944592/72234023-2ec00680-360e-11ea-8fa7-52eb284649ce.png)
2. 임시 스타일로 안내 문구를 추가한 시안
![스크린샷 2020-01-13 오후 2 07 52](https://user-images.githubusercontent.com/11944592/72234027-3384ba80-360e-11ea-80e6-40437db5f422.png)

안내 문구의 경우 error 보다는 warning으로 보이도록 작업했습니다.
두개 시안 검토 부탁 드리며, 확정되는 안으로 퍼블리싱 완료되도록 준비하겠습니다.

감사합니다.

**Comment by yariyarishow** [comment]
1번 안으로 해주세요. 감사합니다

**Comment by onlyeon** [comment]
요청 추가 사항에 대해 답변/추가 질문 드립니다.

_요청 추가) 좌측 상단의 로고를 강주희 선임님이 작업중이시니 이 로고도 대체해 주시기 바랍니다._

로그인 폼 가운데에 IRIS 로고는 그대로 유지되나요?
로그인 화면 상단에는 기업 로고, 로그인 폼 가운데(현 IRIS로고 위치)에 솔루션 로고가 들어갑니다.
확인 부탁 드립니다!

**Comment by yariyarishow** [comment]
IRIS는 솔루션 이름으로 인지하고 있어서 변경 안합니다.

**Comment by veldise** [comment]
로고 이미지지까지 적용한 화면입니다.

![image](https://user-images.githubusercontent.com/3411842/72405535-a328b000-379c-11ea-8ecd-6bf539cc4cfc.png)

**Comment by veldise** [comment]
패치로 적용 완료했다고 전달받아 이슈 닫습니다.
