### ISSUE TITLE
데이터브라우저 - 고급시각화로 이동 - 검색으로 이동  시 에러

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1794]
## 버그 설명 ##
데이터브라우저>검색 에서 결과 조회 후 고급시각화로 이동 
고급시각화화면에서 실행버튼 누르지 않고 다시 검색으로 이동 시 에러 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to  '데이터브라우저-검색'
2. Click on 'myiris'  계정의 분석템플릿 ANIMP_ADE_SCORE_1M_20190617_0621(1)  실행
3. 검색 결과 화면에서 오른쪽 상단  '고급시각화로 이동' 
4. 고급시각화 화면에서 마지막 실행 버튼을 누르지 않고 다시 오른쪽 상단 '검색으로 이동'
5. 에러

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

<img width="852" alt="스크린샷 2020-01-06 오전 11 25 01" src="https://user-images.githubusercontent.com/5126497/71791145-36fccc80-3077-11ea-97cc-bec020ceb565.png">

고급시각화 에서 '실행' 하지 않고 검색으로 이동
<img width="852" alt="스크린샷 2020-01-06 오전 10 45 46" src="https://user-images.githubusercontent.com/5126497/71791013-b938c100-3076-11ea-8589-6e404e54234e.png">

<img width="752" alt="스크린샷 2020-01-06 오전 10 45 55" src="https://user-images.githubusercontent.com/5126497/71791022-c3f35600-3076-11ea-90a7-c662867249b1.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
"분석 유형 선택"을 하지 않았을 때 예외처리가 되어있지 않아서 발생하는 문제입니다.
