### ISSUE TITLE
[Studio]데이터모델에 저장된 위/경도값 및 City 정보를 기준으로 세계지도 상에서 해당 위치에 값 표시 불가

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#1798]
## 기능 요청 ##
DSMS가 아닌 데이터모델에 저장된 위/경도값 및 city 정보 등을 기준으로 세계지도 상에서 해당 위치에 카운트 표현이 안됩니다.
(시각화의 클러스터맵 화면에서는 가능 - 아래 클러스터맵 화면 참조)
![image](https://user-images.githubusercontent.com/23075670/71868947-acd66600-3153-11ea-91c9-a31606e0cf93.png)

## 원하는 솔루션 설명 ##
굳이 DSMS에 지도관련 데이터를 별도로 저장하지 않고, 데이터모델에 저장된 데이터로 지도상에서 표현할 수 있는 기능 구현을 요청드립니다.

**Comment by jins00** [comment]
상기 기능은 다이렉트클라우드와 현재 진행중인 대시보드 서비스에 포함하고자 하는 기능으로, 4월 초에 일본 전시회에서 데모를 희망하고 있습니다.

**Comment by veldise** [comment]
@namjals @seungfwani 
IP_LOC 모델 검색 결과의 일부는 다음과 같습니다.

![image](https://user-images.githubusercontent.com/3411842/72782977-91498000-3c68-11ea-87c3-0c2026f36bab.png)

Studio 에서는 현재 화면에 출력된 지도 범위에 대하여 4꼭지점 위/경도 값을 취하여, 
아래와 같은 형식으로 Angora DSL을 구성하여 실행합니다.
```
model name = 'IP_LOC' spatial_coordinates = 'POLYGON((45.120052841530544 102.65625000000001, 45.120052841530544 144.31640625000003, 29.19053283229458 144.31640625000003, 29.19053283229458 102.65625000000001, 45.120052841530544 102.65625000000001))'
```

위 좌표와 IP_LOC에 있는 `37, 126` 좌표는 아래와 같습니다.

![image](https://user-images.githubusercontent.com/3411842/72783051-ceae0d80-3c68-11ea-8db9-b3130bb5b79c.png)

제가 알기로 `spatial_coordinates`은 일종의 필터링이므로, 위와 같은 구성이라면 작업 결과가 있어야 합니다.
그런데 작업 결과 개수가 0으로 나옵니다.

`spatial_coordinates`, `map_level` 등에 대하여 설명을 해주시기 바랍니다.

**Comment by sunghoon** [comment]
정상적으로 동작하는것 같아 보여 해당 이슈는 닫습니다. 

![스크린샷 2020-09-22 오전 9 49 30](https://user-images.githubusercontent.com/512653/93835037-eab2f480-fcb8-11ea-87b2-7ef54b7d7eb9.png)
