### ISSUE TITLE
[데이터추가] 메뉴에서 로딩이 완료된 것을 명확하게 알 수가 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1799]
## 버그 설명 ##
데이터 추가 메뉴에서 CSV파일을 IRIS 테이블로 로딩하기 위해 '제출' 을 클릭한 후
작업현황의 마지막라인 또는 상단 메뉴바에서 
**명확하게 로딩이 끝난 것을 알 수 가 없습니다**.
한참 지나도 화면이 바뀌는 게 없는 걸 보고
DB 조회에서 테이블에 인서트된 레코드건수를 sql 로 조회한 후에 파일 로딩이 완료된 걸 확인할 수 있었습니다.

<img width="1144" alt="스크린샷 2020-01-07 오후 3 34 15" src="https://user-images.githubusercontent.com/5126497/71874325-01cea800-3165-11ea-809e-3e4d50196211.png">

* 하단 작업 현황의 마지막 줄
<img width="341" alt="스크린샷 2020-01-07 오후 3 47 51" src="https://user-images.githubusercontent.com/5126497/71874498-6c7fe380-3165-11ea-83fc-dae429f75b0d.png">

* 상단 단계 바 : 제출 버튼이 로딩중과 동일하게 비활성화되어 있고, '입력'에서 '검토' 단계로 넘어가는 버튼 등 이 없음
<img width="805" alt="스크린샷 2020-01-07 오후 3 48 02" src="https://user-images.githubusercontent.com/5126497/71874454-57a35000-3165-11ea-986f-b164b4dd3d24.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
동일 사항이 발생하면 새 이슈로 등록해 주세요.
