### ISSUE TITLE
[데이터추가] 한글이 있는 파일을 IRIS테이블로 로딩하는데 unicode 관련 에러가 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1805]
## 버그 설명 ##
한글이 있는 파일(UTF-8) 을 데이터추가 메뉴에서 IRIS테이블로 로딩하는데, 바로 에러 납니다.

Data Splited File:
	Traceback (most recent call last):
  File "addon/iris-load/loader.py", line 267, in <module>
    main()
  File "addon/iris-load/loader.py", line 261, in main
    proc (g, file)
  File "addon/iris-load/loader.py", line 246, in proc
    make_splited_file_and_upload(ctx_path, s, g, job_id)
  File "addon/iris-load/loader.py", line 164, in make_splited_file_and_upload
    print "\t", key, len(partition_group_data[key])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-19: ordinal not in range(128)

<img width="456" alt="스크린샷 2020-01-08 오후 3 36 06" src="https://user-images.githubusercontent.com/5126497/71955800-a667ed00-322c-11ea-9846-02692aac0b97.png">

<img width="1010" alt="스크린샷 2020-01-08 오후 3 34 43" src="https://user-images.githubusercontent.com/5126497/71955718-715b9a80-322c-11ea-8fad-ee6cc3e94510.png">

![스크린샷 2020-01-08 오후 3 32 08](https://user-images.githubusercontent.com/5126497/71955640-3b1e1b00-322c-11ea-9f00-c57492d0b9c8.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
같은 상황이 발생하면 새 이슈로 등록해 주세요.
