### ISSUE TITLE
새모델 생성시 연결정보에서 무한대기현상

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#1808]
## 버그 설명 ##
쿠버네티스로 생성한 클러스터에서 새모델 생성 -> 연결정보 IRIS -> iris 선택시 무한대기현상 발생
![image](https://user-images.githubusercontent.com/44352311/72024783-8cc0b700-32b9-11ea-9e60-b2b6fb7d320b.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 쿠버네티스 클러스터를 통해 IRIS Web 실행
2. 생성된 클러스터의 IRIS Web에 접속후, 로그인
3. GNB 데이터 브라우저 > 관리 > 데이터 모델 접속
4. 우측 상단 '새 모델' 클릭
5. 연결 정보 IRIS -> iris 선택
무한대기현상 발생

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
해당 사항이 재현되지 않으며, 해결된 것으로 보고 닫습니다.
