### ISSUE TITLE
[코트라]메뉴에 외부서비스 등록 실행이 안됨

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1809]
## 버그
![CCF96D80-8DBF-4B5D-AEFB-1D893D699B0B](https://user-images.githubusercontent.com/18297120/72043113-ac74d100-32f3-11ea-9a02-d81f8c00d88a.jpeg)

아이리스 메뉴를 추가하고, 
다른 서비스 URL을 적용해서 보려고 하는데, 
실제 화면에 출력이 안되네요. 

확인해 볼 부분이 무엇이 있을까요?

**Comment by yariyarishow** [comment]
![image](https://user-images.githubusercontent.com/18297120/72043316-315fea80-32f4-11ea-9de8-bd1873fa234e.jpg)

**Comment by veldise** [comment]
@yariyarishow 
입력하신 URL이 iframe 에 설정되는 것이므로, 해당 서버에서 CORS 설정을 비활성화(disable)해줘야 합니다.

사용자가 접속하는 도메인은 `192.168.70.226:8888`, iframe에 설정되는 도메인은 `180.100.100.167`로
서로 다른 도메인이므로 CORS 설정이 걸려있으면 브라우저 보안 정책에 위배되어 차단됩니다.

**Comment by yariyarishow** [comment]
답변 쌩유요.!!
