### ISSUE TITLE
[보고서예제]IRIS 웹/Studio 의  추가되는 기능의 샘플/예제 관리 요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1810]
## 기능 요청 ##
IRIS 웹/studio 의 기능이 추가되고 있어서 기능별 사용예제를 요청드렸었습니다.

그런데 B-IRIS 에 워낙 많은 사용자들이 있어서 전에 사용했던 예제등을 찾기가 어렵네요.

예제를 만드는 계정을 따로 만들던가
보고서목록에서 그룹을 만드는 기능이 있던가 했으면 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
해당 사항으로 반영 될 수 있도록 하겠습니다.
