### ISSUE TITLE
[NMS+] studio 그리드의  세로 스크롤 제거할수있는 방안

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1811]
## 기능 요청 ##

#1775 이슈는 iframe 의 가로/세로 스크롤인데, 

studio 보고서에서 그리드를 생성하여 데이터 조회시 세로스크롤이 무조건 생기는데요.
데이터가 1건만 있어도 아무리 그리드를 크게 생성해도 세로 스크롤이 생김니다.

studio 보고서내의 그리드에 세로 스크롤을 어떻게 제거할수있는지 가이드 부탁드립니다.

![캡처](https://user-images.githubusercontent.com/5468183/72118889-0037f680-3396-11ea-996f-621723a1133f.PNG)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
그리드를 구성하는 것은 Chart 객체로, 현재 스크롤이 차트 객체 자체에 발생하고 있습니다.
이는 버그로 판단되며 차주 패치에 수정하도록 하겠습니다.

아래와 같은 경우는 그리드 내용(contents)가 많아서 생기는 경우로 정상입니다.

![image](https://user-images.githubusercontent.com/3411842/72119158-c9161500-3396-11ea-95ed-c22c216846f7.png)
