### ISSUE TITLE
시각화시 소수점 아래 2자리로 표현

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#1814]
## 버그 설명 ##
시각화시 text(rule_id )와 integer(detection_count)였던 데이터가 소수점 아래 2자리로 표현됩니다.

## 재현하는 방법 ##
데이터 모델: DQ_result
`* | pivot sum(detection_count) SPLITROW rule_id SORT desc | head 7`

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
텍스트와 정수로 표현 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/5077625/72236101-d4787300-3618-11ea-9fd7-71343ed33f02.png)
아래 표처럼 텍스트와 정수로 표현되어야 하는데 소수점 아래 2자리까지 표현됨

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#1916 이슈 긴급 처리로 인해 마일스톤 변경했습니다.

**Comment by veldise** [comment]
7/16 패치로 해결되어 닫습니다.
