### ISSUE TITLE
검색 / "샘플링"에 난수(random seed) 추가

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1815]
## 기능 요청 ##
샘플링 결과가 균일하게 나올 수 있도록 난수(random seed)를 추가할 수 있는 기능 요청

## 원하는 솔루션 설명 ##
예를 들어, 1:100 비율로 샘플링을 할 때 난수를 설정하지 않으면, 사용자마다 샘플링 결과가 다를 수 있다고 생각합니다.

검색 결과를 피벗, 시각화, 이상탐지로 이동하여 분석을 진행할 수 있는 만큼, 일관된 결과를 유지할 수 있도록 난수 설정 기능이 필요하다고 생각합니다.

**Comment by sunghoon** [comment]
해당 기능은 여러가지 사정으로 우선은 reject 하도록 하겠습니다. 
해당 실제 필요한 시점에 다시 재기해 주기 바랍니다.
