### ISSUE TITLE
studio: Popup, Portlet / combo-box 항목 트리거 설정이 동작하지 않음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1816]
## 버그 설명 ##
트리거 설정에 의해 combo-box의 항목 선택되는 동작이, Popup 객체로 보고서를 불러왔을 때는 동작하지 않습니다.

#### 보고서 단독 실행 (정상)
버튼을 누르면 combo 값이 설정됨:
![image](https://user-images.githubusercontent.com/3411842/72326007-aadf4a80-36f1-11ea-91f0-507413af2c53.png)

#### Popup 객체로 보고서 실행 (비정상)
버튼을 눌러도 combo 값이 설정되지 않음:
![image](https://user-images.githubusercontent.com/3411842/72326057-c64a5580-36f1-11ea-92a6-0baacd2c6915.png)

browser console:
![image](https://user-images.githubusercontent.com/3411842/72325956-900cd600-36f1-11ea-85ca-4ff6b9729f51.png)

**Comment by jjinylee** [comment]
해당건 적용됬는지요?

**Comment by veldise** [comment]
@jjinylee 
다른 이슈 처리중이라 아직 처리되지 않았습니다.
처리되어야할 기한이 있다면 박세종 팀장님께 연락 부탁드립니다.

**Comment by jjinylee** [comment]
이건도 close 도 되어있는데 close 된건가요?

확인부탁드립니다.

![combo_1](https://user-images.githubusercontent.com/5468183/75002290-3b563b00-54a7-11ea-8684-788d5466ee6a.png)

![combo_2](https://user-images.githubusercontent.com/5468183/75002381-94be6a00-54a7-11ea-8d49-7f4861ee7dae.png)

**Comment by veldise** [comment]
@jjinylee 
기본적으로 Close 는 본사 데모서버에 패치된 시점에 합니다.
일단 다시 확인해보겠습니다.

**Comment by jjinylee** [comment]
해당건 빠른 확인부탁드립니다.
CRUD 기본 기능으로 해당건은 연구소 일정나온 이후 개발기간을 대기하고있었고, popup 에서 정상동작하지 않아서 적용가능 일시만 사이트에서 대기하고 있었습니다.

만약 위의 사항 재연 및 확인이 어려우면 저희가 폐쇄망이라 직접 접속하실수없으니
제 pc 에 접속하여 확인하는것도 방법입니다.
(필요하시면 comment 주시면 연락드릴게요.
재연/확인을 위한 시간도 가능한 줄이고 싶습니다. )

정말 빠른 확인부탁드립니다.

**Comment by veldise** [comment]
@jjinylee 
1. 이슈 본문에 해당하는 "Popup 내에서 버튼 클릭시 Combo의 값 설정"은 정상 동작을 확인했습니다.

**Comment by veldise** [comment]
@jjinylee 
1. 이슈 본문에 해당하는 "Popup 내에서 버튼 클릭시 Combo의 값 설정"은 정상 동작을 확인했습니다.
2. 항목 > "디폴트 값 입력" > "직접 입력"은 Popup 의 경우 동작하지 않고 있습니다. (버그)
3. 코멘트로 말씀해주신 트리거를 REST API에 걸었을 경우 원인파악에 시간이 조금 걸립니다.

제가 다른 일정이 많아 오늘중에는 어렵고, 차주 화요일까지는 해결해보겠습니다.

**Comment by jjinylee** [comment]
우선 위의 글이 상황을 설명하느라 써놓은거라 전체가 다 에러가 있다는건 아닙니다.

제가 올린 글의 요지는 
1. 페이지 : 콤보에 restAPI 조회하여  restAPI 변수로 값 세팅  : 정상 입니다.  ( 1페이지는 정상입니다.)

2.페이지 :  1페이지에서 기본값 세팅한후 일부 콤보만 수정하였습니다.
 그리고 저장 restAPI 탈경우  콤보를 클릭하여 값을 변경한경우만 정상적으로 (code 값) 세팅되고
콤보를 선택하여 액션을 하지않은경우는 name 으로 넘어간다 입니다.

위에서 restAPI 값중, venId=27, devGroupCd=2 만 콤보를 선택하여 다른값으로 변경한경우 cd 값으로 세팅되나,
나머지 콤보들은 다 name ( 보여지는 필드값) 으로 restAPI 변수에 set됩니다.

**Comment by veldise** [comment]
@jjinylee 
알겠습니다. 변수값을 갱신하는 부분에 버그가 있는 것 같습니다.
현재 "전체 변수명 보기" 에서도 콤보 객체의 변수 값이 갱신되지 않고 있습니다.

**Comment by veldise** [comment]
@jjinylee 
아래 이슈로 분리하여 진행하겠습니다.
#1916
