### ISSUE TITLE
검색 / 시각화 차트의 '값'을 변경할 때 차트가 즉시 변경되지 않음

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1817]
## 버그 설명 ##
스크린샷을 통해 설명 드리겠습니다

## 재현하는 방법 ##
동작을 재현하는 방법 :
스크린샷을 따라 재현하시면 될 것 같습니다.
(사용된 데이터모델은 SYSLOG 데이터모델입니다)

## 스크린샷 ##
1. 스크린샷의 검색 바와 동일하게 입력한 후 실행하여 "시각화 탭"을 보면 처음 보이는 그래프가 아래와 같은 꺾은선 그래프입니다.
![image](https://user-images.githubusercontent.com/35832986/72396007-a4e37b00-377e-11ea-8637-f90d08ee2110.png)

2. "차트 유형"을 '세로막대형'으로 변경하면 별도의 실행없이 그래프가 바로 바뀝니다
![image](https://user-images.githubusercontent.com/35832986/72396090-ee33ca80-377e-11ea-86c4-4b9c51a55af0.png)

3. 그런데 "값"에서 다른 값을 선택 또는 해제해서 내용을 변경하면 그래프가 바로 바뀌지 않습니다.
![image](https://user-images.githubusercontent.com/35832986/72396127-086da880-377f-11ea-8069-85df1d4cc8aa.png)

이걸 적용하려면 반드시 "차트 유형"을 다른걸로 바꿨다가 다시 돌아와야 합니다.
![image](https://user-images.githubusercontent.com/35832986/72396181-318e3900-377f-11ea-993b-d80b830ce275.png)

## 기대하는 해결 방향 ##
"값"도 "차트 유형"과 마찬가지로 내용이 변경되면 그래프에 즉시 반영되어야 한다고 생각합니다.

그렇지 않다면 "옵션" 버튼 옆에 "적용" 버튼 같은 걸 만들어서 사용자가 차트 옵션을 수정한 후 결과가 반영되게 하면 좋을 것 같습니다.

**Comment by veldise** [comment]
#1916 이슈 긴급 처리로 인해 마일스톤 변경했습니다.
