### ISSUE TITLE
[KOTRA]대쉬보드 오류

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1818]
[긴급]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
![DE488268-7702-479E-985A-13DC3260274B](https://user-images.githubusercontent.com/18297120/72408200-775df800-37a5-11ea-91aa-26842b490a31.jpeg)

![image](https://user-images.githubusercontent.com/18297120/72408270-b0966800-37a5-11ea-83bb-22c2b7f2678b.png)

## 재현하는 방법 ##
위 사진에 보이는 버전의 크롬에서 아이리스 기본 대쉬보드 조회시 오류

대쉬보드가 렌더링이 끝나는 시점에 "앗 이런" 화면으로 전환됨.

**Comment by veldise** [comment]
일단 현재 구글 크롬 브라우저 최신 버전은 아래와 같습니다. (MacOS 10.13.6 기준)

![image](https://user-images.githubusercontent.com/3411842/72410625-2dc4db80-37ac-11ea-93b7-16fdca99a581.png)

**Comment by veldise** [comment]
@yariyarishow 
재현을 위해 조금 더 상세한 내용이 필요합니다.

**Comment by yariyarishow** [comment]
위에 캡처한 크롬 버전보다 하위 버전에서는 정상 작동을 하고 있어요. 
폐쇄망이다 보니 크롬 버전 변경이 쉽지 않아요. 
크롬을 최신버전으로 업그레이드 했을때 문제가 없다면 그렇게 유도하려구요.

**Comment by veldise** [comment]
@yariyarishow 
네.. 가급적이면 최신 버전으로 업그레이드하는 방향으로 부탁드립니다.
제 개인 PC가 Windows 7이라서 그런지 76버전으로 다운그레이드가 안되어 테스트가 어렵습니다.

**Comment by sunghoon** [comment]
해결된 이슈로 보고 닫습니다.
