### ISSUE TITLE
[NMS+]보완-보고서에서 사용한 쿼리를 데이터브라우저나 DB브라우저에 넘겨서 화면 띄우기 

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1819]
## 기능 요청 ##
#1626 

- 보고서에서 사용한 쿼리를 데이터브라우저나 DB브라우저에 넘겨서 화면 띄우기 

기능이 적용되었으나 현재 보고서는 쿼리등을 작성시 파라미터값이나 변수값에 따라 쿼리가 동적생성됩니다.
따라서 쿼리를 그대로 넘기면 안되고 파라미터값/변수값을 적용하여 
데이터브라우저나 DB브라우저에 넘겨서 실행되어야 합니다.

현재 기능은 적용되어있으나 변수값들이 치환되어 넘어가지 않으므로 데이터 검색시 결과가 당연히 조회되지않고 해당기능을 제대로 사용할수가 없습니다.

보완요청드립니다. 

![Inkediris_db_LI](https://user-images.githubusercontent.com/5468183/72416529-32908c00-37ba-11ea-9a3e-b60f0401f5d4.jpg)

![iris_db2](https://user-images.githubusercontent.com/5468183/72416577-59e75900-37ba-11ea-81c5-ebd57e063999.PNG)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by jjinylee** [comment]
보완 일정이 예정되어있는지요?

**Comment by veldise** [comment]
@jjinylee 
다른 이슈 처리중이라 아직 처리되지 않았습니다.
처리되어야할 기한이 있다면 박세종 팀장님께 연락을 부탁드립니다.

**Comment by veldise** [comment]
변수값들이 치환되어 넘어가지 않는 문제 금주내로 패치하겠습니다.
