### ISSUE TITLE
회원가입 / 회원가입 신청해놓고 로그인 시도할 때 표시되는 메시지 변경 요청

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1820]
## 기능 요청 ##
IRIS에서 로그인을 시도할 때 "아이디 또는 비밀번호를 다시 확인하세요." 라는 메시지를 보는 경우가 4가지가 있는 것 같습니다.

1) 아이디를 잘못 입력했을 때
2) 비밀번호를 잘못 입력했을 때
3) 회원가입 신청을 했지만 아직 승인이 안났는데 로그인 시도할 때
4) 회원가입 신청이 거절되었는데 로그인 시도할 때

회원가입을 신청한 사용자는 
- 회원가입 신청이 정상적으로 이루어졌는지
- 내 신청이 거절당했는지 아닌지
를 판단할 방법이 없습니다.

그래서 "3) 회원가입 신청을 했지만 아직 승인이 안났는데 로그인 시도할 때" 일 때,
"아이디 또는 비밀번호를 다시 확인하세요." 메시지 대신
"회원가입 신청이 아직 처리되지 않았습니다" 정도의 메시지가 표시되는게 어떨까 싶습니다.

**Comment by sunghoon** [comment]
진행과 관련된 일정 계획을 공유해 주세요.

**Comment by lyj** [comment]
다음달(11월) 적용으로 진행중입니다.

**Comment by sunghoon** [comment]
@lyj 대략 11월 언제 인가요? 초 / 중 / 말 ?

**Comment by mondbarde** [comment]
기획 완료 되었습니다.
https://docs.google.com/presentation/d/1U1y-O3m28Ccvzh4AzWLZMgoSBzb7BEooVwXCdIEx0MQ/edit?usp=sharing
![image](https://user-images.githubusercontent.com/42177543/96206679-6c3e2f80-0fa4-11eb-9025-97fffbf376fd.png)

**Comment by sunghoon** [comment]
@lyj 개발  진행 계획을 공유해 주세요.

**Comment by lyj** [comment]
해당 이슈는 11월 중순 정도에 처리 예정입니다.
