### ISSUE TITLE
[NMS+]angora 파싱에러

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1824]
## 버그 설명 ##
컬럼명 = INSTANCE 

아래와 같이 컬럼명이 "INSTANCE" 인 컬럼에 조건을 넣으면 "IN" 으로 인식하여 syntax 에러가 나는듯합니다.

* |  where DEV_ID =  '364'  and INSTANCE =1  | adv line avg(MEM_USAGE) SPLITROW SDATM | sort -SDATM

![iris앙고라](https://user-images.githubusercontent.com/5468183/72488290-e2fe9e80-3853-11ea-987f-63715e048c7c.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
해당 내용은 현재 수정되어 운영서버(192.168.100.180) 에 배포하였습니다.

위의 모델이 없어 `ml_geo_angora` 모델을 이용하여 재구성 하여 실행 하였으며
문제 없이 동작하였습니다.
![image](https://user-images.githubusercontent.com/46172579/72768525-01d9a800-3c3b-11ea-85c9-4d08ead46884.png)

**Comment by sunghoon** [comment]
@jjinylee 선임님 해당 이슈 관련하여 적용 사이트에도 반영되어 있는지 확인 부탁드립니다. 미 반영되어 있다면 운영기술연구팀에 배포 요청해 주시기 바랍니다.

**Comment by seungfwani** [comment]
해당 이슈를 닫아도 될지 유선상으로 문의 드렸는데 확인이 되셨는지 궁금합니다.

**Comment by jjinylee** [comment]
앗.. 네 답변이 늦어 죄송합다
저희 사이트에 적용되어 정상동작확인했습니다. 감사합니다

**Comment by seungfwani** [comment]
감사합니다. 이슈 닫도록 하겠습니다.
