### ISSUE TITLE
데이터 모델 / [연결 정보]에 권한없는 연결정보와 테이블이 전부 보이는 문제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1825]
## 버그 설명 ##
스크린샷으로 설명드리겠습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

AA연구팀에서 User manual 작성을 맡게 되어 이를 위한 테스트 계정을 생성하고 발견한 이슈입니다.

## 스크린샷 ##
1. manual 계정에서 모든 연걸정보가 보이고
![image](https://user-images.githubusercontent.com/35832986/72505581-9763e900-3883-11ea-8295-cdd3117ee095.png)

2. manual 계정에서 접근 권한이 전혀 없는 테이블들이 [대상 데이터]에 전부 표시됩니다.
![image](https://user-images.githubusercontent.com/35832986/72505780-f45f9f00-3883-11ea-894e-9351189e9cc6.png)

## 예상한 행동 ##
계정별로 계정에서 접근 가능한 데이터만 표시되어야 할 것 같습니다.

## 기타 ##
참고로 현재 (2020.01.16) 기준 manual 테이블에서 권한을 가진 테이블의 목록입니다. 
![image](https://user-images.githubusercontent.com/35832986/72505966-4d2f3780-3884-11ea-9b08-d923327bdf49.png)

**Comment by seungfwani** [comment]
대상 테이블 목록을 리턴하는 주체는 앙고라 이기 때문에 라벨 변경하겠습니다.

**Comment by sunghoon** [comment]
본 이슈는 닫도록 하겠습니다. 추가 사항이 발생하면 별도 이슈로 처리하겠습니다.
