### ISSUE TITLE
데이터 모델 / 값이 숫자이면서 타입이 텍스트일경우 없던 소숫점이 표현됨

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1828]
## 버그 설명 ##
데이터 모델을 생성시에, 값이 숫자이면서 타입이 텍스트로 지정할 경우에
값이 정수값이었음에도 소숫점이 나타나게 됩니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :

* manual 계정의 BATTING_TABLE 참조

- 데이터 모델 BATTING_TABLE을 설정할때 연도(YEARID)컬럼을 텍스트로 설정

<img width="957" alt="스크린샷 2020-01-17 오후 2 20 08" src="https://user-images.githubusercontent.com/36151180/72586372-cd14da80-3934-11ea-9323-0d5f9902ff15.png">

- 텍스트로 변형한 연도(YEARID)컬럼에 소수점이 나타남

<img width="766" alt="스크린샷 2020-01-17 오후 2 21 44" src="https://user-images.githubusercontent.com/36151180/72586649-e2d6cf80-3935-11ea-92fa-72e463514e42.png">

- 파일내보내기를 통해 받은 파일에서는 (YEARID)컬럼에 소수점이 없는것으로 확인됨

<img width="633" alt="스크린샷 2020-01-17 오후 2 25 37" src="https://user-images.githubusercontent.com/36151180/72586671-f2561880-3935-11ea-809f-80cc237dba89.png">

## 예상한 행동 ##
숫자를 텍스트로 변환 할 시에는, 
숫자값이 소수점을 포함한 실수값이든, 소수점이 없는 정수값이든
그 값 자체는 변형되지 않은 그대로 텍스트로 변환되어야 합니다. 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/72588845-f0dc1e80-393c-11ea-98fb-52dd2ac54124.png)

**Comment by seungfwani** [comment]
@joohj7 
해당 부분에 대해서 답변을 드리겠습니다.

우선 작성해주신 부분은 앙고라의 이슈는 아닙니다.
IRIS DB 의 `BATTING.BATTING` 테이블의 스키마를 확인해보면 아래와 같습니다.
```
( PTIME TEXT , PLAYERID TEXT , YEARID NUMBER , STINT NUMBER , TEAMID TEXT , LGID TEXT , G NUMBER , AB NUMBER , R NUMBER , H NUMBER , TWO_B NUMBER , THREE_B NUMBER , HR NUMBER , RBI NUMBER , SB NUMBER , CS NUMBER , BB NUMBER , SO NUMBER , IBB NUMBER , HBP NUMBER , SH NUMBER , SF NUMBER , GIDP NUMBER , FTS_RAW_DATA TEXT , FTS_PARTITION_TIME TEXT )
```
이 테이블은 오래전에 생성된 테이블로 `NUMBER` 라는 타입을 사용합니다.
`NUMBER` 타입은 앙고라에서 실수로 처리가 되기 때문에 작성해주신 문제가 나타난 것입니다.

-----

하지만 현재 IRIS DB에서는 `TEXT`, `INTEGER`, `REAL` 세 종류의 타입만 사용하고, `NUMBER` 타입은 더이상 사용되지 않기 때문에 테이블의 스키마를 수정하였습니다.

테이블을 수정한 후 데이터를 IRIS WEB에서 검색한 결과입니다.
![image](https://user-images.githubusercontent.com/46172579/72703328-a656de00-3b98-11ea-886c-524b02e4f520.png)
