### ISSUE TITLE
데이터 시각화 / 분석탬플릿 저장후, 로드시 시각화가 불러와지지 않음 

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1831]
## 버그 설명 ##
데이터 시각화에서 분석탬플릿을 저장한 뒤에 , 
분석탬플릿기능에서 저장한 탬플릿을 불러오기를 했더니 
아무것도 실행되지 않습니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 고급시각화에서 테이블을 선택한다. 
2. 시각화를 해본다., 
3. 시각화한 것을 분석탬플릿 저장을 해본다. 
4. 메뉴의 분석탬플릿에 가서 저장한 탬플릿을 클릭하여 실행해본다. 

## 예상한 행동 ##
저장된 쿼리에 맞게 저장된 시각화 결과가 나와야 합니다. 

## 스크린샷 ##

<img width="1392" alt="스크린샷 2020-01-17 오후 5 56 22" src="https://user-images.githubusercontent.com/36151180/72598221-ba110300-3952-11ea-9f36-4d18f545ab5d.png">

<img width="884" alt="스크린샷 2020-01-17 오후 5 58 50" src="https://user-images.githubusercontent.com/36151180/72598384-1116d800-3953-11ea-8e8b-3bd9e46cbaf2.png">

<img width="1395" alt="스크린샷 2020-01-17 오후 6 00 49" src="https://user-images.githubusercontent.com/36151180/72598550-5804cd80-3953-11ea-92e1-15ac30c128a4.png">

## 기타 ##

글로벌, 로컬, 공유받은 테이블 모두 테스트를 해 보았고, 
모두다 저장된 분석시각화의 로드가 되지 않았습니다.

**Comment by veldise** [comment]
#1609 와 동일 문제입니다.

**Comment by seungfwani** [comment]
@veldise 
해당 부분을 수정하여 아래와 같이 결과가 나오도록 수정 하였습니다.
```
{
  "data": {
    "q": "*",
    "parameters": {
      "rows": [
        {
          "field": "year"
        }
      ],
      "cols": [
        "country"
      ],
      "col_size": 500,
      "cells": [
        {
          "func": "sum",
          "field": "population"
        }
      ],
      "filters": [
        "country LIKE 'A%'"
      ],
      "sort": null
    },
    "operation": "line",
    "request": {
      "url": "/angora/adv-line",
      "method": "POST"
    }
  }
}
```

위의 결과를 통해 페이지에서 나타난 `필터` 부분이 다릅니다.
확인이 필요 할 것 같습니다.
![image](https://user-images.githubusercontent.com/46172579/72767489-727ec580-3c37-11ea-8bc4-80f98fe5022c.png)

**Comment by veldise** [comment]
@seungfwani 
해당 부분은 UI에서 다르게 출력하도록 처리하는 부분입니다. 정상입니다.

**Comment by veldise** [comment]
@seungfwani 
필터 문제는 별도 이슈로 분리하여 처리하겠습니다. #1837
