### ISSUE TITLE
[NMS+]보고서에서 사용자id 를 알수있는 방법

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1832]
## 기능 요청 ##
CRUD 보고서를 만들었는데, CUD 작업시 작업이력등을 저장할때 사용자 id 를 넣어야합니다.
IRIS 의 로그인한 user_id 정보를 보고서에서 어떻게 알수있나요?

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@jjinylee 
현재 버전에서는 user_id를 얻을 수 있는 방법이 없고, 전역변수로 추가하는 등 기능을 개발해야 합니다.

**Comment by veldise** [comment]
#1833 동일 이슈로 보고 닫겠습니다.
