### ISSUE TITLE
[NMS+]보고서에서 사용자id 를 알수있는 기능 요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1833]
## 기능 요청 ##
아래 문의드렸던 사항으로 보고서로 CRUD 기능을 적용하게 됨으로
어떤 사용자가 등록/수정/삭제했는지 이력을 저장해야하는 기능이 필요하여
사용자 id 확인 기능 개발 부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
`USER_ID` 전역변수를 추가하는 방향으로 진행해보겠습니다.
다만 이 변수는 '내보내기 URL' 관련 기능에서는 사용할 수 없을 것입니다. (인증 정보가 없으므로)

**Comment by jjinylee** [comment]
USER_ID 전역변수를 보고서에서 어떻게 사용하는지 가이드 부탁드립니다

**Comment by veldise** [comment]
@jjinylee 

다른 변수와 동일하게 `${USER_ID}` 와 같이 사용하시면 됩니다.
보고서 편집화면에 들어가서 '전체 변수명 보기'를 눌러보시면 아래와 같이 USER_ID 변수를 확인하실 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/75974430-17b8d900-5f1a-11ea-8543-7cf044070447.png)
