### ISSUE TITLE
[NMS+]보고서 tag 기능 (tag 가 1개인경우)

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1834]
## 버그 설명 ##
보고서의 tag 로 표현해야하는 값이 1개이면 제대로 표현이 안됩니다.

![iris_에러](https://user-images.githubusercontent.com/5468183/72692671-88758300-3b70-11ea-9ccf-fe3fbac02907.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@jjinylee 
본사 데모서버(b-iris.mobigen.com)에서는 재현이 안됩니다.
괜찮으시면 해당 테이블 컬럼 정보와, 사이드 패널의 속성 탭에서 어떻게 설정하셨는지
아래와 같은 캡처를 부탁드립니다.

아래 캡처는 syslog 모델로 설정한 예시입니다.

![image](https://user-images.githubusercontent.com/3411842/72766055-d81c8300-3c32-11ea-90cb-36558c56d7cc.png)

**Comment by jjinylee** [comment]
확인해보니 DSMS 에서 max, count 등 함수를 쓰면 그런거 같네요 
( b-iris.mobigen.com 에서 테스트했습니다. max 빼면 되네요 )

![1캡처](https://user-images.githubusercontent.com/5468183/72950389-96c0da80-3dce-11ea-875a-035f9739b8ba.PNG)

**Comment by veldise** [comment]
@jjinylee 
`max` 등 함수 사용문제 보다는 이전 코멘트에 있는 "... 필드 선택"이 잘못 설정되어서 그런 것 같습니다.
한 번 더 확인해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/72950756-970da580-3dcf-11ea-84ca-f30e25965655.png)

**Comment by jjinylee** [comment]
네~ 위의 가이드대로 속성부분의 필드선택하니 됩니다
감사합니다.
