### ISSUE TITLE
[K8S] 새모델 생성시 연결정보에서 무한대기현상

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#1836]
## 버그 설명 ##
쿠버네티스로 생성한 클러스터에서 새모델 생성 -> 연결정보 IRIS -> iris 선택시 무한대기현상 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 쿠버네티스 클러스터를 통해 IRIS Web 실행
2. 생성된 클러스터의 IRIS Web에 접속후, 로그인
3. GNB 데이터 브라우저 > 관리 > 데이터 모델 접속
4. 우측 상단 '새 모델' 클릭
5. 연결 정보 IRIS -> iris 선택
6. 무한대기현상 발생

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/72763633-fd57c400-3c27-11ea-921b-d7987d1fa41c.png)

## 기타 ##
반복적으로 발생하고 있는 에러상황입니다.

**Comment by leehaejoon** [comment]
관련이슈: #1741 
동일 원인으로 파악됩니다.

**Comment by sunghoon** [comment]
이슈 보고의 모호성을 가지고 있으므로 자체적으로 Close 합니다.
