### ISSUE TITLE
시각화 / 꺽은선형 - 단일차트/다중차트 의 영어버전의 문제

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1840]
## 버그 설명 ##
현재 IRIS 매뉴얼 작업중입니다. 
한글판과 영어판의 y축에 위치한 단일차트, 다중차트 문구위치가 어긋나는데 확인 및  수정 부탁드립니다. 

## 스크린샷 ##

<한글판>
<img width="1390" alt="line_by_group" src="https://user-images.githubusercontent.com/36151180/72856275-652c0e80-3cfd-11ea-90e0-b12e60db4abf.png">

<영어판>
<img width="1391" alt="스크린샷 2020-01-22 오전 9 58 15" src="https://user-images.githubusercontent.com/36151180/72856392-c05e0100-3cfd-11ea-8b24-d13374a0b6b1.png">

위 차트는 사파리에서 확인한 사항입니다.

**Comment by veldise** [comment]
일단 임시로 `Multiple charts` 에서 `Multi charts`로 변경하겠습니다.
