### ISSUE TITLE
[KOTRA]보고서 작성시 숫자 출력 포맷 변경 방법문의

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1841]
1.  조회수, 접속수 등의 정수형 표시와 비율 같은 소숫점이 포함되는 실수형 표시가 
    같은 보고서 안에서 어떻게 표현할 수 있습니까?

2. 개인설정에서 소숫점 자리수를 조정하면 모든 화면에 적용이 되는데
    이렇게 적용할 수는 없습니다. 
3. sql의 format_number 를 활용해 보려고 했으나, 이역시 개인설정이 우선 적용이 되어
   활용이 안됩니다. 

4. 방법좀 알려주세요.

**Comment by veldise** [comment]
현재 IRIS 데이터 브라우저 / Studio는 최종적으로 숫자 출력 방식을 개인 설정에 따라갑니다.
이를 서로 다르게 출력하는 UI 기능은 현재 없습니다.

다만 소수점 및 천단위 표시(`,`) 출력 방식은 컬럼의 유형에 따라갑니다.

`TEXT` 유형 컬럼의 경우, 그대로 출력합니다.
`NUMBER`, `REAL` 유형 컬럼의 경우, 소수점/천단위 표시 설정에 따라 출력합니다. (ex) `1,022.00`)
`BIGINT`, `INTEGER` 유형 컬럼의 경우, 소수점은 출력하지 않고 천단위 표시 설정만 적용하여 출력합니다. (ex) `1,022`)

만약 컬럼 유형이 `INTEGER` 인데 소수점이 출력되는등 위와같이 출력되지 않는다면 버그이므로
제보해주시면 빠른 시일 내에 수정하도록 하겠습니다.

**Comment by yariyarishow** [comment]
![image](https://user-images.githubusercontent.com/18297120/72956194-1e641480-3de2-11ea-90e1-49c66bc197a2.jpg)

접속자수 통계는 integer의 sum값이에요. 소수점 한자리가 표시된던 개인설정 때문이구요. 
참고하시기 바랍니다
