### ISSUE TITLE
[NMS+]studio 다이나믹 chart 

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1842]
## 기능 요청 ##
실시간으로 흘러가는데이터의 특성을 가진경우 ( 30초/1분 주기로 데이터가 변경되는 경우등 )
전체데이터를 리로딩하는 방식외에 변화되는 부분만 흘러가게 표현이 되면 활용도가 높을거같습니다.

하이차트의  dynamic 차트 적용기능 요청드립니다. 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
해당 기능에 대한 샘플 보고서가 있으면 공유 부탁드립니다.

**Comment by swish1995** [comment]
@sunghoon 
해당 기능은 b-iris 의 예제 카테고리 [realtime-chart 보고서](http://b-iris.mobigen.com:80/studio/exported/60187463c6714eeeb63257218a21d1bf8e9cd453b13f49c599b958f0c14067f8)로 확인하실수 있습니다.

**Comment by veldise** [comment]
b-iris.mobigen.com 에 배포되었기에 이슈 닫습니다.
