### ISSUE TITLE
시각화 / sankey chart가 제대로 그려지지 않음

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1843]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
노드와 그 연결선이 바르지 않은듯 합니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
<분석탬플릿 - sankey chart : 버그설명 으로 확인가능>

1. 관계형 -Sankey chart 선택
2. x축 +눌러 노드 3개로 늘림
3. Batting Table 사용
4. 전체시간
5. 왼쪽부터 순서대로 타자ID, 팀ID, 리그 ID
6. 필터링 리그 ID endswith "%L" AND 타자 ID endswith "%01"

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
![그림1](https://user-images.githubusercontent.com/36151180/72951110-a5a88c80-3dd0-11ea-8313-928f4a43422a.png)
매뉴얼에 나와있는 이 그림을 그리려고 했습니다. 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
<img width="1671" alt="스크린샷 2020-01-23 오전 11 15 01" src="https://user-images.githubusercontent.com/36151180/72951429-a7268480-3dd1-11ea-88f2-ba654a9251d7.png">

팀ID 부분이 오른쪽으로 밀려있는 듯하고, 리그ID 는 보이지않습니다.

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }
위에서 작성한 시각화 그래프를 검색으로 이동해서 확인해보면 아래와 같은 쿼리로 작성됩니다. 

`* | adv sankey count(*) SPLITROW PLAYERID,TEAMID,LGID FILTER TEAMID LIKE '%L' AND PLAYERID LIKE '%01'`

**Comment by veldise** [comment]
@joohj7 
매뉴얼에 있는 차트는, LGID 등 필터 조건을 많이 지정하여 결과 개수를 제한한 것입니다.
현재 버전에서는 노드 개수/차트 영역에 따라 노드의 크기를 정하는데
노드 개수가 매우 많으면 본문 스크린샷처럼 노드가 제대로 그려지지 않습니다.

개선이 필요한 사항은 맞습니다.

**Comment by veldise** [comment]
@joohj7 
아래와 같이 PLAYERID 개수를 줄이면 본문 이미지와 같이 그릴 수 있습니다. 업무에 참고하세요.

![image](https://user-images.githubusercontent.com/3411842/73225039-a8c7c200-41ae-11ea-929c-42fa5d377b6c.png)

**Comment by sunghoon** [comment]
해결된 이슈로 보고 닫습니다.
