### ISSUE TITLE
수원시 - 보고서_지도_마커_포인트(점) 시각화 기능 요청

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1844]
## 기능 요청 ##
수원시 주무관의 기능 요청입니다.

보고서 - 지도 - 시각화 - 마커 - 마커종류 : 포인트(점) 
해당 시각화에 대한 추가적인 기능 요청.

## 원하는 솔루션 설명 ##
  1. 포인트의 크기 조절 (실제 지도의 M / KM 단위로 원을 조절)
    - 예시로, 파출소 or 보안등의 데이터가 존재했을 때, 파출소의 보안 범위 / 보안등의 보안범위 등을 표현하길 원합니다.
  2. 포인트의 채우기 옵션 선택.
    - 현재는 포인트가 색상을 선택하여 100% 채워져 나타나는데, 채우기 옵션/투명도 조절 옵션을 요구하였습니다. 

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
![1](https://user-images.githubusercontent.com/8993205/72952325-d2f73980-3dd4-11ea-93c2-5ff73c30f93b.PNG)

위 스크린샷과 같이, 모든 원이 색으로 구별되어 채워져 있으며
크기 항목에 숫자 입력 부분에  M/KM 단위 + 채우기 옵션에 대한 기능 요구입니다

**Comment by veldise** [comment]
포인트의 크기로 특정 데이터 값(범위 크기)을 표현하거나, 포인트의 채우기 옵션 등은 마커에는 적절하지 않은 옵션이고, 데이터 시각화 유형에 '마커', '도형' 대신 '원형'을 추가해야 할 것으로 보입니다.

**Comment by veldise** [comment]
1번은 축적을 px 등으로 변환해야 하므로 기술조사가 필요합니다.
