### ISSUE TITLE
angora: query-analysis API 오류

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1845]
## 버그 설명 ##
adv 명령어를 query-analysis API로 분석(parse)할 경우 잘못된 결과가 반환됩니다.

## 내용
request:
```json
{"q":"* | adv sankey count(*) SPLITROW PLAYERID,TEAMID,LGID FILTER TEAMID LIKE '%L' AND PLAYERID LIKE '%01'"}
```
response:
```json
{
  "data": {
    "q": "*",
    "parameters": {
      "rows": [
        {
          "field": "PLAYERID"
        },
        {
          "field": "TEAMID"
        },
        {
          "field": "LGID"
        }
      ],
      "cells": [
        {
          "func": "count",
          "field": "*"
        }
      ],
      "filters": [
        "TEAMID LIKE '%L'",
        "AND",
        "PLAYERID LIKE '%01'"
      ],
      "sort": null
    },
    "operation": "sankey",
    "request": {
      "url": "/angora/adv-sankey",
      "method": "POST"
    }
  }
}
```

`filters`에 `"AND"`가 포함되어 있습니다.
최근 Angora 버전업에 따라 결과가 달라진 것 같은데, 아직 웹에서는 해당 버전에 맞게 호환 처리를 아직 하지 못한 상황이라, Angora 버전 롤백이 필요해보입니다.

웹 버전과 동작에 관계없이 Angora 패치를 하게 되면 기능이 정상 동작하지 않을 가능성이 큽니다.

**Comment by sunghoon** [comment]
@veldise UI 호환 처리를 위한 작업 소요 시간과 반영 목표 시점을 언제로 고려해야 하는지 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
AND, OR, IN, BETWEEN 등의 연산자를 설정하는 UI가 필요하므로 기획 혹은 UI설계가 필요하며,
설계 내용에 따라 작업 소요시간이 달라집니다.

단순히 `"AND"` 값을 무시하도록 처리한다면 금방 할 수 있습니다.

**Comment by sunghoon** [comment]
@veldise  네. 그러니 업무량을 산정해서 목표일을 알려주세요.

**Comment by seungfwani** [comment]
@veldise @sunghoon 
query-analysis api를 버전을 나누어 리턴하도록 수정하는 방안이 있습니다.
- 기존 버전(version=1) 일 경우 "AND" 는 무시 된 값 반환
  - 즉, `AND` 로만 이어지는 필터조건 나열 값 반환
    ```
    [
        "TEAMID LIKE '%L'",
        "PLAYERID LIKE '%01'"
    ],
    ```

- version=2 일 경우 모든 조건을 반환 ( `and`, `or`, `()` 가능)
  ```
    [
        "TEAMID LIKE '%L'",
        "AND",
        "PLAYERID LIKE '%01'",
        "OR",
        "A > 10",
    ],
  ```

**Comment by seungfwani** [comment]
query-analysis API 를 위의 코멘트와 같이 수정하였습니다.
기존 api를 이용하면 `and` 로만 연결되는 필터가 적용이됩니다.

version=2 에 대해서는 UI 개발에 맞춰 `and`, `or`, `()` 지원할 수 있도록 하겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 최종 상태를 확인해 주세요.

**Comment by seungfwani** [comment]
- /angora/query-analysis/adv?type=tree 사용시 결과
![Screen Shot 2020-09-22 at 10 54 20 AM](https://user-images.githubusercontent.com/46172579/93837656-fa830680-fcc1-11ea-9e9c-2a40719d1910.png)

- /angora/query-analysis/v2/adv?type=tree 사용시 결과
![Screen Shot 2020-09-22 at 10 55 22 AM](https://user-images.githubusercontent.com/46172579/93837697-20a8a680-fcc2-11ea-9af2-f3b3b5ef2260.png)
