### ISSUE TITLE
[KOTRA]간헐적오류

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1846]
![35ABAA67-8A06-428C-BAAD-2EA309A95107](https://user-images.githubusercontent.com/18297120/72961429-5ffdbb00-3df4-11ea-847e-38dfdcb9bf78.jpeg)
![9DCF3AB9-6104-4288-B8E8-F30CBFE79096](https://user-images.githubusercontent.com/18297120/72961430-60965180-3df4-11ea-9e54-a24ea3e8536a.jpeg)
![408A345F-DCA9-4A65-9D2B-8D02753E4DA0](https://user-images.githubusercontent.com/18297120/72961431-60965180-3df4-11ea-8b97-49c2eb81c308.jpeg)
![5CD84D7E-1B68-4817-BEE2-F741E299526C](https://user-images.githubusercontent.com/18297120/72961432-612ee800-3df4-11ea-8278-57816ad1a69f.jpeg)

위의 화면을 보시면
동일 화면의 각각의 콤포넌트가 번갈아 가며 오류를 발생시키고 있습니다. 
1분단위 갱신을 하는데 오류가 랜덤입니다. 

4개의 콤포넌트는 동일한 데이터모델의 서로 다른 칼럼을 참조합니다. 

확인 부탁드립니다.

**Comment by namjals** [comment]
sql 명령어를 사용할때 iris에서 얻어온 데이터 프레임을 angora라는 이름의 임시 테이블로 생성합니다. A 데이터 프레임을 angora라는 임시 테이블로 생성하고 쿼리를 수행하기전에 B라는 데이터 프레임을 angora 라는 임시테이블로 생성하여, 쿼리를 수행하다 발생한 문제입니다.
개선한 버전에 대해 배포 요청하겠습니다.

**Comment by namjals** [comment]
sql명령어 외에 stats에서 임시테이블을 생성하고 있었고, 수정, 배포하였습니다.

10회 이상 반복 시, 재현되지 않음.
![이슈](https://user-images.githubusercontent.com/22319132/74808779-01622900-532f-11ea-9481-923761062397.jpg)
