### ISSUE TITLE
시각화 / Sankey chart - 가중치 변수 추가시 시각화 차트 오류

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1849]
## 버그 설명 ##
IRIS 매뉴얼 작성중에 있습니다. 
Sankey chart 를 그렸을때는 잘 그려지다가 
가중치 변수를 추가하니 차트가 보이지 않거나, 오류가 납니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 분석탬플릿에서 'Sankey chart - 타자와 팀, 그리고 리그의 관계' 를 선택한다.
2. 실행 -> 정상확인
3. 가중치 변수에 '득점(R)' 추가 
4-1. 가중치 변수 옵션 summary '평균' & 상위 3개 등등 -> 오류
4-2. 가중치 변수 옵션 summary '개수' & 상위 3개 등등 -> 오류

## 예상한 행동 ##
가중치가 반영된 그래프로 그려지기를 바랍니다. 

## 스크린샷 ##
<가중치 반영전 그래프>
<img width="1387" alt="show_charts_23" src="https://user-images.githubusercontent.com/36151180/73228165-2264ad80-41b9-11ea-8aed-5f4024adb04e.png">

<가중치 반영후 그래프 1: 합계, 평균 등등>
<img width="1672" alt="스크린샷 2020-01-28 오전 10 19 29" src="https://user-images.githubusercontent.com/36151180/73228300-84bdae00-41b9-11ea-9d2d-e8c95169c55a.png">

- 전체 오류가 납니다. 

<가중치 반영후 그래프 2: 개수 >
<img width="1674" alt="스크린샷 2020-01-28 오전 10 19 13" src="https://user-images.githubusercontent.com/36151180/73228234-593ac380-41b9-11ea-9152-4dd29488914c.png">

- 상단에 오류가 있는듯 합니다.

**Comment by veldise** [comment]
아래와 같이 `REAL` 유형의 결과 데이터에 `null`이 있어서 발생하는 문제입니다.
일단 UI에서는 `null` 값을 `0`으로 처리하도록 예외 처리하겠습니다.

@anhm @namjals @seungfwani 
`null`이 반환되는 이유에 대해서 확인을 부탁드립니다.

검색 명령어:
```
model name = 'BATTING_TABLE' model_owner = manual | adv sankey sum(R) SPLITROW PLAYERID,TEAMID,LGID FILTER PLAYERID LIKE 'abbo%'
```
response data:
```js
{
  "fields": [
    { "name": "S_NODE_NAME", "type": "TEXT", "grouped": false },
    { "name": "T_NODE_NAME", "type": "TEXT", "grouped": false },
    { "name": "SOURCE_ID", "type": "TEXT", "grouped": false },
    { "name": "SOURCE", "type": "TEXT", "grouped": false },
    { "name": "TARGET_ID", "type": "TEXT", "grouped": false },
    { "name": "TARGET", "type": "TEXT", "grouped": false },
    { "name": "WEIGHT", "type": "REAL", "grouped": false }
  ],
  "results": [
    [ "PLAYERID", "TEAMID", "0", "abbotky01", "1", "PHI", 2.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotku01", "1", "OAK", 28.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotpa01", "1", "SEA", 1.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotda01", "1", "TL2", 0.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotji01", "1", "NYA", null ],
    [ "PLAYERID", "TEAMID", "0", "abbotpa01", "1", "PHI", 1.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotfr01", "1", "CLE", 39.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotku01", "1", "NYN", 22.0 ],
    [ "PLAYERID", "TEAMID", "0", "abbotji01", "1", "CAL", null ],
```

**Comment by veldise** [comment]
@seungfwani
확인해보니 가중치 결과값이 0일 경우도 문제가 됩니다.
단순히 `WEIGHT` 결과 값이 단순히 지정한 함수 연산 결과이면 안될 것 같습니다. 검토 바랍니다.

**Comment by veldise** [comment]
`null`, `0`인 노드간 연결선(link)을 제거한 경우:
![image](https://user-images.githubusercontent.com/3411842/73517995-7b924280-4440-11ea-9ccc-4a347adc307b.png)

`null`, `0`을 `1`로 처리한 경우:
![image](https://user-images.githubusercontent.com/3411842/73517980-6e755380-4440-11ea-8512-a98cbe85311b.png)

**Comment by seungfwani** [comment]
@veldise 
현재 모델의 sum(R) 값이 `0`, `null` 이 나오는 것은 데이터 자체의 문제로 보입니다. (0과 null의 의미가 같음)

----

만약 다른 데이터의 경우 0, null의 의미가 다를 수 있기 때문에 앙고라에서 일괄적으로 null을 처리하기 보다, 차트를 그리는 상황에서 null의 처리를 하는 것이 맞다고 생각됩니다.

앙고라에서는 수정 할 내용이 아닌것으로 판단됩니다.

**Comment by veldise** [comment]
@seungfwani 
잘 이해가 안 되는데 `sum(R)` 결과가 `null`인 경우가 어떤 경우인가요? TEXT 유형의 값이 섞인 경우인가요?

**Comment by joohj7** [comment]
@veldise  @seungfwani 현재 BATTING TABLE의 득점(R)에는 NULL 값이 들어있습니다. 이를 SUM 등으로 집계한 경우 NULL 이 생기는 듯 합니다.  
![Uploading 스크린샷 2020-01-31 오후 5.03.46.png…]()

**Comment by veldise** [comment]
@joohj7 
의견대로 null, 0을 1로 처리하도록 하겠습니다. 차주 목요일 정기 패치에 포함될 것입니다.
더 빨리 패치가 필요하시면 따로 연락해주시면 됩니다.

**Comment by veldise** [comment]
최종:
1. angora API 결과에서 `WEIGHT = null`인 레코드 제거
2. `WEIGHT < 0`은 `WEIGHT = 1`과 동일하게 처리

![image](https://user-images.githubusercontent.com/3411842/73525767-2dd30580-4453-11ea-9c10-6cb0533fe807.png)
