### ISSUE TITLE
관리 / 분석탬플릿 - 영어버전 그리드 깨짐

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1850]
## 버그 설명 ##
IRIS 매뉴얼 작성중 입니다. 
관리 / 분석탬플릿 - 영어버전 그리드가 깨져 보입니다. 
매뉴얼 작업중이라 분석탬플릿 영어버전 그리드 조정이 필요해 보입니다. 

## 재현하는 방법 ##
분석탬플릿에 들어가 영어버전으로 변경

## 예상한 행동 ##
필터부분부터 격자가 잘 맞기를 바랍니다. 

## 스크린샷 ##
<img width="1670" alt="스크린샷 2020-01-28 오전 11 16 20" src="https://user-images.githubusercontent.com/36151180/73230333-2ea03900-41c0-11ea-9c16-fce1e404613c.png">

**Comment by veldise** [comment]
영문 버전에서만 Classification 컬럼 크기를 100에서 128로 조정하겠습니다.
