### ISSUE TITLE
데이터 모델 검색시 SORTCOL 동작 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1851]
## 버그 설명 ##
데이터 모델로 검색을 하여 테이블에 표시할때 SORTCOL을 통해 컬럼 정렬을 변경하는 기능이 예전에는 정상적으로 동작을 했었는데 지금 확인해보니 정상적으로 동작을 안합니다..
처음에 오름차순으로 정렬을 하면 내림차순으로 변경해도 오름차순과 동일하게 결과가 표시됩니다.
그리고 이상하게 정렬되는 현상도 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
1. 초기 오름차순 정렬
![image](https://user-images.githubusercontent.com/7067615/73231640-395ccd00-41c4-11ea-89c8-c1807f12cac6.png)

2. 내림차순으로 변경
![image](https://user-images.githubusercontent.com/7067615/73231716-6d37f280-41c4-11ea-8692-17d35e74a71a.png)

3. 이상하게 정렬되는 스크린샷
![image](https://user-images.githubusercontent.com/7067615/73231590-1e8a5880-41c4-11ea-8c09-72a84d7f8405.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
현재 운영서버(100.180)에서는 아래 사진과 같이 sort가 잘 되는 것으로 확인됩니다.
사이트 혹은 쿼리의 확인이 필요합니다.

![image](https://user-images.githubusercontent.com/46172579/73317851-ee51c100-427a-11ea-85bd-d463556814d1.png)

**Comment by seungfwani** [comment]
UI에서 정렬을 선택 한 것이라면 앙고라와 다른 문제일 수 있습니다.

**Comment by seungfwani** [comment]
확인해본 결과로 앙고라의 문제는 아닌것으로 보입니다.
1,2 번 보고서의 경우 -> 결과 화면에서 정렬이 안되는 것으로 보입니다.
3 번의 대쉬보드상의 `주요국 환율` 부분은 앙고라 리턴 및 결과화면 모두 정상적으로 보입니다.
아래는 확인 결과입니다.

----

1-1. 쿼리와 응답 데이터의 결과 -> sortcol asc 순서대로 정상 리턴
```
"model name = '통합지표_Data_Global' start_date = 20000101000000 | sql "select LOC_NAME, STIME, DATA_VALUE, DATA_DATE from angora where 
DATA_TYPE = 'IMF_NGDPDPC'
and LOC_NAME in ('Korea','Luxembourg','Macao SAR','Switzerland','Norway','Ireland','Iceland','Qatar','Singapore','United States','Denmark')


 | pivot avg(DATA_VALUE) SPLITROW LOC_NAME SPLITCOL DATA_DATE SORTCOL ASC |rename LOC_NAME 국가"
```
![image](https://user-images.githubusercontent.com/46172579/73320107-ac784900-4281-11ea-98a0-83121e4c3758.png)

1-2. 보고서 결과 화면
![image](https://user-images.githubusercontent.com/46172579/73320137-b7cb7480-4281-11ea-8eef-5fef97884d29.png)

2-1. 쿼리와 응답 데이터의 결과 -> sortcol desc 순서대로 정상 리턴
```
"model name = '통합지표_Data_Global' start_date = 20000101000000 | sql "select LOC_NAME, STIME, DATA_VALUE, DATA_DATE from angora where 
DATA_TYPE = 'IMF_NGDPDPC'
and LOC_NAME in ('Korea','Luxembourg','Macao SAR','Switzerland','Norway','Ireland','Iceland','Qatar','Singapore','United States','Denmark')


 | pivot avg(DATA_VALUE) SPLITROW LOC_NAME SPLITCOL DATA_DATE SORTCOL DESC |rename LOC_NAME 국가"
```
![image](https://user-images.githubusercontent.com/46172579/73320237-f8c38900-4281-11ea-9cc0-4c9e010414a5.png)

2-2. 보고서 결과 화면
![image](https://user-images.githubusercontent.com/46172579/73320257-0d078600-4282-11ea-8e47-a59fffd8da87.png)


3-1. 쿼리와 응답 데이터의 결과 -> sortcol desc 순서대로 정상 리턴
```
model name = '통합지표_Data_Global' start_date = 20200112000000 end_date = 20200129100734 DATA_TYPE='EXCHANGE' |   sql "select DATA_DATE,  DATA_TYPE, LOC_CODE, LOC_NAME AS 
Exchange_Rate , DATA_VALUE from angora " | where DATA_TYPE = 'EXCHANGE' AND LOC_CODE in ('1', '2', '3', '4') | sort -STIME | head 20 | pivot sum(DATA_VALUE) SPLITROW LOC_CODE, Exchange_Rate SPLITCOL DATA_DATE SORTCOL DESC  | sort +LOC_CODE | fields -LOC_CODE | rename Exchange_Rate 국가/원화
```
![image](https://user-images.githubusercontent.com/46172579/73319498-ecd6c780-427f-11ea-9986-a0c414a68a33.png)

3-2. UI의 대쉬보드상의 `주요국 환율` 부분 입니다. -> 정렬문제는 없는것으로 확인
![image](https://user-images.githubusercontent.com/46172579/73319515-f4966c00-427f-11ea-91f9-c784fc88b482.png)
