### ISSUE TITLE
보고서 /  생성한 보고서가 표시되지 않음

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1853]
## 버그 설명 ##
생성한 보고서가 [보기] 또는 목록에서 클릭해서 보고서를 실행시킬 경우 나타난 새 창에서 차트 컴퍼넌트가 작동하지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
계정 "manual"에서 생성한 "워드클라우드_튜토리얼" 참조

## 예상한 행동 ##
다른 보고서들처럼 차트가 제대로 실행되어 표시되어야 함

## 스크린샷 ##
1) 생성 창에서의 "워드클라우드_튜토리얼" 보고서
![image](https://user-images.githubusercontent.com/35832986/73237837-340a7d00-41da-11ea-8472-6b075636f331.png)

2) [보기] 버튼을 눌러서 나타난 새창의 화면
![image](https://user-images.githubusercontent.com/35832986/73237861-44225c80-41da-11ea-867f-62fd889ac8e8.png)

3) [보고서] 목록에서 "워드클라우드_튜토리얼"을 클릭해서 나타는 화면
![image](https://user-images.githubusercontent.com/35832986/73237889-5bf9e080-41da-11ea-8af3-bdc9f4146188.png)

**Comment by veldise** [comment]
@ssm0219
작년 말에 변수와 이벤트 트리거 설정 기능을 추가하면서,
각 객체가 별다른 설정 없이도 자동으로 실행하던 것을 설정을 해야만 자동 실행하도록 변경했습니다.

이전과 동일하게 동작시키려면 아래와 같이 데이터 탭 > 데이터 실행방법 설정 에서
"자동 실행" 설정을 체크해줘야 합니다.

![image](https://user-images.githubusercontent.com/3411842/73238065-ee9a7f80-41da-11ea-8941-deff92389a55.png)

**Comment by ssm0219** [comment]
@veldise 해결되었습니다. 
감사합니다.
