### ISSUE TITLE
분석탬플릿 / 히트맵 - 불러오기 오류

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1854]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
분석 탬플릿 히트맵에서 저장한 파일이 불러와지지 않습니다.  확인 부탁드립니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 분석탬플릿 : '히트맵 - 버그 발생' 확인 
2. 히트맵 의 for-motion2 (Table) 클릭
3. x축 년도(year), y축 도시명(country), 값: 사망비율의 수(deaths)
4. 필터 : year>= 2000 & country startswith C 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
<img width="1672" alt="스크린샷 2020-01-28 오후 3 16 18" src="https://user-images.githubusercontent.com/36151180/73240163-771c1e80-41e1-11ea-8acf-bc6b41807ae5.png">

## 로그 ##

angora error: <class 'pyspark.sql.utils.AnalysisException'> ("cannot resolve '`AND`' given input columns: [population, country, births, deaths, year]; line 1 pos 24;\n'Filter ((country#671713 LIKE C% && 'AND) && (year#671712 >= 2000))\n+- Project [cast(year#671703 as string) AS year#671712, cast(country#671702 as string) AS country#671713, cast(deaths#671704 as double) AS deaths#671714, cast(births#671705 as double) AS births#671715, cast(population#671706 as int) AS population#671716]\n +- Relation[country#671702,year#671703,deaths#671704,births#671705,population#671706] csv\n",)

**Comment by veldise** [comment]
#1845 로 인한 에러입니다.

![image](https://user-images.githubusercontent.com/3411842/73240498-733ccc00-41e2-11ea-9558-cfc71a795d91.png)

**Comment by seungfwani** [comment]
정상 동작하도록 수정되어 닫겠습니다.
![image](https://user-images.githubusercontent.com/46172579/73409321-443d6c00-4342-11ea-87e6-b720df5a7d49.png)
