### ISSUE TITLE
[수원시] 보고서 - 지도 group by 질문

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1856]
## 기능 요청 ##
보고서 - 지도 에서 데이터유형 (DSMS)를 통한 지도데이터 표시는 했습니다.(시각화-마커)
--> 여기서 group by 를 통한 표시를 하고 싶습니다.

 시각화 - 클러스터 맵에서는 지도데이터를 선택한 이후 Group by를 통해 지도상에 구분하여 표시를 할 수 있는데, 보고서-지도에선 해당 기능을 어떻게 사용하는지 질문드립니다. 

## 원하는 솔루션 설명 ##
보고서 - 지도 에서 group by 를 통한 표시 방법 질문

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@readmehong 
Studio 에서는 데이터 브라우저 - 시각화 - 클러스터맵에 해당하는 기능이 없습니다.
관련 기능을 추가로 개발해야 합니다.
