### ISSUE TITLE
시각화 / 이상치 - max 데이터가 chart에서 보이지 않습니다. 

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1857]
## 버그 설명 ##
IRIS 매뉴얼 작성 중입니다. 
시각화 / 이상치 에서 사용한 컬럼의 max 포인트 값이 시계열 차트에서 
나타나야 하는데, 생략된 것 같아 보입니다. 
max가 시각화 차트에서 보이는게 맞는것 같은데 확인 부탁 드립니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 시각화 - 이상치 선택 
2. 테이블 Batting Table의 컬럼 득점(R) 선택후 실행
3. 기술통계량 및 이상치에서는 Max값이 192가 존재하는데, 
 히스토그램이나 시계열분포 차트상에서는 보이지 않음

## 예상한 행동 ##
히스토그램과 시계열분포 차트에서 max값이 보여야 할 것 같습니다.

## 스크린샷 ##
<img width="1675" alt="스크린샷 2020-01-28 오후 4 42 45" src="https://user-images.githubusercontent.com/36151180/73244567-94ef8080-41ed-11ea-8bed-6fe09852bdd6.png">

**Comment by veldise** [comment]
@joohj7 
히스토그램의 경우, x축의 카테고리 항목이 많아서 없는 것처럼 보이는 것이고
드래그&드랍으로 확대를 하면 아래와 같이 존재하는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/73246859-fe25c280-41f2-11ea-8938-2bbc3e24c638.png)

시계열 분포의 경우, UI에서 데이터 요청시 크기 제한을 걸지 않아 Angora API가 레코드를
500개만 반환하는 것 같습니다. 최대 개수인 `1,000,000`(백만) 으로 크기 제한을 걸도록 하겠습니다.
이 경우 여전히 전체 데이터는 아니므로 MAX값은 나타나지 않을 수 있습니다.
BATTING의 경우에는 총 레코드 개수가 약 10만개 이므로 문제는 없을 것입니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/73502016-fc364c00-440a-11ea-9993-26ec47fb75c3.png)
