### ISSUE TITLE
보고서 / 히트맵 - y축을 설정 하지 못합니다. 

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1861]
## 버그 설명 ##
IRIS 튜토리얼 작성중입니다. 
보고서 / 히트맵 - y축을 설정 하지 못합니다. 
시각화와 다르게 보고서에서는 y축을 설정할 수 없고, 모든 y축의 그림이 그려집니다. 
원하는 그림을 그릴수가 없습니다. 
확인 부탁드립니다. 

## 스크린샷 ##
<의도했던 그림 : 시각화 - 히트맵>
<img width="1042" alt="스크린샷 2020-01-29 오후 5 56 16" src="https://user-images.githubusercontent.com/36151180/73342037-2845b600-42c1-11ea-8ebd-2c1275f640b8.png">

* 데이터 모델: for-motion2 (전체시간)
* x축: 날짜(year) / y축 : 도시명(country) / 값: 사망비율(deaths) 의 합계
* 필터링: * | WHERE country LIKE "C%"

<보고서 : 히트맵>
<img width="1269" alt="스크린샷 2020-01-29 오후 6 10 39" src="https://user-images.githubusercontent.com/36151180/73342847-bff7d400-42c2-11ea-9618-8af53e9f4e4b.png">

<img width="493" alt="스크린샷 2020-01-29 오후 6 16 02" src="https://user-images.githubusercontent.com/36151180/73343187-7bb90380-42c3-11ea-8c12-0e016b678cdf.png">

* 데이터 모델: for-motion2 (전체시간)
* x축: 날짜(year) /  값: 사망비율(deaths) (집계가 아님) 
-> y축을 설정할 수 없음. 현재 y축은 데이터의 모든 컬럼이 주어짐
-> 값의 경우도 집계값이 아님.
* 필터링: * | WHERE country LIKE "C%"

**Comment by veldise** [comment]
1. 히트맵은 집계된 데이터로만 그려야 정상적으로 그려집니다.
2. for-motion2 데이터 자체는 집계 데이터가 아닙니다.

Analyzer 시각화 와 동일한 히트맵을 그리려면 보고서 검색어에 다음과 같이 입력해야 합니다.
```
*
| where  country LIKE 'C%'
| adv heatmap sum(deaths) SPLITROW 'date_group("year", "1y")' SPLITCOL country
```

Analyzer 시각화에서 히트맵을 그린 뒤, 분석 템플릿으로 저장하여 보고서에서 불러오거나
'검색으로 이동' 기능을 사용하시길 바랍니다.

**Comment by veldise** [comment]
더불어 히트맵은 아래와 같이 컬럼명을 Y축으로 매핑하고 있어서 Y축을 선택할 수 없게 하였습니다.
한계점은 맞지만 개선하려면 Studio 구조 자체를 재검토해야합니다.

![image](https://user-images.githubusercontent.com/3411842/78614233-fcd6dd00-78a8-11ea-8a3c-9e84484dd35b.png)
