### ISSUE TITLE
[NMS+]studio combo 콤포넌트 필드 설정 오류

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1862]
## 버그 설명 ##
기존에 되던 기능인데, 갑자기 동작하지 않습니다. ( 아마도 SKBB 에 1/13일 IRIS 웹 패치후 이런건지는 잘모르겠습니다. )

콤보 컴포넌트에 코드값을 세팅하고, 전체를 조회하기위해 다음과 같이 설정하였습니다.
- 콤보의 쿼리
![iris7](https://user-images.githubusercontent.com/5468183/73348351-9a6fc800-42cc-11ea-9038-c4882ef7e524.PNG)

![iris1](https://user-images.githubusercontent.com/5468183/73345644-c6d51580-42c7-11ea-86d9-3d2fa15abd84.PNG)

![iris2](https://user-images.githubusercontent.com/5468183/73345684-d5bbc800-42c7-11ea-9fb0-1a1b906f4efd.PNG)

- 값으로 설정된 필드를 IDC_CD 로 설정하였고
전체를 조회하기 위해  IDC_CD = NULL, IDC_NAME = '전체' 로 쿼리 넣음

![iris3](https://user-images.githubusercontent.com/5468183/73347597-37c9fc80-42cb-11ea-8da8-4aea8f9cca13.PNG)

- "전체" 를 선택하면 IDC_CD 코드가 아닌 IDC_NAME 이 combo_idc 변수로 세팅됩니다.

그리드 조회의 하단쿼리는 위부분은 생략하고  조건부분이 다음과 같습니다.

WHERE 1=1 {%if combo_idc%} AND ( A.IDC_CD=${combo_idc}) {% endif %}

- "전체"선택시 에러나는 경우
![iris5](https://user-images.githubusercontent.com/5468183/73347819-97c0a300-42cb-11ea-8162-c5616174bb19.PNG)

- 다른 조건 선택시 쿼리

![iris6](https://user-images.githubusercontent.com/5468183/73348198-567cc300-42cc-11ea-93b3-12e6dcfa148e.PNG)

![iris4](https://user-images.githubusercontent.com/5468183/73347611-3c8eb080-42cb-11ea-9c93-ca7b993a17c5.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
Combo-box, Check&Radio 등 목록 형태를 가지는 객체의 데이터 설정 방법을 "사용자 정의"로 했을 때
"항목"은 입력하고 "값"은 입력하지 않은 경우, "값"을 "항목" 입력값으로 처리합니다.
다시 말해 "값"은 일종의 선택적(Optinal) 입력값입니다.

이에 따라 아래 2개는 동일하게 처리됩니다.
![image](https://user-images.githubusercontent.com/3411842/73408504-caa47e80-433f-11ea-9205-051098da3d25.png)

이전에 위와같이 동작하지 않았던 것은 설계대로 구현되지 않은 버그로, 1월 2일자 패치로 수정된 내용입니다.
https://github.com/mobigen/IRIS-BigData-Platform/wiki/2020-01-02---Patch

이 부분이 사용상에 어려움을 일으킨다면 코멘트로 의견을 남겨주시기 바랍니다. 팀장님께 상의드려보겠습니다.

**Comment by jjinylee** [comment]
1.사용자 정의시는 이해했습니다.
그렇다면, 아래와 같이 데이터설정방법='데이터' 로 선택하여 처리시도 위의 경우와 동일하게 처리되는건가요?
즉, 데이터설정방법에 상관없이 값이 NULL or 공백 이면 무조건 항목에 해당하는 값으로 처리되는건가요?

![iris8](https://user-images.githubusercontent.com/5468183/73410131-adbe7a00-4344-11ea-978c-36c20fe009c4.PNG)

2. 처리방법이 동일하다면 , combo 값으로 "ALL", "전체" 를 처리할수 있는 방법에 대한 가이드 부탁드립니다.

**Comment by veldise** [comment]
@jjinylee 
1.
데이터 설정 방법이 "데이터" 일 때는 아래 설정을 따르고, 공백이어도 항목 값을 따르지 않습니다.
이 부분은 버그가 있을지도 모르니 확인해보겠습니다.

![image](https://user-images.githubusercontent.com/3411842/73410522-d85d0280-4345-11ea-993c-23c8b08191d6.png)

2.
'전체'로 선택한 값이 SQL select 구문의 where 절에 들어간다면, `1=1`과 같은 방식으로 처리할 수 있지 않을까 싶습니다.

**Comment by jjinylee** [comment]
네~ "데이터" 일경우 동작 확인부탁드립니다
제가 쓴 위의 내용 및 캡처는 다 "데이터" 일 경우입니다.

"데이터" 로 설정하여 일부러 "전체" 조회를 위해
콤보 쿼리를  아래와 같이 만들었고 기존에 정상적으로 동작하다가 1/13일 SKBB 패치이후 동작하지 않습니다.
----------------------------------------------------
SELECT NULL AS IDC_CD, '전체' AS IDC_NAME
FROM DUAL
UNION ALL
SELECT IDC_CD, IDC_NAME
FROM CODE_IDC
----------------------------------------------------

- 그리드의 데이터 쿼리 조회

SELECT ~~~~ 생략
WHERE 1=1 {%if combo_idc%} AND ( A.IDC_CD=${combo_idc}) {% endif %}

**Comment by veldise** [comment]
@jjinylee 
죄송합니다. "사용자 정의"의 경우로 제가 착각했습니다.
버그로 생각되며 조속히 처리하도록 하겠습니다.

**Comment by jjinylee** [comment]
앗. 죄송까진 안하셔도 됩니다 ^^;;
어제 하루종일 테스트해보고 docker log 를 봐도 정확히 모르겠어서... 
아무래도 패치영향인듯 싶어 남겼는데 그나마 원인을 알게되어 안심이네요. ㅜㅜ
그럼 처리부탁드립니다. 감사합니다~

**Comment by swish1995** [comment]
@jjinylee @veldise 
해당 버그는 수정및 PR 대기 중이며 현재 상태로 사용할수 있는 정보를 추가로 알려드립니다.

```
SELECT 'ALL' AS IDC_CD, '전체' AS IDC_NAME
~~
```

```
WHERE 1=1 
{% if combo_idc !== 'ALL' %} 
AND ( A.IDC_CD=${combo_idc})
{% endif %}
```

**Comment by jjinylee** [comment]
이거 close 되었는데, 패치하여 배포된거 맞나요?

저희가 어제 (2/17일) 현재 BIRIS 기준의 최신버전으로 패치하였습니다.

 제가 위에 적었던대로 "사용자 정의" 가 아닌 경우에 

"값" 필드가 공백(NULL) 인경우, "값" 필드에 보이는 필드값이 세팅됩니다.

위의 증상과 동일합니다.
확인후 조치바랍니다.

처리되지않았다면, 처리 일정부터 알려주시고, 완료/패치후 test 화면을 남겨주세요

**Comment by swish1995** [comment]
biris 에 `issue_1862` 이름으로 리포트를 생성해 두었습니다.
혹시 이 현상과 다른 내용인지 확인 부탁드립니다.

area 의 검색어
```
SELECT IDC_CD,  IDC_NAME
FROM CODE_IDC
WHERE 1=1  
{% if combo_1 %} 
AND ( IDC_CD=${combo_1})
{% endif %}
```

특정 idc 선택
<img width="1023" alt="스크린샷 2020-02-18 오후 2 43 51" src="https://user-images.githubusercontent.com/49141403/74707424-27b79400-525d-11ea-8d10-0add0a9ca2a0.png">

전체(NULL) 선택
<img width="1023" alt="스크린샷 2020-02-18 오후 2 44 07" src="https://user-images.githubusercontent.com/49141403/74707429-2ab28480-525d-11ea-8996-31fa5a6408ac.png">

**Comment by jjinylee** [comment]
디폴트 값="전체" 를 넣으면 해당현상이 발생하는거같습니다.


![iris에러](https://user-images.githubusercontent.com/5468183/74711436-533f7c00-5267-11ea-8b67-bb3072bbc94b.PNG)

![iris에러2](https://user-images.githubusercontent.com/5468183/74711449-58043000-5267-11ea-9deb-cf7cb212a4f9.PNG)

**Comment by swish1995** [comment]
@veldise 
해당 오류는 확인하였습니다.

**Comment by veldise** [comment]
@jjinylee 
issue_1862 보고서로 해당 문제 해결됨을 확인하여 닫습니다.
