### ISSUE TITLE
교통빅데이터플랫폼 / 테이블 스페이스 사용율 / 테이블 Size 정보 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1863]
## 버그 설명 ##
테이블 스페이스(사용율 조회) 화면의 내용과 테이블 스페이스(사용율 현황) 정보에 표기되는 테이블크기 정보가 다르게 표현되고 있습니다.

확인 요청 드립니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. https://180.148.181.193/ 접속

## 예상한 행동 ##
각 화면의 테이블 크기가 동일

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/73408231-e5c2be80-433e-11ea-9b1e-b8d38981d9eb.png)

**Comment by veldise** [comment]
본사 운영서버(b-iris.mobigen.com)의 `EVA.SYSLOG`의 경우입니다.

화면상:
![image](https://user-images.githubusercontent.com/3411842/73409475-be6df080-4342-11ea-82f6-3a46783ef419.png)

![image](https://user-images.githubusercontent.com/3411842/73409499-d47bb100-4342-11ea-92a5-d53ce0180b73.png)

각각의 화면을 통해 웹서버에서 수행하는 IRIS-DB dot command 는 아래와 같습니다.
```
.statistics table --stime 20200123000000 --etime 20200130235959 -r 60 --summary --table EVA.SYSLOG --get-all

.table size --summary
```

각 명령어 결과는 다음과 같습니다. (일부만)
```

iplus> .statistics table --stime 20200129000000 --etime 20200130235959 -r 60 --summary --table EVA.SYSLOG --get-all
Ret : +OK Success


 UPDATE_TIME       NODE_ID    DATABASE_NAME    TABLE_NAME    TABLE_SIZE      NUM_OF_FILE    TABLE_SIZE_RAM    NUM_OF_FILE_RAM
================================================================================================================================
... 중략 ...

 20200130070000    -1         -                -             621890650112    11878          121831424         5
 20200130080000    -1         -                -             621957991521    11878          95861047          5
 20200130090000    -1         -                -             622007027611    11879          85357052          5
================================================================================================================================

34 row in set

1.3717 sec
```
```

iplus> .table size --summary
Ret : +OK Success


 NODE_ID    DB_NAME       TABLE_NAME                          SIZE          FNUM    SIZE_RAM    FNUM_RAM    UPDATETIME
=============================================================================================================================
... 중략 ...
 -          EVA           SYSLOG__SAMPLING                    28672         1       0           0           20210515094000
... 중략 ...
 -    EVA         SYSLOG                                  114694225920    2262     30359552     1     20210515094000
... 중략 ...
=============================================================================================================================

530 row in set

1.9145 sec
```

@anhm 
확인 부탁드립니다. 명령어를 잘못 사용한 것이라면 수정하겠습니다.

**Comment by anhm** [comment]
실제 서버에 접속하여 실제 디스크의 사용량을 확인해본 결과 약 18.5T 를 사용하는 것으로 파악되고 있습니다.

원인을 파악해본 결과 서버시간 동기화 이슈로 파악 됩니다.
master: 2020. 02. 05. (수) 13:34:16 KST
data01: 2020. 02. 05. (수) 13:34:16 KST
data02:2020. 02. 05. (수) 13:34:16 KST
data03:2020. 02. 05. (수) 13:34:16 KST
data04:2020. 02. 05. (수) 22:31:07 KST
data05:2020. 02. 05. (수) 13:34:16 KST

위와 같이 동시간대를 확인해본 결과 4번 데이터 노드의 시간에 문제가 있는것이 파악 됬습니다.

수집된 시간을 기준으로 10분단위로 계산이 이루어 지고 그중 가장 최신시간을 보여주게 되어 있는데,
특정 노드가 22시를 가르키다 보니, 해당 노드의 사용량만 표시되는 문제가 발생한 것입니다.

해당 이슈는 서버의 시간을 변경하면 될것 같습니다.


내용을 기술연구 운영팀쪽으로 전달하여 시간설정을 맞춘후 UI상에서 다시한번 확인해 보도록 하겠습니다.

**Comment by anhm** [comment]
웹 화면에서 정상적으로 표시 되는 것을 확인했습니다.
