### ISSUE TITLE
교통빅데이터 플랫폼 /  로고 이미지 변경 필요

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1864]
## 버그 설명 ##
교통빅데이터 플랫폼의 IRIS Analyzer에 대해 로그 이미지 변경 필요

로고 이미지 관련해서는 별도로 연락 드리겠습니다.

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/4444717/73408667-54544c00-4340-11ea-8584-bda81085a05a.png)

![image](https://user-images.githubusercontent.com/4444717/73410023-58826880-4344-11ea-9315-e184728e578b.png)

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
해당 이슈는 사이트 커스터마이징 사항 입니다.
아래 내용 확인 후에 필요한 내용 전달 해주시면 처리 하겠습니다 ~
**[IRIS Web Customize 가이드](https://github.com/mobigen/IRIS-BigData-Platform/wiki/IRIS-Web-Customize-%EA%B0%80%EC%9D%B4%EB%93%9C)**
