### ISSUE TITLE
보고서에서 날짜/시간 선택 콤포넌트에서 설정한 조건이 데이터 테이블에 전달되지 않습니다.

### ISSUE THREAD

**Issue by krjwpark** [mobigen/IRIS-BigData-Platform#1865]
## 버그 설명 ##
보고서의 날짜/시간 선택 기능에서 설정한 조건이 데이터 테이블에 전달되지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 데이터 브라우저> 관리 > 보고서  --> 새 보고서 
2. 차트 콤포넌트 클릭> 시각화옵션:테이블, 데이터모델: WEATHER, 시간 설정: 전체시간 >실행
3. 날짜/시간 선택 콤포넌트 삽입, 날짜/시간 유형 선택: 날짜, 시각화 옵션>달력표시날짜설정>사용체크, 시작날짜:2007/01/01, 종료날짜: 현재날짜 
4. 테이블 클릭> 검색어: * | where DATE < '${date_time_picker_1}'
5. 트리거 설정> 3의 날짜/시간 박스 선택> 실행
6. 날짜/시간 박스에서 2007/01/04 선택

## 예상한 행동 ##
테이블에서 2007/01/01~2007/01/04 까지의 데이터만 도출됨.
## 스크린샷 ##
![image](https://user-images.githubusercontent.com/37128240/73412381-caaa7b80-434b-11ea-93e7-00b35823457f.png)

## 기타 ##
검색어 미리보기 에서  * | where DATE < '2007/01/04'   으로 보이는 것으로 보아 해당 콤포넌트가 전달하는 날짜의 Format이 아이리스 테이블에 설정된 하이픈 형태가 아닌 것으로 추정됨.

**Comment by sunghoon** [comment]
날짜 컴포넌터의 속성 정보에서 시간정보의 Format을 지정할 수 있습니다.

![스크린샷 2020-11-03 오후 4 35 47](https://user-images.githubusercontent.com/512653/97959395-a1df7700-1df2-11eb-984b-17dab07cb13d.png)
