### ISSUE TITLE
[검색] external 명령어인 fill_zero 에러 발생 : angora3 적용후 발생한 에러

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1867]
## 버그 설명 ##
angora2 에서 정상 동작한 external 명령어인 fill_zero 에서 에러 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. root 계정 분석탬플릿  fill_zero_에러_20200203

<img width="426" alt="스크린샷 2020-02-03 오후 3 41 11" src="https://user-images.githubusercontent.com/5126497/73631739-3a4a9e80-469d-11ea-96b0-5f293d7ce24b.png">

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by namjals** [comment]
pandas에서 string이 아닌 컬럼에 대해 .str 속성을 사용할 때, 먼저 astype(str)로 형변환이 필요합니다.
ex)
pd_df['TMP_GRP_KEY_COL'] = pd_df[group_key_list.pop(0)].**str**.cat(pd_df[group_key_list.pop(0)], sep=",")
-> 
pd_df['TMP_GRP_KEY_COL'] = pd_df[group_key_list.pop(0)].**astype(str).str**.cat(pd_df[group_key_list.pop(0)], sep=",")

참조
https://stackoverflow.com/questions/52065909/attributeerror-can-only-use-str-accessor-with-string-values-which-use-np-obje/52065957

**Comment by namjals** [comment]
@seoryjj 
external에 외부 명령어를 업로드할때, 파일별로 indent를 통일시켜야 합니다. (space 4개 혹은 tab)
python2에서 파일을 import하는 라이브러리(imp)는 통일이 안되도 import를 시켜주었는데 python3에서는 에러입니다.
