### ISSUE TITLE
[NMS+]studio 보고서 작성 기능(SKB 고객 요청사항)

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1869]
## 기능 요청 ##
 - 컴포넌트 Copy /past 기능 ( 컴포넌트 cp/pt 가 되면 정말 보고서 작성 시간이 줄어들거같습니다. )
 - 컴포넌트 선택시 영역으로 ( Drag & drop 으로) 컴포넌트 선택이 안됨
 -  컴포넌트 multi 선택이 안됨 ( shift / 영역 선택등의)
 - Ctrl + Z 기능 
   컴포넌트 이동에 대한 취소 기능이 없어서 불편(현재는 텍스트 입력 취소만 되는 듯)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
해당 이슈에 대한 기능이 어느 정도 개발/배포 되어 닫습니다. 
추가 기능이 필요하다면 새 이슈로 등록해 주세요.
