### ISSUE TITLE
[데이터모델] 에서 HDFS 로부터 생성시 HDFS 브라우저가 뜨지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1870]
## 버그 설명 ##
 HDFS에 저장된 파일로부터  **데이터모델** 메뉴로 데이터 모델을 생성하려고 합니디.

그런데 HDFS 브라우저 팝업창이 계속 로딩중으로 나옵니다.

<img width="663" alt="스크린샷 2020-02-04 오전 11 04 44" src="https://user-images.githubusercontent.com/5126497/73707580-56068100-473f-11ea-83eb-aa5f0eb4dd52.png">

<img width="985" alt="스크린샷 2020-02-04 오전 11 09 26" src="https://user-images.githubusercontent.com/5126497/73707573-4e46dc80-473f-11ea-92ce-da671607234b.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
'연결 정보' 기능이 추가되면서 데이터 모델을 생성할 때 항상 '연결 정보 유형'과 '연결 정보'를 선택해야 합니다.
위 경우는 '연결 정보 유형'은 HDFS로 선택했으나 '연결 정보'를 선택하지 않은 상태에서
경로 선택에 해당하는 '찾아보기' 버튼이 클릭 가능하면서 발생하는 문제입니다.

'연결 정보'를 선택하지 않으면 '찾아보기' 버튼을 클릭하지 않도록 수정하겠습니다.
