### ISSUE TITLE
[검색] 메뉴에서 결과를 '내보내기' 하면 결과 파일에서 0, false  의 값이 빈칸으로 저장됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1871]
## 버그 설명 ##
검색메뉴에서 실행 후 결과에서 0 과 false 등의 레코드가 있는 경우 내보내기 하면 파일에서 전부 빈칸으로 저장됩니다.

<img width="1277" alt="스크린샷 2020-02-04 오후 1 16 28" src="https://user-images.githubusercontent.com/5126497/73713574-45f79d00-4751-11ea-81a0-a8e86abcd720.png">

<img width="613" alt="스크린샷 2020-02-04 오후 1 17 24" src="https://user-images.githubusercontent.com/5126497/73713576-47c16080-4751-11ea-95e1-12bddc42f60f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 분석탬플릿  anomalies_err_20200203  실행
2. 결과 확인 후 내보내기 시 tvc 로 저장하여 localPC 에 내보내기
3. 파일 확인

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
POST request:
```js
{ q: 'model name = \'syslog\' model_owner = eva start_date = 20191210090000 end_date = 20191210120000 LEVEL!=\'info\' |  stats  COUNT(*)  as CNT  by  date_group(DATETIME, "10M") , HOST  | sort +dategroup | fill_zero freq=600 stime=20191210090000  etime=20191210120000  time_column=dategroup group_key=HOST value=CNT |   anomalies dategroup  CNT  by=HOST',
     size: 10,
     save: false }
```
GET response:
```
dategroup,HOST,CNT,TMP_GRP_KEY_COL,upper,lower,anomaly
2019-12-10 09:00:00,gcs6,176.0,gcs6,226.0,126,
2019-12-10 09:10:00,gcs6,177.0,gcs6,226.0,126,
2019-12-10 09:20:00,gcs6,174.0,gcs6,226.0,125,
2019-12-10 09:30:00,gcs6,174.0,gcs6,225.0,125,
2019-12-10 09:40:00,gcs6,174.0,gcs6,225.0,125,
2019-12-10 09:50:00,gcs6,177.0,gcs6,225.0,125,
2019-12-10 10:00:00,gcs6,176.0,gcs6,225.0,125,
2019-12-10 10:10:00,gcs6,174.0,gcs6,225.0,125,
2019-12-10 10:20:00,gcs6,177.0,gcs6,225.0,125,
2019-12-10 10:30:00,gcs6,174.0,gcs6,225.0,125,
```

**Comment by seungfwani** [comment]
결과를 스트링으로 변환하는 로직에 문제가 있어 수정하였습니다.

운영서버 배포 후 확인 하도록 하겠습니다.

**Comment by seungfwani** [comment]
운영서버 배포완료 되었습니다.
![image](https://user-images.githubusercontent.com/46172579/73919675-52bdf180-4907-11ea-8d94-cd03ba009fc1.png)
