### ISSUE TITLE
[데이터모델] 에서 IRIS  에서 새모델 생성 시 테이블목록이 뜨지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1872]
## 버그 설명 ##
데이터모델 메뉴에서 IRIS  에서 대상 데이터 선택 시 테이블목록이 뜨지 않습니다.
대상 데이터 드랍박스를 눌러도 변화가 없습니다.

<img width="666" alt="스크린샷 2020-02-04 오후 3 00 37" src="https://user-images.githubusercontent.com/5126497/73718235-4e56d480-475f-11ea-889e-f6dc9a852019.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
3번 째  새 모델 생성 창을 닫고 다시 시작하니 테이블이 보입니다. 
root 계정이라 테이블목록 가져오는 게 오래 걸려서 그런 건가요?

**Comment by seungfwani** [comment]
해당 내용은 저도 경험해 본 적이 있습니다.
그 당시 확인 하였을 때 앙고라의 테이블 목록 가져오는 것이 느린것은 아니였습니다.

저는 당시 해결 방법으로, `chrome 설정 -> 고급 -> 인터넷 사용 기록 삭제 -> 캐시삭제` 를 통해서 캐시를 지운 후 실행하여 해결하였습니다.

**Comment by seungfwani** [comment]
드랍다운 리스트를 눌렀을때 비슷한 현상이 있어 공유드립니다.
- `대상 데이터` 를 클릭 하였을 때 (노란색 부분의 삼각형이 위(▲)로 간 상태 :: 누르지 않으면 ▼ 상태)
  - response를 보면 테이블 리스트는 받아온 상태(앙고라는 테이블 리스트를 반환한 상태)
![image](https://user-images.githubusercontent.com/46172579/74213028-8ff4fb80-4cda-11ea-8e48-7a9f350abdb5.png)

- 몇 초 가량 뒤에 다시 클릭해보면 리스트가 보입니다.
![image](https://user-images.githubusercontent.com/46172579/74213148-41942c80-4cdb-11ea-826d-0199a404125d.png)

**Comment by sunghoon** [comment]
이슈가 해결된 것으로 보고 닫습니다.
