### ISSUE TITLE
[데이터추가] 에서 열이름변경을 해서 데이터로딩하면 오류로 데이터가 안들어갑니다

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1873]
## 버그 설명 ##
데이터 추가 메뉴에서 열이름 변경 후 로딩하면
테이블생성은 변경된 열이름으로 생성되지만 데이터를 로딩할 때 오류로 로딩이 실패합니다.

dategroup 을 NEW_DATE  로 변경

* 테이블 생성은 OK
<img width="543" alt="스크린샷 2020-02-04 오후 3 47 37" src="https://user-images.githubusercontent.com/5126497/73720938-77c72e80-4766-11ea-98c8-594d8c98b689.png">

* 데이터 로딩 시 dategroup컬럼을 찾고 있어서 오류 남
<img width="596" alt="스크린샷 2020-02-04 오후 3 47 59" src="https://user-images.githubusercontent.com/5126497/73720966-87df0e00-4766-11ea-9be3-33067f912441.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
문제가 발생했을 때 아래와 같은 작업 목록UI를 첨부해주시면 문제 해결에 도움이 될 것 같습니다.
현재까지 파악하기로는 '열 분할' 기능에 구조적인 문제가 있습니다.

![image](https://user-images.githubusercontent.com/3411842/73728268-60903d00-4776-11ea-8f28-27c08a5e2811.png)

**Comment by seoryjj** [comment]
<img width="1271" alt="스크린샷 2020-02-04 오후 5 13 30" src="https://user-images.githubusercontent.com/5126497/73801831-156e3c80-47ff-11ea-8697-2dd56f8963f8.png">


-> 여기에서 dategroup 컬럼이름을 NEW_DATE 로  이름변경했습니다.

그런데 **dategroup** 이라는 컬럼명을 사용하면 문제가 되는 것 같습니다.
dategroup 대신  NEW_DATE 로 처음부터 만든 데이터는 에러없이 입력되었습니다.

<img width="1277" alt="스크린샷 2020-02-04 오후 5 47 15" src="https://user-images.githubusercontent.com/5126497/73801935-58301480-47ff-11ea-9831-2139ea6e6ad8.png">
