### ISSUE TITLE
동시에 다중 로그인 방지기능 필요 (보안상 필수기능)

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#1876]
## 버그 설명 ##
동시에 다중 로그인 방지기능 필요합니다. 
이것은 보안상 필수 기능으로 모든 고객사의 보안 담당자가 웹 사이트 오픈시 체크하는 기본 사항입니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 특정 계정으로 한 명이  로그인 한 상태에서,
2. 다른 피시에서 해당 특정 계정으로 추가  로그인이 되는 보안 이슈가 있음.

## 기타 ##
* 로그인 계정과 IP를 IRIS 내부에서 관리하고 추적(Audit Logging) 기록하는 기능도 같이 고려되어야 함.

**Comment by rhcpn** [comment]
해당 부분은 버그라고 표시 하셨는데요, 오해가 있어 답변 남깁니다.

다중로그인 부분은 기존 IRIS Web의 의도적인 부분 입니다. "우연하게" 개발된 것이 아닙니다.

다중로그인 부분에 대해 기능을 추가하는 수순으로 오장석 팀장님과 1차 의견 나누었습니다.
우선 고객과 저희 제품 컨셉을 한번 얘기해봐서 설득을 시도해보는걸로 대략적으로 얘기 했습니다. (아마 설득이 안될것 같다는 이야기를 하였지만 ..) 
구현 방안에 대해서는 중복 로그인 시 나중에 로그인 한 사용자가 우선한다는 정책 까지는 정하였습니다.  또한 IRIS는 현재 구조상 이중화가 어려우므로 한번 로그인한 사용자가 사용 중간에 L4 스위치에서 다른 서버로 스위칭 되지 않아야 한다는 전제 조건도 이야기 하였습니다.

해당 부분은 일정 산정 및 배포 일자를 정하도록 하겠습니다.

**Comment by idaeho** [comment]
@rhcpn 박팀장님, 
빠른  답신 감사드립니다. 버그->보안이슈로 라벨 변경 하였습니다. 
올려드린 내용중에 "로그인 계정과 IP를 IRIS 내부에서 관리하고 추적(Audit Logging) 기록+조회(추적)하는 기능" 꼭 같이 고려 부탁드립니다.

**Comment by sunghoon** [comment]
기능 배포되 되어서 닫습니다.
