### ISSUE TITLE
파티션 키, 파티션 데이트 컬럼 설정

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#1878]
## 버그 설명 ##
파티션 키, 파티션 데이트를 같은 컬럼으로 설정하고 UI에서
데이터를 올릴때 기존 테이블을 선택할 경우
파티션 키는 알맞게 설정 되지만 파티션 데이트는 다른 값으로 선택이 됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/16331916/73993626-15ed0b80-4996-11ea-96ed-bb0ee517cd90.png)

![image](https://user-images.githubusercontent.com/16331916/73993769-97449e00-4996-11ea-9dfd-62a93e3767b5.png)

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }
 UI 에서는 파티션 키와 파티션 데이트를 같은 컬럼으로 선택할 수 없기 때문에 나는 현상 같은데..
테이블 생성시 파티션 키와 파티션 데이트를 같은 컬럼으로 선택할 수 없도록 하거나
UI 에서도 같은 컬럼으로 선택할 수 있도록 통일성이 필요하지 않을런지...

**Comment by veldise** [comment]
말씀하신대로 파티션 키와 파티션 데이터를 동일 컬럼으로 설정해서 발생하는 문제로 확인되었습니다.

**Comment by veldise** [comment]
- 신규 테이블 생성시에는 동일 컬럼 설정이 불가능하도록 현행 유지
- 기존 테이블 설정이 동일 컬럼으로 되어있을 때 예외 처리
