### ISSUE TITLE
사용자 정보 관리에서 기본 항목의 필드 타입 변경 가능

### ISSUE THREAD

**Issue by ollehQ** [mobigen/IRIS-BigData-Platform#1879]
## 버그 설명 ##
사용자 계정 -> 사용자 정보 관리 -> 기본 항목 필드타입 변경 가능

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. IRIS Web에 접속후, super user 계정으로 로그인
2. 사용자 관리 > 사용자 계정 접속
3. 우측 상단의 '사용자 정보 관리' 클릭
4. 비밀번호 항목의 필드 타입을 '드릴 다운'으로 변경

## 예상한 행동 ##
비밀 번호 항목의 필드 타입에서 '드릴 다운'은 선택이 불가능하다.

## 스크린샷 ##
![bug](https://user-images.githubusercontent.com/26221956/74006487-2b2a6000-49bf-11ea-9dc1-0fe44cb018e0.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
'기본' 항목들은 필트 타입을 변경할 수 없는게 맞습니다. 수정하겠습니다.
