### ISSUE TITLE
[검색] 결과는 정상적으로 나오고 난 후,  angora 에러가 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1880]
## 버그 설명 ##
forecasts  실행 후 결과는 아래 sheet 에 전부 나왔는데,
검색이 완료 되지 않은 것처럼 파란 bar 가 중간에 멈춰있고, 약 3 ~ 5분  후에 angora 에러 창이 뜨고 실행이 완료되었습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. myiris 계정  / syslog.myiris 데이터모델
2. 날짜 2019/12/10 09:00:00 ~ 2019/12/10 11:59:59
3.  검색 명령어
`*  HOST='platform2'  | sql "select CONCAT( SUBSTR(DATETIME,1, 11 ) , '000') as DATETIME_10M, * from angora" | stats COUNT(*) as CNT by DATETIME_10M, HOST  |  sort +DATETIME_10M | forecasts DATETIME_10M CNT alg=linear`

## 스크린샷 ##
forecast결과가 다 나왔는데, 진행중으로 나오고 약 5분간 이 상태가 지속
<img width="1277" alt="스크린샷 2020-02-10 오전 11 06 09" src="https://user-images.githubusercontent.com/5126497/74116446-ee48ae00-4bf6-11ea-95b8-1948fc582569.png">

13:20 예측값까지 나오면 결과가 다 출력된 것입니다.
<img width="1265" alt="스크린샷 2020-02-10 오전 11 06 20" src="https://user-images.githubusercontent.com/5126497/74116478-0e786d00-4bf7-11ea-858d-e336eb718d7a.png">

결과가 다 나오고 나서도 계속 진행중인 상태로 약 5분 가량 지난 후 에러 팝업창이 뜹니다.
<img width="1263" alt="스크린샷 2020-02-10 오전 11 15 57" src="https://user-images.githubusercontent.com/5126497/74116509-2a7c0e80-4bf7-11ea-9c10-a2d6eefdedd9.png">

<img width="238" alt="스크린샷 2020-02-10 오전 10 58 01" src="https://user-images.githubusercontent.com/5126497/74116510-2d76ff00-4bf7-11ea-81aa-b0c47f841b4c.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
forecasts 만 그런 게 아니고 검색명령어를 실행하면 다 이런 현상입니다.. 결과는 나왔는데, 진행중인 파란색 bar가 보입니다.
<img width="1152" alt="스크린샷 2020-02-10 오후 1 55 11" src="https://user-images.githubusercontent.com/5126497/74122037-2529be80-4c0d-11ea-8067-8f5c8075ae19.png">

**Comment by anhm** [comment]
서버 리소스 이슈가 조금 존재하는 상황이었습니다.
서버의 프로세스를 재시작해여 정상화 시켜 두었습니다.

**Comment by seungfwani** [comment]
이슈 해결 된건가요?

**Comment by seungfwani** [comment]
해당 문제 더이상 발생하지 않는것으로 보이며 닫도록 하겠습니다.

같은 문제 발생시 재오픈 요청드립니다.
