### ISSUE TITLE
사파리 브라우저에서 라벨(글씨쓰기) 기능 오작동.

### ISSUE THREAD

**Issue by sundoforce** [mobigen/IRIS-BigData-Platform#1882]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

safari 브라우져에서 아이리스 보고서의 라벨 기능이 작동하지 않습니다.
<img width="116" alt="스크린샷 2020-02-10 오후 5 52 16" src="https://user-images.githubusercontent.com/16316626/74134627-333c0700-4c2e-11ea-8812-385ffb18960d.png">
[A] 아이콘 - 누르고 글씨써지는 기능 : 글씨가 써지지 않음.

[](url)
## 재현하는 방법 ##
동작을 재현하는 방법 :
1. b-iris 접속(맥 사파리 브라우져)
2 .로그인 
3. 보고서 - 생성 혹은 편집
4. [A] 아이콘 누른 뒤 글씨 쓰기 시도  

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

<img width="455" alt="스크린샷 2020-02-10 오후 5 45 42" src="https://user-images.githubusercontent.com/16316626/74134763-6ed6d100-4c2e-11ea-9a78-5160eab69413.png">

콘솔창에 특별한 에러는 없었습니다.
## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

사파리 브라우져에서 b-iris 보고서에 글씨를 쓸때 버그가 있습니다.
긴급하거나 중요한 이슈사항은 아니니 
혹시나 시간이 되실때 봐주시면 감사하겠습니다.
(버그보다는 사파리에서 안된다는 제보 및 건의사항 으로 생각해 주시면 감사하겠습니다.)

**Comment by seoryjj** [comment]
추가로  라벨에 대해 우클릭(순서/ 삭제) 이 안됩니다.
