### ISSUE TITLE
[K8S] '데이터브라우저' 항목의 모든 카테고리에서 내부 서버 오류가 발생합니다.

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1883]
## 버그 설명 ##
테스트를 위해 쿠버네티스로 기동한 클러스터 (http://192.168.102.150:32011/#/) 에서,
데이터브라우저 항목의 모든 카테고리에 대해 다음과 같은 `500 내부 서버 오류`가 발생하고있습니다.

<img width="1474" alt="스크린샷 2020-02-11 오전 9 52 22" src="https://user-images.githubusercontent.com/23020977/74203923-92445f00-4cb4-11ea-88f5-3448ceb7cfbd.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://192.168.102.150:32011/#/ 접속
2. 로그인
3. 데이터브라우저 항목에서 임의의 카테고리 클릭
4. 상기 에러 발생

**Comment by jblim0125** [comment]
## 오류 원인 
sherman 에서 angora로 auth요청 단계에서 angora로 연결할 수 없어 발생하고 있습니다.

- sherman 로그 
ERROR 13 --- [nio-8080-exec-6] c.m.s.common.utils.AngoraTokenUtil       : angora token request exception:Failed to connect to angora-svc/10.96.81.254:6036

Angora 혹은 Angora - Sherman 간 연결 관련 확인이 필요합니다.

**Comment by jblim0125** [comment]
## 최종 확인 결과  
* 쿠버네티스 프로비져닝에서 Angora의 서비스 포트를 지정하는 경우 오류 발생  
  Angora의 포트를 지정하고자 하는 경우 Angora로 연결되는 모든 Pod들에 
  Angora Port 변경 필요하나 이 부분이 처리되지 못함.  

## 조치
프로비져닝서버에서 angora port를 지정하는 부분을 삭제처리 함.  

## 결과
정상적으로 화면이 표시되는 것을 확인 함.  
![image](https://user-images.githubusercontent.com/6268831/74217745-a3f52900-4ceb-11ea-921d-35008340fffc.png)
