### ISSUE TITLE
데이터 모델 검색어에 날짜 처리 함수 추가

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1885]
## 기능 요청 ##
데이터 모델 검색어에 날짜 처리 함수 추가

## 원하는 솔루션 설명 ##
현재 날짜시간을 기준으로 날짜시간을 더하거나 뺄수 있는 기능
ex) 현재날짜 - 5개월

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
시간 컬럼 차이를 구하는 명령어를 추가하였습니다.
[timediff](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/timediff.html)

**Comment by SONHOJUN** [comment]
| timediff UNIT 'TIME1' 'TIME2' AS col_name | where col_name < 100

**Comment by seungfwani** [comment]
현재 timediff 명령어에 예외처리가 부족하여 typecast 를 통해 string 데이터를 timestamp 로 바꿔줘야하는 불편함이 있습니다.
로직과 문법이 차차 수정 될 예정이기에 명령어 사용시 에러가 발생하면 문의 바랍니다.

아래는 예제 입니다.
데이터 모델: syslog
```
* | typecast DATETIME timestamp "YYYYMMDDHHmmss" | timediff minute '20201012110000' "YYYYMMDDHHmmss" 'DATETIME'
```

![Screen Shot 2020-10-12 at 10 28 39 AM](https://user-images.githubusercontent.com/46172579/95696361-b73f0680-0c75-11eb-8128-644d77cde185.png)

```
* | typecast DATETIME timestamp "YYYYMMDDHHmmss" | timediff minute '20201012110000' "YYYYMMDDHHmmss" 'DATETIME' | where RESULT < 40
```

![Screen Shot 2020-10-12 at 10 32 06 AM](https://user-images.githubusercontent.com/46172579/95696476-32a0b800-0c76-11eb-9ac6-70fc95fbdd7f.png)

**Comment by SONHOJUN** [comment]
@seungfwani 
now 또는 today 같이 현재 날짜를 가져오는 함수가 있으면 완벽할 것 같습니다.
* | typecast DATETIME timestamp "YYYYMMDDHHmmss" | timediff minute 'now' "YYYYMMDDHHmmss" 'DATETIME' | where < 40
timediff에 현재날짜를 대입하여 비교할 수 있었으면 합니다.

**Comment by sunghoon** [comment]
@SONHOJUN 마지막 요청 사항은 별도 이슈로 다루겠습니다.
