### ISSUE TITLE
보고서 그래프 종류 선택 기능

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1886]
## 기능 요청 ##
보고서 그래프의 종류를 실시간으로 선택하는 기능

## 원하는 솔루션 설명 ##
Studio에서 꺽은선그래프로 저장 후 보고서 조회 시 실시간으로 세로막대나 가로막대 그래프로 변경할 수 있는 기능

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by jjinylee** [comment]
저도 이 기능 요청드리려고 했습니다~^^
NMS+ 도 한표 투척합니다.

**Comment by sunghoon** [comment]
데이터 시각화를 위한 다른 방법이 필요해 보입니다. 
일단 접수하고 고민해 보겠습니다. 
--
pivottableview
