### ISSUE TITLE
[밸류링크유] 쿼리문에 없는 컬럼 표시

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1887]
## 버그 설명 ##
pivot SPLITCOL에서 안나오는 값이 컬럼으로 표시됨.

모든 컬럼을 볼 수 있게 설정하고 컬럼 표시 순서를 '시각화 옵션'->'헤더'에서 변경
특정 컬럼만 보이게 설정하고 조회 시 모든 컬럼 표시됨.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
내용이 없는 컬럼은 pivot SPLITCOL에서 안나오는 항목입니다.

![image](https://user-images.githubusercontent.com/7067615/74221338-3c43db80-4cf5-11ea-826f-af60e02e0d97.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@SONHOJUN 
'모든 컬럼을 볼 수 있게 설정'이 어떤 건지 설명해주실 수 있나요?

**Comment by SONHOJUN** [comment]
보고서 중 '컨테이너 해운 > Korea Flag Carriers Supply-v1.1' 수정 화면에서 Index 체크박스 모두 체크 후 조회 시 조회할 수 있는 모든 컬럼이 보이게 됩니다.

**Comment by veldise** [comment]
@SONHOJUN 
문제 확인했습니다. 제가 이전에 잘못 처리한 것 같습니다.
서버(데이터 모델, DSMS 등)로부터 수신받은 데이터에 존재하는 컬럼만 표시하도록 수정하겠습니다.
