### ISSUE TITLE
데이터 모델의 컬럼 중복 변경 요청

### ISSUE THREAD

**Issue by ollehQ** [mobigen/IRIS-BigData-Platform#1888]
## 기능 요청 ##
IRIS - 데이터 브라우저 - 관리 - 데이터 모델의 컬럼이 유형/컬럼/유형/별칭/기타로 설정을 하고 있습니다.
두개의 유형중 하나의 유형을 다른 이름으로 변경하는 것이 다른 사람이 봤을때 안 헷갈릴꺼 같습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
좋은 의견 감사합니다.
가장 첫번째 열 이름을 '유형' 에서 '분류' 등으로 변경하는 방안을 검토해보겠습니다.
