### ISSUE TITLE
교통빅데이터 플랫폼 / 오픈랩 / 검색 오류 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1889]
## 버그 설명 ##
KT G-Cloud의 object Storage에 있는 파일을 대상으로 데이터 검색시 오류 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. https://openlab.diamond-e.kr:10443/#/ 접속
2. 검색 실행

## 스크린샷 ##
[KT Cloud를 이용한 모델 정보]
![image](https://user-images.githubusercontent.com/4444717/74316221-71ffc780-4dbc-11ea-881c-b87cbecfd414.png)

[검색 실행시 오류화면]
![image](https://user-images.githubusercontent.com/4444717/74316301-a6738380-4dbc-11ea-9750-0d99313984e2.png)

**Comment by JeongHeeDong** [comment]
@배성훈 그룹장님, 
담당자 확인 및 오류 확인 진행 부탁 드립니다.

**Comment by seungfwani** [comment]
현재 상황을 파악한 바로, 
rest api를 통해서 데이터를 가져와 dataframe으로 만드는 과정에서
데이터를 메모리에 중복 저장하는 로직으로 인해서, 메모리가 over되는 현상이 발생하는 것으로 보입니다.

해당 부분을 수정할 방법을 테스트 중이며, 금요일 내로 배포요청을 하도록 하겠습니다.

**Comment by seungfwani** [comment]
아래와 같이 데이터를 읽어올 수 있도록 수정되었음을 알려드립니다.
![Screen Shot 2020-03-11 at 11 17 17 AM](https://user-images.githubusercontent.com/46172579/76375720-e1e87a00-6389-11ea-9dad-058afb4c6df8.png)
