### ISSUE TITLE
[Studio] 에서 지도를 그릴 때, 데이터모델에서 데이터를 가져오지 못합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1891]
## 버그 설명 ##
1. Studio 지도를 선택하고, 마커표시할 레이어의 데이터로 **데이터모델** 선택하고 실행하면 
지도에 "결과가 없습니다" 가 뜹니다.
2. 그리고 시각화탭에서 마커로 지정하고 마커시각화 설정에서 데이터 탭에서 위, 경도 컬럼이 보이지 않습니다.
3. 그 후 다시 데이터텝으로 오면  데이터모델 지정한 것이 저장되어 있지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
root 계정의 SW_PARKING_PLACE 데이터모델

- SW_PARKING_PLACE 조회한 검색 결과  : 위/경도 컬럼이 있는 데이터입니다.
<img width="1208" alt="스크린샷 2020-02-13 오후 12 33 49" src="https://user-images.githubusercontent.com/5126497/74400456-41be3480-4e61-11ea-91f7-deca0cd2ccb9.png">

- 주차장 레이어에서 데이터모델로 설정후 실행버튼 누른 결과
<img width="1217" alt="스크린샷 2020-02-13 오전 11 37 42" src="https://user-images.githubusercontent.com/5126497/74400462-44b92500-4e61-11ea-91c6-71bf2ff5e243.png">

- 주차장 레이어에서 마커의 시각화 설정 화면 : 데이터를 가져오지 못해서 컬럼정보가 없는 거 같습니다.
<img width="1055" alt="스크린샷 2020-02-13 오후 1 05 33" src="https://user-images.githubusercontent.com/5126497/74400565-a083ae00-4e61-11ea-8b7f-b4dbbec55ca4.png">

- 다시 데이터탭 누르면 데이터모델 지정한 것이 사라져 있습니다.
<img width="1066" alt="스크린샷 2020-02-13 오후 1 07 53" src="https://user-images.githubusercontent.com/5126497/74400703-1f78e680-4e62-11ea-8bd4-c7edb3df6097.png">

이 현상은 보고서 저장 한 후 다시 편집으로 들어올 때도 데이터탭에서 데이터모델 부분은 지정한 것이 사라져 있습니다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm @namjals @seungfwani 
아래 쿼리 수행 결과가 없는 이유에 대해서 확인을 부탁드립니다.

1번:
```
model name = 'SW_PARKING_PLACE' spatial_coordinates = 'POLYGON((25.835818618104156 125.42791748046876, 25.835818618104156 130.07037353515628, 36.923547681089296 130.07037353515628, 36.923547681089296 125.42791748046876, 25.835818618104156 125.42791748046876))'
```
2번:
```
model name = 'SW_PARKING_PLACE' spatial_coordinates = 'POLYGON((25.835818618104156 125.42791748046876, 25.835818618104156 130.07037353515628, 36.923547681089296 130.07037353515628, 36.923547681089296 125.42791748046876, 25.835818618104156 125.42791748046876))' map_level = 11
```

**Comment by anhm** [comment]
해당 문제는 GEOM 을 처리하기 위한 컬럼 정보가 없어서 그렇습니다.

해당 기능을 정상적으로 사용하기 위해서는
테이블에
`GEOM`, `GEOM_LEVEL`
컬럼이 존재해야 하며,
`GEOM` 컬럼은 공간 데이터 가 들어가 있어야 하고,
`GEOM_LEVEL` 컬럼은 지도의 zoom정보가  들어가 있어야 합니다.

**Comment by anhm** [comment]
해당 명령어의 사용법및 데이터를 넣는 방법에 대해서는
문서를 정리하여 다시한번 공유해 드리도록 하겠습니다. (약간 시간이 소요될것 같습니다.)

**Comment by veldise** [comment]
@anhm
답변 감사합니다.

**Comment by sunghoon** [comment]
해결된 이슈로 닫습니다.
