### ISSUE TITLE
[KOTRA]IRIS Studio 개인화

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1893]
[개인화]
1. IRIS DB는 전혀 사용하지 않고, 제공된 데이터모델로만 보고서를 만드는 일반사용자 계층이 있음
2. 자신이 작성한 보고서가 갤러리 형태로 보였으면 좋겠음. 
3. 접속시 첫화면을 개인화 했으면 좋겠음 => 사용자가 작성한 보고서 목록화면
4. 또는 사용자별 첫화면을 자신만의 대시보드 형태로 볼수 있으면 좋겠음.

**Comment by sunghoon** [comment]
오래된 이슈라 KOTRA 프로젝트랑 상관없이 개발 아이디어로 접수하겠습니다.
KOTRA 프로젝트와 중요한 연결 관계가 있다면 다시 한번 알려 주시기 바랍니다.
