### ISSUE TITLE
[KOTRA]IRIS Studio 커뮤니티 기능

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1894]
1. 사용자간 보고서를 주고 받을수 있는 커뮤니티 기능 필요
2. IRIS Studio 접속한 사용자에게 공지할 수 있는 관리자의 공지기능.
3. 특정 사용자에게 자신의 보고서 URL을 전달하고, 수신한 사용자는  URL을 통해 해당 보고서를 
    조회하는 기능
4. 화면에 출력한 보고서를 PDF로 출력할 수 있는 기능.

**Comment by sunghoon** [comment]
해당 기능을 추후 개발 아이디어로 접수하도록 하겠습니다.
