### ISSUE TITLE
[KOTRA]시인성 개선필요

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1895]
시인성 문제로 데이터를 확인하기가 어려움
![3D1620CD-C654-4637-B393-2344B39789ED](https://user-images.githubusercontent.com/18297120/74417584-4d722100-4e8a-11ea-8ddf-66b5a7ba5b96.jpeg)

1.우선 모바일에서 올리면 사진이 눕는것 미안하게 생각합니다. 
  폐쇄망이라 모바일로만 캡춰가 가능해서 어쩔수 없네요. 

2. 차트에 범례가 많을 때 제가 확인하고 싶은 데이터의 레이블을 확인할 수가 없습니다. 

3. 차트에 마우스를 올렸을때 툴팁이 나오는데, 내가 선택한 정보의 레이블이 먼저 표기되었으면
   합니다. 모든 레이블이 표시되니 찾기가 어렵네요.

**Comment by sunghoon** [comment]
요청하신 요구사항과 유사한 기능들이 반영되어 있는것으로 알고 있어. 
닫습니다.
