### ISSUE TITLE
[수원시] IRIS-analyzer 관리 > 테이블 권한 에러 알람 

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1897]
## 버그 설명 ##
[수원시] IRIS-analyzer 관리 > 테이블 권한 에러 알람 발생

## 재현하는 방법 ##
 IRIS-analyzer 관리 > 테이블 권한 에러메뉴 클릭 시 error [object Object] 알람 발생

## 예상한 행동 ##
현재 생성한 모든 데이터베이스명 + 테이블 명 조회.
에러 알람 확인 이후 리스트엔 WAS, SUWON_DEV 2개의 데이터베이스명만 조회

## 스크린샷 ##
![iris_error](https://user-images.githubusercontent.com/8993205/74513754-a7d4b580-4f4e-11ea-8b22-6eeb0773f9eb.PNG)
![iris_error2](https://user-images.githubusercontent.com/8993205/74513785-b3c07780-4f4e-11ea-80c8-72437bcd3fc9.PNG)

위 스크린샷같이 2개의 데이터베이스만 존재.

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
일단 에러 메시지가 정상적으로 나오도록 수정하겠습니다.

@big-mobigen 
문제 발생시의 meta, cluster 서비스 로그가 필요합니다. 로그 내용을 보내주실 수 있는지 확인 부탁드립니다.

**Comment by veldise** [comment]
cluster 버전이 낮아서 발생하는 문제로 확인되었습니다.

**Comment by veldise** [comment]
운용기술연구팀 강준희 선임님이 패치를 통해 처리해주셨습니다. 이슈 닫습니다.
