### ISSUE TITLE
보고서 페이지 에러

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#1898]

**Comment by kim3163** [comment]
> ## 버그 설명
> 보고서 창으로 가면 보고서가 읽히지 않음
> 
> ## 재현하는 방법
> 동작을 재현하는 방법 : 
 1.계정 로그인
 2. 관리 > 보고서
> 
> ## 스크린샷
> { 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
> 
![image](https://user-images.githubusercontent.com/16331916/74627489-5e76a700-5196-11ea-88f9-378037b88f56.png)

> ## 로그
> { 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }
> 
> ## 기타
> { 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
보고서의 '내보내기 URL'이 중복 생성되어 발생한 문제로 확인되었습니다.
중복 생성된 URL을 제거하여 현재는 정상 동작합니다.

**Comment by veldise** [comment]
일단 임시 조치로 중복이 발생한 테이블 컬럼에 unique 설정을 걸겠습니다. (2/20 예정)

**Comment by veldise** [comment]
임시 조치 완료되어 일찍 닫습니다.
