### ISSUE TITLE
Column Chart 데이터 잘 못 셋팅되는 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#1899]
## 개요
Column Chart 그릴때 category 개수보다 series 개수가 더 많이 그려집니다.

## 내용
* 데이터 모델: WEATHER
* 시간: 2007/01/01 00:00:00 ~ 2007/01/04 00:00:00
* 시각화
![스크린샷 2020-02-17 오후 4 03 32](https://user-images.githubusercontent.com/5515493/74631181-aea63700-519f-11ea-9198-73cc21f6b779.png)

* results 가 아래처럼 오고 똑같은 날짜가 주기적으로 반복하여 데이터가 있습니다.
```
[
    [ "2007-01-01", "90", 4.5, -0.3, 8.9, null, null, 3.5, 1.6, 30.0, 46.3, 4.0, 1029.4, 1024.1, 1025.8, 6.0 ],
    [ "2007-01-02", "90", 3.1, 1.1, 4.0, 15.0, "15.5", 5.6, 2.2, 56.0, 79.5, 6.2, 1028.6, 1024.1, 1025.7, 0.0 ],
    [ "2007-01-03", "90", 1.9, -0.5, 3.9, 3.75, "0.3", 5.3, 1.9, 60.0, 73.1, 5.2, 1030.7, 1028.1, 1029.4, 0.0 ],
    [ "2007-01-04", "90", 2.6, -0.6, 6.3, null, null, 4.0, 2.0, 59.0, 73.4, 5.5, 1029.9, 1028.1, 1029.0, 1.9 ],
    [ "2007-01-01", "95", 0.3, -5.3, 6.1, 2.33, "0.2", 2.5, 0.6, 40.0, 68.6, 4.2, 1032.0, 1025.1, 1027.7, 2.5 ],
    [ "2007-01-02", "95", 2.1, -0.1, 5.5, 7.17, "0.4", 3.9, 1.1, 71.0, 85.6, 6.2, 1027.2, 1024.2, 1025.8, 0.0 ],
    [ "2007-01-03", "95", 2.8, -2.9, 8.3, null, null, 5.3, 3.0, 49.0, 71.8, 5.3, 1029.3, 1026.4, 1028.2, 2.0 ],
    [ "2007-01-04", "95", -0.8, -6.0, 8.6, null, null, 2.6, 0.6, 41.0, 80.3, 4.4, 1031.0, 1027.5, 1029.4, 7.8]
    ...
]
```

* 위의 데이터로 카테고리는 2007/01/01 00:00:00, 2007/01/02 00:00:00, 2007/01/03 00:00:00, 2007/01/04 00:00:00 4개가 셋팅됩니다.

![스크린샷 2020-02-17 오후 4 02 57](https://user-images.githubusercontent.com/5515493/74631082-6ab33200-519f-11ea-8fbf-f2d9a8b3da23.png)  
*  카테고리 4개 이외의 데이터가 셋팅되어 차트가 위 처럼 나옵니다.

![스크린샷 2020-02-17 오후 4 03 09](https://user-images.githubusercontent.com/5515493/74631679-e497eb00-51a0-11ea-8f5e-0a185cf56a57.png)  
* 카테고리 이외의 데이터는 index로 셋팅되어 point.x 값이 index 값으로 되어 tooltip에서 $filter('msec2str')를 사용하면 1970/01/01 09:00:00 으로 표시 됩니다.

* series 값이 카테고리 만큼 셋팅되어야 할 것 같습니다.

**Comment by veldise** [comment]
보고서는 수신받은 데이터(쿼리 결과)를 그대로 차트로 그리고,
Column chart, Bar chart 의 경우에는 x축/y축에 지정하는 데이터가 unique 해야 잘 그려집니다.
시간 조건만 지정하고 조회할 경우에는 단순 select로 group by 등의 처리를 하지 않으므로,
본문과 같이 그려지는 것이 정상입니다.
