### ISSUE TITLE
[수원시] 데이터브라우저 > 시각화 angora error 공유

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1900]
## 버그 설명 ##
수원시 데이터브라우저 > 시각화 메뉴 실행 이후.
데이터모델에 모델 검색. 이후 모델을 더블클릭 하면 오류 발생.
--> 오류 확인 이후 차트 진행해도 "결과가 없습니다." 발생
## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![error2](https://user-images.githubusercontent.com/8993205/74634420-27f55800-51a7-11ea-9578-5619abb870e8.PNG)
![error3](https://user-images.githubusercontent.com/8993205/74634423-29268500-51a7-11ea-8aa1-80f3c57d3fa5.PNG)
![error1](https://user-images.githubusercontent.com/8993205/74634425-29bf1b80-51a7-11ea-9689-c350dbd27afe.PNG)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
2/18(화) 에 해당 내용에 대해서 @김성준 선임님께 유선상으로 해결 방법을 전달드렸으며,
앙고라는 해당 부분의 로직을 수정하여 배포요청 하였습니다.

현재는 아래와 같이 검색이 가능한 상태입니다.
![Screen Shot 2020-02-19 at 12 24 42 PM](https://user-images.githubusercontent.com/46172579/74799154-14ff9680-5313-11ea-9c76-e2ee8b08c680.png)

**Comment by seungfwani** [comment]
배포 완료되어 닫도록 하겠습니다.
