### ISSUE TITLE
아이리스 보고서 목록에 TREE기능 건의 

### ISSUE THREAD

**Issue by sundoforce** [mobigen/IRIS-BigData-Platform#1903]
## 기능 요청 ##
아이리스 보고서의 [목록] 컴포넌트에서 
TREE기능을 추가 건의 드립니다.

현재는 목록으로만 되어 있습니다.

## 원하는 솔루션 설명 ##
<img width="835" alt="image" src="https://user-images.githubusercontent.com/16316626/74818038-47c08380-5341-11ea-8ca2-3ea937472ecb.png">

TREE 형식의 목록이 있었으면 합니다.

그리고 가능하다면 상태를 나타낼수 있게 구분되는 아이콘도 기능도 추가 건의 드립니다.

## 고려한 다른 대안 ##
[https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxtree/index.htm#demos/jqxtree/treebindingtojson.htm](https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxtree/index.htm#demos/jqxtree/treebindingtojson.htm)

![image](https://user-images.githubusercontent.com/16316626/74818464-0f6d7500-5342-11ea-8a41-2b99602c8175.png)

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
![image](https://user-images.githubusercontent.com/16316626/74818524-2d3ada00-5342-11ea-9660-2cd696e61246.png)

감사합니다.

**Comment by veldise** [comment]
NB_IOT 등 타 업무로 인해 연기되었습니다.

**Comment by sunghoon** [comment]
@veldise @swish1995 본 이슈에 대한 최종 처리 상태를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
다른 고객 요구사항 등을 우선적으로 처리중으로 Tree 기능 개발은 대기 상태입니다.

**Comment by sunghoon** [comment]
@eumminsun 개발을 위한 검토 진행해 주세요.
