### ISSUE TITLE
b-iris 보고서 차트 기능 추가 건의 드립니다.

### ISSUE THREAD

**Issue by sundoforce** [mobigen/IRIS-BigData-Platform#1904]
## 기능 요청 ##

아이리스 보고서의 
차트 - 단일값 에서 

사용자가 정의한 단일 값에 따른 
객체 색상이 변하는 기능이 필요합니다.

가령 사용자가 정한 숫자가 될수도 있고 
백분율이 될수도 있습니다.

![image](https://user-images.githubusercontent.com/16316626/74821709-5ca01580-5347-11ea-8541-c8d09801a754.png)
![image](https://user-images.githubusercontent.com/16316626/74821775-74779980-5347-11ea-88d6-6c20afe4449f.png)

## 원하는 솔루션 설명 ##
![image](https://user-images.githubusercontent.com/16316626/74821522-18147a00-5347-11ea-9a8c-8b6ee730eee8.png)

## 고려한 다른 대안 ##
![image](https://user-images.githubusercontent.com/16316626/74822016-d46e4000-5347-11ea-958c-8ad20bbf93c4.png)

b-iris의 대시보드에 있는 "클러스터 히트맵"으로 구현 가능할것 같습니다.
보고서에서 활용 할 수 있는 방법을 다른 방안으로 제시 드립니다.

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
![image](https://user-images.githubusercontent.com/16316626/74821467-03d07d00-5347-11ea-94ae-666c0d273ec0.png)

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
Chart 객체의 단일값 유형 대신에, 아래와 같이 Label 객체에 "조건부 서식" 기능을 추가하여 해결하는 것으로
김준우 책임과 이야기가 됐었습니다.

![image](https://user-images.githubusercontent.com/3411842/93971229-a4d65900-fdaa-11ea-94c9-5bca2d599dd6.png)
