### ISSUE TITLE
[KOTRA]데이터모델 생성시 사용자 실수 방지방안

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1905]
![1F067326-719E-4E21-B805-966FDEF86CEC](https://user-images.githubusercontent.com/18297120/74893339-7c7b1c00-53cf-11ea-95c9-9aff0043907e.jpeg)

## 현황 ##
사진에 보이는 데이터는 현재 150,000,000 건 정도임.
매년 2천만건씩 증가됨. 
데이터 모델을 만들면서(코트라 사용자가 만듦) 시간 필드를 지정하지 않음.

## 문제 ##
시간 필드를 지정하지 않고 만들었더니, 
다른 사용자들이 해당 데이터모델 조회를 할 때마다 전체 데이터를 조회하고 있음. 
결국, 데이터는 조회하지 못하고, 아이리스만 죽어나고 있음.

## 기능 요청 ##
견고함이 필요함. 
방어적 기능이 있어야 됨. 
예를 들어, 데이터량이 많은 테이블의 경우, 시간필드를 지정하지 않으면 모델 생성이 안된다거나,
경고를 주어 각인 시킬필요가 있음. 

검토 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 해당 사항에 대한 파악 및 정보 공유 바랍니다.
