### ISSUE TITLE
[NMS+]studio 콤포넌트 보완요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1906]
## 기능 요청 ##
1. 콤포넌트의 id 를 찾기가 어려움. 일일이 콤포넌트 클릭하고 속성가서 확인해야함.

   방안1) 첫번째 tab or 상위에 콤포넌트 종류 / id 노출필요
   방안2) studio 콤포넌트 생성시 그 위에 콤포넌트 종류 : 콤포넌트 id 콤포넌트가 보여지면 좋겠슴.
   
   타사이트에서 만든 보고서 활용시, 콤포넌트가 많아지면서 이게 먼지 확인하고 싶음 . 명시적으로 방안2) 로 보여지면 바로 무엇인지 알수있음
   
![iris1](https://user-images.githubusercontent.com/5468183/74894148-830a9300-53d1-11ea-8da0-f5ec788689ba.PNG)

 2. 트리거 설정이 헷갈림
 현재 트리거는 이벤트 수신쪽에 걸어야함. rest_api 등 여러가지 이벤트 등이 생기면서 이게 어느쪽에 걸려야하는지 헷갈림.
 이부분은 기획등의 고민 필요
 
 
 3. 디버그모드가 있었으면 좋겠슴
   [보기] 에서 DSMS / DSL 쿼리가 동적으로 변경될때 해당 쿼리가 무엇인지 에러날경우 확인필요함
   이것만 되도 에러가 왜나는지등 확인/요청등 소요되는 시간이 줄어듬
   

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
기능 검토 하도록 하겠습니다.
