### ISSUE TITLE
[NMS+]studio 디자이너(템플릿) 기능 

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1907]
## 기능 요청 ##
  1. 다크모드 등 스킨을 3~5가지 정도 type 에서 변경가능할수있슴 좋겠슴

  2. 보고서 템플릿 기능 
  
     현재 밸류링크유, 교통, 수원시, NMS+ 등 여러분야에서 보고서를 만드는데 안의 내용은 사이트마다 다르더라도 각 사이트의 보고서 생성 노하우를 공유하면 좋을거같음 

     common , nms, 물류 등 먼가 group 별로 현재 사이트에 적용된 보고서등을 템플릿을 만들어서 해당 템플릿을 타사이트에서 그냥 가져다 쓰면 싸이트에 맞게 쿼리생성만으로도 보고서 작성시간이 엄청 줄어듬
	 
  그럼, 누구나 퀄리티 높은 보고서 작성이 가능함. 
 그 이후는 사용법,  DSL 문법 교육하여 싸이트 활용도를 높일수있슴
	 
  3. icon 등 이미지를 모아놓고 이미지도 선택하여 쓰면 좋겠슴.
  ( 개별적으로 요청하고 하지말고 재사용 )
     common icon
     network icon 
     document icon
     button icon 등등...
	 
   

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
아래와 같은 키워드로 기능 준비 중입니다. 
- 보고서 템플릿
- 보고서 컴포넌트 테마

구체적인 계획이 수립되면 공유 드리겠습니다.
