### ISSUE TITLE
[수원시청] 피벗화면에서 검색으로 이동 실행 시 에러 발생합니다

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1908]
## 버그 설명 ##
피벗에서 챠트를 그린 후 **검색으로 이동** 을 누르면 에러 팝업창이 뜨고 이동이 안됩니다.
http://58.181.37.140:8082/
(수원시청 IRIS)

* 피벗 실행 후  **검색으로 이동** 시행
<img width="1235" alt="스크린샷 2020-02-20 오후 2 53 51" src="https://user-images.githubusercontent.com/5126497/74905292-26b76b80-53f1-11ea-95d6-11166e676e0e.png">

* 이런 에러 팝업창이 뜨고 이동이 안됩니다.
<img width="639" alt="스크린샷 2020-02-20 오후 2 53 38" src="https://user-images.githubusercontent.com/5126497/74905294-2919c580-53f1-11ea-8ba2-7d05fd00a708.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
현재는 정상동작하며 검색 화면에 아래와 같은 검색어가 자동 완성됩니다. 일시적인 문제가 아니었나 생각됩니다.
```
* | pivot sum(MALE_NATIVE_POPULATION_COUNT) SPLITROW BASIS_DATE SPLITCOL DONG
```

**Comment by veldise** [comment]
@seoryjj 
에러 내용으로 볼 때 #1917 과 동일 이슈로 생각됩니다.

**Comment by seungfwani** [comment]
비슷한 현상이 발생하면 재 오픈 하겠습니다.
