### ISSUE TITLE
이미지 URL 동적으로 할당 받기

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#1909]
## 기능 요청 ##
이미지의 URL을 생성하여 동적으로 받아내고 싶습니다.
이미지의 URL 사용 -> 이미지 삽입에서 ${image_url} 식으로 받아내면
데이터에 따라서 동적인 이미지를 생성할 수 있을것으로 보입니다.

## 원하는 솔루션 설명 ##
이미지 삽입 URL에 변수를 설정할 수 있으면 좋겠습니다.

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
![image](https://user-images.githubusercontent.com/16331916/74911897-f1b31500-5400-11ea-9f0e-49acdc320bb4.png)

**Comment by veldise** [comment]
#2113
