### ISSUE TITLE
[Studio] 꺽은선형 그래프에서  데이터를  "모두 선택" 하면 챠트가 그려지지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1910]
## 버그 설명 ##
1개 컬럼 선택하면 그려지고,  모두 선택은 안됩니다.

* 보고서 

* 데이터 :  iris connector
SELECT 
	CDATE, HOUSE, POP_TOTAL
FROM 
	MYIRIS.SW_POP_DATA;

* 꺽은 선형 그래프

<img width="809" alt="스크린샷 2020-02-21 오전 9 43 09" src="https://user-images.githubusercontent.com/5126497/74993557-aba49280-548e-11ea-8517-2a445dbb9da5.png">

**Comment by veldise** [comment]
'모두 선택'시에는 컬럼 유형이 숫자(INTEGER, BIGINT, ...)인 컬럼만 선별하여 차트를 그리게 되어있습니다.
확인 결과 세 가지 필드 모두 `TEXT` 유형입니다.

**Comment by seoryjj** [comment]
INTEGER 로 해도 안 그려집니다.
MYIRIS.SW_GU_MAP_POP_TEST
<img width="188" alt="스크린샷 2020-02-21 오전 11 18 32" src="https://user-images.githubusercontent.com/5126497/74998369-e8c35180-549b-11ea-889c-0a856c65e936.png">

보고서 : 수원구별인구  

의 맵 옆에 테이블을 꺽은선형으로 하고 모두 선택으로 하면 안 그려집니다.
<img width="318" alt="스크린샷 2020-02-21 오전 11 20 36" src="https://user-images.githubusercontent.com/5126497/74998492-3213a100-549c-11ea-9bdc-c088d89bb24a.png">

**Comment by veldise** [comment]
```json
"fields": [
    { "name": "CDATE", "type": "TEXT" },
    { "name": "HOUSE", "type": "TEXT" },
    { "name": "POP_TOTAL", "type": "TEXT" },
    { "name": "POP_MALE", "type": "TEXT" },
    { "name": "POP_FEMALE", "type": "TEXT" },
    { "name": "MEMBER_CNT", "type": "TEXT" }
]
```

@seoryjj
테이블 컬럼 유형과 관계없이 쿼리 결과의 컬럼 유형이 `TEXT`이면
UI에서는 `TEXT`로 판단할 수밖에 없습니다.

@anhm
안형민 선임님, 이 문제에 대하여 답변 부탁드립니다.

**Comment by seungfwani** [comment]
DSMS 는 IRIS DB 로 부터 `메타정보(필드명, 필드타입)` 를 받아오는 그대로 UI로 보내주고 있습니다.

type이 모두 `TEXT` 인 문제는 IRIS DB의 문제이며, 기능개발이 필요합니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 본 이슈에 대한 진행 최종 상태를 공유해 주세요.

**Comment by anhm** [comment]
IRIS-DB를 최신으로 패치할 경우
```
/*+ TYPECAST(0=INTEGER) */ select * from ko_test;
```
와 같은 방식으로 TYPECAST hint문을 사용하여 처리가 가능 합니다.
