### ISSUE TITLE
[KOTRA]보안이슈

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1913]
![73285E1E-2ECF-4470-9B18-63581E146E8D](https://user-images.githubusercontent.com/18297120/75007516-bd029480-54b8-11ea-9769-1c6ae5f524df.jpeg)

## 문제 설명 ##
IRIS 플랫폼에서 구동되는 Spark 관리화면에 대한 접근제어가 필요함. 

접속 주소를 공개하지 않더라고, 내부 사용자가 충분히 알아낼수 있는 상황입니다. 
실행되는 잡들을 Kill 할수 있는 상태라 접근제어가 반드시 필요합니다.

**Comment by sunghoon** [comment]
@anhm IRIS-Cloud에서 해당 상황에 대한 제어 여부를 검토 해 주세요.

**Comment by anhm** [comment]
@sunghoon 
IRIS-Colud에서는 해당 포트를 막기 때문에 일반 사용자도 일반적인 방법으로는 접근이 힘듭니다.
kotra는 IRIS-Colud가 아니기 때문에 현재 상황에서는 처리가 힘든 상태입니다.
현 단계에서는 방화벽 정책으로 해결할수밖에 없습니다.

**Comment by sunghoon** [comment]
@yariyarishow 업그레이드 계획이 필요해 보입니다. 관련된 내용은 별도의 이슈로 처리하며, 본 이슈는 닫도록 하겠습니다.
