### ISSUE TITLE
studio: Combo / 사용자가 직접 선택시에만 항목/트리거가 설정되는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1916]
## 버그 설명 ##
Combo / 사용자가 직접 선택시에만 항목/트리거가 설정되는 문제가 있습니다.

- 관련 이슈: https://github.com/mobigen/IRIS-BigData-Platform/issues/1816#issuecomment-589541429

**Comment by jjinylee** [comment]
![iris](https://user-images.githubusercontent.com/5468183/75303441-11748e00-5884-11ea-81f5-67ea43e09c05.PNG)

이거면 될까요?

필요하신거 있으면 알려주세요

**Comment by veldise** [comment]
@jjinylee 
지금 본사 데모서버에서 발생하는 에러입니다. (버그) 아래와 같은 에러가 발생하는지 확인하고 싶었습니다.
혹시 현상이 재현될때 아래와 같은 에러가 콘솔에 출력되는지 알려주시면 감사하겠습니다.
참고로 아래 에러 문제는 해결되었습니다.

![image](https://user-images.githubusercontent.com/3411842/75313186-75f11680-589f-11ea-993b-385705de7bb9.png)

**Comment by veldise** [comment]
@jjinylee 
운용기술팀 권영길 팀장님께서 NMS+에 배포 완료했다고 하십니다.
문제가 해결되었는지 확인하신 후 해결되었다면 이슈 Close 부탁드립니다.

**Comment by jjinylee** [comment]
![iris에러](https://user-images.githubusercontent.com/5468183/75411244-e3657b80-5961-11ea-860a-2aa0de4a690d.PNG)

동일하게 에러가 나는데 제가 설정을 머를 잘못한건지 모르겠습니다.
확인부탁드립니다.

**Comment by veldise** [comment]
@jjinylee 
저 에러는 단순히 해당 서버(222.239.252.115:12000) 에서 에러를 반환하는 것이라
해당 서버쪽 로그를 확인해야 합니다.

**Comment by jjinylee** [comment]
![iris에러](https://user-images.githubusercontent.com/5468183/75411483-bebdd380-5962-11ea-9af4-590bd5d942fe.PNG)

동일하게라함은  기존과 동일하게 사용자가  설정한 콤보만 code 값이 들어가고
나머지는 동일하게 name 이 설정된다는 뜻입니다.

**Comment by veldise** [comment]
@jjinylee 
제가 직접 해당 보고서를 편집화면에서 확인해야 할 것 같습니다.
아니면 본사 데모서버에 유사한 보고서를 작성해서 테스트를 해야 합니다.

**Comment by jjinylee** [comment]
선임님. 보고서 ID 를 현재 확인할수가없네요

소유자 : nmsplus
조회 화면 : MENU_조회_장비정보
수정 화면 :  POP_장비_수정

입니다.

빠른확인을 위해  제 PC 에 접속할수있는 방법도 메일로 전달드르겠습니다.

**Comment by veldise** [comment]
`GET http://222.239.252.115:12000/equip/iris/1029` 결과:
```js
{
    "data": {
        "devId": 1029,
        "devName": "IDC_JFS15",
        // ... 중략 ...
        "idcCd": 1,
        "stationCd": 2,
        "venId": 0,
        // ... 중략 ...
    }
}
```

제조사 Combo-box 데이터 탭 설정에 따른 데이터:
```js
{
    "status": 0,
    "messages": "",
    "items": {
        "runtime": 0.001,
        "records": [
            [ 4, "CISCO" ],
            [ 6, "HP" ],
            [ 21, "DELL" ],
            [ 24, "EXTREME" ],
            [ 27, "JUNIPER" ],
            [ 41, "Huawei" ]
        ],
        "fields": [
            { "name": "VEN_ID", "type": "LONG" },
            { "name": "VEN_NAME", "type": "VAR_STRING" }
        ]
    }
}
```

제조사 Combo-box 항목 탭 설정 내용:
![image](https://user-images.githubusercontent.com/3411842/75413794-e6646a00-5969-11ea-8228-8e7a822d2de0.png)

**Comment by veldise** [comment]
다른 패치 내용으로 인한 코드 에러...

![image](https://user-images.githubusercontent.com/3411842/75413886-33e0d700-596a-11ea-8313-fbf0af554c4b.png)

**Comment by veldise** [comment]
```json
{
    "data": {
        "error": {
            "code": -1,
            "messages": "somting happened."
        }
    }
}
```
