### ISSUE TITLE
angora: ping API 요청시 10분 시점에서 Internal Server Error 반환

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1917]
## 버그 설명 ##
Analyzer(데이터 브라우저), Studio 에서는 세션 유지 목적으로 Angora의 ping API를 1분에 1회 요청하고 있습니다.
그런데 10번째, 즉 토큰을 발급받고 10분 시점에서 ping 요청을 날리면 아래와 같은 에러가 반환됩니다.

```html
<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

문제로 생각되는 것은 다음과 같습니다.
1. 10분 시점에 token expired 되는 것이 아닌가
2. ping API를 호출해도 token 이 유지되지 않음
3. 에러 response 가 JSON이 아닌 text/html

**Comment by seungfwani** [comment]
확인 해본 내용으로, 앙고라 내부적으로 token의 유지 시간이 업데이트가 안되고 있었습니다.

**Comment by seungfwani** [comment]
코드 수정 후 운영서버에 앙고라 배포 완료 하였습니다. 
20분 정도 ping을 사용해 보았고, 위와 같은 문제는 발생하지 않고, 정상동작 하는 것을 확인했습니다.

**Comment by seungfwani** [comment]
해당 이슈 닫아도 되는지 문의드립니다.

**Comment by veldise** [comment]
@seungfwani 
테스트 스크립트 수행시 17분 시점에서 TokenNotFound 에러가 반환됩니다.
Internal Server Error는 아니므로 본문 이슈는 해결되었으니 닫아도 됩니다만,
ping 요청으로 토큰 유지가 되는지 다시 한 번 확인 바랍니다.

**Comment by seungfwani** [comment]
개인적인 테스트에서 확인이 불가하여 일단 닫도록 하겠습니다.
이후 다시 현상이 발생하면 재오픈 하겠습니다.
