### ISSUE TITLE
사내 IRIS 의 Studio 서비스 사용불가 현상 개선 필요 

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#1918]
## 버그 설명 ##
 * 사내 IRIS 의 Studio 서비스 사용불가 현상 개선 필요 
   * **메모리 사용량 이슈로 추정**

## 재현하는 방법 ##
1. 웹브라우저로 사내 아이리스 로그인 창 하단에 'studio' 경고등 점멸 확ㅇ인.
2. 로그인후 메뉴에서 '보고서' 메뉴 비활성화 확인.
3. 메뉴의 자원 사용량 대시보드에서 노드별 메모리 full 현상 확인. 

## 스크린샷 ##
<img width="234" alt="스크린샷 2020-02-23 오후 10 36 09" src="https://user-images.githubusercontent.com/3426052/75113014-04417e80-568d-11ea-97e1-dc4274465b2f.png">
<img width="328" alt="스크린샷 2020-02-23 오후 10 30 53" src="https://user-images.githubusercontent.com/3426052/75113018-06a3d880-568d-11ea-83ae-c0d3f91296f5.png">
<img width="1006" alt="스크린샷 2020-02-23 오후 10 28 50" src="https://user-images.githubusercontent.com/3426052/75113019-073c6f00-568d-11ea-8bc1-73be6aa0c725.png">

**Comment by veldise** [comment]
로그와 SMS 데이터 확인 결과,
`2020:02:21 11:38:25.970` 시점부터 Angora가 Internal Server Error를 반환하면서 메모리 사용량이 대폭 줄어든 것으로 보입니다.
![image](https://user-images.githubusercontent.com/3411842/75122991-e0128b80-56e6-11ea-9d81-b4b0b0071734.png)

`2020:02:22 16:19:36.016` 시점 이후 로그가 없는 것으로 보아 이 시점에 Studio 서비스가 shutdown 된 것으로 생각됩니다.

**Comment by sunghoon** [comment]
특정 시점의 장애 상황으로 닫습니다.
