### ISSUE TITLE
[데이터추가] 에서 생성되는 테이블이름이 길면 잘립니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1919]
## 버그 설명 ##
DB 브라우저에서는 
SUWON_CITY_STATISTICS_GU_DONG_ACCORDING_TO_POPULATION_STATUS
라는 이름으로 테이블 생성이 완료 되는데

**데이터추가**  메뉴에서는 
SUWON_CITY_STATISTICS_GU_DONG_ACCORDING_TO_POPULAT
로 잘려서 테이블이 생성됩니다.

<img width="583" alt="스크린샷 2020-02-24 오전 10 22 41" src="https://user-images.githubusercontent.com/5126497/75124037-de00fa80-56ef-11ea-8fdf-881895492b37.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
IRIS-DB에 테이블 명 길이 제한이 있는것으로 압니다.
안내 없이 잘라버리는 부분은 수정하도록 하겠습니다.

**Comment by veldise** [comment]
현재 테이블명 입력란에 50글자 제한이 걸려있었습니다. 100글자로 변경하겠습니다.
