### ISSUE TITLE
analyzer: 융합(상관)분석 방법 필요

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1920]
## 기능 요청 ##
- 요청자: 채병석 선임님
- analyzer(데이터 브라우저)에서 서로 다른 2개 이상의 데이터를 동시에 다루어 연관 분석할 수 있는 방법이 필요합니다.
  - ex) 모델 생성시, 대상 데이터를 2개 선택

**Comment by sunghoon** [comment]
관리되지 않는것 같아 이슈를 닫습니다. 
@채병석 중요한 기능이면 다시 요청해 주시기 바랍니다.
