### ISSUE TITLE
[NMS+]studio 에서 datasource='DSMS' & IRIS 설정 가이드

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1921]
## 기능 요청 ##

datasource='DSMS' & IRIS 데이터 조회시 파티션과 시간조건을 캘린더와 어떻게 설정해야하는지 가이드 부탁드립니다.

![iris](https://user-images.githubusercontent.com/5468183/75129693-7ce81f80-570d-11ea-9171-59697603a7cd.PNG)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@cosmos-mc 해당 상황과 같은 경우를 설명하기 위한 메뉴얼을 준비해 주세요.
