### ISSUE TITLE
[NMS+]studio 시각화 옵션(조건부 서식) 미적용됨

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1922]
## 버그 설명 ##
테이블의 시각화 옵션에서 "조건부 서식" 에서 컬럼의 데이터 타입이 text 이면 셀서식에 따라 색상이 잘 적용되나
데이터 타입이 integer 이면 셀서식이 적용안됨

![iris_11](https://user-images.githubusercontent.com/5468183/75131087-b40dff00-5714-11ea-871a-be75827b8d3a.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#1860 동일 이슈입니다.
금주 패치 예정입니다.

**Comment by jjinylee** [comment]
1. 해당건의 정수 type 일경우는 <,<=, >, >=  범위 비교에 따라 색상이 변경되길 원함.
2. 전체 row 색상변경이 아닌, 해당 컬럼에만 색상을 줄수있도록 옵션 처리 요청

**Comment by veldise** [comment]
@jjinylee 
2번은 https://github.com/mobigen/IRIS-BigData-Platform/issues/1778#issuecomment-582179085 에서 진행중입니다.
1번은 별도 이슈로 분리하겠습니다.

**Comment by veldise** [comment]
#1941

**Comment by veldise** [comment]
1860 이슈 해결되어 닫습니다.
