### ISSUE TITLE
[수원시] DB 브라우저 - 다운로드 기능 버그

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1924]
## 버그 설명 ##
10만건이 넘어가는 데이터를 select * 한 뒤에(개발자 모드) "다운로드" 버튼 클릭시 다운로드 파일이 생겨서 완료된 것처럼 보이나, 실제 파일을 열어보면 특수문자 1건만 찍힘

## 재현하는 방법 ##
동작을 재현하는 방법 :
데이터가 많은 테이블의 "개발자 모드"로 SELECT
이후 "다운로드" 클릭.

## 예상한 행동 ##
전체 데이터 다운로드

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
--> 감리와 함께 진행한 테스트 입니다. 해당 기능의 이슈를 제기했습니다

**Comment by veldise** [comment]
#1756 와 동일 이슈로 생각됩니다.

@anhm

**Comment by ollehQ** [comment]
테스트를 진행해 본 결과 IRIS DB의 Error와 관련이 있는 것이 확인되었습니다.
IRIS DB에 Error가 발생하게 된다면, 다운로드를 하게 된다면 빈 파일이 나오게 됩니다.
Backend location file의 블록 파일의 위치정보의 소실 또는 Process Memory Limit로 인한 것으로 예상하고 있습니다.
만일 파일 위치 정보의 소실일 경우에는, Recover의 명령어를 통해 복구작업을 실행해야 합니다.
Process Memory Limit일 경우에는, 파티션의 범위를 줄이거나, dlimit query 구문을 사용하는 방법이 있을 것 같습니다.
혹시라도 같은 이슈가 발생할 경우에는, 이슈를 한 번만 다시 등록 부탁 드립니다.
해당 이슈는 닫도록 하겠습니다.
