### ISSUE TITLE
교통빅데이터 / 오픈랩 / 메뉴설정에서 표시옵션에 대한 변경정보가 적용되지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1925]
## 버그 설명 ##
메뉴설정에서 표시옵션에 대한 정보를 변경해도 적용이 되지 않고 계속 나타남.
"새로고침" 실행하면 다시 체크된 상태로 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. https://openlab.diamond-e.kr:10443/secret_login#/ 접속

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/75141409-3659eb80-5734-11ea-885f-4abf0b68a2ae.png)

![image](https://user-images.githubusercontent.com/4444717/75141547-846eef00-5734-11ea-9f93-df87e4b8d7fe.png)

![image](https://user-images.githubusercontent.com/4444717/75141669-d57ee300-5734-11ea-9b38-0d14c4a7397a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by JeongHeeDong** [comment]
도로공사 내부 IRIS Analyzer도(https://180.148.181.193/#/) 동일하게 메뉴설정 기능이 동작하지 않음

**Comment by JeongHeeDong** [comment]
@veldise (최영철 책임님),

동일한 현상이 다시 발생하고 있습니다.

![image](https://user-images.githubusercontent.com/4444717/77973091-3a2dee80-732e-11ea-818b-3c28fd9155d5.png)

**Comment by veldise** [comment]
@big-mobigen 
해당 사이트 `meta` 서비스 버전 정보를 요청합니다.

**Comment by big-mobigen** [comment]
@veldise 
교통빅데이터 플랫폼 플랫폼사이트(https://180.148.181.193/#/)에 meta 정보는 다음과 같습니다. 

 meta-dist-v2.5_df330e3-20200122.tar.gz

**Comment by veldise** [comment]
@JeongHeeDong 
현재 배포된 meta 서비스가 해당 이슈가 수정되기 전 버전(1월 2일 버전)입니다.
2월 6일 이후 버전을 설치하면 문제가 해결될 것입니다.

**Comment by big-mobigen** [comment]
@veldise @JeongHeeDong 

금일 점심시간을 활용하여 플랫폼사이트(https://180.148.181.193/#/)에 패치를 진행하겠습니다.

**Comment by big-mobigen** [comment]
플랫폼사이트(https://180.148.181.193/#/)에 정상동작을 확인하였습니다.

**Comment by veldise** [comment]
해결되어 닫습니다.
