### ISSUE TITLE
[수원시] 데이터 모델 - 검색 - 조회오류

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#1926]
## 기능 요청 ##
데이터 모델 생성 이후.
데이터브라우저 > 검색 에서 전체 시간 선택 이후 검색 시 에러 알람 발생

## 원하는 솔루션 설명 ##
정상적인 데이터 조회

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
![er1](https://user-images.githubusercontent.com/8993205/75203805-88415680-57b2-11ea-896f-40a268ed793e.PNG)

**Comment by veldise** [comment]
@anhm 
확인 부탁드립니다.

**Comment by veldise** [comment]
오래된 이슈라 닫습니다. 재현되면 Reopen 해주시기 바랍니다.
