### ISSUE TITLE
[KOTRA]트렌드차트 갱신 방법 변경요청

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#1927]
## 기능 요청 ##
![A3B84CCC-70BE-450F-808F-E69FB63C6BCF](https://user-images.githubusercontent.com/18297120/75204392-1964fd00-57b4-11ea-9a68-3a25f40b62ab.jpeg)

## 원하는 솔루션 설명 ##
1분 주기로 서버 자원 모니터링을 하고 있는데, 
갱신시 화면 전체가 리프레쉬 되는것이 굉장히 불편합니다. 
최신정보만 추가되어 화면전체가 갱신되지 않도록 해주세요.

**Comment by veldise** [comment]
#1842 동일 이슈로 생각됩니다.

**Comment by sunghoon** [comment]
연결된 이슈에서 처리된것으로 보고 닫습니다.
