### ISSUE TITLE
studio: Map / 도형 - 경계선 추가

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1928]
## 기능 요청 ##
- 기능 제안: 배성훈 그룹장님
- studio: Map / 도형 - 경계선(border) 추가

## 내용
Map 객체의 시각화 유형인 '도형'을 이용하여 지역맵과 유사하게 데이터 시각화를 하였을 때, 인접한 두 개의 도형이 같은 or 유사한 값이면 경계선이 없어 구분하기가 어렵습니다.

- 먼저 임시 조치로 `#cccccc` 색상으로 경계선 처리

**Comment by swish1995** [comment]
도형의 경계선의 색상과 두께에 대해 map 상수로 정의 되어 있으나 사용하지 않고 
경계색을 도형내부 색과 같이 설정하는것으로 확인했습니다.
임시로 경계 색을 `#cccccc` 로 처리한후
추후 경계색, 경계의 두께(필요시) 옵션 처리 하도록 하겠습니다.

**Comment by sunghoon** [comment]
기능 배포되어 있는 것으로 보고 닫습니다.
