### ISSUE TITLE
교통빅데이터 플랫폼 / 고급시각화 / 파이차트의 옵션이 적용되지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1929]
## 버그 설명 ##
고급시각화에서 파이차트의 옵션설정에서 "데이터값표시" 옵션을 "끄기"로 설정해도 계속 값이 나타남

ValueLinkU 사이트도 확인결과 동일하게 옵션설정이 동작하지 않고 있음.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. https://openlab.diamond-e.kr:10443/#/
2. http://bis.valuelinku.com/secret_login#/

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/75207883-571a5380-57bd-11ea-97ee-54f50673acf1.png)

**Comment by JeongHeeDong** [comment]
ValueLinkU 시험 결과

![image](https://user-images.githubusercontent.com/4444717/75208198-3b637d00-57be-11ea-958b-abd2fd385f25.png)

**Comment by veldise** [comment]
#1914 동일 이슈로 생각됩니다.

**Comment by veldise** [comment]
패치로 해결되어 닫습니다.
