### ISSUE TITLE
보고서 라디오박스에서 DSMS substr

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#1932]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
 sbustr을 이용하여 라디오박스를 만들려고 하는데, 결과값이 나오지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
SELECT substr("20200201",1,6) as string
from "테이블 명"
group by string;

![image](https://user-images.githubusercontent.com/16331916/75303728-e2aae780-5884-11ea-9f8a-9815ef074110.png)

DB 브라우저에서는 결과가 나옴

![image](https://user-images.githubusercontent.com/16331916/75303753-f35b5d80-5884-11ea-9054-6ac3057a95ac.png)

보고서 라디오 버튼에서는 결과가 나오지 않음

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@kim3163 
사용하신 테이블 명이나 SQL을 알려주시면 조금 더 빠른 현상 파악이 될 것 같습니다. 제공 부탁드립니다.

**Comment by veldise** [comment]
답변이 없으셔서 이슈 닫습니다.
