### ISSUE TITLE
[보고서]텍스트 상자의 ReadOnly 색상

### ISSUE THREAD

**Issue by AlexNa** [mobigen/IRIS-BigData-Platform#1934]
## 기능 요청 ##
보고서 작성시 텍스트 상자 객체의 속성을 ReadOnly 로 변경하면 배경색이 회색으로 고정됩니다.
배경색을 사용자가 설정 가능하도록 요청합니다.
![image](https://user-images.githubusercontent.com/3666301/75401344-341aab80-5945-11ea-9d77-b108e3427a7d.png)

## 원하는 솔루션 설명 ##
레벨 객체의 글꼴 속성을 텍스트 상자에도 추가를 요청합니다. 
![image](https://user-images.githubusercontent.com/3666301/75401363-44cb2180-5945-11ea-88ef-49bc7fec08ec.png)

## 고려한 다른 대안 ##
 레벨 객체에 "디폴트 값 선택" 속성의 추가를 요청합니다.
![image](https://user-images.githubusercontent.com/3666301/75401393-5f04ff80-5945-11ea-8eb1-db161194a96c.png)

**Comment by sunghoon** [comment]
기능 변경에 따른 재현 불가로 닫습니다.
다른 특이사항이 있다면 새 이슈로 등록해 주세요.
