### ISSUE TITLE
[보고서]차트의 시리즈별 색상의 사용자 선택

### ISSUE THREAD

**Issue by AlexNa** [mobigen/IRIS-BigData-Platform#1935]
## 기능 요청 ##
막대형,원형 차트의 시리즈별 색상을 사용자가 설정할 수 있도록 속성 추가를 요청합니다.
![image](https://user-images.githubusercontent.com/3666301/75401688-421cfc00-5946-11ea-804e-54c54123187a.png)

## 원하는 솔루션 설명 ##
차트의 시각화 옵션에서 시리즈에 대한 색상을 설정 가능하도록 요청합니다.
![image](https://user-images.githubusercontent.com/3666301/75401810-93c58680-5946-11ea-9ac5-d7b6adbb5846.png)

![image](https://user-images.githubusercontent.com/3666301/75401779-7d1f2f80-5946-11ea-9475-20434869461e.png)

## 고려한 다른 대안 ##
각 시리즈별 색상 설정이 아니라면 엑셀의 데이터 계열 서식과 유사한 색상 설정이 가능하도록 요청합니다.
![image](https://user-images.githubusercontent.com/3666301/75402181-8a88e980-5947-11ea-9c76-2665aa0eeff4.png)

**Comment by JeongHeeDong** [comment]
각종 차트의 시리즈 생상 및 배경 색상등을 설정 할 수있는 기능에 대한 진행이 어떻게 되고 있나요?
현재 검토만 하고 있는 것인지 확인 부탁 드립니다.

**Comment by veldise** [comment]
@JeongHeeDong 
네, 현재는 '보고서 작성 편의 기능'과 지도 객체의 각종 기능 추가/개선 등을 진행 중입니다.
본문 기능은 4월에 진행 가능한지 검토중입니다.

**Comment by veldise** [comment]
개발은 완료되었으나, 기능 테스트 중이며 5월 7일 배포 예정입니다.

**Comment by veldise** [comment]
아래와 같이 기능 추가되어 닫습니다.

![image](https://user-images.githubusercontent.com/3411842/81255134-dce13780-9067-11ea-8b10-eb850987ff1a.png)
