### ISSUE TITLE
[보고서] 보고서 내부의 객체 목록 및 선택 기능

### ISSUE THREAD

**Issue by AlexNa** [mobigen/IRIS-BigData-Platform#1936]
## 기능 요청 ##
보고서에 존재하는 객체목록의 확인 및 객체 선택 기능을 요청합니다.(레이어 형태로 작성시 뒤에 가려진 객체를 선택할 수 없습니다.)
![image](https://user-images.githubusercontent.com/3666301/75402830-3e3ea900-5949-11ea-9d26-5d0c024ec26b.png)

## 원하는 솔루션 설명 ##
전체 변수명 보기에서 해당 오브젝트를 선택할 수 있도록 요청합니다.
![image](https://user-images.githubusercontent.com/3666301/75402872-5f9f9500-5949-11ea-9fdd-3bea64c943e7.png)

**Comment by sunghoon** [comment]
@eumminsun 해당 기능에 대한 컴토 바랍니다.
