### ISSUE TITLE
[보고서] 객체의 속성값 적용 시점/초기화 현상

### ISSUE THREAD

**Issue by AlexNa** [mobigen/IRIS-BigData-Platform#1937]
## 버그 설명 ##
1. 객체의 속성에 특정값을 입력합니다.
![image](https://user-images.githubusercontent.com/3666301/75403160-37fcfc80-594a-11ea-8cff-62edfd9476e2.png)

2. 보고서의 바탕화면을 클릭하면 1번에서 입력한 설정값이 사라집니다.
![image](https://user-images.githubusercontent.com/3666301/75403242-7bf00180-594a-11ea-9633-a5cd96834dbe.png)

3. 1번에서 입력 후 다른 곳으로 포커스 이동시 설정값이 적용됩니다.
![image](https://user-images.githubusercontent.com/3666301/75403278-91fdc200-594a-11ea-8f97-fdf44de14997.png)
 
## 예상한 행동 ##
보고서의 바탕화면을 클릭시에도 설정값이 초기화 되지 않도록 수정 요청합니다.
혹은 '설정'/'적용' 버튼을 클릭하여 적용할 수 있도록 수정 요청합니다.

**Comment by sunghoon** [comment]
기능 변경에 따른 재현 불가로 닫습니다. 
다른 특이사항이 있다면 새 이슈로 등록해 주세요.
