### ISSUE TITLE
[NMS+]studio 팝업 종료후 refresh 요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1939]
## 기능 요청 ##
현재 popup / 포틀릿등으로 화면 띄울때 main 화면이 리플레쉬 되는데
CRUD 기능이 추가되면서 추가/수정/삭제 이후 ( 띄울때가 아닌 팝업 종료시 ) main 화면의 데이터를 리플레쉬하는 방안이 필요합니다.

제가 생각할때 popup / 포틀릿등으로 화면 띄울때 main 화면이 리플레쉬 되는 이유를 잘 모르겠슴.
( 이게 타보고서 적용시 필요한 이유가 있어서 그런건지... )

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise @eumminsun 해당 이슈에 대한 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
데이터 객체가 없고 RESTful-API 객체만 있을 당시에는 기능이 없어 불가능한 동작이었습니다.

현재 버전에서는 아래와 같이 데이터 객체의 실행 트리거를 팝업으로 설정하면, 팝업이 닫혔을 때 데이터를 실행하므로
이슈 본문에 해당하는 동작이 가능합니다.

![image](https://user-images.githubusercontent.com/3411842/93970467-24632880-fda9-11ea-9f1a-2ec1a17b6a0b.png)

**Comment by sunghoon** [comment]
@jjinylee 요청 사항에 대한 방안이 마련된 것으로 보고 닫습니다. 
다른 요청 사항 이였다면 새 이슈로 등록 바랍니다.
