### ISSUE TITLE
studio: Chart / 조건부 서식 - 컬럼이 숫자 유형일 경우는 <,<=, >, >= 및 범위 비교 연산 추가

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1941]
## 기능 요청 ##
studio: Chart / 조건부 서식 - 컬럼이 숫자 유형일 경우는 <,<=, >, >= 및 범위 비교 연산 추가

**Comment by sunghoon** [comment]
@veldise 해당 이슈 최종 진행 상태를 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
아직 기획 및 개발이 진행되지 않았습니다.

**Comment by sunghoon** [comment]
@eumminsun 관련 기능 검토 바랍니다.
