### ISSUE TITLE
[Studio] 지도에서 지도의 축소/확대 기능을 OFF 할 수 있는 설정을 추가해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1942]
## 기능 요청 ##
지도를 인포그래픽처럼  사용하거나 특정 행정지역에서 특수 용도로 사용할  때는 확대/축소 기능이 불필요하고,
오히려 손가락이나 마우스 오동작으로 지도가 확대/ 축소 되어 불편할 때가 많습니다.
그래서
지도 에서 확대/축소 기능 OFF 할 수 있는 설정 기능이 있으면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
아래와 같이 지도 레이어의 시각화 옵션으로 기능이 추가되었습니다.

![image](https://user-images.githubusercontent.com/3411842/79930027-61399500-8482-11ea-8abd-dd874dbe785f.png)
