### ISSUE TITLE
[NMS+]date 관련 콤포넌트의 max 기간범위 제약 설정기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1946]
## 기능 요청 ##
이력, 통계등의 조회기능에서 기간을 설정하는 콤포넌트에서
조회 기간 범위를 제약을 걸수 있는 방안이 있는지 문의드립니다.

사용자가 무조건 몇개월 데이터를 한꺼번에 조회할수도 있기때문에 
설정가능한  기간 범위의 제약을 두고 싶은데( 예를들어, start~end  기간이 1주일, 3개월 기간범위 ) 가이드 부탁드립니다.

없다면 조회범위 기간을 제약걸수 있는 기능 요청드립니다.
(시스템 운영/ 보호차원에서도 꼭 필요합니다. )

아래와 같이 통계조회 보고서를 사용하고있습니다

![image](https://user-images.githubusercontent.com/5468183/75510015-d497cb00-5a2c-11ea-9203-0a483836a56b.png)

- 쿼리  ( DSMS 로 )

/*+ LOCATION ( PARTITION >= replace('${sdate_picker}','') || '000000'  AND  PARTITION <= replace('${edate_picker}','/','') || '000000') */ 
 select substr(sdatm, 1,4) || '/' || substr(sdatm, 5,2)  
|| '/' || substr(sdatm, 7,2)
|| ' ' || substr(sdatm, 9,2)
|| ':' || substr(sdatm, 11,2) as SDATM,
	DEV_NAME, INSTANCE, INST_DESCR, CPU_USAGE, DEV_ID
	from PER_CPU_USAGE_5M	
where 1=1
order by SDATM, DEV_ID
;

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@jjinylee 
현재 아래와 같이 '시작/종료 날짜'를 설정하여 선택할 수 있는 날짜 범위를 제한할 수 있는 기능이 있습니다만, 
말씀하시는 것은 혹시 '초기 날짜'는 현재 날짜(now)로 설정하고, 범위 제약은 '최근 3개월'과 같이 상대적으로 설정할 수 있는 기능인가요?

![image](https://user-images.githubusercontent.com/3411842/75510367-15dcaa80-5a2e-11ea-9807-0e87f9504ede.png)

![image](https://user-images.githubusercontent.com/3411842/75510373-1e34e580-5a2e-11ea-9e8d-720754d78a09.png)

**Comment by jjinylee** [comment]
![image](https://user-images.githubusercontent.com/5468183/75510911-cb5c2d80-5a2f-11ea-8393-8efbf1546b4c.png)

![image](https://user-images.githubusercontent.com/5468183/75510934-d911b300-5a2f-11ea-9487-96667cf25628.png)

보통 이력조회를 할때 캘린더에서 시작~종료날짜는 사용자가 설정하고
조회기간을 1년/몇개월 이내만 조회하도록 하는 기능인데

현재 시각화 옵션은 시작과 종료날짜가 fix 됩니다.

- 시작과 종료날짜는 사용자 지정에, 시작~종료날짜의 기간일자>360일 이상은 안된다던가 이런 기간 제약조건이 필요하고
- DSMS 의 IRIS 쿼리에는 start_날짜, end_날짜에 다른 변수를 넣어야해서 date_time_picker 를 2개써야하는데 이럴경우는 어떻게 할지 모르겠습니다.

**Comment by jjinylee** [comment]
@rhcpn 팀장님~~~이 기능 꼭 필요합니다

**Comment by veldise** [comment]
해당 기능은 6월에 계획중입니다.

**Comment by sunghoon** [comment]
해당 기능은 배포 된것 같습니다. 혹시 다른 내용이였다면 새 이슈로 등록 부탁드립니다.
