### ISSUE TITLE
[GNB] 접속 후 일정시간이 지나면 메뉴 이동시 에러 발생

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1947]
## 버그 설명 ##

현재 GNU가 배포되어있는 사내 서버 (http://192.168.100.180:8888/) 에 로그인 후,

일정 시간이 지난 이후에 메뉴 이동을 시도하면 다음과 같이 두 번의 에러 메시지가 차례로 발생합니다.

두 번 정도 발생했는데,

아무 행동도 하지 않을시에만 발생하는지, 계속 작업을 하는 도중에도 발생하는지 정확히는 모르겠습니다.

최소한 작업을 계속 진행하는 도중에 끊긴 적은 없어서, 전자의 경우로 추정은 하고 있습니다.

<img width="1453" alt="스크린샷 2020-02-28 오후 1 37 13" src="https://user-images.githubusercontent.com/23020977/75510925-d57e2c00-5a2f-11ea-8b87-48c3ee4a9f34.png">

<img width="1463" alt="스크린샷 2020-02-28 오후 1 37 26" src="https://user-images.githubusercontent.com/23020977/75510933-d8791c80-5a2f-11ea-8925-57f201d750b8.png">

로그아웃 이후에 다시 로그인하면 정상작동합니다.

만일 세션 문제라면 세션 만료시 자동으로 로그인 화면으로 이동한다거나, 적절한 논리 정의가 필요할 것 같습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://192.168.100.180:8888/ 로그인합니다
2. 일정시간 이후 메뉴 이동을 시도합니다 (이 부분에 대한 정확한 시간은 몰라 애매합니다)
3. 상기 에러가 발생합니다.

**Comment by rhcpn** [comment]
안녕하세요
이전 버전과 달리 세션타임아웃 시간이나 기준이 상이하여 발생한 문제 입니다.
해당 부분은 설정 조정 및 에러메세지를 적절히 설정하도록 하겠습니다.
