### ISSUE TITLE
[GNB] 일반 유저로 DB브라우저 접근시 'DB 서버속에 문제가 발생했습니다' 에러

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#1948]
## 버그 설명 ##

현재 GNU가 배포되어있는 사내 서버 (http://192.168.100.180:8888/) 에 일반 계정으로 로그인시 DB 브라우저에거 다음과 같이 DB 접속을 할 수 없다는 에러 팝업이 생성됩니다.
-> 메인 개발서버 (http://192.168.100.180/#/) 에서도 동일현상 발생

![스크린샷 2020-02-28 오후 3 06 30](https://user-images.githubusercontent.com/23020977/75515048-622ee700-5a3c-11ea-9f38-51da16a0c8ab.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://192.168.100.180:8888/ root 계정으로 접속 후 유저 생성
2. 생성한 유저로 로그인
3. DB 브라우저 접근
4. 에러 발생

**Comment by rhcpn** [comment]
안녕하세요 혹시 접속 정보 등을 알수 있을까요?
저희쪽에서도 테스트 해보려면 정보가 필요할듯 합니다.

**Comment by leehaejoon** [comment]
@rhcpn 

테스트 할 수 있는 계정을 생성하였습니다. 계정 정보는 아래와 같습니다.

```
id: issuetest
pw: issue1948
```
