### ISSUE TITLE
[NMS+]IRIS 쿼리 문의

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#1949]
## 기능 요청 ##
저희 IRIS 쿼리에서
text to date  날짜포맷을 바꾸는 함수가 있나요 ?

strftime( '%Y-%m-%d', SDATM )  이런형태가 있나요?

전에는 아래처럼 substr 로  썼었는데 혹시 datetime formatting 함수가 있는지 문의드립니다.

/*+ LOCATION ( PARTITION >= '20200226000000'  AND  PARTITION <=  '20200228000000') */ 
 select substr(sdatm, 1,4) || '/' || substr(sdatm, 5,2)  
|| '/' || substr(sdatm, 7,2)
|| ' ' || substr(sdatm, 9,2)
|| ':' || substr(sdatm, 11,2) as SDATM,
	DEV_NAME, INSTANCE, INST_DESCR, CPU_USAGE, DEV_ID
	from PER_CPU_USAGE_5M
where 1=1
order by SDATM, DEV_ID
;

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by jjinylee** [comment]
IRIS 에서는 이렇게 사용하면 된다고 하네요

 **STRFTIME('%Y-%m-%d %H:%M:%S', TO_DATE('20181122010203', '%Y%m%d%H%M%S'), 'unixepoch', 'localtime')**



그럼, angora 에서는 string to date 날짜 포맷팅 함수가 있나요?

* |"select STRFTIME('%Y/%m/%d %H:%M:%S', TO_DATE(DATETIME, '%Y%m%d%H%M%S'), 'unixepoch', 'localtime') AS SDATM  from angora"

이렇게 하면 IRIS 에서 사용할수 있는 date 포맷팅 함수가 에러가 납니다.

angora 에서 사용할수 있는 string to date 날짜 포맷팅 함수 확인부탁드립니다.
![캡처](https://user-images.githubusercontent.com/5468183/75757413-a809e900-5d75-11ea-8837-7250b7ccd00b.PNG)

**Comment by seoryjj** [comment]
- 검색어 : TO_DATE 문을 쓰니 나옵니다.  

`sql " SELECT TO_DATE(CAST(UNIX_TIMESTAMP(CTIME_STR, 'yyyyMMdd') AS TIMESTAMP)) AS newdate  , * from angora"`

<img width="1062" alt="스크린샷 2020-07-31 오전 9 30 04" src="https://user-images.githubusercontent.com/5126497/88987299-725f3100-d310-11ea-9cb5-7ee1ce521e8c.png">

- 검색어 :  TO_TIMESTAMP 예제

`* |  fields CTIME |  sql   " SELECT TO_TIMESTAMP(CAST(UNIX_TIMESTAMP(CTIME, 'yyyyMMddHHmmss') AS TIMESTAMP)) AS newdate  , * from angora"`

<img width="1161" alt="스크린샷 2020-07-31 오전 9 34 53" src="https://user-images.githubusercontent.com/5126497/88987511-1f39ae00-d311-11ea-9a24-445a50f22cc5.png">

**Comment by sunghoon** [comment]
@seungfwani 위 내용을 컴토하여 관련 DSL Command 개발을 진행해 주세요.

**Comment by seungfwani** [comment]
최근 추가된 명령어 [typecast](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/typecast.html) 를 사용하면 타입변환을 할 수 있습니다.

모델 : `EDU_Beijing_air_2013_2017_18_TEXT시간 - VIEW`
쿼리 : 
```
* | fields CTIME, CTIME as NEWTIME | typecast NEWTIME timestamp "YYYYMMDDHHmmss"
```
![Screen Shot 2020-09-23 at 1 23 17 PM](https://user-images.githubusercontent.com/46172579/93966553-f4635780-fd9f-11ea-835d-09caed04e735.png)
