### ISSUE TITLE
[PSI] 시각화 / 막대형 그래프 그룹시 막대 중심이동 

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1950]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

막대형 그래프에서 x축과 그룹에 동일하게 text 를 가했는데, 
x축 막대 중심에서 이동한듯 합니다. 
다음주 내에 PSI 쪽 과제에서 시연해야 하는터라 빠르게 확인이 필요합니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 글로벌 테이블 PSI.CRIME_PER_YEAR

2. 전체시간

3. 조건:  *  POLICE_OFFICE='전국' AND CRIME='7대범죄'

4. 시각화로 이동 후 막대형 그리기 (x축: year, y축 count의 합계)

5-1. 그대로 그리기 : 막대중심이동 안함

5-2. 그룹추가: year : 막대중심이동 함

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
<그룹 : year(text) 안한 경우 >
<img width="1397" alt="스크린샷 2020-03-02 오전 11 29 18" src="https://user-images.githubusercontent.com/36151180/75640644-174de300-5c79-11ea-861d-0cf210a994ac.png">

<그룹 : year(text) 한 경우 >
<img width="1675" alt="스크린샷 2020-03-02 오전 11 24 58" src="https://user-images.githubusercontent.com/36151180/75640612-01402280-5c79-11ea-8854-8beef245a07a.png">
## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
x축과 그룹을 동일 컬럼으로 지정하신 이유가 무엇인가요?
x축과 그룹을 동일 컬럼으로 지정하게 되면, x축에 표현된 카테고리 개수만큼 그룹이 생기므로, 위와 같은 결과는 정상입니다.

예를 들어
x축 2016 인 경우, 그룹: 2016 의 값은 존재하지만
그룹: 2017, 그룹: 2018, 그룹: 2019 값은 존재하지 않습니다.

**Comment by joohj7** [comment]
@veldise veldise 시연에서 iris를 태블로(tableau)와 비슷하게 구현하는것이 현재 목표인데,
아래 그림처럼 태블로에서 구현된 형태에서는 막대 그래프별 색을 지정할 수가 있어서, 
그대로 진행하려다 보니 색에 해당하는 그룹을 x축과 동일하게 지정한 것 입니다.  
![1](https://user-images.githubusercontent.com/36151180/75647136-58e98880-5c8f-11ea-8879-e63e54c95264.png)

x축과 그룹(범례)가 동일한 경우는 다른 오픈소스(python, r)에서도 종종 존재하는 경우입니다. 

막대의 색을 정하는 다른 방법이 있다면 알려주시면 감사하겠습니다.

**Comment by veldise** [comment]
@joohj7 
막대별로 색을 다르게 지정하는 기능은 개발이 필요하며, 3월중에는 어렵습니다.

**Comment by veldise** [comment]
@joohj7 
x축과 그룹(범례)가 동일한 경우에 대하여 사례를 알려주시면
차후 교육이나 기능 개발할 때 참고할 수 있을 것 같습니다.

**Comment by joohj7** [comment]
1) x축의 값을 색을 분리하여 보고싶은 사용자의 경우(그때에는 x 축의 값이 text 일 경우가 많습니다.)  
그때에 x 축에 그룹과 같은 색을 취하는 경우가 있습니다. 

2)  x축의 각 그룹이 다른 경우가 있을 수도 있으나 x와 그룹의 교집합값이 한쪽으로 쏠리는 경우는
그 막대의 색상이 변하는 경우가 있을 수도 있습니다.  

아래와 같은 예가 있을수 있습니다.
<x축과 그룹이 같은경우 >
<img width="1067" alt="스크린샷 2020-03-04 오전 11 32 10" src="https://user-images.githubusercontent.com/36151180/75839980-85c3aa00-5e0d-11ea-9128-eb85785f7877.png">

<x 축과 그룹이 다르지만, 해당되는 값이 1가지밖에 없는 경우>
<img width="992" alt="스크린샷 2020-03-04 오전 11 33 05" src="https://user-images.githubusercontent.com/36151180/75839985-8b20f480-5e0d-11ea-820c-f2ddd378470a.png">

**Comment by veldise** [comment]
@joohj7 
상세히 설명해주신 것은 감사합니다만, 기술하신 것처럼 첫번째 예는 x축 = 그룹인 경우가 아니라, **그룹을 설정하지 않은 경우**입니다. 그룹을 설정하지 않았는데 x축과 그룹이 같다고 볼 수 없습니다.
x축이 group by 연산에 의한 결과이므로 '그룹'이라고 지칭할 수도 있겠으나, 막대형 차트의 그룹(범례)와는 다릅니다.

파이썬의 seaborn 에서는 그룹을 설정하지 않은 경우 각 막대의 색상을 다르게 지정해주는 것으로 보이며,
IRIS Analyzer 및 Studio 에서 사용하고 있는 Highcharts library에서는 동일 색상으로 지정합니다.

**Comment by joohj7** [comment]
@veldise 
1) 번의 예시가 바르지 않았던 것 같아 r의 ggplot의 경우를 첨부합니다. 
<img width="1673" alt="스크린샷 2020-03-04 오후 1 20 26" src="https://user-images.githubusercontent.com/36151180/75845346-2620cb00-5e1c-11ea-82a1-0789f7f51bdd.png">

2) 두번째 예시의 경우도 r의 경우를 첨부합니다. 
<img width="1670" alt="스크린샷 2020-03-04 오후 1 32 21" src="https://user-images.githubusercontent.com/36151180/75845492-a34c4000-5e1c-11ea-9b2d-518642b2d2bb.png">

위의 경우 모두 그룹을 설정하였으나, 각 그룹의 값이 중심이동이 되지는 않는듯 합니다.

**Comment by veldise** [comment]
@joohj7 
x축의 값을 색을 분리하여 보고싶다는 사용자 요구사항이 있다는 것은 알겠습니다.
하지만 `fill` 설정은 색상을 설정하는 옵션으로 보입니다. x축 = 그룹(범례)의 경우라고는 생각되지 않습니다.
http://blog.naver.com/coder1252/220934712108

**Comment by sunghoon** [comment]
@veldise 최종 진행 상황을 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
시각화 메뉴의 '그룹' 용어 변경에 대해서 아직 검토가 되지 않았습니다. 검토 후 추가 댓글을 달겠습니다.

**Comment by sunghoon** [comment]
@veldise 이슈에 대한 Update된 정보 공유 바랍니다.
