### ISSUE TITLE
[PSI] 보고서 / 연도별 순서가 바르지 않음

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1951]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
x축의 연도별 순서가 바르지 않음 
다음주에 PSI 시연이 있어 빠르게 부탁드립니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 : 연도별 범죄(소유자: psi)

or 

1. 보고서: 세로형 막대
2. 분석탬플릿: 연도별 전국 범죄 전체 사건량

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
x축이 2016, 2017, 2018, 2019 가 되기를 바람. 
x축 변수인 year가 형태가 text이든, date이든, integer이든 숫자별 정렬이 되지 않았음

시각화에서는 정렬이 된것으로 확인했음. 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
<보고서: Date/TEXT>
<img width="818" alt="스크린샷 2020-03-02 오후 1 25 15" src="https://user-images.githubusercontent.com/36151180/75645632-0eb1d880-5c8a-11ea-8b49-c08749bcf40b.png">

<보고서: INTEGER>
<img width="702" alt="스크린샷 2020-03-02 오후 1 29 40" src="https://user-images.githubusercontent.com/36151180/75645649-196c6d80-5c8a-11ea-838e-972b06698f41.png">

<시각화>
<img width="1387" alt="스크린샷 2020-03-02 오후 1 34 06" src="https://user-images.githubusercontent.com/36151180/75645772-95ff4c00-5c8a-11ea-8476-ac5ea6a63a6a.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@joohj7 
보고서에서는 SQL이나 DSL을 이용하여 정렬을 해야 합니다.
ex)
```
* | where LOCATION like '9%' | adv bar count(*) SPLITROW LOCATION COLSIZE 500 | sort LOCATION
```
