### ISSUE TITLE
ValuelinkU 테이블 다운로드

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1952]
## 기능 요청 ##
테이블 다운로드 시 컬럼값에 콤마(,)가 있어서 실제 엑셀로 열어보면 컬럼이 밀려서 보이는현상
엑셀에서 CSV 출력할 때 처럼 TEXT나 콤마(,)가 있을 경우 큰 따옴표(")로 묶어주는 기능

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@SONHOJUN 
말씀하시는 테이블 다운로드가 IRIS 플랫폼 어느 기능인지 알려주시기 바랍니다.
DB 조회 / Analyzer(데이터 브라우저) / Studio(보고서) 각각 처리 방식이 다릅니다.

**Comment by SONHOJUN** [comment]
Studio 에서 다운로드입니다.

**Comment by veldise** [comment]
@anhm
Angora의 query download API 텍스트 한정자 설정 기능 추가에 대한 내용으로 생각됩니다.

**Comment by seungfwani** [comment]
운영서버에 아래 사진과 같이 텍스트 한정자 처리를 하였음을 알려드립니다.

![Screen Shot 2020-03-11 at 11 07 38 AM](https://user-images.githubusercontent.com/46172579/76375323-df395500-6388-11ea-86b9-f8ddb3eed757.png)
![Screen Shot 2020-03-11 at 11 07 02 AM](https://user-images.githubusercontent.com/46172579/76375326-e1031880-6388-11ea-9909-b0dd4905b18d.png)

**Comment by veldise** [comment]
@seungfwani 
혹시 본사 운영서버에는 아직 패치가 안 되었나요?

**Comment by seungfwani** [comment]
운영서버에 아래와 같이 배포하였습니다.

모델 : `date-float-test`
다운로드 결과 :
<img width="211" alt="Screen Shot 2020-03-24 at 6 07 56 PM" src="https://user-images.githubusercontent.com/46172579/77408034-70cdab80-6dfa-11ea-9062-a774229d4a1e.png">

**Comment by SONHOJUN** [comment]
@veldise 
해당 기능 ValuelinkU에 적용이 안되어 있는것 같은데 확인부탁드립니다.

**Comment by veldise** [comment]
@SONHOJUN 
해당 이슈에 대하여 UI는 처리 내용이 없습니다.

@seungfwani
ValueLinkU에 위 내용이 배포되었는지 확인 바랍니다.

**Comment by seungfwani** [comment]
ValuelinkU 서버에 배포 요청을 누락하여 오늘 배포요청 하였습니다.
배포가 완료되면 다시 코멘트 하도록 하겠습니다.

**Comment by SONHOJUN** [comment]
금일(5/15) 배포했고 기능동작 확인했습니다.
