### ISSUE TITLE
ValuelinkU 테이블 다운로드 시 컬럼 타입 분석 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1953]
## 버그 설명 ##
테이블 다운로드 시 컬럼 타입을 잘못 분석하여 TEXT인 컬럼이 FLOAT 형태로 인식되어 정상적인 값이 출력되지 않는경우
예) 2018.10 -> 다운로드시 -> 2018.1 로 표시
해당 값은 년.월 값인데 FLOAT 형태로 인식되어 2018.1로 표시되는 현상

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@SONHOJUN 
말씀하시는 테이블 다운로드가 IRIS 플랫폼 어느 기능인지 알려주시기 바랍니다.
DB 조회 / Analyzer(데이터 브라우저) / Studio(보고서) 각각 처리 방식이 다릅니다.

**Comment by SONHOJUN** [comment]
Studio(보고서) 입니다.

**Comment by veldise** [comment]
@SONHOJUN 
아래와 같은 임시 데이터로 테스트해본 결과 재현되지 않았습니다.
문제가 발생했을 때 지정한 데이터 모델 정보 / 검색어(DSL) 등이 필요합니다.

![image](https://user-images.githubusercontent.com/3411842/75649418-648c7d80-5c96-11ea-89d7-ebb1dda6fe53.png)

**Comment by SONHOJUN** [comment]
테이블에서는 정상으로 나오는데 csv 다운로드했을 경우 엑셀로 열어보면 
![image](https://user-images.githubusercontent.com/7067615/75649589-f8f6e000-5c96-11ea-902b-dc9393829160.png)
이렇게 2018.10 으로 나와야되는데 2018.1 로 나옵니다.

**Comment by veldise** [comment]
@SONHOJUN 
엑셀로 csv 파일을 열어서 발생하는 문제로 보입니다...
csv 데이터에는 문제가 없습니다.

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/1952#issuecomment-597407399

**Comment by veldise** [comment]
@SONHOJUN 
#1952 해결되어 닫습니다. 혹시 문제가 해결되지 않았다면 이슈를 Reopen 해주시기 바랍니다.
