### ISSUE TITLE
ValuelinkU 각 객체의 값이 공백일 경우 항목값이 전달되는 현상

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1954]
## 버그 설명 ##
데이터 조회 시 실제 공백으로 나와야하는 부분이 있어 전체적으로 값을 공백으로 만들어놨는데 현재는 값이 공백일 경우 항목에 해당하는 내용이 전달되어 데이터 조회가 안됨.
공백값을 사용할 수 있게 수정 필요

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@SONHOJUN 
Combo, Check&Radio 등의 목록 데이터를 '사용자 정의'로 설정하였고 각 항목별로 '값' 입력이 공백일 경우, 
'항목' 입력 내용을 '값' 입력으로 대체하게 되어있습니다. 이것은 데이터 설정 방법이 '사용자 정의'일 때에만 해당합니다.

비슷한 이슈가 NMS+ 에서도 있어서 본사 데모서버에는 패치를 진행하였습니다.
상세한 내용을 알려주시면 기능 개발없이 해결할 수도 있을 것 같습니다.

**Comment by SONHOJUN** [comment]
'사용자 정의'일 때입니다.
optional 처리라는게 '항목' 입력 내용을 '값' 입력으로 대체할지 선택하는 건가요?
그럼 대체안한다고하면 공백값이 그대로 적용되는건가요?
그게 맞다면 해당 기능으로 처리 가능할 것 같습니다.
사내 b-iris 에서 확인할 수 있는 사이트가 있으면 확인해보겠습니다.

**Comment by veldise** [comment]
@SONHOJUN 
제가 다소 헷갈리게 말씀드린 것 같습니다.
'사용자 정의'일 때, '항목' 입력란은 필수(required)이고, '값' 입력란은 선택 입력(optional) 입니다.
대체 여부를 선택할 수는 없습니다.

'사용자 정의'일 때에도 '값' 입력값을 '항목' 입력값으로 대체하지 않는 옵션 추가에 대하여 검토해보겠습니다.
