### ISSUE TITLE
[교통빅데이터 플랫폼] 클러스터 맵 출력 오류

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1956]
## 버그 설명 ##

클러스터 맵을 출력하면 circle은 범례정보만 나타남,
pointer는 이상한 형태로 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 접속 사이트 : https://openlab.diamond-e.kr:10443/secret_login#/login

## 스크린샷 ##

[Circle 출력]
![image](https://user-images.githubusercontent.com/4444717/75759052-45661c80-5d78-11ea-894a-ba4960429bf1.png)

[pointr출력]
![image](https://user-images.githubusercontent.com/4444717/75759204-89592180-5d78-11ea-97df-a953229698c7.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
확인 결과 해당 사이트는 1월 8일자 버전이 설치되어 있습니다.
본문 내용은 1월 22일 버전에서 해결된 내용으로 보입니다.

@big-mobigen 
교통빅데이터 플랫폼에 최신 버전 패치를 부탁드립니다.

**Comment by big-mobigen** [comment]
@veldise 
교통빅데이터 플랫폼에 패치를 진행하려합니다. 

위에 언급해주신 이슈내용 해결을 위해서 
sherman 서비스만 추가 배포 진행하겠습니다... 

1월22일 배포된 meta, studio 서비스 배포(보고서 mig)도 필요하다면 회신 부탁드립니다.

**Comment by veldise** [comment]
@big-mobigen 
1월 22일 버전을 배포하시는 것이라면 sherman 서비스만 배포해도 괜찮을 것 같습니다만
최신 버전이라면 일본어 언어 추가 등으로 인해 모든 서비스를 배포하셔야 합니다.

**Comment by big-mobigen** [comment]
@JeongHeeDong 
팀장님 교통빅데이터 플랫폼쪽에 일본어언어 추가된 버전에 대한 배포가 필요한지 확인 부탁드립니다. 

@veldise 
선임님 1월 22일 sherman 배포파일 위치를 찾지 못하고 있습니다... 
102.112, 100.180, 102.138 찾을수가 없습니다. ㅠㅠ

아래 버전코드에 해당하는 sherman 재빌드를 요청드립니다. 
sherman 1월 22일 버전코드 ac6c27a

**Comment by veldise** [comment]
@big-mobigen 
네 빌드해서 메일로 위치 알려드리겠습니다.

**Comment by big-mobigen** [comment]
@veldise @JeongHeeDong 

접속 사이트 : https://openlab.diamond-e.kr:10443/secret_login#/login
오픈랩사이트에 배포가 완료되었습니다.

**Comment by JeongHeeDong** [comment]
circle은 정상 동작 확인 하였습니다.

그러나,
pointer의 경우 여전히 정상 출력이 안되고 있습니다.
![image](https://user-images.githubusercontent.com/4444717/75973810-23f06680-5f19-11ea-887c-a31f4aee98f9.png)

**Comment by veldise** [comment]
@JeongHeeDong 
Pointer 동작 확인해보겠습니다.

**Comment by veldise** [comment]
@JeongHeeDong 
제가 돌려보기로는 현재 정상 동작하는 것 같습니다.
재현 방법을 조금 더 상세히 알려주시면 다시 확인해보겠습니다.

![image](https://user-images.githubusercontent.com/3411842/76374639-2888a500-6387-11ea-962a-cdecdbc34844.png)

**Comment by veldise** [comment]
오래된 이슈라 닫습니다. 혹시 현상이 재현되면 Reopen 해주시기 바랍니다.
