### ISSUE TITLE
보고서- 순간적으로 쿼리에러가 발생하고 이후 정상적으로 동작

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1957]
## 버그 설명 ##
보고서를 처음 들어갈때 아래와 같이 쿼리에러가 발생하고,
이후 쿼리가 정상적으로 동작하는 이슈가 발생하고 있습니다.

![스크린샷 2020-03-04 오전 10 41 05](https://user-images.githubusercontent.com/3415270/75836314-e8fd0e80-5e04-11ea-9634-b5f13263de4e.png)

해당 차트에는 2개의 트리거가 잡혀 있는데 아래와 같습니다.
- 체크 박스 (사용자 정의로 값을 미리 정의해둠)
- 콤포 박스 (쿼리를 이용해 데이터를 자동으로 읽어오도록 정의해 둠)

에러 상황을 파악해 보면,  에러가 발생할 때는 지속적으로 체크 박스의 데이터가 들어가지 않고 있는 상태입니다.

특이하게 미리보기를 하면 정상적으로 동작합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

보고서의 root계정의 test-2 로 생성해 두었습니다.

## 예상한 행동 ##
에러 없이 차트가 실행

**Comment by veldise** [comment]
@anhm 
혹시 '접수 죄종' check&radio 의 항목 탭에 트리거 설정이 걸려있는 이유를 알 수 있을까요?

**Comment by veldise** [comment]
일단 check&radio 에서 트리거 발생시키는 부분에 버그가 있는 것 같습니다.

**Comment by veldise** [comment]
아래와 같이 2가지 문제를 확인하였습니다.

1. 트리거 중첩 설정
    - check 항목 설정 대상: combo, chart
    - chart 실행 설정 대상: combo, check
2. check&radio 항목 기본값 설정시 트리거를 상시 발생

2번은 버그이고, 1번은 사용자 설정 미스로 인한 것으로 생각됩니다.
check 의 항목 설정에서 트리거 설정을 제거하면 일부분 정상 동작합니다.
