### ISSUE TITLE
[PSI] 보고서/ 콤보박스 설정변경시, 체크박스 디폴트 설정 오류

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1958]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

- 현재 콤보박스와 체크박스 모두 하나의 그래프에 트리거 옵션 설정이 되어 있는 상태입니다. 

체크박스에서 항목: 디폴트값 선택을 '전체선택'으로 눌러놨는데, 
콤보박스(예: 발생지방청) 를 defualt가 아닌 다른 값으로 변경하게 되면 
체크박스(예 : 접수죄종) 가 전체 선택 모두 안된 상태로 변경이 됩니다. 

그런데, 모두 선택이 안된 상태에서도 선택한것처럼 그래프는 나옵니다.  

다음주에 psi 시연이 있어 빠른 처리 부탁드립니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
psi계정의 보고서:  [분석2-1] 연도별 범죄(전체범죄/7대범죄) (주해지) 의 
2. 연도별 7대범죄 사건량 과 관련된 파란색 콤보박스와 체크박스 
참고하시면 됩니다. 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

콤보박스를 변경해도 체크박스는 처음 디폴트값으로 설정한 값(전체선택)으로  선택하게 해야함. 
또한 체크박스에서 선택하지 않았을때는 값이 안나와야 정상

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
<체크박스 항목설정: 디폴트 - 전체>
![스크린샷 2020-03-04 오전 10 48 02](https://user-images.githubusercontent.com/36151180/75837057-164abc00-5e07-11ea-9299-0cc9037f4781.png)

<보기 - 기본화면: 정상>
![스크린샷 2020-03-04 오전 10 48 56](https://user-images.githubusercontent.com/36151180/75837062-1b0f7000-5e07-11ea-94aa-ba6054e1a2b5.png)

<보기 - 콤보박스 값 변경시, 체크박스 디폴트 설정 오류>
![스크린샷 2020-03-04 오전 10 49 08](https://user-images.githubusercontent.com/36151180/75837066-1e0a6080-5e07-11ea-88ff-c8e5193563f9.png)

콤보박스를 변경하였을때, 체크박스의 디폴트 설정인 전체선택이되지 않은 상태로 나타남. 
또한 그러한 상태인데, 그래프는 전체선택을 한것처럼 나타남

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@joohj7 
현재 '접수 죄종' Check&Radio 의 항목 탭 - 트리거 설정으로 '발생지방청' Combo가 설정되어 있습니다.

![image](https://user-images.githubusercontent.com/3411842/75845374-39cc3180-5e1c-11ea-9d12-e397f2b7124f.png)


이렇게 설정하면 '발생지방청' Combo의 선택이 변경될 때마다 "항목 설정 변수"에 설정한 내용으로
체크한 항목을 변경하게 됩니다. 그런데 "항목 설정 변수"에 아무런 값도 입력되어 있지 않으므로, 체크가 모두 해제되게 됩니다.
'접수 죄종' Check&Radio 의 항목 탭 - 트리거 설정을 모두 해제하면 정상 동작할 것으로 생각됩니다.

**Comment by joohj7** [comment]
@veldise 해결되었습니다. 감사합니다.
