### ISSUE TITLE
meta: acl API 요청시 DATAMODEL 존재 유무 확인 처리

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1959]
## 설명 ##
- meta: acl API 요청시 DATAMODEL 존재 유무 확인 처리

데이터모델 권한을 추가하고자 할 때, 해당 데이터 모델이 존재하는지 검사해야합니다.
현재는 검사하고 있지 않습니다.

**Comment by sunghoon** [comment]
처리된 이슈로 보고 닫습니다.
