### ISSUE TITLE
[NMS+] 보고서 POST API 호출 후 response 메세지 출력 버그

### ISSUE THREAD

**Issue by devjban** [mobigen/IRIS-BigData-Platform#1960]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://222.239.252.120/#/ 접속
2. 보고서 목록에서 'POP_장비_추가' 실행
3. 추가 버튼 클릭
4. Internal Server Error 출력됨

## 예상한 행동 ##
Internal Server Error가 아닌 서버에서 response한 메세지 출력을 하고자함

## 스크린샷 ##
![post api](https://user-images.githubusercontent.com/40290202/75866752-e2908600-5e48-11ea-9072-0d57abe327c9.png)

![post api2](https://user-images.githubusercontent.com/40290202/75866767-e6240d00-5e48-11ea-9647-e1173da58f6a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
질문: 
1. code는 꼭 -1로 만 해야 하는지?? 기타 API서버에서 정의한 코드를 사용해도 되는지??
2. 성공일 경우 response Json 형식??

**Comment by rhcpn** [comment]
REST API로 결과를 받으실 때는 항상 HTTP Status 를 200으로 처리해 주셔야 합니다.

데이터 성공일때와 실패일때 결과 처리는 아래와 같이 해주시면 되는데요, 이때 code 는 사실
언젠가 code 값으로도 무언가 처리 할지 몰라서 넣어둔 필드이고 .. 당장은 의미가 없습니다.
사실상 messages 에 뭔가 값이 있으면 성공이던 실패던 자동으로 Message 창을 띄워 줍니다.

REST API Output 양식은 다음과 같습니다.
- 성공일 때
```json
{
    "success": {
        "code": 0,
        "messages": "처리를 완료하였습니다"
    },
    "data": {}
}
```

- 실패일 때
```json
{
    "error": {
        "code": 0,
        "messages": "저런, 뭔가 잘 안됬네요"
    }
}
```

**Comment by sunghoon** [comment]
메시지가 다르면 code도 달라야 할 것 같습니다.

**Comment by sunghoon** [comment]
@rhcpn HTTP Status Code 체크 후 이를 기반으로 사용자와 Noti 할 수 있도록 해 주시기 바랍니다.
