### ISSUE TITLE
시각화에서 Y축을 다중 설정 시, 분석 템플릿으로 저장 할수 없음

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#1962]
## 기능 요청 ##
시각화에서 Y축을 다중으로 설정 후, 분석 템플릿으로 저장하려 할 경우 저장 할수 없다고 메세지가 나오고 있음
![image](https://user-images.githubusercontent.com/11566844/75960931-5ba0e380-5f04-11ea-88ff-67914ea15ea9.png)

## 원하는 솔루션 설명 ##
현재 Studio의 시각화에서도 Y다중축을 제공 하므로 시각화에서도 이제 다중축으로 템플릿을 저장 해도 될것 같은데 .. 기능 추가 해야 함.

**Comment by veldise** [comment]
Analyzer 시각화에서의 '다중 차트'는 여러개의 꺾은선 차트를 그리는 것이고
Studio의 '다중축'은 하나의 차트 내에서 Y축을 여러개 구성하는 것이므로 서로 매칭되지 않습니다.

따라서 Analyzer 시각화 '다중 차트'를 템플릿으로 저장하는 것은 가능하나 현재 Studio 보고서에서는 불러오지 못하게 처리가 동반되어야 합니다.

**Comment by sunghoon** [comment]
@veldise @eumminsun  @rhcpn 사용자에게 혼란을 줄 수 있는 부분을 개선해서 기능에 일관성을 유지 할 수 있도록 진행해 주시기 바랍니다.
