### ISSUE TITLE
angora: 데이터 모델 시간 포맷에 따라 model-timeline 명령어 pending

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1963]
## 설명 ##
날짜/시간 데이터가 들어가 있는 컬럼이 아래와 같을 때,

2019-06-03 1:23
2019-06-03 7:02
2019-06-03 10:55
2019-06-03 23:22

momentjs 에서는 포맷을 아래와 같이 지정하면 됩니다.

YYYY-MM-DD H:mm

그런데 데이터 모델 시간 컬럼을 설정할 때 위와 같이 포맷을 지정하면
model-timeline 요청 결과가 반환되지 않습니다.

테스트용 데이터 모델:
![image](https://user-images.githubusercontent.com/3411842/75976442-c874a780-5f1d-11ea-862d-6fa72d1613a9.png)

명령어(`q`):
```
model-timeline name = 'date format test' model_owner = root unit = 1d
```

**Comment by seungfwani** [comment]
@veldise 
운영서버(100.180) 으로 아래와 같은 쿼리를 보냈을 때,
pending 없이 데이터 리턴이 되고,
결과도 알맞는 것으로 보입니다.

당시 서버의 문제가 있었을 듯 합니다.

![Screen Shot 2020-03-09 at 1 35 11 PM](https://user-images.githubusercontent.com/46172579/76183166-d6bb1000-620a-11ea-80d5-e7b9cc0e7830.png)
![Screen Shot 2020-03-09 at 1 35 45 PM](https://user-images.githubusercontent.com/46172579/76183223-11bd4380-620b-11ea-8d4d-2d829424073b.png)
![Screen Shot 2020-03-09 at 1 37 21 PM](https://user-images.githubusercontent.com/46172579/76183251-21d52300-620b-11ea-8021-3a74b7aa833f.png)

**Comment by veldise** [comment]
@seungfwani 
위 문제는 해결된 것 같은데, 시간범위 설정했을 때 결과가 이상합니다.
확인 바랍니다.

![image](https://user-images.githubusercontent.com/3411842/76185947-10dcdf80-6214-11ea-96ef-db8df0d98310.png)

**Comment by seungfwani** [comment]
해당 문제는 최초에 말씀하신 `YYYY-MM-DD H:mm` 포맷에 관련된 문제입니다.

현재 `HH`를 시간데이터로 처리하는 로직을 사용하고 있고,
이를 사용하면, `1:35` 데이터가 `01:35` 로 표시가 되게 됩니다.

`1:35` 데이터를 그대로 표기하기 위해서 `H` 포맷을 사용하기 위해서는 코드 수정이 필요합니다.

급한 상황이라면 현재는 `HH` 포맷만 사용가능 한 상황임을 알려 드립니다.

아래는 `YYYY-MM-DD HH:mm` 과 같이 `HH`로 두자리 표현으로 변경하여 실행한 결과입니다.
![Screen Shot 2020-03-09 at 3 05 31 PM](https://user-images.githubusercontent.com/46172579/76187062-a88ffd00-6217-11ea-8fff-9a61332d8b05.png)
![Screen Shot 2020-03-09 at 3 08 13 PM](https://user-images.githubusercontent.com/46172579/76187117-d2492400-6217-11ea-9561-d5a32ad1bf2d.png)

**Comment by veldise** [comment]
@seungfwani @anhm 
네, 그러면 수정이 필요합니다. 최초 설계할 때 momentjs 기준으로 하자고 협의했었습니다.
help icon 툴팁에도 momentjs 링크가 걸려있습니다.

**Comment by seungfwani** [comment]
포멧을 `YYYY-MM-DD H:mm` 포멧을 사용하여도 정상 동작하도록 수정하였습니다.

아래 내용은 해당 모델의 결과입니다. (운영서버)

![Screen Shot 2020-03-10 at 5 12 12 PM](https://user-images.githubusercontent.com/46172579/76292317-5243bc80-62f2-11ea-8340-d33838d66385.png)

**Comment by seungfwani** [comment]
이슈 닫아도 될까요?

**Comment by veldise** [comment]
@seungfwani 
이슈 본문 내용이 해결되었으면 물어보지 않고 닫아도 됩니다.
만약 해결되지 않았으면 이슈 작성자(author)나 다른 사람이 Reopen 할 것입니다.

**Comment by veldise** [comment]
@seungfwani 
그런데 해결 안 된 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/81255764-81b04480-9069-11ea-8161-f4cc04a0aae0.png)

**Comment by seungfwani** [comment]
수정된 버전으로 운영서버 배포완료 하였습니다. 
1. 전체시간
![Screen Shot 2020-05-07 at 6 03 38 PM](https://user-images.githubusercontent.com/46172579/81275782-1aa48700-908d-11ea-8e34-50e428d9857d.png)
2. 시간범위 지정
![Screen Shot 2020-05-07 at 6 03 00 PM](https://user-images.githubusercontent.com/46172579/81275703-01033f80-908d-11ea-8233-3ad47db891f5.png)

**Comment by veldise** [comment]
@seungfwani 
확인했습니다. 이슈 닫습니다.
