### ISSUE TITLE
angora: 줄바꿈이 포함된 데이터를 다운로드하면 csv 깨짐

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1966]
## 버그 설명 ##
줄바꿈이 포함된 데이터를 '결과 내보내기' 기능으로 다운로드한 csv를 MS엑셀로 열면 깨집니다.
텍스트 한정자 옵션이 추가되면 해결될 것 같습니다.

**Comment by seungfwani** [comment]
@big-mobigen 
치안연 서버에 적용이 되었는지 궁금합니다.

**Comment by big-mobigen** [comment]
치안정책연구소 마지막 배포일은 2020년 3월 10일이며 버전 정보는 다음과 같습니다.

[root@PSI-MASTER b-iris]# docker images | grep -v latest
REPOSITORY                       TAG                  IMAGE ID            CREATED             SIZE
mobigen.com/studio               v2.5_2fbea6e         3bb478f5bc2a        25 hours ago        624MB
mobigen.com/sherman              v2.5_f4ce61e         79f8dfc34f6c        25 hours ago        656MB
mobigen.com/meta                 v2.5_fdfcaaa         4a834e3c5e0a        25 hours ago        651MB
mobigen.com/brick                v2.5_c1450ad         d7cfd6e31ae6        6 days ago          195MB
mobigen.com/mariadb              no_version_c64c34f   2166a66642fa        11 days ago         423MB
mobigen.com/cluster              v2.5_6af2cdf         ad6455e4ec8d        11 days ago         697MB
mobigen.com/db-browser           v2.5_014f40b         67dea69dbd72        12 days ago         701MB
mobigen.com/data-import          v2.5_02901cc         3f4f4ec8aedc        13 days ago         188MB
mobigen.com/dashboard            v2.5_c5ce1a7         9a1c83067e73        13 days ago         702MB
mobigen.com/hdfs-browser         v2.5_a5ad119         debcd1adf443        2 weeks ago         177MB
mobigen.com/angora               v2.5_2.4.4_9a0caf4   61c8f2338cdb        2 weeks ago         2.72GB
mobigen.com/dsms                 v2.5_a6ede79         02e034eccf29        3 weeks ago         1.97GB
mobigen.com/ext-manager          2.7.2_ae04c63        9dfd6532c89c        3 weeks ago         255MB
mobigen.com/iris-hive            1.0.0_18aa730        040437a7b8db        7 weeks ago         2.42GB
mobigen.com/sms                  1.0.1_aa0af85        851a0cfe2181        3 months ago        425MB
mobigen.com/data-trans-service   v2.5_d4fac8f         3ff0e5dbf10f        3 months ago        499MB
mobigen.com/jhms                 v2.5_64327fd         c7f2a512a30e        3 months ago        642MB
mobigen.com/jupyter              v2.6                 439df46308c7        5 months ago        26.2GB
mobigen.com/zeppelin             v2.6                 b4f4b9c7af21        6 months ago        2.51GB
mobigen.com/rstudio              v2.6                 9d5fc81d5dba        6 months ago        3.94GB
mobigen.com/nats                 2.0.2_a2c07d6        cc3a8230ebe5        7 months ago        295MB
mobigen.com/memcached            no_version_91ed62c   c02d9997e7b3        8 months ago        171MB

**Comment by sunghoon** [comment]
해결된 이슈로 닫습니다.
