### ISSUE TITLE
보고서 스튜디오에서 라벨 테두리 문제

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#1968]
## 버그 설명 ##
라스튜디오에서 라벨을 만들어 사용 시 테두리 색상을 지정하고 다시 삭제 해도 테두리가 사라지지 않는 문제

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 메뉴
2. 툴바에서 라벨선택
3. 스크롤하여 라벨을 그린다.
4. 우측 패널의 속성(탭)>꾸미기>윤곽선 색상지정
5. 지정한 색상을 다시 제거
6. 검정색 윤곽선이 남는증상발생

## 예상한 행동 ##
윤곽선 색상지정을 없애면 윤곽선이 제거된다.

## 기타 ##

- 윤곽선의 두께를 지정하는 옵션추가도 부탁드립니다.
- 윤곽선의 스타일 점선, 패턴도 지정되도록 옵션기능도 추기되도록 부탁드립니다.

**Comment by veldise** [comment]
@jmlee 
아래와 같이 객체 스타일 지정기능이 추가되면서, 말씀하신 문제 해결되었습니다.

![image](https://user-images.githubusercontent.com/3411842/76598223-bf9b5b80-6545-11ea-92cb-d442e9b2c5b9.png)
