### ISSUE TITLE
[로그인] 네트웍 문제로 재접속 시 "보고서" 메뉴가 비활성화 될 때가 종종  발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1969]
## 버그 설명 ##
재접속 시 "보고서" 메뉴만 다음 처럼 비활성화 될 때가 자주 있습니다.

계정 : myiris 

<img width="1274" alt="스크린샷 2020-03-06 오전 11 21 09" src="https://user-images.githubusercontent.com/5126497/76044225-082ea400-5f9d-11ea-9a5e-e34c83012504.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
특정 시점의 장애라 닫도록 하겠습니다.
