### ISSUE TITLE
시각화/보고서 - 차트 데이터 값 뒤에 특정단위 포맷설정기능 요청

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1970]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.
시각화/보고서 - 차트 데이터 값 뒤에 특정단위 생성 기능 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
시각화/보고서 차트의 데이터 값 뒤에 %, 원, kwh 등 단위를 붙일 수 있었으면 좋겠습니다. 

<img width="654" alt="스크린샷 2020-03-06 오후 1 30 24" src="https://user-images.githubusercontent.com/36151180/76051640-ce669900-5fae-11ea-9238-4ff27a949bba.png">

좋은 예시는 아니나,  위의 데이터는 증감률 값에 따른 막대형 그래프입니다. 
증감률 값에 따라 값이 표현되고, 데이터 값에 붙어 나오는 단위에 해당하는 텍스트가 존재합니다. 
((%)뒤에 XXXX건(발생)이라고 나오는부분은 무시해주세요) 

위의 예시처럼 데이터에서 보여지는 값 뒤에 단위를 붙여서 나올수 있게 출력이 가능하게 했으면 좋겠습니다. 

다양한 시각화/보고서 차트에서 적용가능하게 했으면 좋겠습니다. 

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
