### ISSUE TITLE
보고서 - 콤보박스 안에 스크롤이 가능한 체크박스 형태

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1971]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.
보고서 - 콤보박스 안에 스크롤이 가능한 체크박스 형태
콤보박스처럼 접었다가 펼수 있는 체크박스 형태와 스크롤이 가능한 체크박스 형태를 원합니다. 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

psi 시연 과제를 하다보니 한정된 대시보드 화면 사이즈에서 
현재 아이리스 체크박스의 형태로는 체크박스의 내용이 많아질 경우(200개 넘어가는경우 등) 화면상의 제약이 있어
화면의 대부분을 체크박스가 차지하는 경우가 생겼습니다.

현재 태블로에서는 체크박스가 콤보박스내부에 체크박스가 존재하고, 스크롤이 가능한 형태로 되어 있는데, 
기능 개발이 되었으면 좋겠습니다. 

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
<img width="237" alt="스크린샷 2020-03-06 오후 1 34 28" src="https://user-images.githubusercontent.com/36151180/76053151-9a3fa800-5faf-11ea-9bc0-e7469fa927ed.png">
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }
<img width="245" alt="스크린샷 2020-03-06 오후 1 34 23" src="https://user-images.githubusercontent.com/36151180/76053145-97dd4e00-5faf-11ea-95b9-7ee060df86a2.png">

![KakaoTalk_Photo_2020-03-06-13-42-36](https://user-images.githubusercontent.com/36151180/76053385-6022d600-5fb0-11ea-9222-48a28aa62342.png)

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
