### ISSUE TITLE
보고서 - 차트영역 내에서 스크롤이 가능한 차트 형태

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1972]
## 기능 요청 ##

한정된 대시보드 내에서 차트를 그려야 할 경우, 
범주가 많은 데이터라면 세로축 혹은 가로축이 매우 긴 경우가 생깁니다. 
(예: 범주가 200개 이상 등) 
이러한 차트의 경우 차트를 모두 보이게 하기 위해서 차트영역을 매우 크게 하는데, 
한정된 대시보드에서 여러가지 차트를 그려야 할 경우라면,
필연적으로 차트영역 사이즈를 조절해야 합니다. 

이때 차트그림보다 차트 영역이 작을경우 차트의 그림이 잘려 보이거나 사이즈가 조정되어서 자잘하게 보입니다. 

한정된 대시보드 형태에서 시각화 내용을 잘 전달하기위해서 막대 혹은 히트맵 등 시각화 그림의 크기가 좀 클 필요성이 있는데, 스크롤 형태의 차트를 제안합니다. 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
태블로에서 현재 적용되어 있는 형태를 첨부합니다. 

![KakaoTalk_Photo_2020-03-06-13-49-48](https://user-images.githubusercontent.com/36151180/76053693-6796af00-5fb1-11ea-9a78-b7a234acb1aa.png)
위의 그림은 대시보드 내 하나의 차트 영역과 같습니다. 
200개가 넘어가는 경찰서 범주가 있는데, 스크롤형태로 보이는 만큼만 보이고 스크롤을 내리면 
차례로 보이는 상태입니다. 
선택할 수 있는 시각화옵션형태로 빼면 좋을 것 같습니다. 

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
