### ISSUE TITLE
피벗 범위 선택

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1975]
## 버그 설명 ##
피벗등의 범위 선택시
-범위 크기
-범위 시작
-범위 끝
옵션이 선택사항으로 사용할수 있는데,

이중 하나만 선택사항으로 입력할경우 에러가 발생하는 이슈

전체를 다 제거 하거나, 전체를 다 입력하거나 하면 문제가 없음

## 예상한 행동 ##
3개중 일부만 선택 입력이 가능하도록 변경이 필요

## 스크린샷 ##
![스크린샷 2020-03-09 오전 9 30 06](https://user-images.githubusercontent.com/3415270/76174131-bbd7a400-61e8-11ea-9611-458d94bb01df.png)

**Comment by seungfwani** [comment]
피벗시 범위선택 이슈를 해결하여 운영서버에 배포하였습니다.
![Screen Shot 2020-03-10 at 4 59 19 PM](https://user-images.githubusercontent.com/46172579/76291471-861de280-62f0-11ea-9c00-89399e4c7c34.png)

**Comment by seungfwani** [comment]
본 이슈 닫아도 될까요?
