### ISSUE TITLE
보고서- 챠트>시각화 배경, 테두리, 글자 스타일 설정기능추가

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#1976]
## 기능 요청 ##
보고서에서 사용되는 툴들의 대부분이 
배경색상, 테두리, 글자 스타일을 지정을 할 수 없습니다.
보고서가 흰색 또는 밝은색으로만 작성하여야 하며 
라벨 텍스트, 챠트의 단일텍스트 이외에는 대부분 글자 스타일을 지정할 수 없습니다.
이 기능을 제공하면 현재의 디자인 작업가능한 범위가 
획기적으로 늘어나게 되니 빠른 적용 부탁 드립니다.

## 원하는 솔루션 설명 ##
보고서
 - 챠트 : 테두리 설정, 배경색상 설정, 글자 스타일설정(색상,크기,굵기 등의 스타일)
 - 챠트 이외의 툴들...  : 글자크기, 색상, 굵기등의 스타일

특히 : 챠트 > 시각화 > 단일값 은 
테두리를 제거하고 배경을 투명하게 하면 활용도가 매우 높아서 빠른적용 부탁드립니다.
(성남시 자율주행 인포그라픽에 적용필요)

**Comment by veldise** [comment]
@jmlee 
차트의 테두리(border)를 설정하는 기능은 3/13 일자로 추가되었습니다.
차트 및 차트 외 객체의 배경색, 글자 스타일을 설정하는 기능은 추가 개발이 필요합니다.

**Comment by jmlee** [comment]
@veldise 차트의 테두리(border)를 설정하는 기능은 3/13 일자로 추가이후에 이미지를 불러온 상자의 흰색테두리가 생겼습니다.
해당 이미지 상자를 선택하여 테두리를 제거 하여도 흰색 테두리 라인이 사라지지않습니다.
![이미지상자라인](https://user-images.githubusercontent.com/899539/76599136-b14e3f00-6547-11ea-825d-8d6f550e5093.PNG)

**Comment by veldise** [comment]
@jmlee 
문제 확인하였습니다. 수정하겠습니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/80166331-a1328080-8618-11ea-9ff7-6e3bf9c11984.png)

**Comment by veldise** [comment]
아래와 같이 기능 추가되어 닫습니다.

![image](https://user-images.githubusercontent.com/3411842/81255134-dce13780-9067-11ea-8b10-eb850987ff1a.png)
