### ISSUE TITLE
CI/CD report 목록선택 시 이전에 선택한 값이 출력됨

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#1977]
## 버그 설명 ##
CI/CD report 목록선택 시 이전에 선택한 값(project_nm)이 연결된 컴포넌트로 전달됩니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서>'CI/CD report' 선택
2. 하단 빌드평균점수 라인그래프는 'IRIS-E2E-K8S'로 그려짐 - 디폴트 프로젝트명으로 정상동작 
3. 좌측 상단 '프로젝트 리스트' 선택 시 동일한 값이 그려지고, 이후 다른 프로젝트명을 선택하면 선택된 값이 아니라 기존 값이 할당됨 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
- project 'ITI-cicd' 선택
![image](https://user-images.githubusercontent.com/44352311/76189955-34595780-621f-11ea-889a-fa8183400cf7.png)

- DevTools 확인결과
- project_nm 에 'angora-v2'가 전달됨 
![image](https://user-images.githubusercontent.com/44352311/76189911-1db30080-621f-11ea-94ab-f1cc80548a93.png)

**Comment by veldise** [comment]
#2409 와 동일한 버그로 생각됩니다. 이에 이슈 닫습니다.
