### ISSUE TITLE
studio: Chart / 행 선택 기본값을 설정하는 기능 추가

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1978]
## 기능 요청 ##
studio: Chart / 행 선택 기본값을 설정하는 기능 추가

## 내용
Combo 객체의 경우, 아래와 같이 '항목' 탭에서 항목 선택 기본값을 지정할 수 있습니다. (보고서 실행시 선택을 지정한 항목으로 초기화)
Chart 객체에도 이와 유사한 기능이 필요합니다.

![image](https://user-images.githubusercontent.com/3411842/93974725-35b03300-fdb1-11ea-8419-604dab1a762c.png)

**Comment by sunghoon** [comment]
@veldise 조금 더 구체적인 설명 요청합니다.

**Comment by veldise** [comment]
@sunghoon 
이슈 본문에 보강하였습니다.

**Comment by sunghoon** [comment]
@veldise 그래도 잘 모르겠습니다. T.T 시간 될 때 직접 설명 부탁드립니다.
