### ISSUE TITLE
체크 박스에 변수를 사용할 경우 동작하지 않는 이슈

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#1980]
## 버그 설명 ##
체크 박스에 변수를 사용할 경우 정상동작하지 않는 이슈

크롬의 사용자 도구를 이용해서 해당 이슈를 관찰해본 결과 
서버쪽으로 통신하지를 않음.

## 재현하는 방법 ##
동작을 재현하는 방법 :
체크 박스에서 아래와 같이 입력이 되어 있는 경우에는 동작하지 않음
```
* | where OCCURE_DISTRICT_OFFICE_1 = '${combo_1}'
```

아래와 같이 변수 대신 값을 입력할 경우에는 정상적으로 동작을 함
```
* | where OCCURE_DISTRICT_OFFICE_1 = '서울청'
```

## 예상한 행동 ##
변수에 들어간 값이 존재하는 상태에서 정상적으로 응답

## 스크린샷 ##
![스크린샷 2020-03-09 오후 4 38 10](https://user-images.githubusercontent.com/3415270/76192193-8ea8e700-6224-11ea-8d16-ed3a96c7c8db.png)

**Comment by veldise** [comment]
콤보 박스가 아니라 체크 박스(Check&Radio)에서 발생하는 현상으로 확인되어 본문 수정하였습니다.

**Comment by joohj7** [comment]
@veldise @anhm 
위의 상황을 자세히 말씀 드리자면, 
콤보박스에서 이벤트 변수를 차트에 사용하거나, 
체크박스를 이벤트 변수를 차트에 사용하거나 하는 사항은 모두 가능합니다. 

그런데 위의 경우는 콤보박스의 이벤트 변수를 
체크박스를 보여주는 쿼리에서 받아 필터링된 체크박스를 보여줘야하는 상황입니다.
