### ISSUE TITLE
studio: 내보내기 URL로 보고서 접근시 지도가 동작하지 않는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1982]
## 버그 설명 ##
studio: 내보내기 URL로 보고서 접근시 지도가 동작하지 않는 문제

**Comment by swish1995** [comment]
일단 에러 처리에 관한 부분만 처리 하였고 인증에 관한 부분은 추가 처리 예정입니다.

**Comment by veldise** [comment]
3/13일자로 해결 완료되어 닫습니다.
