### ISSUE TITLE
[오픈랩] ktcloudstorage 데이터모델 화면출력안됨

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#1983]
## 버그 설명 ##
오픈랩사이트에 ktcloudstorage 데이터모델에 연결정보를 선택하고 대상데이터 찾아보기 클릭 시 hdfs-browser 팝업창에서 데이터가 확인되지 않음.

사이트주소: https://211.251.247.185:10443/secret_login#/

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/25650544/76372002-74cfe700-637f-11ea-92fa-bea9e98ce6f5.png)

대상데이터란에 실제경로 및 파일내용을 입력해주면 조회됨.
![image](https://user-images.githubusercontent.com/25650544/76372058-97620000-637f-11ea-88d7-5fdb80f90aa9.png)

## 기타 ##
특이사항 어제 정희동팀장님 요청으로 angora 기능동작을 위해 minio ssl 환경을 없애고  http 로 변경하였습니다.

**Comment by veldise** [comment]
@big-mobigen 
사용한 연결정보 testffff 의 정보를 첨부 부탁드립니다.

**Comment by big-mobigen** [comment]
@veldise 

{"status": 0, "messages": "", "items": {"connector_id": 148, "datasource_name": "KTCLOUDSTORAGE", "connector_name": "testffff", "description": null, "info": {"host": {"type": "text", "value": "https://vsa-00000026-kt-gcloud-01.zadarazios.com"}, "port": {"type": "integer", "value": 8443}, "container": {"type": "text", "value": null}, "user": {"type": "text", "value": "kyujin13@koti.re.kr"}, "password": {"type": "password", "value": "Du7bRHqmMeZR4dxSmmUp"}, "account": {"type": "text", "value": "koti"}}, "create_time": 1583837067, "update_time": null}}

필요하신 정보 전달 드립니다.

**Comment by veldise** [comment]
@big-mobigen 
http로 변경했다고 하셨는데, `host`가 https 로 입력되어 있습니다. 확인 바랍니다.

**Comment by veldise** [comment]
추가로, host에는 https:// 와 같은 부분은 입력하면 안됩니다.

**Comment by big-mobigen** [comment]
@veldise 

![image](https://user-images.githubusercontent.com/25650544/76377691-e5cacb00-638e-11ea-8645-1b1b043ca975.png)

KTCLOUDSTORAGE 연결정보에 host부분과 port를 수정하여 정상조회됨을 확인하였습니다. 
감사합니다.

**Comment by veldise** [comment]
@big-mobigen 
고생하셨습니다.

**Comment by big-mobigen** [comment]
@veldise 
감사합니다. 
해결되었으니 이슈는 닫겠습니다~~
