### ISSUE TITLE
studio: Map / 지도 레이어 시각화 옵션이 편집 화면에서는 적용되지 않는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1984]
## 버그 설명 ##
studio: Map / 지도 레이어 시각화 옵션이 편집 화면에서는 적용되지 않는 문제

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/76372463-d47ac200-6380-11ea-8310-6fea8f05afdb.png)

**Comment by swish1995** [comment]
[맵 고정 기능 요청](https://github.com/mobigen/IRIS-BigData-Platform/issues/1237)
상기 이슈와 같이 처리하도록 하겠습니다.
