### ISSUE TITLE
보고서 / 지도 - 범례의 사이즈 및 위치 변경

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1986]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.

보고서 / 지도 - 범례의 사이즈 및 위치 변경 기능이 필요합니다. 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
현재는 지도 기능에서 범례의 사이즈와 위치가 고정되어 있습니다. 

그런데, 지도 사이즈를 보고서에 맞게 조정하다 보면 
범례의 위치를 조정하고 싶은 경우가 생기기도 하고, 
혹은 지도내에서 지도와 범례의 비율상 범례가 월등하게 커서 범례 사이즈를 조정하고 싶을때가 생깁니다. 

이런 경우때문에 기능을 요청합니다. 

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }
* 범례사이즈 : 최소한 한/두단계정도 범례사이즈를 줄일수 있는 기능이 있으면 좋겠습니다. 
* 범례위치 : 범례의 경우에도 지도의 좌표를 받게 하여 위치를 설정할 수 있게 하거나, 
최소한 왼쪽아래, 왼쪽 위, 오른쪽 아래, 오른쪽 위 등 설정이 생겼으면 좋겠습니다.  

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
<범례 사이즈 동일 >
<img width="546" alt="스크린샷 2020-03-11 오전 11 34 09" src="https://user-images.githubusercontent.com/36151180/76377045-2de8ee00-638d-11ea-957e-50d36180efd4.png">
<img width="405" alt="스크린샷 2020-03-11 오전 11 41 38" src="https://user-images.githubusercontent.com/36151180/76377079-4d801680-638d-11ea-93c2-2a215952c302.png">

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
