### ISSUE TITLE
ValuelinkU/Studio/이중축 그래프 툴팁 표시

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1991]
## 버그 설명 ##
단일축 그래프에서는 마우스오버시 툴팁이 전체 값에 대해서 보여지는데 이중축 그래프에서는 단일값에 대해서만 보여집니다. 이중축 그래프 툴팁을 단일축 그래프와 동일하게 표시할 수 있나요?

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
1. 단일축 그래프
![image](https://user-images.githubusercontent.com/7067615/76394780-5e468180-63b9-11ea-8458-831f397c6fa2.png)

2. 이중축 그래프
![image](https://user-images.githubusercontent.com/7067615/76394810-6bfc0700-63b9-11ea-98f7-f9fabfed44d8.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#### 현재 상태:
각 Y축 마다 컬럼을 1개씩 지정하면 아래와 같이 툴팁이 분리되고,

![image](https://user-images.githubusercontent.com/3411842/76474196-351c0480-643e-11ea-8dbf-27e3ec15a9af.png)

![image](https://user-images.githubusercontent.com/3411842/76474206-3baa7c00-643e-11ea-8309-f11fa4fe3aab.png)

아래와 같이 Y축 중에 '모두 선택'을 지정한 경우가 있으면 툴팁이 통합됩니다. (의도한 동작)

![image](https://user-images.githubusercontent.com/3411842/76474255-60065880-643e-11ea-82f4-4c26f7d77b40.png)

헌데 현재 버그가 있어 위와 같이 동작하고 있지 않습니다.


#### 개선:

아래와 같이 데이터 탭 설정과 관계없이 툴팁이 통합되도록 개선하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/76474623-9db7b100-643f-11ea-8821-5d3dcd73ee56.png)
