### ISSUE TITLE
[교통빅데이터] 데이터모델 검색시 초단위 정렬이 정상적으로 동작하지 않음

### ISSUE THREAD

**Issue by jsk3238** [mobigen/IRIS-BigData-Platform#1992]
## 버그 설명 ##
데이터 모델 검색시 시간 정렬이 정상적으로 동작하지 않음(초단위)

## 재현하는 방법 ##
1. https://180.148.181.193/#/ 접속(root)
2. 모델명 "유통"으로 조회한 후 "* | sort - process_time_msec" 입력 후 조회
3. 조회 내용 확인

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7123538/76488891-3105dc00-646a-11ea-92c0-750e8d9d8968.png)

**Comment by veldise** [comment]
- `* | sort - process_time_msec` 결과(`-` 문자 뒤에 공백): 
![image](https://user-images.githubusercontent.com/3411842/76596011-78f73280-6540-11ea-8423-e0f70235bd23.png)

- `* | sort -process_time_msec` 결과: 
![image](https://user-images.githubusercontent.com/3411842/76596030-83193100-6540-11ea-8e09-05bc6518f494.png)

- `* | sort process_time_msec` 결과: 
![image](https://user-images.githubusercontent.com/3411842/76596046-8f9d8980-6540-11ea-991e-34ed3687b3c8.png)

- 모델 정보:
![image](https://user-images.githubusercontent.com/3411842/76596186-d68b7f00-6540-11ea-83bb-3c9827ea1cb9.png)

**Comment by veldise** [comment]
실데이터:
![image](https://user-images.githubusercontent.com/3411842/76596634-02f3cb00-6542-11ea-9955-82b101b9f4c9.png)

@jsk3238 
1. 실 데이터가 `20200313093349348`가 `2020-03-13 09:33:49.348`을 의미하는 것이라면
포맷을 아래와 같이 대문자 SSS로 하셔야 합니다.

`YYYYMMDDHHmmssSSS`

2. 제가 알기로는 컬럼명 앞에 `-` 기호를 붙인다면 아래와 같이 공백이 없어야 합니다.
`* | sort - process_time_msec` (X)
`* | sort -process_time_msec` (O)

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
