### ISSUE TITLE
보고서/ 지도 - 범례의 최소값/최대값 표시 기능

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#1993]
## 기능 요청 ##
{문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

보고서/ 지도 - 범례의 최소값/최대값 표시 기능

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

지도에서 범례를 표시할때, 
히트맵의 최소값과 최대값의 실값이 함께 표시할 수 있었으면 좋겠습니다. 

<현재 범례상태 >: 최소/최대값의 실값이 표시되지 않음
<img width="405" alt="스크린샷 2020-03-11 오전 11 41 38" src="https://user-images.githubusercontent.com/36151180/76488938-572b7c00-646a-11ea-972a-63c051357afe.png">

<태블로 범례 예시>: 최소/최대값의 실값이 표시됨 
![KakaoTalk_Photo_2020-03-12-14-02-48](https://user-images.githubusercontent.com/36151180/76489033-9eb20800-646a-11ea-8ac9-a1f924d1edc6.png)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

기능은 최소/최대값 표현 여부를 옵션 형태로 선택하게할수 있었으면 좋겠습니다. 

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
