### ISSUE TITLE
[Analyzer] 검색-시각화-검색 으로 메뉴 이동을 했는데, 검색화면에서 계속 시각화 로 보입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#1999]
## 버그 설명 ##

<img width="1274" alt="스크린샷 2020-03-13 오전 11 24 32" src="https://user-images.githubusercontent.com/5126497/76583779-84853200-651d-11ea-988f-6a98a91f2e7d.png">

검색화면으로 돌아왔는데, 상단 메뉴 가 시각화 로  되어있습니다.

## 재현하는 방법 ##
검색 화면에서  
<img width="118" alt="스크린샷 2020-03-13 오전 11 28 28" src="https://user-images.githubusercontent.com/5126497/76583923-da59da00-651d-11ea-9724-c6575b2de271.png">

실행 버튼 없이 다시 "검색으로 이동"
<img width="680" alt="스크린샷 2020-03-13 오전 11 28 57" src="https://user-images.githubusercontent.com/5126497/76583956-e9408c80-651d-11ea-88ce-802a1572a124.png">

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 해당 기능 재현해 보려고 하는데 기능 자체가 동작하지 않습니다. 
확인 후 패치 바랍니다.

![스크린샷 2020-09-23 오후 3 14 21](https://user-images.githubusercontent.com/512653/93973627-76a74800-fdaf-11ea-83fa-1408ebafdc4a.png)

**Comment by veldise** [comment]
@sunghoon 
말씀하신 문제는 #2618 이슈로, 금주 패치 예정입니다.
