### ISSUE TITLE
[KOTRA]TIBERO 연동 오류

### ISSUE THREAD

**Issue by yariyarishow** [mobigen/IRIS-BigData-Platform#2000]
![5CD70C94-1C95-4966-AB52-985F08A63EED](https://user-images.githubusercontent.com/18297120/76589543-bef6cb00-652d-11ea-9639-1319abc88727.jpeg)

![419AF85A-0EE8-4273-9D85-273B598E4EE1](https://user-images.githubusercontent.com/18297120/76589616-fa919500-652d-11ea-85ad-c44b52d79026.jpeg)

## 오류 설명 ##
1. 접속 정보 생성후 테스트는 성공
2. 실제 접속해서 테이블 목록을 조회하려고 하는데 오류.

## 문의 ##
1. 테이블 목록을 조회하기 위한 다른 설정들이 필요한가요?

**Comment by sunghoon** [comment]
@veldise @anhm  해당 오류 어떻게 처리 되었나요?

**Comment by anhm** [comment]
@sunghoon 
해당 이슈는 angora 를 최신 버전으로 패치하면 해결이 되지만,
kotra 사이트의 경우 spark 2.3버전을 사용하고 있어 버전 호환이 힘든 상태입니다.
spark 2.4로 업그레이드 및 IRIS 최신화 작업 예정중에 있습니다.

**Comment by sunghoon** [comment]
@yariyarishow 일정 잡아서 진행 하시면 될 것 같으며, 본 이슈는 닫도록 하겠습니다.
