### ISSUE TITLE
studio: 특정 일자 범위에서, 날짜를 개별 선택하거나 특정 날짜를 제외할 수 있는 객체 필요

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2001]
## 기능 요청 ##
- 요청자: OS개발팀 신운선 책임님
- studio: 특정 일자 범위에서, 날짜를 개별 선택하거나 특정 날짜를 제외할 수 있는 객체 필요

**Comment by sunghoon** [comment]
아이디어 기능으로 처리하겠습니다.
