### ISSUE TITLE
[Discovery] Command 중 string type 컬럼을 IRIS timestamp 포맷 으로 변환하는 명령어가 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2002]
## 기능 요청 ##
처음 데이터모델에  있는 timestamp 컬럼을 
string 으로 변환해서 만들고,  최종 데이터프레임에서 
이 컬럼을 다시 timestamp 컬럼으로 변환하고 싶습니다.

예시 )  syslog(eva) 데이터모델

`
LEVEL!='info' HOST='tsdn-svr1'
| fields +DATETIME,HOST,LEVEL
| sql "select  CONCAT( SUBSTR(DATETIME,1, 13 ), '0') as DATETIME_MIN,  * from angora”
| stats COUNT(*) as CNT by DATETIME_MIN, HOST, LEVEL
| sort DATETIME_MIN

`

에서
최종 데이터프레임의 DATETIME_MIN 컬럼을 
다시 IRIS 의  시간 필드로 인식할 수 있도록 변환하고 싶습니다.

그래서 뒷부분에
시간필드를 인식해서 사용하는 **weekend**  같은 명령어를 사용하거나 시간관련 명령어를 사용하고 싶습니다.

`
LEVEL!='info' HOST='tsdn-svr1'
| fields +DATETIME,HOST,LEVEL
| sql "select  CONCAT( SUBSTR(DATETIME,1, 13 ), '0') as DATETIME_MIN,  * from angora”
| stats COUNT(*) as CNT by DATETIME_MIN, HOST, LEVEL
| sort DATETIME_MIN
| weekend False

`

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
해당 요청은 `weekend` 명령어에 옵션을 주는 방식으로 수정하였습니다. (새명령어 X)

사용자가 시간 컬럼을 임의로 지정하여 해당 컬럼을 이용해 weekend 로직을 실행할 수 있도록 하였습니다.
예를 들어 제시 해주신 쿼리를 바꿔보면 아래와 같습니다.
```
* LEVEL!='info' HOST='tsdn-svr1'
| fields +DATETIME,HOST,LEVEL
| sql "select CONCAT( SUBSTR(DATETIME,1, 13 ), '0') as DATETIME_MIN, * from angora"
| stats COUNT(*) as CNT by DATETIME_MIN, HOST, LEVEL
| sort DATETIME_MIN
| weekend False DATETIME_MIN format YYYYMMDDHHmmss
```

자세한 사용법은 아래 링크를 참조하시기 바랍니다. (현재 머지를 기다리고 있어 반영이 되어있지 않습니다.)
http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/weekend.html

**Comment by sunghoon** [comment]
위에 설명된 정보를 바탕으로 메뉴얼을 보았을때 아래 명령에 대한 조합을 알 수 가 없습니다.
```
weekend False DATETIME_MIN format YYYYMMDDHHmmss
```
관련된 내용에 대한 설명을 보강해 주시면 좋겠습니다.

**Comment by seungfwani** [comment]
위의 코멘트 처럼 이번 이슈를 처리하기 위해서
weekend 명령어에 옵션을 주는 방식으로 수정하였습니다. (새명령어 X)

사용자가 시간 컬럼을 임의로 지정하여 해당 컬럼을 이용해 weekend 로직을 실행할 수 있도록 하였습니다.
예를 들어 제시 해주신 쿼리를 바꿔보면 아래와 같습니다.

* LEVEL!='info' HOST='tsdn-svr1'
| fields +DATETIME,HOST,LEVEL
| sql "select CONCAT( SUBSTR(**DATE_FORMAT(DATETIME, 'yyyyMMddHHmmss')**,1, 13 ), '0') as DATETIME_MIN, * from angora"
| stats COUNT(*) as CNT by DATETIME_MIN, HOST, LEVEL
| sort DATETIME_MIN
| weekend False **DATETIME_MIN format YYYYMMDDHHmmss**

변경된 쿼리를 보면 두가지 굵은 글씨가 있습니다.
1. **DATE_FORMAT(DATETIME, 'yyyyMMddHHmmss')**
  - 이번에 `weekend 명령어 수정` 외에 시간 관련 컬럼의 데이터에 수정이 있었습니다.
  - 해당 수정으로 인해 더이상 `DATETIME` 컬럼의 데이터는 `TEXT` 가 아닙니다.
  - 따라서, `CONCAT`, `SUBSTR`  을 사용하기 위해서, `DATE_FORMAT()` 함수를 사용해야합니다.
  - `DATE_FORMAT` 함수는 spark 함수로, 아래 링크를 참조하시면 됩니다.
  - https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.functions.date_format

2. **DATETIME_MIN format YYYYMMDDHHmmss**
  - weekend 명령어에 옵션을 추가하였습니다.
  - DATETIME_MIN 과 같이 시간데이터가 있는 컬럼명을 먼저 작성한 뒤, `format` 예약어를 사용하여 시간의 포멧이 어떻게 되어있는지 작성해 줍니다.
  - 명령어 문서를 참조해보시면 시간포멧의 의미에 대해 확인 하실 수 있습니다.
  - http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/weekend.html

**Comment by seungfwani** [comment]
이슈 닫도록 하겠습니다.

문제가 있으시다면 재오픈 바랍니다.
