### ISSUE TITLE
[Discovery] pylambda 에서 time, datetime, re  등의 패키지 함수를 사용하게 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2003]
## 기능 요청 ##
pylambda 로 람다함수를 만들 때
시간 관련 함수와 re( 정규식)  관련 함수를 사용할 수 있도록 해주세요.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
pylambda 명령어에 모듈을 임포트 할 수 있도록 옵션을 추가 하였습니다.

re 를 예로 들자면 아래와 같이 이용할 수 있습니다.
```
* | fields HOST | pylambda row: True if re.search('gcs', row[0]) else False import re
```

명령어 사용법 문서는 아래 링크를 참조하시면 됩니다.
http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/pylambda.html
