### ISSUE TITLE
GNB 메뉴 - 기능

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#2005]
![스크린샷 2020-03-16 오전 9 22 39](https://user-images.githubusercontent.com/3415270/76713992-dc16de00-6767-11ea-8ef7-29583a937ae1.png)

위의 이미지에서 톱니바퀴를 클릭할 경우
자신의 계정 정보에 대한 정보를 수정할수 있는 메뉴로 이동을 해야 할것 같은데,
아무 반응도 일어나고 있지 않습니다.

해당 메뉴의 기능을 잘못 알고 있는 것인지, 동작 오류인지 확인을 부탁 드립니다.

**Comment by rhcpn** [comment]
해당 기능은 아직 개발 중이라 그렇습니다. Issue Close 하도록 할께요.
