### ISSUE TITLE
hdfs-browser: 서비스 선택 combo 에 disabled 효과 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2006]
## 버그 설명 ##
hdfs-browser: 서비스 선택 combo 에 disabled(비활성화) 효과 없음

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/76714958-63b31b80-676d-11ea-95e4-f58589445dae.png)

![image](https://user-images.githubusercontent.com/3411842/76714962-6877cf80-676d-11ea-80ed-f0ed80e5c9de.png)

**Comment by onlyeon** [comment]
이슈 반영한 CSS IRIS-Design-System 레파지토리에 올려두었습니다. 확인 및 적용 부탁드립니다.
