### ISSUE TITLE
[Analyzer] 검색메뉴에서 JOIN명령어 후 파이프로 결과 조회 시 컬럼이름이 출력되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2010]
## 버그 설명 ##
검색명령어에 

`  * | JOIN INNER SEOUL_FIRE_STA_COOR SEOUL_GU_COORDINATES. FIRE_CENTER = 
  SEOUL_FIRE_STA_COOR.NAME | fields +GU_CODE,GU_NAME`

처럼  JOIN  .. | fields 나 sql 명령어 사용 후 결과에 컬럼이름이 표시되지 않습니다.

<img width="1130" alt="스크린샷 2020-03-16 오후 3 49 46" src="https://user-images.githubusercontent.com/5126497/76730373-72fe8d00-679e-11ea-8776-200032a4fa40.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 분석탬플릿  "err_demo_join후컬럼이름안나옴"  을 참고하세요

**Comment by seoryjj** [comment]
분석탬플릿에서 가져와서 실행하면 컬럼이 보입니다.

**Comment by veldise** [comment]
4/7(화) 09:45 기준 재현되지 않아 닫습니다.
재현되면 Reopen 해주시고 사용하시는 브라우저 및 브라우저 버전 등을 알려주세요.

![image](https://user-images.githubusercontent.com/3411842/78618104-71634900-78b4-11ea-8905-faeac87bfdf5.png)
