### ISSUE TITLE
studio: 화살표 키 입력으로 객체 이동 개선

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2011]
## 기능 요청 ##
- 이슈 제기: 3/16 보드 미팅
- studio: 화살표 키 입력으로 객체 이동 개선

## 원하는 솔루션 설명 ##
- 객체 선택 후, 키보드로 이동 시 버그
- 객체 선택 후, 키보드 다운을 연속으로 받아들여서 이동을 시키고 싶다

**Comment by sunghoon** [comment]
@veldise 해당 기능에 대한 조치 바랍니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
현재 보고서 편집화면에서 Input, Textarea 등 키보드 입력을 받는 객체가 있어서 생각보다 어려운 작업입니다.
기간을 길게 잡고 진행할 예정입니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
해당 이슈는 11월 업무로 진행 예정입니다.
정확한 일정은 추후 재 등록 하겠습니다.

**Comment by sunghoon** [comment]
@veldise 입력을 받는 객체가 있어도, 이벤트를 처리하는 단에서 객체의 입력모드 여부를 토글로 처리하면 되는부분이라 생각합니다. 
Studio는 점점 편집의기능을 강화해야 합니다. 관련된 목표일정정보를 공유해 주세요.

**Comment by sunghoon** [comment]
@rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 업무 진행 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
아직 업무량 산정 및 일정 계획 중입니다. 차주 월요일(11/23)에는 정리해서 말씀드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
12/10 패치를 목표로 진행하겠습니다.
