### ISSUE TITLE
Studio: 체크박스에서 이벤트 변수 적용 안되는 문제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#2014]
## 버그 설명 ##

![image](https://user-images.githubusercontent.com/35832986/76739835-26bc4880-67b0-11ea-83fd-ae411bb47073.png)

위 캡처 사진의 보고서는 psi 계정의 "체크박스 이벤트 변수 버그" 보고서입니다.

설정은 다음과 같습니다

1) 콤보박스에서 값을 선택
2) 체크박스에서 콤보박스의 이벤트 변수의 값을 가지고 쿼리를 돌려서, where 조건에 필터링 된 결구만으로 체크박스를 생성하고자 함
3) 분명 이벤트 변수가 제대로 된 걸로 보이는데 작동하지 오류가 발생함

**Comment by veldise** [comment]
현재 #1957, #1980 과 같은 문제가 있어 수정중입니다.
