### ISSUE TITLE
Analyzer] 검색 결과로 나온 데이터를 MINIO 로도 내보내기하여 저장할 수 있게 해주세요. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2016]
## 기능 요청 ##
현재 검색결과 내보내기 기능에는  로컬과  HDFS 만 있는데
MINIO 를 추가해주세요.
<img width="962" alt="스크린샷 2020-03-17 오전 10 14 56" src="https://user-images.githubusercontent.com/5126497/76812545-937b2580-6838-11ea-839d-fe13771b8a81.png">

<img width="304" alt="스크린샷 2020-03-17 오전 10 15 07" src="https://user-images.githubusercontent.com/5126497/76812549-9544e900-6838-11ea-85d0-e0085ba12f84.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 해 주세요.

**Comment by veldise** [comment]
@seungfwani 
아래와 유사한 명령어가 필요합니다.
```
model name = 'syslog' model_owner = eva start_date = 20200923152000 end_date = 20200923152122
    | minio csv WRITE '/choi/syslog-test/download.csv' OPTION( sep ',' , name 'root' , group '' , connector_id '177' )
```

**Comment by veldise** [comment]
@seungfwani 
아래와 유사한 명령어가 필요합니다.
```
model name = 'syslog' model_owner = eva start_date = 20200923152000 end_date = 20200923152122
    | minio csv WRITE '/choi/syslog-test/download.csv' OPTION( sep ',' , name 'root' , group '' , connector_id '177' )
```

**Comment by sunghoon** [comment]
@rhcpn @eumminsun @veldise @anhm DSL 명령어가 준비되었으니 UI에서 관련 내용을 처리할 수 있도록 마무리 해 주시기 바랍니다.
