### ISSUE TITLE
[NMS+]studio 버튼의 font size 변경

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2017]
## 기능 요청 ##
버튼 콤포넌트에 그림자/색상등 변경할수있는 부분이 많이 적용되어서 잘쓰고 있습니다.

그런데, 기본폰트 사이즈가 너무커서 조금 촌스러워보이는 경향이 있습니다.
studio 버튼의 font size 도 변경가능하게 부탁드립니다.

아마 제가 font size 변경요청을 하면 추후 누군가가 폰트 색상/폰트체 등 요청을 하겠죠?
따라서 label 처럼, font 관련 설정도 적용되면 좋을거같습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
일정을 고려하여 font-size만 먼저 처리할 예정입니다.
