### ISSUE TITLE
[교통플랫폼] 오픈분석 패키지 3종(R-Studio, 제플린,주피터) 서비스 포트 관련

### ISSUE THREAD

**Issue by suk555** [mobigen/IRIS-BigData-Platform#2018]
## 기능 요청 ##
오픈소스를 환경을보니 설정한 대역의 IP를 오픈분석 앱 당 4포트를 사용하는구조입니다.(SSL사용)
즉, 주피터 4 포트 + R-Studio 4 포트, 제플린 4 포트입니다.
사용자가 분석웹에 접속 후 모든 오픈 분석도구를 클릭한다면 한 사용자당 12포트를 사용합니다.
그래서 고객쪽 방화벽을 충분히(많은 포트를) 오픈해야하는 상황이 발생합니다.

## 원하는 솔루션 설명 ##
사용자가 접속하는 포트는 오픈 분석앱당 1개로 제한하고 내부 접속 포트는 다른 설정의 포트를 사용하는 것 입니다.

## 기타 ##
포트별 사용 용도는 다음과 같습니다.
Spark Drive, Spark Block Port, Web http(ssl 사용시에도 기본 할당됨), Web ssl

교통플랫폼만 아니라 고객사에도 해당하는 사항이기때문에 개선이 필요한 내용입니다.

**Comment by sunghoon** [comment]
@anhm 해당 이슈 최종 상태 정보를 공유 해 주세요 .

**Comment by anhm** [comment]
@sunghoon 
해당 문제는 ext-manager의 고질적인 문제입니다.
ext-manager는 더이상 유지보수 하지 않으며,
play-ground로 업그레이드를 진행해야 합니다. 
iwp, iris-entry 등의 버전이 같이 올라가야 하는 이슈가 존재합니다.

**Comment by sunghoon** [comment]
@suk555 @anhm 오팀장님 새버전으로 배포 가능할까요?

**Comment by sunghoon** [comment]
@suk555 다른 방법으로 해결된 것으로 보고 본 이슈는 닫습니다. 필요하면 새 이슈로 다루겠습니다.
