### ISSUE TITLE
[밸류링크유] 챠트 툴팁 표시 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2020]
## 버그 설명 ##
차트에 마우스 오버시 데이터가 많을 경우 툴팁이 다 안보이는 현상

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/77039099-8c027a80-69f8-11ea-8574-122c47423e4f.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#1433 동일 이슈입니다.
