### ISSUE TITLE
검색화면 기능 오류

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2021]
## 버그 설명 ##
왼쪽 컬럼 클릭하여 대강의 통계를 보는 화면에서 오류 발생.

![스크린샷 2020-03-19 오후 4 59 20](https://user-images.githubusercontent.com/512653/77044653-236ccb00-6a03-11ea-9a91-9aaea87cb793.png)

**Comment by seungfwani** [comment]
원인을 파악한 바로, csv 데이터 자체의 문제로 보입니다.

해당 데이터를 보면 아래와 같습니다.
```
id, sentence_text, type_text
1, 읽기가 어렵다. 난독(難讀)이다. 읽어도 ... 매너가 됐다., text
```

첫 번째 라인을 헤더로 처리를 하는데 처리 기준은 콤마(`,`) 입니다.
그러나, 데이터를 보면 space(` `) 문자가 헤더명에 붙어 있는 것을 확인 할 수 있습니다.

예를 들어 `id` 컬럼을 클릭하시면 아래와 같이 정상적으로 나오는 것을 확인 할 수 있습니다.
![Screen Shot 2020-05-07 at 11 55 30 AM](https://user-images.githubusercontent.com/46172579/81249474-aa304280-9059-11ea-9b5b-dd06ad93040f.png)

**Comment by seungfwani** [comment]
이슈 닫도록 하겠습니다.

동일 문제 발생 시 재 오픈 해주시기 바랍니다.
