### ISSUE TITLE
지도기능 추가 요청(정보, 텍스트 박스), 다중 레이어 중첩시 화면 표시

### ISSUE THREAD

**Issue by lunamay** [mobigen/IRIS-BigData-Platform#2023]
## 기능 요청 ##
![image](https://user-images.githubusercontent.com/4329340/77142462-858d0500-6ac3-11ea-9d3e-f4e7875b0b00.png)

위는 수원시 마스크 사용에 대하여 실시간 표현을 해본 리포트 입니다.

각 구별 지도가 4장으로 투명하게 겹쳐 있는상황인데 표현이 되지 않습니다.

그리고 레이어 위에 올려야만 어떤구 인지 표현이 되고 있습니다.

각 지도위에 표현 되는 문구를 박스형태로 올리고 해당 내역에 대한 값도 정의 할수 있어야 합니다.

97%만들고 박스 표현이 안되어 서비스를 할 수가 없습니다.

아래 홈페이지의 내용을 전부 구현할수 있는데 딱 저 부분이 문제 입니다.!

![image](https://user-images.githubusercontent.com/4329340/77143906-d69ef800-6ac7-11ea-81ae-881ce60ce6ef.png)

**Comment by veldise** [comment]
어제(3/19) 패치로 Map 객체의 시각화 유형 중에 'Label'이 추가되었습니다.
이에 따라 아래와 같이 위경도에 따라 텍스트를 지도 위에 출력할 수 있습니다.

다만 본문 예시와 같이 수치값도 같이 출력하는 것은 기획/검토/개발이 필요합니다.

![image](https://user-images.githubusercontent.com/3411842/77143020-3cd64b80-6ac5-11ea-8d84-011b58366130.png)

**Comment by sunghoon** [comment]
요청 기능 배포된 것으로 보고 닫습니다.
