### ISSUE TITLE
나에게 공유된 보고서/분석 템플릿의 공유 해제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#2024]
## 기능 요청 ##
보고서/분석 템플릿 중 다른 사용자가 공유해준 ("모든 사용자" 에게 공유한 경우 포함) 보고서/분석 템플릿의 공유를 취소할 수 있는 기능 필요

![image](https://user-images.githubusercontent.com/35832986/77147542-d525fd80-6ad0-11ea-8ced-2ff216d60624.png)

위 스크린샷은 중국 시연용 계정의 보고서입니다.

현재 해당 계정에는 다른 사용자로부터 공유받은 다양한 보고서들이 표시되고 있는데, 공유를 받은 계정에서는 해당 보고서들이 무조건 표시될 수 밖에 없습니다.

특히 "모든 사용자"로 공유된 경우는 공유받은 사용자에게 필요하지 않은 혹은 공유되어선 안될 보고서가 보이는 경우가 있습니다.

이런 경우를 해소하기 위해서 공유하는 사람이 보고서/분석 템플릿에 대한 접근 권한을 설정하는 것 외에 공유를 받은 사람도 자신에게 부여된 공유를 해제할 수 있어야 한다고 생각합니다.

## 원하는 솔루션 설명 ##
기능은 다음과 같습니다.

- 모든 사용자는 자신에게 공유된 보고서/분석템플릿의 공유를 해제할 수 있다
- 공유받은 보고서/분석 템플릿의 공유를 해제하면, 해당 보고서/분석 템플릿의 소유자가 다시 공유해줄 때 까진 접근할 수 없다
- 자신이 공유받은 보고서/분석 템플릿을 다른 사용자에게 공유할 수는 없다
- 공유받은 보고서/분석 템플릿을 수정하거나 삭제할 수는 없다

## 고려한 다른 대안 ##
대안은 아니지만 앞서 요청드린 기능이 구현되기 전에는 우선
"내가 만든 보고서/분석 템플릿만 보기" 또는 "공유받은 보고서/분석 템플릿 가리기" 등의 기능이 있으면 당장 화면에 많은 보고서들이 표시되는 경우는 피할 수 있을거라 생각합니다.

**Comment by joohj7** [comment]
#2133

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 진행해 주시기 바랍니다.
