### ISSUE TITLE
studio: Chart / Motion 유형 툴팁 위치 오류

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2026]
## 버그 설명 ##
studio: Chart / Motion 유형 툴팁 위치 오류

모션 차트 툴팁이 마우스오버 대상인 원과 다소 다른 위치에 나타납니다.
심한 경우, 화면에서 보이지 않습니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/77373845-a055c700-6dac-11ea-8c00-8c100709e90b.png)

**Comment by sunghoon** [comment]
@veldise 해당 기능에 대한 개선 요청드립니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
5년 이상된 동결된 d3.js 코드를 수정해야 하는 작업입니다. 시간이 다소 소요될 것으로 생각되어 기간을 길게 잡고 진행하려고 합니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
해당 이슈는 11월 업무로 진행 예정입니다.
정확한 일정은 추후 재 등록 하겠습니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정 정보를 공유해 주세요.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 11월까지는 업무가 산적해있어 12월 중에 진행하려고 합니다. 차주 중에 일정 수립하여 알려드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
12/3 릴리즈를 목표로 진행하겠습니다.
