### ISSUE TITLE
[보고서] 보고서 목록에서 "편집" 컨텍스트 메뉴 위치

### ISSUE THREAD

**Issue by AlexNa** [mobigen/IRIS-BigData-Platform#2027]
## 버그 설명 ##
![image](https://user-images.githubusercontent.com/3666301/77400525-aa001e80-6dee-11ea-9954-fc2575217a91.png)
보고서 목록에서 "편집" 버튼 클릭시 메뉴가 다른 위치에 나타납니다.

## 재현하는 방법 ##
1. 목록 조회 후 "편집" 메뉴 위치 정상
![image](https://user-images.githubusercontent.com/3666301/77400684-e6337f00-6dee-11ea-9163-38675eb135b9.png)
2. "목록개수"를 **50개로 변경하고 스크롤을 최하단**으로 내린 후 "편집" 버튼을 클릭하면 메뉴가 다른 위치에 나타남
![image](https://user-images.githubusercontent.com/3666301/77400865-3579af80-6def-11ea-82a3-e2674cfa2190.png)

**Comment by veldise** [comment]
마우스 스크롤하면 메뉴가 사라지도록 처리하겠습니다.
