### ISSUE TITLE
Studio/Combo 객체 디폴트값 설정관련

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2028]
## 기능 요청 ##
보고서 작성중 콤포박스에 DB에 있는 날짜를 내용으로 할때가 있는데 디폴트 설정을 콤보박스 항목 중 첫번째 또는 마지막 항목을 디폴트 항목으로 설정하는 기능이 있으면 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
