### ISSUE TITLE
extra_param 으로 보고서 하이퍼링크

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2029]
## 버그 설명 ##
 extra_param 을 이용해서 보고서를 불러올때, 변수에 ${컴포넌트 변수명} 을 입력하면
400 에러를 내뱉습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
 보고서를 외부 URL로 만들어서
extra_param을 넣는 URL을 만들어줌.

var reportURL = 'http://192.168.100.180:80/studio/exported/13a9ebb06745470db6c08b382f6c833a7fdf8de2731f4e23a9eca71ce2c8d31c';
var variableJSON = {
    "canvas_1": "g3"
};
var extraParam = encodeURIComponent(JSON.stringify(variableJSON));
var queryStr = 'extra_param=' + extraParam;

var url = reportURL + '?' + queryStr;

console.log(url);

http://192.168.100.180:80/studio/exported/13a9ebb06745470db6c08b382f6c833a7fdf8de2731f4e23a9eca71ce2c8d31c?extra_param=%7B%22canvas_1%22%3A%22g3%22%7D

위의 g3에 ${canvas_1} 등의 변수를 넣어줌.

![image](https://user-images.githubusercontent.com/16331916/77488119-a664aa00-6e77-11ea-9ab9-e218a7cbe00d.png)

값을 읽어오는게 아닌 ${canvas_1} 이라는 문자열 자체를 URL 에 넣어줘서 유효한 문자가 아니라는
에러를 내뱉음

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
현재 버튼의 주소 입력란에는 변수 문법(ex) `${var_1}`)을 사용할 수 없습니다.
기능을 추가해야 합니다.
