### ISSUE TITLE
[분석탬플릿] 에서 구분이 "검색" 일때는 자동실행 , "고급시각화" 일 때는 자동 실행이 아닙니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2032]
## 버그 설명 ##
검색 메뉴 에서 만든 분석탬플릿은 클릭해서 불러오기만 하면 바로 실행이 되는데
고급시각화에서 만든 분석탬플릿은  **실행** 버튼을 눌러야만 합니다.

**Comment by veldise** [comment]
@seoryjj 
부하를 고려하여 검색도 바로 실행이 되지 않도록 개선하겠습니다.

**Comment by veldise** [comment]
개선점이 아니고 버그로 확인되었습니다.
