### ISSUE TITLE
studio: popup 이 열릴때 기존 보고서 초기화 문제

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#2033]
## 버그 설명 ##
이슈 보고 : @jjinylee
보고서에 버튼을 클릭하여 팝업을 열게되면 기존 보고서의 차트가 초기화 됩니다.
차트는 다시 조회하는 동작이지만 TAB 객체는 선택된 탭이 아닌 1번 탭으로 초기화 되면서 객체가 안보이게 됩니다.

## 재현하는 방법 ##
1. 보고서를 만들고 탭을 생성한다.
2. 두개 이상의 탭을 만들고 1번탭과 2번탭의 차트를 다르게 설정한다.
3. 버튼과 팝업을 만들어 팝업버튼을 생성한다.
4. 미리보기후 탭의 2번째 항목을 선택 - 2번탭에 속한 차트가 열림 - 
5. 팝업을 열면 4번에서 열려있던 차트가 사라진다.

## 예상한 행동 ##
탭에 속한 차트가 정상적으로 보임

## 스크린샷 ##
2번 탭을 선택 -> 리스트 객체가 열림
<img width="894" alt="스크린샷 2020-03-27 오전 7 26 18" src="https://user-images.githubusercontent.com/49141403/77702629-4d724e80-6ffc-11ea-94ea-485f85dea6b4.png">
팝업을 열면 리스트 객체가 사라짐
<img width="894" alt="스크린샷 2020-03-27 오전 7 26 27" src="https://user-images.githubusercontent.com/49141403/77702659-5f53f180-6ffc-11ea-9978-07e29d59700c.png">

## 기타 ##
리스트 혹은 차트가 1번 탭에 속해있고 자동 선택일때는 챠트가 다시 그려지는 현상이 발생함

**Comment by jjinylee** [comment]
요건, NMS+ 인수시험중 fail 건이라서 빠른처리가 필요합니다.

3/31(화) 에 고객 시험예정이라 그전에 배포까지 되어야합니다

**Comment by veldise** [comment]
@jjinylee 
검토해서 3/31까지 해결 가능한지 3/30(월)에 연락드리겠습니다.
