### ISSUE TITLE
studio: 날짜/시간 설정 객체 변수 값을 자동실행으로 사용시 오류

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#2034]
## 버그 설명 ##
이슈보고 : @jjinylee
차트 객체의 검색어에 '날짜/시간 설정' 객체 변수를 사용하고 자동실행 설정한 경우,
보고서를 실행시 간헐적으로 변수 값이 '00:00' 으로 설정되어 오류가 발생

## 재현하는 방법 ##
1.  '날짜/시간 설정' 객체 변수를 이용하여 차트를 설정하고 자동실행 설정
2. 보고서 미리보기를 하면 간헐적으로 `결과가 없음`으로 표시됨

## 예상한 행동 ##
설정된 시간값에 의해 차트 조회 됨

## 기타 ##
`결과 없음`으로 표시될 때 로그를 확인하면 날짜 값이 정상적이지 않은 상태로 조회가 이루어짐

**Comment by veldise** [comment]
@jjinylee
말씀하신 '데이터 객체'가 정확히 어떤 객체인지 설명을 부탁드립니다.

**Comment by swish1995** [comment]
@veldise
<img width="103" alt="스크린샷 2020-03-27 오전 9 32 37" src="https://user-images.githubusercontent.com/49141403/77709294-e9f11c80-700d-11ea-97cd-d786a8863809.png">
해당 객체입니다.

**Comment by jjinylee** [comment]
요건, NMS+ 인수시험중 fail 건이라서 빠른처리가 필요합니다.

3/31(화) 에 고객이 재시험예정이라 그전에 배포까지 되어야합니다

**Comment by veldise** [comment]
@jjinylee 
검토해서 3/31까지 해결 가능한지 3/30(월)에 연락드리겠습니다.
