### ISSUE TITLE
데이터 모델에서 검색

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2035]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

 Postgresql 을 이용해서 데이터 모델을 만들고 검색을 하니 아래와 같은 에러가 나옵니다.
전체시간으로 조회를 하면 검색이 되는데, 최근 1분, 지난 1분으로 검색하면 아래와 같은 오류가 찍힘
![image](https://user-images.githubusercontent.com/16331916/77708417-63d3d680-700b-11ea-8082-76b74b309321.png)

## 예상한 행동 ##
 위 시간에 데이터가 없다면, 이벤트가 0으로 검색이 되야 한다고 생각함

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
해당 에러는 앙고라에서 예외처리 하지 못한, spark 작업 에러이며,
위에 보이는 메세지 만으로는 어떤 문제인지 파악하기 어렵습니다.

스크린샷과 같은 조건으로 실행을 해보았지만, 정상동작하였습니다.
![Screen Shot 2020-04-03 at 7 24 43 PM](https://user-images.githubusercontent.com/46172579/78350828-c9fac380-75e0-11ea-98b7-c0d89958eea4.png)

------

실행 할 당시 서버에 문제가 있었을 것이라 추측됩니다...

**Comment by seungfwani** [comment]
비슷한 상황이나 질문 등이 있다면 재오픈 해주세요.
