### ISSUE TITLE
[Discovery Service] mlmodel 명령어를 사용할 때 문제점(192.168.100.180 서버에서 시험)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2037]
## 버그 설명 ##
1. 검색 메뉴에서 mlmodel 명령어를 사용하려면 꼭 데이터 모델을 지정해야 합니다. 
특정 모델을 지정하여 
`* | mlmodel list`
를 실행하면 저장된 mlmodel 리스트가 다 나옵니다. 
그러면 굳이 지정할 필요가 없습니다.

2. 다른 문제는 모델이 5000 개가 넘게 저장되어 있는 경우에는  제가 방금 만든 모델이 결과에서는 보이지 않습니다.

<img width="1133" alt="스크린샷 2020-03-27 오후 2 38 19" src="https://user-images.githubusercontent.com/5126497/77725613-3d2c9480-7039-11ea-9870-cf7b2f052069.png">
 -> 5000 개를 넘으면서 2020년에 만든 것은 결과에 안 나옵니다... 2019년 만든 모델들만 보입니다.

* 데이터모델을 지정하지 않으면 다 보이게 하고,
관련된 데이터모델을 정하면 해당 데이터모델로 만든 mlmodel  만  결과로 나오는 게 맞는 거 같습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
UI의 검색 창에서는 최대 200개의 결과를 보여줍니다.

모델의 개수는 5000개가 넘어, 처음 200개만 보여지기 때문에 발생한 문제 같습니다.

`* | mlmodel list | sort -saved_date` 와 같이 sort를 해보면 2020년에 만든 모델도 확인 할 수 있습니다.

![Screen Shot 2020-03-27 at 3 28 50 PM](https://user-images.githubusercontent.com/46172579/77728344-aa432880-703f-11ea-843e-330f7683530d.png)

**Comment by seungfwani** [comment]
구두상으로 설명이 되었다고 생각 되며 동일 문제가 있을시 재 오픈 하도록 하겠습니다.
