### ISSUE TITLE
감사로그 조회시 100개까지만 화면표시되고, 페이징 처리등이 되지 않은 오류 보고

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#2038]
## 버그 설명 ##
 * **_감사로그 조회시 100개까지만 화면표시되고, 페이징 처리등이 되지 않은 오류 보고_**

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS 로그인 후 '감사로그'  화면에 들어가서
2. 시작 날짜는 2020-03-27 10시로 하고 현재날짜(2020-03-29 13시)까지 조회하면,
3. 아래 스크린샷과 같이 2020-03-27 23시부터만 화면에 조회결과(100개 제한)가 나오고, 더 이상 조회되지 않음.

## 예상한 행동 ##
  * 감사로그 조회시 100개까지만 화면표시되고, 페이징 처리등이 되지 않음.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3426052/77839972-03849680-71bd-11ea-84b2-237c0cc6366d.png)

## 로그 ##
-

## 기타 ##
-

**Comment by veldise** [comment]
@idaeho 
조회 결과가 100개 인 것은 아래와 같이 개수제한이 있기 때문입니다.
개수제한 조정 후 조회 시 정상 조회되는 것을 확인했습니다.

![image](https://user-images.githubusercontent.com/3411842/77863204-91af5a00-725b-11ea-814f-787a0266af38.png)

페이징 처리는 팀장님과 상의해보겠습니다.

**Comment by veldise** [comment]
페이징 처리에 대해서는 grid-view 모듈을 Ag-Grid로 교체하여 virtual-scroll 을 적용하는 것으로 해결하였습니다.
이에 이슈 닫습니다.
