### ISSUE TITLE
[Discovery] fit DecisionTreeClassification 에서 결과를 Tree 로 시각화할 수 있게 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2039]
## 기능 요청 ##
시험 : 192.168.102.140  분석탬플릿이름 : DEMO_fit_결정트리_v01

DecisionTree 모델 결과가 다음처럼 표시되는데, DecisionTree모델은 tree 을 시각화하여 보여줄수 있는 장점이 있는 알고리즘입니다. 하지만 결과는 모델의 정확도나 feature 에 대한 대략적인 판단만을 제공합니다.

<img width="925" alt="스크린샷 2020-03-30 오전 9 10 13" src="https://user-images.githubusercontent.com/5126497/77864885-477fa600-7266-11ea-9db0-076e70cfbf64.png">

따라서 모델의 결과를 시각화하여 보여 줄 수있도록  pySpark 의 결과를 
json 으로 저장하거나
추후에는  tree를 시각화하는 화면도 필요합니다.

일단은 json 으로 저장하는 방법에 대한 참고 사이트입니다. 

아래 답변 예제는  모델로부터 tree 를 그릴 수 있는 json 파일을 생성하는 예제입니다.

요청사항에 대한 답변 참고  : https://stackoverrun.com/ko/q/8772441
pySprk code( json 으로 저장하는 )  : https://github.com/tristaneljed/Decision-Tree-Visualization-Spark/blob/master/DT.py#L51-L64

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 시각화 유형 추가를 위해 관련 사항에 대한 기획을 요청드립니다.
