### ISSUE TITLE
[Discovery] 140 서버 mlmodel list 에 동일이름의 모델 저장됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2040]
## 버그 설명 ##
mlmodel 에 동일 이름의 모델이 생성되고, 저장됩니다.
(140 서버에서 시험)

<img width="923" alt="스크린샷 2020-03-30 오전 9 44 37" src="https://user-images.githubusercontent.com/5126497/77865788-15247780-726b-11ea-9d1c-c7d02d019897.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
같은 이름은 저장되지 않도록 수정하였습니다.
또한 180번으로 모두 merge 하였기 때문에 180번에서 사용하시면 됩니다. :-)
