### ISSUE TITLE
[Analyzer] 검색메뉴에서 검색결과 내보내기 에서 에러메세지가 뜹니다.(192.168.100.180)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2042]
## 버그 설명 ##
* myiris 계정
* 검색 메뉴에서 다음 조건으로 조회되어 나온 결과를 내보내기(약 76만건)
<img width="962" alt="스크린샷 2020-03-30 오전 10 58 36" src="https://user-images.githubusercontent.com/5126497/77868372-f24b9080-7275-11ea-8768-b8ef45c0ed0a.png">

* 약 5분 후에 뜬 화면
<img width="1145" alt="스크린샷 2020-03-30 오전 10 50 55" src="https://user-images.githubusercontent.com/5126497/77868349-da740c80-7275-11ea-8620-f0622c1c91a6.png">

* 검색을 다시 하려고 하니 메뉴화면이 비활성화됨
<img width="722" alt="스크린샷 2020-03-30 오전 11 00 25" src="https://user-images.githubusercontent.com/5126497/77868361-e52ea180-7275-11ea-8bb7-249d66811020.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@veldise 
같은 테스트를 진행하였을 때
`sherman` 도커가 `java heap space` 에러로 죽는 현상이 있었습니다.

**Comment by sunghoon** [comment]
@veldise 메모리 이슈에 대한 대응을 준비해 주세요.

**Comment by anhm** [comment]
해당 이슈는 내부적으로 처리가 되었기 때문에 닫도록 하겠습니다.
