### ISSUE TITLE
(Safari) studio: Label / 글자 작성 및 마우스 우클릭 동작하지 않음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2043]
## 버그 설명 ##
Safari 브라우저에서 Label 객체 - 글자 작성 및 마우스 우클릭 동작하지 않음

**Comment by swish1995** [comment]
@onlyeon 
[safari text 입력안되는 버그 수정](https://github.com/mobigen/B-IRIS-Studio-service/pull/35)
해당 문제는 기존이슈로 해결되었던 문제였으나 
style 적용으로 text-area 하위에 inner-text 클래스를 추가하면서 다시 발생한것으로 확인되었습니다.

기존에 .text-area[contenteditable] 에 적용되는 해당 부분을 .inner-text 로 변경하면 해결되는것으로 확인되었습니다.

css 수정 요청드립니다.

**Comment by veldise** [comment]
@youngjiring

**Comment by veldise** [comment]
#1882 동일 이슈
