### ISSUE TITLE
[NMS+]앙고라 쿼리 에러

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2046]
## 버그 설명 ##
*| sql " select GROUP_NAME , SDATM, ROUND(IN_BPS_MAX/1024/1024/1024,2) as IN_BPS  from angora where GROUP_ID in ( 13791,13792,13793,13794)" |  adv line max(IN_BPS ) SPLITROW 'date_group("SDATM", "1d")' SPLITCOL GROUP_NAME

max(IN_BPS )  함수에 (  ) 안에 공백이 있으면 에러가 납니다.

![1](https://user-images.githubusercontent.com/5468183/77976499-24252b80-7338-11ea-8e85-7cf00d4e3e32.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
해당 이슈 해결완료 하였고, 사이트 배포 요청하도록 하겠습니다.

**Comment by seungfwani** [comment]
배포 완료되었습니다.
![Screen Shot 2020-04-24 at 10 04 50 AM](https://user-images.githubusercontent.com/46172579/80164098-0c795400-8613-11ea-8dfc-aa6787508f24.png)
