### ISSUE TITLE
analyzer: 샘플링 다이얼로그에 padding 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2047]
## 버그 설명 ##
analyzer: 샘플링 다이얼로그에 padding 발생

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/77974135-39e32280-7331-11ea-8cfe-65889f846483.png)

![image](https://user-images.githubusercontent.com/3411842/77978995-63ef1180-733e-11ea-8ccd-347b9f9c68a5.png)

**Comment by onlyeon** [comment]
해당 내용은 이슈 발견하여 작업 해두었습니다. 
sherman 최신 CSS로 갱신 부탁드려요-
