### ISSUE TITLE
[NMS+]studio 그리드 개선(고객요청사항)

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2050]
## 기능 요청 ##
1.     Studio

A.     Grid 의 넓이가 충분히 넓지 않은 경우에 컨트롤바가 3단이 되버리는 현상
목록개수의 내용에 비해 차지하는 넓이가 너무 넓은듯;; 어차피 100까지 밖에 선택이 안되는데~

그리고 paging 의 수를 넓이에 맞춰 적당히 조절해줘야 할 듯

그리고 grid 에서는 목록의 “전체 수”를 보여주면 좋을 듯 (지금은 다운로드 하거나 # 열을 추가해서 확인하는 방법밖에 없어서 매우 불편)

![11](https://user-images.githubusercontent.com/5468183/77991163-15ea0600-735e-11ea-8a4b-ac14f2b001c5.PNG)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
"전체 개수"를 보여주는 기능은 아래와 같은 형태가 될 것으로 예상됩니다.
ex)
`264개 항목 중 20개 표시`

**Comment by veldise** [comment]
"목록개수의 내용에 비해 차지하는 넓이(width)가 너무 넓은 문제"는 5/14 패치 예정입니다.
