### ISSUE TITLE
 [Discovery] MinIO 에 업로드하는 파일이름에 iris 가 있으면, 데이터모델이 생성은 되어도 검색에서 읽을 수 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2052]
## 버그 설명 ##
192.168.100.180   demo 계정

데이터 모델 :  DEMO_TRAIN_IRIS  
-> minIO 에 업로드한 파일이름 : Train_iris_data.csv 

* 검색 메뉴에서 조회 시 에러
<img width="514" alt="스크린샷 2020-03-31 오후 4 31 00" src="https://user-images.githubusercontent.com/5126497/77999062-0cb46580-736d-11ea-8bcf-7f7db63c59cc.png">

* 같은 내용으로 iris 대신 다른 이름으로 올리면
<img width="734" alt="스크린샷 2020-03-31 오후 4 34 30" src="https://user-images.githubusercontent.com/5126497/77999358-82203600-736d-11ea-9e5a-a24a4c70b2a6.png">

에러 안납니다

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
해당 부분을 해결하였습니다. 
운영서버 배포 후 다시 알려 드리겠습니다.
