### ISSUE TITLE
검색 피봇 지도 관련 에러 리포트

### ISSUE THREAD

**Issue by lunamay** [mobigen/IRIS-BigData-Platform#2053]
![image](https://user-images.githubusercontent.com/4329340/78087975-bfcc9f80-73fd-11ea-8bb2-83bb455b7c79.png)

![image](https://user-images.githubusercontent.com/4329340/78087996-cce98e80-73fd-11ea-9da0-5f8aa9613dbc.png)

**Comment by lunamay** [comment]
동일 데이터 중복으로 들어간 케이스 그래프 표시가 잘못 표시되는 문제는 인계동, 무슨동,무슨동,5.00,4.00,3.00 이런식으로 범위가 잘못 나오는등의 문제가 있습니다.

중복데이터셋이 있는경우로 테스트 하시면 됩니다.

![image](https://user-images.githubusercontent.com/4329340/78092721-6e2b1180-740b-11ea-89cb-756401df1d05.png)

**Comment by veldise** [comment]
@lunamay 
본문 내용에 대하여 몇가지 보충을 부탁드립니다.

0. 대상 사이트 or 프로젝트
해당 이슈가 수원시가 맞나요?

1. DB 브라우저 / 데이터 건수가 큰 테이블 엑셀 다운로드
대강 몇 건의 데이터에 대하여 다운로드 하였는지 궁금합니다.

2. 보고서 / 동일 데이터 중복시 Top 차트
이미지가 열화되어 정확한 내용을 파악하기가 힘듭니다.
비교할 수 있을만한 실 DB 정보 / 검색어(DSL) 예시를 부탁드립니다.

3. 피벗 / 필터 설정 or 설정 해제 후 다른 화면 이동시 에러
현재 최신버전 (b-iris.mobigen.com) 에서는 재현되지 않습니다.
원인 파악을 위해 보다 자세한 내용을 첨부해주시면 감사하겠습니다.

**Comment by veldise** [comment]
@lunamay 
막대형 차트의 카테고리 축 (이미지와 같이 가로막대형인 경우, y축)에 위와 같이 수치가 나오는 경우
DSL 혹은 SQL로 수신한 데이터가 잘못되었을 수 있습니다.

정상:
```csv
y축,x축
인계동,1
무슨동,2
무슨동,3
```
이슈:
```csv
y축, x축
인계동,1
무슨동,2
무슨동,3
5.00,null
4.00,null
3.00,null
```

**Comment by veldise** [comment]
@anhm 
동일 데이터 중복 이슈에 대해서 같이 확인 부탁드립니다

**Comment by lunamay** [comment]
0. 네 수원시 입니다.

1. 5900건정도를 감리가 테스트 했습니다.

2. 그냥 동일 데이터셋 2번 넣고 그래프 그려보면 재현 됩니다.

3. 일단 네트워크가 느린상황에서 보고서를 30분이상 누르면서 보시죠. 그이후에 상황을 보시면 될듯 합니다.

2020년 4월 1일 (수) 오전 11:27, 최영철 <notifications@github.com>님이 작성:

**Comment by veldise** [comment]
@lunamay 
죄송합니다만 제가 DB나 데이터를 다루는데 소양이 부족해서, 동일 데이터셋이 어떤 말인지 잘 이해가 안 갑니다.
아래와 같이 동일한 레코드가 중복해서 들어갔다는 의미인가요?

```
K, P, A
k1, 20201231000000, 1
k2, 20201231000000, 3
k3 20201231000000, 3
k1, 20201231000000, 1
k2, 20201231000000, 2
k3, 20201231000000, 3
```

**Comment by veldise** [comment]
DB조회 한글 깨짐 현상은 아래 이슈로 분리했습니다.
#2054

**Comment by lunamay** [comment]
네. 맞습니다.


2020년 4월 1일 (수) 오후 1:08, 최영철 <notifications@github.com>님이 작성:

**Comment by veldise** [comment]
@lunamay 
거듭 요청드려서 죄송합니다만, "동일 데이터셋 - Top 차트" 이슈가 재현이 어렵습니다.
사용하신 SQL 쿼리를 공유해주실 수 있나요?

**Comment by veldise** [comment]
1. DB 브라우저 / 데이터 건수가 큰 테이블 엑셀 다운로드
본사 데모서버는 syslog 약 12,000건 데이터에 대하여 정상 다운로드 됩니다.

**Comment by readmehong** [comment]
@veldise 

동단위 인구 상위 10개 동에 대한 차트를 생성할 시 사용한 쿼리문 공유 드립니다.




```SELECT 
    BASIS_DATE, GU, DONG as '동', HOUSEHOLD_COUNT, MALE_POPULATION_COUNT, FEMALE_POPULATION_COUNT,
    (MALE_POPULATION_COUNT + FEMALE_POPULATION_COUNT) as '인구수' ,    
    HOUSEHOLD_POLITICAL_PARTY_POPULATION_RATE 
FROM 
    SUWON.SUWON_CITY_STATISTICS_GU_DONG_ACCORDING_TO_POPULATION_STATUS 
    WHERE BASIS_DATE =  ${combo_1}
    ORDER BY  '인구수' DESC
    limit 10
;
```

**Comment by veldise** [comment]
@readmehong 
감사합니다.

**Comment by veldise** [comment]
2. 보고서 / 동일 데이터 중복시 Top 차트
중복 데이터 셋일 때 예외 처리하도록 처리하였고 내일 Hotfix 패치에 포함될 예정입니다.

**Comment by veldise** [comment]
### 4.14 기준 재정리
1. DB 브라우저 / 데이터 건수가 큰 테이블 엑셀 다운로드
현재 재현되지 않습니다. 수원시에서 재현된다면 서버 로그를 확인해봐야 합니다.

2. 보고서 / 동일 데이터 중복시 Top 차트
4.3 패치에서 수정되었습니다.

3. 피벗 / 필터 설정 or 설정 해제 후 다른 화면 이동시 에러
현재 재현되지 않습니다. 원인 파악을 위해 보다 자세한 내용(필터 설정 등)이 필요합니다.

**Comment by sunghoon** [comment]
@lunamay 처리된 것으로 보고 닫습니다. 
다른 특이사항이 있으면 새 이슈로 등록해 주세요.
