### ISSUE TITLE
studio: 보고서 스튜디오 캔바스 사이즈 설정

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2056]
## 기능 요청 ##
보고서 사이즈를 정할 때 나오는 사이즈 메뉴가 좀 더 자세하고 친절하게 나와야 할것 같습니다.
지금은 4개의 미리 입력된 메뉴의 사이즈와 사용자 설정으로 사이즈를 정할 수 있게 되어 있지만 
처음 보고서의 사이즈를 정하는것은 매우 중요합니다.
사용자들이 사용하는 각종 디스플레이에 맞는 사이즈가 제공되어야 합니다.

![개선_canva_sizes](https://user-images.githubusercontent.com/899539/78199456-af342c00-74c6-11ea-9486-25355f3b27e5.PNG)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
아래와 같이 주요 모니터 사이즈와 명칭을 같이 표기하고 

640 X 480 (PX) VGA
720 X 480 (PX) SD
1024 X 768 (PX) XGA
1280 X 720 (PX) HD
1920 X 1080 (PX) FHD
2560 X 1440 (PX) QHD
3840 X 2160 (PX) 4K UHD

![개선_canva_sizes2](https://user-images.githubusercontent.com/899539/78200298-28cd1980-74c9-11ea-831d-76f6fd5bdc6a.png)

사용자 설정에서는 가로와 세로 사이즈를 바꾸는 버튼과 기능제공

![개선_canva_sizes3](https://user-images.githubusercontent.com/899539/78200309-2ff42780-74c9-11ea-8f6c-34ecd27b0aae.png)

**Comment by sunghoon** [comment]
기능 검토 하도록 하겠습니다. 
@eumminsun 확인 바랍니다.
