### ISSUE TITLE
studio: 보기화면의 스크롤바가 생기는 문제 

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2057]
## 버그 설명 ##
보고서 스튜디오로 만든 화면을 외부 URL을 만들거나 
스튜디오 화면에서 보기버튼을 눌러 새창을 만들거나 
모두 그 화면을 F11을 눌러 전체화면을 만들었을 때 
화면의 사이즈가 더 크게 영역이 잡혀서 스크롤바가 생기게 됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 스튜디오에서 1920 X 1080 화면의 보고서를 만든다.
2. 보기 버튼을 눌러 보고서를 확인한다.
3. 1 에서 설정한 사이즈와 같은 화면으 모니터에서 브라우저를 전체화면으로 본다.
4. 브라우저 메뉴등이 보이지 않게 하기위해 F11을 눌러 풀사이즈로 본다.
5. 스크롤 바가 좌우, 상하로 모두 나온다.

## 예상한 행동 ##
보고서 생성시 설정하는 화면사이즈는 
그 화면으로 보고서를 만들었을 때 
전체화면으로 보는데 문제가 없다고 생각합니다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 본 이슈 어떻게 되었나요?

**Comment by veldise** [comment]
@sunghoon 
이전 패치에서 기본 설정에서 캔버스 세로 크기를 다소 줄이는 것으로 개선했습니다.

![image](https://user-images.githubusercontent.com/3411842/93982785-a872db80-fdbc-11ea-9f77-b3f144303e69.png)
