### ISSUE TITLE
studio: 익스플로러 11에서 객체 드래그 버그

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2058]
## 버그 설명 ##
현재 스튜디오 보고서의 객체를 드래그하여 이동 시 
좌에서 우로는 이동이 감속되어 느려지고 
우에서 좌로는 가속되어 빨라져 화면밖으로 사라집니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서 스튜디오에서 챠트나 사각형이나 텍스트등 객체를 화면 가운데에 만든다.
2. 마우스로 생성된 객체를 클릭하여 드래그해서 이동시킨다.
3. 좌에서 우로(혹은 상에서 하로, 혹은 이둘에 해당하는 방향의 대각선으로)  이동하면 커서만 이동하고 객체는 조금 움직이다가 멈추어 버린다.
4. 우에서 좌로 (혹은 하에서 상으로, 혹은 이둘에 해당하는 방향의 대각선으로) 이동하면 마우스의 움직임보다 가속이 붙어 객체가 화면밖으로 사라진다.

## 예상한 행동 ##
마우스로 정상적인 드래그가 가능
추가로 키보드의 이동키로도 객체가 이동 가능하면 좋겠습니다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by jmlee** [comment]
등록하고 확인해 보니 제가 사용하는 컴퓨터의 익스플로러에서 일어나는 현상입니다.
크롬에서는 정상작동합니다.
인터넷익스플롤러 버전은 11.719.18362.0 입니다.

**Comment by veldise** [comment]
2020-05-18 Release 및 추가 패치를 통하여 해결되었습니다.
만약 재현되면 Reopen 해주시기 바랍니다.
