### ISSUE TITLE
MINIO 이미지를 studio에서 사용할 경우, url 내보내기 기능 이슈 

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#2060]
## 버그 설명 ##
minio상의 이미지를 보고서에서 사용하고, 보고서의 url 내보내기를 사용할 경우 이미지가 보이지 않는 이슈 

## 재현하는 방법 ##
1. hdfs 브라우져를 이용하여 이미지 업로드
2. 보고서에서 이미지 등록
![스크린샷 2020-04-02 오후 1 22 00](https://user-images.githubusercontent.com/3415270/78210361-f4675680-74e4-11ea-8db4-fdc289e1abce.png)
3. 보고설서를 저장한 이후 URL내보내기 이용하여 접속
(브라우져의 시크릿 모드 혹은 web의 로그아웃 이후에 확인 가능)
![스크린샷 2020-04-02 오후 1 21 19](https://user-images.githubusercontent.com/3415270/78210379-00531880-74e5-11ea-8080-37d65514433b.png)

## 로그 ##
위와 같이 진행할 경우 이미지의 URL로 강제 접속할 경우
[이미지](http://b-iris.mobigen.com/hdfs-browser/minio/download?path=/demo/DEMO_DATA/STUDIO_IMG/FIRE_CENTER/%ED%99%94%EC%9E%AC%2C%20%EC%A0%88%EB%8C%80%EB%A1%9C%20%EC%95%88%EB%8F%BC%EC%9A%94.jpg)
아래와 같이 에러가 발생하고 있음

```
{"code":"403","message":"no auth info for /hdfs-browser/minio/download?path=/demo/DEMO_DATA/STUDIO_IMG/FIRE_CENTER/%ED%99%94%EC%9E%AC%2C%20%EC%A0%88%EB%8C%80%EB%A1%9C%20%EC%95%88%EB%8F%BC%EC%9A%94.jpg"}
```

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
현재 brick, studio 만 내보내기 처리에 대하여 인증 무시 처리가 되어있어 발생하는 문제입니다.
hdfs-browser에는 보안상 인증 무시 처리를 적용하기 어려울 것으로 생각됩니다.

**Comment by veldise** [comment]
IRIS SaaS 관련 이슈로 해당 사이트에서는 해결되어 닫습니다.
