### ISSUE TITLE
studio: 익스플로러 11에서 보고서 스튜디오에서 객체 크기조절 버그

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2063]
## 버그 설명 ##
대부분의 객체를 생성하고 드래그하여 크기를 조절하는 동작을 하면 
이동시의 문제와 같이 이상동작을 합니다. 

## 재현하는 방법 ##

![핸드러문제](https://user-images.githubusercontent.com/899539/78240774-6c03a880-751a-11ea-8a09-b11bf939aac5.PNG)

동작을 재현하는 방법 :
1. 사각형, 그림, 텍스트, 그래프.등의 객체를 만들고 크기를 조절한다.
2. 위의 그림에서 5, 7, 8 번 핸들러는 드래그하여 크기를 조절시 정상작동합니다.
3. 나머지 번호의 핸들러를 드래그하여 크기조절을 하면 
크기조절과 함께 객체가 좌측과 상단으로 이동하며 
1번 핸들러의 경우는 좌측과 상단 두 방향으로 가속을 받아 화면에서 사라집니다. 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by jmlee** [comment]
등록하고 확인해 보니 제가 사용하는 컴퓨터의 익스플로러에서 일어나는 현상입니다.
크롬에서는 정상작동합니다.
인터넷익스플롤러 버전은 11.719.18362.0 입니다.

**Comment by veldise** [comment]
2020-05-18 Release 및 추가 패치를 통하여 해결되었습니다.
만약 재현되면 Reopen 해주시기 바랍니다.
