### ISSUE TITLE
[Discovery]  ML( spark )명령어 fit 으로 만든 모델(mlmodel) 결과가 계정이 다르면 angora error 로 보이지 않습니다.(mlmodel 접근권한문제예상)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2064]
## 버그 설명 ##
demo 계정  biris.mobigen.com 

MLmodel 이름 : DEMO_RF_CLASSIFICATION_WINE,   DEMO_DC_CLASSIFICATION_WINE

보고서 이름 : 분류_RF_DC_1차시험_와인데이터

* demo  계정에서는 정상 출력 확인( biris.mobigen.com, 192.168.100.180 으로 각각 접속해도 정상 출력 됩니다.)
<img width="646" alt="스크린샷 2020-04-03 오전 9 06 38" src="https://user-images.githubusercontent.com/5126497/78310955-7067aa00-758a-11ea-9b56-5691ff50be0d.png">

* 다른 계정에서는 
<img width="652" alt="스크린샷 2020-04-03 오전 9 04 56" src="https://user-images.githubusercontent.com/5126497/78310895-3a2a2a80-758a-11ea-98b5-2e74069e53d5.png">

* MLMODEL 저장 시 접근 권한 문제가 있어 보입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
접근 권한 을 추가하여 다른 계정에서도 볼 수 있도록 수정했습니다.

다만, `B사용자`가 `A사용자`의 모델을 사용하기 위해서는 쿼리를 조금 수정해야합니다.

1. `A사용자`가 `자신의 모델`을 사용 ( 2가지 방법이 있습니다.)
- 기존과 같은 방식
  - `predict 모델명 ...`
- 추가된 namespace를 이용하는 방식 ( 유저명 과 ML모델명 사이에 `.` 을 이용해서 구분)
  - `predict A사용자.모델명 ...`

2. `A사용자` 가 `B사용자`의 모델을 사용하기 위한 조건
- 공유된 모델만 한정
- `predict B사용자.모델명 ...` 쿼리를 이용해서 검색
