### ISSUE TITLE
사용자 삭제 API 수행 시 ACL에서 제외되지 않음

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2065]
## 버그 설명 ##
- data model에 접근 권한을 부여했을 때 그룹인 경우 해당 그룹을 삭제했을 때는 접근권한에서 제외되지만 사용자를 삭제한 경우는 접근권한에 여전히 남아있음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 임의의 사용자를 임의의 data model의 접근권한 부여
2. 해당 사용자 삭제
3. data model 접근 권한 확인

## 예상한 행동 ##
- 그룹과 마찬가지로 사용자를 삭제하면 ACL에서 함께 삭제

**Comment by veldise** [comment]
UI 에서는 그룹/사용자 모두 삭제시 접근권한 정보(ACL)에서 삭제가 됩니다.
API 사용시에는 그룹/사용자 모두 접근권한 정보(ACL)에서 자동 삭제가 되지 않습니다.

API로 삭제시 접근권한 정보(ACL)도 자동 삭제하도록 개선해보겠습니다.

**Comment by AliceLiddell** [comment]
> UI 에서는 그룹/사용자 모두 삭제시 접근권한 정보(ACL)에서 삭제가 됩니다.
> API 사용시에는 그룹/사용자 모두 접근권한 정보(ACL)에서 자동 삭제가 되지 않습니다.
> 
> API로 삭제시 접근권한 정보(ACL)도 자동 삭제하도록 API를 개선해보겠습니다.

아, 제가 잘못 확인했습니다.

API로 삭제할 때 사용자의 경우는 이름도 남아있어서 안지워진걸 바로 인식했는데 그룹의 경우는 빈값으로 남아있는 것이었습니다.

혹시 해당 기능은 언제 개선이 될 수 있을까요?

**Comment by veldise** [comment]
@AliceLiddell 
빠르면 이번주 목요일, 늦으면 차주입니다.
