### ISSUE TITLE
[NMS+]studio를 이용한 데이터 CRUD 보완사항

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2067]
## 기능 요청 ##
1. 팝업창을 닫을수 있는 이벤트 정의
보고서의 CRUD 기능이 추가되면서 팝업으로 추가/수정/삭제등을 처리합니다.
현재 CRUD 가 성공했음에도 팝업창이 그대로 남아있어서 명시적으로 사용자가 팝업창을 닫아야합니다.

* 팝업창을 닫기위한 이벤트 정의가 필요합니다.
 팝업창을 닫아야하는 조건
 - restAPI 의 응답결과가 성공일경우 ( "저장" restAPI 가 성공한경우 "
- 명시적으로 특정버튼을 클릭한경우  ("취소"버튼)
등등

2.  보고서에서 다른 보고서 호출시 파라미터 값 체크 기능
 보통 그리드에서  한행을 선택하여 다른 보고서를 호출할때 파라미터는 잘 넘어가지만
행을 선택하지않고 다른 보고서를 호출하거나 잘못된 행을 선택하거나 하면   ( 파라미터값이 맞지않는 결과를 선택하게 될경우.. )  "Unknown error" 같은 화면을 사용자가 보게되면서  에러라고 여깁니다.

보고서를 호출하기 전에 
파라미터를 넘기는 보고서는 값을 체크하여 사용자에게 명시적으로 "선택하세요" , "잘못된 선택입니다" 등 사이트에 맞는메시지를 보여줘야할 필요가 있습니다.

3. 컴포넌트들의 트리거 / 조회등을  restAPI 연동시 restAPI 를 무조건 실행하는게 아니고 restAPI 의 응답결과에 따라 실행되어야하는 경우가 있습니다.

위의 2번의 경우도 다른 보고서를 호출하기전에 값 체크 restAPI를 호출하여 응답=success 일 경우만 [보기]버튼의 트리거로 연동할수 있는 방안등도 있을듯합니다.

* 위는 실제 저희시스템에서 사용해보면서 기본기능은 되지만 사용자가 알수없는 에러페이지를 보거나 아니면 팝업을 사용하면서 
사용자는 이런경우 그냥 시스템이 불안정하고 먼가 완성도가 떨어진다고 여깁니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 본 이슈 관련 상황 정보 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
데이터 결과에 따른 분기 이벤트 처리를 해야하므로 상당히 복잡합니다. 기획이 필요한 요구사항입니다.

**Comment by sunghoon** [comment]
@eumminsun 기획 바랍니다.

**Comment by sunghoon** [comment]
@eumminsun 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by rhcpn** [comment]
이슈 내용 중에 1번은 이미 기구현된 사항입니다.
2, 3번은 구체적인 기획전에 내용을 살펴보니 개발 공수가 제법소요 될것으로 보입니다.
현재 긴급한 업무들이 산적해 있어서 .. 해당 건은 12월 혹은 내년 1월 중에 처리 해야 할것 같습니다.

**Comment by sunghoon** [comment]
@jjinylee @rhcpn 바로 위 처럼 진행 될 때 NMS+ 프로젝트 진행에 특이사항은 없는지요?

**Comment by jjinylee** [comment]
넵~

**Comment by sunghoon** [comment]
@eumminsun @veldise 해당 이슈에 대한 처리는 어떻게 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
저번에 정해주신 우선순위에 따라 아직 일정 계획만 있고 대기중입니다.

**Comment by sunghoon** [comment]
@veldise 계획을 잡아서 알려 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
이것보다 우선순위가 높은 항목들이 업무량이 많아서 2월 중에 진행하는 것으로 검토중입니다.

**Comment by sunghoon** [comment]
@veldise @veldise 작년에 1차 계획이 잡혀 있던 일정인데. 업무 중요도를 고려해 주시면 좋을 것 같습니다.
단계 계획이 없어도 중기 계획 및 목표를 수립하여 진행해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 검토 의견 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
답변이 늦어서 죄송합니다. 아래와 같이 2, 3번 항목을 나누어 진행중입니다.
보고서 호출시 변수값 검사: https://github.com/mobigen/IRIS/issues/293
REST-API 결과 이벤트 유형 확장: https://github.com/mobigen/IRIS/issues/294

**Comment by sunghoon** [comment]
@veldise 각각에 대한 일정 계획은 어떻게 예정되어 있나요?

**Comment by veldise** [comment]
@sunghoon 
아직 기획을 기다리는 중이고 기획이 완료되면 바로 시작할 예정인데, 2월 중순쯤 개발 시작할 것 같습니다.

**Comment by sunghoon** [comment]
@veldise 완료 예상을 알려 주시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 2월 중순 개발 시작 예정인데 진행 상황 및 완료 목표일을 공유 해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon

**Comment by veldise** [comment]
@sunghoon 
파일 브라우저 관련 심각한 이슈(https://github.com/mobigen/IRIS/issues/389)가 발견되어 해당 이슈를 먼저 처리하느라고 늦어졌습니다.
현재 진행상황은 아래와 같습니다.

- REST-API 결과 이벤트 유형 확장: 개발 완료되어 사내 시스템에 3/5 패치 완료
- 보고서 호출시 변수값 검사: '사용자 메시지 등록/삭제', '조건검사 객체' 2가지 기능으로 나누어 진행중이며, 금주중에 개발 완료 예정이고 패치 일정은 논의중

**Comment by sunghoon** [comment]
@veldise 완료 및 패치 일정 계획을 잡아 공유 해 주시기 바랍니다.

**Comment by veldise** [comment]
4/1 패치에서 '사용자 메시지 등록/삭제', '조건검사 객체' 기능이 추가될 예정입니다.
