### ISSUE TITLE
[Discovery] mlmodel list 결과에서  셀을 클릭하면 filter 창이 나오지만, 동작 시 에러 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2068]
## 버그 설명 ##
* 검색 메뉴에서  mlmodel list 실행 후 특정 셀값을 클릭하면 필터링 창이 보입니다.
<img width="1195" alt="스크린샷 2020-04-06 오후 3 10 49" src="https://user-images.githubusercontent.com/5126497/78527976-3fe96f80-7819-11ea-82ec-b051cad5b3ff.png">

* 검색에서 추가 를 클릭하면 에러가 발생합니다.
<img width="772" alt="스크린샷 2020-04-06 오후 3 10 58" src="https://user-images.githubusercontent.com/5126497/78528055-73c49500-7819-11ea-875d-403be2ce39c8.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
`검색에 추가` 버튼은 `*` 명령어 사용시 추가되는 인자로, `mlmodel` 명령어에는 사용이 제한됩니다.

아래와 같이 `where` 명령어를 통해서 필터링을 하는 것을 권장드립니다.
```
mlmodel list | where name='DEMO_DC_CLASSIFICATION_WINE'
```
