### ISSUE TITLE
ACL API (GET) 비정상 동작

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2069]
## 버그 설명 ##
- GET ACL API 호출 시 type이 GROUP인 경우 정상적으로 출력이 되지 않음
  - 해당 데이터모델의 특정 value(그룹)를 삭제한 후 
  - /meta/acl?category=DATAMODEL&type=GROUP
  - 이런 형태로 호출한 경우
- USER인 경우는 정상 출력
  - /meta/acl?category=DATAMODEL&type=USER는 정상 출력
- /meta/acl?category=DATAMODEL&type=GROUP&id=54d77d5d-d07f-40bd-9204-0765819203bc
  - 이런 식으로 id를 추가하면 GROUP 내용도 표시가 됨
  - id를 모르는 경우 사용할 수가 없음
- value 옵션을 추가하더라도 해당 value가 있는 것만 검색이 되지 않고 전체가 다 반환됨
  - /meta/acl?category=DATAMODEL&type=GROUP&id=54d77d5d-d07f-40bd-9204-0765819203bc&value=d1992de3-640c-4a7a-b4c1-4ed8efc985b8
  - 위와 같이 data model에서 그룹 id를 넣어서 검색하려고 하면 value는 무시되고 data model의 id까지의 정보로 검색되어 반환됨
- DELETE Method의 경우는 value를 설정하고 삭제하면 해당 value의 값만 삭제되는 것으로 보아 GET에서의 value 동작이 비정상적으로 판단

## 예상한 행동 ##
- GROUP 옵션까지만 (category와 type 중 GROUP 설정) 설정했을 때 정상적으로 GROUP 정보 반환
- value 정보까지 넣었을 때 해당 value 정보를 포함한 것만 반환

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/6723557/78633890-a5069900-78dd-11ea-98b7-44d3168661df.png)
- GROUP 조건인 경우 아무 것도 검색되지 않음
![image](https://user-images.githubusercontent.com/6723557/78633844-8c967e80-78dd-11ea-90bb-23732cceedc0.png)
- value까지 넣었으나 value는 무시하고 검색
- type이 GROUP으로 검색이 됨(GROUP 옵션만 부여헀을 때는 나오지 않음)

**Comment by veldise** [comment]
@AliceLiddell 
일단 아래 2개 API 사용 목적을 알려주세요.
```
GET /meta/acl?category=DATAMODEL&type=GROUP
GET /meta/acl?category=DATAMODEL&type=USER
```

**Comment by AliceLiddell** [comment]
- USER는 GROUP이 동작 안해서 테스트로 돌린 것이었습니다.
  - 사용자 삭제 또는 업데이트 시 해당 사용자게게 부여된 데이터모델 권한을 제거할 때 사용할 예정입니다(현재는 아직 미사용)
- GROUP의 경우는 메타 시스템에서 조직 삭제시 해당 조직이 관리하는 데이터 모델 외의 데이터모델(다른 조직이 해당 조직에게 권한 부여한 경우)에서 권한을 제거하려고 합니다.
  - 이전에 올렸던 기능이 존재하면 그냥 조직을 삭제하면 되는데 현재 구현이 되어있지 않아 구현 전까지라도 해당 비즈니스 로직이 필요하여 구현하려다보니 사용하게 되었습니다.

**Comment by veldise** [comment]
@AliceLiddell 
현재 API 요청시 url querystring에 `id`를 입력하지 않은 경우,
입력하지 않았음에도 `userId`, `groupId` 조건으로  필터를 수행하는 것을 확인하였습니다.

IRIS 시스템 내부에서는 다음과 같은 2가지 용도로만 사용하기 때문에 문제가 없었습니다.

1. `id`에 해당하는 접근 권한 정보 조회 (객체 기준)
2. `userId` OR `groupId`에 해당하는 접근 권한 정보 조회 (사용자 기준)

단순하게 url querystring으로 입력한 조건에 따라 목록 결과를 반환하도록 개선하겠습니다.
