### ISSUE TITLE
[Analyzer]  Saas 도 동일 : 검색메뉴에서 컬럼클릭으로 상위 10개를 보여주는 것이 데이터모델 소스에 따라 다르게 동작합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2070]
## 버그 설명 ##
IRIS DB  에서 만든 데이터 모델은 값이 항상 나옵니다.

MinIO 에서 만든 모델은 전체시간으로 검색하면 나오고, 범위를 줘서 재검색 하면 안나옵니다.

Saas 플랫폼은 모두 MinIO 에서 만든 모델이라 범위로 재검색하면 안나옵니다.

* 전체 시간
<img width="874" alt="스크린샷 2020-04-07 오후 4 27 49" src="https://user-images.githubusercontent.com/5126497/78641851-c622b600-78ec-11ea-9344-ed52697dd040.png">

* 범위로 재검색
<img width="1019" alt="스크린샷 2020-04-07 오후 4 26 01" src="https://user-images.githubusercontent.com/5126497/78641735-a25f7000-78ec-11ea-94ce-cab6625ccf22.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
운영서버 패치되었습니다.
![Screen Shot 2020-04-09 at 6 15 30 PM](https://user-images.githubusercontent.com/46172579/78878905-1c7b2a80-7a8e-11ea-875e-c4dde83f815f.png)
