### ISSUE TITLE
hdfs-browser: MinIO 파일 업로드 실패

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2071]
## 버그 설명 ##
위치: jeongheedong.iris.tools
제보자: 정희동 팀장님

hdfs-browser: MinIO 파일 업로드 실패

약 300MB 파일 오류 발생
약 7MB파일 오류 발생

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/78727710-6a017580-7970-11ea-8cf0-eefcfae69f06.png)

**Comment by anhm** [comment]
해당 문제는  AWS 상의 loadbalance 를 위해 설정해둔 설정값이슈로 확인이 되었습니다.
최대 업로드 파일의 크기를 1G로 조정해 두었습니다.

**Comment by veldise** [comment]
@anhm 
고생하셨습니다.
