### ISSUE TITLE
hdfs-browser: MinIO / bucket 이름 규칙 오류

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2074]
## 버그 설명 ##
hdfs-browser: MinIO / bucket 이름 규칙이 적용되어 있지 않습니다.

현재 IRIS는 계정:버켓 = 1:1로, 계정명을 그대로 버켓명으로 사용하여 버켓을 생성하고 있는데,
계정명이 버켓명 규칙에 맞지 않는 경우 버켓이 생성되지 않는 문제가 발생하고 있습니다.

## 참고
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
- 3자 이상 63자 이하 문자열이어야 함
- 대문자 or '_' 문자 안됨
- 소문자 or 숫자로 시작하고 끝나야 함. (마지막 문자에 '-' 안됨)
- '-.' '.-' 와같이 마침표 옆에 '-' 문자 불가능
- DNS 명명 규칙을 준수해야 함.
- 기타
    - 버킷 이름은 일련의 하나 이상의 레이블이어야 합니다. 인접 레이블은 단일 마침표 (.)로 구분됩니다. 버킷 이름은 소문자, 숫자 및 하이픈을 포함 할 수 있습니다. 각 레이블은 소문자 또는 숫자로 시작하고 끝나야합니다.
    - 버킷 이름은 IP 주소 (예 : 192.168.5.4)로 형식화되어서는 안됩니다.

**계정명 규칙과는 맞지 않으므로 논의가 필요합니다.**

**Comment by sunghoon** [comment]
@veldise 해당 이슈 어떻게 진행 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
IRIS-DB 계정명 규칙을 변경할 수 없는 상황이라 대기중입니다.

**Comment by sunghoon** [comment]
@anhm 상세 의견 바랍니다.

**Comment by anhm** [comment]
IRIS-DB의 user 계정 규칙은 다음과 같습니다.

- 대소문자 숫자 _ 문자를 사용 가능함
- 시작은 _ 로 시작되면 안됨
- 최소 글자수 1자 이상

**Comment by sunghoon** [comment]
@veldise 사용자 가입시 MinIO / IRIS 계정 생성 규칙을 포함한 형태로 계정 생성 검사를 진행해 주시기 바랍니다.

**Comment by lyj** [comment]
IWP도 IBP 규칙과 동일하게 적용 예정입니다.

**Comment by veldise** [comment]
ID
- 정규식:
  ```
  /^[a-z]{1}[a-z0-9]{2,62}$/
  ```
- 영문 소문자, 숫자만 허용
- 영문 소문자로 시작
- 영문 대문자, `_`, `-` 문자 사용 불가능 (변경된 규칙)
- 길이 3 ~ 63자 이내

Password
- 정규식:
  ```
  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\{\}\[\]\/?.,;|\)~`!^\-_+<>\#$%&\\\=\(\'\"])[A-Za-z\d\{\}\[\]\/?.,;|\)~`!^\-_+<>\#$%&\\\=\(\'\"]{8,}/
  ```
- 영문 대문자, 영문 소문자, 숫자, 특수문자 1개 반드시 포함
- 8글자 이상
- `:`, `@`,`*`, 공백 제외하고 모든 특수문자 허용 (기존에는 `.` 등 입력이 불가능)

**Comment by rhcpn** [comment]
IWP의 경우 2020-10-22 Milestone 등록 되었습니다.

**Comment by veldise** [comment]
IBP 도 같이 10.22 패치 예정입니다.
