### ISSUE TITLE
PostgreSQL DB Query를 통한 Chart 생성 시 1700 오류

### ISSUE THREAD

**Issue by hipmk62** [mobigen/IRIS-BigData-Platform#2076]
## 버그 설명 ##
PostgreSQL DB Table에 대한 Query 시 Command Line(psql) 상에서는 
원하는 결과가 나오지만, 해당 결과를 Studio DSMS를 통해 Chart 생성 시
1700 오류 발생.
1700 오류 코드(?)만 생성되고 구체적인 오류 원인이 없어 Query를 어떻게 수정해야 할지
모름.

관련 Query "금월 발생한 이벤트 전체에 대해, 노드 - 장애명별 평균 장애지속시간 현황을 보고싶다"

select resource||' '||event_name Node_Event, avg(duration) MTTR
from  fm_tsn_alarm_history
where substring(date_released,1,6)=to_char(now(),'YYYYMM')
group by resource||' '||event_name
order by avg(duration) desc;

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. NI개발그룹 T-SDN 서버에 설치된 IRIS Studio에 로그인
    URL: http://58.181.37.138:8442 (root 기본 계정 암호 사용)

2. 보고서 메뉴 중 "장애 지속시간 현황" 보고서 편집 화면으로 이동

3. 우측 상단 "보기" 버튼 클릭

4. Chart Main 영역에 1700 오류 발생 확인

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/9989040/78758307-e0c26100-79b8-11ea-9236-ef47d753f767.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
연결정보 (id: 2):
```
"host": "58.181.37.137"
"port": 9182
"database": "tsdn"
"user": "tsdn"
```

SQL:
```sql
SELECT
    resource || ' ' || event_name Node_Event,
    avg(duration) MTTR
FROM
    fm_tsn_alarm_history
WHERE
    substring(date_released, 1, 6) = to_char(now(), 'YYYYMM')
GROUP BY
    resource || ' ' || event_name
ORDER BY
    avg(duration) DESC
;
```

response:
```json
{"status": -1, "messages": "1700"}
```

**Comment by seungfwani** [comment]
@hipmk62 
해당 이슈내용에 대한 DSMS 코드를 수정하였습니다.
원인은 코드상 데이터 타입 변환에서 문제가 있었던 것입니다.

배포요청 하도록 하겠습니다.

**Comment by seungfwani** [comment]
@hipmk62 
해당 서버에 배포확인 되었습니다.

![Screen Shot 2020-04-09 at 2 00 43 PM](https://user-images.githubusercontent.com/46172579/78859513-8550ab80-7a6a-11ea-8dc8-5a04b44756cf.png)

**Comment by seungfwani** [comment]
본 이슈는 해결 된 것으로 생각되며, 
같은 이슈 발생시 다시 오픈해 주시기 바랍니다.
