### ISSUE TITLE
[ISP] 연결 정보 메뉴 보완

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2078]
## 기능 요청 ##
1. default-minio  는 root 의 secret-key 가 빈칸으로 나오지만 수정 자체가 안됩니다. 그러니 수정버튼이 불필요합니다.
2. 삭제 하면 일반 유저는 default-minio  를 자체적으로 재생성이 안됩니다. - 삭제 안되게 해야 합니다.
3. 새 연결정보는 유저가 이미 만들어둔  minio(S3) 만 연결정보 생성이 가능합니다. 그 부분에 대한 설명을 연결정보 창에서 추가하면 좋겠습니다. 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
1. secret-key는 password 유형이라 표시되지 않는 것이고, 수정은 가능할 것입니다.
2. 특정 연결 정보를 삭제 불가능하게 하려면 기획을 포함하여 DSMS / IBP 양 쪽에 개발이 필요합니다.

@anhm

**Comment by anhm** [comment]
해당 이슈는 내부 회의를 통해 정책을 정한 이후에 진행하도록 하겠습니다.

**Comment by sunghoon** [comment]
@anhm @veldise 어떻게 결론이 나왔나요? 최종 상태를 알려주세요.

**Comment by anhm** [comment]
해당 이슈는 최신 버전에서 패치가 이루어 졌으므로 close 됩니다.
https://github.com/mobigen/IRIS/issues/501
