### ISSUE TITLE
[Analyzer] 검색에서 데이터모델의 시간이 갑자기 invalid date 로 표기됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2083]
## 버그 설명 ##
* 데이터 모델 : DEMO_북경대기질_2013_2017_18시  
<img width="752" alt="스크린샷 2020-04-09 오후 4 57 33" src="https://user-images.githubusercontent.com/5126497/78950167-d616e180-7b08-11ea-8edb-aebff46e6d5c.png">

* 특징은 CTIME  컬럼에는 18시 시간만 있습니다.2013/03/01 ~ 2017/02/28 동안 매일 18시에 측정한 데이터라 18:00 시만 있는 데이터 입니다.

* 원래 그저께 만해도 시간필드가 바로 나왔는데, 갑자기 이렇게 나옵니다.
<img width="1376" alt="스크린샷 2020-04-09 오후 4 59 27" src="https://user-images.githubusercontent.com/5126497/78950269-2beb8980-7b09-11ea-8cca-1e4fa76c868c.png">

* 이벤트 막대그래프는 맞게 나오고 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
앙고라에서 보내는 데이터는 정상적으로 보입니다.

모델명: syslog
시간: 최근 1분
결과 json:
```
"fields": [
    {
      "name": "DATETIME",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "RAW",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "HOST",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "FACILITY",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "PRIORITY",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "LEVEL",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "LEVEL_INT",
      "type": "INTEGER",
      "grouped": false
    },
    {
      "name": "TAG",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "PROGRAM",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "MSG",
      "type": "TEXT",
      "grouped": false
    }
  ],
  "results": [
    [
      "20200410091701",
      "20200410091701 | tsdn-svr1 | kern | warning | warning | 04 | kernel | audit_printk_skb: 15 callbacks suppressed",
      "tsdn-svr1",
      "kern",
      "warning",
      "warning",
      5,
      "04",
      "kernel",
      "audit_printk_skb: 15 callbacks suppressed"
    ],
   ...
  ]
```
결과 화면
![Screen Shot 2020-04-10 at 9 20 19 AM](https://user-images.githubusercontent.com/46172579/78951265-83d7bf80-7b0c-11ea-9a3b-0aab4e3ebf12.png)

**Comment by veldise** [comment]
@seungfwani 
`DATETIME` 컬럼 유형이 `TEXT`입니다. 확인 바랍니다.

**Comment by veldise** [comment]
@anhm @seungfwani 
확인 결과 이전에는 웹에서 검색 결과 컬럼명이 모델의 시간 유형 컬럼명과 같으면 시간 유형의 컬럼으로 처리하고 있었습니다. 이 경우 다음과 같이 `as` 혹은 `rename`을 사용했을 때 문제가 발생합니다.

예시)
`* | stats avg(LEVEL_INT) as DATETIME by HOST`
`* | rename DATETIME DT | rename LEVEL DATETIME`

**Comment by veldise** [comment]
`date_group()`의 결과도 `TEXT` 입니다.

`* | stats avg(LEVEL_INT) by date_group(DATETIME, "1M")`

**Comment by veldise** [comment]
추가로, `date_group()` 결과 컬럼명이 이전과는 다르게 `dategroup`으로 반환됩니다.
이러면 예외 처리도 할 수 없습니다.

```js
{
  "fields": [
    {
      "name": "dategroup",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "avg(LEVEL_INT)",
      "type": "REAL",
      "grouped": false
    }
  ],
  "results": [
    [
      "20200410100700",
      6.633644859813084
    ],
    [
      "20200410100300",
      6.628366247755835
    ],
    [
      "20200410101100",
```

**Comment by seungfwani** [comment]
`DATETIME` 컬럼 유형은, 이전 부터 `TEXT` 로 리턴이 되고 있었습니다. (최근 수정 한 내용 없습니다.)
그러나, 데이터 모델에서 지정한 컬럼 유형으로 변환을 하도록 수정은 필요한 것으로 보입니다.

stats, rename 명령어의 경우 확인이 필요합니다.

**Comment by veldise** [comment]
@seungfwani 
네 웹에서 예외처리하고 있었습니다. 코멘트를 읽어주세요.

**Comment by veldise** [comment]
@seungfwani @anhm
ICP 관련은 아래 이슈로 분리하였습니다. 일단 이슈 본문은 이전처럼 웹에서 예외처리하도록 수정하겠습니다.

#2084

**Comment by seungfwani** [comment]
데이터 모델에 timestamp, date  타입으로 설정되어 있으면 아래와 같이 POSIX 형식으로 리턴하도록 하겠습니다.
(stats, rename 과 같은 변환이 있는 내용은 확인 필요합니다.)

```
field -> {'name': 'DATETIME', 'type': 'TIMESTAMP', 'grouped': False}
data -> 1572580798.0
```

**Comment by veldise** [comment]
@seungfwani 
네 그러면 웹은 예외처리를 하지 않는 방향으로 수정하겠습니다.
