### ISSUE TITLE
angora: 검색 결과의 일부 컬럼이 시간 유형인데 TEXT로 반환되는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2084]
## 버그 설명 ##
이슈 요약:
- 검색 결과의 일부 컬럼이 시간 유형인데, `TEXT` 유형으로 반환됨
- `date_group()` 결과 컬럼명이 이전과는 다르게 `"dategroup"`으로 반환됨.

## 내용
이전에는 웹에서, 검색 결과 컬럼명이 모델의 시간 유형 컬럼명과 같으면 시간 유형의 컬럼으로 예외처리하고 있었습니다. 이 경우 다음과 같이 `as` 혹은 `rename`을 사용했을 때 문제가 발생합니다.

예시)
`* | stats avg(LEVEL_INT) as DATETIME by HOST`
`* | rename DATETIME DT | rename LEVEL DATETIME`
`* | stats avg(LEVEL_INT) by date_group(DATETIME, "1M")`

```js
"fields": [
    {
      "name": "DATETIME",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "RAW",
      "type": "TEXT",
      "grouped": false
    },
```

추가로, `date_group()` 결과 컬럼명이 이전과는 다르게 `"dategroup"`으로 반환됩니다.
이러면 예외 처리도 할 수 없습니다.

```js
{
  "fields": [
    {
      "name": "dategroup",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "avg(LEVEL_INT)",
      "type": "REAL",
      "grouped": false
    }
  ],
  "results": [
    [
      "20200410100700",
      6.633644859813084
    ],
    [
      "20200410100300",
      6.628366247755835
    ],
    [
      "20200410101100",
```

**Comment by seungfwani** [comment]
model 명령어를 통한 검색 시, `timestamp`/`date` 컬럼에 대해서 POSIX 형태로 데이터를 내려보내도록 수정하였고, 운영서버 배포되었습니다.

syslog 예제
1. `*` 검색
```
  "fields": [
    {
      "name": "DATETIME",
      "type": "TIMESTAMP",
      "grouped": false
    },
    ...
   ],
  "results": [
    [
      1586852941.0,
      "20200414172901 | gcs1 | daemon | info | info | 1e | systemd | Started Session 352175 of user wf.",
      "gcs1",
      "daemon",
      "info",
      "info",
      7,
      "1e",
      "systemd",
      "Started Session 352175 of user wf."
    ],
    ...
]
```
2. `* | stats avg(LEVEL_INT) by date_group(DATETIME, "1M")`
```
 "fields": [
    {
      "name": "DATETIME",
      "type": "TIMESTAMP",
      "grouped": false
    },
    {
      "name": "avg(LEVEL_INT)",
      "type": "REAL",
      "grouped": false
    }
  ],
  "results": [
    [
      1586852880.0,
      6.645328719723183
    ],
    [
      1586852940.0,
      6.6531791907514455
    ]
  ]
```

**Comment by veldise** [comment]
@seungfwani @anhm 
이런 패치는 IBP쪽과 상의해서 하세요. 웹 예외처리를 4/13 패치로 적용해서 정상 출력되었는데
지금 다시 Invalid Date가 출력됩니다.

**Comment by veldise** [comment]
Angora에서 반환하는 데이터가 문자열 -> POSIX 형태로 변경되었으므로
Studio 보고서 쪽도 데이터 모델 유형은 전부 Invalid date가 출력될 것입니다.

**Comment by veldise** [comment]
@anhm @seungfwani 
웹에서 단기간(1~2시간)내 처리가 어려우므로 이전 버전으로 롤백 요청합니다.

**Comment by seungfwani** [comment]
롤백 하였습니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈에 대한 진행 결과를 알려주세요. 준

**Comment by seungfwani** [comment]
stats 명령어 수정 중에 있으며, 수정이 완료되면 아래 문제를 해결 될 것입니다.
- 검색 결과의 일부 컬럼이 시간 유형인데, TEXT 유형으로 반환됨
- date_group() 결과 컬럼명이 이전과는 다르게 "dategroup"으로 반환됨.

**Comment by sunghoon** [comment]
@veldise 위 내용을 기반으로 UI는 처리해야 되는것이 없나요?

**Comment by veldise** [comment]
@sunghoon 
네, `date_group()` 으로 반환되거나, `TIMPSTAMP` 유형으로 반환되면 문제 없습니다.

**Comment by sunghoon** [comment]
@veldise @seungfwani 그럼 최종 확인하고 배포 해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@veldise @anhm @seungfwani 배포 되었나요? 최종 상태를 공유 해 주세요.

**Comment by seungfwani** [comment]
@sunghoon 
금일 배포 예정입니다. 
[배포 내역](https://github.com/mobigen/IRIS-BigData-Platform/wiki/2020-10-16---Patch)

**Comment by seungfwani** [comment]
아래 사진처럼 `date_group()` 결과의 타입이 시간컬럼으로 나오도록 수정이 되었습니다.

![Screen Shot 2020-10-16 at 3 58 18 PM](https://user-images.githubusercontent.com/46172579/96223149-6a866300-0fc8-11eb-9d9e-157531966b78.png)
![Screen Shot 2020-10-16 at 3 58 57 PM](https://user-images.githubusercontent.com/46172579/96223214-825de700-0fc8-11eb-862e-d6dd8bf0dc32.png)
