### ISSUE TITLE
[Studio] 편집 중에 map 의 '시각화옵션-툴팁' 에 컬럼 항목이 보이지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2085]
## 버그 설명 ##
http://b-iris.mobigen.com/    
보고서 이름 : 교육자료_수원시 동별 인구분포 

편집 중에 map - '시각화옵션-툴팁'   컬럼 항목이 보이지 않습니다.
* 시각화 옵션에서  데이터 탭은 컬럼이름이 정상적으로 보입니다.
<img width="357" alt="스크린샷 2020-04-10 오후 5 02 34" src="https://user-images.githubusercontent.com/5126497/78974829-ce2d6080-7b4d-11ea-9a2f-7323df53edd9.png">
 
* 툴팁에서는 항목이 아예 보이지 않습니다.
<img width="357" alt="스크린샷 2020-04-10 오후 5 02 43" src="https://user-images.githubusercontent.com/5126497/78974899-f4530080-7b4d-11ea-9306-5138cb4fcd69.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

보고서 이름 : 교육자료_수원시 동별 인구분포 

<img width="453" alt="스크린샷 2020-04-10 오후 5 10 55" src="https://user-images.githubusercontent.com/5126497/78975090-54e23d80-7b4e-11ea-8142-2a50ff7c3775.png">

레이어는
<img width="210" alt="스크린샷 2020-04-10 오후 5 11 04" src="https://user-images.githubusercontent.com/5126497/78975111-5d3a7880-7b4e-11ea-8d10-27e469d28f29.png">

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
입력된 SQL의 select 구문에 컬럼 2개가 중복되어 있습니다. 이로 인해 발생하는 문제입니다.
중복 컬럼이 있더라도 내부에서는 uniq 처리하도록 개선하겠습니다.

```sql
SELECT
    LOCAL_A.STANDARD_DATE_NAME,
    LOCAL_A.BASIS_DATE,
    LOCAL_A.STANDARD_DATE_NAME,
    LOCAL_A.BASIS_DATE,
    LOCAL_A.GU AS '구',
    LOCAL_A.DONG AS '동',
    LOCAL_A.HOUSEHOLD_COUNT AS '세대수',
    LOCAL_A.MALE_POPULATION_COUNT AS '남성인구',
    LOCAL_A.FEMALE_POPULATION_COUNT AS '여성인구',
    (LOCAL_A.MALE_POPULATION_COUNT + LOCAL_A.FEMALE_POPULATION_COUNT) AS '인구수',
    GB_GEOM.GEOM_JSON
FROM
    MYIRIS.SUWON_CITY_STATISTICS_GU_DONG_ACCORDING_TO_POPULATION_STATUS LOCAL_A,
    MYIRIS.SUWON_DONG_GEOJSON GB_GEOM
WHERE
    LOCAL_A.BASIS_DATE = ${combo_1}
    AND GB_GEOM.DONG = replace(LOCAL_A.DONG, ' ', '');
```
