### ISSUE TITLE
[ISP] 중요- 보고서를 작업하는 중에 갑자기 뜬 에러 - 아마 세션이 끊어진 것 같습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2087]
## 버그 설명 ##
* 보고서를 만들고 있는 와중에 방금까지 되었던 차트 그리기가 에러가 발생합니다.
<img width="770" alt="스크린샷 2020-04-14 오전 10 37 42" src="https://user-images.githubusercontent.com/5126497/79176945-8b64d480-7e3c-11ea-870c-013c45c3142b.png">

* 그래서 급하게 **저장** 을 클릭하니 이미 사용중인 이름이고  문구가 나오면서 저장이 안됩니다.
<img width="338" alt="스크린샷 2020-04-14 오전 10 38 12" src="https://user-images.githubusercontent.com/5126497/79177037-c404ae00-7e3c-11ea-9af6-60af43a9ea76.png">

*  보고서 목록을 가져오는 데 실패하고
<img width="266" alt="스크린샷 2020-04-14 오전 10 38 29" src="https://user-images.githubusercontent.com/5126497/79177063-d383f700-7e3c-11ea-860f-52e21c5759da.png">
<img width="721" alt="스크린샷 2020-04-14 오전 10 39 32" src="https://user-images.githubusercontent.com/5126497/79177067-d5e65100-7e3c-11ea-858b-50155f62ad0b.png">

* 다른 메뉴를 클릭하니 세션 종료 관련 창이 뜹니다.
<img width="872" alt="스크린샷 2020-04-14 오전 10 40 29" src="https://user-images.githubusercontent.com/5126497/79177121-fa422d80-7e3c-11ea-872a-9c2fb5ff6a86.png">

* 작업을 하는 중에 뜬 현상이라 저장을 미처 누르지 못한 경우 보고서를 다시 생성해야 하는 큰 문제가 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lunamay** [comment]
수원시에도 장시간 사용시 동일 합니다.

**Comment by lyj** [comment]
로그인 세션을 관리하고 갱신하는 과정에서 발생한 문제인것 같습니다.
전체 서비스의 세션을  체크하고, 주기적으로 연장하는 기능을 추가 할 계획입니다.

**Comment by lyj** [comment]
로그아웃전까지 세션이 유지되도록 수정되었습니다.
