### ISSUE TITLE
IRIS analyzer, studio 사용자 매뉴얼 갱신 요청

### ISSUE THREAD

**Issue by lunamay** [mobigen/IRIS-BigData-Platform#2088]
제가 가지고 있는 analyzer, studio 매뉴얼은 2016년 버전으로 보이고 스크린샷도 다릅니다.

고객이 최신 버전을 요청 하오니 갱신 배포를 부탁 드립니다.

**Comment by EricLeeMbg** [comment]
현재 docs.iris.tools의 변경작업 중에 있습니다. 
차주까지 작업을 통해 IRIS SaaS용 매뉴얼을 구성할 예정이구요(4.24 완료예정), 
IRIS SaaS와 기존 매뉴얼은 IRIS On-Premise로 분할하여 관리 예정입니다. 
변경배포 완료 후 관련정보를 전달해 드리겠습니다.
