### ISSUE TITLE
[NMS+]studio 콤포넌트(text/lable 등 ) 의 데이터 실행방법 추가요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2089]
## 기능 요청 ##
text 나 lable 콤포넌트에 고정값이 아닌 데이터를 뿌릴수 있는 방법이 restAPI 밖에 없습니다.

파라미터로 받은 값을 뿌리거나 전역변수 값을  text, lable 에 표현하고 싶은데 
그럴수 없어서 다 restAPI 를 만들어서 붙어야합니다.

text / lable / textinput 값등에 전역변수/ dsms 쿼리 결과/ 파라미터값 등을 연동할수 있는 기능이 필요합니다

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 해당 요청 기능에 대한 진행 상황을 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
최근 추가된 데이터 객체를 이용하여 이슈 본문 요건을 처리 가능합니다.
