### ISSUE TITLE
백그라운드 이미지적용 기능추가

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2090]
## 기능 요청 ##
보고서 스튜디오에서 백그라운드에 색상코드 사용이 가능하지만 이미지를  사용하는 기능은 없습니다.
이미지객체를 사용하여 제일 아래 배치하는 식으로 대용으로 사용이 가능하지만 
이미지를 패턴으로 적용이나 풀 사이즈로 볼 때 스크롤이 생기는 문제가 있습니다. 
 참조 - 보고서 > 카테고리(디자인_보고서)의 보고서들은 1920 X1080의 캔버스 사이즈 보고서를 만들고
캔버스사이즈 보다 더 큰 이미지객체를 배경으로 넣어서 만든 보고서입니다.
1920 모니터에서 캔버스 사이즈인데도 불구하고 그보다 더 큰 이미지 사용 때문에 
캔버스 사이즈와 같은 모니터에서 풀 화면으로 봤을 때 스크롤이 나타납니다.

## 원하는 솔루션 설명 ##
1. 보고서 캔버스의 배경 색상코드 설정에 배경이미지 적용이 가능하도록 개선부탁드립니다.
2. 웹에서 지원하는 backgraund-image의 옵션도 설정 가능하도록 기능추가 
 - 반복(가능/불가능), X축만 반복, Y축반 반복....

3. 백그라운드 이미지를 사용하는 기능이 없더라도 캔버스 사이즈를 정한 보고서가 
캔버스보다 더 큰이미지를 사용하더라도 캔버스 사이즈와 같은 모니터에서 풀 화면으로 봤을 때 
스크롤이 생기지않게 적용이 필요.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 진행 요청합니다.
