### ISSUE TITLE
보고서 스튜디오 캔버스 사이즈 100% 사용 시 문제

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2091]
## 버그 설명 ##
캔버스를 100% 사용으로 설정이 가능하면 
내부의 객체도 100% 같은 단위의 사용이 가능해야 할것 같습니다.
캔버스를 100%로  설정하고 박스상자를 만들어 모니터 화면에서 100%가 되도록 배치할 방법이 없습니다.
그리고 보이는 대로 화면전체에 최대한 채워서 만들어 넣어도 
보기화면으로 보면 오른쪽으로 정렬되어 공백이 나타나게 됩니다.
보고서 > 이슈카테고리 >
<사이즈문제> 보고서 참조

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 새 보고서 작성
2. 캔버스사이즈 100%
3. 객체를 만들어 보이는 화면에 최대 크기로 생성
4. 텍스트의 경우 최대크기로 만들어 가운데 정렬로 글자 생성
5. 보기화면으로 확인 (스크롤이 생기며 전체화면이 화면보다 크게나와서 좌우로 스크롤 된다.

## 예상한 행동 ##
1웹문서의 00%라는 설정에 맞게 보는 화면의 100%로 만들어져야 하며
하위의 상속받는 객체의 사이즈도 100% 같은 설정이 가능해야한다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise @onlyeon 해당 사항에 대한 조치 혹은 진행 정보를 공유해 주세요.

**Comment by onlyeon** [comment]
기존에 고정 `px`단위로 구현되어있는 컴포넌트를 `비율`단위로 교체해야 하며, 개발과 함께 충분한 검토가 필요합니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2483 이슈와 동일한 이슈로 보이며, 해당 이슈는 Studio 전체 개선에 포함될 것으로 보입니다.
