### ISSUE TITLE
[브라우저] b-iris.mobigen.com  에서 MINIO 접근이 안되거나, 폴더생성, 업로드가 안됩니다

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2092]
http://b-iris.mobigen.com/

에서 HDFS브라우저를 클릭하면
<img width="1275" alt="스크린샷 2020-04-16 오전 9 44 47" src="https://user-images.githubusercontent.com/5126497/79402487-f17d6300-7fc6-11ea-9590-e3c1311cbadd.png">

로  데이터가 하나도 없다고 나오고, MINIO 로 이동도 되지 않습니다.

그러다 잠시 후에
어떨 때는 MINIO 까지 보이지만, 폴더 생성, 업로드 가 안됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
원인 파악했습니다. 금일 중에 해결해보겠습니다.

**Comment by veldise** [comment]
4/16 추가 배포하여 해결되었습니다.
