### ISSUE TITLE
보고서에서 간혈적으로 오류 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2093]
## 버그 설명 ##
- 위치: direct cloud (https://dboxmanager.directcloud.jp/)
- 제보자: 나규환 책임

보고서에서 간혈적으로 오류 발생 (스크린샷 참고)

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/79406214-6bb2e500-7fd1-11ea-868a-ec1407780acd.png)

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/79413456-ef290200-7fe2-11ea-882b-8f6738903c4c.png)

```html
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by veldise** [comment]
@anhm 
Angora 에서 반환하는 에러로 추측됩니다. 확인을 부탁드립니다.

**Comment by seungfwani** [comment]
@veldise 
해당 보고서를 참고해보니 26개 정도의 쿼리가 동시 동작하는 것으로 확인됩니다.
소수의 쿼리를 처리 할 때는 빠르게 리턴이 되지만, 다수의 쿼리가 동시 동작시 spark 에서 처리하는데 시간이 걸립니다. (서버의 구성이 master node 1개, worker node 1개 입니다.)

timeout 이 걸리는 시점이 정확히 1분으로 나타납니다.
다수 쿼리 동작 시 1분이상 걸리는 job 이 있을 수 있습니다.
brick 이나, sherman 쪽에 시간이 어떻게 설정 되어 있는지 궁금합니다.

<img width="558" alt="Screen Shot 2020-04-16 at 4 05 18 PM" src="https://user-images.githubusercontent.com/46172579/79425414-9ebe9e00-7ffc-11ea-8def-ce62ca65dfdf.png">

**Comment by veldise** [comment]
@seungfwani 
timeout이 1분으로 설정된 것은 없는 것으로 압니다.

**Comment by veldise** [comment]
```
2020-04-16 15:07:28.677 INFO  --- [http-nio-8080-exec-15]
                c.m.s.controller.CommonController : common ping url : /studio/common/ping
2020-04-16 15:07:32.747 ERROR --- [http-nio-8080-exec-11]
                c.m.s.common.utils.AngoraTokenUtil : jacksonUtil.getObject Error:Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty/1.15.8.3</center>
</body>
</html>
"; line: 1, column: 2]
2020-04-16 15:07:32.747 ERROR --- [http-nio-8080-exec-11]
                c.m.s.common.utils.AngoraTokenUtil : data:<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty/1.15.8.3</center>
</body>
</html>
```

**Comment by veldise** [comment]
5/14 버전 배포 후 발생하지 않는 것 처럼 보이고, 
Direct Cloud 요청에 따라 아래와 같이 처리하기로 하였습니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2196#issuecomment-631819793

**Comment by veldise** [comment]
Direct-Cloud 에 배포가 되었기에 닫습니다.
