### ISSUE TITLE
데이터 브라우저 500 에러

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2094]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

현재 데이터 브라우저 하위 메뉴 탭이 모두 500 에러가 나고 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
로그인 -> 데이터 브라우저 아무 메뉴나 클릭

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/16331916/79414951-fa7e2c80-7fe6-11ea-9385-6c8ff52792a3.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
신규 버전을 배포하는 과정에서 서버 설정 미스가 있어서 발생하는 문제였습니다.
현재는 정상화되어 닫습니다.
