### ISSUE TITLE
Studio: Map / 값 필드 설정에 '모든 필드' 항목이 항상 나오도록 개선

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2096]
## 기능 요청 ##
Studio: Map / 값 필드 설정에 '모든 필드' 항목이 항상 나오도록 개선

현재 지도 객체 - 레이어의 '값 필드' 설정의 '모든 필드'라는 항목을 선택하면
레이어의 변수 유형이 string에서 object로 변경되며, 각종 이벤트 값들을 사용할 수 있게 됩니다.

그런데 이 '모든 필드' 항목은 데이터 탭에서 데이터를 서버로부터 한 번 받아와야만 combo-box 목록에 나옵니다. 이 항목이 항상 나오도록 개선되어야 합니다.

## 재현
1. 지도 객체 생성
2. 임의의 레이어 추가, 레이어 선택
3. 데이터 탭 > 설정하고 실행
4. 시각화 탭 > 값 필드 combo-box 설정을 임의의 컬럼으로 설정
5. 저장
6. 목록 화면으로 이동
7. 저장한 보고서 편집
8. 레이어 선택 > 시각화 탭 > 값 필드 combo-box

**Comment by sunghoon** [comment]
@veldise 요구사항 접수 경위가 어떻게 되나요?

**Comment by veldise** [comment]
@sunghoon 
따로 접수받은게 아니라 제가 개선사항으로 올린 이슈입니다.

**Comment by sunghoon** [comment]
그럼 일단 닫아 두겠습니다.
