### ISSUE TITLE
[Discovery] MinIO 모델 끼리 join 하는데, 응답없이(10분이상) 계속 실행중으로 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2097]
## 버그 설명 ##
b-iris.mobigen.com
demo계정
데이터모델 : 서울시구별연령대_2014 ,   서울시구별연령대_2019   
                     각각 25개 raw , 동일 필드명의 모델
                     GU 컬럼으로 join 할 예정

command : 

` *|  join inner 서울시구별연령대_2014  서울시구별연령대_2019.GU = 서울시구별연령대_2014.GU` 

계속 실행중 ...

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
응답 없음 의 문제는 서버의 상태 문제로 예상됩니다.

더불어 한국어 처리가 제대로 되지 않는 듯 하여 수정 후 배포하였습니다.
![Screen Shot 2020-04-24 at 6 13 12 PM](https://user-images.githubusercontent.com/46172579/80195775-52580b80-8657-11ea-8588-42d9eb513dbb.png)
