### ISSUE TITLE
b-iris.mobigen.com 에서 작업중에 로그인세션이 만료되었다거 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2098]
## 버그 설명 ##
네트웍이 유지되고 있고, 작업을 하고 있는 중인데  메뉴를 선택해서 클릭하면
갑자기 로그인 세션이 만료되었다는 창이 뜹니다.

b-iris.mobigen.com  은  별도 네트웍이 끊어지거나 로그아웃 전까지는 세션이 계속 유지되어야 합니다.
그리고 이 때까지 잘 동작했었구요.
오늘(04/16) 갑자기 나타난 현상입니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
로그아웃전까지 세션이 유지되도록 수정되었습니다.
