### ISSUE TITLE
보고서/히트맵 - Y축 및 범례 표시 오류

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#2099]
## 버그 설명 ##
보고서에서 히트맵 객체로 데이터 표시하는 경우, 아래와 같이 Y축과 범례에 오류가 발견되었습니다.

## 재현하는 방법 ##
1. '새보고서' 선택(보고서명: Heatmap_Sample)하고 히트맵 객체로 데이터 표현
2. 아래 1번과 2번은 보고서 내에서 히트맵 객체를 실행한 화면이고
   6번은 '보기' 버튼을 이용하여 해당 보고서를 실행한 화면입니다.
3. 오류 1. Y축(시간값) 표현 오류
    - 1번에서는 Y축 값이 정상적으로 표현되지만,
    - 세로축의 폭을 줄이면 3번과 같이 마지막 값이 소수점으로 표시됩니다.
4. 오류 2. 범례 값 잘림
    - 4번과 같이 범례의 값이 잘리는 현상 발생
5. 오류 3. 범례 표시 오류
    - 5번은 보고서 내에서 해당 객체를 실행한 화면이며, 범례가 정상적으로 표시됩니다.
    - 7번은 '보기' 버튼을 이용하여 보고서를 실행한 화면인데, 범례가 5번과 다르게 표시됩니다.

![image](https://user-images.githubusercontent.com/23075670/79522375-77b4aa80-8096-11ea-8e8e-958083c2f092.png)
![image](https://user-images.githubusercontent.com/23075670/79522381-7d11f500-8096-11ea-8ef9-eefb41486a39.png)

**Comment by veldise** [comment]
#2118 동일 이슈

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/2118#issuecomment-642326725
