### ISSUE TITLE
[ISP]계정 삭제 후에도 MINIO에 해당 계정의 폴더는 유지됨

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#2100]
## 버그 설명 ##
IRIS SaaS에서 일반 사용자 계정을 생성 후 삭제하였으나(화면 1)
File 브라우저의 MINIO에는 해당 계정의 폴더가 자동 삭제되지 않고 유지됨(화면 2)

[화면 1]
![image](https://user-images.githubusercontent.com/23075670/79531025-139ce100-80ac-11ea-8a26-a7282e2bfc4a.png)

[화면 2]
![image](https://user-images.githubusercontent.com/23075670/79531047-21eafd00-80ac-11ea-8300-367ec14d0f8c.png)

**Comment by veldise** [comment]
b-iris.mobigen.com 에서는 재현되지 않지만, demo.iris.tools 에서도 재현되고 있습니다.
서버 로그를 확인해야 합니다.

@anhm
hdfs-browser 서비스 로그를 제공 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @veldise 조치 되었나요?

**Comment by sunghoon** [comment]
@rhcpn 팀장님 해당 내용 조치 되었는지요?

**Comment by rhcpn** [comment]
@hiy2259 해당 이슈 확인 요청 합니다.

**Comment by veldise** [comment]
현재 최신 버전(b-iris.mobigen.com) 에서는 발생하지 않는 문제입니다.

@big-mobigen 
demo.iris.tools 사이트 버전을 요청합니다.

**Comment by sunghoon** [comment]
demo.iris.tools 관련 내용을 조만간 업데이트 될 예정이며, 본 이슈는 닫도록 하겠습니다.
