### ISSUE TITLE
회원 가입 후, 회원 승인이 되지 않는 문제 발생

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2102]
## 버그 설명 ##
회원가입 후, root 계정으로 회원 가입 승인 시, "수락" 버튼을 누른 뒤, 승인 완료 메세지가 출력 되지만 실제로는 승인이 되지 않음.
![image](https://user-images.githubusercontent.com/11566844/79536197-6b424900-80ba-11ea-93e5-63a9bc6f4e3c.png)
![image](https://user-images.githubusercontent.com/11566844/79536253-8e6cf880-80ba-11ea-9cc1-1a7c05b0be22.png)

**Comment by lyj** [comment]
수정 완료됨
