### ISSUE TITLE
[NMS+]사용자 정보 연동시 패스워드 재설정 기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2104]
## 기능 요청 ##

사용자 정보를 다른 시스템에서 주기적 연동하여 IRIS 의 계정으로 생성합니다.
원하는 기능은 사용자가 최초 로그인시, 본인의 패스워드를 본인이 설정할수 있어야합니다.

보통 타시스템에서 계정 ( ID, 조직정보) 만 가져오고 패스워드는 보안상의 이슈로 암호화되어있어 가져올수 없습니다.

1. 따라서 패스워드는 디폴트 패스워드로 넣되 사용자가 최초 로그인시  패스워드를 재설정하여 로그인이 될수있을지요

 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 본 이슈의 최종 상황 정보를 알려주세요.

**Comment by rhcpn** [comment]
해당건에 대해 제가 대신 답변을 달자면, 현 시점에는 아직 해당 기능의 구현에 대해 고려하지 않았습니다.
위의 기능이 여전히 필요한 상황이 아니라면 차년도에 회원가입 ~ 최초 로그인 까지의 과정에 대해 재정리를 하여
처리하는것이 좋을것 같습니다.

**Comment by sunghoon** [comment]
@jjinylee 의견 바랍니다.

**Comment by jjinylee** [comment]
우선 해당기능 고려안해셔도 될듯합니다.
고객에게 그냥 패스워드 무조건 변경해서 쓰라고 했습니다.
