### ISSUE TITLE
로그인후 계속 사용중 일정시간 이후 재 사용시 로그인 세션 만료 인한 접근 불가

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2105]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
로그인 후 계속 사용중인 상태에서 일정시간 지난후
재 사용시  로그인 세션 만료 메시지 이후 접근 불가 상태
이후 브라우저로 다시 접속해도 동일한 메시지 반복 상태이며 접속 불가 상태 지속

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/79628169-a22b6400-8179-11ea-8765-499d354d1fca.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
수정 배포 완료되었습니다.
