### ISSUE TITLE
ISP 도메인 및 서비스 신청 제한 여부 검토

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2106]
## 기능 요청 ##
ISP에서 본인 확인 없이 회원가입만 하면 도메인 및 서비스 신청이 가능하다보니
악용의 소지가 있어 보입니다.
현재도 특정 사용자가 계속적으로 서비스를 신청하여 사용자 이메일로 비밀번호를
전송 하는데, 이메일 사용자가 존재하지 않아 반송 되는 건이 다수 있습니다.

## 원하는 솔루션 설명 ##
회원 가입 시, 본인 인증 (이메일) 을 하지 않으면 사용에 제한을 두는 구성이 필요합니다.

**Comment by sunghoon** [comment]
@rhcpn 조치 되었는지요?
