### ISSUE TITLE
[Studio] 보고서 히트맵 챠트와  시각화옵션 설정 오류

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2107]
## 버그 설명 ##
b-iris.mobigen.com

* 데이터
<img width="712" alt="스크린샷 2020-04-20 오전 10 43 06" src="https://user-images.githubusercontent.com/5126497/79706576-a92ab180-82f4-11ea-929b-33fff8569584.png">

* 히트맵 :  히트맵은 바르게 출력되었습니다. 툴팁의 값의 이름이 0_9세로  잘못 나옵니다.
<img width="713" alt="스크린샷 2020-04-20 오전 10 43 21" src="https://user-images.githubusercontent.com/5126497/79706595-b3e54680-82f4-11ea-889c-0c6ad43032ae.png">

* 시각화옵션 - 데이터  에서 값이 Y축의 컬럼의 값이 아니라, 특정 컬럼 1개만 지정됩니다.
<img width="357" alt="스크린샷 2020-04-20 오전 10 42 16" src="https://user-images.githubusercontent.com/5126497/79706606-bd6eae80-82f4-11ea-9b2c-c19b7a2fa11b.png">

* 툴팁의 내용도 그래서 맞지 않습니다.

## 재현하는 방법 ##
 보고서 "이슈_히트맵"  (demo 계정)참조하세요.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
처리되어 닫습니다.
