### ISSUE TITLE
[Studio] 보고서 챠트 오류 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2108]
## 버그 설명 ##
* 1000 개 이상의 레코드 , sort 하면 1위가 콤텍
![???? 2020-04-20  오후 1 13 28-1](https://user-images.githubusercontent.com/5126497/79714491-f8301100-830b-11ea-8f08-fa5cfc2b1560.png)

* 테이블에서는 같은 레코드 수, 그러나 챠트로 그리면 1위였던 콤텍이 표시 안됨
![???? 2020-04-20  오후 1 12 55](https://user-images.githubusercontent.com/5126497/79714489-f5352080-830b-11ea-9007-557ce78cd6e0.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
현재 보고서는 데이터 개수 제한(limit)를 `10,000`으로 설정하고 있습니다.
조금 더 자세히 확인해봐야 하겠지만, 해당 `pivot` 명령어 결과 개수가 1만개 이상이어서
정렬했을 경우에는 max 값이 포함되고, 정렬하지 않았을 경우에는 포함되지 않는 것으로 생각됩니다.

**Comment by seoryjj** [comment]
데이터 limit 를 더 늘이고, 
사용자가 limit 를 모르고 보고서를 작성해서 엉뚱한 결과가 나오면  IRIS 시스템 자체 신뢰성의 문제가 될 수 있으니,  
관련 limit 를 벗어나 챠트나 결과가 나오면 팝업으로 알려 주는 게 필요해 보입니다.

**Comment by veldise** [comment]
@seoryjj 
알겠습니다. 일단 데이터 limit 설정 기능은 5~6월에 계획중입니다.

**Comment by veldise** [comment]
이제 데이터 객체에서 "데이터 개수 제한" 설정이 가능합니다.
![image](https://user-images.githubusercontent.com/3411842/86301244-53517e80-bc40-11ea-824a-a84bc6c2d43b.png)
