### ISSUE TITLE
[Discovery] DSL 에서 calculate 오류  && sql 에서 컬럼 + 컬럼 오류

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2109]
## 버그 설명 ##
검색 메뉴에서

`* | WHERE  GU like '장안%' |  calculate MALE_NATIVE_POPULATION + FEMALE_NATIVE_POPULATION `

가 동작하지 않습니다.

`* | WHERE  GU like '장안%' |  sql "select  MALE_NATIVE_POPULATION + FEMALE_NATIVE_POPULATION from angora" `

역시 동작하지 않습니다.

* 참고 : 
   * 데이터 모델 : 수원시월별통계

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
해당 모델에 
`MALE_NATIVE_POPULATION`, `FEMALE_NATIVE_POPULATION`
 두 컬럼의 컬럼명이 없습니다.

`MALE_NATIVE_POPULATION_COUNT`, `FEMALE_NATIVE_POPULATION_COUNT`
컬럼명을 이용하셔야 할 것으로 보입니다.

**Comment by sunghoon** [comment]
이슈 보고와 같이 검색하였을때 검색이 종료되지 않습니다. 
빠른 확인 바랍니다.

**Comment by cosmos-mc** [comment]
![image](https://user-images.githubusercontent.com/61724098/80456410-7de53980-8968-11ea-84a5-30ded8ea1b55.png)

메뉴 변경전 화면에서는 오류메시가 정상 동작 합니다.

**Comment by rhcpn** [comment]
comment 남기는 시점에 패치 완료 하였습니다.
