### ISSUE TITLE
검색결과가 정상적으로 출력되지 않음

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2110]
## 버그 설명 ##
검색결과가 정상적으로 출력되지 않고, 대기화면(preloader)이 계속됩니다. 
간헐적으로 하단 그리드 데이터만 출력되고 통계데이터가 출력되지 않습니다. 
반대의 경우도 발생합니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'b-iris.mobigen.com'
2. Main menu '분석' 선택
3. syslog 선택
4. 분석 수행

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/79811518-02581b00-83b1-11ea-905c-ccfee9322ada.png)

## 로그 ##
![image](https://user-images.githubusercontent.com/44352311/79811545-14d25480-83b1-11ea-94f0-d371b972472b.png)

**Comment by veldise** [comment]
`/query/jobs/<sid>` 요청이 pageError로 리다이렉트 되어서
데이터 요청 결과가 json 이 아니라서 발생하는 에러로 확인되었습니다.

현재 syslog 데이터 모델을 선택하면 재현되지 않고, slope_2 모델을 선택하면 재현됩니다.

정상:
![image](https://user-images.githubusercontent.com/3411842/79813282-2702c180-83b6-11ea-95fe-6c9226640297.png)

현재:
![image](https://user-images.githubusercontent.com/3411842/79813222-ff135e00-83b5-11ea-879e-65a410d992dd.png)

@lyj

**Comment by lyj** [comment]
현상 파악 후 적용 예정입니다.

**Comment by lyj** [comment]
적용하여 배포 완료하였습니다.
