### ISSUE TITLE
[ValueLinkU] Studio/테이블 다운로드 시 컬럼순서 불일치

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2111]
## 버그 설명 ##
테이블 조회 시 컬럼 순서가 A C B 로 나와 테이블 시각화 옵션에서 헤더의 순서를 변경하여 A B C로 표시되게 변경하였습니다.
해당 설정이 다운로드 시에도 적용되었으면합니다.
현재는 다운로드 시에는 A C B 순으로 나옵니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
헤더 순서는 UI 스타일 설정이고 다운로드는 분석 미들웨어에서 처리이므로 매우 어렵습니다.
현재 버전에서는 `fields` 명령어 등으로 해결해야 합니다.

**Comment by SONHOJUN** [comment]
넵... 감사합니다. 
말씀하신 방법으로 처리했습니다.
