### ISSUE TITLE
로컬 테이블의 메모리/디스크 보관주기 설정 화면 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2115]
## 기능 요청 ##
로컬 테이블에 대한 메모리/디스크 보관주기를 수정 할 수 있는 설정 화면 필요
현재는 서버에 접속해서 명령어로만 가능 함

## 원하는 솔루션 설명 ##
로컬 테이블에 대한 메모리/디스크 보관주기를 수정 할 수 있는 설정 화면 필요

**Comment by JeongHeeDong** [comment]
진행이 어떻게 되고 있는지 확인 부탁 드립니다.

**Comment by veldise** [comment]
@JeongHeeDong 
아직 진행되고 있지 않습니다.

@anhm 
안형민 책임님, 로컬 테이블의 메모리/디스크 보관주기를 수정하는 IRIS-DB command 가 있나요?

**Comment by anhm** [comment]
@veldise 
```
.table expire {db_name}.{table_name} [disk|ram] {expire_time}
```

형식으로 사용 됩니다.
`expire_time` 의 단위는 분입니다.
`db_name`은  해당 계정으로 로그인 했을 경우 생략이 가능 합니다.

예를 들어 아래와 같이 사용이 됩니다.

```
.table expire ANHM.LOCAL_TEST_TABLE disk 30000
.table expire ANHM.LOCAL_TEST_TABLE ram 30000
```

이와 같이 사용 됩니다.

**Comment by veldise** [comment]
@anhm 
감사합니다.

**Comment by veldise** [comment]
아래와 같이 개발중입니다.

![image](https://user-images.githubusercontent.com/3411842/93572430-cd3c0d00-f9d0-11ea-97e7-c91507c6348d.png)

**Comment by veldise** [comment]
9/24 패치로 기능 추가되어 닫습니다.

![스크린샷 2020-09-24 17 19 50](https://user-images.githubusercontent.com/3411842/94119690-35d03180-fe8a-11ea-94fb-e41378cf627f.png)
