### ISSUE TITLE
[Studio] 여러개 탭에서 작업한 후에 로그아웃 - 다시 로그인하니 화면 헤드가 두줄 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2116]
## 버그 설명 ##
3-4개 탭으로 작업 중 한 탭에서 로그아웃 
-> 다른 탭에서는 로그인세션이 끊어졌다고 팝업이 뜨고, 확인을 누르면 로그인화면이 바로 나옵니다.
-> 다시 로그인하니 두줄의 메뉴바 헤드가 나옵니다.

* 로그인 화면에 보고서 메뉴가 보입니다.

<img width="1304" alt="스크린샷 2020-04-22 오전 10 55 43" src="https://user-images.githubusercontent.com/5126497/79932209-ea06ff80-8487-11ea-8630-1892aca49e20.png">

* 그 상태에서 로그인하면 이렇게 2줄 나옵니다
<img width="1436" alt="스크린샷 2020-04-22 오전 10 42 57" src="https://user-images.githubusercontent.com/5126497/79931587-49fca680-8486-11ea-93bf-5189484edf83.png">

크롬 브라우저

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
처리하여 적용 예정입니다.

**Comment by lyj** [comment]
적용하여 배포 완료하였습니다.
