### ISSUE TITLE
[NMS+]콤보 설정값오류 #1916번 이슈 재발생

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2117]
## 버그 설명 ##

어제 배포후 금일 화면 점검중에 기존 이슈 클로징된 문제가 재발생합니다.
빠른확인부탁드립니다.

#1916 

![캡처에러](https://user-images.githubusercontent.com/5468183/79946032-2186a380-84aa-11ea-8d3b-b2ff1c8b0b38.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#1916 이슈와는 다른 문제입니다. 기존 이슈는 버그였으나
본문 이슈는 combo-box를 구성하기 위한 데이터를 받기 전에 RESTful-API 데이터로 선택이 되어서 발생하는 문제입니다.

다음과 같이 동작해야 정상 동작합니다.
1. combo-box 구성하기 위한 데이터 요청
2. combo-box 목록 구성
3. RESTful-API 요청
4. RESTful-API 결과 수신
5. RESTful-API 결과로 combo-box 항목 선택

**Comment by veldise** [comment]
일단 긴급조치로, combo 목록이 구성되기 전에 '항목 선택' 이벤트가 발생하면
combo 목록이 구성된 다음 코드가 수행되도록 개선해보겠습니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/80075427-a4306100-8585-11ea-927d-980671c63c2f.png)

**Comment by veldise** [comment]
해결 확인 받고 닫습니다.

**Comment by veldise** [comment]
b-iris.mobigen.com 에는 5월 7일 패치하겠습니다.

**Comment by veldise** [comment]
NMS+ 는 패치를 진행하여 해결되었습니다.
