### ISSUE TITLE
[Studio] 보고서-시각화의 히트맵 차트 범례 구간 오류

### ISSUE THREAD

**Issue by yubin90** [mobigen/IRIS-BigData-Platform#2118]
## 버그 설명 ##
보고서에서 히트맵을 생성하여 실행 시 처음 1회 실행에서 범례 구간의 
1. 최소값이 마이너스 값으로 표시됩니다. 
2. 최대값도 데이터 값과 관련 없는 값이 최대값으로 설정됩니다. 
(데이터는 마이너스 값이 없으며 히트맵 차트 위에 표출되는 값도 정상입니다.) 

시각화-시각화옵션의 [데이터] 항목에서 값을 다른 임의의 값으로 클릭하면 다시 정상적으로 범례 및 컬러링이 실행됩니다.  

이후 보고서를 저장-실행시켰을 때 정상적이지 않은 처음 범례 구간(마이너스)이 표출됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서-새 보고서-데이터 모델 및 검색어 입력
![image](https://user-images.githubusercontent.com/40253529/79945911-d5d3fa00-84a9-11ea-9401-b1f923ca5a21.png)
2. 히트맵 시각화 차트 클릭
3. 범례 구간 이상 발생
![image](https://user-images.githubusercontent.com/40253529/79946161-63afe500-84aa-11ea-85aa-e726fd890aec.png)
4. 시각화 옵션의 값 변경

5. 범례 및 컬러링 재설정 됨
![image](https://user-images.githubusercontent.com/40253529/79946251-86da9480-84aa-11ea-8ae1-df644bea6e8a.png)

6. 저장 후 보고서 실행 시 비정상 범례가 보임
![image](https://user-images.githubusercontent.com/40253529/79946362-c99c6c80-84aa-11ea-824e-9a76ddb64056.png)

## 예상한 행동 ##
시각화 옵션 설정 후 보고서 저장-실행하였을 때 범례 및 컬러링이 정상적으로 보여야 함
 
## 스크린샷 ##

![image](https://user-images.githubusercontent.com/40253529/79945515-dd46d380-84a8-11ea-8038-2586c38c66f3.png)

![image](https://user-images.githubusercontent.com/40253529/79945761-7e358e80-84a9-11ea-9f34-e98cf13e9087.png)
![image](https://user-images.githubusercontent.com/40253529/79946738-84c50580-84ab-11ea-897d-be6385e0745c.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
히트맵 유형의 경우, 항상 첫번째 컬럼을 x축으로 설정하고, 다른 컬럼 목록을 y축으로 설정하도록 개선하였습니다.
이에 따라 본문 이슈는 해결되었을 것으로 예상됩니다.
혹시 재현되면 Reopen 및 답글을 달아주시기 바랍니다.
