### ISSUE TITLE
File 브라우저에서 '새로고침' 시 상위 폴더로 이동됨

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2119]
## 버그 설명 ##
폴더명이 한글일 경우 File 브라우저에서 '새로고침' 시 폴더가 상위 폴더로 이동됨

## 재현하는 방법 ##
1. Go to 'File 브라우저'
2. Click on '새로 고침'

## 예상한 행동 ##
새로고침을 했을 경우 현재 폴더 그대로 유지

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/79946966-fd2bc680-84ab-11ea-9d6b-b287cb0f9d7d.png)

새로고침 후 상위폴더로 이동됨
![image](https://user-images.githubusercontent.com/44352311/79946998-0f0d6980-84ac-11ea-9efc-0bd3b2d5d2c8.png)

**Comment by EricLeeMbg** [comment]
폴더명을 한글로 작성할 경우에만 발생하는 문제로 보입니다. 
마찬가지 이유로 한글폴더에는 파일이 업로드되지 않는 현상도 보입니다. 
![image](https://user-images.githubusercontent.com/44352311/79947973-ec7c5000-84ad-11ea-924f-960ecbd314ed.png)

상태는 'success'로 나오나 파일은 업로드되지 않음

**Comment by veldise** [comment]
MINIO의 경우 폴더 개념이 없고 폴더는 단순히 경로일 뿐이라서,
UI에서 새 폴더를 생성하면 내용이 없는 ReadMe.md 파일을 생성하게 되어있습니다.

현재 한글로 된 폴더를 생성하면 ReadMe.md 파일이 없는 것으로 보아 한글 파일이 업로드되지 않는 문제와 같은 문제로 판단됩니다.

**Comment by veldise** [comment]
현재까지는 hdfs-browser 내부 인코딩/디코딩 처리 문제로 판단됩니다.
