### ISSUE TITLE
[ValueLinkU] DSL 명령어 UNION 기능 개선

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2124]
## 기능 요청 ##
현재 DSL 명령어 중 UNION은 다른 데이터모델의 정렬만 지원을 합니다.

기능을 확장하여 다른 데이터모델이 아닌 sql 명령어를 이용하여 서로 다른 결과를 합치는 기능을 지원했으면 합니다.

예를 들어 Raw 데이터를 출력하고 UNION으로 마지막에 통계성 데이터를 합쳐서 테이블에 보여주는 기능이 있으면 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
@SONHOJUN 
위에 작성해주신 내용으로 어떤 기능을 추가해야하는지 정확하게 이해를 하지 못하였습니다.

원하시는 기능에 대한 설명을 조금더 자세히 작성해 주시면 감사하겠습니다.

![IMG_E72B89A96647-1](https://user-images.githubusercontent.com/46172579/81254670-bff83480-9066-11ea-938b-03917b810963.jpeg)

**Comment by SONHOJUN** [comment]
예시한것과 비슷한 기능이면 될것 같습니다.
가능하다면 * | sql "select a, b, c from angora" | union sql "select sum(a), sum(b), sum(c) from angora"
이런식으로 sql 구문을 사용할 수 있는지 확인부탁드립니다.

**Comment by seungfwani** [comment]
요청하신 내용대로 sql 명령어를 사용 할 수 있을 것으로 보입니다.

추가적으로, union 시 두 데이터의 컬럼 개수가 같아야 하는 조건이 있습니다.
예1) df1 = A, B, C 컬럼으로 구성, df2 = sum(A), sum(B), sum(C) 컬럼으로 구성 --> 가능
예2) df1 = A, B, C 컬럼으로 구성, df2 = sum(A), sum(B), NULL 컬럼으로 구성 --> 가능
예3) df1 = A, B, C 컬럼으로 구성, df2 = sum(A), sum(B) 컬럼으로 구성 --> 불가능

**Comment by seungfwani** [comment]
union 이용시 sql 문을 사용할 수 있도록 기능 추가하였고, 금요일(5/15) 배포시에 함께 배포되도록 하겠습니다.

아래는 예시입니다.

![Screen Shot 2020-05-13 at 6 46 09 PM](https://user-images.githubusercontent.com/46172579/81797675-13c4bb00-954a-11ea-9f91-36adb08ba2c4.png)

**Comment by seungfwani** [comment]
사이트 적용이 확인 되었는지 궁금합니다.

**Comment by SONHOJUN** [comment]
@seungfwani 아래와 같이 사용하는데 오류가 발생합니다.

* | sql "select YYYY_WK as Period, CRR_CD, CRR_NM, VSL_NM, VOY_NO_BND, SHIP_AGT_CD, SHIP_AGT_NM, POD_NM, PLAN_Q, POD_ETA_DT, ATA_PTMS, ATA_AIS, ATB_PTMS, ATB_AIS, ATA_PTMS_D, ATA_AIS_D, ATB_PTMS_D, ATB_AIS_D from angora STIME >= '20190101000000'" | union sql "select '' as Period, '' as CRR_CD, '' as CRR_NM, '' as VSL_NM, '' as VOY_NO_BND, '' as SHIP_AGT_CD, '' as SHIP_AGT_NM, '' as POD_NM, count(PLAN_Q)|| '회' as PLAN_Q , count(POD_ETA_DT)|| '회' as POD_ETA_DT, count(ATA_PTMS)|| '회' as ATA_PTMS, count(ATA_AIS)|| '회' as ATA_AIS, count(ATB_PTMS)|| '회' as ATB_PTMS, count(ATB_AIS)|| '회' as ATB_AIS, round(count(CASE WHEN ATA_PTMS_D = 'Y' THEN 1 END)*100 / count(ATA_PTMS),1) || '%' as ATA_PTMS_D, round(count(CASE WHEN ATA_AIS_D = 'Y' Then 1 END)*100 / count(ATA_AIS),1) || '%' as ATA_AIS_D, round(count(CASE WHEN ATB_PTMS_D = 'Y' Then 1 END)*100 / count(ATB_PTMS),1) || '%' as ATB_PTMS_D, round(count(CASE WHEN ATB_AIS_D = 'Y' Then 1 END)*100 / count(ATB_AIS),1) || '%' as ATB_AIS_D from angora where STIME >= '20190101000000'"

![image](https://user-images.githubusercontent.com/7067615/82023413-36c9a900-96c9-11ea-89af-1e16dba8ac2b.png)

**Comment by seungfwani** [comment]
sql 옵션을 추가 하면서,
해당 옵션 사용시 쿼리 파싱에 문제가 있는 것으로 파악 되며,

수정된 버전은 다시 배포요청을 해야합니다.

**Comment by seungfwani** [comment]
union 명령어 수정을 하였으나 배포가 되었는지 확인이 필요합니다.
안되었다면 요청 하도록 하겠습니다.

**Comment by sunghoon** [comment]
해결 되었다고 보고 닫습니다. 추가 사항 발생시 별도 이슈로 등록해 주세요.
