### ISSUE TITLE
[ValueLinkU] Studio/기간 설정 객체 

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2125]
## 버그 설명 ##
현재 기간 설정 객체는 미리 설정 기능과 날짜 및 시간 범위 설정 기능이 한화면에 안나와 사용에 불편함이 있으니 처음부터 같이 나오게 변경해달라는 요청이 있습니다.
검토부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
현재 기능 - 미리 설정
![image](https://user-images.githubusercontent.com/7067615/80077952-2ec68f80-8589-11ea-99ce-e920c7f97920.png)

현재 기능 - 날짜 및 시간 범위
![image](https://user-images.githubusercontent.com/7067615/80078010-43a32300-8589-11ea-8ab8-5ce15f28feeb.png)

요청 기능
![image](https://user-images.githubusercontent.com/7067615/80078068-574e8980-8589-11ea-99f8-879e8fe6d0da.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
#2378 이슈와 같이 리뉴얼 예정으로 현재 개발중입니다.

**Comment by sunghoon** [comment]
@veldise 요구 사항과 진행 내역이 달라보이는데 협의 된것인가요?

**Comment by sunghoon** [comment]
@rhcpn @SONHOJUN #2378로 해당 이슈를 진행하면 본 이슈는 처리 되는것으로 봐도 되는것인가요?
두 분 의견 바랍니다.

**Comment by SONHOJUN** [comment]
@sunghoon @rhcpn @veldise #2378 해당 이슈로 진행되면 본 이슈는 처리 되는 것으로 봐도 될 것 같습니다.
본 이슈는 Close 하겠습니다.
