### ISSUE TITLE
IE에서 로그인정보 상태바 깨지는버그

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2126]
## 버그 설명 ##
IE화면에서 아래 그림과 같이 깨집니다.
![20200424](https://user-images.githubusercontent.com/899539/80131069-a1a92800-85d4-11ea-87d2-98cc8c372fa8.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
IE 화면 뷰에 대한 수정은 추후 적용될 예정입니다.

**Comment by sunghoon** [comment]
@lyj 해당 항목 진행이 어떻게 되었는지 공유 바랍니다. 아직 조치되지 않았다면 진행해 주시고요.

**Comment by onlyeon** [comment]
https://github.com/mobigen/IRIS-Web-Platform/pull/420 이슈 처리 완료되어 현재 IE에서도 제대로 보여지고 있습니다.
