### ISSUE TITLE
HDFS 브라우저에서 파일업로드 문제

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2127]
## 버그 설명 ##

HDFS 브라우저에서 파일 업로드 버튼을 누르면 팝업된 창이 작동하지 않고 
닫기도 안됩니다.
메뉴를 통해 다른 화면으로 이동해야 팝업화면이 풀리고
파일업로드가 불간으한 상태 입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 메뉴 > 브라우저 > HDFS 브라우저 화면으로 이동
2. 상단의 <업로드> 버튼 클릭
3. 팝업된 화면이 작동불능

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
7:30 hotfix 패치로 해결하였습니다.
