### ISSUE TITLE
IE에서 데이터추가 화면 버그

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2128]
## 버그 설명 ##
IE에서 데이터 추가 화면에서 파일을 선택하고 다음단계로 진행한느 버튼이 보이지않는 문제

![20200424-1](https://user-images.githubusercontent.com/899539/80133864-dcad5a80-85d8-11ea-82e0-e877d82b1bd1.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 메뉴 > IRIS DB > 데이터 추가
2. 파일선택을 하고 옵션을 설정하고 다음단계로 이동버튼이 보이지않음

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@jmlee 
(MacOS) google chrome 에서는 정상으로 보입니다.
불편하시더라도 문제가 해결되기 전까지는 google chrome 을 이용해주시기 바랍니다.

![image](https://user-images.githubusercontent.com/3411842/80154520-b6001b80-85fa-11ea-8bd0-d9b72ba8dd61.png)

**Comment by sunghoon** [comment]
@rhcpn @veldise IE 특정 버전 이상에서도 보일 수 있도록 방안을 마련해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
네 알겠습니다.

**Comment by lyj** [comment]
버튼이 보이도록 수정되었습니다.
