### ISSUE TITLE
[ValuelinkU] Studio/테이블 페이징 버튼 및 다운로드 버튼 위치 변경

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2130]
## 버그 설명 ##
테이블 페이징 버튼과 다운로드 버튼이 오른쪽으로 고정되어 있는데 이걸 왼쪽으로 변경

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
배포된 것으로 보고 닫습니다.
