### ISSUE TITLE
사용자 / 그룹(조직) 정보 변경 / 삭제 api 개선

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2134]
## 기능 요청 ##
- 사용자 / 그룹 정보 변경 시 put /meta/account/:id || /meta/group/:id 형태로 전달
- 사용자 / 그룹 정보 삭제 시 delete  /meta/account/:id || /meta/group/:id 형태로 전달
- 사용자 생성의 경우는 multiple 옵션이 있어서 처리가 가능한데 비해 수정, 삭제는 언제나 단일로만 처리
- 그룹 생성의 경우는 multiple 옵션이 써있지 않기에 없는 것으로 판단
- 두 기능(+ 그룹 생성)도 multiple로 처리할 수 있는 api 기능 요청
- 요청이유: 수원시에서(공공이 전반적으로) 사용자의 부서 이동이 잦은데 변경시마다 api로 처리 시간이 오래 걸림

**Comment by sunghoon** [comment]
@veldise 해당 요청 사항에 대하여 어떻게 처리되고 있는지 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
따로 구두로 긴급한 사항이 아니라고 전달받아서, 우선순위가 낮은 것으로 인식하고 있었습니다. 대기 상태입니다.

**Comment by sunghoon** [comment]
@AliceLiddell 해당 이슈에 대한 Site쪽 의견 부탁드립니다.
