### ISSUE TITLE
메뉴 클릭 시 페이지 전환(_self 옵션)

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2135]
## 기능 요청 ##
- 메뉴를 생성하여 클릭 이동하려는 페이지로 변경되는(새 탭으로 뜨는 것이 아닌 _self 옵션과 같이) 기능 추가 요청

**Comment by veldise** [comment]
@lyj 
IWP도 동일한 기능이 필요할 것으로 판단되어 IWP 라벨링합니다.

**Comment by sunghoon** [comment]
@lyj 빠른 조치 바랍니다.

**Comment by lyj** [comment]
@sunghoon 조치 예정입니다.

**Comment by sunghoon** [comment]
@lyj 조치 계획 일정을 공유 바랍니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by rhcpn** [comment]
@sunghoon 해당 이슈는 의미가 애매한 부분이 있습니다. 헌데 이슈 제안자가 퇴사를 하여 인터뷰가 불가능하기 때문에 일단은 close 처리 하는게 좋을것 같습니다.
