### ISSUE TITLE
[ValueLinkU] 특정 데이터가 DB에는 존재하는데 결과에 출력되지 않습니다.

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2136]
## 설명 ##
제보자: 손호준 책임
위치: bis.valuelinku.com

ValueLinkU 사이트 - 저유황 연료유가 (보고서)
IFO380 데이터가 02-26 이전 데이터는 출력되지 않고 있습니다.
DB에는 데이터가 있다고 합니다.

## 내용 ## 
![image](https://user-images.githubusercontent.com/3411842/80183290-86293600-8643-11ea-80e0-5cae737ddd99.png)

```json
{
    "q": "model name = '통합지표_Data_Global' start_date = 20200101000000 end_date = 20200424154753 LOC_CODE = 'HOUSTON' | where DATA_TYPE !='IFO180' | pivot avg(DATA_VALUE) SPLITROW DATA_DATE SPLITCOL DATA_TYPE COLSIZE 500 | sort -DATA_DATE | rename  DATA_DATE  DATE",
    "size": 10000
}
```

![image](https://user-images.githubusercontent.com/3411842/80183304-8de8da80-8643-11ea-8131-e18df6a12e0e.png)

**Comment by anhm** [comment]
문재 파악하여 따로 연락 드렸습니다.
