### ISSUE TITLE
IRIS 메인 화면 사용자 이름 버그

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#2137]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

사용자의 아이디의 아랫부분이 잘려 보입니다. 

## 재현하는 방법 ##
![image](https://user-images.githubusercontent.com/36151180/80189309-6f87dc80-864d-11ea-9372-90451ca29e21.png)
![image](https://user-images.githubusercontent.com/36151180/80189346-7dd5f880-864d-11ea-9078-a378810c9784.png)

psi, joohj7 등 에서 이름의 아랫부분이 잘려보이는 현상이 나타납니다. 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
수정 후 적용 예정입니다.

**Comment by lyj** [comment]
적용하여 배포 완료하였습니다.
