### ISSUE TITLE
Studio: Map / 레이어 추가하면 레이어명 자동 입력

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2138]
## 기능 요청 ##
Studio: Map / 레이어 추가하면 레이어명 자동 입력

## 스크린샷
![image](https://user-images.githubusercontent.com/3411842/80325301-886fd800-886f-11ea-9011-dac892efc55d.png)

**Comment by sunghoon** [comment]
@veldise 간단해 보이는데 바로 반영해도 될지 않을까요?

**Comment by veldise** [comment]
@sunghoon 
네 검토 후 처리하겠습니다.

**Comment by sunghoon** [comment]
기능 확인되어 닫겠습니다.
