### ISSUE TITLE
[OpenLab] 오픈랩에서 제공하는 R/python 자동 생성 스크립트 검증 요청

### ISSUE THREAD

**Issue by big-mobigen** [mobigen/IRIS-BigData-Platform#2140]
## 버그 설명 ##
사용자 계정 비밀번호만 추가하여 조회했을경우 오류 발생합니다.
검색에서 생성하는 기본 IP를 addr = "211.251.247.185" 로 변경해 주면 동작하는 것으로 확인되며 샘플 코드에 IP정보 변경 방법에 대해 문의드립니다.
![image](https://user-images.githubusercontent.com/25650544/80348669-1d42f780-88a9-11ea-933c-746572b33c65.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/25650544/80348876-65621a00-88a9-11ea-974b-e180317c07a2.png)

![image](https://user-images.githubusercontent.com/25650544/80348888-698e3780-88a9-11ea-8a90-051ec95b0869.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm 진행 상황을 공유해 주시기 바랍니다.
