### ISSUE TITLE
[IWP] 오타: IRIS Analyzer & IRIS Analyser

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#2143]
## 버그 설명 ##
무료체험신청으로 제품 페이지 생성시, 메뉴에 실제 제품명인 `IRIS Analyzer` 가 아닌 `IRIS Analy's'er` 로 오타가 있는 것 같습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. iris.tools 로그인
2. 무료체험 신청후 제품(IWP) url 획득
3. IWP 로그인 후 우측 상단 메뉴 확인
4. IRIS Analyser 오타 확인

## 스크린샷 ##
<img width="446" alt="스크린샷 2020-04-28 오전 9 43 51" src="https://user-images.githubusercontent.com/23020977/80434597-28436980-8935-11ea-91f2-8f3c7520d742.png">

**Comment by rhcpn** [comment]
@anhm SaaS Service 설치 버전의 DB 스크립트에 오타가 있는것 같습니다. 수정 요청 합니다.

**Comment by sunghoon** [comment]
@anhm 처리 완료 되었나요?

**Comment by rhcpn** [comment]
@sunghoon 현재 메뉴명도 위의 이슈와 전혀 다르게 되어 있기도 하고 내용도 잘 처리 되었기 때문에 Close 처리 해도 될것 같습니다.
