### ISSUE TITLE
[IWP] IRIS Studio의 접근 권한 메뉴에서 사용자 추가가 되지 않는 문제

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#2144]
## 버그 설명 ##
IRIS Studio 에서 보고서를 생성하고, 접근 권한 메뉴에서 사용자 아이디 오른쪽의 "+" 아이콘을 클릭해도 추가가 되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 부여받은 IWP url로 로그인
2. IRIS Studio 메뉴 접근
3. 임의의 보고서를 선택해 편집 -> 수정 메뉴를 클릭해 수정 화면으로 진입
4. 우측 상단 '접근 권한' 클릭
5. 사용자 추가 메뉴에서 임의의 사용자 오른쪽의 "+" 아이콘을 클릭
6. 사용자가 "권한이 있는 사용" 쪽에 추가될 것으로 예상했으나, 무반응

## 예상한 행동 ##
사용자가 "권한이 있는 사용" 쪽에 추가될 것으로 예상했으나, 무반응

## 스크린샷 ##
<img width="1082" alt="스크린샷 2020-04-29 오전 10 46 56" src="https://user-images.githubusercontent.com/23020977/80554185-45486d00-8a07-11ea-93f6-99c2b9b63620.png">

**Comment by rhcpn** [comment]
@leehaejoon 테스트를 진행한 URL을 알려주시면 테스트 해보겠습니다. 
참고로 http://b-iris.mobigen.com 에서는 발생하지 않는것으로 보입니다.

**Comment by rhcpn** [comment]
@leehaejoon 테스트한 사이트가 최신 버전이 아닌것으로 얘기가 되었으므로 해당 이슈는 close 하겠습니다.
