### ISSUE TITLE
IRIS 보고서 콤보박스의 Default 값

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2145]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

 보고서에서 콤보박스의 Default 값을 넣을 수 있습니다.

콤보박스의 Default 값은 외부에서 canvas 변수로 받아오고, 현재 보고서 페이지의 콤보박스에

넣으려고 하는데 Y,N 의 경우 동작이 재대로 안되는 것 같습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

 텍스트 박스에 값이 N으로 나오니, ${canvas_11} 변수에는 N의 값이 지정되어 있는것으로 보이는데,

콤보박스에 디폴트값 입력에 직접입력, ${canvas_11} 을 입력하면 값이 나오지 않습니다.

다른 str은 되는걸 확인했는데, Y,N의 경우 되지 않습니다.. 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

위의 N 값이 들어가 있는 텍스트 박스가 ${canvas_11} 변수로 받아온 값입니다.

![image](https://user-images.githubusercontent.com/16331916/80555547-83e02680-8a0b-11ea-86d1-deb7d5d47efb.png)

![image](https://user-images.githubusercontent.com/16331916/80555620-c570d180-8a0b-11ea-9525-cf8843224a2e.png)

![image](https://user-images.githubusercontent.com/16331916/80555630-ce61a300-8a0b-11ea-8f76-75eecf62a058.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@kim3163 
해당 Combo 객체의 "데이터"탭 설정 부분도 첨부 부탁드립니다.

**Comment by kim3163** [comment]
![image](https://user-images.githubusercontent.com/16331916/81374630-aaecd580-913a-11ea-8d34-d74eac011ea7.png)

데이터 탭 설정 부분 첨부드립니다.

**Comment by veldise** [comment]
'외부'라고만 하셔서 제가 조금 헷갈렸는데,
`extra_param`을 이용한 querystring 방식은 아래와 같이 정상 처리되고,
Popup, Portlet 객체를 사용시 "직접 입력"에 입력된 내용이 처리되지 않는 버그를 확인하였습니다.

![image](https://user-images.githubusercontent.com/3411842/81622486-14ffc600-942c-11ea-8e08-3358cf9489d4.png)
