### ISSUE TITLE
[NMS+]IRIS slave-node 격리조건 개선요청(중요!!!)

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2146]
## 기능 요청 ##
IRIS slave 의 상태를 점검하여 slave node 를 격리시 현재는 체크하는 시점의 값으로만 체크하여 node 를 격리하여
순간 peak 치는경우에도 무조건 slave node 가 격리되므로,
지속시간 ( 분으로 설정하여) 격리될수있도록 개선 요청드립니다.

현재  담당매니저 몇분만 사용하고 있어서 잠깐 현상이 발생하겠지만,
운용자가 액티브하게 사용하게 될경우 보완조치가 필요합니다. 

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by anhm** [comment]
해당 기능은 개발이 완료된 상태입니다.
해당 사이트에 옵션을 추가하여 적용하도록 하겠습니다.

**Comment by sunghoon** [comment]
@anhm 완료 되었나요?

**Comment by anhm** [comment]
@sunghoon 
해당 옵션이 적용된 버전이 배포되어 있는 상태이며, 옵션 설정을 진행하면 됩니다.
```
[EHD]
ehd_max_busy_cont_cnt = 1
```

**Comment by sunghoon** [comment]
@jjinylee @anhm 옵션 설정은 언제 진행하면 되나요?

**Comment by anhm** [comment]
@sunghoon 
추후 IRIS-DB 패치 일정을 한번더 잡아야 하는 상황이며,
그 일정에 맞춰 설정을 변경 적용 진행할 예정입니다.

**Comment by sunghoon** [comment]
@jjinylee 본 이슈와 관련된 준비가 된 상황이며, 일정을 잡아 주셔서 진행해 주시기 바랍니다.

**Comment by anhm** [comment]
서버의 설정값을 다음과 BUSY가 연속 3번 발생했을 경우에만 BUSY 상태로 변경하도록 수정해 두었습니다.

관련 설정값은 아래와 같습니다.
```
[EHD]
ehd_max_busy_cont_cnt = 3
```
