### ISSUE TITLE
[NMS+]studio 조회결과 표현 개선(고객요청)

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2147]
## 기능 요청 ##
데이터 조회후 결과가 없을경우 현재는 [경고]처럼 보임

경고가 아닌 표현 /색깔로 변경요청 ( 경고 아이콘 말고 )

단순히 조회결과가 없는건데,  운영자들이 장애라고 인지함

![캡처2](https://user-images.githubusercontent.com/5468183/80579569-40a2a980-8a45-11ea-95de-a27f0b620d74.PNG)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/81875708-d00a9980-95bb-11ea-9359-60d2e8edc9cd.png)

#2172 임시 조치로 일단 위와 같이 개선되어 닫습니다.
