### ISSUE TITLE
IRIS-Analyzer 에서 "컬럼이름" 을 카피할 수 있는 기능이 필요합니다.

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2148]
## 기능 요청 ##
실무에서 컬럼이름이 복잡할 경우 애널라이저 쿼리 입력창에서 컬럼이름을 직접 써 넣는 것이 **매우** 불편합니다.
컬럼이름을 복사에서 붙여넣는 기능이 절실합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@rhcpn 위 사항에 대한 검토 및 진행 일정에 대한 정보를 공유해 주세요.
