### ISSUE TITLE
마우스 오버시 자동으로 나타나는 메인메뉴 불편

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2149]
## 기능 요청 ##
아이리스 메인 매뉴에서 마우스 오버시 클릭을 하지 않아도 자동으로 나오는 메뉴가 실작업시 불편합니다.
작업시 마우스 움직임에 메뉴가 자꾸 나와 편집을 방해합니다.
gmail 에서 메인매뉴 동작처럼 하면 좋을것 같습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by rhcpn** [comment]
@tessekim 해당 내용은 내부 기획 검토 후 수정 방향을 정해서 처리 하도록 하겠습니다.
