### ISSUE TITLE
스튜디오 빠른저장, 저장메시지 잠깐 보여주고 자동으로 없어지기

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2150]
## 기능 요청 ##
아이리스 스튜디오 대시보드 편집 후 "빠른저장" 을 누를 시 "저장하였습니다" 메시지와 함께 "확인" 버튼을 눌러야 창이 사라지는데 "빠른저장" 의 컨셉에 맞게 메시지를 1초 정도만 보여주고 자동으로 사라졌으면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 검토 진해 바랍니다.
