### ISSUE TITLE
IOS 상에서 IRIS-Studio 편집화면의 "검색어" 창의 사이즈 조절이 안됩니다.

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2151]
## 버그 설명 ##
macOS 나 윈도우상에서는 잘 됩니다.
IOS 아이패드로 외부에서 작업할 때가 가끔 있는데 IOS 상에서는 창조절이 안됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise @onlyeon 확인하여 조치 바랍니다.

**Comment by onlyeon** [comment]
해당 이슈는 iOS Safari에서 resize 속성을 지원하지 않아 발생하는 것으로 파악됩니다.

![스크린샷 2020-09-24 오후 3 35 13](https://user-images.githubusercontent.com/11944592/94121881-d6bfec00-fe8c-11ea-8b23-6756506baa76.png)

https://codepen.io/onlyeon/pen/zYqeraE 순수 `<textarea>`로 구현한 예제인데, iOS Safari에서 접속시 IRIS에서 발생하는 이슈와 마찬가지로 리사이징이 불가능한 것을 확인할 수 있습니다.
브라우저에서 미지원하는 항목이라 CSS 속성 만으로는 해결이 어렵습니다.

**Comment by sunghoon** [comment]
@onlyeon 확인하였습니다. 

@eumminsun textarea tag 기반이 아닌 별도 UX를 준비 해 주세요.
