### ISSUE TITLE
[고급시각화] network 데이터 시각화를 위해 2개의 데이터모델을 선택해서 그리는 기능이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2152]
## 기능 요청 ##

network 데이터는 from -> to를 나타내는 데이터(edge data) 와 
각각의 노드들을 나타내는 Node data 로 나누어서 만들어 집니다.
컬럼이 다르고, 레코드 수도 다르므로 merge , join 을 할 수 없습니다.

* edge data
<img width="317" alt="스크린샷 2020-05-04 오후 2 22 03" src="https://user-images.githubusercontent.com/5126497/80938197-2e44b900-8e13-11ea-80b9-82b021dac8c5.png">

* node data
<img width="132" alt="스크린샷 2020-05-04 오후 2 22 24" src="https://user-images.githubusercontent.com/5126497/80938203-36045d80-8e13-11ea-9307-ead84dbc5a22.png">

* edge data, node data 로 다음과 같은 sankey 챠트를 그릴 수 있습니다. (D3 sankey chart)

<img width="819" alt="스크린샷 2020-05-04 오후 2 19 00" src="https://user-images.githubusercontent.com/5126497/80937973-3819ec80-8e12-11ea-8c6e-364575ac7833.png">

* R 에서 D3 API 로 그린 코드에서는 다음처럼  edge, node2개의 object 를 같이 불러서 챠트를 그립니다.

` sankeyNetwork( Links = edge_df, Nodes = node_df, Source = "FromNum",
                              Target = "ToNum", Value = "barrel", NodeID = "NodeStr", fontSize = 14,
                              LinkGroup = "LinkGroup")`

* 데이터모델이 2개이므로 IRIS에서는 그릴 수 없어서,  
   * 대화형분석의 Rstudio 에서 그린 후
   *  html 로 minio 에  저장
   * 보고서 에서 **외부URL** 로  붙이기

같은 복잡한 과정이 필요합니다.

network 데이터를 ( edge data, node data )
보고서의 다른 다양한 기능(콤보박스, 달력...) 들을 사용하면서 쉽게 sankey 챠트로 그리고 싶습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@seoryjj 구두로 직접 설명 부탁드립니다.
