### ISSUE TITLE
[Studio] 챠트 - 히트맵 에서 데이터 설정에 Y축 설정을 할 수 없습니다.(X축과 값만 있음)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2153]
## 버그 설명 ##
Studio 의 히트맵 그릴 때
Y 축을 설정할 수 없습니다.

데이터모델 : 수원시월별통계
X축 : BASIS_DATE(기준일)
Y축 : GU 
값 : 세대수

로 하여,  구별로 세대수의 변화를 기준일 추이로 히트맵으로 그리려고 합니다.
그런데 Y축 설정하는 게 없습니다.

<img width="984" alt="스크린샷 2020-05-04 오후 3 18 34" src="https://user-images.githubusercontent.com/5126497/80940379-8e8b2900-8e1a-11ea-934e-9725e4f8ec69.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#2118 동일 이슈

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/2118#issuecomment-642326725
