### ISSUE TITLE
[ValuelinkU] Studio/테이블 객체 이벤트 값 전달 설정

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2155]
## 버그 설명 ##
테이블 객체에 이벤트값 전달 설정이 현재 1개의 컬럼만 설정할 수 있게 되어 있는데 복수컬럼을 설정 할 수 있으면 합니다.
현재는 여러컬럼을 조합한 쿼리문을 작성하여 파라미터로 설정해서 상세 페이지를 호출하는데 문제는 다운로드할 때 파라미터로 넘길 컬럼까지 다운로드가 되는 문제가 있습니다.
다운로드할 때 해당 컬럼을 제외하고 다운로드하는 기능이나 복수컬럼을 파라미터로 설정 할 수 있는 기능이 필요합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
