### ISSUE TITLE
보고서 접근권한 정상 동작 하지 않음

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2156]
## 버그 설명 ##
- 보고서가 그룹(조직)에 따라 공유가 되지 않음

## 재현하는 방법 ##
- iris의 보고서의 접근 권한을 그룹으로 설정한 경우 정상적으로 동작하지 않음
- 사용자를 단독으로 설정한 경우는 해당 사용자에게로 공유됨

## 예상한 행동 ##
- 보고서의 접근 권한 중 그룹을 선택하면 해당 그룹에 속한 사용자(수원시의 경우 groupId2에 포함된 것도 함께)에게도 접근이 가능

**Comment by veldise** [comment]
@big-mobigen 
현재 수원시에 배포된 brick, meta, studio 등의 버전 정보를 확인 부탁드립니다.

**Comment by veldise** [comment]
일단 본사 최신 버전에서는 정상 동작하는 것으로 보입니다.
수원시 버전에서 `groupId2` 관련해서 문제가 있는 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/81261083-597b1280-9076-11ea-872d-4e9f5e7a8ef4.png)

![image](https://user-images.githubusercontent.com/3411842/81261051-449e7f00-9076-11ea-92fe-4aad6fba8c3c.png)

![image](https://user-images.githubusercontent.com/3411842/81261065-4c5e2380-9076-11ea-84d4-1ff0203afb10.png)

![image](https://user-images.githubusercontent.com/3411842/81261016-33ee0900-9076-11ea-8ced-b084554eaf85.png)

**Comment by veldise** [comment]
본사 버전에는 `groupId` 파라미터 처리 관련하여 오타가 있어 수정하였었는데,
수원시에는 배포가 안 된 것 같습니다.

**Comment by big-mobigen** [comment]
@veldise 
수원시청  brick, meta, studio 버전을 전달 드립니다.
brick   v0.1.9_d6325ce
meta   v0.0.2_8b36745
studio  v2.5_1eb040f
sherman  v1.7.2_2ab0d6e

**Comment by veldise** [comment]
@big-mobigen 
감사합니다.

**Comment by veldise** [comment]
@AliceLiddell 
groupId2 에 대해서는 이전에 데이터 모델에 대해서만 이야기가 됐었는데, 보고서도 해야하는 건가요?
