### ISSUE TITLE
GridView로 데이터를 보고 싶습니다. 

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2157]
- 테이블 목록 정보를 조회해서.
![스크린샷 2020-05-06 오후 2 06 39](https://user-images.githubusercontent.com/512653/81139998-d046db80-8fa2-11ea-9741-c1a24c55891c.png)

- GridView로 표현하고 싶은데 오류가 발생합니다.
![스크린샷 2020-05-06 오후 2 05 28](https://user-images.githubusercontent.com/512653/81139988-c4f3b000-8fa2-11ea-950a-5c45db634822.png)

- 시간 필드 설정 혹은 지정 이런것 없이 그냥 데이터만 보는 방법 필요.

**Comment by sunghoon** [comment]
@anhm 요것 좀 봐주세요. DSMS에서 뭔가 안되는듯합니다.

**Comment by anhm** [comment]
웹상에서의 내용을 확인해본 결과 
`UPD_DATE`
컬럼을 사용할 경우 문제가 발생하는 것으로 확인이 되었습니다.

해당 문제를 해결하기 위해서는 DSMS를 패치해야 하며, 그전까지는 해당 컬럼을 제외하고 검색을 하시면 사용이 가능합니다.

**Comment by anhm** [comment]
정확한 원인은 datetime 컬럼이

**Comment by anhm** [comment]
정확한 원인은 컬럼 타입이 datetime이며, 값이 null 인 상태에서
해당 컬럼의 값을 가져오려고 할 경우 발생하고 있습니다.

따라서 case when으로 처리를 하거나, 혹은 컬럼 타입을 변경하는 쿼리를 사용할 경우 해당 컬럼도 사용이 가능 합니다

**Comment by veldise** [comment]
웹 이슈가 아닌 것으로 보고 IBP 라벨 제거하겠습니다.

**Comment by sunghoon** [comment]
@anhm DSMS에서 패치 진행 되고 있나요?
@veldise 그리드에서 예외처리 해서 데이터를 보여 줄 수 있나요?

**Comment by veldise** [comment]
@sunghoon 
위 상태는 UI 에서 데이터를 받지 못한 상태이므로 불가능합니다.

**Comment by sunghoon** [comment]
@veldise 데이터를 받지 못하였으며 해당 하는 메시지로 적절하게 사용자에게 알려 줄수 있도록 메시지를 수정해 주세요.
@anhm  DSMS 관련 패치 사항 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
'에러가 발생했습니다.'와 같이 메시지 출력을 변경하는 것은 이번 패치에 포함되어있습니다.

**Comment by sunghoon** [comment]
@anhm DSMS 관련 패치 사항 공유 바랍니다.

**Comment by anhm** [comment]
해당 문제를 해결하여
다음 패치에 반영될 예정입니다.
