### ISSUE TITLE
삭제된(탈퇴한) 사용자가 생성한 보고서 목록을 호출할 수 있는 API

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2158]
## 기능 요청 ##
- 현재 iris의 사용자를 api를 통해 삭제하는 경우 삭제 대상 사용자가 생성한 보고서로는 접근이 불가능(root 계정 외에)
- 사용자가 삭제될 때마다 담당하는 보고서를 그 시점에서 변경하는 것은 관리자에게 부담이 큼
  - 매번 삭제될 때마다  root 계정으로 접속해서 처리하는 것도 힘듦
  - 보고서 화면에서 삭제된 사용자가 누군지 알 수 없음
- 사용자가 삭제될 때는 지금과 동일한 flow로 처리하는 대신 존재하지 않는 사용자가 생성한 보고서의 정보를 가져올 수 있는 api가 있다면 그것을 이용해 acl 정보를 변경 가능

## 원하는 솔루션 설명 ##
- meta/report/remove-user 같은 형태의 url을 통해 삭제되어 존재하지 않는 사용자가 생성한 보고서 목록 정보 호출

## 기타 ##
- 현재 수원에서 사용자가 이미 삭제되어 접근할 수 없는 보고서들이 있기 때문에 근 시일내에 개발 필요

**Comment by veldise** [comment]
@AliceLiddell 
현재 MDA 및 NB_IOT 요구사항/이슈를 처리중에 있어 근시일 내에 개발이 어렵습니다.
따로 박세종 팀장님께 문의해주시면 감사하겠습니다.

**Comment by rhcpn** [comment]
@veldise @AliceLiddell 홍성남 책임이랑 얘기해봤는데 일단 접근 방식은 아래와 같이 하면 좋을것 같다고 얘기했습니다.

1. 수원시에서 사용자 삭제 시, 삭제된 사용자를 수집
2. 전체 보고서 리스트를 가져와서 삭제된 사용자와 비교
3. 삭제된 사용자가 소유하고 있었던 보고서는 소유자 변경

위와 같은 방식으로 하면 어떨까 하는데 검토 부탁합니다.

**Comment by veldise** [comment]
@rhcpn
네, 전체 보고서 리스트 조회는 root 유저 권한으로 가능하고, 소유자 변경은 acl API를 사용하면 되니 문제 없을 것 같습니다.

**Comment by veldise** [comment]
@rhcpn @AliceLiddell 
파라미터로 1) 보고서 id 목록, 2) 변경할 소유자ID 두 가지를 받아서 해당 보고서의 소유자를 변경하는 API를 차주 화요일까지 만들어보도록 하겠습니다.
