### ISSUE TITLE
[NMS+]캘린더의 초기시간 설정 옵션 및 조회범위 체크 기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2159]
## 기능 요청 ##
보통 그리드에 데이터 조회시 기간을 시작일시~종료일시로 조회하여 조회합니다.

1. 초기 시간설정이 현재는 [현재시간] 밖에 안되는데 
시작부분이 현재시간이 아니고, 현재시간 -1일전 이런경우가 많습니다.

날짜일 경우에는 현재시간에서 1일전 , 2일전, 1달전 등으로 설정할수있도록

날짜 :  [현재시간] - 1D | 1M | 1Y ( 일/월/년)을 설정,
시간:   [현재시간] - 1H | 2H  등 현재시간기준에서 minus 시간설정이 필요합니다.

![i1](https://user-images.githubusercontent.com/5468183/81151576-16f4ff80-8fbc-11ea-97e7-cfdd6baf98a3.PNG)

![i2](https://user-images.githubusercontent.com/5468183/81151590-1bb9b380-8fbc-11ea-8494-f6d13b3efd1d.PNG)

2. 시작일시 ~ 종료일시 의 조회범위 체크 기능
#1946

에 요청한 기능인데,  빠른시간내에 적용되지않을듯하여

시작일, 종료일을 파라미터로 받아서 기간범위만 체크하는 restAPI 를 만들어서 해당기능을 적용하려고보니

그리드의 데이터 조회실행은 데이터모델| DSMS 이고 조회전에 위의 기간체크 restAPI 를 콜하여 restAPI 결과가 성공인경우만 데이터가 조회하도록 하고 싶습니다.
하지만  데이터그리드의  트리거가 restAPI 가 아니므로 해당기능이 정상동작하지 않습니다.

따라서 #1946 의 빠른개발 or 위의 방안을 적용할수 있는 가이드 부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
해당 기능은 6월에 계획중입니다.

**Comment by veldise** [comment]
9/3 패치로 아래와 같이 제한범위와 기본값을 상대시간으로 설정할 수 있게 되었습니다.

![image](https://user-images.githubusercontent.com/3411842/92081865-b4dbc800-edfe-11ea-8609-89455d07725f.png)
