### ISSUE TITLE
[NMS+]studio 에서 데이터모델로 조회시 모델을 동적으로 할당할수있는 기능

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2160]
## 기능 요청 ##

현재 studio 에서 데이터 모델로 조회시 모델을 1개만 선택해야하는데 
모델의 검색쿼리에    sql 처럼, select from angora 가 아니고, "angora.모델명" 을 넣어 쿼리를 동적으로 생성하고 싶습니다.

1분 | 5분 | 30분 마다 테이블이 달라서 모델을 별도로 생성했으나,
통계 테이블마다 각각 보고서를 만드는게 아니고
한 보고서내에 체크옵션( 1분|5분|30분 ) 에 따라 데이터를 조회합니다.
따라서 

 {% if combo_period == '1M' %} 
select *
from per_cpu_1m
{%endif}

{% if combo_period == '5M' %} 
select * from per_cpu_5m
{%endif}

이런식으로 studio 에서 그리드뷰는  DSMS로 동적 쿼리를 생성해서 사용하고 있는데

차트데이터를 보여주기위해 모델을 통해서 조건에 따라 다른 모델을 검색쿼리에 넣을수 있는 기능이 필요합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seoryjj** [comment]
개발전까지 활용하시라고 동적으로 검색어 만드는 방법중 체크박스 사용하는 예시를 알려드립니다.

방법은 체크박스 변수를 사용해서 검색어를 만들면 됩니다.

<img width="511" alt="스크린샷 2020-07-31 오전 8 53 59" src="https://user-images.githubusercontent.com/5126497/88985642-c6b3e200-d30b-11ea-9951-5737088f2dc1.png">

<img width="205" alt="스크린샷 2020-07-31 오전 8 54 16" src="https://user-images.githubusercontent.com/5126497/88985648-c9aed280-d30b-11ea-81d9-8964d22d1d6d.png">

- 검색어 사용 예시
<img width="517" alt="스크린샷 2020-07-31 오전 8 54 49" src="https://user-images.githubusercontent.com/5126497/88985789-3f1aa300-d30c-11ea-9178-cf2b4d6aded3.png">


${checkbox_2} 변수를 검색어에 쓰면 체크되는 값에 따라 검색어 구문이 변합니다.
주의할 점은 체크박스 객체에 디폴트 값을 미리 설정두어야 합니다. 빈 값으로 검색어가 만들어 지지 않게요.
