### ISSUE TITLE
Studio / List Compoment에 상단 검색 기능을 옵션으로 표기 여부를 설정하면 좋을것 같습니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2162]
![스크린샷 2020-05-07 오후 1 02 41](https://user-images.githubusercontent.com/512653/81253362-5a567900-9063-11ea-9f6a-2cd92b1cc08e.png)

**Comment by veldise** [comment]
@sunghoon 
개발 완료되었고 10.29 패치 예정입니다.

**Comment by sunghoon** [comment]
@veldise 어떻게 처리 되고 있나요?

**Comment by veldise** [comment]
패치 후 아래와 같이 미사용으로 설정하면 검색 기능이 나오지 않습니다.

![image](https://user-images.githubusercontent.com/3411842/97540954-b6dd9400-1a07-11eb-99e7-b723a98b481b.png)
