### ISSUE TITLE
[Angora] 명령어 잘못 사용시 발생하는에러가 좀 더 사용자 친화적이면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by leehaejoon** [mobigen/IRIS-BigData-Platform#2163]
## 개선 제안 내용 ##
현재 IRIS Analyzer 에서 Angora 명령어를 제대로 사용하지 않으면, 다음과 같은 오류팝업이 발생합니다.

<img width="1437" alt="스크린샷 2020-05-07 오후 2 14 07" src="https://user-images.githubusercontent.com/23020977/81256995-17010800-906d-11ea-94b0-d228ef6c5921.png">

- 저만 그렇게 느끼는 것일수도 있으나, 느낌표 알림창과 함께 '오류' 라는 문구를 내뱉는 것은 단순히 명령어를 잘못 사용한 것을 넘어 무언가 시스템상에 문제가 있는 것으로 오인할 소지가 있어보입니다. help 같은 느낌으로 명령어 사용법을 출력하는건 어떨까요?
- 또한, `angora error: <class 'angora.exceptions.AngoraException'>` 와 같은 내용을 명령어 잘못 사용시에 굳이 보여줄 필요는 없을 것 같습니다. (일반 사용자 기준에서 지나치게 저수준의 정보인 것 같습니다)
- 또한 현재 페이지는 한국어 버전으로 설정되어 있으므로 발생하는 에러도 한국어로 발생하면 좋을 것 같습니다.

기능상 하자가 아닌 사용하면서 느낀 단순 개인 의견이므로, 검토 후 반영 여부를 결정해주시면 될 것 같습니다.

**Comment by jjinylee** [comment]
위의 개선내용은 타 사이트내에서도 필수기능이라고 생각하지만 그냥 얘기하지않은 불편한 진실입니다.
1. 에러를 봐도 정확히 알려주지않기때문에 먼소리인지 정확히 알수도 없고
2. 왠지 커다란 오류인것만 같은 느낌적인 느낌만 주고
exception 구간마다 코드 exception 을 던질게 아니고
exception 을 정의하여 사용자에게 어느부분을 수정해야하는지 알려줘야합니다.

**Comment by seungfwani** [comment]
@sunghoon @anhm 
앙고라의 예외 메세지의 구성이 예외 발생 원인을 알려주는 수준이 많습니다. (해결 방법 제시 등은 미흡)

한글, 영어 등 언어별 메세지 구성은 현재 구성(예외 발생시 메세지 1개 전송) 에서는 처리하기 까다로울 것으로 보입니다.
방안으로는, 각 언어별로 메세지를 구성하여 전송하는 것이 있을 듯 합니다.

**Comment by cosmos-mc** [comment]
@seungfwani 
저 에러 메시지는 개발자가 예외처리에 필요한 디버깅을 위한 메시지 입니다.
당연히 사용자 메시지라고 볼 수 없습니다.
예외 발생시 내부적으로 정의한 에러코드에 따라 
사용자가 이해할 수 있는 메시지로
변경해야 합니다.
