### ISSUE TITLE
Studio / Combo Box 기능 개선 요청

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2164]
![스크린샷 2020-05-07 오후 5 48 39](https://user-images.githubusercontent.com/512653/81274408-33ac3880-908b-11ea-92d2-ef62c07bb9c6.png)

**Comment by veldise** [comment]
@sunghoon 
"아무런 선택이 없는 상태로 정의한다"라는 동작의 의미가 잘 이해가 안됩니다.
조금 더 설명을 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 사내(180) 서버의 보고서중 '프로젝트별 업무 분석' 을 참고 하시면 될 것 같습니다.

* 기본 내용은 노란색 주석으로 설명해 두었습니다.
* 그룹을 변경하면서 선택 할때 PM 항목을 재검색되는데 이전에 설저오디어 있는값이 남아 있어 동작의 오류를 유발
* 비슷한 내용은 조회 버튼을 클릭하면 특정한 변수값들을 초기화 하고 싶습니다.

**Comment by veldise** [comment]
@sunghoon 
List, Combo-box 등의 목록 데이터를 다른 데이터로 재구성하였을 경우,
해당 객체의 선택 항목 / 변수값을 초기화 로 이해했습니다.

수원시 이슈가 처리되는대로 진행하도록 하겠습니다.

문제 상황:
![image](https://user-images.githubusercontent.com/3411842/82420298-812c9a80-9aba-11ea-97cd-8062726a6121.png)
