### ISSUE TITLE
버튼의 색상이 바뀌지 않는 버그

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2165]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

![image](https://user-images.githubusercontent.com/16331916/81360625-54ba6b00-9117-11ea-8df6-8fc8663be62b.png)

 현재 작성된 보고서의 버튼이 모두 파란색 기본색으로 변경되어있고,

다시 수정해도 색이 바뀌지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
본사 최신 버전은 정상으로 보입니다.

![image](https://user-images.githubusercontent.com/3411842/81362017-deb80300-911a-11ea-9281-fcf4d7bba7c7.png)

다시 한 번 확인해주시고 문제가 다시 발생할 경우에는 재현방법을 조금 더 상세히 기술해주시기 바랍니다.

**Comment by kim3163** [comment]
버튼을 새로 생성하여 바꾸면 정상처리 됩니다..
근데 예전에 만들어 놓았던 버튼들이 비정상 동작하는 것으로 보입니다..

**Comment by veldise** [comment]
@kim3163 
문제 확인하였습니다. 오늘 16시 긴급 패치로 해결하도록 하겠습니다.

**Comment by veldise** [comment]
해결 확인되어 닫습니다.
