### ISSUE TITLE
Studio: 서버 데이터를 다시 불러왔을 때 변수 초기화

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2166]
## 버그 설명 ##
Chart, Map, Combo 등 서버 데이터로 테이블이나 목록을 구성하고, 특정 항목을 선택하여 그 항목에 따라 변수값이 설정된 상태에서 다른 데이터로 테이블/목록 등을 재구성하였을 때 변수가 초기화되어야 합니다.

**Comment by sunghoon** [comment]
@veldise 요구 사항 입수 경로를 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
제가 문제가 된다고 생각하여 작성한 이슈입니다.

**Comment by sunghoon** [comment]
우선은 닫아 두도록 하겠습니다.
