### ISSUE TITLE
데이터 모델 생성 후 조회 시 timestamp에 적용된 format이 정상적으로 출력이 되지 않음

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2167]
## 버그 설명 ##
- 데이터모델에서 특정 컬럼을 timestamp로 한 후 해당 포맷을 'YYYY'로 지정했음에도 검색 페이지에서 조회하면 'YYYY/MM/DD HH:mm:ss' 형태로 표출
- 새로 만드는 IRIS에서는 해당 포맷대로 나오는 것 확인. 수원시에 적용된 버전에서는 그렇지 못함

## 재현하는 방법 ##
1. 데이터 모델 생성, 생성시 특정 컬럼의 포맷을 'YYYY' 등과 같이 처리
2. 검색에서 데이터 모델 검색하여 조회

## 예상한 행동 ##
- 설정한 포맷대로 화면에 표출

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/6723557/81376947-73345c80-913f-11ea-8e72-b26e0e96a98d.png)

![image](https://user-images.githubusercontent.com/6723557/81376937-6dd71200-913f-11ea-8eba-5cb1dd4c09ce.png)

**Comment by veldise** [comment]
버전 문제에 따른 것으로 생각됩니다.

**Comment by veldise** [comment]
수원시에 패치가 수행되었으므로 닫습니다.
