### ISSUE TITLE
메가 메뉴에서 하위 항목을 포함하는 메뉴 클릭 시 스타일 오류

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2169]
## 버그 설명 ##
메가 메뉴 스타일로 지정된 메뉴 항목에서 하위 항목이 있는 경우
해당 항목을 클릭 시, 오른쪽으로 하위 메뉴가 계속 추가 되는 구조인데, 이때 스타일이 어긋남.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/11566844/81383751-851bfc80-914b-11ea-8e0b-fd8a1d8dcd92.png)
![image](https://user-images.githubusercontent.com/11566844/81383776-9402af00-914b-11ea-8cbd-976994df8d0b.png)

**Comment by lyj** [comment]
확인중입니다.

**Comment by lyj** [comment]
적용후 배포되었습니다.
