### ISSUE TITLE
[수원시] 시각화 - 꺾은선형 다중 차트 요구사항

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#2171]
## 기능 요청 ##
시각화 - 꺾은선형 - 다중차트에서 Y축이 늘어남에 따라 여러 그래프가 생기게 되는데, 
수원시 주무관의 요청은 그래프가 늘어남에 따라 어떤 것을 추가 했는지 명확하게 보였으면 하는
것입니다.
## 원하는 솔루션 설명 ##
그래프에 Y축 설정을 한 것을 좀더 명확하게 보였으면 합니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
![요구사항2](https://user-images.githubusercontent.com/8993205/81534211-9f9be300-93a2-11ea-9ff9-34a8b0833fce.PNG)

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
