### ISSUE TITLE
[공통-긴급요청] Analyzer, Studio 에서 데이터모델의 컬럼이름을 쉽게 복사해서 검색어창에 붙여넣기 하고 싶습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2173]
## 기능 요청 ##
[공통-긴급요청] Analyzer, Studio 에서 데이터모델의 컬럼이름을 쉽게 복사해서 검색어창에 붙여넣기 하고 싶습니다.
Analyzer 는 데이터모델의 필드pane 에서  컬럼이름 복사가 안됩니다. (컬럼 클릭 이벤트 기능이 있음)
Studio 에서 검색어 창에 DSL 을 넣을 때 Analyzer 화면을 참조해서 만드는데, 컬럼 이름 복사가 안되기 때문에
모든 컬럼을 한번은 다 불러와서 테이블을 보던지
데이터모델 메뉴 TAB 을 하나 더 띄워서 보고 있습니다.
컬럼 이름이 비슷하면서 매우 긴게 많아서 일일이 **컬럼이름 복사** 기능은 빨리 필요합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by joohj7** [comment]
#2255 #2148
