### ISSUE TITLE
[수원시] 시각화/분석에서 긴 시간 작업 하지 않다가 재작업시 에러 발생

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#2174]
## 버그 설명 ##
수원시 2020.05.08.(금) 기준,
[수원시] 시각화/분석에서 긴 시간 작업 하지 않다가 재작업시 에러 발생

## 재현하는 방법 ##
시각화 분석 진행.
결과 화면 이후 아무 작업을 하지 않은 상태로 그대로 유지. 5~10분 정도

이후 다른 데이터 모델 선택/분석 재시작 등의 일련의 과정 시 에러 발생

## 예상한 행동 ##
정상 분석.

## 스크린샷 ##
![버그2](https://user-images.githubusercontent.com/8993205/81540471-ad566600-93ac-11ea-8c39-6d0536fbfd06.jpg)
![버그1](https://user-images.githubusercontent.com/8993205/81540476-ae879300-93ac-11ea-9564-88ff087b513a.jpg)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
1번째 에러는 최근 Angora - IRIS 웹 서버간 토큰 처리에 예외처리가 덜 되어있어서 발생한 문제와 같은 문제로 보입니다. 5/14 패치로 해결될 것으로 생각됩니다.

@seungfwani 
2번째 스크린샷 에러가 어떤 상황에서 반환되는 에러인지 코멘트를 부탁합니다.
1번째 에러 후 발생한 에러라면 큰 문제는 아닐 것 같습니다.

**Comment by seungfwani** [comment]
2번째 스크린샷은,
DSL 로 앙고라에 질의시 앙고라는 `모델명` 과 `유저아이디` 를 통해 메타저장소에서 특정 데이터 모델에 대한 정보를 가져옵니다.
이때, 중복된 데이터 모델을 검색한 경우 발생한 에러입니다.

동일한 유저에 동일한 모델명으로 데이터 모델을 생성한 경우 발생하는 것으로,
동일한 유저에서는 모델명을 unique 하게 사용해야합니다.

**Comment by veldise** [comment]
@seungfwani 
잘 이해가 안 되는데
중복된 데이터 모델이 존재할 때, 해당 모델에 대하여 검색을 수행하면 발생한다는 말인가요?

**Comment by seungfwani** [comment]
@veldise 
말씀하신게 맞습니다.

UI 를 통해서 생성할 때는 동일 모델명이 존재 할때 예외처리가 되지만,
앙고라 api를 통해서 생성 하였을 때는 무조건 생성이기 때문에 발생한 문제입니다.

예상되는 경위는 아래와 같습니다.
1. 사용자가 앙고라 api 를 통해서 모델을 생성. (같은 유저, 같은 모델명 사용)
2. 해당 모델 검색시 에러발생
3. 사용자가 중복된 모델 중 1개 삭제
4. 현재 정상 동작

**Comment by veldise** [comment]
@readmehong 
홍준표 책임님, 위 설명대로 수원시 IRIS에 아래 예시처럼 중복된 이름을 가진 데이터 모델이 있는 것 같습니다. 확인이 필요합니다.

|데이터 모델명 | 소유자|
|-------|--------|
|abc|user1|
|abc|user1|
|ddd|user1|

**Comment by readmehong** [comment]
@veldise 
네 중복된 데이터 모델 일괄 검색하여 제거하는 과정 거친 후 정상 동작 확인 했습니다.

**Comment by veldise** [comment]
첫번째 에러는 패치로 해결되었을 것으로 기대하고, 2번째 에러는 해결되었으므로 닫습니다.
