### ISSUE TITLE
[Studio] 편집할 때 챠트-테이블에서 마지막행으로 이동 시 보이는 현상 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2180]
## 버그 설명 ##
demo.iris.tools   /  root

Studio 에서 챠트 - 테이블
데이터모델 : population_for_motion
전체시간 

전체 건수는 7000 건 미만의 데이터입니다.

*  결과
<img width="1102" alt="스크린샷 2020-05-12 오후 4 31 18" src="https://user-images.githubusercontent.com/5126497/81652030-194cd300-946e-11ea-9cbe-8d0b9ad9631b.png">

* 맨 끝으로 이동시
<img width="1108" alt="스크린샷 2020-05-12 오후 4 31 26" src="https://user-images.githubusercontent.com/5126497/81652079-22d63b00-946e-11ea-9cfb-b53fd091f110.png">

이상한 문자가 보입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
문제가 발생하는 부분은 차트-테이블 UI 내 Pagenation 컴포넌트로,
숫자 4자리 이상부터 문제가 발생하는 것으로 파악됩니다.

@youngjiring
