### ISSUE TITLE
[Studio] 모션 챠트에 범례 또는 툴팁이 없어서 원이 어떤 그룹값인지 알 수 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2181]
## 기능 요청 ##
Studio 의 모션챠트 시각화옵션에 범례와 툴팁을 추가해주세요.

챠트의 원이 어떤 아이템(그룹 변수)인지 알 수 없습니다.

<img width="187" alt="스크린샷 2020-05-13 오전 7 59 45" src="https://user-images.githubusercontent.com/5126497/81753876-bdc32980-94ef-11ea-88a4-d75cea9f4f14.png">

<img width="851" alt="스크린샷 2020-05-13 오전 7 57 58" src="https://user-images.githubusercontent.com/5126497/81753770-7fc60580-94ef-11ea-802a-5872451827e4.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@seoryjj 
IRIS의 모션 차트는 '그룹' 설정에 따라 각각의 원이 모두 다른 변수값입니다. (ex) 국가코드)
scatter plot과 같이 두개 이상의 원이 같은 그룹이면 범례가 유의미하겠지만, 이 경우에는 적절하지 않다고 생각됩니다.

다만 말씀하신대로 각 원이 어떤 그룹인지 알 수가 없으므로 아래와 같이 원에 레이블을 추가하는 옵션을 검토해볼 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/81756469-ccf9a580-94f6-11ea-8337-b05319d19edd.png)

마지막으로, 마우스오버시 툴팁은 있습니다. 혹시 툴팁이 나오지 않는 것이라면 추가 코멘트를 달아주세요.

**Comment by seoryjj** [comment]
툴팁이   나오지 않고, 또 시각화옵션에도 툴팁 지정하는 게 없습니다

**Comment by veldise** [comment]
@seoryjj 
지금 확인해보니 툴팁은 나옵니다. 재현 방법을 알려주시면 감사하겠습니다.
참고로 모션 차트 툴팁 관련해서, 위치 버그가 있습니다. #2026

**Comment by sunghoon** [comment]
@seoryjj 추가 의견 바랍니다.

**Comment by seoryjj** [comment]
- 툴팁 위치 문제는 수정되어서 툴팁이 보입니다.

- 모션챠트는 범례 및 축 제목을 표시할 수 없어서 X 축이 무슨 값인지, Y 축이 무슨 값인지 알 수 없습니다.
모션챠트에도 축제목, 범례 등을 설정하는 기능이 필요합니다.
<img width="739" alt="스크린샷 2020-11-10 오전 10 54 38" src="https://user-images.githubusercontent.com/5126497/98617933-76551300-2343-11eb-82ec-e8e26c06b1b2.png">

**Comment by sunghoon** [comment]
@veldise 최종 이슈 내용 확인 및 조치를 위한 일정 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
답변이 늦어서 죄송합니다. 2020-12-03 패치로 툴팁 위치 버그는 해결되었습니다.
https://github.com/mobigen/IRIS/issues/34
https://github.com/mobigen/IRIS-BigData-Platform/wiki/2020-12-03---Patch

![image](https://user-images.githubusercontent.com/3411842/105922617-54377b00-607e-11eb-84db-6675c71a90f1.png)
