### ISSUE TITLE
[Studio] 히트맵,시계열챠트 등을 그리기 위해 데이터탭에서 실행하기를 누른 후 시각화탭에서 챠트선택하면 무응답/대기팝업

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2182]
## 버그 설명 ##
1. Studio 에서 데이터 선택 후 실행 ( 약 16000 건 )
2. 시각화 탭에서 테이블로 데이터 확인 후 히트맵/모션챠트/시계열챠트 등 을 클릭하면 한참동안 응답이 없습니다.
     이 때는 중지 버튼도 동작하지 않고,
     한 참후에 이런 탭이 뜹니다.
<img width="1429" alt="스크린샷 2020-05-13 오전 9 34 00" src="https://user-images.githubusercontent.com/5126497/81758754-b1de6400-94fd-11ea-9811-d6bc96ec2ae5.png">

* 예상은 챠트의 시각화옵션에서 변수를 지정하기 전에 디폴트로 설정된 변수로 챠트를 만드려고 시도하는 것 같습니다.
* 한참 기다리면 챠트가 나오는데....  특정 변수에 숫자로 된 측정값이 있을 때, 이 값들을 하나하나 모두 그룹 변수처럼 만들어서 (범례수 최대치가 나오겠죠) 챠트를 그리더군요. 
* 예상은 디폴트설정이 "모두선택" 으로 되어 컬럼을 사용자가 지정도 하기 전에  모든 변수를 챠트로 그리려고 시도하는 것 같습니다.

<img width="858" alt="스크린샷 2020-05-13 오전 9 46 32" src="https://user-images.githubusercontent.com/5126497/81759069-a5a6d680-94fe-11ea-9f61-9218572602ef.png">

* 이건 한참 기다렸다 나온 건데, 시각화탭에서 히트맵을 클릭하자마자 중지 버튼도 안 먹히고,  팝업에서 "대기" 를 누르면 10분후 나온 결과입니다. 전체 컬럼을 다 그린 거라 의미가 없습니다....  

<img width="214" alt="스크린샷 2020-05-13 오전 9 48 51" src="https://user-images.githubusercontent.com/5126497/81759186-fc141500-94fe-11ea-8b19-3891e38e76a9.png">

* 히트맵은 숫자가 아닌 컬럼 station 도 챠트로 그렸고, 시각화옵션에는 No 라는 컬럼 하나 만 지정되어 있네요.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
1. 수행하신 데이터 모델 / 시간 범위 / 검색어 등을 첨부해주시면 보다 빨리 문제를 파악할 수 있습니다.
2. 차트를 그릴 때 차트의 드로잉 객체(히트맵의 경우 칸)가 1만개가 넘어가게 되면 브라우저에 심각한 부하가 발생하여 본문 스크린샷과 같이 '응답없음' 상태가 될 수 있습니다.

**Comment by rhcpn** [comment]
해당 기능은 5월 ~ 6월 사이 시각화 컴포넌트에서 데이터 통신 기능을 분리하는 업데이트를 진행할 예정인데 해당 시점에 처리하는걸로 하겠습니다.

**Comment by swish1995** [comment]
해당 기능은 boost mode 설정으로 해결되었으므로 닫습니다.
