### ISSUE TITLE
[IRIS Discovery] fields 명령어에 as 구문 추가

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2185]
## 기능 요청 ##
향후 fields dsl 이 sql dsl 을 대치하려면
fields 구문에서 
sql "select ddhdaaa as 개발자, hhhdddaaa as 수행자 where ..."
에서처럼 as 에일리어스 기능이 필요합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
fields 명령어로 alias 를 할 수 있도록 옵션을 추가하였습니다.

사용법:
```
fields 필드명 as 필드명별명, 필드명2  as 필드명 별명2
```

명령어 문서:
http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/fields.html

![Screen Shot 2020-05-13 at 6 40 36 PM](https://user-images.githubusercontent.com/46172579/81797108-4de18d00-9549-11ea-8f2a-a84428bc2fbe.png)
