### ISSUE TITLE
[Studio] 챠트-테이블 에서 검색 필터시 조회결과 레코드가 일부만 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2187]
## 버그 설명 ##
demo.iris.tools
보고서 : 이슈 카테고리 Studio예제_테이블에러

* 실제 hadoop02  는 11개 레코드 수입니다.
<img width="252" alt="스크린샷 2020-05-13 오후 3 09 33" src="https://user-images.githubusercontent.com/5126497/81777574-17494980-952c-11ea-8214-ab70a91c061b.png">

* 테이블 결과에서 검색 필터 시에는 6건만 나옵니다.
<img width="1193" alt="스크린샷 2020-05-13 오후 3 09 49" src="https://user-images.githubusercontent.com/5126497/81777615-347e1800-952c-11ea-9d14-9e5d4809c722.png">
<img width="1193" alt="스크린샷 2020-05-13 오후 3 10 03" src="https://user-images.githubusercontent.com/5126497/81777618-3647db80-952c-11ea-8510-be423f8b340b.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
테이블 검색시 UI에서 데이터의 개수를 `1만개` 만 가져오도록 설정이 되어있습니다.

`hadoop02`의 값이 전체데이터에는 `11개` 가 있지만, `1만개` 데이터 안에는 `6개`만 존재하는 것으로 보입니다.

![Screen Shot 2020-05-13 at 5 55 07 PM](https://user-images.githubusercontent.com/46172579/81792386-f04a4200-9542-11ea-8a54-9cb716d54c50.png)

**Comment by veldise** [comment]
@seoryjj 
조금 더 보충하자면, 테이블 UI의 필터 입력란은 "결과 내 재검색" 과 유사하다고 생각하시면 됩니다.
#2108 유사 이슈입니다.
