### ISSUE TITLE
[IRIS DB] full text search index 설정과 사용법에 대한 매뉴얼 작성

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2188]
## 기능 요청 ##
아래 기능에 대한 매뉴얼이 필요합니다.

* IRIS DB 에서 
- full text index 설정하는 법
- full text search 하는법 (예제 sql 등)

* IRIS Analyzer 에서 
- full text index 가 동작하도록 "모델" 만드는 법
- full text search 하는법 (예제 sql, dsl 등)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 최종 상태 확인 해 주시기 바랍니다.

**Comment by anhm** [comment]
# FTS 사용 방법

DSL 을 이용하여 FTS를 사용하기 위해서는 다음과 같은 조건이 만족되어야 합니다.

- IRIS-DB에서만 지원
    테이블 생성시 FTS 테이블로 생성을 진행해야 합니다.
    
- 데이터 모델을 생성시 `원시` 컬럼을 지정
    `원시` 컬럼에 지정된 컬럼을 기준으로 FTS 검색을 실행 합니다.
    
    
## 문법
- 원시 컬럼을 `PRDCTCLSFCNONM` 으로 지정

아래의 SQL의 경우 

```
select count(*)
from EPS.EPS_DATA_LOADER_TEST
where
```

부분은 생략함



### FTS 검색시

| 검색어         | DSL                 | SQL                                        | 건수  |
| -------------- | ------------------- | ------------------------------------------ | ----- |
| 원천초등학교   | ``` 원천초등학교``` | ```PRDCTCLSFCNONM match '원천초등학교'```  | 44    |
| 유지관리       | ```유지관리```      | ```PRDCTCLSFCNONM match '유지관리'```      | 61473 |
| 사업           | ```사업```          | ```PRDCTCLSFCNONM match '사업'```          | 47238 |
| 유지관리, 사업 | ```유지관리 사업``` | ```PRDCTCLSFCNONM match '유지관리 사업'``` | 2063  |
| 빅데이터       | ```빅데이터```      | ```PRDCTCLSFCNONM match '빅데이터'```      | 1995  |

### like 검색시

| 검색어         | DSL                                                          | SQL                                                          | 건수   |
| -------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------ |
| 원천초등학교   | ``` * \|where PRDCTCLSFCNONM like '%원천초등학교%'```          | ```PRDCTCLSFCNONM like '%원천초등학교%'```                   | 44     |
| 유지관리       | ``` *\|where PRDCTCLSFCNONM like '%유지관리%'```               | ```PRDCTCLSFCNONM like '%유지관리%'```                       | 82224  |
| 사업           | ``` *\|where PRDCTCLSFCNONM match '사업'```                 | ```PRDCTCLSFCNONM match '사업'```                            | 438845 |
| 유지관리, 사업 | ``` *\|where PRDCTCLSFCNONM like '%유지관리%' and PRDCTCLSFCNONM like '%사업%' ``` | ```PRDCTCLSFCNONM like '%유지관리%' and PRDCTCLSFCNONM like '%사업%'``` | 5560   |
| 빅데이터       | ``` *\|where PRDCTCLSFCNONM match '빅데이터'```                | ```PRDCTCLSFCNONM like '%빅데이터%'```                       | 2603   |
