### ISSUE TITLE
그리드 테이블 차트의 선택 row의 값이 비어져 있을경우 값 할당 안됨

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2189]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
![image](https://user-images.githubusercontent.com/16331916/81878907-3f848700-95c4-11ea-8e3d-4f329c8712d9.png)

 concat을 이용해서 그리드 테이블 차트의 선택 row를 모두 뽑아내서 변수에 할당하고 있습니다.

그림으로 설명드리면 area_8 은 선택된 row의 값을 val1,val2,val3,... 형태로 내보냅니다.

그런데, 값이 비어져 있을때 val1, val2, , , , 이런식으로 나와야 하는데, 아예 concat 결과 자체가 빈 String 또는 Null이 나오는듯 합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@kim3163 
시각화 탭에 아래 설정을 어떻게 하셨는지 첨부를 부탁드립니다.
참고로 "차트의 선택 row를 모두 뽑아내서 변수에 할당" 이라고 하셨는데 Studio UI에는 현재 그런 기능이 없습니다.

![image](https://user-images.githubusercontent.com/3411842/81879677-65ab2680-95c6-11ea-8e91-627e2bad6702.png)

**Comment by kim3163** [comment]
@veldise 
기능이 없어서 concat 함수를 이용해서 모든 필드의 값을 채우고, 그 값을 값 필드에 넣고 있는데,
concat 함수의 파라미터에 null 이 들어가면 concat 함수 자체가 null을 반환하는 듯 보입니다.
보고서 쪽 버그는 아닌 것으로 보여서, 서버쪽으로 문의 드렸습니다.

**Comment by veldise** [comment]
@kim3163 
아, 제가 착각한거군요. 그러면 "데이터 모델"로 하셨는지, "DSMS"로 하셨는지 추가로 적어주시면 좋을 것 같습니다.

**Comment by veldise** [comment]
@anhm @seungfwani

**Comment by seungfwani** [comment]
@kim3163 

보고서에 작성된 것을 검색 후, 15번 row를 클릭하니 변수자체에는 할당이 되는 것 처럼 보입니다.

테스트 방법이 잘못된 걸까요?

![Screen Shot 2020-05-14 at 1 26 36 PM](https://user-images.githubusercontent.com/46172579/81892639-913e0900-95e6-11ea-95cd-5eefa8aec365.png)

**Comment by kim3163** [comment]
@seungfwani 안형민 책임님에게 문의 후 수정했습니다.

감사합니다.

**Comment by seungfwani** [comment]
@kim3163 

이슈 닫도록 하겠습니다.
관련 이슈 발생시 언제든지 재 오픈 하시면 됩니다.
