### ISSUE TITLE
교통빅데이터플랫폼 / 모니터링 대시보드 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2192]
## 버그 설명 ##
메인대시보드에 IRIS 장애가 표현되지 않음

## 재현하는 방법 ##
https://180.148.181.193/ 접속 하여 대시보드 확인

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/81911316-1be33000-9608-11ea-9123-3a951a3ed573.png)

![image](https://user-images.githubusercontent.com/4444717/81911484-577dfa00-9608-11ea-87d0-942d11ca49fc.png)

![image](https://user-images.githubusercontent.com/4444717/81911401-387f6800-9608-11ea-8707-ed4b520ae8c7.png)

**Comment by veldise** [comment]
DB 조회 화면에서 `.node list` 수행했을 때 결과는 정상입니다.
UI에서 히트맵을 갱신하는 부분에 버그가 있는 것 같습니다.
