### ISSUE TITLE
외부 URL 실행시 배경색 및, 이미지 제거기능

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2194]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.

 외부 URL을 현재 추가하여 실행시 배경이 Default로 회색인 것으로 보이고 변경이 되지 않습니다.

또한 링크설정된 듯 한 이미지가 박혀있습니다.

1. 배경의 색상을 Default로 색상 없음으로 하고 Web 페이지를 개발한 곳에서 반영할 수 있게 하던지,

아니면 배경 색상을 변경할 수 있으면 좋겠습니다.

2. 링크 설정된 듯한 이미지는 없애는게 맞다고 생각됩니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.
![image](https://user-images.githubusercontent.com/16331916/82001267-c190b080-9695-11ea-9b38-751ff970c9f2.png)

**Comment by veldise** [comment]
@youngjiring 
![image](https://user-images.githubusercontent.com/3411842/82001513-48de2400-9696-11ea-83e5-735c7330bc0d.png)
