### ISSUE TITLE
Studio/ 시각화 유형 중 '트리맵'에는 데이터 표시 색상이 다른 컴포넌트랑 다르게 적용되어 있습니다. 

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2197]
Studio/ 시각화 유형 중 '트리맵'에는 데이터 표시 색상이 다른 컴포넌트랑 다르게 적용되어 있습니다. 
통일된 인터페이스가 적용되면 좋을 것 같습니다. 

![스크린샷 2020-05-15 오후 5 07 34](https://user-images.githubusercontent.com/512653/82027228-dc334b80-96ce-11ea-8d7d-9b45a2c4f593.png)

![스크린샷 2020-05-15 오후 5 09 45](https://user-images.githubusercontent.com/512653/82027240-e1909600-96ce-11ea-852d-559d0464629b.png)

**Comment by veldise** [comment]
@sunghoon 
현재 버전에서 트리맵은 히트맵과 동일하게 지정된 "데이터 표시 색상"을 기준으로
그라데이션 형태로 값의 크기를 나타내도록 개발되었습니다.

본문 내용처럼 변경한다면 기획 검토가 필요합니다.

**Comment by sunghoon** [comment]
히트맵으로 볼때와 다른 챠트랑 연계 해서 볼때랑 용도에 따라 표현법이 필요해 보입니다. 
지금을 기본으로 하면서 필요시 다른 챠트와 연결해서 시각적으로(같은색) 참조하는 경우도 있는것 같으니
낮은업무 순위로 천천히 진행해 주시기 바랍니다.
