### ISSUE TITLE
File 브라우저 / 엑셀파일 업로드가 되지 않습니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2203]
선택된 파일을 업로드 하면 종료되었다고 나오는데.
![스크린샷 2020-05-18 오전 11 59 09](https://user-images.githubusercontent.com/512653/82170360-2569e200-98ff-11ea-907d-a1e8c222762e.png)

팝업창을 닫고 '새로고침'을 해도 업로드한 파일이 보이지 않습니다.
![스크린샷 2020-05-18 오전 11 59 13](https://user-images.githubusercontent.com/512653/82170379-361a5800-98ff-11ea-8dad-367226887c75.png)

**Comment by veldise** [comment]
@sunghoon 
그리드뷰 왼쪽 위 필터 입력란에 `hoon`이 입력되어 있어서 나타나지 않는 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/82173518-821dca80-9908-11ea-9c57-ecd33c448c2e.png)

root 유저로 업로드하신게 맞다면 정상이고, hoon 유저로 업로드하셨따면
소유자/그룹 처리하는 부분에 버그가 있는 것 같습니다.

**Comment by sunghoon** [comment]
네. 확인하였습니다.
