### ISSUE TITLE
IRIS DB 매뉴얼 페이지를 못찾겠습니다.

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2205]
## 기능 요청 ##
IRIS 매뉴얼 페이지중에 이번에 리뉴얼 되면서, 기존 IRIS -DB 관련한 매뉴얼을 못차겠습니다.

IRIS DB Schema edit 명령어 등 관련한 페이지를 못찾겠는데요. 

내일 작업관련하여 table edit 해놔야하는데, 어디에 있는지 확인부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by EricLeeMbg** [comment]
docs.iris.tools 사이트의 Manual에서 아래와 같이 확인하실 수 있습니다. 
![image](https://user-images.githubusercontent.com/44352311/82181594-cd8ea380-991d-11ea-8393-e72ac6890fb5.png)

SaaS의 경우 현재 IRIS DB가 제공되지 않아 disable했던 메뉴항목이며, 요청에 따라 reopen해 드렸습니다.
