### ISSUE TITLE
[수원시] IRIS - 시각화/보고서 - map 의 다음 카카오 맵 지원

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#2206]
## 기능 요청 ##
수원시 주무관의 요청으로 네이버맵 지원과 같이 다음 카카오맵 지원을 요청

## 원하는 솔루션 설명 ##
시각화/보고서 - map의 다음 카카오맵 사용

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈 상태를 공유해 주세요.
