### ISSUE TITLE
[수원시] 보고서 접근 권한 그룹 설정 추가 요청

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2207]
## 기능 요청 ##
- 이전 요청(#2156 )에 대해서 수원시 기능으로 role 그룹에 해당하는 groupid2에 대해서는 처리가 되는 것 같지만 사용자가 속한 조직에 대한 정보인 groupId에 대해서는 적용이 되지 않음
- role groupId(groupId2)만이 아니라 조직에 해당하는 groupId에 대해서도 접근 권한이 동작되도록 요청

**Comment by veldise** [comment]
@AliceLiddell 
확인 결과 최신 버전 코드를 병합하는 과정에서 Acl API 쪽에서 `groupId2` 처리 내용이 누락되었습니다.

본문 내용과는 반대로 `groupId`가 아니라 `groupId2`가 누락된 상태로 파악되는데,
정확히 다시 확인을 부탁드립니다. 패치는 운용기술연구팀 쪽에 문의하겠습니다.

**Comment by veldise** [comment]
@AliceLiddell 
혹시 `groupId`은 없는데, `groupId2`만 있는 경우도 있습니까?

**Comment by AliceLiddell** [comment]
@veldise 지금 병원이라 사무실 들어가면 확인해보겠습니다만 groupid는 없이 groupid2만 있는 경우는 없습니다. 그래도 한번 다시 확인하고 코멘트 달겠습니다.

**Comment by AliceLiddell** [comment]
@veldise 토큰을 확인했는데 groupId와 groupId2 둘 다 정상적으로 전달되고 있습니다. groupId에는 사용자가 속한 조직으로 groupId2로는 role 그룹으로 토큰이 생성되어서 iris analyzer에 쿠키로 담기게 됩니다. 적어놓으신 케이스로서 3번에 해당하고 있는데 groupId 부분이 동작하지 않고 있습니다.

**Comment by veldise** [comment]
@AliceLiddell 
확인 결과 Studio 에서만 `groupId2`를 `groupId`로 처리하고 있었습니다. 불편을 끼쳐드려 죄송합니다.

**Comment by veldise** [comment]
6/4(목) 패치로 해결되었을 것으로 보고 닫습니다.
혹시 해결이 안 되었다면 Reopen 및 코멘트 남겨주시기 바랍니다.
