### ISSUE TITLE
[수원시] 데이터 모델, 보고서 접근 관리 시 브라우저 프리징 현상 발생

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2208]
## 버그 설명 ##
- 수원시 기준 사용자 약 5천명, 조직 약 900개가 되는 상황
- 보고서, 데이터 모델에서 접근 권한 팝업을 띄워서 적용할 때 사용자 정보, 그룹 정보가 많은 상태에서 처리하면 해당 페이지가 멈춰버리는 현상이 빈번하게 발생(금일 테스트에서는 매번 발생하였음)
- 사용자나 그룹 정보를 전부 가져와서 처리하는 부분 때문에 발생하는 것 같은데 해당 기능을 server pagination 같은 식으로 변경 요청

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@AliceLiddell 
현재 저희 업무량/일정상 차주에야 해당 문제 해결을 진행할 수 있을 것 같습니다. 혹여 빠른 해결이 필요하시면 댓글 남겨주시기 바랍니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈 최종 상태 어떻게 되나요? 마일스톤에서 이슈를 찾을 수 없습니다.

**Comment by veldise** [comment]
@sunghoon 
해결에 어려운 점이 많아 개발 대기 상태입니다.

**Comment by sunghoon** [comment]
@veldise 개발 관련 이슈 사항이 무엇인지 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
UI에서 해당하는 부분에 virtual-scroll 을 적용해야 하는데
virtual-scroll 기능을 제공하는 ag-grid를 적용하려면 해당 부분의 디자인/퍼블리싱을 처음부터 다시 해야 합니다.

**Comment by sunghoon** [comment]
@veldise virtual-scroll 기능을 잘 활용하기 위해서 이슈 보고자가 ' server pagination' 방식으로 처리 할 수 있는지 문의 하였습니다. 
UI의 ag-grid / 디자인 이라기 보다는 backend 쪽에서 어떻게 처리 할 것인지 기준으로 검토 후 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
네, 서버에서 page 기능 제공하면 infinite scroll 방식으로도 할 수 있습니다.
그런데 infinite scroll 도 적용하려면 virtual-scroll 처럼 ag-grid를 적용하는 것이 좋습니다.
그리고 Analyzer의 데이터 모델 목록에서도 같은 문제가 발생하고 있기 때문에, server pagination 방식으로 처리하려면 angora API 에서도 해당 기능을 제공해야 합니다.
따라서 가능하면 virtual-scroll 방식으로 처리하는 것이 바람직하다고 생각합니다.

혹시 제가 virtual-scroll, infinite scroll 기술에 대해서 오해하고 있는 사항이 있다면 댓글 부탁드립니다.

**Comment by sunghoon** [comment]
관련 기능을 개선 하는 것으로 결정하겠습니다.
- UI Front/Backend 쪽에서는 권한 설정과 관련된 List 창 및 서버쪽 데이터 전달 방식을 (전체 혹은 페이징을 할 수 있도록 개선)
- Discovery 쪽에서는 모델 리스트 정보 전달을 전체 혹은 페이징으로 전달 할 수 있도록 개선
