### ISSUE TITLE
[수원시] 데이터 모델, 보고서 접근 관리 시 사용자 정보 표시 부분에 사용자 이름, 그룹 이름 표시 요청

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2209]
## 기능 요청 ##
- 데이터 모델, 보고서 접근 관리 화면에서 사용자 정보 표시에서 현재 아이디만 표시되는 것을 사용자 이름 및 해당 사용자가 소속된 그룹 이름까지 표시되도록 요청

**Comment by veldise** [comment]
@AliceLiddell 
아래와 같이 변경을 원하시는 정확한 포맷을 알려주세요.

ex) 
```
최영철 (choidev33, UI솔루션연구팀)
```

**Comment by AliceLiddell** [comment]
@veldise 포맷을 정해서 다시 코멘트 달겠습니다

**Comment by AliceLiddell** [comment]
@veldise 예시로 들어주신대로 해주시면 되겠습니다. 이름 (아이디, 부서) 이런 형태로

**Comment by veldise** [comment]
@AliceLiddell 
저도 깜빡한 부분인데, 부서가 `groupId`에 해당하나요, 아니면 `groupId2`에 해당하나요?

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/82514082-ab7c6780-9b4f-11ea-8340-5692666139c1.png)

![image](https://user-images.githubusercontent.com/3411842/82514025-8daf0280-9b4f-11ea-920d-2c0fee2f2344.png)

**Comment by AliceLiddell** [comment]
@veldise 앗 좌상단의 사용자 정보가 아니라 접근권한 팝업에서의 사용자 정보에서입니다.
![image](https://user-images.githubusercontent.com/6723557/82536194-11cead80-9b83-11ea-9da3-3e0ad8f793b8.png)
여기서의 정보인데 혹시 해당 팝업에서도 같은 포맷이 적용된다면 맞긴 한데 확인차 이미지 첨부하여 댓글 추가합니다.

**Comment by veldise** [comment]
@AliceLiddell 
제가 착각을 했군요. 기존 작업은 취소하겠습니다. 아래와 같이 하면 될까요?

![image](https://user-images.githubusercontent.com/3411842/82536573-9d483e80-9b83-11ea-8b55-17aa0cc8569a.png)

**Comment by AliceLiddell** [comment]
@veldise 아 네 맞습니다. 그런데 기존 작업도 없애지는 말고 같이 적용 부탁드립니다. 이슈를 따로 따야한다면 다른 이슈로 등록을 하겠습니다.

**Comment by veldise** [comment]
@AliceLiddell 
알겠습니다. 다만 권한 설정은 작업에 시간이 조금 더 걸립니다.

**Comment by veldise** [comment]
6/4(목) 패치로 해결되었을 것으로 보고 닫습니다.
혹시 해결이 안 되었다면 Reopen 및 코멘트 남겨주시기 바랍니다.
