### ISSUE TITLE
매뉴얼 Off line 버전 필요

### ISSUE THREAD

**Issue by lunamay** [mobigen/IRIS-BigData-Platform#2211]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.
온라인 매뉴얼이 지원되지 못하는 환경 및 제출용 off line(워드!) 매뉴얼 필요

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
온라인 매뉴얼이 지원되지 못하는 환경 및 제출용 off line(워드!) 매뉴얼 필요

## 고려한 다른 대안 ##
온라인 매뉴얼이 지원되지 못하는 환경 및 제출용 off line(워드!) 매뉴얼 필요

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@lunamay PDF 버전으로 제공할 예정입니다.

@EricLeeMbg 메뉴얼 PDF 버전을 생성해서 SaaS 홈페이지의 다운로드 메뉴에서 
사용자들이 필요한 기능의 메뉴얼을 다운로드 받을 수 있도록 조치해 주시기 바랍니다.

**Comment by EricLeeMbg** [comment]
확인 후 조치하겠습니다.

**Comment by EricLeeMbg** [comment]
![image](https://user-images.githubusercontent.com/44352311/82960075-567b9e00-9ff4-11ea-8112-0462d450e296.png)
iris.tools -> 지원 -> 다운로드 메뉴를 선택하시면 IRIS Studio에 대한 pdf 매뉴얼을 다운로드 받을 수 있습니다. 
지속적으로 docs.iris.tools의 매뉴얼을 pdf로 변경하여 등록할 예정입니다.
