### ISSUE TITLE
Studio: copy&paste 동작시 트리거 설정도 복사하도록 개선

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2213]
## 기능 요청 ##
Studio: copy&paste 동작시 트리거 설정도 복사하도록 개선

**Comment by sunghoon** [comment]
@veldise 본 이슈 최종 상태 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
개발 대기 상태입니다.

**Comment by sunghoon** [comment]
@veldise 작업을 위한 예상 작업 소요 시간과 개발 계획을 수립하여 알려주세요.
