### ISSUE TITLE
[NMS+]IRIS 클러스터 관리 화면 오류

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2216]
## 버그 설명 ##
클러스터관리 > 테이블스페이스(사용률조회) 화면에서
테이블을 클릭하고 조회하여 파일을 다운로드 받으면 다운로드 파일의 데이터가 조회내용이 아닌
다른 데이터가(테이블별이 아닌 전체 사용량이 나오는거 같네요 )  나옵니다.

![iris](https://user-images.githubusercontent.com/5468183/82398219-3f392f80-9a8d-11ea-93be-a6928b5e0016.PNG)

테이블별 일별 사용량을 제출해달라는 고객의 요청사항에 따라 해당데이터를 조회하고 싶습니다.

해당 기능 수정 및 반영하는 시간등이 소요되므로 
해당 화면에서 조회하는 메타데이터 DB 등이 있으면 알려주세요. 직접 데이터를 조회하여 
테이블별 일별 데이터 사용량을 뽑고 싶습니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
```
.statistics table --stime ${startDate} --etime ${endDate} -r 60 --summary --table ${tableName} --get-all
```

**Comment by jjinylee** [comment]
@anhm 

현재 의 IRIS 일별 테이블별 사용량 데이터를 뽑으려는데 클러스터 관리하면에서 csv 파일다운로드시 데이터가 잘못나오고 있습니다.

위의 명령어로 접근하는 테이블 ( 아마 SMS 에서 저장하고있을거같은데요 ) 정보를 알려주시면
테이블별 일별 데이터를 뽑고 싶습니다.

용도 : 고객이 일별 테이블별 용량 확인 요청으로 위의 기능이 오동작하므로 오류 수정되면  NMS+ 에 배포도 해야함으로 직접 접근해서 데이터를 뽑고 싶습니다.

확인 부탁드립니다.

**Comment by veldise** [comment]
@anhm 
위 다운로드 버튼에 매핑된 명령어는 아래와 같습니다.

```
.statistics table --stime ${startDate} --etime ${endDate} -r 60 --summary --table ${tableName} --get-all
```
