### ISSUE TITLE
Studio 탭 '적용대상' 으로 라벨 선택 안됨

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2217]
## 버그 설명 ##
이전에는 탭 객체의 '적용대상' 으로 라벨 선택이 가능 했었으나,
현재는 불가능.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 탭 / 라벨 객체 생성
2. 탭 클릭 후 '적용대상' 설정
3. 선택가능할것처럼 라벨에 체크박스가 표시되지만, 선택 불가능

## 예상한 행동 ##
탭 적용대상에 라벨 설정 가능.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3972489/82406626-15d6ce80-9aa2-11ea-9726-b31483d29c4c.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
@imdrak 라벨, 인폿, 텍스트도 동일하게 발생됩니다.

**Comment by swish1995** [comment]
처리되어 닫습니다
