### ISSUE TITLE
Studio 자동실행 안됨

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2219]
## 버그 설명 ##
자동 실행 옵션을 선택한 객체가 자동실행 되지 않음.
보고서명 : '나라장터 보고서 (최종) - 디자인 수정' 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 위의 보고서 명 클릭
2. '전체' 탭의 객체들이 표시되지 않음

## 예상한 행동 ##
자동실행 옵션을 선택한 객체가 표시됨.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3972489/82407725-e8d7eb00-9aa4-11ea-81ef-3170e14add7e.png)

자동실행 설정되어있음.
![image](https://user-images.githubusercontent.com/3972489/82408363-63edd100-9aa6-11ea-9f55-21b6d82117a3.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
Label 객체에서 코드 에러 발생으로 인한 버그입니다.

![image](https://user-images.githubusercontent.com/3411842/82409844-93eaa380-9aa9-11ea-9ea2-dbb9039df093.png)
