### ISSUE TITLE
Studio 라벨 객체 텍스트 입력 도중 'DEL'키 클릭시 객체가 삭제됨

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2220]
## 버그 설명 ##
라벨 객체 텍스트 작성시, 'DEL'키를 클릭하면 객체가 삭제됨.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 라벨 객체 생성.
2. 라벨 객체를 클릭해서 커서가 깜빡이는 상태로 변경.
3. 텍스트 입력 후 (혹은 입력하지 않은 상태에서) DEL키를 클릭하면 라벨 객체가 삭제됨

## 예상한 행동 ##
커서가 깜빡이는 상태일때 DEL키를 클릭하면 텍스트가 삭제된다.

## 스크린샷 ##
이 상태에서 DEL키를 클릭하면 객체가 삭제됨.
![image](https://user-images.githubusercontent.com/3972489/82425161-1b8fdc80-9ac1-11ea-9fa0-44c565ac383b.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
처리 확인되어 닫습니다.
