### ISSUE TITLE
[수원시] Qlik 툴 연동 요청

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#2221]
## 기능 요청 ##
수원시 빅데이터 분석 담당 주무관의 "Qlik" 툴의 IRIS 연동 요청이 있습니다.

## 원하는 솔루션 설명 ##
Qlik 의 분석 툴에서의 IRIS  데이터 연동을 통한 분석 

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
https://www.qlik.com/ko-kr

아래는 수원시의 qlik 접속 제공 리스트 입니다.

![qlik](https://user-images.githubusercontent.com/8993205/82428128-00bf6700-9ac5-11ea-97ed-05285d69932d.jpg)

**Comment by sunghoon** [comment]
@cosmos-mc 연동을 위한 메뉴얼 부탁드립니다.

**Comment by sunghoon** [comment]
프로젝트 담당자와 조치 완료가 확인되었습니다.
