### ISSUE TITLE
[수원시] 개인설정 - 표시의 소수점 자리수 default 변경

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#2223]
## 기능 요청 ##
IRIS 기본 소수점 자리수 표시가 "2"로 셋팅이 되어 있는데, 수원시의 경우 "0"으로 default로 셋팅 요청

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@readmehong 
기본값을 0으로 하면 실수값도 모두 소수점이 나오지 않게 될텐데 괜찮습니까?

**Comment by readmehong** [comment]
@veldise 네, 수원시는 기본값을 0으로 ㅇ하길 원했습니다.

**Comment by veldise** [comment]
지난주 목요일(6/4) 패치가 됐을 것으로 보고 닫습니다.
참고로 기존에 한 번이라도 로그인 한 사람은 쿠키를 지워야만 소수점 자리수 설정이 0으로 초기화됩니다.

해결이 되지 않았다면 Reopen 해주세요.
