### ISSUE TITLE
[수원시] 피벗 분석의 세로막대, 데이터막대 등의 시각화 변경이후 분석 설정이 풀려버림

### ISSUE THREAD

**Issue by readmehong** [mobigen/IRIS-BigData-Platform#2224]
## 버그 설명 ##
피벗 분석의 세로막대, 데이터막대 등의 시각화 변경이후 분석 설정이 풀려버림
--> 행/열/값 선택에 대한 2개 이상의 설정이 세로막대, 데이터 막대 등의 시각화를 한 이후 다시 표로 돌아오면 설정이 풀려 있음

## 재현하는 방법 ##
동작을 재현하는 방법 :
행/열/값 선택에 대한 2개 이상의 설정이 세로막대, 데이터 막대 등의 시각화를 한 이후 다시 표로 돌아오면 설정이 풀려 있음

## 예상한 행동 ##
지정한 설정은 그대로 남아 있음

## 스크린샷 ##
![피벗1](https://user-images.githubusercontent.com/8993205/82429284-990a1b80-9ac6-11ea-87c5-22b7b93cb12b.PNG)
![피벗2](https://user-images.githubusercontent.com/8993205/82429288-9a3b4880-9ac6-11ea-8f48-f0ff19423919.PNG)
![피벗3](https://user-images.githubusercontent.com/8993205/82429291-9ad3df00-9ac6-11ea-8232-9057d7d522a6.PNG)

위의 과정 이후 아래와 같이 되돌아 왔을 때 설정이 풀려 있음
![풀린상태](https://user-images.githubusercontent.com/8993205/82429495-f605d180-9ac6-11ea-83a9-6f9442f76505.PNG)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@readmehong 
피벗의 차트 유형들은 '행 선택', '열 선택'을 하나씩만 할 수 있습니다. (원형은 '행 선택'만 가능)
테이블 유형의 경우에는 '행 선택', '열 선택'을 여러개 할 수 있기 때문에 서로 맞지 않아,
유형 변경시에는 이 부분이 자동 변환되어 피벗을 수행하게 되어있습니다.

위 동작은 의도된 부분 입니다.

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
