### ISSUE TITLE
교통빅데이터 플랫폼/감사로그 조회 결과 없음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2225]
## 버그 설명 ##

교통빅데이터 플랫폼에서 감사로그 조회시 결과가 없는 것으로 출력됨
정상적으로 동작 하는지 확인 필요

## 재현하는 방법 ##
https://180.148.181.193/#/ 접속 후 감사로그 조회

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/82509751-c21cc180-9b43-11ea-97d5-4055e545c5bf.png)

**Comment by veldise** [comment]
@big-mobigen 
해당 사이트 brick, meta 서비스의 각각의 버전 정보와 서버 로그 확인을 요청합니다.

**Comment by sunghoon** [comment]
과거 특정 시점의 이슈 같아 보입니다. 닫습니다.

**Comment by JeongHeeDong** [comment]
현재도 접속해서 보면 로그가 조회되지 않고 있습니다.
혹시나 하여 diamonde계정으로 접속하여 검색,피벗 화면들을 실행해 보았으나, 감사로그 조회에서 나오지 않고 있습니다.

@권영길팀장님, 
brick, meta 서비스의 각각의 버전 정보와 서버 로그 확인을 요청 부탁드립니다.

**Comment by sunghoon** [comment]
@big-mobigen 
정희동 팀장님 요청 'brick, meta 서비스의 각각의 버전 정보와 서버 로그 확인을 요청 부탁드립니다.'
그리고 개인별 계정으로 이슈 대응 해 주시기 바랍니다.

**Comment by big-mobigen** [comment]
@veldise 
brick v0.1.9_dad2c93
meta v2.5_f158e84

MariaDB 에는 WAS.WAS_AUDIT_LOG 테이블 및

**Comment by veldise** [comment]
@big-mobigen 
brick `dad2c93a` 버전은 2월 버전으로 audit-log 와 관련된 기능이 포함되지 않은 버전입니다.
제가 요청했던 버전으로 배포가 되지 않았거나 과거 버전으로 롤백된 것 같습니다.
확인 후 재배포 부탁드립니다.

**Comment by big-mobigen** [comment]
@veldise 
일정 협의하여 brick 서비스 패치하도록 하겠습니다.
문의 사항으로,
해당 사이트는 도로공사 플랫폼 쪽 IRIS-WEB 입니다.
/root/iris-dist/diamond-e/platform/brick-diamond-e-v0.1.9_cfee213-20200327.tar.gz 파일이 아닌,
/root/iris-dist/diamond-e/openlab/brick-openlab_245c2da-20200713.tar.gz 
파일을 사용하여 패치해도 되는 것인지 문의 드립니다.

기존 구축시에 사용된 파일은 
brick-diamond-e-v0.1.9_dad2c93-20200217.tar.gz 으로 보입니다.
검토 부탁 드립니다.

**Comment by veldise** [comment]
@big-mobigen 
각각 다르게 버전을 관리하고 때문에 별도의 요청사항이 없으면 각각의 폴더 파일 버전으로 유지해야 합니다.
플랫폼 쪽은 3월 27일 `cfee213` 버전으로 배포하셔야 합니다.

**Comment by big-mobigen** [comment]
![image](https://user-images.githubusercontent.com/25650544/96080188-7c490700-0ef1-11eb-8a9a-a531ef9a16ee.png)

brick 버전 cfee213 으로 패치 후 audit 로그 조회되고 있음을 확인하였습니다.
이슈 close 하겠습니다.
