### ISSUE TITLE
UI 에러 팝업창이 뜨지 않는 이슈 - 알리바바클라우드

### ISSUE THREAD

**Issue by seungfwani** [mobigen/IRIS-BigData-Platform#2226]
## 버그 설명 ##
내용정리:
에러 팝업이 뜨지 않아 사용자 입장에서 에러 발생 후 동작을 진행 할 수 없는 이슈가 있습니다.

상황:
1. 데이터 모델 생성시 앙고라에서 데이터를 읽지 못해 에러 메세지를 응답.
2. 화면에서 에러메세지 팝업이 뜨지않음.
3. 이후 테이블을 바꾸거나 다른 동작이 불가능

사이트 : http://39.105.39.10

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 데이터모델
2. 새모델 생성
3. 선택 사항, 데이터소스: elasticsearch, 연결정보: 172.17.190.66-es, 테이블: chuyuan
4. 팝업메세지 뜨지않음.

## 예상한 행동 ##
에러 팝업창 나온 후 다음 동작 가능

## 스크린샷 ##
이슈상황 스크린샷:
![Screen Shot 2020-05-21 at 10 34 43 AM](https://user-images.githubusercontent.com/46172579/82513964-65bf9f00-9b4f-11ea-90f4-0db1bcdbbe90.png)
![Screen Shot 2020-05-21 at 10 34 54 AM](https://user-images.githubusercontent.com/46172579/82513968-69ebbc80-9b4f-11ea-95b3-9d429dcae417.png)

해당사이트 버전정보:
![Screen Shot 2020-05-21 at 10 42 04 AM](https://user-images.githubusercontent.com/46172579/82514106-bc2cdd80-9b4f-11ea-9b73-5a6fa4916268.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seungfwani 
이전에 말했던, 에러인데 HTTP StatusCode가 200 이어서 발생하는 문제입니다.

**Comment by seungfwani** [comment]
@veldise 
해당 내용이 공유가 된 적이 있었군요.
확인 해보겠습니다.

**Comment by seungfwani** [comment]
7/20일 배포를 통해 해당이슈는 해결되었습니다.
