### ISSUE TITLE
[Analyzer] sql 문으로 alias 컬럼을 만든 결과에서 sheet에 컬럼이름이 안보입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2227]
## 버그 설명 ##
demo.iris.tools  root계정

검색어

` *  | sql "select count(*) as PM2_5_daycount, avg(PM2_5) as 평균_PM2_5, max(PM2_5) as 최대_PM2_5 from angora where month = 1 and PM2_5 >= 75 " `

sql  로 새로 만든 PM2_5_daycount, 평균_PM2_5, 최대_PM2_5   컬럼이 왼쪽 필드에는 보이는데,
검색 결과  sheet에는 보이지 않습니다.

![이슈1 ng](https://user-images.githubusercontent.com/5126497/82524519-25b9e580-9b6a-11ea-8543-9eabeb28edaf.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
MacOS 10.13, 구글 크롬 및 사파리 브라우저에서 재현되지 않습니다.
사용하고 계신 OS와 브라우저 정보를 코멘트로 달아주세요.

**Comment by veldise** [comment]
#2341 과 유사한 문제로 패치 이후 해결된 것으로 보고 닫습니다.
