### ISSUE TITLE
Studio 메시지 리소스 변수 치환 문제

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#2228]
## 개요
메시지 리소스에 변수 치환하는 부분에 여러가지 유형의 문제가 있습니다.

## 내용
* 대소문자 문제
![스크린샷 2020-05-21 오후 1 56 58](https://user-images.githubusercontent.com/5515493/82525316-0459f900-9b6c-11ea-9537-fc3f125c0851.png)

* ```"``` 이 잘못 들어가있는 문제
![스크린샷 2020-05-21 오후 2 01 05](https://user-images.githubusercontent.com/5515493/82525384-32d7d400-9b6c-11ea-9d8a-b81cc4a9240d.png)

* ```$``` 다음 빈 공간 문제
![스크린샷 2020-05-21 오후 2 01 19](https://user-images.githubusercontent.com/5515493/82525467-687cbd00-9b6c-11ea-933a-69ca22bc74e0.png)

* ```\ n``` 역슬레시 다음 빈칸이 있는 문제
![스크린샷 2020-05-21 오후 2 01 29](https://user-images.githubusercontent.com/5515493/82525498-7e8a7d80-9b6c-11ea-93a5-3ed1b159269d.png)

* 변수 치환 누락 및 변역이 잘 못된 문제
![스크린샷 2020-05-21 오후 2 01 46](https://user-images.githubusercontent.com/5515493/82525540-97932e80-9b6c-11ea-86a4-a46b07f1ca60.png)

* ```"```이 잘 못 들어가 있는 문제
![스크린샷 2020-05-21 오후 2 02 09](https://user-images.githubusercontent.com/5515493/82525597-b98cb100-9b6c-11ea-86a5-7f3d77d8089c.png)

현재까지 발견한 유형은 여기까지 입니다.

이후 더 발견 된다면 이슈 내용에 추가해주시길 바랍니다.

**Comment by tylor-kr** [comment]
\nex) -> /NEX)
![image](https://user-images.githubusercontent.com/13827425/85820652-a7c4ac00-b7b1-11ea-97a8-a9581de978aa.png)

**Comment by tylor-kr** [comment]
br 태그 관련
![image](https://user-images.githubusercontent.com/13827425/85820796-02f69e80-b7b2-11ea-8a1f-d2d4f913be09.png)
