### ISSUE TITLE
Studio: Chart / sankey 차트 실행 후 저장시 코드 에러 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2229]
## 버그 설명 ##
Studio: Chart / sankey 차트 실행 후 저장시 코드 에러 발생

![image](https://user-images.githubusercontent.com/3411842/82768342-69ae3280-9e69-11ea-9744-1b1a579ff3eb.png)

**Comment by swish1995** [comment]
처리되어 닫습니다.
