### ISSUE TITLE
DSL 결과가 틈틈히 에러 발생

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2230]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

 차트를 그리기 위한 DSL 명령어를 모델에서 등록한 후 실행하면

간간히 에러가 발생합니다.

정상적인 결과

![image](https://user-images.githubusercontent.com/16331916/82783763-186a6700-9e9a-11ea-8e93-678bce65b917.png)

동일한 조건으로 실행
-> 에러 결과

![image](https://user-images.githubusercontent.com/16331916/82783810-320bae80-9e9a-11ea-952f-4ffaf870f785.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
join 명령어 버그로, 해당 부분 수정된 것으로 알고있습니다.

필요하시다면 재오픈 해주시기 바랍니다.
