### ISSUE TITLE
[Discovery] 공유 모델에서 join 안됨

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2231]
## 버그 설명 ##
공유된 모델에서 join DSL 을 실행하면 모델이 없다고 나옴.
![스크린샷 2020-05-25 오후 4 56 12](https://user-images.githubusercontent.com/3468426/82791628-1065f380-9ea9-11ea-8175-73b53588dff6.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
모델 생성할때 모델명에 공백이 있어서 발생한 이슈로 모델명 수정으로 처리하였습니다.
