### ISSUE TITLE
[이상탐지] 비교기간 및 참조기간의 데이터가 다 있는데, 이상탐지 결과가 없다고 나옵니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2233]
## 버그 설명 ##
b-iris.mobigen.com root 계정
데이터모델 DEMO_북경대기질_NA처리_2013_2017 
비교기간 : 2015/01/26 00:00:00 ~ 2015/01/27 23:59:59
참조기간 : 2015/01/05 00:00:00 ~ 2015/01/20 23:59:59
1시간 집계  / 같은 요일

* 데이터 특징 : 1시간 마다 측정한 값. 

* 설정 : 참조기간을 최근 4주로 해도 동일하게 결과가 없다고 나옵니다.
<img width="403" alt="스크린샷 2020-05-26 오전 8 35 49" src="https://user-images.githubusercontent.com/5126497/82848193-772cf080-9f2d-11ea-8497-144eb5ba0894.png">

* 결과
<img width="405" alt="스크린샷 2020-05-26 오전 8 36 01" src="https://user-images.githubusercontent.com/5126497/82848256-b4917e00-9f2d-11ea-8594-4bc80f0b8367.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
중복 이슈 정리로 닫도록 하겠습니다.
해당 내용은 https://github.com/mobigen/IRIS-BigData-Platform/issues/2625 이슈에서 진행하겠습니다.
