### ISSUE TITLE
[이상탐지] Saas 에서의 이상탐지

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2234]
## 기능 요청 ##
* 데이터가  1시간, 1일 등으로 시간이 연속적이지 않은 경우의 이상탐지 기능
예) 1시간 마다 측정하는 기온, 전력 사용량...   하루에 1번씩 나오는 오염물질 농도 ...

## 현황 ##
지금 있는 이상탐지 설정은 syslog 같은 이벤트로그나 10분, 10초 같은 짧은 주기의 데이터에 적합합니다.
이상탐지 집계 단위가 1분, 10분, 1시간 까지만 있거든요.

기존 B-IRIS  는 IRIS-DB 나 Hadoop 기반으로 기업고객의 대용량 데이터를 저장/처리 하기 위해서
이런 설정이 필요했는데( 저장된 데이터가 원시로그 또는 10초, 1분 단위 데이터가 대부분. 메모리 성능고려)

SaaS 에서는 다른 시각의 접근이 필요합니다.
처음 사용하는 고객은 
분석이 필요한 데이터를 파일로 가지고 있다가 데이터모델로 만들어서 이상탐지 를 하려고 하기 때문에
다양한 주기/ 적은 용량의 데이터를 가지고 있을 수 있습니다.

## 원하는 솔루션 설명 ##

1. 1시간, 1일로 데이터가 있는 경우의  별도 처리하는 방안이 필요합니다.(현재 이상탐지는 이 경우에 제대로 동작하지 않는 듯 합니다. 내부 로직을 살펴봐야 합니다)
이벤트 로그 데이터일 때와 주기가 있는 데이터( 연속적인 시간이 아닌 경우)로 나누어서 엔진내부에서 처리하는 게 필요합니다.(이상탐지 엔진이 시간필드로 분류하고, 고객은 신경쓰지 않는 방법으로요)

2. 1번이 된 후 manual이나  tutorial 에  "이상탐지" 는 최대 1일 주기의 데이터만 가능하고, 
나머지는 anomalies, outlier로  이상치 검색을 하라는 설명을 추가합니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
중복 이슈 정리로 닫도록 하겠습니다.
해당 내용은 https://github.com/mobigen/IRIS-BigData-Platform/issues/2625 이슈에서 진행하겠습니다.
