### ISSUE TITLE
Studio: RESTful-API / body 등에서 사용하려는 변수값 안에 "(doublequote) 문자가 있을 경우

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2235]
## 기능 요청 ##
Studio: RESTful-API / body 등에서 사용하려는 변수값 안에 `"`(doublequote) 문자가 있을 경우

## 내용
아래와 같이 body를 사용하고자할 때, `contents_var` 변수 값 안에 `"`(doublequote) 문자가 있을 경우 JSON parse 에러가 발생합니다.
```json
{
    "name": "issue test",
    "contents": "${contents_var}"
}
``` 

이를 방지하려면 `"` 문자를 `\"`로 변환해야 하는데, 이를 수행하는 기능 주체를 정해야 합니다.

**Comment by veldise** [comment]
일단 nunjucks 의 replace filter 기능을 고려해볼 수 있습니다.
https://mozilla.github.io/nunjucks/templating.html#replace

**Comment by sunghoon** [comment]
@veldise 배포 된건가요? 마일스톤에서 이슈를 찾을 수 없습니다.

**Comment by veldise** [comment]
@sunghoon 
본 이슈는 아직 처리중입니다.

**Comment by sunghoon** [comment]
@hiy2259 @veldise 배포 예정일이 자꾸 변경되고 있는데 특별한 사유가 있나요?
예상되는 작업 소요 시간 정보 및 완료 예정일을 같이 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
마일스톤 변경은 MDA 이슈로 인해 지연되어서 그렇습니다.
작업시간 및 완료 예정일은 재검토 후 알려드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
작업 소요시간은 1일 이내로 정도로 예상되며, 차주 내로 완료 가능할 것 같습니다.
