### ISSUE TITLE
Studio / 편집보드에서 '날짜/시간 선택' 컴포넌트를 복사/붙여넣기 할 수가 없습니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2236]
-  '날짜/시간 선택' 컴포넌트를 복사/붙여넣기 할 수가 없습니다.

![스크린샷 2020-05-27 오후 2 30 49](https://user-images.githubusercontent.com/512653/82981289-aa06df80-a026-11ea-9cff-9dc6071ebb32.png)

**Comment by veldise** [comment]
@sunghoon 
b-iris.mobigen.com / MacOs / 구글 크롬 & 사파리 기준 새로 추가한 객체에 대해서는 잘 동작합니다.

문제가 발생하는 환경과 문제가 발생할 당시 해당 객체(컴포넌트) 설정이나,
문제가 발생하는 보고서명을 알려주시면 확인해보겠습니다.

**Comment by veldise** [comment]
Input 과 동일한 구조로 인해 발생하는 문제로 확인되었습니다.
