### ISSUE TITLE
데이터모델 / 'YYYY-MM-DDThh:mm:ss.SSSZ' 형식의 timestamp 인식 못하는 문제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#2237]
## 버그 설명 ##
'YYYY-MM-DDThh:mm:ss.SSSZ' 형식은 ISO 8601에 따른 표현식으로 보이며, 현재 중국 협력업체에서 가져온 실제 데이터에서 나타난 포맷입니다.
![image](https://user-images.githubusercontent.com/35832986/82985999-fdc9f680-a02f-11ea-8123-be6bba11cdc2.png)

그래서 데이터모델을 생성할 때 시간 컬럼의 "기타"란에 포맷을 입력하였는데 인식하지 못하는 것으로 보입니다.

## 재현하는 방법 ##
![image](https://user-images.githubusercontent.com/35832986/82985624-5351d380-a02f-11ea-8104-2ea054dea148.png)

위 예시 화면을 보시면 컬럼 '@timestamp'을 시간 컬럼으로 선택하고, "기타"란에 형식을 입력해두었습니다.
그리고 [검색]에서 조회를 하면 오류메시지도 없이 계속 실행중인 것 같은 표시만 뜨고 아무런 결과가 나오지 않았습니다.
(약 2시간정도 기다린 후 결과가 안나오길래 "중지"버튼 눌러 중지했더니 session 에러와 함께 job id를 찾을 수 없다고 메시지가 나타났습니다)

## 예상한 행동 ##
YYYYMMDDhhmmss 형식을 처리하듯이 timestamp 형식을 인식하여 시간컬럼으로써 작동해야 한다고 생각합니다.

## 기타 ##
본 이슈는 서승환 책임님과 이야기해온 내용을 정리하여 올린 것입니다.
현재 중국 알리바바 클라우드에 올라가 있는 IRIS SaaS 버전에서 발견한 문제로, 180번에서는 재연해보지 못했습니다.

**Comment by seungfwani** [comment]
구두상으로 말씀드렸던것 처럼, 해당 포멧을 처리하는 것은 가능합니다.

해당 이슈는 닫도록 하겠습니다.
