### ISSUE TITLE
[디스커버리] calculate 함수 제안

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2239]
## 기능 요청 ##
최종적으로 "sql" 명령어를 deprecated 할 예정이라 들었습니다.
select col1+col2 as cal1, col3+col4 as cal2 from angora
문을 calculate 에서 가능해야 할 것 같습니다.
아니면 이것을 할 수 있는 방법을 usecase 해 주세요.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
calculate 명령어에 alias 기능이 추가되어 해당 동작을 할 수 있을 것으로 예상됩니다.

해당 내용을 명령어 문서에서 확인 할 수 있도록 다음주(6월 3주) 정도에 업데이트 하겠습니다.
