### ISSUE TITLE
Studio / Heatmap 값필드명 출력이 이상합니다. 

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2242]
아래 이미지를 예로 '안형민'이 아닌 '값' 이라고 표기되어야 될 것 같습니다. 

![스크린샷 2020-05-27 오후 8 18 19](https://user-images.githubusercontent.com/512653/83013071-5b256e00-a057-11ea-8281-33aa1107ad5e.png)

**Comment by veldise** [comment]
금일 패치로 아래와 같이 {x축 컬럼명} : {x축 값} / {y축 값} : {cell 값} 출력하도록 변경했습니다.
혹시 추가 개선이 필요하면 수정하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/83089355-19390e00-a0d1-11ea-8967-3d0c2564e1e0.png)

**Comment by sunghoon** [comment]
내용 확인하였습니다.
지금 처럼 나오는것 괜찮은것 같습니다. 

이슈는 닫겠습니다. ^^
