### ISSUE TITLE
[Studio] "기간 설정" 메뉴에서 속성-시간설정-시간목록 구성 시 시작시간선택, 끝시간선택 시 목록이 2개 생깁니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2243]
## 버그 설명 ##
b-iris.mobigen.com 
Studio 에서 "기간설정" 의 속성-시간설정 시 시간목록구성 할 때 "날짜 및 시간범위" 로 
시작시간을 설정하면 목록이 바로 1개 생깁니다.
그리고 종료시간을 설정하면 목록이 또 1개 생깁니다.
그래서 시작시간이 동일하고, 종료시간이 다른 목록이 2개 생깁니다.
종료시간까지 다 선택한 후에 목록이 1개 생성되어야 합니다.
<img width="325" alt="스크린샷 2020-05-29 오전 7 50 07" src="https://user-images.githubusercontent.com/5126497/83201750-27466780-a181-11ea-9ff2-b0c2de446f5c.png">

<img width="326" alt="스크린샷 2020-05-29 오전 7 50 21" src="https://user-images.githubusercontent.com/5126497/83201753-29a8c180-a181-11ea-9634-e67e95269d8c.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
기존에는 날짜 선택기능 하단에 "적용" 버튼이 존재했던 것으로 기억하는데,
이 버튼이 없어서 발생하는 문제입니다.

**Comment by sunghoon** [comment]
@veldise 문제가 어떻게 처리되었는지 결과를 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
기간 설정 객체를 리뉴얼하면서 이슈 본문에 해당하는 UI가 없어질 예정입니다.
