### ISSUE TITLE
[HOLA] Studio의 Line 차트가 주어진 데이터를 전부 표시 못하는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2245]
## 버그 설명 ##
첨부에 있는 데이터를 이용하여 Line chart 를 그리면 데이터에 있는 모든 항목이 표시 되지 않습니다.
아래 이미지와 첨부 데이터를 비교하여 확인 요청합니다.
![image](https://user-images.githubusercontent.com/11566844/83221443-cd5d9600-a1b0-11ea-9144-23e74119a157.png)
[20200528_TSN_FRER_조회_시_그래프_출력_오류_JSON.txt](https://github.com/mobigen/IRIS-BigData-Platform/files/4699700/20200528_TSN_FRER_._._._._._JSON.txt)

* 차트를 그리기 위한 DSMS 쿼리
```sql
select replace(substring(iris_base_tm,12,16),'/',':') as 수집일시,
	tx_pps_5sec as tx_pps_5초,
	tx_bps_5sec as tx_bps_5초,
	rx_pps_5sec as rx_pps_5초,
	rx_bps_5sec as rx_bps_5초
from STS_PM_TSN_DSN_INTERFACE_AVG_ETHERNET_5SEC
where node_name='Mobigen_TSN#2'
and if_name='eth0/2'
order by iris_base_tm desc;
```

**Comment by rhcpn** [comment]
해당 버그에 대한 추가적인 문의사항은 NI 개발2팀 김효정 책임에게 부탁 합니다.

**Comment by veldise** [comment]
일단 내일(6/5) 패치에서 임시로 일부 차트의 데이터 제한을 500 -> 1000 으로 변경하겠습니다.
