### ISSUE TITLE
[NMS+]IRIS 계정(패스워드)정보 암호화 방식 문의

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2246]
## 기능 요청 ##
고객사에서 사용자 패스워드 암호화방식  문의가 있습니다.
확인부탁드립니다

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@jjinylee 
메일로 답변드렸습니다.

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
