### ISSUE TITLE
[Studio] 다중축 그래프: 소수점 아래 2자리 표시 및 y축

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2250]
## 버그 설명 ##
다중축 그래프에서 
 1. 정수 데이터가 소수점 아래 2자리까지 표시됩니다.(수주건수/수주금액)
 2. 다중축 그래프의 y축이 모두 오른쪽에 표시됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 나라장터 보고서 (영업)_0601 실행
2. 탭 '수주업체별' 선택하여 조회

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
[한국환경공단]의 년도별 수주 추이의 다중축 그래프
1. 수주건수/수주금액 정수로 출력
2. y축: 왼편에 수주건수, 오른편에 수주금액 출력

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/5077625/83472819-140a0380-a4c3-11ea-9939-c21745d4536e.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
두가지 문제 모두 다른 이슈에서 해결되어 닫습니다.
