### ISSUE TITLE
데이터모델 Model Join 오류

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2251]
## 버그 설명 ##
Model Join 을 사용하려고, 검색어에 입력하였으나 오류메시지가 표시됩니다.

모델 1 : EPS_DATA_LOADER
모델 2 : EPS_MARIADB_NLP 

사용한 검색어 :
` * | join LEFT_OUTER EPS_MARIADB_NLP `
` EPS_DATA_LOADER.BIDNTCENO = EPS_MARIADB_NLP.bidNtceNo  `
` AND EPS_DATA_LOADER.BIDNTCEORD = EPS_MARIADB_NLP.bidNtceOrd `

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIs Analyzer 
2. 데이터 모델 : EPS_DATA_LOADER 클릭, 시간설정 최근 7일
3. 검색어칸에 위의 검색어 입력 후 실행
4. 오류 팝업이 표시됨

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3972489/83480079-618f6c00-a4d5-11ea-9a66-29fa66c7e0b6.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
`EPS_MARIADB_NLP` 모델에 대한 접근이 불가능 하여 해당 쿼리를 직접 테스트 하지는 못했습니다.

우선 질문해주신 명령어 문법에 대해서 말씀드리자면, 
join의 `on` 문법에 해당하는 `EPS_DATA_LOADER.BIDNTCENO = EPS_MARIADB_NLP.bidNtceNo` 부분은 사용이 가능합니다.

하지만, `AND` 로 이어지는 추가 `where` 조건에 대해서는 DSL where 명령어를 사용해야합니다.

즉, 질문 해주신 쿼리를 아래와 같이 바꿀 수 있습니다.
```
* | join LEFT_OUTER EPS_MARIADB_NLP
EPS_DATA_LOADER.BIDNTCENO = EPS_MARIADB_NLP.bidNtceNo 
| where BIDNTCEORD = EPS_MARIADB_NLP.bidNtceOrd
```

아래 링크의 join 명령어 사용법을 참고하시면 좋을 듯 합니다.
http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/join.html

**Comment by seungfwani** [comment]
답변이 된 것으로 보이며 해당 이슈는 닫도록 하겠습니다.

궁금한 점이나, 사용에 문제가 있다면 **자유롭게 재 오픈** 해주시기 바랍니다.
