### ISSUE TITLE
[Studio] "보고서 가져오기" 에서 불러오기-보고서설정유형 - 변수/값입력 에서 처음실행만 동작합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2253]
## 버그 설명 ##
b-iris.mobigen.com
보고서불러오기 (팝업/포틀릿 모두) 
불러오기-보고서설정유형-변수/값 입력

보고서 : 이슈 - 보고서불러오기_변수값_이슈  를 참고하세요.

* 달력의 날짜 YYYYMMDD 를 받아서 DEMO_20200602, DEMO_20200603 보고서를 부르려고 합니다.
<img width="184" alt="스크린샷 2020-06-03 오전 7 38 16" src="https://user-images.githubusercontent.com/5126497/83576696-453f0e00-a56d-11ea-9b35-53ea455b5034.png">

*
* 보고서가 2개 있음
<img width="184" alt="스크린샷 2020-06-03 오전 7 44 27" src="https://user-images.githubusercontent.com/5126497/83577027-1f663900-a56e-11ea-949c-f94c3beca39a.png">

* 보고서를 불러오지 못합니다.처음 또는 디폴트로 설정된 20200602 인 것 만 실행되는 거 같습니다.
<img width="693" alt="스크린샷 2020-06-03 오전 7 38 27" src="https://user-images.githubusercontent.com/5126497/83576703-48d29500-a56d-11ea-98df-056d57749b7d.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
"import 보고서 변수/값"에는 보고서 이름이 아니라 UUID로 구성된 보고서 ID를 설정해야 합니다.
사업팀 요구사항에 따라 추가된 기능이라 오해 여지가 많은 것 같습니다.

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
