### ISSUE TITLE
[Discovery] select distinct col1 from angora 와 동일한 기능을 하는 dsl 필요

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2256]
## 기능 요청 ##
[Discovery] select distinct col1 from angora 와 동일한 기능을 하는 dsl 필요

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
distinct 명령어는 개발 완료되었습니다.
명령어 문서는 다음주 정도에 아래 페이지에서 확인 할 수 있습니다.
http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/index.html

![Screen Shot 2020-06-09 at 10 27 53 AM](https://user-images.githubusercontent.com/46172579/84096084-e5000e80-aa3b-11ea-96db-e41525d32201.png)
