### ISSUE TITLE
Studio / 공유된 보고서 소수점 자릿수 풀리는 이슈

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2258]
- 보고서 데이터 조회 쿼리에서는 2자리로 설정해 두었습니다.
![스크린샷 2020-06-03 오후 5 23 48](https://user-images.githubusercontent.com/512653/83613611-fde16d80-a5be-11ea-8d43-320b05b6e2a6.png)

- 공유 받은 계정으로 같은 페이지를 접근하면 소수점이 풀림
![스크린샷 2020-06-03 오후 5 22 21](https://user-images.githubusercontent.com/512653/83613650-0d60b680-a5bf-11ea-9eb4-efeef08446c8.png)

- 개인설정은 아래와 같이 되어 있습니다.
![스크린샷 2020-06-03 오후 5 20 16](https://user-images.githubusercontent.com/512653/83613679-181b4b80-a5bf-11ea-804e-52bc242c8355.png)

**Comment by veldise** [comment]
@sunghoon 
본문에 첨부해주신 세번째 스크린샷이 "공유받은 계정"의 개인설정이 맞나요?

**Comment by veldise** [comment]
#2274 이슈로 인한 문제로 확인되었습니다.

![image](https://user-images.githubusercontent.com/3411842/83987545-8f642d00-a97b-11ea-8770-20718ec0fa63.png)

**Comment by veldise** [comment]
개인설정은 로그인한 사용자 기준으로 적용되므로, 비로그인 상태에서는 개인설정 값을 불러오지 못해 발생하는 문제로 확인되었습니다.
일단 기본값이 적용되도록 처리하겠습니다.
