### ISSUE TITLE
RestAPI 주기설정 기능

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2259]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.

현재 주기설정을 넣으면, 차트 및 데이터 표출 컴포넌트만 재실행 됨

RestAPI 로 데이터를 구성하는 경우, 주기설정이 되지 않음.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

주기 설정실행시 컴포넌트에 실행할지 말지 트리거를 줄 수 있으면 좋을듯 합니다.

또는 차트 및 데이터 표출 컴포넌트 외에도 자동실행된 컴포넌트의 경우 모두 재실행

![image](https://user-images.githubusercontent.com/16331916/83613942-79431f00-a5bf-11ea-825d-da375dcc4381.png)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
최근에 다음과 같은 작업을 진행중입니다. 패치 일시는 미정입니다.

- 차트 객체가 별도의 설정없이 주기 설정 동작에 따라 실행(서버 데이터 요청)하던 처리 제거
- 실행 가능한 다른 객체가 주기 설정 객체를 트리거 대상으로 설정할 수 있도록 기능 추가
    - Chart, Map, RESTful-API, Combo, Check&Radio, ...

**Comment by veldise** [comment]
NB-IOT에만 임시 적용하는 것으로 결정되었습니다.

**Comment by veldise** [comment]
NB-IOT에 패치가 수행되어 닫습니다.
