### ISSUE TITLE
[Studio] 지도 에서 "layer map(지도)" 에서 지도선택/지도 이동 미사용 등 클릭후 지도가 보이지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2261]
## 버그 설명 ##
b-iris.mobigen.com
보고서 "메뉴얼 만들기" 참고하세요.

1. "layer map(지도)"  레이어에서 지도를 OSM -> naver 로 변경하면 지도 사라집니다.
2. 시각화옵션에서 이동을 사용-> 미사용 하면 지도가 사라집니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/83709802-3e41f980-a65a-11ea-902d-5ffc87cede3d.png)

**Comment by veldise** [comment]
새 지도 객체에서는 발생하지 않고 해당 보고서 지도 객체에서만 발생합니다.
