### ISSUE TITLE
[Studio] 지도 에서 시각화유형 "라벨" 이 표시되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2262]
## 버그 설명 ##
b-iris.mobigen.com
보고서 : "메뉴얼 만들기" 참조하세요.

지도 : OSM 
데이터모델 : EDU_SEOUL_SAFETY_CENTER_COOR
라벨 :  NAME 
위경도 : LAT / LON

라벨 표시가 되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
데이터 모델의 컬럼 '별칭' 기능을 사용하면 발생하는 버그로 확인되었습니다.
