### ISSUE TITLE
[ValuelinkU] Studio/다중축 차트 저장 시 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2264]
## 버그 설명 ##
다중축 차트 구성화면에서 저장을 하면 Y축이 모두 오른쪽으로 표시가 됩니다.
시각화 옵션의 데이터에 Y축 이라는 항목도 생기고있습니다.
저장하고 보고서 목록으로 갔다가 다시 수정하려고 하면 이전에 선택되어진 데이터가 초기화가 됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
저장 시 "시각화 옵션-데이터"
![image](https://user-images.githubusercontent.com/7067615/83725927-b837aa00-a67d-11ea-8e73-089a16a86113.png)

저장 후 보고서 목록으로 갔다가 다시 보고서 수정했을 경우
![image](https://user-images.githubusercontent.com/7067615/83726213-2a0ff380-a67e-11ea-9a38-d043a5f140bf.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
정상 (편집 화면)
![image](https://user-images.githubusercontent.com/3411842/83982652-5b7d0d80-a963-11ea-8f92-c091b5c41a68.png)

비정상 (실행 화면)
![image](https://user-images.githubusercontent.com/3411842/83982669-6a63c000-a963-11ea-90c5-5bf30f439a9a.png)
