### ISSUE TITLE
Studio: Map / 사이드 패널 하단에 알 수 없는 여백 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2267]
## 버그 설명 ##
Map / 사이드 패널 하단에 알 수 없는 여백

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/3411842/83822339-b0bee200-a70b-11ea-8e91-9354fcd36c70.png)

**Comment by ohmy04180** [comment]
@veldise 
실제 운영 페이지에서 확인을 해보니 map 컴포넌트를 생성했을 경우 bx-btn-play에 **ng-hide** 클래스가 추가가 되어있습니다. (ng-hide: 파란색 실행 버튼이 안 보이도록 지정하는 클래스가 추가된 것 같습니다.)
그리고 실행 버튼이 생성되었을 경우, has-btn-play 클래스가 추가되어야 한다고 주석을 달아 놓았는데, 해당 map 컴포넌트에 has-btn-play가 추가되어 있습니다. 때문에 has-btn-play 클래스가 실행 버튼을 보여주기 위한 값만큼 높잇값이 줄어들면서 잘려 보입니다.  (로컬에서는 확인했을 경우, ng-hide 클래스가 없어서 실행 버튼이 잘 나오는 것으로 보여집니다)

**map 컴포넌트에서 실행 버튼을 사용하지 않는다면 has-btn-play 클래스를 제거하면 될 것 같고, 실행 버튼이 사용한다면 ng-hide를 지워주시면 될 것으로 보입니다.**
확인하시고 피드백 부탁드립니다. 감사합니다 :)

cc. @youngjiring @onlyeon

**Comment by veldise** [comment]
@ohmy04180 
알겠습니다. 확인해보겠습니다.
