### ISSUE TITLE
root 비밀번호 변경 기능 또는 방법 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2271]
## 기능 요청 ##
각 사이트에 배포된 IRIS Analyzer의 root 비밀번호 변경이 필요함.

 - 변경대상 사이트 : Valuelinku, 교통빅데이터 플랫폼 & 오픈랩 , 교통빅데이터 센터, 무역빅데이터 플랫폼, DirectCloud Box

Valuelinku 사이트에 root비밀번호를 변경하여 적용 하려 하였으나, 변경시 문제 발생 가능성이 있어,  테스트 진행 이후 가능 한것으로 답변 받은적이 있음.

**Comment by lyj** [comment]
기능 완료후 배포되었습니다.

**Comment by JeongHeeDong** [comment]
위에 언급된 각 사이트에 배포 가능한 패키지 생성 일정이 어떻게 되는지요?
이미 배포 패키지가 만들어져 있는지요?

**Comment by veldise** [comment]
@JeongHeeDong 
현재 기능은 IWP(현재 b-iris.mobigen.com 메인 사이트)에만 추가되었습니다. 기존 사이트는 메뉴 데이터 마이그레이션 문제로 IWP를 배포하기 어려워 DB 데이터를 직접 변경하기로 한 것으로 알고 있습니다.
IRIS-DB 와 WEB 각각 변경해야 하는데 별다른 이야기를 못 들으셨다면, 잠시 시간을 잡고 논의하시는게 좋겠습니다.
