### ISSUE TITLE
GridTable 차트, RestAPI 와 팝업창 기능

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2272]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

Grid Table 차트에 트리거를 주고 팝업창 (보고서) 을 띄우면서 Grid Table의 key 값을
팝업창(보고서)로 넘겨줌.
팝업창(보고서) 에서는 자동실행으로 RestAPI가 실행.

Grid Table 한개를 선택할 경우 실행이 잘됨

1) Key값을 선택하는 Grid Table 3개
![image](https://user-images.githubusercontent.com/16331916/83985252-6cce1600-a973-11ea-8312-92b1804d10f2.png)

2) Grid Table 에서 row 선택시 나오는 팝업창 (RestAPI 자동실행으로 값을 컨트롤 하고 있음)
![image](https://user-images.githubusercontent.com/16331916/83985246-63dd4480-a973-11ea-953a-820b11741003.png)

그 뒤로 다른 row 또는 다른 Grid Table의 row를 선택할 경우
RestAPI가 여러번 호출됨.

-- API 로그
- [08/Jun/2020 10:37:55] "GET /datetimeHours/20200608100600 HTTP/1.1" 200 -
- [08/Jun/2020 10:37:59] "OPTIONS /datetimeHours/20200608100600 HTTP/1.1" 200 -
- [08/Jun/2020 10:37:59] "OPTIONS /datetimeHours/20200608100600 HTTP/1.1" 200 -
- [08/Jun/2020 10:37:59] "OPTIONS /datetimeHours/20200608100600 HTTP/1.1" 200 -
- [08/Jun/2020 10:37:59] "OPTIONS /datetimeHours/ HTTP/1.1" 404 -
- [08/Jun/2020 10:37:59] "OPTIONS /datetimeHours/20200608100600 HTTP/1.1" 200 -

3) API URI 에는 Grid Table에서 선택된 key 값이 포함되어 있어야 하는데,
key 값이 없는경우 종종 발생
/datetimeHours/ HTTP/1.1" 404 -

- url 호출이 잘못되어 unknown 에러 발생

![image](https://user-images.githubusercontent.com/16331916/83985325-b9195600-a973-11ea-855b-c76bcfe6a3eb.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
@kim3163 재현을 위해 해당 리포트 이름을 알려주시면 감사하겠습니다.

**Comment by sunghoon** [comment]
@swish1995 본 이슈에 대한 최종 진행 상황정보를 공유 해 주세요.

**Comment by swish1995** [comment]
@sunghoon 담당자와 의논시 보고 당시에는 버그가 발생했으나 이후로는 발생되지 않고 있습니다.
버그가 재현되면 다시 검토가 필요할것으로 판단됩니다.

**Comment by sunghoon** [comment]
그럼 우선 닫고 재발하면 새 이슈로 대응하겠습니다.
