### ISSUE TITLE
[Discovery] 모델을 만들때 모델의 별칭이 컬럼이름이 되도록 기능수정

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2273]
## 기능 요청 ##
오리지널 데이터의 컬럼 이름이 복잡하여 별칭을 두는데, 별칭을 dsl 문에서 못쓰니 불편합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
앞서 말씀드린것 처럼,
필요한 명령어를 확인 후 진행 해야 하기 때문에 필요 명령어에 점차적으로 적용하도록 하겠습니다.

**Comment by seungfwani** [comment]
각 모델의 컬럼을 별칭으로 사용할 수 있도록 확인 해보겠습니다.

**Comment by tessekim** [comment]
이 이슈는 팀원들과 협의 결과 현재기능 그대로 쓰는것이 더 좋다는 의견이라 클로징 하겠습니다.
