### ISSUE TITLE
[Discovery] pylambda with int 버그

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2276]
## 버그 설명 ##
분석 템플릿 참조
b-iris 의 tessekim 계정의 '이슈_pylambda_with_int'
with 컬럼:string 은 정상동작
with 컬럼:int 는 값이 안나옴

![스크린샷 2020-06-08 오후 3 41 53](https://user-images.githubusercontent.com/3468426/84000047-e62f2e00-a99e-11ea-8513-48e7d90fff1c.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
```
* | fields TERM_FREQUENCY as 워드, FREQUENCY_NUM as 카운트, prdctclsfcnonm as 과제명 | where 워드 is not null | where 워드 like '%,시설,%'  | pylambda row : int(row[1].split(',')[row[0].split(',').index('시설')]) with `결과`:int
```
해당 명령어를 위와 같이 사용하면 동작하는 것을 확인 했습니다.

현재 pylambda 명령어 상태 설명
- `row: ... ` 에 작성한 함수는 계산 결과를 반환하기 위한 식
- `with ...` 에 작성된 것은 DataFrame의 스키마 정보를 입력하기 위한 곳 (casting 의미가 아닙니다.)
- 즉, `계산 결과 타입`과 `스키마 타입`을 일치 시켜주어야 합니다.

**Comment by tessekim** [comment]
OK, 감사합니다.
