### ISSUE TITLE
[Discovery] 명령어 correlation 이 동작하지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2277]
## 버그 설명 ##
데이터를 id, features 2개의 컬럼

b-iris   root 계정
분석탬플릿 '이슈_correlation_시험에러' 참조

데이터모델 : cordata1

`* |  fields -id | pylambda row : str(row) | rename _1 features | correlation features`

<img width="497" alt="스크린샷 2020-06-08 오후 4 00 40" src="https://user-images.githubusercontent.com/5126497/84001353-5e96ee80-a9a1-11ea-84a4-b8cca5ac8f95.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
AA팀에서 수정을 하여 사용중인 것이라고 들었습니다. 이슈 닫아도 될까요?

**Comment by seungfwani** [comment]
correlation -> corr 명령어 변경,
corr 명령어 머지 후 이슈 닫도록 하겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 진행 상태를 확인해 주세요.

**Comment by seungfwani** [comment]
빌드 테스트 완료 하였으며,
(20.10.16) 배포요청 하였습니다.
