### ISSUE TITLE
[Studio] Button 객체-링크설정시 사파리 브라우저는 윈도우팝업이 하이퍼링크로 동작합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2280]
## 버그 설명 ##
Mac - 사파리 브라우저
b-iris.mobigen.com  demo 계정
보고서명 :  보고서만들기_0608

* 버튼 속성
<img width="207" alt="스크린샷 2020-06-09 오전 9 37 23" src="https://user-images.githubusercontent.com/5126497/84093350-ef6ada00-aa34-11ea-9119-c84935bc867a.png">

<img width="206" alt="스크린샷 2020-06-09 오전 9 37 27" src="https://user-images.githubusercontent.com/5126497/84093430-2b05a400-aa35-11ea-95e7-2ecaf7ab812e.png">

* 결과는 탭으로 열립니다.
<img width="397" alt="스크린샷 2020-06-09 오전 9 38 07" src="https://user-images.githubusercontent.com/5126497/84093448-335ddf00-aa35-11ea-9db3-b00ace8d69ef.png">

* 참고로 보고서 불러오기(윈도우 팝업) 은 사파리에서 정상 동작합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
아래 기준 정상 동작하여 닫습니다.

MacOS: 10.13.6(17G14019)
Safari: 13.1.2(13609.3.5.1.5)

![image](https://user-images.githubusercontent.com/3411842/90840536-32cab880-e395-11ea-88c6-3c77d42e61e2.png)
