### ISSUE TITLE
[Studio] 다중축 그래프 정렬

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2282]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
테이블에서는 정렬이 되는데 다중축 그래프에서는 정렬이 안됩니다.

## 재현하는 방법 ##
보고서: 공공조달_수주업체_v0.6

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/5077625/84106791-03273800-aa57-11ea-88d7-5854d7f0647d.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@euhyesun 
정렬 기준을 무엇으로 하냐에 따라 결과가 달라지므로, 어떤 정렬인지 명확히 써주셔야 합니다.
값에 의한 정렬인지, 아니면 x축 문자열 가나다 순인지, 오름차순/내림차순 정렬인지 기술을 바랍니다.

추가로 현재 Studio는 데이터 정렬을 UI기능 보다는 DSL/SQL의 명령어에 의존하도록 하고 있습니다.
ex) `* | sort HOST desc`

**Comment by euhyesun** [comment]
@veldise 수주 건수에 대한 내림차순 정렬입니다. (| sort -수주건수)
왼쪽 테이블에서는 정렬이 되는데 오른쪽  다중축그래프에서는 정렬이 되지않습니다.
https://user-images.githubusercontent.com/5077625/84106791-03273800-aa57-11ea-88d7-5854d7f0647d.png

**Comment by veldise** [comment]
@euhyesun 
확인했습니다. 현재 무조건 x축으로 정렬되는 버그가 있습니다.
x축에 시간 컬럼을 설정했을 경우에만 x축으로 정렬되어야 합니다.
