### ISSUE TITLE
[Studio] 시각화 옵션: 열 정렬

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2283]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
시각화 옵션 - 열 - 정렬
테이블에 정렬이 적용되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
보고서: 공공조달_수주업체_v0.6

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/5077625/84107333-51890680-aa58-11ea-83b0-ab216c036254.png)
![image](https://user-images.githubusercontent.com/5077625/84107434-8d23d080-aa58-11ea-9bf4-d4d757c08859.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
"공공조달_수주업체_v0.6(계약체결일자 기준)" 보고서 기준입니다.

해당 Chart 객체의 시각화 옵션 - 열 항목은 아래와 같습니다.

![image](https://user-images.githubusercontent.com/3411842/84213113-beed7380-aafa-11ea-820f-bef68f665915.png)

열 이름이 `_1`, `_2`, ... 와 같습니다. 그런데 화면에 표시되는 열 이름은 `일자`, `공고번호`, ... 입니다.
시각화 옵션의 헤더와 열 설정은 열 이름을 기준으로 적용되므로, 이와 같이 설정된 열 이름이 다르면 적용되지 않습니다. 편집 화면에서 같은 조건으로 한 번 실행한 뒤 설정하셔야 합니다.

**Comment by euhyesun** [comment]
@veldise 네, 확인했습니다. 감사합니다.^^
