### ISSUE TITLE
[Discovery] 모든 명령어에서 한글 컬럼명에 `(백쿼터) 안쓰는 것으로 통일 필요

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2285]
## 기능 요청 ##
명령어 마다 한글 컬럼명에 백쿼터를 쓰는 것과 안쓰는것이 혼재되어 있어 혼란이 있음.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
sql 명령어를 제외한 타 명령어는 백쿼터를 안쓰도록 하고 있으나,
일부 처리되지 못한 명령어가 있다면, 함께 말씀해주시면 감사하겠습니다.

현재 인지하고 있는 명령어는 `pylambda` 명령어 입니다.

**Comment by seoryjj** [comment]
한글과 숫자로 시작하는 컬럼이름/모델이름의 시험 결과입니다.
- 백쿼터는 안쓰는 것으로 통일
- 따옴표 없애기
- 숫자로 시작하는 이름은 쓸수 없도록 함
이런 방향으로 DSL 수정하는 것은 어떨까 합니다.

<img width="745" alt="스크린샷 2020-06-16 오전 11 14 05" src="https://user-images.githubusercontent.com/5126497/84724207-8a7a2b80-afc2-11ea-9911-51db19f922d4.png">

**Comment by seungfwani** [comment]
@seoryjj 
감사합니다 😄

**Comment by seungfwani** [comment]
정리해주신 엑셀내용으로 수정을 하였습니다.
두가지 기준으로 수정하였습니다.
1. 영어/한글로만 이루어진 필드 -> nothing|작은따옴표
2. space/특수기호/숫자로 시작하는 필드 -> 작은따옴표
