### ISSUE TITLE
[Studio] 사파리에서 에디터에 글을 작성할 수 없습니다.

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#2286]
## 버그 설명 ##
사파리에서 에디터를 배치 후 보기 모드일때 에디터에 글을 작성할 수 없습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
* 사파리 브라우저를 실행합니다.
* b-iris.mobigen.com 에서 보고서 메뉴에 새 보고서 클릭합니다..
* 보고서에서 에디터를 선택 후 에디터 객체를 캔버스에 배치합니다.
* 우측 상단 보기 모드 클릭하면 보고서가 새 창으로 뜹니다.
* 에디터에 글을 작성하려고 하면 선택이 안됩니다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
* 크롬에서 동작하는 것을 확인 (user-select: none; 만 활성화 됨.)
<img width="1363" alt="스크린샷 2020-06-10 오전 8 17 17" src="https://user-images.githubusercontent.com/5515493/84210421-931abf80-aaf3-11ea-8b17-935668e3888a.png">

* 사파리에서 에디터 동작 안함.
![스크린샷 2020-06-10 오전 8 16 50](https://user-images.githubusercontent.com/5515493/84210427-9d3cbe00-aaf3-11ea-867c-6bf1f2243315.png)

* -webkit-user-select: none; 을 채크 해제하면 에디터에 글을 작성할 수 있습니다.
![스크린샷 2020-06-10 오전 8 16 59](https://user-images.githubusercontent.com/5515493/84210454-b47bab80-aaf3-11ea-876d-596663264f04.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by ohmy04180** [comment]
@veldise @hiy2259 @hiy2259 
안녕하세요!
해당 이슈 처리하여 깃에 올려두었습니다.
감사합니다.

cc. @youngjiring @onlyeon
