### ISSUE TITLE
iris 도움말 페이지에서 카테고리가 잘려보이는 현상

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#2288]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

iris 도움말 페이지(http://docs.iris.tools/manual/IRIS-Usecase/usecase1-syslog/index.html 등) 에서 
카테고리 명칭이 너무 긴 경우, 잘려보입니다. 
(예: 'Usecase'의 'SYSLOG 데이터로 실시간 anomalies, outlier, forcasts 결과 분석 예제')

카테고리 명이 너무 길어 나타나는 문제 인것 같은데, 
카테고리 명이 너무 길면(혹은 일정길이 이상이면) 카테고리를 직접 누르지 않더라도
마우스 오버를 했을 때, 말풍선 같은 것으로 전체 제목이 뜨면 좋을 것 같습니다. 

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

카테고리를 직접 누르지 않더라도 말풍선 같은 것으로 전체 제목이 뜨면 좋을 것 같습니다. 

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
<img width="1406" alt="스크린샷 2020-06-10 오후 5 59 20" src="https://user-images.githubusercontent.com/36151180/84248413-57f4ac80-ab44-11ea-8ede-d3b8983c8e26.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by EricLeeMbg** [comment]
좋은 의견 감사합니다. 
말풍선 등의 기능을 확인하여 적용하겠습니다. 

우선 docs.iris.tools의 좌측 pane은 고정폭으로 서비스되고 있으므로, 긴 형태의 문장은 의미를 파악할 수 있는 최소한의 형태로 변경하여 빠른 시간 안에 적용하겠습니다.

**Comment by sunghoon** [comment]
@cosmos-mc 업무에 참고 하시기 바랍니다.
