### ISSUE TITLE
Studio/버튼컴포넌트 동작하지 않음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2289]
## 버그 설명 ##
기 생성되어 있는 보고서에서 버튼실행시 아무런 동작을 하지 않음.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/84330874-836aac00-abc3-11ea-9402-2401ddd298b1.png)

**Comment by veldise** [comment]
오전중에 긴급 패치 수행하겠습니다.

**Comment by veldise** [comment]
@JeongHeeDong 
해결되었습니다. 불편을 드려 죄송합니다.
