### ISSUE TITLE
[Analyzer] 첫 화면 레코드카운트 막대 그래프 오류

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2290]
## 버그 설명 ##
전체 기간이 나오지 않습니다.
따로 만나 설명 드릴께요.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
2013 ~ 2017년 데이터가 존재하는 데이터 모델로 검색 시:
1. 2014년 7월 13일 이후 데이터가 막대 차트에 출력되지 않음
2. 막대 차트 너비가 너무 작게 그려짐

![image](https://user-images.githubusercontent.com/3411842/84335345-9be0c380-abcf-11ea-8c1f-4b78cb45c64a.png)

**Comment by veldise** [comment]
1번 문제는 Angora /query/jobs API 를 호출할 때 `size` 옵션을 지정하지 않으면
데이터를 `500`개만 반환하는 것 때문에 발생하는 문제입니다. (기본값으로 추정)
