### ISSUE TITLE
[NMS+]보고서 사용쿼리 덤프 문의

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2292]
## 기능 요청 ##
생성한 보고서가 많다보니 고객이 보고서에서 사용한 쿼리를 덤프를 받을수 있는지 문의가 있습니다.

보고서를 저장해놓은 IRIS Maria-DB 에 보고서내의 쿼리가 저장되어있나요?
운용기술지원팀에 문의했으나 개발쪽에 문의해야한다고 해서 문의합니다.
확인부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
사용한 쿼리라면 아래와 같이 '검색어' 부분에 입력한 내용이 맞나요?

![image](https://user-images.githubusercontent.com/3411842/84348542-276a4c80-abf0-11ea-90f6-3741d1f0ab3d.png)

위 내용은 다른 정보들과 함께 정해진 구조의 JSON으로 처리되는데,
MariaDB에 저장할 때는 이 JSON 전체를 Base64로 인코딩하여 저장합니다.

따라서 덤프를 뜨려면 스크립트를 별도로 작성해야 할 것으로 생각됩니다.

**Comment by jjinylee** [comment]
보고서에서 차트/그리드등 콤포넌트에 사용된 
DSMS , DSL 로 사용한 쿼리를 덤프 뜨고 싶다고 합니다.

**Comment by sunghoon** [comment]
@veldise 본 이슈에 대한 최종 진행 상황 공유 바랍니다. 

@jjinylee 최근 보고소 Export 기능 일부가 개발되어 있으니 해당 기능을 이용해 볼 수 있지 않을까요?
참고로 버전 업그레이드 진행해야 합니다.

**Comment by sunghoon** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/2656
같은 요청보이며, 일회성 업무로 개발팀에서 지원 된 것으로 보입니다. 
닫도록 하겠습니다.
