### ISSUE TITLE
[NMS+]데이터브라우저 오류메시지 보완요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2293]
## 기능 요청 ##

아래는 SKB 담당매니저님께 받은 메일의 내용입니다.
아래와 같이  오류가 뜨는데 어떤 부분을 수정해야하는지 알수없어서 어렵다는 얘기를 많이하시네요

일전에도 이런내용의 리포팅이 있었는데
앙고라 에러라고 뜨는 부분의 개선이 필요합니다.

========================================================
안녕하세요. 이순미입니다. 

대시보드를 추가로 만들고 있는데데이터브라우저 쿼리 에러가 발생합니다. 
해결 방법을 모르겠네요 ^^; 확인부탁드립니다. 

angora error: <class 'py4j.protocol.Py4JJavaError'>('An error occurred while calling o1682663.collectToPython.\n', JavaObject id=o1682664)

 - 에러 내용 : 위의 javaerrorl  
 - 보고서 이름 : REPORT_센터별트래픽24H_tensall  
 - 사용 쿼리 : * \| sql "select SDATM, ROUND(IN_BPS/1024/1024/1024,2) as IN_BPS  from angora where GROUP_ID in ( 13791,13792,13793,13794)" \|  adv line sum(IN_BPS) as IN_BPS SPLITROW  'date_group("SDATM", "5M")'l  
   - 데이터 모델 : GROUP_PER_IFC_USAGE_5Ml  
   - 특이사항n  REPORT_센터별트래픽4H_tensal 보고서를 copy 해서 만들고 있음. (센터별 전체 트래픽 관제용으로 사용하던 대시보드)
   - 데이터모델은 신규로 추가함. 
    GROUP_PER_IFC_USAGE 모델과 동일하게 추가한 것 같은데 여기가 잘못된 걸까요
  -  쿼리에서 붉은색 부분을 제외하고 쿼리하면 결과가 나옴. 쿼리는 REPORT_센터별트래픽4H_tensal 에서 사용한 쿼리와 동일하게 사용한 것 같은데 붉은부분에서 에러가 발생합니다. 

수정 방법을 알려주세요~ 
데이터브라우저 검색에서 쿼리할 때 이런부분이 어렵네요 ^^;

에러가 발생했을 때 에러 내용이 파악이 안되고 수정 방법을 확인하기가 어렵습니다. 

다양한 샘플 쿼리가 있으면 참고가 될 것 같은데~방안 고민 부탁드립니다!

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise @anhm 해당 이슈와 관련된 진행 내역 공유 바랍니다.

**Comment by anhm** [comment]
시간이 많이 지난 이슈로 인해 다시한번 확인되면 이슈를 등록 부탁 드립니다.
