### ISSUE TITLE
대시보드 보고서 선택 시 오류

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2294]
## 버그 설명 ##
대시보드 보고서 선택 시 오류

## 재현하는 방법 ##
1. Go to mobigen.iris.tools
2. Click on 대시보드-보고서 선택

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/84351541-89c64b80-abf6-11ea-8e65-f41e21c76c94.png)

**Comment by rhcpn** [comment]
해당 기능은 ISP 에서 접근 해야만 사용 가능하므로 스크린샷에 나온 현상이 정상적입니다.
