### ISSUE TITLE
Studio / 탭 선택에 트리거 걸려있는 "외부 URL" 컴포넌트 표출 시 순간 404이 보이는 문제

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#2296]
## 버그 설명 ##
탭으로 다수의 외부 URL 컴포넌트를 제어하는 대시보드를 제작한 상태입니다.
자동실행이 걸려있지 않은 외부 URL을 탭을 눌러서 실행할 때 순간적으로 404 오류 메시지가 보입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. psi 계정에서 생성한 "[분석 1] 메인 대시보드" 클릭
2. "112 신고수 예측 모니터링", "경찰서별 변수 중요도 분석" ... 등으로 구성된 탭에서 아무거나 클릭
3. 화면 중간에 외부 url 컴포넌트가 표시되는 부분이 탭을 클릭하는 순간 404가 나타났다가 사라짐

## 스크린샷 ##
너무 순간이라 캡처가 안됩니다.
만약 어려우시면 제가 직접 재연해드리겟습니다.

**Comment by sunghoon** [comment]
@eumminsun @veldise 상황 재현을 통해 내용을 확인하고 처리에 필요한 작업 소요 시간 정보를 공유 바랍니다.
