### ISSUE TITLE
[Discovery] distinct 에서 컬럼명에 작은따옴표를 하면 에러없이 컬럼은 출력되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2297]
## 버그 설명 ##
b-iris.mobigen.com 
데이터모델 : **EDU_Beijing_air_2013_2017_18**

`* station='Dingling' | fields year,station,PM10 | rename station '지점' |  distinct year,'지점' `

에러발생은 없이
station 즉  지점 컬럼이 출력되지 않습니다.

distinct 는 컬럼명에 따옴표 등이 있으면 처리하지 않고, 에러도 발생시키지 않습니다.
하지만 결과는 잘못된 것이기 때문에
에러를 출력하는 게 맞다고 봅니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
수정되었습니다.
![Screen Shot 2020-07-09 at 9 58 07 AM](https://user-images.githubusercontent.com/46172579/86984861-b310d200-c1ca-11ea-81a4-056ef4173319.png)
