### ISSUE TITLE
[Analyzer] 결과 sheet 에서 컬럼을 제외, 선택하면 컬럼 head 부분 위치가 틀어집니다.(맥-사파리)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2300]
## 버그 설명 ##
MacBook 사파리브라우저
b-iris.mobigen.com

* 시험
아무 데이터모델을 선택 후 검색어로

`mlmodel list`

후 왼쪽 컬럼 pane 에서 컬럼을 제외, 선택해보세요.

* analyzer 에서 컬럼을 제외, 추가 하면 sheet 에서 헤더가 틀어집니다.

<img width="1430" alt="스크린샷 2020-06-12 오후 2 27 55" src="https://user-images.githubusercontent.com/5126497/84468574-21d93900-acba-11ea-983a-4b94bdf64936.png">

<img width="1431" alt="스크린샷 2020-06-12 오후 2 29 54" src="https://user-images.githubusercontent.com/5126497/84468581-243b9300-acba-11ea-8110-da522a21c27f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/87751920-19849880-c83a-11ea-8d46-ecda54ac0e56.png)
