### ISSUE TITLE
[업무관리] 모든 계정에서 모비젠 업무관리 정보가 다 보이는 보안 이슈

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#2301]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
현재 모든 계정에서 모든 팀의 모비젠 업무관리 정보가 다 보입니다. 
(소속 팀이 아니어도, 다른 팀의 정보도 보임, 외부 계정도 보임)

필요로 하는 몇몇 계정만 확인하게 하거나, 
외부로 나가는 계정 (psi 등)은 권한을 분리하거나 해야 할 것 같습니다. 
보안상의 이슈가 있을 것 같습니다. 

## 스크린샷 ##
<img width="346" alt="스크린샷 2020-06-12 오후 5 39 19" src="https://user-images.githubusercontent.com/36151180/84483135-de8bc400-acd3-11ea-9d4c-85962c1bdd45.png">

<img width="1340" alt="스크린샷 2020-06-12 오후 5 39 27" src="https://user-images.githubusercontent.com/36151180/84483144-e21f4b00-acd3-11ea-80b1-fda8b76163d9.png">

위의 스크린샷은 치안연구소(psi)계정의 '업무관리' 기능 이며, 모비젠 내부 업무기록이 보이는 부분입니다.

**Comment by rhcpn** [comment]
확인 해보니 모든 메뉴가 전 사용자 이용 가능으로 권한 설정이 되어 있습니다.
root 접속 정보를 아신 다면
- 로그인 > 오른쪽 상단 사용자 아이콘 클릭 > 설정 아이콘 (톱니바퀴모양) 클릭 > 메뉴관리 > 업무관리 그룹 선택 하셔서 사용자 지정

만일 위의 과정을 수행하기에 여의치 않으시다면 권한이 필요한 사용자 아이디 혹은 그룹을 comment 로 남겨 주세요.

**Comment by sunghoon** [comment]
조치를 위해 접속 권한을 제한하도록 설정하였으며,
접근 가능한 사용자 기준으로 신청이 들어오는 경우 Mobigen Group으로 이동시켜
접근을 제공하도록 하겠습니다.
