### ISSUE TITLE
[IRIS Studio] 객체 실행이 안되는 현상

### ISSUE THREAD

**Issue by seungfwani** [mobigen/IRIS-BigData-Platform#2303]
## 버그 설명 ##
보고서로 작성한 8가지 객체 중 스크린샷의 "실행중..." 객체만 실행이 되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
보고서명: DEMO_News_Dashboard
소유자: jins00

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![Screen Shot 2020-06-15 at 10 23 22 AM](https://user-images.githubusercontent.com/46172579/84609859-8a5f2a80-aef3-11ea-83f1-13885de91f6a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#2291 과 동일 이슈로 생각됩니다.
