### ISSUE TITLE
[Studio]  테이블의 가로-세로 바가 보입니다.(mac-크롬)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2304]
## 버그 설명 ##
* 보고서 : 야구데이터 분석 : Batting(타격)데이터
* b-iris
*  msc / 크롬(김태수 대표님 노트북/모니터)

![스크린샷 2020-06-15 오전 11 28 16](https://user-images.githubusercontent.com/5126497/84612726-73710600-aefc-11ea-968f-ff8d985a8a3c.jpeg)

* 참고로 저(mac, 크롬) 는 정상적으로 나옵니다.
* 설정 문제라면 권장 설정을 먼저 알려주세요.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
사파리도 바가 보인다고 합니다.

**Comment by veldise** [comment]
#2266 과 동일 이슈로 생각됩니다.

**Comment by youngjiring** [comment]
사파리,크롬 버전별 확인해보았으나 저, 강책임님, 엄책임님 모니터에서 현상 재현이 되지 않았습니다. 클래스로 수정이 가능한지 확인해보았으나, 인라인 스타일의 width 값이 달라지는 것으로 보아 CSS로 해결이 어려울 것 같아 이슈 요청 드립니다. 추후에 퍼블리싱 작업이 필요하시면 말씀해주세요.

**Comment by veldise** [comment]
@seoryjj @tessekim 
제 PC(MacOS / Chrome)에서는 해결된 것으로 보이는데 확인을 부탁드립니다.

**Comment by veldise** [comment]
해결된 것으로 보고 닫습니다.
