### ISSUE TITLE
corr 명령어 결과표출 불가

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#2305]
## 버그 설명 ##
상관계수의 결과값이 나오지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
- 실수형 컬럼 두개에 대해 명령어 입력 
(BATTING) *|corr columns=G,AB
## 예상한 행동 ##
스크린샷내 빈 공간에 값이 나와야합니다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
아이리스 내 사용시 결과 화면 (값나오지 않음)
<img width="1176" alt="스크린샷 2020-06-15 오후 5 33 31" src="https://user-images.githubusercontent.com/32768535/84635716-8ef50480-af2e-11ea-9026-6862ba361509.png">

180 서버내 test 코드 결과 (Row로 잘 나오고있음)
<img width="1627" alt="스크린샷 2020-06-15 오후 5 35 22" src="https://user-images.githubusercontent.com/32768535/84635754-9d432080-af2e-11ea-86e3-912ab4665446.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@GyuminJack 
corr 실행 결과에 null 값이 있는 것으로 보이며 (명령어가 적절한지 or 데이터가 적절한 것인지) 확인해보셔야 할 것 같습니다.
![Screen Shot 2020-06-16 at 1 30 33 PM](https://user-images.githubusercontent.com/46172579/84732045-93282d00-afd5-11ea-90e8-88364bb89078.png)
![Screen Shot 2020-06-16 at 1 37 27 PM](https://user-images.githubusercontent.com/46172579/84732398-8f48da80-afd6-11ea-9ad8-83800a5f00d5.png)

**Comment by GyuminJack** [comment]
다른 데이터로 확인해보니 결과 표출됩니다. 착오를 드려 죄송합니다.
