### ISSUE TITLE
[Analyzer] 검색 결과 표시 필드명 미표시 건

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2306]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

Analyzer 검색에서 데이터 검색 결과 테이블 목록의 컬럼 필드명이 나오지 않는 문제

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
데이터 모델 선택, DSL fields 명령어 사용, 검색 결과 테이블 목록의 필드명 이름 나오지 않음, 또는 필드간격 세로줄 안맞는 현상이 나타남, 가로 스크롤바 조정시에 필드명이 다시 표시됨
## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/84647701-beac0880-af3e-11ea-9181-3c42a4dc0566.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@cosmos-mc 
검색어(DSL) 입력 내용과 왼쪽 컬럼 목록에서 컬럼 표시 설정 여부에 따라 나오지 않을 수 있습니다.
입력하신 검색어 내용과 전체 스크린샷을 첨부 바랍니다.

![image](https://user-images.githubusercontent.com/3411842/84714066-8d1b5780-afa7-11ea-9ac0-22dcded7dcf7.png)
