### ISSUE TITLE
[IRIS Studio] 보고서 팝업을 X 버튼이 아닌 임의의 버튼 클릭 시 Close 되는 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2308]
## 개요 ##
보고서 팝업을 띄우면 현재는 팝업의 상단 우측 X 버튼을 클릭 했을 시에만 창을 닫을 수 있는데
이를 임의의 버튼으로 실행 가능하도록 기능 추가가 필요함

**Comment by sunghoon** [comment]
@veldise 해당 기능 개발일정이 계속 바뀌고 있는 사유 가 무엇인가요?
개발에 필요한 작업 소요일정면 완료 계획을 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
MDA kerberos 이슈, 철도공사 보안점검 이슈로 인해 지연되었습니다.

**Comment by sunghoon** [comment]
@veldise 개발에 필요한 작업 소요일정면 완료 계획을 공유 해 주세요

**Comment by veldise** [comment]
@sunghoon 
6~7일 정도 예상하고 있고 10월 1주차에 완료될 것으로 예상됩니다.

**Comment by veldise** [comment]
@sunghoon 
코어에 준하는 코드 수정 작업을 먼저 처리할 필요가 있어 일정을 조정하였습니다.
"코어에 준하는 코드 수정 작업"은 금주 중에 완료되며, 본 이슈 항목은 차주중에 일정 재협의하여 알려드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
11.05 릴리즈에 포함시키는 것으로 일정을 잡았습니다.
