### ISSUE TITLE
[IRIS Studio] 각 컴포넌트/그룹에 Visible 속성이 있고, 변수로 제어 가능한 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2309]
## 개요 ##
화면 구성 시, 특정 조건에 따라 임의의 영역이 보임/보이지 않음의 기능이 필요한 경우가 있음.
이를 위해 모든 컴포넌트의 속성에 visible 속성이 필요하며, 해당 속성을 변수로 제어 할수 있어야 함.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
