### ISSUE TITLE
[IRIS Studio] 그리드에서 특정 Row 클릭 시, 주소값이 있는 경우 새창을 띄울 수 있는 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2310]
## 개요 ##
시각화 > 그리드 에서 그리드의 특정 컬럼이 Http URL인 경우 해당 Row을 클릭 or 더블클릭 시 해당 주소값으로 새창을 띄울 수 있는 기능이 필요

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
