### ISSUE TITLE
[IRIS Studio] 특정 조건에서 컴포넌트를 실시간으로 동적 추가가 가능한 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2311]
## 개요 ##
보고서를 실행 후 특정 컴포넌트를 동적으로 추가 할수 있는 기능 필요.
예를 들어, 특정 권한에 사용자를 동적으로 추가 하기 위해, 사용자 추가 +버튼 클릭 > Text Input 생성 과 같은 상황이 필요 할 수 있음.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
