### ISSUE TITLE
Elasticsearch connecter 구성시 특정 field의 값에 대괄호가 있는 경우 추가할 수 없는 컬럼으로 분류하고 db연결

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2312]
아래 그림과 같이 analyzed_words 필드에 대해서는 추가하지 못하고 있음.

![image](https://user-images.githubusercontent.com/512653/84723549-cb714080-afc0-11ea-8e48-5a695c4da10b.png)

**Comment by seungfwani** [comment]
현재 IRIS 에서 처리하고 있는 데이터 타입은 아래와 같습니다.
| IRIS Type | Python Type  |
| :-------: | ------------- |
|TEXT | string |
|REAL| float|
|INTEGER| int|
|BIGINT| long |
|DATE| datetime.date|
|TIMESTAMP|datetime.date|

따라서, array 타입을 지원하고 있지 않습니다.

**Comment by jins00** [comment]
* 추가 질문입니다.
ES에 상기와 같은 array 타입의 데이터가 저장된 필드가 있는 경우,
해당 필드만 무시하고 추가할 수 있나요?
만일, 해당 필드만 무시할 수 있다면 굳이 별도의 인덱스를 만들 필요없이 IRIS-ES간 연동이 가능하다고 합니다.

**Comment by jins00** [comment]
@seungfwani 추가 질문입니다.
ES에 상기와 같은 array 타입의 데이터가 저장된 필드가 있는 경우,
해당 필드만 무시하고 추가할 수 있나요?
만일, 해당 필드만 무시할 수 있다면 굳이 별도의 인덱스를 만들 필요없이 IRIS-ES간 연동이 가능하다고 합니다.

**Comment by seungfwani** [comment]
spark - ES 간에 선택한 컬럼을 제외한 후 데이터를 읽어오는 옵션은 있습니다만,
`선택한 컬럼` 만 제외 하는 것이기 때문에,
각 데이터별로 컬럼명이 다르고, 하나하나 추가할 수 없는 방법입니다.

유동적으로 선택을 하기 위해서는, `새모델 만들기` 에서 제외할 컬럼을 먼저 선택해야하는데 이것은 현재 동작 순서와 차이가 있습니다.
아래 동작 과정을 통해서, 사용자는 해당 데이터에 어떤 컬럼이 있는지 확인 할 수 있기 때문입니다.
- 현재 동작 순서 : UI -> angora로 샘플데이터와 스키마 정보 요청 -> angora 데이터를 읽음(현재 여기서 ERROR 발생) -> 샘플, 스키마를 UI로 반환

**Comment by seungfwani** [comment]
처리내용 공유

선택한 인덱스에 IRIS 에서 처리 불가능한 필드가 포함된 경우, 처리불가능 필드만 제외하고 나머지 데이터를 보여주도록 수정하였습니다.

운영서버, 중국 서버 둘다 적용된 상태입니다.
