### ISSUE TITLE
보고서 시계열 분포 쿼리 변경 시 시각화 옵션이 변경됩니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2313]
- 보고서 편집 화면에서 데이터 탭의 실행 버튼을 누르면 기설정된 시각화 탭의 시계열 분포 세팅이 일부 변경되고 있음. 
- 자세한 사항은 아래 그림을 참조.

- 쿼리 변경 전
![image](https://user-images.githubusercontent.com/512653/84723646-0c695500-afc1-11ea-80c2-91bdfe687f13.png)
![image](https://user-images.githubusercontent.com/512653/84723660-155a2680-afc1-11ea-8327-16a86b448058.png)

- 쿼리 변경 후
![image](https://user-images.githubusercontent.com/512653/84723677-1ee38e80-afc1-11ea-9025-b919689e44cc.png)
![image](https://user-images.githubusercontent.com/512653/84723685-22771580-afc1-11ea-82f1-2c0f71309add.png)

**Comment by veldise** [comment]
문제점 확인하여 최초 설정된 값이 변경되지 않도록 개선하겠습니다.
