### ISSUE TITLE
보고서 시계열 분포 그래프가 선형도 선택 가능하면 좋겠습니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2314]
X축은 article_date, Y축은 total_co unt로 하고, news_category로 그룹핑하여
꺾은 선형 차트를 만들고자 하는데, 
보고서에서 이런 꺾은 선형 차트를 그릴 수 있는 방법이 있으면 설명 부탁드립니다.

- 시계열 분포
![image](https://user-images.githubusercontent.com/512653/84723776-636f2a00-afc1-11ea-814c-edeb16c19384.png)

- 꺽은선형
![image](https://user-images.githubusercontent.com/512653/84723793-72ee7300-afc1-11ea-8511-94d6c4beb403.png)

**Comment by veldise** [comment]
아래와 같이 x축으로 지정할 컬럼을 제외한 나머지가 범례(legend)에 해당하는 값들인 상태에서,
y축을 '모두 선택'으로 설정하면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/84724305-d036f400-afc2-11ea-97bf-c1bfd20507c0.png)

![image](https://user-images.githubusercontent.com/3411842/84724377-01afbf80-afc3-11ea-8df1-0c1112dde570.png)

![image](https://user-images.githubusercontent.com/3411842/84724397-0d9b8180-afc3-11ea-96ad-01ce868292bc.png)

**Comment by veldise** [comment]
동일한 데이터로 시계열 분포처럼 꺾은선형을 그리려면 추가 개발이 필요합니다.

**Comment by sunghoon** [comment]
@jins00  아래 이미지를 보면 사용자가 원하는 형태와 결과물이 비슷해 보이는데
이렇게 처리하면 되는건 아닌지요?

@veldise 아래 시각화는 스튜디어에서 는 안되는건가요?

![스크린샷 2020-06-17 오후 3 07 35](https://user-images.githubusercontent.com/512653/84861635-7dd20200-b0ac-11ea-8ea7-98852599d769.png)

**Comment by jins00** [comment]
@sunghoon @veldise, 스튜디오의 보고서 편집 화면에서 꺾은 선형 시각화 옵션을 선택하고, 검색어를 아래와 같이 입력하면 가능한 것 같습니다. 
위즈온텍에서는 해당 검색어를 모르는 상태에서 시각화 옵션의 데이터 값을 선택하여 만들어보려고 한 것 같습니다. 일단, 아래 검색어를 사용하도록 제안하겠습니다.

* | adv line count(*) SPLITROW 'date_group("article_date", "1d")' SPLITCOL news_category COLSIZE 500

![image](https://user-images.githubusercontent.com/23075670/84863810-8a585980-b0b0-11ea-8944-a0ec452bd12d.png)

혹시 x축의 값을 시간을 제외한 날짜만 나오도록 하려면 상기 검색어를 어떻게 바꾸면 되는지 공유해 주시면 도움이 될 것 같습니다.
