### ISSUE TITLE
time2sec 에 as 구문 필요합니다.

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2315]
## 기능 요청 ##
concat 과 같은 이유로 time2sec 에 as alias 기능이 필요합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
아래 사진과 같이 time2sec 명령어도 alias 기능을 사용할 수 있습니다.

![Screen Shot 2020-06-22 at 9 59 52 AM](https://user-images.githubusercontent.com/46172579/85239542-21d1f980-b46f-11ea-8aa6-d9957649f2a8.png)
