### ISSUE TITLE
[Discovery] timediff 명령어가 필요합니다.

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2316]
## 기능 요청 ##
날짜:시간 - 날짜:시간 = 초
가 되는 명령어가 필요합니다.
사용예는 장애발생날자시간, 장액복구날짜시간 두개 필드에서 장애연속시간을 구해 분석하는 일들이 많이 있습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
개발 상태: 80% (개발 내용(코드) 확인/merge/빌드 필요)

**Comment by seungfwani** [comment]
timediff 명령어를 추가하였습니다. 현재 명령어의 규칙이 메일로 공지한 규칙과 상이하여 수정 할 예정입니다.

- [명령어 문서](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/timediff.html)

추가적으로, [typecast 명령어](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/typecast.html)도 추가하였습니다.
