### ISSUE TITLE
[IRIS DB] 에서 테이블  조회 시 에러발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2317]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- demo 계정에서 만든 테이블 조회 시 "insert permission " 에러 발생

<img width="1231" alt="스크린샷 2020-06-16 오후 3 46 48" src="https://user-images.githubusercontent.com/5126497/84740759-ef487c80-afe8-11ea-97c3-24440652592c.png">

- 쿼리 이력 탭을 클릭하면 에러 팝업 창이 뜹니다.

<img width="726" alt="스크린샷 2020-06-16 오후 3 50 22" src="https://user-images.githubusercontent.com/5126497/84740862-1b63fd80-afe9-11ea-8ff6-38abe0aaf494.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
demo 계정에 웹 관련 테이블에 대한 select, insert 권한이 없어서 발생하는 문제입니다.
방금 조치하였습니다. 확인 부탁드립니다.

**Comment by seoryjj** [comment]
이제 조회됩니다. 그런데 이 권한 설정하는 메뉴가 어디에 있나요? root 로 들어가서도 테이블권한 부분은 찾기가 어렵던데요.

**Comment by veldise** [comment]
위 내용은 계정 생성시 자동으로 처리되는 부분입니다만 서버 장애 등으로 누락된 것 같습니다.

IRIS-DB 라서, 테이블 권한 설정하는 UI는 b-iris.mobigen.com 기준으로 아래와 같습니다.
IRIS-DB > 클러스터 관리 > DB > 테이블 권한 

![image](https://user-images.githubusercontent.com/3411842/86439587-cdb6f700-bd43-11ea-9a25-bfe920e489f5.png)
