### ISSUE TITLE
MariaDB: Aborted connection

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2318]
## 이슈 설명 ##
MariaDB 로그에 많은 양의 Aborted connection 로그 발생

### MariaDB 로그:
```
2020-06-17  5:21:41 193529 [Warning] Aborted connection 193529 to db: 'was' user: 'root' host: '172.17.0.1' (Got timeout reading communication packets)
2020-06-17  5:21:55 193530 [Warning] Aborted connection 193530 to db: 'was' user: 'root' host: '172.17.0.1' (Got timeout reading communication packets)
2020-06-17  5:31:30 193549 [Warning] Aborted connection 193549 to db: 'was' user: 'root' host: '172.17.0.1' (Got timeout reading communication packets)
```
### Studio 로그:
```
2020-06-17 05:21:30.068 WARN  --- [http-nio-8080-exec-1]
                com.zaxxer.hikari.pool.PoolBase : HikariPool-1 - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@69d89890 (Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
2020-06-17 05:21:30.069 WARN  --- [http-nio-8080-exec-1]
                com.zaxxer.hikari.pool.PoolBase : HikariPool-1 - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@1843575e (Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
2020-06-17 05:21:30.070 WARN  --- [http-nio-8080-exec-1]
                com.zaxxer.hikari.pool.PoolBase : HikariPool-1 - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@711b820c (Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
```

### 현재 Studio 서비스 Hikari 설정값 일부:
- local 실행 기준
- 전부 기본값으로 설정되어 있음
```
IdleTimeout: 600000
MaxLifetime: 1800000
ConnectionTimeout: 30000
ValidationTimeout: 5000
MaximumPoolSize: 10
MinimumIdle: 10
```

## 참고 ##
https://do-study.tistory.com/97
https://effectivesquid.tistory.com/entry/HikariCP-%EC%84%B8%ED%8C%85%EC%8B%9C-%EC%98%B5%EC%85%98-%EC%84%A4%EB%AA%85
https://joshefin.xyz/mariadb-hikaricp-and-connection-lifetime/
https://annajinee.tistory.com/36
https://blog.miyam.net/100
https://jsonobject.tistory.com/430
https://m.blog.naver.com/eqelizer/220329878230

**Comment by seodong9** [comment]
대전 NB-IOT 에서 일반계정으로 WEB 설치 이후 mariadb에서 동일한 로그가 발생했습니다.
로그와 함께 to many connection 오류로 인해서 WEB 접속이 불가능한 현상이 발생합니다.

<mariadb 로그>
2020-06-01 18:09:33 32 [Warning] Aborted connection 32 to db: 'was' user: 'root' host: '172.17.0.1' (Got timeout reading communication packets)
2020-06-01 18:09:33 34 [Warning] Aborted connection 34 to db: 'was' user: 'root' host: '172.17.0.1' (Got timeout reading communication packets)
2020-06-01 18:09:33 38 [Warning] Aborted connection 38 to db: 'was' user: 'root' host: '172.17.0.1' (Got timeout reading communication packets)

**Comment by swish1995** [comment]
@veldise @sedong9
지금까지의 분석 결과입니다.

- mariaDB 에서 `Aborted connection...` Warn 발생 원인
    1. mariadb.close() 를 호출하지 않고 세션이 끊어진 경우
    2. 데이터 전송중에 관련된 클라이언트 프로그램이 종료된 경우
    3. mariaDB 의 wait_timeout, interactive_timeout 동안 별도의 동작이 없는(sleep)경우    
    - 1,2,3번 모두 정상/비정상적으로 종료된 것으로 워닝 자체의 문제는 없음
    
- studio 서비스등에서 `Failed to validate connection org.mariadb.jdbc.MariaDbConnection ...` Warn 발생 원인 
    - 해당 로그는 springboot 의 커넥션 풀 관리자(HikariCP) 가 커넥션의 상태를 검사하는 중에 익셉션 처리에 의해 로그가 발생함
        - https://jaehun2841.github.io/2020/01/08/2020-01-08-hikari-pool-validate-connection/#그래서-failed-to-validate-connection-로그는-왜-나오나요
    - 정상적인 커넥션 관리절차는 다음의 절차를 따름
        - 커넥션 관리자는 적절한 방법(설정에 따라 다름) 을 사용하여 연결되어 있는 커넥션을 관리함
        - 해당 함수에서 maxlifetime 을 넘어간 커넥션에 대해서는 연결을 해제함(이때 mariaDB 에서 `Aborted connection...` 로그 생성)
    - 문제의 로그는 커넥션을 생성하지 못해서 커넥션 상태 체크시에 유효하지 못한 커넥션으로 인해 워닝이 발생
        
- mariaDB 에서 `Too many connections ...` Error 가 발생하는 원인
    - max_connection 을 초과하는 커넥션을 요청하는 경우
        - 현재 설정은 1000 개로 설정되어 있음
    - 별도의 설정이나 프로그램의 문제라기 보다 사용상의 문제로 판단됨
        
- 현재까지 도출된 결론
    - mariaDB 에서 `Too many ..` 에러로 인해 HikariCP 가 커넥션을 정상적으로 생성하지 못한 상태에서 상태 체크시 `Failed to validat ...` 워닝이 발생함 
    - HikariCP 가 커넥션을 끊기 전에 mariaDB 가 커넥선을 끊을 경우 stuio 등에서 `Failed to validat ...` 워닝이 발생함
    - maridDB 의 wait_timeout, interactive_timeout 조정 필요
        - 현재 mariaDB 의 wait_timeout 은 600 (30분), 개발 서버는 28800(8시간) 
        - 권고사항은 HikariCP 의 maxlitetime 보다 2-3 초 여유롭게 하기를 권장함
        - https://joshefin.xyz/mariadb-hikaricp-and-connection-lifetime
        - wait_timeout, interactive_timeout 을 610 정도로 조정 필요함
    - `Too many.. ` 와 관련해서는 서비스의 커넥션 관련 최적화및 mariaDB 의 max_connection 조정이 필요함 (필요시)

**Comment by veldise** [comment]
mariaDB만 아래와 같이 설정 변경했을 때에는 현상이 재현됩니다.
```
wait_timeout = 610
interactive_timeout = 610
```

**Comment by veldise** [comment]
아래와 같이 웹 서비스 쪽 설정도 변경해야 합니다.
```java
HikariDataSource ds = new HikariDataSource(config);
ds.setMaxLifetime(600000); // 600s, (기존: 1800s)
```

**Comment by sunghoon** [comment]
@veldise 최종 진행 상태 정보를 공유해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
ICP 쪽 처리를 기다리는 중이었습니다만 배포 환경이 K8S 로 변경되어 다시 논의해야 합니다.

**Comment by sunghoon** [comment]
@veldise @anhm IRIS-Cloud를 통해 배포 될때 설정을 할 수 있도록 논의해 주세요.

**Comment by anhm** [comment]
해당 이슈는 닫도록 하겠습니다.
