### ISSUE TITLE
Studio: Popup / 내부 객체 변수명이 초기화되는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2319]
## 버그 설명 ##
Studio: Popup / 내부 객체 변수명이 초기화되는 문제

ex)
Textarea 객체의 변수명을 `host`로 설정하였는데, Popup으로 불러오면 `textarea_1`으로 처리됨

**Comment by swish1995** [comment]
보고서 내부 변수명 확인결과 현재는 이상없는것으로 확인되었습니다.

**Comment by veldise** [comment]
문제가 재현되면 Reopen 하고 처리하겠습니다.
