### ISSUE TITLE
Studio: Popup / 변수 값이 0이면 Textarea 객체에 출력되지 않음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2320]
## 버그 설명 ##
Studio: Popup / 변수 값이 0이면 Textarea 객체에 출력되지 않음

## 내용
RESTful API 객체 등으로 가져온 데이터가 아래와 같을 때
```js
{
    a: 0,
    b: 1,
    c: "aaa"
}
```
Textarea 객체에 아래와 같이 설정하면
```
a: ${restapi_1.a}
b: ${restapi_1.b}
c: ${restapi_1.c}
```
아래와 같이 출력된다.
```
a: 
b: 1
c: aaa
```

**Comment by swish1995** [comment]
@veldise 테스트 케이스에서 해당 이슈가 발견되지 않고 있습니다.
@hiy2259 확인하였습니다.

**Comment by veldise** [comment]
문제가 재현되면 Reopen 하고 처리하겠습니다.
