### ISSUE TITLE
[playGround] Rstudio 를 클릭하면 로그인창이 뜨는데, iris 사용자계정으로 들어갈 수 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2321]
## 버그 설명 ##
b-iris  / demo 계정
* Rstudio 를 클릭하면 로그인 창이 뜹니다.

<img width="877" alt="스크린샷 2020-06-17 오전 10 39 25" src="https://user-images.githubusercontent.com/5126497/84845220-0dfd5080-b087-11ea-82b6-b9fe9ae0c2fb.png">

* demo계정을 입력해도 에러 문구 없이 그대로 로그인창이 뜨면서 들어가지지 않습니다.
<img width="303" alt="스크린샷 2020-06-17 오전 10 43 19" src="https://user-images.githubusercontent.com/5126497/84845358-69c7d980-b087-11ea-8d70-b7441949dc63.png">

* 혹시나 싶어 root를 치면 이런 에러 문구가 뜹니다.
<img width="302" alt="스크린샷 2020-06-17 오전 10 43 09" src="https://user-images.githubusercontent.com/5126497/84845387-7f3d0380-b087-11ea-8a9f-7764f12157f7.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @ollehQ 상황 확인 바랍니다.

**Comment by anhm** [comment]
해당 문제는 과거 ext-manager에서 로그인이 잘못 되었을 경우 발생하는 문제입니다.
현재는 play-ground로 교체된 상태이며, 해당 이슈가 다시 발생하는지 확인이 필요한 상태입니다.
