### ISSUE TITLE
차트의 데이터 표시 색상

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2322]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.

차트의 데이터 표시색상이 자꾸 변하는 상황 발생

-> 장애 = 분홍색 / 정상 = 파란색으로 표시하고 싶음

현재 상태 :
![image](https://user-images.githubusercontent.com/16331916/84845636-0d18ee80-b088-11ea-8a3e-7334821280a4.png)

 위와 같이 적용했을 경우 모두 정상일 경우 분홍색으로 나오고,
정상, 장애가 나올 경우
정상 = 파란색, 장애 = 분홍색이 나옴.

순서를 바꿀경우 모두 정상일 경우 파란색이 나오지만
정상, 장애가 모두 나올 경우
정상 = 분홍색, 장애 = 파란색

![image](https://user-images.githubusercontent.com/16331916/84845840-7b5db100-b088-11ea-80ac-341c87eed368.png)

데이터와 맞물려서 어떤 그룹을 어떤 색으로 조정할지에 대한 기능이 추가되면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by rhcpn** [comment]
해당 기능은 안내한대로 데이터의 순서와 관계가 있습니다.
따라서 현 시점에는 출력하고자 하는 데이터를 정렬하여 사용해주세요.
