### ISSUE TITLE
데이터 시각화에서 integer 값에 소수점이 표시되는 경우

### ISSUE THREAD

**Issue by AliceLiddell** [mobigen/IRIS-BigData-Platform#2323]
## 버그 설명 ##
데이터 시각화 차트에서 데이터 모델 타입이 integer임에도 소수점이 붙어나오는 문제

## 재현하는 방법 ##
동일한 아이디라도 서로 다른 결과가 나타남
총 4대의 pc로 동일한 크롬으로 동일한 사용자로 하였지만 2대에서는 소수점이 없는 상태, 2대는 소수점이 있는 상태로 표시
재현을 어떻게 할수 있는지는 알수 없음

## 예상한 행동 ##
시각화 차트에서 integer인 경우는 소수점이 표시가 안됨

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/6723557/84855049-2462d680-b09e-11ea-92eb-22406fd9c65d.png)

수원시의 요청으로 인해 최대한 빠른 시간 내에 수정 부탁드립니다.

**Comment by veldise** [comment]
일단 어제(7/16) 패치로 해결되었습니다. 혹시 재현되면 Reopen 해주시기 바랍니다.
