### ISSUE TITLE
[Discovery] replace 에서 컬럼에 없는 패턴으로 replace 하면 에러 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2326]
## 버그 설명 ##
b-iris  demo 계정 
데이터모델  DEMO_PIVOT

* '기능' 컬럼에 )  가 없는 경우, 에러 발생하며, 에러내용 보완이 필요해보입니다.
`* | replace 기능 ")" "\."`

<img width="526" alt="스크린샷 2020-06-18 오전 8 39 46" src="https://user-images.githubusercontent.com/5126497/84961543-993a1d00-b13f-11ea-8069-e12da3ed05f0.png">

* '기능' 컬럼에 있는 패턴은 정상으로 나옵니다.
`* | replace 기능 "\." "==="`

<img width="1156" alt="스크린샷 2020-06-18 오전 8 43 02" src="https://user-images.githubusercontent.com/5126497/84961638-c5559e00-b13f-11ea-8b2f-8bf660bcc46f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
개발완료
배포 7/31(금) 예정

**Comment by seungfwani** [comment]
배포 완료 했습니다.

![Screen Shot 2020-07-31 at 5 06 16 PM](https://user-images.githubusercontent.com/46172579/89014210-27fda480-d350-11ea-9dac-7c066c492835.png)
