### ISSUE TITLE
[Analyzer] 에서 fit 으로 저장한 모델이 없다고 나옵니다(->mlmodel 이 저장되는 minio 서버문제로 예상)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2328]
## 버그 설명 ##
b-iris  demo 계정
에러없이 fit 으로 모델을 생성했지만, mlmodel list 에서 보이지 않습니다.
**DEMO_RF_CLASSIFICATION_FLOWER_0618**

* 참고
6월16일 까지만 mlmodel  이 있는 것으로 봐서 
지난 번처럼 mlmodel 이 저장되는 MINIO  서버 문제로 예상됩니다.
만약 동일한 문제라면 b-iris 를 서비스할 때 
필수적으로 체크해야 할 서버 및 데몬, app 등이 모두 정상 동작하는 지 점검하는 process 가 필요합니다.
mlmodel 을 생성하는 것은 시간이 많이 걸리는 작업인데, 힘들게 생성한 모델이 저장되지 않는다면... 문제가 될 것 같습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
운영 장애 상황이였으며, 지금은 해결되었습니다.
