### ISSUE TITLE
[개인설정] 화면에서 소수점을 변경하면 이상한 팝업이 뜨고,  검색결과 소수점은 변경되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2329]
## 버그 설명 ##
b-iris.mobigen.com  /  demo 계정 / 사파리

* 개인설정 변경 : 소수점 0 으로 변경
<img width="991" alt="스크린샷 2020-06-19 오전 7 47 17" src="https://user-images.githubusercontent.com/5126497/85080364-f1d2ee00-b203-11ea-9e17-d97628c4dfb9.png">

* 저장 누르면 뜨는 팝업창
<img width="433" alt="스크린샷 2020-06-19 오전 7 47 02" src="https://user-images.githubusercontent.com/5126497/85080404-0b743580-b204-11ea-91b1-e40fa6e41784.png">

* 위의 팝업창 닫기 누르면 뜨는 팝업창
<img width="434" alt="스크린샷 2020-06-19 오전 7 47 09" src="https://user-images.githubusercontent.com/5126497/85080429-1b8c1500-b204-11ea-805b-ce77da68df97.png">

* Analyzer 에서 검색어를  "round 0"  로 정수로 만든 후 결과는 여전히 소수점 2개로 정수.00 으로 표시
<img width="1387" alt="스크린샷 2020-06-19 오전 7 57 26" src="https://user-images.githubusercontent.com/5126497/85080471-3a8aa700-b204-11ea-993d-16bc9facb312.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
해당 현상 재현이 되지않습니다.
현상 발생시, 자세한 사항을 추가해주시면 확인하도록 하겠습니다.

**Comment by veldise** [comment]
금일 08:10 경에 sherman 서비스 배포를 했었는데 영향이 있었던게 아닌가 싶습니다.

**Comment by seoryjj** [comment]
배포 영향이 맞나 봅니다. 지금은 팝업도 안뜨고, 결과도 바로 나옵니다.  close 하겠습니다.
