### ISSUE TITLE
IRIS 메인 아이콘의 위치가 아래쪽으로 내려가 있습니다 (사파리)

### ISSUE THREAD

**Issue by joohj7** [mobigen/IRIS-BigData-Platform#2330]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
크롬 버전과 다르게 사파리에서 IRIS 로고가 상대적으로 내려가 있는듯 합니다. 
확인 부탁 드립니다. 
## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
<사파리버전>
<img width="667" alt="스크린샷 2020-06-19 오전 9 38 00" src="https://user-images.githubusercontent.com/36151180/85084794-cf939d00-b210-11ea-83b2-ad65b22e7a06.png">

<크롬버전>
<img width="783" alt="스크린샷 2020-06-19 오전 9 38 08" src="https://user-images.githubusercontent.com/36151180/85084784-c9052580-b210-11ea-80af-9654ffeb0535.png">

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
현재 IRIS 메인(메뉴)페이지는 IE11 이후 버전과 Chrome을 대상으로 제작되었습니다.
내부적으로 Safari 지원을 계획하고 있으며, 추후 제공될 예정입니다.
