### ISSUE TITLE
[Discovery] DSL 명령어 calculate 에서 FLAG 를 right 로 설정해도 위치가 변경되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2331]
## 버그 설명 ##
b-iris.mobigen.com / demo 계정 /  사파리

calculate 의 결과 컬럼 위치가 디폴트 right 이지만, 계속 앞(left) 로 나옵니다.

`* | calculate add  row  Sepal_Width, Petal_Width  right`

<img width="1434" alt="스크린샷 2020-06-19 오전 10 25 27" src="https://user-images.githubusercontent.com/5126497/85087187-c22de100-b217-11ea-8c5b-1c95d837f47c.png">

* 처음에는 필드에 결과 컬럼이 선택이 안되어 있어서 안나옵니다.
<img width="271" alt="스크린샷 2020-06-19 오전 10 32 10" src="https://user-images.githubusercontent.com/5126497/85087427-7c254d00-b218-11ea-9059-502305baba45.png">

* 체크 하면 제일 처음 으로 올라옵니다.
<img width="268" alt="스크린샷 2020-06-19 오전 10 32 29" src="https://user-images.githubusercontent.com/5126497/85087456-8e9f8680-b218-11ea-9cc5-82feee7efb6a.png">

* 결과 right 로 해도 위치가 변하지 않습니다.
<img width="1144" alt="스크린샷 2020-06-19 오전 10 32 39" src="https://user-images.githubusercontent.com/5126497/85087482-9fe89300-b218-11ea-990b-e58e1dab018d.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@veldise 
검색화면에서 원본 데이터 컬럼이 아니면, 선택이 되지 않은 상태로 표시가 됩니다.
![Screen Shot 2020-06-19 at 2 31 26 PM](https://user-images.githubusercontent.com/46172579/85100014-fca87580-b239-11ea-8d59-c1a497f87484.png)

이때, 새로운 컬럼을 선택하면, 1번째 컬럼으로 보여지게 됩니다.
![Screen Shot 2020-06-19 at 2 31 57 PM](https://user-images.githubusercontent.com/46172579/85100027-029e5680-b23a-11ea-8259-ebc990dd208a.png)

하지만, 사용자가 원하는 것은 가장 오른쪽 컬럼에 데이터가 보여지기를 원합니다.
어떻게 하면 좋을지 문의드립니다.

추가>
Studio 에서는 새로운 컬럼은 무조건 오른쪽에 붙는 것 같습니다.
- 스튜디오화면
![Screen Shot 2020-06-19 at 2 32 35 PM](https://user-images.githubusercontent.com/46172579/85100081-28c3f680-b23a-11ea-829e-78af937b38d0.png)
- 컬럼 리턴 순서
![Screen Shot 2020-06-19 at 2 35 56 PM](https://user-images.githubusercontent.com/46172579/85100095-324d5e80-b23a-11ea-9b1d-a030ca79ebc0.png)

**Comment by veldise** [comment]
@seungfwani 
순서 관련해서 확인해보겠습니다.

**Comment by veldise** [comment]
UI 에서 쿠키에 저장된 필드목록 기준으로 정렬을 하는 동작이 있습니다.
이 동작을 제거 하겠습니다.
