### ISSUE TITLE
[Analyzer] 컬럼카피기능이 컬럼이름 위에서도 동작하면 더 좋을것 같습니다.

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2332]
## 기능 요청 ##
![스크린샷 2020-06-19 오후 1 54 44](https://user-images.githubusercontent.com/3468426/85098145-b6044c80-b234-11ea-864a-ac592f3c4f87.png)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by rhcpn** [comment]
리스트에 사용중인 AG-GRID가 현재 Community 버전이라서 해당 기능을 당장 구현하지 못했습니다.
우선 해당 부분은 현재의 우클릭 > 팝업에서 선택 방식과 조금 다른 방식으로 구현 될 예정입니다.

**Comment by veldise** [comment]
아래와 같이 기능이 추가될 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/92352369-e7e0cd00-f118-11ea-90da-00eea492b7a3.png)

![image](https://user-images.githubusercontent.com/3411842/92352385-ee6f4480-f118-11ea-83c4-63f4f9be2f44.png)
