### ISSUE TITLE
앙고라 명령어 개발 중 스키마 추출을 위한 defaultdict 객체 추가 요청

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#2333]
## 기능 요청 ##
angora 내부 모듈 개발시 상속 부모객체(simplecommand, basecommand)에 schema dictionary 추가 요청드립니다.
검토부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
원래 방식의 경우 아래와 같이 스키마를 추출하는 과정이 필요함.
<img width="433" alt="스크린샷 2020-06-22 오전 10 39 43" src="https://user-images.githubusercontent.com/32768535/85240847-b0954500-b474-11ea-8daf-e0d0ff9c29e6.png">

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }
<img width="509" alt="스크린샷 2020-06-22 오전 10 40 30" src="https://user-images.githubusercontent.com/32768535/85240885-cd317d00-b474-11ea-83a0-be8fa792c22b.png">
상기와 같이 스키마에 대한 defaultdict객체를 만들어 두면 스키마 추출 코드가 가독성이 높아진다고 판단
<img width="533" alt="스크린샷 2020-06-22 오전 10 41 29" src="https://user-images.githubusercontent.com/32768535/85240925-f18d5980-b474-11ea-85fd-a0448a1ee33c.png">

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
해당 내용이 pandas 라이브러리의 타입과 spark 타입을 매핑하는 것에 대한 요청 인가요?

위와 같은 내용이 맞다면 아래와 같은 이유로 적절한 기능인지 확인이 필요합니다.
- pandas 라이브러리는 비교적 적은양의 데이터를 분석하기 위한 도구로 알고있습니다.
  - 단일 노드에서 데이터를 분석 함으로써, 메모리 이슈 발생가능성 증가
- 앙고라는 대용량 분산처리를 위해서 spark dataframe 을 이용한 데이터 분석을 하고 있습니다.
- spark DF -> pandas DF -> spark DF 로 변환이 되는 것은 큰 오버헤드가 요구 될 수 있으며, 서비스에 문제가 일어 날 수 있어, 앙고라 명령어에서 **지양**하는 로직입니다.
  - 몇몇 명령어가 해당 로직으로 되어 있어, 데이터가 커지면 동작에 문제가 발생하는 경우가 있습니다.

**Comment by GyuminJack** [comment]
상기 우려하시는 사항 확인했습니다.

그렇다면 혹시 앙고라에서 결과로 return할 dataframe을 만들때에 입력되는 schema 정보를 추출하는 방식을 알수 있을까요?

결과로 출력될 모든 컬럼에 대해 일일이 타입을 지정하는 것인지 궁금합니다.

**Comment by seungfwani** [comment]
현재 IRIS 데이터 타입은 아래와 같습니다.
| IRIS Type | Python Type  |
| :-------: | ------------- |
|TEXT | string |
|REAL| float|
|INTEGER| int|
|BIGINT| long |
|DATE| datetime.date|
|TIMESTAMP|datetime.date|

앙고라는 먼저 데이터를 읽어온 후, `새모델` 만들기에서 지정한 타입으로 캐스팅을 하게 됩니다.

이후 연산을 통해 추가된 컬럼 등은, 각 데이터에 맞는 타입으로 생성이 되며, _1. 직접 지정 방식_과 _2. 데이터를 통한 추론 방식_ 을 사용하고 있습니다.

spark dataframe 의 스키마 정보를 확인 하는 방법은 아래와 같습니다.
```
# create DataFrame
>>> df = spark.createDataFrame([[1,2,3]], schema=['A','B','C'])
# get Schema of DF
>>> print(df.schema)
# show DF
>>> df.show()
```

**Comment by GyuminJack** [comment]
그러면, 명령어 개발시에는 판다스를 통해서 컬럼의 타입을 추론하는 것을 지양해야하며, 가능하다면 결과로 리턴할 객체의 스키마를 직접 리스트로 구성하고, 이를 sqlCtx.createDdataFrame에 넘기는 것이 바람직하다고 생각하면 될까요?
