### ISSUE TITLE
[ES연동]Elasticsearch 데이터 검색 시 오류 발생

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#2335]
## 버그 설명 ##
타사 ES와 연동하여 데이터모델을 정상적으로 생성하였으며,
검색 화면에서도 전체시간으로는 검색이 되나,
최근 24시간, 날짜/시간 범위 설정으로 검색 시 에러가 발생됨.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS Discovery Service에서 타사의 ES 연결 및 데이터 모델 생성 시, 에러없이 정상 동작
    (아래 스크린샷 1. 참조)
2. IRIS Analyzer의 검색 화면에서 전체시간으로 검색 시, 정상 동작
    (아래 스크린샷 2. 참조)
3. 시간 탭에서 최근 xx 또는 날짜 및 시간 범위 설정 후 검색 시 에러 발생
    (아래 스크린샷 3. 참조)

## 스크린샷 ##
* 스크린샷 1.
![image](https://user-images.githubusercontent.com/23075670/85347536-cc135500-b533-11ea-9599-b0ede7251c21.png)

* 스크린샷 2.
![image](https://user-images.githubusercontent.com/23075670/85347559-de8d8e80-b533-11ea-84d2-421dd52d3829.png)

* 스크린샷 3.
![image](https://user-images.githubusercontent.com/23075670/85347539-cfa6dc00-b533-11ea-833c-18e18ea19e88.png)

**Comment by sunghoon** [comment]
@seungfwani 오류 확인 바랍니다.
