### ISSUE TITLE
알 수 없는 원인으로 데이터를 조회할 수 없음

### ISSUE THREAD

**Issue by krjwpark** [mobigen/IRIS-BigData-Platform#2336]
## 버그 설명 ##
알 수없는 원인으로 데이터를 조회할 수 없음.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to IRIS DISCOVERY
2. MELT_SEOUL_FIRE_CAUSE 공유된 데이터 모델 복사
3. IRIS Analyzer에서 복사된 MELT_SEOUL_FIRE_CAUSE 선택, 조회
4. 에러: NoneType object is not subscriptable

## 예상한 행동 ##
테이블 내용이 표시됨

## 스크린샷 ##
![s1](https://user-images.githubusercontent.com/37128240/85349452-6de97080-b539-11ea-87ee-2071bdb370d8.PNG)
![s2](https://user-images.githubusercontent.com/37128240/85350215-8195d680-b53b-11ea-8a96-5c6528e350de.PNG)

**Comment by seungfwani** [comment]
현재 해당 이슈가 재현되지 않고, 정상 실행 됩니다.
우선 이슈 페이지는 닫도록 하겠습니다.

![Screen Shot 2020-07-21 at 1 50 07 PM](https://user-images.githubusercontent.com/46172579/88014143-2ca8a880-cb59-11ea-90c5-263f35a20c97.png)
