### ISSUE TITLE
[Analyzer/DSL] count 문을 실행하면 에러가 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2338]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정
데이터모델  : EDU_Beijing_air_2013_2017_18

* count 문 
`* |  count`
<img width="289" alt="스크린샷 2020-06-24 오전 8 51 51" src="https://user-images.githubusercontent.com/5126497/85479096-7c4a9180-b5f8-11ea-9e0f-863046efc755.png">

* sql 문이나  where, pivot 등은 정상 동작
<img width="976" alt="스크린샷 2020-06-24 오전 8 54 55" src="https://user-images.githubusercontent.com/5126497/85479144-94221580-b5f8-11ea-8856-95814321d211.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@seoryjj 
검색 창에서 검색을 실행 할 경우
1. `model-timeline ...` 
2. `model ... | count` 
3. `model ... `
명령어가 실행이 됩니다.

검색 창의 문법으로
`* | count` 를 입력 할 경우 2번 명령어가 `model ... | count | count` 형태로 변하게 되어 발생한 문제입니다.

@veldise 
웹에서 보내는 쿼리는 `검색 DSL + | count ` 가 맞으나, count 같은 경우 어떻게 해야 할지 문의드립니다..

**Comment by seoryjj** [comment]
count 문이 Saas 에 적용되어 있다면 angora  에서 수정을 해야 할 거 같은데요. 
만약 Saas 에 적용 전이라면  row_count  로 명령어(DSL) 를 수정하면 안될까요?

**Comment by seungfwani** [comment]
다시 확인해보니 앙고라에서 변경한 로직에서 처리가 덜 된 것으로 확인 되었습니다.

해당 내용은 수정 하였고, 지금 시도해보시면 문제 없이 동작합니다.
![Screen Shot 2020-06-24 at 2 56 41 PM](https://user-images.githubusercontent.com/46172579/85506233-ed0aa180-b62a-11ea-8a40-d2aecb8b3f79.png)

**Comment by seungfwani** [comment]
이슈 닫겠습니다.
같은 문제 발생시 다시 오픈 하도록 하겠습니다.
