### ISSUE TITLE
[수원시][Studio] 보고서-차트,지도 자동실행을 default 로 체크해달라는 요청사항이 들어왔습니다.

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2339]
![image](https://user-images.githubusercontent.com/19259399/85505075-6fde2d00-b628-11ea-8a27-33757ee76438.png)

수원시에서 보고서 이용시 자동실행을 일일이 체크하기 번거롭다고 default 값이 체크값이면 좋겠다는 요청사항이 들어왔습니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
예제 보고서가 아닌 실제 보고서를 작성할 때에는 자동실행을 사용하는 경우는 크게 많지 않을 것으로 생각됩니다.
또한 자동실행을 기본으로 하였을 경우, 사용자의 작성 실수가 있을 때 데이터 서버로 잘못된/빈번한 요청이 전송되어 서버 부하를 가중시킬 수도 있을 것입니다.
따라서 **자동실행은 지금처럼 체크가 해제된 것을 기본으로 유지**하고자 합니다.

**Comment by sunghoon** [comment]
@yoonah95 위와 같이 최종 정리되었습니다. 업무에 참고하시기 바라비다. 이슈는 닫겠습니다.
