### ISSUE TITLE
[Analyzer] 피벗-원형 분석시 데이터 누락이 발생합니다.

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2340]
## 버그 설명 ##
피벗 분석 - 원형 분석시 몇몇 데이터가 누락되어 기준일 표시가 되지 않습니다.
또한 png 파일로 저장시 더 많은 데이터가 누락되어 나타납니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/19259399/85505568-92bd1100-b629-11ea-964f-809d1ac84470.png)
<피벗-원형 분석>
![image](https://user-images.githubusercontent.com/19259399/85505592-9f416980-b629-11ea-8209-d20612257e7b.png)
<저장된 png 파일>

**Comment by rhcpn** [comment]
해당 사항은 화면 상으로 봤을때 누락이라기 보다 차트에서 데이터 라벨을 임의로 (영역이 작고, 표시 할 공간이 없어서) 표시 하지 않는 상황으로 보이는데요, 추측한 상황이 맞을까요?

**Comment by yoonah95** [comment]
> 해당 사항은 화면 상으로 봤을때 누락이라기 보다 차트에서 데이터 라벨을 임의로 (영역이 작고, 표시 할 공간이 없어서) 표시 하지 않는 상황으로 보이는데요, 추측한 상황이 맞을까요?

네 맞는
