### ISSUE TITLE
[Analyzer] 통계탭 결과의 컬럼이름 / 상위메뉴이름이 안보입니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2341]
## 버그 설명 ##
b-iris.mobigen.com   demo 계정 크롬브라우저
분석탬플릿 이름 : 이슈_EDU_Beijing_통계탭_컬럼명안보임

검색어 창의 fields 뒤의 컬럼이름이 나와야 합니다.

![그림1](https://user-images.githubusercontent.com/5126497/85504653-6accae00-b627-11ea-9fdd-30a13518df04.png)

그런데 새탭으로 열기로  동일한 검색어를 실행하면 새 탭에서는 컬럼이 제대로 보입니다.
즉 컬럼이름이 **보였다 안보였다** 합니다. 
하지만 새탭에서는 컬럼이름은 보이는데, 이번에는 상위 메뉴이름이 안보입니다.

<img width="1078" alt="스크린샷 2020-06-24 오후 2 41 54" src="https://user-images.githubusercontent.com/5126497/85505625-b6805700-b629-11ea-9d8a-1422ef940f38.png">

컬럼이름이 보이지 않은 첫번째 탭에서는 동일 검색어를 다시 실행해도 계속 안보입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
요청 사항이 있습니다.
한가지는 첫번째/두번째 사용하신 쿼리문을 올려주실수 있을까요? 테스트에 도움이 될것 같습니다.
또한가지는 혹시 브라우저를 Safari를 사용하신걸까요?

**Comment by seoryjj** [comment]
위에 첫 줄에 적은 내용대로

b-iris.mobigen.com demo 계정 크롬브라우저
분석탬플릿 이름 : 이슈_EDU_Beijing_통계탭_컬럼명안보임

를 참고하세요

**Comment by lyj** [comment]
새창에서 메뉴가 안보이는 현상은 IWP(메뉴 관련 프로젝트)에서 처리 예정입니다.

**Comment by lyj** [comment]
> 새창에서 메뉴가 안보이는 현상은 IWP(메뉴 관련 프로젝트)에서 처리 예정입니다.

IWP현상은 처리되어 배포하였습니다.

**Comment by veldise** [comment]
컬럼명이 나오지 않는 문제가 패치 이후 재현이 되지 않아 닫습니다.
혹시 재현되면 이슈 reopen 해주시기 바랍니다.

![image](https://user-images.githubusercontent.com/3411842/90840075-fa76aa80-e393-11ea-9ff4-7dc48d1043a4.png)
