### ISSUE TITLE
ElasticSearch 연동시 Index 정보에 정규식? 적용 기능 요청

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2342]
- 아래와 같은 동작이 정상적으로 수행 될 수 있도록 내용 검토 및 기능 개발을 요청합니다.

- @seungfwani DSL 레벨에서 해당 기능 수용 가능한지 검토 후 의견을 주세요.
- @rhcpn @veldise UI 기능 관련 처리 검토 후 의견 주세요.

- 비교적 간단한 내용으로 생각되며, 외부 사업 연결부분이 있어 급하게 요청드립니다. 

![스크린샷 2020-06-24 오후 4 23 48](https://user-images.githubusercontent.com/512653/85514514-16312f00-b637-11ea-8c16-2544d19fdac2.png)

**Comment by seungfwani** [comment]
앙고라에서는 `*` 문자를 통해 비교적 간단한 데이터를 읽는 테스트를 성공 하였습니다.
- ES 데이터
![Screen Shot 2020-06-24 at 8 20 54 PM](https://user-images.githubusercontent.com/46172579/85546917-5a80f700-b658-11ea-8ea7-169c1feb01a8.png)

- Angora Read
![Screen Shot 2020-06-24 at 8 22 59 PM](https://user-images.githubusercontent.com/46172579/85547097-81d7c400-b658-11ea-80ff-cdb8d925ade3.png)

**Comment by veldise** [comment]
현재 해당 Combo-box의 입력란(input)은 필터 동작만 수행하게 되어있습니다.
기능을 변경하려면 '적용' 버튼을 추가한다던가 기획이 필요합니다.

일단 임시 조치로 '대상 데이터' Combo-box의 필터 입력란에서 Enter 키를 입력하면
Combo-box 항목을 선택한 것과 동일하게 동작하도록 해보겠습니다.

**Comment by veldise** [comment]
동작 확인했습니다.

![image](https://user-images.githubusercontent.com/3411842/85808023-a2099f00-b78e-11ea-8a33-1821a5bcdd82.png)

![image](https://user-images.githubusercontent.com/3411842/85808050-b9e12300-b78e-11ea-8f78-452e294ef9f9.png)

**Comment by sunghoon** [comment]
원하는 동작으로 정리가 된것 같습니다.
