### ISSUE TITLE
[개인설정] 화면에 닫기 버튼이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2343]
## 기능 요청 ##
Studio 에서 작업을 하다가 개인설정에서 소수점 설정을 변경하고 저장했습니다.
그런데 닫기 버튼이 없어서
다시 Studio 메뉴를 눌러서 보고서를 열어야 합니다.

이런 설정 화면은 작업 중에 설정한 대로 결과가 나오는지 확인을 하기 때문에
닫기 버튼을 누른 후 이전 작업 화면(Studio 나 Analyzer) 에서 계속 작업을 이어나가게 하면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by lyj** [comment]
http://b-iris.mobigen.com 사이트 에서 실행하신 내용인가요?
