### ISSUE TITLE
[Studio] 에서 챠트의 시각화옵션에  X축, Y축, 데이터에 소수점설정을 추가해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2344]
## 기능 요청 ##
숫자로 된 컬럼이 X 축으로 사용될 때는 소수점 0 로 사용하고 싶고,
값은 소수점 2 자리로 표시하고 싶습니다.

예를 들어 
month 컬럼이 숫자형으로 되어 있어야 sorting 하면 1,2,3,, 12 로 나옵니다. 
string 으로 sorting 하면 1,11,12,2,3,, 이렇게 나오므로 **숫자형으로**  만들어서 X 축으로 둡니다. 
그 때는 월이니까 1,2,3,,,12 로 표시하고
챠트의 데이터값은 소수점 N자리 까지 표시해서 챠트를 그려야 하는 일이 많습니다...

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
