### ISSUE TITLE
[NMS+]Oracle 연동시 제공가능 제한버전 확인요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2345]
## 버그 설명 ##
SKB 고객사에서 다른시스템의 Oracle DB 를 연동하여 데이터모델을 생성하려고하는데 아래와 같은 에러가 난다고합니다.

사용가능한 버전 제한 정보 확인 부탁드립니다. 
( 몇이상 사용 가능 이런 문구를 명확히 하는게 좋을거같습니다. )

- 연결하려는 oracle db 의 버전 정보 : Oracle9i Enterprise Edition Release 9.2.0.8.0 - 64bit Production

![image](https://user-images.githubusercontent.com/5468183/85642059-4b875c80-b6cb-11ea-9364-60c9ccaf896a.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
연결정보 관리자(DSMS) 에서는 `cx-Oracle==7.1.2` 라이브러리를 이용하여 oracle DB 와 연결 테스트를 하고 있습니다.
이 버전은 11 버전 이상으로 지원을 하고있습니다.

추가로,
[JDBC 가이드](https://docs.oracle.com/database/121/JJDBC/getsta.htm#JJDBC20000) 에 따르면, 
아래 내용과 같이 `oracle database 11g realease 1` 버전 부터는 `ojdbc6.jar` 과 `ojdbc7.jar` 을 사용할 수 있다고 명시 되어있습니다.

`Discovery-Service` 에서는 spark에 `ojdbc6.jar` 를 사용하여 oracle 데이터를 가져오도록 하고있습니다.

![Screen Shot 2020-06-30 at 4 15 46 PM](https://user-images.githubusercontent.com/46172579/86095517-fc876000-baec-11ea-83dd-49f07e8d3e11.png)

-------

`Oracle9i Enterprise Edition Release 9.2.0.8.0 - 64bit Production` 버전을 지원하기 위해서는
1.환경구축 2.서비스와 테스트 를 해야하기 때문에 시간이 걸립니다.

**Comment by sunghoon** [comment]
@seungfwani 최종 진행 상태 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
해당 버전을 지원 해야한다면 환경구축 및 테스트를 해야하고,

제한버전 확인 이라면 닫도록 하겠습니다.

제한버전: oracle version 11 이상

**Comment by sunghoon** [comment]
@seungfwani 
외부 연동 시스템 중에 오래된 시스템이 있을 수 있으니 지원을 해야 합니다.
mysql5  처럼 하위 버전 type을 정의하고 지원할 수 있도록 준비해 주세요.
기능 제공 목표 일자를 알려주세요.

**Comment by seungfwani** [comment]
개발, 테스트 후 10월 16일 전으로 전달하도록 하겠습니다.

**Comment by seungfwani** [comment]
@jjinylee @anhm 

개발은 따로 진행 할 수 있을 것 같으나, 테스트를 위해서 해당 버전을 어떻게 설치하면 좋을지 문의드립니다.
버전 : *Oracle9i Enterprise Edition Release 9.2.0.8.0 - 64bit Production*

참조: @sunghoon

**Comment by sunghoon** [comment]
시험 환경 구성 이슈로 인해 처리 완료 일정을 수정하였습니다.

**Comment by sunghoon** [comment]
@안형민 최종 상태 정보 Update 해 주세요.

**Comment by sunghoon** [comment]
@anhm @seungfwani @jjinylee 해당 이슈는 어떻게 처리 해야 하나요? 지원 없이 그냥 두어도 되는건지요?

**Comment by anhm** [comment]
해당 이슈는  원하는 oracle 버전을 지원받지 못한 상태가 지속되어 이슈를 닫도록 하겠습니다.
특정 버전이 필요하실 경우에는 버전을 제공하여, 테스트를 요청하는 이슈를 다시요청 하시기를 부탁 드립니다.
