### ISSUE TITLE
[Studio] IE11에서 보고서 불러오기 팝업이 한번 이상 동작 시킬수 없는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2346]
## 버그 설명 ##
IE1 > 보고서에서 "보고서 팝업" 기능으로 다른 보고서를 팝업창을 띄우면 한번은 잘 나오는데
두번째 부터는 나오지 않고 개발자 도구로 보면 아래와 같은 에러가 발생함 

## 스크린샷 ##
![IE11에서_보고서팝업두번째부터_에러](https://user-images.githubusercontent.com/11566844/85645224-0ddb0180-b6d4-11ea-9b24-c58fb29a92d4.png)

**Comment by tylor-kr** [comment]
## 테스트
* 서버: 192.168.100.180
* 해당 보고서: #2346
* 팝업을 한번 열고 닫은 뒤, 다시 열면 아래와 같은 코드 에러가 발생하면서 팝업이 다시 열리지 않음

---

## IE11
### 버전 정보
![image](https://user-images.githubusercontent.com/13827425/86302032-79781e00-bc42-11ea-9677-969f042a205e.png)
### 개발자 도구
![image](https://user-images.githubusercontent.com/13827425/86302006-66fde480-bc42-11ea-9133-b5259651bef5.png)

---

## 크롬
### 버전 정보
![image](https://user-images.githubusercontent.com/13827425/86302136-cfe55c80-bc42-11ea-92c4-0b18a3d2ecdd.png)
### 개발자 도구
![image](https://user-images.githubusercontent.com/13827425/86302100-ab898000-bc42-11ea-8a9b-30c22bb31564.png)
### 화면
![image](https://user-images.githubusercontent.com/13827425/86302109-b2b08e00-bc42-11ea-8835-d0be112c4045.png)

**Comment by veldise** [comment]
위 에러는 다른 객체의 문제로 확인되어 바로 조치하였습니다.

**Comment by tylor-kr** [comment]
정상 동작 확인 하였습니다.
