### ISSUE TITLE
[Analyzer] 피벗-원형 분석시 일부 데이터 누락

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2347]
## 버그 설명 ##
피벗-원형 분석시 일부 데이터 누락되어 기준일 표시가 안되어 나타납니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/19259399/85653509-19d0be80-b6e8-11ea-8cc4-817fc603aadd.png)

png 파일로 저장시 일부 기준일이 표시가 안되어 나타납니다.

## 기타 ##
답변을 주셨는데 실수로 이슈를 삭제하여 다시 올립니다.
공간이 모자라 일부 기준일이 안뜬거같다고 하셨는데 주신 의견이 맞는거 같습니다.
이럴경우 다른 방법이 없는건가요?

**Comment by veldise** [comment]
본문 상황은 데이터 누락이라기보다는 데이터 레이블(dataLabels)가 누락(missing)된 상황입니다.
이 문제는 원형 차트의 조각 개수가 너무 많아서 데이터 레이블을 그릴 공간이 부족해져서 발생하는 문제입니다.

조각 개수를 줄이도록 summary 조건을 줄이는 것으로 해결할 수 있을 것입니다. (1개월 -> 3개월)
만약 데이터 수치가 균등하지 않다면 시각화 메뉴에서는 아래와 같은 옵션을 고려해볼 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/85821271-3ab21600-b7b3-11ea-9e09-b4015964617a.png)

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
