### ISSUE TITLE
IE 11 이상의 호환성 문제

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2349]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

 팝업창을 띄우는 기능이 Chrome 에서는 반복적인 실행, 종료가 되는데,

IE 11 에서 실행시 1번만 실행, 종료가 되고 2번째부터의 실행에서는 아무런 반응이 없습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#2346 과 동일한 문제로 생각됩니다.

**Comment by veldise** [comment]
2345 이슈가 해결되어 닫습니다.
