### ISSUE TITLE
Studio: Chart / 특정 상황에서 가로막대 차트가 비정상적으로 그려지는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2353]
## 버그 설명 ##
Studio: Chart / 특정 상황에서 가로막대 차트가 비정상적으로 그려지는 문제

## 스크린샷 ##
- 꺾은선이나 세로막대형 차트가 잘 나오도록 설정한 뒤, 가로막대형으로 유형을 전환하면 발생

![image](https://user-images.githubusercontent.com/3411842/85961221-f35e9c00-b9e3-11ea-90f4-275542e16c0a.png)

**Comment by veldise** [comment]
수정 내용을 적용하려면 데이터 마이그레이션을 수행해야 해서, 다른 방법을 모색해야 합니다.

**Comment by sunghoon** [comment]
@veldise 계획된 일정으로 진행 되고 있는지요?
