### ISSUE TITLE
Studio로 생성된 보고서를 PDF 문서로 저장하는 기능

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2355]
## 기능 요청 ##

Studio로 작성된 보고서를 pdf문서로 저장 하는 기능 필요

"exportPDF" 기능이 개발 되었으나, 차트가 있는 보고서의 경우 화면이 깨져서 저장되는 이슈가 있어, 기능을 제거한 이력이 있음

보고서를 PDF로 저장 하는 기능이 하반기 과제에서 필수기능으로 필요

**Comment by veldise** [comment]
PDF 저장 기능 대신 아래와 같이 이미지 파일로 저장하는 기능이 추가되었습니다.

![image](https://user-images.githubusercontent.com/3411842/92081574-3b43da00-edfe-11ea-8c0d-664434067204.png)

![image](https://user-images.githubusercontent.com/3411842/92081592-4139bb00-edfe-11ea-8766-8762b573f6a3.png)
