### ISSUE TITLE
[피벗분석] 에서 행 선택 옵션 결과에서 정렬이 적용되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2356]
## 버그 설명 ##
b-iris.mobigen.com  demo 크롬브라우저

참고할 분석탬플릿 : 이슈_피벗_행_정렬오류_0630

* month 컬럼(숫자형)  : 오름차순 정렬
<img width="338" alt="스크린샷 2020-06-30 오전 8 11 35" src="https://user-images.githubusercontent.com/5126497/86073253-56bcfc80-babe-11ea-9cc0-2b0205bd6cc1.png">

* 결과는 정렬이 되어 있지 않습니다.
<img width="755" alt="스크린샷 2020-06-30 오전 8 11 46" src="https://user-images.githubusercontent.com/5126497/86073205-4c9afe00-babe-11ea-8777-5c13e2e8d60f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
현재 피벗의 정렬 기능은 아래와 같습니다.
1. '값' 기준 정렬입니다.
2. '열 선택'을 한 개라도 한 경우, 정렬이 불가능합니다.

차후 정렬 기능을 열 / 행 / 값 으로 추가 및 분리할 예정입니다.

**Comment by Minsoo-web** [comment]
플랫폼 품질팀 인턴 김민수입니다. 

### 발견한 문제

현재 (08/06 release 적용 이후) 열 / 행 / 값 별로 정렬이 분리 된 것은 확인이 되었지만
행이나 열의 **단위**가 달라지게 되는 경우 정렬이 제대로 되지 않는 것처럼 확인이 되었습니다. 

1. 피벗 분석 ->  데이터 모델 : `통계로보는수원_수원시 전체 인구현황`
2. 시간 -> 전체 시간 선택
3. 행 선택 : 연령  / 정렬 : 오름차순  
4. 값 선택 : 인구수 / 정렬 : 기본 값
5. see error

### 스크린샷

![스크린샷 2020-08-06 오후 12 05 36](https://user-images.githubusercontent.com/57122180/89486297-b4d7b080-d7dd-11ea-96e7-56a23b1f1507.png)

### 관련 이슈

closed #2222

**Comment by veldise** [comment]
@seungfwani
