### ISSUE TITLE
[수원시][Studio] 지도-검색어 쿼리 작성시 테이블명에서 계정명 제거 요청 

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2357]
## 기능 요청 ##
![image](https://user-images.githubusercontent.com/19259399/86101957-e92cc280-baf5-11ea-8382-dee6480b6b16.png)

지도-검색어 쿼리 작성시 테이블명에서 계정명은 제거하고 테이블명만 쳐서 불러올 수 있도록 요청하셨습니다.

**Comment by sunghoon** [comment]
@veldise @anhm 해당 기능 처리를 위한 검토 의견 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
본문의 쿼리에서 계정명은, 실제 계정명이 아니고 계정명과 동일한 database name 입니다.
삭제하려면 `use` 명령어에 해당하는 API 나 인터페이스가 있어야 합니다.

**Comment by anhm** [comment]
@sunghoon 
IRIS-DB와 IRIS-WEB의 관계를 한번 정하는것이 좋을것 같습니다.
ex) 웹에서 계정을 만들면 DB에 자동 생성되는 부분등 이 존재하는 이후 IRIS의 방향과 맞는지 확인이 필요할것 같습니다.

해당 이슈와 관련해서는 DSMS에서 설계를 진행해 보겠습니다.

**Comment by sunghoon** [comment]
@yoonah95 요청 기능에 대하여 전반적인 내용을 확인하였습니다. 
지금 현 시점에서는 요청한 기능에 대한 처리가 어려울 것 같습니다.
기존 IRIS DB의 아키텍쳐 이슈와 다른 업무 우선 순위로 인해 해당 기능은 보류 하도록 하겠습니다.
