### ISSUE TITLE
[연결정보] b-iris.mobigen.com 에서 연결정보 생성위해 root 로 접근하니 비밀번호유출 경고창이 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2359]
## 버그 설명 ##
b-iris.mobigen.com  root 접속 (-> 연결정보를 새로 만들기 위해 접속함)

<img width="1254" alt="스크린샷 2020-07-01 오전 9 06 01" src="https://user-images.githubusercontent.com/5126497/86188633-38b4d200-bb7a-11ea-8bf1-023588f376e0.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@big-mobigen 비밀번호 변경 관리해 주시기 바랍니다.

**Comment by big-mobigen** [comment]
@sunghoon 
@seoryjj 
현재 재현이 불가능하여, 모니터링 후 동일현상 발생시에 적용하도록 하겠습니다.
