### ISSUE TITLE
[DB브라우저] 에서 본인계정의 테이블 조회도 insert permission 에러가 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2360]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정 크롬브라우저

글로벌 / 로컬 모든 테이블 조회시 동일한 에러 발생합니다.

* 글로벌테이블 조회

<img width="1258" alt="스크린샷 2020-07-01 오전 10 29 18" src="https://user-images.githubusercontent.com/5126497/86193754-b3d0b500-bb87-11ea-8890-0abcc1c9e820.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise @anhm UI 장애인가요?

**Comment by veldise** [comment]
@sunghoon 
IRIS-DB 상에서, 위 쿼리를 수행하는 계정이 IRIS-DB 의 `WAS.WAS_QUERY_HIST` 와 같은 테이블에 insert, select 권한이 없으면 발생하는 문제입니다.
계정 생성시 권한을 부여하도록 되어있는데, 알수없는 이유로 권한이 해제되면 발생합니다.

**Comment by anhm** [comment]
에러가 발생하지 않도록 처리해 두었습니다.
