### ISSUE TITLE
[Studio] Html 뷰어 객체에서 HTML document 안에 url link 가 있는 경우, 에러도 없이 아무것도 안나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2361]
## 버그 설명 ##
b-iris.mobigen.com demo 계정  크롬브라우저

참고할 보고서 : EDU_예제_HTML_Viewer

* 하나는 단순 Html document, 하나는 url link 가 있습니다.
* 편집에서는 에러없이 html 보기도 정상적으로 보입니다.
<img width="811" alt="스크린샷 2020-07-01 오후 1 55 05" src="https://user-images.githubusercontent.com/5126497/86204575-d4f2cf00-bba2-11ea-9e2e-9073b782027c.png">

* 보고서 보기하면 url link 가 있는 박스는 안보입니다.
<img width="843" alt="스크린샷 2020-07-01 오후 1 55 17" src="https://user-images.githubusercontent.com/5126497/86204602-e2a85480-bba2-11ea-9dee-41f1860cfe6b.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
Html 뷰어 객체의 경우에는 Chart, List 등의 객체와 같이 '자동실행'에 체크를 해주어야 합니다.

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
