### ISSUE TITLE
[Discovery] -데이터모델 - 새모델 에서 MYSQL 연결정보가 있는데, 없다고 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2362]
## 버그 설명 ##
b-iris.mobigen.com  demo계정 크롬브라우저

- MySQL 연결정보 mySQL_199  를 생성해서 Studio 에서는 사용했습니다.
<img width="244" alt="스크린샷 2020-07-01 오후 1 12 51" src="https://user-images.githubusercontent.com/5126497/86205226-4a12d400-bba4-11ea-8da5-0c9d2322c4a5.png">

- 데이터모델로 만들기 위해 Discovery-데이터모델- 새모델
- 연결정보가 없다고 나옵니다.
<img width="476" alt="스크린샷 2020-07-01 오후 2 04 46" src="https://user-images.githubusercontent.com/5126497/86205295-729ace00-bba4-11ea-841e-db33615bb130.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
최근 연결정보에 '권한 설정' 기능이 추가되어, 일반 사용자는 접근 권한이 있는 연결정보만 사용할 수 있습니다.
그런데 현재 이 내용이 Analyzer 에만 적용되어 있는 것 같습니다. Studio 에도 적용하도록 하겠습니다.

**Comment by veldise** [comment]
Studio에도 적용되었기에 닫습니다.
