### ISSUE TITLE
[NMS+]API 를 통한 사용자 추가시 IRIS DB접속에러

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2363]
## 버그 설명 ##

 - 고객사의 사용자DB 에서 주기적으로 사용자정보를 읽어서 IRIS API 를 통해 사용자를 추가합니다.
API로 추가한 사용자들이

DB조회>DB 브라우저를 접근하면 다음과 같은 에러가 납니다.
확인부탁합니다.

![e](https://user-images.githubusercontent.com/5468183/86209478-a3333580-bbad-11ea-834a-a8034ba8b884.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@big-mobigen 
`db-browser` 서비스의 로그를 요청합니다.

**Comment by veldise** [comment]
@jjinylee 
현재 DB 브라우저 기능을 사용할 수 없는 사용자가 어떤 계정/ID 인가요?
300여개 계정이라고 하셨는데, 현재 확인하기로는 `monitor`, `tensal` 2개 계정 제외하고는 모두 IRIS-DB에 계정이 있는 것으로 확인됩니다. 

참고로 아래와 같은 ID는 ID 규칙에 어긋나므로 사용할 수 없습니다.

숫자로 시작:
```
0326901ky
1161aa
212eun
7es25a
```
한글:
```
TEST짱짱
테스트짱짱짱
```

**Comment by rhcpn** [comment]
해당 이슈는 이후 구두로 추가로 전달 하였으므로 close 합니다.
