### ISSUE TITLE
[수원시][Studio] 보고서-지도 데이터모델로 검색어 쿼리 작성시 오류

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2364]
## 버그 설명 ##

![image](https://user-images.githubusercontent.com/19259399/86217808-f5c71e80-bbba-11ea-8deb-b676ba6f8ed6.png)

본사에서는 데이터모델을 이용해 데이터 불러올때 문제가 없었는데
수원시에서 실행할 때에는 결과가 없읍니다 라는 오류가 뜹니다.
데이터 검색에서 데이터모델을 확인하면 데이터 결과는 정상적으로 나옵니다.

**Comment by veldise** [comment]
Studio 에서는 현재 화면에 출력된 지도 범위에 대하여 4꼭지점의 위/경도 값을 취하여, 
해당 범위 내에서만 데이터를 조회하도록 아래와 같은 형식으로 DSL을 구성하여 실행합니다.

```
model name = 'IP_LOC' spatial_coordinates = 'POLYGON((45.120052841530544 102.65625000000001, 45.120052841530544 144.31640625000003, 29.19053283229458 144.31640625000003, 29.19053283229458 102.65625000000001, 45.120052841530544 102.65625000000001))'
```

다시 말해 지도 객체에서는 부하를 막기 위해 내부적으로 필터 처리가 추가되어 있습니다.
차트 객체에서 동일한 데이터를 조회하면 잘 나올 것입니다.

**Comment by yoonah95** [comment]
![image](https://user-images.githubusercontent.com/19259399/86219935-dbdb0b00-bbbd-11ea-9102-d4f00fb81c64.png)

보내주신 범위 내에 위경도가 포함되어 있는데도 결과가 안뜹니다.
같은 데이터로 본사에서 실행했을땐 되었는데 수원시에서는 뜨지 않네요

**Comment by veldise** [comment]
@anhm @seungfwani

**Comment by veldise** [comment]
@anhm @seungfwani

**Comment by veldise** [comment]
데이터 모델의 대상 데이터 유형이 HDFS 일 때 / IRIS-DB 일 때 차이인 것으로 확인되었습니다.
추가 논의 중입니다.

**Comment by sunghoon** [comment]
@veldise @anhm 본 이슈 최종 상태 정보를 알려주세요.
