### ISSUE TITLE
Studio: Map / 마커 유형 - 마커가 그려지지 않는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2366]
## 버그 설명 ##
Studio: Map / 마커 유형 - 마커가 그려지지 않는 문제

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 새 보고서
2. 지도 객체 추가, 레이어 추가
3. 다음과 같이 데이터 설정:
    - 데이터 모델: `EDU_MAP_MARK_TEST`
    - 검색어: `* | head 100`
4. 실행

## 내용 ##
실행하면 데이터가 마커로 바로 그려져야 하는데, 보고서를 저장 후 불러와야 그려집니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/86306525-79324f80-bc4f-11ea-8fe6-6b756a94df3c.png)

**Comment by swish1995** [comment]
### 발생 원인 분석
- naver 의 원형 아이콘이 px 가 2 이하일때는 보이지 않는 버그가 있습니다.
- 사이즈를 3 또는 4 로 하면 다음과 같이 일부가 잘린상태로 표시되며 5이상일때만 정상적으로 표시됩니다.
- size = 3
   ![image](https://user-images.githubusercontent.com/49141403/86311583-adac0880-bc5b-11ea-9b4d-8570b141dfd9.png) 
- size = 4
   ![image](https://user-images.githubusercontent.com/49141403/86311618-c0bed880-bc5b-11ea-9446-7f26afd2b159.png)
- size = 5
   ![image](https://user-images.githubusercontent.com/49141403/86311656-d46a3f00-bc5b-11ea-908f-b53f4e338c25.png)
- 이는 네이버가 원형을 그릴때 svg 로 표현하며 svg 의 viewBox 설정상 처음 두 값이 -1 -1 로 고정되어 발생하는 문제로 확인되었습니다.
   ![image](https://user-images.githubusercontent.com/49141403/86311909-67a37480-bc5c-11ea-9257-f2b41a4fb5f4.png)
### 네이버 지도일때 해당 문제가 발생하는 마커의 포인트, 도형의 원의 기본 값을 3 또는 5 값으로 변경하거나, 혹은 다른 방식으로 변경할지에 따라 수정하도록 하겠습니다.
