### ISSUE TITLE
Analyzer: 시각화 / forecast, anomalize, outlier 시각화 유형 추가

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2375]
## 기능 요청 ##
Analyzer: 시각화 / forecast, anomalize, outlier 시각화 유형 추가

**Comment by ohmy04180** [comment]
안녕하세요! 오민영입니다. 해당 내용 완료 되었습니다.

- 해당 옵션이 적용될 페이지
/views/sherman/adv.html
-  팝업 
/views/popup_guide_add.html
- 스타일 경로
/assets/css/sherman/style.min.css

**Comment by veldise** [comment]
분석 옵션을 설정하는 기능이 아래와 같이 추가될 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/92425208-845eaa00-f1c1-11ea-8aa9-48d6a1386378.png)

![image](https://user-images.githubusercontent.com/3411842/92425220-8de81200-f1c1-11ea-825b-b4da360b83ef.png)

![image](https://user-images.githubusercontent.com/3411842/92425228-950f2000-f1c1-11ea-9e07-17ad030b62ae.png)
