### ISSUE TITLE
Studio: Chart / forecast, anomalize, outlier 시각화 유형 추가 

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2376]
## 기능 요청 ##
Studio: Chart / forecast, anomalize, outlier 시각화 유형 추가

**Comment by sunghoon** [comment]
@veldise 진행 계획 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 개발 진행 중입니다.

**Comment by sunghoon** [comment]
@veldise 완료 목표일 정보를 알려주세요.

**Comment by veldise** [comment]
@sunghoon 
10월 21일 개발 완료를 목표로 하고 있습니다.
