### ISSUE TITLE
Studio: 기간 설정 객체 재개발

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2378]
## 기능 요청 ##
Studio: 기간 설정 객체 재개발

### 기존:
![image](https://user-images.githubusercontent.com/3411842/86420541-ec9c9580-bd11-11ea-9059-21df4d74a8a0.png) ![image](https://user-images.githubusercontent.com/3411842/86420548-f0c8b300-bd11-11ea-85f1-a07495099c23.png)

### 변경:
![image](https://user-images.githubusercontent.com/3411842/86420569-03db8300-bd12-11ea-9538-3d0c009a53cb.png)

**Comment by sunghoon** [comment]
@veldise @onlyeon 

사이즈 조정에 따른 구성 오류 부분이 발견 됩니다. 
사이즈 조정을 막아든지, 사이즈에 맞게 달력 사이즈가 맞춰 지던지 해야 할 것 같습니다. 

![스크린샷 2020-10-08 오전 10 55 40](https://user-images.githubusercontent.com/512653/95406210-d0ce0e80-0954-11eb-9f80-a2f475601703.png)

**Comment by sunghoon** [comment]
@veldise 아무런 설정 없는 상태에서 오른쪽(미래 >) 를 클릭하였을때  다음과 같은 메시지가 발생합니다.
정상인지? 아닌지요?
![스크린샷 2020-10-08 오전 10 57 27](https://user-images.githubusercontent.com/512653/95406309-0ecb3280-0955-11eb-950d-58772bb51f5c.png)

**Comment by sunghoon** [comment]
@eumminsun @veldise @onlyeon 

아래의 내용이 발짜가 선택 되었다는 의미인지 ? 선택 할 수 없는 의미인지? 잘 모르겠습니다. 
제가 봤을때는 선택 못한다는 의미 같아 보이며, 필요에 따라서는 회색 부분의 날짜도 선택 해야 할 것 같습니다. 

![스크린샷 2020-10-08 오전 10 59 59](https://user-images.githubusercontent.com/512653/95406459-69648e80-0955-11eb-8054-cc3f57d929b1.png)

**Comment by sunghoon** [comment]
@eumminsun @veldise @onlyeon 내부 논의 내용 정보를 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
기간 설정 객체의 동작이 전반적으로 심각한 문제가 있는 것으로 생각됩니다.
먼저 동작을 전체적으로 점검하고 버그 항목들을 정리한 뒤 진행하겠습니다. 다른 일정을 연기하고 바로 진행할 계획입니다.

**Comment by sunghoon** [comment]
@veldise @eumminsun 배포 이전에 발견될 수 있도록 해 주시고, 해당 이슈 내용에 대한 추가적인 상세 정보를 별도로 보고해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@veldise 최근 배포가 된것 같은데? 맞나요?

**Comment by veldise** [comment]
@sunghoon 
아래 이슈에 버그/개선이 필요한 사항에 대하여 정리하였습니다. 시간 내주시면 별도로 설명드리겠습니다.
https://github.com/mobigen/IRIS/issues/59

**Comment by sunghoon** [comment]
@veldise 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
기획 결과 사용자 편의성을 위한 개선 항목이 결정되었고 날짜&시간 객체까지 수정이 필요하여
일단 12/3 Release 를 목표로 하려고 합니다.

버그는 11/5 패치로 해결이 되었습니다.
