### ISSUE TITLE
Studio: Chart / 테이블 유형 - 행 선택 기능을 선택 불가 / 단일 / 다중으로 확장

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2380]
## 기능 요청 ##
Studio: Chart / 테이블 유형 - 행 선택 기능을 선택 불가 / 단일 / 다중으로 확장

## 원하는 솔루션 설명 ##
현재 Chart 객체를 테이블(Gridview)로 구성하였을 때, 행을 클릭으로 선택하는 기능이 기본으로 있습니다.

이 기능을 아래와 같은 3개로 분리해야 합니다.
- 행 선택 불가
- 행 1개 선택 (단일)
- 행 여러개 선택 (다중)

그리고 이에 따라 Chart 객체가 가지는 변수값의 유형을 확장해야 합니다.

**Comment by sunghoon** [comment]
@veldise 계획 일정에 맞춰 진행되고 있는지요?

**Comment by veldise** [comment]
@sunghoon 
일정에 따라 10월 8일에 배포 가능합니다.

**Comment by sunghoon** [comment]
@veldise 10/8일 배포 가능 있는데? 마일스톤에서 제거 되었네요?
어떻게 진행되고 있나요? 다음 계획을 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
#2521 과 동일 이슈입니다.

UI 컴포넌트 추가 개발 및 데이터 마이그레이션이 필요하여 다소 지연되었습니다.
개발은 완료되었으며 차주(10/22) 패치를 목표로 준비중입니다.
