### ISSUE TITLE
[교통빅데이터] IRIS Analyzer/검색/기본 기간설정값 변경 가능한 기능 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2383]
## 기능 요청 ##
IRIS Analyzer/검색/기본 기간설정값 변경 가능한 기능 요청

현재는 검색의 시간 설정 기본값이 "최근1분"으로 되어 있음, 실시간 처리 데이터가 아닌 시간단위, 일단위 , 월단위 데이터가 많은 곳에서는 최근 1분으로 되어 있어 기본 조회시 데이터 조회 결과가 없음으로 실행됨

일반 사용자들이 해당 부분에 대해 불편하다고 피드백을 주고 있음

![image](https://user-images.githubusercontent.com/4444717/86447165-e4fbe180-bd4f-11ea-8ba7-3cefcbeb27df.png)

## 원하는 솔루션 설명 ##

관리자 기능에서 기본값 설정을 정의 할 수 있도록 기능 추가필요

## 고려한 다른 대안 ##
교통빅데이터의 경우 배포버전에 커스텀으로 "전체시간"으로 설정 필요

**Comment by sunghoon** [comment]
모델을 생성할때 디폴드 시간 범위 설정 값을 남길 수 있도록 하면 될 것 같네요.

**Comment by rhcpn** [comment]
모델 뷰 수정 부분은 당장 처리 하기 어려우니, 우선 검색 기간을 "전체시간" 으로 잡아서 처리 하도록 진행 하겠습니다.

**Comment by veldise** [comment]
기본 시간범위 설정값을 '전체시간'으로 변경한 내용이
오픈랩 사이트에 배포 되었으므로 이슈 닫습니다.

**Comment by JeongHeeDong** [comment]
배성훈그룹장께서 의견주신것과 같이 모델 생성시 기본 시간 설정값을 정의 할 수 있게 하거나, 다른 방법으로 설정 할 수 있는 기능은 필요해 보입니다.
해당 기능 추가 검토 요청 드립니다.

**Comment by sunghoon** [comment]
@veldise 이슈 최종 상태 정보를 공유 해 부세요.

**Comment by veldise** [comment]
@sunghoon 
배포 위치/사이트 별로 Analyzer의 시간 범위 설정 기본값(default)를 다르게 하고 싶다는 요구사항으로 해석되어
서버 설정에 시간범위 기본값 설정을 추가할 계획을 하고 있습니다.

다른 업무로 아직 진행하고 있지는 않습니다.

**Comment by sunghoon** [comment]
@eumminsun 책임님 모델을 만들때 해당 모델의 시간 설정 값을 사용자가 지정할 수 있도록 UX 개선을 요청 드립니다.
