### ISSUE TITLE
[Studio] 꺽은선 차트 데이터 표시방법 변경 (심각)

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2386]
## 기능 요청 ##
스튜디오에서 꺽은선 그래프 차트를 표시하고 마우스로 특정 값을 보려고 할때 너무 많은 값이 나와 원하는 값을 볼수 없습니다.
아이리스 어넬라이저의 차트와 같은 모양으로 출력해야 할것 같습니다.

<스튜디오 차트> -> 값이 너무 많아 볼수 없음
![스크린샷 2020-07-06 오후 3 56 32](https://user-images.githubusercontent.com/3468426/86564900-e58bb680-bfa1-11ea-9b6a-748e257d90e0.png)

<어넬라이저 차트> -> 값 1개만 출력되어 보기좋음.
![스크린샷 2020-07-06 오후 3 56 14](https://user-images.githubusercontent.com/3468426/86564963-00f6c180-bfa2-11ea-9ce2-b82edafb4f2b.png)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by tessekim** [comment]
데이터모델 : tylor_syslog
시간 : 최근4시간
DSL : 아래
* HOST='tsdn-svr1' | pivot count(*) splitrow 'date_group("DATETIME","10M")' splitcol FACILITY

**Comment by sunghoon** [comment]
@veldise 계획한 일정으로 준비/진행 되고 있는지요?

**Comment by veldise** [comment]
@sunghoon 
이전 업무가 개발 난이도 등 이슈로 인해 많이 지연되어서, 현재 WBS 일정상으로는 10월 8일에 완료하기 어렵습니다.
10월 8일까지 완료되어야 한다면 담당자 변경이나 다른 방법을 검토하겠습니다.

**Comment by sunghoon** [comment]
@veldise 목료로 하는 일정이 어렵다면 업무량 및 차선으로 가능한 일정 공유 해 주세요.

**Comment by sunghoon** [comment]
@veldise 업무 추진 계획이 어떻게 되나요?

**Comment by veldise** [comment]
@sunghoon 
10/29 패치를 목표로 하고 있습니다.

**Comment by sunghoon** [comment]
@veldise 어떻게 처리되고 있나요?

**Comment by veldise** [comment]
다음과 같이 Chart 객체가 '꺾은선형', '다중축', '세로막대형', '가로막대형'일 때 툴팁이 항상 통합되어있던 것을
시각화 옵션 > 툴팁 설정을 통하여 개별 표기가 가능하도록 기능을 추가했습니다.

![image](https://user-images.githubusercontent.com/3411842/97540764-72ea8f00-1a07-11eb-8924-b2f91cb58ae5.png)
