### ISSUE TITLE
긴급 !! [Studio] root 계정에서 생성하여 전체사용자 공유한 보고서 복제 후 편집-수정 시 데이터모델이름이 보이지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2387]
## 버그 설명 ##
demo 계정으로 로그인 하여 root 계정이 생성한 보고서 ** Studio예제_시계열분포챠트**  복제한 보고서 **Studio예제_시계열분포챠트 (3)**

편집-수정하면 데이터모델란에 데이터모델명이 보이지 않습니다.

<img width="199" alt="스크린샷 2020-07-06 오후 4 02 08" src="https://user-images.githubusercontent.com/5126497/86564966-018f5800-bfa2-11ea-8a0a-f7816301ec13.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/86565411-bd508780-bfa2-11ea-848e-f2149a0d7b83.png)

데이터에는 이상이 없고 네트워크가 느릴때 가끔 발생하는 문제입니다.

**Comment by seoryjj** [comment]
네트웍 문제가 아닌 게 
지금도 안보이고, 다른 계정 사용자도 동일하게 보이지 않는 다고 합니다

**Comment by veldise** [comment]
@seoryjj 
그러면 demo 계정이 해당 모델에 권한이 없어서 그런 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/86570088-5b941b80-bfaa-11ea-9aef-ac84c5c275d7.png)

**Comment by jins00** [comment]
@veldise 
본 건과 관련하여, 아래 내용이 맞는지 확인 부탁드리며,
아래 내용이 맞다면 2번은 개선이 필요하지 않을까 생각됩니다.

내가 만든 보고서의 접근 권한을 설정하는 목적은 크게 2가지인것 같습니다.
1. 내가 만든 보고서를 다른 사용자가 데모등의 목적으로 실행하는 경우
   -> 보고서의 접근 권한 설정만으로 가능
2. 내가 만든 보고서를 다른 사용자가 복제하여 수정하는 경우
   -> 보고서의 접근 권한 설정 시, 상기와 같이 데이터모델이 보이지 않을 것으로 생각됩니다.
       따라서, 이 경우에는 데이터모델 목록에서 해당 데이터 모델의 접근 권한도 같이 설정해야 합니다.

**Comment by veldise** [comment]
@jins00 
데모 등의 목적으로 실행만 하고자 한다면 "내보내기URL"로 충분할 것입니다. 물론 전체 공개가 아닌 특정 사용자만 실행해야 한다면 "내보내기URL" 쪽에 기능을 추가할 필요는 있습니다.

보고서 권한 설정시 데이터 모델 권한도 같이 설정하는 것은 상당히 어렵습니다.
목록 화면에서 특정 보고서 내의 모든 데이터 모델 정보를 얻어야 하며, 모든 데이터 모델의 모든 연결 정보도 권한을 설정해야 합니다.

보고서(1) - 모델(N) - 연결정보(N)

그리고 연결 정보의 경우 DB 접근 권한을 직접 주는 것과 마찬가지이므로 신중하게 처리해야 합니다.
또한 소유자(작성자)가 아닌 경우 권한을 설정할 수 없으므로, 만약 보고서의 데이터 모델이나 연결 정보가 공유 받은 것이라면 위 동작이 아예 불가능합니다.

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
권한 부여에 대한 내용은 필요시 별도 이슈를 작성하여 진행하겠습니다.
