### ISSUE TITLE
[Analyzer] forecasts 의 시각화 챠트가 이상합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2388]
## 버그 설명 ##
demo 계정 b-iris.mobigen.com

데이터모델 : tylor_syslog
시간 : 최근 4시간
검색어
`HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME_10M, * from angora" | stats COUNT(*) as CNT by DATETIME_10M, HOST | forecasts DATETIME_10M CNT alg=linear`

* 시간 필드가 이상하고, 예측값(true) 점선 부분이 엉뚱한 위치...  
* 시간이 1970년...
<img width="971" alt="스크린샷 2020-07-06 오후 4 25 26" src="https://user-images.githubusercontent.com/5126497/86566814-3f41b000-bfa5-11ea-8e6c-baa12f138d67.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
outlier 의 시간 필드도 1970-01-01 로 오류입니다.

**Comment by veldise** [comment]
@seungfwani @anhm 
시간 값이 잘못 반환되고 있습니다. `DATETIME_10M`가 `TEXT` 유형이고, 결과 값도 이상합니다.

```js
{
  "isEnd": true,
  "status": {
    "current": 1,
    "total": 1
  },
  "fields": [
    {
      "name": "DATETIME_10M",
      "type": "TEXT",
      "grouped": true
    },
    {
      "name": "CNT",
      "type": "REAL",
      "grouped": false
    },
    {
      "name": "forecasts",
      "type": "BOOLEAN",
      "grouped": false
    }
  ],
  "results": [
    [
      "2020-07-06 12:00:00",
      415.0,
      false
    ],
    [
      "2020-07-06 12:10:00",
      449.0,
      false
    ],
    [
      "2020-07-06 12:20:00",
      474.0,
      false
    ],
```

**Comment by seoryjj** [comment]
- 임시방편으로 검색어에서 timestamp 로 출력되게  한 후 시각화 결과 

`HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME,  HOST  from angora" |  stats COUNT(*) as CNT by DATETIME, HOST | forecasts DATETIME CNT alg=linear`

`HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME,  HOST  from angora" |  stats COUNT(*) as CNT by DATETIME, HOST | forecasts DATETIME CNT alg=seasonal`

- arg=seasonal
<img width="1032" alt="스크린샷 2020-07-07 오후 3 07 41" src="https://user-images.githubusercontent.com/5126497/86725187-67441880-c064-11ea-872e-5f2965811fc2.png">

- alg=linear
<img width="1031" alt="스크린샷 2020-07-07 오후 3 08 15" src="https://user-images.githubusercontent.com/5126497/86725211-6b703600-c064-11ea-890e-8704a341cecf.png">

- 10분단위데이터라 예측값과 실측값 사이에 10분 간격이 그림처럼 빈공백으로 표시됩니다.
- 실측값과 예측값 사이 line 을 이어주는 게 필요해보입니다.

**Comment by seungfwani** [comment]
문제 해결을 위해서 아래와 같이 진행합니다.
1. typecast 명령어 생성 - 80% 진행
2. [interpolation 명령어](https://github.com/mobigen/IRIS-BigData-Platform/issues/2426) 생성 - 0% 진행

**Comment by seungfwani** [comment]
문제 해결을 위해서 아래와 같이 진행합니다.
1. typecast 명령어 생성 완료 - [명령어문서](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/typecast.html)
2. [interpolation 명령어](https://github.com/mobigen/IRIS-BigData-Platform/issues/2426) 생성 - 0% 진행

**Comment by seungfwani** [comment]
다른 명령어와 상관관계가 없는 문제로 해당 내용은 수정되었으며, 배포 후 닫도록 하겠습니다.

- `HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME_10M, * from angora" | stats COUNT(*) as CNT by DATETIME_10M, HOST | forecasts DATETIME_10M CNT alg=linear`
![Screen Shot 2020-09-22 at 10 38 10 AM](https://user-images.githubusercontent.com/46172579/93837043-b858c580-fcbf-11ea-87eb-a9d8f6c992d3.png)


- `HOST='tsdn-svr1' | sql "select CONCAT(SUBSTR(DATETIME,1,11),'000') as DATETIME_10M, * from angora" | stats COUNT(*) as CNT by DATETIME_10M, HOST | forecasts DATETIME_10M CNT alg=seasonal`
![Screen Shot 2020-09-22 at 10 37 25 AM](https://user-images.githubusercontent.com/46172579/93837024-9d865100-fcbf-11ea-96af-71fca19e6941.png)
