### ISSUE TITLE
[Studio] 주기설정 객체에서  stop 버튼 후 play 재개하면 "다음 갱신까지" 시간이  24시간으로 셋팅됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2389]
## 버그 설명 ##
 b-iris.mobigen.com demo 계정 크롬브라우저

* 10초 주기설정 / stop 후 play 재개하면 "다음 갱신까지" 가 24시간으로 변경됩니다. 다시실행 누르고, stop-play 하면  10초로 돌아옵니다.
<img width="466" alt="스크린샷 2020-07-07 오전 8 38 25" src="https://user-images.githubusercontent.com/5126497/86668269-7196f000-c02d-11ea-8c6d-50906f612daf.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seoryjj 재현되지 않아 닫습니다. 
같은 현상이 재발하면 새 이슈로 등록 바랍니다.
