### ISSUE TITLE
문의 [Studio]  챠트객체의 "데이터누적" 적용 시 동일시간대의 데이터가 최대갯수를 초과할 때 데이터를 표시하는 기준

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2390]
## 기능 요청 ##
b-iris.mobigen.com  demo계정 크롬브라우저

보고서 : realtime_chart (2)

* 최대 갯수 20개
* 하루에 11개의 데이터가 발생합니다. 그래서 2일에 걸친 데이터가 표시됩니다.(예: 1일 9개, 2일 11개)
* 이 때 데이터를 cut 하는 기준이 무엇인가요?

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
기존 데이터와 새로 받은 데이터 간에

1) 중복이 없는 경우
데이터를 합친 뒤, 이전 데이터를 cut 합니다.
ex)
11+11 = 22
limit(22) = 20

2) 중복이 있는 경우
데이터를 합치고 이전 데이터에서 x축을 기준으로 중복을 제거한 뒤, 이전 데이터를 cut 합니다.
ex)
11+11 = 22
uniq(22) = 21
limit(21) = 20

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
현재 '데이터 누적' 기능에 다소 문제가 많아서 차후에는 일부 차트 유형에서만 사용 가능하도록 개선할 계획입니다.
