### ISSUE TITLE
[Studio] 데이터객체에서 데이터실행방법 설정에서 자동실행을 default 로 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2391]
## 기능 요청 ##

*  보고서에서 특별한 경우를 제외하고는 자동실행을 더 많이 사용하게 되니 자동실행이 디폴트로 되어 있으면 좋겠습니다.
<img width="194" alt="스크린샷 2020-07-07 오전 9 59 39" src="https://user-images.githubusercontent.com/5126497/86679545-a2305700-c038-11ea-8198-7a2984e17893.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun @veldise   #2339 도 같은 요청인것 같습니다. 설정값을 변경하여 빠르게 대응 바랍니다.

**Comment by sunghoon** [comment]
#2339

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
예제 보고서가 아닌 실제 보고서를 작성할 때에는 자동실행을 사용하는 경우는 크게 많지 않을 것으로 생각됩니다.
또한 자동실행을 기본으로 하였을 경우, 사용자의 작성 실수가 있을 때 서버로 잘못된/빈번한 요청이 전송되어 서버 부하를 가중시킬 수도 있을 것입니다.
따라서 **자동실행은 지금처럼 체크가 해제된 것을 기본으로 유지**하고자 합니다.

다만 보고서 작성시 불편한 점은 확실히 있습니다. 이는 차후 사용자 편의기능으로 별도로 기획을 해보겠습니다.

**Comment by sunghoon** [comment]
@seoryjj 위와 같이 최종 결정되었습니다. 업무에 참고하시기 바랍니다. 이슈는 닫습니다.
