### ISSUE TITLE
[수원시][Studio] 보고서-지도 툴팁 선택 시 영어 컬럼만 뜹니다.

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2392]
## 버그 설명 ##
![image](https://user-images.githubusercontent.com/19259399/86681512-9c3b7580-c03a-11ea-9947-50ac76692c5d.png)

데이터 선택시에는 한글컬럼과 영어컬럼이 같이 뜨지만
툴팁 선택시에는 영어컬럼만 뜹니다.
한글컬럼도 같이 띄워주세요!

**Comment by veldise** [comment]
@yoonah95 
말씀하시는 한글 컬럼이 어떤건가요? 데이터 선택시 화면도 첨부해주시기 바랍니다.

**Comment by yoonah95** [comment]
![image](https://user-images.githubusercontent.com/19259399/86713940-8f7a4a00-c059-11ea-96db-57c6f815e3c5.png)

데이터 선택시 화면입니다. 데이터 모델 생성 시 별칭으로 생성 되는 한글 컬럼입니다.

**Comment by veldise** [comment]
@yoonah95 
한글 컬럼이 아니고, 데이터 모델 생성시에 별칭으로 지정한 한글 텍스트를 말씀하시는 것 같습니다.

툴팁에서도 별칭 텍스트가 출력되도록 개선하겠습니다.

**Comment by yoonah95** [comment]
네 감사합니다.
