### ISSUE TITLE
[studio] 데이터객체를 별도 객체로 캔버스에 표시(지금버전) / 챠트등 객체에 종속 -> 이렇게 설정이 가능하게 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2393]
## 기능 요청 ##

* 데이터객체를 지금 처럼 하는 것 외에
* 챠트, 콤보박스등에서 데이터객체 종속(예전 버전과 비슷) 하게 선택할 수 있는 기능

* 이유
  * 여러개의 콤보박스나 라디오버튼, 챠트가 있는 보고서의 경우에 편집화면이 너무 복잡해져서 객체에 연결된 데이터객체를 찾기 위해서 매번 데이터연결 버튼을 눌러서 연결된 데이터객체를 찾아야 합니다.
    *  =>  편집시에는 데이터객체의 위치를 옯겨야만 원활한 작업이 가능한 경우가 많기 때문에  연결대상객체옆에 꼭 데이터객체를 둘 수 없기 때문에 매번 연결설정 버튼을 눌러서 확인해야 합니다.

* 다른 방안
  * 챠트 객체를 누르면 자동으로 연결대상 데이터객체를 색이 변하게 하는 등으로 알 수 있게 표시하고, 나머지 데이터 객체는 안보이게 하는 옵션

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
이전 버전으로 돌릴 수는 없고, 다음 기능을 고려해볼 수 있습니다.
- 특정 객체에서 데이터 객체를 자동 추가 & 연결
- 특정 객체의 사이드 패널에서 버튼 클릭 등을 하면 데이터 객체로 선택을 변경

**Comment by veldise** [comment]
패치로 '자동 추가' 기능과 '선택 이동' 기능이 추가되어 닫습니다.
객체를 목록으로 관리하는 기능도 추후 개발 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/90842489-5fcd9a00-e39a-11ea-9afa-88cad0e2ddef.png)
