### ISSUE TITLE
Analyzer: outlier 결과 오류

### ISSUE THREAD

**Issue by tylor-kr** [mobigen/IRIS-BigData-Platform#2394]
## 버그 설명 ##
숫자 필드로  `outlier` 명령을 요청 했는데 결과에는 텍스트 필드로 반환 됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://192.168.100.180/ - IRIS Analyzer - 검색 으로 이동
2. 아래 조건으로 실행
![image](https://user-images.githubusercontent.com/13827425/86684395-782d6380-c03d-11ea-82d1-d21c422b48ed.png)
3. 개발자 도구에서 응답 확인

## 로그 ##
* CNT는 숫자 필드
![image](https://user-images.githubusercontent.com/13827425/86684589-a6ab3e80-c03d-11ea-9fa5-2c01712e82d5.png)

* 요청
```
{"q":"model name = 'anomalies test' model_owner = root | outlier CNT by=HOST","save":false,"size":500}
```

* 응답
  * `CNT`가 텍스트로 반환됨
```
{
    "isEnd": true,
    "status": {
        "current": 1,
        "total": 1
    },
    "fields": [{
            "name": "DATETIME",
            "type": "TEXT",
            "grouped": false
        },
        {
            "name": "HOST",
            "type": "TEXT",
            "grouped": false
        },
        {
            "name": "CNT",
            "type": "TEXT",
            "grouped": false
        },
        {
            "name": "label",
            "type": "INTEGER",
            "grouped": false
        },
        {
            "name": "outlier",
            "type": "BOOLEAN",
            "grouped": false
        }
    ],
...
```

**Comment by seungfwani** [comment]
수정 후 테스트 완료 되었으며 b-iris.mobigen.com 배포 후 닫도록 하겠습니다.

**Comment by seungfwani** [comment]
배포완료되어 닫습니다.
