### ISSUE TITLE
[수원시][Analyzer] 데이터모델에서 설정한 timestamp 포맷팅 과 실제 검색시 나오는 포맷팅이 불일치합니다.

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2395]
## 버그 설명 ##
![image](https://user-images.githubusercontent.com/19259399/86688728-5209c280-c041-11ea-8bec-f0af2992abb4.png)

데이터 모델에 설정된 timestamp 포맷팅은 YYYY-MM-DD 형식인데

![image](https://user-images.githubusercontent.com/19259399/86689003-9006e680-c041-11ea-8443-bf0d0a08d001.png)

실제 데이터 모델 검색시에는 YYYY/MM/DD 형식으로 뜹니다.

다른 예시로는 

![image](https://user-images.githubusercontent.com/19259399/86689842-571b4180-c042-11ea-97e0-c0fab7012e9b.png)

지정한 포맷팅은 YYYY-MM-DD 이지만 

![image](https://user-images.githubusercontent.com/19259399/86689875-5f737c80-c042-11ea-8ef7-5e48da968d15.png)

YYYY/MM/DD HH:mm:ss 로 뜹니다 .

**Comment by veldise** [comment]
데이터 모델의 컬럼 유형을 `TIMESTAMP`로 하는 것은, 해당하는 원본 컬럼의 유형이 문자열(`TEXT`)인데
이 데이터를 시간 포맷에 따라 분석(parse)하여 사용하겠다는 의미입니다.

그래서 먼저 2번째 예시의 경우에는, 데이터 문자열과 입력한 시간포맷이 맞지 않아서 Invalid Date로 출력되는 것입니다.
첫번째의 경우에는 사용자가 보고 판단하기 편하도록 `TIMESTAMP` 유형의 시간 값은 아래 포맷으로 통일하여 출력하고 있기 때문입니다.
`YYYY/MM/DD HH:mm:ss`
`YYYY/MM/DD`

**Comment by yoonah95** [comment]
네...그럼 어떠한 형식이든 다 통일되어 나온다는 뜻인가요?

그리고 
![image](https://user-images.githubusercontent.com/19259399/86719077-b1c29680-c05e-11ea-9ba6-885fc325a7ef.png)

포맷팅 형식은 YYYYMMDD 인데

![image](https://user-images.githubusercontent.com/19259399/86719045-aa02f200-c05e-11ea-8f8f-24b067266848.png)

YYYY/MM/DD hh:mm:ss 형식으로 시간포맷을 설정 하지 않았는데도 시간까지 뜨는경우도 있습니다.

수원시에서는 포맷팅 한 그대로 나왔으면 좋겠다는 요구사항이 있습니다.

**Comment by veldise** [comment]
네, 데이터 모델 생성시에 지정하는 시간 포맷은 문자열을 시간값으로 변환하기 위한 포맷입니다.
설정한 포맷 그대로 나오면 원본 데이터를 그대로 출력하는 것과 다름이 없으므로,
위 데이터 같은 경우 19750427 과 같이 다소 알아보기 힘들게 나올 수 있습니다. (미국의 경우 04/27/1975)

포맷팅한 그대로 나오게 하는 것은 수원시만의 요건이므로 적용하려면 논의가 필요합니다.

**Comment by veldise** [comment]
수원시에 패치되었기에 닫습니다.
