### ISSUE TITLE
[NMS+]앙고라 restAPI 문의

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2397]
## 기능 요청 ##
앙고로 restAPI 를 연동하는 고객사의 타시스템에서 사용하려고 하는데 에러가 있다고 합니다.

http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/restapi/doc/restful_api/query.html

![이순미](https://user-images.githubusercontent.com/5468183/86731217-47afee80-c06a-11ea-91bc-4291ed9e1780.PNG)

1. 내부망에서만 사용가능한것인지, 
2, 아니라면 외부에서 사용가능하도록 요청

확인부탁드립니다

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 해당 이슈 지원 되었는지요?

**Comment by jjinylee** [comment]
해당건 앙고라 restAPI 외부에서 사용가능하도록 운용기술지원팀에서 외부접근 가능하도록 처리하였고,
이후 서승환 책임님이 앙고라 restAPI 사용가능하도록 처리지원하여 완료하였습니다

이슈클로징합니다.
