### ISSUE TITLE
[수원시][Studio] 지도API 선택 시 Open Street Map 은 삭제, Naver Web Map 을 default로 해주세요.

### ISSUE THREAD

**Issue by yoonah95** [mobigen/IRIS-BigData-Platform#2398]
## 기능 요청 ##

보고서-지도
![image](https://user-images.githubusercontent.com/19259399/86731782-d0c72580-c06a-11ea-8cbd-2e25e451ecbf.png)

시각화-클러스트 맵
![image](https://user-images.githubusercontent.com/19259399/86731396-74fc9c80-c06a-11ea-8703-b44994185fcd.png)

지도를 선택하는 기능이 있을 시 Open Street Map 은 삭제, Naver Web Map 을 default로 해달라는 수원시 요청이 들어왔습니다.

**Comment by rhcpn** [comment]
추가로 Basemap을 좀더 다양하게 제공해달라는 요청도 있었습니다.

**Comment by veldise** [comment]
Basemap 까지 포함하여 사이트 커스터마이징 형식으로 처리 완료되어 닫습니다.
