### ISSUE TITLE
[Discovery] 파일을 불러와도 100으로 찍히지 않습니다.

### ISSUE THREAD

**Issue by YusunPark** [mobigen/IRIS-BigData-Platform#2400]
## 버그 설명 ##

![50](https://user-images.githubusercontent.com/59571464/86751891-f0b21580-c079-11ea-97b1-6c16320ea7c1.PNG)

첨부한 사진과 같이 데이터를 불러오고 완료가 되어도100, success라고 찍히지 않고 
50, none 이라고만 나옵니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@YusunPark 
파일 업로드를 시도하신 대상 시스템이 무엇인가요? HDFS 인가요, MinIO 인가요?

![image](https://user-images.githubusercontent.com/3411842/86979272-d6805080-c1bb-11ea-8bd2-96f9d4d0b1af.png)

**Comment by YusunPark** [comment]
### 추가

HDFS에서 문제가 발생하고 있고 한번 여러가지 파일을 넣어본 결과
특정 파일에서만 안되는것 같습니다.
추가적으로 50으로 찍혔던 파일들은 삭제 또한 되지를 않습니다.

![image](https://user-images.githubusercontent.com/59571464/87100389-3f80ca80-c287-11ea-8c49-5eeb65f543ef.png)

![image](https://user-images.githubusercontent.com/59571464/87100403-43ace800-c287-11ea-8ed0-9786ad33eec4.png)

**Comment by veldise** [comment]
지금 MinIO 대상으로 파일 업로드 수행할 때, 파일 내용이 한글이면 업로드가 되지 않는 유사한 문제가 있습니다.
HDFS 에서도 같은 문제인지 확인해보겠습니다.

**Comment by YusunPark** [comment]
![image](https://user-images.githubusercontent.com/59571464/87101653-a489ef80-c28a-11ea-9b16-6eec101e2194.png)

두 파일 모두 내용이 한글이여서 같은 문제는 아닐것 같습니다.

**Comment by YusunPark** [comment]
![image](https://user-images.githubusercontent.com/59571464/88999216-df81bf00-d32e-11ea-8ea7-94cb23a81ce7.png)

![image](https://user-images.githubusercontent.com/59571464/88999395-7189c780-d32f-11ea-9942-9fa5a9c2c454.png)

해당 문제가 재현이 되는것이 아무래도 파일의 문제인듯 싶습니다.
이슈 등록 당시에 올렸던 파일에서는 같은 문제가 재현되고 있고, 
다른 파일을 올린 경우에는 정상적으로 작동하고 있습니다.

> 밑에는 해당 문제가 발생하는 파일의 압축본입니다. 
[범죄발생+장소별+현황.zip](https://github.com/mobigen/IRIS-BigData-Platform/files/5005014/%2B.%2B.zip)

또한 문제가 발생하고 있는 파일의 경우에는 업로드한 파일의 삭제가 되지 않고,
문제 파일을 다운로드할 경우도 정상적으로 작동하고 있지를 않습니다. 
(다른 파일은 삭제와 다운로드 정상 작동)

![image](https://user-images.githubusercontent.com/59571464/88999608-f7a60e00-d32f-11ea-9e28-d6be444d160e.png)

**Comment by hiy2259** [comment]
상세한 코멘트 감사합니다.
URL 인코딩 쪽에서 문제가 발생한 것으로 원인을 찾았고 버그를 수정하겠습니다.

**Comment by veldise** [comment]
@rhcpn @lyj 
업로드는 패치로 해결되었는데, IWP를 통하면 다운로드가 안됩니다. 확인 부탁드립니다.

**Comment by veldise** [comment]
이슈 본문은 해결되었으므로 이 이슈는 닫고, 다운로드 이슈는 아래와 같이 분리하겠습니다.
#2620
