### ISSUE TITLE
[STUDIO] 지도 시각화 마커 기본 색상 및 검토 사항

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2402]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

업데이트 이전 지도 마커 기본 색상이 검은색(블랙)이었습니다. 현재 흰색(화이트)로 표시되고 있습니다.
시각화 옵션 최소 색상을 검은색으로 변경해도 반영되지가 않습니다.

보고서명 : 서울시 버스 정류장 지도 마커 테스트

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/86861299-bab87400-c101-11ea-9c36-bd878a6cfb39.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

지도 시각화의 레이어의 기본맵이 네이버지도에서 마커 정보가 1,000개 정도 되는데 
레이어의 Zoom In, Zoom Out 이벤트 발생시 반응 속도가 생각보다 너무 느린거 같습니다.

검토 부탁 드립니다.

**Comment by veldise** [comment]
현재 네이버 지도일 때는 `#FFFFFF`, OSM일 때는 `#000000`으로 색상이 설정되는 문제가 있습니다.

**Comment by swish1995** [comment]
지도의 색상 설정 방식이 그라데이션이고 참조할 값 (데이터 -> 색상) 이 없을때 기본 색상으로 표시되는 문제가 있습니다.
해당 문제는 그라데이션의 최소 색상으로 반영되도록 수정하겠습니다.

참고로 현재 상태에서 검은색으로 바꾸려면 색상설정 방식을 임계치로 바꾸고 최대 색상을 원하는 색으로 설정하면 바뀝니다.
