### ISSUE TITLE
[보고서 마이그레이션]  이슈사항

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2403]
## 버그 설명 ##

**데이터객체 있는 버전으로 마이그레이션 할 때 이슈**

- 모든 사용자 권한의 데이터모델인데, 데이터모델이 없습니다 라고 팝업창이 뜨고, 데이터모델 란에 이름이 없습니다.
    - b-iris.mobigen.com 에서 **EDU_Studio adv heatmap**   에서  데이터모델 EDU_SYSLOG_2020_0325_09 은 모든 사용자권한 모델입니다.
- 데이터를 가져온 뒤에 객체의 "이벤트값 전달 설정" 의 값필드를 다시 같은 이름으로 지정해줘야 이벤트가 전달됩니다.이미 설정이 되어 있어도 데이터필드를 다시 가져 와서 재지정을 해야 저장이 되는 것 같습니다.
- 테이블의 헤더 순서가 저장이 안되어 있어 다시 지정해줘야 합니다. 
- 객체의 "이벤트값 전달 설정"에서처럼  지도에서도 데이터를 실행하여 모두 가져온 뒤에  시각화옵션에서 데이터를 모두 같은 이름으로 다시 재지정해줘야 지도에 마커 등이 표시됩니다.
- pivot, adv 에서 SPLIROW 필드 에 따라 자동으로 sorting 을 해서 챠트를 그려줬는데, 지금은 끝에  sort 명령어를 추가해줘야 합니다.

* demo.iris.tools 의 EDU 카테고리 보고서 -> b-iris.mobigen.com 의 EDU2카테고리로 하여 이전한 보고서 참고하세요
    * b-iris.mobigen.com 에서 **EDU_Studio adv heatmap**  
    * b-iris.mobigen.com 에서 **EDU_Gallery Batting data Report**    : 챠트 sorting / 이벤트전달 / sorting 안되는 챠트
    * b-iris.mobigen.com 에서 **EDU_Gallery Seoul firecenter Report**  에서 지도가 안그려지는 문제 : 콤보박스데이터 전달 못 받음/시각화옵션에서 데이터 재지정해야 함

## 동일 사이트(demo.iris.tools) 에서 마이그레이션 이슈 정리 ( 07/14 추가 ) ##

1. 지도에 추가된 레이어는  실행 버튼 클릭 후  시각화옵션의  "데이터" 에서 (이미 지정이 되어 있지만) 콤보박스에서 다시 선택 해야 합니다.
   - 마커 로 지정한 포인트가 안 보입니다. ( 갤러리 : 서울시 안전센터 소방서 위치 및 화재 통계  http://demo.iris.tools:80/studio/exported/7f06343f8bfc4b69a5d588ba02fa62b4985dc56ac8424251b4f5c17389bccc81)
<img width="514" alt="스크린샷 2020-07-14 오전 7 56 10" src="https://user-images.githubusercontent.com/5126497/87361922-43269100-c5a8-11ea-9a72-f32aa39c6c8b.png">
 
2. 챠트 - 테이블에서 지정된 시각화옵션의 헤더대로 표시되지 않습니다. 즉 1번과 동일하게 모두 재지정해야 적용되는 것 같습니다.
  - 갤러리 : 야구데이터 분석 : Batting(타격)데이터  
 http://demo.iris.tools:80/studio/exported/8151353e89254d6d94dbadb373848482bdab9c3675ec495d9b1e0bd1cc8a3284

 - 시각화 옵션 - 헤더 에는 playerID, yearID 순으로 설정한 내용이 저장되어 있습니다.
<img width="506" alt="스크린샷 2020-07-14 오전 8 07 27" src="https://user-images.githubusercontent.com/5126497/87362348-5ab24980-c5a9-11ea-9c52-dc78922776d2.png">

- 하지만 결과는 미설정 상태로 표시
<img width="1301" alt="스크린샷 2020-07-14 오전 8 07 57" src="https://user-images.githubusercontent.com/5126497/87362421-93eab980-c5a9-11ea-9e29-1a9835b65b30.png">

3. 검색어 : adv line  을 사용 . 기존에는 이 명령어로 X축이 자동 ordering 되어 챠트가 그려졌습니다. 

`* 
| stats sum(G) as sum_G,
sum(AB) as sum_AB  BY YEARID, PLAYERID  
| sql "select YEARID, PLAYERID, sum_G ,  sum_AB from angora where sum_AB > 0 "  
| adv line avg(sum_G) as 평균경기수, avg(sum_AB) as 평균타석, 
max(sum_G) as 최대경기수, max(sum_AB) as 최대타석  SPLITROW YEARID COLSIZE 500`

- 예전 챠트 결과
<img width="688" alt="스크린샷 2020-07-14 오전 8 23 19" src="https://user-images.githubusercontent.com/5126497/87363063-4ec78700-c5ab-11ea-9374-9a1bd1591efd.png">

- 마이그레이션 후
<img width="706" alt="스크린샷 2020-07-14 오전 8 24 10" src="https://user-images.githubusercontent.com/5126497/87363110-67d03800-c5ab-11ea-867b-4137ae077b25.png">

**Comment by seoryjj** [comment]
demo.iris.tools 의 데이터모델은 권한이 없고
b-iris.mobigen.com 은 데이터모델이 모든 사용자용으로 되어 있을 때,  b-iris.mobigen 으로 이전한 보고서에서 데이터모델을 못찾고있습니다.

**Comment by veldise** [comment]
@seoryjj 
본문 내용이 잘 이해가 안 갑니다. 혹시 demo.iris.tools(구버전)에서 작성된 보고서를 b-iris.mobigen.com(최신버전)으로 이전한 건가요?

**Comment by seoryjj** [comment]
현재는 demo.iris.tools 의 보고서도 데이터객체버전으로 변경이 되어 있습니다.

완벽하게 그대로 이전이 안되는 문제로 
갤러리의 "야구데이터 분석 : Batting(타격)데이터" 보고서는 **테이블 헤더 목록 순서** 가 틀어졌고,
**라인챠트 X 축의 연도가 자동 sorting 되지 않아서**  연도순으로 보여지지 않고 있습니다.

예전의 보고서 outlook은  usecase 메뉴얼 문서에 남아 있습니다.
http://docs.iris.tools/manual/IRIS-Usecase/usecase4-batting_data/index.html#iris-studio

원본은 첫번째 테이블에  playerID, yearID 순으로 출력되었고,
라인챠트의 연도는 자동 sorting 되어 표시되었습니다.


이전한 데이터객체 최신 갤러리 보고서는 
<img width="1304" alt="스크린샷 2020-07-13 오후 2 26 54" src="https://user-images.githubusercontent.com/5126497/87273752-ee860600-c514-11ea-8b48-352417d82f69.png">

**Comment by veldise** [comment]
@seoryjj 
이전을 시도한 데이터(sql or csv)를 제가 받아봐야 정확하게 문제를 해결할 수 있을 것 같습니다.

**Comment by sunghoon** [comment]
@seoryjj 요청 정보 공유 되었는지요?
