### ISSUE TITLE
demo.iris.tools 보고서 링크 에러

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2404]
## 버그 설명 ##
iris.tools 갤러리에서 링크를 누르면 500 에러가 발생합니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to iris.tools > 갤러리 > Style transfer 선택
2. 500 에러 발생
3. demo.iris.tools > studio > style transfer 보고서 선택 > 수행결과 확인

## 스크린샷 ##
iris.tools error 화면
![image](https://user-images.githubusercontent.com/44352311/86877827-a46ee000-c122-11ea-976f-722299ee3087.png)

demo.iris.tools 보고서 실행
![image](https://user-images.githubusercontent.com/44352311/86877855-b18bcf00-c122-11ea-909e-0717cb7e3360.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
brick 서비스가 최신 버전이 아니어서 발생하는 문제로 생각됩니다.
신규 버전 빌드하여 해당 사이트에 배포 요청했습니다.

**Comment by EricLeeMbg** [comment]
![image](https://user-images.githubusercontent.com/44352311/86887888-40551780-c134-11ea-9bfb-24d5e476e55b.png)
현재 새 탭으로 사이트는 이동되나 빈화면이 출력됩니다.

**Comment by veldise** [comment]
@EricLeeMbg 
주소를 코멘트로 남겨주실 수 있나요?

**Comment by EricLeeMbg** [comment]
> @EricLeeMbg
> 주소를 코멘트로 남겨주실 수 있나요?

Style transfer demo 보고서의 URL입니다. 
  - http://demo.iris.tools/studio/exported/79e3ad5da91045e8b9e3c14bf709ed8df44837437c1e4d0cbac0abf9a99b4412

iris.tools > 갤러리 > 'Style Transfer 시연 ' 누르시면 확인하실 수 있습니다.

**Comment by veldise** [comment]
문제 해결되어 닫습니다.
