### ISSUE TITLE
[Discovery] indexer 명령어의 fit, transform 등 HDFS 파일 저장관련 파라미터 구문은 에러발생합니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2406]
## 버그 설명 ##

b-iris.mobigen.com demo 계정 크롬브라우저

데이터모델 : DEMO_TEST_WINE

`* | scaler minmax  Alcohol to Alcohol_s,
Malic_acid to Malic_acid_s, Proline to Proline_s |  indexer fit EDU_WINE_TRAIN_INDEXING classId  to classId_2 `

* 에러
<img width="580" alt="스크린샷 2020-07-09 오전 7 38 29" src="https://user-images.githubusercontent.com/5126497/86977379-6e2f7000-c1b7-11ea-990a-3fa7528fceab.png">

* HDFS 파일저장 없는 구문은 정상동작합니다.

`... | indexer classId to classId_s`

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
수정 완료될 때까지 indexer  정상동작하는 구문으로  manual 수정하겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 해당 이슈 진행 상황에 대한 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
작업 시작하면 코멘트로 공유드리겠습니다
