### ISSUE TITLE
[기능요청-DSL] pylambda 실행 시 input 컬럼배치와 동일한 output 일 때 컬럼이름을 유지시키는 옵션이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2407]
## 기능 요청 ##

SYSLOG 데이터

* 각 HOST 별로 비율을 구하고자 합니다.( sql 문을 사용하지 않으려고 pivot, calculate, pylambda  사용 )
`* |   pivot  count(*) as CNT  splitcol HOST  | 
  calculate add row | rename calculated TOTAL `

<img width="970" alt="스크린샷 2020-07-09 오후 3 46 54" src="https://user-images.githubusercontent.com/5126497/87006323-73161300-c1fb-11ea-8a96-2edf65bd593e.png">

* pylambda 로 각 HOST 별 비율을 백분율로 계산하기 -> WITH 스키마 구문이  없으면 컬럼명이 _숫자 로 나옵니다.
`* |   pivot  count(*) as CNT  splitcol HOST  | 
  calculate add row | rename calculated TOTAL |
 pylambda row : [  round(r / row[-1] * 100,  2) for r in row ]`

<img width="976" alt="스크린샷 2020-07-09 오후 3 48 42" src="https://user-images.githubusercontent.com/5126497/87006461-aeb0dd00-c1fb-11ea-8b78-f8017d94e1ba.png">

* pivot 으로 구한 컬럼이라 pylambda 의 WITH 문 뒤에 일일이 컬럼이름을 적기 어렵습니다.
이 예시처럼 input 과 output 의 데이터프레임 컬럼수와 순서가 동일하면 input 의 컬럼명을 output 으로 출력하게 하는 **옵션** 이 있으면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
pylambda 명령어에 `--use_input_schema` 옵션을 추가하였습니다.
해당 옵션은 모든 컬럼을 재사용 하는 것으로 사용할 때 주의해야합니다.
- 옵션 사용전
![Screen Shot 2020-09-10 at 11 47 18 AM](https://user-images.githubusercontent.com/46172579/92675967-996f4080-f35b-11ea-8f53-4de8dcd68427.png)
- 옵션 사용후
![Screen Shot 2020-09-10 at 11 47 54 AM](https://user-images.githubusercontent.com/46172579/92675970-9b390400-f35b-11ea-9dac-02e33448a38f.png)
