### ISSUE TITLE
Analyzer / Studio 두 솔루션의 데이터 표현법을 통일 시켜 주세요.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2408]
- 동일한 DSL 명령어를 Analyzer / Studio로 수행하였을때 데이터 표현법이 다릅니다.

- Analyzer
![스크린샷 2020-07-09 오후 4 49 26](https://user-images.githubusercontent.com/512653/87013047-0b64c580-c205-11ea-9d76-adbd107848c0.png)
- Studio
![스크린샷 2020-07-09 오후 4 49 33](https://user-images.githubusercontent.com/512653/87013052-0d2e8900-c205-11ea-81e5-a052edc66d47.png)

**Comment by veldise** [comment]
이전에 #1859 요청사항으로 2/13 패치한 내용입니다.
제가 잘못 판단한 것 같은데 논의 후 수정하겠습니다.

**Comment by sunghoon** [comment]
@veldise 본 이슈에 대한 최종 결과 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
Analyzer 에서는 특정 컬럼을 '시간 컬럼'으로 지정하고 시간 컬럼은 국가/언어 설정에 따라 적절한 시간 포맷으로 출력하게 되어있습니다.
Studio 에서도 비슷하게 시간 컬럼 및 TIMESTAMP 유형의 컬럼을 처리하였으나,
#1859 이슈에서 **Studio 에서는 포맷팅 없이 원본 데이터가 출력되는 것이 맞다**고 하여 Studio 는 이슈 본문과 같이 출력하고 있습니다.

Studio 에서도 국가/언어설정에 따라 시간 포맷을 적용해야 한다면 기획 등의 논의가 필요해보입니다.
