### ISSUE TITLE
secret_login의 경우 로그아웃 버튼이 없음

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2410]
## 버그 설명 ##
secret_login 으로 로그인 한 경우 로그아웃 버튼이 나타나지 않음

일반 로그인과 동일하게 로그인 후 로그아웃 할 수 있도록 처리 필요

## 스크린샷 ##
[일반 로그인/로그아웃 버튼 있음]
![logout_Y](https://user-images.githubusercontent.com/4444717/87102913-6d1d4200-c28e-11ea-94c2-a99a9d93a2a9.PNG)

[secret_login /로그아웃 버튼 없음]
![logout_N](https://user-images.githubusercontent.com/4444717/87102917-70b0c900-c28e-11ea-8ea6-13a73fcadfec.PNG)

**Comment by veldise** [comment]
확인 결과 `/secret_login` 경로를 통해서는 로그아웃 버튼이 나오고 이상이 없습니다만,
`/secret_login` 경로를 통해서 로그인을 한 뒤, 로그아웃을 하지 않은 상태에서 정상 경로로 접근하면 발생하는 문제로 추측됩니다.

처리에 시간이 다소 필요합니다.

**Comment by sunghoon** [comment]
@veldise 본 이슈에 대한 계획 정보를 공유 바랍니다.
