### ISSUE TITLE
Studio 카테고리 기능 개선 요청

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2411]
![스크린샷 2020-07-10 오전 9 55 06](https://user-images.githubusercontent.com/512653/87105017-afe21880-c294-11ea-8e92-9a9c69ecd876.png)

1. 콤포 박스에 전체(All)이외의 항목에 대해 정렬된 형태로 항목이 출력되게 해 주세요. 
   All
   가
   나 
   다

1-1 . 카테고리 내용이 다 표시 될 수 있도록 (...) 가변 길이를 적용해 주세요. 
        옆에 빈 공간이 많이 있습니다.

2. 카테고리 항목을 클릭하면 콤포박스에서 항목을 선택한 것과 같이 동작하게 해 주세요.
    빠른 필터/검색이 가능합니다.

**Comment by veldise** [comment]
@sunghoon 
항목 정렬에 대해서는 순서 기능와 배치되어서 적용하기 어렵습니다.

![image](https://user-images.githubusercontent.com/3411842/90842065-48da7800-e399-11ea-95c2-a5705f857076.png)

combo-box 에 필터 기능은 패치로 추가하였습니다.

**Comment by sunghoon** [comment]
@veldise  나머지 사항들은 어떻게 되나요?

**Comment by veldise** [comment]
@sunghoon 
가변길이는 디자인 파트와 논의를 해야합니다. 확인하고 알려드리겠습니다.
