### ISSUE TITLE
[Studio] 보고서 실행시 Python 에러 발생

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2412]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
보고서 실행시 Python 에러가 발생합니다.
('An error occurred while calling o312600.collectToPython.\n', JavaObject id=o312633)

## 재현하는 방법 ##
동작을 재현하는 방법 : 
1. 보고서 '공공조달_업체별_수주 현황_v1.6' 실행후
2. 아래 조건으로 설정 후 조회 버튼 클릭
![image](https://user-images.githubusercontent.com/5077625/87107351-89bf7700-c29a-11ea-96b9-507f19397730.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/5077625/87107306-64cb0400-c29a-11ea-8936-d4f1e0d3bec1.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
컴포넌트의 쿼리에서 `pylambda` 명령어의 사용이 잘못 되었습니다.
문제는 아래와 같은 쿼리가 실행되면 리턴 컬럼의 개수가 9개입니다.
```
pylambda row : row + [row[5].split(',').index('') if '' in row[5].split(',') else -1] 
```
하지만, 작성하신 내용중, with 로 각 컬럼의 이름을 지정한 개수가 8개 입니다.
```
pylambda row : row + [row[5].split(',').index('') if '' in row[5].split(',') else -1]  with `수주업체`: string, `날짜`: string, `공고명`: string, `계약금액`: int, `수요기관`: string, `워드`: string, `카운트`: string,  `인덱스`: int 
```

즉, 데이터는 9개 컬럼이 존재하는데, 8개 컬럼만 지정을 하여, 매핑에서 오류가 난 것입니다. 
아래와 같이 바꾸시면, 동작합니다. (컬럼A 는 바꾸시면 됩니다.)
```
pylambda row : row + [row[5].split(',').index('') if '' in row[5].split(',') else -1]  with `수주업체`: string, `날짜`: string, `공고명`: string, `계약금액`: int, `수요기관`: string, `워드`: string, `카운트`: string,  `인덱스`: int , `컬럼A`: int
```


아래에는 작성해 두신 쿼리이며, pylambda 명령어만 확인 해보시면 됩니다.

```
* 
| fields bidwinnrNm as 수주업체, bidwinnrBizno as 사업자등록번호, PRERGSTDT as 날짜, THTMCNTRCTAMT as 계약금액, PRDCTCLSFCNONM as 공고명, term_frequency as 워드, FREQUENCY_NUM as 카운트, STATE

| where STATE = '계약'
| where 사업자등록번호 is not null 

{% if bizno !='' %}
 | where 사업자등록번호 = '${bizno}'
    {% endif %}

| where 1=1
{% if search_type == 'true' and  keyword_1 !='' %}
 and 워드 like 
  '%${keyword_1}%'

    {% if keyword_1 != '' %}
    | pylambda row : row + [row[4].split(',').index('${ikeyword_1}') if '${ikeyword_1}' in row[4].split(',') else -1]  with `수주업체`: string, `날짜`: string, `계약금액`: int, `공고명`: string, `워드`: string, `카운트`: string,  `인덱스`: int
    {% endif %}
    
    {% if input_1 != '' %}
    | where 인덱스 > '${input_1}'
    {% endif %}

{% elseif search_type != 'true' and  keyword_1 !='' %}
  and 공고명 like 
  '%${keyword_1}%'
{% endif %}

| substr 날짜 1 4 as 년도

| stats count(*) as 수주건수, sum(계약금액) as 수주금액 by 년도

| sort +년도
```

**Comment by seungfwani** [comment]
추가적으로,
추후 pylambda 명령어를 개선하여, 본래 컬럼을 모두 사용하는 경우, 
지정을 하지 않아도 컬럼명이 정상적으로 나오도록 수정할 예정입니다.

**Comment by seungfwani** [comment]
@euhyesun 
해당문제는 답변이 된것으로 보고 닫도록 하겠습니다.

비슷한 문의가 있으면 언제든지 재오픈 하여 코맨트 남겨주시기 바랍니다.

**Comment by euhyesun** [comment]
아래와 같은 에러가 발생합니다.

보고서: 공공조달_공고 목록_v0.4
![image](https://user-images.githubusercontent.com/5077625/88015431-1b14d000-cb5c-11ea-97cf-8b893ca6bb15.png)

angora error: <class 'py4j.protocol.Py4JJavaError'>
('[SPARK] org.apache.spark.api.python.PythonException: Traceback (most recent call last):',)

확인 부탁드립니다. 감사합니다.

**Comment by seungfwani** [comment]
where 조건으로 검색을 할 때 좀 더 상세한 조건으로 해야할 듯 합니다.

명령어중 `where 1=1   and 워드 like '%조사%'` 에 해당하는 명령어 가 있는데, `조사` 라는 단어가 포함된 값을 찾는 내용입니다.
이 `조사`에는 `,조사,` 도 있지만, `설문조사` 와 같은 값도 있습니다.

문제는  pylambda 명령어를 통해서 python 문법인 list.index() 함수를 쓰게 되면, `조사`라는 단어가 리스트에 없으면 에러가 나게 됩니다.
-> 예를들어, `['설문조사', '입찰'].index('조사') ` 를 실행하면 에러가 납니다.

따라서 `where 1=1   and 워드 like '%,조사,%'` 와 같이 콤마로 구분된 단어 라고 변형을 해주시면 될 것 같습니다.


아래는 해당 명령어 전문입니다.
```
model name = 'EPS_DATA_BIS' model_owner = root start_date = 20190101000000 end_date = 20190331235959

| fields preRgstDt as 날짜, STATE as 구분, dminsttNm as 수요기관, bidNtceNo as 입찰공고번호, bidNtceOrd as 차수, prdctClsfcNoNm as 품명, preAsignBdgtAmt as 배정예산금액, sucsfbidMthdNm as 낙찰방법, bidNtceDtlUrl as 입찰공고URL, untyCntrctNo as 통합계약번호, thtmCntrctAmt as 계약금액, cntrctCnclsMthdNm as 계약체결방법, mainContractor as 계약업체, term_frequency as 워드, frequency_num as 카운트

| where 구분 = '입찰' or 구분 = '계약' 

| where 수요기관 is not null  

| substr 날짜 1 8 as 일자 

| calculate (계약금액/배정예산금액)*100 as 낙찰률(%) 

| fields 구분, 일자, 입찰공고번호, 차수, 품명, 배정예산금액, 수요기관, 낙찰방법, 통합계약번호, 계약금액, 낙찰률(%), 계약체결방법, 계약업체, 입찰공고URL, 워드, 카운트 

| where 1=1   and 워드 like '%조사%'       

| pylambda row : row + [row[14].split(',').index('조사')] + [int(row[15].split(',')[row[14].split(',').index('조사')])] with `구분`: string, `일자`: string, `입찰공고번호`: string, `차수`: string, `품명`: string, `배정예산금액`: int, `수요기관`: string, `낙찰방법`: string, `통합계약번호`: string, `계약금액`: int, `낙찰률(%)`: float, `계약체결방법`: string, `계약업체`: string, `입찰공고URL`: string, `워드`: string, `카운트`: string, `인덱스`: int, `빈도수`: int                  

| where 빈도수 > '10'
```

**Comment by seungfwani** [comment]
확인 되셨는지 궁금합니다.

해결이 되었다면 이슈 닫아주시기 바랍니다.

**Comment by euhyesun** [comment]
@seungfwani 
네, 정상 동작합니다.
감사합니다.
