### ISSUE TITLE
피벗분석 / 템플릿 저장에러

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2414]
## 버그 설명 ##
피벗분석 수행 및 템플릿 저장 에러

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to '피벗분석'
2. Click on 'SYSLOG_2020_0326_09'
3. 필터 'GCS1' 추가 후 실행

## 스크린샷 ##
- 실행에러
![image](https://user-images.githubusercontent.com/44352311/87114397-74067d80-c2ab-11ea-9468-cd64604e7bc0.png)

- 템플릿 저장 에러
![image](https://user-images.githubusercontent.com/44352311/87114466-a31cef00-c2ab-11ea-9681-335a2f1ca6bc.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
버전 문제로 배포후 처리되었습니다.
