### ISSUE TITLE
피벗으로 이동 시 에러

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2415]
## 버그 설명 ##
analyzer 검색 후 피벗/고급시각화  이동 시 에러 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'Analyzer'>검색
2. Click on 'SYSLOG_2020_0325_09'
3. '최근 6개월' 선택 후 검색
4. '피벗으로 이동' 선택 후 에러

## 스크린샷 ##
- 피벗분석 이동 에러
![image](https://user-images.githubusercontent.com/44352311/87115778-2b50c380-c2af-11ea-80cc-e372260786a0.png)
- 고급시각화 이동 에러
![image](https://user-images.githubusercontent.com/44352311/87115851-6226d980-c2af-11ea-9c68-6afba5f61527.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
버전 문제로 배포후 해결되었습니다.
