### ISSUE TITLE
새모델 생성 시, 대상 데이터 업로드 할 경우 에러 발생

### ISSUE THREAD

**Issue by stgim** [mobigen/IRIS-BigData-Platform#2416]
## 버그 설명 ##
새모델 생성 시, 대상 데이터 업로드 할 경우 에러 발생

##사전 조건##
1. 서울시 열린 데이터 광장에서 임의의 csv 파일 데이터 내려 받기
2. 내려 받은 csv 파일을 파일 브라우저 MINIO에 파일 업로드

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS Discovery 선택
2. 데이터 모델 선택
3. 새모델 선택
4. 대상 데이터 모델 > 찾아보기 > 다운로드 받은 csv  파일 선택

## 예상한 행동 ##
- 대상 데이터 모델에서 선택한 csv 파일 내용이 로딩되어 보여야 합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/67949847/87117274-1bd37980-c2b3-11ea-9194-f333227f375e.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
이슈 본문 자체는 경로에 없는 파일을 지정하여 발생하는 문제입니다.

![image](https://user-images.githubusercontent.com/3411842/87128469-9fe52b80-c2ca-11ea-8b10-c1572b7324e2.png)

현재 한글 파일 업로드가 안되는 버그가 있습니다.

**Comment by veldise** [comment]
한글 파일 업로드 이슈가 해결되었기에 닫습니다.
