### ISSUE TITLE
시각화/모션차트의 시간 컬럼 설정시 분/시간/일 등의 그룹설정 기능이 필요함

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2417]
## 버그 설명 ##
시각화/모션차트의 시간 컬럼 설정시 분/시간/일 등의 그룹설정 기능이 필요함
다른 라인/바 차트와 같이 시간값에 대한 "Summary 시간 단위" 설정 기능 추가 필요

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/4444717/87118530-9a7de600-c2b6-11ea-8018-fe1cdb4b5154.png)

[일반 차트에서의 시간 설정 화면]
![image](https://user-images.githubusercontent.com/4444717/87118561-af5a7980-c2b6-11ea-9152-4d08f52bfa42.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
UI 기능 변경에 따라 `adv motion` 명령어에 옵션이 필요합니다.

**Comment by sunghoon** [comment]
@veldise @seungfwani 진행 상태 정보를 공유 해 주세요.
