### ISSUE TITLE
시각화/차트에서 date_group으로 생성된 컬럼을 날짜로 사용시 오류 발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2418]
## 버그 설명 ##
1. 검색에서 date_group을 이용하여 날짜값을 그룹핑 한 후 시각화로 이동하여 실행시 오류가 발생함
 - 데이터모델 : BATTING
 - DSL: *|stats sum(R),sum(H),sum(G) BY date_group(FTS_PARTITION_TIME,"1H"),PLAYERID 

#DSL생성시 컬럼명을 기존 모델의 컬럼명과 동일하게 rename처리해 주면 동작 하기는 함, 그러나 이 작업 없이도 시각화에서 DSL에서 검색된 결과 컬럼 값을 이용하여 사용 할 수 있도록 처리가 필요 할 것 같음.

2. 동일한 문제로 발생하는 것으로 보이는데, 보고서 생성 기능에서 DSL을 입력하여 검색된 내용을 모션차트로 적용 하고자 하면, 날짜 컬럼은 선택이 불가하게 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 검색 화면에서 "BATTING" 모델 선택 후 *|stats sum(R),sum(H),sum(G) BY date_group(FTS_PARTITION_TIME,"1H"),PLAYERID  검색 실행
2. 이동 버튼으로 시각화로 이동
3. 라인차트 선택후  실행

## 스크린샷 ##
1.시각화 실행시 오류 화면
![image](https://user-images.githubusercontent.com/4444717/87120338-21cd5880-c2bb-11ea-9eb7-5f63d1932308.png)

2. 보고서에서 모션차트 선택시 날짜 선택이 불가
![image](https://user-images.githubusercontent.com/4444717/87119307-905ce700-c2b8-11ea-9f16-5c9bce9e9d3a.png)

**Comment by veldise** [comment]
2번은 DSL 결과에서 dategroup 컬럼의 유형이 TEXT라서 발생하는 문제입니다.

```js
  "fields": [
    {
      "name": "dategroup",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "PLAYERID",
      "type": "TEXT",
      "grouped": false
    },
```

**Comment by seungfwani** [comment]
1번
- 시각화 의 경우, 생성된 데이터 모델의 컬럼을 기준으로 차트를 생성해주는 화면입니다.
- stats 명령어의 결과로, `FTS_PARTITION_TIME` 컬럼이 `date_group` 함수를 통해 계산이 되어, `dategroup` 이라는 컬럼으로 재생성 되었습니다.
- 시각화에서는 이 컬럼(`dategroup`)을 선택 해서 차트를 그려야 사용자가 원하는 그래프를 그릴 수 있습니다.
- 하지만, 현재 상황에서는 그릴 수 없습니다.
- 데이터모델 뷰 기능이 추가되면 stats 로 처리된 데이터를 이용해 시각화를 할 수 있습니다.

**Comment by seungfwani** [comment]
![Screen Shot 2020-07-13 at 9 21 14 PM](https://user-images.githubusercontent.com/46172579/87303851-c9ae8480-c54e-11ea-883c-b09ec6fa16c1.png)
![Screen Shot 2020-07-13 at 9 21 27 PM](https://user-images.githubusercontent.com/46172579/87303868-d206bf80-c54e-11ea-8c12-64978d395de8.png)
![Screen Shot 2020-07-13 at 9 21 40 PM](https://user-images.githubusercontent.com/46172579/87303886-d9c66400-c54e-11ea-8b37-c15d2c783e78.png)

dategroup 결과가 timestamp type 이 되도록 수정하였습니다.

**Comment by seungfwani** [comment]
해결된 것으로 보며 닫습니다. 추가 이슈 발생시 새 이슈 등록 부탁드립니다.
