### ISSUE TITLE
docs.iris.tools 메뉴얼사이트에서 블로그, 갤러리, 지원 등으로 이동하려고 클릭하면 이동 안 됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2420]
## 버그 설명 ##

 docs.iris.tools  에서 우측 상단 메뉴로 이동 안됩니다.

- safari 에서는 갤러리, 지원 등을 클릭하면 다운로드가 동작합니다.

<img width="1354" alt="스크린샷 2020-07-13 오후 2 01 04" src="https://user-images.githubusercontent.com/5126497/87272855-71f22800-c512-11ea-8c7f-58db92d8c197.png">

- 크롬은 401 에러 뜹니다.
<img width="703" alt="스크린샷 2020-07-13 오후 2 08 36" src="https://user-images.githubusercontent.com/5126497/87272916-a0700300-c512-11ea-8f6f-e233ab9c93f9.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by EricLeeMbg** [comment]
신규 iris.tools 배포 시 URL 변경이 원인 이었습니다. 조치되었으며, 향후 배포 시 바로 변경사항을 반영할 예정입니다.
