### ISSUE TITLE
[Studio] 체크박스 사용 중 중간에 아무것도 선택하지 않으면 해석안되는 에러 팝업창이 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2421]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정 

보고서 : EDU  카테고리 "DEMO_북경대기질분석 ing" 

- 디폴트 설정을 해서 1월이 처음에는 체크되어 있습니다.
<img width="204" alt="스크린샷 2020-07-14 오전 9 30 33" src="https://user-images.githubusercontent.com/5126497/87368036-889e8a80-c5b7-11ea-89ab-4f867e82eddc.png">

- 그러나 사용자가 아무 것도 체크를 하지 않으면 이런 에러창이 뜹니다.
<img width="514" alt="스크린샷 2020-07-14 오전 9 29 37" src="https://user-images.githubusercontent.com/5126497/87368110-b08dee00-c5b7-11ea-82e4-a3c9ea981504.png">

- 검색어 구문 :  checkbox_1 을 사용한 데이터 객체 검색어
`* |  where month in ( ${checkbox_1}  )  |
stats avg(PM2_5) as  PM2_5평균 , avg(PM10) as PM10평균  BY  year  | sort year`

- 체크박스/라디오버튼 에서 아무것도 선택하지 않을 때,  **checkbox_1**  이  빈값이 되어서 검색어에 전달되어 생긴 오류 같습니다.
- 체트박스는 사용자가 아무 것도 선택하지 않을 수 있습니다.
<img width="89" alt="스크린샷 2020-07-14 오전 9 29 42" src="https://user-images.githubusercontent.com/5126497/87368027-84726d00-c5b7-11ea-9435-751e65ac721a.png">

- chekbox_1 이 빈값으로 이벤트 전달이 되지 않도록 하는 설정이 필요해 보입니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise @swish1995 오류 메시지를 사용자가 알수 있도록 적절하게 대응해 주세요. 
@seoryjj if 문을 활용하여 값이 없을때는 동작 하지 않도록 쿼리를 작성해 주시면 될 것 같습니다.

**Comment by veldise** [comment]
@sunghoon 
본문 에러는 Discovery가 반환하는 것으로 보이고, 금일 패치로 오류 발생시 아래와 같이 출력됩니다.

![image](https://user-images.githubusercontent.com/3411842/94099837-d90f4f80-fe66-11ea-9bd8-2fffe6fea13d.png)
