### ISSUE TITLE
sql 의 case when end 문에 대응하는 DSL 이 필요합니다.

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2422]
## 기능 요청 ##
sql 의 case when end 문에 대응하는 DSL 이 필요합니다.
구두로 설명드렸던 부분입니다.
제 생각에는 이 명령어만 만들어지면 sql 문에서 수행되는 대부분의 기능이 동작될것 같습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
`case` 명령어를 추가하였고, [b-iris.mobigen.com](b-iris.mobigen.com) 에서 사용이 가능합니다.
![Screen Shot 2020-09-10 at 11 41 03 AM](https://user-images.githubusercontent.com/46172579/92675516-8a3bc300-f35a-11ea-8516-8090636c76e5.png)

명령어문서: http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/case.html
