### ISSUE TITLE
geomap, geostats 2개 명령어 점검 필요

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2423]
## 버그 설명 ##
명령어가 제대로 동작하지 않는것 같습니다.
이 명령어는 아직까지 많이 사용되지 않는 명령어라 이슈화는 안되고 있는것 같습니다.
제가 내용을 잘 몰라 자세한 내용은 "신운선" 책임과 상의 바랍니다.
(위경도 값의 출력이 바뀌어 나오는 것 같다고 합니다.)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
신운선 책임과 별도로 확인 하도록 하겠습니다. 이슈는 닫겠습니다.
