### ISSUE TITLE
forecasts 차트 버그

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2424]
## 버그 설명 ##
아래 그림 참조

![스크린샷 2020-07-14 오후 2 42 32](https://user-images.githubusercontent.com/3468426/87388761-60775180-c5e0-11ea-8a0c-5ab9cba5a03b.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seungfwani 
NEW_DATE 값이 YYYYMMDDHHmmss 포맷이 아닌 다른 값으로 반환됩니다.
```
  "fields": [
    {
      "name": "NEW_DATE",
      "type": "TEXT",
      "grouped": false
    },
    {
      "name": "CNT",
      "type": "REAL",
      "grouped": false
    },
    {
      "name": "forecasts",
      "type": "BOOLEAN",
      "grouped": false
    }
  ],
  "results": [
    [
      "2020-07-15 04:00:00",
      1258.0,
      false
    ],
```

**Comment by sunghoon** [comment]
@veldise 데이터포맷과 상관없이 전달받은 순서로 그래프를 그래야 하는건 아닌지요?

**Comment by veldise** [comment]
@sunghoon 
위 상황에서는 UI에서 `NEW_DATE`를 시간값으로 처리할 기준이 없어서 그렇습니다.

**Comment by seungfwani** [comment]
수정완료 하였으며, 아래와 같이 테스트가 정상적인 것을 확인 했습니다.

b-iris.mobigen.com 에 배포된 후 이슈 닫도록 하겠습니다.

![Screen Shot 2020-09-11 at 5 10 38 PM](https://user-images.githubusercontent.com/46172579/92890053-bd14b280-f451-11ea-931b-9bb1cadb0e8b.png)

**Comment by seungfwani** [comment]
배포 완료되어 닫습니다.
![Screen Shot 2020-09-22 at 10 44 16 AM](https://user-images.githubusercontent.com/46172579/93837316-91e75a00-fcc0-11ea-8e60-9938fb34d247.png)
