### ISSUE TITLE
탭 환경의 웹브라우저에서 다른 웹 화면 갔다가 아이리스로 돌아오면 화면이 안보이는 현상

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2425]
## 버그 설명 ##
탭 환경의 웹브라우저에서 다른 웹 화면 갔다가 아이리스로 돌아오면 화면이 안보입니다.
아래 그림 참조

![스크린샷 2020-07-14 오후 2 44 29](https://user-images.githubusercontent.com/3468426/87388922-b21fdc00-c5e0-11ea-943b-764aad426051.png)

![스크린샷 2020-07-14 오후 2 44 39](https://user-images.githubusercontent.com/3468426/87388937-b8ae5380-c5e0-11ea-832e-128112264a5c.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
환경 정보:
macOS Catalina 10.15.6
Safari 13.1.2(15609.3.5.1.3)

**Comment by lyj** [comment]
현상이 재현되지 않습니다. 상세 설명이 필요합니다.

**Comment by sunghoon** [comment]
오래되었고, 재현되지 않아 닫도록 하겠습니다.
