### ISSUE TITLE
[DSL  추가 요청] interpolation 명령어가 필요합니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2426]
## 기능 요청 ##
시계열 데이터( timestamp 필드가 있는 데이터) 대상으로  동일한 시간 gap 을 설정했을 때
gap 을 채우는  명령어가 필요합니다.

참고 사이트 : https://towardsdatascience.com/end-to-end-time-series-interpolation-in-pyspark-filling-the-gap-5ccefc6b7fc9

이 DSL 이 있어야  anomalies, forecast,  pivot 에서 집계 데이터를 제대로 만들 수 있습니다.

예시 처럼 HOST = ans41  같은 경우에  10분 단위 gap을 0 으로 채워서 나오게 하고 해야 합니다. 
0 외에 데이터 특성에 맞게 필요한 값을 인자로 받아서 시간 단위 gap 을 채우는 interpolation 명령어가 필요합니다.

- 이 명령어는 anomalies, forcasts, outlier, 기계학습 모델 관련 명령어, 이상탐지, pivot ... 등 집계를 하는 모든 경우에 필요합니다.
- 지금까지는 데이터를 내려받아서 R 이나 python 으로 프로그램을 쨔서 값을 채운 후 다시 로딩하여 사용하거나, fill_zero 라는 개인적인 외부 명령어를 사용했습니다.(fill_zero 는 현재 동작하지 않습니다.)

## 예시 ##

 syslog 최근 60분 데이터 10분 단위 gap 으로 집계 
    - HOST = gcs4  는  다행히 데이터가 많아서 10분마다 서머리가 나옵니다.
<img width="900" alt="스크린샷 2020-07-15 오전 11 12 56" src="https://user-images.githubusercontent.com/5126497/87495470-74788d00-c68c-11ea-90e2-f65aef02a557.png">

`* | pivot count(*) SPLITROW 'date_group("DATETIME", "10M")' , HOST SPLITCOL LEVEL FILTER HOST='ans41' AND  LEVEL = 'notice' COLSIZE 500`

 
<img width="927" alt="스크린샷 2020-07-15 오전 11 13 45" src="https://user-images.githubusercontent.com/5126497/87495543-9a059680-c68c-11ea-93ba-a2780622c040.png">

- HOST ans41 의 정확한 10분 집계는 10:10 ,10:20 ,,, 에는 0 으로 채워진 결과로 나와야 겠지요

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@seungfwani 이슈 최종 상태 정보를 알려주세요.

**Comment by seungfwani** [comment]
192.168.100.180 서버에 아래와 같이 실행이 가능하도록 하였습니다.
해당 기능이 맞는지 확인 부탁드립니다.

```
* | interpolation avg(level_int), sum(level_int), count(level_int) by=host index=datetime interval=60S fillna=1
```
![Screen Shot 2020-10-13 at 1 59 03 PM](https://user-images.githubusercontent.com/46172579/95817392-4f172000-0d5c-11eb-9ee1-488af4bf2e97.png)

**Comment by seoryjj** [comment]
- 명령어 사용 예시

` * | WHERE HOST = 'hadoop02' | interpolation  count(*)  as CNT   by=HOST  index=DATETIME interval=60S fillna=0`

` * | WHERE HOST = 'hadoop02' | interpolation  count(*) as CNT   by=HOST,LEVEL  index=DATETIME interval=60S fillna=0`

- stats 와 동일하게 집계 기능이 동작하면 됩니다. 그런데 지금 버전은 count(*) 같이 사용하면 에러납니다. 

` * | WHERE HOST = 'hadoop02' | interpolation  count(*)   by=host  index=datetime interval=600S fillna=0`

<img width="310" alt="스크린샷 2020-10-13 오후 2 25 23" src="https://user-images.githubusercontent.com/5126497/95818948-f9447700-0d5f-11eb-965b-d2fa93855103.png">

<img width="336" alt="스크린샷 2020-10-13 오후 2 26 51" src="https://user-images.githubusercontent.com/5126497/95819058-36106e00-0d60-11eb-9010-a9dea711122c.png">

**Comment by seoryjj** [comment]
데이터의 시작시간과 종료시간을 받아서 처리해야 하는데 그 부분이 안보입니다.

**Comment by seungfwani** [comment]
@seoryjj @anhm 
빌드 테스트 완료 하였으며,
(20.10.16) 배포요청 하였습니다.
