### ISSUE TITLE
[Studio] 지도 객체에서 geometry 가 있는 레이어에서 시각화유형을 2번째 누르면 표시된 시각화유형이 사라집니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2427]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정 크롬브라우저
이슈 카테고리 : 서울시 행정도 지도

레이어에 시각화유형-도형을 클릭해서 표시가 된 후 다시 시각화유형-도형을 클릭하면 안보입니다.
데이터탭에서 실행을 클릭하면 다시 그려지는데,  저장된 시각화옵션의 일부만 적용되어 그려집니다.
색상은 저장된 대로 그려집니다.
툴팁은 저장은 되어 있으나 마우스를 대어도 반응은 없습니다.

- 처음에는 시각화유형 도형을 선택하면 잘 그려집니다.
<img width="769" alt="스크린샷 2020-07-15 오후 2 20 30" src="https://user-images.githubusercontent.com/5126497/87507883-24f48a00-c6a9-11ea-84b7-a48926a66a6a.png">

- 시각화유형 도형을 다시 클릭하면 그렸던 게 사라집니다. 
<img width="765" alt="스크린샷 2020-07-15 오후 2 27 50" src="https://user-images.githubusercontent.com/5126497/87506901-608e5480-c6a7-11ea-8057-e3e60d348c42.png">

- 다시 데이터탭에서 실행버튼을 누르면 다시 보입니다. 그런데 시각화옵션에 저장된 색상으로는 그려지는데, 설정이 되어 있는 툴팁은 표시되지 않습니다.

<img width="540" alt="스크린샷 2020-07-15 오후 2 42 35" src="https://user-images.githubusercontent.com/5126497/87508038-6f760680-c6a9-11ea-8807-3d2a41952ef9.png">

<img width="441" alt="스크린샷 2020-07-15 오후 2 31 28" src="https://user-images.githubusercontent.com/5126497/87507738-de9f2b00-c6a8-11ea-9b3b-61ab59cb93ba.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
금일 패치로 문제 해결하였습니다.
