### ISSUE TITLE
[Studio] 지도에서 툴팁이 NaN 으로 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2428]
## 버그 설명 ##
b-iris.mobigen.com demo 계정  "서울시 행정도 지도"

<img width="441" alt="스크린샷 2020-07-15 오후 2 31 28" src="https://user-images.githubusercontent.com/5126497/87508712-fa0b3580-c6aa-11ea-8391-9aaac4799d26.png">

<img width="544" alt="스크린샷 2020-07-15 오후 2 27 31" src="https://user-images.githubusercontent.com/5126497/87508736-04c5ca80-c6ab-11ea-9b6b-97e0d2df452e.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
- 그라데이션 색상에 대한 참조값이 TEXT 타입일때 해당 값을 숫자로 변환하는 로직으로 인해 발생하는 문제로 확인되었습니다.
- 툴팁 관련해서는 제대로 나오도록 수정하고, 색상 참조값이 TEXT 일때는 그라데이션 색상의 최소값으로 표현되도록 수정하겠습니다.

**Comment by veldise** [comment]
금일 패치로 문제 해결하였습니다.
