### ISSUE TITLE
[Studio]시각화 옵션에서 글자 색상 선택하면 속성의 글자 색상에 반영 안되는 문제 발생 됩니다.

### ISSUE THREAD

**Issue by stgim** [mobigen/IRIS-BigData-Platform#2430]
## 버그 설명 ##
시각화 옵션에서 글자 색상 선택하면 속성의 글자 색상에 반영 안되는 문제 발생 됩니다.

##사전조건##
- http://b-iris.mobigen.com > 로그인

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS Studio 보고서 선택
2. 라벨 선택 > 속성 선택 > 시각화 옵션 선택
3. 일반 > 글자 색상 선택 > 임의의 색상 선택

## 예상한 행동 ##
시각화 옵션에서 글자 색상 선택하면 속성에 선택한 글자 색상이 반영 되어야 합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/67949847/87523634-21b9c800-c6c2-11ea-8b5f-1a9fdeab44e8.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
현재 재현되지 않습니다.

![image](https://user-images.githubusercontent.com/3411842/87612432-81a58280-c745-11ea-9cc0-08f1a4dcccf5.png)

**Comment by stgim** [comment]
OS : 윈도우10 Pro
브라우저 : 크롬 (버전 83.0.4103.116(공식 빌드) (64비트)) 입니다.

**Comment by sunghoon** [comment]
우선 닫습니다. 
같은 현상이 재발하면 다시 이슈로 등록 해 주세요.
