### ISSUE TITLE
[Studio]볼드, 밑줄, 이탤릭체, 취소선 매뉴 선택하면 아무 반응이 없어서 매뉴가 선택 안되는 문제 발생 됩니다.

### ISSUE THREAD

**Issue by stgim** [mobigen/IRIS-BigData-Platform#2431]
## 버그 설명 ##
볼드, 밑줄, 이탤릭체, 취소선 매뉴 선택하면 아무 반응이 없어서 매뉴가 선택 안되는 문제 발생 됩니다.

##사전조건##
http://b-iris.mobigen.com > 로그인

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS Studio 보고서 선택
2. 라벨 선택 > 속성 선택 > 시각화 옵션 선택
3. 일반 > 볼드, 밑줄, 이탤릭체, 취소선 매뉴 선택

## 예상한 행동 ##
볼드, 밑줄, 이탤릭체, 취소선 매뉴 선택하면 정상적으로 매뉴 선택이 되어야 합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/67949847/87524910-c25cb780-c6c3-11ea-9da6-c13b8b275b6b.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
현재 재현되지 않습니다.

![image](https://user-images.githubusercontent.com/3411842/87612490-a863b900-c745-11ea-9c8d-3ff3b12647b1.png)

**Comment by stgim** [comment]
OS : 윈도우10 Pro
브라우저 : 크롬 (버전 83.0.4103.116(공식 빌드) (64비트)) 입니다.

**Comment by sunghoon** [comment]
일단 닫아 두겠습니다.
같은 현상이 재발하면 다시 이슈 등록 해 주세요.
