### ISSUE TITLE
[Discovery] 데이터모델 메뉴에서 전체 사용자에게 공유된 데이터모델인데 복사가 안됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2432]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- root 에서 생성한 데이터모델 - 전체 사용자 권한의 EDU_TRAIN_WINE
<img width="1233" alt="스크린샷 2020-07-16 오전 8 49 24" src="https://user-images.githubusercontent.com/5126497/87610857-75b7c180-c741-11ea-9cb4-0d3a4b75b870.png">

- 데이터모델 복사가 안됩니다. 
<img width="751" alt="스크린샷 2020-07-16 오전 8 49 16" src="https://user-images.githubusercontent.com/5126497/87610888-93852680-c741-11ea-97b0-e6ad207f0016.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
확인 결과, 버그가 아니고 demo 계정이 `demo-minio` 연결 정보에 권한이 없어서 발생하는 문제로 확인되었습니다.

이 문제 해결에 대해서 별도로 논의가 필요합니다.

**Comment by sunghoon** [comment]
@veldise 누구랑 어떻게 논의 하여야 하나요? 논의 진행 해 주세요.
