### ISSUE TITLE
차트의 배경색 지정 기능

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2433]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.

 차트가 경우 현재 테두리 및 그림자의 색상만 변경 가능하도록 되어 있습니다. 
( 제가 필요한건 단일 값과 꺾은선 그래프 등의 배경색 변경 )
![image](https://user-images.githubusercontent.com/16331916/87615532-e6fd7180-c74d-11ea-9761-cca2a4412396.png)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
 차트의 배경색을 지정할 수 있으면 좀 더 세련된 디자인으로 보고서를 작성할 수 있을 듯 합니다.
![image](https://user-images.githubusercontent.com/16331916/87615681-38a5fc00-c74e-11ea-9c87-356d3f35b684.png)

 위 화면은 Text Field 의 객체 옵션 입니다. 위와 같이 차트의 경우도 테두리 외의 배경색을 지정할 수 있으면 좋겠습니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by swish1995** [comment]
@veldise 차트의 배경색은 차트 속성으로 수정이 가능한것으로 알고 있는데 이건 다른기능인건가요?

**Comment by veldise** [comment]
@swish1995 
본문 스크린샷의 기능은 '객체'에 대한 스타일 속성이고, 현재 차트 객체에는 차트만 존재하는 것이 아니라서
차트(Highcharts) 배경색만 설정하면 적절하게 배경색이 설정되지 않습니다.

이 내용은 기획이 필요한 건입니다.

**Comment by sunghoon** [comment]
@veldise @swish1995 챠트 배경색을 지정할때 색지정을 하지 않거나. 배경색의 투명도를 설정할 수 있도록 지원 부탁드립니다. ^^

**Comment by sunghoon** [comment]
@eumminsun 검토 후 진행 바랍니다.
