### ISSUE TITLE
여러개 tab 에서 작업 시 1개 탭에서 로그아웃 후 다른 계정으로 로그인 하면, 다른 탭에서 계정이름이 변경되지 않은 채로 메뉴가 동작합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2434]
## 버그 설명 ##
b-iris.mobigen.com  크롬

- demo 계정으로 3개의 탭에서 작업중에 1개 탭에서 로그아웃 후 myiris 계정으로 로그인
- 옆의 다른 탭의 Analyzer 에서 실행 - HDFS 내보내기 하니 로그인한 myiris 의 HDFS 디렉토리로 나옵니다만 계정은 예전 demo 로 표시됩니다.
<img width="1303" alt="스크린샷 2020-07-16 오전 10 48 30" src="https://user-images.githubusercontent.com/5126497/87617975-a6a0f200-c753-11ea-9728-9d391918078b.png">

- 실행 버튼이나 다른 메뉴 버튼을 눌러도 정상 동작이 되어서 사용자가 헷갈릴 수 있습니다.( multi 계정을 지원하는 줄로... )
- 사용자가 브라우저에서 계정을 변경할 때 마다 re-load를 부지런히 누르면서 사용하지는 않을 거 같습니다.  다른 메뉴나 버튼을 클릭하면 실제 로그인한 계정으로 변경이 되던지, 다른 탭도 자동 로그아웃이 되어야 할 것 같습니다.

 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by lyj** [comment]
처리되어 배포하였습니다.
