### ISSUE TITLE
요청 [Studio] map 에서 naver 지도의 기본레이어 표현 콤보박스를 옵션에서 사용/미사용 선택할 수 있게 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2435]
## 기능 요청 ##
b-iris.mobigen.com  demo 계정

- naver 지도에서 오른쪽 상단 naver 지도의 레이어표현을 선택하는 콤보박스가 있습니다.
<img width="536" alt="스크린샷 2020-07-17 오전 10 35 24" src="https://user-images.githubusercontent.com/5126497/87738826-3c528500-c819-11ea-84de-2237e435c891.png">

- 지도 레이어를 투명하게 해서 표현을 할 필요가 있는데, 이 콤보박스는 의미가 없이 혼란을 줄 수 있어서 옵션으로 처리할 수 있었으면 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 검토 후 진행 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
처리 완료되어 11/5 패치 예정입니다.

- Map / (Naver Web Map) basemap 선택 UI를 보이지 않게 하는 '지도 선택 기능' 설정 추가

![image](https://user-images.githubusercontent.com/3411842/98053685-7bfeb480-1e7c-11eb-89d5-ca32173ab7b2.png)
