### ISSUE TITLE
[Discovery] "새모델 뷰" 의 창이름이 "새 모델"이 아니라 "새 모델 뷰" 로, "모델 이름" 을 "모델 뷰 이름" 으로 수정해야 혼동이 없을 거 같습니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2436]
## 버그 설명 ##
b-iris.mobigen.com 

기능 및 UI 수정 속도보다 manual 수정 보완이 느리기 때문에, 
manual 없이 기존 사용자가 혼란없이 사용할 수 있도록 이름이나 기능 설정 UI 구성이 되었으면 합니다.

- **새 모델 뷰**  클릭
<img width="193" alt="스크린샷 2020-07-20 오전 7 53 48" src="https://user-images.githubusercontent.com/5126497/87887358-55e50e00-ca5f-11ea-941a-819ab9d9001f.png">

- 팝업창 제목이 "새 모델" 로 나옵니다.  생성할 "모델이름"을 입력하는 게 아니고, 생성할 "모델 뷰 이름"을 입력해야 맞습니다.
<img width="752" alt="스크린샷 2020-07-20 오전 7 54 25" src="https://user-images.githubusercontent.com/5126497/87887363-5c738580-ca5f-11ea-9306-0f0bd74e2643.png">

- 샘플데이터, 컬럼 설정 의 가이드 팁내용도 "데이터 모델을 선택해 주세요" 라는 게 내용이 맞지 않습니다.

-  **새모델**  역시 "연결 정보를 선택해 주세요" 가 맞지 않습니다.
<img width="747" alt="스크린샷 2020-07-20 오전 8 11 58" src="https://user-images.githubusercontent.com/5126497/87887525-f12ab300-ca60-11ea-947d-b2ac8f430321.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
"새 모델" 을 "새 모델 뷰"로, "모델 이름"을 "모델 뷰 이름"으로 수정하겠습니다.

그런데 모델 뷰 생성시 샘플 데이터/컬럼 설정은 모델을 선택해야만 나오므로 가이드 내용이 맞습니다. "참조 모델"로 개선할 수는 있겠습니다.
마찬가지로 모델 생성시에도 연결 정보 -> 대상 데이터 순으로 선택해야 데이터/컬럼이 나오므로 가이드 내용이 맞습니다.
