### ISSUE TITLE
[Studio] 콤포넌트 변수명 사용자정의 기능 필요

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2437]
## 기능 요청 ##

스튜디오에서 대시보드를 만들때 콤포넌트간 값을 주고받기 위한 변수명을 사용자가 정의할수 있어야 할것 같습니다.
그 이유는 다른 보고서에서 만든 콤포넌트를 복사해 쓸때 변수명이 바뀌어 귀찮은 작업들을 해야 하는것 같습니다.
아래 신운선 책임의 내용 참고 바랍니다.

현재 IRIS에서는 A라는 보고서에서 만들어 놓은 컴포넌트와 컴포넌트에 연결된 정보들을 복사하여 B라는 보고서에 붙여 사용할 수 없기 때문에 
갤러리로 공유할 보고서에서는 해당 보고서를 만든 사용자가 컴포넌트에서 사용하는 변수명을 자동으로 생성된 변수명이 아닌 해당 보고서에 특화된 변수명으로 바꿔 사용해야 할 것 같습니다.
그래야 다른 사용자가 해당 보고서에 사용한 컴포넌트를 똑같이 세팅하고 데이터 모델과 변수명, 검색어, 를 그대로 사용할 수 있기 때문입니다.
그렇지 않으면 갤러리로 공유된 보고서를 자신이 사용하려고 할때 시간이나 따로 분석을 해야 하는 번거로움이 생길 것 같습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
변수명을 사용자 정의 하는 것은 사이드 패널의 '속성' 탭에서 가능합니다.

![image](https://user-images.githubusercontent.com/3411842/87998508-1687f180-cb33-11ea-947a-0e2305003d76.png)

보고서를 복제할 때 변수명에 대한 이야기인 것 같은데, 정확한 요구사항은 논의를 해봐야 할 것 같습니다.

**Comment by sunghoon** [comment]
처리된 이슈로 보고 닫습니다.
