### ISSUE TITLE
Studio / 보고서 / hidden 콤포넌트의 트리거 설정시 입력값 저장 결과 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2438]
## 버그 설명 ##
트리거 설정으로 hidden 콤포넌트에 값을 생성하는 경우 입력 형식에 따라 값이 다르게 입력됨

아래 입력 예시와 같이 **2번**과 같이 입력한 경우 지정한 숫자값 이외의 값이 같이 저장됨
**1번**의** 예시와 같이 입력한 경우 숫자값만 저장됨

아래 1번, 2번과 같이 입력 하더라도 숫자값만 적용 되도록 처리 필요

**[입력예시 1]**
{% if input_1==combo_1 %}2{% elif input_1==2 %}3{% elif input_1==combo_2 %}0{% else %}9{% endif %}

**[입력예시 2]**
{% if input_1==1 %}
2
{% elif input_1==2 %}
3
{% else %}
1
{% endif %}

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/87902503-c2c6cb00-ca94-11ea-8095-cab84c79f27e.png)

**Comment by rhcpn** [comment]
해당 내용에 대해 잘 이해가 되지 않습니다.
저장 시 설정값이 잘못 저장된다는 뜻인가요? 아님 변수 바인딩 시 값이 2,3,1 외의 다른 값이 표시된다는 얘기 인가요?

**Comment by veldise** [comment]
```
{%   if input_1 == combo_1 %}
2
{% elif input_1 == 2 %}
3
{% elif input_1 == combo_2 %}
0
{% else %}
9
{% endif %}
```

```
{%   if input_1 == 1 %}
2
{% elif input_1 == 2 %}
3
{% else %}
1
{% endif %}
```

![image](https://user-images.githubusercontent.com/3411842/87998893-34a22180-cb34-11ea-99ee-54413f5666ad.png)

줄바꿈(`\n`)값도 같이 변수에 저장되는 것을 확인하였습니다. 수정하겠습니다.

**Comment by veldise** [comment]
nunjucks 의 `trimBlocks` 옵션으로 해결하겠습니다.
