### ISSUE TITLE
[Studio] 지도 - 정상 동작했던 지도 객체에서 angora 에러 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2439]
## 버그 설명 ##
 b-iris.mobigen.com  demo 계정

- 보고서 : EDU_map_서울시구별_소방서_마커_라벨

<img width="662" alt="스크린샷 2020-07-20 오후 3 57 47" src="https://user-images.githubusercontent.com/5126497/87908837-14298700-caa2-11ea-8408-8d08251c1cd5.png">

- 지난 주(7월17일) 에 생성하여 정상 동작 확인 후에 공유한 보고서였습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
현재 지도 객체에서 전부 에러 납니다.

**Comment by rhcpn** [comment]
Angora 쪽 배포 문제가 있었던것 같습니다. 
해당 이슈는 현재 해결 되었으므로 close 하겠습니다.
