### ISSUE TITLE
[Analyzer] 데이터모델에서 parquet 파일에서 만든 데이터모델을 조회하면 이벤트 시계열 그래프가 잘못 그려집니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2440]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

참조 데이터 모델 : EDU_TEST_parquet,  EDU_TEST2_parquet

- 2016/02/04 일 데이터도 있는데, 표시되지 않습니다. 그런데 막대의 툴팁의 데이터개수를 합하면 전체 데이터 1000 건이 나옵니다.
<img width="1130" alt="스크린샷 2020-07-21 오전 11 40 32" src="https://user-images.githubusercontent.com/5126497/88010803-b43de980-cb50-11ea-9087-3337105ad6a2.png">

<img width="1112" alt="스크린샷 2020-07-21 오후 12 51 16" src="https://user-images.githubusercontent.com/5126497/88010900-ee0ef000-cb50-11ea-8bd4-c21dbd150dc1.png">

<img width="1124" alt="스크린샷 2020-07-21 오후 12 51 22" src="https://user-images.githubusercontent.com/5126497/88010907-f2d3a400-cb50-11ea-8c5d-ae6a67dd63aa.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대지만, 시간 설정을 할 수 없습니다.한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
UI 쪽에서 summary 처리가 다소 잘못되어서 발생한 문제입니다.

@seungfwani 
단위를 1일로 했는데 시/분/초 단위가 데이터에 포함되는게 맞는건가요?

query:
```
model-timeline name = 'EDU_TEST_parquet' model_owner = demo unit = 1d
```

response data:
```json
  "results": [
    [
      "2016-02-03 09:01:00",
      606
    ],
    [
      "2016-02-04 00:00:52",
      394
    ]
  ],
```

**Comment by seungfwani** [comment]
데이터 그룹핑을 할 때 지정한 unit 의 단위 기준으로 그룹핑을 하여,
각 그룹 중 하나의 값으로 해당 그룹이 표현되어 처리되고 있습니다.

예제 데이터 )
| A                   |
| ------------------- |
| 2020-01-01 12:21:21 |
| 2020-01-01 02:01:21 |
| 2020-01-02 13:21:21 |
| 2020-01-03 12:21:00 |

unit = 1d
| A                   |
| ------------------- |
| 2020-01-01 12:21:21 |
| 2020-01-02 13:21:21 |
| 2020-01-03 12:21:00 |

**Comment by veldise** [comment]
해결되어 닫습니다.

![image](https://user-images.githubusercontent.com/3411842/88243584-ca23e980-cccb-11ea-8c0f-ea5cf3505b74.png)
