### ISSUE TITLE
[Analyzer] null 인 필드를 "검색에서 제외" 할 때 검색어가 "isnull" 로 잘못 들어갑니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2441]
## 버그 설명 ##

null 데이터를  "검색에서 제외" 시 **isnull**  로 입력되는데,  **is null** 이 맞는 것 같습니다
<img width="163" alt="스크린샷 2020-07-21 오후 1 21 02" src="https://user-images.githubusercontent.com/5126497/88012502-0e40ae00-cb55-11ea-815a-8fa243a11321.png">

`CS isnull`
<img width="1127" alt="스크린샷 2020-07-21 오후 1 10 24" src="https://user-images.githubusercontent.com/5126497/88012008-b8b7d180-cb53-11ea-9a3a-8aa0754402f6.png">

`CS is null`
<img width="1125" alt="스크린샷 2020-07-21 오후 1 10 49" src="https://user-images.githubusercontent.com/5126497/88012011-ba819500-cb53-11ea-9520-94287a688a34.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seungfwani 
기본적으로는 UI 버그입니다만, 검색 결과에 `<field_name> IS NULL`이 반영이 안되는 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/88015044-4fd45780-cb5b-11ea-8025-8b9cd527da33.png)

**Comment by seungfwani** [comment]
제가 검색하기로는 검색이 되는 것 같습니다.

1. yearid = 1899 일때 -> 결과 개수 348개
![Screen Shot 2020-07-21 at 2 11 28 PM](https://user-images.githubusercontent.com/46172579/88015423-15b78580-cb5c-11ea-9618-43603b0af21d.png)

2. yearid = 1899 and SF is null -> 결과 개수 346개
![Screen Shot 2020-07-21 at 2 10 51 PM](https://user-images.githubusercontent.com/46172579/88015390-05070f80-cb5c-11ea-8a98-b9b5fdac7f8e.png)

3. yearid = 1899 and SF is not null -> 결과 개수 2개
![Screen Shot 2020-07-21 at 2 10 33 PM](https://user-images.githubusercontent.com/46172579/88015392-07696980-cb5c-11ea-8a3d-47d456c42e6c.png)

**Comment by veldise** [comment]
@seungfwani 
확인하였습니다. 제가 착각한 것 같습니다.
