### ISSUE TITLE
[Analyzer] parquet 파일에서 생성한 데이터모델/ 모델 VIEW 를 analyzer 에서 조회후 시간필드를 sorting 하면 팝업이 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2442]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

데이터모델 : EDU_TEST_parquet - VIEW  , EDU_TEST_parquet

- 조회 결과 sheet 에서 registration_dttm 컬럼을 화살표를 눌러서 sorting 하면 Hi 라는 내용의 팝업이 뜹니다.
<img width="1332" alt="스크린샷 2020-07-21 오후 4 09 35" src="https://user-images.githubusercontent.com/5126497/88023788-9f6f4f00-cb6c-11ea-9ef7-20c5d62f551d.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
아래와 같이 Emojj 데이터로 인한 현상으로 보입니다.
```
    [
      "2016-02-03 22:34:32",
      83,
      "Carlos",
      "Washington",
      "cwashington2a@phpbb.com",
      "Male",
      "90.239.40.124",
      "67063904960748578",
      "United States",
      "11/4/1970",
      28853.61,
      "Developer I",
      "❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙"
    ],
```

**Comment by EricLeeMbg** [comment]
![image](https://user-images.githubusercontent.com/44352311/88134397-78258a00-cc1f-11ea-96bd-08fdfec40000.png)

pagenation에서도 마지막 페이지를 선택하면 'hi'라는 팝업이 출력됩니다.
