### ISSUE TITLE
[서초구청] Studio - 주기설정 객체 시작/종료 초기값 설정

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2449]
## 기능 요청 ##
주기설정 객체를 보고서에 추가하면 초기설정이 무조건 시작된 상태입니다.
주기 시작/종료 초기 설정이 있었으면 합니다.

## 원하는 솔루션 설명 ##
보고서 화면 초기에는 주기설정이 멈춰있고 사용자가 시작버튼 클릭 시 주기설정이 동작했으면 합니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 검토 후 빠르게 진행 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
말씀드리는게 늦었는데 금주(11/12) 패치 예정입니다.
