### ISSUE TITLE
긴급 개선 [Studio] map - 데이터모델 콤보박스 넓이가 작게 고정되어 있어서 데이터모델 이름 확인이 안 됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2450]
## 기능 요청 ##
b-iris.mobigen.com  demo 계정  크롬

<img width="208" alt="스크린샷 2020-07-23 오전 10 59 59" src="https://user-images.githubusercontent.com/5126497/88245946-edeb2d80-ccd3-11ea-8535-7658e2b362bf.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
`title` 속성을 일단 추가하고, 차후에 combo-box 크기를 키우는 방향을 논의해보겠습니다.

**Comment by veldise** [comment]
아래와 같이 개선선하기로 하였습니다. 패치 예정

![image](https://user-images.githubusercontent.com/3411842/88985991-adf7fc00-d30c-11ea-80e7-2658ae041411.png)
