### ISSUE TITLE
[Studio] 워드클라우드: 특정값일 때 동작하지 않습니다.

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2451]
## 버그 설명 ##
워드클라우드: 특정값일 때 동작하지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

보고서: 워드클라우드_test

1. 동작하지 않습니다.
* | where bidNtceKey = '2020044122300'
![image](https://user-images.githubusercontent.com/5077625/88265262-23117300-cd08-11ea-8908-7aa2b3a4bb76.png)

2. 정상 동작합니다.
* | where bidNtceKey = '2020042616200'
![image](https://user-images.githubusercontent.com/5077625/88265355-4cca9a00-cd08-11ea-9f94-810e8d4837f9.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
데이터 개수가 1000개 이상일 때 발생하는 문제로 확인되었습니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈 최종 상태 정보를 알려 주세요.

**Comment by veldise** [comment]
@sunghoon 
현재는 1000개 이상의 데이터로 시도시 highcharts 에러가 발생하고 이 내용이 에러로 출력됩니다.

![image](https://user-images.githubusercontent.com/3411842/94099990-4ae79900-fe67-11ea-8099-15eacbd76a89.png)
