### ISSUE TITLE
[Discovery/Analyzer] 모델 뷰를 생성했는데, Analyzer,Studio 에서 조회시 에러 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2452]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

모델 뷰 이름 : EDU_TILE_SEOUL_FIRE_STA_COOR -VIEW  
참조모델이름 : EDU_SEOUL_FIRE_STA_COOR

- 에러 없이 뷰를 생성했습니다.
<img width="744" alt="스크린샷 2020-07-24 오전 9 23 14" src="https://user-images.githubusercontent.com/5126497/88350857-5a773280-cd8f-11ea-8ec9-c9658e95b6c4.png">

- 모델 뷰를 Analyzer 에서 조회하니 에러납니다. 같은 에러가 Studio 에서도 납니다.
<img width="605" alt="스크린샷 2020-07-24 오전 9 18 53" src="https://user-images.githubusercontent.com/5126497/88350744-fe141300-cd8e-11ea-8461-e98b51d95b2d.png">

- 모델 뷰의 검색어구문을 Analyzer 에서 조회하면 잘 나옵니다.
<img width="1169" alt="스크린샷 2020-07-24 오전 9 25 16" src="https://user-images.githubusercontent.com/5126497/88350935-9a3e1a00-cd8f-11ea-9e47-dd4839dc9733.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
수정하여 배포하였습니다.
![Screen Shot 2020-07-24 at 12 59 00 PM](https://user-images.githubusercontent.com/46172579/88360451-b3a38e00-cdb0-11ea-9b94-0d1a3ed0873f.png)
