### ISSUE TITLE
[사용자계정-수정] : 전화번호에 '-' 이 포함되어도 정상적으로 저장이 됩니다

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2453]
## 버그 설명 ##

IRIS-관리-사용자계정-수정 에서 전화번호 입력폼이 '-' 을 제외한 숫자만 입력하라고 되어 있는데
010-123456789 같은 경우와 010-1234-abcd 그리고 0101123455a 같은 경우에는 에러 문구가 잘 뜨지만 
010-1234-5678 같은 경우에는 오류 메세지 없이 저장이 됩니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to '관리-사용자계정-수정'
2. type '010-1234-1234' to phone number
3. click `저장`
4. See error (저장이 되는게 에러)

## 예상한 행동 ##

에러가 뜨길 바라고 잘못된 형식의 전화번호 입력을 해주었는데 저장이 됩니다.

## 스크린샷 ##

![스크린샷 2020-07-24 오전 10 07 02](https://user-images.githubusercontent.com/57122180/88352630-6fef5b00-cd95-11ea-8a89-8c3fc294cc2b.png)

![스크린샷 2020-07-24 오전 10 07 25](https://user-images.githubusercontent.com/57122180/88352662-885f7580-cd95-11ea-9603-9a06b9b3bd40.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##

010-1234-1234 가 저장이 되는게 정상 동작이라면 에러문구를 '-를 포함한' 이라고 명시를 해주어야 할 것 같습니다.

**Comment by veldise** [comment]
@Minsoo-web 
이슈 assign은 해당 이슈를 처리하는 담당자를 대상으로 하고 있으니 assign은 하지 않으셔도 됩니다.

**Comment by veldise** [comment]
확인 결과 `-`도 입력 가능한게 맞으므로, 에러 메시지를 개선하도록 하겠습니다.
