### ISSUE TITLE
[Studio] map 있는 보고서를 복제한 후 편집-수정 화면을 열면  지도레이어에서 시각화옵션이 초기화되어 있습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2454]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 원래 보고서  **EDU_Tile_Seoul_Fire_map2** 에서 지도 - 투명도를 낮추었습니다.
<img width="552" alt="스크린샷 2020-07-24 오전 11 10 24" src="https://user-images.githubusercontent.com/5126497/88355167-7e8e4000-cd9e-11ea-81a3-693fe1f0d3e1.png">

- **복사한 보고서 EDU_Tile_Seoul_Fire_map3** 에서 편집화면의 지도투명도 = 1  로 초기화 되어 있습니다.
<img width="215" alt="스크린샷 2020-07-24 오전 11 14 07" src="https://user-images.githubusercontent.com/5126497/88355284-efcdf300-cd9e-11ea-9a56-4dff6ad5945d.png">

<img width="543" alt="스크린샷 2020-07-24 오전 11 14 12" src="https://user-images.githubusercontent.com/5126497/88355285-f197b680-cd9e-11ea-8060-f1361f7d2565.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
@seoryjj 재현이 되지 않는데 확인가능한 보고서를 알려주시면 감사하겠습니다.
