### ISSUE TITLE
[browser] 엔드 유저 계정으로 브라우저에서 '새폴더' 생성 안되는 문제 발생 합니다.

### ISSUE THREAD

**Issue by stgim** [mobigen/IRIS-BigData-Platform#2457]
## 버그 설명 ##
엔드 유저 계정으로 브라우저에서 [새폴더] 매뉴가 없어서 '새폴더' 생성 안되는 문제 발생 합니다.

##사전 조건##
1. IRIS E2E 테스트 주소 진입
2. ID : USER0 /  PW : !qwerty1으로 로그인

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. [브라우저] 선택
2. 화면 상단 왼쪽 [루트] 매뉴 선택

## 예상한 행동 ##
엔드 유저 계정으로 브라우저에서 [새폴더] 매뉴로 '새폴더'를 생성 할 수 있어야 합니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/67949847/88511670-32523280-d020-11ea-88f5-c7d5c4ff2e0f.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@stgim 
MinIO 에서 가장 최상위 폴더 위치는 버켓입니다. (ex) /user1 => user1 버켓)
일반 사용자는 버켓을 생성할 수 없습니다.

사용자 명에 해당하는 폴더가 아래와 같이 미리 생성되어 있어야 하는데, 해당 폴더가 없는 이유는 확인해봐야 합니다.

![image](https://user-images.githubusercontent.com/3411842/88600836-2b700200-d0aa-11ea-9f63-908aa8008630.png)

**Comment by Minsoo-web** [comment]
플랫폼 품질팀의 인턴 김민수입니다.

현재 발견된 이슈의 일반유저 (USER0)는 회원가입 승인의 과정을 거쳐서 생성이 된 유저가 아닌, 

> 관리 -> 사용자 계정 -> 사용자 계정 추가 

의 과정을 통해 생성된 유저입니다. 
이에 회원가입 승인을 통해 생성된 일반유저로 다시 테스트 해본 결과
사용자 명에 해당하는 폴더가 (일반유저 버켓) 생성이 됨을 확인하였고 새폴더 또한 생성이 가능함을 확인했습니다.

![스크린샷 2020-08-04 오전 10 46 05](https://user-images.githubusercontent.com/57122180/89243770-bf5c4380-d63f-11ea-815c-55e912839502.png)
![스크린샷 2020-08-04 오전 10 45 48](https://user-images.githubusercontent.com/57122180/89243775-c1be9d80-d63f-11ea-8b53-ab42d8dba4a9.png)

**Comment by veldise** [comment]
이슈 해결된 것으로 보고 닫습니다.
