### ISSUE TITLE
[Studio]ES와 DSMS 연결후 꺽은선형 차트의 X축을 날짜형식으로 표현시 오류

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#2458]
## 버그 설명 ##
Elasticsearch와 DSMS로 연결한 후, 
일별 카운트를 조회하는 Select 쿼리문을 작성하여 실행한 경우
세로막대형 차트는 X축이 날짜 형식으로 정상적으로 표시되지만
꺽은선형 차트는 기대했던 날짜 형식이 표시되지 않음

## 재현하는 방법 ##
1. 해당 보고서명: DSMS_TEST1

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/88513377-2156f080-d023-11ea-9f4a-22300aab7511.png)

**Comment by veldise** [comment]
@seungfwani 
날짜에 해당하는 컬럼 유형이 `keyword`로 반환되고 있습니다. 이는 논의된 적 없는 컬럼 유형입니다.
해당 컬럼 유형을 `TEXT`로 반환하거나, Elasticsearch 에서 반환될 수 있는 모든 컬럼 유형 및 IRIS 유형 매핑을 정리해주시기 바랍니다.

ex)
|원본 유형|IRIS 유형|
|:-:|:-:|
|keyword|TEXT|
|...|...|


@anhm

**Comment by anhm** [comment]
@jins00 
해당 쿼리를 다음과 같이 수정해 주시면 원하시는 결과를 얻으실수 있습니다.

```
select 
cast(left(cast(article_date as text),10) as text)
, count(*)
from iris_news_content
group by  left(cast(article_date as text),10)
```
해당 보고서에 쿼리를 수정해 두었습니다.

ES의 경우 문자열 함수를 사용하면 타입이 keyword 가 되는 현상이 확인 되었습니다.
해당 문제를 쿼리단으로 해결하기 위해서는 type cast를 진행해 주시면 됩니다.

타입 이슈는 DSMS에서 추후 패치 진행하도록 하겠습니다.

**Comment by sunghoon** [comment]
@anhm DSM 패치 관련 진행 상태 정보를 공유 해 주세요.

**Comment by anhm** [comment]
발생하는 타입을 아래와 같이 매핑 시켜 두었습니다.

만약 해당범위에 속하지 않는 타입은 `TEXT`로 반환됩니다.
해당 버전은 다음 패치에 반영 됩니다.

```
        'text': 'TEXT',
        'keyword': 'TEXT',
        'long': 'INTEGER',
        'integer': 'INTEGER',
        'short': "INTEGER",
        'byte': "INTEGER",
        'double': "REAL",
        'float': "REAL",
        'half_float': 'REAL',
        'scaled_float': 'REAL',
        'date': 'TEXT',
        'boolean': 'TEXT',
        'binary': 'TEXT',
```
