### ISSUE TITLE
[DSL] 명령어 top 의 결과가 sorting 이 되어 있지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2462]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 데이터 모델 : EDU_Beijing_air_2013_2017_18
- 검색어

`* year=2013 |  fillna PM2_5 | top 10 -PM2_5 `

- 결과 : PM2_5 가 정렬이 되어 있지 않습니다.

<img width="1022" alt="스크린샷 2020-07-29 오후 3 00 15" src="https://user-images.githubusercontent.com/5126497/88762483-4034be80-d1ac-11ea-961e-d4a67a226e9b.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
검색 화면에서는 `sort` 명령어를 사용하지 않은 경우 기본적으로 시간 컬럼 역순 정렬을 하게 되어 있습니다.

**Comment by veldise** [comment]
@seungfwani 
`sort`, `top` 외에 결과를 정렬하는 명령어가 무엇이 있나요?
