### ISSUE TITLE
[Discovery/Analyzer] 생성한 모델뷰를 analyzer, Studio 에서 조회하니 모델을 못찾는다는 에러창이 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2463]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 데이터 모델 뷰 생성함 ( 07/29 14 ~ 15시에 생성 )  :  **EDU_Beijing_air_2013_2017_18_주말_VIEW**
<img width="868" alt="스크린샷 2020-07-29 오후 3 57 00" src="https://user-images.githubusercontent.com/5126497/88767354-7d9d4a00-d1b4-11ea-9b9d-a9115c180f73.png">

- Analyzer, Studio 의  데이터모델 목록에 정상적으로 리스트되어 보여져서 선택 후 조회 -> 에러

<img width="943" alt="스크린샷 2020-07-29 오후 3 56 17" src="https://user-images.githubusercontent.com/5126497/88767766-0b793500-d1b5-11ea-87e6-e2c7c9d568d2.png">

<img width="589" alt="스크린샷 2020-07-29 오후 3 54 54" src="https://user-images.githubusercontent.com/5126497/88767795-159b3380-d1b5-11ea-9e13-6645350f4aca.png">

- 비슷한 시간에 생성한 EDU_Beijing_air_2013_2017_18 _주중_VIEW  는 정상 조회됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
내부적으로 모델 id 와 모델 명을 비교하는데에 있어 단순히 문자열 길이로만 판별하고 있었습니다.
해당 글자수는 36자로, 주말 모델명은 36자, 주중 모델명은 37자 이므로, 주말모델만 동작하지 않았던 것입니다.

해당 내용 수정 후 공유하겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 이슈 처리 최종 상태를 공유 해 주세요.

**Comment by seungfwani** [comment]
모델명 길이에 따른 버그는 수정되었습니다.

![Screen Shot 2020-09-25 at 5 19 35 PM](https://user-images.githubusercontent.com/46172579/94244075-4ac4c780-ff53-11ea-86f0-8e05d9c3f93c.png)
