### ISSUE TITLE
Studio / 캔버스에 이미지를 지정 할 수 있도록 해 주세요.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2464]
캔버스에 색상 설정 이외에 이미지 자체를 설정할 수 있도록 해 주세요.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 후 진행 해 주세요. 
#2090 에서도 언급되었습니다.

**Comment by rhcpn** [comment]
Studio 디자인 개선 시 반영하도록 하겠습니다.
