### ISSUE TITLE
[NMS+]앙고라 restAPI 사용법 문의

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2465]
## 버그 설명 ##

SKB 담당자들이 매뉴얼을 확인하여 직접 restAPI 를 아래와 같이 사용하였는데, 최종 결과가 아래와 같이 에러가 발생합니다.
 확인부탁드립니다.

@seungfwani 승환책임님이 담당이실듯하여, 출근하시면 확인부탁드립니다.

[root@test235 api_test]# curl -XPOST "http://222.239.252.120:6036/angora/auth" -H "Content-Type: application/json" -d '{"id" : "nmsplus","password" : "xxxxxxxx", "group_id" : "Default Group", "encrypted" : false}'
{
  "status": "OK",
  "token": "bm1zcGx1cy0wNTFiZWZjMS0wMDZkLTRlYzYtOTUxZS1jNmM0NjkyMjZiMWU="
}

[root@test235 api_test]# curl -XPOST "http://222.239.252.120:6036/angora/query/jobs" -H "Authorization: Angora bm1zcGx1cy0wNTFiZWZjMS0wMDZkLTRlYzYtOTUxZS1jNmM0NjkyMjZiMWU=" -H "Content-Type: application/json" -d '{"q" : "model name = SYS_LOG start_date = 20200728000000 end_date = 20200729000000 | stats count(*) by datetime", "size" : 500, "fetch_size" : 10}'

{
  "sid": "1595989213.8708,0.0.0.0:6036"
}
[root@test235 api_test]# curl -XGET "http://222.239.252.120:6036/angora/query/jobs/1595989213.8708,0.0.0.0:6036" \
>     -H "Authorization: Angora bm1zcGx1cy0wNTFiZWZjMS0wMDZkLTRlYzYtOTUxZS1jNmM0NjkyMjZiMWU="
{
  "message": "('The job has expired or is missing. Check Job History Server.',)",
  "type": "<class 'angora.exceptions.AngoraException'>"
}

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@jjinylee 

예상되는 바는 다음과 같습니다.
- 작업결과를 얻기 위해서는 `1번. DSL 쿼리를 POST요청 -> 2번. sid 반환 -> 3번. sid를 사용하여 GET 요청 -> 4번. 작업결과 반환` 의 순서로 동작합니다.
- 이전 버전에서 `2번 받고-> 3번 요청` 과정을 10초 내로 하지 않으면 작업이 끝나버리는 버그가 있었습니다.
- 최근 버전에서 `POST 요청` 시에 직접 작업의 시간을 지정하는 옵션을 추가였습니다.

따라서, 버전의 차이인지 확인이 필요 할 듯 합니다.

**Comment by jjinylee** [comment]
여기 권영길 팀장님은 id 가 없는지?
운영기술연구팀에 nms+ 앙고라 버전 확인부탁드립니다.

**Comment by seungfwani** [comment]
nms+ 버전 :  cb57875 (Apr 23, 2020)
이슈내용 수정 버전: 56acf2a (Jul 15, 2020)

**Comment by seungfwani** [comment]
해당이슈 해결이 되었나요.?

**Comment by jjinylee** [comment]
네.  8/3일 18시경  이부분만 같이 패치하고 알려주셨던게 이겁니다. 제가 클로즈 할게요
