### ISSUE TITLE
[NMS+]그리드 숫자정렬 안됨

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2466]
## 버그 설명 ##

그리드에서 아래와 같이 숫자컬럼에 정렬이 안됩니다.
dsms 로 쿼리로 정렬하여 결과를 뿌린후 그리드의 오름차순/내림차순 기능을 사용하면 숫자정렬이 적용되지않습니다.

![정렬](https://user-images.githubusercontent.com/5468183/88865757-acaecc80-d243-11ea-838a-15efd65585da.PNG)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@jjinylee 
문제가 발생하는 보고서나, DSMS 쿼리를 알려주시면 감사하겠습니다.

**Comment by jjinylee** [comment]
nms + ( https://222.239.252.120:8443 )

 보고서  :    MENU_성능>성능통계(그리드)>장비

입니다.

**Comment by veldise** [comment]
@jjinylee

해당 컬럼의 유형 정보가 `TEXT`라서 발생하는 문제입니다. 실수 유형으로 반환되도록 SQL을 조정하시면 될 것 같습니다.
잘 안되면 추가 답글을 달아주시기 바랍니다.

```js
        "fields": [
            { "type": "TEXT", "name": "SDATM"},
            { "type": "TEXT", "name": "\uc7a5\ube44\uba85"},
            { "type": "TEXT", "name": "IF_INDEX"},
            { "type": "TEXT", "name": "IF_DESCR"},
            { "type": "TEXT", "name": "IF_ALIAS"},
            { "type": "TEXT", "name": "\uace0\uac1d\uba85"},
            { "type": "TEXT", "name": "IN BPS (\ud3c9\uade0\uac12 MB)"},
            { "type": "TEXT", "name": "IN BPS DELTA(\ud3c9\uade0\uac12)"},
            { "type": "TEXT", "name": "IN \uc810\uc720\uc728(\ud3c9\uade0\uac12 %)"},
            { "type": "TEXT", "name": "IN \uc810\uc720\uc728 DELTA(\ud3c9\uade0\uac12)"},
            { "type": "TEXT", "name": "OUT BPS (\ud3c9\uade0\uac12 MB)"},
            { "type": "TEXT", "name": "OUT BPS DELTA(\ud3c9\uade0\uac12)"},
            { "type": "TEXT", "name": "OUT \uc810\uc720\uc728(\ud3c9\uade0\uac12 %)"},
            { "type": "TEXT", "name": "OUT \uc810\uc720\uc728 DELTA(\ud3c9\uade0\uac12)"},
            { "type": "TEXT", "name": "DEV_ID"}
        ]
```

**Comment by jjinylee** [comment]
@anhm 책임님

실수 유형으로 반환되도록 SQL을 조정하려면 컬럼+0.0 하면 되나요?
확인부탁드립니다.

**Comment by seoryjj** [comment]
제가 해보니 2가지 방법이 있습니다. 참고고하셔요

- sql 이용 ( sql 은 나중에 없어질 검색어입니다.)

`* | sql "select year + 0.0 as NEW_YEAR from angora" ` 

<img width="952" alt="스크린샷 2020-07-31 오전 8 22 17" src="https://user-images.githubusercontent.com/5126497/88983840-06c49600-d307-11ea-8b0d-0b6cdd81d00a.png">

- calculate  

`* year = 2013 |  calculate year + 0.0 as NEW_YEAR`

<img width="1121" alt="스크린샷 2020-07-31 오전 8 23 29" src="https://user-images.githubusercontent.com/5126497/88983968-54410300-d307-11ea-810e-8888c4212d76.png">

**Comment by veldise** [comment]
답변이 된 것으로 보고 닫습니다.
