### ISSUE TITLE
[관리-메뉴관리 & 개인설정 -> 대시보드 버그] 메뉴 생성/삭제 후 바로 적용이 안 됩니다.

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2468]
## 버그 설명 ##

0. 메뉴를 생성하고 대시보드를 가보면 생성이 적용이 안 되어 있습니다. 
1. 메뉴를 삭제하고 대시보드를 가보면 삭제가 적용이 안 되어 있습니다. 

> 둘 다 새로고침을 하면 적용됩니다.

2. 개인 설정 페이지 진입 후 뒤로가기를 누르면 라우터가 적용이 안 된상태로 화면만 이전 화면으로 가집니다.
2.1 그 상태에서 새로고침을 하면 다시 개인 설정 페이지로 진입하게 되며 그 화면에서 다시 뒤로 가면 흰 화면이 뜹니다. 

> 2번 상태에서 뒤로가기를 한 번 더 적용하면 정상적인 대시보드 화면으로 갑니다.

2.2 그 상태에서 뒤로가기를 한 번 더 누르면 정상적인 대시보드로 가며, 다시 앞으로 가기를 누르면 라우터만 변경된 대시보드 화면이 뜹니다.

## 재현하는 방법 ##

버그 설명에 작성했습니다.

## 예상한 행동 ##

개인설정 뒤로가기 -> / 대시보드 
메뉴 생성/삭제 후 대시보드 -> 적용된 화면

을 예상했습니다. 

### 메뉴를 삭제해도 안 없어진 모습 && 개인 설정 -> 뒤로가기 라우터 변경이 안 된 모습

![스크린샷 2020-07-30 오전 9 54 43](https://user-images.githubusercontent.com/57122180/88868309-c869a100-d24a-11ea-951c-4171ddb603be.png)

### 이 경우 새로고침을 하면 다시 개인 설정 페이지로 진입하게 됩니다. 

> 그 상태에서 (새로고침을 해서 다시 개인 설정 페이지로 진입한 상황에서) 뒤로가기를 한 번 더 누른 상황 

![스크린샷 2020-07-30 오전 9 57 46](https://user-images.githubusercontent.com/57122180/88868434-25655700-d24b-11ea-94df-7d2ce8599b46.png)

**Comment by sunghoon** [comment]
@lyj 해당 이슈 처리와 관련된 최종 상태 정보를 공유 바랍니다.

**Comment by lyj** [comment]
관리자의 특수한  기능으로, 메뉴 변경 후 바로 적용되지 않습니다. 메뉴 적용시 새로고침이 필요합니다.

**Comment by sunghoon** [comment]
@lyj 메뉴 정보가 Update 될때 초기 로딩시 한번 Read되는 메뉴 정보를 재로딩 할 수 있도록 개선을 요청드립니다.

**Comment by lyj** [comment]
다음 이슈 회의시간에, 해당 기능 다시 리뷰하여 처리하도록 하겠습니다.

**Comment by lyj** [comment]
해당 이슈는 11월 중순 정도에 처리 예정입니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 해당 이슈 어떻게 조치 되었는지요?

**Comment by lyj** [comment]
@sunghoon 기능은 처리되었으나, IWP 배포일이 아직 정해지지 않았습니다.
테스트 후 다음 배포시 적용될 예정입니다.

**Comment by lyj** [comment]
2021-01-14 패치되었습니다.
