### ISSUE TITLE
[서초구청] Studio: Map-마커 유형에 투명화 및 강조 기능

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2469]
## 기능 요청 ##
1. 마커에 투명화 옵션 기능 추가
2. 선택된 마커 강조 기능
  - 현재는 어떤 마커가 선택되었는지 알 수가 없음.
3. 이미지 마커 기능 추가 및 임계치에 따른 마커 이미지 변경 기능

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
