### ISSUE TITLE
[서초구청] Studio: 차트 누적 데이터 초기화 기능

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2470]
## 기능 요청 ##
차트 또는 테이블에 누적 데이터 기능을 활성화 후 초기화하는 기능이 필요합니다.

## 원하는 솔루션 설명 ##
예를 들어 주기설정으로 데이터 객체가 이벤트를 받으면 DB조회를 통해 차트 또는 테이블에 데이터가 누적이 됩니다.

이때 표현하는 데이터의 주체변경 시(A장비에서 B장비로 변경) 누적 데이터를 초기화하는 기능이 필요합니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
