### ISSUE TITLE
Studio: 데이터 객체를 Ctrl + C, V 할 수 없음

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2472]
## 버그 설명 ##
Studio: 데이터 객체를 Ctrl + C, V 할 수 없음

**Comment by swish1995** [comment]
드래그로 선택시에는 되지만 객체를 클릭으로 선택한 경우에 안되는것으로 확인되었습니다.

예외: 객체를 처음 추가한 상테에서는 복사가 됨
