### ISSUE TITLE
Studio / 히트맵이 존재하는 보고서 복제 사용시 히트맵 정보가 기존과 같지 않음.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2473]
- 기존 보고서의 히트맵 정보
![스크린샷 2020-07-31 오전 9 59 50](https://user-images.githubusercontent.com/512653/88988766-c1a76080-d314-11ea-91a5-c33933c301b0.png)

- 복제된 보고서의 히트맵 정보
![스크린샷 2020-07-31 오전 9 59 53](https://user-images.githubusercontent.com/512653/88988773-cb30c880-d314-11ea-88b4-4b874a21a5db.png)

- 복제 원본 보고서는 '일일업무 기록확인' 입니다.

**Comment by veldise** [comment]
해당 보고서를 복제한 뒤 json 기준으로 데이터를 비교해본 결과 차이점을 찾을 수 없었습니다.
복제가 아니라 시각화 옵션 내용이 저장되지 않는 문제인 것 같습니다.

**Comment by sunghoon** [comment]
네.  맞습니다. 시각화 옵션. 임계치 정보가 있었는데. 복제된 보고서에는 임계치 정보가 없었습니다.
