### ISSUE TITLE
[KOTRA]루트계정에서 갑자기 연결이 끊어짐

### ISSUE THREAD

**Issue by krjwpark** [mobigen/IRIS-BigData-Platform#2476]
## 버그 설명 ##
KOTRA 분석서버(192.168.70.226)에 루트 계정으로 로그인하여 주피터노트북으로 작업하던 중 갑자기 연결이 끊어짐.

## 재현하는 방법 ##
작업과정 중 별다른 전조증상 없이 연결이 끊어짐
## 예상한 행동 ##
이상없이 작업을 계속

## 스크린샷 ##

![01_20200803_085921](https://user-images.githubusercontent.com/37128240/89138310-2ca3a200-d576-11ea-8bc4-00eb701f35c6.jpg)
![02_20200803_090030](https://user-images.githubusercontent.com/37128240/89138328-388f6400-d576-11ea-8da8-41787cd5627c.jpg)
![03_20200803_090315](https://user-images.githubusercontent.com/37128240/89138346-4513bc80-d576-11ea-9461-63e062bee4c0.jpg)
![04_20200803_090338](https://user-images.githubusercontent.com/37128240/89138357-4e048e00-d576-11ea-91de-aaba7565de9b.jpg)

![05_20200803_090356](https://user-images.githubusercontent.com/37128240/89138487-b8b5c980-d576-11ea-835a-3d327f2467b5.jpg)
해당 창을 닫고 다시 로그인하면 그 사이 변경내용은 저장되지 않은 상태로 연결됨.
## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
발생시각: 2020-07-31 오후 2시-6시 사이 2회 발생함(사진 파일은 2번째 발생을 캡처한 것임).

**Comment by sunghoon** [comment]
같은 상황이 발생하면 새 이슈로 다시 등록 부탁드립니다.
