### ISSUE TITLE
[browser & 일반 유저 생성] : 사용자 계정 추가로 생성된 유저와 회원가입 승인을 통해 생성된 유저에 차이가 있습니다.

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2479]
## 버그 설명 ##

사용자 계정 추가로 생성된 유저와 회원가입 승인을 통해 생성된 유저에 차이가 있습니다.
회원가입 승인을 통해 생성된 유저는 파일 브라우저에서 해당 유저의 아이디의 버켓이 생성이 되는데,

> 관리 -> 사용자계정 -> 사용자 계정 추가

을 통해 생성된 일반 유저는 파일 브라우저에서 해당 유저의 아이디의 버켓이 생성되지 않습니다.

b-iris 에서는 문제가 없었지만 
`http://192.168.102.142/` k8s 서버에서만 발견된 이슈입니다. 

Mac Catalina 10.15.3
chrome v84.0

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. http://192.168.102.142:PORT 로 진입
2. root 로 로그인
3. 사용자 계정 추가
4. 추가된 일반 유저로 로그인
5. 파일 브라우저 
6. see ERROR 

1-1. http://192.168.102.142:PORT 로 진입
2-1. 회원가입 신청
3-1. root로 로그인
4-1. 회원가입 승인
5-1. 추가된 일반 유저로 로그인
6-1. 파일 브라우저
7-1. 정상작동 확인

## 예상한 행동 ##

사용자 계정 추가로 생성된 유저로도 파일브라우저 접근이 가능해야 할 것 같았습니다. 

### root로 로그인한 화면

![스크린샷 2020-08-04 오전 10 46 05](https://user-images.githubusercontent.com/57122180/89244269-072f9a80-d641-11ea-806c-7358ab52f275.png)

### 회원가입 승인을 통해 생성된 일반 유저의 파일 브라우저 화면

![스크린샷 2020-08-04 오전 10 45 48](https://user-images.githubusercontent.com/57122180/89244279-0a2a8b00-d641-11ea-8b07-51493ec94d1e.png)

### 사용자 계정 추가를 통해 생성된 일반 유저의  파일 브라우저 화면

![스크린샷 2020-08-04 오전 10 38 43](https://user-images.githubusercontent.com/57122180/89244315-21697880-d641-11ea-9eaa-8fe687be37c0.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##

open #2457 
과 관련된 이슈입니다.

**Comment by Minsoo-web** [comment]
k8s 서버에서 금일(08/06) 다시 확인 해본 결과
회원가입 승인을 통해 생성된 유저도 버켓이 생성이 안 되는 것을 확인했습니다.

**Comment by veldise** [comment]
@Minsoo-web 
계정명이 대문자라서 안되는 것으로 확인되었습니다. 아래 이슈를 참고하시기 바랍니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2074

**Comment by Minsoo-web** [comment]
확인했습니다.
파일 브라우저에서 실행되는 일반 유저의 아이디를 소문자로 변경하는 것으로 조치하겠습니다.
