### ISSUE TITLE
[Studio] 체크박스/라디오버튼 에서 사용자 정의 선택시 "데이터사용자 정의" 부분이 너무 작게 표시되어 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2482]
## 버그 설명 ##
b-iris.mobigen.com demo계정 크롬브라우저

- 체크박스/라디오 버튼 - 사용자정의

<img width="206" alt="스크린샷 2020-08-05 오후 1 21 32" src="https://user-images.githubusercontent.com/5126497/89371663-ee95b200-d71e-11ea-9c92-51c0c656ee04.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
브라우저의 확대/축소 기능을 사용할 때 발생하는 문제로 확인되어 닫습니다.
