### ISSUE TITLE
[studio] 라벨 컴포넌트나 텍스트 입력 컴포넌트_단일값과 같이 천단위로 콤마(,) 처리 기능필요

### ISSUE THREAD

**Issue by eumminsun** [mobigen/IRIS-BigData-Platform#2484]
## 기능 요청 ##
라벨 컴포넌트나 텍스트 입력 컴포넌트에 표시될 데이터기 숫자인 경우 차트 컴포넌트의 단일값과 같이 천단위로 콤마(,)를 처리 할 수 있는 기능 필요

[관련링크]
(http://b-iris.mobigen.com/studio/exported/ba4c9a8a9b4b4873b3b436b30d1f574020ea21a4fbea4df5a78937143198a403)

**Comment by sunghoon** [comment]
@veldise 어떤 일정 계획으로 진행 중인지 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon

**Comment by veldise** [comment]
@sunghoon 
현재 11/19 패치를 목표로 진행중입니다.
