### ISSUE TITLE
[Studio] 차트 - 꺽은선형, 막대그래프, 다중축_ 축 글자 위치 변경 기능

### ISSUE THREAD

**Issue by eumminsun** [mobigen/IRIS-BigData-Platform#2487]
## 기능 요청 ##
차트 - 꺽은선형, 막대그래프, 다중축에서 Y 축, X 축 제목을 축의 끝에 위치 하며 글자의 위치를 변경 할 수 있도록 기능 수정 필요

[관련링크]
(http://b-iris.mobigen.com/studio/exported/ba4c9a8a9b4b4873b3b436b30d1f574020ea21a4fbea4df5a78937143198a403)

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/90841602-ffd5f400-e397-11ea-94b8-83a88a2ac949.png)

글꼴 정렬 기능을 이용하면 해결되는 이슈로 생각됩니다.
