### ISSUE TITLE
[Studio] 보고서 실행시 이미지를 불러오는 시간이 너무 많이 소요됨

### ISSUE THREAD

**Issue by eumminsun** [mobigen/IRIS-BigData-Platform#2491]
## 버그 설명 ##
보고서 실행시 이미지를 불러오는 시간이 너무 많이 소요됨

[관련링크]
(http://b-iris.mobigen.com/studio/exported/ba4c9a8a9b4b4873b3b436b30d1f574020ea21a4fbea4df5a78937143198a403)

**Comment by sunghoon** [comment]
@rhcpn @eumminsun #1612 과 같은 형식으로 처리 될 수 있도록 진행 바랍니다.
