### ISSUE TITLE
[Studio] 다중축에서 여러개의 Y 축의 값이 동일한 데이터를 사용하는 경우 축의 값이 동일하게 나타날 수 있도록 수정 필요

### ISSUE THREAD

**Issue by eumminsun** [mobigen/IRIS-BigData-Platform#2493]
## 버그 설명 ##
차트 - 다중축에서 여러개의 Y 축의 값이 동일한 데이터를 사용하는 경우 축의 값이 동일하게 나타날 수 있도록 수정 필요

[관련링크]
(http://b-iris.mobigen.com/studio/exported/ba4c9a8a9b4b4873b3b436b30d1f574020ea21a4fbea4df5a78937143198a403)

**Comment by sunghoon** [comment]
@eumminsun 검토 후 진행 해 주세요.
