### ISSUE TITLE
Discovery / where 문법 오류

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2495]
조건문에 대한 문법 처리 오류를 요청합니다. 일반적인 경우 아래 두개가 모두 동작하여야 하는데.
동작하는 경우와 그렇지 않은 경우가 있으며, 보통 사람들이 두개를 구분 하지 못하거나. 문제를 해결하지 못하므로
문법 개선을 통한 처리가 필요해 보입니다. 

실패 케이스 : where (품명 like '%빅데이터%' or 품명 like '%인공지능%' or 품명 like '%AI%') and 배정예산금액 > 500000000
성공 케이스 : where ( 품명 like '%빅데이터%' or 품명 like '%인공지능%' or 품명 like '%AI%') and 배정예산금액 > 500000000

**Comment by seungfwani** [comment]
수정되었습니다.

1.
![Screen Shot 2020-08-27 at 4 33 25 PM](https://user-images.githubusercontent.com/46172579/91411342-23f77080-e883-11ea-8c7b-4c3d13568af2.png)


2. 
![Screen Shot 2020-08-27 at 4 32 36 PM](https://user-images.githubusercontent.com/46172579/91411332-2063e980-e883-11ea-8e01-427f737c974c.png)
