### ISSUE TITLE
[Discovery] 명령어 추가 요청 :  Studio map 의  Mesh 유형에서 사용되는 jpMesh 코드 생성 명령어

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2496]
## 기능 요청 ##

Studio 지도 객체 유형 중  Mesh 유형은 위, 경도 좌표를 JpMesh 코드로 변환한 코드값(text 형) 이 있어야 합니다.
일반적인 GIS에서 사용되는 것이 아니라서 간편하게 mesh code생성하는 명령어가 있으면 좋겠습니다.

http://docs.iris.tools/manual/IRIS-Tutorial/IRIS_Studio/02_map_exam/map_mesh.html#

를 보시면  mesh code 생성 예제와 pyjpmesh 라이브러리 링크가 있습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@seungfwani 해당 요구에 대응하는 명령어를 만들어 주세요.
