### ISSUE TITLE
기능요청 [Discovery] 시작시간,끝시간,단위시간 을 입력받아 시간 데이터를 생성하고 데이터모델과 JOIN 이 가능한 객체로 생성하

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2497]
## 기능 요청 ##

집계 데이터에서 빠진 시간대 집계가 0 으로 채워져서 나오도록 하려면  필요한 기능입니다.
아래처럼 09:00:00 ~ 10:00:00 동안 1분 단위로 집계한 통계인데, 데이터가 있는 시간만 나오고, 나머지 시간대는 안 나옵니다.
하지만 이상탐지나 anomalies , 실시간 감시 같은 모니터링을 위해 집계할 때는 시작시간 ~ 끝시간 동안 안나온 시간대를 0 으로 채워야 
정확한 결과가 나옵니다.

<img width="644" alt="스크린샷 2020-08-06 오전 10 48 11" src="https://user-images.githubusercontent.com/5126497/89481264-58bb5f00-d7d2-11ea-90d7-f82012d13ca1.png">

- 한 보고서 안에서  데이터의 시작시간,끝시간,단위시간(집계단위 예: 10s, 1M, 10M, 1h,,,) 를  변수로 받아서 
  시간만 있는 객체를 만들어서 데이터객체의 검색어에서 JOIN 으로 사용하여 빠진 시간대를 0 으로 채우는 기능이 필요합니다

- 예로 데이터모델 SYSLOG 최근 60분동안 1분단위 집계

`* |  stats   count(*) as CNT by  date_group(DATETIME, "1M")  ` 

- 빠진 시간대를 0 으로 채우는 검색어 예

`* |  stats   count(*) as CNT by  date_group(DATETIME, "1M" )  |  JOIN  outer 단위시간객체  DATETIME = 단위시간객체.DATETIME |  fillna  CNT 0 `

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@seungfwani 해당 요구사항에 대응하기 위한 명령어 대응해 주시기 바랍니다.

**Comment by seungfwani** [comment]
아래 이슈와 같은 것으로 보이며 함께 처리하겠습니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2497

**Comment by sunghoon** [comment]
위에 이슈 번호가 잘 못 되어 다시 공유합니다.
아래 이슈와 같이 처리 해 주세요.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2426

**Comment by seungfwani** [comment]
@seoryjj @anhm 
빌드 테스트 완료 하였으며,
(20.10.16) 배포요청 하였습니다.
