### ISSUE TITLE
k8s 이전 요청사항

### ISSUE THREAD

**Issue by jblim0125** [mobigen/IRIS-BigData-Platform#2499]
## Mount  

- /etc/hosts :  
쿠버네티스 기능을 사용해 컨테이너 /etc/hosts에 추가 가능합니다.  
  동작에 필요한 호스트 정보 정리가 필요합니다.  

- /etc/passwd :  

- /etc/localtime :  
  컨테이너 실행 시 TZ 환경 변수를 사용해 시간을 설정하도록 하겠습니다.  

## Config, ENV
컨테이너 실행에 필요한 환경 변수와 설정 파일이 필요합니다.  
 
- 환경 변수 :    
        Key=value  

- 환경 설정 파일 :  
        yaml or json 형식으로 정리된 파일  
        환경 설정 파일이 위치해야 하는 컨테이너 내 경로  

## 외부 저장소  
컨테이너 종료에도 유지 되어야 하는 파일(경로)을 위한 컨테이너 내 경로 정보가 필요합니다.  

- 예 : 
데이터 저장 : /app/data
사용자 데이터 저장 : /app/user_data
    
## Resource  
컨테이너마다 필요로 하는 CPU, MEM에 대한 자료가 필요합니다.  

## Security  
Dockerfile 내 프로세스 실행(ENTRYPOINT, CMD) 전 USER를 사용해 루트가 아닌 유저로 실행이 필요합니다.
Dockerfile 예 :
```
FROM DOCKER_BASE_IMAGE
ARG USER=docker
ARG UID=1000
ARG GID=1000
ARG PW=docker

# 선택사항 : Using unencrypted password/ specifying password
RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | chpasswd

USER ${UID}:${GID}
ENTRYPOINT ["/bin/app"]
CMD ["--help"]
```

특수한 어플리케이션의 경우 일반 유저 권한 밖의 권한이 필요로 할 수 있습니다. 
다음은 리눅스 기능 별 권한에 대한 정보와 설정 방법입니다. 필요한 경우 참고해주세요.
Linux 권한 정보 : https://man7.org/linux/man-pages/man7/capabilities.7.html
K8S 설정 방법 : https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
Docker 설정 방법 : https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

## Status   
쿠버네티스 기능으로, 무 중단 업데이트, 로드 밸런싱을 위해 필요한 기능입니다.
기능 설명: HTTP Get 요청을 수행, 응답 코드가 200 이상 400 미만이면 성공으로 인지합니다.

- 예 :
Path: http://localhost:8080/status
최초 시작 시간(초): 컨테이너 시작 후 설정한 시간만큼 대기하고 상태 검사를 시작
타임아웃(초) : 설정한 시간동안 응답이 없는 경우 실패로 판단
        
## Log  
컨테이너 내부에서 로그를 파일 형태가 아닌 stdout, stderr로 출력하도록 변경 요청 드립니다.

- 이유 : 
운영 입장에서 로그를 보기 위해 컨테이너 내부 or 로그 저장소소로 이동하여 
확인하는 것에서 플랫폼 기능(docker logs, kubectl logs)을 사용한 로그 확인,
도커 데몬 설정 혹은 로그 수집기를 이용한 로그 수집 수월,

## MariaDB
추가 논의 필요

**Comment by sunghoon** [comment]
@jblim0125 본 이슈와 관련된 최종 상태 정보를 공유 해 주세요.

**Comment by jblim0125** [comment]
최영철 책임
brick, cluster, dashboard, data-import
data-trans-service, db-browser, hdfs-browser
memcached, meta, sherman, studio

추석 전/후로 k8s migration 된 내용과 이미지를 전달 받기로 하였습니다.

서승환 책임  
angora
    migration 진행된 내용 없습니다.

플랫폼팀    
dsms, jhms, service-discovery, iris-entry
    migration, 정책과 관련 정리된 부분이 없습니다.

김영주 책임  
iris-web-platform
    진행부분에 대해서 공유받지 못하였습니다.  

임준범 책임  
mariadb, minio, postgres, osm
    최종적으로는 기본 이미지에 사용자가 지정한 버전으로 실행과 
    환경(접속 정보, 플러그인(지도) 설치)만을 제공하도록 변경이 필요합니다.  
    현재까지는 script를 컨테이너에 마운트하여 이미지 최초 구동 시 
    디비 + 데이터가 생성, 추가되도록 되어 있습니다.
    
고승범 책임  
play-ground
    대부분의 내용이 정리된 상태이나 외부 저장소와 관련된 부분의 정리가 필요합니다.  

임준범 책임
spark-operator
spark-standalone
    migration 필요 없습니다.

**Comment by veldise** [comment]
@jblim0125 
data-trans-service 는 안형민 책임님이나 서승환 책임에게 요청하셔야 합니다.

**Comment by sunghoon** [comment]
본 이슈는 그룹 내부의 개발과 관련된 이슈라 닫고 별도로 이슈 관리 하겠습니다.
