### ISSUE TITLE
[Discovery] 데이터모델 생성 시 "컬럼설정" 의 "유형" 을 일괄 변경하는 기능 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2501]
## 기능 요청 ##
 
-  데이터모델 생성 창에서 "컬럼설정" 의 "유형" 이 default 로 TEXT 입니다.
- 컬럼의 수가 많고, 많은 수의 컬럼을  TEXT  에서 다른 유형으로 변경 할 필요가 있습니다. 선택한 컬럼들의 유형을 한꺼번에 변경하는 기능이 필요합니다.
<img width="789" alt="스크린샷 2020-08-07 오전 10 22 49" src="https://user-images.githubusercontent.com/5126497/89598540-0775a300-d898-11ea-8226-8a0a5a602ded.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
우선은 닫아 두겠습니다. 
동일 상황이 발생하면 새 이슈로 관리하겠습니다.
