### ISSUE TITLE
[사용자 계정 관리] 회원가입, 유저 정보 수정에서는 '-'이 포함된 휴대폰 번호 입력이 제한이 됩니다.

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2502]
## 버그 설명 ##

플랫폼 품질팀 인턴 김민수입니다.

이전 이슈 closed #2453 에서 발견된 에러는 
관리자가 사용자의 핸드폰 번호를 변경하는 상황이였지만

일반 유저가 직접 핸드폰 번호를 설정하는 
회원가입, 유저 정보 수정 페이지에서는 010-1234-5678 의 형태의 입력이 안 됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

### 회원가입 신청 

1. 창열기 (not login)
2. 회원가입 클릭
3. 필수 정보 채운 뒤 휴대폰 번호 `010-1234-1234` 형태로 입력

### 유저 정보 수정

1. 일반 유저로 로그인
2. 개인 설정 페이지 진입 `click css=group-menu-user__account-setting-button`
3. 유저 정보 수정 탭 클릭
4. 휴대폰 번호 변경 `010-1234-1234`
5. See error

## 예상한 행동 ##

이전 이슈에 대한 응답과 이번 08/06 패치 내용을 보면
010-1234-1234 의 형태도 입력이 가능한 것이 맞는 것처럼 인지가 되었는데
회원가입 및 유저 정보 수정 페이지에서는 입력이 불가능해서 예상한 행동과 달랐습니다. 

### 회원가입 에러

> k8s 테스트 서버

![스크린샷 2020-08-07 오전 11 27 35](https://user-images.githubusercontent.com/57122180/89602133-07c66c00-d8a1-11ea-914f-11f0812f568f.png)

> b-iris

![스크린샷 2020-08-07 오전 11 08 07](https://user-images.githubusercontent.com/57122180/89601616-f6309480-d89f-11ea-9b82-312da30f12ad.png)

### 유저 정보 수정 페이지 에러

> k8s 테스트 서버

![스크린샷 2020-08-07 오전 11 23 17](https://user-images.githubusercontent.com/57122180/89601837-6b9c6500-d8a0-11ea-9662-02b420e600c4.png)

> b-iris

![스크린샷 2020-08-07 오전 11 22 34](https://user-images.githubusercontent.com/57122180/89601840-6dfebf00-d8a0-11ea-95c2-57e634d1b3bb.png)

### 관련 이슈 및 패치 

closed #2453 
08-06 release 계정관리 패치 사항

**Comment by veldise** [comment]
@Minsoo-web @lyj 
제가 변경사항을 미처 전달을 못해서 발생한 문제입니다.
