### ISSUE TITLE
개선 [데이터모델] 생성 시 분리기호 란에 스페이스나 tab 은 정규표현식으로 표시해주세요. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2503]
## 기능 요청 ##
b-iris.mobigen.com 

- tsv 형식의 파일에서 데이터 모델 생성
- 파일 유형에 csv 로 되어 있어, 1차 혼란이 옵니다.
- 분리기호에 보이지 않는 tab 이 있어서 분리되어 샘플이 나오지만,  사용자는 알수 없습니다. 그래서  명확하게 하기 위해 분리기호란에  **\t**  를 쓰면 에러가 납니다.
    - 왜냐하면 이미 보이지 않는 tab 이 있어서 탭2개 분리기호가 되어 버리기 때문입니다.
- 특수하게 tab을 2개 이상으로 분리기호를 사용하거나, 스페이스를 분리기호로 사용하는 경우도 있습니다.
- **제안**  
    - text 로 명시되는 거 외에 스페이스, 탭 등은 정규표현식으로 사용합니다. \s, \s\s, \t, \t{2}
<img width="797" alt="스크린샷 2020-08-07 오후 2 02 06" src="https://user-images.githubusercontent.com/5126497/89611382-09e7f500-d8b8-11ea-8667-54735e4cb045.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 기능 구현과 관련된 컴토 의견 주세요.

**Comment by veldise** [comment]
@sunghoon 
구두로 논의한 결과 분리기호를 탭, 공백, 직접 입력 3가지를 선택할 수 있도록 하기로 했습니다. 기획만 진행중인 것으로 알고 있습니다.

**Comment by sunghoon** [comment]
@eumminsun 기획 완료되면 관련 정보 공유 바랍니다.

**Comment by eumminsun** [comment]
@sunghoon @veldise @onlyeon 
기획서 공유 드립니다. 해당 기획은 9월 25일 작업완료 되었으며, 10월 6일 퍼블리싱 작업이 완료 되었습니다. 

[기획서](https://docs.google.com/presentation/d/1Jkw7QG7usjFqdz9XaCQ1ikkH7dqOBgvIR6W-IC4xsyY/edit?usp=sharing)

**Comment by sunghoon** [comment]
@veldise 개발/배포 예정일을 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
현재 일정상으로는 11/19 패치 예정입니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈 어떻게 조치 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
11/19 패치로 아래와 같이 UI가 변경되었습니다.

![image](https://user-images.githubusercontent.com/3411842/100301745-27161000-2fdc-11eb-92da-3f55ec8f72a0.png)
