### ISSUE TITLE
개선[데이터모델] 생성 시 angora 에러 구문을 명확하게 제시해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2504]
## 기능 요청 ##
b-iris.mobigen.com

- 데이터 모델 생성은 에러없이 생성 완료
- 데이터 모델 뷰 생성 시 에러가 발생하는데, 원인을 알 수 가 없는 에러 구문으로 조치를 할 수 없습니다.

<img width="797" alt="스크린샷 2020-08-07 오후 1 48 35" src="https://user-images.githubusercontent.com/5126497/89611845-29cbe880-d8b9-11ea-8839-8ab144f80c67.png">

- angora   의  로그 확인(서승환책임)을 한 후에야  컬럼명에 점(.) 이 있어서 발생했다는 걸 알았습니다.
- angora 로그에는 문제되는 컬럼이름이 바로 나왔습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@seungfwani 확인 후 조치해 주세요.

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 공유 바랍니다.
