### ISSUE TITLE
Discovery, Studio, Analyzer의 리스트 만든 날짜 출력 부분 추가 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2506]
## 기능 요청 ##
Discovery, Studio, Analyzer의 리스트에 만든 날짜도 출력

## 원하는 솔루션 설명 ##
Discovery, Studio, Analyzer에서 파일, 데이터모델, 보고서에 대한 수정된 날짜만 나와 생성된 날짜로 찾고 싶을 때 찾거나 정렬할 수가 없어서 해당 기능이 필요합니다

**Comment by sunghoon** [comment]
@eumminsun 컴토 후 진행해 주세요.
