### ISSUE TITLE
데이터 업로드 또는 데이터 모델 생성시 기존에 열려있던 브라우저를 재실행해야 적용이됨

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2507]
## 버그 설명 ##
Discovery에 데이터 업로드 및 데이터 모델 생성시 열려 있던 Studio, Analyzer를 브라우저를 닫았다/열어야 보임

## 재현하는 방법 ##
 Studio, Analyzer를 브라우저를 열어 놓은 상태에서 Discovery에 데이터 업로드 및 데이터 모델 생성 후 해당 데이터 모델을 불러오면 데이터모델이 없는 것으로 나옴

## 예상한 행동 ##
 Studio, Analyzer를 브라우저를 열어 놓은 상태에서 Discovery에 데이터 업로드 및 데이터 모델 생성 후 에 바로 불러와서 사용할 수 있음

**Comment by veldise** [comment]
기본적으로 Studio 와 Analyzer, Data-Discovery-Middleware는 별개 서비스라서 서로의 상태를 감시하고 있지 않습니다.
따라서 위 동작은 구현하기가 매우 어렵습니다.

Studio 모델 목록에 새로고침 버튼을 넣는 것은 쉽게 가능합니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 후 진행해 주세요.
-상태 변화 감지 혹은 브라우저의 새로 고침이 아닌 모델정보 재조회와 같은 방법으로 닫지 않은 상태에서 상태 정보만 다시 가져와서 로딩하면 되는 방향으로.
