### ISSUE TITLE
컴포넌트 제어 화면 enable/disable 기능 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2508]
## 기능 요청 ##
보고서 캔버스의 화면 좌측에 있는 컴포넌트 제어 화면에 대한 숨기기/보이기 기능 필요

## 원하는 솔루션 설명 ##
보고서 캔버스의 화면 좌측에 있는 컴포넌트 제어 화면에 대한 숨기기/보이기 기능 필요

**Comment by sunghoon** [comment]
@veldise 예정일정대로 진행 되나요?

**Comment by veldise** [comment]
@sunghoon 
이전 업무가 개발 난이도 등 이슈로 인해 많이 지연되어서, 현재 WBS 일정상으로는 10월 8일에 완료하기 어렵습니다.
10월 8일까지 완료되어야 한다면 담당자 변경이나 다른 방법을 검토하겠습니다.

**Comment by sunghoon** [comment]
@veldise 담당자기준(@hyun-jii) 목표일 진행 완료하는 기능이 무엇인지 정리하여 공유 해주세요.

**Comment by veldise** [comment]
@sunghoon 
10월 8일까지 아래 3가지 업무 완료를 목표로 하고 있습니다.
- 기간 설정 / 객체 리뉴얼
- 기간 설정 / 동적으로 날짜 지정 (항목 탭)
- 기간 설정 / 범위 기간 색상 표현 추가

**Comment by veldise** [comment]
@sunghoon 
개발 완료되었고 10.29 패치 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/96970346-8355c200-154e-11eb-97b2-d19d810ac58d.png)

**Comment by sunghoon** [comment]
@eumminsun @veldise 설정 화면을 보이게 하고 안하는 기능이라면 설정화면 자체에 해당 기능이 있어야 하는게 어떻가 합니다.
![96970346-8355c200-154e-11eb-97b2-d19d810ac58d](https://user-images.githubusercontent.com/512653/96971626-55717d00-1550-11eb-9834-9b4e36016b69.png)

**Comment by sunghoon** [comment]
@eumminsun 실제 사용에서는 '전체변수명보기' 와 '컴포넌트 설정역역' 을 토글형식으로 표시(펼치기)/닫기 가 되어야 하지 않을까 합니다.

**Comment by eumminsun** [comment]
@sunghoon 2020-10-29 (목) 해당 이슈와 관련하여 팀내 논의 결과
설정영역 접기 펼치기 부분은 현재 UI를 유지, 이후 사용자 편의성 증대를 위해 여러 레이아웃을 제공 하기로 하였으며, (설정 영역 왼쪽 위치) 
![image](https://user-images.githubusercontent.com/55674432/97638991-12983380-1a81-11eb-9837-22ad77b5f3a8.png)

전체 변수명 보기는 토글 형식으로 변경 하기로 하였습니다. 
전체 변수명 보기의 토글 형식 변경은 신규 이슈로 등록 하여 진행하겠습니다.
