### ISSUE TITLE
캔버스에 있는 컴포넌트들의 종류명과 변수명을 쉽게 확인할 방법이 필요함

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2509]
## 기능 요청 ##
캔버스에서 작업 중에 컴포넌트들의 종류 명과 변수명을 알려면 해당 컴포넌트를 선택하고 제어화면에서 속성을 눌러야만 알수있는데 작업중에 쉽게 알 수 있는 방법이 필요함 

## 원하는 솔루션 설명 ##
보고서 캔버스에서 특수키(F 버튼) 또는 Alt, Shift, Ctl 키 눌렀을때 컴포넌트 선택 시에는 건택된 컴포넌트만 캔버스를  선택했을때는 캔버스 위에 있는 모든 컴포넌트 위에 컴포넌트명과 변수명 출력 기능

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 해 주세요.

**Comment by rhcpn** [comment]
해당 이슈는 Studio 디자인 개선 시 반영하도록 하겠습니다.
