### ISSUE TITLE
화면(보고서/캔버스) 출력시 폭 또는 높이 중 가장 큰 것에 자동 맞춤 기능 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2513]
## 기능 요청 ##
화면(보고서/캔버스) 출력시 폭 또는 높이 중 가장 큰 것에 자동 맞춤

## 원하는 솔루션 설명 ##
캔버스 및 보고서 출력시 내용 중에 좌우/상하로 가장 큰 것에 맞춰 출력하는 기능 필요

**Comment by veldise** [comment]
@shinwoonsun 
이슈 본문 내용을 이해하지 못했습니다. 조금 더 상세히 적어주시면 감사하겠습니다.

또, 캔버스 객체 설정에는 크기를 % 단위로 설정할 수 있는 기능이 있습니다. 참고해주시기 바랍니다.

![image](https://user-images.githubusercontent.com/3411842/89748167-d6e27300-dafc-11ea-9ec7-17ff4f890b6d.png)

**Comment by shinwoonsun** [comment]
![인쇄-001](https://user-images.githubusercontent.com/13842947/89849952-9ea66780-dbc4-11ea-8b0c-a4fe2c508c09.jpg)


![인쇄-002](https://user-images.githubusercontent.com/13842947/89849963-a36b1b80-dbc4-11ea-9339-8ea0372e3ff2.jpg)

![인쇄-003](https://user-images.githubusercontent.com/13842947/89849969-a7973900-dbc4-11ea-994e-dc3d4113c220.jpg)

위의 이미지와 같이 보고서의 화면을 출력하려고 할때 출력내용이 깨지는 경우를 말씀 드린 것입니다.

사용자가 조회한 보고서를 바로 출력을 하려고 할때 해당 보고서가 용지의가로/세로에서 해당 용지의 크기에 대해 보고서의 좌우/상하 중  가장 큰 부분을 용지의 가장 작은 부분과 맞게 해야 될 것 같아 의견을 낸 것입니다.

**Comment by veldise** [comment]
@shinwoonsun 
화면 출력이라고 하셔서 이해를 못했습니다. "인쇄" 기능을 말씀하시는 거군요.
팀장님과 검토해보겠습니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 검토한 의견 공유 바랍니다.
