### ISSUE TITLE
보고서 실행시 조회를 안했을때 관련 차트의 화면이 빈 것으로 나옴

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2514]
## 버그 설명 ##
보고서 실행시 차트 조회를 안했을때 화면에 나타나지 않게 기능 수정 요청

## 재현하는 방법 ##
캔버스에서 작업한 데이터 객체와 연결된 차트가 조회되지 않았을때 화면에 나타나지 않게 기능 수정 요청

## 예상한 행동 ##
캔버스에서 작업한 데이터 객체와 연결된 차트가 조회하기 전까지는 데이터 객체와 같이 화면에서 보이지 않아야 함

**Comment by veldise** [comment]
@shinwoonsun 
실행되지 않았다고 특정 영역이 비어있으면 보고서 화면을 보는 사람들(사용자)이 이상하게 생각할 수 있습니다. 다른 개선 방안이 필요합니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
