### ISSUE TITLE
컴포넌트에서 작업 수행 후 결과가 없는 경우 ‘결과가 없습니다’ 메세지가 출력되도록 기능 수정

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2515]
## 기능 요청 ##
예를 들어 현재 데이터 객제와 연결된 챠트가 있는 경우 데이터 객체에서 작업 수행 후 출력할 데이터가 없는 경우 에러메세지가 DSL문의 에러가 나오는데 캔버스외 보고서로 실행할때는 '결과가 없습니다'와 같은 에러메세지로 출력되도록 기능 수정 요청

## 원하는 솔루션 설명 ##
데이터 객제와 연결된 챠트가 있는 경우 데이터 객체에서 작업 수행 후 출력할 데이터가 없는 경우 에러메세지를  '결과가 없습니다'와 같은 에러메세지로 출력되도록 기능 수정 요청

**Comment by veldise** [comment]
@shinwoonsun 
현재 b-iris.mobigen.com 기준 잘 나옵니다. 버전이나 현상을 확인을 부탁드립니다.

![image](https://user-images.githubusercontent.com/3411842/89751202-182d4f80-db0a-11ea-8bf9-9e435ef79813.png)

**Comment by shinwoonsun** [comment]
![조회 에러 발생 결과](https://user-images.githubusercontent.com/13842947/89849512-a285ba00-dbc3-11ea-9af8-34e445b8e111.jpg)

제가 말씀드린 것은 위의 이미지와 같이 데이터 조회를 위해 사용한 DSL문의 조건에 문제가 발생했을때 나오는 에러를 말씀 드린 것입니다.

진짜 문제가 있어서 나온 메세지이긴 하지만 개발된 IRIS를 사용하는 고객이 봤을때는 시스템의 문제가 있는 것으로 판단할 수 가 있기 때문에 이럴때는 한글로 다른 에러 메세지(예 '명령구문이 잘못되었습니다')를  출력하는 것이 좋을 것 같아 의견을 낸 것입니다.

**Comment by veldise** [comment]
@shinwoonsun 
에러가 발생했는데 결과가 없다고 출력하면 오히려 보고서를 작성하는 사람이 DSL에 문제가 있는지 없는지를 판단할 수 없게 됩니다.
사용자 친화적인 메시지로 개선하는 것은 말씀하신대로 필요합니다.

**Comment by sunghoon** [comment]
@seungfwani 어떻게 진행되고 있는지 공유 바랍니다.
