### ISSUE TITLE
작업중인 캔버스(보고서)의 자동저장기능과 변경내역 관리 기능, 보고서 수정 히스토리 관리와 공유 관리 기능 추가

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2516]
## 기능 요청 ##
작업중인 캔버스(보고서)의 자동저장기능과 변경내역 관리 기능, 보고서 수정 히스토리 관리와 공유 관리 기능 추가

## 원하는 솔루션 설명 ##
작업 중인 캔버스의 자동 저장 기능과 해당 캔버스의 일정 시점(저장시)의 롤백을 위한 히스토리 관리 및 한번 공유된 보고서가 변경되어도 변경된 보고서에 대한 공유가 유지되는 기능이 필요함

**Comment by sunghoon** [comment]
@shinwoonsun 낮은 우선순위로 처리 할 수 있도록 하겠습니다.
@eumminsun 검토 바랍니다.
