### ISSUE TITLE
이벤트 플로워 같이 특정 조건에 대해 컴포넌트를 호출하는 기능이 필요

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2517]
## 기능 요청 ##
조건에 따라 특정 컴포넌트를 호출/실행하도록 하는 기능 필요

## 원하는 솔루션 설명 ##
B, C, D 컴포넌트에서 A라는 컴포넌트(콤보박스라고 했을떄)에 트리거를 설정 했을때 A라는 컴포넌트에서 1=B, 2=C, 3=D라고 설정하고, 선택하는 값에 때라 B, C, D가 A의 결과에 따라 A에 대한 트리거를 실행하도록 기능 추가 요청

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 조건에 따른 이벤트 전달 컴포넌트를 준배 해 주시기 바랍니다.
