### ISSUE TITLE
한 보고서에 있는 여러개의 컴포넌트(차트)의 임계치 값을 일괄 적용하거나 다른 화면에서 개별 또는 일괄 적용값울 설정할 수 있는 기능 필요

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2518]
## 기능 요청 ##
한 보고서에 있는 여러개의 차트의 임계치 값을 일괄 적용하거나 다른 화면에서 개별 또는 일괄 적용값울 설정할 수 있는 기능 필요

## 원하는 솔루션 설명 ##
차트에 대해 하나하나 임계치를 설정하는 것이 아닌 일괄 적용을 할 수 있는 기능이 필요

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.
