### ISSUE TITLE
차트에서 임계치 기준 이상인 경우 이벤트가 발생할 수 있는 기능 필요

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2519]
## 기능 요청 ##
차트에서 임계치 기준 이상인 경우 이벤트가 발생할 수 있는 기능 필요

## 원하는 솔루션 설명 ##
다른 프로그램에서 개발 사용중인 IRIS를 통한 감시기능 구현을 위해 차트에서 특정 값이 임계치 이상 발생시 이벤트가 발생하는 기능이 필요, 해당 이벤트를 통한 다른 컴포넌트 트리거를 실행 하거나 팝업으로 특정 메세지를 실행 하기 위함

**Comment by veldise** [comment]
데이터 임계치에 따른 이벤트 발생은 백엔드와 연계해서 처리하는게 맞다고 생각됩니다.

**Comment by shinwoonsun** [comment]
백엔드라고 말씀 해주신 부분은 어떤 걸 말씀 하시는 것인가요?
혹시 해당 건에 대한 예제나 예시가 있으신가요?

**Comment by sunghoon** [comment]
@shinwoonsun 적용되었을때 사용이 예상되는 시나리오를 조금 더 설명해주시면 검토시 참고하겠습니다.
