### ISSUE TITLE
피봇으로 SPLITROW를 두개의 필드를 지정했을때 '차트'의 헤더에 두개의 필드 정보가 나오지 않고 첫번째 지정 필드만 나옴

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2520]
## 버그 설명 ##
피봇으로 SPLITROW를 두개의 필드를 지정했을때 '차트'의 헤더에 두개의 필드 정보가 나오지 않고 첫번째 지정 필드만 나옴

## 재현하는 방법 ##
피봇으로 SPLITROW를 두개의 필드를 지정했을때 '차트'에 첫번째 지정 필드만 나옴

## 예상한 행동 ##
피봇으로 SPLITROW를 두개의 필드를 지정했을때 '차트'에 SPLITROW 또는 SPLITCOL의 필드값이 다 나와야 함

**Comment by veldise** [comment]
@shinwoonsun 
어떤 명령어 or UI 설정시에 해당 현상이 재현되는지가 필요합니다.

현재 간단히 돌려봤을 때는 잘 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/89751424-f5e80180-db0a-11ea-9275-96941009eb1e.png)

**Comment by shinwoonsun** [comment]
![차트의 필드값 다중 울력](https://user-images.githubusercontent.com/13842947/89849031-9baa7780-dbc2-11ea-83d6-09e98bbddd2a.jpg)

위의 이미지와 같이 pivot을 이용하여 splitrow를 YEAR와 MONTH로 하여 두가지를 출력해야 하나 하나만 출력할 수 있는 상황입니다. 하위(MONTH)를 선택하면 상위의 (YEAR) 값까지 적용되어 나오는 것 같긴 합니다.

**Comment by veldise** [comment]
@shinwoonsun 
이슈를 작성하실 때 Analyzer의 '피벗' 기능에 대한 것인지, DSL `pivot` 명령어에 대한 것인지 적어주시면 감사하겠습니다.
그러면 저희가 조금 더 정확하게 대응할 수 있습니다.

위와 같은 데이터 형태를 다중축 차트로는 그리기 어렵습니다. 추가 검토해서 코멘트 남기겠습니다.

**Comment by veldise** [comment]
@shinwoonsun 
혹시 차트의 헤더라는게 툴팁을 말씀하시는게 맞나요?
그렇다면 지금은 기능이 없지만, Map 객체와 같이 툴팁 설정 기능을 추가하면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/90839257-03667c80-e392-11ea-81d6-de6a60dcc56c.png)

**Comment by sunghoon** [comment]
@shinwoonsun 
원하시는 표현을 위해 PERIOD 필드가 필요해 보이는데
실제 쿼리에는 해당 명령이 없어 참조해 주신 보고서에 적용해 두었습니다. 
확인해 보시고 검토 의견 주세요. 
![스크린샷 2020-09-24 오후 4 34 11](https://user-images.githubusercontent.com/512653/94114794-c8b99d80-fe83-11ea-8b8c-2f8cb8b95830.png)
