### ISSUE TITLE
차트 - 테이블에서 다중 선택이 가능하도록 기능 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2521]
## 기능 요청 ##
차트의 테이블(area)에 나온 값들에 대해 다중선택이 가능하도록 기능 요청

## 원하는 솔루션 설명 ##
차트의 테이블(area)에 나온 값들에 대해 다중선택하여 다른 컴포넌트로 해당 값을 전달 할 수 있는 기능이 필요

**Comment by veldise** [comment]
https://github.com/mobigen/IRIS-BigData-Platform/issues/2380

**Comment by sunghoon** [comment]
@shinwoonsun 10월 8일 배포 예정입니다.

**Comment by sunghoon** [comment]
@veldise 본 이슈에 대한 처리가 어떻게 진행되고 있나요? 계획일이 지났으며, 최근 패치항목에도 포함되어 있지 않은것 같았습니다.
