### ISSUE TITLE
차트 - 꺽은선형/다충축에서 선의 형태가 곡선형으로 설정 할 수 있는 기능 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2522]
## 기능 요청 ##
차트의 시각화 유형 중 꺽은선형이나 다충축에서 선의 형 직선이 아니라 곡선형으로 설정 할 수 있는 기능이 필요

## 원하는 솔루션 설명 ##
차트의 시각화 유형 중 꺽은선형이나 다충축에서 선의 형 직선이 아니라 곡선형으로도 변경할 수 있는 기능이 필요

**Comment by sunghoon** [comment]
@eumminsun 신규 시각화 유형입니다.
