### ISSUE TITLE
차트 - 테이블의  시각화에서 헤더 사이즈를 처음 변경 한 이후 변경이 안됨

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2524]
## 버그 설명 ##
차트 - 테이블의  시각화에서 헤더 사이즈를 처음 변경 한 이후 변경이 안됨

## 재현하는 방법 ##
1. 차트 - 테이블의  시각화에서 헤더 사이즈를 변경
2. 보고서를 저장 후 목록으로 나갔다가 다시 캔버스로 돌아옴
3. 1에서 설정을 변경한 테이블에서 다시 헤더 사이즈 변경시 변경되 값으로 적용이 안됨

## 예상한 행동 ##
차트 - 테이블의  시각화에서 헤더 사이즈를 변경 할 때 마다 변경한 값으로 적용이 되어야 함

**Comment by veldise** [comment]
@shinwoonsun 
시각화 옵션 > 헤더 설정에서 열(헤더) 각각의 가로 길이를 지정할 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/89751507-5e36e300-db0b-11ea-90f5-d27a9d75f0d3.png)

**Comment by shinwoonsun** [comment]
![치드 필드 사이즈 에러 -001](https://user-images.githubusercontent.com/13842947/89848201-e7f4b800-dbc0-11ea-9233-e704b95f8d2a.jpg)


지금 버전에서는 테이블의 필드값을 수정 한 후에 저장 > 목록으로 > 다시 수정으로 캔버스에 들어온다음에 해당 데이터 객체를 실행하여 테이블에 데이터 값을 출력 후에 테이블을 클릭하면 초기화가 됩니다.

확인 부탁드립니다.

**Comment by veldise** [comment]
데이터 객체 실행 후 차트 객체를 선택하면 발생하는 문제로 확인되었습니다.
