### ISSUE TITLE
차트- 다중축에서 같은 값의 범위에서 Y축이 두개인 경우  Y축의 범위가 다르게 나옴

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2525]
## 버그 설명 ##
같은 레벨의 값으로 차트 유형의 다중축을 선택해서 Y축에 같은 값을 2개로 설정하여 하나는 세로막대형으로 하나는 꺽은선형으로 지정했을때 Y 축의 값이 달라 서로 다른 값같이 표현됨

## 재현하는 방법 ##
같은 레벨의 값으로 차트 유형의 다중축을 선택해서 Y축에 같은 값을 2개로 설정하여 하나는 세로막대형으로 하나는 꺽은선형으로 지정했을때 Y 축의 값이 달라 서로 다른 값같이 표현

## 예상한 행동 ##
같은 레벨의 값으로 차트 유형의 다중축을 선택해서 Y축에 같은 값을 2개로 설정하여 하나는 세로막대형으로 하나는 꺽은선형으로 지정했을때 Y 축의 값이 같은 레벨로 출력

**Comment by veldise** [comment]
@shinwoonsun 
현상 재현을 위한 DSL 명령어 혹은 설정 예시가 필요합니다.

간단한 예제를 돌렸을 때는 정상 처리되고 있습니다.

![image](https://user-images.githubusercontent.com/3411842/89751582-b79f1200-db0b-11ea-8649-99b5864fb23c.png)

**Comment by shinwoonsun** [comment]
![다중축차트 에러 보고](https://user-images.githubusercontent.com/13842947/89847508-2ab59080-dbbf-11ea-8e05-2240bc7023fc.jpg)

차트-다중축을 사용했을때 위의 이미지와 같이 똑같은 값인데도 서로 다른 축을 가지게 됩니다.

참고를 위해 '500- 이슈보고 - 2525 - 차트- 다중축에서 같은 값의 범위에서 Y축이 두개인 경우 Y축의 범위가 다르게 나옴' 보고서에 해당 내용을 정리하여 만들었습니다. 확인 부탁드립니다.

**Comment by veldise** [comment]
@shinwoonsun 
확인하였습니다.

**Comment by veldise** [comment]
Highcharts 에서 y축을 자동 구성할 때, 꺾은선 / 막대형이 서로 다르게 처리되는 것 같습니다.

**Comment by sunghoon** [comment]
@veldise http://covid19.iris.tools/ , 'COVID19 실시간' 보고도 동일합니다. 
되도록 빠른 조치가 이루어 지면 좋겠습니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
다중축에서 서로 다른 Y축에 동일한 컬럼을 지정한 경우, 첫번째 Y축을 기준으로 Y축 tick을 구성하도록 해보겠습니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
차주 중에 처리해서 10/29 패치를 목표로 진행하겠습니다.

**Comment by sunghoon** [comment]
@veldise 'Done'로 되어 있는데 해당 기능은 어떻게 확인해야 하나요?
