### ISSUE TITLE
차트 - 원형 선택시 모양을 변경할 수 있도록 기능 추가 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2526]
## 기능 요청 ##
차트 - 원형 선택시 모양을 현재의 모양이 아닌 도넛 모양과 같은 다른 형태로 변경할 수 있도록 기능 추가 요청

## 원하는 솔루션 설명 ##
차트 - 원형 선택시 모양을 현재의 모양이 아닌 도넛 모양과 굵기를 설정할 수 있는 기능 추가 요청

**Comment by sunghoon** [comment]
@eumminsun 컴토 바랍니다.
