### ISSUE TITLE
차트 - 게이지를 선택시 다른 모양으로 변경 할 수 있는 기능 추가 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2528]
## 기능 요청 ##
차트 유형의 게이지를 선택시 원형이나 다른 모양을 변경 할 수 있도록 기능 추가 요청

## 원하는 솔루션 설명 ##
차트 유형의 게이지를 선택시 현재의 모양 처럼 도넛의 반 모양이 아닌 다른 모양(완전한 동그란 도넛)으로 변경 할 수 있도록 기능 추가 요청

**Comment by sunghoon** [comment]
@eumminsun 다양한 게이지 시각화가 있으면 될 것 같습니다.
