### ISSUE TITLE
차트 - 게이지에서 최대값을 지정하도록 기능 추가 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2529]
## 기능 요청 ##
차트 유형의 게이지를 선택시 다른 차트의 유형과 달리 최대값을 지정할 수 없음

## 원하는 솔루션 설명 ##
현재 차트 - 게이지에서는 무조건 100%가 최대값인데 최대값을 0%~100%까지 사용자가 지정 할 수 있도록 기능 추가 요청

**Comment by sunghoon** [comment]
@eumminsun 검토 진행 해 주세요. 추가적으로 지정 값으로 할때는 %가 아닌 일반 상수도 지정할 수 있도록 바랍니다.
