### ISSUE TITLE
라벨 컴포넌트에서 트리거를 설정할때 지도의 값은 선택이 안됨

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2530]
## 버그 설명 ##
라벨 컴포넌트에서 트리거를 설정할때 지도의 값은 선택이 안됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
캔버스에 지도와 라벨을 생성하고 라벨에서 트리거를 선택시 지도에는 트리거를 선택할 수 있는 창이 나타나지 않음

## 예상한 행동 ##
캔버스에 지도와 라벨을 생성하고 라벨에서 트리거를 선택시 지도에는 트리거를 선택할 수 있는 창이 나타나 트리거를 설정하고, 해당 지도를 선택했을때 지정된 값이 라벨에 출력되어야 함

**Comment by sunghoon** [comment]
@shinwoonsun 조금 더 구체적인 사용 예를 알려주시면 진행할지 말지에 대한 판단 자료로 사용하겠습니다.
