### ISSUE TITLE
체크박스/라디오 버튼, Tag의 글자 색, 사이즈 변경 안됨

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2531]
## 버그 설명 ##
체크박스/라디오 버튼, Tag의 글자 색, 사이즈 변경 안됨

## 재현하는 방법 ##
체크박스/라디오 버튼, Tag를 캔버스에 생성시 기본 글자 색, 사이즈외 변경 안됨

## 예상한 행동 ##
체크박스/라디오 버튼, Tag의 글자 색, 사이즈를 사용자의 설정값에 따라 변경

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 해 주세요.
