### ISSUE TITLE
[데이터모델] 목록에서 항목 개수 정보가 "전체" 일 때 항목 개수로만 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2533]
## 버그 설명 ##

b-iris.mobigen.com demo 계정

- Discovery - 데이터모델

- "전체" 선택
<img width="1329" alt="스크린샷 2020-08-11 오전 10 30 09" src="https://user-images.githubusercontent.com/5126497/89847009-bdedc680-dbbd-11ea-9364-bf1bf9a99b6e.png">

- "데이터모델 뷰"  선택 
<img width="1333" alt="스크린샷 2020-08-11 오전 10 30 31" src="https://user-images.githubusercontent.com/5126497/89847012-c1814d80-dbbd-11ea-98d3-3c6f88a769db.png">

- 데이터모델 선택
<img width="1332" alt="스크린샷 2020-08-11 오전 10 30 23" src="https://user-images.githubusercontent.com/5126497/89847021-c6460180-dbbd-11ea-854f-53a672f5efc3.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
항목 개수로만 나온다는게 정확히 무슨말인가요?

**Comment by seoryjj** [comment]
데이터모델을 선택해도, 전체항목의 개수인 137 개로만 표시됩니다. 모델뷰는 21 개 밖에 안되지만,  137개에서 20개 .. 이렇게 보여집니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈가 닫혔다가 다시 열렸는데 사유가 궁금합니다.

**Comment by veldise** [comment]
@sunghoon 
아직 처리가 안 된 항목이어서 다시 열었습니다. 10월 중에 처리 예정입니다.
https://github.com/mobigen/IRIS/issues/27

**Comment by veldise** [comment]
@sunghoon 
차주 패치(10/29)를 목표로 일정을 다시 잡았습니다.

**Comment by sunghoon** [comment]
@veldise 'Done'이면 배포 된것으로 보면 되나요?
