### ISSUE TITLE
차트-테이블의 페이지 이동 버튼이 처음과 끝으로만 이동됩니다.

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2534]
## 버그 설명 ##
차트-테이블의 페이지 이동 버튼이 예전에는 페이지 단위로 선택이 되었는데 지금은 처음과 끝으로만 이동됩니다.

해당 기능이 컨트롤바인거 같은데 1단, 2단 을 선택해도 변화가 없습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
<,> 로는 한페이지씩 이동 <<, >> 이 처음과 끝으로 이동되게 되었으면 합니다.

## 스크린샷 ##
![페이지 이동-001](https://user-images.githubusercontent.com/13842947/89860347-36647f80-dbde-11ea-87d3-0b67062c2994.jpg)

![페이지 이동-002](https://user-images.githubusercontent.com/13842947/89860359-3c5a6080-dbde-11ea-8b07-6f08be50d9c9.jpg)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
디자인 개선 작업에 따라 변경된 UI입니다.
일단 아래와 같이 페이지 번호를 직접 입력하는 것으로 원하는 페이지로 이동할 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/89876916-4d18cf80-dbfa-11ea-9d3e-b6b2a669bc7e.png)

**Comment by veldise** [comment]
기획과는 반대로 구현된 버그로 확인되었습니다.
한 페이지씩 이동하는게 맞고, 처음과 끝으로 이동하는 버튼은 삭제되었습니다.

**Comment by SONHOJUN** [comment]
처음과 끝으로 이동하는 버튼이 있었으면 합니다. 불편합니다.

**Comment by veldise** [comment]
@SONHOJUN 
버튼을 다시 추가할 예정입니다. #2590
