### ISSUE TITLE
[NMS+]DB브라우저 접근시 에러 확인요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2537]
## 버그 설명 ##

일부사용자 계정이 아래와 같이 에러가 뜹니다.
그래서 사용자ID 가 문제가 있는지 ( user_id 생성규칙이 벗어난건지 보았으나 특이사항이 없어서 확인부탁드립니다. )

user_id : tensal

1. DB브라우저 접근시 에러발생 ( user_id : tensal )
![tensal2](https://user-images.githubusercontent.com/5468183/89969007-4d63aa00-dc90-11ea-9a6c-e9477ffd1728.jpg)

2. root에서 데이터베이스 grant 접근 권한 부여시 다음과 같은 에러 발생 ( user_id : tensal )

![tensal1](https://user-images.githubusercontent.com/5468183/89968977-3de46100-dc90-11ea-9922-878aff4ef4cd.jpg)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@jjinylee 
https://github.com/mobigen/IRIS-BigData-Platform/issues/2363#issuecomment-652234564

이전에 코멘트로 말씀드린 것과 같이 IRIS-DB에 계정이 없어서 발생하는 문제입니다.
계정을 삭제 후 다시 추가하면 정상 동작할 것이고, 사용중인 계정이라 삭제하는게 어렵다면
2개 계정에 대해서는 수동으로 IRIS-DB 계정을 추가해야 합니다.

운용기술연구팀에 요청하시면 처리해줄 것입니다.

**Comment by jjinylee** [comment]
@sunghoon 그룹장님.
이번주 권영길T 이 휴가인걸로 알고있습니다.

고객이  특정 사용자에 nmsplus 데이터베이스를 grant 권한을 주다가 오류가난다고,
tensal 부터 안되서  아래계정에 다 작업을 해달라고 합니다.

권영길T 대무자가 있는지 확인부탁드립니다.

tensal
miscre
park7275
wlaqldhsek
hjchoi05
simonps
keab001

**Comment by veldise** [comment]
@jjinylee 
배성훈 그룹장님도 휴가이십니다.

@big-mobigen 
지원 부탁드립니다.

**Comment by big-mobigen** [comment]
@jjinylee 

tensal
miscre
park7275
wlaqldhsek
hjchoi05
simonps
keab001

위 계정들의 비밀번호를 전달해 주실수 있으신가요?
불가능 하다면 위 계정들의 비밀번호를 임시로 변경해도 가능한건지 문의 드립니다.

**Comment by big-mobigen** [comment]
@veldise 
@jjinylee 

tensal
miscre
park7275
wlaqldhsek
hjchoi05
simonps
keab001

계정들에 대해서 PW를 ID와 동일하게 설정 하였으며,
NMSPLUS Database 권한을 부여 하였습니다.

감사합니다.

**Comment by veldise** [comment]
해결된 것으로 보고 이슈 닫습니다.
