### ISSUE TITLE
[NMS+]studio DSMS 쿼리시 그리드내 숫자 정렬이 안됨

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2538]
## 버그 설명 ##

https://github.com/mobigen/IRIS-BigData-Platform/issues/2466

해당이슈에 올렸던 내용으로

DSL 이 아닌 DSMS 쿼리로 아무리 타입변환을 해도 ( iris : +0, mariadb: convert) 
그리드를 뿌릴때 type:TEXT 로 고정이 되어있어 그리드내에서 정수/실수 타입의 컬럼은 정렬이 안됩니다.

IRIS/ Maria-DB 등 다양하게 DSMS 로 그리드를 조회하여 사용하고 있습니다.

숫자/실수 정렬기능이 필요합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm 
쿼리로 타입 변환을 해도 `type: TEXT` 로 반환되는지 확인 부탁드립니다.

**Comment by jjinylee** [comment]
@anhm  책임님. 어제 잠시 회의실에서 확인했던 사항입니다.
안형민C 와 확인시 DSMS 는 type:TEXT 로 고정이라고 확인받았습니다.

**Comment by veldise** [comment]
@anhm 
IRIS-DB는 이전에 듣긴 했는데, 다른 DB는 왜 type이 TEXT로 고정인가요?

**Comment by anhm** [comment]
@veldise 
IRIS-DB의 경우 쿼리의 타입을 유추할수 있는 형태가 아니기 때문에, 결과를 무조건  TEXT로 반환하고 있는 상태입니다.

**Comment by anhm** [comment]
@jjinylee 
DSMS를 이용시  다른 DB들은 정상적으로 타입을 반환하며, 
IRIS-DB만 TEXT 컬럼으로 반환되는 상태입니다.

**Comment by jjinylee** [comment]
@anhm 아하. 아예 전체가 그런줄아랐습니다.

그럼 IRIS-DB는 힌트의 format 기능을 써서 고객에게 보고서를 바꾸라고 하겠습니다. (한두개가 아니라서 다 만들어줘야할텐데 피곤하군요 )
기능  부탁드립니다.

**Comment by sunghoon** [comment]
@anhm 최종 진행 상황 공유 부탁합니다.

**Comment by anhm** [comment]
IRIS-DB를 최신버전으로 패치를 진행하면 
```
/*+ TYPECAST(0=INTEGER) */ select count(*) ...
```
와 같은형태의 hint문을 사용할 수 있습니다.

**Comment by sunghoon** [comment]
@jjinylee 책임님 본 이슈 대응에 대한 처리 인지 되셨는지 의견 바랍니다.

**Comment by jjinylee** [comment]
이부분은 IRIS-DB 만 패치하면 되는건지요?
확인해주시면, 패치일정 잡도록 하겠습니다.

**Comment by sunghoon** [comment]
@anhm @veldise 패치 진행을 위한 최정 확인 답변 바랍니다.

**Comment by anhm** [comment]
@jjinylee 
IRIS-DB만 패치를 진행하면 됩니다.

**Comment by jjinylee** [comment]
차주 월~화(10/12 or 13일) 에 패치가능할까요?
#2146  와 함께 진행했으면 합니다.

위의 일정 가능한지 확인부탁드립니다.

**Comment by sunghoon** [comment]
@jjinylee 운영기술 연구팀으로 해당 업무를 이관하고 본 이슈는 닫도록 하겠습니다.

**Comment by big-mobigen** [comment]
금일 기존 IRIS_CORE_2.1.6_1_3b03964.zip에서 IRIS_CORE_2.1.7_d47f981.zip로 패치가 완료되었습니다.
