### ISSUE TITLE
태그의 활성화/비활성화 상태 관리

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2539]
## 기능 요청 ##
태그에서 지정된 트리거가 발생했을때 조건으로 태그의 활성화/비활성화 상태를 바꿀 수 있을까요?

그리고 조건으로 인하여 비활성화를 만들고 싶은 것이 아에 삭제가 되는데 삭제가 되는 것이 아닌 비활성화로 만들도록 할 수 있을까요?

예를 들어 태그를 이용하여 00~23시까지 만들고 특정 시간을 제외 했을때 사라지는 것이 아닌 비활성화로 만들 수 있을까요?

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }
* 원하는 화면
![제외시간-관리최번-001](https://user-images.githubusercontent.com/13842947/89994846-a567d400-dcc3-11ea-9db8-0a6f621019a0.jpg)

* 실제화면
![제외시간-관리최번-002](https://user-images.githubusercontent.com/13842947/89994865-abf64b80-dcc3-11ea-8270-8d91f0d471f6.jpg)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 개선 검토 바랍니다.
