### ISSUE TITLE
테그의 정렬 문의

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2540]
## 버그 설명 ##
태그와 연결한 데이터 객체에서 정렬한 값과 태그에서 정렬되는 값이 다름
 > 태그는 연결된 값을 무시하고 태그 자체에서 가나다 순으로 정렬 하는 건가요?

예를 들어 월 - 일요일까지 1- 7로 값을 할당하여 정렬하였으나, 태그에서는 금, 목 - 화로 가나다 순으로 정렬됨

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

* 데이터에서 정렬한 값
![데이터모델](https://user-images.githubusercontent.com/13842947/89995950-28d5f500-dcc5-11ea-8b93-9307157c1d2e.jpg)

* 태그에서 나오는 값
![태그정렬](https://user-images.githubusercontent.com/13842947/89995970-2ecbd600-dcc5-11ea-87bc-bc6667360a90.jpg)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
네, 현재 태그 자체에서 정렬을 하고 있습니다. 이는 의도된 동작이 아니므로 **버그**이며, 금일중으로 수정 배포하겠습니다.
