### ISSUE TITLE
태그의 활성화/비활성화 색상 구분

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2541]
## 기능 요청 ##
새롭게 변경된 UX에서 태그의 태그의 활성화/비활성화 색상 구분이 어렵습니다.
태그의 비활성화때 색을 좀더 연하게 하실 수 있으신지 문의를 드립니다.

* 활성화된 태그와 비활성화 된 태그 화면
![태그색상](https://user-images.githubusercontent.com/13842947/89996287-91bd6d00-dcc5-11ea-840e-728472379456.jpg)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun @onlyeon 색상 중심으로 빠른 진행 바랍니다.

**Comment by onlyeon** [comment]
이슈 내용 확인하였습니다.
태그 컴포넌트 활성/비활성 상태 명시도 증가를 위한 디자인, 퍼블리싱 작업 진행 예정입니다.

**Comment by sunghoon** [comment]
@veldise 적용 일정을 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
긴급한 사항이 아니면 차주 목요일(10/22) 패치에 포함시키겠습니다.
