### ISSUE TITLE
[Studio] 차트 -> 테이블 유형의 외각선에 대한 여백 설정 혹은 설정 가능한 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2542]
![image](https://user-images.githubusercontent.com/11566844/90013752-d86c9080-dce0-11ea-9582-fa37c29bd4bb.png)

디자인 1차 개선 이후, 차트의 테이블 유형에 외각선을 설정하면 사방에 padding 설정이 없어서 너무 타이트한 느낌입니다.
1. 기본적인 Padding 설정이 추가 되어야 함
2. 외각선 설정 시, Padding 속성 값을 입력 가능한 기능이 추가 되어야 함

일단 1번 항목은 우선 처리 되어야 할것 같습니다.

**Comment by onlyeon** [comment]
grid-chart 에 상하좌우 기본 `10px` 씩 여백이 생기도록 수정해두었습니다.
IDS `dev` 브랜치 확인 부탁드립니다 :)

**Comment by veldise** [comment]
아래와 같이 적용 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/90206572-f6d8a600-de1e-11ea-8001-1a5fd9c39d4c.png)
