### ISSUE TITLE
[Analyzer] outlier - dbscan 알고리즘 결과가 이상합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2546]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

참고할 분석탬플릿 : **이슈_outlier_chart_0813**

- 결과에서 label 이 -1, 0 으로 나오는데,  같은 label 에  outlier은  true, false 가 같이 있습니다. label 의 의미가 뭔가요???

<img width="1122" alt="스크린샷 2020-08-13 오전 11 33 19" src="https://user-images.githubusercontent.com/5126497/90088005-fc6bb880-dd58-11ea-9da4-b79452b44441.png">

<img width="1134" alt="스크린샷 2020-08-13 오전 11 33 39" src="https://user-images.githubusercontent.com/5126497/90088010-ffff3f80-dd58-11ea-9890-390a29ff1c59.png">

<img width="1138" alt="스크린샷 2020-08-13 오전 11 34 01" src="https://user-images.githubusercontent.com/5126497/90088015-02fa3000-dd59-11ea-9bae-f87c2b31193f.png">

 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
dbscan 알고리즘을 통해서 나온 결과 군집을 라벨로 표시를 하고있습니다.

예를 들어 A,B,C 호스트가 각각 10개씩 있을때, dbscan 결과가 아래와 같이 분리가 됩니다.
  라벨1: A 1개, B 10개, C 10개
  라벨2: A 9개
이와 같이 구분이 된다면 라벨2 군집에 A 만 속해있어 A를 이상치 라고 판단을 하는 것입니다.

그래서 outlier 는 true 이지만, 라벨은 여러개가 있을 수 있습니다.
