### ISSUE TITLE
모델 뷰에서 검색어에 DSL문을 입력후 처리된 데이터에 대해 저장할때 에러 발생

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2550]
## 버그 설명 ##
모델 뷰에서 검색어에 DSL문을 입력후 처리된 샘플데이는 정상으로 출력되는데 저장할때 에러 발생 합니다.

사용한 데이터 모델은 RI_TS_3G_LG_S2116 이고 모델뷰 명은 RI_TS_3G_LG_S2116_VIEW 입니다.

검색어에 입력한 DSL문은 아래와 같습니다.
```
*
| where RNC_ID in ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10' '11', '12', '13', '14', '15', '16', '17', '18', '19', '20')
| stats sum(S2116_CONNECT) as S2116_CONNECT, sum(S2116_CONNACK) as S2116_CONNACK by STAT_DATE, STAT_HOUR, MSC_ID
| concat STAT_DATE, "-", STAT_HOUR, "-", MSC_ID as OBJECT_ID

| where RNC_ID in ('999') 또는 RNC_ID = '999'
| concat STAT_DATE, "-", STAT_HOUR, "-", MSC_ID as OBJECT_ID
```
도 샘플데이터엔 정상으로 출력되나 저장시 에러가 발생합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![iris_error_20200814-001](https://user-images.githubusercontent.com/13842947/90232805-23f57a80-de58-11ea-98ab-02ddd59af7a3.jpg)

![iris_error_20200814-002](https://user-images.githubusercontent.com/13842947/90232820-2952c500-de58-11ea-9840-1eb6cdd6dff4.jpg)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@shinwoonsun 
해당 문제는 최초 저장시 에는 발생하지 않는 것으로 확인되며,
편집기능 즉, 모델 뷰를 업데이트 하고자 할 때 발생하는 것으로 보입니다.

내부적으로 생성-업데이트의 쿼리 생성에 차이가 있는지 확인 후 처리하도록 하겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 정보를 공유 해 주시기 바랍니다.

**Comment by seungfwani** [comment]
모델 뷰 업데이트 시, DSL 의 처리 불가로 인한 문제를 해결 하였습니다.

![Screen Shot 2020-09-25 at 5 23 24 PM](https://user-images.githubusercontent.com/46172579/94244427-d3436800-ff53-11ea-98e2-9164acd12846.png)
