### ISSUE TITLE
[NMS+, 공통] 라인챠트의 데이터값(툴팁) 보기 방법 변경 요청 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2551]
## 기능 요청 ##
- 범례가 3-4개만 넘어가도 라인의 값이 뭔지 보기 어렵습니다.
- 일반적인 라인챠트는 선택한 라인에 대해서만 X축에 따라 값이 보입니다.

- 그리고 이 그래프에 마우스가 지나가기만 해도 툴팁이 나와서 다른 챠트를 보기 어렵습니다.
- IRIS 의 라인 챠트
<img width="717" alt="스크린샷 2020-08-18 오전 9 26 43" src="https://user-images.githubusercontent.com/5126497/90456936-1fb9ad80-e135-11ea-9cb0-df2062de1f2f.png">

- 일반적인 라인챠트
<img width="849" alt="스크린샷 2020-08-18 오전 9 20 53" src="https://user-images.githubusercontent.com/5126497/90457028-61e2ef00-e135-11ea-9518-e4b0eb458556.png">

- NMS+ 뿐 아니라 IRIS 의 라인챠트에 공통된 이슈입니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
#2386 
이전에 선이 겹쳐있을 때 값을 확인하기 어렵다는 사용자 요구사항에 의해 툴팁을 통합했었습니다.
다시 분리할지에 대해서는 검토 후 처리하겠습니다.

**Comment by seoryjj** [comment]
그럼 두가지 모드를 선택해서 볼 수 있게 하는 방법은 없나요?

**Comment by sunghoon** [comment]
@eumminsun 기능 검토하여 진행 바랍니다.
