### ISSUE TITLE
[Studio] cicd 보고서 에러

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2553]
## 버그 설명 ##
cicd-dashboard에서 highchart error 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'Studio'
2. Click on 'CI/CD-dashboard'

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/90577543-2828eb80-e1fc-11ea-8f35-466966beacc5.png)
- 좌측상단 '활성화 프로젝트 리스트'에서 선택 시 'angora-v3'와 'mobigen.github.io'에서 에러메세지 발생

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
지난 배포 시 모든 활성화 프로젝트에 대해 에러 발생하였으나, 현재 2건만 발생 중임

**Comment by veldise** [comment]
highcharts 15번 에러는 X축이 연속형 데이터(숫자, 시간)인데 정렬이 되어있지 않을 때 발생합니다.
이전 막대형 차트를 그릴 때 사용자의 의도와는 관계없이 자동 정렬을 하는 부분이 있어서 정렬 동작을 제거하였었는데,
꺾은선 차트도 같이 제거가 된 것 같습니다. 검토 후 수정하겠습니다.

지금 당장은 아래와 같이 x축에 해당하는 컬럼으로 정렬해주면 정상 동작합니다.
```sql
ORDER BY
    build_no asc
```
