### ISSUE TITLE
[Analyzer] 시각화 분석유형의 아이콘이 정상적으로 출력되지 않음

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#2554]
## 버그 설명 ##
시각화 분석유형의 아이콘이 정상적으로 출력되지 않음

## 재현하는 방법 ##
Analyzer -> 시각화 -> 분석유형 선택

## 예상한 행동 ##
각 기능에 맞는 아이콘 출력

## 스크린샷 ##
이상치, 예측, 지도형의 아이콘이 정상 출력되지 않음
![image](https://user-images.githubusercontent.com/49141403/90606992-917c1f00-e23b-11ea-9877-81ceea814c9d.png)

## 기타 ##
.pop-analysis-type .type4 이상치
.pop-analysis-type .type5 예측
.pop-analysis-type .type6 지도형

의 before 클래스가 정상적으로 nth-child 에 의해 정의 되지 않고 있습니다.

**Comment by veldise** [comment]
금일 패치로 정상화했습니다.

![image](https://user-images.githubusercontent.com/3411842/90834797-052a4300-e386-11ea-9c8f-e3a20326c5da.png)
