### ISSUE TITLE
Studio: Chart / 행 클릭시 코드 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2555]
## 버그 설명 ##
Studio: Chart / 행 클릭시 코드 에러

## 재현하는 방법 ##
동작을 재현하는 방법 :
"CI/CD-dashboard" 보고서
1. `data-143` (common_data_1) 객체 선택하여 실행
2. `chart-5` 객체 grid-view 랜더링
3. 행 클릭

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/90704063-655baf00-e2ca-11ea-8c4e-04b0fd3cfb33.png)

**Comment by sunghoon** [comment]
@veldise 어떻게 처리 되었나요?

**Comment by veldise** [comment]
@sunghoon 
위 에러는 agGrid 모듈 내부에서 발생하고 있는데, agGrid 를 사용하고 있는 코드는
agGrid 공식 사이트에서 가이드하고 있는 코드와 별다른 것이 없어 원인을 찾지 못하고 있는 상황입니다.
추가로 재현이 어렵고 에러가 발생하더라도 동작 상에는 문제가 없는 것처럼 보입니다.

**Comment by sunghoon** [comment]
우선 닫습니다.
