### ISSUE TITLE
[Analyzer] 칼럼 그리드 문제

### ISSUE THREAD

**Issue by YusunPark** [mobigen/IRIS-BigData-Platform#2556]
## 버그 설명 ##

자동으로 선택되어진 칼럼에서 하나를 해제했다가 다시 선택할 경우 그리드가 제대로 그려지지 않는 것 같습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
window 10 / chrome

### 1. 처음 화면
![image](https://user-images.githubusercontent.com/59571464/90703853-e1a1c280-e2c9-11ea-9672-bae1b30b145a.png)

### 2. Species 칼럼을 선택해제 후 -> 재 선택시 => Species 왼쪽 줄이 안 생김  
![image](https://user-images.githubusercontent.com/59571464/90703917-026a1800-e2ca-11ea-9a1d-4d085ee95481.png)

### 3. 2번 상태에서 Petal_Width 선택해제 후 -> 재 선택시 => Petal_Width 내용의 왼쪽 줄 안 생김 & 제목 오른쪽 줄 안생김
![image](https://user-images.githubusercontent.com/59571464/90704000-40ffd280-e2ca-11ea-80c3-2d95d7b1c8d5.png)

### 4.  Sepal_Width 선택해제 후 -> 재 선택시 => Sepal_Width 내용의 왼쪽 줄 안 생김 & 제목 오른쪽 줄 안생김 (위 내용 반복)
![image](https://user-images.githubusercontent.com/59571464/90704090-88865e80-e2ca-11ea-9533-06ca6d9444aa.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by onlyeon** [comment]
안녕하세요!

이슈 내용 검토 결과 컬럼이 사라졌다 다시 나올 때 **DOM의 위치가 달라져서 발생하는 현상**으로 확인됩니다.
현재 ag-grid의 마지막 cell의 `border-right`를 없애는 방식으로 스타일링 되어 있는데
DOM의 구조가 바뀌어 중간에 끼인 cell이 DOM상 마지막 cell이 되고 있습니다.
이런 경우 CSS만으로는 컬럼 사이의 `border`를 스타일링 하는것이 불가능하며,
개발 파트에서도 DOM을 ag-grid에서 제어하기 때문에 개선하기 어려운 부분이라는 답변을 받았습니다.

ag-grid는 어떤 방식으로 대응하는지 [g-grid demo 사이트](https://www.ag-grid.com/example.php?theme=ag-theme-balham)를 살펴보니 컬럼사이에 `border`가 없는 디자인이었습니다.

컬럼이 제거/추가될 때 DOM위치 제어가 어려운 관계로 그리드 차트의 디자인을 개선하는게 제일 좋은 방법으로 판단됩니다.
디자인 개선은 팀내 일정 협의 후 진행하도록 하겠습니다.

**Comment by onlyeon** [comment]
![스크린샷 2020-08-28 오후 3 28 44](https://user-images.githubusercontent.com/11944592/91530282-cf68f980-e945-11ea-8352-c89cd796d544.png)

칼럼 세로 구분선을 제거하는 방식으로 디자인을 수정했습니다.
IRIS-Design-System REPO에 올라가 있으며, 추후 배포에 반영될것으로 예상됩니다.
