### ISSUE TITLE
[Discovery]  새모델 생성 시 MYSQL 테이블 선택하면 angora 에러 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2557]
## 버그 설명 ##
b-iris.mobigen.com  demo

MYSQL / 연결정보 mySQL_199
해당 테이블은 Studio 에서 DB연결로 사용 중인 테이블입니다.

-  새모델 생성 시 MYSQL , 연결정보, 테이블 선택
<img width="467" alt="스크린샷 2020-08-20 오전 10 03 04" src="https://user-images.githubusercontent.com/5126497/90704923-bb315680-e2cc-11ea-9c81-fde730c7b694.png">

-  에러 팝업창이 뜹니다.
<img width="510" alt="스크린샷 2020-08-20 오전 10 02 44" src="https://user-images.githubusercontent.com/5126497/90704958-d0a68080-e2cc-11ea-815c-584bd113cb47.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@veldise 
데이터 검색 쿼리가 제대로 들어오지 않는것 같습니다.

예상 명령어: `mysql read EDU_INCHEON_BUS_08 connector_id = 240`

**Comment by veldise** [comment]
@seungfwani 
버그 확인했습니다. MYSQL일때만 발생합니다.

**Comment by sunghoon** [comment]
@veldise @seungfwani 최종 상태 정보 공유 해 주세요. 어느쪽에서 처리해야 하는건가요?

**Comment by veldise** [comment]
@sunghoon 
UI 버그입니다. 곧 수정하겠습니다.
