### ISSUE TITLE
[개선] 파일이동 시 동일명의 파일이 존재하면 아무 메시지 없이 창이 닫힙니다.

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2559]
## 기능 요청 ##
파일이동 시 동일명 파일이 있는 경우
- '동일한 이름의 파일이 있습니다' 메시지 
- 사용자로 하여금 덮어쓰거나 파일유지를 선택할 수 있는 대화창 필요

- 동일한 이름의 파일(사이즈 다름)이 존재하는 디렉토리로 이동
- 경고 메시지 출력되지 않음
![image](https://user-images.githubusercontent.com/44352311/90710832-2b92a480-e2da-11ea-8eca-3ad1c1760901.png)

- 이동 폴더에 동일한 이름의 파일이 있으나 치환되지 않음
![image](https://user-images.githubusercontent.com/44352311/90710879-46651900-e2da-11ea-82c6-a9001bacce90.png)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
'현재 경로' 추가

![image](https://user-images.githubusercontent.com/3411842/92571625-4f844d00-f2be-11ea-94ee-03aaacee0829.png)

동일 경로 / 단일 파일 / 중복 파일명 존재:

![image](https://user-images.githubusercontent.com/3411842/92571904-aa1da900-f2be-11ea-94c7-3edd8297bbba.png)

동일 경로 / 다중 파일:

![image](https://user-images.githubusercontent.com/3411842/92571930-b3a71100-f2be-11ea-82bb-9b45544e5837.png)

다른 경로 / 중복 파일명 존재:

![image](https://user-images.githubusercontent.com/3411842/92572045-db967480-f2be-11ea-977c-dcfa3e40f16f.png)
