### ISSUE TITLE
[Analyzer] 검색 결과 및 통계 결과가 최대500개만 보이는데, 결과 표시 화면에서 옵션을 통해 조정이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2562]
## 기능 요청 ##
- Analyzer 의 검색 결과, 통계 결과가 최대 500 개 입니다. 데이터의 특성에 따라 조절할 수 있어야 합니다.

- 실제 대부분의 데이터는 필터링을 해도 500 개 이상인 경우가 많습니다.

<img width="1198" alt="스크린샷 2020-08-20 오후 4 02 38" src="https://user-images.githubusercontent.com/5126497/90727991-2005a480-e2ff-11ea-841c-81e4726d8729.png">

- 특히 기계학습 모델(anomalies, outlier, forecasts) 의 데이터는 입력 데이터도 다 보이질 않습니다.그래서 결과 확인이 어렵습니다.

<img width="1101" alt="스크린샷 2020-08-20 오후 4 08 24" src="https://user-images.githubusercontent.com/5126497/90728178-6955f400-e2ff-11ea-8a01-347cc44513c4.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seoryjj** [comment]
9월7일 현재는 지난 500개 보다 더 적은 200개 개수 제한으로 필요한 작업에 어려움이 많습니다.
Anomalies, outlier, forecast 는 시각화결과와 통계 결과를 같이 봐야 하기 때문에 내보내기로 결과를 일일이 확인하는 게 어렵습니다. 

데이터 개수 설정은 저장없이( 로그아웃하면 자동으로 디폴트로 반영)
로그인할 때마다 사용자가 해당 세션에서 필요한 작업에 맞게 조정할 수 있는 기능이 있어야 합니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 개발 진행중으로 11/19 패치 예정입니다.
