### ISSUE TITLE
meta: 사용자 계정 ID를 _ 문자를 시작으로 생성 가능한 버그

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2563]
## 버그 설명 ##
meta: 사용자 계정 ID를 _ 문자를 시작으로 생성 가능한 버그

**Comment by veldise** [comment]
@lyj @SukYoungEun 

IWP 회원가입 기능에도 위 문제를 수정해주시기 바랍니다.

**Comment by sunghoon** [comment]
@lyj @SukYoungEun 최종 진행 상황 정보 공유 바랍니다.

**Comment by lyj** [comment]
@sunghoon 처리 완료되었으나 배포 되지 않았습니다.

**Comment by sunghoon** [comment]
혹시 아래 이슈와 연관된 사항이 있는지 확인 부탁드립니다.

@veldise @lyj @anhm 
https://github.com/mobigen/IRIS-BigData-Platform/issues/2074

**Comment by sunghoon** [comment]
@lyj 관련 내용을 담당자들과 확인 완료하였습니다. 

해당 기능을 배포를 QA 쪽에 요청해 주시기 바랍니다. 

@EricLeeMbg @big-mobigen 배포 적용 완료 후 결과를 알려 주시기 바랍니다.

**Comment by EricLeeMbg** [comment]
@sunghoon 테스트 후 배포 진행하겠습니다.
@lyj 해당 기능이 적용된 버전의 빌드정보 전달해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@EricLeeMbg @lyj 어떻게 진행되고 있나요?

**Comment by EricLeeMbg** [comment]
@sunghoon 금번 배포버전(10.8) 테스트 결과 아직 반영되지 않은 것을 확인하였습니다. 
@lyj 적용된 이미지 정보를 알려주시면 배포본을 다시 제작하여 테스트 하겠습니다.

**Comment by lyj** [comment]
해당 기능은 수정되었으나 IWP 배포 후 확인 가능합니다.

**Comment by EricLeeMbg** [comment]
@sunghoon 금번 배포(10.8-release)에 대한 테스트가 완료되어, 해당 기능은 차주 patch에 포함시켜 진행하겠습니다.

**Comment by sunghoon** [comment]
진행 계획이 수립되었으니 본 이슈는 닫도록 하겠습니다.
