### ISSUE TITLE
[Analyzer] 분석 결과가 없을 경우 화면이 깨지는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2564]
## 버그 설명 ##
아래 화면과 같이 검색 결과가 없는 상황에 화면이 깨집니다.
![image](https://user-images.githubusercontent.com/11566844/91153264-f5e72480-e6fa-11ea-9094-fb6eeecd4ba0.png)

**Comment by rhcpn** [comment]
@onlyeon 아래와 같이 하면 재현 가능 합니다.
1. 데이터 모델 목록에서 "IBP_ISSUE_LIST_2020_08_20" 선택
2. 쿼리 입력란에 "* | pivot count(*) SPLITROW 등록일 SPLITCOL 상태 | join RELEASE_LIST_2020_08_25 AS B 등록일 = B.날짜" 입력 후 결과보기

**Comment by onlyeon** [comment]
![스크린샷 2020-08-28 오전 10 49 45](https://user-images.githubusercontent.com/11944592/91530421-017a5b80-e946-11ea-9207-0d54907b8a80.png)

위 캡쳐와 같이 차트 영역 가운데에 위치할 수 있도록 수정했습니다.
IRIS-Design-System REPO에 올라가 있으며, 추후 배포에 반영될것으로 예상됩니다.
