### ISSUE TITLE
[Studio] 그래프와 입력받기 두가지로 조절하는 부분이 이상한 것 같습니다.

### ISSUE THREAD

**Issue by YusunPark** [mobigen/IRIS-BigData-Platform#2567]
## 버그 설명 ##

Studio 보고서 작성 화면에서 아래 사진과 같이 구현되어있는 조절 칸의 조작이 조금 이상한 것 같습니다.
 
![image](https://user-images.githubusercontent.com/59571464/91421181-90c53780-e890-11ea-841c-9d7cd35e8a2b.png)

### 환경

```
- http://b-iris.mobigen.com/
- window 10, chrome
- root 계정 
```

### 2. 이후 입력 받는 칸에 

```
Backspace 를 누르면 최대치의 '절반' 값 입력
[1] 초기상태 -> 50(절반)
[2] 50 -> 5 -> 50(절반)
[3] 100 -> 10 -> 1 -> 100(절반)

```

### [1] 초기값에서 `<-` 누를경우 중간 값 입력됨

![image](https://user-images.githubusercontent.com/59571464/91422265-e5b57d80-e891-11ea-85ab-a66c74e9cbe1.png)
![image](https://user-images.githubusercontent.com/59571464/91422280-ed752200-e891-11ea-8c35-a708e939ca6f.png)

---

### [2] [3] 1의 자리 숫자인 경우에  `<-` 누를경우 중간 값 입력됨

- [2]
![image](https://user-images.githubusercontent.com/59571464/91421807-590abf80-e891-11ea-9f42-c9c07ec2f675.png)
![image](https://user-images.githubusercontent.com/59571464/91421829-5f00a080-e891-11ea-9c30-fd4deceee786.png)
![image](https://user-images.githubusercontent.com/59571464/91421876-6d4ebc80-e891-11ea-8943-ae780da47808.png)

- [3]
[image](https://user-images.githubusercontent.com/59571464/91421901-73dd3400-e891-11ea-8714-87b1e8935c51.png)
![image](https://user-images.githubusercontent.com/59571464/91421944-7fc8f600-e891-11ea-8f7e-a5a4c84ad762.png)

## 예상한 행동 ##

- [1]번의 경우에는 아무일도 일어나지 않을 것이고
- [2], [3]번의 경우에는 '0' 이 입력될 것으로 예상했습니다.

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 확인하여 조치 바랍니다.
