### ISSUE TITLE
[Studio] 권한이 있는 DSMS 연결정보가 보이지 않습니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2568]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

전체 사용자 권한의 MYSQL 연결 정보가 Studio 에서 보이지 않습니다.
기존 생성한 보고서는 연결정보가 보이지 않아도 데이터는 가져옵니다만
새 보고서 또는 새 데이터객체에서는 연결정보 선택이 안되어서 데이터객체 생성이 안됩니다. 

- 연결 정보 mySQL_199 는 모든 사용자 권한을 주어서 8월21일까지(휴가전) 보고서를 만들고 있었습니다.
<img width="375" alt="스크린샷 2020-08-31 오전 9 34 46" src="https://user-images.githubusercontent.com/5126497/91673206-f7d33c80-eb6d-11ea-8126-d7fc2ded1493.png">

- 8월21일 생성하던 보고서에서  demo 계정으로 보고서를 생성하고 있었습니다.
- 휴가 다녀와서 보니 연결정보가 보이지 않습니다.

참고할 보고서 : EDU_mySql_사용예제_지도_이슈 
http://b-iris.mobigen.com:80/studio/exported/8c3a6744a69f4c8da9d60e4ee8ba1f67e4df4ca8f76c4a72a1c100ade7b2d5ef

<img width="201" alt="스크린샷 2020-08-31 오전 9 31 08" src="https://user-images.githubusercontent.com/5126497/91673267-497bc700-eb6e-11ea-9338-c7e4d81d5f2e.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm @jblim0125 
DSMS 가 구버전이 설치된 것 같습니다. 확인 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @jblim0125 @big-mobigen 관련 사항 어떻게 조치 되었나요?

**Comment by sunghoon** [comment]
장애 처리 된 것으로 보고 본 이슈는 닫습니다.
