### ISSUE TITLE
[Studio] 지도-마커의 깃발에서  깃발막대 밑부분이 아니라 깃발의 좌측위를 좌표로 표시하고 있습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2569]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

IRIS  지도에서 마커-깃발은 왼쪽 위 꼭지점이 좌표로 표시됩니다.  
원래는 깃발막대가 꽂히는 지점이 포인트 좌표와 일치해야 합니다.

- 마커 - 포인트&깃발로 표시한 강화터미널 정류장
<img width="233" alt="스크린샷 2020-08-31 오전 11 06 18" src="https://user-images.githubusercontent.com/5126497/91676205-01fb3800-eb7a-11ea-92cd-d6824c9a7422.png">

- 마커- 포인트만 표시한 경우
<img width="241" alt="스크린샷 2020-08-31 오전 11 06 05" src="https://user-images.githubusercontent.com/5126497/91676220-117a8100-eb7a-11ea-86ca-5b9d902ff173.png">

- 마커 - 깃발만 표시한 경우
<img width="213" alt="스크린샷 2020-08-31 오전 11 08 46" src="https://user-images.githubusercontent.com/5126497/91676317-63230b80-eb7a-11ea-9d91-ad59066349e7.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 개선인가요? 버그 같은데.

**Comment by sunghoon** [comment]
@seoryjj 해당 이슈를 수정 배포 하였습니다.  보고서를 못 찾았는데. 확인 후 특이 사항이 없다면 Close 부탁드립니다.

**Comment by seoryjj** [comment]
확인했습니다.
