### ISSUE TITLE
[DSL] Join 의 조건 구문을 and 로 여러 개가 가능하도록 기능 요청

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2570]
## 기능 요청 ##

- 현재  
JOIN  B모델  A모델.AA = B모델.AA

- 요청 예시
JOIN  B모델  A모델.AA = B모델.AA and  A모델.BB = B모델.BB and A모델.BB = '모비젠' and B모델.BB = '모비젠'

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seungfwani** [comment]
merge 명령어 배포 완료되어 닫습니다.
merge 명령어는 [명령어문서](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/index.html#command-references) 에서 확인 할 수 있습니다.

- `* | merge inner (fwani_joinB) as B1 on A = B1.A and B = B1.B`
![Screen Shot 2020-09-22 at 11 00 52 AM](https://user-images.githubusercontent.com/46172579/93837913-e2f84d80-fcc2-11ea-9e78-9ae8e4d95232.png)
