### ISSUE TITLE
[기능요청] 모델뷰에서 시작시간과 끝시간을 받아서 해당 데이터로만 DSL 을 수행하도록 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2571]
## 기능 요청 ##
모델 뷰 생성할 때

- 시간은 "전체 시간"
- DSL 은 stats 구문을 사용합니다.

이 모델뷰를 Studio, Analyzer 에서 조회 기간을 입력받은 후에, 해당 기간의 데이터에 대해 DSL 이 실행되는 기능이 필요합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by anhm** [comment]
해당 기능은 패치 예정이므로 이슈를 닫도록 하겠습니다.
