### ISSUE TITLE
[DSL]  stats의 함수중 iqr 결과 오류

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2573]
## 버그 설명 ##
 b-iris.mobigen.com  demo 계정

데이터모델 : EDU_INCHEON_BUS_COOR

순번 컬럼은 1 ~ 87 번 까지 있으며, 중간에 빠진 게 있어서 총 83개 가 있음.(31,32,56,57 이 빠짐)

`* 노선번호='1301' |  stats iqr(순번) as iqr_순번 , median(순번) as median_순번,   avg(순번) as 평균순번  by 노선ID`

iqr결과는  디폴트 0.25값으로
**최소값, 25%값 ,중간값, 75%값, 최대값**
이 결과로 나옵니다.
IQR = Q3 -  Q1 
이지만  이 값만 보여주면 안 될 것 같습니다.

결과로 나온 46 은 어디에서 나온 값인지 알 수 없네요.

- IRIS 에서 IQR, median, 평균을 구한 결과에서 median, 평균은 맞는 결과인데, IQR 결과 46은 무슨값인지 알 수 없습니다. 사분위값이 정수로만 나올 때의 문제도 있기 때문에 이 값을 그냥 사용하기 어렵습니다.
<img width="880" alt="스크린샷 2020-09-01 오전 10 36 17" src="https://user-images.githubusercontent.com/5126497/91784997-3c7ad880-ec3f-11ea-8385-f414e80cd017.png">

- R 의 IQR 결과  : 최소값, 25%값 ,중간값, 75%값, 최대값
<img width="290" alt="스크린샷 2020-09-01 오전 10 37 29" src="https://user-images.githubusercontent.com/5126497/91784969-253beb00-ec3f-11ea-8567-f94b006ee022.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 진행 상태 정보 공유 해 주세요.

**Comment by seungfwani** [comment]
해당 기능은 결과의 오류라고 하기 보다는 iqr 함수의 실행 결과를 보여주는 방식의 차이로 보입니다.

IRIS 에서는 iqr 의 결과로 iqr 계산 결과 하나를 반환하고 있으며,
최소값, 25%값 ,중간값, 75%값, 최대값 과 같은 값을 반환 할 수 있는 새로운 함수를 추가 할 예정입니다.

추가 후 사용방법의 예시 입니다.
```
quantile(컬럼, %값) -> 해당 % 의 결과값 반환
```

**Comment by sunghoon** [comment]
@seungfwani 위 내용을 참고하여 진행해 주시기 바랍니다.

**Comment by seoryjj** [comment]
IQR 을 계산하기 위해서 quantile 값을 구하는 방법이 여러 타입이 있습니다.(type 1 ~ type 7)
Spark 에서는 어떤 type 을 디폴트로 하는 지 봐야 겠지만, 이런 이유로 Q1, Q3 값을 같이 표시해줘야 사용에 혼동이 없을 겁니다.

그리고 IQR(IQR = Q3 - Q1 ) 은 그 자체만 사용하는 게 아니고,
lower limit  = Q1 - 1.5 * IQR,   upper limit = Q3 + 1.5 * IQR 
처럼 다른 quantile 값 Q1, Q3 와  같이 사용하는 게 일반적입니다.

그래서 iqr 함수, quantile 함수 등을  stats  에서 제공하는 함수로 사용 할 때, 여러 개의 값이 나오므로 필드이름을 정하는 규칙 등이 필요해보입니다.

예를 들어
`* |  stats quantile(A_column, 25)  as IQR_AA`

- 결과 : alias_Q숫자
IQR_AA_Q0, IQR_AA_Q25, IQR_AA_Q50, IQR_AA_Q75, IQR_AA_Q100

`* |  stats quantile(A_column, 25) ` 
- 결과 : 컬러명_Q숫자
A_column_Q0, A_column_Q25,A_column_Q50,A_column_Q75,A_column_Q100


`* |  stats quantile(A_column, 10) ` 
- 결과
A_column_Q0, A_column_Q10,A_column_Q20,A_column_Q30,,,,,,, A_column_Q100



`* |  stats iqr(A_column) as IQR_AA`
- 결과 : 결과는 Q1, Q3, IQR 을 표시
IQR_AA_Q25, IQR_AA_Q75, IQR_AA_IQR

`* |  stats iqr(A_column) `
- 결과 : 결과는 Q1, Q3, IQR 을 표시
A_column_Q25, A_column_Q75, A_column_IQR

**Comment by sunghoon** [comment]
@anhm @seungfwani 본 이슈와 관련된 진행 일정 정보를 공유 해 주세요.

**Comment by seungfwani** [comment]
quantile 함수 추가하였습니다.
12/17(목) 배포 예정

**Comment by seungfwani** [comment]
b-iris 에서 확인 완료 했습니다.
![Screen Shot 2020-12-18 at 1 19 17 PM](https://user-images.githubusercontent.com/46172579/102574242-a9a17380-4133-11eb-9b04-6c997ad8b0e4.png)
![Screen Shot 2020-12-18 at 1 19 08 PM](https://user-images.githubusercontent.com/46172579/102574245-ab6b3700-4133-11eb-8326-12df1b4fb1eb.png)
