### ISSUE TITLE
[Studio] 주기설정 위젯의 '다음 갱신까지 남은시간 표시' 텍스트가 정상 작동 하질 않습니다. 

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2574]
## 버그 설명 ##

Studio의 주기설정 위젯에서 
다음 갱신까지 남은 시간 표시를 체크 한 후 주기를 추가하게 되면
다음 갱신까지 00:00:00 이라고 표시가 됩니다. 

## 재현하는 방법 ##

동작을 재현하는 방법 :
1. b-iris -> Studio -> 새 보고서
2. 주기설정 위젯을 통해 주기설정 위젯 생성
3. 데이터 탭에서 "다음 갱신까지 남은 시간 표시" 체크
4. 1초로 설정해서 주기 추가
5. 10번 중 1번꼴로 "다음 갱신까지 00:00:01"이란 문구 대신 "다음 갱신까지 00:00:00" 이란 문구로 생성

> '분'일 경우 "다음 갱신까지 00:00:59" 라고 나옵니다. (마찬가지로 간헐적 발생)
> '시간'일 경우 "다음 갱신까지 00:59:59" 라고 나옵니다. (마찬가지로 간헐적 발생)

## 예상한 행동 ##

지정한 주기만큼 다음 갱신까지 남은 시간이 제대로 표시가 되어야 한다고 생각합니다.

1시간 이면 -> "다음 갱신까지 01:00:00"
1분이면 -> "다음 갱신까지 00:01:00"
1초면 -> "다음 갱신까지 00:00:01"

## 스크린샷 ##

00:00:00 으로 표기 되는 상황

![스크린샷 2020-09-01 오후 1 24 46](https://user-images.githubusercontent.com/57122180/91795218-07c74b00-ec58-11ea-804c-7f620b437ff4.png)

예상한 시간 표기

![스크린샷 2020-09-01 오후 1 24 56](https://user-images.githubusercontent.com/57122180/91795222-0b5ad200-ec58-11ea-81c3-2b8c4d348972.png)

1시간으로 설정했을 때의 에러

![스크린샷 2020-09-01 오후 1 33 13](https://user-images.githubusercontent.com/57122180/91795225-0c8bff00-ec58-11ea-9c5a-c88702403e5d.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##

생성페이지 또는 수정페이지에서 "다음 갱신까지 00:59:59"라고 뜨는 상태일 때 저장을 한 후
보고서 수정이 아닌 열람으로 들어가보면 "다음 갱신까지 01:00:00" 에서 1초씩 줄어드는 것을 볼 수 있었습니다.

**Comment by sunghoon** [comment]
@veldise 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
금주(11/12) 패치 예정입니다.
