### ISSUE TITLE
[관리] : 사용자 관리 페이지에서 접근성이 조금 더 높아졌으면 좋겠습니다.

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2575]
## 기능 요청 ##

사용자 관리에서 사용자를 클릭할 시 생기는 박스를 없애는 방법이 너무 한정적이라고 생각합니다.
현재 사용자 관리에서 사용자 상세 보기 기능을 하는 우측 상단에 생성되는 박스를 없애는 방식이 
기존에 눌렀던 사용자를 다시 눌러야 없어지는데 이 방법 말고는 현재 페이지에서 박스를 없애는 방법이 없습니다.
박스가 뜨게 되면 페이지네이션 요소와 사용자 계정 추가, 사용자 관리 버튼이 모두 가려져서 불편합니다.

## 원하는 솔루션 설명 ##

여타 사이트의 모달창처럼 화면의 다른 요소를 클릭하면 사라지는 방식이거나
박스에 x 버튼과 같은 닫기 기능의 버튼이 있다면 훨씬 편할 것 같습니다.

## 고려한 다른 대안 ##

박스안에 작은 텍스트로 없애는 방법을 설명해 놓는 것도 좋을 것 같습니다.
같은 이름을 다시 눌러야 없어지는 걸 몰라서 처음에 조금 헤맸습니다.

## 기타 ##

![스크린샷 2020-09-01 오후 3 57 50](https://user-images.githubusercontent.com/57122180/91812937-d9a03600-ec6c-11ea-9dd3-789b0ad47187.png)

**Comment by veldise** [comment]
#2443

**Comment by sunghoon** [comment]
@eumminsun 기능 검토 바랍니다.

**Comment by eumminsun** [comment]
https://github.com/mobigen/IRIS/issues/30

**Comment by sunghoon** [comment]
연결 페이지가 Close 되어 닫습니다.
