### ISSUE TITLE
[iris.tools 의 갤러리] 차계부

### ISSUE THREAD

**Issue by tessekim** [mobigen/IRIS-BigData-Platform#2578]
## 버그 설명 ##
최근정보 화면이 맨처음 들어가면 아래와 같이 에러발생.
두번째 들어가면 괜찮음.
![이미지 2020  9  2  오후 2 51](https://user-images.githubusercontent.com/3468426/91937682-67dbf100-ed2d-11ea-90ff-b8b6065d99ae.jpeg)

**Comment by sunghoon** [comment]
@veldise @seungfwani 원인 분석하여 조치 바랍니다. discovery에서 먼저 확인해 주세요.

**Comment by seungfwani** [comment]
들어오는 쿼리가 정상적이지 않습니다.
where 명령어의 쿼리를 보시면 `where date >=  and date <= ''` date 의 비교값이 없습니다.

```
model name = 'REFUEL_LOG' model_owner = paru | where date >=  and date <= ''     | stats sum(amount) as 주유량, sum(price) as 비용 by plateno  | round 2
```

----------------------
데이터 모델 쿼리를 작성한 곳을 보면 아래와 같습니다
데이터가 제대로 들어가지 않는 것으로 보입니다.
```
*

{# ------------------------------------------- #}
{# 조회 기간 #}
| where date >= '${SEARCH_DATE_BEGIN}' and date <= '${SEARCH_DATE_FINISH}'
... (생략) ...
```

**Comment by sunghoon** [comment]
@veldise 해당 보고서에서 '최근정보'를 처음 처리할때는 위와 같은 오류가 발행하며, 이후 다른 탭으로 클릭후 재방문 하면 정상 처리됩니다.
관련 내용을 확인하여 공유해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
확인 결과 보고서 작성 오류로 판단됩니다.

에러가 발생하는 데이터 객체의 실행 설정은 아래와 같이 Check&Radio 객체로 되어있습니다.

![image](https://user-images.githubusercontent.com/3411842/95030479-f8ba3980-06ea-11eb-97be-44d44f2b48f5.png)

그런데 문제가 발생하는 `TERM_DATE_BEGIN` 변수 값은 실행시점에 비어있는데,
해당 변수값을 가지는 Input 객체는 Text-convertor(hidden) 객체의 이벤트가 트리거되어야 값이 설정됩니다.
그런데 Text-Convertor(hidden) 객체의 트리거 조건으로 Check&Radio 객체가 되어있습니다.

![image](https://user-images.githubusercontent.com/3411842/95030509-420a8900-06eb-11eb-9a73-1453b495418a.png)

Check&Radio -> Common-data
Check&Radio -> Text-convertor -> Input

이렇게 되면 Input 변수의 값이 설정되기 전에 Common-data 가 실행되므로, Common-data 가 참조하는 Input 변수값이 비어있을 수 밖에 없습니다.

Check&Radio 나 Tab 이벤트가 발생하였을 때 Input 이 아닌 Text-convertor 에서 참조할 변수값을 설정하고,
이를 Common-data가 참조하도록 보고서를 수정해야 합니다.

**Comment by sunghoon** [comment]
@veldise 기존에 동작하던 보고서인데 최근 업그레이드 관련 이슈로 보였습니다. 일단 기존 담당자에게 위 내용을 참고하여 수정을 요청해 보겠습니다.

@shinwoonsun 위 내용을 참고하여 해당 보고서 확인해 보시면 될 것 같습니다.
