### ISSUE TITLE
[DSL] scaler 명령어의 옵션 중 standard 의 결과가 이상합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2579]
## 버그 설명 ##
b-iris.mobigen.com  demo 

- scaler 메뉴얼에서 standard 옵션의 결과
<img width="1040" alt="스크린샷 2020-09-02 오후 3 38 08" src="https://user-images.githubusercontent.com/5126497/91941057-8a710880-ed33-11ea-919e-db96d46118c0.png">

- standard scaler 는 통상 평균에 해당하는 값이 0,  표준편차 1 인 값으로 변경합니다.
- python sklearn 패키지에서 제공하는 c, d 컬럼의 standardScaler  결과는

<img width="517" alt="스크린샷 2020-09-02 오후 3 45 12" src="https://user-images.githubusercontent.com/5126497/91940947-4bdb4e00-ed33-11ea-9dcf-d22d7e7b1d70.png">

로 나옵니다.

 
manual 의  standard scaling 은 어떤 공식을 사용했나요?

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by jheok318** [comment]
scaler의 동작이 다른 것이 아니라 pyspark의 standard scaler option 중 withMean option이 False로 되어있어 발생하는 문제로 보입니다.

참고로 sklearn의 default는 with_mean = True, with_std=True이고 pyspark은 withMean=False, withStd=True입니다.

[참고]
----------
현재 scaler 명령어중 standardScaler 부분에서 withMean의 default 값이 False로 설정이 되어있었습니다.

![](https://i.stack.imgur.com/Yr42l.png)

withMean을 False로 설정하게 되면 μ의 값을 0으로 설정하게 되며 True로 설정할 시 μ에는 실제로 대입한 값이 반영됩니다.
https://stackoverflow.com/questions/57349987/standardscaler-difference-between-with-std-false-or-true-and-with-mean-false

현재 manual에는 withMean의 값에 False를 이용하는 공식을 사용하였습니다.

**Comment by seungfwani** [comment]
수정 완료되었습니다.

![Screen Shot 2021-01-18 at 9 50 03 AM](https://user-images.githubusercontent.com/46172579/104861273-8b1cdb00-5972-11eb-9528-07e076c269f1.png)
![Screen Shot 2021-01-18 at 9 50 39 AM](https://user-images.githubusercontent.com/46172579/104861295-9ff96e80-5972-11eb-9c94-4f4d578de8e9.png)
