### ISSUE TITLE
[Studio] 보고서 목록에서 수정일 시간이 맞지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2581]
## 버그 설명 ##
b-iris.mobigen.com demo계정

- Studio 의 보고서 목록에서 방금 저장(09/03 14:20 분 경) 한 보고서의 시간이 맞지 않습니다.

<img width="1312" alt="스크린샷 2020-09-03 오후 2 29 35" src="https://user-images.githubusercontent.com/5126497/92074970-67f1f480-edf2-11ea-8482-3cfbdd68d7be.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@jblim0125 
보고서를 저장할 때 수정일은 서버 시간을 기준으로 합니다. 서버 시간 설정(timezone 등)에 문제가 있는 것 같습니다. 확인 바랍니다.
