### ISSUE TITLE
[Studio] DSMS 연결정보 조회 안됨

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2582]
## 버그 설명 ##
연결정보에서는 목록을 볼 수 있는데 Studio DSMS 선택 후 연결정보 목록이 아무것도 안나옵니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/92075832-48f46200-edf4-11ea-8985-97da3e067958.png)

![image](https://user-images.githubusercontent.com/7067615/92075739-18acc380-edf4-11ea-9f3d-8be9d3e6cff9.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm @jblim0125 
DSMS 버전이 낮아서 발생하는 문제입니다.

**Comment by sunghoon** [comment]
@anhm @jblim0125 빠른 장애 대응 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise #2630 이슈와 같은 상황인것 같습니다. 빠른 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
위에 제가 달아둔 댓글과 같이 #2568 과 동일한 이슈입니다. 현재는 잘 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/94209696-e16b9700-ff07-11ea-8869-d339f193b9a7.png)

**Comment by sunghoon** [comment]
@veldise 지금 잘 되는 상황은 장애 대응을 통해서 문제가 해결된것 같아보이며 #2630 를 참고하여 이야기 된 방안으로 최종 문제 해결을 위한 계획을 제시해 주시기 바랍니다.

**Comment by sunghoon** [comment]
장애 처리가 된 것으로 보고 본 이슈는 닫겠습니다.
