### ISSUE TITLE
Studio: 날짜&시간 / 객체 초기값을 변수/트리거로 설정하는 기능

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2584]
## 기능 요청 ##
Studio: 날짜&시간 / 객체 초기값을 변수/트리거로 설정하는 기능

## 기타 ##
![image](https://user-images.githubusercontent.com/3411842/92082264-40edef80-edff-11ea-983d-83d924ec65c7.png)

**Comment by sunghoon** [comment]
@veldise @swish1995 일정대로 진행되나요?

**Comment by veldise** [comment]
@sunghoon 
네, 10월 8일 패치 예정입니다.
