### ISSUE TITLE
Studio: 기간 설정 / 객체 초기값을 변수/트리거로 설정하는 기능

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2585]
## 기능 요청 ##
Studio: 기간 설정 / 객체 초기값을 변수/트리거로 설정하는 기능

## 기타 ##
![image](https://user-images.githubusercontent.com/3411842/92082264-40edef80-edff-11ea-983d-83d924ec65c7.png)

**Comment by sunghoon** [comment]
@veldise @hyun-jii 일정대로 진행되나요?

**Comment by veldise** [comment]
@sunghoon 
10월 8일 개발 완료를 목표로 하고 있습니다. QA에 따라 패치 일정과는 다를 수 있습니다.

**Comment by veldise** [comment]
금일 패치로 기능이 추가되었습니다.
"기간 설정 테스트" 보고서에서 확인할 수 있습니다.
