### ISSUE TITLE
Studio: Chart / 분석 템플릿 불러오기 기능 재개발

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2586]
## 기능 요청 ##
Studio: Chart / 분석 템플릿 불러오기 기능 재개발

## 기타 ##
![image](https://user-images.githubusercontent.com/3411842/92082533-a510b380-edff-11ea-819d-207d564c8e5e.png)

**Comment by sunghoon** [comment]
@veldise 10.08일 일정으로 진행 되나요?

**Comment by veldise** [comment]
@sunghoon 
네, 제가 마일스톤을 아직 갱신하지 않았습니다. 수정하겠습니다.

**Comment by sunghoon** [comment]
확인되어 닫습니다.
