### ISSUE TITLE
Studio: Chart / 히트맵 유형 - 셀 클릭시 변수값을 차트 기준으로 설정 가능한 기능

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2587]
## 기능 요청 ##
Studio: Chart / 히트맵 유형 - 셀 클릭시 변수값을 차트 기준으로 설정 가능한 기능

## 기타 ##
![image](https://user-images.githubusercontent.com/3411842/92082698-dab59c80-edff-11ea-9225-b059a84b486a.png)

**Comment by sunghoon** [comment]
@veldise @swish1995 일정대로 진행 되나요?

**Comment by veldise** [comment]
@sunghoon 
네 일정대로 개발 진행중입니다.
