### ISSUE TITLE
Studio: 변수 값(텍스트)의 길이가 길 경우, 전체 값을 확인할 수 있는 방법 제공

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2588]
## 기능 요청 ##
Studio: 변수 값(텍스트)의 길이가 길 경우, 전체 값을 확인할 수 있는 방법 제공

**Comment by sunghoon** [comment]
@veldise 일정되로 진행 되나요?

**Comment by veldise** [comment]
@sunghoon 
이 개발 항목도 10월 8일까지는 어렵습니다. 마일스톤을 변경하는게 좋을까요?

**Comment by sunghoon** [comment]
@veldise 업무량 파악 하여 차선 일정 계획을 알려주세요.

**Comment by veldise** [comment]
@sunghoon 
개발 완료되었고 10.29 패치 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/96970115-2a862980-154e-11eb-9e2c-3b117d6868be.png)

**Comment by sunghoon** [comment]
@sunghoon 
json format 인데 format에 맞게 이쁘게 출력해 주면 더 좋지 않았을까 하는 아쉬움이 있습니다. 
https://github.com/center-key/pretty-print-json

**Comment by sunghoon** [comment]
@veldise 배포 된 것으로 보면 되나요?

**Comment by veldise** [comment]
아래와 같이 패치되었습니다.

![image](https://user-images.githubusercontent.com/3411842/97540610-374fc500-1a07-11eb-9c2e-a58ff64c11aa.png)
