### ISSUE TITLE
[서초구청] Studio: 테이블 선택 행 표시 색상

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2591]
## 버그 설명 ##
이번 패치에 테이블 선택 행에 대한 Highlight 기능이 추가되었습니다.
해당 기능 확인했는데 테이블 행자체가 알록달록이라 가능하면 선택된 행을 좀더 명확한 색으로 처리가 됐으면 합니다.(밝은 노란색 등)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/92186951-557bc780-ee93-11ea-9ba4-f5a446ba9b28.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
해당 부분은 아무래도 범용으로 사용되는 IRIS 특성상 범용 컬러를 지정하다 보니 약간 심심하게 보일 수도 있습니다. 
추후 스타일 관련 기능을 지속적으로 추가하여 해당 속성도 수정할 수 있는 방향으로 진행할 예정입니다. 
따라서.. 현시점에는 제안하신 색상으로 수정하기는 어려울 것 같습니다. 양해 부탁 드립니다.
