### ISSUE TITLE
[서초구청] Studio: Map - 히트맵 가중치 적용

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2592]
## 버그 설명 ##
이번에 신규로 추가된 Map-히트맵을 시험해보고 있는데 가중치를 적용해도 모든 색상이 동일하게 보입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
빨간색 동그라미 친 부분이 방배1동 919-1:PM100A-24 인데 주변 색상과 비교해보면 동일한것처럼 보임.
![image](https://user-images.githubusercontent.com/7067615/92187577-1ea6b100-ee95-11ea-91e2-4892725ea693.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by swish1995** [comment]
@veldist 직접 설명 드렸지만 여기에 정리하도록 하겠습니다.

가중치는 시각화 옵션 -> 히트맵 -> 최대 가중치를 설정할수 있습니다.
해당 지도는 최대 가중치가 1로 설정되어 있어 1이상의 가중치를 가진 영역은 동일한 세기(영향)으로 처리되므로 같이 나오는게 맞습니다.
최대 가중치는 소숫점까지 입력이 가능하므로 값을 조정하여 원하는 형태의 열지도가 나오도록 설정할수 있습니다.

또한 색상 -> 임계치 에서 각 값들은 0 ~ 1 사이의 값을 입력해야 정상 동작하며 해당 내용은 히트맵일때 툴팁에 포함되어 있습니다.

@SONHOJUN 확인해보시고 코멘트 바랍니다.
