### ISSUE TITLE
[Discovery] 파일브라우저 에서 HDFS 로 파일 업로드시 에러납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2593]
## 버그 설명 ##
b-iris.mobigen.com demo

- 50 %  에서 error 발생
<img width="447" alt="스크린샷 2020-09-04 오후 2 04 26" src="https://user-images.githubusercontent.com/5126497/92201669-1dd34680-eeb8-11ea-8d19-f8afe4ccf6bc.png">

- hdfs 
<img width="631" alt="스크린샷 2020-09-04 오후 2 06 25" src="https://user-images.githubusercontent.com/5126497/92201758-4f4c1200-eeb8-11ea-9afd-0225942a2145.png">

- 참고로 MINIO 는 같은 csv 파일이 정상 업로드되었습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@jblim0125 
hdfs-browser container 내부에서 `gcs5`와 같은 hostname 을 찾지 못하고 있는 것 같습니다.

`Error: getaddrinfo ENOTFOUND gcs5 gcs5:50075`

**Comment by jblim0125** [comment]
k8s 환경으로 이전하면서 변경되었어야 할 설정들이 반영되지 못하였습니다.  
> 변경 사항 
 /etc/hosts Local file mount  삭제
HostAliases로 파드의 /etc/hosts 에 hadoop 클러스터 정보 추가  

파일 업/다운로드 동작 확인하였습니다.

**Comment by sunghoon** [comment]
@jblim0125 최종 진행 상황을 공유 해 주세요.

**Comment by jblim0125** [comment]
hdfs-browser에 hadoop hosts 정보를 추가하여 다음과 같이 정상적으로 업로드 되고 있습니다.

![image](https://user-images.githubusercontent.com/6268831/94228672-7090a300-ff38-11ea-9d7b-f9691e8fd6cb.png)

**Comment by sunghoon** [comment]
닫겠습니다.
