### ISSUE TITLE
Analyzer: 시각화 / UI 깨짐

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2595]
## 버그 설명 ##
Analyzer: 시각화 / UI 깨짐

### 필터 > 삭제 아이콘 오류
![image](https://user-images.githubusercontent.com/3411842/92349396-e90dfc00-f110-11ea-8d0a-aedeebcb89e8.png)

### 꺾은선 / 막대 / ... > 그룹을 제외한 UI가 다른 UI와 겹침
![image](https://user-images.githubusercontent.com/3411842/92349427-fb883580-f110-11ea-9377-046abdac43a8.png)

**Comment by ohmy04180** [comment]
안녕하세요! 오민영입니다. 
꺾은선 / 막대 / ... > 그룹을 제외한 UI가 다른 UI와 겹치는 부분 수정하였습니다.
*** 주석 09-07으로 확인 가능합니다.**

변경된 페이지
/views/sherman/adv.html
변경된 스타일 경로
/assets/css/sherman/style.min.css

**Comment by ohmy04180** [comment]
안녕하세요! 오민영입니다.
 꺾은선 / 막대 / ... > 그룹을 제외한 UI가 다른 UI와 겹치는 부분 수정하였습니다.
 ** 주석 09-07으로 확인 가능합니다.**

변경된 페이지 /views/sherman/adv.html 
변경된 스타일 경로 /assets/css/sherman/style.min.css
