### ISSUE TITLE
[Discovery] DSL 의 stats 에서 함수 first, last 는 조회할 때 마다 값이 달라집니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2597]
## 버그 설명 ##

b-iris.mobigen.com demo 계정

- 데이터모델 : EDU_DATA_iris 
- 검색어 
`* Species='setosa' | fields Sepal_Width,Species |  sort  Sepal_Width | stats first(Sepal_Width), last(Sepal_Width)  by Species`

- 같은 검색어, 모델로 3번 실행한 결과가 모두 다릅니다.
<img width="978" alt="스크린샷 2020-09-07 오후 4 04 04" src="https://user-images.githubusercontent.com/5126497/92358229-2cbe3100-f124-11ea-8421-68fe4511af53.png">

<img width="730" alt="스크린샷 2020-09-07 오후 4 04 10" src="https://user-images.githubusercontent.com/5126497/92358234-2e87f480-f124-11ea-9644-1e4874f43444.png">

<img width="664" alt="스크린샷 2020-09-07 오후 4 07 45" src="https://user-images.githubusercontent.com/5126497/92358357-55dec180-f124-11ea-8bf3-c24d7322f94a.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
- stats 에서 by 를 뺀 경우에도 다른 값이 나옵니다.
<img width="804" alt="스크린샷 2020-09-07 오후 4 22 11" src="https://user-images.githubusercontent.com/5126497/92359545-655f0a00-f126-11ea-8e66-6f23038e37c3.png">

<img width="889" alt="스크린샷 2020-09-07 오후 4 22 19" src="https://user-images.githubusercontent.com/5126497/92359553-6859fa80-f126-11ea-8765-b5b17f3d35b6.png">

**Comment by seungfwani** [comment]
아래  내용을 참고해서 수정 및 검증에 활용하시기 바랍니다

---------------------------------------------


# 시험 - 2020.09.09 stats/pivot

## 이슈

1. stats 의 stdev  , stdevp 결과 뒤바뀜
2. stats, pivot 에서 통계함수안에 필드이름은 대소문자 구분없으나  ::pivot::  은 파라미터에 사용하는 필드이름은 exact match ,  ::stats:: 는 대소문자구분 없음
3. 날짜 집계를 위해 사용하는  date_group 함수를 사용시에 stats 는 작은 따옴표 없이, pivot 은 작은 따옴표를 넣어야 동작함
4. fisrt, last 함수의 결과가 실행할 때 마다 다른 결과가 나옴
5. stats, pivot 의 통계함수 중 동일한 기능인데 이름이 다르므로 통일이 필요합니다.
	1. stdev vs. stddev  
	2. distinct_count vs. countDistinct


## 시험 데이터 모델
* 시험 환경  b-iris.mobigen.com 
* 데이터모델 : EDU_DATA_iris ( 150건 )  DATETIME 없음
* 데이터모델 : EDU_SYSLOG_2020_0325_09 ( 37940 건 )  / 전체 기간으로 조회



## stats 시험
IRIS ( 2020.09.09 시험 )


### 데이터 모델  : EDU_DATA_iris

* avg, stdev, stdevp, min, max, median, sum, var ( stdev, stdevp 이슈 )


```
    *  | stats count(*) as 개수,  avg(sepal_width) as 평균_sepal_width,
               stdev(sepal_width) as 표준편차_sepal_width,
               stdevp(sepal_width) as 모표준편차_sepal_width,
               min(sepal_width) as 최소값_sepal_width, max(sepal_width) as 최대값_sepal_width ,
               median(sepal_width) as 중간값_epal_width,  sum(sepal_width) as 합계_sepal_width,  var(sepal_width) as 분산_sepal_width
        by  species |  sort species
```

![DD232167-70DA-4073-B02A-209E9FC2DF8C](https://user-images.githubusercontent.com/5126497/92564527-468e7e00-f2b4-11ea-93cf-eba68ab8f301.png)




::2020.09.09 현재는 **stdev, stdevp 가 바뀌어서 출력** 되고 있습니다. R 의 결과와 꼭 확인하세요 !!!::


  R 의 결과  -  STDEV_P 가 "모표준편차" 

![0A5556B7-E4B2-4BE9-BFB8-20DC8CA29795](https://user-images.githubusercontent.com/5126497/92564587-5c03a800-f2b4-11ea-96e6-5a43c36f4e51.png)



* iqr  (현재 버전 OK)

```
    * | stats iqr(Sepal_Width)  as IQR_Sepal_Width by Species | sort Species
```

![7A8957DA-B77D-46A7-97B0-3C2A660A1572](https://user-images.githubusercontent.com/5126497/92564616-6a51c400-f2b4-11ea-922e-500006bab284.png)


   R 의 결과 : R 에서 IQR 구하는 방법은 데이터에 따라 7개입니다. IRIS 는 그중  **Type 1**  결과와 비교하세요. 
   참고로 R, matlab 의 디폴트 IQR 은 Type 7 , SAS 는 Type 3 입니다. 

![0300BEE3-EF02-42A7-AA25-86F11A31DC58](https://user-images.githubusercontent.com/5126497/92564635-7178d200-f2b4-11ea-9124-9f66a4385082.png)





### 데이터모델 EDU_SYSLOG_2020_0325_09***

* 시간데이터로 집계하기 (OK)

```
    * | where HOST = 'hadoop01' and LEVEL = 'notice'  
      | stats count(*) as CNT by date_group(DATETIME, "10M"), HOST  
      | sort dategroup, HOST
```


![84303D3C-5676-44A5-983A-C99F34F020DA](https://user-images.githubusercontent.com/5126497/92564663-7c336700-f2b4-11ea-9f7c-4c1ede430b70.png)



R의 결과

![F9D093E9-8E78-447A-80FB-6E19C05CF357](https://user-images.githubusercontent.com/5126497/92564727-966d4500-f2b4-11ea-84ea-42a4f85291ab.png)



*  중첩 stats


```
    * | where HOST = 'hadoop01'   
      | stats count(*) as CNT by date_group(DATETIME, "10M"), HOST,LEVEL  | sort dategroup, HOST,LEVEL 
      | stats avg(CNT) as 평균개수 by dategroup,  HOST | sort dategroup
```

![1CDC4468-69A2-468F-A3B8-BCB334BB827E](https://user-images.githubusercontent.com/5126497/92564742-9f5e1680-f2b4-11ea-977d-0d3761ac1d6b.png)







_계속 추가될 예정입니다._

by https://github.com/mobigen/IRIS-BigData-Platform/issues/2596#issuecomment-689348531

**Comment by seungfwani** [comment]
pivot 은 R 과 동일한 결과( median 은 제외 :  여러 type 이 있어서 다를 수 있음) 가 나옵니다.  코드 수정 후 아래 검색어 구문으로 실행한 결과와 같으면 됩니다.

-------------------------------------------------------------------------

## pivot 시험

### 데이터모델 : EDU_DATA_iris

* pivot      SPLITROW     SORTROW

```
*  | pivot count(*) as 개수,
           avg(sepal_width) as 평균_sepal_width,
           stddev(sepal_width) as 표준편차_sepal_width,
           min(sepal_width) as 최소값_sepal_width,
           max(sepal_width) as 최대값_sepal_width,
           median(sepal_width) as 중간값_epal_width,
           sum(sepal_width) as 합계_sepal_width
     SPLITROW Species SORTROW desc
```

<img width="1029" alt="스크린샷 2020-09-09 오후 1 29 29" src="https://user-images.githubusercontent.com/5126497/92565083-1bf0f500-f2b5-11ea-9902-bcf4bc775fe4.png">

 
R 결과와 일치 : OK


* pivot     SPLITROW   date_group ....    SORTROW
```
* | where HOST like 'hadoop%'    | pivot count(*) SPLITROW 'date_group("DATETIME", "10M")',HOST  SORTROW  asc
```

![28E7F15A-8061-4BBE-ADE7-F5C1CA5AD0CF](https://user-images.githubusercontent.com/5126497/92565141-2e6b2e80-f2b5-11ea-84c3-c3a52ec2f521.png)



R 결과와 일치


* pivot  countDistinct   SPLITROW   SORTROW

```
* | pivot countDistinct(LEVEL) as D_LEVEL개수 SPLITROW HOST SORTROW asc
```
<img width="389" alt="스크린샷 2020-09-09 오후 1 44 26" src="https://user-images.githubusercontent.com/5126497/92565208-3dea7780-f2b5-11ea-8215-469f7a6e45df.png">




* pivot   ..  SPLITROW  date_group   SPLITCOL    SORTROW    SORTCOL    |    calculate  

```
* | where HOST  like 'hadoop%' | pivot count(*) as 개수 SPLITROW 'date_group("DATETIME", "10M")',HOST   SPLITCOL LEVEL SORTROW asc  SORTCOL asc  |  calculate add row as CNT
```
<img width="877" alt="스크린샷 2020-09-09 오후 2 04 45" src="https://user-images.githubusercontent.com/5126497/92565236-48a50c80-f2b5-11ea-95eb-fc7028f004ef.png">




### 데이터모델 :  EDU_DATA_iris

* pivot  ...   SPLITROW  SORTROW

```
*  | pivot count(*) as 개수,
           avg(sepal_width) as 평균_sepal_width,
           stddev(sepal_width) as 표준편차_sepal_width,
           min(sepal_width) as 최소값_sepal_width,
           max(sepal_width) as 최대값_sepal_width,
           median(sepal_width) as 중간값_epal_width,
           sum(sepal_width) as 합계_sepal_width
     SPLITROW Species SORTROW desc
```
<img width="1040" alt="스크린샷 2020-09-09 오후 2 06 43" src="https://user-images.githubusercontent.com/5126497/92565268-565a9200-f2b5-11ea-8e15-2fe35464b2b3.png">




### 데이터모델 :  EDU_Beijing_air_2013_2017_18

```
* |  pivot  count(*) as 풍향_CNT  SPLITROW station SPLITCOL wd SORTROW asc SORTCOL asc 
```
<img width="1226" alt="스크린샷 2020-09-09 오후 2 15 17" src="https://user-images.githubusercontent.com/5126497/92565395-886bf400-f2b5-11ea-99b6-681d132d5526.png">



```
* |  where station = 'Changping'  |  pivot  count(*) as 풍향_CNT  SPLITROW station, month  SPLITCOL wd SORTROW asc SORTCOL desc 
```

<img width="1199" alt="스크린샷 2020-09-09 오후 2 22 18" src="https://user-images.githubusercontent.com/5126497/92565425-93bf1f80-f2b5-11ea-9bf9-ac9a00fe8366.png">



```
* |  where station = 'Changping'  and PM2_5 is null
```
=> 31 개 row   / 1461


```
* |  where station = 'Changping'  |  pivot count(*) as 개수, avg(PM2_5) as 평균PM2_5 , stddev(PM2_5) as 표준편차PM2_5,  min(PM2_5) as 최소값PM2_5,
           max(PM2_5) as 최대값PM2_5,
           median(PM2_5) as 중간값PM2_5,
           sum(PM2_5) as 합계PM2_5  SPLITROW station,month SORTROW asc
```

<img width="1072" alt="스크린샷 2020-09-09 오후 2 30 25" src="https://user-images.githubusercontent.com/5126497/92565484-acc7d080-f2b5-11ea-8589-c2911c7ad150.png">




R 의 결과  :   중간값(median) 이 다름 . 이유는  quantile 구하는 방식의 차이로 다르게 나올 수 있습니다. 
<img width="856" alt="스크린샷 2020-09-09 오후 2 37 30" src="https://user-images.githubusercontent.com/5126497/92565565-d08b1680-f2b5-11ea-821a-cd62845a959d.png">

 

```
* |  where station = 'Changping'  
  |  fillna PM2_5 0 
  | pivot count(*) as 개수, avg(PM2_5) as 평균PM2_5 , stddev(PM2_5) as 표준편차PM2_5,  min(PM2_5) as 최소값PM2_5,
           max(PM2_5) as 최대값PM2_5,
           median(PM2_5) as 중간값PM2_5,
           sum(PM2_5) as 합계PM2_5  SPLITROW station,month SORTROW asc

```
<img width="1111" alt="스크린샷 2020-09-09 오후 2 47 02" src="https://user-images.githubusercontent.com/5126497/92565592-da147e80-f2b5-11ea-810d-78f493eeb60c.png">



by https://github.com/mobigen/IRIS-BigData-Platform/issues/2596#issuecomment-689354030

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 정보를 알려주세요.

**Comment by seungfwani** [comment]
first, last 함수는 클러스터 구성에 따라 결과가 제대로 나오지 않는 경우가 있기 때문에
삭제를 하도록 하겠습니다.

앞으로는 first, last 함수를 사용 할 수 없습니다
