### ISSUE TITLE
[Analyzer] 막대그래프의 시간 및 정보가 맞지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2598]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 데이터모델 : EDU_SYSLOG_2020_0325_09
- 데이터 개수 : 37940
- 데이터 시간 : 2020.03.25 09:00 ~ 10:00 1시간 동안의  syslog  데이터

- 전체 기간으로 조회했을 때 막대 그래프 : 막대 1개만 보이고, 해당 막대의 시간이 09:04:00 가 37940 개로 표시됩니다.
<img width="1217" alt="스크린샷 2020-09-07 오후 4 52 57" src="https://user-images.githubusercontent.com/5126497/92363032-d1903c80-f12b-11ea-8054-e8e0a0be1bd0.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
현재 버전에서는 '전체시간'으로 시간 범위를 설정하면, 시계열 트랜드(막대 그래프)를 그리기 위한 데이터를 1일 단위로 요청하기 때문입니다.
날짜를 설정하면 아래와 같이 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/92419921-52424d80-f1ab-11ea-8e8c-b1012662030a.png)

**Comment by seoryjj** [comment]
전체 기간 검색 후 막대를 선택하고 "이 범위로 검색" 을 하면 막대에 표시된  "2020-03-25 09:04:00 ~ 09:04:01" 시간의  데이터만 표시됩니다.

<img width="1065" alt="스크린샷 2020-09-08 오전 9 07 42" src="https://user-images.githubusercontent.com/5126497/92421282-c3d1ca00-f1b2-11ea-9444-80ce828b60a9.png">

전체 기간 조회 후 막대가 하나로 나올 때 시간 정보는 2020-03-25 00:00:00 ~ 2020-03-25 23:59:59 처럼 보여줄 수 있나요?

**Comment by veldise** [comment]
@seoryjj 
웹 UI 에서는 '전체시간'으로 설정했을때, 데이터의 시간 범위 정보를 알 방법이 없습니다. 따라서 불가능합니다.
