### ISSUE TITLE
[Discovery] DSL stats 와 pivot 에서 사용하는 함수 이름 통일

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2599]
## 기능 요청 ##

stats, pivot 에서 사용하는 함수는 avg, min, max, sum,,, 대부분 겹칩니다.

그 중에서 동일한 기능을 하는 2개 함수의 이름이 달라 혼동되면서 자주 에러를 발생시키고 있습니다.

- 표준편차 :  stdev ( stats ),   stddev ( pivot)
- distinct count  : distinct_count ( stats ),  countDistinct ( pivot )

동일한 기능이니 같은 이름으로 통일하면 좋겠습니다. 

* pivot 은 stdev 로 하면 에러납니다. 그러나 stats 에  **stddev** 로 사용하면 에러 없이 결과가 출력됩니다.
  ( stats 코드 보니 if 구문에 없는 명령어는 spark 의 함수를 그대로 사용하도록 되어 있음. spark 의 STDDEV 가 실행됨 )

- pivot  에서 stdev 사용 시 에러 예시
<img width="599" alt="스크린샷 2020-09-08 오전 8 24 25" src="https://user-images.githubusercontent.com/5126497/92420160-c6c9bc00-f1ac-11ea-9047-409a4aca9160.png">

- stats 에서 stddev 사용 시 
<img width="1226" alt="스크린샷 2020-09-08 오전 8 27 04" src="https://user-images.githubusercontent.com/5126497/92420253-448dc780-f1ad-11ea-9fef-eda1d27a6021.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
통일 하였습니다.
호환을 위해 기존 stdev, distinct_count 는 유지 하였습니다.

명령어문서:
- [stats](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/stats.html)
- [pivot](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/pivot.html)

- stats
![Screen Shot 2020-11-03 at 9 47 15 AM](https://user-images.githubusercontent.com/46172579/97934661-a8053180-1db9-11eb-9f16-9daf92a0df64.png)
-pivot
![Screen Shot 2020-11-03 at 9 47 03 AM](https://user-images.githubusercontent.com/46172579/97934658-a471aa80-1db9-11eb-8cde-97823f6e21a0.png)
