### ISSUE TITLE
[Discovery] DSL 마다 필드이름 사용 규칙이 다릅니다.(대소문자 구분, 통계함수안에 사용 규칙) 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2601]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 대소문자 구분없이 소문자로 사용 :  stats 는 동작, pivot 은 에러 발생

- stats : 소문자로 변경해서 사용한 예로 실행이 됩니다.  Species -> species 로 변경해도 실행됨
<img width="1226" alt="스크린샷 2020-09-08 오전 8 27 04" src="https://user-images.githubusercontent.com/5126497/92420816-676dab00-f1b0-11ea-985e-9a14959b94c5.png">

- pivot  :  소문자로 변경하면 필드를 찾지 못한다는 에러 발생.
    - pivot 은 함수안에는 소문자로 변경해서 사용해도 에러 없음. Sepal_width -> sepal_width 사용
    - SPLITCOL, SPLITROW  뒤에 쓸 때는 대소문자 구분한 정확한 필드명을 써야 함

`*  | pivot count(*) as 개수,  avg(sepal_width) as 평균_sepal_width
              SPLITCOL species`

<img width="380" alt="스크린샷 2020-09-08 오전 8 52 20" src="https://user-images.githubusercontent.com/5126497/92420908-e9f66a80-f1b0-11ea-90a3-355425242a35.png">

- avg 함수안에는 Sepal_width -> sepal_width 로 변경해도 결과가 나옴. 
`*  | pivot count(*) as 개수,  avg(sepal_width) as 평균_sepal_width
              SPLITCOL Species`

<img width="1097" alt="스크린샷 2020-09-08 오전 8 55 48" src="https://user-images.githubusercontent.com/5126497/92420936-1e6a2680-f1b1-11ea-94f5-043374d05167.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 공유 해 주세요.

**Comment by sunghoon** [comment]
@안형민 미팅 내용
10월 23일 목표로 진행되고 있음.

**Comment by sunghoon** [comment]
@anhm @seungfwani 이슈 처리 현황 정보를 공유 해 주세요.

**Comment by seungfwani** [comment]
처리 내용 검토 중이며, DSL에 의존된 API 도 함께 확인을 후 배포 할 예정입니다.

**Comment by sunghoon** [comment]
@seungfwani 배포 목표일 정보를 공유 해 주세요. 기존 목표는 20년 10월 23일이 목표 였습니다.

**Comment by seungfwani** [comment]
해당 DSL 에 의존적인 API 가 있어 해당 부분을 확인하지 못해 목표일에 맞추지 못했습니다.
20.10.30 에 배포가 가능 할 것으로 예상됩니다.

**Comment by seungfwani** [comment]
수정 완료 되었습니다.
![Screen Shot 2020-11-03 at 9 56 41 AM](https://user-images.githubusercontent.com/46172579/97935082-e5b68a00-1dba-11eb-84e1-2f6b49137177.png)
