### ISSUE TITLE
[Discovery] DSL stats 와 pivot 에서 date_group 에 따옴표 적용하는 기준이 다릅니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2602]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

데이터모델 : EDU_SYSLOG_2020_0325_09   / 전체기간

stats 에는 date_group 함수에 따옴표를 하면 에러 발생 / 없어야 정상 실행
pivot 은   date_group 함수에 따옴표를 하면 정상 / 없으면 에러

- stats 에서 date_group 함수 이용하여 10분 집계 할 때는 따옴표없이 결과 나옵니다.
`* |  stats count(*) as CNT by date_group("DATETIME", "10M") , HOST | sort  dategroup`

<img width="922" alt="스크린샷 2020-09-08 오후 1 33 53" src="https://user-images.githubusercontent.com/5126497/92433410-f4782a80-f1d7-11ea-90ff-8d03f0159b7e.png">

- pivot 에서는 에러납니다.
`* |  pivot  count(*) as CNT SPLITROW date_group("DATETIME", "10M") , HOST SORTROW asc`
<img width="601" alt="스크린샷 2020-09-08 오후 1 32 08" src="https://user-images.githubusercontent.com/5126497/92433338-b8dd6080-f1d7-11ea-8582-abf627de0c36.png">

- pivot 은 작은 따옴표를 해야 결과가 나옵니다.

`* |  pivot  count(*) as CNT SPLITROW 'date_group("DATETIME", "10M")' , HOST SORTROW asc`
<img width="975" alt="스크린샷 2020-09-08 오후 1 32 51" src="https://user-images.githubusercontent.com/5126497/92433380-d4e10200-f1d7-11ea-85a1-192b687aaca0.png">

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 공유 해 주세요.

**Comment by seungfwani** [comment]
수정 완료 되었습니다.
![Screen Shot 2020-11-03 at 9 57 44 AM](https://user-images.githubusercontent.com/46172579/97935147-0aaafd00-1dbb-11eb-8c8a-5eca3a4783d7.png)
