### ISSUE TITLE
페이지 이동시 콤보박스의 value가 쿼리 조건에 들어가지 않음.

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2603]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :

1. 버튼 클릭시 IRIS 보고서로 만들어진 URL로 param 을 넘겨서 콤보박스가 선택되도록 함.

2. 콤보박스의 value를 그래프를 그리는 쿼리(자동실행)의 where 조건에 넣어줌

3. 버튼을 클릭하면 페이지가 뜨면서 콤보박스가 자동으로 선택됨.

4. 쿼리는 전체 결과가 조회됨.

![image](https://user-images.githubusercontent.com/16331916/92542689-6f971a80-f284-11ea-81bd-1e991ddfcb6d.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

==================================================================================

추가 작성

데이터 조회 쿼리
![image](https://user-images.githubusercontent.com/16331916/93037481-7b684f80-f67d-11ea-818a-7617e8a6d8af.png)

콤보박스 구성
![image](https://user-images.githubusercontent.com/16331916/93037504-8cb15c00-f67d-11ea-8d51-3eb2f69b6cef.png)

 위의 이미지를 참고하여 설명드리면, 
1. 콤보박스의 구성은 데이터 모델에서 쿼리를 해온 리스트 입니다. (자동실행)

2. 데이터조회 쿼리에서는 콤보박스의 value 를 이용하여 쿼리를 진행합니다.

![image](https://user-images.githubusercontent.com/16331916/93037603-c7b38f80-f67d-11ea-8b39-6e90feeb8500.png)

3. 콤보박스의 디폴트 값을 앞단에서 canvas_1로 받아옵니다.

**Comment by veldise** [comment]
@kim3163 
combo-box 구성과 그래프의 쿼리를 알아야 문제를 파악할 수 있습니다. 추가 작성 부탁드립니다.

**Comment by sunghoon** [comment]
@kim3163 검토를 위한 추가 정보 및 구두(@sunghoon) 설명 부탁드립니다.

**Comment by kim3163** [comment]
@rhcpn  박세종 팀장님과 구두로 방법에 대해 논의 하였고, 아직 테스트를 해보진 않았습니다.
위 이슈는 Close하도록 하겠습니다.
