### ISSUE TITLE
[Studio] 보고서 내부에서 생성된 Visual 객체가 해당 보고서가 삭제되어도 DB 에서 지워지지 않음

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#2604]
## 버그 설명 ##
보고서를 생성하고 Visual 객체를 만들어서 저장한뒤에 해당 보고서의 Visual 객체를 삭제해도 DB (visual_report) 상에는 지워지지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 새 보고서 생성
2. visual 객체(area, map) 다중 생성후 저장
3. 2에서 저장된 보고서 수정
4. 기존 visual 객체를 삭제하고 저장
5. 2에서 새로 생성된 visual  객체의 정보가 DB 에 남아 있음

## 예상한 행동 ##
사용되지 않는 visual 객체는 DB(visual_report) 상에서 삭제

## 기타 ##
보고서를 삭제해도 해당 visual 객체의 데이터는 지워지지 않습니다.
이미지 객체의 경우는 사용되지 않는 객체는 삭제됩니다.

**Comment by sunghoon** [comment]
@veldise @swish1995 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
개발 완료되었고 10.29 패치 예정입니다.
