### ISSUE TITLE
Studio: gradient-palette -> rainbow 그라디언트 값 수정 

### ISSUE THREAD

**Issue by ohmy04180** [mobigen/IRIS-BigData-Platform#2606]
## 버그 설명 ##
그라디언트 퍼센티지 값 수정 및 벤더프리픽스 적용 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by ohmy04180** [comment]
오타 수정 및 브라우저 대응을 위한 벤더 프리픽스 적용 완료

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/92571116-ad646500-f2bd-11ea-946c-cb2b78c496ea.png)

**Comment by veldise** [comment]
9/10 패치로 해결되어 닫습니다.
