### ISSUE TITLE
파일브라우저-HDFS 다운로드 오류

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2607]
## 버그 설명 ##
파일 다운로드가 되지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to HDFS
2. Click on '다운로드'

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/44352311/92665418-80f22c80-f341-11ea-9a95-5c02126bcce9.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
#2593 동일 원인으로 인한 이슈입니다.

**Comment by jblim0125** [comment]
k8s 환경으로 이전하면서 변경되었어야 할 설정들이 반영되지 못하였습니다.

>변경 사항
/etc/hosts Local file mount 삭제
HostAliases로 파드의 /etc/hosts 에 hadoop 클러스터 정보 추가

파일 업/다운로드 동작 확인하였습니다.

**Comment by sunghoon** [comment]
@EricLeeMbg 한번 더 확인 하고 닫아 주세요.

**Comment by EricLeeMbg** [comment]
해당 기능에 대해 다음과 같이 테스트 하였습니다. 
- root / 일반유저 테스트
- 파일 업로드/다운로드 테스트
- 파일이동 시 동일이름의 파일이 있으면 '덮어쓰기' 문의창 생성
