### ISSUE TITLE
[밸류링크유] Studio: REST Api 사용 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2610]
## 버그 설명 ##
RESTful API로 데이터를 검색하는 보고서를 작성중인데 계속 오류가 발생한다고 합니다.
사용한 URL은 https://qas.valuelinku.com/api/v1/common/kortest 입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/92681839-b579de80-f369-11ea-85f7-e7066fc3923e.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@SONHOJUN 
ValueLinkU IRIS 사이트는 HTTP 로 구성되어있는 것으로 알고 있습니다.
HTTP 내에서 HTTPS 프로토콜은 사용할 수 없습니다.

**Comment by sunghoon** [comment]
@veldise 프로토콜을 확인하여 이야기 하신 상황을때 사용자가 인지 할 수 있는 메시지로 알람 표기 바랍니다.

@SONHOJUN 확인 되셨는지요?

**Comment by SONHOJUN** [comment]
@sunghoon 넵 확인했습니다. 닫겠습니다.

**Comment by sunghoon** [comment]
@veldise 프로토콜을 확인하여 이야기 하신 상황을때 사용자가 인지 할 수 있는 메시지로 알람 표기 바랍니다.

이슈는 재 오픈 합니다.

**Comment by veldise** [comment]
@sunghoon 
10/15 패치로 아래와 같이 사이트와 프로토콜이 다를경우, 실행시 경고창이 팝업됩니다.

![image](https://user-images.githubusercontent.com/3411842/96058908-763e3080-0ec7-11eb-8d02-506b19b5f593.png)
