### ISSUE TITLE
[Studio] 사각형 우클릭시 설정 비활성화

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2612]
## 버그 설명 ##
사각형 우클릭시 설정할 수 있는 내용이 보이지 않습니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/5077625/92837477-9b4b0980-f418-11ea-8647-269e2b905784.png)

**Comment by veldise** [comment]
## 재현 방법
1. 사각형 or 원형 or '외부 URL' 객체를 화면에 추가 (이전에 다른 객체를 추가하면 재현되지 않음)
2. 마우스 우클릭
