### ISSUE TITLE
[서초구청] Map - 마커일 경우 조건부 서식 추가

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2614]
## 기능 요청 ##
Map - 마커일 경우 특정 조건 일때 마커의 색상을 정해서 표시하고 싶습니다.
챠트 - 시각화 옵션 - 조건부 서식 같이 Map - 마커 - 시각화 옵션 - 조건부 서식 추가

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 검토 진행 바랍니다.
