### ISSUE TITLE
쿼리 실행시 SPARK 에러

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2615]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

Spark 에러 발생. 하단의 에러가 어떤 경우에 나는지, 
[ cannot find job id ~~~~~~~ ] 라는 에러가 납니다.
![image](https://user-images.githubusercontent.com/16331916/93037761-211bbe80-f67e-11ea-8621-30c85972a149.png)

![image](https://user-images.githubusercontent.com/16331916/93037755-19f4b080-f67e-11ea-938d-d73332e562fe.png)
- 이미지의 스크롤바 떄문에 다 보이지 않아 쿼리 첨부
```
| join LEFT_OUTER NB_IOT_CM_NB_APP_INFO NB_IOT_CM_NB_APP_INFO.app_service_code = NB_IOT_PM_SERVICE_KPI_1M_IRIS.app_service_code 
| join LEFT_OUTER NB_IOT_CM_NB_APP_REL_FUNC NB_IOT_CM_NB_APP_REL_FUNC.app_service_code =  NB_IOT_CM_NB_APP_INFO_app_service_code 
| where NB_IOT_CM_NB_APP_REL_FUNC_app_func_code like '%%' 
| stats SUM(tcp_response_count) as TCP_res by CTIME
| sql "SELECT 
substr(ctime , 0,2) || ':' || substr(ctime , 3,2) as 시간,
TCP_res as TCP_응답
from angora
" | sort ctime
```
## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
위의 테스트 쿼리를 192.168.100.180 에서 실행 해보았을 때 특별한 문제점은 찾지못했습니다.
![Screen Shot 2020-09-21 at 4 43 05 PM](https://user-images.githubusercontent.com/46172579/93742705-8c8b0080-fc29-11ea-9d02-8dfe3e3cf1f8.png)

올려주신 이미지로는 에러로그를 확인하기 어렵습니다.

**Comment by sunghoon** [comment]
@kim3163 문제가 해결 되셨는지요?

**Comment by kim3163** [comment]
@seungfwani 서승환 책임과 확인중에 있습니다.
DSL 자체는 문제가 없으나, 대전 상용서버에서 위의 DSL을 실행시 일부가 에러로 발생하는 현상이 있습니다.

**Comment by sunghoon** [comment]
@big-mobigen @seungfwani 본 이슈에 대한 대응 바랍니다.

**Comment by sunghoon** [comment]
@kim3163 요청사항에 대한 진행은 어떻게 되고 있는지요?

**Comment by sunghoon** [comment]
해당 이슈와 관련된 추가 내용이 없어. 본 이슈는 닫도록 하겠습니다. 비슷한 이슈가 발생하면 새 이슈로 다루겠습니다.
