### ISSUE TITLE
Studio: 보고서 가져오기 / 동일한 보고서가 존재하는 경우 가져오기 실패

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2616]
## 버그 설명 ##
Studio: 보고서 가져오기 / 동일한 보고서가 존재하는 경우 가져오기 실패

## 내용 ##
1. 보고서가 실패하는 상황 재현
2. '동일'한 보고서 기준 검토
3. 개선 방안 수립

**Comment by sunghoon** [comment]
@veldise 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
개발 완료되었고 10.29 패치 예정입니다.
