### ISSUE TITLE
[Studio] DSMS 연결 정보 선택: 데이터가 없습니다.

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2617]
## 버그 설명 ##
DSMS 연결 정보 선택에서  '데이터가 없습니다.' 라고 나옵니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/5077625/93154373-728b8280-f73e-11ea-9805-5f6d5c0e94b2.png)

**Comment by veldise** [comment]
#2582

**Comment by sunghoon** [comment]
@veldise 이 이슈와 같은 상황 같아 보입니다. 빠른 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
위에 제가 달아둔 댓글과 같이 #2582, #2568 과 동일한 이슈입니다. 현재는 잘 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/94209696-e16b9700-ff07-11ea-8869-d339f193b9a7.png)

**Comment by sunghoon** [comment]
@veldise 지금 잘 되는 상황은 장애 대응을 통해서 문제가 해결된것 같아보이며 #2630 를 참고하여 이야기 된 방안으로 최종 문제 해결을 위한 계획을 제시해 주시기 바랍니다.

**Comment by sunghoon** [comment]
본 이슈는 닫고 새로운 이슈로 관리하겠습니다.
