### ISSUE TITLE
[Analyzer] 검색 후 "시각화로 이동"  - 이동이 되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2618]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 피벗으로 이동 , 이상 탐지로 이동은 OK

- "시각화로 이동" 은  안됩니다.
<img width="1121" alt="스크린샷 2020-09-16 오전 11 17 51" src="https://user-images.githubusercontent.com/5126497/93284764-4d664500-f80e-11ea-96b4-d3fe5d22a9d4.png">

<img width="183" alt="스크린샷 2020-09-16 오전 11 12 15" src="https://user-images.githubusercontent.com/5126497/93284642-14c66b80-f80e-11ea-9b5c-0cc073270db5.png">
- 계속 검색 화면만 나옵니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
9/24 패치로 해결되어 닫습니다.
