### ISSUE TITLE
[Discovery] DSL "anomalies"  의 옵션에  alert_window 를 추가하면 실행결과가 alert_window 시간의 데이터만 출력됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2619]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정
데이터모델 : EDU_Beijing_air_2013_2017_18

alert_window 에 해당하는 시간의 데이터만 출력됩니다.
하지만 모든 기간의 데이터 출력에 alert_window 기간 데이터는 upper, lower, anomalies 세 필드에 값이 나오는  결과로 출력되어야 합니다.
이렇게 되어야 **시각화** 탭에서 결과 그래프가 조회 기간 데이터로 그래프가 그려집니다.

- alert_window  가 없는 anomalies 결과 : 정상적으로 표시됩니다.
`* | where year = 2017 and month  = 01  and station = 'Changping' |  fields CTIME,station,PM2_5 | sort CTIME | anomalies CTIME PM2_5`

<img width="1130" alt="스크린샷 2020-09-16 오전 11 30 53" src="https://user-images.githubusercontent.com/5126497/93293693-878e1180-f823-11ea-98ed-49adc2e3caf5.png">

- 명령어 에 alert_window 옵션 추가한 결과
`* | where year = 2017 and month  = 01  and station = 'Changping' |  fields CTIME,station,PM2_5 | sort CTIME | anomalies CTIME PM2_5  alert_window=last_24h`

- 결과 :  anomaly 탐지 대상인 마지막 24시간 데이터인  2개 행만 anomaly 결과와 함께 출력되고, 챠트 시각화도 2개만 그려집니다.
<img width="1127" alt="스크린샷 2020-09-16 오전 11 42 45" src="https://user-images.githubusercontent.com/5126497/93286249-c74bfd80-f811-11ea-9462-b802a10af71d.png">

<img width="1115" alt="스크린샷 2020-09-16 오전 11 46 01" src="https://user-images.githubusercontent.com/5126497/93286433-34f82980-f812-11ea-86c0-e5f7f9224265.png">

- 원하는 결과 :  anomaly 의 입력 데이터 전체가 다 보여지고, 마지막 24시간 데이터와 anomaly 결과가 같이 표시되어야 합니다.
<img width="863" alt="스크린샷 2020-09-16 오후 1 47 18" src="https://user-images.githubusercontent.com/5126497/93293561-2ebe7900-f823-11ea-9609-a9feea2e8132.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@veldise 
위와 같은 동작을 하기 위해서 UI 에서도 수정이 필요할 것 같아 의견을 말씀드립니다.

앙고라는 anomalies 의 결과로 `upper`, `lower`, `anomaly` 를 리턴하고 있습니다.
`alert_window` 옵션이 설정 되었을 때는 해당하는 값만 필터링 하여 리턴하고 있습니다. <- 이부분이 이슈가 제기된 원인입니다.

앙고라에서 `alert_window` 옵션이 설정되었을 때 해당하는 값에 대한 T/F 정보를 함께 리턴하도록 수정하면
UI 에서 해당 컬럼의 정보를 이용해서 `true` 인 경우 에만 `upper/lower` 바운더리를 표현하도록 하면 어떨까요?

아래는 현재/ 변경안 에 대한 리턴 결과 입니다.

-현재
```
* |  anomalies CTIME PM2_5 alert_window=last_24h

# 결과
{'name': 'CTIME', 'type': 'TIMESTAMP', 'grouped': False}
{'name': 'station', 'type': 'TEXT', 'grouped': False}
{'name': 'PM2_5', 'type': 'REAL', 'grouped': False}
{'name': 'upper', 'type': 'REAL', 'grouped': False}
{'name': 'lower', 'type': 'REAL', 'grouped': False}
{'name': 'anomaly', 'type': 'BOOLEAN', 'grouped': False}
['2017-01-30 18:00:00', 'Changping', 52.0, 190.47, -63.27, False]
['2017-01-31 18:00:00', 'Changping', 23.0, 191.37, -62.37, False]
```

-변경안
```
* |  anomalies CTIME PM2_5 alert_window=last_24h

# 결과
{'name': 'CTIME', 'type': 'TIMESTAMP', 'grouped': False}
{'name': 'station', 'type': 'TEXT', 'grouped': False}
{'name': 'PM2_5', 'type': 'REAL', 'grouped': False}
{'name': 'upper', 'type': 'REAL', 'grouped': False}
{'name': 'lower', 'type': 'REAL', 'grouped': False}
{'name': 'anomaly', 'type': 'BOOLEAN', 'grouped': False}
{'name': 'alert_window', 'type': 'BOOLEAN', 'grouped': False}    <--- 추가된 컬럼
['2017-01-01 18:00:00', 'Changping', 443.0, 569.87, 316.13, False, False]
['2017-01-02 18:00:00', 'Changping', 199.0, 447.87, 194.13, False, False]
...
['2017-01-29 18:00:00', 'Changping', 8.0, 188.47, -65.27, False, False]
['2017-01-30 18:00:00', 'Changping', 52.0, 190.47, -63.27, False, True]
['2017-01-31 18:00:00', 'Changping', 23.0, 191.37, -62.37, False, True]
                                                                   ^
                                                                   |
                                                                추가된 컬럼
```

-----
-alert_window 옵션이 설정되지 않았을 경우
```
* |  anomalies CTIME PM2_5
* |  anomalies CTIME PM2_5 alert_window=last_24h

# 결과
{'name': 'CTIME', 'type': 'TIMESTAMP', 'grouped': False}
{'name': 'station', 'type': 'TEXT', 'grouped': False}
{'name': 'PM2_5', 'type': 'REAL', 'grouped': False}
{'name': 'upper', 'type': 'REAL', 'grouped': False}
{'name': 'lower', 'type': 'REAL', 'grouped': False}
{'name': 'anomaly', 'type': 'BOOLEAN', 'grouped': False}
['2017-01-01 18:00:00', 'Changping', 443.0, 569.87, 316.13, False]
['2017-01-02 18:00:00', 'Changping', 199.0, 447.87, 194.13, False]
...
['2017-01-29 18:00:00', 'Changping', 8.0, 188.47, -65.27, False]
['2017-01-30 18:00:00', 'Changping', 52.0, 190.47, -63.27, False]
['2017-01-31 18:00:00', 'Changping', 23.0, 191.37, -62.37, False]
```

**Comment by veldise** [comment]
@seungfwani 
추가 컬럼(`alert_window`) 없이, `upper`, `lower` 값을 `null` 로 반환해도 충분할 것 같습니다.

UI 에서는 `upper`, `lower` 값이 null 일 때 처리를 추가하겠습니다.

**Comment by sunghoon** [comment]
@veldise 진행 일정 계획에 대하여 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
박세종 팀장과 논의 후에 말씀드리겠습니다.

**Comment by seungfwani** [comment]
@veldise 
앙고라의 리턴값을 null 로 수정하도록 하니 아래와 같은 그래프가 그려집니다.

@seoryjj 

![Screen Shot 2020-09-23 at 7 05 22 PM](https://user-images.githubusercontent.com/46172579/93998601-bda53580-fdcf-11ea-80a7-7423c04471a8.png)

**Comment by sunghoon** [comment]
@seoryjj 원하시는 결과가 맞으신지요?

**Comment by seungfwani** [comment]
수정 완료되었습니다. 배포후 닫도록 하겠습니다.

![Screen Shot 2020-09-25 at 4 54 51 PM](https://user-images.githubusercontent.com/46172579/94241624-d5a3c300-ff4f-11ea-9100-bcc6ca3e23cf.png)
