### ISSUE TITLE
파일 브라우저: "+" 문자가 들어간 파일을 다운로드하려고 하면 에러 페이지로 전환

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2620]
## 버그 설명 ##
파일 브라우저: "+" 문자가 들어간 파일을 다운로드하려고 하면 에러 페이지로 전환

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 메뉴 > Discovery > 파일 브라우저 로 이동
2. HDFS 에서 `/B-IRIS/USERS/choi` 폴더로 이동
3. `html+복사본+테스트(ㅁㄴㅇㄹ).csv` 파일 다운로드 시도

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/93539468-dfe02300-f98b-11ea-95c6-61855f48c477.png)

**Comment by sunghoon** [comment]
@veldise @lyj 본 이슈에 대한 최종 진행 상태를 공유 해 주세요.

**Comment by lyj** [comment]
현상 파악중입니다. 좀 더 테스트 후, 진행 일정 공유하겠습니다.

**Comment by lyj** [comment]
2020-10-29 Milestone 등록 되었습니다.

**Comment by sunghoon** [comment]
@lyj 어떻게 처리 되었나요?

**Comment by lyj** [comment]
@sunghoon 2020-10-29 배포완료 되었습니다.
