### ISSUE TITLE
[Discovery] anomalies 명령어에서 alg=robust 에서는 그룹 by 데이터의 경우는 결과가 없다고 나옵 니다

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2623]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

anomalies 시간 vlaue by = HOST  -> basic 알고리즘에서는 결과가 나옵니다.
anomalies  시간 value by = HOST  alg = robust  에서는 결과가 없다고 나옵니다.
하지만 HOST 1개로 지정하면 결과가 나옵니다.

- 입력 데이터 검색어 
` * | WHERE LEVEL != 'info'   |  stats  COUNT(*)  as CNT  by  date_group(DATETIME, "10M") , HOST  
  | sort +dategroup 
  | fill_zero freq=600 stime=20191210090000  etime=20191210120000  time_column=dategroup group_key=HOST value=CNT  `

- anomalies  에서 alg = basic  ( 디폴트로 명시하지 않음 )

- anomalies   에서 HOST를 1개로 지정하여 필터링 , robust옵션 넣으면 답이 나옴
<img width="1214" alt="스크린샷 2020-09-21 오후 3 15 47" src="https://user-images.githubusercontent.com/5126497/93738286-601eb680-fc20-11ea-9de3-e1047fe395c2.png">

- by = HOST , robust 옵션 넣으면 답이 없다고 나옴

<img width="1040" alt="스크린샷 2020-09-21 오후 3 24 25" src="https://user-images.githubusercontent.com/5126497/93738320-76c50d80-fc20-11ea-9b8a-15fda0f6e9f8.png">

``
- by=HOST , basic 옵션은 답이 나옴

`* | WHERE LEVEL != 'info' |  stats  COUNT(*)  as CNT  by  date_group(DATETIME, "10M") , HOST  
  | sort +dategroup 
  | fill_zero freq=600 stime=20191210090000  etime=20191210120000  time_column=dategroup group_key=HOST value=CNT  |  anomalies dategroup CNT by=HOST  | typecast dategroup   'timestamp'`

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
결과가 도출 되도록 수정하였습니다.

![Screen Shot 2020-09-23 at 7 08 18 PM](https://user-images.githubusercontent.com/46172579/93998894-255b8080-fdd0-11ea-9a16-9499c7bb5242.png)

**Comment by sunghoon** [comment]
@seoryjj 원하시는 결과가 맞으신지요?

**Comment by seungfwani** [comment]
본 이슈의 문제는 alg=robust 일 때, by 옵션의 동작이 잘못된 것으로,
해당 문제는 수정하였기 때문에 닫도록 하겠습니다.
