### ISSUE TITLE
[Analyzer] 이상탐지 실행 개선 및 점검

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2624]
- 값 컬럼의 함수 '개수'를 'Count'로 표기 변경
- 데이터 조회 시간 및 실행옵션 시간 설정을 사용할때 같은 최근 시간(예 최근 10분)을  설정하였을때, 임의의 시간이 지난 후 실행을 요청하는 시점에서 시간 정보가 다르게 설정되어 요청이 들어감.
- 값 컬럼의 타입이 숫자형일 경우 함수에 min, max, 중간값 함수 추가
  - 함수 추가는 Discovery 쪽과 연계하여 작업

**Comment by veldise** [comment]
참고용 스크린샷 첨부합니다.

![image](https://user-images.githubusercontent.com/3411842/93848949-e9e48780-fce5-11ea-9595-1bfeaf4219ff.png)

**Comment by sunghoon** [comment]
@seoryjj 다음 항목에 대한 정확한 재현을 위한 상황정보를 추가적으로 요청드립니다.
- 최근 10분 처럼 하면, 나중에 "비교 기간" 의 최근 10분과 차이가 발생함

**Comment by seoryjj** [comment]
<img width="458" alt="스크린샷 2020-09-22 오후 3 48 55" src="https://user-images.githubusercontent.com/5126497/93851469-25ce1b80-fceb-11ea-8982-168a99026eed.png">


<img width="225" alt="스크린샷 2020-09-22 오후 3 49 33" src="https://user-images.githubusercontent.com/5126497/93851510-38485500-fceb-11ea-99c5-b462b4231cfb.png">

**Comment by sunghoon** [comment]
@eumminsun @veldise

중간 내용에 대하여 설명을 듣었으며, 아래와 같이 나머지 2개를 진행해 주시기 바랍니다.

- 값 컬럼의 함수 '개수'를 'Count'로 표기 변경
- <s>데이터 조회 시간 및 실행옵션 시간 설정을 사용할때 같은 최근 시간(예 최근 10분)을  설정하였을때, 임의의 시간이 지난 후 실행을 요청하는 시점에서 시간 정보가 다르게 설정되어 요청이 들어감.</s>
- 값 컬럼의 타입이 숫자형일 경우 함수에 min, max, 중간값 함수 추가
  - 함수 추가는 Discovery 쪽과 연계하여 작업

**Comment by veldise** [comment]
@seungfwani 
현재 이상탐지 > 값 필드 설정에서 지정할 수 있는 함수는 아래 4개입니다.

- `sum` (합계)
- `avg` (평균)
- `count` (개수)
- `countDistinct` (값의 개수)

위와 같이 최대값, 최소값, 중간값에 해당하는 함수명만 알려주시면 됩니다.

ade API 옵션 예시:
```json
{
    "ade": {
        "values": [
            {
                "name": "LEVEL_INT",
                "func": "count"
            },
            {
                "name": "LEVEL_INT",
                "func": "sum"
            }
        ],
    // ... 후략 ...
```

**Comment by sunghoon** [comment]
@seungfwani 본 이슈 관련 지원 일정계획을 공유해 주세요.
