### ISSUE TITLE
Discovery ade 명령 점검

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2625]
1. 값 컬럼이 숫자형일때 min, max, 중간값 구할 수 있도록 함수를 추가해 주세요.
2. 다음과 같은 조건일때 데이터 생성이 안됩니다. 
![스크린샷 2020-09-22 오전 9 19 01](https://user-images.githubusercontent.com/512653/93833821-b2a9b280-fcb4-11ea-948d-167164fdd2d0.png)
![스크린샷 2020-09-22 오전 9 19 05](https://user-images.githubusercontent.com/512653/93833822-b4737600-fcb4-11ea-9ad7-9b4cf97f7cad.png)
![스크린샷 2020-09-22 오전 9 19 11](https://user-images.githubusercontent.com/512653/93833824-b5a4a300-fcb4-11ea-8254-92f807c62d48.png)

**Comment by sunghoon** [comment]
값 컬럼이 숫자형일때 min, max, 중간값 구할 수 있도록 함수를 추가해 주세요.

**Comment by seungfwani** [comment]
아래 이슈와 함께 처리 진행 하겠습니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2232
https://github.com/mobigen/IRIS-BigData-Platform/issues/2233
https://github.com/mobigen/IRIS-BigData-Platform/issues/2234

**Comment by sunghoon** [comment]
@anhm 본 이슈 처리 어떻게 되었는지요? 연결 이슈들은 모두 Close 되어 있네요.

**Comment by seungfwani** [comment]
@sunghoon 
연결된 이슈들은 중복된 내용으로 생각 되어 하나의 이슈만 열어놓은 상태입니다. (처리할 때는 연결이슈 3가지를 모두 참고 할 것 입니다.)

현재 진행 대기 중인 상태입니다.
