### ISSUE TITLE
[Studio] "날짜/시간선택" 객체에서 초기날짜 설정이 적용되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2626]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

보고서 : EDU_Studio_트리맵챠트_날짜시간선택예제

- 날짜/시간 선택 객체에서 초기날짜 설정을 변경했지만, 편집 화면에서 객체의 날짜는 수정이 되지 않습니다.
<img width="480" alt="스크린샷 2020-09-22 오전 9 37 03" src="https://user-images.githubusercontent.com/5126497/93834577-58f6b780-fcb7-11ea-882c-22e98018649b.png">

- 저장은 설정값대로 되어 있습니다.
<img width="551" alt="스크린샷 2020-09-22 오전 9 37 54" src="https://user-images.githubusercontent.com/5126497/93834571-5300d680-fcb7-11ea-9072-e00911d91475.png">

- 화면 보기 :  편집화면처럼 날짜 변경이 되지 않습니다.
<img width="397" alt="스크린샷 2020-09-22 오전 9 40 19" src="https://user-images.githubusercontent.com/5126497/93834675-a410ca80-fcb7-11ea-8450-dc1f7f97ad4d.png">

- 새 보고서에서는 문제가 없습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
<img width="496" alt="스크린샷 2020-09-22 오전 9 55 07" src="https://user-images.githubusercontent.com/5126497/93835289-b7249a00-fcb9-11ea-9a6e-b8c99aa28677.png">


- 달력 범위제한을 하면 문제가 되는 것 같습니다

**Comment by veldise** [comment]
현재는 '달력 범위 제한' 설정 후 초기 날짜를 설정할 때, 범위 바깥의 날짜를 선택하면 적용되지 않고 있습니다.
제한 범위 바깥을 선택하려고 하므로 적용되지 않는 것입니다.

아래와 같이 '달력 범위 제한' 설정이 '초기 날짜' 설정에도 적용되도록 개선 예정입니다.

![image](https://user-images.githubusercontent.com/3411842/93835846-91989000-fcbb-11ea-9545-98c1f7ee250d.png)

**Comment by veldise** [comment]
9/24 패치로 해결되어 닫습니다.
