### ISSUE TITLE
IRIS -  한창 작업을 하고 있는데, 갑자기 이 창이 뜹니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2627]
## 버그 설명 ##

b-iris.mobigen.com  demo  크롬 브라우저 / Mac 일시 : 2020-09-22 10:45

<img width="1260" alt="스크린샷 2020-09-22 오전 10 45 55" src="https://user-images.githubusercontent.com/5126497/93837428-04f0d080-fcc1-11ea-9f65-e0a2dbbd3485.png">

- 확인 누르면 약 1-2초 후에는 다시 동작이 됩니다.
- 
## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 이슈 파악 바랍니다.

**Comment by veldise** [comment]
@lyj 
IWP 에서 alert 창을 띄우고 있습니다. 확인 부탁드립니다.

**Comment by seoryjj** [comment]
전날에 IRIS 로그아웃 안하고 맥북을 닫았다 아침에 출근해서 보니 어제 그 창이 떠 있습니다.
확인을 누르니 이번에는 로그아웃이 안됩니다. 메뉴선택 창 자체가 뜨질 않습니다.
  
<img width="450" alt="스크린샷 2020-09-23 오전 8 20 07" src="https://user-images.githubusercontent.com/5126497/93948492-9459ba80-fd79-11ea-80a5-6cad343320a7.png">

- 어제는 팝업창이 뜨고 확인 바로 누르니 다시 정상 동작했고, 이번에는 목록 리로드 버튼 클릭하면 목록이 없다고 나오니 정상 동작은 안합니다.
- 그리고 로그아웃을 위한 창이 안 뜹니다. 그래서 그냥 탭 자체를 닫아야 합니다.
<img width="404" alt="스크린샷 2020-09-23 오전 8 43 43" src="https://user-images.githubusercontent.com/5126497/93948379-404ed600-fd79-11ea-856f-4dc29f47705f.png">

**Comment by sunghoon** [comment]
@lyj 어떻게 파악되거나 진행 할 계획인지 공유 바랍니다.

**Comment by lyj** [comment]
현상 파악 후 적용예정입니다. 다음달(11월) 적용 예상입니다.

**Comment by sunghoon** [comment]
@lyj 11월 초 / 중 / 말 언제로 보시는지요?

**Comment by rhcpn** [comment]
해당 이슈는 11월 중순 정도에 처리 예정입니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 해당 이슈 어떻게 조치 되었는지요?

**Comment by lyj** [comment]
@sunghoon 이 이슈는 해결되었는데, 
박세종팀장님이 전반적으로 테스트 및 검증이 있었으면 좋겠다는 의견이 있어서,
계획을 가지고 있었지만 일정이 조금씩 밀려서 진행되지 못하였습니다.
차후 테스트/검증 시간을 거쳐서, 작업이 필요하면 새로운 이슈로 처리하도록 하겠습니다.
