### ISSUE TITLE
[Studio]  모션 챠트의 "play"   버튼이 동작하지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2628]
## 버그 설명 ##

b-iris.mobigen.com demo 계정

보고서 : EDU_Studio motion chart_데이터객체버전

새보고서에서 같은 모델, 검색어로 모션챠트를 만들면 정상 동작합니다.
특징은 해당 보고서는 **데이터객체** 이전 버전에서 **마이그레이션** 된 보고서입니다.
이 보고서의 모션챠트는  플레이 버튼, stop 버튼 등이 동작하지 않습니다.

<img width="892" alt="스크린샷 2020-09-22 오전 10 42 33" src="https://user-images.githubusercontent.com/5126497/93837738-4930a080-fcc2-11ea-8046-5da0eaa09b82.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
새보고서에서도 동작하지 않네요.  시각화욥션-데이터 설정을 변경하면 그 후에 계속 안됩니다.

**Comment by veldise** [comment]
"상세보기" 등의 버튼이 구성되어있으면 Play 버튼이 클릭되지 않는 것 같습니다.

@onlyeon 
직접 확인 혹은 담당자분께 전달 부탁드립니다.

**Comment by onlyeon** [comment]
_`데이터 다운로드`, `상세보기`, `데이터 갯수`, `데이터 누적`_ 기능을 그룹핑 하는 `area-toolbar` 엘리먼트가 
모션 차트 상위에 떠 있어서 발생하는 문제로 파악됩니다.

문제 해결을 위해 `area-toolbar` 엘리먼트의 구조를 분리해 내부에 있는 **4개 항목이 각각 위치 좌표로 뜨는 방법**이 있는데,
시각화 차트 전반에 사용되고 있고, 각 항목이 지정된 위치에 떠야 하기 때문에 적합하지 않은 방법인것 같습니다.

추가로 모션 차트에 _`데이터 갯수`_ 기능을 활성화 하면 아래 이미지와 같이 모션 차트 컨트롤 버튼과 겹쳐 보이는 문제가 발생합니다.
![스크린샷 2020-09-23 오전 8 48 38](https://user-images.githubusercontent.com/11944592/93955758-71d09d00-fd8b-11ea-94fb-69e4c0a8fae3.png)

위와 같은 문제점들이 있어,
**모션 차트 컨트롤 버튼 위치를 차트 아래쪽으로 옮기는 방법**도 고려해보아야 할 것 같습니다.

![스크린샷 2020-09-23 오전 9 04 31](https://user-images.githubusercontent.com/11944592/93955838-a6445900-fd8b-11ea-97d9-ee930b3c4703.png)

@veldise, @eumminsun 검토 부탁드립니다~! 🙂
감사합니다.

**Comment by sunghoon** [comment]
본 이슈에 대한 접수가 된 것으로 보겠습니다. 
관련 분들은 진행과 관련된 계획을 수립해 주시기 바랍니다.

**Comment by eumminsun** [comment]
개발, 디자인/퍼블리싱 쪽과 개선 방향 협의 하였습니다. 
화면 기획 후 진행하도록 하겠습니다.

**Comment by veldise** [comment]
@sunghoon 
11/26 패치를 목표로 진행중입니다.
