### ISSUE TITLE
[anomalies] 결과를 시각화에서 챠트로 그릴때, alg = robust 에는 다른 옵션이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2629]
## 기능 요청 ##
b-iris.mobigen.com  demo 계정

- 분석탬플릿 : 이슈_anomalies_robust
- 결과
<img width="1062" alt="스크린샷 2020-09-22 오전 11 24 12" src="https://user-images.githubusercontent.com/5126497/93838889-299b7700-fcc6-11ea-9be1-9fabe3fa1821.png">

- 챠트 :   CNT 값을 라인으로 그리는 것은 맞지만, alg=robust 의 upper, lower 는 scale 된 값이라 0 근처의 아주 작은 값으로 나옵니다.
- upper, lower 는 residuals 의 임계치입니다.
<img width="1053" alt="스크린샷 2020-09-22 오전 11 23 14" src="https://user-images.githubusercontent.com/5126497/93838827-04a70400-fcc6-11ea-8f03-da8c75b49254.png">

- 그래서 라인에 마우스를 대면 항상 0 근처 지점포인트를 CNT값과 같이 찍고, 툴팁내용에는 범위도 나옵니다.

- 제안 (1)
   - 챠트에서  alg=robust 일 경우, upper-lower 는 보여주지 않고, 실제 값의 라인 챠트와 이상값일 때 빨간 포인트만 있는 라인챠트 1개
   
- 제안 (2)
   - alg=robust 일 경우,  2개의 챠트를 보여줍니다.
   - upper-lower 는 보여주지 않고, 실제 값의 라인 챠트와 이상값일 때 빨간 포인트만 보여주는 챠트 1개 + residuals, lower, upper 챠트
   

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 해당 기능 검토 진행 바랍니다.

**Comment by seoryjj** [comment]
robust 뿐 아니라 "시각화" 탭의 챠트 공통적인 문제까지 포함해서 정리해보겠습니다.

1. 챠트 : 시각화 그래프에서 툴팁내용이 전혀 도움이 안되는 방식으로 표현됩니다. 이렇게 표시하면 오히려 보는데 방해가 되는 툴팁입니다. 라인을 선택하면 해당 라인의 툴팁 항목만 나오게 해야 합니다.( 예전 시각화 챠트에는 그렇게 표현되었는데... studio chart 도 마찬가지 문제가 있습니다) 
<img width="1227" alt="스크린샷 2020-09-24 오전 9 19 20" src="https://user-images.githubusercontent.com/5126497/94086921-52974580-fe47-11ea-8025-69fe2586ca63.png">

2. 챠트 :  robust 일 경우 툴팁 내용에  임계치는 "gcs7 residuals 의 limit : -2.35375 ~ 2.90931" 로 표시해주세요.
    basic 에서 임계치는 "gcs7 의 limit : lower값  ~ upper 값" 으로 표시해주세요.

3. 챠트 : robust 옵션은 residuals 와 residuals 의 upper, lower 입니다. 그래서 임계치 라인이 전부 0 근처에 아주 얇게 보이는 게 정상이고, residuals 까지 표시해야 하니까 1개의 챠트에 upper, lower 까지 그리면 안됩니다. 2개로 나누던지 안보여주던지.

4. 결과값 : 다른 HOST 와 달리 residual 값의 편차가  tsdn-svr1 은 비정상적으로 크게 나옵니다. 같은 데이터로 python/R 스크립트로 검증이 필요하겠습니다.

**Comment by sunghoon** [comment]
@eumminsun 정혜정책임님이 공유해 주신 정보를 바탕으로 1,2,3 번에 대한 검토 바랍니다.

**Comment by seoryjj** [comment]
b-iris.mobigen.com demo 계정의 "ML-anomalies_현황보고서(UI 이슈있음)"  보고서 참조하세요.
http://b-iris.mobigen.com:80/studio/exported/d37211a5c2fa4bb998842013c4aab0ac94c003ab81fb40d69e52777cd7b0f1b1
