### ISSUE TITLE
DSL 오류 발생합닌다. 

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2631]
![스크린샷 2020-09-23 오후 1 15 11](https://user-images.githubusercontent.com/512653/93966104-d0534680-fd9e-11ea-99f9-07e2838f5eb6.png)

**Comment by seungfwani** [comment]
해당 모델에는 `POLICE_OFFICE` 컬럼 대신 `POL_OFFICE` 로 존재합니다.

따라서 아래와 같이 하면 결과가 도출 됩니다.
`*  POL_OFFICE='전국' AND CRIME_NM='7대범죄'`
