### ISSUE TITLE
Map Analyzer / Naver 지도 연동 요청

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2634]
Map Analyzer / Naver 지도 연동 요청

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 기능 개발을 준비 해 주시기 바랍니다.

**Comment by lyj** [comment]
개발 진행 예정입니다.

**Comment by rhcpn** [comment]
네이버 지도 연동 건은 국토부 국토정보플랫폼 지도 연동건으로 추후 개발 예정으로 일정 변경 되었습니다.
