### ISSUE TITLE
Discovery / Druid를 Data Source로 연동 할 수 있도록 해 주세요. 

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2635]
Discovery / Druid를 Data Source로 연동 할 수 있도록 해 주세요.  by 나상희

**Comment by sunghoon** [comment]
@anhm @seungfwani 개발 일정 계획을 공유 해 주세요.

**Comment by sunghoon** [comment]
@anhm @seungfwani 진행을 위한 목표 일정 정보 공유 바랍니다.

**Comment by anhm** [comment]
druid 연동이 완료 되었기 때문에 해당 이슈는 닫도록 하겠습니다.
