### ISSUE TITLE
[서초구청] Studio: 날짜/시간 선택 동작 관련

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2636]
## 기능 요청 ##
서초구청에서 날짜를 선택하면 달력이 없어지게 해달라는 요청이 있습니다.
옵션으로 날짜를 선택 시 달력 표시 유무를 선택할 수 있으면 좋을 것 같습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@SONHOJUN 
컴포넌트 아이콘 출력 여부를 선택할 수 있는 옵션을 요청한것으로 이해 했습니다.

@eumminsun 기획하여 빠르게 진행 바랍니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
@SONHOJUN 
날짜&시간 객체에서 아래와 같이 달력만 사용하는 '날짜' 유형일 때
달력에서 특정 날짜를 선택시 달력이 사라지도록 할 것인데, 이를 옵션이 아닌 기본 동작으로 하고자 합니다.

반드시 옵션으로 현재 동작과 사라지도록 하는 동작을 구분해야 하는지 한 번 확인을 부탁드립니다.

**Comment by SONHOJUN** [comment]
@veldise 
옵션을 말씀드린건 다른 사이트에서 필요할까봐 말씀드린거고 말씀하신 기본 동작으로 특정 날짜 선택시 달력이 사라지도록 하면 문제없습니다. 감사합니다.

**Comment by veldise** [comment]
@SONHOJUN 
알겠습니다. 빠른 답변 감사합니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
차주 중에 처리해서 10/29 패치를 목표로 진행하겠습니다.

**Comment by sunghoon** [comment]
@veldise 어떻게 처리 되었나요? 위에 'Done' 이라고 되어 있으면 배포된 것으로 보면 되나요?

**Comment by veldise** [comment]
날짜&시간 객체에서 아래와 같이 달력만 사용하는 '날짜' 유형일 때,
달력에서 특정 날짜를 선택시 달력이 사라지도록 동작을 변경하였습니다.

![image](https://user-images.githubusercontent.com/3411842/97539747-dc699e00-1a05-11eb-8c72-836b184a55b9.png)

**Comment by sunghoon** [comment]
@eumminsun @veldise 약간 느낌은 기능동작에 대한 옵션으로 처리 해야 하지 않았을까 하는 생각이 듭니다.
