### ISSUE TITLE
[시각화] anomalies 옵션에서 alert_window 는 옵션이라 설정 자체를 on/off 할 수 있어야 합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2638]
## 버그 설명 ##
b-iris.mobigen.com demo계정

- anomalies의 alert_window 파라미터는  on/off 로 설정하게 해야 하는데, 지금은 무조건 설정하도록 되어 있습니다.
<img width="347" alt="스크린샷 2020-09-24 오후 5 21 03" src="https://user-images.githubusercontent.com/5126497/94120422-0bcb3f00-fe8b-11ea-88b0-3c03a021e855.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@eumminsun @veldise 검토 조치 바랍니다.
