### ISSUE TITLE
[앙고라] : 컬럼명이 한글일 때 띄어쓰기 오류

### ISSUE THREAD

**Issue by Minsoo-web** [mobigen/IRIS-BigData-Platform#2639]
## 버그 설명 ##

컬럼 명이 한글일 경우 

```
where 컬럼='값' 
```

이런식으로 검색하게 되면 오류가 납니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. b-iris Analyzer 검색
2. `서초 미세먼지` 데이터 모델 검색
3. * | 미세먼지 = '40' 검색
4. 정상 작동
5. * | 미세먼지='40' 검색

## 예상한 행동 ##

둘 다 똑같이 검색이 될 것이라고 예상했습니다.

## 스크린샷 ##

띄어쓰기를 하게 될 경우 한글 여부와 상관없이 정상 작동
![스크린샷 2020-09-24 오후 6 26 54](https://user-images.githubusercontent.com/57122180/94127328-bf383180-fe93-11ea-92d2-21616d89e86a.png)

붙여쓰게 될 경우 한글 컬럼만 에러 
![스크린샷 2020-09-24 오후 6 28 07](https://user-images.githubusercontent.com/57122180/94127336-c2332200-fe93-11ea-90bd-a5492da5066f.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 조치 바랍니다.

**Comment by seungfwani** [comment]
@seoryjj @anhm 
빌드 테스트 완료 하였으며,
(20.10.16) 배포요청 하였습니다.
