### ISSUE TITLE
Studio / 연동 서비스 상태 점검 프로세스 개선 요청

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2640]
![93957792-f8877900-fd8f-11ea-9e6f-298dc3fcf751](https://user-images.githubusercontent.com/512653/94218605-c3aa2c00-ff1f-11ea-8488-4caa53b1bfd2.png)

위와 같은 현상을 처리하기 위하여 아래와 같이 처리 될 수 있도록 요청드립니다.

- 연관 서비스 상태가 Offline으로 확인되는 경우 일정 시간 이후 상태확인을 다시 할 수 있도록 재시도 로직 필요
- 보고서 편집 모드 시작시 연관 서비스 상태가 Offline으로 확인되는 경우 사용자가 알수 있도록 메시지 창 동작 필요

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
모델 목록을 조회할 때 연관 서비스 상태를 확인하는 로직을 추가하도록 하겠습니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
차주 중에 처리해서 10/29 패치를 목표로 진행하겠습니다.

**Comment by sunghoon** [comment]
@veldise 어떻게 처리 되었나요?

**Comment by veldise** [comment]
@sunghoon 
데이터 모델, 연결 정보과 관련된 서비스(discovery, dsms)가 offline 상태일 때,
combo-box 를 클릭하면 해당 서비스 상태를 재확인하고 상태가 online 이면 목록 데이터를 재요청하도록 개선하였습니다.
