### ISSUE TITLE
[anomalies] 개선사항 : alg=robust  에서 period=N 을 옵션파라미터로 추가 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2641]
## 기능 요청 ##
b-iris.mobigen.com demo 계정

시험 데이터 모델 : EDU_TEST_TS

- 현재 검색어 예시

`* | where kind = '1' |  sort ctime |  fields ctime,kind,timeseries  | anomalies ctime timeseries by=kind alg=robust `

- 개선  : **period=N**

`* | where kind = '1' |  sort ctime |  fields ctime,kind,timeseries  | anomalies ctime timeseries by=kind alg=robust  period=12`

- 지금은 하드코딩으로 period=3  으로 하고 있습니다. 그리고  이 경우에는 처음,마지막 값이 Nan 이 되는데, 이를 보정하려고 마지막 라인을 하나더 추가하는 식으로 하고 있습니다. period  는  데이터에 따라 다르게 설정되어야 정확하므로, 결과의 신뢰성에 큰 영향을 줍니다. 그래서 데이터를 아는 사용자가 설정해서 넣어야 정확한 결과가 나올 수 있습니다. 

- 코드 수정안 : seasonal_decompose 에 **extrapolate_trend=N**  추가

`result = seasonal_decompose(tmp_data, period=self.period, model=self.seasonality, extrapolate_trend=self.period, two_sided=True)`

- 옵션으로 받은 period 와 같은 수를 **extrapolate_trend**  의 값으로 넣으면 Nan 을 자동 보정해서 Nan  없이 계산할 수 있습니다.
    - 그러면 코드 내부에서 **마지막 row  를 append  하는 것은 빼고** , seasonal_decompose 에 데이터를 넣어서 처리하는 방식으로 하면 됩니다.
    - 제외할 부분
 `tmp_data = data.append(data.tail(1))`

- default  는 6 ( 10분 단위  데이터이고, 주기가 1시간이라고 생각할 때 )

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 진행과 관련된 업무로 내부 계획을 수립하여 공유 바랍니다.

**Comment by seungfwani** [comment]
다른 anomalies 이슈 2개와 함께 처리해서 추석 후 배포 하도록 하겠습니다.

**Comment by seungfwani** [comment]
192.168.100.180 서버에 배포를 해놓았습니다.

![Screen Shot 2020-09-25 at 4 53 39 PM](https://user-images.githubusercontent.com/46172579/94241483-abea9c00-ff4f-11ea-9f67-f4bfbf9cfba2.png)

**Comment by sunghoon** [comment]
@eumminsun 시각화에 해당 옵션을 추가 하여야 할 것 같습니다.

**Comment by seungfwani** [comment]
추가된 옵션은 `period` 입니다.
값은 0이상의 정수가 들어갑니다.

**Comment by eumminsun** [comment]
@seungfwani period 옵션의 기본값 문의 드립니다.

**Comment by sunghoon** [comment]
기획은 진행되었고, 개발 일정 잡아서 진행 예정. 10/15 의견 바랍니다.

**Comment by eumminsun** [comment]
@sunghoon 기획 내용 공유하여 개발 진행하기로 하였습니다.

**Comment by sunghoon** [comment]
@eumminsun  목표로 하는 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
차주(10/29) 패치를 목표로 개발중입니다.

**Comment by veldise** [comment]
시각화 anomalies 기능 보강이 조금 더 필요하다고 하여, 패치노트에서 이슈 링크를 제거하였습니다.

**Comment by sunghoon** [comment]
@veldise 적용 목표일이 언제 인가요? 어떤 기능을 더 보강하는지 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
모호한 의견만 전달받은 상태라서 현재 IRIS-BigData-Platfom 에 올라온 관련 이슈들을 취합해 본 뒤에 일정 계획을 수립할 예정입ㄴ디ㅏ.
