### ISSUE TITLE
[LH빅데이터 플랫폼] 알티베이스 연동 I/F 추가

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2643]
## 기능 요청 ##
LH빅데이터 플랫폼 과제 수행을 위해 **알티베이스 연동 I/F 추가 필요**

## 원하는 솔루션 설명 ##
IRIS Discovery 메뉴의 "연결정보" 설정 기능에 알티베이스 추가 
![image](https://user-images.githubusercontent.com/4444717/94379681-f301a880-016c-11eb-9f3a-8ec9fa862b60.png)

IRIS Studio에서 DBMS 연결유형에 알티베이스 추가 
![image](https://user-images.githubusercontent.com/4444717/94379757-47a52380-016d-11eb-9967-6c9d07f01eb5.png)

**Comment by sunghoon** [comment]
@JeongHeeDong @anhm @seungfwani 업무 진행 일정을 협의 해 주시기 바랍니다.

**Comment by anhm** [comment]
@JeongHeeDong 사용하시는 알티베이스 버전 및 예정된 설치 일정등을 알려 주시면 일정에 맞춰 작업을 진행하도록 하겠습니다.

**Comment by JeongHeeDong** [comment]
@anhm 안형민 책임님,
테스트용 알티베이스가 차주 월요일(10/12) 회사 개발서버에 설치될 예정이며,
테스트용 알티베이스가 설치되면 김무성 책임께서 관련 정보 공유 예정입니다.

**Comment by sunghoon** [comment]
@안형민 미팅 내용
대략의 업무 추진 일정 완료 목표는 10/23 ~ 10/30일을 예상됨.

**Comment by sunghoon** [comment]
@JeongHeeDong 해당 기능 준비가 되었습니다. 업데이트 일정을 운영팀과 협의하여 진행해 주시기 바랍니다.
