### ISSUE TITLE
[Studio] "URL불러오기" 가 동작하지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2644]
b-iris.mobigen.com demo 계정

참고할 보고서 : EDU_URL 불러오기_안됨 http://b-iris.mobigen.com:80/studio/exported/9fc999aee7424caa82d7533bdeb079032a855829375440d8bb3216f2ce78a530

- 잘 동작하여 갤러리나 블로그에 올렸던 보고서입니다.
- URL 불러오기 대상 URL 
`http://b-iris.mobigen.com/hdfs-browser/minio/preview?path=/demo/DEMO_DATA/CHART_DATA/DEMO_OIL_Sankey.html`

- 편집화면에서 "적용" 을 누르면 보이지만, 저장 후 보고서를 실행하면 보이지 않습니다.
- 편집화면
<img width="1308" alt="스크린샷 2020-09-28 오후 1 25 43" src="https://user-images.githubusercontent.com/5126497/94390614-20128300-018e-11eb-992a-b25a6d2a53c0.png">

- 보고서 보기
<img width="1307" alt="스크린샷 2020-09-28 오후 1 10 49" src="https://user-images.githubusercontent.com/5126497/94390636-2b65ae80-018e-11eb-866f-160c350d7297.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seoryjj 
입력하신 URL에서 querystring 부분(`path=...`)에 encoding 이 되어있지 않아서 발생하는 문제입니다.
아래와 같이 입력하시면 됩니다.

```
http://b-iris.mobigen.com/hdfs-browser/minio/preview?path=%2Fdemo%2FDEMO_DATA%2FCHART_DATA%2FDEMO_OIL_Sankey.html
```

**Comment by seoryjj** [comment]
<img width="1321" alt="스크린샷 2020-09-29 오전 8 48 41" src="https://user-images.githubusercontent.com/5126497/94496899-9bc50c00-0230-11eb-9dc4-f70dad9d9575.png">


- minio 의 다운로드 링크복사, 파일보기 링크복사 로 붙인 URL 입니다.

**Comment by sunghoon** [comment]
@veldise 사용자에게 인코딩을 하라고 하는건 아닌것 같습니다. 
시스템에서 입력받은 URL 인코딩 해 주시기 바랍니다.

**Comment by veldise** [comment]
Iframe 객체가 실행/미리보기 모드에서 정상 동작을 하지 않는 버그로 재확인되었습니다.
인코딩 관련된 내용은 잘못 파악한 내용입니다. 혼란을 드려 죄송합니다.

**Comment by sunghoon** [comment]
@seoryjj 해당 보고서를 새로 저장 하였을때 정상 동작함을 확인하였습니다. 
http://b-iris.mobigen.com/studio/exported/9fc999aee7424caa82d7533bdeb079032a855829375440d8bb3216f2ce78a530

![스크린샷 2020-10-08 오전 10 40 43](https://user-images.githubusercontent.com/512653/95405435-b85cf480-0952-11eb-9a43-85964acd3bc3.png)
