### ISSUE TITLE
[ 지란지교] 사이트에서는 Analyzer 에서 fit 등 기계학습 모델링 관련 명령어를 실행하면 에러납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2645]
## 버그 설명 ##

http://192.168.102.114:30013     root 계정 ( 계정 비번은 따로 알려드리겠습니다 )

10월 7일에 지란지교에서 **IRIS  기계학습 명령어 사용 교육** 이 예정되어 있습니다. 그 전에 수정이 되길 바래 봅니다.

- 데이터모델 : EDU_TRAIN_WINE

- 검색어 : fit 수행 -> 이 검색어는 b-iris 에서 정상동작하는 것입니다.( 분석탬플릿 : **연습_와인데이터_DC_CLASSIFICATION** )

`* | scaler minmax  Alcohol to Alcohol_s,
Malic_acid to Malic_acid_s,
Ash to Ash_s, 
Alcalinity_ash to Alcalinity_ash_s,
Magnesium to Magnesium_s,
Phenols to Phenols_s,
Flavanoids to Flavanoids_s, 
Nonflavanoid_phenols to Nonflavanoid_phenols_s,
Proanthocyanins to Proanthocyanins_s,
color_intensity to color_intensity_s,
Hue to Hue_s,
OD280_OD315 to OD280_OD315_s,
Proline to Proline_s |  indexer classId to classId_s | 
fit DecisionTreeClassification FEATURES  Alcohol_s,Malic_acid_s,Ash_s, Alcalinity_ash_s,Magnesium_s,Phenols_s,Flavanoids_s, Nonflavanoid_phenols_s,Proanthocyanins_s,color_intensity_s,Hue_s,OD280_OD315_s,Proline_s   LABEL  classId_s  maxDepth=5  minInfoGain=0.0 seed=None INTO DEMO_0929_1_DC_CLASSIFICATION_WINE`

- 결과 : 에러 발생 
<img width="434" alt="스크린샷 2020-09-29 오전 11 08 54" src="https://user-images.githubusercontent.com/5126497/94504939-f2d4dc00-0244-11eb-89b4-a3c71c93425d.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 확인 바랍니다.

**Comment by seungfwani** [comment]
설정에 누락된 부분이 있었던 것으로 현재 동작합니다
