### ISSUE TITLE
[지란지교] 사이트에서 "geoip"  명령어를 사용하면 에러 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2646]
## 버그 설명 ##

 http://192.168.102.114:30013   root 계정

데이터 모델 : DCB_SUMMARY

- 검색, studio 에서 아래 검색어를 입력하면  b-iris.mobigen.com 에서는 결과가 나오고, 지란사이트에서는 에러 납니다.

`* | geoip IP ALL | where city != ''`

-  결과
<img width="279" alt="스크린샷 2020-09-29 오후 2 49 37" src="https://user-images.githubusercontent.com/5126497/94517654-5a9a1f80-0263-11eb-9758-ac9d84f8d35e.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 확인바랍니다.

**Comment by seungfwani** [comment]
설정에 누락된 부분이 있었으며, 수정하여 현재는 동작합니다.
![Screen Shot 2020-10-07 at 11 04 15 AM](https://user-images.githubusercontent.com/46172579/95279147-ea0b8800-088c-11eb-99a1-90d380efd870.png)
