### ISSUE TITLE
[서초구청] Studio: Map 검색 결과 없을 경우

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2647]
## 버그 설명 ##
Map에 동선을 표시하고 있는데 검색 결과가 없을 경우 나타나는 화면이 오류는 아닌데 오류같이 보입니다.
검색결과가 없을 경우 해당 Layer의 데이터를 모두 초기화해서 아무것도 안나오게 개선했으면 합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/95051473-430ddb80-0728-11eb-93e8-3864acb107c1.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@eumminsun 책임님 내용을 확인 후 개선을 통해 개발이 이루어 질 수 있도록 진행 바랍니다.

**Comment by sunghoon** [comment]
@veldise 이번주 패치 예정입니다.

**Comment by veldise** [comment]
@SONHOJUN 
금일 10/15 패치로 결과가 없을 경우 레이어에 그려진 도형들이 초기화됩니다.
시간 나실 때 확인 부탁드립니다.
