### ISSUE TITLE
[NMS+]IRIS 클러스터 관리 의 IRIS 상태가 실제와 맞지않음

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2648]
## 버그 설명 ##
어제 17시 경부터 NMS+의 IRIS  slave 장애가 발생하여 busy 가 떴으나
IRIS 클러스터 관리의 대시보드에서는 해당사항이 보이지않습니다.

직접 ssh 로  iris master ntop 을 확인한내용과 IRIS 클러스터관리 상태정보가 다릅니다.
장애가 나도 클러스터 관리에서 상황인지가 안됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm 지원바랍니다.

**Comment by anhm** [comment]
어떤 상황에서 발생하는지 사내 테스트를 진행해 보도록 하겠습니다.

**Comment by anhm** [comment]
로그및 테스트를 진행해본 결과 아래와 같은 결과 dashboard에서 현재 상태를 수집하지 못할 경우 기존 상태값을 유지하는 방향으로 되어 있습니다.

해당 이슈는
IRIS 전체 노드가 접속이 되지 않아 정보를 수집하지 못하는 상황에서 마지막에 수집된 정보를 보여주어서 발생한 문제로 파악이 되고 있습니다.

**Comment by sunghoon** [comment]
@eumminsun @veldise 
Web에서 정보 수집과 관련된 이슈가 발생하면 시각적으로 이슈 사항이라는것을 사용자가 알 수 있도록 조치 해 주시기 바랍니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
IRIS-DB 로부터 데이터를 수집하지 못한 경우 UI 에 무언가 장애 상황을 표시하는 쪽으로 진행하기로 하였습니다.

**Comment by sunghoon** [comment]
@veldise 목료로 하는 일정정보를 공유해 주세요.

**Comment by rhcpn** [comment]
해당 이슈는 11월 Development 업무로 진행 예정입니다.
정확한 일정은 추후 재 등록 하겠습니다.

**Comment by sunghoon** [comment]
@rhcpn 일정 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
12/3 Release 를 목표로 개발 진행중입니다.

**Comment by veldise** [comment]
@sunghoon 
LH공사 요구사항(네트워크 차트)을 우선 처리하기로 하여 일정을 1주일 연기하였습니다.
목표를 12/10 패치로 재설정하였습니다.

**Comment by veldise** [comment]
@sunghoon 
LH공사 추가 요구사항을 우선 처리하기로 하여 일정을 추가로 1주일 연기했습니다.
- https://github.com/mobigen/IRIS-BigData-Platform/issues/2720
- https://github.com/mobigen/IRIS-BigData-Platform/issues/2713

**Comment by sunghoon** [comment]
R: 20.12.17 일정은 준수 할 수 있도록 본 이슈에 대한 관리도 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈에 대한 처리는 어떻게 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
국토부 일정으로 인해 연기되었습니다. 해당 처리는 2021.01.07 패치를 목표로 진행하겠습니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈에 대한 처리는 어떻게 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
개발은 완료되었습니다만 아직 NMS+에 배포되지는 않았습니다. 이번에 요구사항 2개가 처리되면 같이 배포할 생각입니다.

**Comment by sunghoon** [comment]
@veldise 요구사항 2개 처리에 대한 일정 계획은 어떻게 수립되어 있나요?

**Comment by veldise** [comment]
@sunghoon 
현재 개발 진행중이며 늦어도 2월 중순에는 배포까지 하는 것을 목표로 하고 있습니다.
차트 영역형(area) 추가의 경우에는 퍼블리싱 일정이 2/9까지라서 조금 늦게 완료될 것 같습니다.

차트 실행중 표시 방식 개선: https://github.com/mobigen/IRIS/issues/307
차트 영역형 유형 추가: https://github.com/mobigen/IRIS/issues/310

**Comment by sunghoon** [comment]
@rhcpn @veldise 해당 이슈 처리 어떻게 진행되고 있나요?

**Comment by veldise** [comment]
@sunghoon 
개발 완료되어 운용팀에서 NMS+ 에 배포(업그레이드) 작업을 협의/진행중입니다.
