### ISSUE TITLE
[문의] angora, DSL 관련 에러 구문이 전부 "작업 수행에 오류가.." 로만 나와서 무엇이 문제인지 알수가 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2649]
## 기능 요청 ##
b-iris.mobigen.com  demo계정

- Analyzer  명령어에서 date_group 에 작은 따옴표를 해야 하는데, 안 하면 원래 에러가 납니다.
`* | where HOST = 'hadoop02' |  pivot count(*) SPLITROW date_group("DATETIME", "10M")  SPLITCOL HOST,LEVEL CASESENSITIVE True COLSIZE 500 SORTROW asc`

<img width="930" alt="스크린샷 2020-10-08 오전 11 13 22" src="https://user-images.githubusercontent.com/5126497/95407314-a16cd100-0957-11eb-90b4-32fc169f8af8.png">

- 이 문구는 angora 가 서비스다운일 때도 발생하는 에러문구이기도 해서, 명령어 구문이 잘못 되서 난 에러인데 그걸 알기 어렵습니다.
- 작은 따옴표 넣어서 실행하면 바로 결과가 나옵니다. "  **검색어 구문에러** 로  date_group 함수는 작은 따옴표 필요.."  등으로  명시가 되면 좋겠습니다.
<img width="912" alt="스크린샷 2020-10-08 오전 11 20 22" src="https://user-images.githubusercontent.com/5126497/95407572-54d5c580-0958-11eb-8698-e6d9fcfc549d.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 검토해 주세요.
