### ISSUE TITLE
[studio] "기간설정" 에서 시간간격 설정 후 화살표로 이동하면 종료시간만 이동하면서 팝업창이 뜹니다.(초기날짜인 경우)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2650]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 참고 보고서 : EDU_기간설정_Beijing

- 사용자지정으로 2013/03/01  00:00:00 ~ 2017/03/01 00:00:00  까지 제한
- 시간 간격 1시간
- 초기 날짜 
<img width="552" alt="스크린샷 2020-10-08 오후 1 03 15" src="https://user-images.githubusercontent.com/5126497/95413549-af761e00-0966-11eb-88f9-8f648d16b203.png">

- 화살표 < 로 이동하면 종료날짜만 이동하면서 시작 날짜와 같아지면서 팝업창이 뜹니다.
<img width="221" alt="스크린샷 2020-10-08 오후 1 01 03" src="https://user-images.githubusercontent.com/5126497/95413596-c4eb4800-0966-11eb-830f-6a10a0f85f5c.png">

- 초기 날짜 그대로인 상태에서 화살표 < 로 하면 종료 날짜만 바뀌면서 에러납니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
연결된 이슈 입니다. 
https://github.com/mobigen/IRIS-BigData-Platform/issues/2378

**Comment by sunghoon** [comment]
@eumminsun UX 개선을 요청드립니다.

**Comment by sunghoon** [comment]
10/15 의견 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
기간 설정 객체의 동작이 전반적으로 심각한 문제가 있는 것으로 생각됩니다.
먼저 동작을 전체적으로 점검하고 버그 사항을 정리한 뒤 처리를 진행하겠습니다. 다른 일정을 연기하고 바로 진행할 계획입니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정을 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon
늦어도 차주 화요일(10/22)까지는 버그/개선 항목들을 정리하고, 일정 계획이 수립되면 바로 알려드리겠습니다.

**Comment by sunghoon** [comment]
veldise 목표로 하는 일정을 공유해 주세요.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정을 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
기획과 디자인 수정도 필요하여, 11/12 패치를 목표로 정했습니다.

**Comment by veldise** [comment]
@sunghoon 
이슈 본문에 해당하는 부분은 11/5 패치 예정입니다.

- 기간 설정 / 시간을 텍스트 입력으로 설정한 후, 시간 이동 버튼(<, >)을 클릭하면 비정상 동작하는 버그 수정
