### ISSUE TITLE
[Studio] 그래포 축 제목 색상이 변환이 안돼요

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2651]
## 기능 요청 ##
문제가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.

그래프 y축과 x축의 제목 색상은 변경이 안됩니다.
## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

축에 글씨색상을 바꾸는 것처럼 제목 색상도 바꿀 수 있게 해주셨으면 좋겠습니다.
![image](https://user-images.githubusercontent.com/50221479/95422131-ba867980-0979-11eb-8242-61d08c9f8c8f.png)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
재현을 위한 Flow  혹은 보고서를 알려주시면 업무에 참고하도록 하겠습니다. 
간단한 형태로 상황 재현을 해 보려고 하였을때는 재현되지 않고 있습니다.

**Comment by handayeon** [comment]
차트 위에서 마우스 오른쪽 클릭 후 시각화 옵션에 들어가셔서 X축 선택하시면 보이는 화면입니다 !

**Comment by seoryjj** [comment]
<img width="1076" alt="스크린샷 2020-10-15 오후 3 25 17" src="https://user-images.githubusercontent.com/5126497/96084797-ace16e80-0efa-11eb-8c0a-07304a9ce7ae.png">

챠트 배경색을 진한 색으로 바꾸면, X축 , Y 축 데이터의 색은 글꼴에서 흰색으로 변경이 가능하지만,
**축 제목** 은 변경 기능이 없어서 진회색으로 그대로 보입니다.(여기서는 "연도" 라는 글)
축의 값 외에 축 제목도 같이 색상 변경 기능이 필요하다는 내용입니다.

**Comment by sunghoon** [comment]
@veldise 내용을 확인하여 조치해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
기획은 진행중이고 개발쪽은 일정 계획을 수립 중입니다. 차주 월요일(11/23)에는 정리해서 말씀드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
12/17 패치를 목표로 진행하겠습니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈에 대한 처리는 어떻게 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
국토부 일정으로 인해 연기되었습니다. 해당 처리는 2021.01.07 패치를 목표로 진행하겠습니다.

**Comment by sunghoon** [comment]
@veldise  해당 이슈 어떻게 조치 되었는지요?

**Comment by veldise** [comment]
@sunghoon 
'축 제목 글꼴' 설정 기능을 추가하는 방향으로 개발 완료되었고 차주(1/28) 패치 예정입니다.
