### ISSUE TITLE
URL 불러오기가 동작하지 않습니다.

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2652]
## 버그 설명 ##
기존에 동작하던 URL 불러오기가 동작하지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
보고서: 입찰공고 상세보기_v0.2 -test

*
| fields bidNtceNo, BIDNTCEORD, BIDNTCEDTLURL
| concat bidNtceNo, BIDNTCEORD as 입찰번호
| where 입찰번호 = '2020100545400'
| fields 입찰번호, BIDNTCEDTLURL

기존에는 아래 검색어로 값을 전달받아 열리는 형태입니다.
재현을 위해 입찰번호를 입력하였습니다.
(기존: | where 입찰번호 = '${bidNtceKey_1}')

## 예상한 행동 ##
![image](https://user-images.githubusercontent.com/5077625/95431305-ed376e80-0987-11eb-928f-311e4244bd19.png)
노란색 음영 주소 페이지를 보여줍니다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@euhyesun 문제를 확인하였습니다.

@veldise 빠른 조치 바랍니다.

**Comment by veldise** [comment]
금주(10/15) 패치 예정입니다.

**Comment by veldise** [comment]
패치되어 정상 동작합니다. 최초에 400 에러 페이지가 뜨는 것은, Iframe 객체가 "자동 실행" 설정이 되어있기 때문입니다.

![image](https://user-images.githubusercontent.com/3411842/96058401-109d7480-0ec6-11eb-9fea-417e8c53db8f.png)
