### ISSUE TITLE
timediff 명령에 옵션 추가 요청

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2653]
* timediff 적용시에 now 또는 today 같은 옵션 추가 (https://github.com/mobigen/IRIS-BigData-Platform/issues/1885)

* 사용 예
```sh
* | typecast DATETIME timestamp "YYYYMMDDHHmmss" | timediff minute 'now' "YYYYMMDDHHmmss" 'DATETIME' | where < 40
```

**Comment by seungfwani** [comment]
b-iris 에서 확인 완료 했습니다

![스크린샷 2020-12-18 오후 1 16 13](https://user-images.githubusercontent.com/46172579/102574336-dbb2d580-4133-11eb-8bbd-62860734d707.png)
![스크린샷 2020-12-18 오후 1 15 55](https://user-images.githubusercontent.com/46172579/102574340-dd7c9900-4133-11eb-8437-3a339abdd859.png)
