### ISSUE TITLE
[Studio] "텍스트입력" 에서 유형이 password 일 때, 편집화면의 전체변수명보기에서는 영어로 자동변환되어 보이지만, 실행화면에서는 자동변환이 아닙니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2654]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

참고할 보고서 :  "이슈_텍스트입력" 
http://b-iris.mobigen.com:80/studio/exported/e59131c6928c4c50b6ed887ba83dcec893c849f653274d45bc19fd43173510e6

studio - 텍스트입력 객체 - password유형

- 편집화면에서 한글로 이름을 쓴 후 그대로 password 유형의 텍스트 입력(input_2) 에 입력하면, 전체변수명 보기에서 영어로 자동 변환되어 보입니다.

<img width="530" alt="스크린샷 2020-10-14 오전 8 30 35" src="https://user-images.githubusercontent.com/5126497/95927348-6bb56580-0df9-11eb-8c9f-68c9c9aceae6.png">

- 실행 화면에서 변수 input_1, input_2, input_3 를 표시하면 영어 자동 변환 없이 한글로 표시되어 나옵니다.
<img width="1042" alt="스크린샷 2020-10-14 오전 8 31 36" src="https://user-images.githubusercontent.com/5126497/95927383-812a8f80-0df9-11eb-90cf-4f689eb99b3c.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 키보드 한영 설정에 맞게 입력되어야 할 것 같습니다. 이슈에 대한 분석 및 확인 후 조치 계획을 알려주시기 바랍니다.

**Comment by veldise** [comment]
@seoryjj 
먼저 studio 에 영문을 자동 변환해주는 기능은 없습니다.
또한 2번째 password 유형의 객체에 한글로 직접 입력을 하거나, 한글 텍스트를 복사-붙여넣기 하였을 때 정상 동작하는 것으로 보입니다.

![image](https://user-images.githubusercontent.com/3411842/96228538-ade4cf80-0fd0-11eb-8481-b39d82202152.png)

자세한 재현 방법이나 이슈 재확인을 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 해당 내용에 대하여 구두로 직접 현상에 대한 설명 및 재현을 하였습니다.

**Comment by veldise** [comment]
@seoryjj 
편집 화면에서만, password 유형의 객체를 선택하면 한영 입력이 전환되는 것을 확인했습니다.

**Comment by sunghoon** [comment]
@veldise 목표로 하는 일정을 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
일단 11/5 패치를 목표로 진행중입니다.

**Comment by veldise** [comment]
@seoryjj 
먼저 password 유형의 input box 로 이동했을 때 키보드 입력이 영문으로 변경되는 것은 브라우저 기본 동작입니다. (모든 브라우저가 동일)
그런데 MacOS / Chrome 환경에서만 키보드 입력이 전환되지 않고 있습니다.
chrome 브라우저 버그로 추측되는데 아직 관련 글이나 자료를 찾지 못했습니다.

**Comment by sunghoon** [comment]
@seoryjj 최종 확인결과, 브라우저에서 보고하신 이슈가 있는것을 확인하였으며, 딱히 다른 방안을 제안하는것도 없는 상태입니다. 
아래의 정보를 참고하시고, 본 이슈는 닫도록 하겠습니다.
https://stackoverflow.com/questions/50114072/google-chrome-macos-password-field-wont-accept-non-ascii-characters
