### ISSUE TITLE
[NMS+]보고서에서 사용한 쿼리 덤프요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2656]
## 기능 요청 ##
SKB 고객이 보고서에서 사용한 쿼리를 덤프받고 싶다고 합니다.

사유 : 보고서마다 작성한 쿼리가 어떤것이 있는지 일일이 보고서를 클릭해야 알수있고

사용했던 DSL 문법등도 다 기억할수가 없어서 현재까지의 보고서에 작성된 쿼리덤프를 받아보고 싶다고 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@jjinylee 일회성으로 필요한 기능인가요? 아님 보고서에서 쿼리 덤프를 받고 싶은 건지요?

**Comment by jjinylee** [comment]
기능요청을 하는게 아니고 일회성으로 현재 보고서에서 사용된 쿼리 덤프 요청입니다.

**Comment by sunghoon** [comment]
@jjinylee 네. 해당 업무를 박세종 팀장님에게 구두 전달 하다록 하고, 본 이슈는 닫아 두겠습니다.
