### ISSUE TITLE
Studio/보고서 리스트 필터기능 개선

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2657]
## 기능 요청 ##
보고서 리스트의 수가 많아진 경우 내가 원하는 보고서 찾기가 힘듬.
내가 보고싶지 않은 보고서는 제외하여 리스트를 볼 수 있는 기능 필요

## 원하는 솔루션 설명 ##
필터조건에 포함하는 조건과 별도로 제외하고 조회 할 수 있는 기능 필요

예시) demo 계정으로 생성된 보고서는 제외하고 보고 싶음
![image](https://user-images.githubusercontent.com/4444717/95970368-d5aa2b00-0e4a-11eb-89e4-1a599f5fb29c.png)

**Comment by sunghoon** [comment]
@JeongHeeDong 요구하신 내용은 아주 중요하거나 크게 필요한 기능은 아닌거 같아 보이는데요 ^^
