### ISSUE TITLE
[Discovery] 동일검색조건으로 데이터모델은 결과가 나오지만, 데이터모델 뷰는 결과 에러("작업수행에 오류가...") 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2658]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 데이터모델 뷰  :  EDU_VIEW_syslog  
- 데이터모델 tylor_syslog   에서 **최근 2주**  로 만든  모델뷰
<img width="795" alt="스크린샷 2020-10-16 오전 10 59 40" src="https://user-images.githubusercontent.com/5126497/96204338-01d6c080-0f9f-11eb-8ddd-1458dcdd0bc2.png">

- 데이터모델 뷰에서 같은 시간 조건, 같은 검색어 결과는 에러 납니다.  분석탬플릿 "이슈_모델뷰검색_에러결과_2016"  참고하세요.
- 약 1분 후에 에러 팝업창이 나옵니다.
<img width="645" alt="스크린샷 2020-10-16 오전 10 58 36" src="https://user-images.githubusercontent.com/5126497/96204641-c983b200-0f9f-11eb-9508-b66fa038eabb.png">

- 같은 시간, 검색어로 원본 데이터모델은 결과가 나옵니다. 분석탬플릿 "이슈_데이터모델검색_정상결과_2016"  참고하세요
<img width="1117" alt="스크린샷 2020-10-16 오전 10 59 13" src="https://user-images.githubusercontent.com/5126497/96204741-03ed4f00-0fa0-11eb-9c68-6747a0048794.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 조치 바랍니다.

**Comment by sunghoon** [comment]
@seungfwani 진행 상황 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
@seoryjj 
아래 두 서버에서 같은 동작이 정상 수행이 되는 듯 보이는데 혹시 다른 조건이 있을까요?

- 192.168.100.180
![Screen Shot 2020-10-21 at 9 55 26 AM](https://user-images.githubusercontent.com/46172579/96660062-8f415880-1383-11eb-808f-236a3c06225e.png)

- b-iris.mobigen.com
![Screen Shot 2020-10-21 at 9 57 05 AM](https://user-images.githubusercontent.com/46172579/96660150-c879c880-1383-11eb-8ee8-0330726a0931.png)

**Comment by veldise** [comment]
@seungfwani 
192.168.100.180 은 곧 폐기될 서버입니다. 현재 구버전이 동작하고 있습니다.

**Comment by sunghoon** [comment]
@seoryjj @seungfwani @veldise b-iris 기준으로만 보시는것으로 하시고, b-iris에서도 계속 이슈가 된다면 이슈를 재오픈해 주세요.
