### ISSUE TITLE
[Studio] 보고서 검색시 오류가 발생합니다.

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2659]
## 버그 설명 ##
기존에 동작하던 보고서인데 현재 검색시 아래와 같이 오류가 발생합니다.
![image](https://user-images.githubusercontent.com/5077625/96389841-9b46e200-11ec-11eb-8639-497e398f8dd4.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :
 보고서명: [용역] 공공조달_공고 목록_v1.7 
 전체조회 선택

**Comment by veldise** [comment]
Discovery 쿼리 1:
```
model name = 'EPS_DATA_BIS' model_owner = root start_date = 20200101000000 end_date = 20201019235959
 | fields preRgstDt as 날짜, STATE as 구분, dminsttNm as 수요기관, bidNtceNo as 입찰공고번호, bidNtceOrd as 차수, prdctClsfcNoNm as 품명, preAsignBdgtAmt as 배정예산금액, sucsfbidMthdNm as 낙찰방법, bidNtceDtlUrl as 입찰공고URL, untyCntrctNo as 통합계약번호, thtmCntrctAmt as 계약금액, cntrctCnclsMthdNm as 계약체결방법, MAINCONTRACTOR as 계약업체, BIDWINNRNM as 낙찰업체,  is_process as 워드클라우드, term_frequency as 워드, frequency_num as 카운트 
 | where 구분 = '입찰' or 구분 = '계약' 
 | where 수요기관 is not null   
 | concat 입찰공고번호, 차수 as 입찰번호 
 | substr 날짜 1 8 as 일자 
 | calculate (계약금액/배정예산금액)*100 as 낙찰률(%)  
 | fields 구분, 일자, 입찰공고번호, 차수, 입찰번호, 품명, 배정예산금액, 수요기관, 낙찰방법, 통합계약번호, 계약금액, 낙찰률(%), 계약체결방법, 낙찰업체, 계약업체, 입찰공고URL, 워드클라우드, 워드, 카운트 
 | where 1=1
```
Discovery 쿼리 2:
```
model name = 'EPS_DATA_BIS' model_owner = root start_date = 20200101000000 end_date = 20201019235959
 | fields preRgstDt as 날짜, dminsttNm as 수요기관, STATE as 구분, bfSpecRgstNo as 사전규격등록번호, prdctClsfcNoNm as 품명, preAsignBdgtAmt as 배정예산금액 
 | where 수요기관 is not null
 | where 구분 = '사전규격'  
 | substr 날짜 1 8  as 일자 
 | fields 구분, 일자, 사전규격등록번호, 품명, 배정예산금액, 수요기관 
 | where 1=1
```

http request body (예시):
```json
{
    "q": "<Discovery 쿼리>",
    "cached": false,
    "force": true,
    "size": 10000
}
```
http response:
```json
{
    "message": "angora error: <class 'TypeError'>\n(\"__init__() missing 1 required positional argument: 'stackTrace'\",)"
}
```

Discovery 에서 TypeError 가 반환되고 있습니다. 자세한 확인이 필요합니다.

**Comment by seungfwani** [comment]
수정 되었습니다.
![Screen Shot 2020-10-19 at 7 34 12 PM](https://user-images.githubusercontent.com/46172579/96439856-12f32c00-1242-11eb-9ecb-b865ecdf11f8.png)

**Comment by euhyesun** [comment]
@seungfwani 수요기관 입력후 검색하여 전체 조회시 아래와 같이 오류가 발생합니다.
![image](https://user-images.githubusercontent.com/5077625/96526830-a582e200-12b9-11eb-82e2-168bef7970b6.png)
확인 부탁드립니다. 감사합니다.

**Comment by seungfwani** [comment]
where 명령어에서 `equal` 의 의미를 가진 문자는 `=` 입니다.
`==` 는 프로그래밍 언어적으로 이퀄을 나타냅니다. 해당 부분을 수정해야할 듯 합니다.

- 에러 원인
![Screen Shot 2020-10-20 at 10 51 09 AM](https://user-images.githubusercontent.com/46172579/96530336-c1b15f80-1276-11eb-9c0c-51eafcc7aa93.png)
![Screen Shot 2020-10-20 at 10 51 30 AM](https://user-images.githubusercontent.com/46172579/96530349-cc6bf480-1276-11eb-926d-c8c48da1b48f.png)

- 해당 부분 수정 후 동작 확인
![Screen Shot 2020-10-20 at 10 53 17 AM](https://user-images.githubusercontent.com/46172579/96530461-089f5500-1277-11eb-8f06-efdd3bcf49d6.png)

**Comment by euhyesun** [comment]
@seungfwani 네, 확인했습니다. 감사합니다.
