### ISSUE TITLE
[서초구청] Studio: Map 새로고침 깜박임 현상

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2660]
## 기능 요청 ##
Map(OSM)에서 새로고침 또는 조회 시 깜박임 현상에 대한 개선 요청(서초구청 담당 주무관님 요청)

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 해당 이슈 대응을 위한 계획 정보를 공유해 주세요....

**Comment by veldise** [comment]
@sunghoon 
일단 다른 우선순위 0번을 먼저 처리하고 나서 진행하기로 하였습니다.
협의에 따라 11.05 릴리즈에서 개선될 예정입니다.
