### ISSUE TITLE
[Analyzer/Studio] ROUND 문 결과가 Analyzer, Studio 가 다르게 보입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2661]
## 기능 요청 ##
b-iris.mobigen.com  demo 계정

데이터모델 : EDU_TRAIN_WINE  
참고 보고서 :  IRIS_EDU_20201016 
http://b-iris.mobigen.com:80/studio/exported/d991c35f68ad4a9c84fbefbf5278940dfa242b5afa664c69ad39b74119f23da2

- 개인설정 : 소수점 3
<img width="353" alt="스크린샷 2020-10-19 오후 2 27 53" src="https://user-images.githubusercontent.com/5126497/96405423-373a1300-1218-11eb-9741-0b80774ee625.png">

- 검색어  :  round [5,5]  toString=True  옵션 적용
```
* | stats  count(*) as CNT, avg(Alcohol) as 평균_Alcohol, max(Malic_acid)  as 최대값_Malic_acid  by classId  |  sort classId 

| round  [5,5] col=[평균_Alcohol, 최대값_Malic_acid] toString=True
```

- Studio
<img width="506" alt="스크린샷 2020-10-19 오후 2 31 46" src="https://user-images.githubusercontent.com/5126497/96405575-8e3fe800-1218-11eb-9d22-d4c85568decb.png">

-Analyzer
<img width="933" alt="스크린샷 2020-10-19 오후 2 37 51" src="https://user-images.githubusercontent.com/5126497/96405635-b0d20100-1218-11eb-8464-7646e96cdd5b.png">

-  별도 제안 : round 문이 있을 때는  toString=False 에서도 개인 설정보다는 round 문의 결과가 우선이 되는 방법이 있었으면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@sunghoon 
11/19 패치를 목표로 진행중입니다.

**Comment by veldise** [comment]
@sunghoon 
생각보다 빠르게 처리되어 금주(11/12) 패치 예정입니다.
