### ISSUE TITLE
[IBP] 관리자의 사용자 관리 기능 그룹 지정 기능 오류

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2662]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
가입되어 있는 일반 사용자의 계정 정보 수정시 슈퍼 유저 임에도 불구하고 비밀번호를 확인합니다.
슈퍼 사용자가 일반 사용자의 계정 정보를 수정시에는 비밀번호 확인 로직이 제외되고 수정이 되어야 할 것 같습니다.

ex) 기존 계정의 그룹 미지정인경우 그룹 지정을 다시 하기 위해 계정 정보를 수정할때 비밀번호 확인 로직을 수행함

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/96424397-9d815e80-1235-11eb-9661-baf32a75e90a.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@eumminsun 관련된 내용을 확인해 주시고 사용자 정보 업데이트 Flow 개선을 요청드립니다.

**Comment by veldise** [comment]
@sunghoon 
처리 완료되어 11/5 패치 예정입니다.
