### ISSUE TITLE
[Discovery] 새모델뷰 생성 시 에러가 나야 할 검색어구문인데, 에러는 없이 계속 실행중으로만 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2663]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 대상 데이터모델 : EDU_SEOUL_DAY_AIR_201910_202010
- 모델 뷰 생성 시 잘못 입력한 검색어 : concat 연결 문자에 싱글따옴표로 잘못 입력함
`* |  substr YYYYMMDD -4 as MMDD | concat LOC, '_', MMDD  as K_STR`

- 상태 : 30초 이상 계속 이 상태입니다.
<img width="799" alt="스크린샷 2020-10-20 오전 8 37 59" src="https://user-images.githubusercontent.com/5126497/96523431-a9f6cd00-12b0-11eb-9c6e-7d9d87b34899.png">

- Analyzer  에서는  바로 에러가 납니다.
<img width="187" alt="스크린샷 2020-10-20 오전 8 47 19" src="https://user-images.githubusercontent.com/5126497/96523508-e1fe1000-12b0-11eb-8f28-b7ea6a3b59ce.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise Front 기반으로 예외 처리가 되어 있는지 확인 후 정보 공유 부탁드립니다.

**Comment by veldise** [comment]
@sunghoon 
에러를 처리하는 코드에 잘못된 부분을 확인했습니다. 금주(10/22) 패치에 포함시키겠습니다.
