### ISSUE TITLE
[DSL] Anlayzer 에서  시간필드가 YYYYMMDD 인 데이터로 anomalies 실행을 하면, 에러없이 "No Rows to show" 구문만 출력됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2664]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 데이터모델 : EDU_DEMO_SEOUL_AIRQ_2019_2020
- 검색어
`* | where YYYYMMDD >= 20200301 |  sort YYYYMMDD  | anomalies  YYYYMMDD PM10 by=LOC`

- 결과 화면
<img width="924" alt="스크린샷 2020-10-21 오전 8 06 07" src="https://user-images.githubusercontent.com/5126497/96653737-bba1a880-1374-11eb-81ba-ac801276b5e2.png">

- 데이터의 특징 : 시간 필드인 YYYMMDD 는  포맷이 YYYYMMDD 인 날짜만 있는 시간필드입니다.
<img width="926" alt="스크린샷 2020-10-21 오전 8 11 18" src="https://user-images.githubusercontent.com/5126497/96653860-04f1f800-1375-11eb-965d-3b6c60697050.png">

- 데이터모델 필드
<img width="713" alt="스크린샷 2020-10-21 오전 8 25 02" src="https://user-images.githubusercontent.com/5126497/96654763-f60c4500-1376-11eb-9715-f1e784aa2f64.png">

- 참고로 typecast 로 YYYYMMDDHHmmss 로 타입변경을 하면 결과가 나옵니다.
<img width="929" alt="스크린샷 2020-10-21 오전 8 24 05" src="https://user-images.githubusercontent.com/5126497/96654678-ceb57800-1376-11eb-9ffc-87193a4fc06c.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
@seoryjj 
`index_type=Date` 옵션을 추가해보시기 바랍니다.

```
* | where YYYYMMDD >= 20200301 | sort YYYYMMDD | rename YYYYMMDD CTIME | anomalies CTIME PM10 by=LOC index_type=Date
```
