### ISSUE TITLE
[Analyzer] 기계학습 관련 명령어는 데이터 건수가 500개 이상이 일반적인데,  실행결과의 확인 자체가 안됩니다. 옵션으로 개수를 조정할 수 있게 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2665]
## 기능 요청 ##
b-iris.mobigen.com  demo 

-  해당데이터로  anomalies 의  실행목적이 25개 구의 트랜드와 이상치를 비교하는 것이기 때문에  500 개로 기간을 줄이면 1/10 도 안되는 기간으로 조회해야 하므로 정확도가 떨어집니다.
- 구별 비교를 하는 것이기 때문에 1개 챠트로 전체 구의 트랜드를 보여줘야 합니다.

- 5825  개의 결과를 보여줘야 합니다. 하지만 500 개 결과만 보여주기 때문에 25개 구별 비교를 해야 하는데, 3개구에 그 중 1개구는 일부데이터로만 결과가 표시되며, 시각화도 500개 결과만 보입니다.
<img width="921" alt="스크린샷 2020-10-21 오전 8 31 40" src="https://user-images.githubusercontent.com/5126497/96655313-1f79a080-1378-11eb-903b-6ce067f98fde.png">

<img width="924" alt="스크린샷 2020-10-21 오전 8 31 16" src="https://user-images.githubusercontent.com/5126497/96655314-21436400-1378-11eb-8305-c8667e31be16.png">

- 강북구는 4월3일 까지의 데이터만 표시됩니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
해당 내용은 개발자와 이야기 하였으며 바로 지원 합니다. 본 이슈는 닫겠습니다.
