### ISSUE TITLE
[DSL] anomalies  robust 옵션을 넣으면 에러납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2666]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

메뉴얼에 있는 동일 데이터 모델 : EDU_Beijing_air_2013_2017_18   을 사용

- 검색어
`* station='Changping' |where year = 2016 |  anomalies CTIME PM2_5  alg=robust index_type=timestamp`

- 에러 발생함

- 동일한 데이터로 basic 은 정상 동작
`* station='Changping' |where year = 2016 |  anomalies CTIME PM2_5  alg=basic index_type=timestamp`

<img width="1058" alt="스크린샷 2020-10-21 오전 10 42 06" src="https://user-images.githubusercontent.com/5126497/96662773-142f7080-138a-11eb-8b78-b6dc5d354874.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
robust 알고리즘 additive 는 target 필드에  null 값이 있으면 exception 이 나는데, 이걸 에러 구문으로 출력할 수 있을까요?
- target 데이터에 null 이 있습니다.(seasonality = additive 에서는 null 을 제외해야 합니다)
- target 데이터에 0 값이 있습니다.(seasonality = multiplicative 에서는 0 을 제외해야 합니다)

제가 일단 manual 에서 robust 일 때 예제 부분에 내용을 보완해서 수정하긴 했는데, 에러 구문으로 넣어야 명확하게 인지가 될 거 같아서요.

**Comment by sunghoon** [comment]
@seungfwani 본 이슈에 대한 의견 주세요.

**Comment by seungfwani** [comment]
각각의 경우에 적절한 에러메세지를 반환 할 수 있도록 코드 수정 하겠습니다.

그러나, 현재 UI 에서는 앙고라의 에러 발생 내역을 `수행중 내부오류...` 로 고정이 되어 나타나기 때문에 이 부분에 대한 처리는 에러 처리 관련 설계가 필요합니다.

**Comment by sunghoon** [comment]
@seoryjj 위에 명령어를 아래와 같은 방식으로 처리 해서 사용하시면 될 것 같습니다. 
```
* station='Changping' |where year = 2016 | where PM2_5 is not null | anomalies CTIME PM2_5 alg=robust index_type=timestamp```

두번째는 0을 제외해 주시면됩니다. 

에러 메시지 관련해서는 적절한 표현이 될 수 있도록 별도 이슈로 다루고, 본 이슈는 닫도록 하겠습니다.
