### ISSUE TITLE
[Analyzer] outlier 결과의 시각화탭에서 시간필드(timestamp) 의 날짜가 정확하게 표시되지 않습니다.(1970-01-01 로 나옴)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2667]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
b-iris.mobigen.com demo 계정

시간필드인 DATETIME  가 시각화 챠트에서 장확하게 표시되지 않습니다.

- 데이터모델 : tylor_syslog
- 시간 : 2020/10/21 09:00:00 ~ 2020/10/21 13:58:08
- 검색어
`* |   interpolation count(*) as CNT
                  by=HOST
                  index=DATETIME
                  index_format='YYYYMMDDHHmmss'
                  interval=10M
                  fillna=0
                  start_date='20201021120000'
                  end_date= '20201021130000' | sort DATETIME |  typecast DATETIME timestamp |   outlier  CNT by=HOST  alg=mad`

- 결과 : 시각화탭(그래프 의 시간이 잘못 나옵니다)

<img width="1214" alt="스크린샷 2020-10-21 오후 2 12 47" src="https://user-images.githubusercontent.com/5126497/96676232-d93c3580-13a7-11eb-8af1-5adccd996cd7.png">

- 결과 : 통계탭

<img width="1281" alt="스크린샷 2020-10-21 오후 2 56 57" src="https://user-images.githubusercontent.com/5126497/96678954-adbc4980-13ad-11eb-8347-9b82391d2bbb.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@sunghoon 
'별칭' 기능을 사용한 데이터 모델을 대상으로 수행할 경우 발생하는 것을 확인했습니다. UI 버그입니다.

**Comment by veldise** [comment]
11/12 패치를 목표로 진행중입니다.
