### ISSUE TITLE
[DSL] interpolation 과  stats 의 결과가 다른 case 가 있습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2668]
## 기능 요청 ##
b-iris.mobigen.com demo 계정

- interpolation 사용 예제 분석 탬플릿 :  이슈_interpolation_ans41예제
- stats 사용 예제 분석 탬플릿 : 이슈_stats_ans41예제

12:00  일 때 ans41 이  stats 일 때는 47,  interpolation 일 때는 58 로 나옵니다.
실제 ans41 건수는 47 이 맞습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 점검 바랍니다.

**Comment by sunghoon** [comment]
@anhm 진행 일정 계획 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
12/17(목) 배포예정입니다.

**Comment by seungfwani** [comment]
1. interpolation 사용 예제 분석 탬플릿 : 이슈_interpolation_ans41예제
  - 시간 설정이 다르게 되어있는 것을 주목해주세요
  - 2번과 비교를 해보면 모델의 시간 설정을 넓게 하고, interpolation 명령어에 시간 설정을 하였는데,
  - 현재 syslog-eva 의 iris 테이블을 확인해보니, partition설정이 잘못되어있습니다.
  - 그래서 2번에서 stats 와 같은 시간 설정을 기준으로 검색하면 같은 결과가 나옵니다.
![Screen Shot 2020-12-18 at 1 11 40 PM](https://user-images.githubusercontent.com/46172579/102573930-ef117100-4132-11eb-9f7a-d85d934ac231.png)

2. 시간 설정을 바꾼 interpolation
![Screen Shot 2020-12-18 at 1 12 16 PM](https://user-images.githubusercontent.com/46172579/102573935-f173cb00-4132-11eb-8f47-9135e3709fd5.png)

3. stats 사용 예제 분석 탬플릿 : 이슈_stats_ans41예제
![Screen Shot 2020-12-18 at 1 12 27 PM](https://user-images.githubusercontent.com/46172579/102573937-f2a4f800-4132-11eb-952b-6fb2de6a009a.png)
