### ISSUE TITLE
[studio]라벨을 클릭할 때마다 크기가 줄어듭니다

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2670]
## 버그 설명 ##
라벨을 클릭할 때마다 크기가 줄어듭니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 메뉴바에 들어가셔서 라벨을 클릭하신 다음
2.대시보드에 생성해주세요
3.글씨를 적고 다음 꾸미기 옵션에서 배경색을 지정해줍니다.
4.객체를 이동시켜 보시면 줄어듭니다. (클릭하셔도 돼요)

## 예상한 행동 ##
크기가 변하지 않고 이동

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/50221479/97124174-613c8980-1772-11eb-8bb1-6b5628180f8d.png)

## 기타 ##
b-iris.mobijen.com 스튜디오에서 "이슈_라벨_한다연" 참고해주세용

**Comment by sunghoon** [comment]
@veldise 이슈 확인 바랍니다.

**Comment by sunghoon** [comment]
@handayeon 재현되지 않습니다. 
조금 더 구체적인 순서 혹은 브라우저 정보를 알려주세요.

**Comment by seoryjj** [comment]
맥(크롬)에서도 재현됩니다.  보고서 "이슈_라벨_한다연"   에서 편집모드에서 라벨을 클릭하는 순간 기존 사이즈보다 줄어듭니다.

**Comment by sunghoon** [comment]
@veldise 위에 보고된 보고서에서 아래의 레이블을 선택하면 보고된 문제가 발생함을 확인하였습니다. 원인 분석 바랍니다. 
![스크린샷 2020-10-26 오전 10 40 04](https://user-images.githubusercontent.com/512653/97125566-b333de00-1777-11eb-84ca-782c8be46650.png)

**Comment by veldise** [comment]
편집화면에서만, Label 객체에 꾸미기 옵션 > 테두리를 설정한 뒤 키보드/마우스를 입력하면 크기가 작아지는 것을 확인했습니다.
버그입니다.

**Comment by sunghoon** [comment]
@veldise 예전부터 관련 현상들이 발견되고 있었습니다. 편집편의를 위해 빠른 초지 바라며, 진행 일정정보를 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
차주(11/5) 패치에는 해결하도록 하겠습니다.

**Comment by veldise** [comment]
@sunghoon 
11/5 패치에 해결하도록 하겠습니다.

**Comment by seoryjj** [comment]
2020/11/13 일 현재
보고서   : 이슈_라벨_한다연
http://b-iris.mobigen.com:80/studio/exported/b5e5d6f538e74c038daa66bf1fd75f3624bb3a428a1a4be9a1b1484f720dc567

편집 화면에서 라벨 선택할 때마다 줄어드는 현상이 재현됩니다.

**Comment by veldise** [comment]
@seoryjj 
어떤 Label을 클릭해야 재현되나요? 현재 눈에 보이는 5개는 정상으로 보입니다.

**Comment by seoryjj** [comment]
Mac 에서 편집하면에서 라벨을 클릭할 때 마다 라벨의 사이즈가 줄어듭니다.
보고서 mac_라벨_편집이슈
http://b-iris.mobigen.com:80/studio/exported/c44bcf4d7edd4ffda8709122773f9e8a40d8e615450f41f3958c7c40c9bd6f16

**Comment by seoryjj** [comment]
브라우저를 75% 로 축소하여 사용하면 생기는 현상이고, 80 ~ 100% 크기로 볼 때는 정상 동작합니다. close 하겠습니다.

**Comment by stgim** [comment]
(RC.ver:202011240831): 편집화면에서 브라우저 글꼴크기 75%, 67%, 50%에서 객체 크기 변하지 않는 것을 확인함
