### ISSUE TITLE
[Studio] "forecast" 의 시각화 결과에서 시간필드 오류(Analyzer는 정상,Studio 는 오류)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2671]
## 버그 설명 ##

b-iris.mobigen.com  demo 계정

참고 보고서 :  이슈_EDU_Forecast시각화

- Analyzer 시각화는 정상
<img width="1430" alt="스크린샷 2020-10-26 오전 11 28 08" src="https://user-images.githubusercontent.com/5126497/97128009-9222bb80-177e-11eb-99da-1da9b3f58baa.png">

-Studio 에서는 시간값(X 축이 1970) 오류. 그래서 예측 부분도 잘못 그려집니다
<img width="906" alt="스크린샷 2020-10-26 오전 11 27 16" src="https://user-images.githubusercontent.com/5126497/97128055-b088b700-177e-11eb-9288-8665e70cfe99.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 문제 조치를 위한 일정 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
#2667 과 같이 11/12 패치를 목표로 하고 있습니다.
