### ISSUE TITLE
선택된 언어팩에 맞는 문자열 출력

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2672]
선택된(일본어)와 관련 없는 다른 언어팩 문자열이 출력되고 있습니다. 
아래는 예시 화면이며, 이뿐만이 아닌 모든 문자열에 대한 확인 및 점검 필요. 

![한글메시지예시](https://user-images.githubusercontent.com/512653/97240905-d7082a00-1832-11eb-81fa-41579447e72e.jpg)

**Comment by veldise** [comment]
이슈 본문 내용은 IBP만 해당되는 것으로 보이며 빠르게 처리해보겠습니다.

**Comment by veldise** [comment]
@sunghoon 
그룹장님, 최신 버전에서는 잘 나오는 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/97241905-c4432480-1835-11eb-922b-6f42d2463f43.png)


@big-mobigen 
Direct Cloud 에 설치된 IRIS Studio 버전 정보를 요청합니다.

**Comment by veldise** [comment]
현재 Direct Cloud 에 설치된 studio 버전 (`f21509ef`) 기준으로, 국가/언어설정이 일본어로 되어있으면 메시지도 일본어로 나옵니다.

![image](https://user-images.githubusercontent.com/3411842/97378294-61b95980-1905-11eb-8618-e2c5c4a362d4.png)

**Comment by sunghoon** [comment]
해당 내용에 대하여 이슈 보고자와 확인이 다 되었으며, 확인된 내용을 바탕으로 어떻게 진행할지는 별도로 진행하도록 하고, 본 이슈는 닫도록 하겠습니다.

**Comment by jins00** [comment]
다이렉트클라우드측 개발사로 부터 아래와 같은 이슈가 발견되어 재확인 요청을 받았습니다.

크롬의 "새 시크릿 창"에서 아래 링크로 들어가면 한글이 표시되며, 화면 리프레시를 하면 일본어로 변경된다고 합니다.
https://visible.directcloud.net/studio/exported/650df046bc9f4c95814e03f4d1c6a5283fad004afcf248ad9f5a8bbb2174c61b?extra_param=%7B%22company_code%22%3A%22lalaworks%22%2C%22title%22%3A%22%22%2C%22start_date%22%3A%2220201022000000%22%2C%22end_date%22%3A%2220201028235959%22%7D&locale=ja

위 링크의 파라메터 값을 보시면 locale=ja 를 전송하고 있는걸 보실 수 있는데요. 처음 접속시에(로케일 값이 아직 쿠키에 세팅되기전)는 일부 리소스가 기본 언어인 한글로 표시되고, 쿠키에 로케일 값이 세팅된 이후부터는 해당 로케일에 따라 언어가 정상적으로 표시되는 것 같아요.
즉 처음 접속하는 사용자는 로케일 설정과 무관하게 무조건 한글을 보게되고, 두 번째 접속시점 부터는 일본어로 정상적으로 표시되는 것 같습니다.

**Comment by veldise** [comment]
@big-mobigen 
다이렉트 클라우드에 brick 설정을 확인해주시고 필요시 수정해주시기 바랍니다.
쿠키값이 없는 상태에서 사이트에 접속하게 되면 locale 우선순위 설정에 따라 언어가 설정됩니다. 현재 한국어로 되어있는 것 같습니다.

파일 위치:
`service/conf/brick/server.json`

기본값:
```js
    "localePriority": ["ko", "en", "zh", "ja"],
```
일본어 우선:
```js
    "localePriority": ["ja", "en", "ko", "zh"],
```

**Comment by big-mobigen** [comment]
요청하신 내용으로 수정되었으며 위 링크 확인시에도 정상적으로 표기됨을 확인하였습니다.

**Before**
`[root@prd-mobigen1 ~]# cat b-iris/service/conf/brick/server.json  | grep localePriority
    "localePriority": ["ko", "en", "zh", "ja"],`

**After**
`[root@prd-mobigen1 ~]# cat b-iris/service/conf/brick/server.json  | grep localePriority
    "localePriority": ["ja", "en", "ko", "zh"],`

![image](https://user-images.githubusercontent.com/25650544/98498612-8a890980-228a-11eb-9561-3c84e5f4098e.png)

**Comment by veldise** [comment]
@big-mobigen 
빠른 처리에 감사드립니다.

**Comment by sunghoon** [comment]
@jins00 최종 확인 후 특이사항이 없다면 Close 바랍니다.
