### ISSUE TITLE
[Studio]  테이블 객체에서 이벤트 변수 설정이  비활성화되어 있습니다. && 시각화유형 선택이 테이블로 고정되어 보입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2673]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 참고 보고서 : 이슈_테이블_이벤트변수설정

- 테이블의 설정
<img width="217" alt="스크린샷 2020-10-27 오전 10 04 03" src="https://user-images.githubusercontent.com/5126497/97244500-3585d600-183c-11eb-990d-b407664950ad.png">

- 꺾은 선형 선택 후 챠트는 그려지고, 이벤트변수 활성화는 됩니다. 하지만 설정에서는 계속 테이블로 나오는 문제가 있습니다
<img width="239" alt="스크린샷 2020-10-27 오전 10 12 11" src="https://user-images.githubusercontent.com/5126497/97244815-fb690400-183c-11eb-9c49-74961e661f46.png">

<img width="219" alt="스크린샷 2020-10-27 오전 10 12 16" src="https://user-images.githubusercontent.com/5126497/97245007-687c9980-183d-11eb-9698-7616084dcc3e.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 디폴트 값 변경을 요청드립니다.

**Comment by veldise** [comment]
@sunghoon 
별다른 문제가 없으면 10/29 패치에서 아래와 같이 변경하겠습니다.
- Chart / 테이블 유형 - ‘행 선택’ 설정 기본값을 ‘사용 안함’ -> ‘단일 선택’으로 변경

**Comment by veldise** [comment]
두번째 차트 시각화 유형 문제는 오늘(10/27) 패치로 해결되었습니다.
![image](https://user-images.githubusercontent.com/3411842/97269243-90392500-1870-11eb-996b-de501a11d06e.png)
