### ISSUE TITLE
[NMS+]IRIS 보고서중 Maria-db 관련 보고서 장애점검요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2674]
## 버그 설명 ##

아래와 같이 maria-db 관련 보고서만 전체 다 실행이 안된다고합니다.

관련해서 
접속테스트 maria-db 연결  확인 완료했고
직접 maria-db 클라이언트 tool 들어가서 해당 쿼리 날려서 정상임을확인했습니다.

보고서쪽에서 maria-db 접근하는 보고서만 안된다고 하는데 확인부탁드립니다.

접속 url은 일전에 @veldise  C 에게 메일드렸는데, 필요하면 댓 달아주세요
보고서 명 : REPORT_고객 상세_tensal

ㄱ

![image](https://user-images.githubusercontent.com/5468183/97245677-eab98d80-183e-11eb-9071-10653e24cb05.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm 
DSMS 에서 요청 응답을 PENDING 으로 반환한 것 같습니다. DSMS 도 확인이 필요합니다.

**Comment by sunghoon** [comment]
@anhm 책임님 확인결과 공유 바랍니다.

**Comment by veldise** [comment]
대상 연결 정보:
- ID: 7
- 이름: MARIADB-NMSPLUS
- URL: 192.168.0.11:13306/skbnmsplus
- user: skbnmsplus

SQL:
```sql
SELECT Ifnull( t.CUST_ID, "-") AS CUST_ID,
       i.DEV_ID,
       d.DEV_NAME,
       d.DEV_IP,
       i.IF_DESCR,
       i.IF_ALIAS,
       i.IF_INDEX,
       i.BW_CD AS "BW(M)",
       i.IP_ADDR,
       i.MAC_ADDR,IF ( Locate('Vlan', i.IF_ALIAS) != 0, 1, 0) AS isVlan,
IF (i.ACT_STATUS = 0, 'N', 'Y') AS isActive, t.DEV_ID, t.IF_INDEX, CONCAT( t.DEV_ID ,'%7C' , t.IF_INDEX) AS 'keys' FROM (
       SELECT CUST_ID,
              TREE_ID,
              DEV_ID,
              IF_INDEX
       FROM   def_tree_info
       WHERE  TREE_PID = '10' ) t LEFT JOIN conf_device_if i ON (
  i.DEV_ID=t.DEV_ID
  AND
  i.IF_INDEX=t.IF_INDEX
)
LEFT JOIN conf_device_ip d ON i.DEV_ID=d.DEV_ID WHERE TRUE
AND
d.USE_YN = 'Y' ;
```

응답:
```json
{"status": 0, "messages": "", "items": {"status": "PENDING"}}
```

**Comment by anhm** [comment]
일차적으로 DSMS를 재기동 하여 서비스는 정상화를 시켜 두었습니다.

**Comment by sunghoon** [comment]
시스템이 정상으로 운영중이라 본 이슈는 닫도록 하겠으며, 원인 분석은 별도 이슈로 다루겠습니다.
