### ISSUE TITLE
[Analyzer] 필드이름에 빈칸이 있을 때 백쿼터로 where 절 검색 시 에러 && 상위 10개 분포 조회 시 에러

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2675]
## 버그 설명 ##
b-iris.mobigen.com  demo 

- 데이터모델 : EDU_SUWON_MINWON_20200927  
엑섹파일에서 만든 데이터 모델로 필드이름에 빈칸이 있습니다.

- Analyzer : 백쿼터사용해서 검색 시 에러 발생합니다.
  
<img width="393" alt="스크린샷 2020-10-27 오후 3 05 33" src="https://user-images.githubusercontent.com/5126497/97263245-e18fe700-1865-11eb-9e6e-c892d2825841.png">
<img width="191" alt="스크린샷 2020-10-27 오후 3 00 42" src="https://user-images.githubusercontent.com/5126497/97263271-efde0300-1865-11eb-9e86-097dde411ead.png">

- 왼쪽 텍스트형의 필드를 클릭해서 상위 10개의 분포를 보는 것도 빈칸이 있는 컬럼은 에러납니다.(빈칸없는 "키워드" 필드는  결과 나옵니다)
<img width="813" alt="스크린샷 2020-10-27 오후 2 51 40" src="https://user-images.githubusercontent.com/5126497/97263283-f9676b00-1865-11eb-8a60-6f3f8ca7227d.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @seungfwani 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
해당 문제는 where 명령어의 문제가 아니고,
내부적으로 재구조화가 필요하여 지체 될 수 있습니다.

일정에 대해서는 추후 공유하도록 하겠습니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 해당 이슈 처리 어떻게 진행되고 있나요?

**Comment by anhm** [comment]
해당 이슈는 Analyzer 의 쿼리 실행시 자동으로 실행되는 timeline을 계산하기 위한 부분에 문제가 있는 상태로
해당 DSL을 수정해야 하는 상태입니다.

해당 작업은 2월 중순까지 완료될 예정입니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 해당 이슈 처리 어떻게 진행되고 있나요?

**Comment by seungfwani** [comment]
처리되어 닫습니다

![Screen Shot 2021-03-23 at 1 37 21 PM](https://user-images.githubusercontent.com/46172579/112093533-ee2e2680-8bdc-11eb-95df-721677bc1b2c.png)
