### ISSUE TITLE
[Studio] 챠트 객체 이벤트전달 시 다중선택 할 때, 텍스트 항목 한정자 설정이 빠졌습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2676]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 참고 보고서 : EDU_교육_수원시예제_20201027 

- 테이블 다중 선택 후 2개 행 선택

<img width="392" alt="스크린샷 2020-10-28 오후 2 58 16" src="https://user-images.githubusercontent.com/5126497/97398229-297a4100-192e-11eb-8df0-74d48665f12e.png">

- 검색어 미리보기 해보면  각 텍스트별로 작은 따옴표로 설정하는 부분이 없어서 잘못된 검색어 구문이 됩니다
<img width="337" alt="스크린샷 2020-10-28 오후 2 58 24" src="https://user-images.githubusercontent.com/5126497/97398219-24b58d00-192e-11eb-95f0-f8099ad38819.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 내용 확인 후 진행 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn @eumminsun 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 업무가 산적해있어 11월에는 진행이 어렵습니다. 차주 중에 다시 검토해보겠습니다.

**Comment by veldise** [comment]
@sunghoon 
현재 국토부 / LH공사 / 수원시청 / 다이렉트 클라우드 / 교통연 등의 외부 사이트 지원을 우선으로 하고 있어,
당장은 진행이 어렵고 위 사이트 지원이 정리되는대로 다시 검토하기로 했습니다.

**Comment by veldise** [comment]
@sunghoon 
행 선택 설정이 '다중 선택', 값 필드 설정이 '단일'인 경우에만 텍스트 한정자 옵션이 Check&Radio 와 같이 처리되도록 계획중입니다.
기획 작업이 예정되어 있습니다.

**Comment by veldise** [comment]
1/7 패치로 완료되었습니다.
