### ISSUE TITLE
Studio / Label 다중 선택 후 배경색을 변경할 수 없습니다.

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2677]
* 단일 선택의 경우 옵션에서 변경 가능
![스크린샷 2020-10-28 오후 3 10 11](https://user-images.githubusercontent.com/512653/97399149-d608f280-192f-11eb-8ead-d66d7076ed41.png)

* 다중 선택의 경우 옵션이 없음.
![스크린샷 2020-10-28 오후 3 10 22](https://user-images.githubusercontent.com/512653/97399171-e1f4b480-192f-11eb-896f-4ebb51f057ce.png)

* 배경색 이외의 다른 기능들 (정렬, 색상  등등등) 공통적용 가능한 것들은 될 수 있도록...

**Comment by rhcpn** [comment]
해당 기능은 다중 선택 관련 기획 단계에서는 논의가 되었던 내용입니다.
제 예상으로는 디자인 개편 이후에 진행 가능할것으로 보입니다.

**Comment by sunghoon** [comment]
@rhcpn 제가 이야기 드린건 디자인 개편이랑 상관없이 선택된 오프젝트에 속성을 루프를 돌면서 적용하는거라 기능적으로 처리 해 줬으면 하는 요청입니다.
