### ISSUE TITLE
[DSL] pivot 에서는 스페이스가 있는 필드명에 백쿼터를 쓰면 에러나고, 작은따옴표를 써야 동작합니다. (다른 DSL 은 백쿼터를 써야 동작)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2678]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

- 데이터 모델 :  EDU_SUWON_MINWON_20200927

- 검색어  :  작은 따옴표로 필드명 "접수 일자" 를 사용하면 결과 나옴
` *  |  where 키워드 in (  '재개발', '불법'  )
  |  pivot count(*) as CNT splitrow '접수 일자'   splitcol 키워드 
`

- 다른 DSL 에서는 빈 칸 있는 필드이름에는 모두 백쿼터 를 써야 함

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
수정 완료 되었습니다.
![Screen Shot 2020-11-03 at 10 05 15 AM](https://user-images.githubusercontent.com/46172579/97935508-177c2080-1dbc-11eb-9688-cf93313459a9.png)
