### ISSUE TITLE
[Studio] 글자 크기 설정이 반영되지 않습니다.

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2679]
## 버그 설명 ##
글자 크기 설정이 반영되지 않습니다. 확인 부탁드립니다.

## 재현하는 방법 ##
보고서: [물품] 공공조달_공고 목록_v0.2-test
1. 글자 크기: 11
![image](https://user-images.githubusercontent.com/5077625/97538922-8811ee80-1a04-11eb-83a3-e918c7d01386.png)

2. 글자 크기: 24
![image](https://user-images.githubusercontent.com/5077625/97539006-a4159000-1a04-11eb-8970-281f0e342ad3.png)

**Comment by sunghoon** [comment]
@veldise 점검 바랍니다.

**Comment by veldise** [comment]
@euhyesun 
보고서를 작성하실 때 해당 텍스트를 어떻게 작성하셨는지 상세한 내용이 필요합니다.
현재 `<span style="font-size: 8px"> ...` 와 같이 텍스트가 아닌 값이 들어가 있어 글꼴이 적용되지 않고 있습니다.

**Comment by euhyesun** [comment]
@veldise 다른 보고서에 있는 텍스트를 복사/붙여넣기 하였습니다.

**Comment by veldise** [comment]
@sunghoon 
Label 객체는 contenteditable 로 구현되어 있는데, 텍스트를 직접 입력하는게 아닌 Ctrl+c,v 로 하면
텍스트 스타일까지 붙여넣기 위해 문자열이 아닌 태그로 입력이 되는 것 같습니다.
개선이 필요한 사항입니다.

**Comment by sunghoon** [comment]
@veldise HTML Tag만 제거되는 간단한 이슈 인것 같습니다. Label의 경우 위와 같은 사용패턴이 많이 있으니 HTML tag를 제거하고 content만 처리되도록 하면 될 것 같습니다.

**Comment by sunghoon** [comment]
@veldise 이슈 처리를 위한 개발 계획 일정 정보를 공유 해 주세요.
