### ISSUE TITLE
[Studio] 지도의 위도 경도 범위 오류

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2680]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
위도 좌표의 숫자 범위는 -90과 90 사이여야 합니다.
경도 좌표의 숫자 범위는 -180과 180 사이여야 합니다.

그리고 Studio의 지도 기본 값 설정에서 위도 경도 입력값 범위도 각각 위도 경도의 숫자 범위에 대한 최소, 최대 제한이 되어 있지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/97540135-8812ee00-1a06-11eb-9c54-b5a9641f7d60.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn 확인 바랍니다.

**Comment by veldise** [comment]
줌 레벨에는 최소/최대 제한이 걸려있지만 위도, 경도에는 걸려있지 않은 것을 확인했습니다.
더 확인해보고 별다른 이슈가 없으면 11/5 패치에 포함시키겠습니다.

**Comment by sunghoon** [comment]
@veldise 이슈 처리를 위한 개발 계획 일정 정보를 공유 해 주세요.
