### ISSUE TITLE
[studio] 챠트 객체에서 분석탬플릿으로 "불러오기" 를 하여 데이터객체를 만들 때, 데이터모델이름이 보이지 않고, 에러발생합니다

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2681]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

참고 보고서 : 이슈_불러오기데이터

- demo 계정으로 생성한 데이터 모델 : TEST_DATA_0141
- 분석 탬플릿 이름 : TEST_anomalies_데이터셋_basic

- 불러오기로 생성된 챠트 의 데이터 객체에 데이터모델 이름이 보이지 않습니다.( 보고서 demo 계정 )
<img width="246" alt="스크린샷 2020-10-30 오후 2 01 09" src="https://user-images.githubusercontent.com/5126497/97661837-cb2d9980-1ab8-11eb-93ce-85070000a033.png">

- 그대로 실행하면 에러 발생
<img width="216" alt="스크린샷 2020-10-30 오후 2 06 04" src="https://user-images.githubusercontent.com/5126497/97661998-35ded500-1ab9-11eb-8fe5-4bf44b76f558.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
재현해 보니, analyzer 에서 데이터모델로 분석탬플릿을 저장한 후에
studio 에서 "불러오기" 하면 탬플릿 리스트는 생성되어 보이지만, 데이터 모델 정보는 한참 뒤에 업데이트 되어서  데이터모델 정보를 뒤늦게 가져오는 현상 같습니다.
지금 보고서를 다시  열어보니 데이터모델이 보입니다

**Comment by seoryjj** [comment]
분석탬플릿이 만들어 질 때,  Analyzer 에서는 새로 만든 데이터모델이 보여서 조회 후 분석탬플릿으로 저장했고, 
그 후에 Studio 에서 바로 새 보고서를 만들 때
분석탬플릿 목록이 보이니까 당연히 데이터 모델도 있을 거라고 생각할 수 있는데,
분석탬플릿 목록과 데이터모델 목록 업데이트 시간이 차이가 나는 현상을 해결해야 할 것 같습니다

**Comment by sunghoon** [comment]
@veldise 확인해 조치해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 업무가 산적해있어 11월에는 진행이 어렵습니다. 차주 중에 다시 검토해보겠습니다.

**Comment by veldise** [comment]
@sunghoon 
현재 국토부 / LH공사 / 수원시청 / 다이렉트 클라우드 / 교통연 등의 외부 사이트 지원을 우선으로 하고 있어,
당장은 진행이 어렵고 위 사이트 지원이 정리되는대로 다시 검토하기로 했습니다.

**Comment by sunghoon** [comment]
@veldise 업무량에 대한 검토 의견 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 아래와 같이 아이디어를 나눈 상태입니다.
1. Combo-box 클릭하여 목록을 펼치면 새로운 데이터를 요청
2. 새로운 데이터와 기존 데이터를 비교
3. 비교 결과 다르면 Combo-box 목록에 '새 데이터로 갱신' 버튼을 표시
4. '새 데이터로 갱신' 버튼을 누르면 새로운 데이터로 Combo-box 목록을 갱신

기획 작업이 예정되어 있습니다.
위 내용 정도로 하면 최대 2일 정도로 예상됩니다.

**Comment by sunghoon** [comment]
@veldise 기존에 설정되어 있는 모델명이 표시되지 않는 이슈 입니다. 
사용자는 아무런 행위 없이 기존의 설정값이 올바르게 적재/표기되어야 할것 같습니다.
신규 기획을 필요로 하는 이슈가 아닌것 같습니다.
