### ISSUE TITLE
[Discovery] 데이터모델-시간필드: 데이터모델 생성 시 timestamp 유형 컬럼의 오동작( UI 오류 & angora 오류)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2682]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 오류  데이터 모델  :  model_test_텍스트

- 검색어
`* |  sort CTIME  |  anomalies  CTIME VAL  by=STS  alg=basic  index_type=timestamp`

1.  UI 오류 :  CTIME 에 timestamp 유형, YYYY-MM-DD HH:mm:ss 로 설정 한 후에 나중에 "시간" 분류로 지정하면 "기타" 에 포맷설정 부분 사라짐

<img width="801" alt="스크린샷 2020-10-30 오후 2 54 51" src="https://user-images.githubusercontent.com/5126497/97669352-4b5afb80-1ac7-11eb-94d2-e928dfa16652.png">

2. angora 오류 :  1번 UI 오류  && 포맷에 빈칸이 있으면 TEXT 로 인식합니다.
    - 데이터 모델 "model_test_텍스트"   참조 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
- 시험할 때 검색어 
`* |  sort CTIME  |  anomalies  CTIME VAL  by=STS  alg=basic  index_type=timestamp`

- 시험할 때 참고할 데이터모델 목록
    - model_test_텍스트  :  결과 없다고 나옴
    - model_test_14자리  : 결과 나옴,  by 를 사용하는 예제
    - model_test_시간  : 지난 주에는 결과가 나왔으나 갑자기 결과 없다고 나옴. 처음에는 "시간" 분류 컬럼 없음 -> timestamp 타입의 CTIME을 나중에 "시간" 분류 컬럼으로 지정함. UI 에서 포맷 사라짐.

**Comment by sunghoon** [comment]
@veldise @seungfwani 내용을 확인해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
UI 동작상에 문제를 확인했습니다. 수정이 필요합니다.

**Comment by sunghoon** [comment]
@veldise 진행 일정 계획 정보를 세워 공유 바랍니다.
