### ISSUE TITLE
[서초구청] Studio: 콤보박스 외부에서 값선택 지정

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2683]
## 기능 요청 ##
콤보객체에 데이터객체를 연결하여 내용을 채우고 특정 값을 선택할 수 있는 설정이 있었으면 합니다.

## 원하는 솔루션 설명 ##
콤보객체에 시간 00시부터 23시까지 채우고 현재 시간을 선택할 수 있는 설정

## 고려한 다른 대안 ##
콤보객체에 처음 데이터가 들어간 후 디폴트 값 선택 설정 적용(디폴트 값 선택 적용 순서를 조정하면 원하는 기능이 될 것 같음)

## 기타 ##
날짜/시간 객체를 현재시간으로 하고 출력을 HH로 해서 콤보객체 디폴트 값 선택을 해당 날짜/시간 객체로 지정하면 
해당 시간 선택이 됐었는데 현재는 안되고 있음.

**Comment by sunghoon** [comment]
@veldise 내용을 확인해 주시기 바랍니다.

**Comment by veldise** [comment]
@SONHOJUN 
현재는 안되고 있다고 하셨는데, b-iris.mobigen.com 사이트에서 다시 한 번 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/3411842/97962247-10730380-1df8-11eb-94f2-5337eaf0a526.png)
