### ISSUE TITLE
[studio] 보기를 누르면 단일값 그래프 크기가 달라져요

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2684]
## 버그 설명 ##
보기를 누르면 단일값 그래프 크기가 달라져요

## 재현하는 방법 ##
동작을 재현하는 방법 :

단일값 그래프를 생성

## 예상한 행동 ##
보기를 눌렀을 때 수정화면이랑 같게 표시되어야 함

## 스크린샷 ##
편집화면
![image](https://user-images.githubusercontent.com/50221479/97819208-7c674600-1cea-11eb-8b3d-f365574b00f4.png)
보기화면
![image](https://user-images.githubusercontent.com/50221479/97819211-85581780-1cea-11eb-89d4-f1059ab1c1d3.png)

## 로그 ##
http://b-iris.mobigen.com/

'이슈_단일값_한다연' 참고해주시면 됩니당

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 내용을 확인하여 조치 해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
Label 객체와 동일하게 테두리에 따른 크기 계산 버그를 확인하였습니다. 처리 일정이 결정되면 코멘트 달겠습니다.

**Comment by veldise** [comment]
@sunghoon 
말씀드리는게 늦었습니다. 금주(11/12) 패치 예정입니다.
