### ISSUE TITLE
[LH빅데이터플랫폼구축사업] IRIS Cloud 하둡 2.10.1버전 지원 요청

### ISSUE THREAD

**Issue by suk555** [mobigen/IRIS-BigData-Platform#2685]
LH빅데이터플랫폼 구축에 필요한 IRIS Cloud시스템 구축

IRIS Cloud 하둡 2.10.1 지원 요청

[ 버전 선택 이유 ]
요구사항 - 하둡기반 데이터 레이크 구축, 관리 및 모니터링 페이지 필요
**하둡버전 - 2.10.1(2.대 최신 안정버전 설치)**
관리 - Ambari (hadoop v3.1.0까지 무료, 이상버전 상용)
         2.x버전이 간혹 없어지는 경우 발생
         무료버전 3.1.0의 경우 없어지지 말라는 법이없음
         반드시 3.X버전을 사용할 이유없음
         안정성이 보장될 수 있는 2.X버전 지원 요청

[ 패키지 설치 일정(납품 SW전체  ]
- 11월 중순에 LH내부에 장비 설치
- 11월 말에 납품 SW설치
- 12월 초에 납품 SW설치 완료 예정
- 12월 16일부터 내부클라우드와 외부 클라우드 연계 진행

**[ 기능 지원 요구 일정 ]
- 12월 첫 째주
- 위 일정이 가능한지 검토 부탁합니다.**

**Comment by anhm** [comment]
@suk555 
해당 내용이 맞는지 확인 부탁 드립니다.
- 설치되어 있는 하둡 2.10.1 버전에 Discover Service가 연동 되도록

문의 사항
- spark의 버전은 현재 2.4.4를 사용중이며, 해당 버전을 사용해도 문제가 없는지

**Comment by suk555** [comment]
@anhm 
11월중순에 HCI서버가 입고되면 하둡 2.10.1을 설치하고
그 버전에 맞는 Spark이 연동되어야합니다. 현재 사용하는 Spark 2.4.4 연동이 가능하면 좋겠는데
하둡 버전에따라 Spark버전이 올라갈 수 있으니 확인이 필요합니다.

**Comment by suk555** [comment]
@anhm 
하둡 관리가 이슈되어서 라이선스 제약이 없는 아래 항목으로 설치를 결정했습니다.
아래 항목으로 테스트할 수 있게 운용팀에서 구축해줄것입니다.

Ambari : 2.7.4
HDP : 3.1.4(Hadoop 3.1.1)
Spark : 2.4.4
[ 개발 및 확인 사항 ]
앙고라 연동 개발 필요함
위 3개버전은 패키지 준비 완료됨

**Comment by anhm** [comment]
@big-mobigen 
테스트 환경 구축 부탁 드립니다.

**Comment by sunghoon** [comment]
@suk555 @anhm @big-mobigen 본 이슈 지원 완료 되었는지요?
