### ISSUE TITLE
[Discovery] 새모델, 새모델 뷰 생성 시 컬럼설정에서 'LONG' 이라는 유형이 나오는데, 콤보박스에 없는 유형입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2686]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
b-iris.mobigen.com  

- discovery - 데이터모델

- 컬럼 설정에서 LONG유형은 콤보박스에 없는 유형입니다.  LONG 대신 콤보박스에 있는 BIGINT 유형으로 표시해야 합니다.
<img width="801" alt="스크린샷 2020-11-02 오후 2 26 59" src="https://user-images.githubusercontent.com/5126497/97833197-2d380a00-1d18-11eb-9e3a-05955e58c95d.png">

- 콤보박스에 있는 유형 목록
<img width="136" alt="스크린샷 2020-11-02 오후 2 34 08" src="https://user-images.githubusercontent.com/5126497/97833349-86a03900-1d18-11eb-8415-2c219917c27f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 내용을 확인하여 조치해 주시기 바랍니다.

**Comment by veldise** [comment]
@seoryjj 
이슈 본문의 데이터 정보(연결정보, 테이블 등)를 알 수 있을까요?

**Comment by seoryjj** [comment]
메일이 너무 많이 와서 이제야 봤습니다.

Discovery - 데이터모델 : EDU_G2B_DATA_TEST   에서 "새모델 뷰" 선택
시간 설정 : 전체 기간 선택
검색어 에
`* | substr bidNtceDt 1 4 as YEAR
 | stats max(asignBdgtAmt) as asignBdgtAmt,
   count(*) as 건수  by YEAR,dminsttNm | sort -asignBdgtAmt,YEAR`
적용 누르면
아래 컬럼설정에서 LONG 타입이 나옵니다.
<img width="738" alt="스크린샷 2020-11-10 오전 10 40 08" src="https://user-images.githubusercontent.com/5126497/98616926-24ab8900-2341-11eb-9de6-36d4ea998c8d.png">

**Comment by veldise** [comment]
@seoryjj 
문제 확인하였습니다. 감사합니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 이슈 처리를 위한 계획 정보를 공유해 주세요.

**Comment by seungfwani** [comment]
11/18 일자 확인에서는 해당 문제가 없는 것으로 보입니다. 닫도록 하겠습니다.
![Screen Shot 2020-11-18 at 4 49 44 PM](https://user-images.githubusercontent.com/46172579/99500710-1226f480-29be-11eb-939c-e9a9dfecaa92.png)
