### ISSUE TITLE
[Studio] 에서 새로 생성한 데이터모델, 모델 뷰가 데이터객체의 데이터모델 리스트에 적용되기 위해서는 브라우저 새로고침을 해야만 합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2687]
## 기능 요청 ##

b-iris.mobigen.com root

새로 생성한 데이터모델, 모델 뷰는 브라우저 새로고침을 해야  보고서의  데이터모델 리스트에 바로 보입니다.  

1. 새 데이터모델 생성 전에 다른 브라우저 탭에 보고서 목록 화면이 있다면 , 데이터모델을 생성한 후 10분이 지난 후에도
    새보고서 만들기로 편집화면에 들어오면  데이터모델 목록에서 보이지 않습니다.
2. 상위 메뉴 이동이 없다면 Studio 의 보고서 목록 새로고침은 새로 생성한 데이터모델 목록을 가져 오지 못합니다.

- 새로 생성한 모델 뷰 : EDU_VIEW_G2B_DATA_NEW 2020/11/02 14:35 에 생성
<img width="1321" alt="스크린샷 2020-11-02 오후 2 46 05" src="https://user-images.githubusercontent.com/5126497/97834092-493cab00-1d1a-11eb-9b6f-40175dab105a.png">

- Studio 의 리스트에 14:45  에도 보이지 않음. 목록으로 나가서 다시  새로고침 후 편집화면으로 들어온 것임
<img width="420" alt="스크린샷 2020-11-02 오후 2 53 20" src="https://user-images.githubusercontent.com/5126497/97834422-2eb70180-1d1b-11eb-8d15-7e6288a8e3b0.png">

- 여전히 보이지 않음
<img width="349" alt="스크린샷 2020-11-02 오후 2 45 50" src="https://user-images.githubusercontent.com/5126497/97834170-7db06700-1d1a-11eb-837d-042530280711.png">

- 크롬의 새로고침을 해야 목록이 보입니다.
<img width="248" alt="스크린샷 2020-11-02 오후 2 54 47" src="https://user-images.githubusercontent.com/5126497/97834507-5e660980-1d1b-11eb-98f4-f1ec948fd2e3.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 내용을 참고하여 사용 편의성을 개선해 주시기 바랍니다.
