### ISSUE TITLE
[수원시청] Studio 에서 특정날짜,기간 선택 후 해당날짜& 기간의 전주, 전월, 전년 시간을 가져오기 기능

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2688]
## 기능 요청 ##

1. 특정 날짜 선택 : 선택일과 선택일 전주, 전월, 전년 날짜 
    2020.10.26 선택  후 "전주 날짜"  선택하면 2020.10.19  와 2020.10.26 날짜 2개를 변수로 가져오기

2. 특정 기간 선택 : 선택 기간과 전주, 전월, 전년 기간 가져오기
    "2020.10.26 01:00:00 ~ 2020.10.27 01:00:00"   선택 후 "전주 동일 기간" 선택하면 
     "2020.10.26 01:00:00 ~ 2020.10.27 01:00:00"   와 "2020.10.19 01:00:00 ~ 2020.10.20 01:00:00"  을 가져오기

    "전월 기간" 은 2020.09.26 01:00:00 ~ 2020.09.27 01:00:00
     "전년 기간" 은  2019.10.26 01:00:00 ~ 2019.10.27 01:00:00"

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 내용을 참고하여 진행해 주시기 바랍니다.
