### ISSUE TITLE
[데이터모델, 모델 VIEW] 생성 시에 이름에 '공백없음' 등의  명명 규칙을 정하는 것을 건의합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2689]
## 기능 요청 ##

일반적인 RDBMS의 테이블 이름 규칙과 동일하게 
IRIS 의 데이터모델과 모델 VIEW 이름명명 규칙을 건의합니다.

1. 반드시 문자로 시작 해야함.

2. 허용되는 특수기호 등을 꼭 명시  예)  _()  =>  실제 angora 의 명명 규칙을 따름

3. 공백허용 안됨.

이 규칙에 따라 모델 VIEW 의 디폴트 명명에 **공백없이**  데이터모델_VIEW_1, 데이터모델_VIEW_2,,,
로 수정해 주세요

데이터모델, 모델뷰에 공백이 있는 걸 모르고( 공백이 있는지 알기 어렵습니다 ) 일반적인 사용 방법으로 JOIN, 기계학습 등의 DSL 사용하면
오류가 발생합니다.
모델.컬럼  과 같은 규칙을 써야 할 때나 새로 자동 생성되는 컬럼이름이 모델_컬럼  이 되는 경우에는 어떤 방법으로 표현해야 할 지 
알기 어렵습니다.

따라서 일반적인 RDBMS 의 테이블, 컬럼 명명 규칙 중 공백없는것, 문자로 시작하는 것, 허용하는 특수문자 규칙 등은 
IRIS 에서도 적용했으면 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 내용을 참고하여 모델/뷰 생성시 검사를 할 수 있도록 진행해 주세요.
