### ISSUE TITLE
[studio] 편집 시 테이블을 클릭하면 빈 컬럼하나가 더 추가 됩니다.

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2691]
## 재현하는 방법 ##
동작을 재현하는 방법 :
테이블에 컬럼을 추가한 후 클릭을 한다.

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/50221479/97935578-5dd17f80-1dbc-11eb-94e0-b63226066dcc.png)

## 로그 ##
http://b-iris.mobigen.com/ 에서 
이슈_테이블_한다연 참고하시면 됩니당

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
무엇을 이야기 하신것인지 정확히 인지 하지 못하였습니다.
조금 더 정확한 설명 부탁드립니다.

**Comment by seoryjj** [comment]
1. 처음에 컬럼 2개 있는 테이블 쿼리 확인 후
<img width="679" alt="스크린샷 2020-11-03 오후 4 15 25" src="https://user-images.githubusercontent.com/5126497/97958212-1c5ac780-1df0-11eb-80ee-c36efc5a8039.png">

- 시각화 옵션
<img width="437" alt="스크린샷 2020-11-03 오후 4 15 38" src="https://user-images.githubusercontent.com/5126497/97958226-21b81200-1df0-11eb-874a-ad96b98bee1f.png">

2. "건수" 컬럼을 추가한 쿼리로 다시 실행하여 테이블을 클릭하면 갑자기 테이블 오른쪽에 빈 컬럼 있는 것처럼 보입니다.
<img width="659" alt="스크린샷 2020-11-03 오후 4 16 20" src="https://user-images.githubusercontent.com/5126497/97958380-6774da80-1df0-11eb-920d-83c483f7ee38.png">

3. 시각화 옵션에서 테이블크기 객체와 가로 길이 맞춤이 체크되어 있는데도 나타나는 현상입니다.
    체크를 지웠다가 다시 체크를 클릭해야 비로소 테이블이 바르게 보입니다. 윈도우, 맥 크롬 모두 나타나는 현상입니다.
<img width="661" alt="스크린샷 2020-11-03 오후 4 21 56" src="https://user-images.githubusercontent.com/5126497/97958521-b753a180-1df0-11eb-89ca-86577db5bec0.png">

**Comment by sunghoon** [comment]
@veldise 확인 후 조치 해 주시기 바랍니다.

**Comment by veldise** [comment]
현재 제 PC 에서는 재현되지 않습니다. 원인을 파악하는데 시간이 걸릴 것 같습니다.

![image](https://user-images.githubusercontent.com/3411842/97960710-51b5e400-1df5-11eb-8470-95b107a76123.png)

**Comment by sunghoon** [comment]
@seoryjj 직접 구도로 @veldise 책임에게 설명 부탁드립니다. 
참고로 저도 몇가지 케이스로 해 보았을때 재현되지 않았습니다. 
만약 다른 특이사항이 없다면 Close 해 주시고요.

**Comment by seoryjj** [comment]
수정이 된 것 같습니다.

이슈 올린 날에 윈도우(한다연 인턴의 PC), 맥 (정혜정 Macbook) 모두 같은 현상이 재현되어 덤프된 화면과 동일하게 시간차를 두고 반복해서 나왔는데,
지금은 그 때와 동일한 과정으로 클릭해도 현상이 재현되지 않습니다.
당시에는 시각화 옵션 설정이 바로 바로 반영안되고 클릭을 한번 더 해야 반영이 되는 것처럼 보였습니다.그 뒤로도 당일에 제가 다른 보고서에서 테이블 생성 할 때도 이런 현상이 계속 보였으니까요.

수정이 된 듯 하니 close 하겠습니다.
