### ISSUE TITLE
[NMS+]사용자 조회 API 확인요청

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2692]
## 버그 설명 ##

NMS+ 에서 IRIS 사용자정보를 조회하는 API 를 사용하고 있습니다.
전달받은 API 가 /meta/account  입니다. 

A) SKB 사용자관리DB  에서 SKB 사용자를 조회하여 -> B) IRIS 사용자 추가

이때 IRIS 사용자 추가시, 위의 API 를 사용하여 사용자를 비교후   IRIS 의 사용자추가 API 를 콜하고 있는데

위의 사용자정보 /meta/account   사용자 정보가 조회되지않습니다.

사용자 조회 API 및 사용방법 확인하여 제공부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 내용을 확인하여 지원 및 조치 해 주시기 바랍니다.

**Comment by jjinylee** [comment]
@veldise 
이거 저희쪽에서 다시 한번 확인해보겠습니다.
제가 api 조회해보니 사용자 정보가 조회되는데, 기개발된 코드와 다르다는건지 개발자와 얘기하고 다시 코멘트 달겠습니다.

**Comment by rhcpn** [comment]
해당건은 확인 결과 Cookie에 Token 정보를 넣지 않아서 동작하지 않았던 문제이고, 담당자가 개발 완료 했다고 합니다.
