### ISSUE TITLE
[DSL] outlier  결과에서  2종류의 label 이 나온 데이터인데, 모델에 따라 outlier  true 판정이 달라집니다.(label = -1 일때) 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2693]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

### outlier 결과 전부 false 로 나온 경우

- 데이터 모델 : TEST_DATA_4grp_01_603_003_21
- 검색어  
`* | sort CTIME |  typecast CTIME timestamp |  outlier VAL by=STS alg=dbscan tolerance=0.3 | stats count(*) as CNT by STS, label, outlier`
-  mean_2_std_1 은 2개의 label ( 0, 1 )이 나왔는데,  outlier = false 임

<img width="1053" alt="스크린샷 2020-11-04 오전 11 30 03" src="https://user-images.githubusercontent.com/5126497/98062865-2a612480-1e92-11eb-8fda-72a2052b744d.png">

### outlier 결과 true 가 1개 있는 경우
- 데이터 모델 : TEST_DATA_4grp_01_41_003_21
- 검색어 - 위의 검색어와 동일함
- mean_4_std_1 은 2개의 label ( -1, 0 )이 나왔는데, outlier = true
`* | sort CTIME |  typecast CTIME timestamp |  outlier VAL by=STS alg=dbscan tolerance=0.3 | stats count(*) as CNT by STS, label, outlier`

<img width="1032" alt="스크린샷 2020-11-04 오전 11 30 28" src="https://user-images.githubusercontent.com/5126497/98062929-4bc21080-1e92-11eb-8c6e-e3c3c7da47da.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
코드를 보니  label 에 1개의 그룹이 있으면 해당 그룹(STS) 은 true  로 판정하네요. 즉 label 기준으로만...

1개 그룹( STS = mean_4_std_1) 이 2개 이상의 label 을 가지고 있고, 그 중 1개 label 에 unique 한 그룹이 되었다면 
이 그룹은 outlier = true 로 되는 로직인데,  73개 데이터중에서 1개 데이터때문에 2개의 label 을 가지게 되었습니다.

휴리스틱하게 판정한다면 
처음에 전부 outlier = false 로 나온 결과는  마지막 그룹인 'mean_6_std_0_3'  은 다른 label 로 나오는 게 더 타당해보입니다.
<img width="998" alt="스크린샷 2020-11-06 오후 2 16 57" src="https://user-images.githubusercontent.com/5126497/98329233-186eb580-203b-11eb-9886-0d8d7c59fc36.png">

그리고 2번째 outlier = true 인 데이터는 오히려 전부 outlier = =false 가 더 맞아 보이고요.
<img width="999" alt="스크린샷 2020-11-06 오후 2 25 06" src="https://user-images.githubusercontent.com/5126497/98329595-e9a50f00-203b-11eb-85dc-9a29cf01d2bd.png">


판정 로직을 조금 더 검토/수정해야 할 것 같습니다. 나중에 일정에 따라 수정하실 때 얘기해주세요.
테스트용 데이터 등과 가능한 방법들을 공유하겠습니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 이슈 확인 후 상화 공유 해 주세요.

**Comment by seoryjj** [comment]
b-iris.mobigen.com demo 계정   보고서 "ML-outlier_현황보고서"  를 참조하세요
http://b-iris.mobigen.com:80/studio/exported/6836b81bde924829bb6cbef57e1e2c4b162773db217646b3aed8b6f8f3dc3918

**Comment by seungfwani** [comment]
현재 outlier 의 로직은 아래와 같습니다.
- dbscan
  - 군집화 진행
  - 단일 그룹만 존재하는 군집이 있는 지 확인
    - 예) 군집 1(A,B), 군집 2(B,C), 군집 3(C) 로 존재할 때, C 그룹은 이상 그룹으로 판단.
  - 이상 그룹의 모든 값은 outlier true 로 설정
- mad 
  - 각 그룹별 upper, lower 값 계산
    - upper, lower 를 이용해 anomaly(T/F) 조사
  - 각 그룹별 설정한 pct 값 보다 anomaly 개수가 많으면 이상그룹으로 판단.
  - 이상 그룹으로 판단된 모든 값을 outlier true 로 설정

로직 검토는 추후 일정을 공유하도록 하겠습니다.
