### ISSUE TITLE
[NMS+]iris master busy 상태 처리 부탁드립니다.

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2695]
## 버그 설명 ##

![image](https://user-images.githubusercontent.com/5468183/98204940-6e2f5900-1f7a-11eb-8eba-8ae6ffe3dd73.png)

마스터 busy 상태입니다.
처리 / 원인 확인부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm 지원 바랍니다. 

@jjinylee 본 이슈는 천천히 처리 해도 되는건가요? github에 올라오는 이슈가 실시간 처리되는건 아닌데....

**Comment by jjinylee** [comment]
형민책임과 얘기해서 처리완료되었습니다.
