### ISSUE TITLE
[Studio] 지도 객체 - OSM 에서 지도 투명도를 변경해도 적용이 되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2696]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 보고서 이름 : 이슈_지도_polygon_투명도변경안됨

- OSM /  지도 투명도 0 에서 0.5 로 변경했는데, 변경사항이 적용되지 않습니다.
<img width="784" alt="스크린샷 2020-11-06 오전 7 46 42" src="https://user-images.githubusercontent.com/5126497/98305242-d6c31800-2004-11eb-828c-bea4e7fd6c06.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 이슈 확인 후 처리 바랍니다.

**Comment by veldise** [comment]
@seoryjj 
현재 MacOS / Chrome 환경에서 해당 보고서가 정상 동작하는 것처럼 보이는데
자세한 재현방법 기술을 부탁드립니다.

**Comment by seoryjj** [comment]
이 이슈는 이슈 당일에 바로 백승욱책임과 공유했습니다. 

레이어 숨김을 체크한 상태였습니다.
편집화면에서 숨김한 레이어이름이 보여서 숨김상태인걸 인지 못해서 발생한 문제입니다. 그래서 숨김 체크한 레이어가 표시되고 있다는 걸 인지할 수 있는 방안을 마련한다고 얘기가 되었습니다

제가 close  하겠습니다

**Comment by veldise** [comment]
@seoryjj 
문제 해결시 바로 코멘트를 달아주시거나 공유해주시면 감사하겠습니다.
