### ISSUE TITLE
[studio]라벨에 붙여넣기를 하면 글자크기가 바뀌지 않아요

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2697]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :
'이슈_라벨붙여넣기_한다연'
사이즈 설정이 끝난 라벨 안에 내용을 카피해서 다른 라벨에 붙여넣기를 하면 사이즈 설정을 할 수가 없습니다.

## 예상한 행동 ##
사이즈 변화가 자유자재로

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/50221479/98489663-4d188200-2272-11eb-9a72-545ce92966de.png)

## 로그 ##
http://b-iris.mobigen.com:80/studio/exported/f51c61dd9ec847f09f15120790983b81e64a7a46e11f41b1ba5cb3033ba659df

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
비슷한 내용으로 ppt , web 브라우저의 text 를 copy 해서 붙여도 사이즈 조정이 안됩니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 확인 바라며, HTML 스타일 복사와 같은 이슈 일것 같습니다. 빠른 초지 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
12/3 릴리즈를 목표로 설정하였습니다.

**Comment by veldise** [comment]
@sunghoon 
이슈 처리에 다소 난항을 겪고 있어서 패치 일자를 12/10으로 변경하였습니다.
혹시 금주 내로 해결되어야 한다면 hotfix 패치로 진행하겠습니다.
