### ISSUE TITLE
[studio] 회전, 도형 추가

### ISSUE THREAD

**Issue by jangwoni79** [mobigen/IRIS-BigData-Platform#2698]
## 기능 요청 ##
다양한 도형이 추가 되고, 원하는 객체를 회전 할 수 있었으면 좋겠습니다.

## 원하는 솔루션 설명 ##
도형과 사진 등에 회전을 할 수 있는 기능이 추가 되었으면 좋겠습니다. 
삼각형, 평행사변형 등의 도형이 생겼으면 좋겠습니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 검토 바랍니다.
