### ISSUE TITLE
[studio] 방향키로 객체 이동 시 화면도 같이 움직입니다.

### ISSUE THREAD

**Issue by jangwoni79** [mobigen/IRIS-BigData-Platform#2699]
## 버그 설명 ##
방향키로 객체를 이동하면 그 방향으로 화면의 스크롤 바도 같이 움직입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 객체 선택
2. 방향키 이동
3. 해당 방향으로 화면의 스크롤바도 함께 이동

## 예상한 행동 ##
화면은 고정 되고 선택한 객체만 이동

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/49233426/98493664-57407d80-227e-11eb-8b8d-d6eda42a485b.png)
![image](https://user-images.githubusercontent.com/49233426/98493767-9ff83680-227e-11eb-86c8-c7f5b5f3739c.png)

## 로그 ##
Issue_객체방향키이동_장원이
http://b-iris.mobigen.com:80/studio/exported/6cfddacfcfee4870b1baca3d020eab6db27044c412bc4e5b9b643da57cc745d5

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 빠른 처리 요청드립니다.

**Comment by seoryjj** [comment]
같은 종류의 현상으로  객체 1,2,3  이 있을때
1. 아무 객체 하나 생성
2. 그룹으로 1번에서 생성된 객체를 제외한 다른 객체를 묶음
3. 선택된 그룹 객체를 화살표로 이동시키려고 하면 1번 객체가 이동됨

**Comment by rhcpn** [comment]
#2011 해당 이슈와 중복된 이슈 입니다.
해당 건은 접수는 한 상태이지만 개발 기간이 필요하여 11월 중에는 어렵고 12월 중 개발 하는 방향으로 검토 하겠습니다.
