### ISSUE TITLE
[Studio] 체크박스/라디오버튼 세로정렬 옵션 추가

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2700]
## 버그 설명 ##
체크박스/라디오버튼의 세로정렬이 위쪽 정렬이라 앞에 라벨을 가운데 정렬로 하면 라벨과의 정렬이 안 맞습니다.
옵션으로 체크박스/라디오버튼의 세로정렬 옵션을 추가하거나 기본 세로정렬을 가운데 정렬로 했으면합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
현재 상태 - 라벨은 세로정렬:가운데, 체크박스/라디오버튼 세로정렬:기본 위
![image](https://user-images.githubusercontent.com/7067615/98522255-cf776500-22b7-11eb-97eb-52299a856a96.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@eumminsun @onlyeon 스타일 적용을 통한 빠른 조치 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 업무가 산적해있어 11월에는 진행이 어렵습니다. 차주 중에 다시 검토해보겠습니다.

**Comment by veldise** [comment]
@sunghoon 
현재 국토부 / LH공사 / 수원시청 / 다이렉트 클라우드 / 교통연 등의 외부 사이트 지원을 우선으로 하고 있어,
당장은 진행이 어렵고 위 사이트 지원이 정리되는대로 다시 검토하기로 했습니다.

**Comment by sunghoon** [comment]
@veldise 일정잡기 어려우면 업무량 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
개발 쪽은 정렬 옵션 1개만 추가하면 되어서 1일 내로 처리가 가능합니다.
다만 퍼블리싱 작업이 주가 되는 일이라 전체 업무량은 조금 더 논의가 필요합니다.

**Comment by eumminsun** [comment]
@sunghoon @veldise 
기획, 퍼블리싱 업무량도 각 1일 / 총 2일 정도로 생각하고 있습니다.
