### ISSUE TITLE
[DSL]  forecasts 문을 사용한 챠트가 갑자기 오류가 납니다.(정상동작했던 보고서임)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2701]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

어제(2020/11/09) 오후까지 생성했던 보고서 &&  Analyzer 의 검색결과가
오늘(2020/11/10 08시) 은 전부 에러 납니다.
<img width="786" alt="스크린샷 2020-11-10 오전 8 06 21" src="https://user-images.githubusercontent.com/5126497/98607267-2e76c180-232c-11eb-911a-aa8e21f3b199.png">

- 데이터모델 : EDU_Beijing_air_2013_2017_18
- 검색어
`*  |  where  station='Dingling'   and  CTIME >= 20161201000000
|  fields station,CTIME,year,month,day,hour,PM2_5,TEMP 
| sort CTIME 
| fillna PM2_5
| typecast CTIME timestamp "YYYYMMDDHHmmss" 
| forecasts CTIME PM2_5 f_coeff=72 index_type=timestamp`

- 참고 보고서 : http://b-iris.mobigen.com:80/studio/exported/dc30aa8243204de09732487131337d2fde468ab7a04d47468334757089e5546e

- 건의 사항
## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
forecasts 가 아니라 이 구문 때문에 에러나는 것 같습니다.
`*  |  where  station='Dingling'   and  CTIME  >=  20161201000000`

**Comment by veldise** [comment]
```js
{"code":500,"message":"{\"message\":\"angora error: <class 'TypeError'>\\n(\\\"__init__() missing 1 required positional argument: 'stackTrace'\\\",)\"}"}
```

**Comment by seoryjj** [comment]
서승환책임님과 오늘 아침에 내용 공유했습니다.
서 책임님이 어제 수정한 걸 오늘 아침에 다시 원복했고, 이제 다시  정상 동작합니다.
이 이슈는 닫습니다.
