### ISSUE TITLE
[Studio] 테이블-시각화옵션 에서 "조건부서식" 에서 셀의 값이 true/false 로 나오는 경우에는 적용이 안됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2702]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

보고서 : http://b-iris.mobigen.com:80/studio/exported/ea3ce84fb07d4c339dfddb75ee0133284b0727c1bb8c4d4182e9c2df98c3bdd7

- anomaly , outlier 컬럼의 값이 true / false 로 나오는데,  조건부 서식으로 true, false 로 넣으면 적용되지 않습니다. 숫자, 텍스트는 잘 됩니다.
<img width="551" alt="스크린샷 2020-11-11 오전 9 14 05" src="https://user-images.githubusercontent.com/5126497/98749571-48cd9f80-23ff-11eb-898f-78f0a57864e2.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 확인하여 빠른 조치 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon
일정 계획을 수립 중입니다. 차주 월요일(11/23)에는 정리해서 말씀드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
12/10 패치를 목표로 진행하겠습니다.
