### ISSUE TITLE
[Studio] 탭 적용대상에 에디터 추가 안됨

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2703]
## 버그 설명 ##
탭 적용대상에 에디터가 추가되지 않습니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서에 탭 추가
2. 보고서에 에디터 추가
3. 탭 클릭 후 > 속성 > 적용대상 클릭 후 에디터 클릭
4. 에디터 선택 되지 않음.

## 예상한 행동 ##
에디터가 선택 되어서 탭 클릭시 화면에 표시/미표시 된다.

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 보고된 이슈 문제를 확인하였습니다. 빠른 조치 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon
일정 계획을 수립 중입니다. 차주 월요일(11/23)에는 정리해서 말씀드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
12/3 릴리즈를 목표로 진행하겠습니다.
