### ISSUE TITLE
[Studio]   챠트 - anomaly 에서 처음에는 무조건 챠트오류가 뜨지만, 챠트가 그려진 후에는 같은 설정을 해도 챠트오류는 뜨지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2704]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

보고서 : anomaly 챠트 이슈  http://b-iris.mobigen.com:80/studio/exported/1620491e8314435c8da6926327f5f13f3870f211071340e487ea5701daa43fff

1. high chart 오류 메세지가 꺽은선형과 다릅니다. 
<img width="451" alt="스크린샷 2020-11-11 오전 11 11 51" src="https://user-images.githubusercontent.com/5126497/98756963-e41a4100-240e-11eb-96ae-b0c09f2991cb.png">

<img width="376" alt="스크린샷 2020-11-11 오전 11 11 57" src="https://user-images.githubusercontent.com/5126497/98756935-d82e7f00-240e-11eb-8218-919afb017af4.png">

2. 맨처음(그룹 변수가 선택하지 않음) 에는 오류 , 그 후 시각화옵션에 그룹 변수를 바르게 STS 로 설정하면 원하는 챠트가 그려집니다.
    그 후에 다시 그룹변수를 선택하지 않음 으로 하면 오류 메세지 없이 챠트가 그려집니다. 물론 원하는 챠트는 아니지만요.
<img width="700" alt="스크린샷 2020-11-11 오전 11 13 50" src="https://user-images.githubusercontent.com/5126497/98757035-00b67900-240f-11eb-86fb-99002cb93733.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 확인및 빠른 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 Highcharts 에러가 발생하지 않도록 처리하여 11/26 패치를 목표로 진행중입니다.

**Comment by sunghoon** [comment]
@veldise @EricLeeMbg @stgim 본 이슈에 대해서 참고 보고서가 이슈에 보고 되어 있는데. 오늘 배포시 여전히 표기되고 있지 않습니다.

**Comment by sunghoon** [comment]
@seoryjj 본 이슈와 연결된 보고서 확인 바랍니다.

**Comment by veldise** [comment]
다같이 모여서 확인하였습니다.
