### ISSUE TITLE
[Studio] "보고서 가져오기" 에서 보고서 목록의 "구분"이  대시보드를 제외하면 보고서이름으로 나오는데, 구분에 카테고리 정보를 넣어주세요

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2706]
## 기능 요청 ##

- studio 에서 "보고서 가져오기" - 팝업/포틀릿  하면 보고서 목록이 보입니다. "구분" 이 대시보드 가 아닌 경우에는 보고서 이름으로 나옵니다.
<img width="400" alt="스크린샷 2020-11-12 오전 10 42 06" src="https://user-images.githubusercontent.com/5126497/98885018-97993900-24d4-11eb-9e91-67226bcab920.png">

- studio 에서 분석탬플릿 불러오기의 경우에는 "구분" 이 검색, 시각화 등으로 나오고 있습니다. 보고서 불러오기 목록에서 "구분" 은  카테고리 정보로 보여주는 게 더 유용해보입니다.
<img width="206" alt="스크린샷 2020-11-12 오전 10 44 41" src="https://user-images.githubusercontent.com/5126497/98885074-bd264280-24d4-11eb-8c05-8941d19ce062.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by seoryjj** [comment]
"대시보드"   구분의 정의가 이상합니다. 
카테고리가 있으면 전부 "대시보드"  로 나오고, 카테고리가 미분류된 것은 보고서 이름으로 나오고 있습니다.

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 개선을 위한 업무 진행 바랍니다.

**Comment by veldise** [comment]
3/5 패치 예정입니다.
