### ISSUE TITLE
[LH빅데이터] Network graph 시각화 차트추가 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2707]
## 기능 요청 ##
Network graph 시각화 차트추가 요청
LH빅데이터 플랫폼의 분석과제중에 "LH평판분석" 시각화를 위한 Network graph 차트필요

[예시화면]
![image](https://user-images.githubusercontent.com/4444717/98893127-2910a700-24e5-11eb-94d5-914c4d0d8004.png)

## 원하는 솔루션 설명 ##
Network graph 시각화 차트추가 요청

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 해당 내용에 대하여 @JeongHeeDong 팀장님과 업무 협조를 진행 해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn 어떻게 진행 하시기로 결정되셨는지요? 내용 및 일정 정보 공유 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon
기획은 진행중이고 개발쪽은 일정 계획을 수립 중입니다. 차주 월요일(11/23)에는 정리해서 말씀드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
추가로 기획 및 검토가 필요한 부분이 있어, 금주 중에 일정 결정하여 알려드리겠습니다.

**Comment by veldise** [comment]
@sunghoon 
LH 공사 일정에 맞추어 패치 예정이고, 개발은 12월 2일 정도에 완료될 예정입니다.
