### ISSUE TITLE
[Studio] 탭이 있는 보고서에서 영역설정 할때에, 컴포넌트 선택이 제대로 되지 않음.

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2708]
## 버그 설명 ##
탭이 있는 보고서에서, 영역설정을 이용하여 컴포넌트 선택 할때, 표시되지 않은 탭의 컴포넌트까지 선택됩니다.
선택 했을때는 표시되고 있는 컴포넌트만 선택된것처럼 보이지만,  위치를 변경하거나 삭제할경우 표시되지 않은 탭의 컴포넌트들도 같이 실행됩니다.
아래의 스크린샷으로 확인 부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서에서 탭1,2 설정
2. 각 탭에 컴포넌트 추가
3. 탭2 클릭 한 뒤, 영역 설정 한 후에 위치변경
4. 탭1의 컴포넌트까지 선택됨. 탭1의 컴포넌트도 위치가 변경된다.
5. 삭제 할 경우, 같이 삭제됨.

## 예상한 행동 ##
탭 2의 컴포넌트들만 선택된다.
탭 2의 컴포넌트들만 위치가 변경 된다.
탭 2의 컴포넌트들만 삭제된다.

## 스크린샷 ##
1. 탭1 설정
![image](https://user-images.githubusercontent.com/3972489/98901969-1784ca80-24f8-11eb-9fd9-ac9ab9c975d0.png)

2. 탭2 설정
![image](https://user-images.githubusercontent.com/3972489/98901984-1f446f00-24f8-11eb-8c7b-ddfb25040418.png)

3. 탭2에서 위치변경을 위해 영역설정
![image](https://user-images.githubusercontent.com/3972489/98901997-28354080-24f8-11eb-9a98-e9b73e9c9893.png)

4. 위치변경 후 (삭제할 경우 다같이 삭제됨)
![image](https://user-images.githubusercontent.com/3972489/98902013-2ff4e500-24f8-11eb-95e6-850c8b15a68d.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 확인 후 조치 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 국토부 / LH공사 / 수원시청 / 다이렉트 클라우드 / 교통연 등의 외부 사이트 지원을 우선으로 하고 있어,
당장은 진행이 어렵고 위 사이트 지원이 정리되는대로 다시 검토하기로 했습니다.

**Comment by veldise** [comment]
@sunghoon 
마우스 드래그로 객체를 선택시 객체의 invisible 상태이면 선택되지 않도록 처리하면 됩니다.
처리 자체는 간단한데 테스트를 면밀하게 수행해야 합니다. (최대 2~3일)

**Comment by veldise** [comment]
금일(1/14) 패치 예정입니다
