### ISSUE TITLE
[studio]라벨 행 위치고정이 안됩니다

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2709]
## 버그 설명 ##
빈 행이 있는 라벨이 라벨을 클릭할 때마다 행이 바껴요

## 재현하는 방법 ##
스크린 샷에 있는 라벨을 선택하면 행의 위치가 바껴요

## 예상한 행동 ##
라벨 안 내용의 행이 바뀌지않고 썼던 행 그대로 출력

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/50221479/99200892-7180db00-27eb-11eb-8afe-c03fb6e44b69.png)
![image](https://user-images.githubusercontent.com/50221479/99200910-937a5d80-27eb-11eb-8537-a58acdbfb9bf.png)

## 로그 ##
'이슈_라벨위치고정X_한다연'
http://b-iris.mobigen.com:80/studio/exported/5b25200b86664000837c5a4d06e69388e970d828b9434f01b125a3b54ead9f52

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
상황이 잘 재현되지 않습니다. 조금 더 구체적인 정보를 주시면 좋을것 같습니다.

**Comment by handayeon** [comment]
80%로 페이지를 축소해서 봤을 때 재현이 되고 100%로 봤을 땐 현상이 일어나지 않습니다 !!
일단 클로즈 하겠습니당 ..!!  페이지를 축소했을 때 오동작에 대해서 UI팀에서 내부적으로 협의한다고 합니다 !
