### ISSUE TITLE
[Studio] 보고서 목록 그리드 뷰 너비 오류

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2710]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

보고서 메뉴 선택 후 보고서 목록에서 브라우저의 창 크기가 일정 크기로 줄이거나 혹은 기타 모니터에서 목록을 보는 경우 그리드 뷰의 너비가 맞지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

로그인 -> Studio  -> 브라우저 창 크기 조절 (특정 크기 이하로 줄어드는 경우)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/99348383-cd775c80-28dc-11eb-8ef0-c69af6077340.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@onlyeon 해당 내용을 검토 확인해 주세요.

**Comment by onlyeon** [comment]
[[공통] 목록 화면 최적화 #127](https://github.com/mobigen/IRIS/issues/127) 이슈를 처리하며 기준 해상도를 FHD(1920*1080) 로 정의해서 발생한 문제입니다.

금주 이슈 회의 때 논의될 수 있도록 요청하겠습니다.
