### ISSUE TITLE
[Studio] 탭이있는 보고서 수정 화면에서 모든 탭의 컴포넌트들이 표시됨

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2711]
## 버그 설명 ##
탭이 있는 보고서를 수정할때, 모든 탭의 컴포넌트들이 표시됩니다.
아래의 스크린샷으로 내용 확인 부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서에 탭 추가 후 탭1,2 설정
2. 각각의 탭에 컴포넌트 추가
3. 보고서 저장후 목록으로 이동
4. 다시 보고서 수정 클릭
5. 모든 탭의 컴포넌트들이 표시됨.

## 예상한 행동 ##
기본 탭에 설정된 컴포넌트들만 표시된다.

## 스크린샷 ##
1. 탭1
![image](https://user-images.githubusercontent.com/3972489/99468588-3cf45700-2984-11eb-9e02-0d0b2bde863d.png)

2. 탭2
![image](https://user-images.githubusercontent.com/3972489/99468608-47aeec00-2984-11eb-9da4-429b1594d8d1.png)

3. 탭3
![image](https://user-images.githubusercontent.com/3972489/99468628-4da4cd00-2984-11eb-82e4-af054a019918.png)

4. 목록에서 수정 클릭해서 표시된 보고서 화면 
![image](https://user-images.githubusercontent.com/3972489/99468673-6614e780-2984-11eb-9b82-bba1d78596a4.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 편집모드 초기 설정할때 탭에서 설정된 형태로 컴포넌트 표시여부가 될 수 있도록 빠른 조치 바랍니다.

**Comment by sunghoon** [comment]
@veldise @rhcpn 업무 진행 일정 계획 정보 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 국토부 / LH공사 / 수원시청 / 다이렉트 클라우드 / 교통연 등의 외부 사이트 지원을 우선으로 하고 있어,
당장은 진행이 어렵고 위 사이트 지원이 정리되는대로 다시 검토하기로 했습니다.

**Comment by veldise** [comment]
@sunghoon
각 객체의 초기화 처리 문제입니다. 탭 객체와 관련된 동작이지만 객체 쪽에서 수정이 필요하여
모든 객체에 대하여 처리 방법 및 코드에 대한 검토가 필요합니다.

**Comment by veldise** [comment]
차주 (1/21) 패치 예정입니다
