### ISSUE TITLE
[Studio] 기간 설정 객체

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2712]
## 기능 요청 ##
보통 기간설정을 할때 날짜로만 하는 설정이 대부분이라 시간이 안보였으면 좋겠습니다.
옵션으로 처리가 복잡할 것 같은데 날짜 기간 설정 객체를 추가해주셨으면 합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 디폴트값이 다르게 설정되어 있는 날짜 컴포넌트를 추가하는 방향으로 기획하여 진행 부탁드립니다.
