### ISSUE TITLE
[LH빅데이터] Studio: 테이블 멀티라인 출력

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2713]
## 버그 설명 ##
LH빅데이터 보고서 구성에 필요한 테이블 컬럼의 멀티라인 출력 기능 요청
데이터에 포함된 텍스트에 \n또는 <br>이 있을 경우 줄바꿈 처리 여부 옵션 추가
Row 높이는 설정으로 지정

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/100040622-f783ce00-2e4a-11eb-89f6-247e8476f2dd.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 검토 의견 바랍니다.

**Comment by sunghoon** [comment]
@veldise 업무 진행 일정 정보를 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
금주중에 개발 진행하여 12/10 패치를 목표로 하고 있습니다.
