### ISSUE TITLE
Studio / 지도 컴포넌트의 레이어 활성화 스크롤 오류

### ISSUE THREAD

**Issue by sunghoon** [mobigen/IRIS-BigData-Platform#2714]
- 참조 보고서 : GeoJSON테스트2

- 버그 재현
  - 레이어 Show/Hide 버튼 클릭
  - 하위 레이어 활성화 시도를 위한 스크롤 동작시 오류
     - 레이어 활성화 스크롤이 아닌 지도 줌 인/아웃이 동작 

![스크린샷 2020-11-25 오전 9 26 17](https://user-images.githubusercontent.com/512653/100166527-48093300-2f00-11eb-848c-21ff8eebb112.png)

**Comment by sunghoon** [comment]
@veldise @rhcpn 해당 내용을 확인하여 빠른 조치 바랍니다. 일정 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
백승욱 책임이 빠르게 처리해줘서 12/3 패치 예정입니다.
