### ISSUE TITLE
[DSL]  절대값을 구하는 함수가 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2716]
## 기능 요청 ##
b-iris.mobigen.com

절대값을 구하려고 합니다.

- 현재 가능한 방법 : typecast 로 text 변환 후 substr 으로 - 부호 제외 한 후 숫자형으로 변환
<img width="1033" alt="스크린샷 2020-11-25 오후 3 51 35" src="https://user-images.githubusercontent.com/5126497/100192902-1ca13b00-2f36-11eb-9a71-aa948748b605.png">

- 현재 상황
1. 현재  **calculate** 에서는 -1 을 곱하면 에러가 납니다.
<img width="592" alt="스크린샷 2020-11-25 오후 3 54 11" src="https://user-images.githubusercontent.com/5126497/100193083-799cf100-2f36-11eb-985b-b153f938b787.png">

2. 현재 stats 에는 abs 함수가 없습니다.   DSL sql  에서도 제공하지 않는지 에러납니다.
<img width="597" alt="스크린샷 2020-11-25 오후 3 59 24" src="https://user-images.githubusercontent.com/5126497/100193512-473fc380-2f37-11eb-80aa-fab99535571f.png">

### 원하는 기능
- calculate 에   -1 곱하기  가 가능하거나
- abs  필드   as 뉴필드   

이런 기능의 DSL 이 필요합니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 관련 내용을 지원하기 위한 DSL 준비 및 일정정보 공유 해 주세요.

**Comment by seungfwani** [comment]
abs 명령어를 추가하였습니다.

[명령어 문서](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/abs.html)
![Screen Shot 2021-01-18 at 9 46 26 AM](https://user-images.githubusercontent.com/46172579/104861158-09c54880-5972-11eb-8ffe-ec8da9bd3043.png)
