### ISSUE TITLE
[Studio] 지도 - 시각화옵션 - 색상 - 임계치 에서 0 을 설정하면 범례에 0 이 표시되지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2717]
## 버그 설명 ##
b-iris.mobigen.com demo계정

- Studio 의 지도 객체에서 시각화옵션 - 색상 탭에서 임계치 설정

<img width="554" alt="스크린샷 2020-11-26 오전 8 19 29" src="https://user-images.githubusercontent.com/5126497/100291192-70f0fd00-2fc0-11eb-983c-d9952cee848d.png">

- 지도에 표시되는 범례에 0 인 값은 보이지 않습니다.
<img width="91" alt="스크린샷 2020-11-26 오전 8 19 35" src="https://user-images.githubusercontent.com/5126497/100291232-92ea7f80-2fc0-11eb-9e04-bb2b26b36a49.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 확인 및 조치 바랍니다.
