### ISSUE TITLE
[DSL] case  문에서 컬럼에 따옴표 넣는 규칙이 manual 과 다르고, 다른 DSL의 컬럼 규칙과 통일되어 있지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2719]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

## CASE 의 manual 내용 
```
`컬럼명에는 원하는 컬럼명을 ` ` 혹은 따옴표 없이 넣을 수 있다.

> 띄어쓰기가 포함된 컬럼명은 ` ` 를 통해 넣을 수 있다.`

`as 뒤의 컬럼명에는 ` ` 혹은 따옴표 없이 컬럼명을 설정할 수 있다.

> 띄어쓰기가 포함된 컬럼명은 ` ` 를 통해 넣을 수 있다.`
```

## 시험결과

- 데이터 모델 : 한국_순이동인구통계_1970_2020

- 검색어 1 : OK  컬럼명에 따옴표 넣음. 공백이 없어서 안 넣어도 되는데 넣어야 동작하나 결과가 **틀림** 전부 plus 로 나옴
`* |  where 행정구역 = '서울특별시'      |  case when '계'  < 0.0  then  'minus' otherwise  'plus'     as  aa`
<img width="890" alt="스크린샷 2020-11-26 오후 4 23 10" src="https://user-images.githubusercontent.com/5126497/100319868-b256cc00-3003-11eb-8ca3-8fc13db58855.png">

- 검색어 2 : 에러  ->  컬럼명에 따옴표 없음
`* |  where 행정구역 = '서울특별시'      |  case when 계  < 0.0  then  'minus' otherwise  'plus'     as  aa`

- 검색어 3 : 한글 컬럼을 영문으로 변경하면 따옴표 없이 동작 OK.  같은 DSL 인 **rename** 에서는 **한글 컬럼명에 따옴표 없이 정상 동작**하고 있음 !!!!
`* |  where 행정구역 = '서울특별시'      |  rename  계  temp_col |  case when   temp_col   < 0.0  then  'minus' otherwise  'plus'     as  aa`
<img width="928" alt="스크린샷 2020-11-26 오후 4 25 31" src="https://user-images.githubusercontent.com/5126497/100320066-03ff5680-3004-11eb-964d-9bcd2a84f468.png">

- 요약
DSL **case**  는 다른 DSL 과는 다르게 공백없는 한글 컬럼명이라도 한글에는 꼭 작은 따옴표를 써야하며, 결과도 맞지 않음!!!!

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
기능 오류 보다
한글컬럼명을 쓴 case 문의 결과가 맞지 않는 게 더 치명적인 문제라고 생각됩니다.  case 로 만든 통계 결과를 리포트, 대시보드로 만들면 잘못된 정보가 될테니까요.

수원시나 다른 공공기관의 데이터모델에서 한글컬럼명을 많이 사용하므로 빠른 조치를 요청드립니다.

**Comment by sunghoon** [comment]
@seungfwani 확인 후 조치 바랍니다.

**Comment by seungfwani** [comment]
해당 명령어 파싱에 미비한 부분이 있어 수정이 필요합니다. 12월 초에 배포할 수 있도록 하겠습니다.

**Comment by seungfwani** [comment]
b-iris 에서 테스트 완료했습니다.
![Screen Shot 2020-12-18 at 1 05 03 PM](https://user-images.githubusercontent.com/46172579/102573420-c8066f80-4131-11eb-9b7b-c89d89a907da.png)
![Screen Shot 2020-12-18 at 1 04 19 PM](https://user-images.githubusercontent.com/46172579/102573421-c9379c80-4131-11eb-9202-623f166f1c81.png)
