### ISSUE TITLE
[LH빅데이터]Studio의 차트를 이미지로 저장하는 기능 필요

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2720]
## 기능 요청 ##
Studio에서 차트출력 후 저장 기능이 현재는 csv로만 가능함
이미지 저장 기능 추가 필요

csv로저장 / 이미지로 저장  모두  가능 하도록 기능 필요

![image](https://user-images.githubusercontent.com/4444717/100320705-ebdc0700-3004-11eb-81bd-5eb3ebeb7cd2.png)

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 기능 검토 바랍니다.

**Comment by sunghoon** [comment]
@veldise 업무 진행 일정을 공유 해 주세요.

**Comment by veldise** [comment]
@sunghoon 
금주중에 개발 진행하여 12/10 패치를 목표로 하고 있습니다.
