### ISSUE TITLE
[DSL,Analyzer,Studio 공통] DSL "fit" 으로 생성한 기계학습 모델을 가져와서 predict 로 사용할 때, angora 에러발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2722]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 기계학습 모델이 이미 목록에 있어서 predict 로 예측하려는데 에러 발생합니다.
- 모델명 : EDU_1022_TEST_RF_CLASSIFICATION_WINE  
<img width="648" alt="스크린샷 2020-12-01 오후 3 16 40" src="https://user-images.githubusercontent.com/5126497/100704092-3a641980-33e8-11eb-91e4-ec91db5026ce.png">

- 검증용 보고서 :   이슈_분류기계학습_RF_2차시험_와인데이터
http://b-iris.mobigen.com:80/studio/exported/354c65f6e1554fd794156d57d121bd6fe6c3a2904e084b038e07152637bf49af

- predict 구문 전까지는 동작,  predict 에서 모델을 사용하려면 에러 발생합니다.

- 모델 : EDU_TEST_WINE

`* | scaler minmax  Alcohol to Alcohol_s,
Malic_acid to Malic_acid_s,
Ash to Ash_s, 
Alcalinity_ash to Alcalinity_ash_s,
Magnesium to Magnesium_s,
Phenols to Phenols_s,
Flavanoids to Flavanoids_s, 
Proanthocyanins to Proanthocyanins_s,
Hue to Hue_s,
OD280_OD315 to OD280_OD315_s,
Proline to Proline_s |  indexer classId to classId_s | predict  demo.EDU_1022_TEST_RF_CLASSIFICATION_WINE   Alcohol_s, Malic_acid_s,Ash_s, Alcalinity_ash_s,Magnesium_s,Phenols_s,Flavanoids_s, Proanthocyanins_s, Hue_s,OD280_OD315_s,Proline_s |
fields classId, classId_s, prediction`

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @seungfwani 확인 및 조치 바랍니다.

**Comment by seungfwani** [comment]
동작 확인 완료 했습니다
![Screen Shot 2020-12-18 at 12 47 39 PM](https://user-images.githubusercontent.com/46172579/102572368-47467400-412f-11eb-8530-7d3cee0b3b15.png)

![Screen Shot 2020-12-18 at 12 47 45 PM](https://user-images.githubusercontent.com/46172579/102572364-431a5680-412f-11eb-9241-444e09c83c1c.png)
