### ISSUE TITLE
[Studio] 날짜/시간선택 객체에서 시각화옵션 달력범위제한 설정한 게 저장되지 않고 오늘날짜로 셋팅되어버립니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2723]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

어제 생성해서 편집화면에서 시험할 때는 정상 동작했는데,  오늘(2020/12/03) 오전에 보고서를 열어서 편집해보니 발견됩니다.

- 날짜/시간선택 객체  에서 달력범위제한 - 사용자설정
<img width="635" alt="스크린샷 2020-12-03 오전 10 43 35" src="https://user-images.githubusercontent.com/5126497/100952787-8633d180-3554-11eb-907c-2281a08a258a.png">

- 오늘로 변경되어 있음

<img width="705" alt="스크린샷 2020-12-03 오전 10 41 19" src="https://user-images.githubusercontent.com/5126497/100952580-29381b80-3554-11eb-9bac-b91a0d395014.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
예전 8월에 생성한 보고서 "EDU_component_날짜시간선택"  http://b-iris.mobigen.com:80/studio/exported/f6319faaccfe41d5ace3de9d62eadad344bfdf7cd40c491389816bf76cb13188
은  달력범위를 2013/03/01 ~ 2017/02/28  로 설정한 겁니다. 그래서 2017년 2월까지만 화살표로 달력이 이동합니다.
- 하지만 "오늘" 을 클릭하면 그게 다 풀립니다.
- 편집화면에서는 예전 설정값이 저장되어 있지 않습니다. 그래서 다시 맞추고 저장해야 합니다.

**Comment by sunghoon** [comment]
@veldise 이슈를 확인하고 조치 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 업무 진행 계획을 공유해 주세요.

**Comment by veldise** [comment]
12/17~12/18 Release 에서 해결된 것으로 추정되며 현재는 재현되지 않습니다.
