### ISSUE TITLE
[Studio]  데이터객체의 넓이를 조정한 후 저장했는데, 다시 디폴트 길이로 되어 있습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2724]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

<img width="164" alt="스크린샷 2020-12-03 오전 10 47 34" src="https://user-images.githubusercontent.com/5126497/100953043-0823fa80-3555-11eb-8790-c37f979489e6.png">

<img width="213" alt="스크린샷 2020-12-03 오전 10 48 20" src="https://user-images.githubusercontent.com/5126497/100953060-12de8f80-3555-11eb-9ea7-aae03e6b3a5f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 이슈를 확인하고 조치 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 업무 진행 계획을 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
해당 문제 자체는 간단히 해결이 가능합니다만 비슷한 객체(Text-Converter, Popup, ...)도 같은 수정이 필요하고
지금은 국토부/수원시 이슈 대응중이라 12/17 패치에서 해결하겠습니다.
