### ISSUE TITLE
수원시 보고서 연결정보 미표시

### ISSUE THREAD

**Issue by sanxoo** [mobigen/IRIS-BigData-Platform#2725]
## 버그 설명 ##
수원시 분석 플랫폼 업그레이드 후...
DBMS MariaDB 연결정보 생성 후, 보고서 작성 화면에서 연결 정보가 보이지 않습니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/8120623/100975191-f6584c80-3580-11eb-988a-c42cd6466184.png)

![image](https://user-images.githubusercontent.com/8120623/100975265-1425b180-3581-11eb-959e-b5d2d65d37ba.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 빠른 확인 후 조치 바랍니다.

**Comment by rhcpn** [comment]
해당 건은 12/11 패치 예정으로 담당자와 협의 하였습니다.
참고로 수원시 커스터마이징 기능 중에 하나가 패치시 누락되어 발생한 현상입니다.

**Comment by veldise** [comment]
문서에서도 누락됐었습니다. 죄송합니다.

**Comment by sunghoon** [comment]
@veldise 조치 완료 되었는지요?

**Comment by veldise** [comment]
수원시에 커스텀 요소로 패치되어 해결됐습니다.
