### ISSUE TITLE
[DSL] anomalies 에서  date 필드가 14자리가 아닌 경우에, 꼭 fields 로 컬럼을 재지정한 후 anomalies 를 실행해야 결과가 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2726]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

-데이터모델 : PM_MME_TEST_JJ_1
- 검색어 : fields 를 넣어서 결과가 나온 경우
`* |  where EMS_ID = 'GURO_MME1'  | sort COL_DT | calculate INIT_SUCCESS / INIT_ATTEMPT  as SUCC_RATE   |  fillna SUCC_RATE 0 |  fields COL_DT,EMS_ID,OBJECT,SUCC_RATE   |  anomalies COL_DT SUCC_RATE  by=OBJECT`

<img width="1170" alt="스크린샷 2020-12-07 오전 9 55 45" src="https://user-images.githubusercontent.com/5126497/101298651-63662d80-3872-11eb-9211-3913414e5265.png">

- 검색어 : fields 를 빼면 결과가 없다고 나옴
`* |  where EMS_ID = 'GURO_MME1'  | sort COL_DT | calculate INIT_SUCCESS / INIT_ATTEMPT  as SUCC_RATE   |  fillna SUCC_RATE 0    |  anomalies COL_DT SUCC_RATE  by=OBJECT`

<img width="1003" alt="스크린샷 2020-12-07 오전 9 56 40" src="https://user-images.githubusercontent.com/5126497/101298680-82fd5600-3872-11eb-9a14-069f29ab4e4a.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
fields 를 해도 결과가 나오지만 동일 시간에 2개의 데이터가 나오고 있습니다.
원본에는 OBJECT = '/2'  가 시간에 1개씩
<img width="1066" alt="스크린샷 2020-12-07 오전 11 19 32" src="https://user-images.githubusercontent.com/5126497/101302105-1be59e80-387e-11eb-9745-e8b269f38370.png">

그러나 위의 첫번째 결과를 보면 2개씩 나옵니다. 이것도 해결해야 합니다.

**Comment by seoryjj** [comment]
이제 보니 시간이 5분 간격이 아니고 결과가 1분으로 나오네요. 즉 꼭 14자리여야 시간 처리가 바로 되네요...

**Comment by sunghoon** [comment]
@anhm @seungfwani 업무 검토 해 주세요.

**Comment by seungfwani** [comment]
b-iris 동작 확인 완료 했습니다.

![Screen Shot 2020-12-18 at 1 07 40 PM](https://user-images.githubusercontent.com/46172579/102573569-13b91900-4132-11eb-8e94-60f56958e333.png)
![Screen Shot 2020-12-18 at 1 08 00 PM](https://user-images.githubusercontent.com/46172579/102573579-161b7300-4132-11eb-8b68-84e6734a0a42.png)
