### ISSUE TITLE
[DSL] timediff  명령어에서 시간문자열, 컬럼명 의 diff 결과가 null 로 나옵니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2727]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- 검색어 
`* |  where  C_COMPANY = '17060101'   |  substr C_DATEOFACCESSUTCTOLOCAL 1 10 as YYYYMMDD |   distinct YYYYMMDD | fillna  YYYYMMDD  | fields YYYYMMDD | typecast 'YYYYMMDD' date "YYYY-MM-DD"  |    timediff day   '2020-11-20'  'YYYYMMDD' `

<img width="1159" alt="스크린샷 2020-12-08 오후 1 37 18" src="https://user-images.githubusercontent.com/5126497/101440621-823fef00-395a-11eb-9986-8367ace9905d.png">

- 분석탬플릿 :   test_timediff   참조

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @seungfwani 업무 진행 계획을 공유해 주세요.

**Comment by seungfwani** [comment]
b-iris 동작 확인 완료 했습니다.

[timediff 명령어 문서](http://docs.iris.tools/manual/IRIS-Manual/IRIS-Discovery-Middleware/command/commands/timediff)

```
* | where C_COMPANY = '17060101' | substr C_DATEOFACCESSUTCTOLOCAL 1 10 as YYYYMMDD | distinct YYYYMMDD | fillna YYYYMMDD | fields YYYYMMDD | typecast 'YYYYMMDD' date "YYYY-MM-DD" | timediff day '2020-11-20' 'YYYY-MM-DD' `YYYYMMDD`
```

![Screen Shot 2020-12-18 at 12 51 40 PM](https://user-images.githubusercontent.com/46172579/102572551-c89e0680-412f-11eb-9b57-29143408fd7c.png)
