### ISSUE TITLE
[데이터모델] 메뉴 - 새모델 - 컬럼 설정 시  컬럼 유형 선택 콤보박스가 위로 열리면 선택할 수 없습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2728]
## 버그 설명 ##
b-iris.mobigen.com demo

Mac  크롬브라우저 100% 

- 새모델 생성 시 컬럼 유형을 선택하는 콤보박스가 위로 열리면 잘려서 선택 할 수 없습니다.  위로는 이동이 스크롤바 이동이 막혀있습니다. 

<img width="990" alt="스크린샷 2020-12-08 오후 2 31 30" src="https://user-images.githubusercontent.com/5126497/101444148-37c27080-3962-11eb-81e9-a8a2c9af340d.png">

브라우저를 100% 가 아니라 계속 축소를 하다보면 콤보박스가 아래로 변할 때가 있는데, 그 때 아래로 스크롤바 이동하여서 선택이 됩니다.
<img width="823" alt="스크린샷 2020-12-08 오후 2 42 12" src="https://user-images.githubusercontent.com/5126497/101444827-bbc92800-3963-11eb-88ef-57e076e08be3.png">

- 콤보박스를 전부 아래로 해주세요.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise @onlyeon 내용을 확인하고 조치 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
Combo-box 목록 부분을 JS/CSS 모두 완전히 다른 방식으로 변경해야 해결이 가능한 이슈입니다.
현재 IRIS Repo 에 이슈는 등록되어 있으며, LH공사 등 외부사이트 지원 등이 마무리 되어야 진행이 가능할 것 같습니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 해당 이슈 처리 어떻게 진행되고 있나요?

**Comment by veldise** [comment]
@sunghoon 
현재 처리중입니다만 다소 어려움이 있어서 지연되고 있습니다.

**Comment by sunghoon** [comment]
@veldise 얼마나 진행되었으며, 언제까지 처리하는것이 목표일정인지 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 절반 정도 진행되었고 차주 초에 마무리 짓고 2월 초에 패치 적용하는 것으로 생각하고 있습니다.

**Comment by veldise** [comment]
미비점이 있어 패치가 늦어졌습니다. 금주(2/25) 패치 예정입니다.
