### ISSUE TITLE
[데이터 모델] 새모델 생성 시 샘플데이터 조회 지연

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2729]
## 버그 설명 ##
새모델 생성 시 참조하는 테이블/뷰의 데이터가 많아 샘플 데이터 조회가 지연되면 데이터 모델 생성을 할 수가 없습니다.
샘플 데이터 조회를 옵션으로 처리 했으면 좋겠습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
아래 화면에서 진행이 안됨.
![image](https://user-images.githubusercontent.com/7067615/101449653-8412ae00-396c-11eb-8cba-657dcc55c4c3.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @seungfwani 요청 사항에 대한 확인하여 조치 해 주시기 바랍니다.

**Comment by seungfwani** [comment]
메일로 답변을 하였습니다.

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 

- 샘플 데이터 조회 여부를 옵션으로 처리 할 수 있도록 화면 UX 개선을 요청드립니다.
