### ISSUE TITLE
본사-playground ( R-Studio) 미동작 

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2730]
## 버그 설명 ##
http://b-iris.mobigen.com/   의 Palyground > R-Studio 가 실행되지않고 있습니다.
정상화 부탁드립니다.

![image](https://user-images.githubusercontent.com/5468183/101604235-fd310480-3a43-11eb-8a07-589799bcfdcb.png)

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm 조치 바랍니다.

**Comment by anhm** [comment]
@jjinylee 
어떤 아이디를 이용하셨는지 알려 주시기 부탁 드립니다.

**Comment by jjinylee** [comment]
@anhm
molitpmo   입니다

**Comment by jjinylee** [comment]
@anhm  책임님. 열립니다.. -_-;;
늦게뜨는거였슴요~ 쏴리~~~
