### ISSUE TITLE
[LH빅데이터] Studio: 차트 꺽은선형 옵션 추가 요청

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2731]
## 기능 요청 ##
꺽은선형 차트에 Spline(곡선처리), maker(포인트표시여부) 옵션이 추가 되었으면 합니다.

## 원하는 솔루션 설명 ##
![image](https://user-images.githubusercontent.com/7067615/101604700-a2e47380-3a44-11eb-8c9b-ba2fb1fdd231.png)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
위 차트의 Javascript입니다.

Highcharts.chart('container', {
    **chart: {
        type: 'spline',
        scrollablePlotArea: {
            minWidth: 600,
            scrollPositionX: 1
        }
    },**
    title: {
        text: 'Solar Employment Growth by Sector, 2010-2016'
    },
    subtitle: {
        text: 'Source: thesolarfoundation.com'
    },
    yAxis: {
        title: {
            text: 'Number of Employees'
        }
    },
    xAxis: {
        accessibility: {
            rangeDescription: 'Range: 2010 to 2017'
        }
    },
    legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle'
    },
    plotOptions: {
        **series: {
            marker: {
                enabled: false
            },
            label: {
                connectorAllowed: false
            },
            pointStart: 2010
        }**
    },
    series: [{
        name: 'Installation',
        data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
    }, {
        name: 'Manufacturing',
        data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
    }, {
        name: 'Sales & Distribution',
        data: [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]
    }, {
        name: 'Project Development',
        data: [null, null, 7988, 12169, 15112, 22452, 34400, 34227]
    }, {
        name: 'Other',
        data: [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]
    }],
    responsive: {
        rules: [{
            condition: {
                maxWidth: 500
            },
            chartOptions: {
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                }
            }
        }]
    }
});

**Comment by sunghoon** [comment]
@rhcpn @eumminsun 차트 시각화 유형 추가를 해 주시기 바랍니다.
