### ISSUE TITLE
[LH빅데이터]메뉴 이미지 등록 오류 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2732]
## 버그 설명 ##
메뉴수정에서 이미지 등록시 오류가 발생함
![image](https://user-images.githubusercontent.com/4444717/101622825-e2b65580-3a5a-11eb-8bc8-4a4b8b143938.png)

## 재현하는 방법 ##
1. http://101.101.212.224:31886/ 사이트에 root계정으로 로그인
2. 메뉴설정에서 이미지 등록

**Comment by sunghoon** [comment]
@rhcpn @lyj @veldise 내용을 확인하여 빠른 조치 바랍니다.

**Comment by lyj** [comment]
그룹 아이콘 이미지 사이즈가 커서 발생하는 문제로 보여집니다.
현재 아이콘 등록 화면에서 아이콘 이미지로 대강의 사이즈 예시를 보여주고 있는 방식인데,
앞으로 조금 더 정확한 이미지 사이즈 안내와 예외처리가 필요해보입니다.
추후 해당 내용을 추가하도록 하겠습니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 해당 이슈 처리 어떻게 진행되고 있나요?

**Comment by lyj** [comment]
전반적인 UI 개선 계획이 진행중이며, 해당 이슈도 이 계획에 포함되어 같이 처리될 예정입니다.
다만 완료까지 시간이 다소 소요될 것으로 예상됩니다.
우선 여기에 메뉴 이미지 설정에대한 안내를 드리려고 합니다.

권장 이미지 사이즈
- 메뉴 아이콘: 높이 24px, 높이 24px
- 그룹 메뉴 아이콘: 높이 24px, 높이 24px
- 그룹 로고 이미지: 높이 24px, 넓이 제한 없음

용량은 40KB 이내 입니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 전반적인 UI 개선이랑은 별개로 
본 이슈에 대한 처리를 먼저 해서 사업팀에서 운영하는데 문제가 되지 않게 진행해 주시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 진행 계획 정보를 공유해 주세요.

**Comment by lyj** [comment]
다음주 이슈에 선정하여 적용할 계획입니다.

**Comment by rhcpn** [comment]
내부에서 2021 상반기 업무 정리 중에 IWP 고도화 업무에 포함 시켜서 진행 하는게 좋을것 같다는 의견입니다.
괜찮다면 상반기 중에 기능을 전체적으로 개선 하도록 하겠습니다.

**Comment by sunghoon** [comment]
@rhcpn 최종 상황을 공유해 주세요. 정희동 팀장님도 협의가 되신것인지 궁금합니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 본 이슈에 대한 최종 상태 정보를 공유해 주시기 바랍니다. 일정이 변경 되었으면 변경된 일정 정보를 공유바랍니다.

**Comment by lyj** [comment]
정희동 팀장님과는 가이드 공유를 하였고, 협의가 된것으로 알고 있습니다.
메뉴관리 개선 사항 관련 기획이 5월중 계획되어 있고, 
일정의 변동사항이 있어, 현재 정확한 종료일이 확정되지는 않았습니다.
하지만 올해 상반기 업무에 포함되어 진행될 예정입니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj @JeongHeeDong 일정 관련 부분 확인하여 업무에 참고하시기 바랍니다.
