### ISSUE TITLE
[Studio] 테이블의 목록개수 보이기를 체크하면 5 미만에는 개수 목록이 보이지 않습니다. 같이 표시해서 테이블의 시각화 통일이 필요합니다. 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2733]
## 기능 요청 ##

- 테이블 시각화 옵션
<img width="498" alt="스크린샷 2020-12-10 오전 7 55 06" src="https://user-images.githubusercontent.com/5126497/101698685-496c5b00-3abd-11eb-930a-573f2f74e609.png">

- 동일한 옵션으로 5개 이상일 때 2개의 테이블에서는 라인 위치가 딱 맞게 표시되어 보기 좋습니다.
<img width="1113" alt="스크린샷 2020-12-10 오전 7 58 04" src="https://user-images.githubusercontent.com/5126497/101698785-73be1880-3abd-11eb-9de2-756c33f8d6b8.png">

- 5개 미만일 때는 목록개수가 표시되지 않으면서 라인 위치가 맞지 않게 표시됩니다.
<img width="1101" alt="스크린샷 2020-12-10 오전 7 57 53" src="https://user-images.githubusercontent.com/5126497/101698865-951f0480-3abd-11eb-8456-709986c2df2c.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@veldise 빠른 조치 바랍니다.

**Comment by veldise** [comment]
차주 (1/21) 패치 예정입니다
