### ISSUE TITLE
[Studio] URL 내보내기 창 Title 변경

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2734]
## 기능 요청 ##
URL 내보내기의 경우 해당 URL을 크롬에서 확인 시 창 또는 탭 Title이 Studio로 나오는데 해당 보고서명으로 나오거나 지정할 수 있는 기능히 필요합니다.

## 원하는 솔루션 설명 ##
- 현재
![image](https://user-images.githubusercontent.com/7067615/101727231-750c3700-3af7-11eb-8b7f-a9d880e60de1.png)

- 향후(탭명이 보고서명이나 옵션으로 지정한 문구로)
![image](https://user-images.githubusercontent.com/7067615/101727325-9f5df480-3af7-11eb-9df7-0c3661b837ab.png)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 다이렉트 주소 접근시 보고서명이 보기 될 수 있도록 주치 바랍니다.

**Comment by veldise** [comment]
1/7 패치로 완료되었습니다.
