### ISSUE TITLE
[KORAIL] csv 파일 업로드시 에러 발생

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2735]
## 버그 설명 ##
csv 파일 업로드시 아래와 같이 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/5077625/102043892-042b8e80-3e19-11eb-804a-9156ec94795c.png)

Data File: ./tmp/8d49c658-eb2d-4427-991f-75032c098bef/FM_VENDOR_MAP_1.csv.trans.trans
Create Control File: ./tmp/8d49c658-eb2d-4427-991f-75032c098bef/FM_VENDOR_MAP_1.csv.trans.ctx
Data Splited File:
	20141231122000:dcs-210 1
		+OK SUCCESS. success count : 1
		Loading time : 0.21940112114
Traceback (most recent call last):
  File "addon/iris-load/loader.py", line 267, in <module>
    main()
  File "addon/iris-load/loader.py", line 261, in main
    proc (g, file)
  File "addon/iris-load/loader.py", line 229, in proc
    key = "%s:%s" % ( make_partition_time(items[partition_time_idx], g['partition_range']), make_partition_key(items[partition_key_idx]))
IndexError: list index out of range

## 재현하는 방법 ##
동작을 재현하는 방법 :
1.
![image](https://user-images.githubusercontent.com/5077625/102044002-405eef00-3e19-11eb-8e51-1535510dd6cb.png)

2.
![image](https://user-images.githubusercontent.com/5077625/102044463-32f63480-3e1a-11eb-8479-cb1c7c8f82bd.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm 해당 이슈 처리 어떻게 진행되고 있나요?

**Comment by anhm** [comment]
@euhyesun 
답변이 늦어서 죄송합니다.
테스트시 사용된 파일을 공유 해 주시면 테스트를 진행할수 있을것 같습니다.
가능하면 메일로 파일을 전달 부탁 드리겠습니다.

**Comment by sunghoon** [comment]
@euhyesun @anhm KORAIL 관련 완료된 상태라 본 이슈에 관련 추가 처리 내용이 있다면 메일을 통해 처리 해 주시면 좋을것 같습니다.
본 이슈는 닫도록 하겠습니다.
