### ISSUE TITLE
[Studio]라벨이 바껴요

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2736]
## 버그 설명 ##
라벨에 글씨를 붙여넣기하고 저장을 한 후에 보기를 보면 변형되어있습니다. 혹은 저장 후 다시 보고서를 들어가보면 변형되어 있습니다.
## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
변형되지 않고 저장한 상태 유지
## 스크린샷 ##
![image](https://user-images.githubusercontent.com/50221479/102177657-55a24f00-3ee7-11eb-934a-9377d6ff178d.png)
^보고서 수정화면
![image](https://user-images.githubusercontent.com/50221479/102177641-4de2aa80-3ee7-11eb-9aaa-18661632105c.png)
^저장 후 보기화면

## 로그 ##
http://b-iris.mobigen.com:80/studio/exported/37e9e4b3a95140cca964acc336f16e7bdc489bfa88bc43dd939fa0a2fbfec115
## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 확인 후 조치 바랍니다.
