### ISSUE TITLE
보고서 다중축 그래프 일부 선택 사용성 개선

### ISSUE THREAD

**Issue by sanxoo** [mobigen/IRIS-BigData-Platform#2737]
## 기능 요청 ##
다중축 그래프에서 일부 그래프만 선택해서 보고 싶습니다. 현재는 범례에서 하나씩 선택/선택해제를 해야 합니다.
축이 많은 경우, 하나하나 해제하고 필요한 것만 선택하기가 많이 불편합니다.

## 원하는 솔루션 설명 ##
범례를 사용해야 한다면... 범례에 전체 해제 방법이 있으면 좋겠습니다.

## 고려한 다른 대안 ##
아니면... 콤보박스에 멀티선택 기능이 있으면 활용할 수 있을 것 같습니다.

## 기타 ##
콤보박스 검색 기능과 멀티선택 기능은 이 상황 외에도 유용하게 사용할 수 있는 기능인 것 같습니다.
긍정적인 검토 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 기능 개선시 참고해 주시면 좋을것 같습니다.
