### ISSUE TITLE
보고서 콤보박스 편집(검색) 후 먹통

### ISSUE THREAD

**Issue by sanxoo** [mobigen/IRIS-BigData-Platform#2738]
## 버그 설명 ##
콤보박스에 무언가를 입력하거나 지우고 나면... 항목을 선택하거나 해도 동작을 하지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise 해당 내용에 대한 파악 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
콤보박스 다른 버그와 함께 금주중에 수정하겠습니다.
https://github.com/mobigen/IRIS/issues/221
