### ISSUE TITLE
보고서 그래프 데이터 작업 수행 오류

### ISSUE THREAD

**Issue by sanxoo** [mobigen/IRIS-BigData-Platform#2739]
## 버그 설명 ##
보고서 그래프에서 아래와 이미지와 같은 오류가 발생합니다. 새로고침 하면 오류가 발생하지 않기도 합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/8120623/102319077-b439fc80-3fbd-11eb-926e-592d0d496693.png)

![image](https://user-images.githubusercontent.com/8120623/102319115-bc923780-3fbd-11eb-8487-83d2b99ae5ed.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@veldise @lyj @anhm 해당 사항에 대한 파악 바랍니다.
추가 사항으로는 SaaS의 갤러리에 존재하는 보고서를 보는 경우에도 비슷한(?) 현상이 있습니다.
- 초기 보고서 첫 표기시에는 '모델없음' 오류 발생
- 새로고침 하면 정상 표기

**Comment by veldise** [comment]
@sunghoon
'모델 없음' 오류 발생하는 문제는 현재 확인하여 수정중입니다. 수원시에 패치가 가능한지 확인해보겠습니다.

참고로 아래 에러는 네이버 지도 모듈 인증키를 '솔루션 관리'메뉴에서 입력하지 않은 경우에 발생합니다.
![image](https://user-images.githubusercontent.com/3411842/102421736-8057e900-4048-11eb-807b-11e6c8da1d46.png)

아래 에러는 네이버 지도 플러그인 모듈을 불러오지 못했을 경우 발생합니다. (폐쇄망 환경 등)
![image](https://user-images.githubusercontent.com/3411842/102421747-89e15100-4048-11eb-9fa4-a1e1be18150b.png)

@anhm 
![image](https://user-images.githubusercontent.com/3411842/102421731-76ce8100-4048-11eb-9fed-2360a9873df4.png)

http://58.181.37.140:8092

**Comment by sunghoon** [comment]
@veldise 네. 확인하여 지원 완료 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
'모델 없음' 문제는 b-iris.mobigen.com 기준으로는 1/14 패치로 해결되었습니다.
`naver is not defined` 에러와 네이버 모듈을 불러오지 못하는 문제는 설정이나 환경 문제로 생각됩니다.

작업 수행 오류는 안형민 책임 확인이 필요합니다.
