### ISSUE TITLE
[NMS+]IRIS DSL 사용중 sort 명령어 사용 여부에 따라 결과 다른 현상

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2740]
## 버그 설명 ##

https://github.com/mobigen/NMSplus/issues/145

고객이 확인요청한 사항입니다.
확인부탁드립니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@seungfwani 내용 확인 바랍니다.

**Comment by seungfwani** [comment]
@jjinylee 
https://github.com/mobigen/NMSplus/issues/145 해당 링크에 대한 확인을 다시한번 진행하였지만
데이터나, DSL, 그래프를 그리는 전반적인 프로세스에는 문제는 없는 것으로 판단됩니다.

해당 그래프를 보면 매우 많은 1분 데이터가 조밀하게 붙어있는 것을 알 수 있습니다.
아래 동영상 처럼 `매 분 데이터`는 존재하지만 그래프에 마우스를 오버 하였을 때 모든 `분 데이터` 를 확인하기는 어려웠습니다.

그래프 상에서 마우스를 오버하여 데이터를 확인 하는 부분은 UI 팀에 문의 해보아야 할 것 같습니다. @rhcpn 

https://user-images.githubusercontent.com/46172579/105265840-6a53c000-5bd4-11eb-9e73-6b98003fd512.mov
