### ISSUE TITLE
[NMS+]고객의 개선사항 검토요청입니다.

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2742]
## 기능 요청 ##

https://github.com/mobigen/NMSplus/issues/185

검토부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 이슈와 관련된 기능 개선 요청드립니다.

@jjinylee 다른 중요 개발일정을 완료하고 지원될것 같습니다.
내부에서는 낮은 우선순위로 처리될 예정입니다. 
일정관련 특이사항이 있다면 알려주시기 바랍니다.

**Comment by anhm** [comment]
mobigen/NMSplus#185 이슈가 close 된 상태이기 때문에 닫도록 하겠습니다.
