### ISSUE TITLE
[철도청] chart-시각화옵션-데이터 에서 value 필드 선택을  "모두선택" 외에 개별 컬럼을 (1개 & 여러개)지정하는 기능이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2743]
## 기능 요청 ##
철도청 Studio 보고서 에서

<img width="1208" alt="스크린샷 2020-12-22 오후 2 21 26" src="https://user-images.githubusercontent.com/5126497/102852182-fa310d80-4460-11eb-8475-b4a53fd0fa2f.png">

에서 데이터객체는 1개이며 Y 축 value 에 해당하는 필드가 총 8개를 가져옵니다.
탭을 선택하면 그중 2개만 보이게 하고 싶습니다.

- 다중축을 사용할 수는 없습니다. 이유 : 이번주, 전주 데이터를 보여주는 챠트이므로 동일한  Y 축을 가져야하며, 개별로 간격, 최대,최소를 설정할 수 없습니다.여러 장비와 데이터특성이 있으므로....
- 데이터양이 많고, merge 가 들어가는 데이터객체를 탭의 개수만큼 만드는 것은 성능, 속도 이슈가 있습니다.

따라서 chart-시각화옵션-데이터 에서 value 필드 선택을  "모두선택" 외에 개별 컬럼을 선택할 수 있으면
탭을 클릭할 때마다 그에 맞는 다른 value  필드를 시각화옵션으로 설정하여 보여 줄 수 있으면 좋겠습니다.

<img width="424" alt="스크린샷 2020-12-22 오후 2 12 22" src="https://user-images.githubusercontent.com/5126497/102852404-86433500-4461-11eb-9b87-70f14aa729e5.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 확인 및 지원 바랍니다.
