### ISSUE TITLE
[철도청] Studio 의 outlier 챠트-시각화옵션 에서 툴팁에서 개별항목 선택이 되게 (꺾은선형 처럼) 해주세요.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2744]
## 기능 요청 ##
- outlier 결과
<img width="1397" alt="스크린샷 2020-12-22 오후 4 18 19" src="https://user-images.githubusercontent.com/5126497/102860742-c7434580-4471-11eb-8393-75369fc8a4e0.png">

- outlier 는 시각화옵션에 툴팁 항목이 없습니다. 꺾은선형-시각화옵션의 툴팁항목처럼 추가해주세요
- 꺾은선 챠트의 시각화옵션-툴팁 항목
<img width="276" alt="스크린샷 2020-12-22 오후 4 19 19" src="https://user-images.githubusercontent.com/5126497/102860875-083b5a00-4472-11eb-9c8d-77a064ec7834.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@eumminsun 확인 및 지원바랍니다.
