### ISSUE TITLE
Studio: Label / locale querystring이 적용되지 않는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2747]
## 버그 설명 ##
Studio: Label / 텍스트가 cookie locale 값에 따라서 변경되지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Label 객체를 생성
2. ko, ja 로케일 각각 텍스트를 다르게 입력
3. 보고서 저장
4. **내보내기 URL 생성**
5. 내보내기 URL 복사, 새 창에서 다음과 같이 `?locale=ja` 붙여넣어 접속
    - http://b-iris.mobigen.com/studio/exported/eafc593614f4437a91dfca00cf3ec8b9bee69e1cec424ca28bd177df0e45ab15?locale=ja
6. 텍스트가 일본어로 나오지 않음

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/102755384-a7e4e380-43b1-11eb-95e1-4d8f2d4e5e55.png)

**Comment by veldise** [comment]
다이렉트 클라우드에는 hotfix 패치를 진행하기로 하였습니다.

**Comment by sunghoon** [comment]
@veldise 다이렉트 클라우드 일정이 있으니 일정에 문제가 되지 않게 진행 바랍니다.

**Comment by veldise** [comment]
1/5 다이렉트 클라우드에만 hotfix 패치로 해결하였습니다.
