### ISSUE TITLE
Studio: 보고서 제목 스타일(크기, 색깔, 폰트, 배경, ...)를 설정하는 기능

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2750]
## 기능 요청 ##
보고서 제목 스타일(크기, 색깔, 폰트, 배경, ...)를 설정하는 기능

## 원하는 솔루션 설명 ##
보고서 실행화면에서 좌측 상단에 출력되는 제목(타이틀)의 스타일(크기, 색깔, 폰트, 배경, ...)을 설정하는 기능 추가

![image](https://user-images.githubusercontent.com/3411842/102973250-c4af2180-453f-11eb-89b9-c24b6d9e8632.png)

**Comment by sunghoon** [comment]
@eumminsun 해당 내용에 대한 기획 검토해 주시기 바랍니다.
