### ISSUE TITLE
Studio: Map / 툴팁에서 일부 문자열 데이터가 NaN 으로 나오는 현상

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2752]
## 버그 설명 ##
Studio: Map / 툴팁에서 일부 문자열 데이터가 NaN 으로 나오는 현상

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/103056407-39399d00-45e0-11eb-8907-f45b29f01d3d.png)

**Comment by SONHOJUN** [comment]
LH에서도 해당 현상이있어서 다음과 같이 해결했습니다.
컬럼명이 한글일때 나타나는 현상같아 컬명명에 공백을 하나 추가하니 정상적으로 표시됐습니다.
예) select sigungu as '시군구' -> select sigungu as '시군구 '
