### ISSUE TITLE
[LH-빅데이터] 이미지 툴팁 추가 기능

### ISSUE THREAD

**Issue by qkrwkd124** [mobigen/IRIS-BigData-Platform#2755]
## 기능 요청 ##
느낌표 같은 이미지에 마우스를 올려놓을 때만 간단한 설명이 보일 수 있는 툴팁기능 추가요청

## 원하는 솔루션 설명 ##
이미지에 마우스를 올려 놓을 시 간단한 설명이 보일 수 있는 툴팁기능 추가
이미지 내부에 기능이 있었으면 좋겠습니다.

## 고려한 다른 대안 ##
툴팁 객체를 만들어 이미지를 트리거해 특정 마우스이벤트가 발생하면 보여지도록 하는 형식.

**Comment by sunghoon** [comment]
@eumminsun 신규 컴포넌터 기획 바랍니다.

**Comment by SONHOJUN** [comment]
진행상황이 어떻게 되고 있나요?
LH 프로젝트에서 필요한 기능이고 여러 프로젝트에 적용할 수 있을 것 같습니다.
확인부탁드립니다.

**Comment by sunghoon** [comment]
@SONHOJUN 현재는 우선순위를 높여 작업하지 않고 있는 것으로 알고 있습니다. 

@rhcpn 우선순위 조정이 가능한지 확인해 보는것이 좋을것 같습니다.

**Comment by JeongHeeDong** [comment]
진행일정 공유 요청 드립니다.

**Comment by eumminsun** [comment]
기획 일정은 02/18 ~ 2/19 로 산정되어있습니다. 
기획 완료 후, 개발파트와 기획 협의 기간이 필요 할 수도 있습니다.

**Comment by veldise** [comment]
@SONHOJUN 
사내 시스템(b-iris.mobigen.com)에는 3/11 에 기능이 추가될 예정입니다.
