### ISSUE TITLE
[철도청] DSL 에서 typecast 에서 text 로 저장된 숫자를 real 로 변환해서 forecasts 를 수행하면 에러납니다.(integer 는 됨)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2756]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

- 분석탬플릿  :  forecasts_오류_이상함

- OK   :   typecast COL_VAL001 integer
`* | where EQUIP_SERNO = '12003' 
   | fields COL_DT,EQUIP_SERNO,COL_VAL001
   | typecast COL_VAL001 integer    | typecast COL_DT timestamp "YYYYMMDDHHmmss"  |  fillna COL_VAL001  | sort COL_DT |  forecasts COL_DT  COL_VAL001 `

<img width="1193" alt="스크린샷 2020-12-24 오후 4 03 56" src="https://user-images.githubusercontent.com/5126497/103068946-9eea5100-4601-11eb-8579-9c1676fa67b4.png">

- ERR :  typecast COL_VAL001 real
`* | where EQUIP_SERNO = '12003' 
   | fields COL_DT,EQUIP_SERNO,COL_VAL001
   | typecast COL_VAL001 real    | typecast COL_DT timestamp "YYYYMMDDHHmmss"  |  fillna COL_VAL001  | sort COL_DT |  forecasts COL_DT  COL_VAL001 `

 angora 오류 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
2. Click on '...

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @seungfwani 확인바랍니다.

**Comment by seungfwani** [comment]
내용 파악 및 처리 완료 되었으며, 다음 배포시 포함 될 예정입니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani 배포 및 적용을 위한 일정을 확인하여 진행해 주시기 바랍니다.

**Comment by seungfwani** [comment]
철도청에 1/21(목) 배포에는 해당내용을 포함하지 않기로 하여, 다음 배포에 포함될 예정입니다.
