### ISSUE TITLE
[국토부]보고서 명과 URL 을 다운로드할수 있는방법

### ISSUE THREAD

**Issue by jjinylee** [mobigen/IRIS-BigData-Platform#2757]
## 기능 요청 ##
국토교통부 포털에서 보고서로 만든 분석케이스를 보고서 URL을 링크걸어서  보여주고 있습니다.

상용 오픈으로 국토부 인턴이 만든 50여개 보고서를 상용환경에 마이그레이션하고 있는데

상용환경에서는 보고서의 URL 이 변경되어 URL 정보를 전부 수정해야하는데
보고서명 / 보고서 URL을 다운로드 받을수있는 기능이 없으므로

보고서명/ 보고서 URL을 덤프뜰수 있는 방법 확인부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
개별 메일로 @rhcpn 팀장님이 처리하였습니다.
