### ISSUE TITLE
[LH빅데이터] Studio:데이터 객체 - REST-API 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2758]
## 버그 설명 ##
보고서에서 데이터 객체 유형을 'REST-API' 로 처리하려고 하는데 정상적으로 표시가 되어야 할 것 같은데 'Unknown Error(-1)'가 발생합니다.
URI는 http://101.101.212.224:30380/LH_WSEARCH/dashBoard/dashBoard01.do 입니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
응답내용
{
	"success":{
		"code":0,
		"messages":""
	},
	"hide_messages":false,
	"data":{
		"fields":[
			{"name":"name1","type":"TEXT"},
			{"name":"count1","type":"INTEGER"},
			{"name":"count2","type":"INTEGER"}
		],
		"results":[
			["전체",4070445,0],
			["뉴스",221663,0],
			["뉴스댓글",2776835,0],
			["카페게시글",112584,0],
			["카페댓글",345303,0],
			["블로그",614060,0]
		]
	}
}

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
해당 이슈는 REST API 사용 가이드 전달 시 사용법을 잘못 전달한 부분이 있었습니다.
아래의 두가지 Case 에 따라 결과값 구성을 달리 해야 한다고 안내 했습니다.
1. 데이터 조회 시
- 성공 시 "data" 필드만 반환

2. 기타 서버에 요청 후 성공 여부만 받아야 할때
- success 필드만 사용

위의 내용에 대해 확인 후 피드백 주기로 되어 있습니다.

**Comment by SONHOJUN** [comment]
안내에 따라 수정 후 정상동작 여부 확인.
해당 이슈 Close.
