### ISSUE TITLE
[교통빅데이터플랫폼] IRIS Analyzer 보고서 변수 값 전달 기능 버그

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2760]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

아래 그래프에서 차트를 선택하여 값 전달을 하려합니다.
![image](https://user-images.githubusercontent.com/16331916/103504177-fad29680-4e99-11eb-8290-1339253492c4.png)

아래 이미지는 위 그래프의 시각화 이벤트 값 전달 설정 입니다.
![image](https://user-images.githubusercontent.com/16331916/103504170-f4441f00-4e99-11eb-9fa4-ac9a5adf0a41.png)

아래 이미지는 그래프에서 트리거를 발생시켰지만 전체 변수명 보기를 통해서 area_5 변수명에 변수 값이 비어져 있는 것을
보여줍니다.
![image](https://user-images.githubusercontent.com/16331916/103504248-366d6080-4e9a-11eb-8502-4a08d06e2752.png)

교통빅데이터플랫폼 서버 기준의 버그입니다.
차트의 세로막대그래프에서 변수값 전달 기능이 정상 동작하지 않습니다.

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@kim3163 
교통빅데이터 플랫폼은 현재 마이그레이션 문제로 구버전이 설치되어 있습니다. (정확한 버전 정보는 운용기술팀에 문의하시면 됩니다.)

b-iris.mobigen.com 에서 유사하게 작업을 해보시고 같은 문제가 발생한다면 회신해주시기 바랍니다.

제가 b-iris.mobigen.com에서 테스트해보기로는 정상 동작하였습니다.

**Comment by veldise** [comment]
세로막대가 아니고 다중축 유형에서 발생하는 문제로 확인되었습니다. (구버전)

**Comment by veldise** [comment]
1/5 해당 버그만 hotfix 패치하여 해결되었습니다.
