### ISSUE TITLE
[교통빅데이터플랫폼] IRIS 보고서 차트 그리기 버그

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2761]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

![image](https://user-images.githubusercontent.com/16331916/103608521-e0162580-4f5e-11eb-83e8-1d00d00bf16d.png)

위와 같은 결과가 나오는 차트가 있을때, 막대그래프에 
X축은 YMD_DATE
Y축은 모두 선택을 선택할 경우 X 축은 YMD_DATE, 막대그래프는 X 축 마다 2개가 그려져야 되는데 결과가 나오지 않습니다.

![image](https://user-images.githubusercontent.com/16331916/103608744-60d52180-4f5f-11eb-804f-4f18e8b1187c.png)

Y축을 1개만 선택했을땐 그래프가 그려짐

![image](https://user-images.githubusercontent.com/16331916/103608766-74808800-4f5f-11eb-8a70-96a00ec83fe4.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@kim3163 
차트는 기본적으로 수치데이터를 시각화 하는 것이므로 데이터 컬럼 유형에 따라 동작이 다를 수 있습니다.

현재 시각화 옵션 > 데이터 탭에서 y축 등을 '모두 선택'으로 설정한 경우,
숫자 유형(INTEGER, BIGINT, REAL)인 경우에만 그리도록 처리가 되어 있습니다.

현재 버전에서는 SQL 혹은 DSL 쿼리를 조정하여 결과 데이터의 컬럼 유형을 숫자로 조정하시면 정상 동작할 것으로 생각됩니다.
만약 숫자 유형으로 조정하였는데도 같은 문제가 발생하면 답글을 달아주시기 바랍니다.

**Comment by veldise** [comment]
IRIS-DB가 모든 유형을 TEXT로 반환해서 발생하는 문제로, DSL로 변경하여 해결하신 걸로 추측됩니다.
