### ISSUE TITLE
Studio: 값필드가 설정된 차트(테이블)에 데이터가 다시 로드 되었을때, 이전 값이 남아있음.

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2762]
## 버그 설명 ##
AI바우처(STI) 프로젝트 관련된 문의사항입니다.
값 필드를 설정한 차트(테이블)에서 차트 데이터를 다시 로드 했을때 이전 값이 남아있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 차트(테이블)에 A컬럼을 값필드로 설정
2. 아무행 클릭
3. 차트 데이터 다시 로드
4. 이전에 클릭했던 A컬럼값이 계속 남아있음.

## 예상한 행동 ##
차트 데이터를 다시 로드 하면 이전에 클릭했던 값이 삭제된다.

## 스크린샷 ##
- '조직도시도명'을 값필드로 설정, '서울특별시'행 클릭 > 트리거 설정된 우측 라벨에 '서울특별시' 표시됨
![image](https://user-images.githubusercontent.com/3972489/103610228-f1f9c780-4f62-11eb-90a3-c9828f95b894.png)

- 테이블 데이터 다시 로드 > 로드 전 클릭했던 '서울특별시' 값이 남아있음
![image](https://user-images.githubusercontent.com/3972489/103610377-63397a80-4f63-11eb-95c7-798d55a2565d.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
위 상황에서 Label 객체는 트리거 설정이 테이블 행 클릭에만 되어 있으므로 데이터 객체의 동작과는 연관이 없습니다.
따라서 데이터 객체에서 데이터를 다시 불러와서 테이블이 다시 그려지더라도 Label 은 변화가 없는 것입니다. 위 동작은 정상입니다.

데이터를 다시 불러왔을 때 테이블 뿐만 아니라 Label 객체의 값도 초기화하고 싶다면
Label 객체의 값을 초기화하는 트리거를 데이터 객체에 설정할 수 있어야 하는데 아직은 기능이 없습니다.

**Comment by soraJang** [comment]
@veldise 
제가 예를 라벨로 들어서 전달이 잘못된것 같습니다.
아래의 이슈가 제가 말하려고 한 기능입니다.
https://github.com/mobigen/IRIS-BigData-Platform/issues/2166

**Comment by sunghoon** [comment]
@veldise 변수값 초기화 관련 이슈로 진행 해 주시면 될 것 같습니다.
