### ISSUE TITLE
[Studio]라벨 글씨가 쓰여지지 않아요

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2763]
## 버그 설명 ##
글씨를 적으면 사라져요 덮어씌여지고 줄바꿈을 하기도 하고 글씨가 적히지 않아요
## 재현하는 방법 ##
동작을 재현하는 방법 :
들어가셔서 원형그래프 라벨에 글씨를 써보시면 됩니다
## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##

![image](https://user-images.githubusercontent.com/50221479/103611188-1bb3ee00-4f65-11eb-9c10-93bae1aef1e8.png)

## 로그 ##
http://b-iris.mobigen.com:80/studio/exported/d7e8836a04104b9f908f3d1d6acf17513c30a28dc69c40ed813734b61bed74be
이슈라벨_한다연
## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@handayeon 
MacOS / Chrome 환경에서 재현되지 않습니다. 보다 자세한 재현 방법을 알려주시면 다시 확인해보겠습니다.

**Comment by sunghoon** [comment]
@handayeon 오래된? 이슈라 닫습니다. 본 문제가 해결되지 않았다면 Reopen 해 주세요.
