### ISSUE TITLE
[철도공사] Angora에 결과를 Transpose 할수 있는 명령어 추가 요청

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2766]
## 기능 요청 ##
DSL 결과로 출력된 테이블을 Transpose 할수 있는 명령어가 필요합니다.

## 원하는 솔루션 설명 ##
![image](https://user-images.githubusercontent.com/11566844/103854827-b42ca880-50f4-11eb-8f1b-6636a02366e9.png)
위의 데이터를
![image](https://user-images.githubusercontent.com/11566844/103854863-c575b500-50f4-11eb-8e69-0addfb08a6d9.png)
와 같은 형태로 변환 하고자 합니다.

현재 위와 유사하게 동작 하도록 Spark SQL stack func 을 사용해도 되긴 하는데요,
기능으로 추가 가능한지 검토 요청 합니다.

**Comment by rhcpn** [comment]
위의 결과는 아래의 명령어를 이용하면 되긴 합니다. 기능 검토 시 참고 요청 합니다.
```
.. | sql "SELECT stack(n, 'A', A, 'col_1', col_1, 'col_2',  col_2 ...) from angora"
```

**Comment by veldise** [comment]
@rhcpn 
A 컬럼은 고정되어 있어야 하는건가요?

**Comment by sunghoon** [comment]
@anhm @seungfwani 확인 후 빠른 지원 바랍니다.
