### ISSUE TITLE
[ Analyzer ] 검색 기능 사용 후, 시각화로의 페이지 이동시의 이슈

### ISSUE THREAD

**Issue by ollehQ** [mobigen/IRIS-BigData-Platform#2767]
## 버그 설명 ##
검색 기능을 이용 한 후, 시각화 페이지로 이동하게 되지 않는 버그 발견.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Analyzer의 검색 페이지 접속
2. 데이터모델 'SEOUL_FIRE_CAUSE' 선택
3. " * | adv LINE avg(TOTAL) SPLITROW NATURAL SORTROW desc " Query 입력
4. Play버튼 실행
5. 데이터가 뜬 후, 시각화로 이동 버튼 클릭
6. 버그 발생

## 예상한 행동 ##
시각화로의 이동

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@seungfwani 

request:
```
POST
http://192.168.100.180:6036/angora/v2/query-analysis/v2/adv?type=tree
{"q": "* | adv LINE avg(TOTAL) SPLITROW NATURAL SORTROW desc"}
```

response:
```
{"message": "'NoneType' object is not iterable", "type": "TypeError"}
```

**Comment by jheok318** [comment]
adv 쿼리의 query-analysis api 실행 중  'LINE' 의 대문자로 인해 발생한 오류 입니다.

추후 대소문자 구분없이 실행될 수 있도록 수정하겠습니다.

**Comment by seungfwani** [comment]
처리완료되었습니다.
