### ISSUE TITLE
Studio: 지도 마커(경로) focus 되는 기능

### ISSUE THREAD

**Issue by soraJang** [mobigen/IRIS-BigData-Platform#2768]
## 기능 요청 ##
AI바우처(STI) 프로젝트 관련된 문의사항입니다.
테이블 클릭 > 맵에 마커(경로) 로 표시 하는 기능을 구현중입니다.
마커(경로)로 focus 되는 기능이 필요합니다.
설명은 아래의 스크린샷으로 확인부탁드립니다. 

## 원하는 솔루션 설명 ##
1. 테이블 클릭 > 맵에 마커(경로) 표시 > 지도 확대
![image](https://user-images.githubusercontent.com/3972489/103986284-cfb7b200-51cd-11eb-8404-08181e3f5376.png)

2. 테이블 다른 행 클릭 > 확인하기 어려움 (지도에 표시된것처럼 보이지 않음)
![image](https://user-images.githubusercontent.com/3972489/103986353-ed851700-51cd-11eb-9abf-d293eaf99976.png)

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
Map 객체 우측 사이드 패널에서 레이어를 'Base Map'으로 선택하시면
아래와 같이 트리거 설정과 함께 변수값으로 위도/경도/줌레벨을 설정하실 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/103988076-d3006d00-51d0-11eb-924b-da02057027dc.png)

테이블 행을 클릭하였을 때, 원하시는 위도/경도/줌레벨 로 이동하도록 적절하게 입력하시면 됩니다.

**Comment by sunghoon** [comment]
설명이 된것으로 보고 이슈를 닫습니다. 
해결되지 않았다면 Reopen 해 주시기 바랍니다.
