### ISSUE TITLE
모델 뷰 수정 시, 컬럼 정보 변경을 할수 없는 부분 개선 요청

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2769]
## 기능 요청 ##
이미 생성된 모델 뷰의 컬럼 정보 수정이 불가능 합니다. 모델 뷰 수정 시 컬럼도 재지정 되었으면 합니다.

## 원하는 솔루션 설명 ##
1. 모델 뷰 생성 후 해당 모델 뷰를 수정하기로 들어감
2. 모델 뷰의 DSL 수정.
3. 결과 컬럼이 이전에 지정한 컬럼과 달라짐.
4. 하지만 변경된 컬럼 정보로 컬럼 선택 부분이 갱신되지 않아서 저장 불가

DSL 수정 후 "적용" 버튼을 누르면 아래 컬럼 지정 부분이 초기화 되어 지정 가능 하게 수정 되면 좋을것 같습니다.

![image](https://user-images.githubusercontent.com/11566844/103993971-b452a400-51d9-11eb-95f8-58a5731b1f2c.png)

![image](https://user-images.githubusercontent.com/11566844/103994087-dc420780-51d9-11eb-872a-df1b53f5345e.png)

**Comment by rhcpn** [comment]
마이너 하게 하나 더 있는데
모델 뷰 생성 시 "전체 시간" 으로 지정 하고 저장 했지만, 수정 시 최근 1분으로 초기화 되어 있어서 이 부분도 문제 입니다.

**Comment by veldise** [comment]
@rhcpn 
저장되어있는 컬럼 정보가 사라졌을 시에는 사라진 컬럼을 체크 해제해줘야 저장이 가능합니다.

![image](https://user-images.githubusercontent.com/3411842/104138663-e71eb700-53e8-11eb-910f-4baea5c3cd04.png)

**Comment by veldise** [comment]
@rhcpn 
모델 뷰 생성시 시간 설정을 '전체 시간'으로 하였을 경우, 시간 설정 정보가 저장되지 않는 버그를 확인하였습니다.

**Comment by rhcpn** [comment]
수정 부분은 설명대로 하니까 동작 하는것을 확인했습니다 ~
