### ISSUE TITLE
모델 뷰 생성 시 컬럼 지정을 할 수 없는 오류 수정 요청

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2770]
## 버그 설명 ##
모델 뷰 생성 시 컬럼 지정을 할 수 없는 상황이 생겨서 저장을 하지 못함

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 모델 뷰 생성
2. 필요한 정보 설정 후 "적용" 버튼 클릭
3. 컬럼에 필요한 리스트가 나오는 것을 확인
4. DSL 입력란에 아무렇게나 동작 되지 않는 문구 입력 후 "적용" 을 눌러서 오류 발생 시킴
5. 컬럼 선택 부분이 초기화 되며 되돌릴수 없음

## 예상한 행동 ##
오류 발생 후, 오류 수정 하고 난뒤 재실행 해서 성공한 경우 컬럼 리스트가 출력 되어야 함.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/11566844/103995098-4f984900-51db-11eb-98a3-fa1c2f588be1.png)

**Comment by veldise** [comment]
@rhcpn 
재현이 되지 않습니다. 조금 더 자세한 상황이 필요합니다.

1. 새 모델 뷰
2. 정상 쿼리 실행하여 샘플 데이터, 컬럼 설정 출력 확인
3. `asdf`와 같이 에러 발생하는 컬럼 입력하고 '적용'
4. 샘플 데이터, 컬럼 설정이 사라지고 '작업 수행에 오류가 발생했습니다.' Alert 및 에러 출력 확인
5. ![image](https://user-images.githubusercontent.com/3411842/104138422-55627a00-53e7-11eb-9b3a-2be532faab88.png)

**Comment by rhcpn** [comment]
해당 이슈 내용은 테스트가 잘못된것으로 파악 되었습니다. 잘 동작 하는것을 확인 하였습니다.
