### ISSUE TITLE
꺾은선형 차트 드래그 시 동작 이상

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#2771]
## 버그 설명 ##
보고서 내의 꺾은선형 차트에서는 영역 드래그 시에 차트가 확대되는데 결과가 이상하게 표출됩니다.

더불어 꺾은선 차트 객체가 클릭 시 발생하는 객체에 대해서만 참조가 가능한데 이것을 영역 드래그 시에 시작점과 끝점의 데이터를 변수로 받을 수 있으면 좋겠습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
- EDU_Studio line chart_데이터객체버전에서 차트 영역 드래그
<img width="1161" alt="스크린샷 2021-01-11 오전 10 34 10" src="https://user-images.githubusercontent.com/32768535/104141143-957e2880-53f8-11eb-82f1-d8bef026a829.png">

드래그 결과 (47~60까지 드래그 )
<img width="1174" alt="스크린샷 2021-01-11 오전 10 34 51" src="https://user-images.githubusercontent.com/32768535/104141152-a5960800-53f8-11eb-9aeb-6724c177c268.png">

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@GyuminJack 확대/축소는 자체는 기본 동작입니다. 

@veldise 해당 이슈에 대한 검토 바랍니다.

**Comment by GyuminJack** [comment]
그래프 확대가 될 경우 확대된 데이터를 대상으로 그래프를 다시 보여줘야 하지 않나 싶습니다.
지금은 단순히 확대만 되어서 위 그림 처럼 47~60까지 드래그 시에 47의 데이터만 보이고 나머지의 데이터는 있음에도 불구하고 보이지 않는 상황입니다.

**Comment by sunghoon** [comment]
@GyuminJack 혹시 실명이 어떻게 되시는지요? 구두로 직접 들어봐야 이해가 될 것 같습니다.

**Comment by veldise** [comment]
@GyuminJack 
다소 오해가 있는 것 같습니다. 차트의 확대/축소(zoom-in/out)는 x축 뿐만 아니라 y축에 대해서도 동작합니다.
지금 본문 스크린샷은 x축: 47~60, y축: 140~155 부분을 확대했다고 보시면 됩니다. 따라서 정상입니다.

**Comment by sunghoon** [comment]
@veldise @GyuminJack 직접 이야기 하면서 설명 완료하였습니다.
