### ISSUE TITLE
Studio: Chart / 신규 시각화 유형으로 Area 추가

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2775]
## 기능 요청 ##
Studio: Chart / 신규 시각화 유형으로 Area 추가

## 원하는 솔루션 설명 ##
![image](https://user-images.githubusercontent.com/3411842/104254145-86ab7a80-54b9-11eb-80c0-d76a194283d9.png)

**Comment by sunghoon** [comment]
위와는 조금 다른 아래 형태가 아닐지,
최종적으로는 둘 다 필요해 보입니다.

![81KbD](https://user-images.githubusercontent.com/512653/104255021-74cad700-54bb-11eb-9def-76d2a0fef2b1.png)

**Comment by veldise** [comment]
영역형 차트에는 막대형 차트와 동일한 스택 옵션이 추가될 예정입니다.
![image](https://user-images.githubusercontent.com/3411842/106556659-58bed080-6563-11eb-996d-0af458ac8247.png)

**Comment by veldise** [comment]
4/1 패치로 추가될 예정입니다.
