### ISSUE TITLE
보고서 작성시 이상탐지 그래프 값전달 불가능.

### ISSUE THREAD

**Issue by GyuminJack** [mobigen/IRIS-BigData-Platform#2776]
## 버그 설명 ##
이상탐지 그래프에서 클릭되는 값들이 다른 객체로 넘어가지 않습니다.

<img width="268" alt="스크린샷 2021-01-12 오후 12 27 03" src="https://user-images.githubusercontent.com/32768535/104265856-dc8c1c80-54d1-11eb-8004-c5d8775a622f.png">
<img width="282" alt="스크린샷 2021-01-12 오후 12 26 55" src="https://user-images.githubusercontent.com/32768535/104265858-ddbd4980-54d1-11eb-80f3-1d28f915474f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :
KOTRA_ANOMALY 라는 보고서를 참고하시면 됩니다.

상단의 꺾은선 그래프는 이상탐지 그래프인데 여기서 이벤트 값 설정을 하더라도 값이 다른 객체에서 불리지 않습니다.
하단의 꺾은선 그래프는 잘 동작합니다.
## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
Anomaly 유형에서 클릭 동작과 관련된 기능이 누락된 것을 확인했습니다. 조치하겠습니다.

**Comment by veldise** [comment]
차주 (1/21) 패치 예정입니다
