### ISSUE TITLE
메뉴 경로 표시 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2777]
## 기능 요청 ##
IWP 메뉴 항목을 선택 시 선택한 대상이 화면에 출력 되고 있는데, 이때 선택한 메뉴 경로를 화면에 표시해 주는 기능이 필요함.
현재 기능 상으로는 1Depth 만 표시 되고 있어, 2 ~ N Depth 메뉴를 선택 시에는 알길이 없음.

1Depth 선택 시
![image](https://user-images.githubusercontent.com/11566844/104410222-37457700-55ab-11eb-9a48-d8fe8532e929.png)

3Depth 선택 시 (메뉴를 펼쳐 봐야지만 알 수 있음)
![image](https://user-images.githubusercontent.com/11566844/104410264-4f1cfb00-55ab-11eb-8512-ed640bd00857.png)

**Comment by sunghoon** [comment]
@rhcpn 임시로 보고서에 라벨 컴포넌트를 이용하여 직적 표기해 놓아도 되지 않나요?

**Comment by rhcpn** [comment]
@sunghoon 그렇게 하고 있는데 메뉴 항목이 Studio가 아닐 경우도 있을수 있어서 추후 기획을 통해서 추가 되었으면 합니다 ^^;;

**Comment by rhcpn** [comment]
@sunghoon 해당 기능이 감리지적 사항으로도 나왔습니다. 하지만 일단은 말로 때우려고 하는데요 추후 기능 보강이 필요해 보입니다.
