### ISSUE TITLE
[국방부] 데이터 모델 / 엑셀 파일을 대상 데이터로 선택하면 오류 발생

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2781]
## 버그 설명 ##
[국방부] 데이터 모델 / 엑셀 파일을 대상 데이터로 선택하면 오류 발생

제보자: 남한별 책임

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/104537425-4d137480-565d-11eb-866b-9fcf36298ffe.png)

## 로그 ##
```json
{"message":"angora error: Py4JJavaError\n[SPARK] java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream"}
```

## 비고
가능한 빠른 처리를 요청했습니다.

**Comment by sunghoon** [comment]
@anhm @seungfwani @onursoyer 빠른 확인 및 조치 바랍니다.

**Comment by seungfwani** [comment]
해당 엑셀 파일의 포멧이 지원하지 않는 파일입니다.

최신 ms excel 프로그램으로 다시 저장을 한 뒤 테스트를 해보니 정상적으로 데이터를 읽을 수 있었습니다.

**Comment by sunghoon** [comment]
@seungfwani @anhm @onursoyer 가능 범위 안에서 old format도 지원 할 수 있도록 다음의 내용을 확인해 보고

https://openwritings.net/pg/python/python-read-and-write-old-ms-excel-filexls

지원 가능 여부 최소 버전 정보를 명시해 주는 것이 좋을 것 같습니다.

**Comment by seungfwani** [comment]
종료되어 닫습니다.
