### ISSUE TITLE
보고서 편집 시 연결정보 선택 오류

### ISSUE THREAD

**Issue by EricLeeMbg** [mobigen/IRIS-BigData-Platform#2784]
## 버그 설명 ##
보고서 연결정보가 보이지 않습니다. 

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Go to 'CI/CD-dashboard - 0118'
2. Click on '수정'

## 스크린샷 ##
- 우측 연결 정보 선택에 연결정보 없음
- '실행' 버튼을 누르면 데이터는 정상적으로 출력됨
- 보고서의 수행은 정상적임
![image](https://user-images.githubusercontent.com/44352311/104862064-8ad20f00-5975-11eb-87b0-f2bee336834b.png)

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
데이터 확인 결과 연결정보 존재 유무를 체크하는 로직에서 연결정보가 숫자로 처리되고 있었습니다. 곧 수정하겠습니다.

**Comment by EricLeeMbg** [comment]
이슈 이동하고 닫습니다.
