### ISSUE TITLE
IRIS SSO 후 로그아웃이 되지 않음

### ISSUE THREAD

**Issue by jjpark0620** [mobigen/IRIS-BigData-Platform#2785]
## 버그 설명 ##
IRIS SSO 후 로그아웃이 되지 않음

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. IRIS SSO 로그인
2. IRIS 사이트에서 로그아웃 버튼 클릭
   -> iris-session-id 쿠키 삭제 (스크린샷 2)  
   -> x-access-token 이 삭제되지 않아 iris-session-id 다시 생성 (스크린샷 3)  

## 예상한 행동 ##
IRIS 로그아웃 후 IRIS 로그인 페이지 출력

## 스크린샷 ##
1. IRIS SSO 로그인 (x-access-token 으로 iris-session-id 쿠키 생성)  
![그림1](https://user-images.githubusercontent.com/20884554/104900337-4ec39c00-59bf-11eb-9a14-bd11eaf94e3d.png)
2. IRIS 로그아웃 (iris-session-id 쿠키 삭제, x-access-token 쿠키는 남아있음)  
![그림2](https://user-images.githubusercontent.com/20884554/104900354-53885000-59bf-11eb-8996-08ef6d14d413.png)
3. IRIS 재 로그인 (x-access-token 쿠키로 재 로그인 하는듯 보임)  
![그림3](https://user-images.githubusercontent.com/20884554/104900363-55521380-59bf-11eb-88d2-6bd1677fb203.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @lyj @veldise 해당 이슈를 확인하여 확인된 정보를 공유 바랍니다.

**Comment by lyj** [comment]
초기 SSO 인증에 로그아웃 기능이 지원되지 않았을때의 버전인것 같습니다.
현재 버전에서는 로그아웃 기능이 제공되고 있습니다.
버전 패치가되면 해당 문제가 해결될것으로 예상됩니다.

**Comment by sunghoon** [comment]
@jjpark0620 이슈를 제기 한곳의 사이트 정보를 주시면 @lyj 책임이 이야기 한 부분이 맞는지 확인을 해 볼 수 있을 것 같습니다.

**Comment by rhcpn** [comment]
해당 이슈는 IWP에 SSO 기능 추가 초기에 SSO 인증/로그아웃 시에도 Cookie에서 x-access-token을 지우지 않던 문제가 있었습니다.
현재는 SSO 인증 성공 직후 해당 cookie를 명시적으로 지우도록 처리 완료되었으니 참고 하시기 바랍니다.

**Comment by JeongHeeDong** [comment]
@big-mobigen  @오장석 팀장님,

**Comment by big-mobigen** [comment]
LH공사 IWP 버전입니다. 

iris-web-platform:v2.20201215.0-9cb500e

**Comment by rhcpn** [comment]
해당 버전은 SSO 초기 버전이라 최신 버전으로 패치가 필요합니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 본 이슈에 대한 최종 상태 정보를 공유해 주시거나 해결된 이슈면 Close 해 주세요.

**Comment by lyj** [comment]
오늘(2월1일) LH공사 패치 완료되었습니다.

**Comment by JeongHeeDong** [comment]
어제 김무성 책임께 보여드린바와 같이, 여전히 로그아웃이 안되고 있습니다.
다시 한번 확인 부탁 드립니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 조치가 완료 되었는지요?

**Comment by rhcpn** [comment]
패치 이후에도 해당 오류가 계속 재현 되어 자세히 살펴보니 현재 iris 가 동작하는 도메인 보다 설정된 cookie 의 도메인이 상위이기 때문에 cookie 삭제가 되질 않는 문제가 원인 이였습니다.

위와 같은 상황에서는 유선상으로 공유드린대로 IRIS 페이지를 띄울때 http header에 x-access-token을 입력하여 접근해주셔야 합니다.

자세한 내용은 아래 링크를 참조 부탁드립니다.

https://github.com/mobigen/IRIS-BigData-Platform/wiki/IRIS-Web-SSO-%EC%9D%B8%EC%A6%9D-%EA%B0%80%EC%9D%B4%EB%93%9C

**Comment by jjpark0620** [comment]
x-access-token max-age 값을 짧게 설정하고(10 Sec) 로그인 이후 만료 되도록 설정하여 로그아웃이 정상적으로 처리 되도록 하였습니다.

**Comment by sunghoon** [comment]
이슈가 처리되어 Close 합니다.
