### ISSUE TITLE
특정 그룹으로 접근 시 메뉴 선택 부분이 이중으로 표시 되는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2788]
## 버그 설명 ##
특정 그룹을 선택 후 다른 메뉴 선택 하고 다시 그룹을 눌렀을 때 메뉴가 이중 선택 되어 있습니다.

## 재현하는 방법 ##
1. 특정 그룹 선택
2. 메뉴에서 하위의 다른 항목 선택
3. 다시 그룹 선택 화면에서 같은 그룹 선택
4. 기본 메뉴 항목이 화면에 나타나고 메뉴를 활성화 해보면 이전에 선택한 항목도 같이 포커스 되어 있음

## 예상한 행동 ##
마지막에 선택한 항목만 활성화 되어야 함

## 스크린샷 ##
1. 그룹으로 처음 접근 하면 기본 메뉴 항목 선택 되어 있음
![image](https://user-images.githubusercontent.com/11566844/105116128-7c1e6000-5b0d-11eb-99fe-6eb37fe13fdf.png)

2. 다른 항목 선택 후 다시 그룹을 선택 시 아래와 같이 보임
![image](https://user-images.githubusercontent.com/11566844/105116323-d9b2ac80-5b0d-11eb-9478-b33fd192a558.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
@sunghoon 감리지적사항으로 긴급 처리를 요청해둔 상태 입니다.

**Comment by rhcpn** [comment]
해당 사항은 이제 급하지 않아졌으므로 기입된 중요도 순으로 추후 처리 하도록 하겠습니다.

**Comment by lyj** [comment]
처리 완료되어 21/02/18 패치 예정입니다.
