### ISSUE TITLE
Studio 컴포넌트를 여러개 선택 후 스타일 일괄 지정 시 설정이 반영되지 않음

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2790]
## 버그 설명 ##
Studio 에서 여러개의 컴포넌트를 선택 하여 공통 스타일을 변경하면 에디터 상에서는 적용되어 보이나 미리보기 등에서는 적용 되지 않음.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. Studio 에서 Label 컴포넌트를 여러개 생성
2. 생성한 모든 컴포넌트를 선택
3. 글자를 가운데 정렬
4. 미리 보기로 확인

## 예상한 행동 ##
반영된 스타일이나와야 하지만 반영 되지 않음.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/11566844/105268464-a4719180-5bd5-11eb-98bd-f7a1269dfbcb.png)
![image](https://user-images.githubusercontent.com/11566844/105268469-aa677280-5bd5-11eb-93c6-ecf42d004ced.png)

**Comment by sunghoon** [comment]
@rhcpn 일정 계획을 세워서 진행 해 주세요.

**Comment by veldise** [comment]
Label 객체에서만 위 버그가 발생하는 것을 확인하였습니다. 2/4 패치에서 해결하겠습니다.
