### ISSUE TITLE
그룹별로 도움말을 다운로드 할수 있는 기능 필요

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2791]
## 기능 요청 ##
그룹별로 필요한 도움말로 이동 혹은 다운로드 받을 수 있는 기능이 필요 합니다.

## 원하는 솔루션 설명 ##
현재는 공통 도움말 메뉴에서 전체 도움말 링크로 이동하거나 다운로드 받을 수 있는 방식입니다.
그룹 지정 시 각 그룹에 해당하는 도움말 링크나 파일을 지정할수 있게 하여 그룹에 따라 도움말이 선택 적으로 동작 되는 기능이 필요 합니다.

**Comment by lyj** [comment]
도움말 항목 그룹별로 분류하여 link 혹은 download 받을 수 있도록 수정되었습니다.

**Comment by sunghoon** [comment]
@lyj 왼료된건가요? 배포 예정일은 어떻게 되는지요?

**Comment by rhcpn** [comment]
@sunghoon 위의 처리 방법은 일단 철도공사건이 급해서 임시로 처리된 사항이고 추후 기획을 통해 정식으로 추가하자는 의미로 등록한 이슈 입니다. 

@lyj 해당 이슈는 위 코멘트와 같은 사항이니 IRIS#340 항목은 별도로 처리 해주세요

**Comment by lyj** [comment]
@rhcpn 철도공사건 도움말 추가는 별도 이슈로 추가하고, 이 이슈의 처리 라벨 및 코멘트는 삭제합니다.
