### ISSUE TITLE
라벨 컴포넌트 크기를 임의로 지정 후 특정 사이즈로 변경 되는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2792]
## 버그 설명 ##
라벨 컴포넌트 크기를 임의로 지정 한 뒤에 해당 컴포넌트를 다시 선택하면 일정한 단위로 크기가 변경 됩니다.

## 재현하는 방법 ##
1. 라벨 추가
2. 속성 창에서 임의의 크기로 높이 지정 ex. 127
3. 해당 라벨을 다시 클릭
4. 라벨 높이 확인

## 예상한 행동 ##
지정한 대로 변경 되지 않아야 합니다.

## 스크린샷 ##
1. 최초 생성
![image](https://user-images.githubusercontent.com/11566844/105280403-0689c100-5bed-11eb-9a6e-887dd946295a.png)

2. 크기 변경
![image](https://user-images.githubusercontent.com/11566844/105280415-0e496580-5bed-11eb-8cdd-87668bcd7b37.png)

3. 클릭!
![image](https://user-images.githubusercontent.com/11566844/105280429-16a1a080-5bed-11eb-9c03-b01c87a98e14.png)

**Comment by sunghoon** [comment]
@rhcpn @veldise 확인 후 빠른 조치 및 진행 일정 정보를 공유 해 주세요.

**Comment by veldise** [comment]
Label 객체만 클릭시 크기를 round 처리하는 문제를 확인하였습니다. 2/4 패치에 포함시키겠습니다.
