### ISSUE TITLE
[국토부] Studio: Map / Basemap OSM 을 국토지리정보원 으로 교체

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2793]
## 기능 요청 ##
- 요청자: 김대용 팀장님

[국토부] Studio: Map / Basemap OSM 을 국토지리정보원 으로 교체

## 원하는 솔루션 설명 ##
Studio 의 지도(Map) 객체의 Basemap 중에 OSM(open street map)을 국토지리정보원에서 제공하는 지도로 교체

**Comment by sunghoon** [comment]
@rhcpn 진행 일정 계획을 잡아 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
현재 금요일까지 임시조치해서 차주 화요일에 국토부에 배포하는 것으로 협의중입니다.

**Comment by veldise** [comment]
지리원 2D 지도서비스가 약 1주간 서비스 중지라고 하여, 금일(화요일)에 배포는 취소되었습니다.
대신 OSM 을 교체하는 것이 아니라 신규 basemap 유형으로 국토지리정보원을 추가하는 것으로 다시 진행중입니다.

차주(2/1~2/5) 개발 예정이며 국토부 배포 일자는 아직 미정입니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 일정변경 사항에 대하여 김대용 팀장과 이야기 되신거죠?

**Comment by veldise** [comment]
@sunghoon 
네 메일로 받았고, 자세한 내용은 박세종 팀장님이 직접 통화한 것으로 알고 있습니다.
