### ISSUE TITLE
[철도청/DSL] forecasts 명령어는 parameter 로 한글 필드명 사용시 에러 납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2794]
## 버그 설명 ##

 철도청개발서버에서 확인했는데, 아마 b-iris.mobigen.com 도 동일하리라 생각됩니다.

forecasts 뒤에 오는 필드명이 영문일 때만 동작하고
앞부분에서 rename 이나 as 등으로 한글필드로 바꾼 뒤 forecasts  사용하면 angora 에러 납니다.

철도청개발서버 :  분석탬플릿 "이슈_forecasts_영문필드_정상"  참고

- 영문이름은 정상 실행
<img width="934" alt="스크린샷 2021-01-24 오전 11 58 29" src="https://user-images.githubusercontent.com/5126497/105619991-47771500-5e3b-11eb-9e6c-cf8eb69e876a.png">

- ATTACH_SUCC_RATE 를 `ATTACH성공률` 로 하면 에러납니다

- 참고로 anomalies 는 한글 필드이름으로 해도 정상 실행됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
확인해보니 지난주까지만 해도 forecasts 에서 한글 파라미터가 되었습니다. 그래서 지난주 forecasts 챠트에서는 한글 필드명 `발생건수`  필드로  forecasts  실행되어 아래처럼 챠트 결과가 나왔습니다.
<img width="798" alt="스크린샷 2021-01-24 오후 2 35 24" src="https://user-images.githubusercontent.com/5126497/105622057-405b0180-5e51-11eb-9d49-5e3ce6fe3cdd.png">

**Comment by seoryjj** [comment]
b-iris.mobigen.com  demo 계정

철도청과 마찬가지로 b-iris 에서도 forecasts 는 한글 필드명은 에러 납니다.

보고서 : ML-forecasts_이슈_2021_01_24   http://b-iris.mobigen.com:80/studio/exported/6cacfb6f54c949cab586e5967f4277bcdcc145647f6b48b985b6d014dac080dd

를 참고하세요.

**Comment by sunghoon** [comment]
@anhm @onursoyer @seungfwani  이슈 처리 일정 계획을 공유해 주세요.

**Comment by seoryjj** [comment]
<img width="1122" alt="스크린샷 2021-02-01 오전 10 29 04" src="https://user-images.githubusercontent.com/5126497/106405029-21bfc080-6478-11eb-997f-407b86d92327.png">

angora 에러(수행오류 문구) 가 아니라 이런 에러가 발생하고 있습니다.(ML-forecasts_이슈_2021_01_24  보고서)

**Comment by seungfwani** [comment]
@sero
현재 앙고라 에러 관련 리펙토링을 진행하고 있습니다.
