### ISSUE TITLE
[Studio] 기간설정 객체 - 초기날짜 설정하면 편집화면에서 비활성화될 때가 있습니다. 선택범위제한 이상으로 초기디폴트는 지정이 가능합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2796]
## 버그 설명 ##
b-iris.mobigen.com  /  철도청

참고 보고서 : 이슈_기간설정_2021_01_24버전_JHJ  http://b-iris.mobigen.com:80/studio/exported/dd8e4c99ae524a6eb0b4e784e5917f6a0afe8a76a5b840968ab0f50b9d0daace

- 초기 날짜를 사용자지정(예: 최근 7일 등등) 으로 하면 편집화면에서 기간설정 객체가 비활성화되어 시험 및 변경을 할 수 없습니다.
- 선택 범위 제한 1개월로 설정해도 초기날짜는 1개월 이상 기간으로 지정할 수 있습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@rhcpn @veldise 확인 후 조치 바랍니다.

**Comment by veldise** [comment]
@seoryjj 
아래와 같은 상태를 말씀하시는 것이라면 미리 설정(프리셋) 목록에서 '최근 7일'이 선택되었기 때문입니다.
'사용자 지정'으로 변경해야만 비활성화가 풀리고 날짜 변경이 가능해집니다.

![image](https://user-images.githubusercontent.com/3411842/105808361-eee67a00-5fea-11eb-956c-1bfa6ac93091.png)

"선택 범위 제한" 설정이 "초기 날짜(디폴트 값)" 설정 UI에 반영되지 않는 문제는 확인하였습니다.

**Comment by sunghoon** [comment]
문제가 되가 되는 부분 패치 일정은 잡히면 공유 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 이슈 처리 일정 계획을 공유해 주세요.

**Comment by veldise** [comment]
@sunghoon 
우선순위 높은 NMS+ 이슈를 먼저 처리하고 이어서 진행하려고 합니다.
자세한 일정은 차주에 다시 공유드리겠습니다.

**Comment by veldise** [comment]
금주 중에 처리하고 2/18 패치 예정입니다.

**Comment by veldise** [comment]
미비점이 있어 패치가 늦어졌습니다. 금주(2/25) 패치 예정입니다.
