### ISSUE TITLE
[다이렉트클라우드]extra_param에 회사코드 노출로 인한 보안이슈

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#2797]
## 버그 설명 ##
현재 다이렉트클라우드 서비스의 기존 관리자 화면에서 IRIS에서 만든 보고서를 iframe으로 제공하고 있습니다.
IRIS는 다이렉트클라우드의 AWS 클라우드에 설치되어 운용하고 있습니다.
얼마전 SSR에서 모의 해킹 후에 내부적으로 점검 결과,
보고서 페이지를 호출할때 extra_param 파라미터에 회사코드가 그대로 노출되는 것으로 발견하였다고 합니다.
이 경우, 회사코드만 알면 외부 악의의 사용자가 접근하여 정보 유출이 가능하지 않을까 하는 우려가 있습니다.
아래 파라미터를 보시면 kovecinc라는 회사코드가 그대로 노출되는 것을 확인하실 수 있습니다.

?extra_param=%7B%22report_title%22%3A%20%22%5Cu30c9%5Cu30e1%5Cu30a4%5Cu30f3%5Cu5206%5Cu6790%22%2C%20%22start_date%22%3A%20%2220201220000000%22%2C%20%22end_date%22%3A%20%2220201221000000%22%2C%20%22company_code%22%3A%20%22kovecinc%22%7D

이 문제를 해결할 수 있는 방안에 대하여 검토 부탁드립니다.

**Comment by sunghoon** [comment]
@rhcpn 확인 후 지원 바랍니다.

**Comment by rhcpn** [comment]
해당 이슈가 해결 되려면 Studio에서 query를 처리 (암호화) 하는 방식과 동일하게 접근해야 할것 같습니다.
최영철 책임과 논의 해보겠습니다.

**Comment by veldise** [comment]
`extra_param` 은 내보내기 URL로 보고서를 실행할 때, 기존과는 다른 값(날짜, 코드, ...)으로 보고서가 실행될 수 있도록
사용자가 임의의 값을 URL querystring 으로 입력할 수 있는 기능입니다.

따라서 보고서 페이지를 호출하는 쪽은 다이렉트 클라우드의 사용자 혹은 다이렉트 클라우드의 웹페이지로 생각됩니다.

**Comment by rhcpn** [comment]
해당 이슈에 대해서 진상현 팀장님께 아래와 같이 답변 하였습니다.
- extra_param은 사용자가 만들어낸 특정 파라메터와 값을 Studio에 전달하는 방식 입니다.. 따라서 파라메터를 어떻게 만들지는 Studio에서 고민 해야 할 부분이 아니라고 보여지기 때문에 현 시점에서는 별도의 암호화를 하는것은 맞지 않아 보입니다.
- 위와 같은 이유로 연구소에서는 해당 건에 대해 현 시점에 별도의 조치를 하지 않는게 맞는것 같아 보입니다.

**Comment by sunghoon** [comment]
@jins00 등록된 이슈에 대한 다른 사항이 없다면 Close 부탁드립니다.

**Comment by jins00** [comment]
@sunghoon 안녕하세요,
다이렉트클라우드측에서는 폐쇄망이 아닌 클라우드상에서 서비스하다보니 보안 이슈에 특히 민감한 것 같습니다.
따라서, 시간이 좀 걸리더라도 해결방안을 같이 찾아보자는 입장이기 때문에 협의가 지연되고 있습니다.
조금만 더 시간을 주시기 바랍니다.

**Comment by jins00** [comment]
@sunghoon 안녕하세요, 
본 건은 나규환책임님쪽에서 처리하기로 결정되어 이슈 close 하겠습니다.
