### ISSUE TITLE
[오픈랩] Studio의 IMA 컴포넌트 사용시 사용자 정의 필터의 template code가 처리 되지 않는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2798]
## 버그 설명 ##
IMA 컴포넌트를 Studio에서 사용시, 사용자 정의 필터 부분에 template 코드가 처리 되지 않습니다.

## 재현하는 방법 ##
스크린샷 참조 합니다.
![image](https://user-images.githubusercontent.com/11566844/105669955-97c9a200-5f23-11eb-842d-c33a5d0e0f3e.png)
![image](https://user-images.githubusercontent.com/11566844/105669967-9ef0b000-5f23-11eb-84dd-0fb5220f8f48.png)

## 예상한 행동 ##
현재 미리보기 버튼을 누르면 정상적으로 파싱 되어 보이는데, 실행 시에만 안되고 있습니다.
실행 시, 코드가 파싱되어 동작 해야 합니다.

**Comment by sunghoon** [comment]
@lyj @veldise 확인 조치 바랍니다.

**Comment by veldise** [comment]
현재 nunjucks 문법이 처리되지 않는 것과 별개로, IMA 뷰어(컴포넌트)에 아래와 같은 2가지 문제가 있어서 수정하고 IMA와 연동 테스트중입니다.
- Base Map 레이어에서 '변수 값 설정'을 입력하지 않고 트리거 설정을 한 경우, 이벤트 트리거시 에러가 발생하는 문제
- 데이터 레이어에서 '스냅샷 설정 변수'를 입력하지 않고 트리거 설정을 한 경우, 이벤트 트리거시 "잘못된 스냅샷입니다." 에러가 발생하는 문제

**Comment by sunghoon** [comment]
@rhcpn @veldise @lyj 이슈 해결을 위한 일정 정보를 공유해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
ASAP 으로 지시 받아 어제 개발팀 내에서 테스트까지 완료하고,
16:35 경 배포 후 해당 사이트에서 정상 동작하는 것을 확인했습니다.
