### ISSUE TITLE
메뉴 설정에서 그룹 메뉴 동작 추가 - 새창 띠우기

### ISSUE THREAD

**Issue by lyj** [mobigen/IRIS-BigData-Platform#2799]
#### 발생 이슈
- 메뉴 그룹에 새창으로 이동하는 하나의 메뉴만 존재함

#### 처리 방안
- 기존의 그룹 메뉴 방식으로 동작하지 않는 새로운 그룹 메뉴 타입 추가
- 사용자 URL 입력 받아 처리

**Comment by sunghoon** [comment]
@rhcpn @lyj 이슈 수행 계획 공유 바랍니다. 대략 2월 4일 패치 목표인것 같은데 맞는지요?

**Comment by lyj** [comment]
네. 2월4일 패치 예정입니다.
