### ISSUE TITLE
[LH빅데이터]Studio의 보고서에 대한 보기 권한 설정 기능 추가

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2800]
## 기능 요청 ##
Studio의 보고서 목록에 나타난 보고서들이 현재는 아무런 제약없이 모두 볼 수 있음.   
접근권한이 없으면 보고서를 볼 수 없도록 권한 설정 기능 필요

LH 사업의 경우 특정 부서에서만 봐야 하는 화면을 보고서로 만들어 제공 하고 있으나,   
향 후 모든 사용자에게 보고서 생성기능이 오픈될 경우 이를 아무나 볼 수 있게되는 문제가 있음

## 원하는 솔루션 설명 ##
보고서를 검색해서 나타난 리스트를 보고,   
공개되지 않은 보고서에 대해서는 보기 권한 요청을 통해 볼 수 있는 권한을 획득 할 수 있도록 기능 추가

-  보고서 보기 권한 예시 : 비공개 or 공개(전체공개, 특정 그룹 or 사용자 공개)

**Comment by sunghoon** [comment]
@rhcpn @eumminsun @veldise 확인 후 조치 바랍니다.

**Comment by veldise** [comment]
@JeongHeeDong 
보고서를 작성한 사람이 다른 사용자에게 접근 권한(실행 및 복제 권한)을 부여하는 기능은 현재 있습니다.
다만 보기(실행)만 가능하거나 권한을 요청하는 기능은 아직 없습니다.

해당 기능을 보강하는 방향으로 가면 원하시는 내용에 부합할지 검토 부탁드립니다.

![image](https://user-images.githubusercontent.com/3411842/105808738-a4193200-5feb-11eb-9073-61a91c99c95d.png)

**Comment by JeongHeeDong** [comment]
@veldise 
현재 기능으로도 해결 가능 할 것으로 보입니다.
나중에 추가로 필요하면 다시 요청 드리겠습니다.
