### ISSUE TITLE
데이터 그리드 페이징바 출력 여부 설정 기능 추가 요청

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2801]
## 기능 요청 ##
Studio의 시각화의 데이터 그리드에 페이징 바 출력 여부를 설정 가능한 옵션 추가를 요청 합니다.

## 원하는 솔루션 설명 ##
보고서 작성 시 단순 테이블로서의 기능으로 사용할 목적으로 시각화 테이블을 지정 하는 경우가 있습니다.
이때 명시적으로 페이징바를 제거 할수 없어서 해당 기능이 필요합니다.

**Comment by sunghoon** [comment]
@eumminsun 옵션 설정 기능을 정의해서 준비해 주시기 바랍니다.

**Comment by veldise** [comment]
2/9 패치로 아래와 같이 기능 추가되었습니다.

![image](https://user-images.githubusercontent.com/3411842/109108031-178e9a80-7776-11eb-8e35-2281089e556b.png)
