### ISSUE TITLE
[DSL] union sql 이 갑자기 오류 납니다.(2021-01-27 버전)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2802]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- union sql 문이 갑자기 angora 오류 납니다.

## 내용
- 먼저 데이터모델 : EDU_TEMP_DUAL  에 A 컬럼에 레코드 1개 생성 후에
`* | mkdata [{'A': '20201201'}] `
<img width="700" alt="스크린샷 2021-01-27 오후 3 51 28" src="https://user-images.githubusercontent.com/5126497/105953896-4baf6680-60b7-11eb-865b-67d712e0692a.png">

- 여기에 union sql 로 레코드 1개 더 추가하기  -> 오류 발생
`* | mkdata [{'A': '20201201'}]  | union sql "select '20210127' from angora" `
<img width="635" alt="스크린샷 2021-01-27 오후 3 53 06" src="https://user-images.githubusercontent.com/5126497/105954078-86190380-60b7-11eb-81c4-134017ed2310.png">

- 철도청 사이트에서는 union sql 로 레코드 1개 추가하여 정상 동작했습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@onursoyer @seungfwani 빠른 확인 후 조치 바랍니다. TEST Case도 추가해 주시고요.

**Comment by seungfwani** [comment]
angora-proxy(angora 와 다른 서비스) 와 동작하는 로직에서 문제가 있는 것을 발견하여 수정을 하였습니다.
오늘(21/01/28 목) 배포 후에 확인해보도록 하겠습니다.

**Comment by sunghoon** [comment]
@seungfwani 배포 완료 되었으면 Close 해 주세요.

**Comment by seungfwani** [comment]
처리되었습니다
<img width="1293" alt="Screen Shot 2021-01-29 at 1 17 13 PM" src="https://user-images.githubusercontent.com/46172579/106231141-58a59480-6234-11eb-9577-aa12f4724e11.png">
