### ISSUE TITLE
[LH빅데이터] 메뉴가 나타나지 않는 현상 확인 요청

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2804]
## 버그 설명 ##
사용자 추가 후 개인 설정의 초기 화면이 설정되지 않으면
모든 메뉴가 나타나지 않음
개인설정에서 초기 화면 설정을 하면 권한있는 메뉴가 모두 나타남

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 특정 그룹으로 사용자 추가
2. 추가된 사용자로 로그인

## 예상한 행동 ##
권한이 있는 메뉴는 초기화면 설정과 상관없이 나타나야함

## 스크린샷 ##

[메뉴가 나타나지 않음]
![image](https://user-images.githubusercontent.com/4444717/106418775-6a887100-649a-11eb-8cb1-c8680042bba9.png)

[초기화면 설정]
![image](https://user-images.githubusercontent.com/4444717/106418681-40cf4a00-649a-11eb-92f7-e9c0ceb20150.png)

[메뉴가 나타남]
![image](https://user-images.githubusercontent.com/4444717/106419226-5c872000-649b-11eb-94dd-6ded0324434c.png)

**Comment by rhcpn** [comment]
@JeongHeeDong 접속 정보 및 해당 사용자 정보를 따로 공유 해주시면 확인 해보겠습니다.

**Comment by JeongHeeDong** [comment]
lh893745 로 테스트 하시면 됩니다.
password는 메세지로 알려 드리겠습니다.

**Comment by rhcpn** [comment]
유선상으로 가이드 드린대로 IRIS 소개 페이지 (IRIS 대시보드) 를 사용하지 않을때, 기본 페이지가 사라져서 생기는 문제입니다.
해당 부분은 수정 예정이며 우선 아래와 같이 설정하면 해당 현상을 방지 할수 있습니다.

1. 관리자 화면 > 메뉴 관리 > 그룹 선택 > 첫그룹 항목의 첫 그룹으로 설정 체크
2. 첫 화면으로 지정하고자 하는 메뉴 선택 후 첫 화면 항목의 첫 화면으로 설정 체크

**Comment by sunghoon** [comment]
@rhcpn @lyj 업무 진행 일정을 잡아서 공유 해 주시기 바랍니다.

**Comment by lyj** [comment]
IWP 다른 이슈중에 Dashboard 서비스 사용하지 않는 구성 요청으로,
첫페이지 표시 변경 기능이 2월1일 패치되었습니다.
수정 버전은 Dashboard 메뉴가 없을경우 첫번째 그룹이 default로 표시됩니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj
