### ISSUE TITLE
[LH빅데이터]개인설정 메뉴의 유저정보 메뉴 안보이도록 처리

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#2807]
## 기능 요청 ##
개인설정정 메뉴의 유저정보 메뉴는 보이지 않도록 처리 요청

SSO로 로그인한 경우 개인이 비밀번호를 변경 할 수 없도록 해야 하는 이슈가 있음
현재 LH공사에 배포된 버전을 보면 개인설정 메뉴의 유저정보에서  비밀번호를 포함한 정보들을 수정 할 수 있도록 되어 있어 문제가 됨

"유저정보" 메뉴의 표시 여부를 root관리자가 관리 할 수 있도록 처리 필요

기능 추가에 시간이 많이 소요된다면, 우선 root계정과 같이 모든 사용자에서 "유저정보" 메뉴는 보이지 않도록 처리 필요

![image](https://user-images.githubusercontent.com/4444717/106534336-344cff00-6537-11eb-86ee-76826046ad9b.png)

**Comment by sunghoon** [comment]
@rhcpn @eumminsun SSO 설정에 따른 UX를 개선해 주시면 좋을것 같습니다.

**Comment by lyj** [comment]
"유저정보" 메뉴의 표시 여부를 root관리자가 관리 기능 추가는 기획, 디자인, 개발이 모두 필요하여 시간이 많이 소요됩니다.
우선 SSO 인증으로 로그인한 경우, 해당 메뉴를 표시하지 않도록 처리하겠습니다.
오늘(2/3)중 완료 예정입니다.

**Comment by lyj** [comment]
기능 완료하여 2월3일 운영팀에게 전달하였습니다.
