### ISSUE TITLE
[Studio] 테이블객체 - 시각화 이벤트값 전달 설정 시 텍스트한정자를 설정해도 저장이 되지 않습니다.(갑자기 발생한 현상)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2808]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

일시 : 2021-02-02 12시 전후
오전에는 정상적으로 동작했는데, 12시 전후부터 테이블객체-시각화 에서 설정한 텍스트한정자가 저장되지 않는 현상이 발생합니다.

<img width="200" alt="스크린샷 2021-02-02 오후 12 18 31" src="https://user-images.githubusercontent.com/5126497/106548035-a599ab80-6551-11eb-8f10-e1a83e8c657e.png">

다시 편집으로 들어가면 저장되어 있지 않습니다.
<img width="205" alt="스크린샷 2021-02-02 오후 12 20 35" src="https://user-images.githubusercontent.com/5126497/106548048-ac282300-6551-11eb-9238-99995d5056f1.png">

- 참조보고서 : 이슈_테이블텍스트한정자  http://b-iris.mobigen.com:80/studio/exported/029a9982bc5348eeaee0eebe240fb4bf3e410d87a919473192dfb5d56ee921e9

왼쪽 테이블 객체를 선택 후 시각화-텍스트한정자 설정해보세요
<img width="207" alt="스크린샷 2021-02-02 오후 12 26 17" src="https://user-images.githubusercontent.com/5126497/106548275-0aed9c80-6552-11eb-95f1-dedcf0907e86.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
갑자기가 아닐 수도 있을 듯... 계속 편집화면의 보기 로 실행을 해서 정상동작하는 것처럼 착각했을 수도 있겠습니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 이슈를 확인 해 주시기 바랍니다.

**Comment by veldise** [comment]
@sunghoon 
개발서버에서도 저장되지 않는 현상을 확인했습니다. 버그로 판단됩니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 조치 일정 계획을 새워서 공유 해 주세요.

**Comment by veldise** [comment]
버그 수정 완료하여 2/9 패치 예정입니다.
