### ISSUE TITLE
[Studio] 검색어 실행 후 angora 오류메시지가 없어졌습니다(2021-02-09)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2809]
## 버그 설명 ##
b-iris.mobigen.com  demo

Analyzer 에서는 angora 오류 발생 메세지가 보이지만
Studio 에서는 에러 문구 없이 그냥 무응답입니다.

보고서 : 이슈_에러메세지 http://b-iris.mobigen.com:80/studio/exported/4992807a209a477fbd04405ef7ee4a06602c4734921a4a2ab7995e675a8ef698

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
@anhm @onursoyer @seungfwani 내용 확인하여 빠른 조치 바랍니다.

**Comment by veldise** [comment]
@seungfwani 
화면에 에러 메시지가 출력되지 않는 것은 response status code 가 200 이어서 그렇습니다.

```json
{
    "q": "model name = 'EDU_apple_mobility_data_0113_0804' model_owner = demo | where geo_type='country/region'  and region =  'Republic of Korea'  | fields  -geo_type,sub-region,country",
    "cached": false,
    "force": true,
    "size": 10000
}
```
```json
{
  "message": "(\"Syntax error near '-'\",) [fields -geo_type,sub-region,country]",
  "type": "SyntaxError"
}
```

**Comment by seungfwani** [comment]
수정완료되어 닫습니다.
