### ISSUE TITLE
[NB-IOT] Studio: 팝업 내 보고서의 버튼 - 링크 URL 에 변수값이 전달되지 않는 문제

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2813]
## 버그 설명 ##
[NB-IOT] Studio: 팝업 내 보고서의 버튼 - 링크 URL 에 변수값이 전달되지 않는 문제

제보자: 김준우 책임

메일 원문:
```
팝업창에서 새로운 창을 또 띄워야 합니다.
현재는 링크설정의 하이퍼링크를 이용하고 있고,

http://192.168.102.124:18080/studio/exported/13a9ebb06745470db6c08b382f6c833a7fdf8de2731f4e23a9eca71ce2c8d31c?extra_param=%7B%22canvas_1%22%3A%22${combo_1}%22%7D

주소에 위와같은 URL을 이용하고 있습니다.
팝업창에서 링크설정을 했을경우 canvas_1 변수에 combo_1 값이 전달되지 않는 것으로 보입니다.
기능상 원래 안되는 것인지.. 버그인지 확인이 필요합니다.

canvas_1%22%3A%22${combo_1} << 이 부분
파란색 표시되어 있는 combobox 가 combo_1 객체 이고,
파란색 표시되어 있는 링크설정이 하이퍼링크를 이용하고 있는 URL 입니다.
```

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/108158674-cdc80380-7128-11eb-891a-847aadbdfb44.png)

**Comment by sunghoon** [comment]
@veldise 조치 일정 공유 바랍니다.

**Comment by veldise** [comment]
@veldise 
NB-IOT 개발기에는 어제 오후에 바로 지원하여 완료하였습니다.
사내 시스템에는 차주 적용 예정입니다.

**Comment by veldise** [comment]
@sunghoon 
NB-IOT 개발기에는 어제 오후에 바로 지원하여 완료하였습니다.
사내 시스템에는 차주 적용 예정입니다.
