### ISSUE TITLE
스튜디오 데이터 조회시 데이터가 없을 경우 이슈 사항

### ISSUE THREAD

**Issue by anhm** [mobigen/IRIS-BigData-Platform#2814]
## 버그 설명 ##
스튜디오에서 데이터를 검색시,

데이터가 결과가 존재한 다음에, 데이터 결과가 없는 상태의 결과를 조회할 경우 이전에 실행된 쿼리 결과가 그대로 남아 있는 현상이 존재함

## 스크린샷 ##
![스크린샷 2021-02-17 오후 5 18 29](https://user-images.githubusercontent.com/3415270/108175713-6fa91980-7144-11eb-9804-8842088a3b20.png)

**Comment by veldise** [comment]
2/9 패치로 변경된 내용인데, 한 번 더 개선이 필요한 것 같습니다.
https://github.com/mobigen/IRIS-BigData-Platform/wiki/2021-02-09---Patch#%EB%94%94%EC%9E%90%EC%9D%B8%EC%8A%A4%ED%83%80%EC%9D%BC-%EB%B3%80%EA%B2%BD

**Comment by sunghoon** [comment]
@veldise 빠른 조치 바랍니다.
@EricLeeMbg QA 점검시 관련 검증 개선 바랍니다.

**Comment by EricLeeMbg** [comment]
> @veldise 빠른 조치 바랍니다.
> @EricLeeMbg QA 점검시 관련 검증 개선 바랍니다.

확인 테스트 추가하겠습니다.

**Comment by veldise** [comment]
@sunghoon 
아래와 같이 동작하도록 2/25 패치하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/108306955-9755bb80-71f0-11eb-84b2-9504f287e1ba.png)
