### ISSUE TITLE
[Studio] hidden객체인 "텍스트변환" 객체에서 트리거 설정 연결 해제가 안됩니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2815]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

보고서 : 이슈_히든객체  
http://b-iris.mobigen.com:80/studio/exported/5f3af9b696da402f84195b59370fd23e3e83b490effa4152b8edcb1bd7133196

hidden_1 객체에서 설정된 2개 트리거중 앞에 걸 연결 해제 하려고 하는데, 해제가 안됩니다.

<img width="248" alt="스크린샷 2021-02-22 오후 2 35 34" src="https://user-images.githubusercontent.com/5126497/108666794-4d841280-751b-11eb-95c1-f8e68d8313af.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
코드 오타로 인한 버그라서 바로 수정하였습니다. 금주(2/25) 패치 예정입니다.
