### ISSUE TITLE
[NB_IOT] 테이블 차트 결과

### ISSUE THREAD

**Issue by kim3163** [mobigen/IRIS-BigData-Platform#2821]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

1. 조회 버튼 클릭시 테이블 조회

![image](https://user-images.githubusercontent.com/16331916/109896377-317b3080-7cd4-11eb-857a-4e774e00a532.png)

2. 필터링을 넣어서 조회 버튼 클릭시 조회 결과가 없음.

![image](https://user-images.githubusercontent.com/16331916/109896314-0db7ea80-7cd4-11eb-95ec-c1bd46d0d7c8.png)

결과가 없습니다 라는 결과가 보여지긴 하지만, 그 전에 조회했던 결과가 있는 테이블 조회가 함께 보여서

마치 결과가 있는 것 처럼 보임.

192.168.100.180 서버 에서는 발생하지 않는 버그 입니다.

위 현상은 192.168.102.124:18080 서버에서 발생.
[192.168.102.124:18080 은 Kubenates 가 아닌 docker 버전으로 되어있습니다.]

**Comment by veldise** [comment]
#2814 와 동일 이슈로 생각됩니다.
동일 이슈가 맞다면 2020-02-25 버전으로 패치하여 해결이 가능합니다.
