### ISSUE TITLE
[Studio, IMA] Studio 보고서의 IMA 컴포넌트가 로그인시와 로그인하지 않는 경우 다른 결과가 출력 되는 문제

### ISSUE THREAD

**Issue by rhcpn** [mobigen/IRIS-BigData-Platform#2822]
## 버그 설명 ##
교통빅데이터 오픈랩 보고서 관련하여 확인요청드립니다.
오픈랩에 로그인한 경우와 로그인하지 않은 경우 보고서의 IMA가 다르게 출력됩니다.
속성데이터에 대한 색상이 정상적으로 적용되지 않아 보입니다.
확인요청드립니다.

## 스크린샷 ##
- 로그인
![image](https://user-images.githubusercontent.com/11566844/109910550-ba519680-7ceb-11eb-9d73-826257b7463b.png)

- 로그인 하지 않는 경우
![image](https://user-images.githubusercontent.com/11566844/109910563-c2113b00-7ceb-11eb-823b-86fee3b0056f.png)

**Comment by rhcpn** [comment]
DV개발실 장세경 책임이 제보해준 내용을 등록 하였으니 참고하시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @lyj 최종 처리 상태 정보를 공유 해 주시기 바랍니다.

**Comment by rhcpn** [comment]
해당 이슈는 최근에 원인이 밝혀 졌습니다. 차주 패치 예정입니다.
아래 이슈에서 추가 정보 확인이 가능 합니다.
https://github.com/mobigen/IRIS/issues/487
