### ISSUE TITLE
[Studio] 트리거 이벤트 제거가 안돼요

### ISSUE THREAD

**Issue by handayeon** [mobigen/IRIS-BigData-Platform#2823]
## 버그 설명 ##
트리거 설정 확인에서 이벤트 제거 버튼을 누르면 먹지를 않아요

## 재현하는 방법 ##
동작을 재현하는 방법 :
 Click on '조회년도 옆 콤보박스' -> 속성

## 예상한 행동 ##
트리거가 지워진다

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/50221479/110083215-c57ef200-7dd1-11eb-842f-78458618e136.png)

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
해당 사이트는 2021-01-14 버전으로 보입니다. 현재 최신 버전은 2021-03-05 입니다.

@handayeon 
최신 버전에서는 문제가 재현되지 않는 것으로 보입니다.
해당 사이트 로그인 정보를 알려주시면 확인해보겠습니다.

이 사이트는 공개되어 있으므로 로그인 정보는 코멘트로 남기지 마시고 문자 등으로 보내주시기 바랍니다.

**Comment by sunghoon** [comment]
@rhcpn @veldise 최종 처리 상태 정보를 공유 해 주세요.

**Comment by handayeon** [comment]
'이슈_#2823'
들어가셔서 데이터모델(common_data_1) - 속성 - 트리거 속성확인에서 위에 있는 제거 표시 누르시면 안먹는 거 확인 가능하실거에요 !

**Comment by veldise** [comment]
@handayeon 
확인했습니다.
