### ISSUE TITLE
[Studio] 파이차트 조회시 데이터가 없을 경우, '데이터가 없습니다.' 표시 필요

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2826]
## 버그 설명 ##
파이차트 실행시, 조회 결과가 없을 경우 이전 데이터 그대로 남아있습니다.
테이블의 경우, '데이터가 없습니다.' 라고 표시됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 보고서명: 조달정보분석_갤러리_v0.2

2. 키워드 '빅데이터' 입력 후 조회
![image](https://user-images.githubusercontent.com/5077625/110397738-bfc92b00-80b5-11eb-81a4-e231e21abc11.png)

3. [관심분야 신규 공고]의 2번째행 선택시 아래에 파이차트와 테이블 출력
![image](https://user-images.githubusercontent.com/5077625/110397824-ed15d900-80b5-11eb-88de-20e96ee8309d.png)

4. [관심분야 신규 공고]의 1번째행 선택
![image](https://user-images.githubusercontent.com/5077625/110398016-48e06200-80b6-11eb-931c-abea92d9b601.png)
파이차트는 이전 조회 결과가 그대로 남아있습니다. (테이블의 경우, '데이터가 없습니다.' 표시)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@euhyesun 
버그로 확인되었습니다. 근시일내에 수정하겠습니다.

**Comment by veldise** [comment]
3/18 패치 예정입니다.
