### ISSUE TITLE
[Studio] 스튜디오 반응형 화면기능중 확대/축소 기능 추가

### ISSUE THREAD

**Issue by swish1995** [mobigen/IRIS-BigData-Platform#2827]
## 기능 요청 ##
브라우져의 확대/축소 기능 외에 편집화면만 버튼 또는 특정 키+마우스 스크롤 로 확대/축소 가능한 기능

## 원하는 솔루션 설명 ##
전체 화면의 확대/축소 기능이 아닌 편집화면만 확대/축소 해서 작업하기 위한 기능
- 화면에 맞추기 기능(Fit Screen), 원본 사이즈(100%), 기타 프리셋을 선택
- 프리셋 말고 직접 숫자를 입력하여 확대/축소

**Comment by swish1995** [comment]
편집 화면 DIV 를 확대하기 위해서는 다음의 두가지 css 속성을 이용할수 있습니다.
- `zoom` 속성
   - 참조 : https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
   - 다른 브라우져들은 지원하지만 firefox 는 지원하지 않음
   - 전체 화면을 다시 rendering 하기 때문에 스크롤이나 다른 문제가 발생하지 않음
   - 마우스 의 offset 이 100% 기준으로 계산되어 동작함
- `transform` 속성중 `scale` 이용
   - 참조 : https://developer.mozilla.org/ko/docs/Web/CSS/transform
   - 모든 브라우져 지원
   - 해당 DIV 만 rendering 하기 때문에 속도면에서 이점이 있으나 스크롤 바 를 해결해야 함
   - 마우스 의 offset 이 100% 기준으로 계산되어 동작함

위의 두가지 방식중 zoom 을 사용하게 되면 firefox 를 배재 하여야 하며 transform 을 사용하려면 스크롤 문제등을 해결해야 함
어떤 방식을 사용하던 마우스의 상호 동작시 100% 기준으로 포인트가 계산 되므로 작업하고자 하면 별도의 일정 산정이 필요함

참고로 스튜디오에서 사용하는 interact.js 도 mouse drag 동작시 [버그](https://github.com/taye/interact.js/issues/137) 있는 것으로 확인됨

**Comment by veldise** [comment]
내부 개발 이슈라서 닫습니다.
