### ISSUE TITLE
[Studio] 버튼 객체 - 꾸미기옵션의 "채우기"에서 색상 지정을 없애도 색상이 없어지지 않습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2829]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

참고 보고서 : 이슈_버튼 채우기색상  http://b-iris.mobigen.com:80/studio/exported/cf493924f5054d6f841d7b737038a9a9567ae22a6820474ca1e111ba8e23f424

- 버튼 객체 에서 "꾸미기옵션"  에서 채우기 색상을 없애고, 테두리만 두려고 합니다.
<img width="380" alt="스크린샷 2021-03-10 오후 2 30 55" src="https://user-images.githubusercontent.com/5126497/110581146-52002a80-81ad-11eb-9a23-3dba86a39f39.png">

- 하지만 기본 색상이 그대로 남아 있습니다.
<img width="237" alt="스크린샷 2021-03-10 오후 2 26 05" src="https://user-images.githubusercontent.com/5126497/110580925-eddd6680-81ac-11eb-88fa-e2ee8d369dae.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
3/18 패치에서 해결하겠습니다.
