### ISSUE TITLE
[Studio] TAG 컴포넌트 동작 오류

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2831]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
태그 컴포넌트 객체 편집모드에서는 변수에 태그 값이 동작하지만 보고서를 편집 모드가 아닌 보고서 목록에서
선택해서 보면 태그 기능이 정상 동작하지 않습니다.
그리고 속성에서 태그 객체의 변수 명이 종종 중복된다는 경우가 있습니다.
그리고 추가로 태그도 체크 박스처럼 전체 선택 옵션이 있으면 좋겠습니다.
보고서명 태그이슈 공유합니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/110733415-3f4b2b80-8269-11eb-818d-7b9836b70b55.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
변수처리 관련하여 버그를 확인하였습니다. 3/18 패치에서 해결될 수 있도록 하겠습니다.
