### ISSUE TITLE
[LH 빅데이터] IRIS Web 테이블 권한 오류

### ISSUE THREAD

**Issue by qkrwkd124** [mobigen/IRIS-BigData-Platform#2834]
## 버그 설명 ##
IRIS Web DB 클러스터 관리에서 테이블 권한을 그룹으로 설정할때 아무런 반응을 안합니다.
저렇게 하면 안되는 건지 아니면 버그인지 모르겠습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

IRIS DB 클릭
![image](https://user-images.githubusercontent.com/46804062/111129289-42bc1b00-85b9-11eb-8de0-7752ded7354f.png)

클러스터관리 => 관리 => 테이블권한 에서 설정 클릭
![image](https://user-images.githubusercontent.com/46804062/111129454-6f703280-85b9-11eb-8523-2a6a7e4d04f0.png)****

설정에서 그룹 선택 후 

테이블을 클릭해도 아무런 반응이 없고 저장을 눌러도 반응이 없습니다.
![image](https://user-images.githubusercontent.com/46804062/111124312-b8bd8380-85b3-11eb-83c5-e37759eae74b.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
버그 상황이고, 이전에 국토부 보안조치 관련하여 수정한 내용으로 인한 것 같습니다.
패치 가능한지 검토해보겠습니다.

**Comment by veldise** [comment]
사내 시스템에는 3/25 패치에서 해결하겠습니다.

**Comment by sunghoon** [comment]
@veldise 2월 25일 이죠? ^^
