### ISSUE TITLE
[Studio][개발요청] 변수에 저장된 text type 값들을 "예제1", "예제2", "예제3"  처럼 따옴표와 콤마로 만드는 함수 또는 명령어

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2839]
## 기능 요청 ##
b-iris.mobigen.com demo 계정

- studio : EDU_예제_그룹_여집합구하기
http://b-iris.mobigen.com:80/studio/exported/89d7a85f1c784c24ac0306f366dfc80623435f48882e47ae9704e66a76b26d5e

에서 
-  "common_data_3"
<img width="479" alt="스크린샷 2021-03-22 오전 8 29 48" src="https://user-images.githubusercontent.com/5126497/111924633-e9884600-8ae8-11eb-87cf-d76ef35b8177.png">

- "common_data_2"
<img width="478" alt="스크린샷 2021-03-22 오전 8 31 48" src="https://user-images.githubusercontent.com/5126497/111924683-0fade600-8ae9-11eb-9020-c18d4e37921f.png">

- 원하는 구문
```
* |   
sql "SELECT  explode(array_except( array( 'setosa','virginica' ), array( 'versicolor','virginica' ) ) ) as my_uniqSpecies
from angora"
```
 
- 변수명에서는 문자열에 따옴표가 있지만, studio 에서 사용할 때는 **따옴표가 삭제** 됩니다. 그래서 nunjucks  로 for loop 구문을 써서 따옴표를 붙이는 작업을 해야 합니다. 
```
* |  {% set my_string = '' %}
{% for i in common_data_3.results -%}
  {% set my_string =  my_string ~ "'" ~  i  ~ "',"  %}
{%- endfor %}
{% set  my_string = my_string.slice(0,-1)   %}
 {% set my_string2 = '' %}
{% for i in common_data_2.results -%}
  {% set my_string2 =  my_string2 ~ "'" ~  i  ~ "',"  %}
{%- endfor %}
{% set  my_string2 = my_string2.slice(0,-1)   %}

sql "SELECT  explode(array_except( array( {{ my_string }} ), array( {{ my_string2 }} ) ) ) as my_uniqSpecies
from angora"
```

## 원하는 솔루션 설명 ##
nunjucks 없이 
변수에  TYPE : text  이면 따옴표가 붙은 채로 사용할 수 있는 기능

검색어에서

- 현재 
```
 * | where A in ( ${common_data_3.results}  )  => * | where A in ( setosa,virginica  )
```
- 요청
```
 * | where A in ( ${common_data_3.results}  )  =>  * | where A in ( 'setosa', 'virginica'  )
```

로 사용할 수 있는 방법이 필요합니다.

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
@anhm @onursoyer @seungfwani 이슈 진행 상황에 대해 정보 공유 바랍니다.

**Comment by seungfwani** [comment]
@rhcpn @veldise 해당 이슈는 studio 에서 수정이 되어야 할 것으로 보입니다.

--------

앙고라에서 수정이 불가능한 이유입니다.

angora 는 사용자가 입력한 string(query) 을 분해하여 해당 string 의 구조가 원하는 구조가 맞는지 확인을 하게 됩니다.

위 예제의 where 명령어를 보면, `A in ( 'setosa', 'virginica'  )` 라는 string 을 angora 는 `A`, `in`, `(`, `'setosa'`, `'virginica'`, `)` 의 토큰의 구조가 맞는지 확인하고 데이터 필터링 동작을 실행하게 됩니다.

토큰을 자세히 보면 아래와 같을 것입니다.
- `in` 은 값의 비교를 위한 예약 문자로 구분됩니다
- `(`, `)`  는 특수 문자로 사용 됩니다.
- `A` 는 비교되는 컬럼명으로써 사용됩니다.
- `'setosa'`, `'virginica'` 는 비교되는 값으로써 사용됩니다.

그런데 만약 `'setosa'` 를 `setosa` 로 사용 할 수 있도록 한다면, where 명령어 에서는 컬럼명과 값의 구분이 되지 않게 되어 잘못된 수행을 할 가능성이 높아 집니다. 또한, 다른 명령어에서도 컬럼명과 값의 구분이 어려워집니다.

**Comment by veldise** [comment]
@seoryjj 
아래와 같이 nunjucks 문법으로 제공하려고 하는데 어떠신가요?
```
 * | where A in ( ${common_data_3.results | joinstr } )  => * | where A in ( 'setosa','virginica' )
 * | where A in ( ${common_data_3.results | joinstr('"', '|') } )  => * | where A in ( "setosa"|"virginica" )
```

**Comment by veldise** [comment]
위와 같이 nunjucks custom filter 추가하는 방향으로 진행하겠습니다. (목표: 4/15)
