### ISSUE TITLE
[KDX]작업조회기능 오류

### ISSUE THREAD

**Issue by jins00** [mobigen/IRIS-BigData-Platform#2841]
## 버그 설명 ##
개별 사용자별 특정 쿼리 사용 빈도 등 분석을 위해 작업조회 기능을 사용하고자 하였으나,
root 사용자의 작업만 출력됨

## 재현하는 방법 ##
1. http://analytics.kdx.kr/ 에 root 계정으로 접속
2. IRIS 관리 > 작업조회로 이동
3. 기간을 설정한 후, 검색 버튼을 클릭
4. 조회 결과 화면에서 사용자 = root의 작업결과만 리스트되며, 타 사용자의 작업 결과는 확인 불가함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/23075670/112101624-50415880-8bea-11eb-9ba5-6feade8af805.png)

## 요청사항 ##
본 기능은 각 사용자별 자주 사용하는 쿼리 등 분석을 통해 성능 개선 등에 활용이 가능할 것으로 기대됩니다.
따라서, root가 아닌 일반 사용자의 작업 결과도 조회 가능하도록 수정 부탁드립니다.

**Comment by rhcpn** [comment]
@seungfwani 해당 작업 관리 목록은 angora 쪽에서 남기는것으로 알고 있는데요, 이력 남길때 root 로 지정 중인지 확인이 필요합니다.
참고로 UI 쪽에서는 로그인한 사용자로 angora query 요청 하는 부분을 확인 하였습니다.

**Comment by seungfwani** [comment]
@rhcpn  jhms 에서 user 로 필터링하는 코드가 있어서 발생한 것으로 보입니다. (where user = 'root')  jhms 를 수정해야합니다.

**Comment by anhm** [comment]
해당 기능은 다음 패치에 기능이 추가될 예정입니다.

아래와 같이 root 계정에서는 모든 계정의 정보를 보이도록 작업을 했습니다.
![image](https://user-images.githubusercontent.com/3415270/112424453-c6bf9100-8d77-11eb-8e12-8898d4903913.png)
