### ISSUE TITLE
[PlayGround] Jupyter - python 3  작업한지 5분도 되지 않아서 connection fail 창이 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2843]
## 버그 설명 ##
 b-iris.mobigen.com demo 계정

- notebook 작업중에 갑자기 이 창이 뜨고, 그 뒤로 실행해도 무응답...  connection fail 됩니다.
<img width="562" alt="스크린샷 2021-03-24 오후 1 49 47" src="https://user-images.githubusercontent.com/5126497/112257578-6d3c6100-8ca8-11eb-842e-8f637f51a904.png">

- 이렇게 작업하다가 위의 창이 뜨더니 곧 오른쪽 상단에 Not connected 버튼이 생깁니다.
<img width="977" alt="스크린샷 2021-03-24 오후 1 51 47" src="https://user-images.githubusercontent.com/5126497/112257473-3ebe8600-8ca8-11eb-8e0c-435991d315a9.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by anhm** [comment]
@seoryjj
현재 해당 문제가 재현되고 있지 않은 상태입니다.
현재도 같은 현상인지 확인을 부탁 드립니다.

**Comment by anhm** [comment]
이슈를 등록하신 분과 확인하여, 현재 발생하고 있지 않은 상황이라 일단 이슈를 닫도록 하겠습니다.
