### ISSUE TITLE
[이상탐지] 메뉴에서 syslog 로 10분 통계로 SPC 이상탐지 시 angora 에러 발생합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2846]
## 버그 설명 ##
b-iris.mobigen.com demo계정

- 데이터모델 tylor_syslog / 최근 60 분
- 설정
<img width="477" alt="스크린샷 2021-03-25 오후 3 41 36" src="https://user-images.githubusercontent.com/5126497/112430012-e7401900-8d80-11eb-9148-1c22e57d0ec9.png">

- 에러
<img width="394" alt="스크린샷 2021-03-25 오후 3 40 35" src="https://user-images.githubusercontent.com/5126497/112430027-ee672700-8d80-11eb-9272-f380a2beb22e.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
동일 조건으로 지금은 또 실행이 됩니다. 
<img width="730" alt="스크린샷 2021-03-25 오후 3 52 55" src="https://user-images.githubusercontent.com/5126497/112431012-4b171180-8d82-11eb-8e79-8d1eb33fcc34.png">
<img width="386" alt="스크린샷 2021-03-25 오후 3 53 59" src="https://user-images.githubusercontent.com/5126497/112431034-536f4c80-8d82-11eb-9c47-26fd068f00fa.png">

**Comment by seungfwani** [comment]
해당 테이블(SYSLOG) 의 블록 파일에 문제가 있어서 발생한 오류입니다.
블록파일 복구를 진행하였습니다.
