### ISSUE TITLE
[KOTRA] IRIS Analyzer 사용자 계정 암호 변경 불가 관련 기능 수정 요청

### ISSUE THREAD

**Issue by srust4533** [mobigen/IRIS-BigData-Platform#2848]
## 버그 설명 ##
IRIS Analyzer Docker 버전에서 kubernates 버전으로 마이그레이션 후 기존 ID의 호환성 문제 발생
비밀번호 변경시 아이디 수정도 안되며, 아이디 유효성 체크로 인해 변경 불가함.

## 재현하는 방법 ##
1. 메뉴 > 설정 클릭
2. IRIS관리 > 사용자관리 > 사용자 계정 클릭
3. 사용자 계정 목록에서 관리 항목에서 수정 클릭
4. 비밀번호 변경후 저장
* 아이디 수정도 안되며, 아이디 유효성 체크로 인해 변경 불가

## 수정 방향 ##
사용자 계정 수정시 아이디가 변경이 안되므로 기존 시스템과 호환성으로 위해 아이디 유효 체크가 발생하지 않아야함.

## 스크린샷 ##
![KakaoTalk_20210330_142325754](https://user-images.githubusercontent.com/38521075/112951027-e68af680-9175-11eb-8d0b-4899bce12691.jpg)

**Comment by veldise** [comment]
@srust4533 
사내 시스템(b-iris.mobigen.com) 에는 4/8 에 패치가 될 예정입니다.
혹시 KOTRA 에는 더 빨리 문제 해결이 되어야 한다면 운용팀을 통하여 (가급적 메일로) 연락 부탁드립니다.
