### ISSUE TITLE
수원시청 보고서 내 IMA 오류

### ISSUE THREAD

**Issue by sanxoo** [mobigen/IRIS-BigData-Platform#2849]
## 버그 설명 ##
보고서 내 IMA 맵 삽입 시, 너무너무너무 느립니다. 표시되지 않는 경우가 더 많습니다.
아래 링크 참조하세요.

## 재현하는 방법 ##
동작을 재현하는 방법 :

http://27.101.101.188:20007/studio/exported/c42c0ca2e0a6466583a7a4c43d4769bc1891d07940ed4a27aaf7784b2d80407b

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by idaeho** [comment]
고객사에서 리뷰예정이므로, 조속한 확인&조치 부탁드립니다.

**Comment by veldise** [comment]
@big-mobigen 
수원시청에 설치된 IRIS 버전 정보를 요청합니다. 메일로 보내주시면 감사하겠습니다.

**Comment by sanxoo** [comment]
안녕하세요... DX개발1팀 박상수 책임입니다.

제가 버전까지는 잘 모르고요...

직접 설치하신 기술지원팀 강준희 책임님이 알고 계십니다.

감사합니다.


2021년 3월 31일 (수) 오전 9:34, 최영철 ***@***.***>님이 작성:

**Comment by veldise** [comment]
@sanxoo 
아, 책임님께 요청한게 아니고 운용팀에 요청한겁니다. big-mobigen 계정이 운용팀(기술지원팀)입니다.

**Comment by rhcpn** [comment]
@veldise @almalibreolo2 수원시 IMA 버전은 105.1.2.181:32500/iris-map-analyzer:v2.20210120.0-782fc4c 입니다.

**Comment by anhm** [comment]
해당 이슈를 해결 해 두었습니다.
확인 부탁 드립니다.

자세한 내용은 메일로 공유 드리겠습니다.
