### ISSUE TITLE
오래된 IRIS 교육 동영상을 실무에 사용 가능하도록 제작 의뢰

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#2854]
## 버그 설명 ##
2019년 유투브에 올라온 IRIS 소개동영상은 예전것이라서, 상용 과제에서 교육이나 홍보용으로 사용이 불가합니다.
IRIS 신규버전에 맞는 동영상이 필요합니다.

**내용은 사용자가 동영상을 보고, 쉽게 데이터를 IRIS에 올리고, Analyzer로 분석해보고, Studio로 시각화하고, IMA로 지도 시각화하여서, 웹에 게시하고, 타인에게 공유하는 스토리로 제작 부탁드립니다. 가급적 화면 자막과 음성(나레이션)도 같이 더빙 부탁드리겠습니다**.

필요한 프로젝트는 아래와 같습니다.
**LH 빅데이터, 교통 빅데이터, 수원시 빅데이터, 국토부 통합채널, 서초구 빅데이터, SKB NMS+, 도로공사, 밸류링크유 및 하반기 예정 프로젝트 등 다수**입니다.

**필요기한은 2021년 6월 이전에 부탁드립니다.**

(참고 : 2019년 IRIS 소개동영상 https://www.youtube.com/watch?v=zPciyv-Focs )

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3426052/113078363-e9d1c100-920d-11eb-9430-0303b3be47c6.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by sunghoon** [comment]
본 이슈는 깃헙이 아닌 별도의 사항으로 다루겠습니다.
