### ISSUE TITLE
[수원시] 전사 차원 IRIS Analyzer 동영상 설명서 제작 건의

### ISSUE THREAD

**Issue by sanxoo** [mobigen/IRIS-BigData-Platform#2857]
## 기능 요청 ##
고객 사이트 여러 곳에서 동영상 설명서를 요청하고 있는 것으로 알고 있습니다.
사이트 별로 동영상을 제작하는 것은 비효율적이기도 하고, 잘못된 내용을 포함할 수도 있을 것 같습니다.
전사 차원에서 IRIS Analyzer 동영상 설명서를 제작하였으면 좋겠습니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by sunghoon** [comment]
관련 내용은 내부 논의 중에 있습니다. 해당 사항은 별도로 다루고 있어 본 이슈는 닫겠습니다.
