### ISSUE TITLE
[수원시] IRIS studio 보고서 막대그래프 글씨 표출 이슈, 이미지 캡처 IMA 표출 이슈

### ISSUE THREAD

**Issue by juunho** [mobigen/IRIS-BigData-Platform#2858]
## 버그 설명 ##
보고서 막대 그래프 기능 사용 시 간격이 좁아 공간이 없으면 글씨가 아예 표출이 안됩니다.
수원시에서 가로 스크롤이 생기지 않는 보고서를 요청해서 그래프 크기를 더 늘릴 수 없는 상황입니다.
포털 및 시장실 화면에 띄워야 하는 보고서라 모든 수치가 글씨로 표출되어야 합니다.

또한 이미지 캡쳐 기능을 사용할 시 IMA 부분이 아예 표출되지 않습니다.

![image (5)](https://user-images.githubusercontent.com/81394769/113268077-f93a3280-9311-11eb-87ff-7b9bf10b971e.jpeg)

**Comment by veldise** [comment]
@clzls1gh 
어떤 위치에 어떤 글씨가 나오지 않는건가요? 첨부하신 스크린샷으로 보기에는 전부 나오는 것 같습니다.

**Comment by clzls1gh** [comment]
기관별 예방접종 진행현황 (명) - 고위험 의료기관 위치에 두번째 막대 수치가 생략되었습니다

**Comment by veldise** [comment]
![image](https://user-images.githubusercontent.com/3411842/113270021-05bf8a80-9314-11eb-920b-94743e6e8c91.png)

**Comment by sunghoon** [comment]
@veldise 레이블 부분은 확인하신것 같고, IMA 지도 표기 되지 않는 부분(회색으로 표기)도 같이 확인 후 정보를 공유 바랍니다.

**Comment by veldise** [comment]
@sunghoon @clzls1gh 
이미지 캡처 기능 사용시 IMA 가 표기되지 않는 것은 IMA 뷰어가 iframe 이라서 그렇습니다.

**Comment by rhcpn** [comment]
해당 이슈는 라벨 부분은 패치가 완료 되었으며, 캡쳐 부분은 현재 기술적으로 처리가 어렵다고 담당자에게 따로 내용 공유 하였기에 close 합니다.
