### ISSUE TITLE
[국토부] IMA: Geojson 표시 안됨

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#2863]
## 버그 설명 ##
IMA에서 Geojson정보를 가지고 있는 데이터모델(KORMAP_SOUTH_SIGUNGU)을 조회하여 OSM에 표시하려할때 표시안됨.
보고서 자체 OSM을 사용하면 정상적으로 표시됨.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
IMA 데이터 추가
![image](https://user-images.githubusercontent.com/7067615/113555173-6b25bb00-9635-11eb-9d08-7d3eee1e09a5.png)

IMA 레이어 추가(Geojson 표시 안됨)
![image](https://user-images.githubusercontent.com/7067615/113555295-ad4efc80-9635-11eb-90a4-e941814ccfa2.png)

보고서 지도 데이터 설정
![image](https://user-images.githubusercontent.com/7067615/113555535-0a4ab280-9636-11eb-8da5-4b830ce61907.png)

보고서 지도 표시(Geojson 정상 표시)
![image](https://user-images.githubusercontent.com/7067615/113555634-35350680-9636-11eb-8467-c84dd424c6aa.png)

![image](https://user-images.githubusercontent.com/7067615/113555659-3fef9b80-9636-11eb-967b-68408da8da5e.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
현재 IMA의 지도 위 표현 방식은 GeoJson을 사용 하고 있습니다.
GeoJson은 내부 coordinat값을 **경도/위도**로 표시 해야 합니다. 화면상에 표시된 데이터를 보면 **위도/경도**로 데이터가 추가되어 있는것으로 보입니다. 

참고로 Studio에서 제공하는 지도는 **위도/경도**로 넣어야 동작을 하는 문제가 있었고 아직 수정 전 입니다. 
따라서 IMA를 사용하시려면 현재 데이터를 **경도/위도**로 변경 해주셔야 할것 같습니다.
