### ISSUE TITLE
[NMS+] IRIS 데이터 시간 설정 옵션 추가의 건  

### ISSUE THREAD

**Issue by idaeho** [mobigen/IRIS-BigData-Platform#2865]
## 기능 요청 ##
* [IRIS] studio 의 시간설정 기능 검토 OR 사용 가이드 요청 #238
   * https://github.com/mobigen/NMSplus/issues/238
   * NMS+ 에서 트래픽 모니터링시 지난주 같은 요일 트래픽을 비교하는 경우가 많아서 지난주 트래픽 chart 를 만들려고 하는데
기간 선택에 번거로움이 있습니다.
      * studio 에서 데이터 설정시 시간 설정 옵션에 "지난주(일주일전)" 추가 가능하신지 검토 부탁드립니다.
      * ![image](https://user-images.githubusercontent.com/3426052/113643682-cf8c5d00-96bd-11eb-9d47-7b034e1376e5.png)

      * 최근 24시간 데이터와 지난주 데이터를 하나의 chart 로 만들고 싶은데 혹시 방법이 있으면 가이드 부탁드립니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@idaeho 
'이전 주' 항목을 선택하면 직전주 일요일~토요일을 범위로 지정할 수 있습니다.
ex) 오늘: 4/6(화), '이전 주': `2021/03/28 00:00:00 ~ 2021/04/04 00:00:00`

혹시 '지난 7일'을 말씀하시는 것이라면 추가를 해야하며 가능합니다.
ex) 오늘: 4/6(화),
지난 7일: `2021/03/23 00:00:00 ~ 2021/03/30 00:00:00`
최근 7일: `2021/03/30 00:00:00 ~ 현재`

**Comment by rhcpn** [comment]
위의 요구 사항은 기능 추가 없이 다음과 같이 진행 하여 구현 가능합니다. (조금 어렵습니다 ..)

1. 데이터객체의 기간을 기간설정 컴포넌트에서 출력하는 변수로 참조하도록 합니다.
2. X축 날짜에 해당하는 데이터를 생성 합니다. 이때 날짜는 최근 7주일을 그대로 표시 하면 됩니다.
- X축 날짜를 만드는 방법은 기간을 이용하여 일주일치 날짜를 뽑아내야 하므로 일반적인 방법으로는 어렵습니다. 쉽게 접근하는 방법은 미리 날짜 테이블을 생성 하는 것입니다. (이젠 MySQL에서 날짜로 Pivot을 하기 위해 날짜만 들어있는 참조 테이블 생성과 유사) 아래 이미지는 샘플입니다.
![image](https://user-images.githubusercontent.com/11566844/113683292-fe76f300-96fe-11eb-9be7-1d61d7ec0ec9.png)
3. 출력하고자 하는 지난 일주일 데이터 모델을 기간으로 쿼리하여 merge 문을 이용하여 날짜 컬럼과 합칩니다.
4. 출력하고자 하는 지지난 일주일 데이터 모델은 현재 설정된 기간에서 7일을 빼는 nunjuck 문법을 사용합니다. 이를 이용하여 또다른 데이터를 Query 하여 또다시 merge 합니다.
5. 위와 같이 수행 하면 "날짜" | "최근 7일" | "이전 7일" 3개의 컬럼 데이터를 추출 할수 있으며 이를 이용하여 차트에 X축 하나 Y축 두개로 설정 가능힙니다.
6. 아래는 위 설명에 대한 sample dsl 입니다.
```
*

| merge left ( PM_LTER_1H_MME_KPI
    start_date=${date_time.startDate}
    end_date=${date_time.endDate}
     EQUIP_ID  = '${combo_equip}'
) as CUR on CDATE = CUR.COL_DT

| merge left ( PM_LTER_1H_MME_KPI
start_date=${moment(date_time.startDate, 'YYYYMMDDHHmmss').add(-7, 'd').format('YYYYMMDDHHmmss')}
end_date=${moment(date_time.endDate, 'YYYYMMDDHHmmss').add(-7, 'd').format('YYYYMMDDHHmmss')}  
    EQUIP_ID  = '${combo_equip}'
) as OLD on PDATE = OLD.COL_DT

| typecast CDATE timestamp "YYYYMMDDHHmmss"

 | case when CUR_ATT = 0 then 0 when CUR_ATT is null then 0 otherwise (CUR_SUCC/CUR_ATT)*100 as CUR_RATE 

| case when OLD_ATT = 0 then 0 when OLD_ATT is null then 0 otherwise (OLD_SUCC/OLD_ATT)*100 as OLD_RATE 

| round [2,2] col=[CUR_RATE, OLD_RATE]

| fields CDATE as 날짜
, CUR_RATE  as 
 MME_성공률(현재)
, OLD_RATE  as 
MME_성공률(전주)
```
