### ISSUE TITLE
[DSL] lag, lead 수행시 정렬 기준 변경 건

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2866]
## 버그 설명 ##
Analyzer, Studio에서 조회된 데이터를 sort로 정렬을 하고 lag 또는 lead를 사용하는 경우 앞서 지정한 sort로 되지 않고 다른기준-내부기준인지는 모르겠음-으로 정렬 되어 lag 또는 lead가 수행됨

## 재현하는 방법 ##
동작을 재현하는 방법 :
* | ...
| sort A, -B
| lag C by B

## 예상한 행동 ##
lag 또는 lead 앞에서 수행된 정렬 상태로 lag 또는 lead 가 수행됨

## 스크린샷 ##
* Analyzer에서 sort 만 수행한 경우
![001_sort](https://user-images.githubusercontent.com/13842947/113661460-1b043280-96e1-11eb-9ab7-d8229e8b7510.PNG)

* Analyzer에서 sort 후 lag를 수행한 경우
![002_lag](https://user-images.githubusercontent.com/13842947/113661467-1f305000-96e1-11eb-90df-e2454aab6f83.PNG)

* Analyzer에서 sort 후 lead를 수행한 경우
![003_lead](https://user-images.githubusercontent.com/13842947/113661475-235c6d80-96e1-11eb-8d0b-e13fd4ca9d81.PNG)

* Studio의 경우
![004_total](https://user-images.githubusercontent.com/13842947/113661491-28212180-96e1-11eb-85a5-a591819d245a.PNG)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
각 명령어는 독립적입니다.
앞에서 sort 를 하였다고 해서 다음 명령어에서 해당 기준을 사용하지는 못합니다.

현재 lead, lag 의 경우 `by` 로 지정한 컬럼을 ascending 으로 sort 한 뒤 해당 정렬 기준으로 앞,뒤 데이터를 가져오도록 하고 있습니다.

**Comment by shinwoonsun** [comment]
답변 감사합니다.

그렇다면 제가 요청드린 내용과 같이 특정 결과에 대해 lead나 lag 명령어를 사용하려 하지만 앞에서 수행된 결과에 대해 lead나 lag를 사용할 수 없다면 해당 명령어의 사용 방법이 제한적일텐데 lead나 lag를 앞선 결과에 대해 사용하려면 어떻게 해야 하나요?

**Comment by seungfwani** [comment]
구두로 설명되었고, 해결되었다고 보고 닫습니다.
