### ISSUE TITLE
[수원시] IRIS Studio CSV 다운로드 오류

### ISSUE THREAD

**Issue by juunho** [mobigen/IRIS-BigData-Platform#2867]
## 버그 설명 ##
데이터 분석 - 검색에서 쿼리 적용 후 결과 CSV 다운로드와

![csv오류1](https://user-images.githubusercontent.com/81394769/113662572-4daf2a80-96e3-11eb-97f3-7a177c50cf6a.PNG)
![csv오류2](https://user-images.githubusercontent.com/81394769/113662581-54d63880-96e3-11eb-9757-5ea4edbaac7a.PNG)

보고서 내 옵션인 다운로드 기능을 통한 CSV 다운로드 시 오류가 발생합니다.
![csv오류3](https://user-images.githubusercontent.com/81394769/113662590-599aec80-96e3-11eb-9f8d-ed615e4391ef.PNG)
![csv오류4](https://user-images.githubusercontent.com/81394769/113662594-5c95dd00-96e3-11eb-8bb3-280437427f50.PNG)

현재 내부 행정망 사용 중입니다.

**Comment by anhm** [comment]
@juunho 
한가지 확인을 부탁 드립니다.
IRIS가 설치된 서버에 접속이 가능하시면,
```
kubectl get service -n iris angora-svc
```
와 같은 실행 결과를 공유 부탁 드립니다.

**Comment by juunho** [comment]
@anhm

![캡처11](https://user-images.githubusercontent.com/81394769/113812268-c62bef00-97a8-11eb-9d0e-945e369db765.PNG)

**Comment by anhm** [comment]
해당 기능은 수정 반영되었습니다.
확인 부탁 드립니다.

**Comment by juunho** [comment]
@anhm 
수원시에서 사용 결과 다운로드는 해결됐는데 한글이 깨져서 보인다고 합니다

![csv캡처](https://user-images.githubusercontent.com/81394769/114799884-a2356280-9dd3-11eb-92db-970c0cec6580.PNG)

**Comment by anhm** [comment]
@juunho 

해당 문제의 경우 인코딩 이슈가 있는 상태입니다.
현재 IRIS에서 제공되는 인코딩은 UTF-8 인 상태입니다. 따라서 메모장 등으로 열 경우 글자가 정상적으로 보이게 됩니다.
excel에서는 기본적으로 cp949인코딩을 지원하고 있기 때문에, 더블 클릭으로 csv를 여는것이 아닌 엑셀의 메뉴인 [데이터]-[텍스트에서 가져오기] 메뉴를 선택하여 인코딩을 UTF-8로 맞추시면 데이터를 정상적으로 가져올수 있습니다.

만약 해당 방법으로는 사용을 할수 없을 경우에는 IRIS를 최신버전으로 패치를 진행해야 하는 상태입니다.
최근 버전에서는 해당 문제를 해결하기 위해 cp949로 다운받을수 있도록 기능이 패치된 상태입니다.

따라서 패치 가능 여부 등을 파악해서 패치를 진행하거나 위의 설명처럼 파일을 open해야 하는 상태입니다.
패치를 할 경우에는 현재 수원시에 배포되어 있는 버전에 따라 패치의 범위가 달라질수 있습니다.

**Comment by juunho** [comment]
@anhm

확인했습니다 감사합니다.
