### ISSUE TITLE
[업무관리:일일업무로그]일일업무로그 오류

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2868]
## 버그 설명 ##
{ 업무관리의 일일업무로그 내용출력 오류.}

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. http://b-iris.mobigen.com/ 로그인
2.업무관리 > 팀원 > 일일로그조회 선택
3. 기간설정 후 검색 하면 오류 문구만 출력
4. "
 {"status": 6, "messages": "interface execute exception (datasource: MYSQL5, err: (2013, 'Lost connection to MySQL server during query (timed out)')) "}"
## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
[
![000001](https://user-images.githubusercontent.com/899539/113671486-5c9cd980-96f1-11eb-8064-82d25719364f.JPG)
](url)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
현재 해당 쿼리를 수행하는 서비스에서 DB 에 연결 할 때 connection timeout 이 5초로 적용 되어 있습니다.
하지만 해당 DB 에서 직접 쿼리를 수행해보니 5초 이상 수행 시간이 걸립니다. 즉, DB 의 성능이 느려서 발생한 이슈입니다.

![Screen Shot 2021-04-08 at 4 44 28 PM](https://user-images.githubusercontent.com/46172579/113987730-b33d1b80-9889-11eb-88c7-7da828f77c81.png)


@anhm 팀장님 dsms 의 connection timeout 설정을 수정하면 동작이 가능할 것으로 보입니다.

**Comment by seungfwani** [comment]
처리 완료 되었습니다.
![Screen Shot 2021-04-08 at 4 53 44 PM](https://user-images.githubusercontent.com/46172579/113989040-02378080-988b-11eb-8aef-b4dd3b063054.png)
