### ISSUE TITLE
[업무관리:일자별 근무시간 트랜드 그래프]마지막 그래프 누락오류

### ISSUE THREAD

**Issue by jmlee** [mobigen/IRIS-BigData-Platform#2869]
## 버그 설명 ##
{ 아이리스 업무관리 보고서중에 일자별 근무시간 트랜드 그래프 에서 마지막 그래프 미표시 문제}

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 아이리스 로그인
2. 업무관리 > 팀원 > 프로젝트분석
3. 기건 설정 후 검색하면 나오는 항복중에 일자별 근무 시간 트랜드 그래프가 나오는데 마지막 날짜의 그래프가 누락됩니다.
4. 전에 마지막 날짜 데이터가 나오지 않아서 수정 요청을 해서 총근무시간은 포함되어 나오는데 트랜드그래프는  누락되어표시됨.

## 예상한 행동 ##
{아래 그림에서 기간 선택은 3월 31일까지 했지만 마지막 그래프를 보면 3월30일 입니다. }

## 스크린샷 ##
{ [}](url
![000002](https://user-images.githubusercontent.com/899539/113672927-4728af00-96f3-11eb-954b-e10e12a85695.JPG)
)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seungfwani** [comment]
IRIS 는 기간조회시 `시작시간 <= x < 끝시간` 으로 처리하고 있습니다.
오류가 아니라고 판단됩니다.

**Comment by seungfwani** [comment]
정상 동작으로 판단되기 때문에 이슈를 닫도록 하겠습니다.

해당 문제에 대한 추가 사항이 있으시면 reopen 하시고 코멘트 해주시면 됩니다.
