### ISSUE TITLE
[DSL] checkpoint 명령어에서  KEY 를 대문자로 사용하면 에러납니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2872]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정

```
정상동작
*  | checkpoint delete key=f66084f7-cb99-4c53-9fc8-10ba7f1612a5

에러
*  | checkpoint delete KEY = f66084f7-cb99-4c53-9fc8-10ba7f1612a5
```

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
<img width="416" alt="스크린샷 2021-04-14 오전 9 59 49" src="https://user-images.githubusercontent.com/5126497/114639186-2a4e3600-9d08-11eb-8f05-85dee5b74827.png">

처럼 저장된 컬럼명이 대문자 KEY 로 나와서 대문자로 사용했는데, 그러면 에러가 나네요.

**Comment by seungfwani** [comment]
@jheok318 파싱에러 입니다. 수정 필요합니다.

**Comment by seungfwani** [comment]
해결되어 닫습니다.
