### ISSUE TITLE
[Studio] 시계열 분포 x축 값 중복 출력

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2875]
## 버그 설명 ##
시계열 분포의 특정 x축 값이 중복으로 출력됩니다.

![image](https://user-images.githubusercontent.com/5077625/114818498-db32fe80-9df6-11eb-9732-15d1008ff0c2.png)
- x축 값 SE1은 중복으로 출력되나 SEA는 1개로 출력됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

보고서 url: http://b-iris.mobigen.com:80/studio/exported/d33d159246194d3099497701f17b45d59f16a7fb6dc848b69a35dd37061af8ad

데이터모델: BATTING_NEW
검색어: * | fields TEAMID, G | where TEAMID like 'SE%' | where G>50 and G<100

**Comment by veldise** [comment]
@euhyesun 
DSL 명령어를 이용하여 집계 처리를 해야만 차트가 정상적으로 그려집니다.

**Comment by euhyesun** [comment]
@veldise 위의 차트는 별도의 연산이 필요하지 않습니다. 
![image](https://user-images.githubusercontent.com/5077625/114823788-f1dd5380-9dfe-11eb-966c-ce1091ceaf7a.png)
x축 값 SEA처럼 SE1도 하나로 표현되면 될 것 같습니다.
확인 부탁드립니다.

**Comment by veldise** [comment]
@euhyesun 
x축의 경우에는 말씀하신 처리를 DSL로 하셔야 합니다.

**Comment by veldise** [comment]
@euhyesun 
확인했습니다. 4/22 패치에서 해결하겠습니다.
