### ISSUE TITLE
[수원시] 지표 검색 후 엑셀 다운 기능 문제

### ISSUE THREAD

**Issue by juunho** [mobigen/IRIS-BigData-Platform#2879]
## 버그 설명 ##

현재 지표 내 엑셀 다운 기능에서 검색이 적용되지 않습니다.

화면에서는 검색이 적용되나, 다운로드 된 엑셀 파일은 검색이 적용되지 않고 전체 목록입니다.

## 스크린샷 ##

![전체](https://user-images.githubusercontent.com/81394769/115202561-7a2a6400-a131-11eb-86f2-5faf1335821a.PNG)

![검색](https://user-images.githubusercontent.com/81394769/115202590-81ea0880-a131-11eb-952e-f6857367802c.PNG)

![엑셀](https://user-images.githubusercontent.com/81394769/115202742-ac3bc600-a131-11eb-840f-3bfc22530190.PNG)

**Comment by veldise** [comment]
@juunho 
좌측 트리뷰 등으로 미루어볼 때 IRIS로 구현된 페이지가 아닌 것 같습니다.
확인이 필요합니다.

**Comment by juunho** [comment]
@veldise 
부서 문의 결과, 부서 내 개발 건으로 확인했습니다. 
이슈 닫도록 하겠습니다.
