### ISSUE TITLE
[Studio] 가로막대형 차트 정렬

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2882]
## 버그 설명 ##
가로막대형 차트 정렬시 결과가 반대로 출력됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
보고서명: 가로막대형_20210421
데이터모델: EDU_CHART_SEOUL_MELT_FIRE_CAUSE
검색어: `* | stats sum(CNT) as 합계 by FIRE_CAUSE | top 5 -합계 | sort -합계`
![image](https://user-images.githubusercontent.com/5077625/115496179-107e9700-a2a4-11eb-8054-58605caaef16.png)
 - 합계 값이 오름차순 정렬

## 예상한 행동 ##
![image](https://user-images.githubusercontent.com/5077625/115496252-3dcb4500-a2a4-11eb-933d-dcfa7fe3412d.png)
(검색어: `* | stats sum(CNT) as 합계 by FIRE_CAUSE | top 5 -합계 | sort 합계`)

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@euhyesun 
현재 가로축(x축)이 하단에 있기 때문에, 세로축(y축)의 순서는 하단 -> 상단이 됩니다. 세로축이 숫자일 경우를 상상해보시면 됩니다.
세로막대의 경우에는 세로축(y축)이 좌측에 있기 때문에, 순서가 좌단 -> 우단이 됩니다.

따라서 정상입니다.

만약 축을 반대로 그리고 싶다면 '축 반전' 옵션을 이용하시면 됩니다.

![image](https://user-images.githubusercontent.com/3411842/115511857-4c255b00-a2bc-11eb-990c-db438ecb97bc.png)
