### ISSUE TITLE
[Studio] 라벨의 사이즈가 자동으로 작아짐

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2891]
## 버그 설명 ##
크롬에서 화면 크기를 75%이하로 설정을 했을때 라벨을 생성하고 난 후 라벨에 텍스트입력 상태에서 키보드 또는 마우스 클릭을 할때마다 좌우 사이즈가 작아짐 

## 재현하는 방법 ##
1. 보고서 라벨 생성
2. 마우스로 라벨을 더블 클릭(이때도 작아짐)
3. 라벨에 텍스트를 입력할 수 있는 상태가 되었을때 키보드의 아무키를 누르거나 마우스의 왼쪽 버튼을 클릭
4. Action이 벌어질 때마다 라벨의 좌우 크기가 작아짐

## 예상한 행동 ##
사이즈가 작아지면 안됨

## 스크린샷 ##
[라벨 생성]
![생성](https://user-images.githubusercontent.com/13842947/116533602-888c3300-a91c-11eb-9690-b37d262be25e.PNG)

[라벨이 더이상 작아지지 않는 상태]
![생성 후 시험](https://user-images.githubusercontent.com/13842947/116533630-92ae3180-a91c-11eb-883c-9d6334c05af7.PNG)

**Comment by rhcpn** [comment]
해당 이슈는 확인 결과 브라우저 확대/축소 에서 축소 상태일때 발생하는것으로 확인 되었습니다.
![image](https://user-images.githubusercontent.com/11566844/116543885-64831e80-a929-11eb-9363-880dc1f54e27.png)
