### ISSUE TITLE
[Studio] 캔버스와 컴포넌트 사이즈 및 이동 포인트 값 통일화 요청

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2894]
## 기능 요청 ##
캔버스와 컴포넌트의 사이즈는 px 단위로 조정을 할 수 있지만 이동은 px 단위가 아닌 block(캔버스의 눈금선과 같은 박스-px로 10x10) 단위로 되어 있으며 이동시 캔버스의 block의 상단 또는 좌측 기준 정렬이 되기때문에 컴포넌트 조정에 어려움이 있음 관리 단위를 px이나 block단위로 통일화 요청

![001](https://user-images.githubusercontent.com/13842947/116639362-5b369800-a9a3-11eb-9f7d-04f8a8206df5.jpg)

## 원하는 솔루션 설명 ##
사이즈와 이동 포인트를 px의 자유설정이 된다면 캔버스의 이동 포인트도 동일하게 하거나, 아니면 10x10 px 단위로 고정

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by veldise** [comment]
@shinwoonsun 
객체(컴포넌트)의 드래그 이동을 1px 로 하면 드래그로 깔끔한 위치를 잡기 대단히 어려울 것입니다.
우측 크기 설정에서 단위를 10px(block) 로 하게 되면 미세한 위치 조정이 불가능하게 됩니다.

이 부분은 위와 같이 의도적으로 개발된 것입니다.
어떤 상황에서 조정에 어려움이 있는지 보다 상세하게 말씀 부탁드립니다.

**Comment by shinwoonsun** [comment]
현재 캔버스에서 컴포넌트의 이동의 간격이 10px인 것으로 보이는데
답변을 주신 내용으로는 미세한 조정도 안될 뿐더러 
오히려 사이즈를 1px 단위로 조정이 되었을 때 배치 자체에 문제가 있습니다.

**Comment by veldise** [comment]
@shinwoonsun 
다소 오해를 하고 계신것 같은데, 미세한 조정은 우측 패널 쪽에서 하시면 됩니다.
배치 자체에 문제가 있다는건 무슨 말인가요?

**Comment by veldise** [comment]
현재 입력 단위:
- 마우스 드래그 / 키보드 화살표 키로 이동: 10 px (block)
- 설정 패널 > 객체 탭 > 크키/위치 설정: 1 px

다음 2가지 요건으로 정리되었습니다.
- 드래그로 위치 조정시 객체간 Snap 기능
- 좌상단(left-top)이 아닌 우하단(right-bottom) 기준의 위치 설정 방법
