### ISSUE TITLE
[Discovery] 데이터모델에 연결할 HDFS 대상데이터 찾아보기를 실행하는경우 root 디렉토리가 열림

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2900]
## 버그 설명 ##
Discovery에서 데이터모델에 연결할 연결정보를 HDFS로 선택하고 대상데이터 찾아보기를 실행하는 경우 상용자의 디렉토리가 아닌 root 디렉토리가 열려서 본인의 디렉토리를 찾아서 이동해야함

## 재현하는 방법 ##
1. Discovery 선택
2. 데이터모델 선택
3. 새모델 또는 기존의 데이터모델의 편집 선택
4. 연결정보를 HDFS와 HDFS_180을 선택
5. 대상데이터의 찾아보기 선택

## 예상한 행동 ##
IRIS에 접속한 사용자의 디렉토리가 열려야함

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@shinwoonsun 
찾아보기 버튼 등으로 파일 브라우저를 팝업 창으로 열었을때, 처음 디렉토리 경로는 연결정보를 따라갑니다.
연결정보에 설정된 path 값이 `/` 혹은 `/root`가 아닌지 확인해주세요.

![image](https://user-images.githubusercontent.com/3411842/117251788-136eaf80-ae80-11eb-9960-fbf557c267e9.png)

**Comment by shinwoonsun** [comment]
새로 새모델을 만들때 찾아보기로 파일 브라우저를 열면 
![path](https://user-images.githubusercontent.com/13842947/117386776-6d27b600-af22-11eb-92cc-49bcabf6087c.PNG)
로 열립니다.

**Comment by jheok318** [comment]
1. Discovery 선택
2. 데이터모델 선택
3. 새모델 또는 기존의 데이터모델의 편집 선택
4. 연결정보를 HDFS와 HDFS_180을 선택
  => 이때 HDFS에 저장 되있는 HDFS_180은 사용자가 root로 저장돼 있는 연결정보를 선택했습니다.
5. 대상데이터의 찾아보기 선택 
  => root의 디렉토리 경로가 열리는게 맞습니다.

이를 해결하기 위해선 관리자(root)가 새로운 연결정보(NEW)를 추가로 입력해서 4번의 방식대로 HDFS선택 => HDFS_NEW 를 선택하면 사용자가 원하는 디렉토리로 부터 시작하게 할 수 있습니다.

**Comment by veldise** [comment]
@shinwoonsun 
말씀하시는 파일 브라우저 디렉토리 경로는 계정 정보와는 무관하게 동작합니다.

**Comment by shinwoonsun** [comment]
@jheok318 @veldise 
그렇다면 현재 IRIS는 사용자에 대한 관리 정책이 사용자 등록과 해당 사용자의 STORAGE 연결 설정을 따로해야 한다는 것인가요?

**Comment by veldise** [comment]
@shinwoonsun 
네, 지금 현재 버전에서는 그렇습니다.

연결정보는 시스템에 직접 연결할 수 있는 민감한 정보이므로 시스템(사이트) 관리자가 등록/관리하여 사용자에게 제공하는 것으로 개발되었으나,
사용자가 직접 연결정보를 등록하고 싶다는 요구사항을 수용하여 사용자가 직접 등록/관리할 수 있고
권한 설정 기능을 통해 다른 사용자에게 공유도 가능하도록 변경되었습니다.

b-iris.mobigen.com 사이트의 root 경로(`/`)로 설정되어있는 연결정보의 경우에는 위 변경 내용 이전에 만들어진 연결정보라서 그렇습니다.

말씀하신대로 IRIS 에서 자동으로 원격 저장공간(HDFS/MinIO)을 제공하는 부분이 있는데
연결정보를 위와 같이 변경하는 과정에서 이 부분이 잘 검토가 되지 않은 것 같습니다.

**Comment by veldise** [comment]
@shinwoonsun 
Discovery 파일 브라우저는 연결정보가 아니라 서버 설정에 따라 동작해서 그렇습니다.

**Comment by shinwoonsun** [comment]
@veldise 
그렇다면 IRIS의 원격 저장공간(HDFS/MinIO) 관리 기능 재정립이 필요하다는 말씀인거죠?

**Comment by veldise** [comment]
@shinwoonsun 
원격 저장공간 관리 기능보다는, Discovery / Analyzer / Studio 에서 원격 저장공간의 사용자 데이터를
쉽고 편하게 접근할 수 있도록 기능 개선이 필요하다고 생각합니다.
