### ISSUE TITLE
[Discovery] 데이터모델에 연결할 엑셀데이터의 첫번째 행의 데이터가 숫자로 되어 있는 경우 불러오기 실패가 발생

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2901]
## 버그 설명 ##
Discovery의 파일브라우저에 올린 Excel 파일의 column 명으로 사용할 첫번째 row의 데이터가 숫자로 되어있는 경우 모델의 연결 대상데이터에서 불러오면 실패가 발생하나 csv인 경우는 정상 처리

## 재현하는 방법 ##
1.엑셀파일의 첫번째 row에 숫자를 입력
![raw](https://user-images.githubusercontent.com/13842947/117253003-ab20cd80-ae81-11eb-9880-81bd7a7d96f7.PNG)

2. Discovery의 파일 브라우저에서 파일 업로드
3. Discovery의 데이터모델에서 새모델 선택
4. 대상데이터를 1항에서 업로드한 파일을 선택
5. error 메세지 창 팝업
![error](https://user-images.githubusercontent.com/13842947/117253034-b7a52600-ae81-11eb-8435-aeb6e38c3d55.PNG)

## 예상한 행동 ##
첫번째 row가 csv 파일과 같이 숫자로만 되어있는 상태라도 데이터를 불러와야 함

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by jheok318** [comment]
현재 spark-excel의 version 변경 및 코드 수정으로 해결하려 하였으나 spark-excel library 자체적으로 컬럼명에 숫자가 입력시 에러를 발생하고 있습니다.
추후 이슈를 해결할 수 있을 시 문제를 해결하도록 하겠습니다.

**Comment by jheok318** [comment]
현재 상황은 library가 일부러 에러를 발생시키고 있는 상황이므로 버그가 아닙니다.
