### ISSUE TITLE
[Map Analyzer]  프로젝트 이름 입력/수정방법 변경 요청

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2903]
## 기능 요청 ##
b-iris.mobigen.com

새 프로젝트 생성하여 프로젝트 이름을 입력하여 저장할 때
Studio 에서는 1번 클릭하거나 연필 버튼으로 보고서이름을 편집할 수 있게 되어 있어서 1번 클릭했는데, IMA 는 더블클릭입니다. 그리고 편집할 수 있는 버튼이 보이지 않습니다.
보고서 이름 편집과 동일한 방법으로 이름 편집을 하면 일관성이 있어서 좋을 듯 합니다.

- 참고 : 보고서 이름 수정
<img width="371" alt="스크린샷 2021-05-06 오후 4 18 50" src="https://user-images.githubusercontent.com/5126497/117257395-c8a46600-ae86-11eb-9dc5-fc7a41b907e1.png">
<img width="233" alt="스크린샷 2021-05-06 오후 4 18 57" src="https://user-images.githubusercontent.com/5126497/117257403-cb06c000-ae86-11eb-8f3d-7745a1daedd4.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by rhcpn** [comment]
해당 부분은 저희도 인지 하고 있으며 추후 디자인 개편 시 개선 예정입니다.
