### ISSUE TITLE
[Map Analyzer]  프로젝트 목록이 나오는 처음 화면, 실행방법등이  Studio 목록, 실행방법과  같은 방식으로 동작이 되면 좋겠습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2904]
## 기능 요청 ##
b-iris.mobigen.com  demo 계정

1.  Map Analyzer 의 실행 방법이 잠깐 해보니 2가지로 나옵니다.  -> 버튼 클릭,  더블클릭
    **더블클릭**  은  빼고 기존 IRIS 와 동일한 실행 방식을 사용하면 혼선이 없을 듯 합니다.
   -> 더블 클릭은 IRIS Analyzer 나 Studio 에서는 없는 방법입니다.  ( 버튼 클릭과 우클릭 ) 
   manual 에서는  그냥 클릭, 실행이라고만 되어 있어서 기존 IRIS 에 익숙한 사람은 시행착오를 한참 거쳐야 합니다.

2. 처음 진입 화면의 메뉴 이름과 아이콘버튼을 Studio 와 동일한 화면 구성, 아이콘으로 통일하면  사용자 입장에서는 익숙하게 시작을 할 수 있습니다.
  
- IMA
<img width="660" alt="스크린샷 2021-05-07 오전 7 19 33" src="https://user-images.githubusercontent.com/5126497/117373296-ed8bee00-af05-11eb-94ef-7e1dc4661172.png">

<img width="271" alt="스크린샷 2021-05-07 오전 7 29 43" src="https://user-images.githubusercontent.com/5126497/117373344-02688180-af06-11eb-9f2c-e588fbefb181.png">

- Studio
<img width="265" alt="스크린샷 2021-05-07 오전 7 19 59" src="https://user-images.githubusercontent.com/5126497/117373303-f2e93880-af05-11eb-8cd8-87b6cbfcee4a.png">

<img width="597" alt="스크린샷 2021-05-07 오전 7 30 40" src="https://user-images.githubusercontent.com/5126497/117373420-275cf480-af06-11eb-8129-da294e7f4bfa.png">

3.  카테고리는 Studio 와 같은 방식으로 사용하는 것인데,  관리 방법을 Studio 와 같은 방식으로 하는 것이 추후 manual 관리나 사용 측면에서 효율적입니다.
- IMA  :   카테고리관리 버튼 - 더블클릭으로 카테고리 이름 변경
<img width="283" alt="스크린샷 2021-05-07 오전 7 36 03" src="https://user-images.githubusercontent.com/5126497/117373824-f9c47b00-af06-11eb-9043-6e66b371b85f.png">
<img width="350" alt="스크린샷 2021-05-07 오전 7 35 53" src="https://user-images.githubusercontent.com/5126497/117373831-fb8e3e80-af06-11eb-8f2b-d4a8b919fc7f.png">

- Studio :  리스트에 편집 항목 클릭 - 정보변경 클릭 - 카테고리, 보고서이름 같이 변경
<img width="1172" alt="스크린샷 2021-05-07 오전 7 36 25" src="https://user-images.githubusercontent.com/5126497/117373844-01841f80-af07-11eb-8925-78ce04a7b1af.png">
<img width="384" alt="스크린샷 2021-05-07 오전 7 36 31" src="https://user-images.githubusercontent.com/5126497/117373848-02b54c80-af07-11eb-8627-a2ea0642eecb.png">

4. 프로젝트 리스트도 Studio 목록과 같은 방식으로 표현하는 게 필요해 보입니다.  사용자 대부분  studio 에서 처럼 프로젝트 수정을 하려고 **편집**  버튼을 찾거나 우클릭을 시도합니다. 
- IMA
<img width="110" alt="스크린샷 2021-05-07 오전 7 57 57" src="https://user-images.githubusercontent.com/5126497/117375466-fd0d3600-af09-11eb-8ae7-83f8b14fce7b.png">
리스트뷰 버튼으로 목록 진입
<img width="1171" alt="스크린샷 2021-05-07 오전 7 58 05" src="https://user-images.githubusercontent.com/5126497/117375487-0b5b5200-af0a-11eb-8957-9829d5cd4ec1.png">
편집하는 방법을 못 찾았습니다.
<img width="1183" alt="스크린샷 2021-05-07 오전 7 58 13" src="https://user-images.githubusercontent.com/5126497/117375491-0d251580-af0a-11eb-866f-2f3cc9163825.png">
프로젝트이름을 더블클릭해야 들어갑니다.

- Studio : 편집 - 수정으로 들어갑니다.
<img width="1201" alt="스크린샷 2021-05-07 오전 7 57 34" src="https://user-images.githubusercontent.com/5126497/117375419-e4048500-af09-11eb-9561-62ff7d794b1e.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by rhcpn** [comment]
해당 부분은 디자인 개편에 해당 하는 부분입니다. 추후 모든 서비스로 기획 방향을 통일할 예정입니다. 지적해주신 부분에 참고 할 부분은 기획에 반영 하도록 하겠습니다.
