### ISSUE TITLE
[Map Analyzer] 프로젝트보기에서 마우스나 패드 이동으로  잘못 확대/축소가 될 때, 중간에 실행을 중단하는 버튼이 필요합니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2906]
## 기능 요청 ##
b-iris.mobigen.com 

줌을 잠금하지 않은 프로젝트를 열 때, 마우스, 패드의 오동작으로 지도기 확대, 축소되면서 재실행이 됩니다.
<img width="173" alt="스크린샷 2021-05-07 오전 9 41 36" src="https://user-images.githubusercontent.com/5126497/117382080-92afc200-af18-11eb-95fb-9ec6d28b19f2.png">
- 대부분 샘플 프로젝트가 시간이 오래 실행이 되는데, 줌 잠금이 풀려 있습니다.

이 때 , 불필요한 재실행을 중간에 중단할 수 있는 버튼이 있으면 좋겠습니다.
Studio , Analyzer 의  ``실행중단``  버튼 같은 게 필요해 보입니다.

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by almalibreolo2** [comment]
5/13일에 [지도 이동시 데이터 재조회] 라는 기능이 패치되었습니다.
해당 기능으로 성능적인 부하가 있는 경우 재조회에 대한 기능을 지정할 수 있습니다.
