### ISSUE TITLE
[Map Analyzer]  마커, polygon 의 색상지정을  group 데이터로 표시되도록 기능 추가요청 ( studio 지도객체에 있는 기능입니다) 

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2908]
## 기능 요청 ##
b-iris.mobigen.com  demo계정

- 데이터모델 : EDU_INCHEON_BUS_COOR
- 내용 : 4개 버스노선의 경유 정류장을 각각 버스노선 4개 색상의 마커(원)으로 표시하기
- Studio 지도 객체에서 그린 결과
<img width="831" alt="스크린샷 2021-05-07 오전 10 50 16" src="https://user-images.githubusercontent.com/5126497/117386525-0a361f00-af22-11eb-983f-5bc896b32cdb.png">

- Studio 마커의 시각화옵션 : 노선번호는 text 형( 13-2번 이런 노선 번호가 있기 때문에) 입니다.  노선번호별로 마커 색상을 지정할 수 있습니다.

<img width="384" alt="스크린샷 2021-05-07 오전 10 49 00" src="https://user-images.githubusercontent.com/5126497/117386871-9ea08180-af22-11eb-937d-86f4b6a265f0.png">

<img width="368" alt="스크린샷 2021-05-07 오전 10 50 01" src="https://user-images.githubusercontent.com/5126497/117386553-16ba7780-af22-11eb-8c8b-caf72dc046cb.png">

-  IMA 결과는 그룹별 색상 지정이 안됩니다.
- 색상 채우기 속성데이터가 numeric 만 지원하고 있습니다.  즉 그룹별 마커 색상 지정을 할 수 없습니다.
<img width="1193" alt="스크린샷 2021-05-07 오전 10 27 21" src="https://user-images.githubusercontent.com/5126497/117385873-d5759800-af20-11eb-9489-18bce09ec924.png">

<img width="254" alt="스크린샷 2021-05-07 오전 10 42 52" src="https://user-images.githubusercontent.com/5126497/117386008-14a3e900-af21-11eb-8be6-3c9c3be1c270.png">

## 원하는 솔루션 설명 ##
{ 원하는 기능에 대한 명확하고 간결한 설명 부탁드립니다 }

## 고려한 다른 대안 ##
{ 고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명 부탁드립니다. }

## 기타 ##
기능 요청에 대한 다른 의견 또는 스크린샷을 여기에 모두 추가 부탁드립니다.

**Comment by almalibreolo2** [comment]
IMA에서는 한개의 데이터 모델로 여러가지 레이어를 조합하여 데이터를 조회할 수있습니다.
또한 스냅샷 기능을 이용해서 studio와 같은 기능을 구현가능합니다.
