### ISSUE TITLE
[DSL] stats 수행 후 출력(조회)되는 데이터의 정렬 기준은 무엇인가요? 

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2910]
## 버그 설명 ##
stats 수행 후 출력(조회)되는 데이터의 정렬 기준은 무엇인가요? 

## 재현하는 방법 ##
아래의 그림과 같이 우측의 테이블이 좌측의 데이블 데이터를 stats max(column_name) as column_name을 수행시킨 결과입니다. (좌/우측  모두 sort나 top을 사용하지 않은 상태)
그런데 우측의 테이블은 어떤 기준으로 정렬이 수행된 것 인지를 모르겠습니다. 
물론 sort를 사용하여 정렬을 하면 되겠지만 기본적인 정렬 기준을 확인 하고 싶습니다.

![계산 후 정렬기준](https://user-images.githubusercontent.com/13842947/117401238-2e542900-af3f-11eb-890a-5c6894f0f048.PNG)

## 예상한 행동 ##
정렬 조건을 설정하지 않은 경우는 출력(조회)되는 데이터 기준 첫번재 컬럼, 두번째 컬럼...순으로 정렬을 하거나 stats에서 수행하는 컬럼의 순으로 정렬

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by jheok318** [comment]
@shinwoonsun 
사용한 데이터 모델명을 알려주실수 있으신가요?

**Comment by shinwoonsun** [comment]
@jheok318 
1. 데이터모델 : ONSULTATION_PHONE_RAW
2. 사용 DSL문
*
| where date >= '${date_time_picker_1}' and date <= '${date_time_picker_2}'
| stats avg(answer) as answer, avg(loss) as loss by date

**Comment by seungfwani** [comment]
stats 그룹에 정렬 기준은 없습니다.
stats 명령어의 그룹의 의미는 각 그룹별 통계를 계산 하는 것입니다.

**Comment by shinwoonsun** [comment]
@seungfwani 서승환책임님 그러면 데이터모델을 stats 처리 후에는 정렬이되는 기준이 없다는 것인가요? stats에서 재일 처음 주어진 컬럼의 결과를 오름차순으로 정렬하거나 기준(by)로 사용된 컬럼을 기준으로 정렬이 되게 할 수는 없는 것인가요?

**Comment by seungfwani** [comment]
`stats ... | sort ... ` 구문으로 사용하시면 정렬 가능합니다.
