### ISSUE TITLE
[Map Analyzer]  17개 시도 경계(polygon) 을 그리는데, 20 ~ 60초 정도 걸립니다.(studio 지도는  1-3초 이내)

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2911]
## 버그 설명 ##
b-iris.mobigen.com demo 계정

- IMA  프로젝트 명 :  전국시도별 인구수 현황 JHJ버전
http://b-iris.mobigen.com/iris-map-analyzer/exported/067b9f7229c1404f96c10730f6e5c248a0e9e9d3f195427b803ab73e9bd6b83a

- studio 보고서 :  시도별인구_JHJ
http://b-iris.mobigen.com:80/studio/exported/b9408991733a44d8af3ef7dad9c002b44b995f3dbb084da7ba2d87bdb43e927e

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
성능의 문제가 있다고 보입니다. 해당 부분은 지속적으로 고민 해야 할듯 합니다.
