### ISSUE TITLE
[Map Analyzer] 레이어 안보이기로 설정하고 저장했는데, 다시 열면 레이어가 보입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2913]
## 버그 설명 ##
b-iris.mobigen.com demo계정

참고 프로젝트 : 서울시 소방서 및 화재발생건수_JHJ(1) 

- 2018 화재건수 레이어 ( 원크기와 색이 다르게 보이는 레이어 )안보이게 설정 후 저장

<img width="906" alt="스크린샷 2021-05-10 오후 1 24 25" src="https://user-images.githubusercontent.com/5126497/117605819-884d2c80-b193-11eb-9d79-d83f7a15ddf2.png">

- 프로젝트를 목록에서 다시 클릭하여 열면 해당 레이어가 보이고, 안보이도록 한 설정이 저장되어 있지 않습니다.
<img width="1266" alt="스크린샷 2021-05-10 오후 1 25 08" src="https://user-images.githubusercontent.com/5126497/117605977-e5e17900-b193-11eb-8dfd-b43a2f6a3a5f.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by almalibreolo2** [comment]
현재 IMA에서는 레이어의 show/hide에 대한 기능은 데이터를 유지 않도록 기획을 하여 기능 제공이 되고 있지 않습니다.
