### ISSUE TITLE
[Map Analyzer] 프로젝트편집화면에서 줌을 잠금하고 저장했는데, 다시 열면 잠금이 풀려있습니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2914]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정 /  Mac OS 크롬 브라우저

- 12로 줌 설정 후 잠금하고 저장했습니다.
<img width="178" alt="스크린샷 2021-05-10 오후 1 47 40" src="https://user-images.githubusercontent.com/5126497/117607351-c39d2a80-b196-11eb-9d82-89a8bffdd187.png">
<img width="567" alt="스크린샷 2021-05-10 오후 1 47 57" src="https://user-images.githubusercontent.com/5126497/117607357-c4ce5780-b196-11eb-9ef9-a8c1aa8a234e.png">

- 프로젝트 목록에서 다시 클릭 하여 편집을 하면 잠금이 풀려있고, 확대,축소,이동이 됩니다.
<img width="183" alt="스크린샷 2021-05-10 오후 1 49 14" src="https://user-images.githubusercontent.com/5126497/117607437-ef201500-b196-11eb-81c6-76e77ee22adb.png">

<img width="1177" alt="스크린샷 2021-05-10 오후 1 36 50" src="https://user-images.githubusercontent.com/5126497/117607488-0a8b2000-b197-11eb-81f4-39b9c340db26.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by almalibreolo2** [comment]
현재 IMA에서 줌레벨 잠금기능에 대한 기능은 저장되지 않도록 기획되어 기능 제공이 되고 있지 않습니다.
