### ISSUE TITLE
[Map Analyzer] 마커가 깃발일 때, 라벨을 같이 사용하고, 라벨설정의 텍스트정렬을 이용하면 깃발과 라벨이 사라집니다.  

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2915]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정  / Mac OS 크롬브라우저

참고 프로젝트명 : SEOUL_GU_FIRE_작업중_0510  http://b-iris.mobigen.com/iris-map-analyzer/exported/5729b53787ba4a049acad819f7663a781b145aa36bca42149a7c315f9fb3f6dc

- 마커-깃발 & 라벨이 라벨 설정을 하면 레이어가 보이지 않는 문제
- 마커-원 & 라벨은 ``시각화적용``  버튼 클릭 후 ``레이어 숨김`` - ``보기``   를 해야 다시 보이는 문제

< 현상 >

- 마커를 원 - 라벨을 디폴트로 설정 하면 정상동작합니다.
<img width="1134" alt="스크린샷 2021-05-10 오후 2 36 26" src="https://user-images.githubusercontent.com/5126497/117611346-4aa1d100-b19e-11eb-87d3-03133d6dcf4c.png">

- 마커-원은 오른쪽 정렬, 가로세로 라벨 위치 조정까지 정상 동작합니다.
<img width="854" alt="스크린샷 2021-05-10 오후 2 37 51" src="https://user-images.githubusercontent.com/5126497/117611408-66a57280-b19e-11eb-8bb5-47e04f258e1e.png">

- 새로 생성할 레이어가 원도형을 그릴 거라 마커를 깃발로 변경해야 합니다. 그래서 마커-깃발로 변경하기만 하면 바로 라벨과 깃발까지 보이지 않습니다.  이 상태에서는 마커 - 깃발을 다시 마커 - 원 으로 변경해도 보이지 않습니다.
<img width="870" alt="스크린샷 2021-05-10 오후 2 38 24" src="https://user-images.githubusercontent.com/5126497/117611477-88065e80-b19e-11eb-8b70-6090ad10bb82.png">

- 레이어를 숨김/보임 아이콘을 눌러야  마커-원은 보입니다.
<img width="1048" alt="스크린샷 2021-05-10 오후 2 49 43" src="https://user-images.githubusercontent.com/5126497/117611851-2e526400-b19f-11eb-932a-88a158bd2d7d.png">

- 하지만 마커-깃발로 다시 변경하고, 레이어 숨김/보임 아이콘을 눌러도 깃발과 라벨은 보이지 않습니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by almalibreolo2** [comment]
5/13일 패치에 적용되었습니다.

**Comment by rhcpn** [comment]
@almalibreolo2 IRIS 쪽 이슈만 링크 걸어주세요. 해당 이슈는 일단 Close 하겠습니다.
