### ISSUE TITLE
[Map Analyzer] 모든 레이어가 다 보이도록 저장했는데, 목록에서 다시 열면 특정 레이어가 안보입니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2921]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정 / Mac OS 크롬브라우저

참고 : 서울시 소방서 및 화재발생건수_0511
http://b-iris.mobigen.com/iris-map-analyzer/exported/18a4304ec97341469c97bbeaed3344df020fd0d53ed14c9b88cfa2a6e1849eed

- 프로젝트 목록 : 여기서는 저장한 지도내용이 전부 표시되어 보입니다. ( 큰원안에 작은 노란색원이 있습니다)
<img width="318" alt="스크린샷 2021-05-11 오전 11 38 07" src="https://user-images.githubusercontent.com/5126497/117749816-5dbfaa00-b24d-11eb-8816-42c75065b317.png">
- 클릭해서 들어가면 첫화면에서  "2018실수원인건수"  레이어가 보이지 않습니다. 즉 작은 노란원이 안보입니다.
<img width="1164" alt="스크린샷 2021-05-11 오전 11 39 25" src="https://user-images.githubusercontent.com/5126497/117749957-93649300-b24d-11eb-8af4-9003826b16c7.png">
- 2018실수원인건수  레이어의 상태
<img width="1115" alt="스크린샷 2021-05-11 오전 11 40 09" src="https://user-images.githubusercontent.com/5126497/117750056-bee77d80-b24d-11eb-92bb-4e78beb47133.png">
- "시각화 적용" 버튼을 눌러야 레이어가 보입니다.  이 후 다시 저장
<img width="1141" alt="스크린샷 2021-05-11 오전 11 42 17" src="https://user-images.githubusercontent.com/5126497/117750206-fbb37480-b24d-11eb-8b5a-25aed6210f5f.png">

- 그리고  목록에서 다시 클릭하면 이번에는 "화재건수_부주의화재" 레이어가 보이지 않습니다. 즉 큰 바깥 원
<img width="1096" alt="스크린샷 2021-05-11 오전 11 43 42" src="https://user-images.githubusercontent.com/5126497/117750340-35847b00-b24e-11eb-8ab9-96d7576afa3d.png">

-  이 2 레이어가 같은 데이터모델(모델뷰) 을 쓴다는 공통점이 있습니다.  

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by seoryjj** [comment]
이문제는 모델뷰의 결과에서 공간데이터셋을  merge 하는 방식이 아니라 모델뷰의 쿼리와 동시에 공간데이터셋을 merge 즉 3개의 데이터를 merge 수행하면서 같은 도로명주소가 있어서 생긴 문제로 보입니다.
동일한 이슈로 제안요청 한 게 있으니 close  합니다.

**Comment by seoryjj** [comment]
데이터를 중복없이 처리했는데, 여전히 첫화면에서 "2018실수원인건수" 레이어가 보이지 않습니다. 즉 작은 노란원이 안보입니다. 그래서 다시 reopen 합니다.
참고 보고서 : 서울시 소방서 및 화재발생건수_JHJ  http://b-iris.mobigen.com/iris-map-analyzer/exported/d008d9a840b44d68953eb298fd23c1700472d81346bd4dca97cf2bcfd78965ac

를 봐주세요.

**Comment by rhcpn** [comment]
이슈를 이동 하셨기 때문에 해당 이슈는 close 합니다.
