### ISSUE TITLE
[DSL] unpivot 수행시 앞서 fields로 alias 처리된 필드의 값으로는 수행안됨

### ISSUE THREAD

**Issue by shinwoonsun** [mobigen/IRIS-BigData-Platform#2923]
## 버그 설명 ##
unpivot 수행시 앞서 fields로 alias 처리된 필드의 값으로는 unpivot 수행이 안됨

## 재현하는 방법 ##
1. raw 테이블 조회
![001](https://user-images.githubusercontent.com/13842947/117766450-928e2a00-b26a-11eb-8f64-f706d60802ab.PNG)

2. fields로 alias 수행
![002](https://user-images.githubusercontent.com/13842947/117766462-9752de00-b26a-11eb-8757-e65086a56623.PNG)

3. unpivot 수행
![003](https://user-images.githubusercontent.com/13842947/117766476-9b7efb80-b26a-11eb-84d4-42f69a54c612.PNG)

raw테이블에서 바로 unpivot 수행시에는 양호
![004](https://user-images.githubusercontent.com/13842947/117766488-a043af80-b26a-11eb-9b5d-ef1b51e34048.PNG)

## 예상한 행동 ##
앞서 fields로 alias 처리된 필드 값으로도 unpivot 정상수행

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by jheok318** [comment]
@shinwoonsun 
현재 해당 이슈 해결하였습니다.

쿼리의 문제가 아니라 세션 id 관리 과정에서 혼동이 발생한 것이었습니다.

해당 세션 id를 재 정돈하여 해결하였습니다.

원래 쿼리는 그대로 사용하셔도 가능합니다.

![스크린샷 2021-05-12 오전 11 08 24](https://user-images.githubusercontent.com/67408315/117907805-6201cb00-b312-11eb-973e-c1fc0d79be4a.png)
