### ISSUE TITLE
[DSL] typecast 실행시 invalid date 출력

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#2930]
## 버그 설명 ##
typecast 실행시 invalid date 출력됩니다.

## 재현하는 방법 ##
동작을 재현하는 방법 :
데이터모델: EPS_DATA_BIS
검색어: * | fields PERIOD | typecast PERIOD date "YYYY/MM/DD"
![image](https://user-images.githubusercontent.com/5077625/117919610-473a5100-b328-11eb-9a89-d58264afc7c4.png)

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }
2021/05/11

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
위에 작성 해주신 DSL에서 typecast 문법이 잘못되었습니다.

typecast PERIOD date "YYYY/MM/DD" 부분에서 "YYYY/MM/DD" 란에 들어가야 할 내용은 파싱되어야 할 원본 데이터 형식을 써주셔야 합니다.

따라서 아래와 같이 입력해주셔야 제대로 나옵니다.

_**typecast PERIOD date "YYYYMMDD"**_

**Comment by euhyesun** [comment]
OPTION 부분이 파싱된 데이터 형식으로 잘못 이해했습니다. 
확인했습니다. 감사합니다.
