### ISSUE TITLE
[DB Browser] 테이블 생성> 데이터 유형 선택시 불편 사항

### ISSUE THREAD

**Issue by aDataGuy** [mobigen/IRIS-BigData-Platform#693]
![image](https://user-images.githubusercontent.com/6846179/35613678-245a694a-06b0-11e8-9f25-48ad80fe4712.png)

**Comment by sunghoon** [comment]
@onlyeon 해당 이슈는 완료 된건가요?

**Comment by onlyeon** [comment]
@sunghoon 아직 처리가 완료되지 않았습니다.
 부모 엘리먼트에 추가한 `overflow: auto` 속성으로 인해 발생하는 이슈입니다. `z-index`나 `position: absolute` 등 해결 방안을 찾아봤으나 순수하게 CSS만으로는 해결이 불가능 했습니다.
[참고 이슈](https://stackoverflow.com/questions/51550849/dropdown-menu-cut-off-when-using-over-flow-with-scroll) 대부분의 해결 방안이 

>부모 엘리먼트에 `overflow: visible` 처리

로 가능하지만 저희 화면에서는 컬럼이 늘어나면 영역 내에서 스크롤해 정보를 확인해야하기 때문에 불가능했습니다.

 고려했던 해결 방안은
1. **콤포넌트 개선**: 
    - 디자인이 적용된 dropdown이 아닌 순수 HTML 태그로 구성한다 (`select`, `option`) 
    - 디자인 커스텀에 제약이 있다
    - 사용자의 OS나 테마에 디자인이 영향을 받게된다
2. **설계 변경:** 
    - 셀렉트 박스가 아니라 버튼 그룹으로 표시
    - 데이터 유형이 3개 이상 늘어날 수 있어 버튼 그룹으로 처리하기는 어렵다

등이 있었으나, 개발팀과 논의하던 중 우선순위에 밀려 진행이 누락되고 있었습니다.
혹시 더 좋은 해결 방안이 있는지 UI솔루션팀과 논의해보겠습니다.
