### ISSUE TITLE
[고급시각화] Heatmap 상관계수

### ISSUE THREAD

**Issue by euhyesun** [mobigen/IRIS-BigData-Platform#826]
아래 조건으로 차트 실행시 상관계수가 표시되지 않습니다.

x축: DELTA_DN_LINK_PACKET_COUNT, 최대 행 수 20
y축: DELTA_DN_LINK_DATA, 최대 열 수 20
값: 이벤트 개수

![image](https://user-images.githubusercontent.com/5077625/37391501-b3855e76-27ae-11e8-8215-872156e99b7b.png)

![image](https://user-images.githubusercontent.com/5077625/37391481-a3ef8496-27ae-11e8-9e0a-cee70ed2f182.png)

참고)
![image](https://user-images.githubusercontent.com/5077625/37391630-17047c5c-27af-11e8-8fa4-67c480094c63.png)

**Comment by veldise** [comment]
아래와 같이 Heatmap 유형의 설명을 변경하겠습니다.

![image](https://user-images.githubusercontent.com/3411842/50757306-3550cb00-12a2-11e9-9e54-b3e8f6cb6d9e.png)

**Comment by veldise** [comment]
180번 서버에 적용 완료했습니다.
