### ISSUE TITLE
[Data Browser] 데이터 모델 컬럼명 선택 부분 스크롤 기능 필요

### ISSUE THREAD

**Issue by aDataGuy** [mobigen/IRIS-BigData-Platform#848]
![image](https://user-images.githubusercontent.com/6846179/38185259-4c543dc4-3688-11e8-9ad9-82d84d4467c4.png)

컬럼명이 15자 이상인 경우 그냥 식별 불가 
마우스 커서를 놓고 툴팁이 생길 때 까지 기다려야함

Join 명령의 결과 컬럼명이 데이터모델명+컬럼명으로 자동으로 길어진 상황

**Comment by veldise** [comment]
수정 및 배포 완료된 내용이라 닫습니다.
