### ISSUE TITLE
DB 브라우저 / 도움말 필요(IRIS v2, 영문/한글)

### ISSUE THREAD

**Issue by hiy2259** [mobigen/IRIS-BigData-Platform#971]
## 개요
2018-08-08

###  DB 브라우저 웹 페이지 도움말 상태
|버전|한/영|상태
|---|---|---|
|v1.6|한글|있음|
|v1.6|영문|없음|
|v2|한글|없음|
|v2|영문|없음|

* 현재 v1.6 한글 도움말은 markdown 파일이 있는 것으로 알고 있습니다.
* 웹에서 사용할 도움말은 markdown이 필요 하며 현재 v1.6 markdown 저희가 가지고 있지 않습니다.
* 추후 다른 도움말을 작성 할때 웹에서 사용할 markdown 파일이 필요 하면 주실때 v1.6도 같이 주시면 될 거 같습니다.
* 공항철도에 나가있는 도움말은 v1.6 상태입니다. 이점 참고하세요.

**Comment by anhm** [comment]
매뉴얼은 전체적으로 처리가 필요하며,
IRIS WEB, DB, angora 를 통합하여 처리해야 하는 상황이기에 해당 이슈는 닫고, 다른 프로세스로 진행 예정.
